### ISSUE TITLE
Support RPC payload compression

### ISSUE THREAD

**Issue by iamqizhao** [grpc/grpc-go#101]
deflate, zippy, etc.

**Comment by ebfio** [comment]
+1

**Comment by dsymonds** [comment]
`+1` isn't a useful comment. Click the "Subscribe" button if you're just interested in updates.

**Comment by ebfio** [comment]
@dsymonds Thanks David. Even though this comment is valid and widely accepted to support a request from another user (especially one without any reply from the maintainers), I just subscribed. Thanks for your time and helpful answer :+1:

**Comment by mwitkow-io** [comment]
Does gRPC do automatic negotiation of compression? If this is added for other languages (Java, C++), will they be transparently negotiating it?

**Comment by pires** [comment]
Will it be enabled by default? I vote for not doing it by default.

**Comment by iamqizhao** [comment]
compression will be off by default.

**Comment by wencan** [comment]
+1

**Comment by wencan** [comment]
+Snappy

**Comment by wencan** [comment]
you can use [grpc.Codec](https://godoc.org/google.golang.org/grpc#Codec)

**Comment by stevvooe** [comment]
@wencan Is there a way to use `grpc.Codec` such that it changes based on the request headers or would this be static at instantiation time?

**Comment by oxtoacart** [comment]
The problem with using `grpc.Codec` is that it operates one message at a time.  When streaming results, compression would work better when done at the stream level rather than the message level, since repetition of data may occur across messages rather than within them.

**Comment by oxtoacart** [comment]
Ah, looks like there are some options now to use compression, for example https://godoc.org/google.golang.org/grpc#RPCCompressor

**Comment by pboyer** [comment]
@iamqizhao As noted by @oxtoacart, there are already compression API's. Are these API's supported? Is this issue to expand the set of supported compressors?

**Comment by c4milo** [comment]
This is already covered with the `Compressor` and `Decompressor` types, right?

**Comment by dfawley** [comment]
Yes, compression is supported now.

**Comment by bboreham** [comment]
Since this is the top hit when I search for info on compression, I'll add a link here to
https://github.com/grpc/grpc-go/blob/master/Documentation/compression.md
