### ISSUE TITLE
gRPC Receiver contention

### ISSUE THREAD

**Issue by rogeralsing** [grpc/grpc-go#1011]
Hi,
I am trying to track down some random slowness I see in my benchmark app for my actor lib, which uses gRPC streams as a transport.

The benchmark sends 10 mil messages from one node to another, which then replies to each incoming message back to the sender.
Nothing fancy, and not a real world representative test.
The benchmark itself can be found here https://github.com/AsynkronIT/gam/tree/dev/examples/remotebenchmark

But, about 1 out of 10 times, I can see the test slows down towards the end. resulting in a total perf drop of about 40%

I have profiled this using the block/contention profile.

Here is an SVG from a good run:
https://cdn.rawgit.com/AsynkronIT/gam/dev/debug/contention.svg

And here is an SVG of a bad run:
https://cdn.rawgit.com/AsynkronIT/gam/dev/debug/contentionbad.svg

In the latter, I see a big build up of contention on the `google.golang.org/grpc/transport.(*http2Server).controller`

Is this something coming from gRPC or it's internals, or am I doing something that I shouldn't do here?

I have also profiled this with GC logging turned on, and the slowness does not match the GC runs, so that is not what is going on here.

I cannot give much more details as there is nothing broken/not working.
This is more in the domain of non functional requirements. 
Is there anything obvious that sticks out that I am not seeing?

**Comment by a-robinson** [comment]
Hi @rogeralsing - I'm also curious about grpc-go's behavior under contention, and couldn't help but notice that your SVGs are no longer available.

**Comment by rogeralsing** [comment]
I believe the behavior was due to pre Go 1.8 GC.
After 1.8 was released, I am seeing much more consistent performance under heavy load.
Although somewhat lower than the previous max, I assume this is because of a more evenly spread GC.

**Comment by hsaliak** [comment]
@rogeralsing I am closing this issue since the performance seems to be caused and resolved by underlying GC changes in the language. If you think that there are still gRPC specific performance issues we should investigate, please reopen.
