### ISSUE TITLE
Locking for SetLogger

### ISSUE THREAD

**Issue by jsha** [grpc/grpc-go#1013]
In [`grpclog`](https://godoc.org/google.golang.org/grpc/grpclog#SetLogger), `SetLogger` says "Call only from init() functions." However, in the letsencrypt/boulder project, we use syslog, and would like to be able to call SetLogger well after `init()`, since we need to parse a config file and connect to syslog.

Would you consider alternate implementations for `grpclog`, like providing a mutex for `SetLogger` or (more ambitiously) making logger a property of a client or server?

**Comment by menghanl** [comment]
You can call `SetLogger` outside of `init()`, as long as you can make sure it is called early enough so that gRPC internals can find the logger to use.
