### ISSUE TITLE
gRPC server behavior when the client doesn't respect WINDOW_UPDATE

### ISSUE THREAD

**Issue by kchristidis** [grpc/grpc-go#1020]
Does the server close the connection in such cases, as it should?

Background:
[0] https://http2.github.io/http2-spec/#rfc.section.5.2.1
[1] https://www.imperva.com/docs/Imperva_HII_HTTP2.pdf (section "HTTP/2 Security Considerations")

**Comment by menghanl** [comment]
Yes, the connection will be closed.
Did you see any unexpected behavior related to this?

**Comment by kchristidis** [comment]
@menghanl Thank you. Do you happen to know approx. where in the codebase this is being handled, so that I can review?

To your question: I haven't bumped into any issues, but wanted to make sure that this case is covered.

**Comment by menghanl** [comment]
For onnection: https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L384
For stream: https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L407

**Comment by kchristidis** [comment]
(Thank you.)
