### ISSUE TITLE
Benchmark for stream

### ISSUE THREAD

**Issue by fiibbb** [grpc/grpc-go#1032]
Hi, I'm evaluating GRPC stream for our golang project. It all seems very promising feature-wise, but I was not able to find any benchmark regarding streams. I wonder how many concurrent streams can a server handle approximately? Does grpc team have any numbers lying around?

**Comment by menghanl** [comment]
We have local benchmarks in https://github.com/grpc/grpc-go/tree/master/benchmark.
```
cd benchmark
go test -bench=.
```
