### ISSUE TITLE
Please test with broken HTTP/2 stream IDs

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc-go#104]
Hi there,
We recently got hit in C with a crash that happened when HTTP/2 stream IDs went unexpected (violating the invariant of increase on a connection) and also aren't prepared for the situation where we approach or cross max stream id (0x7fffffffu). Please check that this case works in Go. If you need some client code to test that, I can let you use the client code that was sent to me.
This is related to C issues: https://github.com/grpc/grpc/issues/946 and https://github.com/grpc/grpc/issues/957

Thanks!
Vijay

**Comment by iamqizhao** [comment]
Thanks. I think bradfitz/http2 has handled this but I need to verify and see whether grpc handles it appropriately.

**Comment by easwars** [comment]
Draining of client transport when the streamID approaches MaxStreamID was handled here: https://github.com/grpc/grpc-go/pull/5889

**Comment by easwars** [comment]
We have checks on the server for validating the incoming stream ID here: https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_server.go#L369
