### ISSUE TITLE
Example request: Access Control: Intercepting requests to a particular method

### ISSUE THREAD

**Issue by ofpiyush** [grpc/grpc-go#1045]
Use case:

```protobuf
service A {
  rpc GetState(StateQuery) returns (State) {}
  rpc CreateState(CreateReq) returns (State) {}
  rpc MutateState(NewState) returns (google.protobuf.Empty) {}
}
```

I want to allow every service with a valid cert, access to the `GetState` method, but only limited privileged ones to have access to `CreateState` and `MutateState` methods.

Is intercepting requests to a particular method the recommended way to do it, or should one create a new Service definition and use that instead?

**Comment by menghanl** [comment]
Interceptors are called after the requests are read by the server. It works, but it may be a bit late in your situation.

[`tap.ServerInHandle`](https://github.com/grpc/grpc-go/blob/master/tap/tap.go#L54) may be what you want.
InTapHandle ServerOption defined here: https://github.com/grpc/grpc-go/blob/master/server.go#L195
