### ISSUE TITLE
Event/Callback on server close?

### ISSUE THREAD

**Issue by rogeralsing** [grpc/grpc-go#1047]
We are using gRPC streams as the transport for messages in http://Proto.Actor (https://github.com/AsynkronIT/protoactor-go)

This works extremely well.
But, one thing that I have not yet figured out how to get notified if the server disconnects?
e.g. say that the client has an open connection with an open stream.
if the server disconnects, is there any way to get notified of this?
Currently we only detect this when we try to interact with the stream

**Comment by iamqizhao** [comment]
Yes, you get notified when you interact with stream. But be aware that all the underlying information of this stream is cleaned up once the server disconnects (instead of waiting for user interaction) and only the minimal info is left in the stream object used to notify the caller.

**Comment by rogeralsing** [comment]
I see that I get the error information when I interact with the stream, but that is not visible to me until I send something, is there no way to get notified that there is a disconnect w/o me trying to write to the stream?

**Comment by iamqizhao** [comment]
You can always have a pending recv call to either receive incoming messages or get notified if there is an error.

**Comment by rogeralsing** [comment]
I'm not following?
Pending as in sending heartbeat messages myself ?

**Comment by iamqizhao** [comment]
I meant you can have a stream.Recv() call pending so that you can get notified when there is an error.

**Comment by rogeralsing** [comment]
Ah, currently the contract is defined as:

```proto
  rpc Receive (stream MessageBatch) returns (Unit) {}
```

So the client/sender has nothing to wait for really, but if I add a stream of whatever as a response then I could Recv on the response stream, right?

**Comment by iamqizhao** [comment]
You need a Recv call to receive the final status of the stream anyways.

**Comment by rogeralsing** [comment]
I must be super dense, I get how I can do that on the server side.
I'm not getting how I can do this on the client/sender side.

```go
c := NewRemotingClient(conn)
stream, err := c.Receive(context.Background(), state.config.callOptions...)
if err != nil {
	return err
}
//can I do something here to monitor that the stream which we are Sending to is open/broken?
state.stream = stream
```

**Comment by iamqizhao** [comment]
Yep, you can spawn a goroutine to call Recv on that line.

**Comment by iamqizhao** [comment]
And you probably should use bi-directional streaming instead of client streaming. With client streaming, you probably need to deal with concurrent readers in your use case.

**Comment by rogeralsing** [comment]
Thanks.
Bidirectional stream + go routine waiting for Recv did the trick.

**Comment by rogeralsing** [comment]
For anyone interested in the actor model for Go, we now have support for watching remote actors and endpoint termination due to the above fix.
http://proto.actor/docs/golang/eventstream#remote-termination
