### ISSUE TITLE
"Socket is not connected" error when issuing RPCs

### ISSUE THREAD

**Issue by steeve** [grpc/grpc-go#1049]
Hi,

We are using grpc-go on iOS and noticed weird behaviours related to the network connection. When `ENOPIPE`d, the network connection successfully reconnects (we are silencing `SIGPIPE`), however sometimes, after long sleeps, the gRPC calls fail with this error:
```
error="rpc error: code = 13 desc = connection error: desc = \"transport: read tcp x.x.x.x:y->z.z.z.z:443: read: socket is not connected\""
```

Go version:
```
go version devel +d9a0579 Tue Jan 10 17:29:46 2017 +0000 darwin/arm64
```

We will try to reset the client, but we are not sure how to properly catch this error in particular. I also think catching this on the client side this is too high level.

Thanks!

**Comment by MakMukhi** [comment]
Hey,

We'll need more information to debug. Do you see anything peculiar on the
server or client other than the error? Have you been able to reproduce the
issue?

Best,
Mak

**Comment by steeve** [comment]
We have no real idea on how to reproduce it, we just saw it in the wild on one of our apps, thanks to the log..

I can tell you that the call was in fail fast mode, but alls the calls after this one failed from then on.

**Comment by menghanl** [comment]
We haven't started on support gRPC-go on iOS yet.
Please comment if you find anything more.
Closing this for now.
