### ISSUE TITLE
iamqizhao' status change

### ISSUE THREAD

**Issue by iamqizhao** [grpc/grpc-go#1051]
I am leaving the team. From tomorrow I will not work on gRPC-Go as a full-time developer/lead. The rest of team will continue serving the project.

Thank you guys for your support in the past years!  I will try to continue to contribute in best-effort mode.

**Comment by zellyn** [comment]
Qi, just wanted to post a quick note thanking you for all your work, effort, and energy in implementing GRPC and engaging the wider community. It was a pleasure working with you!
