### ISSUE TITLE
Spurious server log produced when client closes birectional stream

### ISSUE THREAD

**Issue by geeknoid** [grpc/grpc-go#1059]
I have a client/server setup using bidirectional streaming. When the client calls stream.CloseSend and then immediately closes the underlying TCP connection, the server produces the following spurious log entry:

http2_server.go:320] transport: http2Server.HandleStreams failed to read frame: read tcp [::1]:9091->[::1]:38241: read: connection reset by peer

After this, everything works fine. If I insert a 1 second delay on the client between the call to CloseSend and the call to close the socket, then the log message doesn't get emitted. 

This message is polluting our logs, that's why I'd like to get rid of it.

This is with Go 1.7.4

**Comment by MakMukhi** [comment]
Hey Martin,

We're working on adding levels to logging. This will reduce the verbosity
for more restrictive levels. The PR is under its way. However, I don't have
a time line for you at this moment since the guy working on this is out on
vacation.

Regards,
Mak

**Comment by geeknoid** [comment]
Thanks for the follow-up. For now, I've added a 50ms delay in our test
client code to eliminate the issue internally for us. But that's not a good
long-term story of course...
