### ISSUE TITLE
Simple password authentication example

### ISSUE THREAD

**Issue by prazzt** [grpc/grpc-go#106]
I'm trying to figure out how to authenticate requests in simple password based/session token case.

Should I :
- create my own proto, embedding token in each message ? or
- do it in grpc: implementing my own credential.Credentials ? how to check server side ? 

Would appreciate if there's some basic examples.

**Comment by iamqizhao** [comment]
On Fri, Mar 6, 2015 at 11:55 PM, prazzt <notifications@github.com> wrote:

> I'm trying to figure out how to authenticate requests in simple password
> based/session token case.
>
> Should I :
>
>    - create my own proto, embedding token in each message ? or
>    - do it in grpc: implementing my own credential.Credentials ? how to
>    check server side ?
>
> I would suggest using the metadata to transmit the passwd/token. Please
take a look at
https://github.com/grpc/grpc-go/blob/master/test/end2end_test.go#L353 for
how a client sets metadata for an RPC and
https://github.com/grpc/grpc-go/blob/master/test/end2end_test.go#L92 for
how a server gets the metadata.

**Comment by GeertJohan** [comment]
How would this work to do connection based authentication? So that you don't have to check password for each rpc call?

**Comment by GeertJohan** [comment]
I've seen https://godoc.org/google.golang.org/grpc/credentials#TransportAuthenticator, but it would be nice to have an example of how this would work in practice.

**Comment by iamqizhao** [comment]
credentials.tlsCreds is one example. You can look at
i) the simple HOWTO https://github.com/grpc/grpc-go/blob/master/grpc-auth-support.md;
ii) examples/route_guide for an example (both client and server).

**Comment by ishbir** [comment]
I can't figure out how to use simple password based authentication. If I use TransportAuthenticator, https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L127 won't let me have TLS and password based auth at the same time. I can't figure out how to use per request based authentication either.

**Comment by Gurpartap** [comment]
@ishbir Make a call to AuthenticationService{}.Authenticate(user, pass) on the server. Make this function on the server to create a session token, store it in memory (memcache or redis) and return it to the client. Then have the client set this session token in metadata; and have the server verify it against the session store.

Or use JWT (with exp) instead of session tokens to avoid the DB trip.

**Comment by amenzhinsky** [comment]
I would recommend to use interceptors:

```go
// server initialization
grpc.NewServer(grpc.StreamInterceptor(streamInterceptor), grpc.UnaryInterceptor(unaryInterceptor))

func streamInterceptor(srv interface{}, stream grpc.ServerStream, info *grpc.StreamServerInfo, handler grpc.StreamHandler) error {
	if err := authorize(stream.Context()); err != nil {
		return err
	}

	return handler(srv, stream)
}

func unaryInterceptor(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
	if err := authorize(ctx); err != nil {
		return err
	}

	return handler(ctx, req)
}

func authorize(ctx context.Context) error {
	if md, ok := metadata.FromContext(ctx); ok {
		if len(md["username"]) > 0 && md["username"][0] == "admin" &&
			len(md["password"]) > 0 && md["password"][0] == "admin123" {
			return nil
		}

		return AccessDeniedErr
	}

	return EmptyMetadataErr
}
```

**Comment by milewski** [comment]
@amenzhinsky your code keeps yelling me with 

```
grpc: no transport security set (use grpc.WithInsecure() explicitly or set credentials)
```

something has changed?

**Comment by amenzhinsky** [comment]
@milewski, seems like now you have to pass `grpc.WithInsecure()` to `grpc.Dial` explicitely unless you set transport credentials.
