### ISSUE TITLE
panic: Unexpected error from context packet: context canceled

### ISSUE THREAD

**Issue by rbewley4** [grpc/grpc-go#1061]
Related to #711 

If passing a Go 1.7 context to gprc, and it is canceled or it times-out, gprc panics with the following message:

`panic: Unexpected error from context packet: context canceled`

I have traced the issue to this function in https://github.com/grpc/grpc-go/blob/master/transport/transport.go#L572:

```go
// ContextErr converts the error from context package into a StreamError.
func ContextErr(err error) StreamError {
	switch err {
	case context.DeadlineExceeded:
		return streamErrorf(codes.DeadlineExceeded, "%v", err)
	case context.Canceled:
		return streamErrorf(codes.Canceled, "%v", err)
	}
	panic(fmt.Sprintf("Unexpected error from context packet: %v", err))
}
```

I think a workaround could be to compare error strings, although it is error-prone and frowned upon:

```go
// ContextErr converts the error from context package into a StreamError.
func ContextErr(err error) StreamError {
	switch err.Error() {
	case context.DeadlineExceeded.Error():
		return streamErrorf(codes.DeadlineExceeded, "%v", err)
	case context.Canceled.Error():
		return streamErrorf(codes.Canceled, "%v", err)
	}
	panic(fmt.Sprintf("Unexpected error from context packet: %v", err))
}
```

Alternatively, you could remove the panic altogether, since the use of panic itself is discouraged, and simply return an error.

**Comment by tamird** [comment]
Could also use build tags to do the right thing in 1.8.

1 февр. 2017 г. 5:58 ПП пользователь "Russell Bewley" <
notifications@github.com> написал:

**Comment by MakMukhi** [comment]
Hey,

I couldn't reproduce the issue on a machine running go 1.7.3. I tried the following code, let me know if you can reproduce it.

package main
import (
        "context"
        "fmt"
        xcontext "golang.org/x/net/context"
)
func main() {
        ctx, cancel := context.WithCancel(context.Background())
        cancel()
        err := ctx.Err()
        switch err {
        case xcontext.Canceled:
                fmt.Println("comparision worked")
                return
        }
        fmt.Println("comparision did NOT work")
}

**Comment by rbewley4** [comment]
I ran your test program and it also failed to reproduce the issue for me. I even tried with some variations of timeout/deadline to no avail. 

To add some more context to the problem, this issue arises when using Google Cloud PubSub via https://github.com/google/google-api-go-client. When it occurs, the panic from `ContextErr` originates from a goroutine inside of the pubsub (?) package, which cannot be recovered from userland. This is a huge thorn in my side, as it routinely crashes my application. Regardless of why it is happening, I think the panic in `ContextErr` should be replaced with an error return, similar to the other cases. 

The code I posted in my previous message fixes the problem for me, so I am stumped as to why your test program did not reproduce the issue. Maybe the pubsub package is doing something naughty like creating its own Context implementation. Anyway, I shall endeavor to find cause the problem.

**Comment by tomwilkie** [comment]
We're also seeing this - when a HTTP connection is prematurely closed, the context that is cancelled is from `context`, not `golang.org/x/net/context`.  Does grpc need to support pre-go1.7, or can we switch to using go1.7's `context` package?

**Comment by tomwilkie** [comment]
I see #711 mentions that `golang.org/x/net/context` uses `context` on go1.7 - what had happened was I had an old version of `golang.org/x/net/context` vendored that didn't have the new go1.7 behaviour.  Might this explain why @MakMukhi and @rbewley4 couldn't reproduce - they had the up-to-date `golang.org/x/net/context` package?

**Comment by dfawley** [comment]
Sounds like this issue is caused by having an older x/net/context package in combination with a newer version of Go.  This issue should resolve itself when we drop 1.6 support and switch to using the Go context.
