### ISSUE TITLE
Question: Should not have error on grpc.Dial() ?

### ISSUE THREAD

**Issue by ThibaultRiviere** [grpc/grpc-go#1072]
I tried this part of code, but i don't receive an error. Did i miss something? If somebody can explain to me
```go
package main

import (
	"google.golang.org/grpc"
	"log"
)

func main() {
	_, err := grpc.Dial("toto:42", grpc.WithInsecure())
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
}
```

**Comment by menghanl** [comment]
In your case, Dial() returns immediately and connecting the server happens in background.

WithBlock() dial option can make Dial() block until connections are established.
https://github.com/grpc/grpc-go/blob/master/clientconn.go#L174

**Comment by ThibaultRiviere** [comment]
Make sens thanks :)
