### ISSUE TITLE
ServerStream send context

### ISSUE THREAD

**Issue by immesys** [grpc/grpc-go#1074]
In our testing with pathological clients, we have a situation where the client calls a function that streams return values, with no deadline in their context. Then they don't consume the stream. We enforce a maximum timeout in the context within the server, but for the Stream.Send() function (in the server, returning the data to the client), there appears to be no way to change the context or apply a different timeout. The result is that the function blocks forever, tying up resources until the client connection is terminated.

My question is, how would I change the context used by the ServerStream, or otherwise enforce a timeout, short of wrapping calls to ServerStream.Send with my own timeout logic?

If the answer is to wrap my own timeout logic, how would I cancel the context used by send, as it is actually the incoming request context which naturally I cannot cancel?

**Comment by menghanl** [comment]
InTapHandle server option can do whant you need: https://github.com/grpc/grpc-go/blob/master/server.go#L196.

[ServerInHandle](https://github.com/grpc/grpc-go/blob/master/tap/tap.go#L54) takes a context and returns a context. You can set some timeout on the returned context.

**Comment by immesys** [comment]
Perfect, thank you!
