### ISSUE TITLE
provide grpc version constant

### ISSUE THREAD

**Issue by pongad** [grpc/grpc-go#1081]
Hi!
I'm working on https://github.com/googleapis/toolkit . To help track versions of grpc libraries in the wild, we'd like to report some kind of grpc version in our headers. Would it be possible for you to declare something like `const Version = "12345"`?

The grpc version need not be consistent with other languages. We'd like to use it to track whether users are getting major bug fixes and the like.

cc @bjwatson . Please let me know if I misrepresent anything.

**Comment by bjwatson** [comment]
SGTM

**Comment by pongad** [comment]
I assume that sgtm was to my bug description, not approving the idea for this repo 😆
