### ISSUE TITLE
Steps for change of license

### ISSUE THREAD

**Issue by zinuga** [grpc/grpc-go#1085]
Issue to track the following changes

- [ ] change LICENSE file to Apache v2.
- [ ] change license text in all source files.
- [ ] change license type in BUILD files.
- [ ] change copyright text from "Google Inc" to "gRPC AUTHORS" in all files.
- [ ] Add a AUTHORS file

**Comment by zinuga** [comment]
@nicolasnoble can we do these changes now? Want to start with one repo to test?

**Comment by jtattermusch** [comment]
Will be fixed by https://github.com/grpc/grpc-go/pull/1290.
