### ISSUE TITLE
Mechanism for knowing write success

### ISSUE THREAD

**Issue by apoydence** [grpc/grpc-go#1092]
If I have a service that accepts a stream, is there any way for the client to know how many writes were successful if it eventually receives an error?

It doesn't appear that the `Send(...)` that returns the error always implies that the buffered data made it.

**Comment by menghanl** [comment]
There's current no way to know that.
For example, in the case of connection errors, there's no way to know how many bytes are received by the server.

**Comment by apoydence** [comment]
OK thanks. I suspected as much, but wasn't sure if streaming involved an 'ack'.
