### ISSUE TITLE
Implement an option for error conversion

### ISSUE THREAD

**Issue by phifty** [grpc/grpc-go#1097]
Hi,

In my eyes, it would be useful to have an option, that converts a custom error (on the server side) into an grpc error. On the client should be converted back into a custom error.

    func WithErrorHandler(h func(error) error) DialOption
    func ErrorHandler(h func(error) error) ServerOption

This way, the handling of grpc errors doesn't inject dependencies all around the code. A cleaner separation would be possible.

**Comment by menghanl** [comment]
You can do this with interceptors.
Server side interceptors: https://github.com/menghanl/grpc-go/blob/master/server.go#L171
Client side interceptors: https://github.com/menghanl/grpc-go/blob/master/clientconn.go#L252

In this case, your service handlers can return the custom error, and in the interceptor, you can convert that error to a gRPC error.

**Comment by phifty** [comment]
Brilliant! That was exactly what I was looking for. Thanks a lot!
