### ISSUE TITLE
Way to access the string description of error from RPC method

### ISSUE THREAD

**Issue by tv42** [grpc/grpc-go#110]
Right now, errors seen from rpc calls provide no access to original error string, forcing a prefix:

```
rpc error: code = 3 desc = "original error goes here"
```

I would like to display errors from my server to the user, but this wrapping makes that ugly. It's also unlike other Go error handling, where e.g. os.PathError exposes the data items as struct fields, including the underlying error.

Is there a reason this can't be

```go
type RPCError struct {
    Code codes.Code
    Message string
}
```

with rpc client calls typically returning `*RPCError` values (pointer to match stdlib behavior).

Also, is there a reason this message looks like program code instead of like all the other errors, e.g. http://golang.org/src/os/error.go?s=600:634#L16 ? That and a String method on Code would make it more pleasant.

**Comment by maxhawkins** [comment]
+1

Exposing these fields would also give errors a better JSON serialization, which could be useful when mapping GRPC to a REST API.

**Comment by yinhm** [comment]
+1

I want  to return something like "404 page not found" to the client, It would be easier if export RPCError.

**Comment by iamqizhao** [comment]
We did not construct a new exported type for RPC error because we were
discussing whether we should open source the google internal status type
which has been used by all rpc frameworks and a lot of others inside google
and rpcErr was treated as a short-to-medium term solution. But that
discussion went silent for a while... I will see how I can rpcErr itself
better probably sometime next week and try to revive the previous
discussion. Thanks for all the valuable suggestions here!

**Comment by maxhawkins** [comment]
Could you make rpcErr similar enough to the internal status type that it will be compatible when/if you open source it? In the meantime a decent JSON serialization would be tremendously helpful.

**Comment by hezhit** [comment]
+1
rpcErr is very useful for error handling.

**Comment by joeatwork** [comment]
+1
It'd be great to be able to pass and read error descriptions

**Comment by sym3tri** [comment]
This is something I am very much in need of. Otherwise we'll have to resort to the gross last resort of parsing the error string.

**Comment by iamqizhao** [comment]
How about adding a Desc(err error) string to return the original error
description?

**Comment by sym3tri** [comment]
@iamqizhao that would suite my needs and seems like a very simple solution.
