### ISSUE TITLE
How to get UserAgent on server side

### ISSUE THREAD

**Issue by dtjm** [grpc/grpc-go#1100]
How would I access the UserAgent of the client stream in my GRPC server?  I can't seem to find any examples or interfaces that would allow this.

**Comment by MakMukhi** [comment]
It is added to the metadata which you can access from the context.
https://github.com/grpc/grpc-go/blob/8b2e129857480cb0f07ef7d9d10b8b252c7ac984/transport/http_util.go#L208

**Comment by bharatnc** [comment]
Usually, the user-agent can be included on the client side and extracted from the server side. You can add a user-agent using the WithUserAgent("user-agent") function that grpc provides when making the dial connection.

`server := grpc.Dial(grpc_server, WithUserAgent("user-agent",))
`
On the server side, you can extract it out from the incoming context meta-data:

`mD, _ := metadata.FromIncomingContext(ctx)
`
where mD itself is key,val pairs and you would want to get hold of the user-agent using its's key.

`mD["user-agent"]
`
