### ISSUE TITLE
Graceful shutdown for clients in Go

### ISSUE THREAD

**Issue by zinuga** [grpc/grpc-go#1104]
Coming from Mixpanel.

**Comment by shuaichang** [comment]
+1

**Comment by dfawley** [comment]
Note that this is low priority because users can implement this feature without support from the grpc library.  E.g. every time a stream is started/stopped, increment/decrement a WaitGroup (potentially using an interceptor).  When you are ready to gracefully stop the client, stop using the client for new RPCs, and in a goroutine do: `wg.Wait(); client.Close()`

**Comment by prune998** [comment]
I'm not sure I understand how to cleanly stop a Grpc Streaming feed from the client out of the comments here...

**Comment by jadekler** [comment]
Hi @prune998 - this issue is currently under development, and the specifics are still a bit up in the air. I'm happy to post implementation details here after-the-fact if you'd like!

**Comment by prune998** [comment]
Yes, please. Sounds a lot of people are wondering what is the right way to handle this.
Thanks a lot !

**Comment by dfawley** [comment]
@prune998 

> I'm not sure I understand how to cleanly stop a Grpc Streaming feed from the client out
> of the comments here...

If you mean a single stream, that is not the topic of this issue.  To stop a stream, you can simply cancel the context given to `NewStream`.  Or to "cleanly" stop it, the client would typically `CloseSend`.  Then the server's `Recv` would see an `io.EOF`, at which point, the server handler would return the status of the RPC (or `nil` for success).  The client's `Recv` would then see the status (or `io.EOF` for success).

The feature in this bug will not stop any streams.  It will prevent new ones from being created and block until the existing streams finish naturally.

**Comment by dfawley** [comment]
It's unclear how this would work, or why it's necessary.  Users should be fully aware what streams are open on their own client, and should control closure on their own.   See #2738 for more discussion.
