### ISSUE TITLE
ServeHTTP: intermittent panic due to race in WriteStatus

### ISSUE THREAD

**Issue by edrex** [grpc/grpc-go#1111]
I'm seeing a panic on the server when the client disconnects while the server is still streaming, about half the time. 

Reproduced with 4eaacfed9779ee7568c9e72e9f763dbd3af8e0b4.

```
panic: send on closed channel

goroutine 15851 [running]:
…/vendor/google.golang.org/grpc/transport.(*serverHandlerTransport).do(0xc4204c24e0, 0xc4204df240, 0x9b9620, 0xc4200dfe01)
	/Users/eric/src/…/.gopath/src/…/vendor/google.golang.org/grpc/transport/handler_server.go:177 +0x13d
…/vendor/google.golang.org/grpc/transport.(*serverHandlerTransport).Write(0xc4204c24e0, 0xc420215400, 0xc4203078f0, 0x65, 0x65, 0xc4204d9758, 0x0, 0x0)
	/Users/eric/src/…/.gopath/src/…/vendor/google.golang.org/grpc/transport/handler_server.go:250 +0xcb
…/vendor/google.golang.org/grpc.(*serverStream).SendMsg(0xc420154360, 0xa1a7e0, 0xc4204847e0, 0x0, 0x0)
	/Users/eric/src/…/.gopath/src/…/vendor/google.golang.org/grpc/stream.go:564 +0x29b
…/switch/protobuf.(*sGMSServiceStreamSGMSServer).Send(0xc4200f2870, 0xc4204847e0, 0x0, 0xc4200fb301)
	/Users/eric/src/…/.gopath/src/…/switch/protobuf/sgms.pb.go:1652 +0x49
…/switch/cmd/common.(*NodeCommon).StreamSGMS.func1(0xc420071180, 0xc4200f2880, 0xc4200f2880)
	/Users/eric/src/…/.gopath/src/…/switch/cmd/common/node.go:393 +0x12e
created by …/switch/cmd/common.(*NodeCommon).StreamSGMS
	/Users/eric/src/…/.gopath/src/…/switch/cmd/common/node.go:395 +0x8a
```

I'm attempting to reproduce in a minimal example but in the meantime, any ideas what might be causing this?

**Comment by edrex** [comment]
I now understand this issue a lot better.

 - It looks like there's a race between the `close(writes)` on https://github.com/grpc/grpc-go/blob/master/transport/handler_server.go#L214 and the previous `ht.do(func() ...` block which runs in the ServeHTTP goroutine. I'm not sure the best way to avoid the race. Maybe putting the `close` in a `defer` inside the block?
 - We're using the ServeHTTP implementation, which is still very rough, because we're muxing some regular HTTP stuff on the same port. We'll probably stop doing this to avoid ServeHTTP.

I think I can put together a minimal failing example if that's helpful.

**Comment by gyuho** [comment]
@edrex Can you try with https://github.com/grpc/grpc-go/pull/1546?

**Comment by menghanl** [comment]
Closing this issue now. Please leave a comment if you still see the problem.
