### ISSUE TITLE
Unclear how to add a request-scoped values to a context.Context from server stream interceptors.

### ISSUE THREAD

**Issue by c4milo** [grpc/grpc-go#1114]
The specific example is adding user information to the request context, upon successful access token verification. 

With server unary interceptors it works fine as I can call the next handler passing a new context with the information about the user and token's scope. However, with stream interceptors, I can't do the same as `grpc.ServerStream` doesn't seem to provide a way to specify a new context. Is this the right way to do it for streaming calls? any suggestion?

**Comment by menghanl** [comment]
The context scope is for each stream. It's not support to change context for each request.

Can you explain a bit more about your use case? Do you want to update the context for each request received in the stream, or just to update the context once when the first request is received?

**Comment by c4milo** [comment]
once when the first request is received, I would like to validate token's scope in the specific handler, before letting the user to consume the stream.

**Comment by menghanl** [comment]
How about override the `Context()` method of `ServerStream`?

Create a wrapper of `ServerStream` that contains the token you want to attach to the context. And override the `Context()` function to always attach the token.
```go
type myStream struct {
	token string
	grpc.ServerStream
}

func (s *myStream) Context() {
	s.ServerStream.Context().WithValue(tokenkey{}, s.token)
}
```

The stream interceptor will return the warpper `myStream` here.

**Comment by c4milo** [comment]
yes, I can totally do that. Thanks!
