### ISSUE TITLE
grpc.Code using interface?

### ISSUE THREAD

**Issue by adam-26** [grpc/grpc-go#1118]
Hi,

Would you consider changing `grpc.Code()` to to use an interface instead of `*rpcError` to determine an error code?

Example:
```go
// Add new interface
type ErrorCoder interface {
  Code() codes.Code
}

// implement for rpcError
func (e *rpcError) Code() codes.Code {
  return e.code
}

// Change implementation
func Code(err error) codes.Code {
	if err == nil {
		return codes.OK
	}
	if e, ok := err.(*ErrorCoder); ok {
		return e.Code()
	}
	return codes.Unknown
}
```
Something similar was mentioned in #494, but the additional coder interface is really all that is required to allow custom error implementations to be used.

I have a case where I want to use a custom error that uses the `type Formatter interface` to include additional info in a log, but not return it to the caller:
```go
type CustomError struct {
  code codes.Code
  msg string // returned to caller
  desc string // additional info written to log
}
```

Is there an alternative way to achieve the same thing without introducing the new interface?

Thanks, Adam.

**Comment by menghanl** [comment]
Is #1097 what you are trying to do?
If yes, you can do that with interceptors.

If no, can you explain a bit more about your use case?

**Comment by adam-26** [comment]
Using interceptors works. Thanks :)
