### ISSUE TITLE
grpc server access content-type header

### ISSUE THREAD

**Issue by adam-26** [grpc/grpc-go#1127]
Hi,

I need access to the http2 `content-type` header on the grpc server, is this possible? 

I can see that [grpc headers are filtered](https://github.com/grpc/grpc-go/blob/master/transport/http_util.go#L190), can the filter be configured, or is there another way to access the content-type header? Currently, I work around this by duplicating the content-type header in another `x-content-type` header, but this duplication is not ideal.

Could another [server option](https://github.com/grpc/grpc-go/blob/d122f1dfe6ecece11d0c914ce4b2d9cab6d4b4ff/server.go#L107) be added for this purpose?

Thanks.

**Comment by menghanl** [comment]
Can you explain a bit more on why you need to access `content-type`?
Most of time it just should be `application/grpc`.

**Comment by adam-26** [comment]
This being the case, i can just use a hard-coded value. Thanks
