### ISSUE TITLE
Golang GRPC Oauth Server & Client Examples

### ISSUE THREAD

**Issue by uguessmyid** [grpc/grpc-go#1128]
Can anyone please provide us how to use the credentials/oauth in golang.
Simple Golang Server & Client examples using Oauth will be helpful.

**Comment by dfawley** [comment]
We would like to provide some official examples or documentation for this scenario, but don't currently have the cycles.  In the meantime, if you search the web for "grpc oauth golang", you should find some samples to get you started.

**Comment by rakyll** [comment]
Is it sufficient to add some high-level godoc examples to `credentials` and `credentials/oauth`? If so, I can contribute the necessary reference examples.

**Comment by enocom** [comment]
OK. Sounds good. 👍
