### ISSUE TITLE
Add values to base context for a server / service

### ISSUE THREAD

**Issue by acasajus** [grpc/grpc-go#113]
I'd like to add some values to the base context for a server or a service. For instance a db connection or something. Something like:

1. Bootstrap app
2. Open DB connection
3. Create a context with the db connection as value
4. Set is a the base context for a server 
5. All RPC requests are able to access the DB connection through the context.

**Comment by GeertJohan** [comment]
Wouldn't it be better to add the db connection as a field to the server structure that implements the service interface? I think context isn't supposed to be used for values like these..

**Comment by acasajus** [comment]
What if you want to pass something to all the services in a server? We need to add that to all the services?

**Comment by GeertJohan** [comment]
Yes but when adding it to the context you'll have to get the value from the context and assert it to be your connection...
I don't think adding a line of code to each service implementing struct is a large problem.. If you have multiple services you could add a global accessor.
 is a good reason to instead add more lines of code to each method implementation

**Comment by acasajus** [comment]
Point taken :)
