### ISSUE TITLE
Error response from daemon: rpc error: code = 14 desc = grpc: the connection is unavailable

### ISSUE THREAD

**Issue by vaibhav-gadgil-sp** [grpc/grpc-go#1131]
I have initialized my docker swarm on one node and now I am trying to add node 2 as a worker to this swarm. When I am trying to run "docker swarm join --token [token goes here] [host]:[port]", I am getting the error: "Error response from daemon: rpc error: code = 14 desc = grpc: the connection is unavailable"

Note: My both docker nodes are working on Windows 10 pro 64 bit machine and I am trying to run this command using powershell

**Comment by menghanl** [comment]
Something is wrong with the connection. I'm not sure what the root cause of this though.
I would suggest make sure the network settings are correct.
