### ISSUE TITLE
Naming: generating a proto service should generate an interface ending in "Service" not "Server"

### ISSUE THREAD

**Issue by acasajus** [grpc/grpc-go#114]
When generating the the 'pb.proto' file after defining a service in the protofile. The interface for the service is named '<Name>Server' but it should be named '<Name>Service' to keep consistency A grpc server can have several services registered.

Instead of having to call 
```go
pb.RegisterMyNameServer(*grpc.Server,MyNameServer) 
```
it should be
```go
pb.RegisterMyNameService(*grpc.Server,MyNameService) 
```

The rest of the 'pb.proto' file is consistent afaik.

**Comment by dsymonds** [comment]
In this sense, a "server" is something that implements a "service" or a "server interface". It's a little unfortunate that the `grpc.Server` type has the same name, but it's not a big deal once you get used to it.

**Comment by acasajus** [comment]
Now that is alpha It could be fixed to keep consistency with the rest of the language implementations :)

**Comment by GeertJohan** [comment]
I agree with @dsymonds that "Server" could be a good name for something that implements the server side of a service. But the name is indeed confusing with `grpc.Server`.
The grpc.Server can serve multiple server's that implement the service's server interface.. :stuck_out_tongue_winking_eye: 

So how about adopting a new word? For instance `Handler`?

A `Handler` interface describes a `Service` and is implemented by the user.
e.g.:
```go
// Generated from the proto service definition
type FoobarHandler interface {
    Foobar(int) (int, error) // rpc method
    OtherThing(int
}

// Registration linker
RegisterFoobarHandler(*grpc.Server, FoobarHandler)
```

Now the `grpc.Server` can serve multiple Handlers which implement the service's Handler interface.

The name Handler is already being used by grpc, but afaik mostly internally.
For instance, this is generated code:
```go
var _Foobar_serviceDesc = grpc.ServiceDesc{
	ServiceName: "foobar.Foobar",
	HandlerType: (*FoobarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Foobar_Info_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Foobar_Subscribe_Handler,
			ServerStreams: true,
		},
	},
}
```

We can see `Handler` is already being used as a field to link service methods, but it also refers to the Server itself (`HandlerType`).

I don't think that the ServiceDesc, MethodDesc and StreamDesc's are to be modified by the user, so the Handler word might be a good option here.

**Comment by acasajus** [comment]
I'd prefer `Service` becase it describes a `Service`:

`A Handler interface describes a Service and is implemented by the user.` 

But I'm ok which `Handler` since it's different from `Server`

**Comment by iamqizhao** [comment]
I do not like Handler since it is already used in grpc meaning different thing. I like "Service"  and am also okay with "Server". I leave the decision to @dsymonds who is the owner of grpc codegen and protobuf in Go.

**Comment by dsymonds** [comment]
I've thought about it, and I think the current state is fine. Let's close this and move onto more important issues.

**Comment by GeertJohan** [comment]
:+1:
