### ISSUE TITLE
When a GRPC server also uses a GRPC client when handling a request, error code is incorrectly propagated

### ISSUE THREAD

**Issue by jhump** [grpc/grpc-go#1150]
This is actually a bit similar to https://github.com/grpc/grpc-go/issues/1148.

Currently, client errors and server errors are the same -- both typically created by calls to `grpc.Errorf(code, string, ...)` or other factory functions for `grpc.rpcError`. This means that when a server is handling a request during which it must make an outbound RPC, if the logic uses typical Go idioms for error propagation, the server will fail with the same response code as received by the client call.

While there are some cases where this appropriate -- like when forwarding/proxying a request to another server -- it should be the exception, not the rule.

For example, suppose a scenario where client A sends a request to server B. In processing the request, server B sends a request to server C which rejects the request -- the operation fails with "InvalidArgument". In this case, server B *should not* send back "InvalidArgument". It really should instead send back "Internal" since what likely happened is a bug in B that caused to create a malformed request. In this case, it was not A that supplied an invalid argument. And if it was, logic in B needs to ascertain that explicitly, vs. that being the default behavior. "Unimplemented" is another code that, in particular, makes no sense to propagate.

This behavior can be particularly problematic in systems that try to provide idempotence guarantees -- for example, services where "Unavailable" is stated to always be safe to retry later, even if the call in question is not idempotent (e.g. guarantees that no work was begun on behalf of the call). If one server (A) is processing a non-idempotent method and makes a call to another server (B) which returns "Unavailable", if any mutative or non-idempotent steps have already been taken in the first server (A), it must no propagate the return code or it has broken the contract. Suddenly, writing server code that adheres to the contract becomes difficult and error-prone, because straight-forward/intuitive error handling code will subvert the contract.

This issue could easily be solved by having a separate factory function for client errors (which would be used by both the framework as well as possibly by client interceptors). When a server call results in an error, treat client exceptions as other kinds of exception -- e.g. send "Unknown" or "Internal" instead of extracting the original error code.

Utility methods can be provided for translating a client exception into a server exception, for cases where proxying the original error code is actually the appropriate thing to do.

**Comment by dfawley** [comment]
> if the logic uses typical Go idioms for error propagation, the server will fail with the same response code as received by the client call.
>
> While there are some cases where this appropriate -- like when forwarding/proxying a request to another server -- it should be the exception, not the rule.

Part of idiomatic Go error propagation includes determining whether the error is appropriate to forward directly or if it might need to be wrapped or translated into another type of error instead.  Deciding how to translate errors should be the responsibility of the person implementing the middle service, not gRPC.  Mechanically, this translation can be readily accomplished via several methods without changing the gRPC core or API, e.g.s:

- client interceptors
- wrapper types/libraries
- translation functions (func (error) error) called in-line

I am not convinced the value of a gRPC-provided method of doing this would be worth the cost of API complexity or ongoing maintenance overhead.

FWIW, I've personally had success using a generic client wrapper library that wraps RPC calls using lambdas (func(context.Context) error) and does this kind of error translation -- and also adds other useful features like rate limiting and retrying.

Thank you for taking the time to write up your suggestion.

**Comment by jhump** [comment]
It is a shame that the "default" behavior -- code that doesn't have such boiler-plate error-checking for every call or use a custom interceptor -- doesn't just do the intuitive thing. A well-designed and easy-to-use API is one where the "right" thing to do is also the easiest and most intuitive ("pit of success").

**Comment by dragonsinth** [comment]
Perhaps this should be title, "It would be helpful to have separate error types for server and client errors, to enable easier error processing"

**Comment by dfawley** [comment]
> Perhaps this should be title, "It would be helpful to have separate error types for server and client errors, to enable easier error processing"

That title would put more emphasis on the proposed solution than the problem.  This also wouldn't make anything easier, really.  It would make it harder to accidentally forward the error code from an outbound call in a service handler.

Having separate types would be easy to implement, but this would be a behavior change.  I'm sure there are proxying/forwarding services out there that we would break if we did this.
