### ISSUE TITLE
Is there a way to close connection in RPC handler?

### ISSUE THREAD

**Issue by kkzhang** [grpc/grpc-go#1159]
Here i want to close the whole connection when unauthorized. But i cannot find the way.

Below is the code
```
func (s *server) Listen(req *pb.CommandReq, stream pb.CentralCommand_ListenServer) error {
	for {
		if req.Token != "123" {
			return errors.New("Unauthorized")
                        // Close connection here
		}
		stream.SendMsg(&pb.CommandBody{Func: "say", Args: "hello, " + time.Now().Format("2006-01-02 15:04:05")})
		var resp pb.CommandBodyResp
		stream.RecvMsg(resp)
		time.Sleep(100 * time.Millisecond)
	}
}
```

**Comment by dfawley** [comment]
I don't believe there's any way to do that using the stream or req parameters to the handler, but you can do it if you have a field in your server struct with the Server returned by grpc.NewServer().  Then you could call Stop() or GracefulStop() on that Server as desired.
