### ISSUE TITLE
Support for easier parsing and creation of Cookie

### ISSUE THREAD

**Issue by TamalSaha** [grpc/grpc-go#1174]
We can get the header keys from Metadata. But the related parsing code from Cookies in private in `net/http` package. Is there any way those can be exposed from Metadata or `net/http` package?
https://golang.org/src/net/http/cookie.go#L198

Thanks.

**Comment by menghanl** [comment]
We don't have support for that.
But I believe you should be able to do something like
```go
cookies := (&http.Request{Header: metadata}).Cookies()
```

**Comment by TamalSaha** [comment]
I tried the above code snippet. It does not work. This is what worked for me:

```
package auth

import (
	"fmt"
	"net/http"
	"testing"

	"google.golang.org/grpc/metadata"
)

func TestGetFromCookie(t *testing.T) {
	md := metadata.Pairs("Key-A", "Val-A")
	req := &http.Request{
		Header: http.Header{},
	}
	for k, v := range md {
		for _, val := range v {
			req.Header.Add(k, val)
		}
	}
	// req := &http.Request{Header: http.Header(md)}
	fmt.Println(req.Header.Get("Key-A"))
}
```
