### ISSUE TITLE
proto: duplicate proto type registered: google.rpc.Status

### ISSUE THREAD

**Issue by trevorgray** [grpc/grpc-go#1175]
Currently the packages under `cloud.google.com/go/...` are importing the `genproto/googleapis` protos from `google.golang.org/genproto/googleapis/...` however grpc imports them from `github.com/google/go-genproto/googleapis/rpc/status`.

This means that there are two `google.rpc.Status` protos defined and when I import packages from both grpc and `cloud.google.com/go/...`, I get the following error:

`proto: duplicate proto type registered: google.rpc.Status`

Which is the correct way to import the `genproto/googleapis` protos?

**Comment by dfawley** [comment]
From https://github.com/google/go-genproto/blob/master/README.md:

> IMPORTANT  This repository is currently experimental

I'll update grpc to use google.golang.org instead since it was only recently added.  Thanks.
