### ISSUE TITLE
how to assert an error is a type of rpcError from an outer package?

### ISSUE THREAD

**Issue by allencloud** [grpc/grpc-go#1177]
Hi, All, 

Thanks for the gRPC team who contributes  greatly to the community.

While when I do some practices with this, I got an issue which I think needs some help from the community.

Here is the scene:
1. I have a package package_A, and package_A imports package grpc-go;
2. in package_A, we have some code like this: `return grpc.Errorf(codes.InvalidArgument, "invalid")`. We know that codes returns an rpcError, which is defined in rpc_utils.go.
3. If I have a package package_B, which imports package_A; then in package_A, there are some cases that return an error has a type of rpcError. Then how do I assert that this is as rpcError. Actually I do not think we could use 
```
switch e := err.(type) {
case grpc.rpcError: // this is invalid, since rpcError is not exported.
        ........
case ...
        .......                  
}
```

Hope get some feedback. And any thought helps. Thanks

Allen

**Comment by menghanl** [comment]
Can you explain a bit more about what you plan to do based on whether the error is an rpcError?

We actually removed rpcError recently and replaced it with status: https://github.com/grpc/grpc-go/blob/master/status/status.go. And the new function [FromError](https://github.com/grpc/grpc-go/blob/master/status/status.go#L128) does what you need.
So you could switch to this if package_A uses a updated gRPC.

**Comment by allencloud** [comment]
> And the new function FromError does what you need.
That is true.

I need to make sure whether the error is an rpcError, then transfer the rpcError's code into http status code.

**Comment by mehrdada** [comment]
In the latest version of grpc-go (on master), some things are changed, and you can feed the `error` object you have to [`grpc/status.FromError`][1] and it returns `ok=false` if it is not actually a `statusError`. Does something like the following resolve your issue?

```go
if st, ok := status.FromError(err); ok {
    // use `st.Code()` here to get the status code
} else {
   // etc...
   switch err.(type) {
   }
}
```

[1]: https://github.com/grpc/grpc-go/blob/master/status/status.go#L128

**Comment by allencloud** [comment]
Yeah, I could get the answer in the latest version pf grpc-go. Thanks a lot @menghanl 
Closing this.
