### ISSUE TITLE
Why is stream.Send() not blocking

### ISSUE THREAD

**Issue by fiibbb** [grpc/grpc-go#1179]
Hi, I'm using server-side streaming, and I noticed that after the stream is established, `Send()` call on server-side does not seem to block, even if client side never calls `Recv()`. Does this mean the messages get  buffered in client's TCP (or transport, in general) layer? I just wanna confirm that unread messages are not staged on the server side, causing memory issue etc.

Also, the [documentation](https://github.com/grpc/grpc-go/blob/master/stream.go#L76) says `Send()` blocks until the message is sent. That conflict with what I described above. May be I misunderstood and the doc simply means `Send()` blocks until the transport layer system call returns?

**Comment by MakMukhi** [comment]
You're right in correction of your misunderstanding; Send blocks until the
message is sent out from the server and not until the client actually
receives it.
