### ISSUE TITLE
f.fr.SetReuseFrames undefined

### ISSUE THREAD

**Issue by kristinn** [grpc/grpc-go#1183]
Hi all. I hope I'm creating a ticket to the correct repository, since the code in question is part of `google.golang.org/grpc` (which I suppose is this repository?).

This library seems to be affected by a bad merge, causing issues when trying to `go get` it.

1. Go version: 1.8.1
2. OS + Arch: Mac OS X (darwin), amd64.
3. What did I do: `go get google.golang.org/grpc`.
4. What did I expect to see: Nothing (no errors).
5. What did I see instead:
```
# google.golang.org/grpc/transport
../google.golang.org/grpc/transport/http_util.go:388: f.fr.SetReuseFrames undefined (type *http2.Framer has no field or method SetReuseFrames)
```

I suspect this to be the culprit: https://github.com/grpc/grpc-go/commit/ff17eeb5f6e2112ef30f103d686fa725ee31202e

I would create a pull request myself if I would be sure reverting that wouldn't cause some other issues, so instead I'm creating a ticket.

Thank you!

**Comment by tsl0922** [comment]
You may need to update your `golang.org/x/net/http2` package.

**Comment by kristinn** [comment]
Ahh! That fixed it! Thanks! :facepalm:
