### ISSUE TITLE
New release with issue # 1148?

### ISSUE THREAD

**Issue by TamalSaha** [grpc/grpc-go#1187]
Hi,
Can we get a new release with https://github.com/grpc/grpc-go/issues/1148 ?

Thank.

**Comment by mehrdada** [comment]
If everything goes right, a 1.3 release should be right around the corner (probably in a week or so, maybe less).

**Comment by mehrdada** [comment]
I am closing the issue, but please reopen and do let us know if that time frame would not be acceptable to you.
