### ISSUE TITLE
Status 404 does not trigger an error on the client side

### ISSUE THREAD

**Issue by kyessenov** [grpc/grpc-go#1190]
Version: 1.2.1
I deploy GRPC client and server with a http2-aware proxy in the middle. In some cases, my proxy returns status 404 to the client when the server is not available. GRPC client does not detect this as an error and returns an empty response with an empty error.
This seems like a bug, since GRPC mandates status 200 and status 404 should trigger a protocol error.

**Comment by menghanl** [comment]
This issue will be fixed by #975
