### ISSUE TITLE
Compression / Decompression API change

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#1193]
The current system requires the user to create types and define Do and Type methods on those types to satisfy the Compressor and Decompressor interfaces.  This makes it cumbersome to install new compressors and decompressors.

A proposal to replace this:

- For compression, change grpc.WithCompressor as follows:

func WithCompressor(name string, f func(io.Writer) io.WriteCloser) DialOption

Outbound RPC requests/responses will use f to create a writer that compresses the messages before sending.  "name" will be written to the header (as Type() is today) for decompression.

- For decompression, create a RegisterDecompressor function in the grpc package as follows:

func RegisterDecompressor(name string, f func(io.Reader) (io.ReadCloser, error))

f will be added to a map maintained within the grpc package.  Upon receiving a compressed message, grpc will check if a decompressor for that type is registered.  If so, f will be used to decompress it.

Enabling gzip would look something like this:

grpc.RegisterDecompressor("gzip", func(r io.Reader) (io.ReadCloser, error) { return gzip.NewReader(r) })
grpc.Dial(..., grpc.WithCompressor("gzip", func(w io.Writer) (io.WriteCloser) { return gzip.NewWriter(w) })

(The wrappers are unfortunate but necessary because of Go's type system.)

This would be API breaking, so must be coordinated appropriately.  One benefit of breaking this API is that it enables us to remove the gzip dependency from the core grpc package at the same time.

**Comment by dfawley** [comment]
Some minor changes to this proposal:

```go
package grpc

func RegisterCompressor(name string, f func(io.Writer) io.WriteCloser)
func RegisterDecompressor(name string, f func(io.Reader) (io.ReadCloser, error))
func UseCompressor(name string) CallOption
```

Usage:
```go

func init() {
  grpc.RegisterCompressor("gzip", func(w io.Writer) (io.WriteCloser) { return gzip.NewWriter(w) })
  grpc.RegisterDecompressor("gzip", func(r io.Reader) (io.ReadCloser, error) { return gzip.NewReader(r) })
}

cc, err := grpc.Dial(..., grpc.WithDefaultCallOptions(grpc.UseCompressor("gzip")))
// All calls use "gzip" unless overridden:
res, err := client.SomeMethod(..., grpc.UseCompressor("deflate"))
```

The legacy `grpc.WithCompressor` will continue to be used (unless overridden by the `UseCompressor` call option).

If `grpc.WithDecompressor` is specified, we will always use that decompressor instead of looking for the registered decompressor, to avoid a behavior change.  No compressors/decompressors will be installed by default, but we will add a package that implements gzip compression/decompression (mainly as an example), which can be imported to self-register gzip support.

This effectively matches how codecs will be implemented in the near future.

**Comment by mehrdada** [comment]
I commented here about the max message sizes at https://github.com/grpc/grpc-go/pull/1428#issuecomment-321037862 , but here might be a more appropriate place to discuss the max message size issue. Where does the max message size get enforced? Simply checking at the end of decompression is certainly not enough and not very useful either. Ideally, a decompressor would only allocate a small buffer and flushes it in the writer downstream, and that underlying writer should be aware of the max message size and return an error on Write if the decompressor is flushing too much data. That error should be then propagated by the decompression filter.

**Comment by dfawley** [comment]
@mehrdada yes, this is how I envision this check will happen eventually.

**Comment by mehrdada** [comment]
Cool! Thanks. Just wanted to make sure this requirement does not get forgotten.
