### ISSUE TITLE
http2_server.go undefined var causes failure to build

### ISSUE THREAD

**Issue by nullaus** [grpc/grpc-go#1196]
https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L744

statusCode is not defined.

**Comment by nullaus** [comment]
Offending commit: https://github.com/grpc/grpc-go/commit/6d0e6b04b3cd553e2007ef075fd2445a192e4c0d

**Comment by MakMukhi** [comment]
Making a revert.

**Comment by nullaus** [comment]
Thanks! :)
