### ISSUE TITLE
Binary metadata are base64 encoded/decoded with paddings

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc-go#1207]
Currently go expects incoming base64 encoded headers to have paddings. It also encodes with paddings.

This violates the grpc spec: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

> Implementations MUST accept padded and un-padded values and should emit un-padded values.

`RawStdEncoding` seems to do the trick.

**Comment by yang-g** [comment]
This cause grpc-go to reject valid metadata from C-based libraries...

**Comment by dfawley** [comment]
I don't believe the base64 package can handle padded OR unpadded values.  So it looks like we'll have to try both.

**Comment by yang-g** [comment]
Maybe you can check whether `input_length % 4 == 0`...

**Comment by dfawley** [comment]
Yes, that seems reasonable, thanks for the suggestion.

**Comment by yang-g** [comment]
Thanks for the quick fix.
Also thanks to @menghanl for helping me debugging.
