### ISSUE TITLE
channel state changes

### ISSUE THREAD

**Issue by damanloox** [grpc/grpc-go#1208]
"All libraries should also expose an API that enables the application (user of the gRPC API) to be notified when the channel state changes." (https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md)

Has this been implemented yet...? I can't see any way of getting state changes on the client...

**Comment by menghanl** [comment]
This is currently not implemented.

Can you give more information about what you are planning to do with this API?

**Comment by damanloox** [comment]
I've a long-lived client (of gobgpd server) and a stream coming from the server. I need to be able to detect if/when the server goes offline and back to be able to reconnect the stream (and notify end user of the problem). Unfortunately I don't have control on the server (besides public API) so I need to be able to detect connection state changes on the client...
