### ISSUE TITLE
Don't see a way to know the current state of a client connection (connected or not)

### ISSUE THREAD

**Issue by raff** [grpc/grpc-go#121]
I am trying to use grpc as the transport for exchanging messages on a cluster.

I don't have a "service discovery" yet, so I am starting with hard-coded cluster peers. When one peer start it will create a grpc service and then open one client connection to each other peer.

When the cluster is starting up, some of the client connections will be pending, waiting for the remote peer to start. The documentation seems to imply the client Dial should fail, but instead it retries in the background. This is what I want, but I don't think I have any way to know when the connection succeed so that I can start sending requests.

I guess I could use the WithTimeout(t) option on the Dial, and do my own retries, but it would be great if there was a way to just check the client object. The other alternative is to use a context with timeout when calling the various rpc methods (with context.Background all requests seem to wait a few seconds before aborting) but I don't really want to wait if the connection is not active yet nor I want to start a goroutine for each rpc call (I need to preserve ordering).

**Comment by iamqizhao** [comment]
I can add a getter for the state of ClientConn. But be aware of that this kind of getter is always racy -- you could get stale state (the underlying could change the state at any time.) when you call that getter. That's the reason I did not add that in the first place. Actually, you can feel free to send requests when the connection is doing retries unless you inject too many pending requests leading to memory issues.

**Comment by dsymonds** [comment]
I don't think we should be adding APIs that are fundamentally racy. And a network connection can fail at any time, so it's not just a startup problem.

If an RPC service needs a way to probe the liveness of a connection, it can easily add a Ping method or similar.

**Comment by raff** [comment]
Actually I did realize that I would need this also after the connection has
been established. The problem of just sending requests when the connection
is down is that I do have a ton of those and some of those are long
running. I have no problem returning an error or losing requests (this is
for a sharded pubsub) but I can't keep clients pending if one of the nodes
is not responding.

I am going to do some experiments with timeouts and see where I get.

**Comment by raff** [comment]
So, what about having the option to define a callback triggered when the connection status changes ?

**Comment by dsymonds** [comment]
That's just as racy, and a lot of the time there's no way to tell that the connection is broken until you try to use it.

**Comment by iamqizhao** [comment]
regarding callback approach,
i) As dsymonds mentioned, it is still racy unless the calls holds a lock (so that others cannot change the state) when it runs, which is clearly not a sound solution;
ii) I always try hard to avoid all these callback based stuffs in grpc-go lib and favor the simple synchronous model which has been used in it.
