### ISSUE TITLE
It's possible to get ServiceName?

### ISSUE THREAD

**Issue by anticpp** [grpc/grpc-go#1216]
I have integrated our OAuth flow with gRPC call credentials.
Thus, for the OAuth scope, which can be the service name or method name of the gRPC protocol.  However, I can't find way to extract service name for it's not exported. I have to introduce an interface to specify the service name in my middleware.

Problem: It's there any way to get the service name? Then I can conseal the service name interface for in my middleware, which seems more gracefully.

**Comment by menghanl** [comment]
I'm not clear what you are trying to get here.
Is this on server side? Where do you need the service name?

**Comment by anticpp** [comment]
Actually, It's on the client side, I need to get the service name or method name(as known FullMethodName) to identify a scope in OAuth.

**Comment by dfawley** [comment]
Sorry for dropping this -- were you able to resolve it?
