### ISSUE TITLE
gRPC v1.3.0 Invoke array doubles

### ISSUE THREAD

**Issue by elvizlai** [grpc/grpc-go#1218]
proto
```
syntax = "proto3";

package pb;
// The greeting service definition.
service Greeter {
    // Sends a greeting
    rpc SayHello (HelloRequest) returns (HelloRequest) {}
}

// The request message containing the user's name.
message HelloRequest {
    repeated string name = 1;
}
```

server
```
package main

import (
	"../pb"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"
	"log"
	"net"
)

type server struct {
}

func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloRequest, error) {
	return in, nil
}

const port = ":50051"

func main() {
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	s := grpc.NewServer()
	pb.RegisterGreeterServer(s, &server{})
	// Register reflection service on gRPC server.
	reflection.Register(s)
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
```

client
```
package main

import (
	"../pb"
	"context"
	"google.golang.org/grpc"
	"log"
	"time"
)

const (
	address = ":50051"
)

func main() {
	// Set up a connection to the server.
	conn, err := grpc.Dial(address, grpc.WithInsecure())
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	defer conn.Close()
	//c := pb.NewGreeterClient(conn)

	//for i := 0; i < 100; i++ {
	//	r, err := c.SayHello(context.Background(), &pb.HelloRequest{Name: []string{"a"}})
	//	if err != nil {
	//		log.Fatalf("could not greet: %v", err)
	//	}
	//
	//	log.Printf("Greeting: %s", r.Name)
	//
	//	<-time.After(time.Second)
	//}

	for i := 0; i < 100; i++ {
		x := &pb.HelloRequest{Name: []string{"a", "b"}}
		err = grpc.Invoke(context.Background(), "/pb.Greeter/SayHello", x, x, conn)
		if err != nil {
			log.Fatal(err)
		}
		log.Printf("Greeting: %s", x.Name)

		<-time.After(time.Second)
	}
}
```

Client Output:
```
2017/05/04 20:02:26 Greeting: [a b a b]
2017/05/04 20:02:27 Greeting: [a b a b]
```

It should be [a b]

This work fine in gRPC v1.2.1

**Comment by menghanl** [comment]
You are reusing the request to get the response, which doesn't seem correct.
It shouldn't work. It worked because the proto unmarshaller didn't reuse the underlying buffer.
In a performance change, we reuse the buffer when unmarshalling. So this problem is revealed.

What you should do is what we do in our generated code (https://github.com/menghanl/grpc-go/blob/master/examples/helloworld/helloworld/helloworld.pb.go#L86):
```go
x := &pb.HelloRequest{Name: []string{"a", "b"}}
out := new(pb.HelloReply)
err = grpc.Invoke(context.Background(), "/pb.Greeter/SayHello", x, out, conn)
```

Also, do you have any particular reasons to call `Invoke` instead of calling the generated code? This kind of problems can be avoided if you are using the generated code.

**Comment by elvizlai** [comment]
Yes，I know using a new object can avoid this.

We has a framework using Invoke to make gRPC call more easily in our project. It handles conn automatic(we made a map of conn and service name). What we do is using service name and the method name to call rpc.

For example

RRC(ctx, "greater", "SayHello" ,in ,out)

Unfortunately this failed now if in and out using same ptr.

**Comment by menghanl** [comment]
If you **really** want this to work, you could try to override the codec with the some custom codec ([WithCodec](https://godoc.org/google.golang.org/grpc#WithCodec)) when dialing.

I think the old codec here would just work: https://github.com/grpc/grpc-go/pull/1010/files#diff-9d9af2a19a6c9f88d8535aa95b1f9c22L68

**Comment by elvizlai** [comment]
Using a not clear output, it works like append too.
```
	for i := 0; i < 100; i++ {
		x := &pb.HelloRequest{Name: []string{"a", "b"}}
		y := &pb.HelloRequest{Name: []string{"c", "d"}}
		err = grpc.Invoke(context.Background(), "/pb.Greeter/SayHello", x, y, conn)
		if err != nil {
			log.Fatal(err)
		}
		log.Printf("Greeting: %s", y.Name)

		<-time.After(time.Second)
	}
```

Output:
```
2017/05/05 09:38:37 Greeting: [c d a b]
```

**Comment by elvizlai** [comment]
@menghanl 
How about adding `v.(proto.Message).Reset()` before https://github.com/grpc/grpc-go/blob/master/codec.go#L99
