### ISSUE TITLE
godoc improvement needed

### ISSUE THREAD

**Issue by adelez** [grpc/grpc-go#1220]
What version of Go are you using (go version)?
master

What did you expect to see?
Descriptions in https://godoc.org/google.golang.org/grpc/health and https://godoc.org/google.golang.org/grpc/status need elaboration.
e.g. "Errorf returns Error(c, fmt.Sprintf(format, a...))." is not a useful comment.

serverHTTP in server.go doesn't have description.

**Comment by dfawley** [comment]
Docs were added to ServeHTTP and clarified elsewhere.  The status package was not changed -- similar documentation is pretty common in Go.
