### ISSUE TITLE
Server-side streaming for latency-critical options (allow `Delay:false`)

### ISSUE THREAD

**Issue by mwitkow** [grpc/grpc-go#1242]
The current interface of a `ServerStream` allows one to only send a message to a potentially buffered connection. https://github.com/grpc/grpc-go/blob/master/stream.go#L594

This means that for use cases when user logic wants to make sure that small and rare messages are pushed to a listener ASAP (e.g. for `WatchAPI` like streams), there can be a sigificant delay (couple of tens of ms) just buffering on the `grpc/transport`. 

It would be great if `ServerStream.Send` accepted an options block that allowed you to say "NoDelay".

It is possible to work around now by going to low level hacks:

```go
			// Flush the stream
			lowLevelServerStream, ok := transport.StreamFromContext(stream.Context())
			if !ok {
				return grpc.Errorf(codes.Internal, "lowLevelServerStream does not exist in context")
			}
			lowLevelServerStream.ServerTransport().Write(lowLevelServerStream, make([]byte,0), &transport.Options{
				Delay: false,
```

But this is not ideal.

**Comment by MakMukhi** [comment]
You're right and this should be an easy implementation too, given the hooks are available. However, we'd like to give a little more thought to it. 
We are looking into batching writes together as performance optimization and would like to think about how this would interact with that, given the API says this is only a hint to the transport.
As a rough timeline on this I'd say somewhere around a month or more. 

Also, we think what you're seeing is actually a flow-control push-back. Moreover, the hack( setting Delay ) shouldn't do anything in the current state of transport. Write function doesn't look at it:
https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L838

**Comment by mwitkow** [comment]
@MakMukhi the `http.Handler` transport does respect it:
https://github.com/grpc/grpc-go/blob/master/transport/handler_server.go#L263

**Comment by dfawley** [comment]
@mwitkow, could you clarify this better, please?  From what we can tell, we never set Delay to true, so we will always flush at the end of every message.  (In fact, #524 is requesting the ability to set Delay to true when performing a Send.)

**Comment by MakMukhi** [comment]
Both `http2Server` and `http2Client` now have a dedicated goroutine that flushes when there's nothing else to be sent or the underlying I/O buffer is full. I'm not sure how effective would it be to force flush a message; it would be helpful only in case where there are other streams but in such a case there's no way to prioritize one stream's schedule over the other.
Are you still interested in this?
