### ISSUE TITLE
Enable Connectivity State API

### ISSUE THREAD

**Issue by lukaszx0** [grpc/grpc-go#1245]
The Connectivity State API was introduced in https://github.com/grpc/grpc-go/pull/690 but at the time it was _temporarily disabled_.

Year later, the `WaitForStateChange` and `GetState()` are still [private](https://github.com/grpc/grpc-go/blob/master/clientconn.go#L787).

What's the reason for that? Can we enable this functionality?

Is there any other way to listen on channel/client state changes? My use case is reestablishing stream connections after server reconnects and in order to do that I need to have some way of listening on reconnect event.

**Comment by dfawley** [comment]
Those functions deal with addrConns, which are individual connections, not the ClientConn, which represents a connection to zero or more servers.  It sounds like you're interested in just knowing whether the ClientConn is valid?

Can you attempt to re-establish the stream even though the server is still down, but set non-fail-fast and a very long deadline?

**Comment by lukaszx0** [comment]
Thanks, I'll have a look - this will probably work.

Regardless of workaround though, shouldn't this be exposed in `ClientConn` as part of cross-language spec: https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md#channel-state-api ?

**Comment by dfawley** [comment]
We are planning to implement the connectivity state API next quarter (by September).

**Comment by TheSalmonTapes** [comment]
Thanks for the update!

**Comment by dfawley** [comment]
Looks like there's a dupe of this.  #1208.
