### ISSUE TITLE
using both cancelled and canceled in codes

### ISSUE THREAD

**Issue by ghasemloo** [grpc/grpc-go#1246]
https://github.com/grpc/grpc-go/blob/master/codes/codes.go#L48

Both spelling are correct, but we should pick one and be consistent.

**Comment by hsaliak** [comment]
Given that Canceled is the spelling of the exported constant, the comment should be updated. 
@dfawley just a heads up to perhaps fix this the next time changes go into this file..

Alternatively, @ghasemloo if you want to send us a PR that should work too.

**Comment by ghasemloo** [comment]
Hmm, looking at 
https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto#L39
it seems they use "Cancelled" but I guess changing the const may break things.
Aren't these files generated from googleapis repo?

**Comment by shurcooL** [comment]
> Both spelling are correct, but we should pick one and be consistent.

Related: https://dmitri.shuralyov.com/idiomatic-go#use-consistent-spelling-of-certain-words.

The Go project chose to go with the single-l spelling.
