### ISSUE TITLE
How to achieve ssh like auth based on SSL public keys?

### ISSUE THREAD

**Issue by spikebike** [grpc/grpc-go#1252]
I'm trying to setup a client and server where each peer recognizes the other by the public key.  Then both client and server can act accordingly.  So 10 clients could connect, I could give 10 different responses, and they couldn't impersonate each other without stealing the private key of the other clients.  Much like ssh which based the security on the host key and the users key.

First I tried overriding the Server/Client Handshake.  Unfortunately ClientHandshake is passed a context.Context, but doesn't return one.  So I can NOT do something like:
```
   ip, ok := ctx.Value(peerIDKey).(int)
   if ok == false { 
       <retreive peerID based on public key>
       ctx = context.WithValue(ctx, peerIDKey, )
   } 
   return ctx
```
The ServerHandshake is even more difficult because it is not passed a ctx.  So that rules out the client/server handshake, which is unfortunate since doing the auth per connection would minimize auth overhead.

With that not working I tried using UnaryServerInterceptor and StreamServerInterceptor, this are per RPC call, but could potentially work.  UnaryServerInterceptor was straight forward:
```
   peerID, ok := ctx.Value(peerIDKey).(int)
   if ok == false {
      peerID = <get peerID>
      ctx = context.WithValue(ctx, peerIDKey, peerID)
   }
   resp, err := handler(ctx, req)
   return resp, err
```

However StreamServerInterceptor is not passed a ctx, and returns only an error.  

So my goal is to set a peerID somewhere, and have all RPC calls have access to the peerID.  The natural place for the peerID seems to be the context.Context, which is inaccessible to StreamServerInterceptor.

Suggestions?

**Comment by menghanl** [comment]
Have you considered put the information in [AuthInfo](https://github.com/grpc/grpc-go/blob/master/credentials/credentials.go#L88)?

`AuthInfo` can be retrieved from [peer](https://github.com/grpc/grpc-go/blob/master/peer/peer.go#L52)

**Comment by spikebike** [comment]
Where would you set it, during the handshake?  Or in the Interceptor?  Where would you check it?

**Comment by menghanl** [comment]
You can set `AuthInfo` during handshake. It's one of the values returned by handshake functions.

To check, first get the `Peer` for the RPC, using [FromPeer](https://github.com/grpc/grpc-go/blob/master/peer/peer.go#L63).
(Note that for Unary RPCs on client side, you need to use [this call option](https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L198) to get Peer, and it's only available when the unary call is finished).

Then with `Peer`, you can check the `AuthInfo` (with a type assertion).
