### ISSUE TITLE
Question: rpc_util.go:recvMsg buffer reuse

### ISSUE THREAD

**Issue by Tapanito** [grpc/grpc-go#1253]
In the recvMsg method there is the following TODO comment:
```
	// TODO(bradfitz,zhaoq): garbage. reuse buffer after proto decoding instead
	// of making it for each message:
	msg = make([]byte, int(length))
	if _, err := io.ReadFull(p.r, msg); err != nil {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
		return 0, nil, err
	}
```

When running a grpc server, which supports large file (200MB) upload, the memory usage of this method is extremely high as it creates a new buffer for reach message, and it takes some time before GC releases the memory. Here is top5 output from pprof:
```
(pprof) top5
175.82MB of 177.83MB total (98.87%)
Dropped 110 nodes (cum <= 0.89MB)
Showing top 5 nodes out of 16 (cum >= 1MB)
      flat  flat%   sum%        cum   cum%
  175.82MB 98.87% 98.87%   175.82MB 98.87%  github.com/Satalia/se-app/vendor/google.golang.org/grpc.(*parser).recvMsg
         0     0% 98.87%        1MB  0.56%  encoding/json.(*decodeState).object
         0     0% 98.87%        1MB  0.56%  encoding/json.(*decodeState).unmarshal
         0     0% 98.87%        1MB  0.56%  encoding/json.(*decodeState).value
         0     0% 98.87%        1MB  0.56%  encoding/json.Unmarshal
```

Are there any updates on this issue?

**Comment by dfawley** [comment]
This change isn't possible without changing the API for codecs.  I.e. we hand that buffer straight to the codec, which is free to take a reference to it, and pass it along to the application.

We are focusing on performance more in the upcoming weeks/months, and have some changes we are considering in this area at that time.
