### ISSUE TITLE
Flaky test: TestFlowControlLogicalRace

### ISSUE THREAD

**Issue by MakMukhi** [grpc/grpc-go#1255]
This test fails occasionally with errors like:
end2end_test.go:4149: got 0 responses to request 316
end2end_test.go:4149: got 0 responses to request 317
end2end_test.go:4149: got 0 responses to request 318

None of us have been able to reproduce it. This was seen earlier by menghanl@ and apolcyn@. Alex mentions of this in the issue #1164.

**Comment by MakMukhi** [comment]
Update: Got around reproducing this (once every couple 1000 runs); The time out set on RPCs is 1 second. Changed that to 5 seconds and ran for 100000 times, all pass.

Not sure though why 1 second wasn't enough.

**Comment by dfawley** [comment]
The flaky test was fixed; @MakMukhi still wanted to investigate why a full second was insufficient for something expected to take microseconds.

**Comment by dfawley** [comment]
It seems like scheduling issues were the root cause of this.
