### ISSUE TITLE
panic: io.Reader is *transport.recvBufferReader, not *transport.transportReader

### ISSUE THREAD

**Issue by jefferai** [grpc/grpc-go#1257]
This was caused by https://github.com/grpc/grpc-go/pull/1248 (@MakMukhi)

In the PR, in handler_server line 335 (https://github.com/grpc/grpc-go/commit/6dff7c5f333b5331089ccc6451fc842664f3be6a#diff-95e9a25b738459a2d3030e1e6fa2a718R335), `s.trReader` is set as a `recvBufferReader`. However, in the same PR, everywhere else it is changed to use `transportReader`. As a result the type assertion at line 329 of transport.go (https://github.com/grpc/grpc-go/commit/6dff7c5f333b5331089ccc6451fc842664f3be6a#diff-fa3fe0c81c67082780f26a237879b514R329) panics.

This error was not caught by existing tests.

**Comment by MakMukhi** [comment]
Ah! My bad. I'll have a fix in later this morning.
