### ISSUE TITLE
one grpc-go server only can support 1000 connections ? 

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [grpc/grpc-go#1261]
when i dialed more than 1006 conn , and call rpc funcion, client will hang . even , other new client can not connect to server  . 

my test  code 
```

func test(remote, ip string) {
	conn, err := grpc.Dial(remote, grpc.WithInsecure())
	if err != nil {
		fmt.Printf("did not connect: %v", err)
		return
	}
	//defer conn.Close()
	c := protobuf.NewControllerClient(conn)
	report := protobuf.Report{AgentIp: ip, Type: "dpdk"}
	_, err = c.ReportStatus(context.Background(), &report)
	if err == nil {
		fmt.Printf("finish\n")
	} else {
		fmt.Printf("err:%s\n", err)
	}
}


func main() {
	if len(os.Args) != 3 {
		fmt.Printf("test X.X.X.X:Port IP\n")
		return
	}
	remote := os.Args[1]
	ip := os.Args[2]
	for i := 0; i < 10000; i++ {
		fmt.Printf("%d:", i)
		test(remote, ip)
		time.Sleep(time.Duration(10) * time.Millisecond)
	}
	time.Sleep(time.Duration(100) * time.Second)
}

```

**Comment by zhengxiaochuan-3** [comment]
```
981:finish
982:finish
983:finish
984:finish
985:finish
986:finish
987:finish
988:finish
989:finish
990:finish
991:finish
992:finish
993:finish
994:finish
995:finish
996:finish
997:finish
998:finish
999:finish
1000:finish
1001:finish
1002:finish
1003:finish
1004:finish
1005:finish
1006:^C
```

**Comment by qiyunfeng01** [comment]
I ran into the same problem these days, suspect it be introduced by grpc.

**Comment by MakMukhi** [comment]
I tried to reproduce your issue but couldn't. How big are your messages? [Here](https://github.com/grpc/grpc-go/compare/master...MakMukhi:debug?expand=1), I tried with 1 MB messages.

By the way, this example and subsequently my repro attempt both are leaking resources; conn should be closed once it's not useful anymore.

**Comment by MakMukhi** [comment]
It'd be great if you can create a standalone repro of the issue.

**Comment by zhengxiaochuan-3** [comment]
thanks for your test .
my message is very small . 
and I tried to reproduce it by grpc-go/examples/helloworld ,but couldn`t . 

I will test my project again. will update this issue when i get result .

**Comment by zhengxiaochuan-3** [comment]
Turns out it`s the systemd open file limits . My service is started by systemd .

here it is :
 https://bugzilla.redhat.com/show_bug.cgi?id=754285[
](url)
