### ISSUE TITLE
Allow the use of a server as a client

### ISSUE THREAD

**Issue by tomwilkie** [grpc/grpc-go#1263]
Sometimes (for instance, when testing) it is useful to skip the whole RPC layer and just wire up the system in a single process.  As such, I would like to be able to use my gRPC server types as clients but I can't, as the client wants to pass the extra `grcp.CallOption`s.

Would you consider auto-generating an adapter type to allow people to do this?  It would be a little more complicated to support the various streaming interfaces too, but nothing to difficult.  An example of a manually written adapter is here: https://github.com/weaveworks/cortex/blob/master/pkg/ingester/ingester_lifecycle_test.go#L248

**Comment by dfawley** [comment]
Upon further consideration, I don't think this is a good idea.  The "extra" `CallOption`s can do things like specify metadata, which may affect the behavior of the server.

I believe what you really want is #906 to cut out unnecessary gRPC processing while still doing the things it needs to do that affect client/server interaction.

**Comment by mackross** [comment]
We're not that concerned with serialization overhead but during development having all services in one binary and stack traces through RPC would be great.

**Comment by dfawley** [comment]
You don't need this feature to do that.  You can put your clients and services in one binary and have the server serve to a free port on localhost, with the clients dialing that same port.

Or, you could try out our [bufconn package](https://godoc.org/google.golang.org/grpc/test/bufconn) that we use for some of our testing to avoid the network stack entirely.  To use it, you pass a `bufconn.Listener` to a `grpc.Server`'s `Serve` method, and pass the listener's `Dial` function as a custom dialer via the [`WithDialer`](https://godoc.org/google.golang.org/grpc#WithDialer) call option.  (Wrap it to ignore the args.)
