### ISSUE TITLE
Server leaks goroutines

### ISSUE THREAD

**Issue by utrack** [grpc/grpc-go#1269]
(grpc-go v1.3.0, go1.8.1)

Hi,
We've encountered a weird goroutine leak at

```
goroutine profile: total 774
221 @ 0x42e27a 0x429397 0x4289d9 0x594e68 0x594ed4 0x596627 0x5a9840 0xad5087 0xad649f 0x4ed822 0x470929 0x470a98 0x76236b 0x762cc4 0x7a11bf 0x79833a 0x7b8dc2 0x7b8c19 0x7b874a 0x45b541
#	0x4289d8	net.runtime_pollWait+0x58								/usr/local/go/src/runtime/netpoll.go:164
#	0x594e67	net.(*pollDesc).wait+0x37								/usr/local/go/src/net/fd_poll_runtime.go:75
#	0x594ed3	net.(*pollDesc).waitRead+0x33								/usr/local/go/src/net/fd_poll_runtime.go:80
#	0x596626	net.(*netFD).Read+0x1b6									/usr/local/go/src/net/fd_unix.go:250
#	0x5a983f	net.(*conn).Read+0x6f									/usr/local/go/src/net/net.go:181
#	0xad5086	search_api/vendor/github.com/soheilhy/cmux.(*bufferedReader).Read+0x176			/go/src/search_api/vendor/github.com/soheilhy/cmux/buffer.go:53
#	0xad649e	search_api/vendor/github.com/soheilhy/cmux.(*MuxConn).Read+0x4e				/go/src/search_api/vendor/github.com/soheilhy/cmux/cmux.go:259
#	0x4ed821	bufio.(*Reader).Read+0x311								/usr/local/go/src/bufio/bufio.go:213
#	0x470928	io.ReadAtLeast+0xa8									/usr/local/go/src/io/io.go:307
#	0x470a97	io.ReadFull+0x57									/usr/local/go/src/io/io.go:325
#	0x76236a	search_api/vendor/golang.org/x/net/http2.readFrameHeader+0x7a				/go/src/search_api/vendor/golang.org/x/net/http2/frame.go:237
#	0x762cc3	search_api/vendor/golang.org/x/net/http2.(*Framer).ReadFrame+0xa3			/go/src/search_api/vendor/golang.org/x/net/http2/frame.go:492
#	0x7a11be	search_api/vendor/google.golang.org/grpc/transport.(*framer).readFrame+0x2e		/go/src/search_api/vendor/google.golang.org/grpc/transport/http_util.go:544
#	0x798339	search_api/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams+0x2c9	/go/src/search_api/vendor/google.golang.org/grpc/transport/http2_server.go:364
#	0x7b8dc1	search_api/vendor/google.golang.org/grpc.(*Server).serveStreams+0x161			/go/src/search_api/vendor/google.golang.org/grpc/server.go:525
#	0x7b8c18	search_api/vendor/google.golang.org/grpc.(*Server).serveHTTP2Transport+0x488		/go/src/search_api/vendor/google.golang.org/grpc/server.go:506
#	0x7b8749	search_api/vendor/google.golang.org/grpc.(*Server).handleRawConn+0x4a9			/go/src/search_api/vendor/google.golang.org/grpc/server.go:475

221 @ 0x42e27a 0x43d574 0x43c1dc 0x79d0d8 0x45b541
#	0x79d0d7	search_api/vendor/google.golang.org/grpc/transport.(*http2Server).keepalive+0x487	/go/src/search_api/vendor/google.golang.org/grpc/transport/http2_server.go:885

221 @ 0x42e27a 0x43d574 0x43c1dc 0x79da0d 0x45b541
#	0x79da0c	search_api/vendor/google.golang.org/grpc/transport.(*http2Server).controller+0x78c	/go/src/search_api/vendor/google.golang.org/grpc/transport/http2_server.go:947

15 @ 0x42e27a 0x43d574 0x43c1dc 0x70b44a 0x45b541
#	0x70b449	net/http.(*persistConn).writeLoop+0x439	/usr/local/go/src/net/http/transport.go:1704
```

Top3 grows linearly over time.
Number of routines shrinks a bit (total around 50 routines) and then grows more. Any pointers?

**Comment by MakMukhi** [comment]
Each connection has associated go routines: controller, keepalive and from the looks of it a writer routine that comes from the net/http library. If the connection is closed (shutdown channel closed) properly, these goroutines end. I'd start with making sure the connection was terminated properly.
The goroutine relating to reading(HandleStream) is associated with every RPC request the server receives and persists only as long as the RPC itself.

Does that help? If not, how exactly do you see these leaks? What's the use-case? Perhaps, some related code that you can share?

**Comment by MakMukhi** [comment]
If there's nothing that needs to be done, can we close this issue?

**Comment by ewang** [comment]
@MakMukhi We're seeing something similar but may or may not be the same issue. We're on grpc-go 1.0.2 and are seeing lots of unclosed connections which seems to lead to the related goroutines not getting garbage collected.

I think it might be due to client side not properly closing connections so the server still leave them open. I'm thinking that upgrading to the latest grpc-go and implementing the new server side keepalive should clean up those connections on the server side. Would you be able to confirm if the server side keepalives would help w/ clients that don't properly close connections?

**Comment by MakMukhi** [comment]
So assuming this is your use-case: 
On the client-side there are unused connections that aren't closed by the user (ClientConn.Close() wasn't called). These connections are therefore healthy but idle. In such a case you could set [max age](https://github.com/grpc/grpc-go/tree/master/keepalive/keepalive.go#L42) parameters on your server to close idle connections after a set time (and more functionalities).

However, if your use-case is such that the connections are unhealthy (broken), however the client never closed them so the server never noticed them going down, keepalive probes will help you there.

**Comment by ewang** [comment]
@MakMukhi In my case, the clients are in python and the connections no longer exist there. They're only lingering on server side.

**Comment by MakMukhi** [comment]
In that case, keepalive probes will help the server realize that and close the connection.
