### ISSUE TITLE
Context as a server option

### ISSUE THREAD

**Issue by Julio-Guerra** [grpc/grpc-go#1282]
There should be a way to provide to the server the context to start from instead of always using `context.Background()` in `grpc.NewServer()`.

Go's documentation clearly states it:
> Background returns a non-nil, empty Context. It is never canceled, has no values, and has no deadline. **It is typically used by the main function, initialization, and tests, and as the top-level Context for incoming requests.**
[Source](https://golang.org/pkg/context/#Background)

For example, my `main()` function derives the background context using `context.WithCancel()` to be able to stop everything when a signal is received. So I should be able to pass this new sub-context to the gRPC server.

**Comment by dfawley** [comment]
"Typically used by" does not mean it _may not_ be used elsewhere.  The `context.Background()` you see in `grpc.NewServer` is just a signal we use internally for one small purpose. `Server`'s `Stop()` and `GracefulStop()` methods are intended to be used to close the connection.  If you need to trigger server close on this other context, you can do the following:

```go
s := grpc.NewServer()
go func() {
  select {
    case <-myctx.Done():
      s./*Graceful*/Stop()
  }
}()
```

**Comment by Julio-Guerra** [comment]
@dfawley Still, the API is inconsistent since we can provide a context to a client call...

I have another relevant example where current implementation fails when simply following common Go principles to further extend another type:

```
type MyContext {
    context.Context
    // plus whatever...
}
```

If we could provide the context ourselves, we would be able to type-assert it to our own types.  Current implementation forces using a global variable instead...

**Comment by MakMukhi** [comment]
The context provided to a call is different (it's on the client side
anyways) than the context used in the server's internal implementation.

**Comment by Julio-Guerra** [comment]
@MakMukhi @dfawley I understood, by reading the code, that stopping the server should cancel contexts provided to handlers (as argument or through stream's `Context()`.

So handlers and sub-goroutines have two ways of knowing they should abort: using `context.Done()` or when `RecvMsg()` `SendMsg()` return an error.

This really should be clearly documented answering the question when is a handler's context or stream's canceled.
