### ISSUE TITLE
Create comprehensive benchmarks

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#1285]
From #1043: Add a collection of benchmarks to measure our performance for different types of workloads under various network conditions (high and low bandwidth and latency). Performance metrics will include throughput, QPS, and tail latency (as well as localized metrics like allocations, syscalls, and CPU usage).

**Comment by dfawley** [comment]
Remaining work: a benchmark that sends messages in an unconstrained fashion (as opposed to ping-pong)

**Comment by MakMukhi** [comment]
#1952 Solves all of this except for options to control network conditions.

**Comment by dfawley** [comment]
Actually, we have the network parameters in there already.  But we're still missing unconstrained-streaming-RPC benchmarks.

**Comment by dfawley** [comment]
This is now implemented in the benchmarks.
