### ISSUE TITLE
Context not passed from client to server

### ISSUE THREAD

**Issue by fengjingchao** [grpc/grpc-go#130]
Hi,

I tried to insert a key-value in the context to client, but didn't get it from server. And I also tried to cancel a context from client, but server didn't get it.

Can you help provide any advice here? Is it gonna be implemented in the future?

**Comment by dsymonds** [comment]
Contexts are not for passing arbitrary bits of data from client to server. That's what the RPC message itself is for. There will probably be a mechanism for attaching bits of data to an RPC via a context (e.g. trace IDs), but it's going to be tightly controlled, and almost definitely not what you want to use.

**Comment by iamqizhao** [comment]
Please use metadata API to transmit your key-value pair. The example is
for unary rpc:
https://github.com/grpc/grpc-go/blob/master/test/end2end_test.go#L355
for streaming rpc:
https://github.com/grpc/grpc-go/blob/master/test/end2end_test.go#L504

Cancellation is propagated to server only when it is needed.

**Comment by harlow** [comment]
> There will probably be a mechanism for attaching bits of data to an RPC via a context (e.g. trace IDs), but it's going to be tightly controlled, and almost definitely not what you want to use.

@dsymonds any idea how far down the line this will be? It would be really nice to have Trace IDs as part of the context. It feels a bit clunky having to wrap all the Protos with `Args/Req/Reply` messages just to pass the Tracer around.

**Comment by iamqizhao** [comment]
On Sat, Apr 11, 2015 at 9:15 AM, Harlow Ward <notifications@github.com>
wrote:

> There will probably be a mechanism for attaching bits of data to an RPC
> via a context (e.g. trace IDs), but it's going to be tightly controlled,
> and almost definitely not what you want to use.
>
> @dsymonds <https://github.com/dsymonds> any idea how far down the line
> this will be? It would be really nice to have Trace IDs as part of the
> context. It feels a bit clunky having to wrap all the Protos with
> Args/Req/Reply messages just to pass the Tracer around.
>
grpc-go does not allow users attach metadata to the context directly (grpc
will ignore that). Users are required to use metadata API to attach the
info (e.g., trace ID) to the context.

**Comment by shurcooL** [comment]
> Please use metadata API to transmit your key-value pair. The example is
> for unary rpc:
> https://github.com/grpc/grpc-go/blob/master/test/end2end_test.go#L355
> for streaming rpc:
> https://github.com/grpc/grpc-go/blob/master/test/end2end_test.go#L504

For anyone looking for that example in the future, the above links won't work because `master` has since changed and the line numbers don't match up. Here are the correct links:

For unary rpc:

https://github.com/grpc/grpc-go/blob/51496073b86104a21479f1b0c09337ab76f0f883/test/end2end_test.go#L355

For streaming rpc:

https://github.com/grpc/grpc-go/blob/51496073b86104a21479f1b0c09337ab76f0f883/test/end2end_test.go#L504

Tip: You can press `y` when looking at a file to get a permalink:

![image](https://cloud.githubusercontent.com/assets/1924134/7310718/ad34b35a-e9e5-11e4-90d6-cf3cb69bb815.png)

**Comment by dramdass** [comment]
Is there a way to set the metadata from the generated protobuf client code?

**Comment by iamqizhao** [comment]
Can you take a look at the examples in my very first reply on this issue on
how to set and receive metadata and see whether it answers your question?

Copied/pasted for your convenience:

*Please use metadata API to transmit your key-value pair. The example is*
*for unary rpc: *

*https://github.com/grpc/grpc-go/blob/master/test/end2end_test.go#L355
<https://github.com/grpc/grpc-go/blob/master/test/end2end_test.go#L355>*
*for streaming rpc:*

*https://github.com/grpc/grpc-go/blob/master/test/end2end_test.go#L504
<https://github.com/grpc/grpc-go/blob/master/test/end2end_test.go#L504>*

**Comment by harlow** [comment]
Here is a commit for anyone interested in using the `metadata`. Works nicely for things such as `traceID`:
https://github.com/harlow/go-micro-services/commit/221a67bca4309aa12b69cd57ca6c1e9522c09cfc

**Comment by iamqizhao** [comment]
Thanks, Harlow!

**Comment by pires** [comment]
@harlow you rock! Thank you.

**Comment by WIZARD-CXY** [comment]
@harlow just what I need! Tnank you!
