### ISSUE TITLE
LICENSE file doesn't contain the proper text from ASLv2

### ISSUE THREAD

**Issue by tsuna** [grpc/grpc-go#1309]
As I noted on commit 3c7e64ff7fec932311650d00c631c2edf7c2551b, the `LICENSE` file was recently updated from 3-clause BSD to ASLv2 but for some reason the text of the license wasn't directly copied from http://www.apache.org/licenses/LICENSE-2.0.txt (seems like it's missing a line).

This is making some automated license checks fail in our internal system, so we can't vendor/distribute newer versions of gRPC with our products.

**Comment by menghanl** [comment]
@jtattermusch can you take a look at this?
I can make the change if you think it's appropriate.
