### ISSUE TITLE
Single *ClientConn backed by multiple *addrConn per Server

### ISSUE THREAD

**Issue by Zeymo** [grpc/grpc-go#1315]
Under high-concurrency or high-qps-benchmark situation (as gateway-proxy), single `*ClientConn `backed by single `*addrConn` per Server will limitation num of HTTP2 Max-Stream immediately(e.g. 1000 ) , we need more `*addrConn` to one server enhance throughput and performance

In anthor way , In previous stress test under spdy protocol ,  **8 TCP-Connection + 100 Max-stream** has best performce in 4core+8G kvm server . **1000 Max-Stream** cause more extra-competition

Is any plan to support this scenario (also refer to _loadBalance_)？

In addition , new `*ClientConn` is expensive ? 
 1 * `*ClientConn` -> connPerServer * `* addrConn`  with 1 lb  or `[]*ClientConn`  with each own lb , which will be satisfied ?

**Comment by menghanl** [comment]
We don't have a gRPC option for creating multiple connection to the same server, but the same functionality is supported by [balancer](https://github.com/grpc/grpc-go/blob/master/balancer.go#L65).

Balancer returns a list of addresses to gRPC via [Notify()](https://github.com/grpc/grpc-go/blob/master/balancer.go#L110), each address is a `string` +  [`metadata`](https://github.com/grpc/grpc-go/blob/master/balancer.go#L40).
gRPC creates a connection for each different Address struct returned. If the addresses contain the same server address but different metadata, gRPC will create multiple connections to the same server.
Load balancing between these connection is done by the same Balancer.

About the overhead of `ClientConn`.
Each `ClientConn` maintains it's own connection pool, and some goroutines for balancers. There's some overhead, but the overhead is quite small.
For the situation you are interested in, maintaining your own pool of `ClientConn`s would work, too. But then you need to do load balancing between multiple `ClientConn`s.

I would suggest take a look at the `Balancer` APIs, and see if it satisfies your requirements.

**Comment by Zeymo** [comment]
Thx for your time
