### ISSUE TITLE
status: expose error details

### ISSUE THREAD

**Issue by pongad** [grpc/grpc-go#1324]
### What version of gRPC are you using?
1.5.0-dev

### What version of Go are you using (`go version`)?
1.8

### What operating system (Linux, Windows, …) and version?
Linux 14.04

### What did you see instead?
[rpc/status.Status](http://godoc.org/google.golang.org/genproto/googleapis/rpc/status#Status) contains the `Details []Any` field. There is currently no short way to unwrap these details. Client libraries can help by providing a convenience function like
```go
Details(grpc_status.Status) []proto.Message
```
but we think it's better for this functionality to be centrally implemented here instead.
Please also see [this issue](https://github.com/googleapis/toolkit/issues/1357).

I'll be happy to implement this if you guys are busy.

**Comment by dfawley** [comment]
This looks like #1233 to me.  Please see the discussion and proposal there and chime in if you'd like to take over the implementation from @ghasemloo or if you have other input.  Thanks!
