### ISSUE TITLE
easy way to valid input params

### ISSUE THREAD

**Issue by jinleileiking** [grpc/grpc-go#1328]
grpc will auto gen the struct:

```
-    80 type HelloReply struct {¬
|    81 ▸   Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`¬
|    82 }¬
     83 ¬
```

proto3 have no require, and regex check.

Can we use add some struct tag for check?

For example, use https://github.com/go-playground/validator to check.

**Comment by dfawley** [comment]
Can you explain more specifically what you are looking for?  I'm not sure I'm understanding exactly.

I'm not as familiar with proto3 yet, but in proto2, it was possible to use tags in brackets on the fields in the proto and create a custom plug-in to generate your pb.go files with additional checks like I believe you are asking for.

Also, if this request isn't specifically about the service stubs being generated for grpc, then this would not fall under grpc's control.  It would be up to https://github.com/golang/protobuf to assess your request and implement.

**Comment by jinleileiking** [comment]
Yes. I found middleware to solve this. Thanks for the patient reply.

**Comment by zxy198717** [comment]
Hi @jinleileiking , which middleware you found? could you share it?
