### ISSUE TITLE
Dial WithTimeout prevents client from reconnecting

### ISSUE THREAD

**Issue by maxhawkins** [grpc/grpc-go#133]
Setting the grpc.WithTimeout option in grpc.Dial causes all RPCs to fail with the error ```"grpc: the client connection is closing"``` after a server restart.

Steps to reproduce:

1. Create a client with a connection timeout:
    
    ```go
    conn, err := grpc.Dial(address, grpc.WithTimeout(timeout))
    ```
2. Make an RPC call. It succeeds.
3. Shut down the server
4. Make an RPC call with a deadline. As expected, it cannot connect and fails:
    ```'rpc error: code = 4 desc = "context deadline exceeded"'```
5. Start up the server
6. Make another RPC call. I expect this to work. Instead, it and each subsequent RPC fails with
    ```'rpc error: code = 2 desc = "grpc: the client connection is closing"'```

**Comment by iamqizhao** [comment]
On Mon, Mar 23, 2015 at 5:07 PM, Max Hawkins <notifications@github.com>
wrote:

> Setting the grpc.WithTimeout option in grpc.Dial causes all RPCs to fail
> with the error "grpc: the client connection is closing" after a server
> restart.
>
> Steps to reproduce:
>
>    1.
>
>    Create a client with a connection timeout:
>
>    conn, err := grpc.Dial(address, grpc.WithTimeout(timeout))
>
>     2. Make an RPC call. It succeeds.
>    3. Shut down the server
>    4. Make an RPC call with a deadline. As expected, it cannot connect
>    and fails: 'rpc error: code = 4 desc = "context deadline exceeded"'
>    5. Start up the server
>    6. Make another RPC call. I expect this to work. Instead, it and each
>    subsequent RPC fails with 'rpc error: code = 2 desc = "grpc: the
>    client connection is closing"'
>
> This is the expected behavior. Use Dial timeout only when you needed. If
you use it,  make sure it is long enough to accommodate the use case that
you do not want to fail.

**Comment by maxhawkins** [comment]
Ah, I see. I assumed this only applied to the initial connection. I suppose this makes sense.

I'll close this issue. Thanks!

**Comment by shafreeck** [comment]
Now I know `grpc.WithTimeout(timeout)` controls the timeout of grpc.Dail including the time cost of retries. Sometimes in fact I want to set the timeout of tcp connect which avoid blocking the goroutine and I'd like it to retry many times.
