### ISSUE TITLE
Registering two servers on the same port

### ISSUE THREAD

**Issue by RajeshKumar1990** [grpc/grpc-go#1332]
I am new to grpc.So please bear if anything wrong in my question

I have a project where i use grpc.I have two proto files and these two proto files creates  two different .pb file.for example 
```
proto1 have EmpGuildServer and EmpGuildClient
proto2 have DataServer and DataClient
```

On my server end can i use like this 
```
type server struct{}
type server1 struct{}
 
func main() {

	lis, err := net.Listen("tcp", ":50055")
	if err != nil {
		log.Fatal("Error in the listen", err)
	}
	s := grpc.NewServer()

	rpcdata.RegisterEmpGuideServer(s, &server{})
	filedata.RegisterDataServer(s, &server1{})
	reflection.Register(s)
	if err := s.Serve(lis); err != nil {
		log.Fatal("fail to server", err)
	}
}
```
Here i am registering two different server in one port so i can access all the functions of these two servers on the  same port.If i do like this will there be any problem in the future.
If its wrong implementation then can anyone suggest best way to do this.
Thanks

**Comment by overvenus** [comment]
Hi,

How about registering two different services on the same server?

Just like https://github.com/coreos/etcd/blob/1df8b90d675d2b731305337f34dac211ff6fb5e7/etcdserver/api/v3rpc/grpc.go#L36

**Comment by dfawley** [comment]
Yes, what you have above is the normal/recommended way of doing this.  If you run into problems with that, feel free to comment here.  Thanks!
