### ISSUE TITLE
Creating stream to non-existent endpoint does not return an error

### ISSUE THREAD

**Issue by apoydence** [grpc/grpc-go#1335]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.4.2

### What version of Go are you using (`go version`)?
go version 1.7.4

### What operating system (Linux, Windows, …) and version?
OS X 10.11.16

### What did you do?
If possible, provide a recipe for reproducing the error.
1. Build `route_guide` client
2. Update `RecordRoute` to `RecordRoute2` in `route_guide.proto` and `server.go`
3. `go run server.go`
4. Error returned from `stream.Send(point)` instead of `client.RecordRoute(context.Background())`

### What did you expect to see?
While I still see an error, it seems late (have to send data). Would it be infeasible to have the stream creation return an error?

### What did you see instead?
Creating stream returns an error.

**Comment by dfawley** [comment]
The server does not send an 'ack' back to the client at the start of a streaming RPC, so it is not possible to block and determine whether the server sent back an error at that time.  It is the user's responsibility to call Recv to receive the error.  Without significant changes to the API, I'm afraid there isn't anything we can do here.

This has recently been documented in the ClientStream interface [here](https://godoc.org/google.golang.org/grpc#ClientStream), and we plan to improve our documentation on github in the next quarter or so.

Thanks!
