### ISSUE TITLE
stream.Recv() on server side in bidirectional method locks forever on server.GracefulStop()

### ISSUE THREAD

**Issue by DenKoren** [grpc/grpc-go#1355]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
I can't find gRPC version number anywhere in code, so I try to identify it the only way I found:
it is gRPC implementation for GO with latest commit hash _a8cd0c13a447ed2fdbad93a9afbf7f4302d386ab_

### What version of Go are you using (`go version`)?
go version go1.8.1 darwin/amd64

### What operating system (Linux, Windows, …) and version?
Mac OS X

### What did you do?
When you have a bidirectional streaming gRPC function on server side:
```golang
func (api *API) StreamingMethod(stream pb.SampleService_StreamingMethodServer) error {
```

you usually do something like this inside the function:
```golang
in, err := stream.Recv()
if err == io.EOF {
	return
}
<do some staff with "in" message>
```

The problem is in `stream.Recv()`. It blocks till one of two events: client disconnects from gRPC server or client sends you a message.

If we create and start gRPC server in the following way:
```golang
	lis, err := net.Listen("tcp", "localhost:4444")
	if err != nil {
		log.Fatalln("Can't start gRPC server:", err)
	}

	server := grpc.NewServer()

	pb.RegisterSampleServiceServer(server, api)
	err := server.Serve(lis)
        // ... checks and other staff
```

Then if we connect a stub "echo" client to bidirectional streaming method described above (which reads data from server and just sends it back) and run
```golang
server.GracefulStop()
```
from any other place, the client connected to gRPC will be disconnected, the socket will be closed (`server.Serve(lis)` will return) but the `stream.Recv()` will stay waiting for data.

### What did you expect to see?
I expected `stream.Recv()` of my example to return `err == EOF` after `server.GracefulStop()` call

### What did you see instead?
`stream.Recv()` locks forever until I make forced stop (call `server.Stop()`) or close the application.

I hope my description of the problem is clear but if not - I can create simple reproduce-case code and put it into public github repository.

**Comment by menghanl** [comment]
The purpose of `GracefulStop`, as described in the [godoc](https://godoc.org/google.golang.org/grpc#Server.GracefulStop), is to stop the server from accepting new RPCs, but keep working on the pending RPCs.

In your case, the streaming RPC is a pending RPC, and the server will not try to close. The behavior you saw is expected.

If you want the stop all RPCs, why not call `Stop` instead?
