### ISSUE TITLE
Let Middleware(interceptor) use only in some custom rpc or service

### ISSUE THREAD

**Issue by jinleileiking** [grpc/grpc-go#1371]

**Comment by menghanl** [comment]
Can you provide more details? What you expect to see? And some examples would also be good.

**Comment by dfawley** [comment]
Without further clarification on this, it sounds like you want to have your interceptor only be called for certain services/methods.  The method name is passed to the interceptor, so your interceptor could match on that to control its behavior.

E.g. https://godoc.org/google.golang.org/grpc#UnaryClientInterceptor

**Comment by jinleileiking** [comment]
sorry for the late response. At the server side, I want some rpc use some interceptor, some not

**Comment by dfawley** [comment]
Server-side, the [interceptor](https://godoc.org/google.golang.org/grpc#UnaryServerInterceptor) receives a [`UnaryServerInfo`](https://godoc.org/google.golang.org/grpc#UnaryServerInfo) that contains the method name, so you could match on that to control interceptor behavior.

**Comment by jinleileiking** [comment]
@dfawley Thanks a lot 👍
