### ISSUE TITLE
Serve() returns before GracefulStop()

### ISSUE THREAD

**Issue by dgpc** [grpc/grpc-go#1372]
### What version of gRPC are you using?
eddbd11c7ecd001d06777cb87b5ea7af54227907

### What version of Go are you using (`go version`)?
go1.8

### What operating system (Linux, Windows, …) and version?
Linux, Ubuntu 14.04 LTS.

### What did you do?

Called `GracefulStop()` on a `grpc.Server`.

### What did you expect to see?

Expect `Serve()` to not return until `GracefulStop()` has finished serving the last request, probably with the `ErrServerStopped` error.

### What did you see instead?

`Serve()` returns immediately when you call `GracefulStop()`, returning the error `accept tcp 127.0.0.1:8888: use of closed network connection`

This causes problems for what I believe is a fairly common application pattern for clean shutdown:

    func main() {
      s := grpc.NewServer()
      ...
      
      go func() {
        sigs := make(chan os.Signal, 1)
        signal.Notify(sigs, syscall.SIGTERM, syscall.SIGINT)
        _ = <-sigs
        s.GracefulStop()
      }()

      lis, err := net.Listen(...)
      ...
      if err := s.Serve(lis); err != grpc.ErrServerStopped {
        log.Fatalf("unclean shutdown: %v", err)
      }
    }

If you do this, as soon as `SIGTERM` is received, `Serve` will return an error, and the application will exit without allowing in-flight RPCs to drain.

I am working around this by waiting for `GracefulStop()` to return in the `main()` goroutine, and ignoring the error from `Serve()` in this case.

**Comment by gjnoonan** [comment]
Can this issue be closed now? I believe it was fixed in #1485

**Comment by dfawley** [comment]
Yes, thanks!
