### ISSUE TITLE
add a function to status to facilitate checking the code of an error

### ISSUE THREAD

**Issue by ghasemloo** [grpc/grpc-go#1378]
Often one wants to check the code of a status error. It would nice to have functions like the following so one doesn't need to convert to state and then check the code in two steps:

```go
// Is checks the error code of a status error.
func Is(err error, code codes.Code) bool {
	if s, ok := status.FromError(err); ok {
		return s.Code() == code
	}
	return false
}
```

Then we can have simple error handling like:

```go
resp, err := client.RPC(ctx, req)
if status.Is(err, codes.NotFound) {
	...
}
```

Or if we want to support multiple codes at once:
```go
// Is checks the error code of a status error.
func Is(err error, c ...codes.Code) bool {
	s, ok := status.FromError(err)
	if !ok {
		return false
	}
	for _, code := range c {
		if s.Code() == code {
			return true
		}
	}
	return false
}
```

Another alternative is to have a ErrorCode function so we can do a switch on it:

```go
// ErrorCode returns the error code of a status error. 
// Returns codes.Unknown if the error is not a status error.
func ErrorCode(err error) codes.Code {
	if s, ok := status.FromError(err); ok {
		return s.Code()
	}
	return codes.Unknown
}
```

Then we can have:

```go
resp, err := client.RPC(ctx, req)
switch ErrorCode(err) {
case codes.NotFound:
	...
case codes.InvalidArgument:
	...
}
```

**Comment by dfawley** [comment]
`grpc.Code(error)` implements the last example, but is marked as deprecated.

I am thinking that `status.FromError(<non-status error>)` could reasonably return a non-nil status containing `{Code: codes.Unknown, Msg: err.Error()}` and false.  If it did, it would be sensible to do a switch on `status.FromError(err).Code()`.  Essentially, `FromError` would be a general error-conversion function, with the boolean indicating whether the provided error was already a status or if the returned status was fabricated.

Right now, `status.FromError(err)` returns a status that represents a *success* if err is a non-status error, which could be misused and cause problems.

**Comment by ghasemloo** [comment]
That is fine with me, however wouldn't that be a breaking change?

ps: we have something similar to "Is" internally, that's where the idea for it came from.

**Comment by dfawley** [comment]
It is a behavior change, but if anyone is relying upon `status.FromError(<non-nil, non-status error>) == nil` (when it also returns `, false`), they're probably doing _something_ wrong (mostly because `(*status.Status)(nil).Code() == OK`, which is in conflict with the non-nil error provided)...so I think this should be safe and probably even desirable.

**Comment by ghasemloo** [comment]
sgtm then. :)

I think having an `Is` is also useful in addition for cases like:
```go
if _, err := client.RPC(ctx, req); status.Is(err, codes.NotFound) {
	...
}
```
without `Is` I think the if would need to be in two lines in place of one with an temp variable just to pass the status object between the two lines (cause `status.FromError` returns two values, that is generally the issue with returning two values in go :). So I think there is value in having `Is` as well, it leads to cleaner and shorter code.

**Comment by dfawley** [comment]
> (because status.FromError returns two values, that is generally the issue with returning two values in go :).

I somehow keep overlooking this.  I'm now really wishing this general-purpose conversion function wasn't a ", ok".

How about this?

```go
// Convert returns a Status representing err.  If err was not produced by this package,
// it returns a Status with an Unknown code and a message of err.Error().
func status.Convert(err error) *Status {
  s, _ := FromError(err)
  return s
}
```

This would have more utility than `Is` (which also doesn't feel very Go-idiomatic to me).

**Comment by ghasemloo** [comment]
SGTM. :)
