### ISSUE TITLE
Error type *http2.Framer has no field or method SetReuseFrames

### ISSUE THREAD

**Issue by iordaniordanov** [grpc/grpc-go#1379]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
HEAD
### What version of Go are you using (`go version`)?
go version go1.8.3 linux/amd64
### What operating system (Linux, Windows, …) and version?
Linux 14.04.1-Ubuntu
### What did you do?
Tried installing github.com/coreos/etcd/clientv3
### What did you expect to see?
Success 
### What did you see instead?
goprojects/src/google.golang.org/grpc/transport/http_util.go:465: f.fr.SetReuseFrames undefined (type *http2.Framer has no field or method SetReuseFrames)

**Comment by iordaniordanov** [comment]
It seems that the problem was introduced in [This commit](https://github.com/grpc/grpc-go/commit/ff17eeb5f6e2112ef30f103d686fa725ee31202e)

**Comment by nussjustin** [comment]
Try to update your copy of golang.org/x/net/http2. SetReuseFrames was only added recently and you may have an older version. Just execute `go get -u golang.org/x/net/http2` and then everything should work again.

The commit that added SetReuseFrames: https://github.com/golang/net/commit/bb807669a61aca6092d8137da1fab2150bb96ad7

**Comment by iordaniordanov** [comment]
Thanks. Any help with that?
```
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>

package golang.org/x/text/secure/bidirule: exit status 1


```

**Comment by nussjustin** [comment]
Your golang.org/x/text is not on a branch. Just do a "git checkout master" inside your $GOPATH/src/golang.org/x/text and then run go get again. Or just delete $GOPATH/src/golang.org/x/text and run go get again.

**Comment by iordaniordanov** [comment]
Ahh, thanks a lot problem is fixed. Closing the issue :)
