### ISSUE TITLE
unnecessary allocations in attaching metadata to RPCs

### ISSUE THREAD

**Issue by chensunny** [grpc/grpc-go#1390]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.4.1
### What version of Go are you using (`go version`)?
1.7
### What operating system (Linux, Windows, …) and version?
lNAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7

Linux version 3.10.0-327.el7.x86_64 (mockbuild@sl7-uefisign.fnal.gov) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) ) #1 SMP Fri Nov 20 11:12:42 CST 2015
### What did you do?
If possible, provide a recipe for reproducing the error.

 i run benchmark use example  pb in gRPC-go.

      req := &pb.HelloRequest{Name: "sunny"}
      ctx, cancel := context.WithTimeout(context.Background(), time.Second*3)
      defer cancel()
      md, _ := metadata.FromOutgoingContext(ctx)
      send := make(map[string]string)
      send["key1"] = "value1"
      send["key2"] = "value2"
      send["key3"] = "value3"
      send["key4"] = "value4"
      send["key5"] = "value5"
      send["key6"] = "value6"
      send["key7"] = "value7"
      send["key8"] = "value8"
      ctx = metadata.NewContext(ctx, metadata.Join(metadata.New(send), md))
      if _, err := r.cli.SayHello(ctx, req); err != nil {
          return err
      }
      return nil
### What did you expect to see?

before  add metadata ,my benchmark case can run 112378/s .
 i expect  it was  reduce throughput less than 5%.

### What did you see instead?
my case just run 85088/s。

**Comment by chensunny** [comment]
through Flame Graph , 

CPU was consumed on the function 'metadata.Join' and 'metadata.New'

**Comment by dfawley** [comment]
I'm playing around with an API change that would improve performance of this.  The idea is to make a CallOption for metadata, so adding extra metadata is as easy as injecting an extra call option.
