### ISSUE TITLE
Graceful close client by third-part (e.g. discovery console) without  handle GO_AWAY

### ISSUE THREAD

**Issue by Zeymo** [grpc/grpc-go#1399]
third-part (e.g. discovery console) sometime will offline some addrs for purpose (not actually shutdwon server) ,then 

1.  receive and delete addr from `[]conns` and `tearDown` with `err == errConnDrain`
2. `err == errConnDrain && ac.transport != nil` so invoke `ac.transport.GracefulClose()`
3. have no `<-t.GO_AWAY `and mostly **`len(activeStreams) != 0`**
4. `ac.transport != nil && err != errConnDrain` is `false` so not invoke `t.close()`
5. transportMonitor trigger `<-ac.ctx.Done()` and `<-Error()` is not return

https://github.com/grpc/grpc-go/blob/master/clientconn.go#L1149

In the end ac.transport  not close and leaked

so ,any suggestion for this ?  maybe provide high_level api to close(goaway) ?

**Comment by menghanl** [comment]
It seems what you want is to tearDown some connections on the client side, is that right?
If yes, balancers could do what you want. Just send a list of addresses without the server address you want to gRPC through (`Notify()`)[https://github.com/grpc/grpc-go/blob/master/balancer.go#L110], gRPC will graceful close this transport (in (`lbWatcher()`)[https://github.com/grpc/grpc-go/blob/master/clientconn.go#L613]).

Note that, we are working on changing the balancer API in gRPC, and `Notify()` will be deprecated. The new balancer work is tracked in #1388.

**Comment by Zeymo** [comment]
@menghanl Thx to reply. I already do what you say above (notify lbWatcher new addrs list without certain addr) but it will not graceful shut down. if i wrong  ,correct me

because in `tearDown(err error)`[https://github.com/grpc/grpc-go/blob/master/clientconn.go#L1145]  ac.transport.GracefulClose() will success only when receive `goAway`  before fix #1393 

```
switch t.state {
	case unreachable:
		t.mu.Unlock()
		t.Close()
		return nil
	case closing:
		t.mu.Unlock()
		return nil
	}
	select {
	case <-t.goAway:
		n := t.prevGoAwayID
		if n == 0 && t.nextID > 1 {
			n = t.nextID - 2
		}
		m := t.goAwayID + 2
		if m == 2 {
			m = 1
		}
		for i := m; i <= n; i += 2 {
			if s, ok := t.activeStreams[i]; ok {
				close(s.goAway)
			}
		}
	default:
	}
        
        if t.state == draining {
		t.mu.Unlock()
		return nil
	}
	t.state = draining
	active := len(t.activeStreams)
	t.mu.Unlock()
	if active == 0 {
		return t.Close()
	}

```
 this server is serving so len(t.activeStreams) != 0  in **`func (t *http2Client) GracefulClose() error`**

and don't close at all cos' err == errConnDrain in
https://github.com/grpc/grpc-go/blob/master/clientconn.go#L1176

**Comment by menghanl** [comment]
The connections are gracefully stopped. They will kept open until existing RPCs on it all finish.
Do you have a long live streaming on the connection?

There's currently no way to force close a particular addrConn on the client side. Do you have a situation where you want the connection to the server to abort immediately? What are you expectations for the existing RPCs to this server?

**Comment by Zeymo** [comment]
sry for my carelessness  : P
```
if t.state == draining && len(t.activeStreams) == 0 {
		defer t.Close()
}
```
