### ISSUE TITLE
Incompatibility between V >1.5 client and V 1.3 to V 1.4 Server

### ISSUE THREAD

**Issue by MakMukhi** [grpc/grpc-go#1401]
This issue is meant to inform users about this incompatibility.

What happened:
Keepalive policy enforcement by server was introduced in V 1.3. This had a bug; it was too restrictive against pings. The pingStrikes counter was reset only once for a message being sent even if the message spawned multiple frames. The correct behavior is to reset the counter for every frame being written.
This bug would prevent BDP estimation by gRPC clients since their BDP probing pings would violate this overly restrictive policy. This would result in server sending out GoAway frames with EnhanceYourCalm error  and debug data of "too_many_pings". 
The bug was first noted during our BDP estimation implementation. Later, it was also found to have affected users. #1348: A Python client was getting these errors while talking to the gRPC server.

The incompatibility arises from the fact that BDP estimation is turned on by default. Note, that it can be turned off by manually setting window sizes.

So, if someone is facing the same problem they can get rid of it by updating the server(recommended way) or by setting manual window size values.

Sorry about the inconvenience.

**Comment by ppg** [comment]
@MakMukhi Just to clarify the issue is with a c-core client >= 1.5 and a golang server >= 1.3 and < 1.5 right? Would it also affect a c-core server >= 1.5 and golang client >= 1.3 and < 1.5? Either way it sounds like the safest path is upgrade all golang servers/clients to >= 1.5 first; then upgrades to c-core based clients/servers should be safe?

**Comment by MakMukhi** [comment]
The issue here is about incompatibility between different golang versions.
A golang server between 1.3 and 1.4 (inclusive) is incompatible with any client that tries to do BDP estimation. Now c-core included BDP estimation a while back (unsure which version) and we introduced it in v 1.5. I suppose the bug went unnoticed for this long  because there weren't many cases of golang server talking to a c-core client, yet.
You are right that the safest bet is to update the golang server.
