### ISSUE TITLE
Proposal: Support for non-standard error detail messages

### ISSUE THREAD

**Issue by ewang** [grpc/grpc-go#1405]
Currently there is support for returning rich error status details by means of the google.rpc.Status message. This is transmitted via the `grpc-status-details-bin` metadata field.

Any chance we can extend the above mechanism to support custom status message types? The `google.rpc.Status` message type doesn't not work well in certain cases, e.g. when we need to add new top level fields or change the data type of the details field.

I'm proposing supporting an additional metadata field `grpc-status-details-bin-type` which would contain the full name of the protobuf message to be used for serializing/de-serializing the contents of `grpc-status-details-bin`. For backwards compatibility, this field will default to `google.rpc.Status`.

As an aside, there are various GRPC-JSON transcoding projects (CloudEndpoints ESP, Envoy, etc) that are considering adding rich error support. One of the methods currently being explored is by using the `grpc-status-details-bin` field. If we have support for custom status message types, it would give the transcoding side the ability to support non-standard error messages, which would allow us to migrate legacy APIs to a gRPC backend while still providing a JSON interface via transcoding.

**Comment by dfawley** [comment]
The details field in the Status proto is a "repeated Any", which can hold any arbitrary serialized data you would like, and includes a string field to specify its type.

https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Any

I believe this should satisfy your requirements for custom data types.  If not, could you please explain why?  Thanks!

**Comment by ewang** [comment]
@dfawley This affects users of the GRPC-JSON transcoding part more, since if we use google.protobuf.Any, when serialized to JSON, it adds additional @type annotations of the full type name, which in my opinion is leaking unnecessary details. It also prevents us from replacing legacy APIs using grpc-go+transcoding since we won't be able to come up with a message type that mirrors existing JSON errors.

I guess this could exist as a separate filter for Envoy, but it seemed like a better idea to keep the errors contained within the gRPC server code and having the transcoders simply serialize to JSON using jsonpb.

**Comment by dfawley** [comment]
If you control the clients and servers, you can put literally any data in the details field you wish -- including raw JSON error strings directly -- and/or, you can serialize/deserialize them by any means you choose.

If that still doesn't meet your needs, you can also define your own custom trailer fields for your specific detailed error data and types.

Adding a feature like this would require a gRPC spec change and cross-language support, which would first require a gRFC to be submitted and accepted.  If you feel strongly about this, feel free to send your proposal to the [grpc.io forum](https://groups.google.com/forum/#!forum/grpc-io) for discussion.
