### ISSUE TITLE
Peer details not populated when requests fail

### ISSUE THREAD

**Issue by therc** [grpc/grpc-go#1417]
### What version of gRPC are you using?
1.5.1
### What version of Go are you using (`go version`)?
1.8.4
### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
Add a Peer() call option to a call, then send a request that fails somehow (e.g. bad request).

### What did you expect to see?
The peer information is populated
### What did you see instead?
The peer information is not populated. It seems to work only if the call succeeds.

We looked at this a bit and it seems like the issue is that Peer() is implemented as a deferred "after" function. invoke() will call sendRequest() and, if an error occurs, it will return. The Peer() code will still run, because it was deferred, but the peer details haven't been filled in yet, so the function will just copy a nil value.  The callInfo.peer field is only set at the end of recvResponse(), which never gets invoked when a request fails.

Would it be OK to send a PR that sets the peer in sendRequest() instead? Or maybe in both if e.g. AuthInfo can change between the end of sendRequest and recvResponse.

@MakMukhi @jack0

**Comment by MakMukhi** [comment]
Yes go ahead; the peer is set in a stream's context when it's created so setting it somewhere [here]( https://github.com/grpc/grpc-go/blob/master/call.go#L264) should do the trick.

**Comment by therc** [comment]
This should be fixed now in HEAD, only waiting for release. Closing.

**Comment by menghanl** [comment]
@therc This was released in v1.5.2.

**Comment by therc** [comment]
@menghanl We just saw that, thanks!
