### ISSUE TITLE
Question about the format of `PerRPCCredential.GetRequestMetadata()`'s parameter

### ISSUE THREAD

**Issue by mitake** [grpc/grpc-go#1435]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.5.1

### What version of Go are you using (`go version`)?
1.8.1

### What operating system (Linux, Windows, …) and version?
linux

### What did you do?
I checked `PerRPCCredential.GetRequestMetadata()`'s second parameter, `uri`.

### What did you expect to see?
I expected that the `uri` is something like this`https://<host>:<port>/<method>`.

### What did you see instead?
I saw `https://<host>:<port1>:<port2>/<method>`.

### question
My question: is the above format that contains 2 port numbers intentional? I expected that the URI is information of the target: host, port and method . It is a little bit strange and according to the URI construction code (https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L351), it is constructed like this: `audience = "https://" + callHdr.Host + port + callHdr.Method[:pos]`. And `callHdr.Host` contains its own port number that comes from here: https://github.com/grpc/grpc-go/blob/master/clientconn.go#L378 .

**Comment by dfawley** [comment]
This is a bug.  See PR #1433 for a possible fix.  However, we still aren't completely sure if using the port from the host is correct, or if we should use the target's port instead (which is what the code was attempting to do before).

**Comment by mitake** [comment]
@dfawley thanks for the pointer and I'm glad to see the problem was fixed. Will the format of the parameter be changed in the future?

**Comment by dfawley** [comment]
There are no plans to change this beyond what #1433 did.  Please comment here if you think there's any issues using it as implemented.  Otherwise, I'll close this, as the PR has been merged.  Thanks.

**Comment by mitake** [comment]
@dfawley thanks for the answer. And I don't have problems for now. Will #1433 be backported to 1.5.x?

**Comment by dfawley** [comment]
We will not be backporting it unless there is an urgent need.   We will be doing the 1.6 release next Wednesday.

**Comment by mitake** [comment]
I understand. Thanks a lot for your help!
