### ISSUE TITLE
Question regarding prevention of client abuse

### ISSUE THREAD

**Issue by SuhasAnand** [grpc/grpc-go#1442]
I am new to go-gRPC. So please pardon my ignorance if this is not the right place to ask questions and let me know where I could ask questions in future regarding go-grpc. 

I am looking for pointers to any existing mechanisms to prevent rouge client abuse in go-grpc. 
To keep it simple, For example, if I have a gRPC server which has a single rpc called SendData() which streams Data. 

Now I want to restrict invocation of SendData() to once per client only.  I.e. only one active stream per client. Is there way to enforce this ?

**Comment by MakMukhi** [comment]
There's a server option to limit the number of streams that a client can
open on a connection MaxConcurrentStreams.

**Comment by SuhasAnand** [comment]
@MakMukhi : Thanks for your reply and sorry for not being clear:
How about if I have a gRPC server which has a two (or more) rpc called SendABC() and SendXYZ() both of which are server side stream. From what I understand MaxConcurrentStreams (lets say for this example I set it to 2)  will not restrict client to have single invocation of SendABC() and SendXYZ() right ? since MaxConcurrentStreams is 2 in this example there could be two streams of SendABC() or two streams of SendXYZ(). is there a way to limit at max one stream per rpc per client ?

**Comment by dfawley** [comment]
Probably the best way to do this kind of check would be to implement this yourself in either your server handler or an interceptor.  Note that there could be races where the client disconnects and attempts to reconnect before the server notices the client has disconnected.  This would result in the client's reconnect being rejected until the server notices the first connection has been lost.  Note also that this will only limit one client per server, so if you have multiple instances of this server, the same client could connect to all of them and initiate a SendABC and SendXYZ on each one.
