### ISSUE TITLE
Setting proxy parameters is not flexible enough

### ISSUE THREAD

**Issue by shevchenkodenis** [grpc/grpc-go#1446]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
bfaf0423469fc4f95e9eac7e3eec0b2abb46fcca

### What version of Go are you using (`go version`)?
go version go1.8.3 linux/amd64

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
There are multiple grpc connections in my project at one time. One of them need proxy, another not. Proxy require credentials.

### What did you see?
Currently, grpc-go takes proxy settings from ENV only once at the start of binary. In addition, it is a little bit buggy. It takes only host and ignores credentials.

### What did you expect to see?
I want 
* use credentials with proxy
* possibility to change proxy in runtime. Since grpc-go takes it only once from env, so it will be enough to add optional parameter ProxyURL. If it is not exist, then use value from ENV

**Comment by EdSchouten** [comment]
It would have made sense if there was a `grpc.WithProxy()` or something that took a callback that has the same signature as `http.ProxyFromEnvironment` and `http.ProxyURL`. For a project of mine ([bb-storage](https://github.com/buildbarn/bb-storage)) it's a bit wacky that all of the gRPC settings are done through a config file, except for the proxy. That can only be configured through an environment variable.

**Comment by dfawley** [comment]
For more complex dialing protocols that don't work with our built-in proxy support, we would recommend using the [WithContextDialer](https://pkg.go.dev/google.golang.org/grpc#WithContextDialer) dial option.
