### ISSUE TITLE
Consumer can`t get address by peer while timeout

### ISSUE THREAD

**Issue by chensunny** [grpc/grpc-go#1450]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.5.0
### What version of Go are you using (`go version`)?
1.8.3
### What operating system (Linux, Windows, …) and version?
macOS 10.12.5
### What did you do?
If possible, provide a recipe for reproducing the error.

### What did you expect to see?
i want to get the provider address through peer
  
    var server peer.Peer
    err := invoker(ctx, method, req, reply, cc, opts...)
    if server.Addr != net.Addr(nil) {
            aclog.ProviderAddress = server.Addr.String()
     }

  
### What did you see instead?
but when timeout  i find that peer will return nil. which provider can get consumer address by peer

**Comment by MakMukhi** [comment]
A timeout on an RPC may occur even before an underlying transport is selected to send the RPC on. In other words the operation timed-out before we could get to know about a peer and therefore there's no peer info to be returned.
