### ISSUE TITLE
no buildable Go source files for grpclb

### ISSUE THREAD

**Issue by chy168** [grpc/grpc-go#1452]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
master

### What version of Go are you using (`go version`)?
```go version go1.7.4 darwin/amd64```

### What operating system (Linux, Windows, …) and version?
MacOS and Ubuntu Linux

### What did you do?
```go get -u -v google.golang.org/grpc/...```

### What did you expect to see?
install all grpc-go packages recursive.

### What did you see instead?
```
-> % GOPATH=/tmp/testing3 go get -v google.golang.org/grpc/grpclb
Fetching https://google.golang.org/grpc/grpclb?go-get=1
Parsing meta tags from https://google.golang.org/grpc/grpclb?go-get=1 (status code 200)
get "google.golang.org/grpc/grpclb": found meta tag main.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/grpclb?go-get=1
get "google.golang.org/grpc/grpclb": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc?go-get=1
Parsing meta tags from https://google.golang.org/grpc?go-get=1 (status code 200)
google.golang.org/grpc (download)
google.golang.org/grpc/grpclb
go build google.golang.org/grpc/grpclb: no buildable Go source files in /tmp/testing3/src/google.golang.org/grpc/grpclb
```

**Comment by menghanl** [comment]
Did you run `go build` after `go get`?
You don't need to `build` the package to use `grpc`. Just `get` should be sufficient.

**Comment by chy168** [comment]
Hi @menghanl, i didn't run `go build`, i just `go get -v google.golang.org/grpc/grpclb` and got error.
My previous error message is not clear enough, so i update the error message with the command for test.

**Comment by irfansharif** [comment]
@chy168: there _are_ in fact no buildable Go source files in the `/grpc/grpclb` source tree, there's no `func main()` which is what go will look for when instructed to build (look for the `go build ...` in the verbose output). I suspect what you really wanted to do is to simply get the `grpc` source tree, in which case `go get -u -v google.golang.org/grpc` is sufficient.

**Comment by menghanl** [comment]
@chy168 I just tried the command you posted and it worked for me without errors.
The go version I'm using is `1.9` though, maybe that causes some difference.

As @irfansharif mentioned, `go get` should download the gRPC source files for you.
One way to verify if the installation was successfully is to run the [helloworld example](https://github.com/grpc/grpc-go/tree/master/examples/helloworld).
