### ISSUE TITLE
Fail Fast / non-Wait For Ready behavior is wrong

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#1463]
Currently, we fail RPCs immediately if failfast is set and the ClientConn is in an idle or connecting state.  This does not conform with the gRPC spec found [here](https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md).

**Comment by menghanl** [comment]
This has been fixed by the new balancer behaviors (`picker_wrapper` in #1506).
