### ISSUE TITLE
Support graceful server shutdown

### ISSUE THREAD

**Issue by iamqizhao** [grpc/grpc-go#147]
A server that is attempting to gracefully shut down a
   connection SHOULD send an initial GOAWAY frame with the last stream
   identifier set to 2^31-1 and a NO_ERROR code.  This signals to the
   client that a shutdown is imminent and that no further requests can
   be initiated.  After waiting at least one round trip time, the server
   can send another GOAWAY frame with an updated last stream identifier.
   This ensures that a connection can be cleanly shut down without
   losing requests.

**Comment by mwitkow-io** [comment]
Nice to see lameduck mode being planned :) 
Are you guys planning in any way to bridge it with other mechanisms, such as:
https://github.com/facebookgo/grace

**Comment by mwitkow** [comment]
@iamqizhao, can you provide any tips as to how to get started here? Is the logic inside `http2Server`?

**Comment by bobbytables** [comment]
Is there anything I can do to help with this? I'm also looking for a way to gracefully shutdown a grpc server.

**Comment by frosenberg** [comment]
What is the status of this item?
