### ISSUE TITLE
constant overflow error in `rpc_util.go` when getting current version on i386 linux machine

### ISSUE THREAD

**Issue by mrbeskin** [grpc/grpc-go#1470]
# gRPC version

gRPC ver 1.6 (master branch)
not reproducible in ver v1.5.x

# What version of Go are you using (`go version`)?

`go version go1.8 linux/386`

# OS

i386 linux (ubuntu)

# when running the following command 
in dir `$GOROOT/src/google.golang.org/grpc`:
running command `$ go get -u ./...`

# Issue

expected: successful package update
got the following error:
`./rpc_util.go:320: constant 4294967295 overflows int`

**Comment by dfawley** [comment]
Tracking with #1469
