### ISSUE TITLE
Grpc client memory leak - WithBlock(), WithBalancer(), WithTimeout()

### ISSUE THREAD

**Issue by Kilmar** [grpc/grpc-go#1483]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.5.2

### What version of Go are you using (`go version`)?
1.8.3

### What operating system (Linux, Windows, …) and version?
Debian Stretch

### What did you do?
When grpc.Dial() method is called WithBalancer(), WithBlock(), WithTimeout() and you give unexisted address so your balancer cant provide addresses in Notify() []Address channel -  it ends with unexited blocking goroutine and slow memory leak. 

Problem is at this line: https://github.com/grpc/grpc-go/blob/b3ddf786825de56a4178401b7e174ee332173b66/clientconn.go#L408

lbWatcher is called with doneChannel but it will be never triggered because WithTimeout() ends dialing and do not notify lbWatcher. So return from grpc.Dial() is null conection with error, but lbWatcher is still waiting for done.

doneChan from clientconn.go#L408 should be closed when ctx->Done() is checked.

### What did you expect to see?
closing lbWatcher's goroutine and free all memory

### What did you see instead?
blocking lbWatcher and slow memory leek

**Comment by dfawley** [comment]
Good catch, thanks for the report.  The goroutine should block on either doneChan or ctx.Done to avoid blocking indefinitely.  Or lbwatcher could close doneChan as it exits if it hasn't already (The channel returned by Notify() should close when the balancer is closed).

**Comment by dfawley** [comment]
Actually, lbWatcher already _does_ close doneChan as it exits:

https://github.com/grpc/grpc-go/blob/master/clientconn.go#L584

This was fixed by #1424.  The fix was not in 1.5.2 (1.6 will be released on Wednesday, so we do not plan to backport this to the 1.5.x branch).
