### ISSUE TITLE
CallOption is totally opaque

### ISSUE THREAD

**Issue by jhump** [grpc/grpc-go#1495]
The `CallOption` type is a function that accepts a non-exported type as its argument. This makes a few things basically impossible:

1. It is not possible for a client interceptor to meaningfully intercept and modify incoming call options. Since the options are themselves just functions that refer to unexported types, there's no way an interceptor can inspect existing options and omit/modify/replace them. The best it can do is to append call options. This means that there is no way, for example, to intercept response metadata for a unary RPC (also see #1494).
2. It is not possible to provide alternate implementations of the client stub interfaces. There are a variety of possible use cases here, including testing, but also in-process dispatch (also see #906). But there is no way for call-option-driven parameters (like per-RPC credentials, where to store response metadata, where to store server/peer identity, etc) to be used/respected by an in-process dispatcher. That means it's not possible for in-process and normal (TCP) clients to behave the same -- application code that interacted with response metadata couldn't be made to work the same with an in-process channel.

A solution that does not break compatibility with existing APIs would be to modify the representation of `CallOption` to refer to exported types (e.g. `grpc.callInfo` -> `grpc.EffectiveCallOptions`). Technically, this would be a change in API. But existing source code would still compile with this change. Only code that relied heavily on reflection magic to instantiate or invoke a `CallOption` would be broken (if this is even possible -- maybe via `reflect.MakeFunc` and `reflect.Convert`?).

Resolving this issue would also effectively resolve the client side of #1494.

**Comment by dfawley** [comment]
Another option for this would be to make the `CallOption`s implement various interfaces that allow the interceptor to retrieve the data from the `CallOption`.  This approach would allow us to add/remove support for introspecting `CallOption`s in the future.  I have something like this kicking around in a branch of my fork:

https://github.com/dfawley/grpc-go/blob/metadata_callopt/rpc_util.go#L157-L181
