### ISSUE TITLE
Bidirectional RPC

### ISSUE THREAD

**Issue by prazzt** [grpc/grpc-go#152]
Does grpc support bidirection (e.g. server calls client's method anytime)?

**Comment by iamqizhao** [comment]
There is no such thing (service, method impl) on client side. gRPC is a
client-server rpc framework instead of a peer-to-peer messaging library.
You can start both a grpc client and a grpc server on each peer to
accommodate your requirements.

**Comment by ctiller** [comment]
Or (depending on your need) - have the client initiate a bidirectional
stream to the server that the server later sends data to.
