### ISSUE TITLE
OAuth tokens use TokenType field directly instead of calling Token() method.

### ISSUE THREAD

**Issue by wallaceicy06** [grpc/grpc-go#1524]
The Golang oauth2 library has the following doc on the `TokenType` field for a `Token`.

    // TokenType is the type of token.
    // The Type method returns either this or "Bearer", the default.
    TokenType string `json:"token_type,omitempty"`

But grpc-go does not use the Token() method; instead it accesses the TokenType field directly:
https://github.com/grpc/grpc-go/search?utf8=%E2%9C%93&q=TokenType&type=

**Comment by dfawley** [comment]
Fixed by #1537
