### ISSUE TITLE
busy loop in transportMonitor

### ISSUE THREAD

**Issue by tsuna** [grpc/grpc-go#1525]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

Commit bb78878767b96d411e740439ac820f118e95ae2f

### What version of Go are you using (`go version`)?

Go 1.9

### What did you do?

When connecting to a gRPC backend through a load balancer like HA Proxy, if the load balancer decides to close the connection immediately (e.g. because there is no backend available), gRPC will attempt to reconnect immediately.

### What did you expect to see?

gRPC should back off before trying to reconnect

### What did you see instead?

gRPC is tying to reconnect thousands of times per second.

The issue comes from the loop in `transportMonitor()` in `clientconn.go`.  When the backend closes the connection, we wake up in `case <-t.Error():` with an EOF error, then we do `if err := ac.resetTransport(false); err != nil {` and this works because we are able to connect to the load balancer again, so then we loop again.  But the new connection gets almost instantaneously closed again by the load balancer, leading to a quasi-busy loop in `transportMonitor()` and a ton of log spam.

**Comment by tsuna** [comment]
Probably a dup of #954

**Comment by tsuna** [comment]
or of #1444...

**Comment by dfawley** [comment]
Yes, definitely a dupe.  Thanks for the report.
