### ISSUE TITLE
credentials package should support oauth2.TokenSource

### ISSUE THREAD

**Issue by dsymonds** [grpc/grpc-go#153]
The `google.golang.org/grpc/credentials` package should have a function that can be given an `oauth2.TokenSource` and returns a `credentials.Credentials`. This might just involve renaming and exporting its existing `computeEngine` type.

This will make it easier to use "Application Default Credentials" ([1], [2]) with gRPC.

[1] https://developers.google.com/accounts/docs/application-default-credentials
[2] http://godoc.org/golang.org/x/oauth2/google#DefaultTokenSource

**Comment by iamqizhao** [comment]
sgtm. I am on vacation this week. Feel free to make a pull request to me if
you want to contribute. Thanks. BTW, does Andrew finish the application
default credentials already?

**Comment by dsymonds** [comment]
Yep, I'll try to make a pull request a bit later.

Yes, Andrew finished the Go implementation. It was all of ~150 lines; not hard at all.
