### ISSUE TITLE
Server not streaming to all clients

### ISSUE THREAD

**Issue by theobouwman** [grpc/grpc-go#1530]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
Latest

### What version of Go are you using (`go version`)?
1.9

### What operating system (Linux, Windows, …) and version?
MacOS

### What did you do?
I wanted to create just a simple chat service which sends received messages into a stream to all clients.

### What did you expect to see?
Receiving messages from other clients from the server.

### What did you see instead?
Not sending it to other clients, only to the client sending the message.

## This is my service
```proto
service Chat {
    rpc Chat(stream MessageRequest) returns (stream MessageResponse) {}
}
```

## This is my service Go code
```go
package main

import (
	pb "github.com/theobouwman/gRPC/examples/chat/proto"
	"google.golang.org/grpc"
	"net"
	"log"
	"google.golang.org/grpc/reflection"
	"fmt"
	"io"
)

type server struct {}

func (s *server) Chat(stream pb.Chat_ChatServer) error {
	for {
		req, err := stream.Recv()
		if err == io.EOF {
			return nil
		} else if err != nil {
			return err
		}

		fmt.Println(fmt.Sprintf("Get message: %v", req.Message))

		if stream.Send(&pb.MessageResponse{
			Message: req.Message,
		}); err != nil {
			return err
		}
	}

	return nil
}

func main() {
	lis, err := net.Listen("tcp", "localhost:5050")
	if err != nil {
		log.Fatal(err)
	}

	defer lis.Close()

	s := grpc.NewServer()

	pb.RegisterChatServer(s, &server{})

	reflection.Register(s)

	fmt.Println("Server running...")
	if err := s.Serve(lis); err != nil {
		log.Fatalf("Failed to serve: %v", err)
	}
}
```

## This is my client code
```go
package main

import (
	pb "github.com/theobouwman/gRPC/examples/chat/proto"
	"google.golang.org/grpc"
	"log"
	"context"
	"io"
	"fmt"
	"math/rand"
	"time"
)

func main() {
	conn, err := grpc.Dial("localhost:5050", grpc.WithInsecure())
	if err != nil {
		log.Fatalf("Failed to dial: %v", err)
	}

	defer conn.Close()

	chatClient := pb.NewChatClient(conn)

	stream, err := chatClient.Chat(context.Background())

	s1 := rand.NewSource(time.Now().UnixNano())
	r1 := rand.New(s1)

	err = stream.Send(&pb.MessageRequest{
		Message: fmt.Sprintf("new message: %v", rand.Intn(r1.Int())),
	})
	if err != nil {
		fmt.Println(fmt.Sprintf("Error when sending message: %v", err))
	}

	waitc := make(chan struct{})
	go func() {
		for {
			in, err := stream.Recv()
			if err == io.EOF {
				//close(waitc)
				return
			}
			if err != nil {
				log.Fatalf("Failed to receive a message : %v", err)
			}
			log.Printf("Got message %s", in.Message)
		}
		fmt.Println("End...")
	}()
	stream.CloseSend()
	<-waitc
}
```

**Comment by dfawley** [comment]
It looks like your server's Chat handler is only attempting to echo the message back on the same stream that it is serving.

You need something in your server that shares the message with all the other connected streams as well.

**Comment by theobouwman** [comment]
@dfawley and how could I do that?

**Comment by dfawley** [comment]
@theobouwman that would be up to your implementation.  The basic idea is that in the server, there is one call to `Chat()` outstanding for every open stream.  You need to broadcast messages from each invocation of `Chat()` to every _other_ one.  I.e. each `Chat()` should have a background goroutine subscribed to messages coming from other `Chat()`s and calling `Send()` for each one received, and a foreground goroutine calling `Recv()` and publishing the messages it receives to the other `Chat()`s.  Hope that helps.
