### ISSUE TITLE
"Wait for Ready" RPCs retry even if data was written to the wire

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#1532]
Once data is written to the wire, unless we are certain the remote server did not receive it, gRPC cannot resend an RPC.  However, we are doing this in many cases.  E.g., in the event an error occurs while waiting for a response from the remote server:

https://github.com/grpc/grpc-go/blob/1253dac14b4cb7d0d73580bcd946a44b6e92b439/call.go#L292-L294

**Comment by xiang90** [comment]
for read request, we do want to retry. i think we need to provide options to users.

**Comment by dfawley** [comment]
This would be covered by retry support ([gRFC A6](https://github.com/grpc/proposal/blob/master/A6-client-retries.md)), but it isn't otherwise a part of gRPC.

**Comment by xiang90** [comment]
@dfawley awesome. good to learn.
