### ISSUE TITLE
context.Context on the server side

### ISSUE THREAD

**Issue by kidoman** [grpc/grpc-go#156]
I see that we are to provide a `context.Context` on the client side:

https://github.com/grpc/grpc-go/blob/master/examples/route_guide/client/client.go#L73

However, should the context.Context be made available on the server side as well?

http://talks.golang.org/2014/gotham-context.slide#13

**Comment by dsymonds** [comment]
It's there. For non-streaming RPCs (e.g. https://github.com/grpc/grpc-go/blob/master/examples/route_guide/server/server.go#L75) it is the first arg. For streaming RPCs (e.g. https://github.com/grpc/grpc-go/blob/master/examples/route_guide/server/server.go#L86) it is available by calling the `Context` method on the stream value.

**Comment by kidoman** [comment]
Ah. I only saw the steaming examples. Thanks for this :+1:

**Comment by kidoman** [comment]
Reopening this for a clarification.

On the client, if I do this:

```
ctx = ctx.WithValue(someKey, someValue)
```

And on the server:

```
value := ctx.Value(someKey)
```

Should I not expect to get the value back?

**Comment by dsymonds** [comment]
You should not expect that. You need to use the metadata mechanism.

**Comment by kidoman** [comment]
I can see that a deadline set on the client gets propagated to the server. Any reason for excluding the values (apart from serialization/deserialization headaches) ?

**Comment by dsymonds** [comment]
Those are a bit more than headaches. They are major design issues. And there's only a limited set of context values that make sense to transit across machines transparently.

**Comment by kidoman** [comment]
I just saw https://godoc.org/google.golang.org/grpc/metadata

Thanks for the clarification though :)
