### ISSUE TITLE
Error too many open files after some time

### ISSUE THREAD

**Issue by sandeepkdpl** [grpc/grpc-go#1563]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.6.0
### What version of Go are you using (`go version`)?
1.7.5
### What operating system (Linux, Windows, …) and version?
 linux 16.04
### What did you do?
Client is making a new connection in every 30 seconds and sending request to server and each connection is closed after processing the same request.  There are more than 500 clients
### What did you expect to see?
Every time connection will be closed at server side.
### What did you see instead?
I have seen that there are too many connections from one ip which is idle but not closing at server side.

We are also using these keep alive parameters in our rpc server. 
MaxConnectionIdle = 60 seconds 
MaxConnectionAge = 60 seconds 
MaxConnectionAgeGrace = 30 seconds 
Timeout = 20 seconds 
Time = 1 second.

System Keep alive parameters are
Keep Alive Time = 60 Seconds 
Keep Alive Probes = 5 time
Keep Alive Interval = 24 Seconds

**Comment by menghanl** [comment]
Could you provide a small snippet to show what you did on the client side?
It would be even better if you can provide a reproduction of the problem.

**Comment by sandeepkdpl** [comment]
We have a android application which is making connection in every 30 seconds. Please see below code for how we are creating connection and closing connection in every request to server. We are using async task to perform grpc server call.

private ManagedChannel mChannel;
protected GRPCResponse doInBackground(GRpcType... params) {
try {
   // Initializing Channel  with timout 15 seconds 
   mChannel = ManagedChannelBuilder.forAddress(mHost, mPort).build();
    yegoappinfsrvGrpc.yegoappinfsrvBlockingStub stub = yegoappinfsrvGrpc.newBlockingStub(mChannel)
            .withDeadlineAfter(15, TimeUnit.SECONDS);
    // Some more code ….
  ….
……
}

protected void onPostExecute(GRPCResponse result) {
    try {
        mChannel.shutdown().awaitTermination(1, TimeUnit.SECONDS);
    // Some more code ….
     ….
     ……

}


As per our observation normally when internet connection is running fine then there is no issue but if there internet connection is not running properly then some connection gets ideal after at server.

**Comment by dfawley** [comment]
I'm not familiar with the Java API.  You say you're using the async task, and you have a `shutdown` call in `onPostExecute`, but your stub is created using `newBlockingStub`.  Is this correct?

Another thing you could try is setting the MaxAge values to something very short to ensure that the keepalive mechanism is properly killing the connections from the server side.

**Comment by sandeepkdpl** [comment]
In Async Task class, DoInBackground() runs in separate thread other than UI thread, while OnPostExecute() runs after DoInBackground() and runs on UI thread. 

"I'm not familiar with the Java API. You say you're using the async task, and you have a shutdown call in onPostExecute, but your stub is created using newBlockingStub. Is this correct?" 
Yes we are doing exactly the same way !!!

We have already set MaxAge to 60 seconds on server side. Do we need to set it on client side also ?

**Comment by sandeepkdpl** [comment]
MaxConnectionAge means the maximum time for which connection is active. 
If we will set this time to very short like 1 second that means it will disconnect the connection after 1 second if client is communicating. Am I Right? 
Please see below parameters we are using and suggest us which parameters are to be updated for properly killing the connections from the server side.
See these parameters.

RPC Server Keep alive Parameters 
MaxConnectionIdle = 60 seconds
MaxConnectionAge = 60 seconds
MaxConnectionAgeGrace = 30 seconds
Timeout = 20 seconds
Time = 1 second.

System Keep alive parameters are
Keep Alive Time = 60 Seconds
Keep Alive Probes = 5 time
Keep Alive Interval = 24 Seconds

**Comment by sandeepkdpl** [comment]
@menghanl  and @dfawley any more input is required?

**Comment by dfawley** [comment]
@sandeepkdpl, sorry we lost track of this.  Are you still seeing problems related to this issue?

To answer your question above, setting `MaxConnectionAge` to something short like 1 second would cause the server to only accept new RPCs from the client for 1 second, then put it into a "draining" state where the existing RPCs would be processed until `MaxConnectionAgeGrace`, at which point the connection would be hard-closed.

**Comment by sandeepkdpl** [comment]
@dfawley  Yes looks like problem is resolved. Since last 6 days we have not faced this issue after upgrading.
Thanks

**Comment by dfawley** [comment]
That's great, thanks!
