### ISSUE TITLE
Cache responses in client?

### ISSUE THREAD

**Issue by buchanae** [grpc/grpc-go#1577]
### What version of gRPC are you using?
```
git -C $GOPATH/src/google.golang.org/grpc/ rev-parse HEAD
c443156028b9fa563e063e9fa8ba7881d467833b
```

### What version of Go are you using (`go version`)?

```
go version
go version go1.8.3 linux/amd64
```

### What operating system (Linux, Windows, …) and version?

```
uname -a
Linux buchanan01 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

I'd like to cache http responses in a client, similar to https://github.com/gregjones/httpcache

Is this possible? Is it unadvisable? Should I take the less generic approach of caching my objects instead? I've read this [proposal](https://github.com/grpc/grpc/issues/7945). Will this be implemented in the Go library?

I considered trying to do this via UnaryInterceptor, but honestly it seems easier just implement a one-off caching client for the specific service.

Thanks! And, sorry if this isn't the place to ask questions, I couldn't find a better venue.

**Comment by dfawley** [comment]
This is honestly the first I've heard of this, so thanks for filing this.  It looks like something we probably will implement, but don't have any plans to do so in the current quarter.

**Comment by dfawley** [comment]
This isn't a priority for the team, and won't be in the foreseeable future.  If you're interested in caching, you will need to do it at the application layer.  Thank you for the PR.
