### ISSUE TITLE
transport.go using ambiguous context

### ISSUE THREAD

**Issue by pavelbyles** [grpc/grpc-go#1578]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
git -C $GOPATH/src/google.golang.org/grpc/ rev-parse HEAD
c209cdff16049a924bef4aa5c6f7588f0b42b2fa

### What version of Go are you using (`go version`)?
go version
go version go1.9.1 linux/amd64

### What operating system (Linux, Windows, …) and version?
uname -a
Linux cs-6000-devshell-vm-96980dc6-dbaa-4e5b-8286-27c616384221 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux

### What did you do?
If possible, provide a recipe for reproducing the error.
import "cloud.google.com/go/pubsub" has google.golang.org/grpc/transport/transport.go as a dependency.

App has:
import "cloud.google.com/go/pubsub"
...
ctx := context.Background()
topic := Pubsubclient.Topic(PubsubTopicID)
...

Ran:
$ dev_appserver.py ./app.yaml

### What did you expect to see?
Successful compile and run

### What did you see instead?
/home/pavelbyles/src/src/google.golang.org/grpc/transport/transport.go:24: can't find import: "context"

2017/10/15 03:57:39 Can't find package "context" in $GOPATH: cannot find package "context" in any of:
        /google/google-cloud-sdk/platform/google_appengine/goroot-1.6/src/context (from $GOROOT)
        /home/pavelbyles/src/src/context (from $GOPATH)
2017/10/15 03:57:49 go-app-builder: build timing: 0×skip (13ms total), 62×compile (9.158s total), 0×link (0 total)
2017/10/15 03:57:49 go-app-builder: failed running compile: exit status 2

**Comment by dfawley** [comment]
We will re-add go1.6 support as a short-term workaround for AppEngine users still stuck on 1.6.  #1580 

(The transport package was not intended to be used outside the grpc package, so hopefully this dependency is indirect.)
