### ISSUE TITLE
are all errors returned by gRPC wrapped by status.Status?

### ISSUE THREAD

**Issue by xiang90** [grpc/grpc-go#1581]
Can I assume that all errors returned by gRPC are https://godoc.org/google.golang.org/grpc/status#Status type?

If so, why ErrClientConnClosing is public? And there are other error types defined in https://godoc.org/google.golang.org/grpc/transport.

**Comment by gyuho** [comment]
Note: currently we are using grpc v1.6.0. And plan to upgrade to v.1.7.0.

**Comment by menghanl** [comment]
`Status` is to represent RPC status (the error code, message and details).
All errors returned by RPCs should be type `Status`.

Errors returned by other function like `Dial` are not type `Status`.

**Comment by xiang90** [comment]
@menghanl 

Great! That matches my expectation.

Can we document this somewhere? (Or if this is already documented, can you point me to the doc?)

**Comment by menghanl** [comment]
It's not explicitly documented now.
In the doc for `status` package, there's this line conveys the same message:

    gRPC service handlers should return an error created by this package, and 
    gRPC clients should expect a corresponding error to be returned from the RPC call

We will see if there's a better place to document this behavior.
