### ISSUE TITLE
better retry support

### ISSUE THREAD

**Issue by xiang90** [grpc/grpc-go#1585]
Now gRPC-go support failfast option. When it is enabled, gRPC will retry the RPC when connection fails.However, for some use cases, we need to be more careful about retry. 

For some systems that requires at most once semantics, retry can have unexpected side effect. If gRPC retries after the request is sent successfully, then the requests might end up delivering to the server twice. gRPC should only retry if the request is not sent successfully (connection fails before the request body has fully sent out).

Our current workaround for this is to not use failfast for write requests, and implement our retry logic, but it is less than ideal. Is there a better way to do this?

**Comment by dfawley** [comment]
I believe this is the same as #1532.

Also, we are implementing retry logic in gRPC itself, hopefully it will be done in the next few weeks.

https://github.com/grpc/proposal/blob/master/A6-client-retries.md

**Comment by xiang90** [comment]
> Also, we are implementing retry logic in gRPC itself, hopefully it will be done in the next few weeks.

You mean implementing retry policy? gRPC-go has naive retry support with failfast=false on connection issues as it is today, no?

**Comment by gyuho** [comment]
e.g. https://github.com/grpc/grpc-go/blob/v1.7.x/call.go#L226-L240

**Comment by dfawley** [comment]
> You mean implementing retry policy? gRPC-go has naive retry support with failfast=false on connection issues as it is today, no?

Technically, yes, it does currently have retry support, but that is actually a bug.  Non-fail-fast is not _supposed_ to retry; it's supposed to wait until a connection is available, and then send the RPC.  It will be fixed to follow this behavior, and we will also be adding transparent retry support (as part of gRFC A6) if we are sure the request was not received by the server.

**Comment by xiang90** [comment]
> on-fail-fast is not supposed to retry; it's supposed to wait until a connection is available, and then send the RPC

this makes much more sense to me. can you update the documentation here: https://godoc.org/google.golang.org/grpc#FailFast to clarify that failfast wont retry on transit failures? thank you.

**Comment by dfawley** [comment]
Thanks for noticing that problem with the doc.  #1586 fixes it.

**Comment by xiang90** [comment]
> but that is actually a bug

@dfawley will the bug be fixed in the up coming release. We now have to work around it by disabling  failfast, and write our own connection ready waiting logic.

**Comment by dfawley** [comment]
Yes, I'm hoping to have that done in a week or two.
