### ISSUE TITLE
grpc client and server should not allow you to set Max*MessageSize of more than 4GB

### ISSUE THREAD

**Issue by Civil** [grpc/grpc-go#1590]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.7.0 (f7bf885db0b7479a537ec317c6e48ce53145f3db)

### What version of Go are you using (`go version`)?
go version go1.9 darwin/amd64

### What operating system (Linux, Windows, …) and version?
Mac OS X 10.12.6

### What did you do?
1. Wrote a client and server
2. Trying to send large message (20MB) over gRPC. Both send max message size to 8GB.

### What did you expect to see?
Message should be sent ok

### What did you see instead?
```rpc error: code = ResourceExhausted desc = grpc: received message larger than max (15600780 vs. 8589934592)```

From my understanding:
https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L279 here maxReceiveMessageSize down-converted to uint32 from int (which is 64 bit on amd64). 8GB (8 * 1024 * 1024 * 1024) is larger than uint32.

**Comment by Civil** [comment]
Actually same problem also affects client. I've set 'grpc.WithMaxMsgSize' to 8589934592 (8GB) and got error message:
```grpc: received message larger than max (23 vs. 8589934592)```

**Comment by lyuxuan** [comment]
#1598

**Comment by lyuxuan** [comment]
#1623
