### ISSUE TITLE
panic: runtime error: integer divide by zero with https://github.com/hashicorp/go-plugin/

### ISSUE THREAD

**Issue by srinarayanant** [grpc/grpc-go#1602]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
issue occur from Latest build in a non vendored go project

### What version of Go are you using (`go version`)?
```
[root@worker3 grpc]# go version
go version go1.9 linux/amd64
```
### What operating system (Linux, Windows, …) and version?
Linux
### What did you do?
If possible, provide a recipe for reproducing the error.
https://github.com/srinarayanant/terraform-provider-vcloud-director/blob/master/go/src/test/test.go

We have go to python grpc call for a terraform provider , link to the test file above .
Executing the file with latest google.golang.org produces panic integer division by zero error

I took a copy of the google.goland.org directory from a working environment which was working and without the update and it works fine with it, pointing that the issue is with the latest update of the google.golang.org repo

```
[root@worker3 google.golang.org]# ls
genproto  grpc

```

### What did you expect to see?

GRPC call established from the go client to the python server

### What did you see instead?
```
[root@worker3 test]# ./test 
2017/10/20 09:50:52  ok starting to client 
2017-10-20T09:50:52.626-0400 [DEBUG] plugin: starting plugin: path=/usr/bin/sh args="[sh -c python3 /home/terraform-provider-vcloud-director/plugin-python/plugin.py]"
2017-10-20T09:50:52.626-0400 [DEBUG] plugin: waiting for RPC address: path=/usr/bin/sh
panic: runtime error: integer divide by zero

goroutine 23 [running]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc42021a000, 0x0, 0xc4201c4420)
	/home/terraform-provider-vcloud-director/go/src/google.golang.org/grpc/clientconn.go:930 +0xf50
google.golang.org/grpc.(*addrConn).connect.func1(0xc42021a000)
	/home/terraform-provider-vcloud-director/go/src/google.golang.org/grpc/clientconn.go:736 +0x2f
created by google.golang.org/grpc.(*addrConn).connect
	/home/terraform-provider-vcloud-director/go/src/google.golang.org/grpc/clientconn.go:735 +0x400
[root@worker3 test]# 

```

Please let me know if any more info is required

**Comment by srinarayanant** [comment]
I have added the working copy to the vendor directory

https://github.com/srinarayanant/terraform-provider-vcloud-director/tree/master/go/src/vendor/google.golang.org

**Comment by srinarayanant** [comment]
https://gist.github.com/srinarayanant/168e400af5b617aa6173597fcfe6a262

**Comment by menghanl** [comment]
#1606 should have fixed this. Please give it a try.
