### ISSUE TITLE
Commit a353537 is causing my code to panic

### ISSUE THREAD

**Issue by chrissnell** [grpc/grpc-go#1604]
Please answer these questions before submitting your issue.

### What version of gRPC are you using? 
1.8.0-dev (HEAD of master branch)

### What version of Go are you using (`go version`)?
`go version go1.9.1 linux/amd64`

### What operating system (Linux, Windows, …) and version?
`Linux socotra 4.13.7-1-hardened #1 SMP PREEMPT Sun Oct 15 10:56:32 EDT 2017 x86_64 GNU/Linux
`

### What did you do?
If possible, provide a recipe for reproducing the error.
I built my software against a non-vendored copy of grpc-go and noticed that it was failing.  If I reverted to commit `94687c3b56350c6172f3fdb30f969e63b9d7c7fa`,  my software works and is able to make gRPC requests.

### What did you expect to see?
gRPC library usage that doesn't cause a panic.

### What did you see instead?
A panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7a28f7]

goroutine 1 [running]:
github.com/chrissnell/weather-bar/vendor/google.golang.org/grpc.(*ClientConn).Close(0x0, 0x1, 0x1)
	/home/cjs/dev/go/src/github.com/chrissnell/weather-bar/vendor/google.golang.org/grpc/clientconn.go:805 +0x37
panic(0x835680, 0xb35d70)
	/usr/lib/go/src/runtime/panic.go:491 +0x283
github.com/chrissnell/weather-bar/vendor/google.golang.org/grpc.NewClientStream(0xb02520, 0xc420062240, 0xb37c60, 0x0, 0x8c3713, 0x17, 0x0, 0x0, 0x0, 0xc420090530, ...)
	/home/cjs/dev/go/src/github.com/chrissnell/weather-bar/vendor/google.golang.org/grpc/stream.go:100 +0x29
github.com/chrissnell/weather-bar/protobuf.(*weatherClient).GetLiveWeather(0xc42000e090, 0xb02520, 0xc420062240, 0xb654f0, 0x0, 0x0, 0x0, 0xc420011d30, 0x18, 0xc4201624b8, ...)
	/home/cjs/dev/go/src/github.com/chrissnell/weather-bar/protobuf/grpcweather.pb.go:137 +0xb5
main.main()
	/home/cjs/dev/go/src/github.com/chrissnell/weather-bar/main.go:64 +0x504
```

**Comment by menghanl** [comment]
This could be caused by the switching of resolvers, and #1606 may fix this.
Can you try again with the latest code?

**Comment by chrissnell** [comment]
I tried again.  Still no-go:

```
socotra% govendor fetch google.golang.org/grpc@94f1917696488c633b485fe76feb764c935f2561
socotra% go build
socotra% ./weather-bar
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7a2f17]

goroutine 1 [running]:
github.com/chrissnell/weather-bar/vendor/google.golang.org/grpc.(*ClientConn).Close(0x0, 0x1, 0x1)
	/home/cjs/dev/go/src/github.com/chrissnell/weather-bar/vendor/google.golang.org/grpc/clientconn.go:824 +0x37
panic(0x836680, 0xb37df0)
	/usr/lib/go/src/runtime/panic.go:491 +0x283
github.com/chrissnell/weather-bar/vendor/google.golang.org/grpc.NewClientStream(0xb045a0, 0xc42009c240, 0xb39ce0, 0x0, 0x8c48be, 0x17, 0x0, 0x0, 0x0, 0xc42009a530, ...)
	/home/cjs/dev/go/src/github.com/chrissnell/weather-bar/vendor/google.golang.org/grpc/stream.go:100 +0x29
github.com/chrissnell/weather-bar/protobuf.(*weatherClient).GetLiveWeather(0xc420098080, 0xb045a0, 0xc42009c240, 0xb67570, 0x0, 0x0, 0x0, 0xc42007fd20, 0x18, 0xc4201707e8, ...)
	/home/cjs/dev/go/src/github.com/chrissnell/weather-bar/protobuf/grpcweather.pb.go:137 +0xb5
main.main()
	/home/cjs/dev/go/src/github.com/chrissnell/weather-bar/main.go:64 +0x504
```

If you want to try weather-bar, use this for your `config` file:

```ini
[server]
hostname = home.chrissnell.com
port = 7500
cert = /home/cjs/.config/weather-bar/fullchain.pem

[format]
weather-format = " %temperature-fahrenheit%°F   %humidity%%   %windcardinal% @ %windspeed% MPH   %rainfall%"
```

**Comment by menghanl** [comment]
The dial on this line might have returned an error and `nil` ClientConn: https://github.com/chrissnell/weather-bar/blob/master/main.go#L53, and I guess the defer following that calls `Close` on the `nil`. Please check the error.

Also, I don't have the cert file you listed in your config. I removed that line and got connection error.

**Comment by chrissnell** [comment]
OK, printed the connection error and here's what it says now:
```
2017/10/20 15:37:18 Could not connect to gRPC weather server: failed to build resolver: could not get resolver for scheme: ""
```

Here is the cert if you want to test:

https://gist.github.com/chrissnell/15baef1c095df6eb0ec96539c9e688e7

**Comment by menghanl** [comment]
I tried with the current gRPC master and it worked for me.

The error you got should never happen. For scheme `""`, the default resolver will be used.
Please make sure your gRPC code is up-to-date, and try again.

**Comment by chrissnell** [comment]
I deleted my $GOPATH/pkg directory and rebuilt.  It works now.  Crazy!  

Thanks for the help.
