### ISSUE TITLE
[Go] provide a way to annotate a Status message

### ISSUE THREAD

**Issue by jba** [grpc/grpc-go#1613]
Libraries that use gRPC might want to add information to errors. The usual way to do this in Go,
```
fmt.Errorf("more info: %v", err)
```
loses the ability to extract the error code (and details) programatically.

Consider adding functions
```
func (*Status) Annotate(msg string) *Status
func (*Status) Annotatef(format string, args ...interface{}) *Status
```
that prepend a string to the Status's message, preserving other fields.

**Comment by dfawley** [comment]
Please let us know if that isn't sufficient for your needs.
