### ISSUE TITLE
TestServerStatsServerStreamRPCError failed

### ISSUE THREAD

**Issue by lyuxuan** [grpc/grpc-go#1615]
```
--- FAIL: TestServerStatsServerStreamRPCError (0.01s)
	stats_test.go:710: - 0, *stats.ConnBegin = &{Client:false}, ctx: context.Background.WithCancel.WithValue(stats_test.connCtxKey{}, &stats.ConnTagInfo{RemoteAddr:(*net.TCPAddr)(0xc820019f50), LocalAddr:(*net.TCPAddr)(0xc8200197d0)})
	stats_test.go:710: - 1, *stats.ConnEnd = &{Client:false}, ctx: context.Background.WithCancel.WithValue(stats_test.connCtxKey{}, &stats.ConnTagInfo{RemoteAddr:(*net.TCPAddr)(0xc820019f50), LocalAddr:(*net.TCPAddr)(0xc8200197d0)})
	stats_test.go:710: - 2, *stats.ConnBegin = &{Client:false}, ctx: context.Background.WithCancel.WithValue(stats_test.connCtxKey{}, &stats.ConnTagInfo{RemoteAddr:(*net.TCPAddr)(0xc8201e24b0), LocalAddr:(*net.TCPAddr)(0xc8201e2480)})
	stats_test.go:710: - 3, *stats.ConnBegin = &{Client:false}, ctx: context.Background.WithCancel.WithValue(stats_test.connCtxKey{}, &stats.ConnTagInfo{RemoteAddr:(*net.TCPAddr)(0xc8205f02a0), LocalAddr:(*net.TCPAddr)(0xc8205f0270)})
	stats_test.go:710: - 4, *stats.ConnEnd = &{Client:false}, ctx: context.Background.WithCancel.WithValue(stats_test.connCtxKey{}, &stats.ConnTagInfo{RemoteAddr:(*net.TCPAddr)(0xc8205f02a0), LocalAddr:(*net.TCPAddr)(0xc8205f0270)})
	stats_test.go:712: got 5 stats, want even positive number
```

**Comment by MakMukhi** [comment]
So did TestServerStatsClientStreamRPCError

- FAIL: TestServerStatsClientStreamRPC (0.00s)
	stats_test.go:710:  - 0, *stats.ConnBegin = &{Client:false}, ctx: context.Background.WithCancel.WithValue(stats_test.connCtxKey{}, &stats.ConnTagInfo{RemoteAddr:(*net.TCPAddr)(0xc82015f050), LocalAddr:(*net.TCPAddr)(0xc82015f020)})
	stats_test.go:710:  - 1, *stats.ConnBegin = &{Client:false}, ctx: context.Background.WithCancel.WithValue(stats_test.connCtxKey{}, &stats.ConnTagInfo{RemoteAddr:(*net.TCPAddr)(0xc82015e180), LocalAddr:(*net.TCPAddr)(0xc82015e0c0)})
	stats_test.go:710:  - 2, *stats.ConnEnd = &{Client:false}, ctx: context.Background.WithCancel.WithValue(stats_test.connCtxKey{}, &stats.ConnTagInfo{RemoteAddr:(*net.TCPAddr)(0xc82015f050), LocalAddr:(*net.TCPAddr)(0xc82015f020)})
	stats_test.go:712: got 3 stats, want even positive number
