### ISSUE TITLE
recent checkin causes builds for arm to fail

### ISSUE THREAD

**Issue by zorkohiro** [grpc/grpc-go#1620]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

commit 5856538706dc3abc44dd5ba1a8bb19a0dfb1ab25
Author: lyuxuan <yuxuanli@google.com>
Date:   Tue Oct 24 10:20:54 2017 -0700

    cap max msg size to min(max_int, max_uint32) (#1598)

### What version of Go are you using (`go version`)?
go version go1.9.1 linux/amd64

### What operating system (Linux, Windows, …) and version?
callmejoe > uname -a
Linux callmejoe 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
callmejoe > cat /etc/issue
Ubuntu 16.04.3 LTS \n \l

### What did you do?
If possible, provide a recipe for reproducing the error.

Try to compile grpc

### What did you expect to see?

a clean compile which happens on amd64

### What did you see instead?

callmejoe > GOARCH=arm go build -o bookshelf.arm64 bookshelf.go
# github.com/eero-inc/grpc-playground/bookshelf/vendor/google.golang.org/grpc
vendor/google.golang.org/grpc/server.go:215:28: constant 4294967295 overflows int
vendor/google.golang.org/grpc/server.go:228:25: constant 4294967295 overflows int
vendor/google.golang.org/grpc/service_config.go:169:7: constant 4294967295 overflows int

**Comment by MakMukhi** [comment]
The commit was reverted by #1619. Sorry about the breakage.
