### ISSUE TITLE
clientconn fails to return the underlying network error due to a recent change

### ISSUE THREAD

**Issue by sougou** [grpc/grpc-go#1633]
@menghanl @dfawley , I believe this change broke errors returned by clientcoonn: https://github.com/grpc/grpc-go/pull/1596. The 1.7 release works correctly. However, google internally imported a more recent version and the vitess tests started failing.

I'm not too familiar with the flow, but there are two problems:
1. FailOnTempDialError does not immediately fail any more. It hangs if no timeout is provided.
2. If a timeout is provided, it loses the underlying error and returns "deadline exceeded" instead.

### What version of gRPC are you using?
master

### What version of Go are you using (`go version`)?
1.9

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
The following tests fail with the latest grpc because it either returns deadline exceeded (if timeout is provided), or panics if no timeout is given:
https://github.com/youtube/vitess/blob/master/go/vt/grpcclient/client_test.go

### What did you expect to see?
The tests should pass with the proper error message(s)

### What did you see instead?
Generic timeout errors, or panics due to test hanging.

**Comment by sougou** [comment]
We have a workaround for this via https://github.com/youtube/vitess/pull/3348:
* WithDialer was not a viable option because it bypasses the proxy detection layer, which may be useful.
* Overriding the DNS would have caught some use cases, but not all.

So, we decided to just redirect grpc logging into our own logs. They are a little spammy, but it felt like the best trade-off.

Based on internal discussions, I understand that the design is such that it's hard for the outermost layer to know the underlying error. But it would be definitely something that the vitess community will appreciate if it could be made to work.

I'll leave the issue open in case you think of a solution. Otherwise, you may close it.

**Comment by sougou** [comment]
An update on this bug: the work-around of redirecting grpc logs to our own has allowed us to better trouble-shoot issues. However, users have not been happy with the amount of spam the logs generate. Sometimes, they also get confused that something is wrong when everything is actually working as intended.

Ideally, it would still be nice if we could figure out a way to return the underlying failure. Another option would be to look at reducing spam (without loss of info). The source of most spam seems to come from these two lines:

```
W1202 14:47:20.861791   11030 clientconn.go:1028] grpc: addrConn.transportMonitor exits due to: context canceled
W1202 14:47:20.862964   11030 clientconn.go:934] grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp: lookup myserver-7 on 10.1.2.3:53: dial udp 10.1.2.3:53: operation was canceled"; Reconnecting to {myserver-7:16302 0  <nil>}
```

**Comment by menghanl** [comment]
We will do a cleanup in addrConn/ClientConn, and will see what we can do on the errors here.
Tracking in #1742

**Comment by jhump** [comment]
Relevant thread on grpc.io Google Group, along with a work-around that uses `WithDialer` (which is not always viable, unless one also forks more logic in the default dialer, like proxy handling):
https://groups.google.com/d/topic/grpc-io/yCUwuHycNWk/discussion

**Comment by sougou** [comment]
Thanks for this fix! We'll let you know how it works out once we upgrade.
