### ISSUE TITLE
Release 1.7.1 somehow doesn't have the changes from #1596

### ISSUE THREAD

**Issue by sougou** [grpc/grpc-go#1638]
I am completely stumped, and have sanity checked this multiple times, but can't find an explanation for what I see:

https://github.com/grpc/grpc-go/blob/v1.7.1/clientconn.go does not contain the changes from #1596.

I can see it in the commit history here: https://github.com/grpc/grpc-go/commits/v1.7.1, but the file is still showing the pre-commit version. You'll see that the `connect` function still takes the `block` parameter.

However, the master branch shows the changed version.

### What version of gRPC are you using?
1.7.1

### What version of Go are you using (`go version`)?
1.9

### What operating system (Linux, Windows, …) and version?
Linux
### What did you do?
Pulled the file using govendor @=v1.7.1

### What did you expect to see?
Expected to see the changes made in #1596 

### What did you see instead?
Saw an older version of the file.

**Comment by dfawley** [comment]
This was actually intentional to avoid an unnecessary part of that change that also relied on other changes from earlier commits.  From the commit message:

```
This commit cherry-picked the connectivity state change from b3ed81a,
excluding the connect() function cleanup.
```

Do you need some changes related to that in a 1.7.x release?  If so, can you explain what/why?  Thanks.

**Comment by sougou** [comment]
If it was intentional, we're good.

The open source version is behaving differently from the google import: `Connect` in 1.7.1 still returns the underlying error. But that's our problem.
