### ISSUE TITLE
hpack frame decoding fault poisons entire connection

### ISSUE THREAD

**Issue by dsymonds** [grpc/grpc-go#164]
If I have a single gRPC connection and flood it such that a bunch of RPCs end up timing out, the connection gets into an unrecoverable state. Any future RPCs that should otherwise work end up failing with errors like
  `rpc error: code = 13 desc = "transport: HPACK header decode error: decoding error: invalid indexed representation index 82"`
(and the index increments over time).

I traced it to the http2 hpack decoder, which has d.parseHeaderFieldRepr returning an error. Somewhere after that, though, I'd expect the connection to recognise that it is stuck and automatically reset. But it doesn't.

I have a private reproduction that appears to be able to reproduce this 100% of the time. I haven't tried reproducing it with a smaller test case yet.

I don't know who is at fault, grpc-go or http2. But it shouldn't be possible to send a bunch of RPCs on a gRPC connection such that the connection ends up poisoned.

/cc @bradfitz in case he has thoughts.

**Comment by iamqizhao** [comment]
can you share your private reproduction?

**Comment by dsymonds** [comment]
Not publicly, no. I can try to create a self-contained reproduction case though.

**Comment by iamqizhao** [comment]
grpc should treat it as ConnectionError so that reconnect is triggered (now
it is a StreamError). I am generating a pull request now. But this error is
not expected and we should figure out the root cause. It seems the hpack
state is messed up either due to a miss use in grpc or a bug in hpack impl.

**Comment by iamqizhao** [comment]
Hi David,

not in good condition to work today. The pull request will be made later.
Sorry about that. It would be great to have a self-contained reproduction
from you so that I can investigate what is going on here. Thanks.

**Comment by iamqizhao** [comment]
okay, it seems I can reproduce it by running TestRPCTimeout test cases a few thousand times. will look into it.

**Comment by dsymonds** [comment]
Thanks. I haven't had time to create a reproduction from my code, so it's good that you've been able to reproduce it yourself. I can verify a fix that you come up with.

**Comment by iamqizhao** [comment]
should be fixed via #165. will have another pull request to make it connection though.

**Comment by iamqizhao** [comment]
s/connection/connection error/

**Comment by dsymonds** [comment]
Yep, I can no longer reproduce the problem. Thanks!
