### ISSUE TITLE
New balancer wrapper tearDown does not call down function from Up

### ISSUE THREAD

**Issue by gyuho** [grpc/grpc-go#1649]
### What version of gRPC are you using?

v1.7.2

### What version of Go are you using (`go version`)?

Go 1.9.2

### What operating system (Linux, Windows, …) and version?

> Linux 4.10.0-38-generic 16.04.1-Ubuntu x86_64 x86_64 x86_64 GNU/Linux

### What did you do?

etcd with grpc v1.6.0 implements old(v1) balancer interface with `Up`, `Get`, `Notify`, etc..
Now we are upgrading to v1.7.2, while keeping current etcd implementation--temporarily, we will rewrite balancer to use new interface.

### What did you expect to see?

Same behavior in etcd client balancer with gRPC's v1.7.2 balancer v1 wrapper.

### What did you see instead?

A lot of etcd test failures.

<br><br>
Our balancer depends on `v1.6.0` `lbWatcher` where it creates/drains connections from `Notify` channel. And it calls `down` function to propagate `grpc: the connection is drained` error to the balancer. We use this error to unpin/switch endpoints.

`v1.7.2` `lbWatcher` creates/drains connections the same way, except `tearDown`. It calls `RemoveSubConn` and `tearDown`, but not `down` function on `grpc: the connection is drained`. 

<br><br>

Relevant changes:

v1.6.0

https://github.com/grpc/grpc-go/blob/84671c5e11bfb5b7c237ff1799a660ff11a518d2/clientconn.go#L1212-L1221

v1.7.2

https://github.com/grpc/grpc-go/blob/5ffe3083946d5603a0578721101dc8165b1d5b5f/clientconn.go#L644-L655

https://github.com/grpc/grpc-go/blob/5ffe3083946d5603a0578721101dc8165b1d5b5f/clientconn.go#L1109-L1130

<br><br>

Isn't v1 balancer wrapper supposed to keep the old behavior?
Could anybody help understand why `down(errConnDrain)` was removed?

Thanks in advance!
/cc @xiang90

**Comment by menghanl** [comment]
`down` is called by v1 balancer wrapper when the `SubConn` state changes from `Ready` to non-`Ready`:
https://github.com/grpc/grpc-go/blob/4318e6475c4b2660f7b8ddb77a4504da77311504/balancer_v1_wrapper.go#L243-L249

It's called with `"grpc: the connection is closing"` though.

Did you see that your `down` function is never called?
Or you expect the drain error message?

**Comment by gyuho** [comment]
> It's called with "grpc: the connection is closing" though.

Right. We are also seeing that.

But our current balancer logic was built, based on v1.6.0 logic.
So, we were expecting to see `errConnDrain` message first.
And then, `grpc: the connection is closing`.

Was there any reason why `errConnDrain` was removed and not trigger `down` any more in v1.7.x?

**Comment by menghanl** [comment]
`down` is called by notify balancer that the connection is not working.
It should be only called once. What do you mean see `errConnDrain` and then `the connection is closing`?

`down` is not removed. It's moved to the v1 balancer wrapper. When `tearDown()` is called, the `down` function should eventually be called v1 balancer wrapper. If your `down` is not called, that will be a bug.

**Comment by gyuho** [comment]
> What do you mean see errConnDrain and then the connection is closing?

v1.6.0 has this in `lbWatcher`:

https://github.com/grpc/grpc-go/blob/84671c5e11bfb5b7c237ff1799a660ff11a518d2/clientconn.go#L651-L653

So when we delete connections, v1.6.0 `tearDown` calls `down` function, so custom balancer knows that this connection has been drained.

v1.7.2 has this in `lbWatcher`:

https://github.com/grpc/grpc-go/blob/57ebb0fa1c896a23101f49b61dd887313fbcd055/balancer_v1_wrapper.go#L216-L218

And `RemoveSubConn` calls `removeAddrConn` and `tearDown`

https://github.com/grpc/grpc-go/blob/57ebb0fa1c896a23101f49b61dd887313fbcd055/balancer_conn_wrappers.go#L178-L185

https://github.com/grpc/grpc-go/blob/57ebb0fa1c896a23101f49b61dd887313fbcd055/clientconn.go#L646-L655

But v1.7.2 `tearDown` does not call `down` as I linked above.

So, I meant to say `tearDown(errConnDrain)` is called in both versions, but not the `down` function due to change in `tearDown` method.

**Comment by menghanl** [comment]
`tearDown` calls [`handleSubConnStateChange`](https://github.com/menghanl/grpc-go/blob/4318e6475c4b2660f7b8ddb77a4504da77311504/clientconn.go#L1148), which will eventually trigger v1 balancer wrapper's [`HandleSubConnStateChange`](https://github.com/menghanl/grpc-go/blob/4318e6475c4b2660f7b8ddb77a4504da77311504/balancer_v1_wrapper.go#L231) being called with `Shutdown` state.

The `HandleSubConnStateChange` function in v1 balancer wrapper calls the `down` function whenever the `SubConn`'s state changes from `Ready` to non-`Ready`.

So, when a `SubConn`'s `tearDown` gets called, the corresponding `down` function should eventually be called by the v1 balancer wrapper (because of the state transition that happens after `tearDown`).

**Comment by gyuho** [comment]
> The HandleSubConnStateChange function in v1 balancer wrapper calls the down function whenever the SubConn's state changes from Ready to non-Ready.

Then `down(errConnClosing)` is only called in such case.

https://github.com/grpc/grpc-go/blob/57ebb0fa1c896a23101f49b61dd887313fbcd055/balancer_v1_wrapper.go#L236-L242

This is different than how v1.6.0 handles drained connections, right?
v1.6.0 calls directly `down(errConnDrain)` when removing a connection in `lbWatcher`.

Please correct me if I am wrong.

Thanks!

**Comment by menghanl** [comment]
v1.6.0 calls `down(errConnDrain)` if `down` is not nil, which means `Up` was called.
If the ac was never Up, `down` will be nil, and `tearDown` won't call it.

In balancer wrapper, `Up` is called when state goes from non-Ready to Ready, and `down` is called when it goes from Ready to non-Ready. `tearDown` for a Ready SubConn will call its `down` function.
The behavior should be the same.

**Comment by menghanl** [comment]
If you mean the timing is different, that might be right.
In v1.6.0, `down` is called immediately when `tearDown` is called, while in balancer wrapper, `down` will be called when the state change is propagated to the balancer.

**Comment by gyuho** [comment]
@menghanl Think our clientv3 can internally handle this.
Thanks for response!
