### ISSUE TITLE
Compressor not installed for grpc-encoding "identity"

### ISSUE THREAD

**Issue by aaronbee** [grpc/grpc-go#1654]
### What version of gRPC are you using?
Server: Go, master branch, revision 4318e6475c4b2660f7b8ddb77a4504da77311504
Client: Python, grpc v1.1.1

### What version of Go are you using (`go version`)?
go1.9.2

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
Attempt to have a Python gRPC client connect to Go gRPC server and execute RPCs.

### What did you expect to see?
Successful connection and execution of RPC.

### What did you see instead?
The server returned this error: 
```
StatusCode.INTERNAL, grpc: Compressor is not installed for grpc-encoding "identity"
```

The connection succeeds when using gRPC v1.7.2 on the Go server.

Possibly related to https://github.com/grpc/grpc-go/commit/5db344a40acb427635d1a2da686decd1ad6b7835

**Comment by dfawley** [comment]
Thanks for the bug.

Looks like an encoding of "identity" is a thing in our spec: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests

So we need to support it.  I'll take a look.

**Comment by tsuna** [comment]
Any update on this bug?

**Comment by dfawley** [comment]
I have a fix for this almost ready, I should be able to get it out for review tomorrow.

**Comment by tsuna** [comment]
Cool.  I send a PR (#1660) with a quick fix to always add a simple `identity` compression codec but maybe you had something else in mind.  At least this simple code change fixed the problem for us.

**Comment by dfawley** [comment]
#1664 is out for review, and should hopefully be the complete fix for this (and other small but previously-undiscovered issues).  Things are a bit confusing with both the old and new compressor APIs in flight, so I added a doc to help explain it (and to help me implement it!).
