### ISSUE TITLE
Unable to go get gRPC

### ISSUE THREAD

**Issue by subbu05** [grpc/grpc-go#1661]
go get google.golang.org/grpc
# google.golang.org/grpc/transport
go/src/google.golang.org/grpc/transport/http_util.go:485:6: f.fr.SetReuseFrames undefined (type *http2.Framer has no field or method SetReuseFrames)

 go version
go version go1.9.2 darwin/amd64

Darwin MACPC 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

**Comment by MakMukhi** [comment]
You need to update your net/http2 package. Try go get -u.

**Comment by FX-HAO** [comment]
Got the same issue on go 1.9. Branch `master` of `golang.org/x/net` does not fix the issue. Then I  used `release-branch.go1.9` branch, the issue was fixed. 
```
cd $GOPATH/src/golang.org/x/net
git fetch --all
git checkout origin/release-branch.go1.9
```
I am using glide, the command is `glide get golang.org/x/net#release-branch.go1.9`.
