### ISSUE TITLE
Finer-grained locks or atomics for addrConn

### ISSUE THREAD

**Issue by menghanl** [grpc/grpc-go#1669]
addrConn has one mutex to protect state, transport and subConn wrappers. Some of them are independent of others and don't need to share the mutex.

related to #1665 and #1666

**Comment by dfawley** [comment]
@menghanl - do you remember if any of these are on the RPC path and are likely to collide with other frequent operations?  If not (which I believe should be the case), then I don't think this is something we need to worry about too much.

**Comment by menghanl** [comment]
No. This is not on the RPC path. This is mostly for cleanup.
