### ISSUE TITLE
New Compressor/Decompressor API broke interop with old C core

### ISSUE THREAD

**Issue by dzbarsky** [grpc/grpc-go#1671]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

go server @ 409fd8e23b1b48140bc8dc73950f762063baa859, old C core client

### What version of Go are you using (`go version`)?

1.8

### What operating system (Linux, Windows, …) and version?

ubuntu 16.04

### What did you do?

Send rpc from old client, it comes with `Grpc-Encoding: identity` header which fails due to https://github.com/grpc/grpc-go/commit/5db344a40acb427635d1a2da686decd1ad6b7835#diff-fbfc8ce05aefe6707b98c99fa7317602R100

### What did you expect to see?

Go server should not break interop with clients.

### What did you see instead?

Breaking changes.

**Comment by menghanl** [comment]
Thanks for filing the issue. The fix for `identity` is in #1664.

**Comment by dfawley** [comment]
There's already an issue for this: #1654
