### ISSUE TITLE
Closing a connection fails all future calls to that address even after a Dial

### ISSUE THREAD

**Issue by sougou** [grpc/grpc-go#1675]
### What version of gRPC are you using?
1.7.1
### What version of Go are you using (`go version`)?
1.9
### What operating system (Linux, Windows, …) and version?
Linux
### What did you do?
Two vitess users were affected by this:
```
conn1 := Dial("addr")
conn1.Exec()  // works
conn1.Close()
...
conn 2 := Dial("addr") // same address as before
conn2.Exec() // returns context canceled errors
```

### What did you expect to see?
conn2.Exec() should have worked

### What did you see instead?
All calls failed.

I think `Close` should become a no-op because connections are multiplexed under the covers? For now, we're working around by commenting out all calls to Close.

Let us know if there's a better way out.

**Comment by dfawley** [comment]
Connections are not shared between ClientConns.  This doesn't sound at all expected, and I'd be surprised if we don't have at least one test that creates multiple connections and closes in between -- would it be possible for you to put together a small repro case that demonstrates this?

**Comment by sougou** [comment]
Thanks for the quick response. This is basically from code that works with 1.6.0, but fails on 1.7.1. Commenting out the `Close` calls fixed the problem.

It's possible that we're not using the connections correctly in the first place, which might have accidentally worked with 1.6.0. I'll post back here with what I find.

**Comment by sougou** [comment]
I wan't able to reproduce this using a trivial test. The additional data point is that the user was getting this error in a tight loop until the call failed:

`W1114 19:16:07.712290 330818 clientconn.go:1028] grpc: addrConn.transportMonitor exits due to: connection error: desc = “transport: error while dialing: dial tcp: operation was canceled"`

Seems to be originating from go runtime, but also due to a canceled context.

**Comment by sougou** [comment]
cc @demmer @tirsen

**Comment by sougou** [comment]
More update: I was able to reproduce that error by adding `grpc.FailOnNonTempDialError(true)`. So, that's not it.

My theory right now is that the continuous spam of opening and closing connections is causing one of the servers (vttablet) to be too slow to respond, and fail a request we don't retry on.

If we didn't close connections, it's likely that grpc reused the underlying connection and multiplexed the requests over it, which avoided the timeout error. We'll run some more tests tomorrow to confirm.

**Comment by dfawley** [comment]
> If we didn't close connections, it's likely that grpc reused the underlying connection

We do not reuse connections across `ClientConn`s.  If the dialing context is being canceled, that would explain the error -- are you reusing the same context in subsequent `grpc.DialContext` calls perhaps?

**Comment by sougou** [comment]
The user (@tirsen) worked around this by just going back to an older snapshot. They were in a hurry, and couldn't wait.

For now, I'll add a retry on that failed call, and we'll see how it goes the next time they retry the workflow. I'll close this bug for now. We can always re-open if the work-around fails.
