### ISSUE TITLE
balancer.go#watchAddrUpdates would abandon updates if lbWatcher method busy ?

### ISSUE THREAD

**Issue by hotdust** [grpc/grpc-go#1677]
a part of balancer.go#watchAddrUpdates source as following:
```
	select {
	case <-rr.addrCh:
	default:
	}
	rr.addrCh <- open
```

It seems that before sending open to rr.addrCh, clean rr.addrCh chan empty. because balancer_v1_wrapper.go#lbWatcher handles rr.addrCh, if lbWatcher is busing to process addrs, meanwhile watchAddrUpdates accepts two updates notifications, the first one of notification will be abandoned. 

Is than right?

Please answer these questions before submitting your issue.
### What version of gRPC are you using?
Master 2017.11.17

**Comment by menghanl** [comment]
This channel is used to send address updates from balancer to ClientConn. ClientConn will create/close connections based the received addresses.
Thus, if there's a new update to notify ClientConn before the previous one gets processed, the old one is not needed anymore. Only the latest update matters.

One other thing to mention here is, `balancer.go` is the old balancer APIs. If you are trying to create your own custom balancer, please take a look at the new [balancer package](https://github.com/grpc/grpc-go/tree/master/balancer).

**Comment by hotdust** [comment]
> One other thing to mention here is, balancer.go is the old balancer APIs. If you are trying to create your own custom balancer, please take a look at the new balancer package.

thank you for additional information
