### ISSUE TITLE
Client keepalives and keepalive.EnforcementPolicy

### ISSUE THREAD

**Issue by mwf** [grpc/grpc-go#1686]
### What version of gRPC are you using?
1.7.3

### What version of Go are you using (`go version`)?
go1.8.3

### What operating system (Linux, Windows, …) and version?
Linux/MacOS 

Hi guys, I have a small question regarding EnforcementPolicy behaviour https://github.com/coreos/etcd/issues/8905

I've played around the latest stable etcd version and noticed no visible client errors when `EnforcementPolicy.MinTime = 5*time.Second` on server side and `ClientParameters.Time = 1*time.Second`.

```
It's said that if client pings server more often too_many_pings error is returned.
I experimented and set DialKeepAliveTime to 1 sec on client, but almost nothing happened - client Watch operated well and smoothly transferred between nodes on node outage.
The only thing found - just 2 lines in log of 1 server for 15 minutes...

2017-11-22 15:23:01.425657 I | etcdserver/api/v3rpc: transport: Got to too many pings from the client, closing the connection.
2017-11-22 15:36:58.446237 I | etcdserver/api/v3rpc: transport: Got to too many pings from the client, closing the connection.
Maybe it's painful for etcd Client to operate undercover? Just the error is not exposed anywhere?
```

So the question is how does it really operate undercover? Even with more frequent pings then the server must allow my client operates well, discovers connection loss and switches to healthy endpoint without any errors.
What's the intended behaviour in such case? Will there be any additional CPU load on client or some other consequences of bad configuration?

**Comment by MakMukhi** [comment]
When the client gets too_many_pings go away from the server it updates it's keepalive settings.https://github.com/grpc/grpc-go/blob/2ef021f78d5bf8030e14f780caa7f7c9d9488390/clientconn.go#L1064
