### ISSUE TITLE
reuse roundrobin balancer with custom picker?

### ISSUE THREAD

**Issue by predmond** [grpc/grpc-go#1690]
I need to implement a custom balancer that uses rendezvous hashing to select the server (the key is passed in via the context)

I implemented this in the old balancer API by copying the round robin implementation. I would like to avoid this in the new API.

It seems like all I should have to do is implement a new picker. Does it make sense to refactor the roundrobin balancer so a picker can be provided?

**Comment by dzbarsky** [comment]
We hit the same thing, would love to avoid copy-pasting the code this time around especially given that these APIs are marked experimental and keep changing out from under us.

**Comment by therc** [comment]
Same here (consistent hashing with bounded load).

**Comment by menghanl** [comment]
Can you give some more information about what you plan to do and what you will need in the picker implementation?
For example, does a slice of `SubConn`s work for you? Or you will need a map from address to `SubConn`?

**Comment by predmond** [comment]
Sorry for the delay..

Looking at it again I don't think just a slice of SubConns will do. We need some place to store the computed rendezvous weight for each address (for example computed in HandleResolvedAddrs when new addresses are added)

Given a map from address to SubConn we could compute the weight each time but that would not be efficient.

**Comment by menghanl** [comment]
A `map[Address]SubConn` will be provided when a new picker is built. While building the picker, you can calculate the rendezvous weight and store that in the picker. IMO this should be acceptable.

I created a tentative in #1707, please take a look and let me know if that works.

**Comment by predmond** [comment]
I think this will work fine :) I made one comment about Name()
