### ISSUE TITLE
Keep Alive for streaming doesn't work behind Envoy proxy

### ISSUE THREAD

**Issue by cdelguercio** [grpc/grpc-go#1695]
grpc-go version 1.7.2
Go version 1.8.3
Ubuntu 16.04.3

When behind Lyft's Envoy proxy, gRPC keep alive PING frames never fail because Envoy responds to them instead of proxying them to the client. I opened an issue at Envoy here: https://github.com/envoyproxy/envoy/issues/2086 and got this in return:

> PING frames are only hop-by-hop in HTTP/2 and per-connection, and I don't know if there are any sensible proxying semantics if you are splitting a single client stream across multiple upstream hosts for example. I think Envoy should respond to PING, but not forward.

If they are right, is there an alternative to PING frames that should be used for Keep Alive? The solution we agreed on in my issue is that Envoy would implement its own Keep Alive heartbeat, but it seems off that gRPC isn't able to handle Keep Alive behind a proxy.

**Comment by dfawley** [comment]
@ejona86 can you advise on this?

**Comment by ejona86** [comment]
> Envoy responds to them instead of proxying them to the client.

This is working as expected. Keepalive is monitoring a _particular_ TCP connection, which is the same hop-by-hop stuff Envoy is mentioning.

> The solution we agreed on in my issue is that Envoy would implement its own Keep Alive heartbeat

This is exactly what I would suggest. The connection from your backend to Envoy can be quite different from the connection to Envoy from the client. The two will fail at different times (thus Envoy can't depend on backends triggering ping to the client), easily need different keepalive times, connection lifetimes, and more. So keepalive being hop-by-hop is really an intended feature and not a bug.

**Comment by cdelguercio** [comment]
So my use case outlined in the Envoy issue is that I have open streaming gRPC connections to clients who often disconnect ungracefully. Because Envoy doesn't proxy the keep alive frames I am then left with hanging connections. It seems hacky that there is no good way for gRPC to manage its own streaming connections when it is being proxied. Right now I am considering making my streaming connection bidirectional and making my client->server payload a oneof with an initial message or a heartbeat. This feels like an awful solution. Am I missing another gRPC pattern that could be put to use in this situation?

**Comment by ejona86** [comment]
@cdelguercio, you need some level of keepalive support in Envoy. That could be via kernel-provided keepalive. But to do anything other than have keepalive in Envoy in a hack.

Doing your own heartbeat can help. But it sounds like you want the heartbeat to be from the server to the client, since you want Envoy to notice when the TCP connection is broken. Triggering a write is a good way to do that.

**Comment by cdelguercio** [comment]
Ah so here's the next problem. When a client ungracefully disconnects, triggering a Send() doesn't cause an error. Here's my code:

```
myProto := &pb.MyProto{}
err = stream.Send(myProto)
if err != nil {
	fmt.Printf("Stream failed: %v", err)
	return err
}
```

**Comment by cdelguercio** [comment]
Envoy never notices the failure. Only when I bypass Envoy do I get a delayed response to the dropped connection.

**Comment by dfawley** [comment]
This sounds like an Envoy problem, then, since it works without Envoy.

**Comment by mpuncel** [comment]
Is RST_STREAM the mechanism used by grpc to cancel a stream (e.g. when you cancel a `context.Context`)?

**Comment by menghanl** [comment]
@mpuncel Yes.
