### ISSUE TITLE
Flaky test: TestTimeoutOnDeadServer

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#1700]
```
--- FAIL: TestTimeoutOnDeadServer (0.00s)
        end2end_test.go:520: Running test in tcp-clear-v1-balancer environment...
        end2end_test.go:837: TestService/EmptyCall(context.Background.WithDeadline(2017-11-10 21:59:58.840767983 +0000 UTC [785.444µs]), _) = _, rpc error: code = Unavailable desc = transport is closing, want _, error code: DeadlineExceeded
```

**Comment by menghanl** [comment]
This might be caused by this `select` in `Write()`
https://github.com/grpc/grpc-go/blob/c6b46087ab923e9f453ec433f99174cdd45b9b89/transport/http2_client.go#L640-L648

**Comment by dfawley** [comment]
Apparently this is caused by https://github.com/golang/go/issues/10527; `listener.Accept()` can return a connection even after `listener.Close()` has returned.  Our tests are assuming this is impossible.

The workaround I will employ is to add a `WaitForHandshake` to the `DialOption`s for these tests; that way RPCs won't be scheduled until after the server's preface has been received, which will never happen because the server was closed.  (Actually, I believe I'll also have to add/move a check to ensure that is the case.  I.e. the following:)

https://github.com/grpc/grpc-go/blob/cce0e436e5c428f2094edd926779788f1024938d/server.go#L524-L530

**Comment by dfawley** [comment]
Actually, it looks like this protects us from starting a http2 transport for the connection:

https://github.com/grpc/grpc-go/blob/cce0e436e5c428f2094edd926779788f1024938d/server.go#L558-L562
