### ISSUE TITLE
Lock-Free dedicated write goroutne

### ISSUE THREAD

**Issue by Zeymo** [grpc/grpc-go#1702]
I customed grpc-go but use same goroutine model, in 8core 16g  linux server with 64 connetions per client

no-dedicated-goroutine_no-speed-up-pool_64-conn_30000-qps_12-clients_1000-concurrency
 >  Min : 2 , 50th pct : 13 , 75th pct : 24 , 95 pct : 49 , 99 pct : 99 , Max : 497 , Mean :19

dedicated-goroutine_speed-up-pool_64-conn_30000-qps_12-clients_1000-concurrency
 >  Min : 2 , 50th pct : 25 , 75th pct : 48 , 95 pct : 125 , 99 pct : 367 , Max : 1789 , Mean :45

It seems that a dedicated write goroutine is not efficiency enough under heavy load , lock-free queue maybe better

In addition , what about remove `defer` of inFlow like transport ?

**Comment by dfawley** [comment]
Not sure if we have another issue that encapsulates this, but we are working on it (and have been for a week or two).

**Comment by dfawley** [comment]
We'll track this under #1512. Thanks.
