### ISSUE TITLE
Cannot dial addresses with `tcp://` prefix on 1.8.0

### ISSUE THREAD

**Issue by ebuchman** [grpc/grpc-go#1705]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

v1.8.0

### What version of Go are you using (`go version`)?

v1.9.2

### What operating system (Linux, Windows, …) and version?

Mac Sierra

### What did you do?

1. Run grpc server
2. Run grpc client that dials server on `tcp://0.0.0.0:46658`
3. Send a simple message from client

### What did you expect to see?

Client should connect to server, send the message, and receive a response.

### What did you see instead?

Client failed to send message with:

```
rpc error: code = Unavailable desc = all SubConns are in TransientFailure
```

Note it works fine if I remove the `tcp://` prefix or downgrade to v1.7.3.

It does not work if I try to use a unix socket, with or without `unix://`. But it does work on v1.7.3 (with the prefix).

For the record, here is the consuming project: https://github.com/tendermint/abci

Thanks!

**Comment by menghanl** [comment]
The dial target syntax is `scheme://authority/endpoint_name` as defined in [grpc/naming.md](https://github.com/grpc/grpc/blob/master/doc/naming.md).

The target you dialed to (`tcp://0.0.0.0:46658`) couldn't be parsed correctly, so no connection can be established.

I believe `tcp:///0.0.0.0:46658` (not the triple `/`) or just `0.0.0.0:46658` would work. Please give it a try.

**Comment by menghanl** [comment]
Closing this. Filed a new issue to track scheme "unix".
