### ISSUE TITLE
New resolver API is less usable than previous iteration

### ISSUE THREAD

**Issue by dzbarsky** [grpc/grpc-go#1710]
We use a custom resolver to do service discovery - it works by connecting to an SD server with a streaming response RPC and watching for update. With the previous resolver API, we would create an object that implemented `grpc_naming.Watcher` on top of this watcher, which gave us a lot of flexibility in how we issue the original RPC to SD server (for example we can limit how many servers are returned)

With the new API, there is no nice way to inject custom per-client behavior/object into the resolver implementation. The closest thing we've found is to make the `Target` contain "query params", but serializing/parsing our options to a string is a pretty clear regression.

It seems like what we would like is custom `BuildOptions` for the ResolverBuilder, and pass in those `BuildOptions` at client creation time (so `WithResolver(resolverName) -> WithResolver(resolverName, Options{Limit:4})` or such.  This is probably useful for other folks implementing custom resolver as well. Thoughts?

**Comment by menghanl** [comment]
Added a DialOption `WithResolverUserOptions` in #1711. Please take a look.

**Comment by dzbarsky** [comment]
great, that works for me. thanks!

**Comment by ejona86** [comment]
I'm arguing we need to remove the `WithResolverUserOptions` in #1812. @dzbarsky, I assume you'll want to speak up and maybe explain some of the difficulties of your use case.

**Comment by alecthomas** [comment]
I just opened #1860, then found this. We have the same issue as @dzbarsky.
