### ISSUE TITLE
Does CloseSend() flush the stream?

### ISSUE THREAD

**Issue by apoydence** [grpc/grpc-go#1714]
When writing data into a stream (via `Send()`), is there a way to "flush" the data before closing the connection?

I thought/hoped that `CloseSend()` would do so, but I don't see anything in the docs.

**Comment by dfawley** [comment]
`Send` will make sure the data gets flushed for each message.  Not before returning, but the message will be put on the wire very soon with no need to manually flush anything.

- On clients, if you want to make sure the data has been sent before calling `Close` on the `ClientConn`, then wait for `Recv` to return `io.EOF`.
- On servers, you should use `GracefulStop` to make sure in-flight RPCs finish before closing the server.

**Comment by apoydence** [comment]
If I do not have a bidirectional stream, then would `CloseAndRecv` suffice?

**Comment by dfawley** [comment]
Yes.  `CloseAndRecv` is basically just a wrapper for `CloseSend` and `RecvMsg`.  As a special case, `RecvMsg` for client-only-streaming RPCs will block until the final status of the RPC is received from the server.

**Comment by apoydence** [comment]
Thanks that worked.
