### ISSUE TITLE
Support IDLE_TIMEOUT (client-side)

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-go#1719]
[IDLE_TIMEOUT](https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md) is defined as a way for clients to drop unused connections after inactivity.

I could not find an API for this in Go. Java has [had support](https://grpc.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#idleTimeout-long-java.util.concurrent.TimeUnit-) since 1.0. Note that in Java, when the IDLE_TIMEOUT is reached, the NameResolver and LB are shutdown, returning the Channel to the same state as initially created. This does cause a nomenclature problem, because there are two levels of IDLEness; we've been calling the shutting down of all IO (NR and LB) "idle mode."

The server-side equivalent [is MAX_CONNECTION_IDLE](https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md). But both are necessary.

C doesn't support this either (grpc/grpc#13212). It's likely more important for C as it can be very useful on mobile. But it is commonly a better alternative to KEEPALIVE_WITHOUT_CALLS and, since KEEPALIVE_WITHOUT_CALLS is not necessarily permitted, can be necessary.

**Comment by dfawley** [comment]
Note that this needs a solution to #1786 which is about supporting idleness in general.

**Comment by beef9999** [comment]
Looks like I have to add a timer to implement client_idle_timeout by myself.
Also I noticed that gRPC C++ version had already implemented this feature.

**Comment by ejona86** [comment]
@beef9999, I don't think C++ has implemented this. I think Java is the only language to have this implemented.

Server-side idle timeout is a bit different, simply because different clients may need different settings and server-side doesn't achieve that. Also, with multiple LB policies (and all the time in grpc-go), when the client receives a GOAWAY it just reconnects.

**Comment by dfawley** [comment]
Fixed by #6263
