### ISSUE TITLE
no way to set background context of rpc server

### ISSUE THREAD

**Issue by stevvooe** [grpc/grpc-go#172]
There doesn't seem to be a way to control the root context of the server. For example, it would be nice to have at least something like the following:

```
ctx := MySpecialContext()
s := NewServer(WithContext(ctx))
```

Such that the `context` passed to an implemented rpc method descends from the above:

```
func (mg *myGreeter) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {}
```

Following from that, there doesn't seem to be a way to "prepare" a context using headers. One could imagine a per-request context preparation that incorporates header metadata (ie spans, auth, metrics, etc.) at the entire sever-level.

I may be missing API details in the documentation.

**Comment by dsymonds** [comment]
Contexts are request-scoped (see http://blog.golang.org/context). What would it mean for a server-wide context? If something is server-wide, it doesn't belong in a context.

**Comment by stevvooe** [comment]
@dsymonds The blog post outlines other uses as "cancelation signals, and deadlines across API boundaries to all the goroutines involved in handling a request". Not all of these boundaries may be exclusive to the request scope.

Imagine an API that could be used as part of a request-scoped server or client-side:

```
func GetStuff(ctx context.Context) (Stuff, error) { ... }
```

This method may use something in context but it doesn't care whether or not the context is request-scoped. Subsequently, we may configure the default resources used by `GetStuff` in a background context that then _may_ be replaced at request time with something more specific to the context.

There may also be information setup in the background context that is service-wide but doesn't make sense to pass explicitly, such as loggers and tracing facilities.

**Comment by dsymonds** [comment]
Either you misread, or the blog post needs clarifying. That "API boundaries" reference does not suddenly let contexts escape from being request scoped. @Sajmani

**Comment by stevvooe** [comment]
@dsymonds That is a blog post I have read several times. I understand that the values are request scoped. There are cases where one wants to control the instantiation of the background context. Here is [an example](https://github.com/golang/appengine/blob/master/internal/api.go#L248), written by you.

**Comment by dsymonds** [comment]
`internal.BackgroundContext` is not a good counter example. It is an edge case that is somewhat unfortunate and largely dictated by how App Engine works. It is not a model for how to otherwise write good Go APIs. If I were to redo everything in the entire Go App Engine ecosystem then that function may not even exist.

**Comment by stevvooe** [comment]
@dsymonds How would you accomplish the same task now?

**Comment by iamqizhao** [comment]
I have not seen a strong reason to have a server-scoped context so far. Close this now.

**Comment by stevvooe** [comment]
@iamqizhao @dsymonds Any insight implementing similar functionality to `internal.BackgroundContext`? A little more advice than "don't do that" would be helpful.

Allowing one to set the server context provides a mechanism to control the background context used in requests. The main reasoning behind requiring a server-scoped context is to avoid having different ways of transmitting contextual values depending on the use case.

**Comment by menghanl** [comment]
@ilius You can append content to context using interceptor: https://godoc.org/google.golang.org/grpc#UnaryInterceptor
