### ISSUE TITLE
does ClientConn.Close() actually teardown connections or does that happen in the background?

### ISSUE THREAD

**Issue by nhooyr** [grpc/grpc-go#1726]
https://github.com/grpc/grpc-go/blob/cce0e436e5c428f2094edd926779788f1024938d/clientconn.go#L887

Docs say it tears down all the underlying connections but as far as I can tell, it just closes channels and sets state. It doesn't return any error except for ErrClientConnClosing either. Does the teardown happen in the background? If so, the docs should be clarified to reflect that.

**Comment by MakMukhi** [comment]
`Close()` cancels the clientConn context which results in closing of all underlying transports.
https://github.com/grpc/grpc-go/blob/cce0e436e5c428f2094edd926779788f1024938d/clientconn.go#L889

**Comment by nhooyr** [comment]
@MakMukhi shouldn't the docs on `Close()` be updated?

**Comment by nhooyr** [comment]
@MakMukhi ping.

**Comment by MakMukhi** [comment]
Would you like the docs to say something like "although `clientconn.Close` returns the underlying transports may have not finished closing yet" ? Such behavior, by the way, is true for a lot of other things too; for instance, a `stream.Send` may return but the message might not have been written on the wire yet. 
I don't see how these subtle implementation details affect using of the API.
Do you have a suggestion on how you want the documentation to be updated and why is it important for your use-case?

**Comment by nhooyr** [comment]
It was important for my use case because I wanted to know if Close() would take a long time or not. I was writing a map for grpc connections to different hosts (each host is of the same service type) and after a single host was not used for a while, I wanted to close it.

But I wanted to make sure that Close() would not send a message and then wait or anything like that would could take a relatively long time when the map is locked. I could have closed all old connections in a loop after the all old connections were deleted from the map but I was just curious whether it would take a lot of time and if I would need to do that.

Yes, what you suggested would be fine. However, after reading your response, I'm not positive because you're right, it is true for many other things.
