### ISSUE TITLE
`godep save` fails on empty grpc_lb_v1 package for grpc 1.6+

### ISSUE THREAD

**Issue by jpbetz** [grpc/grpc-go#1733]
When [upgrading kubernetes from grpc 1.3.0 to 1.7.4](https://github.com/kubernetes/kubernetes/issues/56114), `godep save` reported this error:

```
godep: no buildable Go source files in /usr/local/google/home/jpbetz/Projects/k8s/src/k8s.io/kubernetes/_output/local/go/src/google.golang.org/grpc/grpclb/grpc_lb_v1                                                                                                                              
 !!! Error in hack/godep-save.sh:69
...
```

After locally adding a `doc.go` placeholder file to the `grpc/grpclb/grpc_lb_v1` dir in grpc source, the `godep save` command ran successfully.

I'll attempt to create a minimal example that reproduces the issue.

```
go version go1.9.1 linux/amd64
godep v79 (linux/amd64/go1.8.1.typealias)
kubernetes master (@ b97e17603b)
```

**Comment by jpbetz** [comment]
Was able to resolve this. Once the `grpc/grpclb/grpc_lb_v1` package was excluded (`godep get google.golang.org/grpc/...` will exclude it) as will removing it from `Godeps.json`, godeps correctly ignored the directory.

**Comment by jpbetz** [comment]
godep issue: https://github.com/tools/godep/issues/554

**Comment by dfawley** [comment]
Thanks!  I had a feeling that was the problem -- we have no .go files in that path, so the error is accurate; it's just not clear why it would be an error.

**Comment by jpbetz** [comment]
@dfawley If you're willing to merge it, https://github.com/grpc/grpc-go/pull/1743 would be a huge help to kubernetes for getting grpc upgraded. We're currently stuck on 1.3.0. We'd need a new 1.7.x cut with it though..
