### ISSUE TITLE
Recv error race condition on gRPC server stream when calling CloseSend on gRPC client stream

### ISSUE THREAD

**Issue by willhug** [grpc/grpc-go#1735]
### What version of gRPC are you using?

v1.8.2

### What version of Go are you using (`go version`)?

1.9

### What operating system (Linux, Windows, …) and version?

OSX 10.11.6

### What did you do?

Wrote an example to simulate streaming between a client and a server.  In the tests, I validate that calling `CloseSend` from a client will cause an `io.EOF` error on the `Recv` method of the server.  

`server.go`:
```go
package main

import (
	"fmt"
	"google.golang.org/grpc"
	"net"
)

type customCodec struct{}

func (customCodec) Marshal(obj interface{}) ([]byte, error) {
	return obj.([]byte), nil
}

func (customCodec) Unmarshal(data []byte, obj interface{}) error {
	value := obj.(*[]byte)
	*value = data
	return nil
}

func (customCodec) String() string {
	return "yarpc"
}

func handle(_ interface{}, serverStream grpc.ServerStream) error {
	var msg []byte
	err := serverStream.RecvMsg(&msg)
	if err != nil {
		panic(err)
	}
	if string(msg) != "first message" {
		panic("did not receive correct message on server")
	}

	err = serverStream.SendMsg([]byte("second message"))
	if err != nil {
		panic(err)
	}

	var msg2 []byte
	err = serverStream.RecvMsg(&msg2)
	if err == nil {
		panic("should have been an error, what?")
	}
	fmt.Println("Ended stream with: ", err.Error())
	return nil
}

func main() {
	server := grpc.NewServer(
		grpc.CustomCodec(customCodec{}),
		grpc.UnknownServiceHandler(handle),
	)
	listener, err := net.Listen("tcp", "127.0.0.1:12345")
	if err != nil {
		panic(err)
	}
	server.Serve(listener)
}
```

`client.go`:
```go
package main

import (
	"context"
	"google.golang.org/grpc"
)

type customCodec struct{}

func (customCodec) Marshal(obj interface{}) ([]byte, error) {
	return obj.([]byte), nil
}

func (customCodec) Unmarshal(data []byte, obj interface{}) error {
	value := obj.(*[]byte)
	*value = data
	return nil
}

func (customCodec) String() string {
	return "yarpc"
}

func main() {
	clientConn, err := grpc.Dial(
		"127.0.0.1:12345",
		grpc.WithInsecure(),
		grpc.WithCodec(customCodec{}),
	)
	if err != nil {
		panic(err)
	}
	clientStream, err := clientConn.NewStream(
		context.Background(),
		&grpc.StreamDesc{
			ClientStreams: true,
			ServerStreams: true,
		},
		"test/test",
	)

	err = clientStream.SendMsg([]byte("first message"))
	if err != nil {
		panic(err)
	}

	var msg []byte
	err = clientStream.RecvMsg(&msg)
	if err != nil {
		panic(err)
	}
	if string(msg) != "second message" {
		panic("did not receive correct message")
	}

	err = clientStream.CloseSend()
	if err != nil {
		panic(err)
	}
}
```

Essentially we start up a gRPC server with a handler that will sequentially perform the actions:
1) Receive a Message, expect that message to equal "first message"
2) Send a Message "second message"
3) Receive a Message and expect that Recv call to error, print the error

And the client performs the following actions when calling the stream:
1) Send a message "first message"
2) Receive a message, expect that message is equal to "second message"
3) Close the stream (call `CloseSend` on the gRPC stream)

### What did you expect to see?

I expected that the error returned from the Recv on the handler would be an io.EOF every time.

I want console output:
`server`
```
% go run server/main.go
Ended stream with:  EOF
```
`client`
```
% go run client/main.go
```

### What did you see instead?

About 50% of the time we will get the io.EOF error, the rest of the time we get a grpc error with message:"context canceled" and code:"Canceled".

With multiple client calls, the server logs look like:
```
% go run server/main.go
Ended stream with:  rpc error: code = Canceled desc = context canceled
Ended stream with:  EOF
Ended stream with:  rpc error: code = Canceled desc = context canceled
Ended stream with:  rpc error: code = Canceled desc = context canceled
Ended stream with:  rpc error: code = Canceled desc = context canceled
Ended stream with:  EOF
Ended stream with:  EOF
```
I took a bit of a look into the http2 server when I noticed this and I believe that there's a race with the context of the stream being cancelled before the Recv method has been called.

It's possible this is expected since the `Stream.RecvMsg` docs state: `On server side, it simply returns the error to the caller.` which doesn't guarantee any consistency on the errors returned from Recv in the handler.  However, if I change the client code to explicitly **panic** on the request (instead of calling CloseSend), the server only sees the `rpc error: code = Canceled desc = context canceled` error, which means that the server has no clue whether a Client ended "properly" or completely crashed.

**Comment by willhug** [comment]
cc @peter-edge, @abhinav

**Comment by MakMukhi** [comment]
@willhug Thanks for reporting, I'll try and take look at it today.

**Comment by willhug** [comment]
@MakMukhi this may actually not be necessary.  Just modified the client function to have a `time.Sleep(time.Minute)` at the end of the main, and all the errors turned into `io.EOF`.

This looks like it might have been legitimately "the client doesn't exist anymore" context canceled.  Still weird, but likely the right thing in most cases.

I think my problem was invalid, going to close.

**Comment by willhug** [comment]
![you_didnt_see_anything_madagascar](https://user-images.githubusercontent.com/613317/33969959-58ef3098-e025-11e7-8179-aaf42daced17.gif)

**Comment by MakMukhi** [comment]
Lol! I was actually going to reply with the same thing. I added a second sleep and things seemed fine. To make sure all grpc related goroutines exit you can use `leakcheck` : https://github.com/grpc/grpc-go/blob/8fba5fc8fd4073dd1452d6b2c7335030848a41b1/test/leakcheck/leakcheck.go#L22

**Comment by willhug** [comment]
oh cool! thanks for the tip!
