### ISSUE TITLE
grpclog: grpc internal logging should respect log verbosity

### ISSUE THREAD

**Issue by gyuho** [grpc/grpc-go#1758]
### What version of gRPC are you using?

v1.7.4

### What version of Go are you using (`go version`)?

Go 1.9.2

#### Problem

Balancer wrapper info logging does not respect verbosity

https://github.com/grpc/grpc-go/blob/2720857d978b9873027f6d739d74794428f49c03/balancer_v1_wrapper.go#L124-L126

where you can set with

```go
SetLogger(grpclog.NewLoggerV2WithVerbosity(os.Stderr, os.Stderr, os.Stderr, 4))
```

Only `transport` package respects verbosity, while others don't.

https://github.com/grpc/grpc-go/blob/2720857d978b9873027f6d739d74794428f49c03/transport/log.go#L28-L32

Could we add verbosity check to all internal logging?

ref. https://github.com/coreos/etcd/pull/8994

**Comment by menghanl** [comment]
The log you are referring to is a `Info` log. Does it work for you to ignore all the `Info` logs?

Or if you are only interested in `Error`s,
`grpclog.NewLoggerV2WithVerbosity(ioutil.Discard, ioutil.Discard, os.Stderr, 0)` would work.

**Comment by gyuho** [comment]
@menghanl We want to see `Warning/Error/Fatal`, but opt out on `Info` (only when our `--debug` flag is off). So `grpclog.NewLoggerV2WithVerbosity(ioutil.Discard, os.Stderr, os.Stderr, 0)` would totally work.

Feel free to close this.

Thanks!
