### ISSUE TITLE
Low perfomance

### ISSUE THREAD

**Issue by sg3des** [grpc/grpc-go#1762]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
Version = "1.9.0-dev"

### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### What operating system (Linux, Windows, …) and version?
x86_64 GNU/Linux 4.14.8-1-ARCH

### What did you do?
I created a benchmak for a simple server and client from:  https://google.golang.org/grpc/examples/helloworld.  

    BenchmarkGRPC-8           	    5000	    295527 ns/op
    BenchmarkGRPC_Connect-8   	    2000	    898525 ns/op

Result uploaded to git: https://github.com/sg3des/grpc.

### What did you expect to see?
higher performance.

### What did you see instead?
lower performance ^^... 
5000 requests are very slow! 
Is there anyway to speed it up?? thx.

**Comment by menghanl** [comment]
The cpu is not saturated with one unary ping-pong.
If you create more concurrent RPCs, you will see more QPS.

Running our benchmark with 1-byte request 1-byte response for 10 seconds shows over 7000 QPS:
```
go run benchmark/benchmain/main.go -benchtime=10s -workloads=unary -compression=off -maxConcurrentCalls=1 -trace=off  -reqSizeBytes=1 -respSizeBytes=1 -networkMode=Local
Unary-traceMode_false-latency_0s-kbps_0-MTU_0-maxConcurrentCalls_1-reqSize_1B-respSize_1B-Compressor_false: 
50_Latency: 133.1520 µs 	90_Latency: 149.2080 µs 	99_Latency: 188.4030 µs 	Avg latency: 133.4440 µs 	Count: 74822 	7748 Bytes/op	201 Allocs/op	
Histogram (unit: µs)
Count: 74822  Min:  78.8  Max: 4259.3  Avg: 133.44
------------------------------------------------------------
[     78.843000,      78.844000)      1    0.0%    0.0%  
[     78.844000,      78.848441)      0    0.0%    0.0%  
[     78.848441,      78.872606)      0    0.0%    0.0%  
[     78.872606,      79.004092)      0    0.0%    0.0%  
[     79.004092,      79.719529)      0    0.0%    0.0%  
[     79.719529,      83.612338)      3    0.0%    0.0%  
[     83.612338,     104.793739)   3831    5.1%    5.1%  #
[    104.793739,     220.045163)  70441   94.1%   99.3%  #########
[    220.045163,     847.146781)    536    0.7%  100.0%  
[    847.146781,    4259.308000)      9    0.0%  100.0%  
[   4259.308000,            inf)      1    0.0%  100.0%
```

If concurrent RPC count is increased to 10 (by changing `-maxConcurrentCalls=10`), QPS is about 40000.
```
go run benchmark/benchmain/main.go -benchtime=10s -workloads=unary -compression=off -maxConcurrentCalls=10 -trace=off  -reqSizeBytes=1 -respSizeBytes=1 -networkMode=Local
Unary-traceMode_false-latency_0s-kbps_0-MTU_0-maxConcurrentCalls_10-reqSize_1B-respSize_1B-Compressor_false: 
50_Latency: 218.5850 µs 	90_Latency: 287.4020 µs 	99_Latency: 710.9700 µs 	Avg latency: 237.5280 µs 	Count: 420160 	7101 Bytes/op	148 Allocs/op	
Histogram (unit: µs)
Count: 420160  Min:  92.7  Max: 4357.5  Avg: 237.53
------------------------------------------------------------
[     92.660000,      92.661000)       1    0.0%    0.0%  
[     92.661000,      92.665453)       0    0.0%    0.0%  
[     92.665453,      92.689738)       0    0.0%    0.0%  
[     92.689738,      92.822169)       0    0.0%    0.0%  
[     92.822169,      93.544349)       0    0.0%    0.0%  
[     93.544349,      97.482580)       0    0.0%    0.0%  
[     97.482580,     118.958762)     141    0.0%    0.0%  
[    118.958762,     236.073878)  277758   66.1%   66.1%  #######
[    236.073878,     874.732587)  141704   33.7%   99.9%  ###
[    874.732587,    4357.502000)     555    0.1%  100.0%  
[   4357.502000,            inf)       1    0.0%  100.0%
```

**Comment by MakMukhi** [comment]
@sg3des Thanks for intimating us of your findings.

QPS numbers are subjective to the machine that you're using. Try and saturate your resources by varying number of connections and number of concurrent streams. May be start with 100 connections each with 100 concurrent streams. 

Also, we are actively working on performance and tracking it in issues #1512 and #1280.
Since this issue has misleading numbers and is a dupe I'm going to go ahead and close this one.
