### ISSUE TITLE
How to count active connections?

### ISSUE THREAD

**Issue by ivanjaros** [grpc/grpc-go#1773]
I would like to expose an rpc call that would provide brief information about the server and one thing I cannot figure out is how to get the number of active connections?
I've looked at the code but the Server.conn is simply inaccessible from any callback I've looked at.

Is this even possible at this time, to get this information?

**Comment by MakMukhi** [comment]
You should be able to do that and more using a `stats.Handler`. Look into
the `stats` package and see it helps your use case.

**Comment by dfawley** [comment]
Please let us know if that didn't help or you need more information.  Thanks!
