### ISSUE TITLE
go get -u google.golang.org/grpc i/o timeout

### ISSUE THREAD

**Issue by kingeasternsun** [grpc/grpc-go#1780]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
      the latest
### What version of Go are you using (`go version`)?
1.8
### What operating system (Linux, Windows, …) and version?
ubuntu14
### What did you do?
If possible, provide a recipe for reproducing the error.

### What did you see instead?

for the reason everyone knows, the chinese people can not access google.golang.org,  so whether the developers can use https://github.com/grpc/grpc-go to install the pkg

**Comment by menghanl** [comment]
Please set up VPN and try again.

Or, do a `git clone` instead:
```
git clone https://github.com/grpc/grpc-go.git $GOPATH/src/google.golang.org/grpc
```
This won't download gRPC's dependencies (and unfortunately, many of the dependencies are hosted on `golang.org`). So you will need to clone them, too.
