### ISSUE TITLE
How is compression supposed to be used?

### ISSUE THREAD

**Issue by bboreham** [grpc/grpc-go#1789]
### What version of gRPC are you using?
master

### What version of Go are you using (`go version`)?
1.9.1

### What operating system (Linux, Windows, …) and version?
Linux; Ubuntu 16.04

### What did you do?
I read the docs and Googled for things like 'go grpc compression'

### What did you expect to see?
Clear instructions on how to use compression

### What did you see instead?

`WithCompressor` says "Deprecated: use UseCompressor instead."
`UseCompressor` says "This API is EXPERIMENTAL"

Should I just avoid the whole thing?

**Comment by dfawley** [comment]
Have you seen: https://github.com/grpc/grpc-go/blob/master/Documentation/compression.md?

`UseCompressor` is marked as experimental mostly as a hedge in case we discover that something doesn't work and it needs to be changed.  There are no expected changes there, but it's possible.

Per [our versioning doc](https://github.com/grpc/grpc-go/blob/master/Documentation/versioning.md) deprecated functions will stick around until the next MAJOR release (which we do not have planned).  Also, a backward-incompatible release is likely to live in another import path (e.g. "grpc/v2").  If you have no tolerance for breakages, use the deprecated API.

**Comment by bboreham** [comment]
Thanks.  I had not seen that doc. 

I would still find it useful to see an example of how to use the calls described, perhaps as an extension to https://github.com/grpc/grpc-go/blob/master/examples/

**Comment by bboreham** [comment]
To get the gzip compressor registered, is the idea that you do:

    import _ "google.golang.org/grpc/encoding/gzip"

?

Also it feels like there should be a constant for `"gzip"` rather than having me type it out and possibly misspell it.

**Comment by dfawley** [comment]
> To get the gzip compressor registered, is the idea that you do:
> `import _ "google.golang.org/grpc/encoding/gzip"`
> ?

Yes, exactly.

> Also it feels like there should be a constant for "gzip" rather than having me type it out and possibly misspell it.

SGTM
