### ISSUE TITLE
Behavior difference between v1 and v2 resolver APIs

### ISSUE THREAD

**Issue by dzbarsky** [grpc/grpc-go#1793]
### What version of gRPC are you using?

master

### What version of Go are you using (`go version`)?
1.8

### What operating system (Linux, Windows, …) and version?
linux 

### What did you do?

I am porting our RPC layer to the new resolver api and it seems things have changed a little bit. We issue non-blocking non-timeout connection with `DialContext` and then do FailFast rpcs on the resulting channel.

We also have an integration test that performs an rpc to an address that refers to a server that does not exist.

With v1 resolver, this scenario would produce an error like so:
```
rpc error: code = Unavailable desc = there is no address available
```
the caller code would see the error and perform fallback logic.

With the v2 resolver API, we see an error like this: 
```
rpc error: code = Canceled desc = context canceled
```
because the context is cancelled, even if the client attempts to do fallback logic, it actually propagates cancellation back to its own caller.

While we can certainly work around this specific failure by creating a background context for the RPC, this behavior change can potentially affect 10K+ rpc callsites for us - basically any code talking to a server that is not up is liable to break in this way :(

Is this intentional? Is there a reason for this? Am I missing something?

**Comment by menghanl** [comment]
What exactly do you mean by "a server that does not exist"?
I tried with target "nothing.addr" which clearly doesn't exist, and got error `rpc error: code = Unavailable desc = all SubConns are in TransientFailure`.

Do you have logs from your program? You can get logs by setting environment variable `GRPC_GO_LOG_SEVERITY_LEVEL=info` to get logs including info.

It will also be great if you can provide a reproduction for this so we can look into what's happening.

**Comment by dzbarsky** [comment]
OK, let me try to come up with a repro

**Comment by menghanl** [comment]
Friendly ping. Did you get time for the repro?

**Comment by dzbarsky** [comment]
We use a custom resolver but even with that, all my attempts to reduce the problem led to the same error you posted (which is what we want). Since this was only affecting one of our services internally out of hundreds I suspect there is something buggy in it. In any case the service was not setting timeouts properly and once that was fixed the context was no longer being cancelled due to shorter timeout. Going to close this out since it's not actionable for you, thanks for following up
