### ISSUE TITLE
Relative import

### ISSUE THREAD

**Issue by ivanjaros** [grpc/grpc-go#1796]
Hi, I have the following directory structure:
```
- Foo
-- foo.pb.go
-- foo.proto
- Bar
-- bar.pb.go
-- bar.proto
```

and I am including Foo into Bar. Unfortunately I am not able to achieve relative path in bar.pb.go import of foo. I always get either `import foo "."` or `import foo "foo"`. I do not want to specify repo path. Hence I have to manually fix this import path each time I compile the proto definition. the `go_package` does not work either.

Is there a way to have this fixed via some option argument?

**Comment by menghanl** [comment]
>  I do not want to specify repo path.

My understanding is that the suggested way is to set the `go_package` option to the import path, which will likely be something containing `github.com/user/project`.

Also, this is not a gRPC specific question.
Please file an issue against the protobuf repo: https://github.com/golang/protobuf
