### ISSUE TITLE
Please add WithBalancerUserOptions API

### ISSUE THREAD

**Issue by dzbarsky** [grpc/grpc-go#1798]
Similar to https://github.com/grpc/grpc-go/pull/1711, it would be useful to setup some balancer params at client creation time and have those passed in for more advanced balancing. (The motivating use-case is consistent hashing, we would like client to be able to specify hash function/seed)

**Comment by menghanl** [comment]
Filed #1807 for this issue. Please take a look.

**Comment by dfawley** [comment]
Is this needed only for per-RPC balancing decisions, or when the balancer is created?

The `balancer.BuildOptions` is passed a `Build`-time.  If you only need this when RPCs are performed, one option would be to pass data from the client to the [Picker](https://godoc.org/google.golang.org/grpc/balancer#Picker) using the context.

cc @ejona86

**Comment by menghanl** [comment]
Closing as discussed in #1812
