### ISSUE TITLE
Mysterious file ".please-update"

### ISSUE THREAD

**Issue by bboreham** [grpc/grpc-go#1799]
This file: https://github.com/grpc/grpc-go/blob/master/.please-update was added in #1479.

It does not seem connected to that change, nor is it mentioned anywhere.

What is it for?

cc @ZhouyihaiDing

**Comment by ZhouyihaiDing** [comment]
Sorry this file doesn't connected to any files.
It was created when my commit and commit --amend doesn't update pull request, it needs .please-update to force pull request update new commit.
https://github.com/grpc/grpc-go/pull/1800
