### ISSUE TITLE
Unary RPCs in server cannot set metadata with alternate transports

### ISSUE THREAD

**Issue by jhump** [grpc/grpc-go#1802]
There is currently an API deficiency in that alternate transports (such as in-process dispatch or other custom mechanisms) cannot support the server sending metadata from unary RPCs.

The issue is that the API for sending metadata from a unary RPC handler is to call `grpc.SetHeader` and `grpc.SetTrailer`. However, these methods *require* that there be an active `*transport.Stream` in [the](https://github.com/grpc/grpc-go/blob/1cd234627e6f392ade0527d593eb3fe53e832d4a/server.go#L1275) [given](https://github.com/grpc/grpc-go/blob/1cd234627e6f392ade0527d593eb3fe53e832d4a/server.go#L1285) [context](https://github.com/grpc/grpc-go/blob/1cd234627e6f392ade0527d593eb3fe53e832d4a/server.go#L1305).

If this API instead expected an interface that provided these three methods (as opposed to the concrete type `*transport.Stream`), then an alternate transport could store its own stream interface in the context, allowing it to receive the metadata and ensure they are delivered to the client.

This would also require making a public API for injecting the stream into a context. Currently, there is only an [unexported method](https://github.com/grpc/grpc-go/blob/1cd234627e6f392ade0527d593eb3fe53e832d4a/transport/transport.go#L440) which puts a `*transport.Stream` into the context (the associated context key is, of course, also unexported).

(Note that, even if this is fixed, there is a client-side problem with receiving the metadata, too: see #1494 and #1495.)

**Comment by dfawley** [comment]
@jhump - How are you injecting an alternate transport into grpc?  Do you have a client interceptor that doesn't use the provided `invoke` function?

**Comment by jhump** [comment]
@dfawley:
1) I have a protoc plugin that generates an alternate implementation of the client interface and a factory function that takes a `Channel` interface.
    * The `Channel` interface exposes the `Invoke` and `NewStream` methods with the same signatures as those on `*grpc.ClientConn`.
    * The alternate implementation is identical to the one that protoc-gen-go emits, except that there's a different struct whose field type is a `Channel`, not `*grpc.ClientConn`.
2) There is a function to create an "intercepted channel", which takes a `Channel` and both unary and stream client interceptors.
    * The resulting thing still implements the `Channel` interface, but invokes the interceptors instead.
    * Since there is no `*grpc.ClientConn`, a `nil` value is passed for that argument of the interceptor. Of the various interceptors I've written, none have actually needed this anyway.
    * The code provides a valid `grpc.Streamer`/`grpc.UnaryInvoker` to the interceptor, which will proceed to the transport implementation.
3) The server-side is similar to gRPC internals: you register a service by supplying the server implementation and the `grpc.ServiceDesc`.
    * The alternate transport handles marshalling/unmarshalling metadata and request & response bytes. It then invokes the handlers.
    * There is an alternate implementation of `grpc.ServerStream` that is passed into the handlers for stream methods.

We haven't open-sourced this stuff yet, but I have considered it. The channel implementations we have are an in-process channel and a grpc-over-http channel (for http 1.1 -- does not support full-duplex bidi streams, but handles all other kinds of methods).

Due to the various bugs I've filed (including this one), neither can support call options, which also means that it is not currently possible to use response metadata (the server can't set it per this bug; the client can't get it per #1495 ).

**Comment by jhump** [comment]
@dfawley, in case you are still curious how I am doing alternate transports, it is now open-sourced: https://github.com/fullstorydev/grpchan
