### ISSUE TITLE
client grpc ResourceExhausted cause the server taking lots of memory.

### ISSUE THREAD

**Issue by hashstone** [grpc/grpc-go#1809]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
commit: 08b7bd3beb5c8765c042ddc17c096308f6f1ffd7

### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### What operating system (Linux, Windows, …) and version?
Linux  4.4.0-87-generic 14.04.1-Ubuntu SMP Tue Jul 18 14:51:32 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?
```go
/////////////////////////////////////////////
// server 
package main
 
import (
    "flag"
    "log"
    "net"
    "net/http"
    _ "net/http/pprof"
 
    "golang.org/x/net/context"
    "google.golang.org/grpc"
    pb "google.golang.org/grpc/examples/helloworld/helloworld"
    "google.golang.org/grpc/reflection"
)

const (
    port = ":50051"
)   
 
var (
    msgLen    = flag.Int("msg_len", 500, "the length of response body")
    maxMsgLen = flag.Int("max_msg_len", 15000, "the max length of response body")
)   
     
// server is used to implement helloworld.GreeterServer.
type server struct{}
     
// SayHello implements helloworld.GreeterServer
func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
    body := make([]byte, *msgLen)
    for i, _ := range body {
        body[i] = 'a'
    }

    return &pb.HelloReply{Message: "Hello " + string(body)}, nil
}   
         
func main() {
    flag.Parse()
    
    go func() {
        log.Fatal(http.ListenAndServe("0.0.0.0:8282", nil))
    }()
    lis, err := net.Listen("tcp", port)
    if err != nil {
        log.Fatalf("failed to listen: %v", err)
    }
    s := grpc.NewServer(grpc.MaxMsgSize(*maxMsgLen))
    pb.RegisterGreeterServer(s, &server{})
    // Register reflection service on gRPC server.
    reflection.Register(s)
    if err := s.Serve(lis); err != nil {
        log.Fatalf("failed to serve: %v", err)
    }
} 
```
``` go
/////////////////////////////////////////////
// client
package main
     
import (
    "flag"
    "log"
    "sync"
    "time"
 
    "golang.org/x/net/context"
    "google.golang.org/grpc"
    pb "google.golang.org/grpc/examples/helloworld/helloworld"
)   

const (
    address        = "localhost:50051"
    defaultName    = "world"
    defaultTimeout = 10 * time.Second
)   
         
var (
    maxMsgLen = flag.Int("max_msg_len", 2500, "the max length of response body")
    repeat    = flag.Int("repeat", 1000, "times of grpc request repeated")
    //memprofile = flag.String("memprofile", "mem.mprof", "write memory profile to this file")
)   
     
func main() {
    flag.Parse()
    // Set up a connection to the server.
    conn, err := grpc.Dial(address, grpc.WithInsecure(), grpc.WithMaxMsgSize(*maxMsgLen))
    if err != nil {
        log.Fatalf("did not connect: %v", err)
    }
    defer conn.Close() 
 
    // Contact the server and print out its response.
    name := defaultName
      
    wg := new(sync.WaitGroup)
    for i := 0; i < 1; i++ {
        wg.Add(1)
        go func() {
            c := pb.NewGreeterClient(conn)
            ctx, cancel := context.WithTimeout(context.Background(), defaultTimeout)
            defer cancel()
            for j := 0; j < *repeat; j++ {
                r, err := c.SayHello(ctx, &pb.HelloRequest{Name: name})
                if err != nil {
                    log.Printf("FAILED: %v", err)
                } else {
                    log.Printf("Greeting: %v", len(r.Message))
                }
            }   
            wg.Done()
        }()     
    }          
    wg.Wait()   
}
```

1. ./greeter_server -msg_len 4194304
2. ./greeter_client -repeat 10240 -max_msg_len 1024000

### What did you expect to see?
1. client problem should not affect server's performance.

### What did you see instead?
we should got the "rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4194315 vs. 1024000)" error message. Then we should notice that 'greeter_server' had took lots of memory.

### Something want to ask
1. when client got a grpc error, should client notify server not to send response continue?
I have used Wireshark to capture packge, notice that server was sending response after client "call.go:recvResponse" got the resource-exhausted error.

so what's the problem with this program,  any advice and suggestions will be greatly appreciated!
Thanks!

**Comment by lyuxuan** [comment]
Actually, what you expect to see holds true. Server successfully responded with a message of size 4194315. And when client tried to read this message from the wire, it detected that the received message size violate the receive message size limit which is 1024000, and returned the error you saw (code [here](https://github.com/grpc/grpc-go/blob/08b7bd3beb5c8765c042ddc17c096308f6f1ffd7/rpc_util.go#L302)).
On server side, since it had successfully sent the response, it then sent the OK status to client, which is what you capture through Wireshark.
As this is a unary rpc, client won't notify server since this rpc has already finished with error.

**Comment by dfawley** [comment]
Seems like there may be an issue here.  The CloseStream [here](https://github.com/grpc/grpc-go/blob/master/call.go#L45), which is what happens when the client receives a message that is too large, will not result in a RST_STREAM being sent back to the server, which means the server will block indefinitely once the stream's flow control is exhausted.

**Comment by hashstone** [comment]
thx!
