### ISSUE TITLE
Revert WithResolverUserOptions

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-go#1812]
`WithResolverUserOptions` was added in response to #1710. However, "use query params" is the grpc-wide answer for configuration. If there is a strong enough need for such a feature, it should be added to all languages. But lacking that, it shouldn't be in grpc-go.

Part of the vision of targets is that they can be provided anywhere, including the command line. As a single string there is little risk of needing to plumb addition details through (user) APIs in order to configure how to talk to a service. Combined with the global registry you can take a grpc-using library and configure it for a new environment easily, without lots of API having to be exposed.

That does mean that all the per-channel configuration details for a name resolver need to be serialized into a string. But it's hard to determine an alternative design that is anywhere near as simple for its benefits.

Aside: `WithResorverUserOptions` is dangerous/weird without also setting the name resolver. If we're going to allow per-client configuration of a name resolver, we should probably just expose a `WithResolver` option instead and let the user configure the resolver before passing it to gRPC.

**Comment by ejona86** [comment]
CC @dzbarsky

**Comment by ejona86** [comment]
> Due to internal optimizations

That's pretty vague. Is there a way to describe the use-case such that we could make design decisions?

I do understand trying to figure out things on the resolver vs balancer.

**Comment by euroelessar** [comment]
> That's pretty vague. Is there a way to describe the use-case such that we could make design decisions?

Sure thing:
1. We use it mostly for sharding (there are several thousands of shards per service)
2. Process initiates single streaming rpc to resolver server asking for (streamed) mapping from shard to list of associated endpoints.
3. Based on the response we create resolver for every individual shard which is later used to initialize per-shard grpc clients, effectively allowing us to re-utilize single request with client streaming to resolver server for all this clients.
4. Later each client makes its own balancing decisions, in some cases custom balancer is used.

**Comment by ejona86** [comment]
Ah! We've been looking at that sort of use case as well. I can totally understand why it would impact you. It's not that different from like Bigtable architecture.

Some follow-up questions:
1. How do you determine which shard to use for an RPC? Can it be semi-automatic, e.g., by looking at a field of the request?
2. I don't quite understand your (4), since I don't know why/how some shards would be "special" to receive custom configuration. Unless that was also received in your (2)?

**Comment by euroelessar** [comment]
> How do you determine which shard to use for an RPC? Can it be semi-automatic, e.g., by looking at a field of the request?

Application logic usually splits original request to per-sharded ones and potentially is capable to pass this information further in stack using context or some other mean. It's usually non-trivial to determine actual shard by just looking on the request as it involves some computation & knowledge about topology.

> I don't quite understand your (4), since I don't know why/how some shards would be "special" to receive custom configuration. Unless that was also received in your (2)?

One of the examples is graceful deployment process - client should prefer opening new transactions on new endpoint while allowing transactions on old endpoint to be finished. Balancer is currently stateful to determine which endpoint is new and which is old.

**Comment by euroelessar** [comment]
Oh also, regarding two - it's not some shards are special, but some services. (i.e. all shards for once service have the same balancer logic)

**Comment by dfawley** [comment]
Thanks for all the feedback!

> Due to internal optimizations we can't serialize all options to a string due to shared data structures between different resolver objects.

Your [resolver builder](https://godoc.org/google.golang.org/grpc/resolver#Builder) is a single struct type that is registered and accessed globally (e.g. from the dns resolver: [link](https://github.com/grpc/grpc-go/blob/10598f3eb3eee9565d6ab7d472e7a1b5d2287a6e/resolver/dns/dns_resolver.go#L57)).  You could store the shared data structures there.  Each [`Resolver`](https://godoc.org/google.golang.org/grpc/resolver#Resolver) returned by the `Builder` would then be able to reference the shared data.

Would something like that work for your use case?

**Comment by ejona86** [comment]
CC @dgquintas, who's been messing with this sort of design cross-language.

So our rough design for this would be to move all the resolution into gRPC (you own name resolver, but it is "within" the ClientConn) and allow the LB to make the sharding decisions.

Basic flow:
1. Register resolver and LB globals
2. Client creates ClientConn with target that chooses custom resolver, with basic necessary details like service name
3. Custom resolver resolves at least part of the details. It selects the proper LB via client config (COMING SOON) and passes any necessary details to the LB via resolver.Address.Metadata
4. Client issues a request, along with a custom CallOption (or Context attribute, or something else)
5. LB sees custom CallOption (or similar) and routes the request to the proper shard.

Potential problems:
1. Resolver and LB may be service-specific in your world. It sounds like that isn't the case, but this design sort of imagines you'd have "a few" such resolvers/LBs. If you end up getting 10+ it starts being awkward
2. Some of the plumbing might still be in-progress. The client config piece in particular may not have landed. Client passing something to LB may also benefit from a more direct API
3. This sort of stuff is complex. Maybe we're missing something.
