### ISSUE TITLE
Undefined: lookupSRV

### ISSUE THREAD

**Issue by henmja** [grpc/grpc-go#1816]
gRPC version: 1.8.5
go version: 1.5.2
operating system: windows 10

I installed grpc with the commands:
go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
go get -u google.golang.org/grpc

When I try to run server.go in google.golang.org/grpc/examples/route_guide/server, I get the following error message:
# google.golang.org/grpc/naming
..\..\..\naming\dns_resolver.go:213: undefined: lookupSRV
..\..\..\naming\dns_resolver.go:219: undefined: lookupHost
..\..\..\naming\dns_resolver.go:240: undefined: lookupHost
# google.golang.org/grpc/transport
..\..\..\transport\control.go:193: undefined: ContextErr
..\..\..\transport\handler_server.go:287: undefined: contextFromRequest
..\..\..\transport\http2_client.go:120: undefined: dialContext
..\..\..\transport\http2_client.go:651: undefined: ContextErr
..\..\..\transport\http2_server.go:708: undefined: ContextErr
..\..\..\transport\http2_server.go:837: undefined: ContextErr
..\..\..\transport\http_util.go:86: undefined: http.StatusTooManyRequests
..\..\..\transport\transport.go:134: undefined: ContextErr
..\..\..\transport\transport.go:260: undefined: ContextErr

**Comment by henmja** [comment]
Fixed by updating golang version

**Comment by dfawley** [comment]
:+1: Glad you were able to work this out.

I also hope you upgraded to a fairly recent release of golang; we intend to also drop support for Go1.6 in the not-too-distant future.
