### ISSUE TITLE
Fix read behavior when timeout is set by service config

### ISSUE THREAD

**Issue by menghanl** [grpc/grpc-go#1818]
If timeout is set by service config, when a new stream is created, a new context will be created based on the user's context with the timeout
https://github.com/grpc/grpc-go/blob/b71aced4a2a1ee80a1cbbd26b85a57623790d7f4/stream.go#L128-L129

This context will be canceled in `clientStream.finish()`
https://github.com/grpc/grpc-go/blob/b71aced4a2a1ee80a1cbbd26b85a57623790d7f4/stream.go#L529-L531

`finish()` is called when `transport.Stream` is done
https://github.com/grpc/grpc-go/blob/b71aced4a2a1ee80a1cbbd26b85a57623790d7f4/stream.go#L288-L291

And the `transport.Stream` is done when final status is received
https://github.com/grpc/grpc-go/blob/b71aced4a2a1ee80a1cbbd26b85a57623790d7f4/transport/http2_client.go#L1138
https://github.com/grpc/grpc-go/blob/b71aced4a2a1ee80a1cbbd26b85a57623790d7f4/transport/transport.go#L406-L410

So, when final status is received by the stream, the context created by gRPC will be canceled, thus all read from this stream will return context canceled error.

**Comment by benlangfeld** [comment]
What did this actually fix? As a user, it's very difficult to connect the description here to observed behaviour. Could this be related to https://github.com/kubernetes/helm/issues/3409 ?

**Comment by dfawley** [comment]
@benlangfeld, I tried to improve the commit message in #1838 for our release notes.  I do not suspect this is related to kubernetes/helm#3409.  That mentioned "the transport is closing" but here you would get "context canceled" errors instead of being able to receive the RPC data.

**Comment by benlangfeld** [comment]
Thanks dfawley. I apologise, I got mixed up while tracking this issue down and thought this was an issue on kubernetes/helm, then deleted my comment when I realised my mistake.

Thanks for the pointers!
