### ISSUE TITLE
Client grpc call does not return despite failed keepalive

### ISSUE THREAD

**Issue by joyzheng** [grpc/grpc-go#1821]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.9.2

### What version of Go are you using (`go version`)?

1.9.2

### What operating system (Linux, Windows, …) and version?

Docker container running Debian GNU/Linux 9.3, on Amazon Linux

### What did you do?
If possible, provide a recipe for reproducing the error.

We have a client with the following keepalive settings (along with matching ones on the server):
```
keepalive.ClientParameters{
	Time: 15 * time.Second,
	Timeout: 5 * time.Second,
	PermitWithoutStream: false,
}
```

After the client is idle for a while (with no requests or keepalive pings being sent), the connection breaks without the client noticing. 

Then, while the connection is broken, we attempt to make a grpc call with the client, passing in a `context` which times out after 1 hour. 

### What did you expect to see?

I would expect the following sequence of events:

1. the new call wakes up the keepalive and causes a ping to be sent
2. after 5 seconds, the keepalive times out
3. 5 seconds in, the grpc call returns with an error (due to the keepalive timing out)
4. (the keepalive timeout also causes a new connection to be established, so that if we retry the grpc call after it errors, it should succeed)

### What did you see instead?

Instead, we see that:

3. 1 hour later, the grpc call returns with an error (due to the context timing out)

I tried setting `GODEBUG=http2debug=2` and was able confirm that the following happens when we try to make the grpc call: 

- the client sends a `HEADERS` frame
- the client sends a `DATA` frame
- the client sends a `PING` frame
- the client does not receive back any frames from the server

Thanks!

**Comment by menghanl** [comment]
> the connection breaks without the client noticing.

Can you give more details on this? Like what's the environment your code runs on, and is there a proxy between the client and server?

I tried this locally, the behavior I got is what you expected.
One thing I noticed different is that, `PING` should be sent out before `HEADERS` for this new stream.
Also, aside from the order the frames are sent out, with that `PING` frame sent out, if the client doesn't get ack without 5 seconds, the connection will be closed.

**Comment by joyzheng** [comment]
My bad, I was walking through this again and realized that the delay is due to our backoff logic on failed grpc requests, rather than due to the grpc client not timing out. 

Thanks for taking a look!
