### ISSUE TITLE
rpc resturn "Unimplemented desc = unknown service" after server restart

### ISSUE THREAD

**Issue by YuleiXiao** [grpc/grpc-go#1822]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.2.1
### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64
### What operating system (Linux, Windows, …) and version?
Linux node1_81 3.10.0-229.42.1.105.x86_64 #1 SMP Fri Dec 2 06:40:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
### What did you do?
server was killed, and restart. Client call RPC interval but fail after server restart. Before server restart, it always success. And the error message is weird ```error: rpc error: code = Unimplemented desc = unknown service pinetree.pb.Admin```
### What did you expect to see?
no error, rpc success
### What did you see instead?
```error: rpc error: code = Unimplemented desc = unknown service pinetree.pb.Admin```

**Comment by menghanl** [comment]
The error code indicates the server is not installed on your server. Can you double check the server restarted is one with the server registered?

Also, can you try to update your gRPC version? The latest is `1.9.2`.

I tried with the latest code, with server stopped, client got error `code = Unavailable desc = all SubConns are in TransientFailure`. When the server is restarted, all RPCs succeeded.

**Comment by YuleiXiao** [comment]
OK, I get the reason, it is my program, not grpc

**Comment by upeediak** [comment]
This is the first link coming up when searching for the error. @YuleiXiao if you don't mind can you share what was the issue and fix in your case?
