### ISSUE TITLE
client report WithInsecure error when server is restart

### ISSUE THREAD

**Issue by go-fish** [grpc/grpc-go#1826]
Please answer these questions before submitting your issue.

### What version of Go are you using (`go version`)?
go version go1.8.1 linux/amd64
### What operating system (Linux, Windows, …) and version?
Linux 
### What did you do?
If possible, provide a recipe for reproducing the error.
Set up server and client WithInsecure, then restart the server, client report rpc error: code = Unknown desc = grpc: no transport security set (use grpc.WithInsecure() explicitly or set credentials) when connect to server
### What did you expect to see?
client should reconnect server without security error
### What did you see instead?
client report security error when server restarted

**Comment by menghanl** [comment]
Which version of gRPC are you using?
And can you double check that you set `grpc.WithInsure()` on the client side?
It would also be helpful if you can paste your client and server code or provide a small reproduction.

I could not reproduce this issue locally with HEAD. The client I tried could successfully send RPCs after the server is restarted.

**Comment by go-fish** [comment]
i found the problem, sorry for the issue
