### ISSUE TITLE
Unable to test context with stream (server side unary rpc)

### ISSUE THREAD

**Issue by thurt** [grpc/grpc-go#1849]
### What version of gRPC are you using?
master@1cd234
### What version of Go are you using (`go version`)?
go 1.8.5
### What operating system (Linux, Windows, …) and version?
linux 4.4.0-93-generic x86_64 GNU/Linux
### What did you do?
I have a function for a server side unary rpc implementation that I want to test. The function simply adds one or more headers to the context via `grpc.SetHeader`.

For testing, I need to create a fake context with stream that I can pass to this function. Then I will inspect the fake to confirm whether the correct headers were added. 

However, I am not able to create a new context with stream. It looks like the function I need is `transport.newContextWithStream`, but this function is not exported/public. 

The only alternative way that I can see to test this function is to mock the `grpc` package so I can test whether `grpc.SetHeader` is called, but I would have to pass this top-level package as a parameter, which seems wrong.
### What did you expect to see?
An easy way to create a context with stream (maybe I haven't found it?)
### What did you see instead?
`transport.newContextWithStream` is not accessible.

edit:
i think this snippet from #1494 is a similar description of the problem
> For the server-side, application code sets response metadata using top-level methods that rely on there being a transport tucked inside of a context.Context. Since the methods for modifying the context in the correct way are unexported, it is not possible for a server interceptor to wrap the transport, and thus intercept metadata.

**Comment by dfawley** [comment]
@thurt, issue #1802 looks very similar, and should cover your needs.  Can you take a look and see if you agree?

**Comment by thurt** [comment]
yes i think so!
a public API for injecting the stream into a context, and then have the ability to write a fake implementation for a stream interface.
