### ISSUE TITLE
Compile error: transport/http_util.go:486:6

### ISSUE THREAD

**Issue by wanghaiyang1930** [grpc/grpc-go#1851]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.9.x
### What version of Go are you using (`go version`)?
go version go1.9.3 linux/amd64
### What operating system (Linux, Windows, …) and version?
Linux
### What did you do?
If possible, provide a recipe for reproducing the error.
Compile error.
transport/http_util.go:486:6: f.fr.SetReuseFrames undefined (type *http2.Framer has no field or method SetReuseFrames)

**Comment by wanghaiyang1930** [comment]
We could not visit google.golang.org/grpc (China....crying...)

**Comment by menghanl** [comment]
Please try to update your local packages with `go get -u golang.org/x/net/http2`. Or simply do `go get -u google.golang.org/grpc` to update all the dependencies.

For the accessability issue,  does [this](https://blog.golang.org/hello-china) help? If not, please try setting up VPN.
