### ISSUE TITLE
New resolver API - per-client resolvers?

### ISSUE THREAD

**Issue by alecthomas** [grpc/grpc-go#1860]
With the old `grpc.WithBalancer(b)` API it was possible to have per-connection resolvers. For example, if you wanted to connect to services behind two etcd-based resolvers you could do:

```go
cluster1 := grpc.WithBalancer(NewEtcdBalancer("etcdhost1,etcdhost2"))
cluster2 := grpc.WithBalancer(NewEtcdBalancer("etcdhost3,etcdhost4"))
conn1, err := grpc.Dial("etcd://foo", cluster1)
conn2, err := grpc.Dial("etcd://bar", cluster2)
```

With the new [resolver](https://godoc.org/google.golang.org/grpc/resolver#BuildOption) API this no longer seems to be possible. In fact, it seems that to configure a resolver you must essentially set a global variable with the configuration, which is then used across all connections. eg.

```go
resolver.Register(NewEtcdResolverBuilder("etcdhost1,etcdhost2"))
```

I see that there is a `grpc.withResolverBuilder(b) DialOption`, which would effectively achieve the above, but this is not publicly exposed.

Is there some other way to achieve the previous behaviour that I've missed? Alternatively, can `withResolverBuilder(b)` be made public?

**Comment by alecthomas** [comment]
I just found #1710 and #1812 which argue for passing this information via query parameters. In the example above that would mean that every Dial would need something like the following, is that correct?

```go
conn1, err := grpc.Dial("etcd://foo?server=etcdhost1&server=etcdhost2")
conn2, err := grpc.Dial("etcd://bar?server=etcdhost3&server=etcdhost4")
```

Then the `ResolverBuilder` would need to maintain a mapping from query parameters to etcd client connections...?

**Comment by alecthomas** [comment]
I guess now that I've read the other two issues, my question is: what is the best way to solve this conundrum?

**Comment by alecthomas** [comment]
Read the naming guide. I guess it would be:

```go
conn1, err := grpc.Dial("etcd://etcdhost1,etcdhost2/foo")
conn2, err := grpc.Dial("etcd://etcdhost3,etcdhost4/bar")

```

**Comment by menghanl** [comment]
@alecthomas If what you need from the resolver is to return the hosts passed in back as resolved addresses, the solutions you suggested would all work.

You could also do `grpc.Dial("etcd:///etcdhost1,etcdhost2")`, the resolver builder will receive a struct as
```go
resolver.Target{
  Scheme: "etcd",
  Authority: "",
  Endpoint: "etcdhost1,etcdhost2",
}
```
Now you need to make sure the etcd resolver builder knows how to parse "etcdhost1,etcdhost2".

This will be similar to a [`passthrough` resolver](https://github.com/grpc/grpc-go/blob/master/resolver/passthrough/passthrough.go#L19) that also parses the endpoint string.

**Comment by alecthomas** [comment]
No, the hosts are the etcd servers. Foo and bar are service to resolve.

**Comment by alecthomas** [comment]
At heart my question is how to use different sets of resolver hosts in a reusable way. With the old API I would just pass two separate Balancer values around. With the new API it seems I have to pass the host strings around and concatenate then with the targets?

**Comment by menghanl** [comment]
So you want to specify the etcd servers that the resolver should query to resolve the service.
Then what you suggested `grpc.Dial("etcd://etcdhost1,etcdhost2/foo")` is the right way.

In this target string, `"etcdhost1,etcdhost2"` becomes the `authority`, and from the [naming doc](https://github.com/grpc/grpc/blob/master/doc/naming.md#name-syntax)
> The authority indicates some scheme-specific bootstrap information, e.g., for DNS, the authority may include the IP[:port] of the DNS server to use.

**Comment by alecthomas** [comment]
Okay, thanks!

**Comment by alecthomas** [comment]
Though I have to say, if the authority needs a large amount of configuration, like SSL certs, passphrases, etc., having to pass all that through a URL-like string is pretty tedious.

**Comment by Asarew** [comment]
I just ran into the same 'issue' as @alecthomas. i've build a custom naming resolver and passing all configuration as a naming.Target is not only tedious but also blocks use cases. The current `WithBalancerName` api is very limiting in flexibility compared with the already deprecated `WithBalancer` DialOption, I really would like to see a similar solution for configuring a per connection naming.Resolver.
