### ISSUE TITLE
Avoid using context.Background in tests

### ISSUE THREAD

**Issue by menghanl** [grpc/grpc-go#1878]
`context.Background` is used in many tests/benchmarks. Which might be misleading for users.

Some of the tests expect an error, so `context.Background` is probably OK.
We should check and make sure  `context.Background` doesn't cause any problem.

**Comment by gauravgahlot** [comment]
@dfawley I would like to take this up.

**Comment by dfawley** [comment]
Sounds great, thank you!

I would do a grep for `context.Background()` in our tests (* - see below); any usages _should_ appear in a `context.WithTimeout` or `context.WithDeadline` call as a rule.  It's possible some tests add a timeout later, or a deadline isn't relevant for some tests, but I believe those should be rare.

\* - `find . -name '*_test.go' | xargs grep -F 'context.Background()'`
