### ISSUE TITLE
streaming RPC documentation

### ISSUE THREAD

**Issue by menghanl** [grpc/grpc-go#1880]
Check documentation for stream (`RecvMsg`, `SendMsg`) to make sure they are up to date (after change #1854).

Also, should mention `send` only buffers the message instead of actually sending it out (#1876).

A separate tutorial (`Documentation/streaming.md`) could also be helpful.

**Comment by dfawley** [comment]
See also: https://groups.google.com/d/msg/grpc-io/XcN4hA9HonI/5PskjxpYAAAJ

**Comment by srini100** [comment]
Consolidating streaming API documentation issues in https://github.com/grpc/grpc-go/issues/1894 and closing this one.
