### ISSUE TITLE
Stabilizing ClientInterceptor API

### ISSUE THREAD

**Issue by aamitdb** [grpc/grpc-go#1898]
The client interceptors APIs are marked as experimental on HEAD still https://github.com/grpc/grpc-go/blob/7c5299d71e2b8d403195f6071eecea690bf5622a/interceptor.go#L31.

I'm not aware of any issue blocking them from being promoted to stable, although I see some requests tagged as "feature" e.g. #1805 about changing them.

Can the apis be promoted to stable or is there any place I can track the remaining work to be done on them?

Asked same q on mailing list and got directed to open an issue here.

**Comment by dfawley** [comment]
@aamitdb We don't intend to make any changes to this API; however, we do intend to replace it eventually.  When we do so, we will make sure we do at least one major release containing both the new and old APIs to provide an opportunity to migrate.  The new API should be very similar, so isn't expected to take much effort to change.  We would like to leave these marked as experimental until then.

Thanks!
