### ISSUE TITLE
Error after `dep ensure -update`

### ISSUE THREAD

**Issue by grkuntzmd** [grpc/grpc-go#1903]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.10.0 (8e4536a)

### What version of Go are you using (`go version`)?
go version go1.10 linux/amd64

### What operating system (Linux, Windows, …) and version?
Linux (Ubuntu 17.10)

### What did you do?
If possible, provide a recipe for reproducing the error.
dep ensure -update
I am using the Google Cloud Storage API (`cloud.google.com/go/storage`).

### What did you expect to see?
Not an error in my build.

### What did you see instead?
\# .../vendor/google.golang.org/api/transport/grpc
vendor/google.golang.org/api/transport/grpc/go18.go:25:45: undefined: ocgrpc.ClientHandler

**Comment by dfawley** [comment]
Sorry, but this is not actually grpc related.  This is some kind of interaction between the cloud libraries, opencensus, and dep.  The error is coming specifically from this file: https://github.com/google/google-api-go-client/blob/master/transport/grpc/go18.go.

cc @jba in case he can help.

**Comment by jba** [comment]
You need to update `go.opencensus.io/plugin/ocgrpc` to the latest version.
