### ISSUE TITLE
.: Permission denied   or proto: Permission denied

### ISSUE THREAD

**Issue by zldafeng** [grpc/grpc-go#1916]
### 
```
protoc -I proto  proto/hello.proto --go_out=plugins=grpc: proto
proto: Permission denied
```
```
protoc -I . --go_out=plugins=grpc: . proto/hello/hello.proto
.: Permission denied
```
### i want expect to generate  hello.pb.go  successfully.

I tried to run as an administrator.And I have full control over all the files.now how can i do.

**Comment by lyuxuan** [comment]
There shouldn't be any space between `--go_out=plugins=grpc:` and the destination path.
Please remove the space  between "grpc:" and "proto", i.e. change ` -go_out=plugins=grpc: proto` into `-go_out=plugins=grpc:proto`, and try again. 
Let us know if you still have any problem. Thanks!
