### ISSUE TITLE
Prioritize HTTP errors over gRPC errors

### ISSUE THREAD

**Issue by MakMukhi** [grpc/grpc-go#1924]
when specified wrong endpoint, grpc fails with

 rpc error: code = FailedPrecondition desc = transport: received the unexpected content-type "text/html; charset=UTF-8"

it might be better to return other error, since response status is 404

**Comment by Capstan** [comment]
Even if you don't prioritize HTTP errors over gRPC errors, it should be better interleaved. Today, `processHeaderField` gets called before the the httpStatus is inspected, and will return if the `Content-Type` is invalid. But if there's a problem with a proxy, e.g., [IAP](https://cloud.google.com/iap/), or urlmapping on a server with colocated HTTP services, you will very likely get `text/html` responses meant for human consumption. gRPC clients may still wish to try and recover programmatic data and give a better error responses.

I suggest pulling out `Content-Type` from `processHeaderField` to be a special deferred error, to be returned if http status doesn't return an error status.

**Comment by Capstan** [comment]
Also, some way of actually returning the html would be way helpful for diagnosis.

**Comment by dfawley** [comment]
#2599 should fix this, for the most part.  Still not returning the raw HTML, however, but I think we should cover that with a separate feature request instead of as part of this bug.

**Comment by lyuxuan** [comment]
#2599 is now merged. @Capstan please check out the current master head and see if it works for you. Thanks!
