### ISSUE TITLE
Add metadata.MD helper methods for keys

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-go#1926]
When setting and getting values from a metadata.MD object, it would be nice if they could have some helpers for accessing the values.  Consider the following snippet:

```go 
const headerName = "My-Optional-Header"
// ...
md := metadata.Pairs(headerName, "42")
ctx = NewOutgoingContext(ctx, md)
// ...
```

Meanwhile, on the server side:

```go
md, present := FromIncomingContext(ctx)
if val, ok := md[headerName]; ok {
  // handle val
}
```

On the surface this looks correct.  Since the header is optional, no error is raised incase it isn't included. 

Unfortunately, the bottom code never executes and it's hard to track down why.  The same header key was used in both places, there aren't any special methods for getting headers out, so this is basically correct code.   Even the header name follows the HTTP pattern

The problem is that Pairs silently turns the names to lower case (as required by HTTP/2), but Go maps don't know that.  It would be nice if there was a helper method on `MD` to get and set values, which will automatically lowercase key names.   This is the same approach used by [net/http.Header](
https://golang.org/pkg/net/http/#Header.Get).   There are two benefits I see: 

1.  It is much less bug prone to access headers from MD.  The presence of these methods would make it clearer that something different is going on.
2.  Users who don't want to pay the cost of lowercasing their strings can keep accessing the map directly.

**Comment by lyuxuan** [comment]
This issue should have been solved by #1940.
