### ISSUE TITLE
Respect SETTINGS_HEADER_TABLE_SIZE http2 setting

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#1928]
Refs:
Spec: http://httpwg.org/specs/rfc7540.html#SettingValues
hpack Encoder setting: https://godoc.org/golang.org/x/net/http2/hpack#Encoder.SetMaxDynamicTableSizeLimit
hpack Decoder setting: https://godoc.org/golang.org/x/net/http2/hpack#Decoder.SetAllowedMaxDynamicTableSize

Note that the x/net/http2 server doesn't natively support this setting.

**Comment by Terminator637** [comment]
When will you fix it?

**Comment by lyuxuan** [comment]
It's on our todo list for this quarter. Thanks!

**Comment by sercand** [comment]
Due to this bug, we can't use latest nginx as load-balancer. A [nginx ticket](https://trac.nginx.org/nginx/ticket/1538) and [commit](https://trac.nginx.org/nginx/changeset/2713b2dbf5bb5b6284c8581d8dd3bba9270b1a2b/nginx) mention this.
