### ISSUE TITLE
Adding spans to client creation/token refresh

### ISSUE THREAD

**Issue by maksharma** [grpc/grpc-go#1937]
We want to add opencensus spans to record stats related to bigtable client creation for [bigtable go client](https://github.com/GoogleCloudPlatform/google-cloud-go/tree/master/bigtable) -
- the time taken to establish the client connection
- if the connection was refreshed, add a flag to specify the same
- how much time does it take to establish a new connection on refresh
- auth actions: time taken to fetch auth token

This would help us in figuring out issues as well as optimisations that we can do.

[This](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigtable/bigtable.go#L69) is how we are creating the client in Go bigtable client, which in turn invokes [this](https://github.com/google/go-genproto/blob/master/googleapis/bigtable/v2/bigtable.pb.go#L865)
We are using the Dial() method of [grpc](https://github.com/grpc/grpc-go/blob/master/clientconn.go#L400) 
I think we would need to think about adding the spans here?

Would need assistance to figure out how we can go about adding the above info to spans.

**Comment by lyuxuan** [comment]
We suggest that you use custom dialer and handshaker in order to instrument and collect the stats you listed here.

@rakyll. We wonder if opencensus is going to support the stats listed here.

**Comment by lyuxuan** [comment]
Friendly ping! Do the custom dialer and handshaker solve your problem?

**Comment by maksharma** [comment]
We have a custom [dialer](https://github.com/google/google-api-go-client/blob/master/transport/grpc/dial.go#L36) implemented already. This can solve tracking of client connection.
Still trying to figure out how we can manage refreshes.

**Comment by dfawley** [comment]
> Still trying to figure out how we can manage refreshes.

I'm not sure what you mean by "refreshes".  Do you believe this is a gRPC thing or a bigtable client library thing?  If gRPC, could you please clarify?  Otherwise, if you have everything sorted out from the gRPC side, please close this.  Thanks!

**Comment by dfawley** [comment]
@maksharma if you haven't solved your problems yet, it might be better to open an issue against the [google-cloud-go](https://github.com/GoogleCloudPlatform/google-cloud-go) repo.  Thanks!
