### ISSUE TITLE
Question: How to get MethodOptions from an RPC request?

### ISSUE THREAD

**Issue by nate-meta** [grpc/grpc-go#1938]
I am using interceptors to perform additional validation based on the optional extensions set on an RPC on incoming and out going RPCs. Given the following gRPC schema:

```proto
extend google.protobuf.MethodOptions {
  string my_option = 50006;
}

service MyService {
  rpc Foo (FooRequest) returns (FooResponse) {
    option (my_option) = "foo"
  }
}
```

How do I go about getting the value of my_option? At first I had thought to get it from the request using [this](https://github.com/golang/protobuf/issues/179#issuecomment-261146848). However, as this is a MethodOptions it doesn't seem that its part of the descriptor. Thoughts?

**Comment by jhump** [comment]
@nate-meta: see the code example in #1526.
