### ISSUE TITLE
Clarify whether WithBalancer() or WithBalancerName() are preferred

### ISSUE THREAD

**Issue by mpuncel** [grpc/grpc-go#1942]
On master, the `WithBalancer()` dial option's godoc says it is [deprecated](https://github.com/grpc/grpc-go/blob/master/clientconn.go#L211), but the `WithBalancerName()` option says it's an [experimental API](https://github.com/grpc/grpc-go/blob/master/clientconn.go#L227). Is the former still safe to use, or should the latter be promoted from experimental status?

**Comment by mpuncel** [comment]
closed because now my understanding is that the entire `Balancer` API is experimental, but if using it, `WithBalancerName()` is preferred

**Comment by dfawley** [comment]
@mpuncel yes, that's right -- the first API was `grpc.Balancer`, which was marked as experimental before GA.  This API had some limitations that prevented us from implementing service configs (i.e. we could not dynamically switch the balancer).  We have no firm plans to remove it, but I wouldn't rely upon it.

Any changes to the new API are expected to be minor.
