### ISSUE TITLE
API design seemingly makes client connection reuse/pooling impossible when request metadata is needed

### ISSUE THREAD

**Issue by sqs** [grpc/grpc-go#195]
Because metadata and auth are tied to a ClientConn in the current Go API (because they're passed to Dial), you can't reuse/pool underlying TCP connections for requests with differing metadata and auth credentials.

Consider the case where you want to attach user credentials and a request tracing ID (Dapper-style) to each gRPC call. Even though there might be a large number of already open ClientConns, you need to create a new one (and accompanying underlying TCP connection) for each unique pair of user credentials and tracing ID. Even if you quickly close the TCP connections, they still stick around in TIME_WAIT state and can quickly exhaust the total number of ports (1000 public API requests per second, each public API request subsequently makes 5 other API calls with unique Dapper span IDs -- you will exhaust your port space in less than 11 seconds, even assuming all 65,535 ports are available).

The net/http package's solution to this issue is to separate the Client (which handles connection reuse) from the Transport (which can be used to inject user auth and tracing IDs into, e.g., HTTP headers).

Am I missing something, or is this indeed a limitation of the current API?

I can think of pooling workarounds but none that work if you inject high-cardinality parameters (such as a Dapper span ID). And the Credentials interface isn't sufficient because it must be created when the connection is created, and it is not possible to inject data into its metadata arg differentially in such a way that this problem would be solved.

Otherwise, gRPC is awesome. :) Thanks!

**Comment by iamqizhao** [comment]
no idea how you got impression metadata and auth are tied to ClientConn,
which is wrong. Metadata is definitely per rpc. Auth depends -- for some
types of auth such as SSL/SSH/TLS, they have to be per connection. Some
others such as oauth2 are per-rpc.

**Comment by sqs** [comment]
You are right, sorry. I was thinking about it in the wrong way (trying to use the gRPC client like an HTTP client).
