### ISSUE TITLE
GRPC streams vs HTTP2 streams

### ISSUE THREAD

**Issue by vitalyisaev2** [grpc/grpc-go#1950]
Could you please clarify, are there any limitations for the number of GRPC streams outgoing from GRPC client?

Within a HTTP2 client implementation there is a `streamsQuota` which is always initialized with `100`, and it can't be overriden:
https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L225

Doesn't it mean that simultaneously there can be only 100 outgoing GRPC calls? How do GRPC streams map to HTTP2 streams?

Another question is about good API design. In case of bidirectional streaming, does it make sense to have single long-living reusable stream instead of creating a new stream every time? The first option requires stream messages to have some kind of identifiers, while the second allows API to stay laconic. So does GRPC stream creation give significant overhead?

Kind regards

**Comment by minaevmike** [comment]
Also i'll want to notice that there is some misleading code:
- https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L1229
- https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L134
so by default on server max streams - 4294967295, on client - 2147483647, so client limitation must be same as server - `math.MaxUint32`

**Comment by vitalyisaev2** [comment]
@MakMukhi thanks for explanation!

Regarding to the second question, I actually meant the situation when GRPC client and server collaborate through bidirectional streaming, but every session is quite short (maybe a couple of messages from each side), however, unary RPC is not an option here. In fact the question is how to find out, what would be better: to reuse one long-living stream with the cost of extending messages, or just to create new bidirectional stream per every request.
