### ISSUE TITLE
Why is DialContext not blocking by default?

### ISSUE THREAD

**Issue by nhooyr** [grpc/grpc-go#1953]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.9.2

### What version of Go are you using (`go version`)?
go version go1.10 darwin/amd64

### What operating system (Linux, Windows, …) and version?
macOS 10.13.3

### What did you do?
If possible, provide a recipe for reproducing the error.

```go
package main

import (
	"context"
	"log"
	"time"

	"google.golang.org/grpc"
)

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	_, err := grpc.DialContext(ctx, "example.com",
		grpc.WithInsecure(),
	)
	log.Print(err)
}
```

### What did you expect to see?

An error

### What did you see instead?

nil

This is because DialContext does not block by default. It should as otherwise, it doesn't really make sense to pass in a Context. If someone is passing in a Context to a Dial, its pretty much guaranteed that they want it to block as they want the Context to apply to the dial. Its extremely counter intuitive to run the dial in the background and immediately return.

**Comment by nhooyr** [comment]
Ah, its from https://github.com/grpc/grpc-go/pull/858

I think this behaviour should be changed or clearly documented on `grpc.DialContext`. I can whip up the PR if this sounds good.

**Comment by nhooyr** [comment]
Or maybe we should just deprecate `grpc.DialContext` and recommend users who want to timeout the dial use the `WithDialer` option and use a timeout inside of that.

**Comment by dfawley** [comment]
> Or maybe we should just deprecate grpc.DialContext and recommend users who want to
> timeout the dial use the WithDialer option and use a timeout inside of that.

This has different connotations.  A `grpc.ClientConn` is not a single connection, it is a connection _pool_.  If you apply a timeout in your dialer, that applies to that particular connection attempt.  If you apply a timeout to `Dial`, that applies across all of the initial connection attempts.

In #1786, I have proposed deprecating `Dial`/`DialContext` and replacing them with a `NewClient[Conn]` instead, which would make that distinction more apparent, and eliminate blocking client creation altogether.  (Users would still be able to use the [connectivity state API](https://godoc.org/google.golang.org/grpc#ClientConn.GetState) to achieve the same result, if desired.)

It would probably be appropriate to mention the non-blocking default behavior in the docstring.

**Comment by nhooyr** [comment]
That all sounds great to me.

**Comment by nhooyr** [comment]
I'll keep this open to track the clarification of the docs.
