### ISSUE TITLE
Peer-to-peer gRPC?

### ISSUE THREAD

**Issue by alltom** [grpc/grpc-go#1954]
I have two computers with private IPs, and I'd like one of them to be able to call gRPC endpoints on the other. Is there a peer-to-peer configuration for gRPC? I have a third computer with a public IP to coordinate.

I thought that Dial might return an interface that I could implement on top of a peer-to-peer connection, but it looks opaque. Is there an override point that I could use to dial in a custom way?

**Comment by fd** [comment]
The simples way to achieve this is to do nat-traversal from the machines with private IPs (using upnp).
This will map a public ip/port pair to a service running on each machine. Note that the port is randomly selected and thus not predictable. Next each port-mapped service would signal it's public ip:port pair to a known signalling service (this needs service needs to be accessible to all participants). Then if you want to o connect to a port-mapped service you first ask the signalling service for the ip-port and the dial that address.

**Comment by dfawley** [comment]
@alltom,

To answer your specific question:

> I thought that Dial might return an interface that I could implement on top of a peer-to-peer connection, but it looks opaque. Is there an override point that I could use to dial in a custom way?

You can provide the client with a custom dialer that returns a `net.Conn` interface:
https://godoc.org/google.golang.org/grpc#WithDialer

Let us know if you have further questions about this.

**Comment by asimonov** [comment]
is it possible to do this in python?

**Comment by dfawley** [comment]
@asimonov, I'm not familiar with the Python API.  You could ask on [grpc-io](https://groups.google.com/forum/#!forum/grpc-io) or in [an issue on the grpc repo](https://github.com/grpc/grpc/issues/new).
