### ISSUE TITLE
 go get not working unrecognized import path "google.golang.org/grpc" 

### ISSUE THREAD

**Issue by tyler2018** [grpc/grpc-go#1959]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
can't install gRPC
### What version of Go are you using (`go version`)?
1.0
### What operating system (Linux, Windows, …) and version?
macos 10.12
### What did you do?
If possible, provide a recipe for reproducing the error.
➜  golangProject go get -u google.golang.org/grpc

### What did you expect to see?
install done
### What did you see instead?
➜  golangProject go get -u google.golang.org/grpc
package google.golang.org/grpc: unrecognized import path "google.golang.org/grpc" (https fetch: Get https://google.golang.org/grpc?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

**Comment by tyler2018** [comment]
go version 1.10

**Comment by douglarek** [comment]
@tyler2018 maybe you should f**k the GFW ? yeah, maybe

**Comment by menghanl** [comment]
Unfortunately, there is not much we can do here. Please try to set up VPN or do a manual clone as @douglarek suggested.

See also: https://github.com/grpc/grpc-go/issues/1780#issuecomment-355365355

**Comment by tyler2018** [comment]
I already have VPN. If is VPN problem, not like these " unrecognized import path "google.golang.org/grpc"  It should be timeout or something like that.

unrecognized means already get the code, and have something wrong when processing it.

unbelievable I had to explain this.

**Comment by menghanl** [comment]
The error message does show it's a timeout error:
> dial tcp 216.239.37.1:443: i/o timeout
