### ISSUE TITLE
All packages should have comments(including main packages)

### ISSUE THREAD

**Issue by MakMukhi** [grpc/grpc-go#1967]
Style guide: https://github.com/golang/go/wiki/CodeReviewComments#package-comments

**Comment by dfawley** [comment]
List of packages missing package-level comments:

- [ ] balancer/grpclb/grpc_lb_v1
- [ ] benchmark/client
- [ ] benchmark/grpc_testing
- [ ] benchmark/server
- [ ] benchmark/stats
- [ ] benchmark/worker
- [ ] channelz/grpc_channelz_v1
- [ ] credentials/alts/internal/proto/grpc_gcp
- [ ] examples/helloworld/greeter_client
- [ ] examples/helloworld/greeter_server
- [ ] examples/helloworld/helloworld
- [ ] examples/helloworld/mock_helloworld
- [ ] examples/route_guide/mock_routeguide
- [ ] examples/route_guide/routeguide
- [ ] health/grpc_health_v1
- [ ] interop
- [ ] interop/client
- [ ] interop/grpc_testing
- [ ] interop/http2
- [ ] interop/server
- [ ] reflection/grpc_reflection_v1alpha
- [ ] reflection/grpc_testing
- [ ] stats/grpc_testing
- [ ] stress/grpc_testing
- [ ] stress/metrics_client
- [ ] test
- [ ] test/codec_perf
- [ ] test/grpc_testing

Note that a handful of these are generated.

**Comment by zelahi** [comment]
I would like to take this ticket.  My only question is how do you like the PRs to be submitted?  One per file, or all of these in one PR?.  I was thinking of grouping them by level such as the benchmarking in one and interop as another

**Comment by dfawley** [comment]
@zelahi sounds good, thanks!  One for all of them is fine, or if you want to break it up into smaller chunks, that's fine too.  One per package is probably too much, though.

Obviously the generated packages don't need comments (unless the generator was updated to produce them).

**Comment by zelahi** [comment]
Sweet thanks, as I'm going through them, I'll note down the auto-generated packages

**Comment by dfawley** [comment]
@zelahi did #2612 fully resolve this or are there more packages missing comments?

**Comment by dfawley** [comment]
Ping @zelahi - any update?

**Comment by zelahi** [comment]
Hi @dfawley , Apologies for the late reply.  I compiled a list of what items are completed, needs to be finished, and autogenerated ones

Completed: 
```
benchmark/client
benchmark/server
benchmark/stats/stats.go
examples/helloworld/greeter_client/main.go
examples/helloworld/greeter_server/main.go
```

Needs to be completed:
```
benchmark/worker
interop
interop/client
interop/grpc_testing
interop/http2
stress/metrics_client
test/
intro/server
```

Autogenerated files that don't need comments:
```
examples/helloworld/helloworld
examples/helloworld/mock_helloworld
examples/route_guide/mock_routeguide
examples/route_guide/routeguide
test/codec_perf
```

**Comment by dfawley** [comment]
Great, thanks for the update!  I've checked off the "completed/autogenerated" entries in my checklist above.
