### ISSUE TITLE
Flaky test: TestFailFastRPCErrorOnBadCertificates

### ISSUE THREAD

**Issue by MakMukhi** [grpc/grpc-go#1968]

**Comment by MakMukhi** [comment]
Couldn't reproduce in about 11,000 runs. Will keep this issue open in case travis finds it again.

**Comment by MakMukhi** [comment]
--- FAIL: TestFailFastRPCErrorOnBadCertificates (25.36s)
	end2end_test.go:533: Running test in bad-cred environment...
	end2end_test.go:6177: Dial(_) = context deadline exceeded, want <nil>

**Comment by menghanl** [comment]
```go
	opts := []grpc.DialOption{grpc.WithTransportCredentials(clientAlwaysFailCred{})}
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	cc, err := grpc.DialContext(ctx, te.srvAddr, opts...)
	if err != nil {
		t.Fatalf("Dial(_) = %v, want %v", err, nil)
	}
	defer cc.Close()
```

The `Dial` is not a blocking dial...
Will try to extend deadline to 10 second.
