### ISSUE TITLE
Data race between new balancer Register() and Get() functions.

### ISSUE THREAD

**Issue by jpbetz** [grpc/grpc-go#1973]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

v1.11.1

### What version of Go are you using (`go version`)?

go1.9.2

### What operating system (Linux, Windows, …) and version?

linux

### What did you do?

While testing our an upgrade of etcd to use the new grpc load balancer interface, we called `balancer.Register(mybalancer)` concurrent with other grpc client operations running.

### What did you expect to see?

New balancer is registered safely.

### What did you see instead?
```
WARNING: DATA RACE
 Write at 0x00c420094e70 by goroutine 188:
   runtime.mapassign_faststr()
       /usr/local/google/home/jpbetz/.gvm/gos/go1.9.2/src/runtime/hashmap_fast.go:598 +0x0
   github.com/coreos/etcd/vendor/google.golang.org/grpc/balancer.Register()
       /usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/vendor/google.golang.org/grpc/balancer/balancer.go:43 +0xae
   github.com/coreos/etcd/clientv3/balancer.New()
       /usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/clientv3/balancer/balancer.go:90 +0x45c
   github.com/coreos/etcd/clientv3.newClient()
       /usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/clientv3/client.go:437 +0xc3c
   github.com/coreos/etcd/clientv3.New()
       /usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/clientv3/client.go:86 +0xf3
   github.com/coreos/etcd/snapshot.createSnapshotFile()
       /usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/snapshot/v3_snapshot_test.go:179 +0xa17
   github.com/coreos/etcd/snapshot.TestSnapshotV3RestoreSingle()
       /usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/snapshot/v3_snapshot_test.go:39 +0xb1
   testing.tRunner()                                                     
       /usr/local/google/home/jpbetz/.gvm/gos/go1.9.2/src/testing/testing.go:746 +0x16c

 Previous read at 0x00c420094e70 by goroutine 202:
   runtime.mapaccess2_faststr()
       /usr/local/google/home/jpbetz/.gvm/gos/go1.9.2/src/runtime/hashmap_fast.go:315 +0x0
   github.com/coreos/etcd/vendor/google.golang.org/grpc/balancer.Get()
       /usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/vendor/google.golang.org/grpc/balancer/balancer.go:50 +0x9a
   github.com/coreos/etcd/vendor/google.golang.org/grpc.(*ClientConn).switchBalancer()
       /usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/vendor/google.golang.org/grpc/clientconn.go:779 +0x2f7
   github.com/coreos/etcd/vendor/google.golang.org/grpc.(*ClientConn).handleResolvedAddrs()
       /usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/vendor/google.golang.org/grpc/clientconn.go:741 +0x2de
   github.com/coreos/etcd/vendor/google.golang.org/grpc.(*ccResolverWrapper).watcher()
       /usr/local/google/home/jpbetz/Projects/etcd/src/github.com/coreos/etcd/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:117 +0x58e
```
At a glance it looks like the races happen when accessing https://github.com/grpc/grpc-go/blob/30fb59a4304034ce78ff68e21bd25776b1d79488/balancer/balancer.go#L36 via `Register()` and `Get()`.

cc @gyuho

**Comment by menghanl** [comment]
The map used by `Register` and `Get()` is currently not protected by mutex.

The expectation was that all balancers should already be registered by the time you do something with gRPC. The registration should happen at init time (in an init() function or some where early enough).

Did this only happen in your tests because tests run in parallel? Do you need to register balancers while the client is running?

**Comment by jpbetz** [comment]
I was able to register the balancer in an init function. Closing this. Thanks!

**Comment by dfawley** [comment]
We should document `balancer.Register` to make it clear that it must be called during initialization time.

**Comment by jpbetz** [comment]
@menghanl I may have spoken too soon. For etcd we might need to be able to register load balancers on the fly.

I'll try to summarize the use case:

For the etcd "clientv3" interface, we need to support instantiation of etcd clients to any number of etcd server clusters within the same go process. Each etcd "clientv3" can be configured with a distinct set of endpoints that it should loadbalance across.  E.g.:

```
c1 := clientv3.New(clientv3.Config{Endpoints: []string{"http://127.0.0.1:1001", "http://127.0.0.1:1002", "http://127.0.0.1:1003"}})
c2 := clientv3.New(clientv3.Config{Endpoints: []string{"http://127.0.0.1:2001", "http://127.0.0.1:2002", "http://127.0.0.1:2003"}})
```

And our balancer picker would be able to select the appropriate endpoint for each client for each request.  Our WIP approach has been instantiate a resolver per "clientv3" instance.

Using a balancer per "clientv3" almost works, except we have the `Register` / `Get` issue we originally opened this issue about:

```
r1 := NewEtcdResolver("etcd-client1", endpoints1) // creates and registers the resolver on the fly
b1 := NewEtcdBalancer("etcd-client1-balancer") // creates and registers the balancer on the fly
grpc.DialContext(ctx, "etcd-client1:///http://127.0.0.1:1001", grpc.WithBalancerName("etcd-client1-balancer"))

r2 := NewEtcdResolver("etcd-client2", endpoints2)
b2 := NewEtcdBalancer("etcd-client2-balancer")
grpc.DialContext(ctx, "etcd-client1:///http://127.0.0.1:2001", grpc.WithBalancerName("etcd-client2-balancer"))
```

If we were to instead use a single balancer, I'm not sure how to set things up properly. We can't just do:

```
init() {
  balancer.Register(NewEtcdBalancer())
}

r1 := NewEtcdResolver("etcd-client1", endpoints) // creates and registers the resolver on the fly
grpc.DialContext(ctx, "etcd-client1:///http://127.0.0.1:1001", grpc.WithBalancerName("etcd-balancer-name"))

r2 := NewEtcdResolver("etcd-client2", endpoints) // creates and registers the resolver on the fly
grpc.DialContext(ctx, "etcd-client2:///http://127.0.0.1:2001", grpc.WithBalancerName("etcd-balancer-name"))
```

Because this results in two resolvers sending different sets of endpoints in `NewAddress` calls to a single balancer.

Is there a way to do this with a statically defined balancer that I'm missing or do we need to register balancers on the fly here?

**Comment by gyuho** [comment]
Just to add more of our etcd use cases: we may call `balancer.Register` concurrently in our balancer unit tests to test different set of pickers, and if multiple tests run with same balancer name, we randomize balancer names to avoid balancer register conflicts, but the racey write/read to `grpc/grpc-go/balancer.m` can still happen as described in this issue. It would be great if this shared map is protected in gRPC by default.

Thanks!

**Comment by lyuxuan** [comment]
In gRPC-go, for each `ClientConn `created by `DialContext()`, a resolver and a balancer that **only** service this `ClientConn` will be instantiated through specific resolver builder and balancer builder, which are configured through scheme prefix in the target string and the DialOption `WithBalancerName()` respectively. For example, the when dialing with the DialOption `WithBalancerName("ABC")`, grpc selects the balancer builder with the name "ABC" from the registered balancer builder table, and then use the selected builder to create a balancer just for this connection. The same goes for resolver.

I think the there might be some confusion here about balancer and balancer builder, as we recently introduced the concept of balancer builder. In a simple way, users are expected to register all the balancers builder implementation possibly needed during int(). And gRPC will use them to create desired balancer for each connection. Resolver and balancer are not shared across different `ClientConn`s. For more info about the architecture of resolver and resolver builder, balancer and balancer builder, you can refer to the deisgn doc [here](https://github.com/grpc/proposal/blob/master/L9-go-resolver-balancer-API.md). Thanks!

**Comment by jpbetz** [comment]
Thanks @lyuxuan that makes a lot of sense, I'll adjust our implementation to use the builders properly, that should solve my problem.
