### ISSUE TITLE
Is there a way to get the peer's address(server addr) in the client's Interceptor?

### ISSUE THREAD

**Issue by longXboy** [grpc/grpc-go#1978]
In the client's Interceptor cannot get the server's address through peer.FromContext (ctx), so there are other ways to get the server's address from the client's Interceptor?

**Comment by menghanl** [comment]
You can use `Peer` to retrieve peer information, note that the field is populated **after** the RPC finishes.

https://github.com/grpc/grpc-go/blob/7f73c863c0d52a3900bdd76ccaf08191ed51b714/rpc_util.go#L231-L235
