### ISSUE TITLE
Permit setting User-Agent

### ISSUE THREAD

**Issue by dsymonds** [grpc/grpc-go#198]
It'd be good to have some way to control the User-Agent used by the gRPC package, whether on a per-ClientConn or per-RPC basis (I don't care which). The use case is for client libraries that wrap gRPC to be able to indicate who they are.

**Comment by iamqizhao** [comment]
How to handle user-agent header is still under discussion. We have not
decided among i) grpc reserves it. do not allow users overwrite; ii) grpc
does not reserve it. it is simply a metadata and ii) grpc reserves it but
allows users overwrite. Will keep you posted.

**Comment by ebfio** [comment]
+1

**Comment by iamqizhao** [comment]
After some discussion, we will only support per-channel basis for now. It looks like
grpc-go/1.2.3 application-user-agent

I will have a PR shortly to implement this.

**Comment by dsymonds** [comment]
By "per-channel" you mean per-ClientConn? That's fine with me.

Note that http://tools.ietf.org/html/rfc7231#section-5.5.3 specifies that User-Agent should be ordered in descending order of identification specificity, so the application part should come first, and the grpc-go/1.2.3 tag should be added after that.

**Comment by iamqizhao** [comment]
On Wed, Jul 22, 2015 at 2:46 PM, David Symonds <notifications@github.com>
wrote:

> By "per-channel" you mean per-ClientConn? That's fine with me.
>
yup

> Note that http://tools.ietf.org/html/rfc7231#section-5.5.3 specifies that
> User-Agent should be ordered in descending order of identification
> specificity, so the application part should come first, and the
> grpc-go/1.2.3 tag should be added after that.
>
I will bring this up to the team. Thanks.

**Comment by iamqizhao** [comment]
closed via #255

**Comment by dsymonds** [comment]
Your #255 put the User-Agent strings in the wrong order. Please fix.

**Comment by iamqizhao** [comment]
I will keep this order until the team reaches the agreement on this.
Current all the other implementations use the current order.

**Comment by iamqizhao** [comment]
otherwise, the corresponding interop test will fail.

**Comment by dsymonds** [comment]
Can you reopen this bug to track this? And poke the team to change their
minds quickly?

**Comment by iamqizhao** [comment]
closed via #257
