### ISSUE TITLE
doc error: using NewClientTLSFromCert incorrectly for a server in the example of go

### ISSUE THREAD

**Issue by GingerMoon** [grpc/grpc-go#1980]
Please answer these questions before submitting your issue.
document error: using NewClientTLSFromCert for an http server incorrectly
https://grpc.io/docs/guides/auth.html

Server:
```go
creds := credentials.NewClientTLSFromCert(certFile, "")
s := grpc.NewServer(grpc.Creds(creds))
lis, _ := net.Listen("tcp", "localhost:50051")
// error handling omitted
s.Serve(lis)
```

It's very confusing and misleading for a new bee. If I am not a new bee, I will not need to read this doc.

expected:
NewServerTLSFromCert

**Comment by menghanl** [comment]
Thanks for point this out!
Please see https://github.com/grpc/grpc.github.io/pull/651 for the fix.

**Comment by GingerMoon** [comment]
thank you very much!
