### ISSUE TITLE
Unable to get transport.Stream from context

### ISSUE THREAD

**Issue by ZachEddy** [grpc/grpc-go#1992]
### What version of gRPC are you using?
v1.11.0

### What version of Go are you using (`go version`)?

go1.10 darwin/amd64

### What operating system (Linux, Windows, …) and version?
macOS 10.12.5

### What did you do?
I upgraded gRPC from v1.10.0 to v1.11.0.

### What do you see?

Without changing any code, I now get the following error inside my gRPC server interceptor:
```
undefined: transport.StreamFromContext
```

I see that #1904 removed `StreamFromContext(ctx)` from the `transport` package, which explains the error above. With the changes introduced in this pull request, I don't think it's currently possible to get a `transport.Stream` from the request context (the context key is private and a public getter no longer exists).

Looking at [this unit test](https://github.com/grpc/grpc-go/blob/master/server_test.go#L128), maybe exporting `grpc.serverTransportStreamFromContext` would fix the issue? If so, I'm happy to open a pull request.

Thanks!

**Comment by lyuxuan** [comment]
Since transport package is intended for internal usage, we unexported the `StreamFromContext(ctx)`. Instead, we added [`Method(ctx)`](https://godoc.org/google.golang.org/grpc#Method) function to get the method string from context. It should work for your case. Thanks!

**Comment by lyuxuan** [comment]
Can you let us know your purpose of getting the `transport.Stream`? `transport` package is really for grpc internal purpose, and we don't want to expose things to users. Please let us know about your use case for the `transport.Stream`, we could probably figure out some thing for you. Thanks!

**Comment by ZachEddy** [comment]
Thanks for the speedy response, @lyuxuan! 

I'm writing a server interceptor that uses the `transport.Stream` from an incoming request. Specifically, I use the `transport.Stream` to determine the service name (e.g. PetStore) and method name (e.g. ListPets) of a given request.

To get the stream itself, I called `transport.StreamFromContext(ctx)` and from that point I could call `stream.GetMethod()` to get the service and method names.

Is that helpful?

**Comment by lyuxuan** [comment]
Thank you @ZachEddy. For your case, we provide [`Method(ctx)`](https://godoc.org/google.golang.org/grpc#Method) in `grpc package` to get the service and method strings from the context.

**Comment by ZachEddy** [comment]
Awesome — that did the trick 🎉 

Thanks for your help!
