### ISSUE TITLE
Support turning off TXT lookups in DNS resolver

### ISSUE THREAD

**Issue by Teddy-Schmitz** [grpc/grpc-go#1998]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.10.0
### What version of Go are you using (`go version`)?
1.10
### What operating system (Linux, Windows, …) and version?
Linux
### What did you do?

Use the DNS resolver
### What did you expect to see?
No log messages
### What did you see instead?
Lots and lots of warning messages

It would be nice if it was possible to configure the resolver to not try to get TXT records to configure grpc.  We don't use that functionality and our logs are filled with warning lines about not being able to resolve or parse TXT records.

**Comment by lyuxuan** [comment]
Thanks for the suggestion. We are willing to change the log level from warning to info. Does that sound ok to you?

**Comment by Teddy-Schmitz** [comment]
That would work for us as well, thanks.  

Though I think longer term it would still be good to be able to turn it off as to not waste CPU on the DNS resolver nor the local machine trying for a TXT record we know will fail.
