### ISSUE TITLE
Difficulty using Balancer API

### ISSUE THREAD

**Issue by jsha** [grpc/grpc-go#2012]
gRPC v1.9.2, Go 1.10.1, Linux

I'm trying to update Boulder's [creds](https://github.com/letsencrypt/boulder/blob/master/grpc/creds/creds.go) and [balancer](https://github.com/letsencrypt/boulder/blob/master/grpc/balancer.go) from the v1.1 APIs to the v1.9.2 APIs. I am using the `manual` resolver, with a static list of backend addresses configured at startup time. I keep running into problems with the ServerName not matching.

My setup is that I have multiple named hosts, e.g. `sa1.example.com`, `sa2.example.com`, `sa3.example.com`, and the gRPC service on each host has a server certificate valid for its own hostname (not a generic service name). As best as I can tell by reading the grpc code, it looks like the assumption is that the expected `ServerName` is a static property of a `TransportCredentials` and can't be affected by a resolver. Is that an accurate interpretation? Is there any way to make the expected ServerName depend on the name of the host being connected to?

Thanks,
Jacob

**Comment by menghanl** [comment]
Yes, your understanding is correct. A `ClientConn` is one service name.

Also see this comment: https://github.com/grpc/grpc-go/issues/1627#issuecomment-340599404
