### ISSUE TITLE
Goroutine leaks on streams - unclear purpose of CloseSend

### ISSUE THREAD

**Issue by cstockton** [grpc/grpc-go#2015]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
tried master (d27df52a27ae0f6e08b19846f31eaf7d86e6bfa4) & most recent tag

### What version of Go are you using (`go version`)?
1.10.1

### What operating system (Linux, Windows, …) and version?
linux

### What did you do?
I am calling a package that returns a stream, such as:

```Go
stream, err := pkgthat.ReturnsStream(ctx, PkgRequest{...})
if err != nil {
	return nil, err
}
defer stream.CloseSend()
```

At one particular call site, I am performing an "exact search" and can exit for the first item that matches:

```Go
p, err := stream.Recv()
if err != nil {
	return nil, err
}
return p, nil
```

This leaks one goroutine each created stream here: https://github.com/grpc/grpc-go/blob/master/stream.go#L300 - Iterating the stream until EOF does not leak goroutines, nor does adding a new context before the function call and canceling it when I exit.

### What did you expect to see?

No goroutines leaked, the API is not very clear to me in general- "CloseSend" makes me think I am closing the sends, but perhaps it has another meaning? It is also not clear why a goroutine is needed here, it seems as if the context I give the function is what signals it to exit, but then what is the purpose of CloseSend? These are "auto" generated and contain no documentation in the API I am calling.

Is there a way to avoid the condition below that causes the goroutine to start? https://github.com/grpc/grpc-go/blob/master/stream.go#L294 - I would prefer this over any other solution. 

### What did you see instead?

1 goroutine leaked each call.

### Thoughts:
-------

At the very end of writing this issue I came across this comment in the code: https://github.com/grpc/grpc-go/blob/master/stream.go#L552 - it appears that the users must call recv until it returns a non-nil err. This made me think I suddenly understood what is at play here, so I modified my code to:

```Go
p, err := stream.Recv()
if err != nil {
	return nil, err
}
stream.CloseSend()
_, err = stream.Recv()
fmt.Println(err)
return p, nil
```

Figured it was not very intuitive but at least I had a work around, but much to my surprise err was still nil- even after an explicit call to CloseSend. It turns out that CloseSend streams the same amount of values no matter when I call CloseSend. Most GRPC api docs I've come across look like: https://godoc.org/github.com/osrg/gobgp/api - now perhaps it's on me for not visiting https://godoc.org/google.golang.org/grpc#ClientStream. I am still confused after reading the documentation for stream though:

```Go
    // CloseSend closes the send direction of the stream. It closes the stream
    // when non-nil error is met.
    CloseSend() error
    // Stream.SendMsg() may return a non-nil error when something wrong happens sending
    // the request. The returned error indicates the status of this sending, not the final
    // status of the RPC.
    //
    // Always call Stream.RecvMsg() to drain the stream and get the final
    // status, otherwise there could be leaked resources.
    Stream
```

I feel like CloseSend should trigger the EOF condition and free all resources, or not exist. Having "defer stream.CloseSend()" feels precisely like io.Closer except it doesn't really do anything- Recv() could perform CloseSend when it hits it's condition to terminate, since it's the only authority on when a stream is truly done. I'm not sure what options are available now though since it's a core interface, maybe an atomic counter for each one of those goroutines and log a message beyond a threshold for anyone who makes a similar mistake?

**Comment by lyuxuan** [comment]
`CloseSend()` is called by client to signal server that it has sent all the messages it want to send, and will send no more message, i.e 

> closes the send direction of the stream.

However, server is still free to send whatever message(s) it wants to send to client, and rpc is still alive. It's not until client receives  the trailer/RST_STREAM sent by server or rpc context has expired/cancelled, that the rpc is indeed ended.

In the comment of this [commit](https://github.com/grpc/grpc-go/commit/365770fcbd7dfb9d921cb44827ede770f33be44f), it describes four conditions for a stream to be fully cleaned up. I think you've found two of them, which are calling `RecvMsg` until non-nil error occurs and cancelling the context , i.e.

> iterating the stream until EOF does not leak goroutines, nor does adding a new context before the function call and canceling it when I exit.

In summary, `CloseSend()` does not end an rpc call, and thus will not release the resources related to the stream. To cleanly end a rpc call, one must use one of the four ways as described [here](https://github.com/grpc/grpc-go/commit/365770fcbd7dfb9d921cb44827ede770f33be44f).

**Comment by cstockton** [comment]
> In summary, CloseSend() does not end an rpc call, and thus will not release the resources related to the stream. To cleanly end a rpc call, one must use one of the four ways as described here.

I think I understand how it works now, but feel it is unexpected for a goroutine to stay running after calling a function that has the name Close in it. Having so many conditions for a stream to be closed doesn't seem right already, but adding to this CloseSend not actually closing anything- but rather "Asking politely" to stop is probably the main issue here.

I'm having trouble understanding the benefits of the current design. When does someone want to ask the server to stop sending messages, but not terminate the connection? I guess my point here is based on what I've read the purpose of CloseSend is to indicate the client no longer wishes to receive messages by **asking** the server to stop sending. Since it is the clients intent to no longer Recv, that intent should be immediately honored by closing the connection.

**Comment by lyuxuan** [comment]
HTTP2 has a notion of `half-closed` for stream state. `CloseSend()` is the corresponding function call that will make client side stream enter the `half-closed (local)` state. The name of the function does precisely reflect its functionality. Please refer to the HTTP2 spec [here](https://tools.ietf.org/html/rfc7540#section-5.1) for more details about `half-closed`.



> I'm having trouble understanding the benefits of the current design. When does someone want to ask the server to stop sending messages, but not terminate the connection? I guess my point here is based on what I've read the purpose of CloseSend is to indicate the client no longer wishes to receive messages by asking the server to stop sending. Since it is the clients intent to no longer Recv, that intent should be immediately honored by closing the connection.

You may have some misunderstanding here. `CloseSend()` means client will no longer send message to server, not asking the server to stop sending messages, and client will be willing to receive messages from server. It only stops local sending.

**Comment by cstockton** [comment]
> You may have some misunderstanding here. CloseSend() means client will no longer send message to server, not asking the server to stop sending messages, and client will be willing to receive messages from server. It only stops local sending.

Yes I was misunderstanding, this is very surprising to me. The api I am calling https://godoc.org/github.com/osrg/gobgp/api#GobgpApi_GetPathClient doesn't even support sending messages. I assumed "send direction" would be the server since no methods are exposed for me to "Send" anything, I only call the "Recv" function so it seemed reasonable to think the server is calling a "Send" function since the documentation also says:

>      // CloseSend closes the send direction of the stream. It closes the stream
>     // when non-nil error is met.
>     CloseSend() error

I really want to avoid exiting a function without control of the running goroutines, instead explicitly free resources before returning to callers. Currently that is impossible without draining the entire channel but that is just unacceptable, there can be tens of thousands of items. It potentially opens up a denial of service vulnerability if a caller can find a code path that queues such a large stream and immediately disconnect. Currently my only work around is to increase the cost of a user request by at least 2 goroutines (depending on current ctx) and use the [the stream.go](https://github.com/grpc/grpc-go/blob/master/stream.go#L300) with context.WithTimeout - but I still have to exit that function scope with the "cleanup" goroutine started by GRPC live and hope it exists timely.

Having to think so much to free a simple network resource is a good sign it just needs an io.Closer in my opinion. Then I can put in a defer after my connect statement and break the recv loop as needed. Since I assume the interface is frozen what about implementing io.Closer on stream? Then I can do the below and return to caller knowing all resources in that call frame are free:

```Go
func streamClose(sr stream) (err error) {
	switch T := sr.(type) {
	case io.Closer:
		err = T.Close() // compiled with grpc that supports io.Closer
	case GobgpApi_GetPathClient:
		for err == nil {
			_, err = stream.Recv() // recv messages for no reason >_<
		}
  case ...:
    ...
	}
	return
}
stream, err := pkgthat.ReturnsStream(ctx, PkgRequest{...})
if err != nil {
	return nil, err
}
defer streamClose(stream)
```

**Comment by dfawley** [comment]
@cstockton you can call the context's cancel() function to fully terminate the stream on the client side, without needing to receive all of the data from it.

**Comment by dfawley** [comment]
OK, I see what you're saying now.  #1933 covers this same concern.  Note that our hands are a bit tied with the current API, due to the use of interfaces, so any changes here will be harder to use than we'd like.  I.e. you'll need to do something like one/either of `stream.(io.Closer).Close()` or `grpc.CancelClientStream(stream)`.
