### ISSUE TITLE
"unsafe" dependency causing App Engine to break

### ISSUE THREAD

**Issue by colesimmons** [grpc/grpc-go#2022]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.11.3

### What version of Go are you using (`go version`)?
1.8

### What operating system (Linux, Windows, …) and version?
macOS 10.13.1

### What did you do?
First of all, I'd like to apologize if this a dumb issue, but I don't have a ton of experience with Go and its dependency management system!

I've been using the [Firebase Admin SDK](https://godoc.org/firebase.google.com/go) which has gRPC as a dependency. I ran `go get -u` earlier, which upgraded, among other things, gRPC to the [commit](https://github.com/grpc/grpc-go/commit/e8a6e2844b5d361a53025d9b27f5f7b404a50f45) made today where `unsafe` is included as a dependency. `unsafe` is not compatible with the App Engine Go Standard Environment, so this has been a massively breaking change.

### What did you expect to see?
Successful build

### What did you see instead?
`go-app-builder: Failed parsing input: parser: bad import "unsafe" in google.golang.org/grpc/backoff.go from GOPATH`

**Comment by menghanl** [comment]
fixed by #2023

**Comment by colesimmons** [comment]
Thank you!
