### ISSUE TITLE
Headers Not Returned on Errors

### ISSUE THREAD

**Issue by joshuarubin** [grpc/grpc-go#2037]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

`master` branch

### What version of Go are you using (`go version`)?

`go version go1.10.1 darwin/amd64`

### What operating system (Linux, Windows, …) and version?

`MacOS`

### What did you do?
If possible, provide a recipe for reproducing the error.

When using the `grpc.Header(&md)` `grpc.CallOption`, if the endpoint returns an error, `md` is not populated.

### What did you expect to see?

`md` should have the response headers.

### What did you see instead?

`md` is empty.

I've traced the issue down to the `http2Client.operateHeaders` method. The issue stems from the response headers having `flags=END_STREAM|END_HEADERS`.

Here is some example output with `GODEBUG=http2debug=2`:

```
2018/04/30 17:25:00 http2: Framer 0xc4205107e0: wrote HEADERS flags=END_HEADERS stream=1 len=169
2018/04/30 17:25:00 http2: Framer 0xc4205107e0: wrote DATA flags=END_STREAM stream=1 len=10 data="\x00\x00\x00\x00\x05\n\x03foo"
2018/04/30 17:25:00 http2: Framer 0xc4205107e0: read SETTINGS len=6, settings: INITIAL_WINDOW_SIZE=268435456
2018/04/30 17:25:00 http2: Framer 0xc4205107e0: read WINDOW_UPDATE len=4 (conn) incr=268369921
2018/04/30 17:25:00 http2: Framer 0xc4205107e0: read SETTINGS flags=ACK len=0
2018/04/30 17:25:00 http2: Framer 0xc4205107e0: wrote SETTINGS flags=ACK len=0
2018/04/30 17:25:00 http2: Framer 0xc4205107e0: read HEADERS flags=END_STREAM|END_HEADERS stream=1 len=148
2018/04/30 17:25:00 http2: decoded hpack field header field ":status" = "200"
2018/04/30 17:25:00 http2: decoded hpack field header field "content-type" = "application/grpc"
2018/04/30 17:25:00 http2: decoded hpack field header field "grpc-status" = "5"
2018/04/30 17:25:00 http2: decoded hpack field header field "grpc-message" = "some error"
2018/04/30 17:25:00 http2: decoded hpack field header field "date" = "Mon, 30 Apr 2018 23:25:00 GMT"
```

It seems that `http2Client.operateHeaders` will only copy in the headers if `!stream.headerDone && !frame.StreamEnded()`. However, in this case the headers _only_ come with the `END_STREAM` flag.

I think that the correct approach is to check, rather than for `!frame.StreamEnded()`, simply for `frame.HeadersEnded()`.

The following patch seems to fix the issue for me, but I am not too familiar with the http2 protocol and if this works in all cases. Tests on `google.golang.org/grpc/transport` and `google.golang.org/grpc` do succeed with this patch though.

```diff
diff --git a/transport/http2_client.go b/transport/http2_client.go
index a55c3c1..75cf3c5 100644
--- a/transport/http2_client.go
+++ b/transport/http2_client.go
@@ -1027,7 +1027,6 @@ func (t *http2Client) operateHeaders(frame *http2.MetaHeadersFrame) {
                return
        }
 
-       endStream := frame.StreamEnded()
        var isHeader bool
        defer func() {
                if t.statsHandler != nil {
@@ -1048,7 +1047,7 @@ func (t *http2Client) operateHeaders(frame *http2.MetaHeadersFrame) {
        }()
        // If headers haven't been received yet.
        if atomic.SwapUint32(&s.headerDone, 1) == 0 {
-               if !endStream {
+               if frame.HeadersEnded() {
                        // Headers frame is not actually a trailers-only frame.
                        isHeader = true
                        // These values can be set without any synchronization because
@@ -1061,7 +1060,7 @@ func (t *http2Client) operateHeaders(frame *http2.MetaHeadersFrame) {
                }
                close(s.headerChan)
        }
-       if !endStream {
+       if !frame.StreamEnded() {
                return
        }
        t.closeStream(s, io.EOF, false, http2.ErrCodeNo, state.status(), state.mdata, true)
```

**Comment by MakMukhi** [comment]
The gRPC server can return trailer only responses in error cases. Metadata in those trailers can be accessed by the [`grpc.Trailer`](https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L213) call option.

**Comment by joshuarubin** [comment]
The Trailer got me enough info out of the error. Thanks a bunch.
