### ISSUE TITLE
vet.sh does not work in mac

### ISSUE THREAD

**Issue by jadekler** [grpc/grpc-go#2047]
### What version of Go are you using (`go version`)?

`go version go1.10.1 darwin/amd64`

### What operating system (Linux, Windows, …) and version?

macOS High Sierra

### What did you do?

`vet.sh`

### What did you expect to see?

Errors per https://travis-ci.org/grpc/grpc-go/jobs/373732686

### What did you see instead?

Silent failure:

```
deklerk at klerk-macbookpro in ~/workspace/go/src/google.golang.org/grpc on withtimeout_cleanup
$ ./vet.sh
+ set -o pipefail
+ PATH=/Users/deklerk/workspace/go/bin:/bin:/Users/deklerk/.rbenv/shims:/Users/deklerk/.rbenv/bin:/usr/local/opt/python/libexec/bin:/Users/deklerk/.rbenv/shims:/Users/deklerk/.rbenv/bin:/usr/local/opt/python/libexec/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:/Users/deklerk/dev/google-cloud-sdk/bin:/Users/deklerk/dev/protoc-3.5.1/bin:/Users/deklerk/workspace/go/bin:/Users/deklerk/dev/apache-maven-3.5.2/bin:/Users/deklerk/dev/google-cloud-sdk/bin:/Users/deklerk/dev/protoc-3.5.1/bin:/Users/deklerk/workspace/go/bin:/Users/deklerk/dev/apache-maven-3.5.2/bin:/Users/deklerk/dev/android-tools/bin
+ [[ '' != \t\r\u\e ]]
+ check_proto=true
+ '[' '' = -install ']'
+ [[ 0 -ne 0 ]]
+ git status --porcelain
+ read
+ git ls-files '*.go'
+ xargs grep -L '\(Copyright [0-9]\{4,\} gRPC authors\)\|DO NOT EDIT'
+ tee /dev/stderr
+ read
deklerk at klerk-macbookpro in ~/workspace/go/src/google.golang.org/grpc on withtimeout_cleanup
$ echo $?
1
```

Also, it shouldn't be failing on that line. There's nothing wrong with Copyright notice. It should be failing further down in `go tool vet -all .`.

**Comment by jadekler** [comment]
More info: it appears as though the following line

```
git ls-files "*.go" | xargs grep -L "\(Copyright [0-9]\{4,\} gRPC authors\)\|DO NOT EDIT" 2>&1 | tee /dev/stderr | (! read)
```

Works perfectly until the `(! read)`. It seems as though the `set -e` fails on `read` and never gets to the 'not' (`! read`) part.

This is probably some subtly different behavior in mac that we need to account for.

Also, the sed further down seems to not work either. Haven't investigated that.

**Comment by easwars** [comment]
With #3452 and #3469, vet.sh should work just fine on darwin.
