### ISSUE TITLE
undefined: proto.InternalMessageInfo

### ISSUE THREAD

**Issue by lijianwh** [grpc/grpc-go#2053]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
latest
### What version of Go are you using (`go version`)?
go version go1.9.4 linux/amd64
### What operating system (Linux, Windows, …) and version?
Linux
### What did you do?
when I use `go get` to install the package “google.golang.org/grpc/health/grpc_health_v1”
```
go get google.golang.org/grpc/health/grpc_health_v1
# google.golang.org/grpc/health/grpc_health_v1
../../google.golang.org/grpc/health/grpc_health_v1/health.pb.go:81:40: undefined: proto.InternalMessageInfo
../../google.golang.org/grpc/health/grpc_health_v1/health.pb.go:119:41: undefined: proto.InternalMessageInfo
```

### What did you expect to see?
install the package smoothly
### What did you see instead?
the install fail with `undefined: proto.InternalMessageInfo`

**Comment by dfawley** [comment]
Please make sure your proto package is up-to-date: `go get -u github.com/golang/protobuf/proto`

**Comment by lijianwh** [comment]
`go get -u github.com/golang/protobuf/proto` does't work for me, I use `go get google.golang.org/grpc/health/grpc_health_v1` instead, it works. Thanks!

**Comment by dfawley** [comment]
Great, thanks for sharing the fix.
