### ISSUE TITLE
Hook after method execution

### ISSUE THREAD

**Issue by bleleve** [grpc/grpc-go#2065]
Hi there,

In the same way that interceptors allow to run hooks before the request is executed, it could be interesting to create the same logic after the execution.

I looked for any such mechanism without success.

I have implemented a Redis cache with an interceptor and need to reset some cache keys after the request succeeds. I have integrated this in the interceptor but it is not the most adapted.

Is there a more efficient method? What is your opinion?

Thank you all !

**Comment by lyuxuan** [comment]
Interceptor is supposed to be able to run hooks before and after the request is executed. For example, for client unary case:
```
func yourInterceptor(ctx context.Context, method string, req, reply interface{}, cc *ClientConn, invoker UnaryInvoker, opts ...CallOption) error {
	// hooks before the request
	err := invoker(ctx, method, req, reply, cc, opts...)
	// hooks after the request
}
```
Please let us know if this doesn't work for you. Thanks!

**Comment by bleleve** [comment]
Hi lyuxuan,

This is a client interceptor, can I do the same with the server interceptor (and call handler()) ? In the interceptor doc it is announced as intended to be run only before.

Best regards.

**Comment by lyuxuan** [comment]
Hi @bleleve, server interceptor should work the same way like client interceptor, applicable for both pre- and post- request processing.

BTW, could you please let us know about the doc that says the interceptor is intended to be run only before so we could possibly fix it? Thanks!

**Comment by bleleve** [comment]
Hi lyuxuan,

On the gRPC middleware repository, server side interceptors are only indicated as being available before the request (https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/README.md) :

gRPC Go recently acquired support for Interceptors, i.e. middleware that is executed either on the gRPC Server before the request is passed onto the user's application logic, or on the gRPC client either around the user call.

Best regards.

**Comment by lyuxuan** [comment]
Hi @bleleve, thanks for the info. I think the description they have is more for the middleware itself, not grpc-go in general. For their chaining feature, all the interceptors are executed before the handler is called. However, grpc itself is more flexible in that you can call the handler whenever you want (even not calling it).Please let us know if you encounter any issue using the interceptor. Thanks! (closing the issue as I think the initial question has been answered)
