### ISSUE TITLE
Naming services

### ISSUE THREAD

**Issue by JCzz** [grpc/grpc-go#2075]
Please answer these questions before submitting your issue.

proto3

Is it possible to name a service?

```
	s := grpc.NewServer()
	s.ServiceName = "myapp.helloworld"
```

Or in protofile?

**Comment by menghanl** [comment]
The service name is generated from proto files. It's currently not possible to rename a service. You could modify your proto file and regenearte pb.go files.

**Comment by JCzz** [comment]
Thanks @menghanl

**Comment by menghanl** [comment]
Closing issue now. Please comment if you have further questions!
