### ISSUE TITLE
high memory usage: Idle connections are not closed despite MaxConnectionIdle is set

### ISSUE THREAD

**Issue by avikio** [grpc/grpc-go#2086]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.12
### What version of Go are you using (`go version`)?
go version go1.10.2 windows/amd64
### What operating system (Linux, Windows, …) and version?
Windows 10
### What did you do?
I have a simple bidirectional rpc function and I wanted to test what happens if a client doesn't explicitly close the connection.
**Server**
```
func (rpcService *RpcService) Start() error {
	lis, err := net.Listen("tcp", ":1234")
	if err != nil {
		return err
	}
	serverParameters := keepalive.ServerParameters{}
	serverParameters.MaxConnectionIdle = 1 * time.Minute
	grpcServer := grpc.NewServer(grpc.KeepaliveParams(serverParameters))
	dto.RegisterOperationServiceServer(grpcServer, rpcService)
	err = grpcServer.Serve(lis)
	if err != nil {
		return err
	}
	return err
}
```
```
func (rpcService *RpcService) StreamMessages(stream dto.OperationService_StreamMessagesServer) error {
	for {
		message, err := stream.Recv()
		if err == io.EOF {
			return err
		}
		if err != nil {
			return err
		}
	}
}
```

**Client**
```
func TestSendManyMessages(t *testing.T) {
	for i := 0; i < 5000; i++ {
		conn, err := grpc.Dial("localhost:1234", grpc.WithInsecure())
		if err != nil {
			log.Fatalf("failed to connect: %s", err)
		}

		client := dto.NewOperationServiceClient(conn)
		stream, err := client.StreamMessages(context.Background())
		msg := &dto.Message{}
		err = stream.Send(msg)
		if err != nil {
			fmt.Print(err)
		}
		// the client close the stream but don't close the connection !!
		stream.CloseSend()
		//conn.Close()
	}
}
```
### What did you expect to see?
At first I expected the connection to be closed after the client close the stream.
It was not the case so I added MaxConnectionIdle (1min) on the server side but it didn't change anything. I don't see any public api allowing me to close connection from server side.

### What did you see instead?
Very high memory usage.
If I run this test twice (10000 iterations) the server use more than 800MB of memory.
The memory start decreasing a long time after the tests runs.

**Comment by avikio** [comment]
I understand your arguments but I want to expose my grpc server on internet.
How can I prevent malicious users to crash my server? 
It took me only few minutes to make it consumes several gigabytes of memory just by running this simple code.

**Comment by menghanl** [comment]
To protect your server, you will need authorization.

You could start with [this doc](https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-auth-support.md), or search for other related topics on the internet.
