### ISSUE TITLE
Server abruptly terminates connections if write buffer is small enough

### ISSUE THREAD

**Issue by euroelessar** [grpc/grpc-go#2089]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
grpc-1.12.0

### What version of Go are you using (`go version`)?
go version go1.8.4 linux/amd64

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
Started a server with 8KB write buffer (using `grpc.WriteBufferSize`) in order to reduce per-connection memory usage by paying extra cpu cost.

### What did you expect to see?
Server successfully processes incoming connections and requests.

### What did you see instead?
Server abruptly terminates incoming connection if http2 frame size happens to be greater than write buffer size.
It happens due to combination of following factors:
1. `bufWriter` gives up if incoming data is greater than its buffer size and returns non-nil error:
https://github.com/grpc/grpc-go/blob/master/transport/http_util.go#L530
2. http2 framer library verifies that writer doesn't violate `Writer` interfaces and returns `io.ErrShortWrite`:
https://github.com/golang/net/blob/master/http2/frame.go#L368
3. gRPC http server doesn't tolerate any errors and terminates tcp socket:
https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L278

I would assume that this is also true for outgoing client connections due to shared code but didn't try to reproduce it.

**Comment by MakMukhi** [comment]
Thanks for reporting. I'll take a look at it shortly.

**Comment by euroelessar** [comment]
@MakMukhi hi, any chance this can be part of patch release?

**Comment by menghanl** [comment]
@euroelessar Sorry, just release 1.12.1 but missed this...
Will make another release with this.

There's also another release request (#2125), but I'm a bit unsure about the mentioned PR. If you don't mind, I will want for their reply and combine the releases.
Expect a minor by tomorrow.

**Comment by euroelessar** [comment]
that works for me, thanks!

**Comment by menghanl** [comment]
@euroelessar Please see https://github.com/grpc/grpc-go/releases/tag/v1.12.2 for the release.
