### ISSUE TITLE
Type safe metadata or layering RPC methods

### ISSUE THREAD

**Issue by meling** [grpc/grpc-go#2091]
In our [relab/gorums](https://github.com/relab/gorums) project, we have come across an issue related to layering. That is, we wish to augment RPC calls with metadata that gets processed by an interceptor and stripped before being passed on to the user-defined server method.

*Background:* In gorums, we can specify an option on an RPC method to generate (client-side) code for invoking this method on multiple servers, and collecting and coalescing the replies into a single reply. Now, this works fine as long as we only work with client-side generated code, and the data being passed to the servers is defined as messages in the proto file. 

*What we want to achieve:* In some on going work, we are interested in intercepting invocations and augmenting the call with metadata, e.g. an epoch number, which can be intercepted and unwrapped on the server-side before invoking the server-side (application-level) RPC method. Likewise, we wish to intercept the return value on the server-side, and augment this reply with some metadata, e.g. the set of active servers, which again will be intercepted and stripped at the client-side interceptor, before being returned to the client application. 

*Solutions:* So far, we have two solutions, both of which I'm not particularly happy with.

1. Use the `grpc.metadata` package. This sort of works but is not type safe in that everything is a string.
2. For each RPC method `X` and message `Y`, generate two methods `X` and `gX` and two messages `Y` and `gY`, where the `gY` encapsulate the message `Y` along with another `Metadata` message. This is bad in that both RPC methods become accessible, and the metadata field of the message is also exposed, i.e., no encapsulation.

My question is if there is some other way to augment calls with metadata in a type safe way and at the same time avoid exposing RPC methods and messages to users?? I would love to hear any other recommendations.

**Comment by lyuxuan** [comment]
For the metadata approach, you can use a type safe mechanism(e.g. protobuf, json, etc) to enforce type safety. On one side, in the interceptor, define typed data, marshal it into bytes and then convert to string to be carried inside metadata. And on the other side, inside interceptor, you get the string, convert to bytes and use an unmarshaler to convert them to type safe data. Unfortunately, you have to do these conversions, marshaling and unmarshaling yourself, as grpc currently doesn't support such things over metadata. Please let us know if you have any further question. Thanks!
