### ISSUE TITLE
Unable to use log env vars

### ISSUE THREAD

**Issue by snktagarwal** [grpc/grpc-go#2097]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.10.0

### What version of Go are you using (`go version`)?
1.9.2

### What operating system (Linux, Windows, …) and version?
Alpine

### What did you do?
Enabled the env flags that look like:
GRPC_GO_LOG_SEVERITY_LEVEL=info
GRPC_GO_LOG_VERBOSITY_LEVEL=2

Other env vars, if relevant:
GOLANG_VERSION=1.9.2
GOPATH=/go
CGO_ENABLED=1

I don't see any transport logs when I have a streaming RPC back and forth. Is there something I am doing wrong?

Cheers
--Sanket

**Comment by menghanl** [comment]
Can you try this command and see if it works?

Start the server:
```sh
go run examples/helloworld/greeter_server/main.go
```

Run the client:
```sh
GRPC_GO_LOG_SEVERITY_LEVEL=info go run examples/helloworld/greeter_client/main.go
```
With `GRPC_GO_LOG_SEVERITY_LEVEL=info`, the output I got is:
```
INFO: 2018/05/22 16:47:05 parsed scheme: ""
INFO: 2018/05/22 16:47:05 scheme "" not registered, fallback to default scheme
INFO: 2018/05/22 16:47:05 ccResolverWrapper: sending new addresses to cc: [{localhost:50051 0  <nil>}]
INFO: 2018/05/22 16:47:05 ClientConn switching balancer to "pick_first"
INFO: 2018/05/22 16:47:05 pickfirstBalancer: HandleSubConnStateChange: 0xc420184060, CONNECTING
INFO: 2018/05/22 16:47:05 pickfirstBalancer: HandleSubConnStateChange: 0xc420184060, READY
2018/05/22 16:47:05 Greeting: Hello world
```

**Comment by snktagarwal** [comment]
Yeah, I manage to get these logs on `client` side. But interestingly I don't see any `server` gRPC logs when the RPC is in action. I am running the server as:
`GRPC_GO_LOG_SEVERITY_LEVEL=info go run examples/helloworld/greeter_server/main.go`

**Comment by menghanl** [comment]
There's currently much less info logs on the server side than the client side. But if you made it work on the client side, it should be the same thing on the server side.

**Comment by snktagarwal** [comment]
Is there a DEBUG level?

To give more motivation, we're trying to figure out why sometimes we see backup (or so it seems) in our gRPC calls. Basically we have NodeJS <-> GoLang gRPC and we see that sometimes the client is not able to push data to the RPC. My understanding is that could happen if the `server` blocks or other possible issues on NodeJS side itself.

To get more information I am trying to get more debugging information printed. Do you have suggestion on how I should about it?

**Comment by menghanl** [comment]
There's currently no DEBUG level.

Maybe try this: `GODEBUG=http2debug=2`, this shows frame level information, so you will know what's sent and what's received.

And also try to turn on client side logging on the client side?
