### ISSUE TITLE
Feature Request: Adding RPC Info to Picker

### ISSUE THREAD

**Issue by mfycheng** [grpc/grpc-go#2103]
## Background

We currently use grpc-java for most of our internal infrastructure, and have written a custom resolver / loadbalancer / picker that uses a ZooKeeper backed service registry, along with additional routing rules.
We've implemented it roughly:

1. A resolver that retrieves all of the endpoints (for all services) from ZooKeeper, along with their routing metadata
2. A load balancer that partitions the resolved endpoints into services
3. A picker that uses a pool of endpoints for the service of the RPC, then filters the set down based on routing rules.

Currently, grpc-go supports all of these API's / construct, but is missing RPC info from the Picker interface that's required in this situation to select
the pool of endpoints for a given service. In Java, the PickerOptions contains the call options, headers, and method descriptor[1] (method descriptor
being the one of interest in this particular case).

## Implementation

I'm fully willing to try and implement an equivalent feature set here, but I wanted to get a little feedback about the correctness of this use case,
or alternative approaches.

1. Add equiavlent fields to the `balancer.PickerOptions`. I believe this can be done simply for the method name, at least, but not so sure about the others.
2. Add similar information to the `context` that's passed into the picker.
3. Don't touch the grpc internals, and instead write our own `ClientConn` implementation that maintains multiple `ClientConn`s on a per-service basis. (related: https://github.com/grpc/grpc-go/issues/1287)

For our particular use case, the only thing that we really care about is the method name and any caller context, but I figured it would be nice to expose the other things as well for consistency, in case
other users need access to them. For now, I've manually hole punched the method name through https://github.com/grpc/grpc-go/blob/master/stream.go#L269, which seems to work, but is a little hacky.

[1] https://github.com/grpc/grpc-java/blob/61f2528ccd839199de2a750bad407b188a6fe68d/core/src/main/java/io/grpc/LoadBalancer.java#L189

**Comment by menghanl** [comment]
The main problem in this issue is fixed by #2204. The other fields can be added similarly if people are interested in them.

Closing now. Please comment if it's still a problem.
