### ISSUE TITLE
Memory leak of gRPC server

### ISSUE THREAD

**Issue by dreamflyfengzi** [grpc/grpc-go#2110]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
master 1.12.0 
### What version of Go are you using (`go version`)?
go 1.9.2
### What operating system (Linux, Windows, …) and version?
 Linux ip-172-31-26-2 4.4.0-1060-aws #69-Ubuntu SMP Sun May 20 13:42:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### What did you do?

I'm using grpc-go in server side and uses http in the client side. 

The problem is that the gRPC server leaks memory. Both heap size and number of go routines grows linearly!
The result of /debug/pprof/heap & /debug/pprof/goroutine are attach at the
end of this issue.

I guess the reason is that there is something bad happens at flow control of the underlying
HTTP2 stream. And many go routines stuck at google.golang.org/grpc/transport.(*quotaPool).get.
The gRPC server is unable to aquire quota and write out the response.

the issue like the right issue  [Memory leak of gRPC server](https://github.com/grpc/grpc-go/issues/1685) 

```
goroutine 6964741 [select, 1342 minutes]:
github.com/nebulasio/go-nebulas/vendor/google.golang.org/grpc/transport.(*quotaPool).get(0xc44b15f540, 0x7fffffff, 0x1762f60, 0xc4497f5a40, 0x1762ea0, 0xc420cb4480, 0x0, 0x0, 0x3dea, 0xc400000000, ...)
	/neb/golang/src/github.com/nebulasio/go-nebulas/vendor/google.golang.org/grpc/transport/control.go:191 +0x27a
github.com/nebulasio/go-nebulas/vendor/google.golang.org/grpc/transport.(*http2Server).Write(0xc420d62a80, 0xc44396be00, 0xc4d1cbc000, 0x5, 0x4000, 0xc4de572000, 0x64718c, 0x742000, 0xc436a8fd0c, 0xc436a8fd10, ...)
	/neb/golang/src/github.com/nebulasio/go-nebulas/vendor/google.golang.org/grpc/transport/http2_server.go:876 +0x6d2
github.com/nebulasio/go-nebulas/vendor/google.golang.org/grpc.(*Server).sendResponse(0xc420567e40, 0x1766fa0, 0xc420d62a80, 0xc44396be00, 0xe18040, 0xc42017acc0, 0x0, 0x0, 0xc436a8fd0c, 0x0, ...)
	/neb/golang/src/github.com/nebulasio/go-nebulas/vendor/google.golang.org/grpc/server.go:770 +0x277
github.com/nebulasio/go-nebulas/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420567e40, 0x1766fa0, 0xc420d62a80, 0xc44396be00, 0xc4206cbef0, 0x1733e70, 0x0, 0x0, 0x0)
	/neb/golang/src/github.com/nebulasio/go-nebulas/vendor/google.golang.org/grpc/server.go:946 +0xfc3
github.com/nebulasio/go-nebulas/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420567e40, 0x1766fa0, 0xc420d62a80, 0xc44396be00, 0x0)
	/neb/golang/src/github.com/nebulasio/go-nebulas/vendor/google.golang.org/grpc/server.go:1143 +0x1528
github.com/nebulasio/go-nebulas/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4206c6270, 0xc420567e40, 0x1766fa0, 0xc420d62a80, 0xc44396be00)
	/neb/golang/src/github.com/nebulasio/go-nebulas/vendor/google.golang.org/grpc/server.go:638 +0x9f
created by github.com/nebulasio/go-nebulas/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/neb/golang/src/github.com/nebulasio/go-nebulas/vendor/google.golang.org/grpc/server.go:636 +0xa1
```

```
(pprof) text
Showing nodes accounting for 3.66GB, 98.45% of 3.72GB total
Dropped 135 nodes (cum <= 0.02GB)
Showing top 10 nodes out of 34
      flat  flat%   sum%        cum   cum%
    1.96GB 52.78% 52.78%     1.96GB 52.78%  github.com/nebulasio/go-nebulas/vendor/github.com/golang/protobuf/proto.(*Buffer).EncodeRawBytes
    1.68GB 45.13% 97.91%     1.68GB 45.13%  github.com/nebulasio/go-nebulas/vendor/github.com/gogo/protobuf/proto.(*Buffer).DecodeRawBytes
    0.02GB  0.54% 98.45%     0.02GB  0.54%  time.NewTicker
         0     0% 98.45%     1.68GB 45.13%  github.com/nebulasio/go-nebulas/core.(*BlockChain).GetBlock
         0     0% 98.45%     1.68GB 45.13%  github.com/nebulasio/go-nebulas/core.(*BlockChain).GetBlockOnCanonicalChainByHeight
         0     0% 98.45%     1.68GB 45.13%  github.com/nebulasio/go-nebulas/core.LoadBlockFromStorage
         0     0% 98.45%     0.02GB  0.54%  github.com/nebulasio/go-nebulas/net.(*Stream).writeLoop
         0     0% 98.45%     1.69GB 45.31%  github.com/nebulasio/go-nebulas/rpc.(*APIService).GetBlockByHeight
         0     0% 98.45%     1.69GB 45.48%  github.com/nebulasio/go-nebulas/rpc.loggingUnary
         0     0% 98.45%     1.69GB 45.31%  github.com/nebulasio/go-nebulas/rpc/pb._ApiService_GetBlockByHeight_Handler
```

**Comment by menghanl** [comment]
Ping. Can you provide a reproduction so we can look at it? Thanks.

**Comment by dreamflyfengzi** [comment]
I set MaxConcurrentStreams ,  will happen  "error": "stream terminated by RST_STREAM with error code: REFUSED_STREAM". the rpc requests don't be closed.

**Comment by lyuxuan** [comment]
Hi @dreamflyfengzi it seems that you are not running the grpc v.12.0 release, as the error message shows `grpc/transport/control.go:191`, while `control.go` has been renamed to `flowcontrol.go` in #1962, which is the v.12.0 release. Can you please check again what is the grpc version that you are using? Thanks!

**Comment by dfawley** [comment]
Ping @dreamflyfengzi - if you can provide a reproduction case for this, it would help us to diagnose and fix it.  Also, can you confirm what version of grpc you were using?

**Comment by dreamflyfengzi** [comment]
sorry  grpc version is 1.9.2

**Comment by dfawley** [comment]
@dreamflyfengzi thanks for the update.  Could you try with the latest release, and if you're still seeing a problem, share the code you're using to get these results (ideally reducing it to a minimal reproduction case first)?

**Comment by alexcarol** [comment]
@dreamflyfengzi We recently experienced a similar issue, in our case we found it was caused by Stream.waitOnHeader (https://github.com/grpc/grpc-go/blob/master/transport/transport.go#L236) being blocked. We haven't found out why it got stuck, but adding a timeout to the context fixed the memory leak for us.

**Comment by mofirouz** [comment]
@alexcarol I believe I'm in the same situation as you. Can you tell me how bad (in terms of Gigabyte) the memory leak was, and how quickly the application consumed the available memory once leak started? I understand this is quite situational but may be your experience could shed some light on mine?
