### ISSUE TITLE
why there is a net.Listener type map in the server struct,and use the sync.mutex to protect it,  will there be many lis

### ISSUE THREAD

**Issue by sht1992** [grpc/grpc-go#2114]
Please answer these questions before submitting your issue.

### What version of Go are you using (`go version`)?
1.9
### What operating system (Linux, Windows, …) and version?
windows
### What did you do?
If possible, provide a recipe for reproducing the error.

**Comment by menghanl** [comment]
Because a server can serve on multiple listeners (multiple ports).

```go
	s := grpc.NewServer()
	pb.RegisterGreeterServer(s, &server{})

	lis1, err := net.Listen("tcp", port1)
	lis2, err := net.Listen("tcp", port2)
	err = s.Serve(lis1)
	err = s.Serve(lis2)
```
