### ISSUE TITLE
【QA】When to publish a new Release？

### ISSUE THREAD

**Issue by longXboy** [grpc/grpc-go#2125]
I want to update my grpc because of the fatal bug #2106 ,but the bazel only support official version [https://github.com/bazelbuild/rules_go/blob/master/go/private/repositories.bzl](url)
So When to publish a new Release 1.12.1?

**Comment by menghanl** [comment]
Can you double check it's #2106? Why is that important for you?

**Comment by longXboy** [comment]
My project crashed three times because of this unsafe datarace bug.

**Comment by menghanl** [comment]
Since you've found a workaround, I will not include #2106 in the next minor release (the reason is to minimize the change in case there are unintentional changes).

If you later find it still bothers you, please reply here.
