### ISSUE TITLE
Context canceled for large number of gRPC calls.

### ISSUE THREAD

**Issue by garnix** [grpc/grpc-go#2151]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.2.0-398-gb71aced

### What version of Go are you using (`go version`)?
go1.10

### What operating system (Linux, Windows, …) and version?
3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64

### What did you do?
Sending multiple (>1M) gRPC messages of max. 1MB size each.

### What did you expect to see?
Successful gRPC calls.

### What did you see instead?
rpc error: code = Canceled desc = context canceled

What could be causing the cancellation of the context of a gRPC call except timeouts? Is there a way to print more information on the error?

**Comment by menghanl** [comment]
I assume you mean multiple RPCs in parallel, not one stream RPC sending messages in parallel, right?

Can you try to set these environment variables to get logs: `GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info`?

**Comment by nicolasnoble** [comment]
There's a soft limit in http2 on the number of parallel streams, which is 100 by default.

I don't know if this is the problem here, nor how to configure it in go. Note that this needs to be tweaked on both the client and the server.

**Comment by MakMukhi** [comment]
1M RPCs in parallel each of which is 1MB of data is about 1TB of memory. Unless it's a beefy server, I suspect your system isn't making progress very fast on those RPCs and the context deadline expires.

**Comment by zhenqianz** [comment]
Hi @garnix ,

I'm currently having the same problem with you.
Do you mind to share any updates? 

Thanks
