### ISSUE TITLE
Go - gRPC Is that possible to add a new flag in the protobuf to specify use some more clear API names for client streaming

### ISSUE THREAD

**Issue by josephusmv** [grpc/grpc-go#2156]
### What version of gRPC are you using?
Release 1.12.0

### What version of Go are you using (`go version`)?
V1.8.3

### What operating system (Linux, Windows, …) and version?
Windows 8

### What did you do?
generate go grpc codes.

### What did you expect to see?
The name could be synchronized for all three way of streaming, client/server/bidirectional.

### What did you see instead?
When using client side streaming, I found the generated stream interface API are named poorly.
SendAndClose and CloseAndRecv. But both bidirectional and server streaming are named in a more tidy and simple way: "Recv" and "Send". And the "Close" in client streaming seems very confusion and my application level codes has to call it which are lead to some confusion.
I understand that there are much backward compatible considerations about this. Is that possible the team could add some option in the protobuf file to let user make decision about whether using the new style or the old.
This is more than an informational than bug. Thanks in advance.

**Comment by dfawley** [comment]
@josephusmv Sorry, we would prefer to have one set of possibly-confusing function names than two different APIs to document and support.  We should fix any problems of confusion surrounding the current API with better documentation instead.  Thanks for the suggestion.
