### ISSUE TITLE
AppEngine support

### ISSUE THREAD

**Issue by ernestoalejo** [grpc/grpc-go#216]
I have not seen any issue to track this. Client could probably work using the dialer of the `appengine/socket` package (I have not tried it); but the server can't be started on an instance.

**Comment by iamqizhao** [comment]
@dsymonds 

David mentioned to me that dialer should work for appengine. Any particular issue for server (I do not have any experience with appengine)?

**Comment by dsymonds** [comment]
Client connections should work as long as the destination address is permitted by the Socket API (the `googleapis.com` hostnames unfortunately haven't been whitelisted yet).

Servers won't work for a while on classic App Engine. They work already on Managed VMs though.

**Comment by zboralski** [comment]
Do servers work now?

**Comment by nodirt** [comment]
I assume this bug was closed because it was ambiguous (client or server).
I've filed #805 specifically about server.

**Comment by ernestoalejo** [comment]
It was about server only (*the server can't be started on an instance.*), client was already working last year when I filled the issue. Thank you for referencing the new tracking issue; looking forward to see it resolved.
