### ISSUE TITLE
How should grpclb react on grcplb-server closing the connection?

### ISSUE THREAD

**Issue by krzysztofdrys** [grpc/grpc-go#2161]
### What version of gRPC are you using?
```
[[projects]]
  name = "google.golang.org/grpc"
  packages = [".", "balancer", "balancer/base", "balancer/roundrobin", "codes", "connectivity", "credentials", "credentials/oauth", "encoding", "encoding/proto", "grpclb/grpc_lb_v1/messages", "grpclog", "internal", "keepalive", "metadata", "naming", "peer", "resolver", "resolver/dns", "resolver/passthrough", "stats", "status", "tap", "transport"]
  revision = "d11072e7ca9811b1100b80ca0269ac831f06d024"
  version = "v1.11.3"
```
### What version of Go are you using (`go version`)?
```go version go1.10 darwin/amd64```

### What operating system (Linux, Windows, …) and version?
```alpine:3.7```

### What did you do?
We implemented our own grpclb-server, which we are using to balance load inside our cluster. Main function of this server looks more or less like this:

```
func (s *Server) BalanceLoad(stream service.LoadBalancer_BalanceLoadServer) error {
	ctx := stream.Context()
	// a lot of code omitted for simplicity  
        connectionTime := s.MaxConnectionTime
        go s.receiveMessages(stream)
        go s.broadcastUpdates(stream)
	select {
	case  <-ctx.Done():
		log.Info("Connection closed")
		return nil
	case <-s.Done:
		log.Debugf("Closing connection because graceful shutdown is in progress")
		return nil
	case <-time.After(connectionTime):
		log.Debugf("Closing because 'connectionTime' (%v) has elapsed", connectionTime)
		return nil
	}
}
```
With this code, we trying to avoid long living connections between grpclb-client and grpclb-server. When connections are long-lived, we have a problem with load balancing calls to grpclb-server. 

We are using kubernetes and have two pods with grpclb-server.  When we are using long-lived connections to grclb-server, most pods connect to the grcplb-server which was first up. Ratio is about 100:1.

So to rephrase, we have a situation where service A talks to service B using our own grpclb-server as a load balancer. So in this situation A is client to both B and grpclb-server. We want to avoid long lived connections between A and grpclb-server.

### What did you expect to see?
When grpclb-server closes connection, I expected its client (service A) to reconnect silently.

### What did you see instead?
When grpclb-server closes connection, its client (service A) emits the following error:
```
grpclb: failed to recv server list: EOF
```

I understand that I am using an old version of grpc, but as far as I can see (looking at the code), the issue is still on master. I can retest on HEAD.

One possible fix is changing definition of `readServerList` (https://github.com/grpc/grpc-go/blob/master/balancer/grpclb/grpclb_remote_balancer.go#L145:23) to something like this:
```
func (lb *lbBalancer) readServerList(s *balanceLoadClientStream) error {
	for {
		reply, err := s.Recv()
		if err != nil {
                        if err == io.EOF {
                           return nil
                        }
			return fmt.Errorf("grpclb: failed to recv server list: %v", err)
		}
		if serverList := reply.GetServerList(); serverList != nil {
			lb.processServerList(serverList)
		}
	}
}
```
The error is actually emitted here: https://github.com/grpc/grpc-go/blob/master/balancer/grpclb/grpclb_remote_balancer.go#L232

I am posting this as a question, because I am not sure whether this is a bug or an intended feature.

**Comment by menghanl** [comment]
Thanks for the fix for the issue.

There's something related to grpclb I think you may want to know:

We recently moved the grpclb package to a [sub package of `balancer`](https://github.com/grpc/grpc-go/tree/master/balancer/grpclb), and grpc package no longer installs it by default. So your clients will need to `import _ ".../grpclb"`.

We also moved the generated proto files, which may affect you if you import the proto from grpc repo. You will not immediately notice this because we kept the old package to avoid breakage. But it will be great if you could import the [new generated code](https://github.com/grpc/grpc-go/tree/master/balancer/grpclb/grpc_lb_v1) instead.

The changes were made in #2107 and #2137, and the reason is to make it easier to sync proto with the [official grpclb proto file](https://github.com/grpc/grpc-proto/blob/master/grpc/lb/v1/load_balancer.proto).

**Comment by krzysztofdrys** [comment]
@menghanl Thanks for handling this so quickly.

Note taken about the recent changes in package structure. I think we will start migrating our client services, after `1.14.0` is released.
