### ISSUE TITLE
Does gRPC support HTTPS transport for client / server connections?

### ISSUE THREAD

**Issue by jaytaylor** [grpc/grpc-go#2164]
### The Setup

Server running behind Apache, with Apache terminating SSL.

gRPC client needs to connect over the internet to example.com:443, establish an SSL transport connection to Apache, then start communicating with the gRPC server.

---

### Error message

Error produced when gRPC connection is attempted from the client:

`rpc error: code = Unavailable desc = transport is closing`

---

### Questions

1. Does this sound like a reasonable thing? (i.e. is it a supported configuration?)

2. Is the technique for achieving this documented somewhere and I'm just bad at searching the web? (this would be my ideal scenario! :)

---

#### What version of gRPC are you using?

Latest from `go get`

#### What version of Go are you using (`go version`)?

1.10

#### What operating system (Linux, Windows, …) and version?

Linux, Ubuntu 14.04

**Comment by jaytaylor** [comment]
Thanks for the info @MakMukhi, those are good questions.

Investigating revealed the Linux is too old to easily get mod_http2 installed.  However, as luck would have it I'll be dumping Linode and moving to a newer Linux machine (and distro) in the next day or two.

So assuming an apache server with mod_http2 _is_ in the mix, is there a way to let apache do the SSL termination and still let gRPC clients in?

I understand it may not be feasible, as the server's TCP port is being multiplexed between an HTTP goroutine and the gRPC goroutine based on a header, all behind an apache reverse-proxy.

It seems to me like a matter of getting the gRPC client to connect to example.com:443 using SSL, without using credentials (i.e. establishing HTTPS tunnel without authentication).

Does my understanding of what is needed seem correct?

Thanks for bearing with me.

**Comment by dfawley** [comment]
@jaytaylor this _should_ still be possible.  If you are doing port-sharing on the server, you can use the http [server handler implementation](https://godoc.org/google.golang.org/grpc#Server.ServeHTTP) (which is experimental) or something like [cmux](https://github.com/soheilhy/cmux), depending on your needs.

You can configure your client to do TLS and Apache can terminate it, and then from there to to the grpc server you can use another secured connection or just forward RPCs as plaintext (via [WithInsecure](https://godoc.org/google.golang.org/grpc#WithInsecure)) if your network is considered secure or if you are on the same machine (e.g. UDS or an in-process connection).

If you do get this working, please share what you can about your solution.  Thanks!

**Comment by jaytaylor** [comment]
@dfawley Right on, this is along the lines of what I've been aiming for (in the meantime, things are connected through unreliable SSH tunnels as a temporary workaround for the HTTPS termination issue).

The part I could really use some advice and / or guidance on is the TLS/Apache part:

What is the technique to configure (or otherwise convince) the gRPC client to connect to the SSL Apache proxy server?

Is it necessary to somehow bind the LetsEncrypt TLS certificate to the gRPC client?  This would be somewhat of an annoyance since the cert must be renewed on a quarterly basis.  That said, any solution which improves on the current strategy would be wonderful :)

**Comment by dfawley** [comment]
@jaytaylor Unfortunately I'm not familiar enough with Apache to help with this.  The TLS certificate used for the gRPC client should always be the one that the terminating endpoint expects to see.  Since that's Apache in your case, you need to make sure Apache and the gRPC client are paired -- how to do that in Apache and what options you have is where my knowledge ends.  From the client-side, however, you'd need to use `WithTransportCredentials` something like this:

```
grpc.Dial(..., grpc.WithTransportCredentials(credentials.NewClientTLSFromFile(certFile, "")))
```

**Comment by annismckenzie** [comment]
We have the same general setup with an HAProxy terminating TLS, announcing ALPN (this was crucial) and working in `tcp` mode. We only have server written in Go but have clients in Go and Python. For the Go clients we do use `grpc.WithTransportCredentials(credentials.NewClientTLSFromCert(nil, "*.our-domain.tld"))`. Our gRPC servers themselves are not using TLS of course, which is why that works. What I don't know for your case is whether Apache can do TLS offloading in TCP mode.

**Comment by dfawley** [comment]
@jaytaylor were you able to get things working with TLS and Apache?

**Comment by jaytaylor** [comment]
Sort of.  Part of the problem was [a missing cmux matcher for HTTP2 on the web server side of things](https://github.com/jaytaylor/andromeda/commit/0182aa53b83eb0d7f44f36db15a5466acc964e7c#diff-319b02700d2243dbfc1e060e2fbb1ff5).

Full HTTP2 direct mode must be available on the Go side, because apache2 does not support HTTP1.1 -> HTTP2 connection upgrades.

I also incorporated support for h2c in the commit above, which was necessary for things to play nice with apache.  After applying the changes above, streaming gRPC requests started working!  However, now non-streaming gRPC requests still don't work.  I get 1 of the following 2 errors in the client:

```FATA[0001] rpc error: code = Internal desc = server closed the stream without sending trailers  source="andromeda/main.go:475"```

```FATA[0000] rpc error: code = Internal desc = transport: received the unexpected content-type "text/plain; charset=utf-8"  source="andromeda/main.go:475"```

Other [cases of gRPC trailers errors exist](https://github.com/nghttp2/nghttp2/issues/588), and AFAICT the error is the result of a proxy making alternative decisions about HTTP2 structures that ultimately result in gRPC wire-protocol issues.

[Here](https://github.com/grpc/grpc-go/issues/892) is another similar gRPC error message when proxying by nginx.

Overall I'm not feeling too good about this situation.  gRPC requires HTTP2, and the most widely-used load balancers are not able to completely work with gRPC.

I've considered switching to use Envoy, but it is a whole additional can of worms and I'm not sure it will even do what is needed here.

Is there a list of reverse-proxy load balancers which gRPC is known to be compatible with (ideally with samples of working configurations)?

**Comment by jaytaylor** [comment]
Sort of.  Part of the problem was [a missing cmux matcher for HTTP2 on the web server side of things](https://github.com/jaytaylor/andromeda/commit/0182aa53b83eb0d7f44f36db15a5466acc964e7c#diff-319b02700d2243dbfc1e060e2fbb1ff5).

Full HTTP2 direct mode must be available on the Go side, because apache2 does not support HTTP1.1 -> HTTP2 connection upgrades.

I also incorporated support for h2c in the commit above, which was necessary for things to play nice with apache.  After applying the changes above, streaming gRPC requests started working!  However, now non-streaming gRPC requests still don't work.  I get 1 of the following 2 errors in the client:

```FATA[0001] rpc error: code = Internal desc = server closed the stream without sending trailers  source="andromeda/main.go:475"```

```FATA[0000] rpc error: code = Internal desc = transport: received the unexpected content-type "text/plain; charset=utf-8"  source="andromeda/main.go:475"```

Other [cases of gRPC trailers errors exist](https://github.com/nghttp2/nghttp2/issues/588), and AFAICT the error is the result of a proxy making alternative decisions about HTTP2 structures that ultimately result in gRPC wire-protocol issues.

[Here](https://github.com/grpc/grpc-go/issues/892) is another similar gRPC error message when proxying by nginx.

Overall I'm not feeling too good about this situation.  gRPC requires HTTP2, and the most widely-used load balancers are not able to completely work with gRPC.

I've considered trying out Envoy, but held off since it's geared mostly towards kubernetes / web-apps applications rather than a general-purpose high-performance LB.

**Is there a list of reverse-proxy load balancers which are known to be compatible with gRPC?**

(ideally with samples of working configurations :)

**Comment by jaytaylor** [comment]
Sort of.  Part of the problem was [a missing cmux matcher for HTTP2 on the web server side of things](https://github.com/jaytaylor/andromeda/commit/0182aa53b83eb0d7f44f36db15a5466acc964e7c#diff-319b02700d2243dbfc1e060e2fbb1ff5).

Full HTTP2 direct mode must be available on the Go side, because apache2 does not support HTTP1.1 -> HTTP2 connection upgrades.

I also incorporated support for h2c in the commit above, which was necessary for things to play nice with apache.  After applying the changes above, streaming gRPC requests started working!  However, now non-streaming gRPC requests still don't work.  I get 1 of the following 2 errors in the client:

```FATA[0001] rpc error: code = Internal desc = server closed the stream without sending trailers  source="andromeda/main.go:475"```

```FATA[0000] rpc error: code = Internal desc = transport: received the unexpected content-type "text/plain; charset=utf-8"  source="andromeda/main.go:475"```

Other [cases of gRPC trailers errors exist](https://github.com/nghttp2/nghttp2/issues/588), and AFAICT the error is the result of a proxy making alternative decisions about HTTP2 structures that ultimately result in gRPC wire-protocol issues.

[Here](https://github.com/grpc/grpc-go/issues/892) is another similar gRPC error message when proxying by nginx.

Overall I'm not feeling too good about this situation.  gRPC requires HTTP2, and the most widely-used load balancers are not able to completely work with gRPC.

I've considered trying out Envoy, but held off since it's geared mostly towards kubernetes / web-apps rather than a general-purpose high-performance LB.

**Is there a list of reverse-proxy load balancers which are known to be compatible with gRPC?**

(ideally with samples of working configurations :)

**Comment by jaytaylor** [comment]
Also, [this OpenSSL command to get the public ssl/tls cert.pem](https://github.com/jaytaylor/andromeda/blob/76d775d0a3e0ae7b2665c1e088f80f62dbf969be/pkg/openssl/download_cert_pub_key_linux.go#L15) proved to be quite useful.

```openssl s_client -showcerts -servername $hostname -connect $hostname_or_ip:$port </dev/null 2>/dev/null | openssl x509 -outform PEM```

And [here's an example of the gRPC client setup](https://github.com/jaytaylor/andromeda/blob/76d775d0a3e0ae7b2665c1e088f80f62dbf969be/crawler/remote.go#L43-L51).

**Comment by jaytaylor** [comment]
[Here's an example of the gRPC client setup](https://github.com/jaytaylor/andromeda/blob/76d775d0a3e0ae7b2665c1e088f80f62dbf969be/crawler/remote.go#L43-L51).

[This OpenSSL command to get the public ssl/tls cert.pem](https://github.com/jaytaylor/andromeda/blob/76d775d0a3e0ae7b2665c1e088f80f62dbf969be/pkg/openssl/download_cert_pub_key_linux.go#L15) proved to be quite useful, too.

```openssl s_client -showcerts -servername $hostname -connect $hostname_or_ip:$port </dev/null 2>/dev/null | openssl x509 -outform PEM```

**Comment by dfawley** [comment]
Hi @jaytaylor, I don't know of any list of LBs, but nginx as of 1.13.10 does support grpc (the issue you linked is 2 years old).  Envoy should also work well.  Thanks for following up with the extra details.  Let us know if you have any further issue/comments/concerns.

**Comment by jaytaylor** [comment]
Thanks for the info @dfawley.

I currently have it sort of working with Apache2, but now thinking of putting nginx out in front, hooking up the gRPC app there, and bypassing apache.

Apache does so much, which can often be a really good and nice thing.  In this case, however, it's leading to difficulties such as sporadic client / server errors, occasional _very_ high apache memory usage (climbing to consume 100% of what is available on the machine), as well as occasional difficulty for gRPC clients to attach to streams or detect that a stream has gone away.  Since none of these is consistently reproducible, diagnosis is quite a challenge.

Nginx is looking pretty appealing :) My experience so far is that proxying HTTP/2 is almost nothing like proxying HTTP/1.  Just my .02c~

Jay
