### ISSUE TITLE
Flaky test: TestCloseConnectionWhenServerPrefaceNotReceived

### ISSUE THREAD

**Issue by lyuxuan** [grpc/grpc-go#2180]
```
--- FAIL: TestCloseConnectionWhenServerPrefaceNotReceived (5.24s)
	clientconn_test.go:218: Error while accepting. Err: accept tcp 127.0.0.1:39371: use of closed network connection
E0627 00:03:27.746675    4111 pickfirst.go:59] pickfirstBalancer: failed to NewSubConn: grpc: cannot create SubConn with empty address list
FAIL
```

Note: creating a new issue instead of reusing old ones due to different root cause of flakiness.

**Comment by dfawley** [comment]
Do you have time to look into this this week, Mak?

**Comment by MakMukhi** [comment]
on it.

**Comment by MakMukhi** [comment]
Couldn't reproduce in 100000 runs. Is it possible that the error was seen on an old branch that didn't have the fix in?

**Comment by dfawley** [comment]
It failed last night in our cron build.

**Comment by MakMukhi** [comment]
Reproducible only on head. Pushing a fix.
