### ISSUE TITLE
Deprecated Codec interface used in rpc_util.go

### ISSUE THREAD

**Issue by fJancsoSzabo** [grpc/grpc-go#2189]
### What version of gRPC are you using?
1.13.0

### What did you do?
I was trying to update https://github.com/mwitkow/grpc-proxy to not use deprecated functions from this library, and came across some weirdness.

[In `rpc_util.go`](https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L406-L408) `CallCustomCodec` uses `Codec`, which has been deprecated [in favour of `encoding.Codec`](https://github.com/grpc/grpc-go/blob/master/codec.go#L41).  It *feels* like `CallCustomCodec` should either also be deprecated, or updated to use `encoding.codec`, but I'm not totally sure.

**Comment by dfawley** [comment]
That's a good point.  We should have a form of `CallCustomCodec` that accepts an `encoding.Codec` instead.  (We can't alter it in-place to take an `encoding.Codec`, as that would break backward compatibility.)

Note that the only difference between the two interfaces is the `String` vs. `Name` method, which was changed to make it unify with `encoding.Compressor`, so it should be easy to make one type that satisfies both.

**Comment by fJancsoSzabo** [comment]
What's the best thing to do in the mean time?  Continue to use the deprecated `Codec`?

**Comment by dfawley** [comment]
If you need `CallCustomCodec` (are you *sure* you need it?), then you should just go ahead and implement `grpc.Codec` and use it.

Otherwise, the recommend approach is to use `CallContentSubtype` and implement your codec using the new interface.  See the relevant docs here: https://github.com/grpc/grpc-go/blob/master/Documentation/encoding.md

Converting to the new interface should be as easy as changing `String()` to `Name()`.

**Comment by dfawley** [comment]
@prannayk - This would be a problem for type safety, shifting compile-time type checks to runtime.  Also, call option functions don't return errors, so the error at runtime would have to be a panic, and panics in libraries like this should be avoided at all costs.

What I suggested above should be a pretty simple change to make; I'll just take care of it now to close this out.
