### ISSUE TITLE
grpc-go should not depend on oauth2

### ISSUE THREAD

**Issue by tamird** [grpc/grpc-go#219]
There is no real harm here, but go-grpc ought to maintain a slim set of dependencies to reduce the cost of integrating it into an application.

https://github.com/grpc/grpc-go/blob/master/credentials/credentials.go defines all the necessary interfaces; the `oauth2` implementations can (and should) be put into a separate package to allow people to opt-out.

**Comment by dsymonds** [comment]
I don't think we should be reshuffling the credentials package right now just to trim down dependencies. The credentials package in general needs a broad rethink, and this just makes it harder to do that.

@adg @okdave

**Comment by iamqizhao** [comment]
@adg @okdave

Hi Andrew and David,

Could you guys have a proposal on how to improve credentials package? Thanks. I hope to get it done before beta release.

**Comment by tamird** [comment]
@dsymonds I disagree that this makes it harder to redesign the package - inevitably there will be a package which defines the necessary interfaces, and an auxiliary package which implements them for oauth. Getting this separate in now ensures that the eventual refactor does not neglect this concern.

**Comment by tamird** [comment]
Ping

**Comment by dsymonds** [comment]
http://www.grpc.io/docs/guides/auth.html, which is the official gRPC docs for authentication, holds OAuth 2.0 as a supported auth mechanism. It is a standard piece. Unless there's a compelling scenario in which this dependency is particularly harmful (beyond just unnecessary), we should not do this. It's making it harder for a standard, supported use case.

**Comment by okdave** [comment]
Are there any "real world" uses of gRPC which do not currently rely on oAuth? Removing the dependency seems to have very little practical implications.

**Comment by tamird** [comment]
We would like to experiment with grpc in github.com/cockroachdb/cockroach, and we will be using mutual-TLS rather than oauth.

**Comment by dsymonds** [comment]
Please explain how the oauth dependency is actively harmful for that use case, rather than just being a (fairly lightweight) unnecessary dependency.

**Comment by awalterschulze** [comment]
Networks without internet access running on generators are a thing (I have not worked with oauth, but I assume it requires access to the internet). (potential idiot right here)
But either way grpc-go has a lot of dependencies.
I don't know if it has been fixed, but I think something even depends on google.golang.org/cloud.
I want to use grpc and go without using a google api.
I am not complaining I think grpc-go gives a lot, but I still think there could be fewer dependencies.
I think its dependency on github.com/bradfitz/http2 is probably temporary.
It just adds up.
Maybe with go having such a great standard library we have just become quite allergic to dependencies.
Anyway I am just saying tamird is not alone, but I love grpc-go, I just use git-anchor to manage all of its dependencies.

**Comment by tamird** [comment]
To my knowledge, the oauth dependency is not actively harmful; this is stated in the original description. That said, I'd like to keep unused dependencies in my application to a minimum; this is just a personal choice, and there will be others who will feel similarly as grpc gains adoption. The status quo allows no workaround.

This proposal is pretty light - those who need the oauth support get it with a single import statement.

**Comment by crast** [comment]
The only "harm" is that doing a "go get" gets a tree of dependencies which increases the time spent in go get, increases your checkout size, and the code is compiled into your binary even if not using oauth... because it's currently in the same package as other credentials you might be using.

We're using GRPC right now in a new internal microservice we're writing, and it's not using OAuth. It's not in full production yet, but it will be in the next month; again I know it's not harmful, it's just a bit silly that I need the oauth library which I won't use to compile into my binary.

**Comment by adg** [comment]
Looking at the import graph, the oauth2 packages do seem extraneous:
http://godoc.org/google.golang.org/grpc?import-graph&hide=2

I think it does seem reasonable to trim the dependencies, and I think it's on our roadmap to make some changes to the cloud and oauth2 packages that will make this possible.

**Comment by tamird** [comment]
@adg from #220:
> To avoid breaking bigtable, we can make this change in 3 stages:
- add a new empty package credentials/oauth/oauth
- import that package in bigtable
- merge this PR

Would you be open to my contributing these changes?

**Comment by dsymonds** [comment]
I don't care about a potential Cloud Bigtable break. It's trivial to solve that.

I still think it's a fairly academic point and some unnecessary fuss for a very common case, but no-one else seems to agree, so I'll withdraw my objections.

Let me know when there's a package for bigtable to import and I'll take care of that.

**Comment by tamird** [comment]
@dsymonds would you sign off on https://github.com/grpc/grpc-go/pull/220/files?

**Comment by dsymonds** [comment]
It'd be better if it were staged so that a new package happens first, then we can update anyone who cares, and only then do we drop the default import.

**Comment by tamird** [comment]
@dsymonds https://github.com/grpc/grpc-go/pull/237

**Comment by awalterschulze** [comment]
Seems grpc still has some oauth2 dependencies
```
src//google.golang.org/grpc/credentials/oauth/oauth.go:	"golang.org/x/oauth2"
src//google.golang.org/grpc/credentials/oauth/oauth.go:	"golang.org/x/oauth2/google"
src//google.golang.org/grpc/credentials/oauth/oauth.go:	"golang.org/x/oauth2/jwt"
src//google.golang.org/grpc/interop/client/client.go:	"golang.org/x/oauth2"
src//google.golang.org/grpc/interop/client/client.go:	"golang.org/x/oauth2/google"
```
This results in depending on google.golang.org/cloud which results in depending on google.golang.org/api which is huge.

I have seen there has been some progress on removing the dependency on oauth.
Are there still plans on completely removing it?

**Comment by awalterschulze** [comment]
Maybe I could just delete the folders (credentials/oauth and interop/client) from my git subtree?

**Comment by tamird** [comment]
`grpc/credentials/oauth` is an optional dependency, and interop is used only for testing I think. If you're just `grep`ing to find dependencies, you're doing it wrong.

**Comment by awalterschulze** [comment]
Ok ... so explain an optional dependency please. :)

Are you telling me that:
1) if I go get and run go test -v ... everything will work?
2) I shouldn't run my dependencies' tests?
3) ?

**Comment by awalterschulze** [comment]
Please don't think I don't appreciate the work you have do to move this dependency as far into a corner as possible.
What do you do to manage this dependency?

**Comment by tamird** [comment]
@awalterschulze optional dependency means that if you `import "google.golang.org/grpc"` in your application, the optional dependency will not be linked in. If you're trying to prevent `go get` from downloading it, well, that's a lost cause AFAIK.

As far as running your dependencies' tests: not sure what that has to do with anything. Run them if you like.

**Comment by awalterschulze** [comment]
Well I run them and try to build everything I'll get a compile error asking for google's cloud and api libraries.
Ok so this sucks, but I'll be pragmatic and delete those folders (credentials/oauth and interop/client) in my git subtree and then I can delete those google cloud and api dependencies.
Thank you for all the work of moving these dependencies to somewhere, where I can delete the code that uses it.

**Comment by aaronbee** [comment]
@awalterschulze FYI, [godep](https://github.com/tools/godep) will do the right thing here and will only vendor the import paths (and the import paths of those import paths) that your code actually uses. ie. My project vendors grpc with godep but my godep workspace doesn't include google.golang.org/cloud, api, glog, etc.

**Comment by awalterschulze** [comment]
Thats really cool :)
I'll have to look into that for letmegrpc.
