### ISSUE TITLE
WaitForHandshake: correct break statement?

### ISSUE THREAD

**Issue by itizir** [grpc/grpc-go#2203]
Hi!

Going through the code, this line puzzled me a bit:
https://github.com/grpc/grpc-go/blob/40cd6b15e2880b88deb091b0fcb091694285fcb0/clientconn.go#L1355

Is that break statement not supposed to break out of the for loop instead of the select (where it wouldn't be necessary anyway)?

**Comment by lyuxuan** [comment]
Hi @itizir, thanks for opening this issue. Good catch! I don't think it is necessary and we'll fix it soon.

**Comment by MakMukhi** [comment]
I suppose we could return with `errConnClosing` instead of `break`

**Comment by itizir** [comment]
Indeed not sure what the right fix would be, but it did look like the break was perhaps meant to interrupt the for loop. Thanks for looking into it in any case! Happy I could be of some help at all.
