### ISSUE TITLE
How to dial DNS SRV record

### ISSUE THREAD

**Issue by Derliang** [grpc/grpc-go#2209]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.7.0
### What version of Go are you using (`go version`)?
1.9.1
### What operating system (Linux, Windows, …) and version?
windows
### What did you do?
This is my first time to post my issue on github. Here is my question.
I just use grpc-go and grpc-c++ to construct our code. I find the latest version of grpc-c++ has already 
support DNS SRV record.  
Qusetion 1: I'm so confused if grpc-go has some func to invoke or  has not implement
that?
Question 2: If already has implement, can you give some code sample or function name?

**Comment by lyuxuan** [comment]
Hi @Derliang, our default DNS resolver does look up DNS SRV records ([link](https://github.com/grpc/grpc-go/blob/c491b25057c873b1f7d8e4109d380c0d9f48f75f/resolver/dns/dns_resolver.go#L208)), but it's for grpclb usage only, as we make the prefix to be  "_grpclb._tcp". If you want to use other prefix for SRV lookup, you can have your own custom DNS resolver (you can simply copy our DNS resolver code and change the [line](https://github.com/grpc/grpc-go/blob/c491b25057c873b1f7d8e4109d380c0d9f48f75f/resolver/dns/dns_resolver.go#L210) that specifies the prefix) and register it to be used. Please let us know if you want more info. Thanks!

**Comment by uschen** [comment]
documentation and example will be nice. especially there are timeout, frequency and other stuffs which can be confusing in the beginning.

**Comment by Derliang** [comment]
@lyuxuan  Thanks!  documentation and example will be nice. Also I can read source code to know how to use this dns-resolver.
