### ISSUE TITLE
grpc.Sever.Stop seems not to block until the resource is completely released

### ISSUE THREAD

**Issue by zjshen14** [grpc/grpc-go#2214]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

v1.11.0

### What version of Go are you using (`go version`)?

go version go1.10.3 darwin/amd64

### What operating system (Linux, Windows, …) and version?

mac OS 10.13.4

### What did you do?

We run `go test` which contain multiple tests that will start and stop an rpc server. And all this rpc server binds to the same address. We don't use parallel option for unit tests.

### What did you expect to see?

The unit tests should succeed all. 

### What did you see instead?

However, tests failed because of binding to the same address. It seems to us that after calling `Server.Stop()`, the resource is not released immediately. Instead, we add `time.Sleep(time.Second)` after the stop call. We can walk around the issue.

**Comment by dfawley** [comment]
@zjshen14 I believe you are running into a TCP feature, not a problem with grpc.  You cannot re-use a port within a certain amount of time.  Your best bet would be to pick a unique port for your tests (listening on port 0 will find one for you).  For more information about that, this is a good resource: https://vincent.bernat.im/en/blog/2014-tcp-time-wait-state-linux

If you are not listening on the same port in your tests, we may need some more details to help debug this.

**Comment by zjshen14** [comment]
@dfawley, yes we bind to a fixed port. Thanks for explaining the root cause
