### ISSUE TITLE
resolver: should adds a NOTE to SetDefaultScheme like Register?

### ISSUE THREAD

**Issue by chanxuehong** [grpc/grpc-go#2216]
https://github.com/grpc/grpc-go/blob/master/resolver/resolver.go#L54

for SetDefaultScheme is not thread-safe, should we adds a NOTE link Register:

// NOTE: this function must only be called during initialization time (i.e. in
// an init() function), and is not thread-safe. If multiple Resolvers are

**Comment by dfawley** [comment]
Yes, that makes sense, thanks for the suggestion.
