### ISSUE TITLE
How to remove(disable) grpc log

### ISSUE THREAD

**Issue by huyntsgs** [grpc/grpc-go#2221]
****I want to remove logs from my grpc client. My go version 1.9, win7 x64. 
I have set two environment variables GRPC_GO_LOG_SEVERITY_LEVEL = ERROR, GRPC_GO_LOG_VERBOSITY_LEVEL = 3 but logs are still verbosed**
--------------
2018-07-15 15:37:07.587 [INF] GRPC: ccResolverWrapper: sending new addresses to cc: [{127.0.0.1:888  <nil>}]
2018-07-15 15:37:07.588 [INF] GRPC: ClientConn switching balancer to "pick_first"
2018-07-15 15:37:07.589 [INF] GRPC: pickfirstBalancer: HandleSubConnStateChange: 0xc0424fa5d0, CONNECTING
2018-07-15 15:37:07.589 [INF] GRPC: blockingPicker: the picked transport is not ready, loop back to repick
-----------------------**

**Comment by dfawley** [comment]
@huyntsgs How are you setting your environment variables?  Are you using `set`/`setx`?  `setx GRPC_GO_LOG_SEVERITY_LEVEL ERROR` will make it apply for all processes.  (They must be restarted first.)

Also, verbosity should be set to "0" for "least verbose".

**Comment by huyntsgs** [comment]
@dfawley thanks for your feedback. I set environment variables from my computer window. I added logs to grpc code and got correct these environment variables that have been set. Set to "0" and restart also not work.

**Comment by dfawley** [comment]
@huyntsgs Did you use "setx"?  Otherwise the setting will only take effect for the current window.

**Comment by dfawley** [comment]
Are you using a custom logger?  Our logger does not print " [INF] GRPC: ..."  If anything you are importing is calling `SetLoggerV2` in an `init`, then you will get that logger implementation instead of ours.

**Comment by huyntsgs** [comment]
You are right, our system uses a custom logger for grpc. Thx!
