### ISSUE TITLE
error 'unable to update checked out version: fatal: reference is not a tree' when updating grpc depend version to v1.13.1

### ISSUE THREAD

**Issue by quanjielin** [grpc/grpc-go#2229]
### What version of gRPC are you using?
Go

### What version of Go are you using (`go version`)?
go version go1.10 linux/amd64

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
Our repo need a commit that includes in gRPC v1.13.1, so I updated depend in our repo here to be
```
  revision = "befc7220cadb963755de86763a04ab6f9dc14200"
  version = "v1.13.1"
```

run dep ensure -v hit below error
```
	v1.13.1: unable to update checked out version: fatal: reference is not a tree: befc7220cadb963755de86763a04ab6f9dc14200
: command failed: [git checkout befc7220cadb963755de86763a04ab6f9dc14200]: exit status 128
```

**Comment by quanjielin** [comment]
it's my env issue, pls ignore.

btw, when v1.13.1 for go will be out ? https://github.com/grpc/grpc/releases/tag/v1.13.1 is out yesterday.

**Comment by lyuxuan** [comment]
grpc and grpc-go is independent regarding minor releases. Our next release v.1.14.0 is scheduled for 07/31/2018 and will be in sync with grpc.

**Comment by quanjielin** [comment]
@lyuxuan, another question - 
if I updated [grpc sha in our repo](https://github.com/istio/istio/blob/master/Gopkg.lock#L1232) to point to your repo's latest commit ex (445634bdcc9393d2681e504aafd3efc9b28c4bf2)[https://github.com/grpc/grpc-go/commits/master](https://github.com/grpc/grpc-go/commits/master), will it include the PR we needed(https://github.com/grpc/grpc/pull/15909) ?  If, our testing could be unblocked, thanks !

**Comment by lyuxuan** [comment]
Hi @quanjielin, [grpc](https://github.com/grpc/grpc) and [grpc-go](https://github.com/grpc/grpc-go) are two independent repositories. grpc-go releases only include the PRs that get merged in [grpc-go repository](https://github.com/grpc/grpc-go). Therefore, the PR https://github.com/grpc/grpc/pull/15909 will not be included our next release or current master as it is a PR for [grpc repository](https://github.com/grpc/grpc). As said in the description of https://github.com/grpc/grpc/pull/15909, grpc-go has no problem supporting `non-google secure tokens (call credentials) to be sent over insecure channels`. So I think your testing should be fine with grpc-go. Please let us know if you encounter any problem. Thank you!

**Comment by quanjielin** [comment]
@lyuxuan , thank you !  /cc @qiwzhang @wattli
The reason I asked is our feature need envoy to fetch some google credential(https://github.com/envoyproxy/envoy/pull/3577)(some token from GEK) and send it to server through UDS. 

A few more questions - 
1. does grpc-go already supported sending google credential through UDS securely ?
2. if yes for 1, is TLS required(setting up channel_credentials) at the same time ?

btw, if possible, could you pls shoot us an internal email, that would be faster(sorry I couldn't find your ldap..)

**Comment by quanjielin** [comment]
I gave a try by setting up TLS
1. envoy gRPC config
```
grpc_services {
  google_grpc {
    target_uri: "unix:/var/run/sds/uds_path"
    channel_credentials {
      ssl_credentials {
        root_certs {
          filename: "/etc/istio/nodeagent-root-cert.pem"
        }
      }
    }
    call_credentials {
      google_compute_engine {
      }
    }
    stat_prefix: "test"
  }
}

```
2. server side error
```
ransport: http2Server.HandleStreams failed to receive the preface from client: EOF"
2018-07-21T01:30:37.250966Z	info	grpc: Server.Serve failed to create ServerTransport: connection error: desc = "transport: http2Server.HandleStreams failed to receive the preface from client: EOF"
2018-07-21T01:31:42.641122Z	info	grpc: Server.Serve failed to create ServerTransport: connection error: desc = "transport: http2Server.HandleStreams failed to receive the preface from client: EOF"

```

**Comment by quanjielin** [comment]
server side error is thrown from https://github.com/grpc/grpc-go/blob/11b582728a13ef54e14e4fa930d693de2e32420f/internal/transport/http2_server.go#L264 

[ClientPreface](https://github.com/grpc/grpc-go/blob/11b582728a13ef54e14e4fa930d693de2e32420f/internal/transport/http_util.go#L56) are defined https://godoc.org/golang.org/x/net/http2, 

```
    // ClientPreface is the string that must be sent by new
    // connections from clients.
    ClientPreface = "PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"
```
