### ISSUE TITLE
undefined: proto.InternalMessageInfo

### ISSUE THREAD

**Issue by basheer12** [grpc/grpc-go#2234]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
  - package: google.golang.org/grpc
  version: v1.7.5

### What version of Go are you using (`go version`)?
go1.10
### What operating system (Linux, Windows, …) and version?
Linux(ubuntu)

### What did you do?
Building Felix from the below link:
https://github.com/projectcalico/felix/tree/3.1.3

Felix had dependency on the grps and protobuf. Above I have provided grpc version used by the felix for compilation.

### What did you expect to see?
Expected to compile without any error.

### What did you see instead?
```
proto/felixbackend.pb.go:116:33: undefined: "github.com/projectcalico/felix/vendor/github.com/gogo/protobuf/proto".InternalMessageInfo
proto/felixbackend.pb.go:180:33: undefined: "github.com/projectcalico/felix/vendor/github.com/gogo/protobuf/proto".InternalMessageInfo
proto/felixbackend.pb.go:914:35: undefined: "github.com/projectcalico/felix/vendor/github.com/gogo/protobuf/proto".InternalMessageInfo
proto/felixbackend.pb.go:1161:34: undefined: "github.com/projectcalico/felix/vendor/github.com/gogo/protobuf/proto".InternalMessageInfo
proto/felixbackend.pb.go:1206:28: undefined: "github.com/projectcalico/felix/vendor/github.com/gogo/protobuf/proto".InternalMessageInfo
proto/felixbackend.pb.go:1247:33: undefined: "github.com/projectcalico/felix/vendor/github.com/gogo/protobuf/proto".InternalMessageInfo
proto/felixbackend.pb.go:1309:38: undefined: "github.com/projectcalico/felix/vendor/github.com/gogo/protobuf/proto".InternalMessageInfo
proto/felixbackend.pb.go:1369:33: undefined: "github.com/projectcalico/felix/vendor/github.com/gogo/protobuf/proto".InternalMessageInfo
proto/felixbackend.pb.go:1416:41: undefined: "github.com/projectcalico/felix/vendor/github.com/gogo/protobuf/proto".InternalMessageInfo
proto/felixbackend.pb.go:1469:41: undefined: "github.com/projectcalico/felix/vendor/github.com/gogo/protobuf/proto".InternalMessageInfo
proto/felixbackend.pb.go:1469:41: too many errors```

**Comment by menghanl** [comment]
The error message means, `github.com/gogo/protobuf/proto` in the vendor directory is not in sync with `proto/felixbackend.pb.go`. Most likely, your `github.com/gogo/protobuf/proto` is outdated.

Please try to refresh the dependencies. I'm not very familiar with `glide`, but there might be a command to do that.

This is not a gRPC issue. The felix repo is probably a better place to ask.
