### ISSUE TITLE
Feature Request: Add registry package

### ISSUE THREAD

**Issue by leaxoy** [grpc/grpc-go#2249]
GRPC is a great RPC framework, now, we have balancer package for balance strategy, resolver package for resolve upstream addresses, but we have no package to register a service(aka server) to somewhere like config central(etcd, consul, zk, etc...).
So I suggest add package `registry` and define a basic `Server` struct, with this, user can easily register a service on startup and deregister a service when shutdown automatically.

**Comment by dfawley** [comment]
@leaxoy could you please clarify this a bit more?  What functions/types would be in the `registry` package, and how would it interact with the `grpc` package and with the application?

**Comment by menghanl** [comment]
@leaxoy Do you have any updates on this? Thanks.

**Comment by leaxoy** [comment]
The `resolver` package can resolve upstream server from `dns` or `passthrough`, in addition, user can implemente other protocol like `etcd`(with a target maybe looks like `etcd://etcd-server-list/endpoint`), `consul`(with a target `consule://consol-agent/endpoint`), but we have not a unifying `package` to register a upstream server to `etcd` or `consul` when a server started, and deregister it at server shutdown,  and the `resolver.Address` is not enough for various strategy of `balancer`, like `weight base round robin`.

**Comment by leaxoy** [comment]
So I think it's useful to add a `resolver` to unify the interface register and deregister a service and give a more rich `Address` definition for client load balancing.

**Comment by leaxoy** [comment]
As the `Resolver` wrapped as `resolverBuilder`, and `Balancer` as `balancerBuilder`, those two act as a field of `dialOptions` struct, we can add `registryBuilder` to `Server.options`. 
The `Registry` interface should has three method
1. Name() string returns the name of this registry, like `etcd`, `consul`,`zk`.
2. Register(server   struct act as a common service definition) error. Do real register action. maybe invoked after net.Listen started, or after the server started.
3. Deregister(same with Register method) error. Do deregister action. Maybe invoked after server stop, and before the runtime shutdown

**Comment by menghanl** [comment]
My understanding is that, you want to specify a set of services and when new gRPC servers are created, those services will be automatically installed on the new servers. Is that right?

If that's the case, it seems that you can have a wrapped `NewServer` function, which calls `grpc.NewServer` and do service registration on the returned server.

**Comment by dfawley** [comment]
Closing this issue.  This is possible to do externally (by wrapping `NewServer`), and I'd rather avoid an API that allows for silent injection of services into all gRPC servers.
