### ISSUE TITLE
Connection churning until oom'd

### ISSUE THREAD

**Issue by fastest963** [grpc/grpc-go#2251]
We're experiencing connection churning that is causing over 15,000 connections to Google's backend over a period of 30 minutes without any interaction with the driver. The issue doesn't happen on commit fb6867e but does happen on 97da9e0. I've supplied the commits below. In case there's another repo in question, let me know and I can get the relevant commits involved for other repos in the build.

This is occurring roughly once an hour in our staging environment. We've since rolled back the service until this can be resolved.

### What version of gRPC are you using?
Here are the versions from the "bad" build:
google.golang.org/grpc (git) - 97da9e0 internal: remove transportMonitor, replace with callbacks (#2219)
cloud.google.com/go (git) - f42556a Remove WithServiceAccountFile from README

Here the the versions from the "good" build:
google.golang.org/grpc (git) - fb6867e Change version to 1.15.0-dev (#2247)
cloud.google.com/go (git) - 4193b8d all: regen gapics

### What version of Go are you using (`go version`)?
go version go1.10.2 linux/amd64

### What operating system (Linux, Windows, …) and version?
CentOS 7

### What did you do?
We create a PubSub client using [pubsub.NewClient](https://godoc.org/cloud.google.com/go/pubsub#NewClient) and then make a topic instance using [pubsub.Topic](https://godoc.org/cloud.google.com/go/pubsub#Client.Topic) and call the Publish method on the topic to submit a job based on an incoming HTTP payload. The binary that's experiencing the connection churning does no subscribing, only publishing. We have not tested a binary that does subscribing. During the time periods where the connection churning was happening, no requests were made to the service so there was no usage of the pubsub.Client during these periods. The client was used in the past to publish ~10 payloads.

### What did you expect to see?
I expect the number of TCP connections to not increase exponentially when there is no usage of the driver and to the point where the process is killed by the kernel.

### What did you see instead?
Over time the go process opened up more and more connections until the box ran out of memory and the process was killed. Before it was killed here are the established connection counts for the process using netstat:
```
    724 209.85.200.95:443
   1750 64.233.181.95:443
   6486 74.125.124.95:443
   1495 74.125.129.95:443
    788 74.125.69.95:443
   2471 74.125.70.95:443
```
Here is the relevant goroutine pprof:
```
goroutine profile: total 42645
14039 @ 0x42ca0a 0x43c720 0x9e3ba3 0x9e42d8 0xa035e0 0x459f11
#	0x9e3ba2	google.golang.org/grpc/internal/transport.(*controlBuffer).get+0x132	/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/internal/transport/controlbuf.go:321
#	0x9e42d7	google.golang.org/grpc/internal/transport.(*loopyWriter).run+0x1a7	/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/internal/transport/controlbuf.go:439
#	0xa035df	google.golang.org/grpc/internal/transport.newHTTP2Client.func4+0x7f	/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/internal/transport/http2_client.go:322

14039 @ 0x42ca0a 0x43c720 0x9f3a77 0x459f11
#	0x9f3a76	google.golang.org/grpc/internal/transport.(*http2Client).keepalive+0x136	/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/internal/transport/http2_client.go:1263

14038 @ 0x42ca0a 0x427d2a 0x4273a7 0x49345b 0x4934dd 0x49433d 0x4eec0f 0x4ffcba 0x5d4586 0x5d4a90 0x5d8030 0x56b2e8 0x470f76 0x4710e8 0x9bea2b 0x9bf2b4 0x9f3292 0x459f11
#	0x4273a6	internal/poll.runtime_pollWait+0x56					/usr/local/go/src/runtime/netpoll.go:173
#	0x49345a	internal/poll.(*pollDesc).wait+0x9a					/usr/local/go/src/internal/poll/fd_poll_runtime.go:85
#	0x4934dc	internal/poll.(*pollDesc).waitRead+0x3c					/usr/local/go/src/internal/poll/fd_poll_runtime.go:90
#	0x49433c	internal/poll.(*FD).Read+0x17c						/usr/local/go/src/internal/poll/fd_unix.go:157
#	0x4eec0e	net.(*netFD).Read+0x4e							/usr/local/go/src/net/fd_unix.go:202
#	0x4ffcb9	net.(*conn).Read+0x69							/usr/local/go/src/net/net.go:176
#	0x5d4585	crypto/tls.(*block).readFromUntil+0x95					/usr/local/go/src/crypto/tls/conn.go:493
#	0x5d4a8f	crypto/tls.(*Conn).readRecord+0xdf					/usr/local/go/src/crypto/tls/conn.go:595
#	0x5d802f	crypto/tls.(*Conn).Read+0xff						/usr/local/go/src/crypto/tls/conn.go:1156
#	0x56b2e7	bufio.(*Reader).Read+0x237						/usr/local/go/src/bufio/bufio.go:216
#	0x470f75	io.ReadAtLeast+0x85							/usr/local/go/src/io/io.go:309
#	0x4710e7	io.ReadFull+0x57							/usr/local/go/src/io/io.go:327
#	0x9bea2a	golang.org/x/net/http2.readFrameHeader+0x7a				/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/golang.org/x/net/http2/frame.go:237
#	0x9bf2b3	golang.org/x/net/http2.(*Framer).ReadFrame+0xa3				/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/golang.org/x/net/http2/frame.go:492
#	0x9f3291	google.golang.org/grpc/internal/transport.(*http2Client).reader+0x171	/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/internal/transport/http2_client.go:1212

229 @ 0x42ca0a 0x43c720 0xa1594d 0xa143d3 0xa2a8cd 0x9f0e40 0x9f28df 0x9f379f 0x459f11
#	0xa1594c	google.golang.org/grpc.(*addrConn).nextAddr+0x24c				/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/clientconn.go:1130
#	0xa143d2	google.golang.org/grpc.(*addrConn).resetTransport+0x52				/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/clientconn.go:877
#	0xa2a8cc	google.golang.org/grpc.(*addrConn).createTransport.func2+0x15c			/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/clientconn.go:970
#	0x9f0e3f	google.golang.org/grpc/internal/transport.(*http2Client).Close+0x2af		/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/internal/transport/http2_client.go:779
#	0x9f28de	google.golang.org/grpc/internal/transport.(*http2Client).handleGoAway+0x22e	/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/internal/transport/http2_client.go:1097
#	0x9f379e	google.golang.org/grpc/internal/transport.(*http2Client).reader+0x67e		/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/internal/transport/http2_client.go:1249

63 @ 0x42ca0a 0x43c720 0xa1594d 0xa143d3 0x459f11
#	0xa1594c	google.golang.org/grpc.(*addrConn).nextAddr+0x24c	/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/clientconn.go:1130
#	0xa143d2	google.golang.org/grpc.(*addrConn).resetTransport+0x52	/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/clientconn.go:877

1 @ 0x42ca0a 0x42cabe 0x404212 0x403ecb 0xa3fd0a 0xa0a937 0xa2a45b 0x459f11
#	0xa3fd09	google.golang.org/api/internal.(*PoolResolver).Next+0x49	/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/api/internal/pool.go:54
#	0xa0a936	google.golang.org/grpc.(*roundRobin).watchAddrUpdates+0x56	/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/balancer.go:166
#	0xa2a45a	google.golang.org/grpc.(*roundRobin).Start.func1+0x2a		/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/balancer.go:241

1 @ 0x42ca0a 0x42cabe 0x404212 0x403f0b 0xa0ddcc 0x459f11
#	0xa0ddcb	google.golang.org/grpc.(*balancerWrapper).lbWatcher+0xeb	/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/balancer_v1_wrapper.go:124

1 @ 0x42ca0a 0x43c720 0x4fd57d 0x4fb5c4 0x4e05fc 0x4e17bb 0xa16d13 0xa2a58d 0xa2b1fa 0x9e9f0a 0x9ea1d5 0xa01b77 0xa14df5 0xa14883 0xa2a8cd 0x9f0e40 0x9f28df 0x9f379f 0x459f11
#	0x4fd57c	net.(*Resolver).LookupIPAddr+0x50c						/usr/local/go/src/net/lookup.go:212
#	0x4fb5c3	net.(*Resolver).internetAddrList+0x5c3						/usr/local/go/src/net/ipsock.go:293
#	0x4e05fb	net.(*Resolver).resolveAddrList+0x50b						/usr/local/go/src/net/dial.go:193
#	0x4e17ba	net.(*Dialer).DialContext+0x22a							/usr/local/go/src/net/dial.go:375
#	0xa16d12	google.golang.org/grpc.dialContext+0xb2						/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/go17.go:38
#	0xa2a58c	google.golang.org/grpc.DialContext.func1+0x4c					/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/clientconn.go:175
#	0xa2b1f9	google.golang.org/grpc.newProxyDialer.func1+0x129				/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/proxy.go:121
#	0x9e9f09	google.golang.org/grpc/internal/transport.dial+0x59				/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/internal/transport/http2_client.go:134
#	0x9ea1d4	google.golang.org/grpc/internal/transport.newHTTP2Client+0x104			/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/internal/transport/http2_client.go:167
#	0xa01b76	google.golang.org/grpc/internal/transport.NewClientTransport+0xe6		/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/internal/transport/transport.go:499
#	0xa14df4	google.golang.org/grpc.(*addrConn).createTransport+0x374			/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/clientconn.go:999
#	0xa14882	google.golang.org/grpc.(*addrConn).resetTransport+0x502				/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/clientconn.go:929
#	0xa2a8cc	google.golang.org/grpc.(*addrConn).createTransport.func2+0x15c			/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/clientconn.go:970
#	0x9f0e3f	google.golang.org/grpc/internal/transport.(*http2Client).Close+0x2af		/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/internal/transport/http2_client.go:779
#	0x9f28de	google.golang.org/grpc/internal/transport.(*http2Client).handleGoAway+0x22e	/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/internal/transport/http2_client.go:1097
#	0x9f379e	google.golang.org/grpc/internal/transport.(*http2Client).reader+0x67e		/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/internal/transport/http2_client.go:1249

1 @ 0x42ca0a 0x43c720 0xa0ca8a 0x459f11
#	0xa0ca89	google.golang.org/grpc.(*ccBalancerWrapper).watcher+0x149	/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/balancer_conn_wrappers.go:122

1 @ 0x42ca0a 0x43c720 0xa19a22 0x459f11
#	0xa19a21	google.golang.org/grpc.(*ccResolverWrapper).watcher+0x181	/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/resolver_conn_wrapper.go:109

1 @ 0xa14380 0x459f11
#	0xa14380	google.golang.org/grpc.(*addrConn).resetTransport+0x0	/opt/TeamCityBuild/work/wombat-2/37092157b66e4e8e/.deps/src/google.golang.org/grpc/clientconn.go:867
```

Here's a graph of the established connections of the process over time:
![image](https://user-images.githubusercontent.com/112555/43547530-7eee7738-95a9-11e8-9602-a826e8ed1680.png)

Here's a graph of the memory usage:
![image](https://user-images.githubusercontent.com/112555/43547558-914f5104-95a9-11e8-9430-2f41d247bfec.png)

**Comment by dfawley** [comment]
Thanks for the report @fastest963.  We'll revert the change now and look into the root cause and follow-up later.

**Comment by fastest963** [comment]
@dfawley Thanks for the quick follow-up and revert!

**Comment by jadekler** [comment]
@fastest963 Did this occur immediately after deploying, or some time after deploying?

**Comment by jadekler** [comment]
Hi @fastest963, sorry for the slow reply; gophercon week last week. That would be extremely helpful. So that I don't waste your time, I'd like to try once more this week to reproduce it, and if I'm still unable to I'd love to take you up on that offer.

**Comment by jadekler** [comment]
Hi @fastest963. I've done some more work to the branch, and have tested it by pushing an app to GKE and having it use [`cloud.google.com/go/pubsub`](https://github.com/GoogleCloudPlatform/google-cloud-go) to publish a message to pubsub every second. I've left it running for about a day and have not noticed any memory issues:

<img width="951" alt="screen shot 2018-09-09 at 12 22 13 pm" src="https://user-images.githubusercontent.com/3584893/45267997-404a3a80-b42b-11e8-8fb1-73aab0b571cd.png">

- [My `main.go` is here.](https://gist.github.com/jadekler/34045ef7cc2d98b7e363d007b29c1926)
- [My Dockerfile is here.](https://gist.github.com/jadekler/88eba87590d3ca05bb250cb8be58d3c8)
- The branch can is `transport_refactor` in `https://github.com/jadekler/grpc-go.git`

Would you mind trying this yourself to see if you run into the issue again? If you're still willing, another pair of eyes would be greatly appreciated.

**Comment by fastest963** [comment]
@jadekler Thanks for update! I'll test this out tomorrow and report back.

**Comment by jadekler** [comment]
Super, thank you. I've pushed another - more intensive - pubsub benchmark that does 10,000 publishes a second while creating topics every second, and the memory has been consistently and happily flatlined for the past 6 hours or so. If, however, you do see memory spikes or crashes tomorrow, I'd be very interested in hearing about your setup so that I can further tune mine to match yours.

Thanks again for your help.

**Comment by fastest963** [comment]
@jadekler Everything looks good to me. I deployed
```
google.golang.org/grpc (git) - fa6e9ca fix cancel check
```
to a single production server earlier today and the memory usage over the last 90 minutes seems to be stable:
![image](https://user-images.githubusercontent.com/112555/45451817-3bdf8500-b6aa-11e8-9d37-54c3abb949e5.png)

I'll keep it running overnight and report back if memory spikes or anything bad happens. Thanks for following up and working on this

**Comment by fastest963** [comment]
@jadekler observing the last 24 hours shows no unbounded growth in memory and the memory looks similar to other boxes not running with your patch. 👍

**Comment by jadekler** [comment]
Woot! Thanks @fastest963 !
