### ISSUE TITLE
Clarification on RPC Retry Timeout vs. Absolute Timeout

### ISSUE THREAD

**Issue by trvsysadmin** [grpc/grpc-go#2260]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.14.0

### What version of Go are you using (`go version`)?
1.10.3

### What operating system (Linux, Windows, …) and version?
Ubuntu 16.04

### What did you do?
In `shouldRetry` inside `stream.go` [link](https://github.com/grpc/grpc-go/blob/07ef407d991f1004e6c3367c8f452ed9a02f17ff/stream.go#L495)

```go
	t := time.NewTimer(dur)
	select {
	case <-t.C:
		cs.numRetries++
		return nil
	case <-cs.ctx.Done():
		t.Stop()
		return status.FromContextError(cs.ctx.Err()).Err()
	}
```

It seems that when the context deadline is exceeded, the entire call is stopped and no retry is attempted. Our experiments also verify this behavior where we put our service to sleep for 1 second before replying the call (and the timeout is set to 1 second). Once you set the timeout to 1.1 second, it goes through (as our service replies within about 40ms, so total 1040ms with the sleep, less than 1.1 seconds).

Our past experience in other systems provide us two different timeout values. One for the absolute timeout and another timeout for retries.

We were wondering if a) we have misconfigured something / don't understand something or b) this is as intended.

If the answer is b), is there any way currently to implement a retry based on timeouts? And would there be a chance two timeouts could be introduced for the method config?

Note: I can confirm that I set the environment `GRPC_GO_RETRY=on` although the code uses an inverse `disableRetry`. Hope this is correct.

Much appreciated!

**Comment by menghanl** [comment]
Your understanding is correct.
The RPC deadline applies across all retry attempts for a given RPC.

There was a discussion on gRPC deadline vs attempt deadline:
https://groups.google.com/d/msg/grpc-io/zzHIICbwTZE/0bDxQwPECQAJ (search for deadline)
Short answer is, this case will be covered by hedging.

Hedging support is not available now.

**Comment by trvsysadmin** [comment]
Thanks for the reply. 

Would it be possible for us to mock the simple retry deadline mechanism, even if it's hackish, while we wait for hedging to be implemented without severely affecting grpc internals? As we are not too familiar with the code base, any hints at the right direction would be deeply appreciated.

**Comment by trvsysadmin** [comment]
Another quick clarification: if the service does not provide a service/method config, is there a default time out set for all rpc calls? Asking this in case we have to use a unary interceptor and some hardcoded grpc deadline will also override the interceptor. Thanks!

**Comment by menghanl** [comment]
As you already mentioned yourself, a retry interceptor would work in this case.

What I image this interceptor could do is to get the timeout from the context, and make several RPC attempts with a shorter timeout. Those attempts can happen in a for loop, and at the same time, the interceptor should keep an eye on the overall timeout.

There's no default timeout applied to the RPCs.

**Comment by trvsysadmin** [comment]
Ok, we will try that out. Thanks again for the help!

**Comment by menghanl** [comment]
Closing this issue now.
Please reply if you have further questions.

**Comment by trvsysadmin** [comment]
Thanks @menghanl - We ended up using https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/retry. Will move over to hedging once it is implemented.
