### ISSUE TITLE
No API for server to obtain/validate client's per-RPC credentials?

### ISSUE THREAD

**Issue by chronos-tachyon** [grpc/grpc-go#227]
"google.golang.org/grpc/credentials".Credentials seems to be oriented around attaching credentials to an outgoing client connection.  What I want is to write a server that e.g. validates the client's JWT token against my list of authorized clients.

**Comment by iamqizhao** [comment]
Currently on server side you can use Metadata API FromContext(...) (
https://github.com/grpc/grpc-go/blob/master/metadata/metadata.go#L141 )to
extract oauth token. In the future, we probably will have dedicated API to
do that.
