### ISSUE TITLE
resolver: dns resolver does not allow to set the lookup frequency

### ISSUE THREAD

**Issue by davidklassen** [grpc/grpc-go#2279]
It would be nice to have an option for the resolver builder to set the lookup frequency.
This can be useful when we are balancing grpc client connections in autoscaled environments.
Right now the default freq is set to 30 minutes (https://github.com/grpc/grpc-go/blob/master/resolver/dns/dns_resolver.go#L47) and there is no way to configure this value.

**Comment by dfawley** [comment]
From #1663, your options here are to set max connection age or make a custom resolver that behaves the way you like.  Note that the default DNS resolver will be changed soon to not poll at all.

**Comment by bwplotka** [comment]
> Note that the default DNS resolver will be changed soon to not poll at all.

Can you give more info about this one?

**Comment by dfawley** [comment]
gRPC in Java and C do not poll DNS; they only update when connection errors happen.  We already update when connection errors happen, but we need to implement something to keep retrying if no addresses are returned.  Once that happens, we will remove polling from our DNS resolver.
