### ISSUE TITLE
How to configure .travis.yml to build grpc project on Travis CI?

### ISSUE THREAD

**Issue by hsluoyz** [grpc/grpc-go#2282]
I'm using grpc in my Golang project: https://github.com/casbin/casbin-server. But my Travis CI fails because there's no ``protoc`` binary and the grpc plugin in the CI server.

So what is the correct or recommended way to configure ``.travis.yml`` to let Travis CI setup the protobuf and grpc environment?

**Comment by dfawley** [comment]
You can see how we install `protoc` in our `.travis.yml` -- it's in `vet.sh` and that does:

```sh
      PROTOBUF_VERSION=3.3.0
      PROTOC_FILENAME=protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
      pushd /home/travis
      wget https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/${PROTOC_FILENAME}
      unzip ${PROTOC_FILENAME}
      bin/protoc --version
      popd
```

That said, most open source users check in their generated `pb.go` files to avoid the need to regenerate them for every build.  We only use `protoc` in our CI to make sure they are not stale.
