### ISSUE TITLE
Doubt in grpclb lbpicker code

### ISSUE THREAD

**Issue by lokanadhamm** [grpc/grpc-go#2288]
In the implementation of grpclb-lbPicker at
https://github.com/grpc/grpc-go/blob/ce4f3c8a89229d9db3e0c30d28a9f905435ad365/balancer/grpclb/grpclb_picker.go#L148-L149
we are checking Drop status of serverlist returned by external load balancer and droping the request if its true. But where we will get such an use case at the cost of request drop? or my understanding is wrong?

**Comment by menghanl** [comment]
The drop field is defined [here](https://github.com/grpc/grpc-proto/blob/9b13d199cc0d4703c7ea26c9c330ba695866eb23/grpc/lb/v1/load_balancer.proto#L144). The grpclb server sends a list of `servers` where the client can send the RPCs. Some of those `servers` can be drops.

One use case is that when the backend servers are overloaded, and the grpclb server wants the clients to drop some loads.
This assumes that the client is a well-behaving client. So servers still need to be able to correctly handle the situation where client doesn't respect drop.

**Comment by lokanadhamm** [comment]
In that case why can't load balancer itself ignore those servers in serverlist and send only ready ones?

**Comment by menghanl** [comment]
If all servers in serverlist are valid, traffic will all be sent to those servers.

But 50% of the RPCs will be dropped if half of the servers are valid, and the other half are drops.
