### ISSUE TITLE
How to cancel streaming gRPC Send from server

### ISSUE THREAD

**Issue by rfarnham** [grpc/grpc-go#2295]
I have a bi-directional streaming gRPC server communicating with multiple clients. However, if one client hangs indefinitely, it will cause the `Send` method to block.

Initially I was sending the messages like this:
```
// A message to send to clients currently connected
var serverMsg pb.MyServerMessage

// Currently connected clients
var clients map[pb.MyStreamingServer_MyStreamingServer]bool

for conn := range clients {
    err := conn.Send(&serverMsg)  // NOTE! This will eventually block is any client is unresponsive
    if err != nil {
        log.Printf("Client %v seems to have dropped: %v", conn, err)
        delete(clients, conn)
    }
}
```

If one of the clients is derelict in receiving messages, eventually the goroutine executing the above will block on `conn.Send`. The only way the server code will proceed is if the bad client is restarted (thus closing the stream and returning a non-nil error).

I cannot apply the solution described here https://github.com/grpc/grpc-go/issues/444 because the goroutine calling `Send()` is different from the one calling `Recv()`. Concretely, `Recv()` just enqueues the messages onto a `events chan interface{}` and continues to accept messages. The sender goroutine polls from `events` and propagates them to all the other listening clients.

I adopted the solution described in https://github.com/grpc/grpc-go/issues/1229
```
for conn := range clients {
    // Only difference from above
    err := sendWithTimeout(conn, &serverMsg)
    // ... etc ...
}

func sendWithTimeout(conn pb.MyStreamingServer_MyStreamingServer, serverMsg *pb.MyServerMessage) error {
	errChan := make(chan error, 1)
       // NOTE! This goroutine can be leaked
	go func() {
		err := conn.Send(serverMsg)
		errChan <- err
		close(errChan)

		if err != nil {
                      // This winds up only being called when hung client is killed (i.e. conn.Send returns)
			log.Printf("Async send exiting abnormally: %v", err) .
		}
	}()
	t := time.NewTimer(3 * time.Second)
	select {
	case <-t.C:
               // Ideally, I could close the stream here to unblock the goroutine above
		return status.Errorf(codes.DeadlineExceeded, "send timed out")
	case err := <-errChan:
		if !t.Stop() {
			<-t.C
		}
		return err
	}
}
```

However, the goroutine executing the actual send can block indefinitely in case the client ceases reading messages. The above does avoid blocking the event processing loop, but it could potentially leak a goroutine waiting on a bad client.

Ideally, I could close the streaming connection in the timeout case to notify the async goroutine and allow it to clean up. Is there a way to do that?

**Comment by dfawley** [comment]
@rfarnham

You need to make sure the RPC handler corresponding to the stuck client will terminate when `sendWithTimeout` returns an error.  How to communicate that back to your handler will depend on your implementation.  It looks like you have a centralized registry of active streams that you're looping over in a separate goroutine when sending, so you'll need something like a channel created for each RPC that the main handler goroutine blocks on.  When the main RPC handler returns back to gRPC, the RPC is terminated and all Send/Recv calls are unblocked.  Let us know if you need any further help.
