### ISSUE TITLE
transport is closing error

### ISSUE THREAD

**Issue by VaibhavPage** [grpc/grpc-go#2298]
### What version of gRPC are you using?
v1.14.0

### What version of Go are you using (`go version`)?
1.10

### What operating system (Linux, Windows, …) and version?
MacOS and Linux. Problem appears on both OS.

### What did you do?
The client connects to server and listens for data on the stream(server side streaming). The connection state shows READY and then transitions to TRANSIENT_FAILURE.

_INFO: 2018/09/07 21:50:07 pickfirstBalancer: HandleSubConnStateChange: 0xc420566d00, CONNECTING
INFO: 2018/09/07 21:50:07 pickfirstBalancer: HandleSubConnStateChange: 0xc420566d00, READY
INFO: 2018/09/07 21:50:07 pickfirstBalancer: HandleSubConnStateChange: 0xc420566d00, TRANSIENT_FAILURE
INFO: 2018/09/07 21:50:07 pickfirstBalancer: HandleSubConnStateChange: 0xc420566d00, CONNECTING
INFO: 2018/09/07 21:50:07 pickfirstBalancer: HandleSubConnStateChange: 0xc420566d00, READY_

**After connection becomes READY, calling `Recv()` method on stream throws following error,** 
_INFO: 2018/09/07 21:50:07 transport: loopyWriter.run returning. connection error: desc = "transport is closing"_

The server does not start streaming as soon as client connects but rather waits for some other processing to happen and then starts streaming data. At the client side I tried to set keepalive parameter `PermitWithoutStream` to true but the error persists. I don't override any other default client or server keepalive parameters.

### What did you expect to see?
gRPC to work.

**Comment by menghanl** [comment]
Can you check the server side logs and see if there's any errors? Like creds handshake errors?

Also, on client side, try adding [WithWaitForHandshake dialoption](https://godoc.org/google.golang.org/grpc#WithWaitForHandshake) and see if it makes any difference.

**Comment by uschen** [comment]
seeing quite a few of this error with google cloud go
https://github.com/GoogleCloudPlatform/google-cloud-go/issues/479

**Comment by jadekler** [comment]
@uschen Note - transport errors can come about in a variety of ways. This particular issue is probably gRPC-specific, whereas I suspect yours may be with the google-cloud-go library. If you're seeing errors in google-cloud-go, we welcome you to file a new issue at https://github.com/GoogleCloudPlatform/google-cloud-go/issues so that we can triage.

**Comment by dfawley** [comment]
Closing from inactivity.  Please let us know if you are continuing to have problems.
