### ISSUE TITLE
can't install using go get google.golang.org/grpc

### ISSUE THREAD

**Issue by xi3** [grpc/grpc-go#230]
C:\Users\xi3> go get -u -v google.golang.org/grpc
Fetching https://google.golang.org/grpc?go-get=1
https fetch failed.
Fetching http://google.golang.org/grpc?go-get=1
import "google.golang.org/grpc": http/https fetch: Get http://google.golang.org/grpc?go-get=1: dial tcp 74.125.200.141:8
0: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
package google.golang.org/grpc: unrecognized import path "google.golang.org/grpc"

**Comment by dsymonds** [comment]
Sounds like you have a problem with your network.

**Comment by kissgyorgy** [comment]
I don't:

```
$ go get google.golang.org/grpc                                                                                                                   [07:42:44]
# google.golang.org/grpc/transport
../../../../go/src/google.golang.org/grpc/transport/handler_server.go:220: undefined: http2.TrailerPrefix
../../../../go/src/google.golang.org/grpc/transport/http2_client.go:1070: undefined: http2.MetaHeadersFrame
../../../../go/src/google.golang.org/grpc/transport/http2_client.go:1191: undefined: http2.MetaHeadersFrame
../../../../go/src/google.golang.org/grpc/transport/http2_server.go:232: undefined: http2.MetaHeadersFrame
../../../../go/src/google.golang.org/grpc/transport/http2_server.go:404: undefined: http2.MetaHeadersFrame
../../../../go/src/google.golang.org/grpc/transport/http_util.go:200: undefined: http2.MetaHeadersFrame
../../../../go/src/google.golang.org/grpc/transport/http_util.go:465: f.fr.SetReuseFrames undefined (type *http2.Framer has no field or method SetReuseFrames)
../../../../go/src/google.golang.org/grpc/transport/http_util.go:466: f.fr.ReadMetaHeaders undefined (type *http2.Framer has no field or method ReadMetaHeaders)
../../../../go/src/google.golang.org/grpc/transport/http_util.go:596: f.fr.ErrorDetail undefined (type *http2.Framer has no field or method ErrorDetail)
```

**Comment by dfawley** [comment]
This error is unrelated to the original issue created >2 years ago.  We would prefer not to have one issue for "encountered an error running `go get`".  Please file a new issue if you're still having trouble, and make sure to provide as much information about your environment as you can.
