### ISSUE TITLE
unable to go-get grpc x509 failed solaris 10

### ISSUE THREAD

**Issue by amandeepgautam** [grpc/grpc-go#2304]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
trying to get the latest version

### What version of Go are you using (`go version`)?
LD_LIBRARY_PATH=/usr/gnu/lib go version
go version go1.10.3 gccgo (GCC) 8.2.1 20180814 solaris/sparc

### What operating system (Linux, Windows, …) and version?
Solaris 10

### What did you do?
sudo GOPATH=/opt/go_pkgs LD_LIBRARY_PATH=/usr/gnu/lib go get google.golang.org/grpc

### What did you see instead?
package google.golang.org/grpc: unrecognized import path "google.golang.org/grpc" (https fetch: Get https://google.golang.org/grpc?go-get=1: x509: failed to load system roots and no roots provided)

This is probably related to the installation of CA certs, other packages like glog etc. are installable using go get. Only grpc is not so am creating an issue here for further guidance.

**Comment by amandeepgautam** [comment]
I have ca-certificates already installed but somehow go get is unable to access them. Output of `pkgchk`:

`-bash-3.2$ /usr/sbin/pkgchk -L CSWcacertificates
NOTE: Couldn't lock the package database.
/etc/opt/csw/ca-certificates.conf.CSW f cswpreserveconf 0755 root bin 773 2257 1519820251 CSWcacertificates
/etc/opt/csw/pkg d none 0755 root bin CSWsudo CSWcacertificates CSWopenssh-client CSWgit CSWfontconfig CSWscreen CSWwget
/etc/opt/csw/pkg/CSWcacertificates d none 0755 root bin CSWcacertificates
/etc/opt/csw/pkg/CSWcacertificates/cswmigrateconf f cswmigrateconf 0644 root bin 37 3105 1519820260 CSWcacertificates
/etc/opt/csw/ssl d none 0755 root bin CSWcacertificates
/etc/opt/csw/ssl/certs d none 0755 root bin CSWcacertificates
/opt/csw/etc/ssl d none 0755 root bin CSWcacertificates
/opt/csw/etc/ssl/certs=../../../../etc/opt/csw/ssl/certs s none CSWcacertificates
/opt/csw/sbin/update-ca-certificates f none 0755 root bin 4632 37496 1519820251 CSWcacertificates
/opt/csw/share/cacertificates d none 0755 root bin CSWcacertificates
/opt/csw/share/cacertificates/hash.db f none 0755 root bin 13504 50658 1519820251 CSWcacertificates
/opt/csw/share/cacertificates/mozilla d none 0755 root bin CSWcacertificates
/opt/csw/share/cacertificates/mozilla/ACCVRAIZ1.pem f none 0644 root bin 2775 30089 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/AC_RAIZ_FNMT-RCM.pem f none 0644 root bin 1974 32620 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/AC_RaAz_CerticAmara_S.A..pem f none 0644 root bin 2283 56897 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Actalis_Authentication_Root_CA.pem f none 0644 root bin 2051 37598 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/AddTrust_External_Root.pem f none 0644 root bin 1523 59701 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/AddTrust_Low-Value_Services_Root.pem f none 0644 root bin 1482 56103 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/AffirmTrust_Commercial.pem f none 0644 root bin 1205 32869 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/AffirmTrust_Networking.pem f none 0644 root bin 1205 32823 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/AffirmTrust_Premium.pem f none 0644 root bin 1893 25019 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/AffirmTrust_Premium_ECC.pem f none 0644 root bin 754 61298 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Amazon_Root_CA_1.pem f none 0644 root bin 1189 31365 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Amazon_Root_CA_2.pem f none 0644 root bin 1884 23196 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Amazon_Root_CA_3.pem f none 0644 root bin 656 53170 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Amazon_Root_CA_4.pem f none 0644 root bin 738 59284 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Atos_TrustedRoot_2011.pem f none 0644 root bin 1262 37895 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068.pem f none 0644 root bin 2169 47281 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Baltimore_CyberTrust_Root.pem f none 0644 root bin 1262 37824 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Buypass_Class_2_Root_CA.pem f none 0644 root bin 1917 27153 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Buypass_Class_3_Root_CA.pem f none 0644 root bin 1917 27650 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/CA_Disig_Root_R2.pem f none 0644 root bin 1937 30160 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/CFCA_EV_ROOT.pem f none 0644 root bin 1986 33612 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/COMODO_Certification_Authority.pem f none 0644 root bin 1490 54532 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/COMODO_ECC_Certification_Authority.pem f none 0644 root bin 941 10622 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/COMODO_RSA_Certification_Authority.pem f none 0644 root bin 2088 41943 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Camerfirma_Chambers_of_Commerce_Root.pem f none 0644 root bin 1706 10158 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Camerfirma_Global_Chambersign_Root.pem f none 0644 root bin 1718 11278 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Certigna.pem f none 0644 root bin 1331 43011 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Certinomis_-_Root_CA.pem f none 0644 root bin 1994 33561 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Certplus_Class_2_Primary_CA.pem f none 0644 root bin 1299 40385 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Certplus_Root_CA_G1.pem f none 0644 root bin 1941 28153 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Certplus_Root_CA_G2.pem f none 0644 root bin 795 64163 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Certum_Root_CA.pem f none 0644 root bin 1120 25981 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Certum_Trusted_Network_CA.pem f none 0644 root bin 1356 45279 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Certum_Trusted_Network_CA_2.pem f none 0644 root bin 2080 42173 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Chambers_of_Commerce_Root_-_2008.pem f none 0644 root bin 2596 18925 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/ComSign_CA.pem f none 0644 root bin 1303 41500 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Comodo_AAA_Services_root.pem f none 0644 root bin 1518 59067 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Cybertrust_Global_Root.pem f none 0644 root bin 1319 41237 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/D-TRUST_Root_CA_3_2013.pem f none 0644 root bin 1470 55826 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/D-TRUST_Root_Class_3_CA_2_2009.pem f none 0644 root bin 1518 58746 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/D-TRUST_Root_Class_3_CA_2_EV_2009.pem f none 0644 root bin 1539 60513 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/DST_Root_CA_X3.pem f none 0644 root bin 1201 33233 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Deutsche_Telekom_Root_CA_2.pem f none 0644 root bin 1319 43022 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/DigiCert_Assured_ID_Root_CA.pem f none 0644 root bin 1352 45858 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/DigiCert_Assured_ID_Root_G2.pem f none 0644 root bin 1307 42512 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/DigiCert_Assured_ID_Root_G3.pem f none 0644 root bin 852 4646 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/DigiCert_Global_Root_CA.pem f none 0644 root bin 1340 44553 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/DigiCert_Global_Root_G2.pem f none 0644 root bin 1295 41010 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/DigiCert_Global_Root_G3.pem f none 0644 root bin 839 2711 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/DigiCert_High_Assurance_EV_Root_CA.pem f none 0644 root bin 1368 46264 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/DigiCert_Trusted_Root_G4.pem f none 0644 root bin 1990 34281 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/E-Tugra_Certification_Authority.pem f none 0644 root bin 2246 53504 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/EC-ACC.pem f none 0644 root bin 1913 26764 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/EE_Certification_Centre_Root_CA.pem f none 0644 root bin 1453 54690 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Entrust.net_Premium_2048_Secure_Server_CA.pem f none 0644 root bin 1506 58356 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Entrust_Root_Certification_Authority.pem f none 0644 root bin 1645 3407 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Entrust_Root_Certification_Authority_-_EC1.pem f none 0644 root bin 1091 23326 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Entrust_Root_Certification_Authority_-_G2.pem f none 0644 root bin 1535 60094 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/GDCA_TrustAUTH_R5_ROOT.pem f none 0644 root bin 1982 32886 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/GeoTrust_Global_CA.pem f none 0644 root bin 1218 35152 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/GeoTrust_Primary_Certification_Authority.pem f none 0644 root bin 1270 38991 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/GeoTrust_Primary_Certification_Authority_-_G2.pem f none 0644 root bin 990 15239 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/GeoTrust_Primary_Certification_Authority_-_G3.pem f none 0644 root bin 1445 53832 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/GeoTrust_Universal_CA.pem f none 0644 root bin 1937 29691 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/GeoTrust_Universal_CA_2.pem f none 0644 root bin 1941 28886 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/GlobalSign_ECC_Root_CA_-_R4.pem f none 0644 root bin 713 57861 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/GlobalSign_ECC_Root_CA_-_R5.pem f none 0644 root bin 795 64922 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/GlobalSign_Root_CA.pem f none 0644 root bin 1262 37552 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/GlobalSign_Root_CA_-_R2.pem f none 0644 root bin 1356 46253 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/GlobalSign_Root_CA_-_R3.pem f none 0644 root bin 1230 34832 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Global_Chambersign_Root_-_2008.pem f none 0644 root bin 2588 19381 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Go_Daddy_Class_2_CA.pem f none 0644 root bin 1449 53612 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Go_Daddy_Root_Certificate_Authority_-_G2.pem f none 0644 root bin 1368 45395 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Hellenic_Academic_and_Research_Institutions_ECC_RootCA_2015.pem f none 0644 root bin 1018 18024 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Hellenic_Academic_and_Research_Institutions_RootCA_2011.pem f none 0644 root bin 1514 59669 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Hellenic_Academic_and_Research_Institutions_RootCA_2015.pem f none 0644 root bin 2157 46922 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Hongkong_Post_Root_CA_1.pem f none 0644 root bin 1169 30585 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/ISRG_Root_X1.pem f none 0644 root bin 1941 30191 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/IdenTrust_Commercial_Root_CA_1.pem f none 0644 root bin 1925 28329 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/IdenTrust_Public_Sector_Root_CA_1.pem f none 0644 root bin 1933 29044 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Izenpe.com.pem f none 0644 root bin 2124 46314 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/LuxTrust_Global_Root_2.pem f none 0644 root bin 2059 39671 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Microsec_e-Szigno_Root_CA_2009.pem f none 0644 root bin 1462 54228 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/NetLock_Arany_Class_Gold_FAtanAsAtvAny.pem f none 0644 root bin 1478 56142 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Network_Solutions_Certificate_Authority.pem f none 0644 root bin 1413 51973 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/OISTE_WISeKey_Global_Root_GA_CA.pem f none 0644 root bin 1429 51898 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/OISTE_WISeKey_Global_Root_GB_CA.pem f none 0644 root bin 1348 43648 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/OpenTrust_Root_CA_G1.pem f none 0644 root bin 1945 29360 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/OpenTrust_Root_CA_G2.pem f none 0644 root bin 1945 28277 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/OpenTrust_Root_CA_G3.pem f none 0644 root bin 799 63825 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/QuoVadis_Root_CA.pem f none 0644 root bin 2080 42320 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/QuoVadis_Root_CA_1_G3.pem f none 0644 root bin 1925 28953 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/QuoVadis_Root_CA_2.pem f none 0644 root bin 2043 36715 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/QuoVadis_Root_CA_2_G3.pem f none 0644 root bin 1925 28324 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/QuoVadis_Root_CA_3.pem f none 0644 root bin 2356 64975 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/QuoVadis_Root_CA_3_G3.pem f none 0644 root bin 1925 27736 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/S-TRUST_Universal_Root_CA.pem f none 0644 root bin 1396 49349 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/SSL.com_EV_Root_Certification_Authority_ECC.pem f none 0644 root bin 957 11210 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/SSL.com_EV_Root_Certification_Authority_RSA_R2.pem f none 0644 root bin 2116 44782 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/SSL.com_Root_Certification_Authority_ECC.pem f none 0644 root bin 945 10146 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/SSL.com_Root_Certification_Authority_RSA.pem f none 0644 root bin 2096 43478 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/SZAFIR_ROOT_CA2.pem f none 0644 root bin 1258 37915 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/SecureSign_RootCA11.pem f none 0644 root bin 1250 36342 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/SecureTrust_CA.pem f none 0644 root bin 1352 44193 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Secure_Global_CA.pem f none 0644 root bin 1356 44358 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Security_Communication_RootCA2.pem f none 0644 root bin 1262 38021 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Security_Communication_Root_CA.pem f none 0644 root bin 1226 33577 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Sonera_Class_2_Root_CA.pem f none 0644 root bin 1144 28289 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Staat_der_Nederlanden_EV_Root_CA.pem f none 0644 root bin 1950 30322 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Staat_der_Nederlanden_Root_CA_-_G2.pem f none 0644 root bin 2072 41199 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Staat_der_Nederlanden_Root_CA_-_G3.pem f none 0644 root bin 1954 32154 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Starfield_Class_2_CA.pem f none 0644 root bin 1470 56408 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Starfield_Root_Certificate_Authority_-_G2.pem f none 0644 root bin 1401 49941 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Starfield_Services_Root_Certificate_Authority_-_G2.pem f none 0644 root bin 1425 52340 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/SwissSign_Gold_CA_-_G2.pem f none 0644 root bin 2047 39339 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/SwissSign_Platinum_CA_-_G2.pem f none 0644 root bin 2059 39082 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/SwissSign_Silver_CA_-_G2.pem f none 0644 root bin 2051 38693 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Swisscom_Root_CA_2.pem f none 0644 root bin 2092 42191 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Symantec_Class_1_Public_Primary_Certification_Authority_-_G4.pem f none 0644 root bin 982 15572 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Symantec_Class_1_Public_Primary_Certification_Authority_-_G6.pem f none 0644 root bin 1437 53543 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Symantec_Class_2_Public_Primary_Certification_Authority_-_G4.pem f none 0644 root bin 982 15513 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Symantec_Class_2_Public_Primary_Certification_Authority_-_G6.pem f none 0644 root bin 1437 53464 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/T-TeleSec_GlobalRoot_Class_2.pem f none 0644 root bin 1368 49071 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/T-TeleSec_GlobalRoot_Class_3.pem f none 0644 root bin 1368 47157 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/TARKTRUST_Elektronik_Sertifika_Hizmet_SaAlayAcAsA_H5.pem f none 0644 root bin 1502 58124 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/TC_TrustCenter_Class_3_CA_II.pem f none 0644 root bin 1681 6390 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/TUBITAK_Kamu_SM_SSL_Kok_Sertifikasi_-_Surum_1.pem f none 0644 root bin 1584 63712 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/TWCA_Global_Root_CA.pem f none 0644 root bin 1884 25151 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/TWCA_Root_Certification_Authority.pem f none 0644 root bin 1270 37689 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Taiwan_GRCA.pem f none 0644 root bin 1950 31263 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/TeliaSonera_Root_CA_v1.pem f none 0644 root bin 1872 23562 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/TrustCor_ECA-1.pem f none 0644 root bin 1494 55836 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/TrustCor_RootCert_CA-1.pem f none 0644 root bin 1514 58057 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/TrustCor_RootCert_CA-2.pem f none 0644 root bin 2206 51917 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Trustis_FPS_Root_CA.pem f none 0644 root bin 1242 36169 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/USERTrust_ECC_Certification_Authority.pem f none 0644 root bin 949 13302 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/USERTrust_RSA_Certification_Authority.pem f none 0644 root bin 2096 42240 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/UTN_USERFirst_Email_Root_CA.pem f none 0644 root bin 1669 8146 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/VeriSign_Class_3_Public_Primary_Certification_Authority_-_G4.pem f none 0644 root bin 1283 42305 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/VeriSign_Class_3_Public_Primary_Certification_Authority_-_G5.pem f none 0644 root bin 1734 13055 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/VeriSign_Universal_Root_Certification_Authority.pem f none 0644 root bin 1701 10671 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Verisign_Class_1_Public_Primary_Certification_Authority_-_G3.pem f none 0644 root bin 1486 58461 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Verisign_Class_2_Public_Primary_Certification_Authority_-_G3.pem f none 0644 root bin 1482 56082 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Verisign_Class_3_Public_Primary_Certification_Authority_-_G3.pem f none 0644 root bin 1486 59179 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/Visa_eCommerce_Root.pem f none 0644 root bin 1323 42008 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/XRamp_Global_CA_Root.pem f none 0644 root bin 1514 59682 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/certSIGN_ROOT_CA.pem f none 0644 root bin 1177 30002 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/ePKI_Root_Certification_Authority.pem f none 0644 root bin 2035 37519 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/thawte_Primary_Root_CA.pem f none 0644 root bin 1494 57428 1519820194 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/thawte_Primary_Root_CA_-_G2.pem f none 0644 root bin 941 10992 1519820193 CSWcacertificates
/opt/csw/share/cacertificates/mozilla/thawte_Primary_Root_CA_-_G3.pem f none 0644 root bin 1506 59455 1519820193 CSWcacertificates
/opt/csw/share/doc/cacertificates d none 0755 root bin CSWcacertificates
/opt/csw/share/doc/cacertificates/README.CSW f none 0755 root bin 1766 27852 1519820261 CSWcacertificates
/opt/csw/share/doc/cacertificates/license f none 0644 root bin 202 16939 1519820259 CSWcacertificates
`

**Comment by dfawley** [comment]
Closing from inactivity. Please let us know if you are continuing to have problems.
