### ISSUE TITLE
frequency cannot be configurable for DNS resolver

### ISSUE THREAD

**Issue by kazegusuri** [grpc/grpc-go#2306]
DNS resolver has fixed duration for DNS resolution (30 min) for now.
I want to customize it as smaller duration to resolve more frequently.

`dnsBuilder` it self has `freq` field for resolution, but there is no interface to change it.
`resolver.ResolveNowOption` is the common option for resolvers.
We can populate duration by the option, but is it good for the option?

### What version of gRPC are you using?

v1.15

### What version of Go are you using (`go version`)?

go version go1.11 darwin/amd64

### What operating system (Linux, Windows, …) and version?

Linux, Mac

### What did you expect to see?

I want to customize frequency of DNS resolution

### What did you see instead?

fixed duration is used for resolution

**Comment by dfawley** [comment]
To be in-line with the other grpc implementation languages, we will be removing polling from the DNS resolver; updates will be only performed when a connection error occurs.

See #1663 for more information.
