### ISSUE TITLE
Vendoring breaks reflection

### ISSUE THREAD

**Issue by bluecmd** [grpc/grpc-go#2328]
### What version of gRPC are you using?
Master

### What version of Go are you using (`go version`)?
1.11

### What operating system (Linux, Windows, …) and version?
Linux (Debian testing)

### What did you do?

Using vendored golang project with gRPC and reflection turned on. `grpc_cli` fails with:
```
[bluecmd]$ grpc_cli call localhost:8080 bmc.ManagementService.PressButton 'button: POWER, duration_ms: 1000'
Method name not found
Failed to find method bmc.ManagementService.PressButton in proto files.
Method name not found
Method name not found
Failed to parse request.
```

Removing vendor/ from the project directory and compiling works fine.

For details, see https://github.com/u-root/u-bmc/issues/36

### What did you expect to see?
Same behavior for vendor and non-vendored compilation.

### What did you see instead?
Broken reflection.

**Comment by dfawley** [comment]
What is in your `vendor/` directory before you remove it?

Note that if the same proto package (`pb.go`) is imported multiple times from different locations (including a vendor and a non-vendor directory), that can cause problems.

**Comment by menghanl** [comment]
If the `verdor` directory that got removed is this: https://github.com/u-root/u-bmc/pull/37, it seems there's no gRPC in it.

But it does contain `protobuf`, and we use `protobuf` to find the registered and do reflection. Could it be that the `protobuf` version was old and missed some features?

**Comment by bluecmd** [comment]
According to the (mistakenly) remaining [Gopkg.toml](https://github.com/u-root/u-bmc/blob/master/Gopkg.toml#L28) the version was 1.2.0 which seems to be the latest one.

**Comment by lyuxuan** [comment]
Share some of my findings. I took a look at the issue description here(https://github.com/u-root/u-bmc/issues/36) for more info, and found that the vendor case does not have the line `connecting to localhost:8080` like the successful case. And from the `grpc_cli` source code here(https://github.com/grpc/grpc/blob/master/test/cpp/util/grpc_tool.cc), it seems the parsing is failed in the grpc_cli tool locally. Not sure why vendor caused it though.

**Comment by bluecmd** [comment]
I reproduced the issue with the hints so far presented here.

I can reproduce it by copying `go get vendor/github.com/golang/protobuf` and copy that result into `vendor/github.com/golang/protobuf`.

```
[sfu-diz-gw]$ go build
[sfu-diz-gw]$ ./grpc &
[sfu-diz-gw]$ grpc_cli call localhost:8080 bmc.ManagementService.PressButton 'button: BUTTON_POWER'
connecting to localhost:8080
2018/09/25 09:48:05 Request: {BUTTON_POWER 0 {} [] 0}

Rpc succeeded with OK status
[sfu-diz-gw]$ mkdir -p ../../vendor/github.com/golang/
[sfu-diz-gw]$ cp -R ~/go/src/github.com/golang/protobuf ../../vendor/github.com/golang
[sfu-diz-gw]$ fg
[1]  + running    ./grpc
^C
[sfu-diz-gw]$ go build
[sfu-diz-gw]$ ./grpc &
[sfu-diz-gw]$ grpc_cli call localhost:8080 bmc.ManagementService.PressButton 'button: BUTTON_POWER'
Method name not found
Failed to find method bmc.ManagementService.PressButton in proto files.
Method name not found
Method name not found
Failed to parse request.
```

**Comment by dfawley** [comment]
I'm able to reproduce this with those steps.  It doesn't make any sense to me at this point, but with a repro case we should be able to track down the problem.

With grpcurl:
```
$ grpcurl -plaintext localhost:8080 describe bmc.ManagementService
Failed to resolve symbol "bmc.ManagementService": Symbol not found: bmc.ManagementService

<<however>>

$ grpcurl -plaintext localhost:8080 describe grpc.reflection.v1alpha.ServerReflection
grpc.reflection.v1alpha.ServerReflection is a service:
{
  "name": "ServerReflection",
  "method": [
    {
      "name": "ServerReflectionInfo",
...snip...
```

Strange that the reflection proto descriptors are fine but the ManagementService ones are not.

**Comment by dfawley** [comment]
OK, this is what's happening:

Proto works by having a global registry of symbols.  This "global" registry lives in the `protobuf` package.  Vendoring the `protobuf` package means that every pb.go file that uses the vendored copy will register its symbols with the vendored package, but everything outside of that path will still attempt to use the non-vendored package.

The right solutions are:

1. Don't vendor protobuf (use Go modules instead if version control is needed), or
2. Vendor grpc as well as protobuf, but be wary of anything that isn't vendored that might be using proto, like the well-known types in google.golang.org/genproto (actually those will cause a compile error if they are not vendored also, but this won't be true for all protos).

**Comment by bluecmd** [comment]
Thanks for the investigation. I guess this was triggered by https://github.com/u-root/u-bmc/commit/6befb429b7c3d432b930b87af722598e5631526f in that case. Is there a way to detect this and not fall silently?

I'll certainly add a test for it but if everybody in the whole ecosystem needs to do that it's a bit sub-optimal.

**Comment by dfawley** [comment]
I don't think there's any way for grpc to notice a situation like this.  The best it can do is return an error from the reflection service when it fails to find a symbol in the global proto registry, and that is what it's doing.

Note that vendoring is not really recommended for reasons like this, and vendoring in Go 1.11 with modules enabled works differently - it forces the use of a single copy of a package to avoid situations like this.
