### ISSUE TITLE
used for two different module paths

### ISSUE THREAD

**Issue by mzmuer** [grpc/grpc-go#2339]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
```
v1.15.0
```
### What version of Go are you using (`go version`)?
```
go version go1.11 windows/amd64
```
### What operating system (Linux, Windows, …) and version?
```
windows10 version is 1803
```
### What did you do?
If possible, provide a recipe for reproducing the error.
```
in my project file go.mod
replace (
    google.golang.org/grpc v1.15.0 => github.com/grpc/grpc-go v1.15.0
)
```
### What did you expect to see?
```
normal run, replace 'golang.org/x/lint' to 'github.com/golang/lint'
```
### What did you see instead?
```
go: github.com/golang/lint@v0.0.0-20180702182130-06c8688daad7 used for two different module paths (github.com/golang/lint and golang.org/x/lint)
```

**Comment by menghanl** [comment]
Do you have other replace rules? The error message is about `golang.org/x/lint`, not `grpc-go`.

And this is not a gRPC issue. It's a go module issue, probably related to:https://github.com/golang/go/issues/26904https://github.com/golang/go/issues/26904
