### ISSUE TITLE
Edge case in grpclb: empty server list handled differently between Go/Java/C++

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc-go#2347]
Context: noticed in https://github.com/grpc/grpc/pull/16727, specifically on `client_falls_back_because_no_backends_*` scenarios, which involve:
  * grpclb server that sends empty server lists at the start of the connection and periodically after
  * a fallback server
  * DNS server that resolves the fallback server and the grpclb

If the Go clients receive a "server list", [fallback mode](https://github.com/grpc/grpc-go/blob/master/balancer/grpclb/grpclb_remote_balancer.go#L50) is cancelled regardless of whether or not there are any servers in the server list. [Same for Java clients](https://github.com/grpc/grpc-java/blob/master/grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java#L572). C++, however, only cancels fallback if it received a "server list" containing a non-zero number of backends.

This is admittedly an edge case, but it's a behavior that differs between Go/Java and C++, and I believe isn't described in the name resolution semantics spec.

cc @markdroth @AspirinSJL @zhangkun83 @menghanl

**Comment by markdroth** [comment]
I agree.  In general, I think we should always ignore empty serverlists from the balancer, since that's semantically meaningless.  If the balancer actually wants us to not contact any backends, it should send a serverlist containing a single drop entry.

**Comment by menghanl** [comment]
It sounds reasonable to ignore empty serverlists, and is an easy fix.

But if the balancer never needs to send empty serverlists, and will not send empty serverlists, it is also unnecessary for the client side to handle empty serverlists.

**Comment by markdroth** [comment]
I take back what I said above.  We've run into an internal case where ignoring empty server lists causes us to fail to go into TRANSIENT_FAILURE and stop sending to the last good backend when that backend goes bad and the balancer sends us an empty serverlist.  So I think the right behavior here is to *not* ignore empty serverlists.

I'll fix C-core to do the right thing here.

**Comment by markdroth** [comment]
Doesn't look like I have permission to close this, but it should be fixed by the PR I just merged.

**Comment by menghanl** [comment]
@markdroth Thanks for the fix. I will close this now.
