### ISSUE TITLE
codegen.sh/protoc error

### ISSUE THREAD

**Issue by ggitau** [grpc/grpc-go#236]
Hi?
I get the following error when generating code with the codegen.sh script.

codegen HelloWorld.proto 
protoc-gen-go: program not found or is not executable
--go_out: protoc-gen-go: Plugin failed with status code 1.

The only program I could find in $GOPATH/bin with a similar name is  "protoc-gen-gogo" .

**Comment by ggitau** [comment]
Creating a symbolic link to this file (protoc-gen-gogo) with the name "protoc-gen-go" has solved the issue.

**Comment by awalterschulze** [comment]
Seems you have installed gogoprotobuf and not golang/protobuf you can simply type --gogo_out instead of --go_out that should also fix your problem

**Comment by ggitau** [comment]
Oh my bad.Thanks for pointing that out. Installed golang/protobuf and that sorted it out.
