### ISSUE TITLE
http2client.Write ConnectionError semantics -- possible at-most-once violation

### ISSUE THREAD

**Issue by andres-erbsen** [grpc/grpc-go#238]
I am concerned that there might be an at-most-once violation in the client.go retry loop. I have not tried to trigger it, and probably won't have time to on the immediate future. It may be worth looking at though, just to be sure -- accidentally doubling an RPC call can be pretty bad. Here is my understanding of the code right now:

https://github.com/grpc/grpc-go/blob/master/call.go#L170 calls sendRequest in a loop, retrying if it returns transport.ConnectionError. sendRequest calls http2client.Write without wrapping the returned error. http2client.Write can return transport.ConnectionError after sending the request (https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L463).

Now, the question is whether if http2client.Write returning transport.ConnectionError guarantees that that the server will not process the write? Can we be sure that a write that looks failed to the client actually means that the server does not get the entire request (and handle it)? Because if it does, and the error is returned to client.go, which retries, the RPC would get executed twice. And this would not be how one would want to call "Dispense20Dollars()".

**Comment by iamqizhao** [comment]
rpc is identified with a unique id. retry will issue a brand-new rpc with a different id. Let me know if I missed something.
