### ISSUE TITLE
implementing grpc proxy

### ISSUE THREAD

**Issue by tianxiaoliang** [grpc/grpc-go#2390]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.13-v1.14
### What version of Go are you using (`go version`)?
go 1.11
### What operating system (Linux, Windows, …) and version?
linux
### What did you do?
I have implemented a http2 proxy for grpc, it is based on x/net/http2 pkg
In that case grpc will detect http_proxy env and does http1.1 handshake.
because it is a http2 proxy, the handshake fails and the invocation can not be proceed 
```go
// newProxyDialer returns a dialer that connects to proxy first if necessary.
// The returned dialer checks if a proxy is necessary, dial to the proxy with the
// provided dialer, does HTTP CONNECT handshake and returns the connection.
func newProxyDialer(dialer func(context.Context, string) (net.Conn, error)) func(context.Context, string) (net.Conn, error) {
	return func(ctx context.Context, addr string) (conn net.Conn, err error) {
		var skipHandshake bool
		newAddr, err := mapAddress(ctx, addr)
		if err != nil {
			if err != errDisabled {
				return nil, err
			}
			skipHandshake = true
			newAddr = addr
		}

		conn, err = dialer(ctx, newAddr)
		if err != nil {
			return
		}
		if !skipHandshake {
			conn, err = doHTTPConnectHandshake(ctx, conn, addr)
		}
		return
	}
}
```
### What did you expect to see?
why that handshake is necessary?
after I comment those code, my http2 proxy works fine.

**Comment by tianxiaoliang** [comment]
if this is nessary, how I can make h2c and http1.1 listen on same port?

**Comment by menghanl** [comment]
The code you linked is to support [HTTP CONNECT](https://tools.ietf.org/html/rfc7231#section-4.3.6) proxy. It seems your proxy is not a HTTP CONNECT proxy server. If you don't want this connection to go through your proxy, can you just unset http_proxy?

**Comment by tianxiaoliang** [comment]
User must set http_proxy to easily use my http2 proxy, otherwise user has to modify there code and rebuild to use custom dialer. it is not good experience.

**Comment by menghanl** [comment]
If you don't want to have the default proxy behavior, it can be turned off by setting the custom dialer to one without the proxy code.

**Comment by tianxiaoliang** [comment]
yes, I can set the custom dialer. but why default dialer will do the http 1.1 handshake to a proxy? grpc can use http1.1 proxy?

**Comment by menghanl** [comment]
The handshake done in the default dialer is to support HTTP CONNECT Proxy as defined in https://github.com/grpc/proposal/blob/master/A1-http-connect-proxy-support.md

HTTP CONNECT creates a HTTP tunnel, after that, we send HTTP2 traffic through the tunnel.

**Comment by tianxiaoliang** [comment]
ok, so as a grpc proxy it must support http2 and http1.1 on same listen port

**Comment by menghanl** [comment]
By "grpc proxy", I think you actually mean proxy that supports grpc traffic.
It can be
 - a HTTP2 proxy (which means it parses the request header, looks at the path, and decides where to forward the request).
   - In this case, the proxy needs to do HTTP2 because it needs to parse HTTP2 headers.
 - a [HTTP tunnel](https://en.wikipedia.org/wiki/HTTP_tunnel).
   - In this case, the proxy supports HTTP CONNECT (this is http1.1), and then forwards the raw bytes. Because it doesn't parse HTTP2 headers, it doesn't need to know about HTTP2

Only if you want to support both of these on the same port, you will need to support both HTTP2 and HTTP1.1. But I believe you will only need one of them.

**Comment by menghanl** [comment]
Closing this issue now. Please reply if you have further questions. Thanks.
