### ISSUE TITLE
Invalid connection after renewal of TLS certificate

### ISSUE THREAD

**Issue by nikkolasg** [grpc/grpc-go#2394]
Hi all,

### What version of gRPC are you using?
Master's branch

### What version of Go are you using (`go version`)?
go1.11

### What operating system (Linux, Windows, …) and version?
Linux - multiple OS

### What did you do?

Different nodes talk to each other via gRPC-go with TLS enabled. One certificate was expired on a node, say node 1. We stopped node 1, renewed the certificate, and relaunched node 1. Node 2 was talking correctly to node 1 before, but after the renewal, we got the certificate expired error thing.

### What did you expect to see?

I was not expecting to see any error at all, since reconnecting *should* (?) try with a new complete TLS stack ? 

### What did you see instead?

Errors of expired certificate while the certificate has been renewed.

It has been shown on our setup, and I wanted to know if this is a known issue or something that can happen in your opinion.  And generally, how to handle certificate renewal ? If it is a really surprising issue,  I can try to code a small test to reproduce it but that would take me quite some time.

Thank you !

**Comment by menghanl** [comment]
This is not an expected behavior. Reconnecting will start over with the TLS handshake.
Does this only happen when reconnecting in an existing ClientConn? If you restart the ClientConn, will the connection be successful?

It will also great if you can provide the test to reproduce so we can look into that. Thanks!

**Comment by nikkolasg** [comment]
> Does this only happen when reconnecting in an existing ClientConn? If you restart the ClientConn, will the connection be successful?

Yes I use the same ClientConn, I never create a new one. I need to try with a new ClientConn in case I ave an error, but it's very likely to solve the problem I guess !
I'm keeping in mind to make a small test, but as I said, it won't be very soon...

**Comment by dfawley** [comment]
@nikkolasg if you can provide a reproduction test case, please let us know and we will reopen the issue and investigate.  Thanks!
