### ISSUE TITLE
FR: Provide a canonical method for parsing resolver.Target

### ISSUE THREAD

**Issue by ashi009** [grpc/grpc-go#2403]
As shown on https://godoc.org/google.golang.org/grpc/resolver, resolver.Target doesn't have a public Parse function.  

There are various places in grpc package implemented their own version of `parseTarget`.  Given https://github.com/grpc/grpc/blob/master/doc/naming.md is finalized, there should be a single copy of ParseTarget.

### What version of gRPC are you using?
1.14

### What version of Go are you using (`go version`)?
go version go1.11 darwin/amd64

### What operating system (Linux, Windows, …) and version?
macOS 10.13.6 (17G65)

**Comment by dfawley** [comment]
@ashi009 what are you trying to do and why?  We've considered it grpc's job to parse the target string into a `resolver.Target`, and pass the parsed result to the resolver.

**Comment by ashi009** [comment]
We set dial options based on the scheme of the server address.  For instance, `https://` ones will use TLS security, and `k8s://` ones will use an ALTS variant for in-cluster communication.

Right now we use a simple parser to decide what dial options to use and then let resolver to do its work.

**Comment by dfawley** [comment]
@ashi009 - In that case, you should be able to use `url.Parse` to parse the target string and get the scheme.

**Comment by ashi009** [comment]
Yep. That's what we do ATM.  However, it comes with a few caveats: 

- url.Parse is designed to parses a URL, not URIs. eg. `[2404:6800:4004:80b::200e]` is a valid name per the doc, but will fail url.Parse.
- url.Parse().String() cannot reassemble a target name. There are cases, where we need to re-write the target name. eg. https://abc.com -> dns:///abc.com:443

Given those issues, I think this method should be defined in grpc library.

**Comment by dfawley** [comment]
I discussed this with the other grpc language leads, and they don't offer anything similar.  Target URIs aren't intended to be parsed by users.  We are investigating some different options to configure connection settings based on the scheme, but haven't made any concrete plans yet.
