### ISSUE TITLE
GRPC server and rpc clients with http1.1 

### ISSUE THREAD

**Issue by vaishalig2693** [grpc/grpc-go#2404]
I changed my RPC server which used http1.1 protocol for communication to GRPC server. 
I tried to hit the new server with my existing client and got this error -  

net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x00\x04\x00\x00\x00\x00\x00" type: *url.Error

Is there a way to make it work? If not, how can I build REST-gateway support over rpc server?

**Comment by menghanl** [comment]
gRPC uses HTTP2, so http1.1 request/response won't work.

To do REST with gRPC, you will need a layer to do the conversion.
E.g. https://github.com/grpc-ecosystem/grpc-gateway
