### ISSUE TITLE
UDP

### ISSUE THREAD

**Issue by ggitau** [grpc/grpc-go#241]
Most server side examples I have come across use net.Listen("tcp"...is it possible to use udp instead?

**Comment by ejona86** [comment]
No, we need a reliable channel and UDP is not supported. There has been discussion with playing with things like QUIC, but we aren't currently trying it out and it would be even longer before we decided whether we would support it.

**Comment by ahundt** [comment]
I second this request, I have data that doesn't need guaranteed delivery and instead needs delivery with a deadline, at which point the message/request should simply be dropped because a new more up to date one will be sent.

**Comment by gazialankus** [comment]
It would be great to have a UDP option for streams.

**Comment by bkeys** [comment]
A UDP option would be awesome to have

**Comment by varshanbp** [comment]
I too Support this request. UDP option would be good.

**Comment by hainesc** [comment]
I'd like UDP as well.

**Comment by Swoboderz** [comment]
UDP would be absolutely wonderful in boosting TCP, according to this article https://gafferongames.com/post/deterministic_lockstep/

it would make gRPC ideal for any lockstepping systems, and likely many other systems!

**Comment by hitzhangjie** [comment]
It would be nice if grpc supports UDP.
Walking throught the grpc source code, it still only supports TCP now.
Add support for UDP should be easier than TCP, so why not support it?  What's the reason behind this? For reliability consideration?

**Comment by menghanl** [comment]
We are working on [new interface/abstractions](https://github.com/grpc/grpc-go/issues/906#issuecomment-409368070) between the grpc & transport packages to make it possible for custom transports (UDP could be one of them) to be implemented.
