### ISSUE TITLE
No way to set max receive message size for client

### ISSUE THREAD

**Issue by a-urth** [grpc/grpc-go#2419]
I have a need to send/receive files over grpc and noticed that clients cannot receive messages over 4Mb. On server its all clear how to set both send and receive message size limits. But on client its not that obvious.

Client has method to set option `WithDefaultCallOptions(MaxCallRecvMsgSize(1024*1024*size))` but seems like its not affecting actual max message size on receive. Seems like it should set `maxReceiveMessageSize` for `callInfo`. And it sets, but.
In `google.golang.org/grpc/stream.go:191` used only `maxReceiveMessageSize` from `defaultCallInfo` function call, which returns default value with max receive message size nil. So always `defaultClientMaxReceiveMessageSize` is used as max receive message limit.

Am I missing something or there is no way to set max receive message size limit?

### What version of gRPC are you using?
v1.15.0

### What version of Go are you using (`go version`)?
go1.10 darwin/amd64

**Comment by menghanl** [comment]
This appears to be working for me. Did you get any problem caused by this?

On the code:
we make a copy of default callInfo, and modify it with the call options set by user. So at the line you saw, the value of `c.maxReceiveMessageSize` is already set to the value from your call option.

**Comment by a-urth** [comment]
Ok, so it works with regular client creation, but using balancer (consul in my case) it doesn't. This is how looks client creation in my case (yes, we're using old balancer api)

```golang
grpc.Dial(
		consulURI,
		grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(ClientMaxReceiveMessageSize)),
		grpc.WithInsecure(),
		grpc.WithBlock(),
		grpc.WithTimeout(60*time.Second),
		grpc.RoundRobin(wonaming.NewResolver(serviceName)),
)
```

**Comment by a-urth** [comment]
It seems like its not consul lb either. it should be proxy grpc
