### ISSUE TITLE
Metadata should be case-insensitive/canonicalized

### ISSUE THREAD

**Issue by ishbir** [grpc/grpc-go#242]
Right now, request metadata is a map[string]string without any sort of operation on the key. Considering that the metadata essentially comprises of custom headers, the setter key should be canonicalized using `http.CanonicalHeaderKey` to ensure consistent and expected behaviour.

**Comment by iamqizhao** [comment]
http2 is just one type of transport we have/will have. Probably It is not proper to use the thing in http world to "canonicalize" gRPC. gRPC probably should define its own canonicalization rules. Anyways, this is not a gRPC-Go-specific issue. Please have your proposal in grpc/grpc repo.

**Comment by iamqizhao** [comment]
see https://github.com/grpc/grpc/issues/2587. I will follow once it is done.
