### ISSUE TITLE
Proxy with auth (digest) doesn't work

### ISSUE THREAD

**Issue by kaushiksriram100** [grpc/grpc-go#2422]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
Latest from master branch

### What version of Go are you using (`go version`)?
go version go1.10.3 darwin/amd64

### What operating system (Linux, Windows, …) and version?
CentOS, Production env, using a Squid Proxy (accounts.google.com and pubsub.googleapis.com:443 whitelisted)

### What did you do?
I posted this in google pubsub repo but am diverted here (https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1202#issuecomment-434710884).

I am using the GO-PubSub Package which uses this package for gRPC. 

When interacting with google pubsub, the function hangs forever. 

```
pub, err := pubsub.NewClient(ctx, projectID, option.WithCredentialsFile("file"))
if err != nil {
		fmt.Println(err.Error())
	}
cctx, cancel := context.WithTimeout(context.Background(), 1*time.Minute)
defer cancel()
sub := pub.Subscription("sub")
ok, err := sub.Exists(cctx)  // <- hangs here and then after a minute deadline exceeded.  When I use sub.Receive it hangs forever and never returns even after context expires.
if err != nil {
	fmt.Println(err.Error())
	return
}
fmt.Println(ok)
```

### What did you expect to see?
Expect the function to return and consume messages or interact with pubsub as needed. 

### What did you see instead?

The receive function hangs. 

The squid proxy logs show a TCP_DENIED/407 error. 

Also here is the GRPC DEBUG LOGS:

```
WARNING: 2018/10/31 13:13:06 grpc: addrConn.createTransport failed to connect to {pubsub.googleapis.com:443 0  0}. Err :connection error: desc = "transport: Error while dialing failed to do connect handshake, response: \"HTTP/1.1 407 Proxy Authentication Required\\r\\nConnection: keep-alive\\r\\nContent-Type: text/html;charset=utf-8\\r\\nDate: Wed, 31 Oct 2018 20:13:06 GMT\\r\\nMime-Version: 1.0\\r\\nProxy-Authenticate: Digest realm=\\\"outbound_proxy\\\", nonce=\\\"0gzaWwAAAACAtaIBAAAAANZpvlAAAAAA\\\", qop=\\\"auth\\\", stale=false\\r\\nProxy-Authenticate: Basic realm=\\\"outbound_proxy\\\"\\r\\nServer: squid\\r\\nVia: 1.1 (squid)\\r\\nX-Cache: MISS from \\r\\nX-Cache-Lookup: NONE from \\r\\nX-Squid-Error: ERR_CACHE_ACCESS_DENIED 0\\r\\nContent-Length: 0\\r\\n\\r\\n\"". Reconnecting...
```

**Comment by menghanl** [comment]
Thanks for reporting!

> `407 Proxy Authentication Required`

Authentication is not supported in the current proxy dialer.
I have a fix in #2426. Please give it a try if you have time. Thanks.

**Comment by kaushiksriram100** [comment]
@menghanl : Thanks for this. I am not sure if this is solving my case. I tried setting the http_proxy as env variable. And tried the fixes you provided. Is this related to just squid proxy unable to support http/2 ?

```
export http_proxy=http://user:pwd@web-proxy:3128
```
I am hitting this error (same as old). 

```
WARNING: 2018/11/01 10:44:28 grpc: addrConn.createTransport failed to connect to {pubsub.googleapis.com:443 0  1}. Err :connection error: desc = "transport: Error while dialing failed to do connect handshake, response: \"HTTP/1.1 407 Proxy Authentication Required\\r\\nConnection: keep-alive\\r\\nContent-Type: text/html;charset=utf-8\\r\\nDate: Thu, 01 Nov 2018 17:44:28 GMT\\r\\nMime-Version: 1.0\\r\\nProxy-Authenticate: Digest realm=\\\"outbound_proxy\\\", nonce=\\\"fDvbWwPkQz1gAAAAA\\\", qop=\\\"auth\\\", stale=false\\r\\nProxy-Authenticate: Basic realm=\\\"outbound_proxy\\\"\\r\\nServer: squid\\r\\nVia: 1.1 web-proxy (squid)\\r\\nX-Cache: MISS from web-proxy\\r\\nX-Cache-Lookup: NONE from web-proxy1004\\r\\nX-Squid-Error: ERR_CACHE_ACCESS_DENIED 0\\r\\nContent-Length: 0\\r\\n\\r\\n\""
```

**Comment by menghanl** [comment]
I'm not familiar with squid proxy, but from the error message, I think it supports HTTP CONNECT. In that case, it's not about HTTP2 support, because it's just a HTTP tunnel.

Does it support basic authentication?
The error message (`Proxy-Authenticate: Basic realm="outbound_proxy"`) shows it does, but I still want to confirm.

And if you can get the server side logs for this request, it would also help a lot debugging the problem. Thanks!

**Comment by kaushiksriram100** [comment]
I checked with out network engineer - Looks like it supports only DIGEST AUTH and Basic Auth is disabled.

**Comment by menghanl** [comment]
Supporting digest auth would require more time to do, and we currently don't have the cycles. Sorry about that. I filed #2440 to track it.

In the mean time, if you really need this, you can try to install a [custom Dialer](https://github.com/grpc/grpc-go/blob/master/Documentation/proxy.md#custom-proxy) and do digest auth with it.

**Comment by kaushiksriram100** [comment]
Thank you!
