### ISSUE TITLE
What would lead to block at  "writeQuota"

### ISSUE THREAD

**Issue by yjp211** [grpc/grpc-go#2427]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.14.0-dev
### What version of Go are you using (`go version`)?
1.10.1
### What operating system (Linux, Windows, …) and version?
linux
### What did you do?
If possible, provide a recipe for reproducing the error.

Encapsulated Quic( source code: https://github.com/lucas-clemente/quic-go)  provides both net.listner and net.conn  replace TCP listening and connection for GRPC.

quic.Listener  ==> tcp.Listner
  https://github.com/yjp211/go-replica/blob/master/quic/listener.go
quic.Conn == > tcp.Conn
  https://github.com/yjp211/go-replica/blob/master/quic/conn.go

grpc client:
```
        var opts []grpc.DialOption
	opts = append(opts, grpc.WithInsecure())
	opts = append(opts, grpc.WithDefaultCallOptions(grpc.UseCompressor("gzip")))
	
	opts = append(opts, grpc.WithDialer(func(s string, duration time.Duration) (net.Conn, error) {
		return quic.Dial(s, duration)
	}));


	conn, err := grpc.Dial(addr, opts...)
	if err != nil {
		return nil, err
	}
	return &RpcGreeter{
		conn: conn,
		greeter: pb.NewRpcGreeterClient(conn),
	}, nil
```

grpc server:
```
        lis, err := quic.ListenAddr(fmt.Sprintf(":%d", port))
	if err != nil {
		log.Fatal("failed to listen quic: %v", err)
	}
	s := grpc.NewServer()
	pb.RegisterRpcGreeterServer(s, &Server{})
	go s.Serve(lis)
```

### What did you expect to see?

It works  good, but some time it will be blocked. Restart the client or restart the Server and work again. 

```
goroutine 1413 [select, 157 minutes]:
github.com/webull/go-replica/vendor/google.golang.org/grpc/internal/transport.(*writeQuota).get(0xc42ee9e0e0, 0xc4000001a2, 0x19d, 0x5)
	/go/src/github.com/webull/go-replica/vendor/google.golang.org/grpc/internal/transport/flowcontrol.go:59 +0xdb
github.com/webull/go-replica/vendor/google.golang.org/grpc/internal/transport.(*http2Client).Write(0xc435e0d440, 0xc42e0c4d00, 0xc43e7bd880, 0x5, 0x1c0, 0xc432f8e000, 0x19d, 0x377, 0xc4349ff4ad, 0x6, ...)
	/go/src/github.com/webull/go-replica/vendor/google.golang.org/grpc/internal/transport/http2_client.go:816 +0x1c8
github.com/webull/go-replica/vendor/google.golang.org/grpc.(*csAttempt).sendMsg(0xc439b67e40, 0xa77820, 0xc43e567860, 0xc4349ff4a8, 0x5, 0x5, 0xc432f8e000, 0x19d, 0x377, 0xc433578d80, ...)
	/go/src/github.com/webull/go-replica/vendor/google.golang.org/grpc/stream.go:713 +0xeb
github.com/webull/go-replica/vendor/google.golang.org/grpc.(*clientStream).SendMsg.func2(0xc439b67e40, 0x0, 0x0)
	/go/src/github.com/webull/go-replica/vendor/google.golang.org/grpc/stream.go:637 +0xb3
github.com/webull/go-replica/vendor/google.golang.org/grpc.(*clientStream).withRetry(0xc42d5b0480, 0xc429a30be0, 0xc42e193bf0, 0xc4349ff4a8, 0x5)
	/go/src/github.com/webull/go-replica/vendor/google.golang.org/grpc/stream.go:534 +0x7e
github.com/webull/go-replica/vendor/google.golang.org/grpc.(*clientStream).SendMsg(0xc42d5b0480, 0xa77820, 0xc43e567860, 0x0, 0x0)
	/go/src/github.com/webull/go-replica/vendor/google.golang.org/grpc/stream.go:643 +0x46b
github.com/webull/go-replica/rpc.(*rpcGreeterReplicaClient).Send(0xc435187140, 0xc43e567860, 0x0, 0x0)
	/go/src/github.com/webull/go-replica/rpc/grpc.pb.go:390 +0x49
main.startRelicaTopic.func1.2(0xc423bd24c0, 0xc42203af00, 0xc423526200, 0xc42006e180, 0xc42022fc80, 0xc4234729f0)
	/go/src/github.com/webull/go-replica/client/consumer.go:265 +0x45d
created by main.startRelicaTopic.func1
	/go/src/github.com/webull/go-replica/client/consumer.go:194 +0xdb
```

### What did you see instead?
Quic now still can't get the official support.
To solve this problem, I should start from what direction, can provide some help?

**Comment by yjp211** [comment]
> This function blocks when the sender does not have sufficient flow control to send the current message. That happens when the remote side (the server in this case) isn't reading from the stream. Is the server actively calling `stream.RecvMsg`?


Thanks!!


This is the client-server pseudo-code. Is there any problem?


Client side:
(create a GRPC connection, then open a new  stream and circulates send business data until the stream error,  then open  another a new  stream again)
```
// rpc greeter
var greeter pb.RpcGreeterClient
// stream chain
var streamChain = make(chan pb.RpcGreeter_ReplicaClient)

func main(){
	// create greeter
	createGreeter()

	//work loop
	for {
	WAIT_STREAM:
		stream, ok :=<- streamChain
                
		for {
			//get data from  business queue 
			data :=<- bizQueue

			if err :=stream.Send(data); err != nil{
				//open a new stream when error
				go openNewStream()
				goto WAIT_STREAM
			}
		}
	}
}

func createGreeter() {
	if conn, err := grpc.Dial(addr, opts...); err == nil{
		greeter = pb.NewRpcGreeterClient(conn)
	}else{
		//exit when error
		log.Fatal(err.Error())
	}

}
func openNewStream(){
	for {
		if stream, err := greeter.Replica(context.Background()); err == nil {
			streamChain <- stream
			return
		}else{
			//retry after one Second
			<- time.After(time.Second)
		}
	}
}
```

Server side:
```
func (s *Server) Replica(stream pb.RpcGreeter_ReplicaServer) error {
	for {
		ctx := stream.Context()

		switch val, err := stream.Recv(); {
		case err == nil:
			//TODO something

		case err == io.EOF:
			time.Sleep(1 * time.Second) // provoke race condition
			select {
			case <-ctx.Done():
				log.Warn("Context is already DONE!")
			default:
				log.Info("Context is OK")
			}
			return nil
		default:
			log.Error("receive error: %+v", err)
			return err
		}
	}
}
```
unexpected logs were found on the Server side：

`receive error: rpc error: code = Canceled desc = context canceled`

**Comment by dfawley** [comment]
Do you have info logging enabled on the client and server?  Is your connection persistent or is the connection dying and the client reconnecting when this error occurs?

Could you also update your grpc-go version to our master/HEAD for testing?

**Comment by dfawley** [comment]
@yjp211 have you had a chance to look at any of the debugging info for this?

**Comment by yjp211** [comment]
I haven't repeated "WriteQuota" block recently.

However, some other exceptions were found. GRPC quic conn seems to be easy to "time-out".
The detailed log is as follows:（left is the sending client ）
![image](https://user-images.githubusercontent.com/3926181/48297288-a280f380-e4df-11e8-9c8d-9fd1d6330269.png)

"open new  quic conn" print at:
![image](https://user-images.githubusercontent.com/3926181/48297314-073c4e00-e4e0-11e8-8b19-3c23217717dd.png)

**Comment by yjp211** [comment]
GRPC heartbeat doesn't seem to work as expected. Deploy client&server both on my MAC , 100% recurrence.
During the "80 second timeout", both sides of the GRPC stream can receive and send packages normally.

This is a log printed on my MAC.
Client disconnects earlier than server (every time), but so close. 
![image](https://user-images.githubusercontent.com/3926181/48322496-da647400-e662-11e8-988c-5a7c151b7bd6.png)

**Comment by yjp211** [comment]
GRPC heartbeat doesn't seem to work as expected. Deploy client&server both on my MAC , 100% recurrence.
During the "80 second timeout", both sides of the GRPC stream can receive and send packages normally.

This is a log printed on my MAC.
Client disconnects earlier than server (every time), but so close. 
![image](https://user-images.githubusercontent.com/3926181/48322496-da647400-e662-11e8-988c-5a7c151b7bd6.png)

**Comment by yjp211** [comment]
After extensive debugging, the problem seems at quic-go, I will timely report

**Comment by dfawley** [comment]
Great, thank you for following up.  Let us know if you have any trouble in the future.
