### ISSUE TITLE
Error handling in bi-directional stream on server side

### ISSUE THREAD

**Issue by snktagarwal** [grpc/grpc-go#2435]
Please answer these questions before submitting your issue.

### What did you do?
Here's some of the scaffold.

Client
=====
1. Starts a stream to server
2. Sends a bunch of data
3. Waits for the server to send an *error* back

Server
====
1. Receives the data
2. Simulates an error condition
3. Uses `return err` on the stream thread.
4. I tried to do a Recv() on a separate thread so that I can see io.EOF before that thread is closed down. <-- This never happens.

My question is as follows. If the Server figures out there's an error at T1 and has only gotten messages until T1 - D (last D duration has some inflight messages on Recv() on server). I want to make sure I see all those messages, is that a valid use case on the server side?

Is the expectation that once there's an error on the server side, no more server Recv() calls are going to be useful?

**Comment by dfawley** [comment]
Once the server returns an error from the method handler, the stream is closed and sends/receives on the stream in other goroutines will fail.

I'm not sure why you're wanting to receive messages after returning an error from the server, but note that, in general, when a client sends a message there is no guarantee the server will receive it unless the RPC completes successfully or an ack message is sent back to the client from the server (this must be done in your protocol; grpc does not include message-level acks).

Please let me know if that doesn't answer your question or if you have any follow-ups.  Thanks!

**Comment by snktagarwal** [comment]
There's two concerns with the above design that you might be able to answer:
1. My streaming server does a few things. It is a streaming audio server, so it (a) does storage and (b) does ASR transcription. Storage is the higher priority task. If (b) fails I still want to store all the incoming audio and notify the client that an error has occurred. I thought GRPC errors was the way to go but it seems like building this as application error is a better choice.

2. Recv() is a blocking call which makes it harder for me to do select {Recv(), ContextCancellation(), ...}. For this purposes I put Recv() is a go routine as such:
```
// Converts the recv() call into a channel so that we can use select on various inputs
// TODO: This leaks today, figure out the right behavior here
func (s *VoiceAgentServer) grpcRecvToChan(
    ctx context.Context,
    dialog voice.MsVoiceAgent_DialogServer,
    ch chan interface{}) {
    for {
        req, err := dialog.Recv()
        ch <- &reqWrapper{req: req, err: err}

        // Exit on non-nil error
        if err != nil {
            return
        }
    }
}
```

This leaks if I return error from the main GRPC thread. Any suggestions how to not make this goroutine leak? One idea is to make the main GRPC thread never return an error and hence Recv() shall always finish (assuming we make sure GRPC thread always returns)?

**Comment by dfawley** [comment]
Let us know if you have any further questions.
