### ISSUE TITLE
Handling CORS policy

### ISSUE THREAD

**Issue by Generalomosco** [grpc/grpc-go#2436]
I'm getting cors issue when try to connect web-grpc to golang grpc server saying..

> Access to XMLHttpRequest at 'domain.com:7777/data_grpc.DataHandler/Get' from origin 'http://domain.com' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

How can i handle this issue?

**Comment by menghanl** [comment]
https://github.com/grpc/grpc-web might be a better place for this question.

Also found this: https://github.com/grpc/grpc-web/issues/285. Not sure if this is related though.

**Comment by Generalomosco** [comment]
Solved by using envoy as reflection to Golang grpc server

**Comment by menghanl** [comment]
Glad that worked.
Closing this now. Please reply if you have further questions.
