### ISSUE TITLE
transport is closing every 4 mins

### ISSUE THREAD

**Issue by breznik** [grpc/grpc-go#2447]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.14.0

### What version of Go are you using (`go version`)?
1.10.3

### What operating system (Linux, Windows, …) and version?
Alpine 3.8

### What did you do?
I have two gRPC services running (A & B), each in their own individual container, built on top of the golang:1.10.3-alpine3.8 docker image. I'm running both services via docker-compose, and each one has these two envariables set:
GRPC_GO_LOG_SEVERITY_LEVEL=info
GRPC_GO_LOG_VERBOSITY_LEVEL=2

Service A establishes a gRPC client connection to Service B on startup, using the WithInsecure dial option and a service target such as: "serviceb:10001". KeepAlives are not configured so just the default gRPC behavior. 

### What did you expect to see?
Nothing - just two happy gRPC services, with a transport connection that has happily sitting idle waiting for an rpc to come along.

### What did you see instead?
Exactly every 4 minutes, I'm seeing errors like:
transport: loopyWriter.run returning. connection error: desc = "transport is closing"

When I run these two services locally on my OSX machine (not inside a containers), I see them sitting happily idle, without any transient failures. This somewhat helps me narrow down the issue to alpine and/or linux network settings in general. Obviously this is not an alpine support forum, but since linux has to be a common target to run gRPC in, I'm wondering if there's certain linux network/kernel settings that are expected to be set to maintain gRPC connections and prevent them from being constantly killed and re-established.

**Comment by lyuxuan** [comment]
Hi @breznik, we don't know of such setting that kills the connection every 4 mins. We suspect that it's something related to your specific configuration/environment setup (e.g. container configuration, or platform configuration). If you find the root cause, please let us know about it. It will be very helpful. Thanks!

**Comment by ekrengel** [comment]
@breznik Did you ever figure this out? We're seeing a similar issue.

**Comment by breznik** [comment]
@ekrengel I spent some time unsuccessfully debugging further and haven't had time to take a 2nd look at it, although I still see the same issue, just, not sure how impactful it really is.
