### ISSUE TITLE
Can GracefulStop have a timeout?

### ISSUE THREAD

**Issue by ceshihao** [grpc/grpc-go#2448]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
gRPC 1.7
### What version of Go are you using (`go version`)?
go version go1.9.5 darwin/amd64
### What operating system (Linux, Windows, …) and version?
MacOS Mojave 10.14
### What did you do?
Use `GracefulStop` to stop gRPC Server. It blocks until all the pending RPCs are finished.

However, if some RPC is abnormally pending for a long time, the server has to wait.
Can I set timout for the `GracefulStop`?
### What did you expect to see?
The server can be stop by `GracefulStop` timeout, if some RPC is abnormally pending for a long time.

**Comment by menghanl** [comment]
This can be done by running `GracefulStop` in a goroutine, and do a select-wait on timer followed by a force Stop in the main goroutine.

Something like:
```go
stopped := make(chan, struct{})
go func () {
  s.GracefulStop()
  close(stopped)
}

t := time.NewTimer(10 * time.Second)
select {
case <- t.C:
  s.Stop()
case <- stopped:
  t.Stop()
}
```
