### ISSUE TITLE
FR: Please export "oneof" generated "isMessageName_MyField"  interface

### ISSUE THREAD

**Issue by shavac** [grpc/grpc-go#2449]
The "oneof" field generated code in golang is so complicated. When i want to store inner fields of "one of" with an array, there is no way to determine type validity of that value. Generated code has it's own mechanism by an unexported "isMessageName_MyField" interface , can just export that interface for others to use?

**Comment by menghanl** [comment]
This is a request for protobuf, not gRPC. https://github.com/golang/protobuf is the golang protobuf repo.

Also, this seems like a dup of https://github.com/golang/protobuf/issues/261.
