### ISSUE TITLE
grpclog configure GRPC_GO_LOG_VERBOSITY_LEVEL not takes effect

### ISSUE THREAD

**Issue by longbozhan** [grpc/grpc-go#2451]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.14.0
### What version of Go are you using (`go version`)?
1.1.0
### What operating system (Linux, Windows, …) and version?
linux
### What did you do?
If possible, provide a recipe for reproducing the error.
GRPC_GO_LOG_VERBOSITY_LEVEL  not takes effect while I export GRPC_GO_LOG_VERBOSITY_LEVEL=16.
I found grpclog/loggerv2.go
![image](https://user-images.githubusercontent.com/5351555/48366744-b4ce7d80-e6e9-11e8-84db-fc9ce9cb6389.png)
log.LstdFlags should replaced by v?
v have no use???
how to set GRPC_GO_LOG_VERBOSITY_LEVEL? how to set verbosity level?
### What did you expect to see?
GRPC_GO_LOG_VERBOSITY_LEVEL takes effect.
### What did you see instead?
no effect.

**Comment by menghanl** [comment]
> GRPC_GO_LOG_VERBOSITY_LEVEL not takes effect

What did you see that makes you it's not taking effect?
If you didn't see a whole lot of logs, that's because we don't have that many verbose logs.

I also just tried (by adding a testing log with verbose level 2), and it works.

Also you may want to set `GRPC_GO_LOG_SEVERITY_LEVEL=info`, too.

**Comment by longbozhan** [comment]
@menghanl 
Thanks for you reply. I set verbose export GRPC_GO_LOG_VERBOSITY_LEVEL=16, 16 is log.Lshortfile in glog, means will display file name, but I didn't see any file name.

**Comment by menghanl** [comment]
Did you import `github.com/grpc/grpc-go/tree/master/grpclog/glogger` to install `glog`?

In that case, the log levels and verbose levels are controlled by `glog` command line flags: https://github.com/golang/glog/blob/master/glog.go#L399.

**Comment by longbozhan** [comment]
I solved by import github.com/grpc/grpc-go/tree/master/grpclog/glogger, thank you very much. @menghanl
