### ISSUE TITLE
Support other oauth2/oidc providers apart from Google

### ISSUE THREAD

**Issue by dalu** [grpc/grpc-go#2454]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

current

### What version of Go are you using (`go version`)?

1.11.2

### What operating system (Linux, Windows, …) and version?

Linux arch 64bit

### What did you do?

I read the doc part about using oauth2 for authenticatin purposes, read this file https://github.com/grpc/grpc-go/blob/master/credentials/oauth/oauth.go and saw this lib only support google as the oauth2 provider. It happens I'm running keycloak for my auth needs and  the Google console is limited to ca. 10 free projects.

As it is right now grpc-web is GA. And I'm using a oidc client package with angular to auth.
I would like to not have to write a service definition where every message has a `string bearer = 1;` but use my own, autodiscovery provding oidc endpoint to configure grpc client/server side.

### What did you expect to see?

A custom provider type, not exclusively Google as the possible provider.

### What did you see instead?

Google being the only provider for oauth2 in https://github.com/grpc/grpc-go/blob/master/credentials/oauth/oauth.go

**Comment by menghanl** [comment]
All oauth2 can be implementations of [PerRPCCredentials](https://godoc.org/google.golang.org/grpc/credentials#PerRPCCredentials). The important part is to return the `Metadata` (HTTP headers) to be sent together with the RPCs.

I'm not very familiar with oidc, but I think they would require browsers to work. If your app is going to run in terminal, you will need to solve that.
I imagine you can create one `PerRPCCredentials` at init time, ask user to auth, and reuse it for all `ClientConn`s in the binary.

**Comment by dalu** [comment]
I'm too tired to even begin understanding that and it sound like it's quite low-level too.

I believe that issue should be made at the golang.org/x/oauth2 issue tracker
