### ISSUE TITLE
support generate asynchronous interface for golang implementation

### ISSUE THREAD

**Issue by NeoCN** [grpc/grpc-go#246]
the C and Java implementation will generate asynchronous interface, but golang implementation not, is there a plan ? or some reason ?

**Comment by dsymonds** [comment]
There's generally no reason to have async APIs in Go. It's trivial enough to start a new goroutine when you have need for that.

**Comment by NeoCN** [comment]
when use c client code with async method to invoke golang grpc server, there will be a problem, because there is no  async server interface, unless to modify the generated code. @dsymonds

**Comment by dsymonds** [comment]
You're not making any sense. What problem are you observing in your Go program?

**Comment by murgatroid99** [comment]
"async" is not a property of the method. It is simply the way the method is invoked from the point of view of the invoker. Synchronous and asynchronous versions of the same method send functionally equivalent data on the wire, which is consistent with either form of the method on the server side. There is no problem with sending an RPC using the async interface with a C client and handling it with a synchronous go server.

**Comment by NeoCN** [comment]
get it, thanks @murgatroid99. I will give it a try.

**Comment by yangy2000** [comment]
reverify CLA
