### ISSUE TITLE
If response status not 0 - fields of response message will be initialized with default values

### ISSUE THREAD

**Issue by nikitamiroshnichenko** [grpc/grpc-go#2463]
### What version of gRPC are you using?
1.15.x

### What version of Go are you using (`go version`)?
go1.10.3 linux/amd64

### What operating system (Linux, Windows, …) and version?
Fedora 28 Linux kernel  4.18.13-200.fc28.x86_64

### What did you do?
I have an simple go grpc server (very similiar to GreetingsServer from examples) and I try to send request from C++ client. My response message have int32 field called `magic_number` and this variable always equals 12 in response.

Now problem:
 if ```resonse status.Error(codes.OK)``` - client see correct `magic_number` value - 12, but if ```resonse status.Error(codes.<any_another_grpc_status>)``` - client always see `magic_number` = 0

### What did you expect to see?
I expect that fields in response should receive correct values with any grpc status

P.S.
I tried to write same server in python3 and it works as I expect.

**Comment by dfawley** [comment]
For unary RPCs, if the RPC status is not `OK`, the response message is invalid.

Please see https://github.com/grpc/grpc/issues/12824 for explanation / justification.
