### ISSUE TITLE
Health server implementation imports internal package

### ISSUE THREAD

**Issue by breznik** [grpc/grpc-go#2467]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.14.0 (also tried 1.16.0)

### What version of Go are you using (`go version`)?
1.10.1

### What operating system (Linux, Windows, …) and version?
OSX Mojave

### What did you do?
I'm trying to implement the health-checking solution as outlined in this [kubernetes post](https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/). I wrote a simple code snippet:

```go
import (
    "github.com/grpc/grpc-go/health"
)

var healthSvr = health.NewServer()
```

I'm assuming the above code snippet is considered valid code to write for utilizing the health server.

### What did you expect to see?
Code should compile

### What did you see instead?
vendor/github.com/grpc/grpc-go/health/client.go:30:2: use of internal package not allowed
vendor/github.com/grpc/grpc-go/health/client.go:31:2: use of internal package not allowed

Sure enough, I see in client.go that it imports the packages:
```go
"google.golang.org/grpc/internal"
"google.golang.org/grpc/internal/backoff"
```

Am I misusing this relatively new functionality in gRPC?

**Comment by menghanl** [comment]
One possible reason I can think of is, `internal` package is not vendored correctly. The vendored `client.go` is trying to import `internal` from gopath, and caused the build failure.

Can you check your vendor directory and see if you find `internal` there?

**Comment by breznik** [comment]
Hi,

I'm using glide (for now) as my dependency manager for go. When I look in my `vendor/github.com/grpc/grpc-go/` directory, I do indeed see the `internal` directory.

I tried this again on v1.16.0,  using the following code:

```go
import (
    "google.golang.org/grpc/credentials/google"
)

var test = google.NewDefaultCredentials()
```

This compiles fine, and chose this as the google.go credentials file directly imports the `internal` pkg.

I then tried to modify it (still on v1.16.0) to:
```go
import (
    "github.com/grpc/grpc-go/health"
    "google.golang.org/grpc/credentials/google"
)

var test = google.NewDefaultCredentials()
var healthSvr = health.NewServer()
```

And I once again get the same build error as initially reported.

**Comment by menghanl** [comment]
I just noticed that you are importing `"github.com/grpc/grpc-go/health"`, but the canonical import path is `"google.golang.org/grpc/health"`. Same for your vendored directory hierarchy.

Please try fixing your vendor directory hierarchy and import path.

**Comment by breznik** [comment]
Ah~ha! My import statement was wrong - that was indeed the issue and works on my side now. Thanks for noticing that!
