### ISSUE TITLE
cannot find package "google.golang.org/grpc/test/leakcheck"

### ISSUE THREAD

**Issue by bradylove** [grpc/grpc-go#2469]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

Master

### What version of Go are you using (`go version`)?

1.11.2

### What operating system (Linux, Windows, …) and version?

Linux

### What did you do?

We have a CI job that runs our tests against all the latest dependencies to ensure that we stay up to date. The first part of this CI job runs `go get -u -t ./...`.

### What did you expect to see?

All the packages to be available and downloaded when running `go get -u -t ./...`

### What did you see instead?

```
package google.golang.org/grpc/test/leakcheck: cannot find package "google.golang.org/grpc/test/leakcheck" in any of:
        /usr/local/go/src/google.golang.org/grpc/test/leakcheck (from $GOROOT)
        /home/user/workspace/temp-go/src/google.golang.org/grpc/test/leakcheck (from $GOPATH)
```

Looking at the master branch the `google.golang.grpc/test/leakcheck` package does not exist.

**Comment by menghanl** [comment]
`leakcheck` is not meant to be a public package and was moved to `internal` (#2129).

I just checked that there's all imports in gRPC are pointing to the right location.
Are there imports in your code or other packages that's still referencing the old location?

**Comment by bradylove** [comment]
Terribly sorry, we had apparently added that as a dependency in our code and I have removed it. Thanks for your help.
