### ISSUE TITLE
Test Server/ClientConn, put behind interfaces?

### ISSUE THREAD

**Issue by peter-edge** [grpc/grpc-go#247]
With ClientConn, you might actually be worried about performance in terms of putting behind an interface, but the e2e testing of server implementations, I end up always doing something like this: https://github.com/pachyderm/pachyderm/blob/fa094c9bb80f077c3fe8f30402cc8a403b771aab/src/pfs/pfstest/pfs_test.go#L179

Which is no fun at all, I wish I didn't have to actually use the http transport to do a round trip from the client to server. What I would prefer is a `grpc.NewTestServer()` function, that returns something that both implements a new `grpc.Server` interface, along with a `grpc.GetClientConn()` method that returns a new `grpc.ClientConn` interface, and I don't have  to worry about cleaning up resources or finding free ports.

I'm happy to do the work to implement this, but wanted feedback first. Thoughts?

**Comment by dsymonds** [comment]
I don't see the benefit of you testing the grpc dispatch code, which is really all you're getting if you aren't doing a full server. The generated code has interfaces for the client and server side; I recommend you write tests against those, or write full end-to-end tests that use the complete network stack (i.e. a full grpc server listening on localhost). That's plenty quick enough, and it is actually representative of the environment your code will be running under.

**Comment by peter-edge** [comment]
I don't want to test any of the grpc code, what my goal is is to be able to write tests against a client, that call a server implementation. This is especially hard with, for example, streaming calls. The method signature is significantly different on both sides.

I want to write tests against the client, that call a server implementation, does this make sense? It's very similar to what people try to do with http libs.

**Comment by dsymonds** [comment]
It is still unclear what you're trying to achieve. What's wrong with using grpc.Server, listening on localhost, and having your client code dial that? It's plenty quick enough (O(150µs) roundtrip) and exercises everything fully.

If you're worried about ports, listen on "localhost:0" and let your OS pick a free port.

**Comment by peter-edge** [comment]
That's what I'm doing now - it's fine. I was trying to make it one level nicer, but I can u sweats d the argument to not add more complication.

**Comment by peter-edge** [comment]
*understand the argument (phone typos)
