### ISSUE TITLE
Unimplemented desc = Method

### ISSUE THREAD

**Issue by WithLin** [grpc/grpc-go#2471]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.17.0-dev
### What version of Go are you using (`go version`)?
1.11
### What operating system (Linux, Windows, …) and version?
windows/amd64
### What did you do?
If possible, provide a recipe for reproducing the error.
```go
conn, err := grpc.Dial("localhost:11800", grpc.WithInsecure())
		if err != nil {
			log.Fatalln("Can't connect: " + "localhost:11800")
		}
		defer conn.Close()


		client :=pb.NewApplicationRegisterServiceClient(conn)
		resp,err := client.ApplicationCodeRegister(context.Background(), &pb.Application{ApplicationCode:"test"})
		if err != nil {
			log.Fatalln( err)
		}
		log.Println(resp)
```
### What did you expect to see?
err==nil
### What did you see instead?
Unimplemented desc = Method not found: proto.ApplicationRegisterService/applicationCodeRegister

**Comment by WithLin** [comment]
But it's implemented.

**Comment by menghanl** [comment]
This sounds to me like something is misconfigured.

Can you confirm that the client is connecting to the right server, and the service is registered on the server?

(One thing I notice that's a bit suspicious: the client is called `ApplicationRegisterServiceClient`, but the error message is about a `ServiceNameDiscoveryService`. Those seem to be two very different services.)

**Comment by WithLin** [comment]
I am used  C # client request server, it works perfectly
```c#
var channel = new Channel("localhost:11800", ChannelCredentials.Insecure);
channel.ConnectAsync(DateTime.UtcNow.AddMilliseconds(3)).ConfigureAwait(false);
var client = new ApplicationRegisterService.ApplicationRegisterServiceClient(channel);
var applicationMapping = client.applicationCodeRegister(new Application { ApplicationCode = "test" });
Console.WriteLine($"Register Success{applicationMapping?.Application?.Value}");
Console.Read();
```
The server is written in java. I debug the server and that c# is connected to it successfully, but golang can't connect to the server.

The client is not  connecting to the right server. So what should I do to connect the server correctly?

**Comment by WithLin** [comment]
Because the client is not connecting to the right server, so I try to write a server in golang. The client of golang connects to the server of goalng. It is successful.

```go
type test struct {

}

func (c *test)ApplicationCodeRegister(ctx context.Context, in *pb.Application)(*pb.ApplicationMapping,error){
	a :=new(pb.ApplicationMapping)
	b :=new(pb.KeyWithIntegerValue)
	b.Value=12345

	a.Application=b
	return  a,nil
}

func main()  {
	
	go func() {

		listen, err := net.Listen("tcp", "localhost:11111")
		if err != nil {
			grpclog.Fatalf("failed to listen: %v", err)
		}

		s := grpc.NewServer()


		pb.RegisterApplicationRegisterServiceServer(s, &test{})

		grpclog.Println("Listen on " + "localhost:11111")

		s.Serve(listen)
	}()

	conn, err := grpc.Dial("localhost:11111", grpc.WithInsecure())
	if err != nil {
		log.Fatalln("Can't connect: " + "localhost:11111")
	}
	defer conn.Close()
	for ; ;  {
		resp,err:=pb.NewApplicationRegisterServiceClient(conn).ApplicationCodeRegister(context.Background(),&pb.Application{ApplicationCode:"aaaaa"})
		if err != nil {
			log.Fatalln( err)
		}
		log.Println(resp)

	}
}
```
The c# client is not connecting to the right golang server.

**Comment by menghanl** [comment]
I'm assuming this is just a client and a server, no proxy or anything in between.

1. Is the client connected to the server as expected? (Is the connection established between the client and the server)
   - If not, you might be dialing to a wrong address
   - [Turn on logs](https://github.com/grpc/grpc-go#how-to-turn-on-logging) could help clarify things out.
1. If the client is connected to the expected server (the service is registered on this server), but still get `Unimplemented` error
   - This sounds like a strange problem. 
   - Are the generated codes in different languages in sync?
   - Another suggestion is to look in the generated functions that register services (for go, it would be the `RegisterApplicationRegisterServiceServer` function. There's should be similar ones in Java and c#).


(Another totally random guess:
in `proto.ApplicationRegisterService/applicationCodeRegister`, the first letter of the method name is not capitalized. IMO this should work find and **shouldn't** cause any problems. But if you are still stuck, it's worth trying to change it to `ApplicationCodeRegister`.)

**Comment by WithLin** [comment]
My log output is as follows:

INFO: 2018/11/30 09:48:42 Channelz: socket options are not supported on non-linux os and appengine.
INFO: 2018/11/30 09:48:42 parsed scheme: ""
INFO: 2018/11/30 09:48:42 scheme "" not registered, fallback to default scheme
INFO: 2018/11/30 09:48:42 ccResolverWrapper: sending new addresses to cc: [{localhost:11800 0  <nil>}]
INFO: 2018/11/30 09:48:42 ClientConn switching balancer to "pick_first"
INFO: 2018/11/30 09:48:42 pickfirstBalancer: HandleSubConnStateChange: 0xc0000f6060, CONNECTING
INFO: 2018/11/30 09:48:42 blockingPicker: the picked transport is not ready, loop back to repick
INFO: 2018/11/30 09:48:43 pickfirstBalancer: HandleSubConnStateChange: 0xc0000f6060, READY
2018/11/30 09:48:43 rpc error: code = Unimplemented desc = Method not found: proto.ApplicationRegisterService/applicationCodeRegister
exit status 1

I don't really understand this log. It looks like I can connect to the server successfully.

**Comment by WithLin** [comment]
According to the official demo, goalng can connect c# server. It makes me very confused.
I'll check my code again. Thank you for your reply.

**Comment by menghanl** [comment]
> According to the official demo, goalng can connect c# server. It makes me very confused.

Golang client should be able to talk to c# servers. Interoperability between all languages are expected to work.

I'm going to close this issue now. Please comment here when you have a reproduction or new findings. Thanks!
