### ISSUE TITLE
data race detected reading trailers when stream context cancelled at the same time as server's status is being processed

### ISSUE THREAD

**Issue by jhump** [grpc/grpc-go#2474]
There appears to be a race condition, found by the race detector, when client app reads trailers. I think it must be exceptionally rare as this is the first time I've ever seen it, but Travis CI has been running these tests against the same version of grpc-go for some time.

Interestingly, the fact that my test expected one gRPC error code but instead got `Canceled` likely points to the problem:

1. I have one goroutine sending messages on the bidi stream. If this goroutine encounters an error calling `stream.SendMsg()`, it cancels the context. This happens to be the same context supplied to `NewClientStream` when the RPC was originally invoked.
2. The other goroutine handles the receive side of the bidi stream: it reads the headers, then exhausts the stream via `stream.RecvMsg()`, and finally reads the trailers.

I suspect the cancellation is the issue. What I think might be happening is an interleaving of operations along these lines:

1. Server sends error code, e.g. `PermissionDenied`.
2. Client reads error code and sets state so that calls to `stream.SendMsg()` return an error (`io.EOF` I suspect).
3. Concurrently, goroutine calling `stream.SendMsg()` sees this error. It subsequently *cancels* the stream context.
4. Canceled context is noticed by client so that calls to `stream.RecvMsg()` being to return `Canceled` error. (Error from step 2 above not yet recorded.)
5. Client code that is terminating RPC (same as step 2 above) records trailers. (Here is the write that triggers race detector.)
6. Application code tries to read `stream.Trailer()`. There has been no synchronizing activity between step 5 and this (so race detector is triggered).

The issue is in step 4: the context cancellation seems to be racing the logic that is terminating the RPC based on server's response. So the synchronizing action that would normally occur during the call to `stream.RecvMsg()` is skipped if the context is cancelled, allowing for the data race (even though usage of the client stream seems to be correct).

I could be barking up the wrong tree. But I'd bet the flow above that triggers the race isn't *too* far off...

### What version of gRPC are you using?

1.12.0 (41344da2231b913fa3d983840a57a6b1b7b631a1)

(I looked at release notes and did not see this issue mentioned as being fixed in newer versions. Other race conditions were described as being fixed, but none that appeared to describe this case.)

### What version of Go are you using (`go version`)?

Go 1.11

### What operating system (Linux, Windows, …) and version?

Linux. Unsure of version -- this was in a [Travis CI build](https://travis-ci.org/fullstorydev/grpcurl/jobs/461592602).

### What did you do?

When running unit tests for my project ([grpcurl](https://github.com/fullstorydev/grpcurl)), I got an error from the race detector when trying to access trailers.

The code that is reading the trailers only does so *after*:
1. Invoking a bi-directional method. ([source](https://github.com/fullstorydev/grpcurl/blob/master/invoke.go#L291), which subsequently calls [NewClientStream](https://github.com/jhump/protoreflect/blob/master/dynamic/grpcdynamic/stub.go#L128))
2. Writing requests from a [goroutine](https://github.com/fullstorydev/grpcurl/blob/master/invoke.go#L300) while...
3. Reading the response headers ([source](https://github.com/fullstorydev/grpcurl/blob/master/invoke.go#L329))
4. Reading all response messages until a non-nil error is returned ([source](https://github.com/fullstorydev/grpcurl/blob/master/invoke.go#L336))
Finally, after all this, it reads the trailers ([source](https://github.com/fullstorydev/grpcurl/blob/master/invoke.go#L357)).

Notable: the goroutine in step 2 above sees an error calling `stream.SendMsg()` because the server has returned an error before even bothering to read the first request message. When that happens it [cancels](https://github.com/fullstorydev/grpcurl/blob/master/invoke.go#L324) the stream context.

This triggered a race in the Go race detector:
```
WARNING: DATA RACE
Read at 0x00c0003541b0 by goroutine 97:
  google.golang.org/grpc/transport.(*Stream).Trailer()
      /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.12.0/transport/transport.go:273 +0x41
  google.golang.org/grpc.(*csAttempt).trailer()
      /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.12.0/stream.go:439 +0x50
  google.golang.org/grpc.(*clientStream).Trailer()
      /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.12.0/stream.go:385 +0x50
  github.com/jhump/protoreflect/dynamic/grpcdynamic.(*BidiStream).Trailer()
      /home/travis/gopath/pkg/mod/github.com/jhump/protoreflect@v1.1.0/dynamic/grpcdynamic/stub.go:271 +0x50
  github.com/fullstorydev/grpcurl.invokeBidi()
      /home/travis/gopath/src/github.com/fullstorydev/grpcurl/invoke.go:357 +0x476
  github.com/fullstorydev/grpcurl.InvokeRPC()
      /home/travis/gopath/src/github.com/fullstorydev/grpcurl/invoke.go:135 +0xf1a
  github.com/fullstorydev/grpcurl.InvokeRpc()
      /home/travis/gopath/src/github.com/fullstorydev/grpcurl/invoke.go:56 +0x15e
  github.com/fullstorydev/grpcurl_test.doTestFullDuplexStream()
      /home/travis/gopath/src/github.com/fullstorydev/grpcurl/grpcurl_test.go:683 +0x10c6
  github.com/fullstorydev/grpcurl_test.TestFullDuplexStream.func1()
      /home/travis/gopath/src/github.com/fullstorydev/grpcurl/grpcurl_test.go:631 +0xba
  testing.tRunner()
      /home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:827 +0x162
Previous write at 0x00c0003541b0 by goroutine 20:
  google.golang.org/grpc/transport.(*http2Client).closeStream()
      /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.12.0/transport/http2_client.go:641 +0x48d
  google.golang.org/grpc/transport.(*http2Client).operateHeaders()
      /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.12.0/transport/http2_client.go:1095 +0x321
  google.golang.org/grpc/transport.(*http2Client).reader()
      /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.12.0/transport/http2_client.go:1146 +0x8e1
Goroutine 97 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:878 +0x650
  github.com/fullstorydev/grpcurl_test.TestFullDuplexStream()
      /home/travis/gopath/src/github.com/fullstorydev/grpcurl/grpcurl_test.go:630 +0x1ad
  testing.tRunner()
      /home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:827 +0x162
Goroutine 20 (running) created at:
  google.golang.org/grpc/transport.newHTTP2Client()
      /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.12.0/transport/http2_client.go:265 +0x1119
  google.golang.org/grpc/transport.NewClientTransport()
      /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.12.0/transport/transport.go:466 +0x124
  google.golang.org/grpc.(*addrConn).createTransport()
      /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.12.0/clientconn.go:1282 +0x450
  google.golang.org/grpc.(*addrConn).resetTransport()
      /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.12.0/clientconn.go:1240 +0x794
  google.golang.org/grpc.(*addrConn).connect.func1()
      /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.12.0/clientconn.go:941 +0x3c
```

### What did you expect to see?

No race conditions: as far as I can tell, I am using the stream correctly and not trying to access trailers inappropriately.

### What did you see instead?

Race condition detected (see above for stack traces of offending read and write).

**Comment by canguler** [comment]
I was able to reproduce the data race with the version that you're using but not with the latest version. This [commit](https://github.com/grpc/grpc-go/commit/40a879c23a0dc77234d17e0699d074d5fd151bd0#diff-e2d91404d5609adc9273e4603f6ce67dR571) from 6 months ago seems to fix the problem. Closing this now. Please reopen, if you witness the same data race with a version having the above mentioned commit.

On a side note, while investigating this issue, we have realized that RPC's status and trailer are not always consistent. (e.g. "context cancelled" status and a non-nil trailer) As they're set at the same time on the client side, one should see a nil trailer, if the RPC's returned status is "context cancelled". #2554 solves this problem.
