### ISSUE TITLE
Errors using as dependency due to context import

### ISSUE THREAD

**Issue by Lsquared13** [grpc/grpc-go#2501]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

master branch (fetched with `go get`)

### What version of Go are you using (`go version`)?

go1.11.1

### What operating system (Linux, Windows, …) and version?

OSX Mojave 10.14.1

### What did you do?

Using grpc as a dependency:

1. `git clone https://github.com/Eximchain/go-ethereum.git`
2. `cd go-ethereum`
3. `git checkout 371e2e0ea7675b270807f02f62745e5856df2e1b`
4. `make all`

### What did you expect to see?

A successful build, or at least failures related to building the code in the main repo

### What did you see instead?

An error building `vendor/google.golang.org/grpc/health/grpc_health_v1`:

`vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go:261:20: cannot use handler (type func("github.com/eximchain/go-ethereum/vendor/golang.org/x/net/context".Context, interface {}) (interface {}, error)) as type grpc.UnaryHandler in argument to interceptor
vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go:291:4: cannot use _Health_Check_Handler (type func(interface {}, "github.com/eximchain/go-ethereum/vendor/golang.org/x/net/context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value`

The problem seems to be with [the context import](https://github.com/grpc/grpc-go/blob/master/health/grpc_health_v1/health.pb.go#L11). It seems that adding [commit c0ce831578692f8b2b527755cee28d275b139e58](https://github.com/Eximchain/go-ethereum/commit/c0ce831578692f8b2b527755cee28d275b139e58) to change the context import to use the built-in library fixes my problem

I'd be happy to submit a Pull Request to fix this but I suspect there may be further implications for changing the imported context version.

**Comment by menghanl** [comment]
This shouldn't be a problem since you are using go1.11, and `x/net/context` has been made a type alias of `context` for go version>=1.9 (https://github.com/golang/net/blob/master/context/go19.go).

Your vendored `x/net/context` is pretty old (last updated 2 years ago).
Updating your vendored `x/net/context`, or just removing it from vendor should fix this problem for you.

On updating `context` in the generated code, the change for the codegen has been submitted. We are waiting for a release from protobuf repo.

**Comment by Lsquared13** [comment]
Well one of my dependencies takes issue with me removing it, but the update seems to make it work. Glad to hear the change to the generated code is coming down the pipeline. Thanks
