### ISSUE TITLE
Unable do go get test pacakge

### ISSUE THREAD

**Issue by anjmao** [grpc/grpc-go#2506]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
Newest

### What version of Go are you using (`go version`)?
go1.11.2 darwin/amd64

### What operating system (Linux, Windows, …) and version?
Mac

### What did you do?
1) Go modules on
2) go get -u google.golang.org/grpc
3) go get -u google.golang.org/grpc/test (since step 2 doesn't get test package)

### What did you expect to see?
I expect to be able to get test package, since google.golang.org/grpc.

### What did you see instead?
go get google.com/grpc/test/bufconn: unrecognized import path "google.com/grpc/test/bufconn" (parse https://google.com/grpc/test/bufconn?go-get=1: no go-import meta tags ())

Also it's not possible to get test package using dep. I want to use "google.com/grpc/test/bufconn" to mock connection so I can write unit tests for my streaming api easer.

Probably the easiest solution is to add go.mod file into test folder.

**Comment by dfawley** [comment]
> unrecognized import path "google.com/grpc/test/bufconn" 

This should be imported as "google.golang.org/grpc/test/bufconn", and then everything should work as expected.
