### ISSUE TITLE
json encoding

### ISSUE THREAD

**Issue by wellorange** [grpc/grpc-go#2533]
Below is my protobuf' file:

```proto
enum Dataflag {
  Dic= 0;
  Wor= 1;
}

message Operation {
  Dataflag Dataflag=1;
  Actionflag  Actionflag=2; 
  Word  Word=3;
  Dictionary Dictionary=4;
}
```

After I generated the go code, I used the json encoding operation.
Json will discard fields Actionflag and Dataflag
How to deal with this?

**Comment by dfawley** [comment]
That doesn't sound right to me -- fields should not be discarded.  Can you provide a more complete example that demonstrates what you are seeing?

**Comment by wellorange** [comment]
@dfawley 
This is protobuffer:


service System {
  rpc RequestWord(Operation) returns (Status) {}
  rpc Request(Query) returns (DmResponse) {}
}


  enum Dataflag {
    Dic= 0;
    Wor= 1;
  }
  
  enum Actionflag {
  Add= 0;
  Update = 1;
  Delete=2;
}


message Operation {
  
  Dataflag Dataflag=2;
  Actionflag  Actionflag=3;
  
  Word  Word=1;
  Dictionary Dictionary=4;

}
//  Dictionary is used fronetnd update lexicon
message Dictionary{
  string id=1;
  string dic=2;
  string value=3;
}

client:
	 var op pb.Operation
	 op.Actionflag=pb.Actionflag_Add
	 op.Dataflag=pb.Dataflag_Dic
	 op.Dictionary=&pb.Dictionary{Id:"id",Value:"value",Dic:"测试"}
	 r, err := c.RequestWord(ctx, &op)

server:


func DbWatch(data *pb.Operation) (ok bool)  {
	fmt.Println(data)
	fmt.Println(*data)
	g, _ := json.Marshal(data)
       fmt.Println(string(g))
}

console log:

Dictionary:<id:"id" dic:"\346\265\213\350\257\225" value:"val
{Dic Add <nil> id:"id" dic:"\346\265\213\350\257\225" value:"
{"Dictionary":{"id":"id","dic":"测试","value":"value"}}



When I am json encoded data(g) is stored to mysql
After finding that fields Actionflag and Dataflag are gone

**Comment by wellorange** [comment]
I have solved this problem.I skipped the 0 index
