### ISSUE TITLE
Byte insert into [ ] byte

### ISSUE THREAD

**Issue by udayakumarvdm** [grpc/grpc-go#2539]
I'm working on GRPC stream, In server side, I receive the multiple byte inside the for loop, I want to merge in a single array of byte (I tried append method but not use), Here I have attached my sample code. Any one guide me.

**Example Code**

        func (s *ServerGRPC) Upload(stream pb.GuploadService_UploadServer) (err error) {

        for {
        resp, err := stream.Recv()

        if err != nil {
            if err == io.EOF {
                goto END
            }

            err = errors.Wrapf(err,
                "failed unexpectadely while reading chunks from stream")
            return err
        }

        for _, result := range resp.Content {

            fmt.Println("result ====>>>", result)

          //Actual Output (Byte)
          //result ====>>> 136
          //result ====>>> 84
          //result ====>>> 232
          //result ====>>> 12

          //Expectation ([ ]byte)
          //result ===> [136 84 232 12] 

        }

    }
        s.logger.Info().Msg("upload received")

    END:
        err = stream.SendAndClose(&pb.UploadStatus{
            Message: "Upload received with success",
            Code:    pb.UploadStatusCode_Ok,
        })
        if err != nil {
            err = errors.Wrapf(err,
                "failed to send status code")
            return
        }

        return
    }

**Comment by lyuxuan** [comment]
I think `append` should work for your case. I wrote a quick test code [here](https://play.golang.org/p/FRWWPiGK8wz). Please let me know if your need is different than what I understood and thus append does not work for you. Thanks!

**Comment by lyuxuan** [comment]
Xlose it for now. Please let us know if the you still experience any problem. Thanks!
