### ISSUE TITLE
channelz/types_linux is causing compile-time errors

### ISSUE THREAD

**Issue by jadekler** [grpc/grpc-go#2543]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.16.0

### What version of Go are you using (`go version`)?

```
$ go version
go version go1.11.2 darwin/amd64
```

### What operating system (Linux, Windows, …) and version?

osx

### Problem

https://sponge.corp.google.com/target?id=385a86ed-7a4e-4e00-8bf9-6583fffe2ac2&target=cloud-go-libraries%2Fgoogle-cloud-go%2Fpresubmit%2Fgo110&searchFor=

```
+ eval 'go get -v -t ./...'
++ go get -v -t ./...
../../google.golang.org/grpc/internal/channelz/types_linux.go:26:2: found packages unix (affinity_linux.go) and main (mksysnum.go) in /root/go/src/golang.org/x/sys/unix
+ eval 'go get -v -t ./...'
++ go get -v -t ./...
../../google.golang.org/grpc/internal/channelz/types_linux.go:26:2: found packages unix (affinity_linux.go) and main (mksysnum.go) in /root/go/src/golang.org/x/sys/unix
```

**Comment by jadekler** [comment]
FWIW, this just started popping up in our CI. I have no idea what could have precipitated it. It doesn't seem as though a recent commit to grpc-go would cause it, but...?

**Comment by menghanl** [comment]
Should be fixed by https://github.com/golang/sys/commit/c6cbdbf9e68a68b19802a5c44e537c284b9c8e1a#diff-5f6b0bf9df53057228c1438f608c3b0b

Travis reruns look good.
