### ISSUE TITLE
context deadline exceed

### ISSUE THREAD

**Issue by SavostinVladimir** [grpc/grpc-go#2561]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.12.1
### What version of Go are you using (`go version`)?
1.10.2
### What operating system (Linux, Windows, …) and version?
linux
### What did you do?
I try to get connection here...
```golang
creds, err := credentials.NewClientTLSFromFile(cert, "performer")
			if err != nil {
				logs.Error("Failed to create TLS credentials", err)
			}
			ctx, _ := context.WithTimeout(context.Background(), 3*time.Second)
			conn, err := grpc.DialContext(ctx,"127.0.0.1:"+port, grpc.WithTransportCredentials(creds), grpc.WithBlock())
			if err != nil {
				logs.Error("fail to dial:", err)
				return &grpc.ClientConn{}, errors.New("Performers " + err.Error())
			}
```
this is my server side, and it`s ok:
```golang
lis, err := net.Listen("tcp", fmt.Sprintf("0.0.0.0:%d", *port))
	if err != nil {
		logs.Error("failed to listen:", err)
	}
creds, err := credentials.NewServerTLSFromFile(*certFile, *keyFile)
	if err != nil {
		logs.Error("Failed to generate credentials", err)
	}
	opts := []grpc.ServerOption{grpc.Creds(creds)}
	grpcServer := grpc.NewServer(opts...)
	pb.RegisterGrpcPerformerServer(grpcServer, server.NewGrpcPerformerServer(*advLog, *advLogAll))
	err = grpcServer.Serve(lis)
	if err != nil {
		logs.Error(err)
	}
```
`netstat -at` also says that it`s ok:
![screenshot from 2019-01-14 18-43-19](https://user-images.githubusercontent.com/27097483/51113492-4ebabf80-182c-11e9-9e53-22bab3b6e0d2.png)

### What did you expect to see?
I expect to get connection
### What did you see instead?
`fail to dial: context deadline exceed`
 all of this worked fine a few days ago... I don't understand why now not

**Comment by lyuxuan** [comment]
Can you turn on logging by running the program with env var `GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info` and paste the output log here? Thanks!

**Comment by SavostinVladimir** [comment]
I have seen grpc logs, my certificate was expired, now it's ok! thank you!
