### ISSUE TITLE
Looks like Go client does not check if issuer and subject domains match in self issued certificate

### ISSUE THREAD

**Issue by srini100** [grpc/grpc-go#2566]
See https://github.com/grpc/grpc/issues/17685#issuecomment-453767084 for details.

**Comment by dfawley** [comment]
Is this a check the TLS library should implement, because it is a hard requirement?  Or is it an optional check that we're supposed to be performing that others might not?  (Seems like the former to me, but I'm not completely sure.)

**Comment by srini100** [comment]
When the issuer and subject domains don't match, an issuer CA cert is needed to validate the cert. Unlike [Python API](https://grpc.io/grpc/python/grpc.html?highlight=ssl_channel_credentials#grpc.ssl_channel_credentials), the [Go API](https://godoc.org/google.golang.org/grpc/credentials#NewClientTLSFromFile) doesn't take cert chain as a parameter. Perhaps the Go SSL lib is using the system store and in this case finds the appropriate CA cert while Python depends on CA cert to passed in when issuer and subject names don't match.

cc/ @jiangtaoli2016, any thoughts?

**Comment by srini100** [comment]
@spl0i7, can you confirm if you have the issuer CA cert in your store that Go client may be using for successful handshake? See the above comment.

**Comment by spl0i7** [comment]
I used [certstrap]( https://github.com/square/certstrap) to generate certificates, I do not think I had issuer CA cert.

**Comment by dfawley** [comment]
@spl0i7 - do you happen to know the flags/config you used to generate them?

**Comment by spl0i7** [comment]
I think it was similar to following - 
```
$ certstrap init --common-name "ca.domain"
$ certstrap request-cert --common-name "app.domain"
$ certstrap sign app.domain --CA ca.domain
```

**Comment by srini100** [comment]
Go crypto lib allows partial cert chain validation. This allows a client trusted cert to be used a trust anchor without the need to chain back to root CA cert. gRPC Python is using BoringSSL default that doesn't allow this. Closing this issue as Go behavior is correct. Python behavior is being improved in https://github.com/grpc/grpc/pull/17868
