### ISSUE TITLE
GRPC GO log not logging

### ISSUE THREAD

**Issue by sohilgogri** [grpc/grpc-go#2577]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.19.0

### What version of Go are you using (`go version`)?
go version go1.9.3 darwin/amd64

### What operating system (Linux, Windows, …) and version?
macOS High Sierra

### What did you do?
Enabled the env flags that look like:
GRPC_TRACE=all 
GRPC_VERBOSITY=DEBUG 
GRPC_GO_LOG_SEVERITY_LEVEL=info 
GRPC_GO_LOG_VERBOSITY_LEVEL=2 
CGO_ENABLED=1
GOPATH=/go

### What did you expect to see?
I don't see any transport logs when I have a streaming RPC back and forth. Is there something I am doing wrong?
I tried to follow steps in this issue https://github.com/grpc/grpc-go/issues/2097 as here https://github.com/grpc/grpc-go/issues/2097#issuecomment-391176307. I tried to run the example code as well but I do not see any transport logs. I just see the log that the code is making
`2019/01/16 13:49:49 Greeting: Hello World` on the client and 
`2019/01/16 13:49:49 Received: world` on the server

--Sohil

**Comment by lyuxuan** [comment]
I just tried, and it worked on my desktop, what I am doing is cd into examples/helloworld directory. 
Run the server with the command:
```
$ GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_GO_LOG_VERBOSITY_LEVEL=2 go run greeter_server/main.go
```
Run the client with the command:
```
$ GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_GO_LOG_VERBOSITY_LEVEL=2 go run greeter_client/main.go
```

And I got the following output from client:
```
INFO: 2019/01/16 14:35:29 parsed scheme: ""
INFO: 2019/01/16 14:35:29 scheme "" not registered, fallback to default scheme
INFO: 2019/01/16 14:35:29 ccResolverWrapper: sending new addresses to cc: [{localhost:50051 0  <nil>}]
INFO: 2019/01/16 14:35:29 ClientConn switching balancer to "pick_first"
INFO: 2019/01/16 14:35:29 Subchannel Connectivity change to CONNECTING
INFO: 2019/01/16 14:35:29 pickfirstBalancer: HandleSubConnStateChange: 0xc000150010, CONNECTING
INFO: 2019/01/16 14:35:29 blockingPicker: the picked transport is not ready, loop back to repick
INFO: 2019/01/16 14:35:29 Subchannel Connectivity change to READY
INFO: 2019/01/16 14:35:29 pickfirstBalancer: HandleSubConnStateChange: 0xc000150010, READY
2019/01/16 14:35:29 Greeting: Hello world
INFO: 2019/01/16 14:35:29 Subchannel Connectivity change to SHUTDOWN
```
The following output from server:
```
2019/01/16 14:35:29 Received: world
INFO: 2019/01/16 14:35:29 transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```

Can you try the exact same commands I use and see if it works?

**Comment by sohilgogri** [comment]
I ran the exact same comments. I cd'ed in the examples/helloworld directory and ran the above commands. I also made sure the other variables like `GRPC_TRACE` and `GRPC_VERBOSITY` are not set and they were not. I still get the same log on the client as `2019/01/16 14:44:41 Greeting: Hello world` and on the server as `2019/01/16 14:44:41 Received: world`. Can it be some issues with my version of the dependencies ?

**Comment by lyuxuan** [comment]
`GRPC_TRACE` and `GRPC_VERBOSITY` are irrelevant for grpc go programs, they are for C core based programs.

You can try `go get -u google.golang.org/grpc` to update all dependencies. And you may restart your machine to see if this issue goes away.

**Comment by sohilgogri** [comment]
`go get -u google.golang.org/grpc` worked for me. Maybe it was just a dependency issue.
