### ISSUE TITLE
grpc stream's unclear memory usage findings

### ISSUE THREAD

**Issue by rohanil** [grpc/grpc-go#2588]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
master

### What version of Go are you using (`go version`)?
go 1.10.3

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
I have 2 go applications running on 2 different servers. I have implemented logic to send records from one application to other. I am using grpc Client Streaming RPC to send a sequence of records from client to server. When client is done with all records to send, it stops sending and waits until it receives response from server. The response is sent by server once it is done processing with all records. Somehow, my server is growing with in-use memory and crashing after some time. To check if there is any memory leak, I checked pprof heap profile and it shows some unexplainable things. In in_use heap profile of server, it is shown that memory is used by functions which are there in client application. But ideally, client application's functions should not use memory from server. Is there any reason why this might be happening?

**Comment by menghanl** [comment]
Can you provide more details about where the memory is allocated? Maybe the stack trace you got from pprof?

It would also help if you can give us an example to reproduce the issue. Thanks!

**Comment by menghanl** [comment]
@rohanil ping. Did you have time to take a look and collect pprof data? Thanks!

**Comment by dfawley** [comment]
Please let us know if you have any more information and we can reopen this and investigate.
