### ISSUE TITLE
Time consuming problem, when grpc-go in high concurrency

### ISSUE THREAD

**Issue by adanteng** [grpc/grpc-go#2589]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.17.0

### What version of Go are you using (`go version`)?

1.9.2

### What operating system (Linux, Windows, …) and version?

linux/amd64

### What did you do?

Do some press test on grpc-go, the server is very simple, use helloworld example in grpc-go src, I found that when in high concurrency the time consuming of grpc-go framework is not stable in many places.

1. Start from put a dataFrame in controlbuf, end with loopyWriter sent the dataFrame, the time consuming sometime is longer than others in ms level.
2. Sometimes md.Handler in processUnaryRPC cost too much time too, but the SayHello api in helloworld just return empty response object.
3. Start from client sent dataFrame for a stream, end with server receive the headerFrame for the a stream, the time is also long in ms level sometimes.

https://gist.github.com/adanteng/82fbc9634bab0acb4764bd5689e9b988

### What did you expect to see?

I got some grpc-go service need very stable in time consuming, I want know why grpc-go is not stable in high concurrency, is there any way for me to do some research.

**Comment by adanteng** [comment]
At sender side, I test again to find the position where cost too much time,  found that between "complete put dataFrame to controlbuf" and `preprocessData` alway cost too much time when lots of  dataFrame need to be put into controlbuf and many other dataFrame need `processData`, almost 100+ will cause ms level time consuming.

**Comment by canguler** [comment]
It wasn't always the case. When loopyWriter wasn't the only function to handle writes, all functions that  write needed to acquire a single lock. That was creating contention for the lock and decreasing the performance. [PR #1962](https://github.com/grpc/grpc-go/pull/1962) moved all writes to a single go routine, loopyWriter, to solve this problem.

Let me know if this doesn't answer your question.

**Comment by adanteng** [comment]
`controlBuffer` use `Mutex`，does this will cause all req use the same connection blocked by the send out operation of `loopyWriter`. @canguler

**Comment by adanteng** [comment]
I print the time cost of all funcs of `handle` in controlbuf.go, found that `registerStreamHandler`'s time cost is not fixed, alway >1ms, so I give `estdStreams` a fixed size like 64*1024 when `newLoopyWriter`, performance is better than before.

**Comment by canguler** [comment]
I will try to reproduce this. Can you share your measurements as well?

**Comment by canguler** [comment]
Hey,

I've failed to reproduce that.

My findings for how long registerStreamHandler takes for each configuration.
for n = 1; c = 1000000
Avg: 702.36 ns
for n = 10; c = 100000
Avg: 632.26 ns
for n = 100; c = 10000
Avg: 559.13 ns
for n = 1000; c = 1000
Avg: 456.69 ns

Not just the averages are very low but also in all cases, 100% of registerStreamHandler's invocations take less than 1ms.

**Comment by canguler** [comment]
@adanteng 

Can you share more details on the specifics of your observation? What code did you run?

Thanks!
Can

**Comment by adanteng** [comment]
https://gist.github.com/adanteng/bbd59a0fce1b7228765b2eb39c21700e

**Comment by adanteng** [comment]
My mistake for "alway >1ms" in above comment.

Here is my test code:
https://gist.github.com/adanteng/bbd59a0fce1b7228765b2eb39c21700e

Add following code to  controlbuf.go, I can see some time cost >1ms.

```
	case *registerStream:
		start := time.Now()
		defer func() {
			if time.Now().Sub(start).Nanoseconds()/1000 > 1000 {
				fmt.Println(time.Since(start))
			}
		}()
		return l.registerStreamHandler(i)
```

Actually my point is that I want to found out why sometimes client encounter the cost when call `SayHello` bigger than 5ms. And the qps is low If you use https://gist.github.com/adanteng/82fbc9634bab0acb4764bd5689e9b988 to test.

I do the following, to improve the qps.
1. As I said above, give `estdStreams` a fixed size map, like 128*1024
2. Add `grpc.InitialWindowSize(math.MaxInt32)` and `grpc.InitialConnWindowSize(math.MaxInt32)` when `grpc.NewServer`, which may disable the flowcontrol, what is the side effect?

After I do the above two points, qps is >10w in my machine, look pretty good to me.

**Comment by canguler** [comment]
Hi @adanteng,

I tried to reproduce your initial results (without the suggested optimizations) with the latest grpc (master branch).

Clients run time percentiles - all in nanoseconds:
75th: 400617
95th: 665268
99th: 882342

`registerStreamHandler` run time percentiles - all in nanoseconds:
75th: 394
95th: 1009
99th: 2110

I used your code with slight simplification to only capture the run times that we are interested in.
The code is here: https://gist.github.com/canguler/fc34c005a7faed2dcd6618827588ea54

I ran client with ` -n=100000 -c=20`

I am not sure why you are getting so long run times. I realized that in your initial version, you are printing your run times if they are higher than a threshold. Whereas in your improved version, you are recording the run times and do the printing at the end. I believe second one gives more accurate results. So, I used this approach in my tests.

The results I have doesn't match with yours. Let me know if you can get my results.

**Comment by canguler** [comment]
Hey @adanteng,

Do you have any update on this one?

**Comment by adanteng** [comment]
Sorry for the delay, I run the code in your gist, run time percentiles is stable and look good to me. 

I think this problem can be closed. Thanks for the reply.

I still need some time to test more details in grpc-go, when I found something, will post a question.

**Comment by canguler** [comment]
No problem. Please let us know when you find more.
