### ISSUE TITLE
Empty data frames are mistaken for EOF.

### ISSUE THREAD

**Issue by awpr** [grpc/grpc-go#259]
If the peer sends an empty data frame, we will mistakenly consider the stream to be closed.  This is caused by transport.recvBufferReader.Read() returning the results of a bytes.NewReader without checking that the underlying buffer is non-empty.  This returns EOF, which bubbles all the way up to grpc.recvResponse().

PR incoming.

**Comment by iamqizhao** [comment]
In grpc wire protocol, there is no empty data frame since it always has
compression flag and a length field (refer to "Delimited-Message" part in
the protocol doc). But yes, we need to deal with misbehaved peers. For this
purpose, the right operation to deal with empty data frame and data frame
with EOS flag (your previous pr) should be tearing down the connection. We
should not keep talking to the peer when we already know it is broken. I
will make a pr to fix this (including the case of data frame with EOS).
Your contribution is welcome too.

**Comment by awpr** [comment]
The spec specifically says that there is no connection between frame
boundaries and delimited message boundaries.  Empty data frames are unusual
but not invalid, and should be treated as if nothing had happened.  From a
higher level, the spec treats the concatenated contents of all data frames
in a stream as if they were an undistinguished stream of bytes -- that is,
it explicitly knows nothing about where frames begin and end.  Treating an
empty HTTP2 data frame as illegal would be inconsistent with this, because
it would behave differently depending on on how the bytes were divided into
frames.

**Comment by iamqizhao** [comment]
I was not saying there is a connection between frame boundaries and
delimited message boundaries. I was saying with the per-message header
(compression flag + length), there is no way for a valid impl to send an
empty data frame. If you do not have any data to send, why bother sending a
data frame? Show me a case where an empty data frame will be sent if you
insist.

The only reason for this handling is for mis-behaved peer in my mind. But I
am  a bit panic to keep adding the code for corner case handling without
test cases showing the corner case could happen.

**Comment by awpr** [comment]
It's true that there's no way for an _optimal_ implementation to send an empty data frame because it would always be cheaper not to send it, but it's not disallowed.  An implementation could legally send each byte in its own data frame followed by an empty data frame, if it felt like being wasteful.  I don't understand how allowing the RPC to be silently corrupted in this case is an acceptable option.

**Comment by awpr** [comment]
Also, regarding tearing down the connection in response to a data frame with EOS, it's not necessarily the case that the whole connection is broken.  This could happen if the client erroneously tries to make an RPC call to a path on the same server that's not a gRPC path (e.g. /example_dashboard_url).  In this case the server is not broken (because normal HTTP/2 requests are not required to have trailers frames) and the connection is not invalid; only that particular RPC is affected, and other RPCs on the same connection to correct paths can still succeed.
