### ISSUE TITLE
`Unavailable` mistakenly being returned on ConnectionError

### ISSUE THREAD

**Issue by g7r** [grpc/grpc-go#2590]
### What version of gRPC are you using?
v1.18.0

### What version of Go are you using (`go version`)?
```
> go version
go version go1.11.4 linux/amd64
```

### What operating system (Linux, Windows, …) and version?
Pop! OS Linux

### What did you do?
I'm making a request to a gRPC server that is starting to stop in the middle of request handler execution.
For steps to reproduce refer to https://github.com/g7r/grpcunavailable

### What did you expect to see?
I expected status code different from `Unavailable` because `Unavailable` is the most reliable way to determine whether request should be retried. Here is documentation excerpt from https://github.com/grpc/grpc-go/blob/master/codes/codes.go#L83:
```
	// A litmus test that may help a service implementor in deciding
	// between FailedPrecondition, Aborted, and Unavailable:
	//  (a) Use Unavailable if the client can retry just the failing call.
```

### What did you see instead?
gRPC client returns gRPC status with `Unavailable` code.
It is a serious issue for any retry logic that depends on gRPC status code.

**Comment by dfawley** [comment]
This is implemented according to the grpc spec [here](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md):

> Some data transmitted (e.g., request metadata written to TCP connection) before connection breaks | UNAVAILABLE | Client

It's unlikely this can be changed.

> I'm making a request to a gRPC server that is starting to stop in the middle of request handler execution.

As a general suggestion related to this, you may want to look into graceful shutdown for your servers:
https://godoc.org/google.golang.org/grpc#Server.GracefulStop

It's common to call this then -- in another goroutine -- wait for a timeout before calling `Stop` to allow existing RPCs extra time to finish before forcefully closing the server.

Additionally, you should try to make sure your API is designed such that all RPCs are safe to retry.

**Comment by g7r** [comment]
> This is implemented according to the grpc spec here:

>>    Some data transmitted (e.g., request metadata written to TCP connection) before connection breaks | UNAVAILABLE | Client

> It's unlikely this can be changed.

I can't agree with you. Spec says that "Some data transmitted" which clearly is not the same as "All data transmitted". I don't see that anything should be changed in spec to fix described behaviour.
> As a general suggestion related to this, you may want to look into graceful shutdown for your servers:
https://godoc.org/google.golang.org/grpc#Server.GracefulStop
> It's common to call this, then -- in another goroutine -- wait for a timeout before calling Stop to allow existing RPCs extra time to finish before forcefully closing the server.

This is exactly what I do. But it leaves possibility for clients to receive `Unavailable` status.

I think that returning `Unavailable` for fully transmitted requests breaks guarantees for retryability mentioned in status codes docs.

**Comment by dfawley** [comment]
> "Some data transmitted" which clearly is not the same as "All data transmitted".

"All data transmitted" is a special case of "Some data transmitted".  It's also unclear how this condition would apply to streaming RPCs.

This would be a change to the grpc spec, and any proposals to change it should be filed against the [grpc/grpc](https://github.com/grpc/grpc/issues/new) repo or brought up on the [grpc-io](https://groups.google.com/forum/#!forum/grpc-io) mailing list.

> I think that returning Unavailable for fully transmitted requests breaks guarantees for retryability mentioned in status codes docs.

What docs are you referring to?  The status codes doc I linked effectively says there are no guarantees:

> As shown in the table above, the gRPC library can generate the same status code for different cases.  ...  Therefore, there is no fixed list of status codes on which it is appropriate to retry in all applications.

I agree this is unfortunate, but I'm not sure it will be feasible to change it.  We would also need to change the "Server shutting down" case for it to have any benefit.   Additionally, finding a more appropriate status code is tricky.  E.g. `Aborted` seems best, but we've already declared that grpc will never generate it.

**Comment by g7r** [comment]
> "All data transmitted" is a special case of "Some data transmitted".

While this statement is logically true, the cases are very different when we are trying to see them from retrying possibility point of view. For example, docs on transparent retries clearly differentiate the former from the latter: https://github.com/grpc/proposal/blob/master/A6-client-retries.md#transparent-retries

> This would be a change to the grpc spec, and any proposals to change it should be filed against the grpc/grpc repo or brought up on the grpc-io mailing list.

I don't think that fixing the problem will be against the grpc spec. Furthermore, the current state of client status codes is incompatible with the spec.

> What docs are you referring to?

https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto#L118 and https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto#L172

> > As shown in the table above, the gRPC library can generate the same status code for different cases. > > ... Therefore, there is no fixed list of status codes on which it is appropriate to retry in all applications.

> I agree this is unfortunate, but I'm not sure it will be feasible to change it.

The citation you've provided is about application specifics. Of course I can reuse in my application any gRPC status codes in any way I like to. And I can break retries too. But current Go gRPC implementation doesn't allow me any kind of retries (except transparent ones) because I can't be sure about the real cause of `Unavailable`.

I've just checked what status code Java gRPC client returns in the same case. And it turns out that Go gRPC implementation isn't alone. It is very sad that the current state of the art in gRPC ecosystem effectively prevents retries on `Unavailable` status.

**Comment by dfawley** [comment]
> Furthermore, the current state of client status codes is incompatible with the spec.

`code.proto` is not a spec.  It provides guidelines on when to use different codes, which the grpc spec is unfortunately not following in this case.  grpc-go and grpc-java are following the grpc spec -- what you are asking for would require a change to the spec.  But be aware that it may not be possible to change given other constraints (backward compatibility, choosing a more appropriate code, consideration of streaming RPCs, etc).

In terms of retry, best practice is to make all RPCs idempotent or safe to retry, so retrying on `Unavailable` in all cases where grpc generates it would be OK.
