### ISSUE TITLE
ErrConnClosing is returned as Internal error by http2Server.Write

### ISSUE THREAD

**Issue by euroelessar** [grpc/grpc-go#2593]
### What version of gRPC are you using?

1.18.0

### What did you do?

In server-side streaming make client disconnect before server sends headers via `http2Server.Write`.

### What did you expect to see?

Server sees `code = Unavailable desc = transport is closing` error.

### What did you see instead?

First `.Send` call implicitly sends headers.
`http2Server.WriteHeader` returns `ErrConnClosing`, but `http2Server.Write` wraps it into one with `Internal` code, which results into `code = Internal desc = transport: connection error: desc = "transport is closing"`.

**Comment by dfawley** [comment]
@euroelessar to help us prioritize this, can you let us know if this is causing any problems for you or is just something you happened to notice?  Thanks.

**Comment by FUSAKLA** [comment]
Hi, just wanted to check if this should apply also for the [`ErrIllegalHeaderWrite`](https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_server.go#L757) error or not?
I'm getting lots of those errors reported as an `Internal` status but IIUC those are caused just by client closing the connection and trying to write the headers to done stream?
