### ISSUE TITLE
cannot find module providing package google.golang.org/genproto/googleapis/rpc/status

### ISSUE THREAD

**Issue by tingtingr** [grpc/grpc-go#2597]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.18.0

### What version of Go are you using (`go version`)?
go version go1.11.4 darwin/amd64

### What operating system (Linux, Windows, …) and version?
macOS Sierra 10.12.6

### What did you do?
`go get -u google.golang.org/grpc`

`make build`

### What did you expect to see?
no error

### What did you see instead?

`../go/pkg/mod/google.golang.org/grpc@v1.18.0/status/status.go:37:2: unknown import path "google.golang.org/genproto/googleapis/rpc/status": cannot find module providing package google.golang.org/genproto/googleapis/rpc/status`

in another version, I encountered the same error.

`..grpc-go@v0.0.0-20180806230247-07ef407d991f/internal/transport/http_util.go:37:2: unknown import path "google.golang.org/genproto/googleapis/rpc/status": cannot find module providing package google.golang.org/genproto/googleapis/rpc/status
`

**Comment by menghanl** [comment]
Where did you run `go get -u google.golang.org/grpc` and what's its output?

Also what does `make build` do?

`google.golang.org/genproto` is specified in [our dependencies](https://github.com/grpc/grpc-go/blob/master/go.mod#L18), so this shouldn't be a problem.

**Comment by tingtingr** [comment]
Where did you run go get -u google.golang.org/grpc and what's its output?
- from our project directory

Also what does make build do? Is it just go build?
-Yes. It just build and compile

I have `google.golang.org/grpc v1.17.0` in my `go.mod` file and it gives me the error. Maybe I am doing something wrong with that line.

**Comment by menghanl** [comment]
Closing now. Please reply if you still have the problem. Thanks!
