### ISSUE TITLE
Client hangs until connection dies when a stream is refused.

### ISSUE THREAD

**Issue by awpr** [grpc/grpc-go#261]
If a stream is reset by the peer before headers are received (e.g. by REFUSED_STREAM when the client has exceeded the server's allowed concurrency), the select in transport.Stream.Header will block forever (or until the context is cancelled or all headerChans are cancelled by connection closure).  handleRSTStream should probably close the stream's headerChan if necessary.

It might also make sense to consider REFUSED_STREAM failures as retryable.

**Comment by iamqizhao** [comment]
CloseStream will be called to close headerChan.

It will almost be sure to get another failure if we retry that rpc with REFUSED_STREAM immediately. Some backoff algorithm is needed. I lean to leave this to users.

**Comment by iamqizhao** [comment]
It would be good if you have a test case to confirm your hypothesis if you think there is still some issue.

**Comment by awpr** [comment]
There is no call to CloseStream that could wake this select.  The only two calls involved in unary RPCs are in sendRequest and in Invoke; the first has already not happened if we're blocking on stream.Header() in recvResponse, and the second does not happen until after recvResponse returns.

I've seen this happen every time a server sent a RST_STREAM frame with REFUSED_STREAM.  I'm not sure how easy it would be to make this happen with a Go gRPC server since I haven't looked at that code much, but if it has a configurable concurrency limit, setting it to 0 should probably reproduce it consistently.

**Comment by awpr** [comment]
Regarding retrying, the client code has a quota pool that's supposed to block requests until there's an available concurrency slot on the server, so the only time we should get REFUSED_STREAM is when the settings are out of sync, and that should correct itself relatively quickly (~ network round-trip time).  If the quota pool is working correctly, retrying immediately at the top level would actually result in blocking on stream quota until we believe the server will not refuse the stream and _then_ retrying.
