### ISSUE TITLE
Client fails to account for existing streams when setting MAX_CONCURRENT_STREAMS.

### ISSUE THREAD

**Issue by awpr** [grpc/grpc-go#262]
When a client transport receives its first settings frame setting MAX_CONCURRENT_STREAMS to N, it initializes http2Client.streamsQuota with N available streams, regardless of the number of currently active streams.  This causes it to attempt to exceed the concurrent stream limit, which is forbidden by http://http2.github.io/http2-spec/index.html#rfc.section.5.1.2.  This exacerbates the impact of #261 by provoking servers to send the problematic RST_STREAM frames.

**Comment by iamqizhao** [comment]
Thanks for reporting. This seems an issue. Will have a fix soon.
