### ISSUE TITLE
what's the advantage to accessing request information via context.Context in server endpoint handlers?

### ISSUE THREAD

**Issue by nhooyr** [grpc/grpc-go#2626]
Why was the API designed such that request information like the metadata/remote peer information is accessed via the request context in server endpoint handlers and not a typed parameter? It makes discoverability really difficult as afaik there is no documentation regarding what exactly is available in the context for endpoint handlers.

**Comment by dfawley** [comment]
Those are reasonable concerns, but none of the current team were around when the original API was designed, and it isn't something we're capable of changing at this point.  I don't think there's anything that can be done here.

**Comment by nhooyr** [comment]
is it possible we can at document the various fields available in the context.Context of endpoints somewhere?

**Comment by dfawley** [comment]
Good idea.  Opened #2664 to track.
