### ISSUE TITLE
Keepalive pings are sent every [Time + Timeout] period; not every [Time] period

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#2638]

**Comment by jhump** [comment]
I think this is the root cause for a bug filed against grpcurl, too: https://github.com/fullstorydev/grpcurl/issues/99

**Comment by jhump** [comment]
@dfawley, I take it you are on top of the misattribution of "stale" to all of these and I should be able to just ignore the GH notifications I am getting?

**Comment by dfawley** [comment]
@jhump - Correct.  I am still interested in discussion on #2909, however.  :)

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/pull/3102 fixes the issue on the client side. A similar fix on the server side is required.

**Comment by easwars** [comment]
This is fixed now, on both client and server side.
