### ISSUE TITLE
bug about channel of func (csm *connectivityStateManager) updateState

### ISSUE THREAD

**Issue by liangzhiyang** [grpc/grpc-go#2646]
### version of gRPC
tag  v1.15.0 ~ v1.18.0

in file clientconn.go  , func (csm *connectivityStateManager) updateState(state connectivity.State)
line 355-356
```golang
close(csm.notifyChan) 
csm.notifyChan = nil
```
maybe another goroutine cannot receive msg from csm.notifyChan,   because of csm.notifyChan = nil  immediately after close(csm.notifyChan)。
The result is uncertain

**Comment by lyuxuan** [comment]
A `notifyChan` (type `chan struct{}`) get created when someone wants to be notified when state changes. And `csm.notifyChan` stores a reference to the channel, while the requester also gets passed a reference to the channel. Therefore, `connectivityStateManager` uses the reference it has (as stored in `csm.notifyChan`) to close the channel when state changes. And the requester, listens on the the channel for notification using the reference it gets passed. In other words, `csm.notifyChan` itself is not shared by multiple goroutines, but the value assigned to it (i.e. the chan) is shared by having multiple copies of reference.
