### ISSUE TITLE
The RPC failed with error "code = Unavailable desc = transport is closing"

### ISSUE THREAD

**Issue by liangzhiyang** [grpc/grpc-go#2653]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.15.0
### What version of Go are you using (`go version`)?
1.10
### What operating system (Linux, Windows, …) and version?
linux
### What did you do?
use etcd for balance
like
```golang
        resolver := &naming.GRPCResolver{Client: etcdClient}
	b := grpc.RoundRobin(resolver)
	grpcClient, err = grpc.Dial(
		serviceTarget(target),
		grpc.WithBalancer(b),
		grpc.WithCompressor(grpc.NewGZIPCompressor()),
		grpc.WithDecompressor(grpc.NewGZIPDecompressor()),
		grpc.WithDefaultCallOptions(grpc.FailFast(false)),
		grpc.WithInsecure(),
		grpc.WithBlock(),
		grpc.WithTimeout(time.Second*5),
		grpc.WithUnaryInterceptor(unaryClientInterceptor),
	)
```
Occasionally the RPC failed with error "code = Unavailable desc = transport is closing"

then i open grpc.EnableTracing
get info like
![image](https://user-images.githubusercontent.com/13274315/53224890-35b9ef80-36b1-11e9-82dc-90eec240dec6.png)

why？？？

**Comment by lyuxuan** [comment]
Hi, could you turn on the log, which is more helpful in this case. Thanks.

`GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info your_command`

**Comment by dfawley** [comment]
@liangzhiyang have you had a chance to run again with logging enabled on your client and server?

**Comment by dfawley** [comment]
Please let us know if you are still encountering this problem and have debugging info for us.

**Comment by liangzhiyang** [comment]
@dfawley 
I have solve the problem by add some params  in grpc.NewServer(opt...)
`grpc.KeepaliveParams(keepalive.ServerParameters{
			MaxConnectionIdle: 5 * time.Minute, 
		}`

**Comment by dfawley** [comment]
Yes, that sounds plausible.  If something in the middle is closing the connection then you may need to enable keepalive on either the client or server to keep the connection open (or gracefully close it).
