### ISSUE TITLE
cannot load syscall 

### ISSUE THREAD

**Issue by yinjun622** [grpc/grpc-go#2667]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.17.0

### What version of Go are you using (`go version`)?
go version go1.12 darwin/amd64

### What operating system (Linux, Windows, …) and version?
macos 10.13.6

### What did you do?

build my project:
``CC=$NDK/bin/aarch64-linux-android/bin/aarch64-linux-android-gcc GOOS=android GOARCH=arm64 CGO_ENABLED=1 go build``

error info: 
build google.golang.org/grpc/internal/syscall: cannot load google.golang.org/grpc/internal/syscall: no Go source files

**Comment by yinjun622** [comment]
build by tags linux , it works.
CC=$NDK/bin/aarch64-linux-android/bin/aarch64-linux-android-gcc GOOS=android GOARCH=arm64 CGO_ENABLED=1 go build -tags linux

**Comment by lyuxuan** [comment]
Hi @yinjun622, I was able to build our library with GOOS=andriod without any issue and without the usage of `-tags linux`. Actually, as specified here: https://golang.org/pkg/go/build/

> Using GOOS=android matches build tags and files as for GOOS=linux in addition to android tags and files.

GOOS=andriod should pick up files for linux. 

FYI, I used the most recent andriod ndk: **android-ndk-r19b** with **MacOS 10.13.6** and go version **go1.12 darwin/amd64**. Below is my command to build all grpc packages.

`CC=~/Downloads/android-ndk-r19b/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android28-clang GOOS=android GOARCH=arm64 CGO_ENABLED=1 go build ./...`

Please let us know if you need anymore help with your issue. Thanks!

**Comment by yinjun622** [comment]
@lyuxuan Thx.

**Comment by happyalu** [comment]
I seem to be running into the same issue: 

```go
package main

import (
        "fmt"

        "google.golang.org/grpc"
)

func main() {
        fmt.Println(grpc.SupportPackageIsVersion3)
}
```

go.mod:
```
module x.co/example

go 1.12

require google.golang.org/grpc v1.20.1
```
```
CC=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang GOOS=android GOARCH=arm64 CGO_ENABLED=1 go build
build google.golang.org/grpc/internal/syscall: cannot load google.golang.org/grpc/internal/syscall: no Go source files
```
This is building with android-ndk-r19c, linux (ubuntu 18.04) and `go version go1.12.5 linux/amd64
`
