### ISSUE TITLE
Add CloseSend to server for bidirectional streaming

### ISSUE THREAD

**Issue by SpeedyCoder** [grpc/grpc-go#2668]
In bidirectional streaming a client can call `CloseSend` on the stream object to signal to the server that it won't send more messages. This functionality is not available on the server. I'm not sure if it's possible to add it, but it makes the bidirectional stream asymmetric in the sense that the client is able to signal that it won't send any more messages, whereas the server can't do that.

My use case for this is something like this on the server side
```go
func (s *server) Serve(stream pb.Message_Server) error {
	sCtx := stream.Context()

	ctx, cancel := context.WithCancel(sCtx)
	eg, ctx := errgroup.WithContext(ctx)

	in := make(chan *pb.Message)
	out := make(chan *pb.Message)

	eg.Go(func() error {
		defer cancel()
		for {
			msg, err := stream.Recv()
			if err != nil {
				if err == io.EOF {
					return nil
				}
				return err
			}
			select {
			case in <- msg:
			case <-ctx.Done():
				return nil
			}
		}
	})

	eg.Go(func() error {
		// defer stream.CloseSend() // signal to the client that the server is stopping
		defer cancel()
		for {
			var msg *pb.Message
			select {
			case msg = <-out:
			case <-ctx.Done():
				return nil
			}
			if err := stream.Send(msg); err != nil {
				return err
			}
		}
	})

	eg.Go(func() error {
		defer cancel()
		return s.run(ctx, in, out)
	})

	return eg.Wait()
}
```
So, I want to run 3 goroutines one for receiving messages one for sending messages and one for doing processing in the middle. However when the processing goroutine fails I want to terminate cleanly and make sure the other two goroutines shutdown as well. The issue is that in this setup the receiving goroutine can block on the call to `stream.Recv()` as long as the connection is healthy. With `CloseSend` available on the server stream I could call it when exiting the sending goroutine, then the client that works analogically will initiate shutdown after receiving `io.EOF` and call `stream.CloseSend` as well. This will cause the call to `stream.Recv()` to return `io.EOF` and so all the goroutines will terminate and the function call will return. 

My workaround was not to wait for the receiving goroutine to finish and returning from the function. However that doesn't feel like a clean way to terminate...

**Comment by dfawley** [comment]
A separate `CloseSend` on the server would not be possible to implement without a gRPC wire protocol change.  The way the client implements `CloseSend` is by setting the end stream flag on the stream.  If the server were to do this, it would not be able to subsequently send the trailers for the RPC.

> The issue is that in this setup the receiving goroutine can block on the call to stream.Recv() as long as the connection is healthy.

`stream.Recv()` will return `io.EOF` after the server handler returns - signaling the end of the RPC.  I think your workaround is entirely fine and is the expected way to handle this kind of scenario.

If you need the stream to stay alive, but let the client know the server is done sending messages, that would need to be communicated via your API protocol (e.g. a field in your streaming message to indicate this).

**Comment by SpeedyCoder** [comment]
Ah cool, thank you 👍
