### ISSUE TITLE
Connecting to localhost fails

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-go#2678]
Repro:

1.  Create a server listening on `[::1]:1234`
2.  Create a client that connects to `localhost:1234`
3.  See RPC failure `rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:1234: connect: connection refused"`

This fails with `dns:///localhost:1234` as well.  I am using `grpc.DialContext()`.  I tried to work around this by adding `&grpc.FailFastCallOption{}` call option, but that just causes the RPC to hang.  If the pick-first load balancer is being used, 2 addresses for localhost should come back (IPv4 and IPv6) and at least one of them should be used.

**Comment by lyuxuan** [comment]
Hey @carl-mastrangelo, you can run your program with `GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info` to look into the internal channel/subchannel state changes and errors. Let me know if you find something suspicious or you can just paste the log here. Thanks!

**Comment by carl-mastrangelo** [comment]
@lyuxuan I'll give it a go tonight.  In the mean time, is there a public doc on debugging tools (like the env vars) for gRPC Go?   I wouldn't have known that they are listed on the grpclog page, or that they existed if you hadn't said so.

**Comment by lyuxuan** [comment]
It's actually on our repo's [front page](https://github.com/grpc/grpc-go#faq) and the  debugging [example page](https://github.com/grpc/grpc-go/blob/master/examples/features/debugging/README.md). But probably these are not the most obvious pages that someone will first look at.

**Comment by dfawley** [comment]
@carl-mastrangelo have you had a chance to look at this more?  We suspect the underlying issue is your host's resolver not returning an IPv6 localhost address.

**Comment by carl-mastrangelo** [comment]
@dfawley oh, wow, I thought I pasted the results from my laptop already.  I'll post them as soon as I can.

**Comment by carl-mastrangelo** [comment]
```
$ GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info go run authuser.go '--spec=dns:///localhost:8889' > ~/.token.pb.txt
INFO: 2019/03/14 20:54:46 parsed scheme: "dns"
INFO: 2019/03/14 20:54:46 grpc: failed dns SRV record lookup due to lookup _grpclb._tcp.localhost on 173.230.145.5:53: no such host.
INFO: 2019/03/14 20:54:46 grpc: failed dns TXT record lookup due to lookup localhost on 173.230.145.5:53: no such host.
INFO: 2019/03/14 20:54:46 ccResolverWrapper: got new service config: 
INFO: 2019/03/14 20:54:46 ccResolverWrapper: sending new addresses to cc: [{127.0.0.1:8889 0  <nil>}]
INFO: 2019/03/14 20:54:46 ClientConn switching balancer to "pick_first"
INFO: 2019/03/14 20:54:46 pickfirstBalancer: HandleSubConnStateChange: 0xc0000872c0, CONNECTING
WARNING: 2019/03/14 20:54:46 grpc: addrConn.createTransport failed to connect to {127.0.0.1:8889 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:8889: connect: connection refused". Reconnecting...
INFO: 2019/03/14 20:54:46 pickfirstBalancer: HandleSubConnStateChange: 0xc0000872c0, TRANSIENT_FAILURE
INFO: 2019/03/14 20:54:46 grpc: failed dns SRV record lookup due to lookup _grpclb._tcp.localhost on 173.230.145.5:53: no such host.
INFO: 2019/03/14 20:54:46 grpc: failed dns TXT record lookup due to lookup localhost on 173.230.145.5:53: no such host.
INFO: 2019/03/14 20:54:46 ccResolverWrapper: got new service config: 
INFO: 2019/03/14 20:54:46 ccResolverWrapper: sending new addresses to cc: [{127.0.0.1:8889 0  <nil>}]
INFO: 2019/03/14 20:54:47 pickfirstBalancer: HandleSubConnStateChange: 0xc0000872c0, CONNECTING
INFO: 2019/03/14 20:54:47 pickfirstBalancer: HandleSubConnStateChange: 0xc0000872c0, TRANSIENT_FAILURE
WARNING: 2019/03/14 20:54:47 grpc: addrConn.createTransport failed to connect to {127.0.0.1:8889 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:8889: connect: connection refused". Reconnecting...
INFO: 2019/03/14 20:54:47 grpc: failed dns SRV record lookup due to lookup _grpclb._tcp.localhost on 173.230.145.5:53: no such host.
INFO: 2019/03/14 20:54:47 grpc: failed dns TXT record lookup due to lookup localhost on 173.230.145.5:53: no such host.
INFO: 2019/03/14 20:54:47 ccResolverWrapper: got new service config: 
INFO: 2019/03/14 20:54:47 ccResolverWrapper: sending new addresses to cc: [{127.0.0.1:8889 0  <nil>}]
INFO: 2019/03/14 20:54:48 pickfirstBalancer: HandleSubConnStateChange: 0xc0000872c0, CONNECTING
INFO: 2019/03/14 20:54:48 pickfirstBalancer: HandleSubConnStateChange: 0xc0000872c0, TRANSIENT_FAILURE
WARNING: 2019/03/14 20:54:48 grpc: addrConn.createTransport failed to connect to {127.0.0.1:8889 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:8889: connect: connection refused". Reconnecting...
INFO: 2019/03/14 20:54:48 grpc: failed dns SRV record lookup due to lookup _grpclb._tcp.localhost on 173.230.145.5:53: no such host.
INFO: 2019/03/14 20:54:48 grpc: failed dns TXT record lookup due to lookup localhost on 173.230.145.5:53: no such host.
INFO: 2019/03/14 20:54:48 ccResolverWrapper: got new service config: 
INFO: 2019/03/14 20:54:48 ccResolverWrapper: sending new addresses to cc: [{127.0.0.1:8889 0  <nil>}]
INFO: 2019/03/14 20:54:51 pickfirstBalancer: HandleSubConnStateChange: 0xc0000872c0, CONNECTING
WARNING: 2019/03/14 20:54:51 grpc: addrConn.createTransport failed to connect to {127.0.0.1:8889 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:8889: connect: connection refused". Reconnecting...
INFO: 2019/03/14 20:54:51 pickfirstBalancer: HandleSubConnStateChange: 0xc0000872c0, TRANSIENT_FAILURE
INFO: 2019/03/14 20:54:51 grpc: failed dns SRV record lookup due to lookup _grpclb._tcp.localhost on 173.230.145.5:53: no such host.
INFO: 2019/03/14 20:54:51 grpc: failed dns TXT record lookup due to lookup localhost on 173.230.145.5:53: no such host.
INFO: 2019/03/14 20:54:51 ccResolverWrapper: got new service config: 
INFO: 2019/03/14 20:54:51 ccResolverWrapper: sending new addresses to cc: [{127.0.0.1:8889 0  <nil>}]

```

**Comment by dfawley** [comment]
This is as suspected then.  The name resolver is turning `localhost` into `127.0.0.1` and does not include `[::1]`.  If you change your target to `[::1]`, it should work.  As for why your system is not including an IPv6 localhost address, I don't know.  You could try running with `GODEBUG=netdns=cgo` in your environment and see if that makes any difference.  Another idea is we could try using `LookupIPAddr` instead of `LookupHost` in our resolver.  They're supposed to be identical (aside from return type), but the documentation of `LookupIPAddr` explicitly mentions IPv6, while `LookupHost` does not, which is odd.

**Comment by carl-mastrangelo** [comment]
@dfawley thanks for the suggestions.  I tried with `GODEBUG=netdns=cgo` but it still failed to resolve the IPv6 address.   

The LookupIPAddr looks promising.

**Comment by carl-mastrangelo** [comment]
Well...   I have some good news.  The reason localhost connection fails is because of the `/etc/hosts` file, which is subtly wrong:

```
127.0.0.1	localhost
127.0.1.1	ubuntu

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
```

Why or how this got into place I am not sure, but sorry for the false alarm.

**Comment by dfawley** [comment]
Glad you were able to solve the problem!
