### ISSUE TITLE
Server shutdown, client see different errors

### ISSUE THREAD

**Issue by BlueStalker** [grpc/grpc-go#2679]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.19.0
### What version of Go are you using (`go version`)?
go version go1.11.4 linux/amd64
### What operating system (Linux, Windows, …) and version?
Linux, 4.14.97-90.72.amzn2.x86_64
### What did you do?
If possible, provide a recipe for reproducing the error.

It's bidi stream, and the client is do thing just like: (I open multiple stream inside the same go client).
```
go func() {
    for {
      in, err := RequestStream.Recv()
    }
  }()
```
and server side is java, using 1.17.1, and the server side code,it just normally send stuffs into stream, and everthing is ok, and when I do engine.shutdown() in server side, 
I see the above code received different kinds of err, some of them is 
```
rpc error: code = Unavailable desc = transport is closing
```
and some are:
```
rpc error: code = Canceled desc = context canceled,
```

and In my go code, I didn't seem to do cancel to the stream, why I got some cancel errors?

**Comment by Astone-Chou** [comment]
`server.Stop()`  will cancel request process by using context.Context

**Comment by Astone-Chou** [comment]
`transport/http2_server.go` maybe what u are looking for

**Comment by BlueStalker** [comment]
my server grpc is in java, and I am using engine.shutdown() function to shutdown the server.
And it is confusing me that why some of the stream is seeing Unavailable, and some is seeing cancel, this depends on what?

**Comment by lyuxuan** [comment]
Hi @BlueStalker, can you file this issue in the [grpc-java repo](https://github.com/grpc/grpc-java). It depends on what java server does when `engine.shutdown()` is called. I believe the behavior you saw depends on timing, but I don't have the java implementation knowledge to explain here. Thank you. And it will be great if you can update this bug once you get your answer.

**Comment by lyuxuan** [comment]
It seems that the original issue has been answered in the java repo, closing this issue now.
