### ISSUE TITLE
can net/rpc call for long running method?

### ISSUE THREAD

**Issue by kaixinbuyu** [grpc/grpc-go#2682]
`client:call-server's-methodA------though net/rpc---------->server:methodA(){running about 1-2hours}`

I have find many examples,all of them are rpc call on sample,small time(<50ms) method.

I my case,can net/rpc call for long running method,and wait the result?

**Comment by lyuxuan** [comment]
Absolutely. As long as your RPC timeout is set to be longer than the method running time, the RPC will be alive until the server handler returns. Please give it a try, and let us know if you encounter any problem. Thanks!

**Comment by kaixinbuyu** [comment]
Thank you!I'll try it at once!
