### ISSUE TITLE
Question: can header/trailer propagate

### ISSUE THREAD

**Issue by elvizlai** [grpc/grpc-go#2704]
Can header/trailer propagate?

example:

client <------ svc1 <---header---svc2

when svc1 resp client, header from svc2 is missing.

**Comment by menghanl** [comment]
It doesn't happen automatically (to avoid leaking information accidentally). You will need to manually explicitly forward (in svc1, read headers from svc2, and send them to client).

**Comment by dfawley** [comment]
Let us know if you have any further questions.
