### ISSUE TITLE
Slow response time from the server

### ISSUE THREAD

**Issue by TheFunnySunny** [grpc/grpc-go#2705]
Hello! 
I have created a simple Go server (well actually it is an example server but build from the beginning) and I have an issiue with it. Everything is provided here:[my stackoverflow question](https://stackoverflow.com/questions/55123018/grpc-server-long-response-times-over-ethernet)
### my grpc version:
  grpc versiom 1.19

### My go version is:
  go version go1.12 windows/386

### What operating system (Linux, Windows, …) and version?
Wyndows 10 64bit

### What did you do?
Description of my problem: [my stackoverflow question](https://stackoverflow.com/questions/55123018/grpc-server-long-response-times-over-ethernet)

### What did you expect to see?
Well I expected to see performance that is comparable with other microservices I have built in that time (less than 1ms for response).
### What did you see instead?
Connecting to Go server over ethernet is about 40 times slower than to a server written in C++, C# or RUST

**Comment by dfawley** [comment]
Can you provide your client code?  Are you testing only a go client with the go server or clients from another language or all languages to the go server?

40ms for a trivial RPC over a local network is not expected.

**Comment by TheFunnySunny** [comment]
Yeah I can, actually I did already, it is before **What did you expect to see?** in the hyperlink to my stackoverflow topic. Also it is here: https://stackoverflow.com/questions/55123018/grpc-server-long-response-times-over-ethernet

**Comment by dfawley** [comment]
@TheFunnySunny the only code I see in stackoverflow is for the server and not the client.  I'm interested in seeing what's going on in the client as well, since the server looks very simple.

**Comment by TheFunnySunny** [comment]
My bad, sorry for that. My client was written in C# (.NET framework) and the code for that is right here:

`  using System;
using Grpc.Core;
using Talk;
using System.Diagnostics;
using System.Collections.Generic;
namespace Client
{
    class Program
    {
        static void Main(string[] args)
        {
            Stopwatch Watch = new Stopwatch();

            int TESTCASES = 10000;
            string address;
            string port;
            Console.WriteLine("Watch frequency is: " + Stopwatch.Frequency);

            Console.WriteLine("Specify server address (in form of 0.0.0.0) : ");
            address = Console.ReadLine();
            Console.WriteLine("Specify server port(without :) : ");
            port = Console.ReadLine();

            Channel channel = new Channel(address + ":" + port, ChannelCredentials.Insecure);
            var client = new Greeter.GreeterClient(channel);
            HelloReply reply;

            ulong min = ulong.MaxValue, max = 0, mean = 0;
            double minms = double.MaxValue, maxms = 0, meanms = 0;
            List<ulong> times = new List<ulong>();
            List<double> timesms = new List<double>();

            String user = "I";
            long ans;
            for (int i = 0; i < TESTCASES; i++)
            {
                Watch.Reset();
                Watch.Start();
                reply = client.SayHello(new HelloRequest { Name = user });
                Watch.Stop();
                ans = Watch.ElapsedTicks;
                 times.Add((ulong)(ans));
                 timesms.Add(Watch.Elapsed.TotalMilliseconds);               
            }
            for(int i = 1; i < TESTCASES; i++)
            {
                if(times[i] < min)
                {
                    min = times[i];
                }
                if(timesms[i] < minms)
                {
                    minms = timesms[i];
                }
                if (times[i] > max)
                {
                    max = times[i];
                }
                if(timesms[i] > maxms)
                {
                    maxms = timesms[i];
                }
                mean += times[i];
                meanms += timesms[i];
            }
            mean /= (uint)(TESTCASES - 1);
            meanms /= (double)(TESTCASES - 1);
            //divide ticks by that to convert them to ms
            Console.WriteLine("Connection time: " + times[0] + "\t\t(" + timesms[0] + "ms)");            
            Console.WriteLine("Max value: " + max + "\t\t(" + maxms + "ms)");           
            Console.WriteLine("Min value: " + min + "\t\t(" + minms + "ms)");            
            Console.WriteLine("Average value: " + mean + "\t\t(" + meanms + "ms)");

            min = ulong.MaxValue;
            max = 0;
            mean = 0;
            minms = double.MaxValue;
            maxms = 0;
            meanms = 0;
            //calculate without high time jumps
            mean += times[1];
            meanms += timesms[1];
            int ok_cntr = 1;
            for (int i = 2; i < TESTCASES; i++)
            {
                if (times[i] <= ((mean / Convert.ToUInt64(ok_cntr)) * 10))
                {
                    ok_cntr++;
                    mean += times[i];
                    meanms += timesms[i];
                    if (times[i] < min)
                    {
                        min = times[i];
                    }
                    if (timesms[i] < minms)
                    {
                        minms = timesms[i];
                    }
                    if (times[i] > max)
                    {
                        max = times[i];
                    }
                    if (timesms[i] > maxms)
                    {
                        maxms = timesms[i];
                    }
                }
            }
            mean /= (uint)(ok_cntr);
            meanms /= (double)(ok_cntr);
            Console.WriteLine("Times without high time jumps: ");
            Console.WriteLine("Connection time: " + times[0] + "\t\t(" + timesms[0] + "ms)");
            Console.WriteLine("Max value: " + max + "\t\t(" + maxms + "ms)");
            Console.WriteLine("Min value: " + min + "\t\t(" + minms + "ms)");
            Console.WriteLine("Average value: " + mean + "\t\t(" + meanms + "ms)");

            Console.WriteLine("Press any key to exit...");
            Console.ReadKey();
        }           
    }
}
 `

**Comment by TheFunnySunny** [comment]
So what do You think? is that something on my side?

**Comment by dfawley** [comment]
@TheFunnySunny - The client looks pretty reasonable to me.  Can you try running the server with debugging options set in your environment and provide the output:

```
$ GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info <your_go_server_command>
```

On the client-side, please also try setting:

```
$ GRPC_VERBOSITY=DEBUG GRPC_TRACE=connectivity_state,client_channel_call <your_c#_client_command>
```

**Comment by TheFunnySunny** [comment]
Uhhmm, sorry but where do I put these commands? In the code or in PS somehoew??

**Comment by dfawley** [comment]
They need to be set in your environment, so you would usually set them on the command-line either before or on the same line where you are running your client/server commands.

**Comment by TheFunnySunny** [comment]
Okay so I have never done that and obviosly might do everything wrong but I set these options in PS like that: `set GRPC_GO_LOG_VERBOSITY_LEVEL=99` and so on but after running both client and server nothing is showing up.  I have also tried setting them as environment variables but that was not working either. What can I do to get it working on windows? 
There is something about **Channelz** [here](https://github.com/grpc/grpc-go/tree/master/examples/features/debugging) so maybe I can use that? But I know there has to be a better and faster way

**Comment by dfawley** [comment]
If you are using powershell, try something like this:

```
PS C:\...> $Env:GRPC_GO_LOG_VERBOSITY_LEVEL = "99"
PS C:\...> $Env:GRPC_GO_LOG_SEVERITY_LEVEL = "info"
PS C:\...> <run server>


PS C:\...> $Env:GRPC_VERBOSITY = "DEBUG"
PS C:\...> $Env:GRPC_TRACE = "connectivity_state,client_channel_call"
PS C:\...> <run client>
```

I'm not much of a Windows user, so I'm not sure if this is right.  :smile:

**Comment by dfawley** [comment]
@TheFunnySunny have you had a chance to collect debug logs?

**Comment by TheFunnySunny** [comment]
ohh I'm so sorry for not posting the rest of the debug logs. I will do that tomorrow asap. I have tested it acutally and it worked out for me but only on the client side. I do not remember what it was exacly but I will show you tomorrow

**Comment by TheFunnySunny** [comment]
`CLIENT OUTPUT:

I0405 14:19:13.019061 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.071958 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.103487 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.150364 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.187935 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.234810 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.287835 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.319282 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.372202 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.403731 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.450606 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.488481 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.535358 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.588303 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.619606 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.672738 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.704267 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.751142 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.804102 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.835585 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.888632 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.920060 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:13.973031 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.004561 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.051436 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.089367 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.136242 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.189285 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.220684 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.273643 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.305172 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.352047 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.389595 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.436470 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.489665 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.536541 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.573846 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.620998 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.667875 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
I0405 14:19:14.705482 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:81: CONWATCH: 00C7DA40 request_router: get READY
Connection time: 4582606                (320.055ms)
Max value: 5398274              (377.0223ms)
Min value: 43449                (3.0345ms)
Average value: 612137           (42.7524153315333ms)
Times without high time jumps:
Connection time: 4582606                (320.055ms)
Max value: 5398274              (377.0223ms)
Min value: 43449                (3.0345ms)
Average value: 612102           (42.7499996249368ms)
Press any key to exit...
 I0405 14:20:05.355284 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:164: SET: 00C7DA40 request_router: READY --> SHUTDOWN [disconnect] error=00C7A4A0 {"created":"@1554499205.366000000","description":"Channel Destroyed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\surface\channel.cc","file_line":471}
I0405 14:20:05.371043 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:164: SET: 00CCD628 pick_first: READY --> SHUTDOWN [shutdown] error=00C7A1A0 {"created":"@1554499205.372000000","description":"Channel shutdown","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\ext\filters\client_channel\lb_policy\pick_first\pick_first.cc","file_line":193}
I0405 14:20:05.371043 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:190: NOTIFY: 00CCD628 pick_first: 00CC1CE0
I0405 14:20:05.371043 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:113: CONWATCH: 00CCD780 subchannel: unsubscribe notify=00CC1C4C
I0405 14:20:05.371043 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:164: SET: 00CD4E44 client_transport: READY --> SHUTDOWN [close_transport] error=00C7A120 {"created":"@1554499205.376000000","description":"Transport destroyed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\transport\chttp2_transport.cc","file_line":561,"grpc_status":14,"occurred_during_write":0}
I0405 14:20:05.371043 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\transport\connectivity_state.cc:190: NOTIFY: 00CD4E44 client_transport: 00C90404


SERVER:
INFO: 2019/04/05 21:26:41 CPU time info is unavailable on non-linux or appengine environment.
2019/04/05 21:26:41 Server listening on: [::]:50051
INFO: 2019/04/05 23:20:06 transport: loopyWriter.run returning. connection error: desc = "transport is closing"`

this is what I get. I have not inserted the whole output of the client because everything at the top was the same but with a different time and thre is 10k of them so, yeah. On the server I get that message so unfortunately it did not show any time

**Comment by dfawley** [comment]
Nothing here looks suspicious.  Are you still seeing these problems or have you solved/worked around them?
