### ISSUE TITLE
grpclb contributes a lot of log spam

### ISSUE THREAD

**Issue by Capstan** [grpc/grpc-go#2709]
Suggest the `grpclog.Infof`s under balancer/grpclb become `grpclog.V(2).Infof`s wholesale, or at least audited for utility.

As it stands, we see a _lot_ of log entries like the following, making it very difficult to isolate real issues:

```
I0321 18:25:37.270095  206490 grpclb_remote_balancer.go:44] lbBalancer: processing server list: servers:<ip_address:"redacted" port:redacted load_balance_token:"redacted" >…many lines removed…
I0321 18:25:37.270146  206490 grpclb_remote_balancer.go:77] lbBalancer: server list entry[0]: ipStr:|[redacted]|, port:|redacted|, load balancer token:|redacted|
```

/cc @carl-mastrangelo

**Comment by Capstan** [comment]
Ugh, and can we make `grpclog.V()` return a typed `bool` that implements `Infof` etc. so the syntax `grpclog.V(2).Infof` just works?

**Comment by carl-mastrangelo** [comment]
@menghanl
