### ISSUE TITLE
Balance Wrapper writes excess new line

### ISSUE THREAD

**Issue by breznik** [grpc/grpc-go#2716]
Please answer these questions before submitting your issue.

Was trying to figure out why I have some random newlines in my logs...traced it back to:
https://github.com/grpc/grpc-go/blob/master/balancer_v1_wrapper.go#L123

Which seems to include an extra `\n`. I don't know if there's a good reason for the extra newline in the log statement, but I haven't seen other grpc-go code do the same. Hoping it can be removed?

**Comment by canguler** [comment]
Hey @breznik,

Do you mind sending a PR to fix this?
