### ISSUE TITLE
There is no tracking information for the current branch.

### ISSUE THREAD

**Issue by emparanimrod** [grpc/grpc-go#2717]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.19.1
### What version of Go are you using (`go version`)?
1.12.1
### What operating system (Linux, Windows, …) and version?
Windows
### What did you do?
If possible, provide a recipe for reproducing the error.
I tried adding the package via
$go get -u google.golang.org/grpc

### What did you expect to see?
A successful install maybe
### What did you see instead?

 cd C:\Users\25472\go\src\google.golang.org\genproto; git pull --ff-only        There is no tracking information for the current branch.                         Please specify which branch you want to merge with.                              See git-pull(1) for details.                                                                                                                                          git pull                                                                                                                                      If you wish to set tracking information for this branch you can do so with:                                                                                           git branch --set-upstream-to=origin/ master                                                                                                           package google.golang.org/genproto/googleapis/rpc/status: exit status 1

**Comment by menghanl** [comment]
One guess is your local genproto copy is bad.
Try to `cd C:\Users\25472\go\src\google.golang.org\genproto` and `git status`.
If you didn't make any changes there on purpose, it should be safe to all the unsubmitted changes there.

**Comment by dfawley** [comment]
@emparanimrod are you still having any problems related to this?

**Comment by emparanimrod** [comment]
I went into the folder and manually deleted genproto, then it worked. But I tried again just to check and I am still getting the same error right now

**Comment by dfawley** [comment]
@emparanimrod when you tried again just now, did you again try deleting `genproto`?  Does that fix it?

You might also want to try `go get -u google.golang.org/genproto` by itself to see if it gives the same errors.

This is almost certainly a configuration issue with your system and not a grpc-go problem.  We can help you debug this a little bit, but I don't think there's much more we can do, unfortunately.

One last note: I would recommend NOT developing in your `GOPATH` anymore, if possible, and using Go's module support (in v1.11 and later) instead.  Or set `GO1111MODULE=on` in your environment to avoid moving your files.  Dependency management is much more predictable that way, and you never have to run `go get` again if you do it right (`go build` and `go test` will automatically download dependencies at the appropriate versions).
