### ISSUE TITLE
Is gRPC compliant with FIPS 140-2 from a SSL/TLS perspective 

### ISSUE THREAD

**Issue by devanshah2** [grpc/grpc-go#2721]
Based on the base Golang it looks like it is not compliant according to: https://github.com/golang/go/issues/21734

The recommendation is to use BoringCrypto: https://github.com/golang/go/blob/dev.boringcrypto/README.boringcrypto.md which can be used by using golang from the dev.boringcrypto branch as the base.

Since FIPS 140-2 also applies to the SSL/TLS communication between a gRPC client and server, is gRPC complaint with FIPS from a SSL/TLS communication perspective. When the gRPC server is created using:

```
creds, _ := credentials.NewServerTLSFromFile(config.CertPEMPath, config.CertKEYPath)

gRPCServer := grpc.NewServer(
    grpc.Creds(creds),
)  
```

Both config.CertPEMPath, config.CertKEYPath are generated using openssl. 

When gRPC establishes the connection would this be FIPS 140-2 compliant?

**Comment by dfawley** [comment]
> Based on the base Golang it looks like it is not compliant according to: golang/go#21734

I agree.

> When gRPC establishes the connection would this be FIPS 140-2 compliant?

Based on my reading of the [README](https://github.com/golang/go/blob/dev.boringcrypto/README.boringcrypto.md), it's possible, but with the same caveat as that in the README:

>> To be clear, we are not making any statements or representations about the suitability of this code in relation to the FIPS 140-2 standard

`credentials.NewServerTLSFromFile` uses the golang `tls` library for the actual crypto implementation, so if the `dev.boringcrypto` branch updates all of the `tls` library directly to use boringssl, then grpc-go would transitively pick that up.  Whether this would be considered FIPS 140-2 compliant, I am not sure, but it would be the case that we would be using the boringcrypto library.

**Comment by devanshah2** [comment]
@dfawley Thanks. Looks like to be FIPS 140-2 will need to use go from `dev.boringcrypto`. Thanks once again.
