### ISSUE TITLE
What if the issuing certificate authority is not known to the client in Mutual Authentication ?

### ISSUE THREAD

**Issue by ruchika93** [grpc/grpc-go#2722]
I am trying to build a secure GRPC server/client connection such that the ca.crt (the  Certificate Authority trust certificate) is not known to the client. How does one go about doing a Mutual Authentication in this case ? How does the client side code look ?

For example, in the case of grpc-java, one can provide a properly configured SslContext or SSLSocketFactory to the NettyChannelBuilder or OkHttpChannelBuilder, respectively.
Link for the same: https://grpc.io/docs/guides/auth.html

**Comment by menghanl** [comment]
You can create transport credentials with [`NewTLS`](https://godoc.org/google.golang.org/grpc/credentials#NewTLS) from `tls.Config`, where you can set your list of RootCAs.

**Comment by ruchika93** [comment]
So, I made use of the pem.decode() to extract the RootCA from the chain of certificates.
Solved!
