### ISSUE TITLE
Server doesn't respond any requests

### ISSUE THREAD

**Issue by CMogilko** [grpc/grpc-go#2730]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
master (ef9bac260455a9a77b29a082f5f7ee71b3d74dad)

### What version of Go are you using (`go version`)?
1.11.5

### What operating system (Linux, Windows, …) and version?
Linux CentOS 7.6

### What did you do?
We have development servers, where grpc service works 24/7. Roughly speaking once per week one of grpc services stops to serve requests. Clients connect and never get response. No matter what service method it is.

We have stats collector, setted `WithStatsHandler()`, it has method:
```go
func (c *collectorImpl) TagRPC(ctx context.Context, rpcTagInfo *grpc_stats.RPCTagInfo) context.Context {
   c.logger.Info("Request handling started")
   return ctx
}

func (c *collectorImpl) HandleConn(ctx context.Context, connStats grpc_stats.ConnStats) {
   switch connStats.(type) {
   case *grpc_stats.ConnBegin:
      c.logger.Debug("Connection has been established")
   }
}
```
And service method:
```go
func (a *Api) DoSmth(ctx context.Context, request *server.DoSmthRequest) (*server.DoSmthResponse, error) {
   a.logger.Info("DoSmth invoked")
   return &server.DoSmthResponse{}, nil
}
```
This service can works fine whole week, but then something happens and service stops processing requests. Only restart helps.

### What did you expect to see?
I expect get response and see these lines in log:
```
Connection has been established
Request handling started
DoSmth invoked
```

### What did you see instead?
I see only these lines
```
Connection has been established
Request handling started
```
and never get response.
I wasn't able to figure out how to trigger this situation or what is wrong.

**Comment by dfawley** [comment]
Please enable debug logging on your client and server and let us know what you find: `GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info`

**Comment by dfawley** [comment]
@CMogilko have you been able to collect any debug logs?

**Comment by CMogilko** [comment]
@dfawley hi, not yet, only a few days ago I could enable debug logs on all the services. I think may be next week I will able to reproduce this situation. It's a quite rare.

**Comment by dfawley** [comment]
@CMogilko is this still happening?  If so, please provide debug logs, otherwise we will need to close it until you can gather more information.

**Comment by CMogilko** [comment]
@dfawley it happened once, but I wasn't able to gather server logs due to some admin issues. Okay, I will reopen issue if I would have more logs.
