### ISSUE TITLE
Gracefully switch balancers

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#2731]
When switching balancers, we currently `Close` the old balancer, but keep using its `Pick` method.  Also, we do not update the balancer when the state of its subconns change.  We should keep using the old balancer more fully until the new balancer indicates it is ready.

**Comment by menghanl** [comment]
The first step is to stop using the picker after balancer is closed.
The fix for real graceful switch can happen later.

**Comment by dfawley** [comment]
Fixed by #5285
