### ISSUE TITLE
Should I add backpressure on stream sender side?

### ISSUE THREAD

**Issue by pdaures** [grpc/grpc-go#2747]
Hi, 
I have a streaming application using Grpc streaming, potentially sending data to 100s of customers at the same time.

My question is: before calling stream.Send(...), should I implement my own backpressure mechanism to avoid to block the sender if one of my receiver is slow, or is it taken care of by GRPC stream implementation?

My implementation currently looks like on the stream sender side:

```go
var mu sync.RWMutex
var subscriberChans []chan *Event

// when sending a new event, create a new copy for each subscriber
func Send(evt *Event){
   mu.Rlock()
   for _,ch := range subscriberChans {
      // check if the channel is full or not (backpressure mechanism)
       select {
           case ch <- evt:
           // ok
           default:
           // apply backpressure
       }
   }
   mu.RUnlock()
}


func (s *streamer) Stream(req *StreamRequest, stream Stream_StreamServer) error {
  // create a new channel to receive events and register it to the list of subscriber channels
  ch := make(chan *Event, 1024) 
  mu.Lock()
  subscriberChans = append(subscriberChans, ch)
  mu.Unlock()

   // whenever there is a new message, send it right away
   for msg := range ch {
     err :=  stream.Send(msg)
     // ....
   }
}
```

Can I remove the select from this piece of code and expect stream.Send(...) to not block and take care of dropping messages if necessary?
Thanks!

**Comment by menghanl** [comment]
`stream.Send` won't drop messages. `Send` blocks until the message is scheduled to be sent, and after that there will be no way to drop the message. `Send` calls must be synchronized.

As part of the broadcasting, you will need something (for example the channel you use), to pass the `Event` to each `stream.Send()` anyway. So I think your code makes sense.

I didn't fully understand what you mean by "apply backpressure".
If all the events need to be sent to all subscribers, there has to be a mechanism to queue the events when the previous `Send` is still pending.
If only the most up-to-date events need to be sent, a channel with buffer size one should be sufficient.

**Comment by pdaures** [comment]
Thank you very much for taking the time to answer.
