### ISSUE TITLE
DNS resolver: configurable frequency, SRV and TXT lookups via authority URL

### ISSUE THREAD

**Issue by rantav** [grpc/grpc-go#2751]
### Use case(s) - what problem will this feature solve?
When using the DNS resolver it's impossible to configure the frequency of lookups.   
The frequency is 30 minutes; what we need is 30 seconds or so (configurable).   
We load balance using DNS and during deployment servers go down and up and so we want the grpc client to be able to notice these updates in a timely manner, 30 minutes is way too long.  Other means (such as Envoy, Consul agent etc) are valid options but right now we want to stick to plain old DNS. 

On top of that we want a way to disable the SRV and the TXT queries, mainly for efficiency (if we query every 30 seconds we want the bare minimum, only A lookups, that's all). 

I know this topic had been discussed plenty before, a few points of reference: 
https://github.com/grpc/grpc-go/issues/1663
https://github.com/grpc/grpc-go/issues/2279
https://github.com/grpc/grpc-go/issues/2306
https://github.com/grpc/grpc-go/issues/1998

And I know that in the past there had been objection due to efficiency concerns (running SRV lookup and then for each result an A lookup and then TXT lookup, every 30 seconds could result in considerable load on the DNS server) therefore I bundle my suggestion to configure all three: `minFreq`, `lookupSRV` and `lookupTXT` 

### Proposed Solution
The suggestion is to allow URL parameters to the _authority_ section which would allow additional configuration, here's an example (conforming to [naming](https://github.com/grpc/grpc/blob/master/doc/naming.md))

```
dns://127.0.0.1:8600?lookupSRV=0&lookupTXT=0&refreshRate=30/endpoint.service.consul.:8080
```

Where in this example

`127.0.0.1:8600?lookupSRV=0&lookupTXT=0&refreshRate=30` the entire authority section
`127.0.0.1` is the IP of the DNS server
`8600` is the DNS server port (default is 53)
`lookupSRV=0` disables SRV records lookups
`lookupTXT=0` disables TXT records lookup
`refreshRate=30` configures the refresh frequency to 30 seconds

`endpoint.service.consul.` is the host to lookup at the DNS server. This name returns zero or more A records. 
`8080` is the service port (when disabling SRV lookups we need to specify the port) 

### Alternatives Considered
Right now there's an option to disable the TXT lookup, with `resolver.BuildOption.DisableServiceConfig` but there's no way to disable SRV lookups or to configure the refresh frequency via the BuildOption.  
To be honest, I haven't figured out how as a grpc client I'm able to access and configure the BuildOption, but if it's something that's supposed to be accessible to gRPC clients (and I just missed it) then an alternative solution might be to add those two options to `BuildOption`. If we don't, then there would be two ways to disable TXT lookups and that's less than ideal

### Additional Context

I know others have been told "your requirements are unique, you should build your own resolver", I can do that. But I thought it's worth checking if there's more common interest that I could contribute this back, e.g. work on the mainline DNS resolver.  

I'm happy to send a PR if so.

**Comment by dfawley** [comment]
This may be somewhat related to https://github.com/grpc/grpc/issues/12295, although this is requesting some additional features.  Anything like this would need to be done grpc-wide, not just in grpc-go - would you mind filing an issue in the main grpc repo to propose/discuss this (https://github.com/grpc/grpc/issues/new)?  Thanks!

**Comment by rantav** [comment]
Done, although I'm not sure how to mark it as a **feature request** 

https://github.com/grpc/grpc/issues/18743

**Comment by dfawley** [comment]
Let's close this for now since it's being handled in the grpc/grpc repo (https://github.com/grpc/grpc/issues/12295).
