### ISSUE TITLE
no body fixed this? get grpc code error?

### ISSUE THREAD

**Issue by apptut** [grpc/grpc-go#2761]
when I run try grpc code use golang through the document but not work?
```bash
go get google.golang.org/grpc
package google.golang.org/grpc: unrecognized import path "google.golang.org/grpc" (https fetch: Get https://google.golang.org/grpc?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
```
Anybody can fixed that?

**Comment by dfawley** [comment]
Are you trying to access from China?  If so, golang.org is blocked.  This is a problem for all of the "extended standard" packages in `golang.org/x`, too.  One solution is to set up a VPN.  There are other workarounds - I'll add something to our FAQ on our main page soon.

**Comment by dfawley** [comment]
I've updated our FAQ; please take a look and let us know if you still have problems.
