### ISSUE TITLE
grpc-go is now depends on gogo/protobuf instead of golang/protobuf?

### ISSUE THREAD

**Issue by S-YOU** [grpc/grpc-go#2769]
grpc-go is now depends on gogo/protobuf instead of golang/protobuf.
Is that intentional changes?

**Comment by menghanl** [comment]
The gogo/protobuf dependency is introduced by the [xds balancer](https://github.com/grpc/grpc-go/tree/master/balancer/xds), which now depends on the generated code from [envoyproxy/go-control-plane](https://github.com/envoyproxy/go-control-plane).

#2750 will remove this dependency and also solve other xds proto related problems.

Is it causing any problems for you?

**Comment by shuya-takano** [comment]
gogo/protobuf is not an official library as far as I understand, so I am a little worried about the compatibility for future versions.

**Comment by menghanl** [comment]
AFAIK, gogo/protobuf is quite stable.
Also, I think as long as you don't directly depend on gogo/protobuf, gRPC depending on gogo/protobuf shouldn't affect you, as non of those details is exported in gRPC's APIs.

With that all being said, the dependency has been removed in #2750, and is backported to 1.12.1. Closing this issue now. Please reply if you have further questions.
