### ISSUE TITLE
Better documentation and examples around gRPC health checks

### ISSUE THREAD

**Issue by johanbrandhorst** [grpc/grpc-go#2770]
### Use case(s) - what problem will this feature solve?

Make it easier for users to use gRPC for health checks of their applications.

### Proposed Solution

Create an example in the examples directory.

### Alternatives Considered

Adding health documentation to the documentation directory.

### Additional Context

You've done a great job of adding new examples and documentation, but health checking is still lacking an example implementation.

https://github.com/grpc/grpc-go/issues/448 was raised and closed regarding the documentation, so I don't think we necessarily need anything better than that, but it would be nice with an example implementation.

**Comment by johanbrandhorst** [comment]
Still a problem

**Comment by darmawan01** [comment]
same problem here, how you fix this @johanbrandhorst ?

**Comment by johanbrandhorst** [comment]
I'm not the best person to ask, since I raised this issue. Hopefully the contributors can provide a good example in time, but for now I think you have to look at the implementation.

**Comment by mjpitz** [comment]
@dfawley If no one has started on this, I can pick this up and put together an `example`. I already have a couple that I could reference.

**Comment by dfawley** [comment]
@mjpitz as far as I'm aware nobody is working on this.  Thanks for offering to help! 
 Something in `grpc/examples/features/health` would be great.

Also note that things have changed since #448 many years ago.  We now have implemented https://github.com/grpc/proposal/blob/master/A17-client-side-health-checking.md so clients are able to take advantage of health checks provided by the server more transparently.

**Comment by mjpitz** [comment]
Thats where I was looking. Good to know about A17. Wasn't aware that had landed. I'll need to dig up and example or two to figure out how that can be leveraged, but definitely good to know!

**Comment by mjpitz** [comment]
Alright, I've got a client and server implemented demonstrating use of both `Check` and `Watch`. Just need to work on the README. Open to any preliminary feedback: https://github.com/mjpitz/grpc-go/tree/gh-2770/examples/features/health

I think there are some other use cases (like using the grpc-ecosystem's health probe in Kubernetes) but this demonstrates how it can be used programmatically.

**Comment by mjpitz** [comment]
I also noticed that you could specify health check configuration through the service config string. Last I had heard, service config was a little in the air with the XDS discussions going on. Is that the case? Or would you rather I added a demonstration using the service config to do health checking transparently?

**Comment by dfawley** [comment]
> I also noticed that you could specify health check configuration through the service config string. Last I had heard, service config was a little in the air with the XDS discussions going on. Is that the case? Or would you rather I added a demonstration using the service config to do health checking transparently?

Service configs are solidified in gRPC.  The only concern is enabling TXT/SRV lookups to find the service config and balancer addresses by default.

If your example can inject a service config using `WithDefaultServiceConfig`, that would be ideal, since that allows it to work transparently in the client.

**Comment by dfawley** [comment]
Note that you will need to use a round_robin load balancer ([ref](https://github.com/grpc/proposal/blob/master/A17-client-side-health-checking.md#round_robin)).

**Comment by mjpitz** [comment]
@dfawley Yup! The example code currently demonstrates programmatic use of the health API, but the README calls out to how to use it transparently. Let me throw up a PR for ya to take a look.

**Comment by william-lg** [comment]
> @dfawley Yup! The example code currently demonstrates programmatic use of the health API, but the README calls out to how to use it transparently. Let me throw up a PR for ya to take a look.

I'm a little confused about grpc/examples/features/health.clientHealthCheck, line 93-end
for {
	err = s.RecvMsg(resp)
        // Reports healthy for the LBing purposes if health check is not implemented in the server.
	if status.Code(err) == codes.Unimplemented {
		setConnectivityState(connectivity.Ready, nil)
			return err
		}
         }
         ...
}
It's a loop receiving the data from server. When server response SERVING, it's just blocked here.
I don't know how to use this health-check, from server pushing data?
Many Thanks.

**Comment by mjpitz** [comment]
@william-lg I'm unsure which block of code you are referring to as most of the files I've pushed up don't exceed 50 lines of code. It looks like the block that you pulled may have been from the gRPC connectivity loop where channels are being established and monitored in a transparent way (see README.md on how to set up the transparent use of health checks using withDefaultServiceConfig.)

As for the server side, you can toggle your server's serving status based on asynchronous dependency checks. The server side code demonstrates this by just toggling it's serving status every 5 seconds but you could imagine toggling your own serving status based on upstream systems / dependencies.

**Comment by william-lg** [comment]
> @william-lg I'm unsure which block of code you are referring to as most of the files I've pushed up don't exceed 50 lines of code. It looks like the block that you pulled may have been from the gRPC connectivity loop where channels are being established and monitored in a transparent way (see README.md on how to set up the transparent use of health checks using withDefaultServiceConfig.)
> 
> As for the server side, you can toggle your server's serving status based on asynchronous dependency checks. The server side code demonstrates this by just toggling it's serving status every 5 seconds but you could imagine toggling your own serving status based on upstream systems / dependencies.

I update the file path grpc/health/client.go.clientHealthCheck(the previous one is not correct).
And where is the health-check readme?
Still confused about the asynchronous dependency checks, can you provide an example?

**Comment by mjpitz** [comment]
Looks like I'm missing some more documentation for the client. I stumbled upon this comment block which adds some additional context as to how the client uses health checks rather transparently.

https://github.com/grpc/grpc-go/blob/fff75ae40fde3e38ad4dc57695d639c8a99cb1ba/clientconn.go#L1297-L1301
