### ISSUE TITLE
grpc/resolver/dns_resolver : lookup failure causes connection to give misleading errors

### ISSUE THREAD

**Issue by jeffbean** [grpc/grpc-go#2785]
### What version of gRPC are you using?
master of grpc-go

### What version of Go are you using (`go version`)?
go version go1.12.4 darwin/amd64

### What operating system (Linux, Windows, …) and version?
Linux/osx

### What did you do?
    $ go get google.golang.org/grpc
    $ cd $GOPATH/src/google.golang.org/grpc/examples/route_guide

#### One terminal:
We just start the server with no arguments.

    $ go run server/server.go

#### On another terminal

GOOD:
  
    $ go run client/client.go -server_addr "dns://127.0.0.1/localhost:10000"
    ```
    logs omitted
    ....
    2019/04/22 14:24:16 Got message Fourth message at point(0, 1)
    2019/04/22 14:24:16 Got message Second message at point(0, 2)
    2019/04/22 14:24:16 Got message Fifth message at point(0, 2)
    2019/04/22 14:24:16 Got message Third message at point(0, 3)
    2019/04/22 14:24:16 Got message Sixth message at point(0, 3)
    ```

BAD (the issue in question):

    $ go run client/client.go -server_addr "dns://127.0.0.5/localhost:10000"
    ```
    2019/04/22 14:45:57 Getting feature for point (409146138, -746188906)
    2019/04/22 14:46:07 &{0xc000154000}.GetFeatures(_) = _, rpc error: code = DeadlineExceeded desc = context deadline exceeded:
    exit status 1
    ```

### What did you expect to see?
I expect to see the connection fail to be ready with a failure to lookup any peers.

### What did you see instead?
I see a client timeout error.

**Comment by menghanl** [comment]
There's currently no way for resolvers to report errors.
It is tracked in #2102 (and [here](https://github.com/grpc/grpc-go/blob/47e1ebe575df3e712691b4415f96ff3ab4db6a06/resolver/resolver.go#L106)), and is being actively worked on.

For the time being, you can turn on logs to see errors from the DNS resolver.

I'm going to close this as a duplicate. Please reply if you have further questions.
