### ISSUE TITLE
Seeing 1s latency in between OUTBOUND DATA and INBOUND WINDOW_UDPATE

### ISSUE THREAD

**Issue by jschlather** [grpc/grpc-go#2788]
We've been investigating some 1-2s latency spikes that we've been seeing in Vitess. The setup is that we have a Java GRPC client connecting to to a go-grpc server. Occasionally, we will see latency spike and all of the slow requests will finish at the same time. After turning on GRPC debug logging in the client we were able to observe that when we get these slow series of requests, the `INBOUND WINDOW_UPDATE` appears to be greatly delayed, whereas it should be returning immediately I'm seeing it come 1-2s after outbound data is sent. So it seems that the go grpc server is either unresponsive, or not looking at this stream for that amount of time. I was wondering if there were any possible causes of this or debugging we can do on the grpc server side to figure out what's going on.

### What version of gRPC are you using?
`1.16.0`

### What version of Go are you using (`go version`)?
`1.11`

### What operating system (Linux, Windows, …) and version?
Linux

**Comment by menghanl** [comment]
To confirm that server is not sending window updates timely, try to turn on http2 debugging with env variable `GODEBUG=http2debug=2`.
Also turn on grpc logging `GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info`.

Some questions:
Did you config the window size? And how big are your messages?

**Comment by jschlather** [comment]
I will try to run the server with http2 debugging, do you happen to know how much overhead it has?

We do not configure the window size. The inbound and outbound messages for this service tend to be around 500 bytes.

**Comment by menghanl** [comment]
I'm not sure how much overhead the debugging will cause, but be cautious if you are considering turning it on production.

**Comment by jschlather** [comment]
I was eventually able to get this setup properly and tie together the debug messages between client and server. I verified there are no clock skew issues and it seems that the grpc client is sending the data, but it's taking around ~600ms for the grpc service to receive the data. So, you can see below the log message on the client and then the corresponding read on the server.

```
2019-05-02 02:11:10.932 [vitess-eventloop-1-1] DEBUG h.v.io.grpc.netty.NettyClientHandler - [id: 0x94a48f60, L:/192.168.102.2:31090 - R:{REDACTED}] OUTBOUND DATA: streamId=9043 padding=0 endStream=true length=518 bytes={REDACTED}
I0502 02:11:11.588269      44 logutil.go:31] log: http2: Framer 0xc005553340: read DATA flags=END_STREAM stream=9043 len=518 data={REDACTED}
```

Once the server reads the data everything happens pretty normally. It seems like this is probably not the fault of the go-grpc service, but I was wondering if you had any thoughts. Thanks.

**Comment by jschlather** [comment]
Going to close this out, we narrowed it down to latency in the network layer.
