### ISSUE TITLE
install grpc error 

### ISSUE THREAD

**Issue by toplinuxsir** [grpc/grpc-go#2794]
go get  google.golang.org/grpc
../../go/src/bytes/bytes.go:11:2: 
../../go/src/unicode/tables.go:1:1: expected 'package', found 'EOF'

I use latest go(1.12) version and latest grpc verison

**Comment by canguler** [comment]
Hi @toplinuxsir,

It looks like you're having issues with standard go packages and not with grpc-go. This suggests that you may have some problem with your local Go configuration. Can you check that your GOPATH and GOROOT environment variables are properly set up? If that doesn't help, your local go installation may have some issues. You can try reinstalling it.
