### ISSUE TITLE
Stream got stuck in waitOnHeader even after the underlying transport has gone away

### ISSUE THREAD

**Issue by angl** [grpc/grpc-go#2796]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
1.20.1

### What version of Go are you using (`go version`)?
1.12.4

### What operating system (Linux, Windows, …) and version?
Linux, ubuntu 19.04

### What did you do?
The trigger of the issue was unknown, but there is some suspicion a network interruption was in play. One of the newly created gRPC stream got stuck in waitOnHeader() call for very long time (>10hours). The underlying TCP connection was gone already (verified by netstat).

### What did you expect to see?
The stream's context should get cancelled when the underlying TCP connection went away and that should break the wait.

### What did you see instead?
Apparently the context was not cancelled.

Backtrace of the relevant goroutines (goroutines with stacks inside grpc):
```goroutine 19 [select, 873 minutes]:
observe/vendor/google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader(0xc000161d00, 0x2, 0x8)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/transport.go:267 +0xcc
observe/vendor/google.golang.org/grpc/internal/transport.(*Stream).RecvCompress(...)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/transport.go:278
observe/vendor/google.golang.org/grpc.(*csAttempt).recvMsg(0xc0003fc700, 0x14a1b20, 0xc0003be090, 0x0, 0xc000248900, 0xc0003be090)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/stream.go:856 +0x70c
observe/vendor/google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc0003fc700, 0x0, 0x203000)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/stream.go:721 +0x46
observe/vendor/google.golang.org/grpc.(*clientStream).withRetry(0xc000248900, 0xc0006adb58, 0xc0006adb48, 0xc00042a360, 0x18)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/stream.go:577 +0x7c
observe/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc000248900, 0x14a1b20, 0xc0003be090, 0xc00047b580, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/stream.go:720 +0x100
observe/proto3/agentpb.(*collectorServiceCollectClient).Recv(0xc00064e650, 0xc00047b580, 0x0, 0x0)
	/home/dev/observe/code/go/src/observe/proto3/agentpb/agent.pb.go:2114 +0x62
observe/collector/client.register(0x173caa0, 0xc00064e650, 0x7ffd0626bc64, 0x3, 0x7ffd0626bc75, 0x12, 0x0, 0x0)
	/home/dev/observe/code/go/src/observe/collector/client/client.go:38 +0x1b0
observe/collector/client.newConn(0x16f34e0, 0xc0000de000, 0x173caa0, 0xc00064e650, 0x7ffd0626bc64, 0x3, 0x7ffd0626bc75, 0x12, 0x14f704d, 0x5, ...)
	/home/dev/observe/code/go/src/observe/collector/client/client.go:57 +0x6d
observe/collector/client.Connect(0xc0006aded0, 0x1, 0x1, 0x7ffd0626bc64, 0x3, 0x7ffd0626bc75, 0x12, 0x14f704d, 0x5, 0xc0005a92c0, ...)
	/home/dev/observe/code/go/src/observe/collector/client/client.go:101 +0x3a3
main.runGrpcEmitterOnce(0xc000347650, 0x17231c0, 0xc0003a00c0)
	/home/dev/observe/code/go/src/observe/cmd/agent/agent.go:192 +0x327
main.runGrpcEmitter(0xc000347650, 0xc00035e160)
	/home/dev/observe/code/go/src/observe/cmd/agent/agent.go:218 +0x9f
created by main.NewAgent
	/home/dev/observe/code/go/src/observe/cmd/agent/agent.go:745 +0x23ac

goroutine 97642 [select]:
observe/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00047ad80)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:115 +0x110
created by observe/vendor/google.golang.org/grpc.newCCBalancerWrapper
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:106 +0x14f

goroutine 97606 [select, 873 minutes]:
observe/vendor/google.golang.org/grpc.newClientStream.func5(0xc0000de840, 0xc0002bf200, 0x1722fc0, 0xc0007b6720)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/stream.go:320 +0xd7
created by observe/vendor/google.golang.org/grpc.newClientStream
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/stream.go:319 +0x8e2

goroutine 97659 [select, 873 minutes]:
observe/vendor/google.golang.org/grpc.newClientStream.func5(0xc0000de000, 0xc000248900, 0x1722fc0, 0xc000479f50)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/stream.go:320 +0xd7
created by observe/vendor/google.golang.org/grpc.newClientStream
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/stream.go:319 +0x8e2

goroutine 97643 [chan receive]:
observe/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc0000aea00)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/clientconn.go:1040 +0x5a1
created by observe/vendor/google.golang.org/grpc.(*addrConn).connect
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/clientconn.go:700 +0xb6

goroutine 97590 [chan receive]:
observe/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc0000af180)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/clientconn.go:1040 +0x5a1
created by observe/vendor/google.golang.org/grpc.(*addrConn).connect
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/clientconn.go:700 +0xb6

goroutine 97589 [select]:
observe/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00011c0c0)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:115 +0x110
created by observe/vendor/google.golang.org/grpc.newCCBalancerWrapper
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:106 +0x14f

goroutine 110724 [select]:
observe/vendor/google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc003521cc0, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:317 +0x104
observe/vendor/google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc003594de0, 0x0, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:435 +0x1b6
observe/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc0003af6c0)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/http2_client.go:330 +0x7b
created by observe/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/http2_client.go:328 +0xeb2

goroutine 110707 [IO wait]:
internal/poll.runtime_pollWait(0x7f9c7424cbf0, 0x72, 0xffffffffffffffff)
	/usr/local/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00339ee18, 0x72, 0xe00, 0xe87, 0xffffffffffffffff)
	/usr/local/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00339ee00, 0xc0033a4000, 0xe87, 0xe87, 0x0, 0x0, 0x0)
	/usr/local/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00339ee00, 0xc0033a4000, 0xe87, 0xe87, 0x203000, 0x0, 0xe7a)
	/usr/local/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc002efa6b8, 0xc0033a4000, 0xe87, 0xe87, 0x0, 0x0, 0x0)
	/usr/local/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc00057f480, 0xc0033a4000, 0xe87, 0xe87, 0x26, 0x16f1a20, 0xc000404a78)
	/usr/local/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc0033d2958, 0x16f18c0, 0xc00057f480, 0x410425, 0x13626c0, 0x14a1960)
	/usr/local/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc0033d2700, 0x16f1c80, 0xc002efa6b8, 0x5, 0xc002efa6b8, 0x9)
	/usr/local/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc0033d2700, 0x158a200, 0xc0033d2838, 0x0)
	/usr/local/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc0033d2700, 0xc003574000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/src/crypto/tls/conn.go:1236 +0x137
bufio.(*Reader).Read(0xc0034cbb60, 0xc0034ece38, 0x9, 0x9, 0xc000061880, 0x7f9c79f59008, 0x0)
	/usr/local/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x16f1720, 0xc0034cbb60, 0xc0034ece38, 0x9, 0x9, 0x9, 0x81be89, 0xc00315ca20, 0xc003150004)
	/usr/local/src/io/io.go:310 +0x88
io.ReadFull(...)
	/usr/local/src/io/io.go:329
observe/vendor/golang.org/x/net/http2.readFrameHeader(0xc0034ece38, 0x9, 0x9, 0x16f1720, 0xc0034cbb60, 0x0, 0x0, 0xc00315ca20, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/golang.org/x/net/http2/frame.go:237 +0x88
observe/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0034ece00, 0xc00315ca20, 0xc00315ca00, 0x0, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/golang.org/x/net/http2/frame.go:492 +0xa1
observe/vendor/google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc0003af180)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/http2_client.go:1236 +0x168
created by observe/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/http2_client.go:286 +0xd15

goroutine 110708 [select]:
observe/vendor/google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc003521740, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:317 +0x104
observe/vendor/google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0034cbc20, 0x0, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:435 +0x1b6
observe/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc0003af180)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/http2_client.go:330 +0x7b
created by observe/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/http2_client.go:328 +0xeb2

goroutine 110723 [IO wait]:
internal/poll.runtime_pollWait(0x7f9c74200a10, 0x72, 0xffffffffffffffff)
	/usr/local/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc003596218, 0x72, 0xe00, 0xe87, 0xffffffffffffffff)
	/usr/local/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc003596200, 0xc0035aa000, 0xe87, 0xe87, 0x0, 0x0, 0x0)
	/usr/local/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc003596200, 0xc0035aa000, 0xe87, 0xe87, 0x203000, 0x0, 0xe7a)
	/usr/local/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc002efa908, 0xc0035aa000, 0xe87, 0xe87, 0x0, 0x0, 0x0)
	/usr/local/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc0006566c0, 0xc0035aa000, 0xe87, 0xe87, 0x26, 0x16f1a20, 0xc0008e9a78)
	/usr/local/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc0033d3758, 0x16f18c0, 0xc0006566c0, 0x410425, 0x13626c0, 0x14a1960)
	/usr/local/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc0033d3500, 0x16f1c80, 0xc002efa908, 0x5, 0xc002efa908, 0x9)
	/usr/local/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc0033d3500, 0x158a200, 0xc0033d3638, 0x0)
	/usr/local/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc0033d3500, 0xc0035bc000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/src/crypto/tls/conn.go:1236 +0x137
bufio.(*Reader).Read(0xc003594d20, 0xc0034ed0d8, 0x9, 0x9, 0xc000061880, 0x7f9c79f59008, 0x0)
	/usr/local/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x16f1720, 0xc003594d20, 0xc0034ed0d8, 0x9, 0x9, 0x9, 0x81be89, 0xc003070ab0, 0xc003070004)
	/usr/local/src/io/io.go:310 +0x88
io.ReadFull(...)
	/usr/local/src/io/io.go:329
observe/vendor/golang.org/x/net/http2.readFrameHeader(0xc0034ed0d8, 0x9, 0x9, 0x16f1720, 0xc003594d20, 0x0, 0x0, 0xc003070ab0, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/golang.org/x/net/http2/frame.go:237 +0x88
observe/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0034ed0a0, 0xc003070ab0, 0xc003070a00, 0x0, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/golang.org/x/net/http2/frame.go:492 +0xa1
observe/vendor/google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc0003af6c0)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/http2_client.go:1236 +0x168
created by observe/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/http2_client.go:286 +0xd15
```

**Comment by canguler** [comment]
Hi @angl,

http2Client.reader calls framer.ReadFrame and if ReadFrame returns an error, then http2Client.closeStream is called for the stream which in turn closes stream's headerChan. Closing of headerChan should unblock waitOnHeader.

As your program is stuck in waitOnHeader, I assume these didn't happen. So, ReadFrame is not aware that the underlying TCP connection is lost. Can you check what is your TCP keepalive configuration?

Also, are you using grpc's keepalive and if you are, what is your configuration?

**Comment by angl** [comment]
Hi @canguler,

Thanks for the pointers. First to answer your questions, I am not using grpc's keepalive and have default TCP keepalive configurations:
```root@observe-agent-4r6jh:~# cat /proc/sys/net/ipv4/tcp_keepalive_time
7200
root@observe-agent-4r6jh:~# cat /proc/sys/net/ipv4/tcp_keepalive_intvl
75
root@observe-agent-4r6jh:~# cat /proc/sys/net/ipv4/tcp_keepalive_probes
9```

I did a bit digging on my side with delve. The problem seems to happen when `http2Client.operateHeaders()` bails due to header decoding error:
```
	state.data.isGRPC = !initialHeader
	if err := state.decodeHeader(frame); err != nil {
		t.closeStream(s, err, true, http2.ErrCodeProtocol, status.Convert(err), nil, endStream) // <<
		return
	}
```
At this point the stream's `headerDone` has already been set to 1 because of
```
	initialHeader := atomic.SwapUint32(&s.headerDone, 1) == 0
```
and bailing now would prevent the actual channel from being closed. For reference, here is the state of a stream after this happens:

```
*observe/vendor/google.golang.org/grpc/internal/transport.Stream {
    	id: 1,
    	st: observe/vendor/google.golang.org/grpc/internal/transport.ServerTransport nil,
    	ctx: context.Context(*context.valueCtx) *{
    		Context: context.Context(*context.valueCtx) ...,
    		key: (unreadable interface type "observe/vendor/google.golang.org/grpc/peer.peerKey" not found for 0xc000030588: no type entry found, use 'types' for a list of valid types),
    		val: interface {}(*observe/vendor/google.golang.org/grpc/peer.Peer) ...,},
    	cancel: nil,
    	done: chan struct {} {
    		qcount: 0,
    		dataqsiz: 0,
    		buf: *[0]struct struct {} [],
    		elemsize: 0,
    		closed: 1,
    		elemtype: *runtime._type {
    			size: 0,
    			ptrdata: 0,
    			hash: 670477339,
    			tflag: tflagExtraStar (2),
    			align: 1,
    			fieldalign: 1,
    			kind: 153,
    			alg: *(*runtime.typeAlg)(0x22bde30),
    			gcdata: *1,
    			str: 65131,
    			ptrToThis: 681472,},
    		sendx: 0,
    		recvx: 0,
    		recvq: waitq<struct {}> {
    			first: *sudog<struct {}> nil,
    			last: *sudog<struct {}> nil,},
    		sendq: waitq<struct {}> {
    			first: *sudog<struct {}> nil,
    			last: *sudog<struct {}> nil,},
    		lock: runtime.mutex {key: 0},},
    	ctxDone: <-chan struct {} {},
    	method: "/observe.agent.CollectorService/Collect",
    	recvCompress: "",
    	sendCompress: "",
    	buf: *observe/vendor/google.golang.org/grpc/internal/transport.recvBuffer {
    		c: chan observe/vendor/google.golang.org/grpc/internal/transport.recvMsg {
    			qcount: 1,
    			dataqsiz: 1,
    			buf: *[1]observe/vendor/google.golang.org/grpc/internal/transport.recvMsg [
    				(*"observe/vendor/google.golang.org/grpc/internal/transport.recvMsg")(0xc000030600),
    			],
    			elemsize: 40,
    			closed: 0,
    			elemtype: *runtime._type {
    				size: 40,
    				ptrdata: 40,
    				hash: 907385309,
    				tflag: tflagUncommon|tflagExtraStar|tflagNamed (7),
    				align: 8,
    				fieldalign: 8,
    				kind: 25,
    				alg: *(*runtime.typeAlg)(0x22bde20),
    				gcdata: *17,
    				str: 203576,
    				ptrToThis: 623296,},
    			sendx: 0,
    			recvx: 0,
    			recvq: waitq<observe/vendor/google.golang.org/grpc/internal/transport.recvMsg> {
    				first: *sudog<observe/vendor/google.golang.org/grpc/internal/transport.recvMsg> nil,
    				last: *sudog<observe/vendor/google.golang.org/grpc/internal/transport.recvMsg> nil,},
    			sendq: waitq<observe/vendor/google.golang.org/grpc/internal/transport.recvMsg> {
    				first: *sudog<observe/vendor/google.golang.org/grpc/internal/transport.recvMsg> nil,
    				last: *sudog<observe/vendor/google.golang.org/grpc/internal/transport.recvMsg> nil,},
    			lock: runtime.mutex {key: 0},},
    		mu: (*sync.Mutex)(0xc000aea2c8),
    		backlog: []observe/vendor/google.golang.org/grpc/internal/transport.recvMsg len: 0, cap: 0, nil,
    		err: error(*observe/vendor/google.golang.org/grpc/status.statusError) ...,},
    	trReader: io.Reader(*observe/vendor/google.golang.org/grpc/internal/transport.transportReader) *{
    		reader: io.Reader(*observe/vendor/google.golang.org/grpc/internal/transport.recvBufferReader) ...,
    		windowHandler: observe/vendor/google.golang.org/grpc/internal/transport.(*http2Client).newStream.func3,
    		er: error nil,},
    	fc: *observe/vendor/google.golang.org/grpc/internal/transport.inFlow {
    		mu: (*sync.Mutex)(0xc000495c20),
    		limit: 65535,
    		pendingData: 173,
    		pendingUpdate: 0,
    		delta: 0,},
    	wq: *observe/vendor/google.golang.org/grpc/internal/transport.writeQuota {quota: 65536, ch: chan struct {} 0/1, done: <-chan struct {} 0/0, replenish: observe/vendor/google.golang.org/grpc/internal/transport.(*writeQuota).realReplenish-fm},
    	requestRead: observe/vendor/google.golang.org/grpc/internal/transport.(*http2Client).newStream.func1,
    	headerChan: chan struct {} {
    		qcount: 0,
    		dataqsiz: 0,
    		buf: *[0]struct struct {} [],
    		elemsize: 0,
    		**closed: 0,**
    		elemtype: *runtime._type {
    			size: 0,
    			ptrdata: 0,
    			hash: 670477339,
    			tflag: tflagExtraStar (2),
    			align: 1,
    			fieldalign: 1,
    			kind: 153,
    			alg: *(*runtime.typeAlg)(0x22bde30),
    			gcdata: *1,
    			str: 65131,
    			ptrToThis: 681472,},
    		sendx: 0,
    		recvx: 0,
    		recvq: waitq<struct {}> {
    			first: *(*sudog<struct {}>)(0xc000081200),
    			last: *(*sudog<struct {}>)(0xc000081200),},
    		sendq: waitq<struct {}> {
    			first: *sudog<struct {}> nil,
    			last: *sudog<struct {}> nil,},
    		lock: runtime.mutex {key: 0},},
    	**headerDone: 1,**
    	hdrMu: sync.Mutex {state: 0, sema: 0},
    	header: observe/vendor/google.golang.org/grpc/metadata.MD nil,
    	trailer: observe/vendor/google.golang.org/grpc/metadata.MD nil,
    	noHeaders: false,
    	headerSent: 0,
    	state: streamDone (3),
    	status: *observe/vendor/google.golang.org/grpc/status.Status {
    		s: *(*"observe/vendor/google.golang.org/genproto/googleapis/rpc/status.Status")(0xc0000a6eb0),},
    	bytesReceived: 1,
    	unprocessed: 0,
    	contentSubtype: "",}
```
Note the inconsistency between **headerDone** and **headerChan**.

AFAICT, a 503 service unavailable responded by the server (it's a nginx proxy and the backend is being restarted) triggered the issue.

**Comment by angl** [comment]
Seems to be introduced by https://github.com/grpc/grpc-go/commit/79c9bc679419ff2f57deccc996e33477a64b6762
