### ISSUE TITLE
SIGSEGV in google.golang.org/grpc.(*ClientConn).healthCheckConfig

### ISSUE THREAD

**Issue by t57root** [grpc/grpc-go#2824]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?

commit 4b60e3b6a1900853971945c616869c0fc211ac75

### What version of Go are you using (`go version`)?

go version go1.12.4 linux/amd64

### What operating system (Linux, Windows, …) and version?

Code compiled on CentOS 6.3
and SIGSEGV occurred on
CentOS Linux release 7.3.1611 (Core)
3.18.6-2.el7.centos.x86_64 #1 SMP Mon Oct 24 13:01:33 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?

I think it's just standard usage of grpc over tls, all things including grpc.DialContext and RPC call work well, but seems something happened in the health checking part. will try to streamline the code to reproduce the problem if it's necessary

### What did you expect to see?

Run without SIGSEGV

### What did you see instead?

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x268 pc=0x7e7895]

goroutine 16 [running]:
sync.(*RWMutex).RLock(...)
/usr/local/go/src/sync/rwmutex.go:48
google.golang.org/grpc.(*ClientConn).healthCheckConfig(0x0, 0x0)
/build/src/google.golang.org/grpc/clientconn.go:828 +0x35
google.golang.org/grpc.(*addrConn).resetTransport(0xc00031a000)
/build/src/google.golang.org/grpc/clientconn.go:1080 +0x513
created by google.golang.org/grpc.(*addrConn).connect
/build/src/google.golang.org/grpc/clientconn.go:765 +0xb6

**Comment by canguler** [comment]
Hi @t57root 

It looks like `healthCheckConfig()` is called for a `nil` `*ClientConn`.
Can you share the full call stack and the code to reproduce the problem?

**Comment by t57root** [comment]
hi, @canguler   thanks for the reply.
I believe the call stack I attached above is all the output golang printed while the crash. And this crash is not inevitable so it's not easy to reproduce the problem. 

I wrap grpc code into a single golang struct, and used in two different binaries. Only one particular binary would cause the problem, and seems the problem always occurs while the process is receiving signal and about to exit (I register a signal handler(SIGUSR1) in C for cleaning up). 

I haven't figured out healthCheckConfig() is called by which user-faced API and I never call a healthcheck-related API in my code. Also I never close the grpc connection in my code. 
So I kinda think this operation is called automatically in some internal grpc goroutine?

**Comment by canguler** [comment]
hi @t57root,

Could you share your code?

Thinking now, it looks like RLock() is called with a nil *RWMutex. But it's weird, because in healthCheckConfig(), RLock() is not called on a *RWMutex but on an actual RWMutex. So, it shouldn't be nil. This may be related to what you describe in your second paragraph: `... the problem always occurs while the process is receiving signal and about to exit (I register a signal handler(SIGUSR1) in C for cleaning up).`

**Comment by canguler** [comment]
Hey @t57root,

Any update on this?

**Comment by t57root** [comment]
sorry,  my original code is fairly large and I haven't managed to streamline the code into a simple piece which could reproduce the problem
