### ISSUE TITLE
[xds] Support per-endpoint weights propagation

### ISSUE THREAD

**Issue by euroelessar** [grpc/grpc-go#2827]
### Use case(s) - what problem will this feature solve?

It allows out-sourcing load balancing decisions to centralized control plane.

### Proposed Solution

There seems to be no trivial solution unfortunately due to non-extensibility of `Address` structure. Adding new field or modifying any existing one affects comparison logic, which is a problem assuming that `Address` is used as unique identifier of the connection (so if weight is changed - client will re-connect).

**Comment by alazarev** [comment]
The easiest way to implement the feature is just to add weight to Address metadata.
@menghanl do you think it is valid approach?
Do you have plans to add this functionality in a reasonable timeframe?
We (Dropbox) are happy to help with that if needed.

**Comment by menghanl** [comment]
As mentioned in the issue, it might not work that well:

> Adding new field or modifying any existing one affects comparison logic, which is a problem assuming that Address is used as unique identifier of the connection (so if weight is changed - client will re-connect).

The way to do weights today is to return duplicate addresses with different [metadata field](https://github.com/grpc/grpc-go/blob/0435a4bb26ac754b679412c2d7f93748b99897ca/resolver/resolver.go#L91).
Or, if you have control of both name resolver and load balancer, you can use this field as the weight (additional logic will be needed in the balancer to take care of the comparing problem).

Also, are you using the xds balancer?

**Comment by alazarev** [comment]
>if weight is changed - client will re-connect
is it the real issue? It shouldn't be a problem if weight doesn't change often. But yes, I agree that it is more like workaround.

>Also, are you using the xds balancer?
Not yet, but going to use.

**Comment by menghanl** [comment]
> > if weight is changed - client will re-connect
> 
> is it the real issue? It shouldn't be a problem if weight doesn't change often. But yes, I agree that it is more like workaround.

Addresses are not used as map keys in gRPC, but are often used in balancers.
If you control the balancers, this won't be a problem.

> > Also, are you using the xds balancer?
> 
> Not yet, but going to use.

xds needs to support all balancers as sub-balancers (for intro-locality endpoint picking).
I think the trick to return duplicate addresses with different metadata can still work. The concern is that multiple connections will be created to the same backend.

(Kind of related, there's also a plan to add a load based weighted-round-robin balancer. The backends will report load to the clients, and clients will adjust the weight of backends.)

**Comment by alazarev** [comment]
Is there any progress on this?
Possible solution could be to introduce PickerBuilderV2 that could take weights into account. I've made https://github.com/grpc/grpc-go/pull/2936/commits/c4a684e8c1802a7b18feae21580a68d17db6e2ed that introduces new WeightedAddress that will make sure that code relying on old API (with Address as a key) still works.
@menghanl Does it make sense? Is it the direction xds developent could go? If yes, I can polish code / add tests to make it real pull request.

**Comment by menghanl** [comment]
Please see reply in #2936.

**Comment by alazarev** [comment]
Continue discussion started at https://github.com/grpc/grpc-go/pull/2945 here. 

>I think we should leave base package as is, and re-implement this for wrr.
I tried to do so, and it looks like path to nowhere (can share result if there is an interest). Half of the logic is copy-paste from base with no easy way to reuse it.

I think the right approach here will be to:
1. add something like "ClearMetadata" field to balance config with false value as default to keep backward compatibility. 
2. Introduce new interface for PickerBuilder that is aware of weights and NewBalancerBuilder that takes a new PickerBuilder (may be in separate from base.go file), but keep balancer.go implementation in place (with two switches inside - one to clear metadata, another - to call different picker builder)
3. Inherit weightedroundrobin.go from base balancer.

@menghanl do you have strong opinion on having weightedroundrobin without base balancer reuse?

**Comment by menghanl** [comment]
I still prefer to keep base simple. It's not expected to be used in balancers more complicated than round-robin. It's not part of the balancer APIs, but more like an example.

Also, how about the following things:

> wrr will have some special behaviors, some I can think of now:
>  - Duplicates in addresses list (same address string, but multiple entries in addrs list, with potential different metadata)
>   - Should we add up the weights?
> - Since metadata is not hashed, the only useful thing is the address string itself. Maybe we should use the string as the key, instead of the address struct

**Comment by menghanl** [comment]
The xDS balancers do carry weights now.
The remaining part in this PR was to support weights in the base balancer, which there's currently no plan to do.
Closing now.
