### ISSUE TITLE
Client hangs if server returns 502 status code

### ISSUE THREAD

**Issue by jared2501** [grpc/grpc-go#2836]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
1.21.0

### What version of Go are you using (`go version`)?
go version go1.12.4 darwin/amd64

### What operating system (Linux, Windows, …) and version?
Mac OS

### What did you do? What did you expect to see? What did you see instead?

Running [this minimal repro](https://github.com/jared2501/grpc-go-repro) hangs indefinitely using grpc-go 1.21.0, but if I downgrade to 1.19.0 (as in [this branch](https://github.com/jared2501/grpc-go-repro/tree/grpc-go-1.19.0)) the client returns an error immediately.

**Comment by lyuxuan** [comment]
#2818 should fix your problem. Please modify your go.mod to master and try again.

**Comment by jared2501** [comment]
Ah looks like you're right @lyuxuan, master seems to have this fixed. Is there any chance of getting this in a 1.21.1?

**Comment by menghanl** [comment]
@jared2501 Yes, we will make a minor release with the fix.

**Comment by jared2501** [comment]
Awesome! thanks :)

**Comment by menghanl** [comment]
@jared2501 
FYI [v1.21.1](https://github.com/grpc/grpc-go/releases/tag/v1.21.1) is just released
