### ISSUE TITLE
Server hangs in a C environment with custom signal handlers

### ISSUE THREAD

**Issue by anqurvanillapy** [grpc/grpc-go#2839]
I have a legacy C application left unchanged that runs on an environment with custom signal handlers, i.e.

* SIGUSR1, SIGUSR2, **SIGIO**...

and need to create a gRPC server using Go on top of the application (C executable calling Cgo routines).  But my server:

* hangs after `.Serve`, not able to be connected via some gRPC client like `evans`, with error message
```
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp x.x.x.x:xxx: i/o timeout"
```
* `netstat -a | grep PORT` indicates that the port is being listened to
* `telnet` and `nc` can connect to the server, but `Connection closed by foreign host.` after seconds

My question is that do the custom signal handlers (like `SIGIO`) really affect the function of grpc-go?  If grpc-go is signal-handler-free, does this affect the Go runtime?

**Comment by menghanl** [comment]
grpc-go doesn't rely on signal handlers, so this doesn't look like a grpc specific problem to me.

I'm not very familiar with the impact of signal handlers. But maybe you can try a simpler test with just a `net.Dial`.

**Comment by anqurvanillapy** [comment]
Well, this is a very embarrasing issue I'm quite sorry 🤣.  I found that I can connect to the server via local gRPC client, but failed at a remote client, becoming an trivial network issue.  Thanks for your sincere help here!
