### ISSUE TITLE
Is there anyway to prevent reconnection attempt behavior in Credentials?

### ISSUE THREAD

**Issue by iwasaki-kenta** [grpc/grpc-go#2863]
I defined a set of custom credentials, which implement `ClientHandshake` and `ServerHandshake` methods. It appears that the default behavior is that if handshaking fails, a reconnection will be attempted.

However, say for example that the handshaking fails as a result of the server claiming that I have provided invalid credentials, or that I have provided credentials that were valid but are unauthorized. How can I forcefully stop retriggering a reconnection to the server in this case?

**Comment by lyuxuan** [comment]
As indicated [here](https://github.com/grpc/grpc-go/blob/a1d4c283c6bcd51bb1162a0eb0b59ad1dd4b7a56/credentials/credentials.go#L82), if the error returned by `ClientHandshake` implements `Temporary()` and returns false, then when you `Dial` with `DialOption` [`WithBlock`](https://godoc.org/google.golang.org/grpc#WithBlock) and [`FailOnNonTempDialError` ](https://godoc.org/google.golang.org/grpc#FailOnNonTempDialError), it will fail for the case you described and not triggering reconnection.

Some relevant context [here](https://github.com/grpc/grpc-go/issues/2031#issuecomment-417101194).

**Comment by iwasaki-kenta** [comment]
> As indicated [here](https://github.com/grpc/grpc-go/blob/a1d4c283c6bcd51bb1162a0eb0b59ad1dd4b7a56/credentials/credentials.go#L82), if the error returned by `ClientHandshake` implements `Temporary()` and returns false, then when you `Dial` with `DialOption` [`WithBlock`](https://godoc.org/google.golang.org/grpc#WithBlock) and [`FailOnNonTempDialError` ](https://godoc.org/google.golang.org/grpc#FailOnNonTempDialError), it will fail for the case you described and not triggering reconnection.
> 
> Some relevant context [here](https://github.com/grpc/grpc-go/issues/2031#issuecomment-417101194).

What exactly is a wrapper error under this definition?

```go
	// If the returned error is a wrapper error, implementations should make sure that
	// the error implements Temporary() to have the correct retry behaviors.
```

The option `FailOnNonTempDialError` appears to be what I need in this case. Is there any reason why gRPC does not choose to have it enabled by default?

**Comment by lyuxuan** [comment]
Below is an example of wrapper error.
```
type errorWrapper struct {
	err error
}

func (e *errorWrapper) Temporary() string {
    return false
}
```
In your case, your `ClientHandshake` implementation knows whether the error should be retried or not, so you can return the error wrapper which wraps around the original error as necessary to force no retry.

For grpc, an attempt to establish a connection may be impacted by many different things (e.g. interrupt in network, server not up yet, etc.), and many of those are temporary and can be resolved by retrying. Very few situations like what you have mentioned is hard failure and retry won't help. Therefore, by default, `FailOnNonTempDialError` is not on.

**Comment by iwasaki-kenta** [comment]
> Below is an example of wrapper error.
> 
> ```
> type errorWrapper struct {
> 	error // embedding the original error
> }
> 
> func (e *errorWrapper) Temporary() bool {
>     return false
> }
> ```
> 
> In your case, your `ClientHandshake` implementation knows whether the error should be retried or not, so you can return the error wrapper which wraps around the original error as necessary to force no retry.
> 
> For grpc, an attempt to establish a connection may be impacted by many different things (e.g. interrupt in network, server not up yet, etc.), and many of those are temporary and can be resolved by retrying. Very few situations like what you have mentioned is hard failure and retry won't help. Therefore, by default, `FailOnNonTempDialError` is not on.

Gotcha, one last question then. Using `WithBlock()`, I noticed that the error returned does not include any information as to why a call to `Dial()` fails. Removing `WithBlock()` properly yields an error that describes why the custom handshaking protocol I implemented failed (my own custom error).

Would this be expected behavior?

**Comment by menghanl** [comment]
What error did you get from `Dial` without `WithBlock()`? Did you also set `FailOnNonTempDialError()`?

**Comment by dfawley** [comment]
Ping @iwasaki-kenta - do you have any additional information on this?
