### ISSUE TITLE
why my grpc client channel status is ready while the stream has already been closed

### ISSUE THREAD

**Issue by sunjun-csu** [grpc/grpc-go#2872]
I have implemented a grpc client with c++, the grpc server provided for me is written with go.
The server will close connection every 30 minutes, and I will check the status of the channel before I call ClientReaderWriter.Read or ClientReaderWriter.Write;
Here come my questions, after the server closed the connection, i got a ready status from Channel.GetState() , however, when i try to write a request with the stream, it directly returns false, which means the stream has been closed according to your doc.
 Why the channel status is always ready or idle, how can I realy detect the connection closed in grpc client?

**Comment by menghanl** [comment]
This seems to be a question about the c++ client. Please file a issue in https://github.com/grpc/grpc instead. Thanks!
