### ISSUE TITLE
How return specific response when handler panic

### ISSUE THREAD

**Issue by asgmojtaba** [grpc/grpc-go#2882]
Consider following service:

	service MicroService {
	  rpc generalCall (RequestPr) returns (ResponsePr) {
	  }
	}

so my handler look like this:

	func (h *GRPCHandler) GeneralCall(context context.Context, request *micro.RequestPr) (response *micro.ResponsePr, err error) {
		defer func() {
			if r := recover(); r != nil {
				var err error
				switch r.(type) {
				case string:
					err = errors.New(r.(string))
				case error:
					err = r.(error)
				default:
					err = errors.New("unknown error")
				}
				log.Println(err)
				response = &micro.ResponsePr{StatusCode: -1}
			}
		}()
		////

		panic("something exploded!")
	}

but in case of panic i got this error: 

> ERROR: 2019/06/25 18:46:13 grpc: server failed to encode response:  rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil

I wonder how this possible, why response not changed and remained nil?

**Comment by menghanl** [comment]
It worked for me, with `examples/helloworld`, and the following diff:

```diff
diff --git a/examples/helloworld/greeter_server/main.go b/examples/helloworld/greeter_server/main.go
index e99fb26a31..e4eb780a7d 100644
--- a/examples/helloworld/greeter_server/main.go
+++ b/examples/helloworld/greeter_server/main.go
@@ -38,7 +38,15 @@ const (
 type server struct{}
 
 // SayHello implements helloworld.GreeterServer
-func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
+func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (resp *pb.HelloReply, err error) {
+       defer func() {
+               if r := recover(); r != nil {
+                       log.Println("server: recovered,", r)
+                       resp = &pb.HelloReply{Message: "from panic"}
+               }
+       }()
+       panic("something exploded!")
+
        log.Printf("Received: %v", in.Name)
        return &pb.HelloReply{Message: "Hello " + in.Name}, nil
 }
```

Did you try to start from a simple assignment, and add other things (like the switch), to see what makes it not work.
