### ISSUE TITLE
Transfer large file via gRPC Streaming

### ISSUE THREAD

**Issue by nandakumar111** [grpc/grpc-go#2885]
I am getting nil pointer dereference error while transferring file more than 1MB in receiver side.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1454e81]
```

I tried segmenting the large file into many small bytes less than 1MB each and transfer through gRPC streaming and its working. Is there any other way to stream large files using gRPC?

>pb/transfer.proto
```
//TODO() generate proto file following command => protoc ./transfer.proto -I. --go_out=plugins=grpc:.

syntax = "proto3";

package pb;

service GuploadService {
    rpc Upload(stream Chunk) returns (UploadStatus) {}
}

message Chunk {
    bytes Content = 1;
    string totalSize = 2;
    string received = 3;
}

enum UploadStatusCode {
    Unknown = 0;
    Ok = 1;
    Failed = 2;
}

message UploadStatus {
    string Message = 1;
    UploadStatusCode Code = 2;
}
```
>file_receive.go
```
package main

import (
    "./pb"
    "fmt"
    "github.com/pkg/errors"
    "log"
    "google.golang.org/grpc"
    "io"
    "net"
    "os"
)

const (
    port = "localhost:50051"
)

type server struct {
}

func (s *server) Upload(stream pb.GuploadService_UploadServer) (err error) {
    // open output file
    fo, err := os.Create("./output")
    if err != nil {
        return errors.New("failed to create file")
    }
    // close fo on exit and check for its returned error
    defer func() {
        if err := fo.Close(); err != nil {
            panic(err)
        }
    }()
    var res *pb.Chunk
    for {
        res, err = stream.Recv()

        if err == io.EOF {
            err = stream.SendAndClose(&pb.UploadStatus{
                Message: "Upload received with success",
                Code:    pb.UploadStatusCode_Ok,
            })
            if err != nil {
                err =  errors.New("failed to send status code")
                return err
            }
            return nil
        }
        fmt.Println(res.Received)
        // write a chunk
        if _, err := fo.Write(res.Content); err != nil {
            err =  errors.New(err.Error())
            return err
        }
    }
}

func main(){
    lis, err := net.Listen("tcp", port)
    if err != nil {
        log.Fatalf("failed to listen: %v", err)
    }
    s := grpc.NewServer()

    pb.RegisterGuploadServiceServer(s, &server{})

    if err := s.Serve(lis); err != nil {
        log.Fatalf("failed to serve: %v", err)
    }
}
```
>file_send.go
```
package main

import (
    "./pb"
    "context"
    "fmt"
    "github.com/pkg/errors"
    "log"
    "google.golang.org/grpc"
    "io"
    "os"
    "strconv"
)

const (
    address     = "localhost:50051"
    sentValue = 1000000 //limit
)

func main()  {
    conn, err := grpc.Dial(address, grpc.WithInsecure())
    if err != nil{
        log.Fatalf("didn't connect %v", err)
    }
    defer conn.Close()
    c := pb.NewGuploadServiceClient(conn)

    var (
        buf     []byte
        status  *pb.UploadStatus
    )
    // open input file
    fi, err := os.Open("./input.dmg")
    if err != nil {
        fmt.Println("Not able to open")
        return
    }

    stat, err := fi.Stat()
    if err != nil {
        return
    }
    // close fi on exit and check for its returned error
    defer func() {
        if err := fi.Close(); err != nil {
            fmt.Println("Not able to open")
            return
        }
    }()

    ctx := context.Background()
    stream, err := c.Upload(ctx)
    if err != nil {
        err = errors.Wrapf(err,
            "failed to create upload stream for file %s",
            fi)
        return
    }
    defer stream.CloseSend()

    buf = make([]byte,stat.Size())
    for {
        // read a chunk
        n, err := fi.Read(buf)
        if err != nil && err != io.EOF {
            err = errors.Wrapf(err,
                "failed to send chunk via stream")
            return
        }
        if n == 0 {
            break
        }
        var i int64
        for i = 0 ; i < ((stat.Size()/sentValue)*sentValue)  ; i += sentValue {
            err = stream.Send(&pb.Chunk{
                Content: buf[i:i+sentValue],
                TotalSize:strconv.FormatInt(stat.Size(), 10),
                Received:strconv.FormatInt(i+sentValue, 10),
            })
        }
        if stat.Size()%sentValue > 0{
            err = stream.Send(&pb.Chunk{
                Content: buf[((stat.Size()/sentValue)*sentValue):((stat.Size()/sentValue*sentValue)+ (stat.Size()%sentValue))],
                TotalSize:strconv.FormatInt(stat.Size(), 10),
                Received:string(stat.Size()%sentValue),
            })
        }

        if err != nil {
            err = errors.Wrapf(err,
                "failed to send chunk via stream")
            return
        }
    }


    status, err = stream.CloseAndRecv()
    if err != nil {
        err = errors.Wrapf(err,
            "failed to receive upstream status response")
        return
    }

    if status.Code != pb.UploadStatusCode_Ok {
        err = errors.Errorf(
            "upload failed - msg: %s",
            status.Message)
        return
    }

    return
}
```
check my working code.

https://stackoverflow.com/questions/56767293/transfer-large-file-via-grpc-streaming

**Comment by dfawley** [comment]
@nandakumar111 were you able to get this working?  Your code example above looks like it may have some issues breaking up the data - you might want to verify that the data passed to Send is exactly as you expected it.

**Comment by nandakumar111** [comment]
@dfawley :) thanks for your reply. I tried many files like *.dmg, *.sh, *.rar, *.txt and binary files. It was working. but in the future, it may affect. Here I'm just converting a file to bytes and stream a small amount of data. I know there’s no way to guarantee in which order each message arrives in the type system. What I'm asking is grpc will support streaming a huge amount of single data? Is there is any way to achieve this?

**Comment by dfawley** [comment]
> I know there’s no way to guarantee in which order each message arrives in the type system.

I'm not sure what you're saying with this - message ordering **is** preserved by gRPC streams.

gRPC can support up to 2GB per message (although I wouldn't recommend going this high due to memory requirements).  I'm not sure why you were getting a nil pointer dereference panic, but it is most likely a bug in your code.  Can you try to debug it further and determine whether the error was in your code or grpc-go?  I would recommend starting with the goroutine trace produced when the nil pointer error happens.

**Comment by nandakumar111** [comment]
hi, I added **`MaxSendMsgSize`**  in **`grpc.ServerOption`** and **`MaxCallRecvMsgSize`** in **`grpc.DialOption`** like,
>  file_send.go
```
var dialOpt []grpc.DialOption
dialOpt = append(dialOpt, grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(1024 * 1024 * 1024 * 1024 * 1024), grpc.MaxCallSendMsgSize(1024 * 1024 * 1024 * 1024 * 1024)), grpc.WithInsecure())
conn, err := grpc.Dial(address, dialOpt...)
```

> file_receive.go
```
var options []grpc.ServerOption
options = append(options, grpc.MaxSendMsgSize(5 * 1024 * 1024 * 1024 * 1024), grpc.MaxRecvMsgSize(5 * 1024 * 1024 * 1024 * 1024))
s := grpc.NewServer(options...)
```
and, I tried many times to transfer 4.24GB (4,241,813,988 bytes) file but, I got consistantly 1.07GB (1,073,741,824 bytes) in every time. 

OS: MAC OS
RAM: 8GB 

OS: Windows 10 Pro
RAM: 8GB

I tried in both windows and mac with 8GB RAM.

**Comment by dfawley** [comment]
Ping @canguler PTAL at this when you have time

**Comment by nandakumar111** [comment]
@dfawley thank you

**Comment by dfawley** [comment]
@nandakumar111 have you been able to figure anything out here on your own?  We don't currently have the resources to debug without a more concrete starting point.  We can leave this open and revisit when we have time, but if you are able to do some more debugging and determine the root cause that would be very helpful.

**Comment by simonbaren** [comment]
@dfawley I'm not expert in go so I might miss something but I think that this [thread](https://github.com/grpc/grpc-java/issues/6259#issuecomment-544005872) would help.

TL'DR - When streaming with GRPC, one must wait for the server to be ready between each send. In my implementation (cpp )I have an instance to a

**Comment by nandakumar111** [comment]
> @dfawley I'm not expert in go so I might miss something but I think that this [thread](https://github.com/grpc/grpc-java/issues/6259#issuecomment-544005872) would help.
> 
> TL'DR - When streaming with GRPC, one must wait for the server to be ready between each send. In my implementation (cpp )I have an instance to a

this issue is resolved few months back. I'm able to send large files via grpc.
