### ISSUE TITLE
with one request from a client, the server handles two times.

### ISSUE THREAD

**Issue by tannva-1559** [grpc/grpc-go#2895]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
1.22.0
### What version of Go are you using (`go version`)?
go1.11.5 
### What operating system (Linux, Windows, …) and version?
windows 10
### What did you do?
If possible, provide a recipe for reproducing the error.
checkout and run example hello world
### What did you expect to see?

```
- client :
 2019/07/05 13:29:17 Greeting: Hello world
- server: 
 2019/07/05 13:29:17 Received: world
```

### What did you see instead?

```
- client :
 2019/07/05 13:29:17 Greeting: Hello world
- server: 
 2019/07/05 13:29:14 Received: world
 2019/07/05 13:29:17 Received: world
```

**Comment by menghanl** [comment]
Can you turn on logs for both the client and server with `GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info`?
And also, try turn on go http debug logs with `GODEBUG=http2debug=2`?

**Comment by dfawley** [comment]
ping @tannva-1559
