### ISSUE TITLE
Lots of newClientStream goroutines

### ISSUE THREAD

**Issue by danielmai** [grpc/grpc-go#2902]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
v1.13.0

### What version of Go are you using (`go version`)?
go1.12.5

### What operating system (Linux, Windows, …) and version?
Linux, Amazon Linux release 2 (Karoo) 4.14.114-105.126.amzn2.x86_64

### What did you expect to see?

I don't expect to see thousands of gRPC streaming requests. I'm not sure where they are coming from given that they're not one-to-one associated with incoming client requests.

### What did you see instead?

We're seeing thousands of goroutines for gRPC newClientStream, and the overall number of goroutines is growing over time. Here's a graph of the last day:

![Screenshot_2019-07-10 Go Processes - Grafana(4)](https://user-images.githubusercontent.com/2251820/61017552-76589380-a348-11e9-9147-e1ac7be99553.png)

Full goroutine stack dump: [goroutine.txt](https://github.com/grpc/grpc-go/files/3379966/goroutine.txt) with 7700 of the following gRPC newClientSteam goroutines:

```
goroutine 2630 [select, 11266 minutes]:
google.golang.org/grpc.newClientStream.func5(0xc33a488000, 0xc000126500, 0x16f5d20, 0xc0aeac3140)
    /tmp/go/src/google.golang.org/grpc/stream.go:324 +0xd7
created by google.golang.org/grpc.newClientStream
    /tmp/go/src/google.golang.org/grpc/stream.go:323 +0xa26
```

**Comment by menghanl** [comment]
Can you provide more information about what you did?

This sounds like stream leaks. Please double check your code and make sure one of these actions is performed to close the stream: https://godoc.org/google.golang.org/grpc#ClientConn.NewStream

**Comment by dfawley** [comment]
ping @danielmai
