### ISSUE TITLE
Client Concurrency

### ISSUE THREAD

**Issue by JamesMurkin** [grpc/grpc-go#2911]
Hello.

I have a question about client concurrency.

From reading https://github.com/grpc/grpc-go/issues/85 and https://github.com/grpc/grpc-go/blob/master/Documentation/concurrency.md

**I have gathered:**

- A connection object can be shared between multiple goroutines
- A stream should not be shared between multiple go routines (It is actually more subtle than this but I am not too bothered about this)

**I want to know:**

- Is is OK to share a client object between multiple goroutines?
- Will this mean the RPCs are sent in parallel, or will I need to make a client in each goroutine from a shared connection?

In issue 85 (above) this question was asked and answered (without much detail) that you can share the client object. However no discussion on if this would mean the RPC is sent in parallel.

However the documentation seems to suggest:

> Using helloworld as an example, one could share the ClientConn across multiple goroutines to create multiple GreeterClient types. In this case, RPCs would be sent in parallel

Which makes it seem like goroutines should each create their own client from a shared connection if they want the RPCs to be sent in parallel

**Comment by dfawley** [comment]
> Is is OK to share a client object between multiple goroutines?

Yes

> Will this mean the RPCs are sent in parallel, or will I need to make a client in each goroutine from a shared connection?

They will be sent in parallel.

> Which makes it seem like goroutines should each create their own client from a shared connection if they want the RPCs to be sent in parallel

Maybe the documentation should say "one or more GreeterClient types"?  The client wrappers from the generated code are also threadsafe.

**Comment by JamesMurkin** [comment]
Thanks a lot for this clarification. 

It is much appreciated, as this is one of this things that if you don't set it up right, appears to work for a while then gets you at a bad time :)

Yeah the documentation could be a little more explicit on what is considered threadsafe and what isn't. From what you said, most things are threadsafe however so generally quite easy to use once you know.
