### ISSUE TITLE
gRPC at the edge and combined reflection

### ISSUE THREAD

**Issue by mattbailey** [grpc/grpc-go#2912]
This might be a feature request, or maybe even a proposal to the reflection spec, but I'll start as a question.

I am would like to expose many gRPC services through a single edge.  Currently, I am using envoy to do path based routing to multiple gRPC services.

gRPC reflection requires (unless I'm missing something) to be served at the root at `/grpc.reflection.v1alpha.ServerReflection`, grpc-go doesn't appear to have a way to namespace it under a different path, and clients don't expect that either (e.g. grpcurl).

My current approach is to write a small proxy server that can combine the responses from many backends and host it as a combined `/grpc.reflection.v1alpha.ServerReflection`.

Has anyone else faced this kind of issue? Is this the best solution?

**Comment by dfawley** [comment]
@mattbailey sorry this got dropped.  Do you have any updates on this from your end?  Do you still need this?  Did your previous approach work well enough?  FWIW, your approach does feel like the best option given that there is no way to route based on the payload's contents.

**Comment by mattbailey** [comment]
My approach worked _well enough_ for what I needed to do, combined responses, and stored in an LRU.  It's only a convenient approach if I'm very consistent with hostnames and how they align with service symbols so I can do just in time discovery of servers that it should go ask reflection info from. This "feels" pretty fragile to me.

I'm really just throwing out the problem here to hopefully pull in others that have had the same thing to solve. I'm not sure if the solution lies under the purview of the grpc reflection spec itself or something like a proxy (I opened an issue in envoy as well).

**Comment by dfawley** [comment]
@ejona86 - any ideas about this?  I may have mentioned this issue to you awhile back (I intended to, anyway).

Looks like the envoy issue was closed due to lack of activity, but that they were open to a design proposal.  It seems to me that doing it in envoy (or any other reverse proxy that would be doing this kind of fowarding) would be the most viable long-term solution.

**Comment by ejona86** [comment]
I don't remember you mentioning it. Trying to have multiple instances of a service with different path prefixes is not supported and would not be encouraged. So doing this does require a custom reflection service implementation that combines results from backends.

**Comment by mattbailey** [comment]
@ejona86 not multiple instances of the same service, but multiple, discrete services with a single edge. i.e. path based routing to services rather than one host per service, for a single public edge.

**Comment by ejona86** [comment]
> Trying to have multiple instances of a service with different path prefixes

I was meaning for the reflection service. I understand that the "actual" services are disjoint across backends

CC @dklempner

**Comment by dklempner** [comment]
My mini-proposal for solving this family of problems is to extend the
protocol by
1. adding optionally to each DescriptorDatabase ServerReflection API the
method you'd want to call with this descriptor information
2. The ServerReflection API returns a validity prefix for responses to
calls with said method

Two example usecases solved by this protocol:
1. Path based routing has a straightforward ServerReflection proxy based
implementation which doesn't require any understanding of proto syntax in
order to merge potentially conflicting universes. (for example, even in a
single giant codebase like Google has internally where almost all code
agrees on proto import paths, two backend binaries built at different times
can have conflicting versions of the same proto)
2. A binary which exports services on the same port built with different
proto universes can have a sensible implementation of ServerReflection.

There's a fair bit of detail that would need to be hashed out, and it's not
clear that either of these usecases could be handled automatically at
grpc's level of abstraction without substantial application assistance, but
the protocol would at least work.

**Comment by mattbailey** [comment]
Thanks for the input, this is a hard problem to solve while still retaining the usefulness of reflection.

**Comment by dfawley** [comment]
I'm not sure there's anything else we can do on this for now, so I will close this issue.  If you believe gRPC should have support for something like this, please file an issue in the [main gRPC repo](http://github.com/grpc/grpc), since this would need to be done as a cross-language feature.  Thanks!
