### ISSUE TITLE
ClientConn.Target() not found 

### ISSUE THREAD

**Issue by Cjen1** [grpc/grpc-go#2913]
What version of protobuf and what language are you using?
v 1.14.0 and go

What did you do?
I'm using the etcd clientv3 package and to get the target of a request I am using:
`client.ActiveConnection.Target()`

This results in `client.ActiveConnection.Target undefined (type func() *grpc.ClientConn has no field or method Target`

Looking at my local `go/src/go.etcd.io/etcd/vendor/google.golang.org/grpc/clientconn.go` that method is in it, so I'm rather confused...

**Comment by menghanl** [comment]
It seems `ActiveConnection` is a method. Please try `client.ActiveConnection().Target()`.

**Comment by Cjen1** [comment]
Thanks sorry!
