### ISSUE TITLE
Unimplemented GRPC target method can't be resolved.

### ISSUE THREAD

**Issue by fbens** [grpc/grpc-go#2915]
When I use the gRPC to call the [Google gRPC API](https://developers.google.com/actions/smarthome/reference/rpc/),It returns rpc error like below:
```shell
could not greet: rpc error: code = Unimplemented desc = GRPC target method can't be resolved.
```

**Comment by fbens** [comment]
Problem solved.

**Comment by menghanl** [comment]
Closing now. Please reply if you have further questions.
