### ISSUE TITLE
How to define struct field in message 

### ISSUE THREAD

**Issue by fbens** [grpc/grpc-go#2916]
I'm using gRPC to call [Google HomeGraph](https://developers.google.com/actions/smarthome/reference/rpc/google.home.graph.v1),But some of the filed type is `struct` ,and some of them are end with `[]`,when I write with the tip name, procto can not Generate gRPC code.

**tip**
```shell
homegraph.proto:50:22: Missing field number.
homegraph.proto:58:44: Missing field number.
```
![003](https://user-images.githubusercontent.com/1414939/61517525-05953380-aa3a-11e9-8af6-836987531a7b.png)

**code**
in file homegraph.proto
```txt
message Device {
	string id = 1;
	string type = 2;
	string traits[] = 3;
	DeviceNames name = 4;
	bool will_report_state = 5;
	string room_hint = 6;
	string structure_hint = 7;
	DeviceInfo device_info = 8;
	Struct attributes = 9;
	string custom_data = 10;
	AgentOtherDeviceId other_device_ids[] = 11;
}
```

**Google**
according to their [documents Device](https://developers.google.com/actions/smarthome/reference/rpc/google.home.graph.v1#device),need type `struct` and some name is end with `[]`,like  `string traits[]`.

![001](https://user-images.githubusercontent.com/1414939/61517608-3ffed080-aa3a-11e9-917d-0d525e60999b.png)

**Comment by dfawley** [comment]
It seems like you are trying to write your own `.proto` file definition of the `google.home.graph.v1` package.  You can find them here instead: https://github.com/googleapis/googleapis/tree/master/google/home/graph/v1 and the generated code you should be importing into your programs at: https://github.com/googleapis/go-genproto/blob/master/googleapis/home/graph/v1

**Comment by fbens** [comment]
@dfawley Thank you very much.Now problems resolved. :-)

**Comment by fbens** [comment]
@dfawley 
Hi, I create the field use [`*_struct.Struct`](https://chromium.googlesource.com/external/github.com/google/go-genproto/+/refs/heads/master/googleapis/home/graph/v1/homegraph.pb.go#331), but I am very confused how to create a json string from `google.protobuf.Struct`: `states` of [ReportStateAndNotificationRequest:](https://developers.google.com/actions/smarthome/reference/rpc/google.home.graph.v1#google.home.graph.v1.ReportStateAndNotificationRequest)
```
{
  "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",
  "agentUserId": "1234",
  "payload": {
    "devices": {
      "states": {
        "123": {
          "on": true
        },
        "456": {
          "on": true,
          "brightness": 10
        }
      },
    }
  }
}
```

```
service HomeGraphApiService {
	rpc ReportStateAndNotification (ReportStateAndNotificationRequest) returns (ReportStateAndNotificationResponse) {
	}
}

message ReportStateAndNotificationDevice {
	google.protobuf.Struct states = 1;
	google.protobuf.Struct notifications = 2;
}

```

```go
// main.go
states := &_struct.Struct{}
```
![屏幕快照 2019-07-21 15 12 38](https://user-images.githubusercontent.com/1414939/61588209-01981b80-abca-11e9-8afb-d64e2f352d71.png)

**Comment by dfawley** [comment]
Hi @fbens, the definition of the proto-json struct message is here:
https://github.com/protocolbuffers/protobuf/blob/9857d636fd7814ab432669bf94d5aac7a1d1ffb2/src/google/protobuf/struct.proto#L51, and the generated code is here: https://github.com/golang/protobuf/blob/6c65a5562fc06764971b7c5d05c76c75e84bdbf7/ptypes/struct/struct.pb.go#L60.  You should be able to follow the fields defined there when creating the struct in your request.

If you need help beyond that, please try [stackoverflow](http://stackoverflow.com), the [protobuf](https://github.com/golang/protobuf) repo, or google's [support](https://developers.google.com/actions/support/) as these questions are not really grpc-related.  Thanks!
