### ISSUE TITLE
Field option json_name not work.

### ISSUE THREAD

**Issue by fbens** [grpc/grpc-go#2924]
I defined a field`request_id` use the option `[json_name="requestId"]` in a proto file like below:
```text
message ReportStateAndNotificationRequest {
	string request_id = 1 [json_name="requestId"];
}
```
After generate ,the code become `json:"request_id,omitempty"` instead of expected  `json:"requestId,omitempty"` like  below:

```go
type ReportStateAndNotificationRequest struct {
RequestId 	string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
// more generated code ...
}
```

How to let the protobuf generate the `json:"requestId"`.
because the key name of [Send Data JSON](https://developers.google.com/actions/smarthome/reference/rpc/google.home.graph.v1#google.home.graph.v1.ReportStateAndNotificationRequest) is not `request_id` but `requestId`:
```json
{
  "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",
  "agentUserId": "1234",
  "payload": {
    "devices": {
      "states": {
        "123": {
          "on": true
        },
        "456": {
          "on": true,
          "brightness": 10
        }
      },
    }
  }
}
```

**Comment by dfawley** [comment]
Hi @fbens.  json-proto is part of https://github.com/golang/protobuf, not grpc.  Please file your issue there instead.  Thanks!
