### ISSUE TITLE
Data race in sentLast between Send() and CloseSend()

### ISSUE THREAD

**Issue by howardjohn** [grpc/grpc-go#2927]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
v1.20.1
### What version of Go are you using (`go version`)?
v1.12.5

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
If possible, provide a recipe for reproducing the error.
Ran `go test -race` on github.com/istio/istio. 

### What did you expect to see?
No race detected in grpc code

### What did you see instead?
Test fails pointing to race in grpc code: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15684/istio-racetest-master/2150
```
==================
WARNING: DATA RACE
Read at 0x00c000cb15d0 by goroutine 234:
  istio.io/istio/vendor/google.golang.org/grpc.(*clientStream).SendMsg()
      /home/prow/go/src/istio.io/istio/vendor/google.golang.org/grpc/stream.go:674 +0xf8
  istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2.(*aggregatedDiscoveryServiceStreamAggregatedResourcesClient).Send()
      /home/prow/go/src/istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2/ads.pb.go:143 +0x6a
  istio.io/istio/pkg/adsc.(*ADSC).handleEDS()
      /home/prow/go/src/istio.io/istio/pkg/adsc/adsc.go:545 +0x5e8
  istio.io/istio/pkg/adsc.(*ADSC).handleRecv()
      /home/prow/go/src/istio.io/istio/pkg/adsc/adsc.go:306 +0x607

Previous write at 0x00c000cb15d0 by goroutine 535:
  istio.io/istio/vendor/google.golang.org/grpc.(*clientStream).CloseSend()
      /home/prow/go/src/istio.io/istio/vendor/google.golang.org/grpc/stream.go:757 +0x64
  istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2.(*aggregatedDiscoveryServiceStreamAggregatedResourcesClient).CloseSend()
      <autogenerated>:1 +0x62
  istio.io/istio/pkg/adsc.(*ADSC).Close()
      /home/prow/go/src/istio.io/istio/pkg/adsc/adsc.go:214 +0xbe
  istio.io/istio/pilot/pkg/proxy/envoy/v2_test.TestLDSEnvoyFilterWithWorkloadSelector.func2()
      /home/prow/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/lds_test.go:535 +0x57d
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163

Goroutine 234 (running) created at:
  istio.io/istio/pkg/adsc.(*ADSC).Run()
      /home/prow/go/src/istio.io/istio/pkg/adsc/adsc.go:253 +0x346
  istio.io/istio/pkg/adsc.Dial()
      /home/prow/go/src/istio.io/istio/pkg/adsc/adsc.go:160 +0x555
  istio.io/istio/pilot/pkg/proxy/envoy/v2_test.TestLDSEnvoyFilterWithWorkloadSelector.func2()
      /home/prow/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/lds_test.go:503 +0x2c7
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163

Goroutine 535 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:916 +0x65a
  istio.io/istio/pilot/pkg/proxy/envoy/v2_test.TestLDSEnvoyFilterWithWorkloadSelector()
      /home/prow/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/lds_test.go:502 +0x95b
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163
==================
```

So it is written at https://github.com/istio/istio/blob/aa554e793a6d7ed5b2857db79c87624ccefd07e9/pilot/pkg/proxy/envoy/v2/lds_test.go#L516 and read at https://github.com/istio/istio/blob/bafb4fb946c534c24d6ce9a83bf971048ac015cd/pkg/adsc/adsc.go#L545

Not clear to me how two different streams can have a race? Is the same stream object being reused?

**Comment by menghanl** [comment]
They are the same [stream](https://github.com/istio/istio/blob/bafb4fb946c534c24d6ce9a83bf971048ac015cd/pkg/adsc/adsc.go#L65), race is between [this `Send`](https://github.com/istio/istio/blob/bafb4fb946c534c24d6ce9a83bf971048ac015cd/pkg/adsc/adsc.go#L545) and [this `CloseSend`](https://github.com/istio/istio/blob/bafb4fb946c534c24d6ce9a83bf971048ac015cd/pkg/adsc/adsc.go#L214).

1. `CloseSend()` is actually a send action. It sends an `END_STREAM` to indicate there's no more message to be sent.
1. It's not safe to call two sends concurrently, as commented here: https://godoc.org/google.golang.org/grpc#ClientStream

---

Another problem I saw, and probably also the solution for this race, is that, `CloseSend` does __NOT__ close a stream. It's also __NOT__ necessary to call `CloseSend` when closing the stream.

The ways to ensure a stream is closed are mentioned here: https://godoc.org/google.golang.org/grpc#ClientConn.NewStream. The easiest way that works for you is to create the stream with a cancellable context, and cancel the context.

**Comment by howardjohn** [comment]
Thanks for looking into this so thoroughly! It seems like we can just not CloseSend and should be good. 

Since that will fix things you can close this if you want, but I am still not sure how this happened. Each test case is creating its own ADSC object so it should be a different stream I would think?

https://github.com/istio/istio/blob/d06ea0c0dae646ca67d15fe92645a9100ebdf980/pilot/pkg/proxy/envoy/v2/lds_test.go#L506 creates new object at https://github.com/istio/istio/blob/bafb4fb946c534c24d6ce9a83bf971048ac015cd/pkg/adsc/adsc.go#L136-L142 which later gets a stream added at https://github.com/istio/istio/blob/bafb4fb946c534c24d6ce9a83bf971048ac015cd/pkg/adsc/adsc.go#L247-L252

**Comment by menghanl** [comment]
From the stack trace, the race happened in test `TestLDSEnvoyFilterWithWorkloadSelector`.

In this test, `adsc.Dial()` is called to create `ADSC` with the stream in it. `Dial` also calls `Run`, which starts a goroutine (`go a.handleRecv()`) that calls `Send`.
In the same test, there's a `defer adsResponse.Close()` that will call `CloseSend`.
So there are two goroutines calling `Send`.

(Closing this issue now. But we can keep discussing here if you have other questions.)

**Comment by howardjohn** [comment]
Ah that makes perfect sense, I was thinking it was a race between multiple
test cases. Thanks!
