### ISSUE TITLE
Add SetContext to ServerStream/ClientStream

### ISSUE THREAD

**Issue by dzbarsky** [grpc/grpc-go#2928]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?

Sometimes you want to replace the context on the stream with one that has been amended with additional request metadata. Currently you have to wrap the stream with another struct and override Context (and store the new context in a pointer).

### Proposed Solution

Allow overriding Context on the stream itself (like http.Request)

**Comment by dfawley** [comment]
`ServerStream` and `ClientStream` are interfaces and cannot be extended.  The way we typically would implement something like this is via a global function in `grpc` that type asserts the `Stream` parameter and calls the appropriate method.

That said, as you mentioned, this kind of functionality is already achievable with interceptors - what problems are you facing with that approach?

**Comment by dzbarsky** [comment]
Interceptors work OK. It would have been nice in some ways to more closely mirror the http api that go developers are familiar with, but not worth breaking the interface.
