### ISSUE TITLE
Unexpected error when canceling a stream using compression

### ISSUE THREAD

**Issue by jasoncqiu** [grpc/grpc-go#2933]
### What version of gRPC are you using?
v1.22.0

### What version of Go are you using (`go version`)?
go version go1.12.6 linux/amd64

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
Start client-side streaming rpc with compression enabled, receive messages from a server that's consistently sending messages, and cancel the stream context on a different goroutine.

Can be reproduced using something like this pseudocode, with the server constantly sending messages:
```
	ctx, cancel := context.WithCancel(context.Background())
	clientStream := ClientSideStreamingRpc(ctx, grpc.UseCompressor(gzip.Name))
	go func() {
		for {
			_, err := clientStream.Recv()
			if err != nil {
				fmt.Printf("client failed to recv: %s\n", err)
			}
		}
	}()
	time.Sleep(100*time.Millisecond)
	cancel()
```
### What did you expect to see?
Expected Recv() errors to always be `rpc error: code = Canceled desc = context canceled`

### What did you see instead?
Recv() mostly returns error ``rpc error: code = Canceled desc = context canceled``, but sometimes `code = Internal desc = grpc: compressed flag set with identity or empty encoding` is returned instead.

**Comment by menghanl** [comment]
A client-side streaming RPC only gets one response from server. How do you have a server consistently sending messages in this case?

Also I tried with a bidi streaming RPC, and couldn't reproduce.
Can you provide your reproduction that I can run? Thanks!

**Comment by jasoncqiu** [comment]
Sorry got my terminology mixed up, what I'm doing is a server-side streaming RPC.

Attached a zip file of the reproduction, what I see when I run it:
```
while go run *.go; do :; done
subscriber failed to recv: rpc error: code = Internal desc = grpc: compressed flag set with identity or empty encoding
subscriber failed to recv: rpc error: code = Internal desc = grpc: compressed flag set with identity or empty encoding
subscriber failed to recv: rpc error: code = Canceled desc = context canceled
subscriber failed to recv: rpc error: code = Internal desc = grpc: compressed flag set with identity or empty encoding
subscriber failed to recv: rpc error: code = Canceled desc = context canceled
subscriber failed to recv: rpc error: code = Canceled desc = context canceled
subscriber failed to recv: rpc error: code = Internal desc = grpc: compressed flag set with identity or empty encoding
subscriber failed to recv: rpc error: code = Canceled desc = context canceled
subscriber failed to recv: rpc error: code = Internal desc = grpc: compressed flag set with identity or empty encoding
subscriber failed to recv: rpc error: code = Canceled desc = context canceled
subscriber failed to recv: rpc error: code = Canceled desc = context canceled
subscriber failed to recv: rpc error: code = Canceled desc = context canceled
```
[repro.zip](https://github.com/grpc/grpc-go/files/3433079/repro.zip)

**Comment by menghanl** [comment]
Thanks for the reproduction. Will have a fix shortly.
