### ISSUE TITLE
grpc-go server becomes unresponsive after Layer-3 congestion event

### ISSUE THREAD

**Issue by natemurthy** [grpc/grpc-go#2938]
### What version of gRPC are you using?
1.15

### What version of Go are you using (`go version`)?
1.12

### What operating system (Linux, Windows, …) and version?
Debian Linux (stretch-slim, kernel 4.15.0)

### What did you do?
This is a bizarre bug.  My company operates many of its own networks and data centers. On one occasion we observed our gRPC services become unresponsive after a network congestion event and did not recover.

There are many components in our networks. We are running an on-prem deployment of a few gRPC services in Kubernetes. We have clients in another VLAN connected to a switch that routes connections to another VLAN in our data center with a F5 load balancer in front of it. This data center houses our Kubernetes cluster and has an NGINX ingress controller with the grpc module enabled for routing all HTTP/2 traffic to a ClusterIP service backed by pods running the grpc-go  application containers described herein.

To summarize, here is the full path of all the unary and streaming RPCs along the connections that are established between all the hops described above.
```
clients <=> IRB VLAN switch <=> F5 load balancer <=> nginx-ingress <=> k8s service <=> pods
```

With the above details in mind, below is the full sequence of events.

The network has clients that are physically connected to a switch with IRB for routing and bridging between VLANs. Around 11:15 am one day we observed a brief spike in Layer-3 traffic on this switch effectively maxing out a 1 Gbps interface for a few minutes:

![1](https://user-images.githubusercontent.com/1788878/61925373-e35f5200-af20-11e9-9425-4d87e5c87964.png)

As this was happening and as traffic on the switch eventually decongested, we observed connections landing on one pod and piling up:

<img width="1126" alt="2" src="https://user-images.githubusercontent.com/1788878/61925363-d80c2680-af20-11e9-8f0c-ff5d784a18dd.png">

One can observe that this is not many connections, only on the order of hundreds.

On the client side we observed write requests began to taper off around the time of the congestion event,

<img width="1059" alt="3" src="https://user-images.githubusercontent.com/1788878/61925355-d0e51880-af20-11e9-9112-f799b01dede9.png">

but even after relieved of congestion on the switch, write requests were near zero except for around 11:55a when we observed a brief respite along with one:
```
rpc error: code = Unavailable desc = transport is closing
```
error log captured from each client.

The clients backoff their gRPC requests exponentially, however we only observed a single retry attempt over this 40 minute outage in our logs from each client, implying that the RPC itself on each client was somehow blocked and timing out and not exceeding context deadlines. Also, grpc requests tapered, declined, and recovered in a similar fashion based on logs from our nginx-ingress controller.

The result of all these blocked RPCs is a build of messages on all the clients until we eventually deleted the grpc-go pods.

<img width="1139" alt="4" src="https://user-images.githubusercontent.com/1788878/61925331-b612a400-af20-11e9-8fcb-e8b124f03116.png">

At around 12:24pm we performed a rolling restart on all the pods running the grpc-go application containers, and as observed in the charts above, stale connections were closed, subsequently rebalancing more evenly, writes resumed successfully, and messages piled up on the clients flushed themselves immediately after being written upstream

Unfortunately I do not have a pprof of all the go clients and servers during this outage. And although I've only observed this once and cannot reproduce it, this is a critical path and will raise alarms where I work if this is not resolved.

### What did you expect to see?
I expected to see connections balanced evenly across gRPC pods and for the pods to not become unresponsive due to a small network switch congestion blip. In the case of the pods becoming unresponsive, we would normally expect to see gRPC failures exponentially backing off in our error logs, but this too did not occur. 

### What did you see instead?
Instead, I observed one pod accumulate all the connections after the congestion event and the gRPC pods become unresponsive.

### Addendum
I'm anticipating someone to tell me to just upgrade to a newer version of grpc on all my clients and servers. Although it can be done, it is somewhat of a non-trivial task given how complex my organization is, and I am more interested in understanding how this can happen while noting that we've been using this particular version of the grpc-go libaries for nearly a year without having to upgrade.

It might also be that we have a silent application bug in our client or server code whereby a goroutine handling the RPC blocks thus blocking subsequent RPCs. There could also be an issue with the nginx ingress controller similar to what is noted [here](https://github.com/kubernetes/ingress-nginx/issues/4054) and already resolved. But within the scope of this repository, I would like to rule out any possible issues with the grpc-go library particularly regarding sensitivity to Layer-3 network congestion that could affect the state of already established Layer-4 connections from grpc-go clients to grpc-go servers.

**Comment by natemurthy** [comment]
Pinging @menghanl @dfawley , looking for 👀when either of you have a chance :)

**Comment by menghanl** [comment]
Do you happen to have logs from the client during the failure? That could give us some hints on what happened (e.g. whether connection was broken, whether reconnecting happened).

Some questions/thoughts I have so far:
1. Do you use balancer? I'm guess something like roundrobin, but want to confirm.
1. Do you have keepalive enabled?
   - One guess is the connection is down, but the TCP connection was not properly closed. Keepalive would help in this case.
1. Do you set timeout on RPCs? And did you get many deadline exceeded or you got mostly just "transport is closing"?

**Comment by natemurthy** [comment]
> Do you happen to have logs from the client during the failure?

Over the entire outage duration (11:15 - 12:25), these were the only error logs we observed on each client:
```
11:55:25.159 - rpc error: code = Unavailable desc = transport is closing
12:24:40.614 - rpc error: code = Internal desc = transport: received the unexpected content-type "text/html"		
```
The log at 12:24 is due to us restarting all the pods and the nginx ingress serving up its canonical 404 page.

And responding to your remaining list of questions and thoughts in order:

1. We are not using the grpc-go balancer.

2. Yes, on the client we have this:
```go
kacp := keepalive.ClientParameters{
	Time:                25 * time.Second,
	Timeout:             5 * time.Second,
	PermitWithoutStream: true,
}
conn, err := grpc.Dial(addr, creds, grpc.WithKeepaliveParams(kacp))
```

3. If you are referring to setting `context.WithTimeout` on the `ctx` passed into the RPC on the client side, we are not. (thinking to myself as I write this: "aha, this is probably something I need to do!")

**Comment by menghanl** [comment]
You mentioned in the original post
> I expected to see connections balanced evenly across gRPC pods and for the pods to not become unresponsive due to a small network switch congestion blip.

But if you are not using balancer, how does that work? Is it done by a lower level load balancer?
If so, how does it re-balance after a breakage?

About logging, you can turn on grpc logs following https://github.com/grpc/grpc-go#how-to-turn-on-logging or installing your own logger https://godoc.org/google.golang.org/grpc/grpclog#SetLoggerV2

---

It's hard to figure out what actually happened with the given information. We will need more detailed information. Let us know if you get more information.

**Comment by natemurthy** [comment]
To answer:

> But if you are not using balancer, how does that work? Is it done by a lower level load balancer?
If so, how does it re-balance after a breakage?

We are not using the grpc-go balancer, but we have an [F5](https://www.f5.com/products/big-ip-services/local-traffic-manager) in front of our data center load balancing connections to nodes in the cluster, and once they land on a node the nginx ingress controller balances connections to pods.

For future reference, we will enable grpc logs. Thank you Menghan.

**Comment by menghanl** [comment]
> We are not using the grpc-go balancer, but we have an F5 in front of our data center load balancing connections to nodes in the cluster, and once they land on a node the nginx ingress controller balances connections to pods.

Is the load balancing done for each connection? Does it re-balance if some nodes are down and come back?

gRPC creates connections to backends, and reuse the connections for different RPCs. So if connections are created to the only working node while the other nodes are done, the loads won't be re-balanced to the other nodes even after they come back.

**Comment by natemurthy** [comment]
> Is the load balancing done for each connection? Does it re-balance if some nodes are down and come back?

Yes, and yes.

Btw, had a chance to enable logging, still haven't been able to reproduce the issue. Nothing unusual on the client side:
```
INFO: 2019/07/31 12:26:34 parsed scheme: ""
INFO: 2019/07/31 12:26:34 scheme "" not registered, fallback to default scheme
INFO: 2019/07/31 12:26:34 ccResolverWrapper: sending new addresses to cc: [{REDACTED:50052 0  <nil>}]
INFO: 2019/07/31 12:26:34 ClientConn switching balancer to "pick_first"
INFO: 2019/07/31 12:26:34 pickfirstBalancer: HandleSubConnStateChange: 0xc000065910, CONNECTING
INFO: 2019/07/31 12:26:34 blockingPicker: the picked transport is not ready, loop back to repick
INFO: 2019/07/31 12:26:34 pickfirstBalancer: HandleSubConnStateChange: 0xc000065910, READY
```
but what I found odd on the server side is that the only grpc-go logs I see are of the form:
```
INFO: 2019/07/31 12:26:34 transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```

**Comment by menghanl** [comment]
>> Is the load balancing done for each connection? Does it re-balance if some nodes are down and come back?

> Yes, and yes.

About re-balancing. Note that client will __NOT__ recreate connections when the broken backends come back. Reconnection only happens when the existing connection is down. If re-balancing only works for new connections, it won't work in this failure.

---

Usually client logs are more useful, and show more information.
We don't have as much server logs as client.
