### ISSUE TITLE
Streams end up spending significant time growing the stack

### ISSUE THREAD

**Issue by dzbarsky** [grpc/grpc-go#2942]
### What version of gRPC are you using?
Master

### What version of Go are you using (`go version`)?
1.12

### What operating system (Linux, Windows, …) and version?
ubuntu 16.04

### What did you do?
See https://github.com/grpc/grpc-go/blob/b5748caae736985df50f394cdc363e33fb3989c8/server.go#L703-L712

We end up spawning a new goroutine to handle the stream, which will end up growing the stack later (when it is much more expensive, due to more pointers/defers to update). See https://github.com/golang/go/issues/18138 for more context. The `growStack` hack described there could solve it. 

In terms of impact, this is around 50% of `parser.recvMsg` and around 15% overall time of serving StreamUnary rpc in our server. Interestingly enough, the same server serving UnaryUnary RPC does not end up running into this issue.

**Comment by canguler** [comment]
This looks worth trying. Do you have time to try the hack and see how much it helps?

**Comment by dzbarsky** [comment]
Hmm so I gave this a stab and even with 128kb stack i'm still seeing the same `newstack` call. 
I also ran an experiment where I made the stream handler push the request into a channel for background goroutines to handle (which end up growing the stack after the first request), which made one of the 2 `newstack` calls disappear, but the one inside grpc.NewContextWithServerStream remains. See https://www.dropbox.com/s/pbk8gnhl4rp3qjb/Screenshot%202019-07-30%2017.56.32.png?dl=0

Once thing to note - we have custom dropbox-specific grpc stubs, so perhaps we are doing something terrible in there? Anyone have suggestion to see what's taking up space on the stack?

**Comment by canguler** [comment]
Hi @dzbarsky,

I am also curious about your testing methodology. Which code are you profiling?

**Comment by dzbarsky** [comment]
Sorry for the silence. We have internal benchmarks of our rpc stack (which is grpc integrated with dropbox infrastructure like service discovery, etc.) Unfortunately I wasn't able to convince the go runtime to upsize the initial stack. I'll probably play around with patching the runtime in a less hacky fashion to satisfy my curious but it doesn't look like I'll come up with a grpc patch that would improve things here.
