### ISSUE TITLE
error while using google.golang.org/grpc from a vendor directory

### ISSUE THREAD

**Issue by dayadev** [grpc/grpc-go#2948]
I am having issues using google.golang.org/grpc  from vendor directory and I get the below error

`cannot use &metadata.HeaderMD (type *"google.golang.org/grpc/metadata".MD) as type *"project1/vendor/google.golang.org/grpc/metadata".MD in argument to grpc.Header
`

I get the error though I am using the necessary version of the package which I copied from my gopath. But, when I delete the golang.google.org/grpc folder from vendor my project fetches the dependency from gopath and it works fine though the one gopath is a copy of when I have in vendor directory and every other library in vendor directory works fine except grpc.

**Comment by menghanl** [comment]
gRPC doesn't have anything that needs special vendor handling.

Please check your vendor setup. Or, use a tool to manage vendor instead of doing it manually.
