### ISSUE TITLE
Server keep alive not closing client connection

### ISSUE THREAD

**Issue by anjmao** [grpc/grpc-go#2955]
### What version of gRPC are you using?
v1.22.1

### What version of Go are you using (`go version`)?
go version go1.12.6 darwin/amd64

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
On server site I'm using grpc with keep alive set.
```go
keepalivePolicy = keepalive.EnforcementPolicy{
	MinTime:             5 * time.Second, 
	PermitWithoutStream: true,
}

keepaliveParams = keepalive.ServerParameters{
	MaxConnectionIdle:     1 * time.Hour,
	MaxConnectionAge:      1 * time.Hour, 
	MaxConnectionAgeGrace: 5 * time.Second,
	Time:                  10 * time.Second,
	Timeout:               5 * time.Second,
}
```

On client side I'm using swift-grpc and iOS.

After I connect to server's bidirectional stream I see logs on server

```
2019/08/05 15:31:29 http2: Framer 0xc00016ed20: wrote HEADERS flags=END_HEADERS stream=1 len=16
2019/08/05 15:31:29 http2: Framer 0xc00016ed20: wrote DATA stream=1 len=5 data="\x00\x00\x00\x00\x00"
2019/08/05 15:31:30 http2: Framer 0xc00016ed20: read DATA stream=1 len=5 data="\x00\x00\x00\x00\x00"
2019/08/05 15:31:30 http2: Framer 0xc00016ed20: wrote WINDOW_UPDATE len=4 (conn) incr=5
2019/08/05 15:31:30 http2: Framer 0xc00016ed20: wrote PING len=8 ping="\x02\x04\x10\x10\t\x0e\a\a"
2019/08/05 15:31:30 http2: Framer 0xc00016ed20: read PING flags=ACK len=8 ping="\x02\x04\x10\x10\t\x0e\a\a"
2019/08/05 15:31:30 http2: Framer 0xc00051e000: wrote SETTINGS len=0
2019/08/05 15:31:30 http2: Framer 0xc00051e000: read SETTINGS len=18, settings: HEADER_TABLE_SIZE=0, ENABLE_PUSH=0, INITIAL_WINDOW_SIZE=2147483647
2019/08/05 15:31:30 http2: Framer 0xc00051e000: read WINDOW_UPDATE len=4 (conn) incr=2147418112
2019/08/05 15:31:30 http2: Framer 0xc00051e000: read HEADERS flags=END_HEADERS stream=1 len=443
2019/08/05 15:31:30 http2: decoded hpack field header field ":method" = "POST"
2019/08/05 15:31:30 http2: decoded hpack field header field ":scheme" = "http"
2019/08/05 15:31:30 http2: Framer 0xc00051e000: wrote SETTINGS flags=ACK len=0
2019/08/05 15:31:30 http2: decoded hpack field header field ":path" = "/stats.Stats/Connect"
2019/08/05 15:31:30 http2: decoded hpack field header field "host" = "staging.my-app.net:443"
2019/08/05 15:31:30 http2: decoded hpack field header field "connection" = "close"
2019/08/05 15:31:30 http2: decoded hpack field header field "x-request-id" = "a390ba5dd7c0668e5dc02b8959647d69"
2019/08/05 15:31:30 http2: decoded hpack field header field "x-real-ip" = "90.131.xx.xxx"
2019/08/05 15:31:30 http2: decoded hpack field header field "x-forwarded-for" = "90.131.xx.xxx"
2019/08/05 15:31:30 http2: decoded hpack field header field "x-forwarded-host" = "staging.my-app.net:443"
2019/08/05 15:31:30 http2: decoded hpack field header field "x-forwarded-port" = "443"
2019/08/05 15:31:30 http2: decoded hpack field header field "x-forwarded-proto" = "https"
2019/08/05 15:31:30 http2: decoded hpack field header field "x-original-uri" = "/stats.Stats/Connect"
2019/08/05 15:31:30 http2: decoded hpack field header field "x-scheme" = "https"
2019/08/05 15:31:30 http2: decoded hpack field header field "te" = "trailers"
2019/08/05 15:31:30 http2: decoded hpack field header field "x-version" = "1.3.0.1"
2019/08/05 15:31:30 http2: decoded hpack field header field "content-type" = "application/grpc"
2019/08/05 15:31:30 http2: decoded hpack field header field "user-agent" = "grpc-c/7.0.0 (ios; chttp2; gold)"
2019/08/05 15:31:30 http2: decoded hpack field header field "grpc-accept-encoding" = "identity,deflate,gzip"
2019/08/05 15:31:30 http2: decoded hpack field header field "accept-encoding" = "identity,gzip"
2019/08/05 15:31:30 http2: decoded hpack field header field "grpc-timeout" = "8M"
```

Then I disable internet connection on my mobile device. 
On server I see server keep alive pings.

```
2019/08/05 15:38:35 http2: Framer 0xc00051e000: wrote PING len=8 ping="\x00\x00\x00\x00\x00\x00\x00\x00"
2019/08/05 15:38:35 http2: Framer 0xc00051e000: read PING flags=ACK len=8 ping="\x00\x00\x00\x00\x00\x00\x00\x00"
```

### What did you expect to see?
I starter my stream at **18:42:55** and expect it to close after ~15 seconds (keep alive ping interval + ack timeout).

### What did you see instead?
Stream is closed after 18:50:55. What I understand is that I set grpc-timeout of 8 minutes in client side so this is why it is closed only after this period of time.  I found this code in go server implementation which checks for this header https://github.com/grpc/grpc-go/blob/eca11cb9e47ddbe78dc0819ce345cb283450a135/internal/transport/handler_server.go#L78

I think server should ignore grpc-timeout header for streaming calls if server's keep alive is configured.

**Comment by menghanl** [comment]
If my understanding is correct, what you want is for the client to detect connection problem after internet is disable. If so, you need client side keepalive, not server side.

**Comment by anjmao** [comment]
Nope. I want server to detect that client is not alive anymore. Imagine if mobile is switching network interfaces from wifi to cellural, in such case you can’t easily close previous stream so only server could detect if connection is not alive.

**Comment by menghanl** [comment]
On server side, when the connection is closed, all the streams' context will be canceled.

From these two lines
> ```
> 2019/08/05 15:38:35 http2: Framer 0xc00051e000: wrote PING len=8 ping="\x00\x00\x00\x00\x00\x00\x00\x00"
> 2019/08/05 15:38:35 http2: Framer 0xc00051e000: read PING flags=ACK len=8 ping="\x00\x00\x00\x00\x00\x00\x00\x00"
> ```

It seems server got a ping ack. If client's internet is disabled, this ack should not happen.
Do you have a proxy in between that will ack the pings?

**Comment by anjmao** [comment]
@menghanl Yes I have ngnix proxy. You are right, the problem is that I configured ngnix for 1 hour timeout in my ingress.

```
nginx.ingress.kubernetes.io/server-snippet: |
      grpc_read_timeout 3600s;
      grpc_send_timeout 3600s;
      client_body_timeout 3600s;
```

It now make sense that keepalive.ServerParameters Timeout is not working as expected since ngnix is doing ping ack.

I'm closing this issue as this is not grpc specific issue. Do have any examples how to setup proper keep alive settings when using proxy like ngnix? Thanks a lot.

**Comment by menghanl** [comment]
I don't know how to configure ngnix for keepalive.
If there's a setting to forward the keepalive pings instead of ack, that should work. But I don't know if such setting exists.

It will be great if you can comment here when you find out how to do it. Thanks!

**Comment by anjmao** [comment]
Issue for traefik https://github.com/containous/traefik/issues/5181
Issue for ngnix ingress https://github.com/kubernetes/ingress-nginx/issues/4402
