### ISSUE TITLE
grpc connection doesn't release memory after closing connection

### ISSUE THREAD

**Issue by jayeshwebcluesglobal** [grpc/grpc-go#2961]
Please see the FAQ in our main README.md before submitting your issue.

**Comment by jayeshwebcluesglobal** [comment]
we are making large number of concurrent connections and also we are closing each connections
but memory doesn't free event after closing each connections

**Comment by jayeshwebcluesglobal** [comment]
This is how we make connection from client

func BootstrapSync(self api.Contact, target *api.Contact, request api.Request, channel chan []byte, wg *sync.WaitGroup) *api.BootstarpSyncResponse {

	conn, err := grpc.Dial(target.Address, grpc.WithInsecure(), grpc.WithDefaultCallOptions(
		grpc.MaxCallRecvMsgSize(MaxMsgSize),
		grpc.MaxCallSendMsgSize(MaxMsgSize),
	))

	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}

	client := api.NewPingClient(conn)
	defer conn.Close()

	request.Sender = &self
	request.Target = target
	response := &api.BootstarpSyncResponse{}
	if request.Action != "" {
		response, err = client.SyncAction(context.Background(), &request)
	} else {
		response, err = client.Sync(context.Background(), &request)
	}
	if err != nil {
		log.Fatalf("Error when calling Sync: %s", err)
	}

	if wg != nil {
		wg.Done()
	}
	if channel != nil && response.Data != nil {
		channel <- response.Data
	}

	return response
}

**Comment by jayeshwebcluesglobal** [comment]
![Screenshot from 2019-08-07 14-50-12](https://user-images.githubusercontent.com/29976553/62611249-d845f200-b922-11e9-8ee5-908fdfad2e56.png)

**Comment by jayeshwebcluesglobal** [comment]
pprof showing transport.newBufWritter keep increasing when we make more requests

**Comment by jayeshwebcluesglobal** [comment]
![Screenshot from 2019-08-07 15-03-58](https://user-images.githubusercontent.com/29976553/62612224-9e75eb00-b924-11e9-87b3-e6f1d7d26d9c.png)

**Comment by menghanl** [comment]
120 MB is not a huge amount of memory, and is not necessary a leak.
Does it keep increasing as your program runs?

Also, one thing to mention is, you don't need to create a new ClientConn for each RPC. The ClientConn can be reused to perform multiple RPCs, so you can save the overhead for creating connections.

**Comment by jayeshwebcluesglobal** [comment]
It is keep increasing, this is for one port, i am making 100s grpc servers on a single machine
So memory is increasing in GBs and it is not getting free

**Comment by jayeshwebcluesglobal** [comment]
@menghanl I am creating more then 100k connections, i tried by saving connections and used same one but still it is increasing memory drastically

**Comment by jayeshwebcluesglobal** [comment]
google.golang.org/grpc/internal/transport.newFramer /usr/local/go/src/google.golang.org/grpc/internal/transport/http_util.go:665

This line shows the memory usage

**Comment by menghanl** [comment]
Are your RPCs working normally? Do they finish in time?

The buffer you're referring to is allocated for each connection. So if you are making a log of connections, it's expected that a lot of memory is allocated.
They are freed when the connection is closed, so make sure to closed the connections when they are done.

It will also be helpful if you can provide code to reproduce this problem, so we can take a further look.

**Comment by jayeshwebcluesglobal** [comment]
@menghanl I have changed temporary to permanent connections and now it is not showing memory increase at newFramer but now memory is increasing at reflect.new, can you please help me what is wrong here

![Screenshot from 2019-08-09 20-39-55](https://user-images.githubusercontent.com/29976553/62789152-f871de80-bae5-11e9-9f87-d960ca2dce25.png)

**Comment by menghanl** [comment]
This seems to be the memory allocated for proto messages. The size should be correlated to your message size and the number of RPCs sent.
This memory will be garbage collected when you release the reference to them.

**Comment by jayeshwebcluesglobal** [comment]
@menghanl Yes it is correlated to message size and number of RPCs sent. but it is not freed by GC even if i wait to 10-15 mins

**Comment by menghanl** [comment]
Downgrading go version might be a good walkaround, but doesn't solve the problem. If this is a real leak, you will be affected again when you upgrade later.

It will be great if you can try to reproduce this with a minimal client and server. So we can take a further look. Thanks!
