### ISSUE TITLE
grpclog: log levels should be exported

### ISSUE THREAD

**Issue by rogpeppe** [grpc/grpc-go#2963]
version: 36ddeccf18604a5cb0fb17ceea9c24dffeb5b034

The `LoggerV2` interface contains a `V` method with an `int` argument.
The possible values for that argument are not documented, which makes it awkward (and potentially unstable) to implement a version of `V` or use it. In my specific case, I'm trying to provide an adaptor from grpc logging to [logrus](https://godoc.org/github.com/sirupsen/logrus), but this applies to anyone that might want to use the `LoggerV2` interface or implement it.

The workaround is to return `true` always, but it would be nice for efficiency reasons to do better than that.

I propose that the following constants be exported:

```
const (
	// infoLog indicates Info severity.
	infoLog int = iota
	// warningLog indicates Warning severity.
	warningLog
	// errorLog indicates Error severity.
	errorLog
	// fatalLog indicates Fatal severity.
	fatalLog
)
```

Perhaps also rename them to `InfoLevel`, `WarningLevel` etc to reflect the "level" terminology used in the documentation for the `V` method.

**Comment by menghanl** [comment]
Log level (severity) and verbose level are two dimensions.
```
log.V(2).Info()
log.V(2).Error()
log.V(3).Info()
log.V(3).Error()
```

**Comment by rogpeppe** [comment]
I don't understand. The V method returns a bool, and only takes one argument. How is that two-dimensional?

**Comment by rogpeppe** [comment]
Also, how is any code external to the package expected to know what 2 and 3 mean?

**Comment by rogpeppe** [comment]
@menghanl Perhaps you could explain a bit more. The code you included [seems to be invalid to me](https://play.golang.org/p/-qZgwnaOTPz).

**Comment by menghanl** [comment]
The same feature set as in https://github.com/golang/glog is supported.

2 and 3 (and other integers) are verbose levels, that users usually specify as command line parameters (with "-v=2").
Users can also specify the logging severity, like "-severity=error" to only log errors.
In gRPC, by default, those are configured by environment variables: https://github.com/grpc/grpc-go#how-to-turn-on-logging

We didn't add support for `Infof` on `V` (#2713). Those were listed as examples of using verbose level and severity level.
The following should work. The point I wanted to make is, you can log `verbose-level-2, info`, `verbose-level-2, error` and also `verbose-level-3, info`. Verbose level and severity level are two dimensions.
```
if log.V(2) { Info() }
if log.V(2) { Error() }
if log.V(3) { Info() }
if log.V(3) { Error() }
```

**Comment by rogpeppe** [comment]
Ah, thanks for the explanation. Forgive my obtusity: I haven't seen any logger implementation until now that had severity and verbosity as independent dimensions - most loggers seem to use "Debug" and "Info" levels to the similar effect (which _almost_ maps OK to the way that grpclog uses verbosity, except that there's one case where an Error call is suppressed at lower verbosity). It's slightly unfortunate that there's no way for a `LoggerV2` implementation to know what verbosity level is guarding a given message, so no way to choose how to map it to an underlying severity-only-based logger.
