### ISSUE TITLE
Is there a hook for server when the connection lost from client

### ISSUE THREAD

**Issue by zj8487** [grpc/grpc-go#297]
the scene is as follow:
```
when client close or lose the connection and server want to do some resource clean
```

**Comment by iamqizhao** [comment]
It won't be in beta. But I can do something after beta. To do that, can you elaborate your requirements a bit?

**Comment by zj8487** [comment]
ok, it will in my later post!

**Comment by zj8487** [comment]
# Shortage of abilitys for grpc
* Checking the connection on client and server end
* Marking the connection on client and server end

## Checking the connection on client and server end
**Why need the ability?**

Both client and server should know the status of the connection to the other side, so that the each end can do some work tor it. for example, reconnect, destroy the resource.
maybe you will say we can monitor the service status by zookeeper, etcd. yes, you are right. but it will not  work on mobile client.

**What is the status of the connection?**

* heartbeat timeout
  grpc should supply the ability to config the heartbeat. the options is as follow:
  * enable the heartbeat detect ---if no, no heartbeat package will send to detect the connection.
  * the interval for the heartbeat package----send the heartbeat package every interval
  * heartbeat timeout time----if no package received in the time, ```heartbeat timeout hook``` will be triggerd
   * handshake between client and server. the client should detect the connection like server. but should use the same config as above used in server side. so handshake is needed to sync the config.

   ***if the handshake is possible to sync the custom config is better***

* connection lost for reason, ETIMEDOUT, EHOSTDOWN, EHOSTUNREACH, etc.
  if the event of connection tiggerd, the hook will trggered

## Marking the connection on client and server end
**Why need the ability?**
In general, we can not give every connection a hook. so we should know the owner of the connection in the hook.
for exapmle, if a client logon by a ```login rpc function```, and then we record the userId or user object on the connection. and then, we will know who is lost in the hook function. 

@iamqizhao

**Comment by iamqizhao** [comment]
See my comments inline. I still do not see a compelling reason to have
server side per-connection hook.

On Tue, Aug 18, 2015 at 6:53 PM, zj8487 <notifications@github.com> wrote:

> Shortage of abilitys for grpc
>
>    - Checking the connection on client and server end
>    - Marking the connection on client and server end
>
> Checking the connection on client and server end
>
> *Why need the ability?*
>
> Both client and server should know the status of the connection to the
> other side, so that the each end can do some work tor it. for example,
> reconnect, destroy the resource.
> maybe you will say we can monitor the service status by zookeeper, etcd.
> yes, you are right. but it will not work on mobile client.
>
We have channel state API on client side now.  See
https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md
.

> *What is the status of the connection?*
>
>    -
>
>    heartbeat timeout
>
> This is the health check service we have implemented. See
https://github.com/grpc/grpc/blob/master/doc/health-checking.md

>
>    -
>
>    grpc should supply the ability to config the heartbeat. the options is
>    as follow:
>    - enable the heartbeat detect ---if no, no heartbeat package will send
>       to detect the connection.
>       - the interval for the heartbeat package----send the heartbeat
>       package every interval
>       - heartbeat timeout time----if no package received in the time, heartbeat
>       timeout hook will be triggerd
>       - handshake between client and server. the client should detect the
>       connection like server. but should use the same config as above used in
>       server side. so handshake is needed to sync the config.
>
>    *if the handshake is possible to sync the custom config is better*
>    -
>
>    connection lost for reason, ETIMEDOUT, EHOSTDOWN, EHOSTUNREACH, etc.
>    if the event of connection tiggerd, the hook will trggered
>
> Marking the connection on client and server end
>
> *Why need the ability?*
> In general, we can not give every connection a hook. so we should know the
> owner of the connection in the hook.
> for exapmle, if a client logon by a login rpc function, and then we
> record the userId or user object on the connection. and then, we will know
> who is lost in the hook function.
>
I do not see per-connection hook is required here. Why does you care
connection on server side?

**Comment by zj8487** [comment]
@iamqizhao 
### Why does i care connection on server side?
Scene: 
* some mobile client connect to a grpc server.
* there are some different state for every client on the server.
* the server should destroy the resource and clean the state of the user lost connection.

### Health checks 
* Health checks are used to probe whether the server is able to handle rpcs, but it can not check if client is alive.
* it is not automatic, it need user layer to start a timer.

**Comment by zj8487** [comment]
@iamqizhao 
Health check will satisfy the need

**Comment by joseAndresGomezTovar** [comment]
I have the same requirement, because:
- I want to run a DLL remotely
Scenary:
- I have a main process and tow dlls
- one of these dll will be run using the gRPC server
- By making a new dll "**gRPC client**" that is loaded in the main process, I remotely connect the original "dll" with the main process

The **gRPC server** loads the "original dll" when the _connection is established_, and it downloads it when it _breaks_

thank you in advance
