### ISSUE TITLE
How many connections should I create in a large concurrency ?

### ISSUE THREAD

**Issue by Astone-Chou** [grpc/grpc-go#2975]
I was using grpc in bidirectional streaming mode. If I have 10k streams. Should I create `runtime.NumCPU` of `grpc.ClientConn` to improve throughput ?

**Comment by canguler** [comment]
Hi @Astone-Chou,

It really depends on your situation. Ideally, to a single server, one ClientConn should be enough. But again, if you are seeing a lot of contention on that connection, then it makes sense for you to increase the number of connections.
