### ISSUE TITLE
Memory Leaks in InTap when context has no timeout

### ISSUE THREAD

**Issue by venuchitta** [grpc/grpc-go#2976]
I went though https://github.com/grpc/grpc-go/issues/2532 where @dfawley mentioned that `InTap` should have context timeout. But no where in the documentation it is mentioned that context should have timeout and also I am curious to know what if client misuses without sending context timeout. 

I can create MR for any outcome for this thread.

### What version of gRPC are you using?
v1.15.0

### What version of Go are you using (`go version`)?
go1.11.5

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
Just add InTapHandler to greeter_server example rejecting every request and `ulimit` memory to 400MB. On Client side, fired 5000 reqs per sec with no context timeout and of-course every request fails with `REFUSED_STREAM`.
Here is the server code:
```
package main

import (
	"context"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/grpc/tap"
	"log"
	"net"
	"syscall"

	"google.golang.org/grpc"
	pb "google.golang.org/grpc/examples/helloworld/helloworld"
)

const (
	port = ":50051"
	MB   = 1024 * 1024
)

var resExhaustedErr = status.New(codes.ResourceExhausted, "Ratelimitted").Err()

func inTapHandler(ctx context.Context, info *tap.Info) (context.Context, error) {
	return ctx, resExhaustedErr
}

// server is used to implement helloworld.GreeterServer.
type server struct{}


// SayHello implements helloworld.GreeterServer
func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
	return &pb.HelloReply{Message: "Hello " + in.Name}, nil
}

func main() {
	syscall.Setrlimit(syscall.RLIMIT_AS, &syscall.Rlimit{
		Cur: 300 * MB,
		Max: 300 * MB,
	})
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	s := grpc.NewServer(grpc.InTapHandle(inTapHandler))
	pb.RegisterGreeterServer(s, &server{})
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
```

### What did you expect to see?
Server never runs out of memory.

### What did you see instead?
Server running out of memory after some time. This could be because context is never cancelled on server side and memory keeps growing until server runs out of memory.

**Comment by canguler** [comment]
Hi @venuchitta,


I can reproduce your issue, but the weird thing is that server is running out of memory even with a timeout.

Can you try running the same test with the latest gRPC version? What happens when you introduce a timeout? Do you still see server running out of memory?

Can you also please share your client code?

**Comment by venuchitta** [comment]
Thanks for having a look @canguler. Here is the client code I have used:
```
// Package main implements a client for Greeter service.
package main

import (
	"context"
	"fmt"
	"log"
	"time"

	"google.golang.org/grpc"
	pb "google.golang.org/grpc/examples/helloworld/helloworld"
)

const (
	qpsPerSec   = 5000
	grpcAddress = "localhost"
)

func main() {
	// Set up a connection to the server.
	conn, err := grpc.Dial(fmt.Sprintf("%s:50051", grpcAddress), grpc.WithInsecure())
	defer conn.Close()
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	c := pb.NewGreeterClient(conn)

	ticker := time.NewTicker(1 * time.Second)
	quit := make(chan bool, 1)
	go func() {
		for {
			select {
			case <-ticker.C:
				for i := int64(0); i < qpsPerSec; i++ {
					go func() {
						//ctx := context.Background()
						ctx, cancelFunc := context.WithTimeout(context.Background(), time.Second * 5)
						defer cancelFunc()
						c.SayHello(ctx, &pb.HelloRequest{})
					}()
				}
			case <-quit:
				ticker.Stop()
				return
			}
		}
	}()

	log.Println("Sleeping while firing requests")
	time.Sleep(time.Minute * 30)
	quit<-true
	log.Println("Stopping after firing requests")
}
```

- Can you try running the same test with the latest gRPC version? - **I see the issue even in latest version v1.23.0**

- What happens when you introduce a timeout? - **Seeing no memory increase if I add timeout to context as shown in above snippet.** 

- Another interesting observation: If I run above server code with just calling `SayHello` once, InTap is being called twice. To reproduce, add a print in `inTapHandler` in server snippet, you would see it being called twice.
```
// Package main implements a client for Greeter service.
package main

import (
	"context"
	"fmt"
	"log"
	"time"

	"google.golang.org/grpc"
	pb "google.golang.org/grpc/examples/helloworld/helloworld"
)

const (
	grpcAddress = "localhost"
)

func main() {
	// Set up a connection to the server.
	conn, err := grpc.Dial(fmt.Sprintf("%s:50051", grpcAddress), grpc.WithInsecure())
	defer conn.Close()
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	c := pb.NewGreeterClient(conn)
	ctx, cancelFunc := context.WithTimeout(context.Background(), time.Second * 5)
	defer cancelFunc()
	c.SayHello(ctx, &pb.HelloRequest{})
}

```
Not sure if this would imply anything, I can create another bug for this one.

**Comment by canguler** [comment]
I am able to reproduce this.  Without a timeout on the client side, `RES` and `%MEM` keep increasing for the server process.  When a timeout is introduced, they don't.

When stream's context is created `operateHeaders`, it is added to the children set of the parent (transport's) context.  Then, `inTapHandle` returns a non-nil error and `operateHeaders` returns without canceling this newly created context.  Since it never gets cancelled, it never gets removed from the children set of transport's context.

We may solve this issue by making sure that stream's context is cancelled, when `operateHeaders` doesn't pass the stream to the handler.

**Comment by canguler** [comment]
HI @venuchitta.
#2985 should fix this. Can you try running your code with it and confirm?
