### ISSUE TITLE
NO_PROXY env var

### ISSUE THREAD

**Issue by nadilas** [grpc/grpc-go#2977]
Hi guys,
does anyone know if this issue is resolved in grpc-go? 
https://github.com/grpc/grpc/issues/9989

I can't seem to able to use no_proxy.

**Comment by menghanl** [comment]
Everything supported by [http.ProxyFromEnvironment](https://golang.org/pkg/net/http/#ProxyFromEnvironment) should be supported.

Note that the config is for the backend address (ip:port if using DNS), not for the dial target ("example.com" or other URLs).

**Comment by nadilas** [comment]
Thanks! Then the issue I’m having is rather a firewall issue.
