### ISSUE TITLE
could not greet: rpc error: code = Unimplemented desc = unknown service helloworld.Greeter exit status 1

### ISSUE THREAD

**Issue by niketagrawal** [grpc/grpc-go#2979]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
Can't determine
### What version of Go are you using (`go version`)?
 go1.11.6 linux/arm
### What operating system (Linux, Windows, …) and version?
Linux raspberrypi 4.19.58-v7+ (Raspbian GNU/Linux 10 buster)
### What did you do?
1. Installed gRPC on the PI using `go get -u google.golang.org/grpc`
2. The code for the server and the required .proto and .pb.go files are taken directly from examples/helloworld/ and embedded into a larger code base of another application. When tested locally on the host machine, the application could launch gRPC server successfully. A binary for this application is created to run on the Raspberry Pi.
3. The binary is run on the Pi and the client code (examples/helloworld/greeter_client/main.go) is run in another terminal on the Pi.
4. Error seen on the client terminal:
`could not greet: rpc error: code = Unimplemented desc = unknown service helloworld.Greeter exit status 1`

[UPDATE] The error is also reproduced when the server and the client are run on a general Linux PC. The server is run embedded in another application and I can trace from the logs that the `Serve` method has been called successfully by the server. The client is run by directly executing the main.go in google.golang.org/grpc/examples/helloworld/greter_client/

I'm uncertain as to whether this error is from the server side or the client side?

### What did you expect to see?
Client to be able to greet the server successfully
### What did you see instead?
`could not greet: rpc error: code = Unimplemented desc = unknown service helloworld.Greeter exit status 1`

**Comment by canguler** [comment]
Hi @niketagrawal,

Did you build the binaries on the Pi, or did you build them on a different machine?

**Comment by niketagrawal** [comment]
I cross compiled binaries for Pi on a different machine.

**Comment by canguler** [comment]
Can you try running greeter client against greeter server, without the larger code base, on Pi and see if it succeeds?

**Comment by niketagrawal** [comment]
The greeter client and server example works fine if run by itself on the Pi. I'd like to know specifically what does the error `could not greet: rpc error: code = Unimplemented desc = unknown service helloworld.Greeter exit status 1` means exactly?, so that there I an get some clue on how to debug it.

**Comment by dfawley** [comment]
It seems to me like your service isn't registered with the gRPC server.  Make sure the server is calling `RegisterGreeterServer`:

https://github.com/grpc/grpc-go/blob/c26cd97e18ad26799c9233fd79889f69df3f742a/examples/helloworld/greeter_server/main.go#L52

**Comment by menghanl** [comment]
Did you set the right environment variables when cross compiling?
https://github.com/golang/go/wiki/GoArm

**Comment by niketagrawal** [comment]
> It seems to me like your service isn't registered with the gRPC server. Make sure the server [application] is calling `RegisterGreeterServer`:
> 
> https://github.com/grpc/grpc-go/blob/c26cd97e18ad26799c9233fd79889f69df3f742a/examples/helloworld/greeter_server/main.go#L52

Service registration is fine. I added a print just after that line in the code and I could see the print later during the tests.

**Comment by niketagrawal** [comment]
> Did you set the right environment variables when cross compiling?
> https://github.com/golang/go/wiki/GoArm

I did not come across this link at all. I am able to build and run go programs on the PI as usual and have been able to test a basic client server functionality using TCP sockets in Go.

**Comment by dfawley** [comment]
> Service registration is fine. I added a print just after that line in the code and I could see the print later during the tests.

If you're adding prints, try adding one here:

https://github.com/grpc/grpc-go/blob/c26cd97e18ad26799c9233fd79889f69df3f742a/server.go#L1290

I'm pretty sure this is where the error is coming from.  If so, there is something wrong with your service registration (either the generated code or your usage of it; maybe the server you're contacting isn't the same as the one you've registered the service on).

**Comment by niketagrawal** [comment]
> > Service registration is fine. I added a print just after that line in the code and I could see the print later during the tests.
> 
> If you're adding prints, try adding one here:
> 
> https://github.com/grpc/grpc-go/blob/c26cd97e18ad26799c9233fd79889f69df3f742a/server.go#L1290
> 
> I'm pretty sure this is where the error is coming from. If so, there is something wrong with your service registration (either the generated code or your usage of it; maybe the server you're contacting isn't the same as the one you've registered the service on).

@dfawley You are right. I added a print statement at this place in server.go and I'm able to see it in the output log. You pointed out that it could be because of the generated code or its usage. Is there any approach to debug what could have gone wrong here?

**Comment by dfawley** [comment]
Make sure the service name ("helloworld.Greeter") is correct on the `Register` function you're calling in the server (e.g. https://github.com/grpc/grpc-go/blob/c26cd97e18ad26799c9233fd79889f69df3f742a/examples/route_guide/routeguide/route_guide.pb.go#L581).  And make sure the `Register` function is being called on the same gRPC server the client is connecting to.

You could also print `s.m` when the error is produced to see the list of registered services for that server.

**Comment by niketagrawal** [comment]
> Make sure the service name ("helloworld.Greeter") is correct on the `Register` function you're calling in the server (e.g.
> 
> https://github.com/grpc/grpc-go/blob/c26cd97e18ad26799c9233fd79889f69df3f742a/examples/route_guide/routeguide/route_guide.pb.go#L581
> 
> ). And make sure the `Register` function is being called on the same gRPC server the client is connecting to.
> You could also print `s.m` when the error is produced to see the list of registered services for that server.

@dfawley Thank you for your inputs so far. I could finally fix the issue! The problem was that the service name in the .pb.go file on the client side did not match with the service name in the .pb.go file on the server side. Reason being that these files were generated from their respective .proto files which had exactly the same obviously, barring the package name which was derived from the root directory in which the .proto file resided. And, eventually, different package names in .proto files resulted in different package name and service name in the generated .pb.go file

To ensure that the .pb.go files on server and client match perfectly, I had to replicated the same package structure on the client side as I had on the server side so that in the .proto file the same package name could be used.

I'm sure there should be a best practice to be followed in such a case that I'm unaware of right now as the approach I took seemed rather inconvenient.

**Comment by dfawley** [comment]
> I'm sure there should be a best practice to be followed in such a case that I'm unaware of right now as the approach I took seemed rather inconvenient.

You should only have one copy of any `.proto` file, and, further, only one copy of the generated (`.pb.go`) files as well.  This would prevent any similar mismatches in the future from being possible.
