### ISSUE TITLE
Safe to remove `WithBlock()` from `NewClientWithConfig()`?

### ISSUE THREAD

**Issue by mattayes** [grpc/grpc-go#2993]
Hi folks,

I was looking at the code for [`NewClientWithConfig()`]() and noticed [this comment](https://github.com/googleapis/google-cloud-go/blob/0f42522d468af83e2d814e7b069402984504f41f/bigtable/bigtable.go#L77-L79):

```go
// TODO(grpc/grpc-go#1388) using connection pool without WithBlock
// can cause RPCs to fail randomly. We can delete this after the issue is fixed.
```

#1388 is closed. Is it safe to remove `WithBlock()`? Happy to do the work if so.

**Comment by menghanl** [comment]
The referenced issue is fixed, it should be safe to remove.

From my experience, removing `WithBlock` may cause test failures. Some of the tests may assume connections are created when a ClientConn is created.
Please check with the cloud library maintainers too.

**Comment by mattayes** [comment]
My bad, I posted this in the wrong project 🙃. Thank you for your patience.
