### ISSUE TITLE
Panic on runtime

### ISSUE THREAD

**Issue by jiyeyuran** [grpc/grpc-go#2998]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
master
### What version of Go are you using (`go version`)?
1.12
### What operating system (Linux, Windows, …) and version?
MacOS
### What did you do?
If possible, provide a recipe for reproducing the error.
go build and run
### What did you expect to see?
no panic.
### What did you see instead?
```
panic: interface conversion: interface {} is nil, not func(*status.Status) *status.Status

goroutine 1 [running]:
ih5.cn/vendor/google.golang.org/grpc/internal/transport.init.ializers()
        /Users/ih5/go/src/ih5.cn/vendor/google.golang.org/grpc/internal/transport/http2_server.go:62 +0x86d
```

**Comment by canguler** [comment]
Hi @jiyeyuran,

What executable did you run?

**Comment by dfawley** [comment]
@jiyeyuran this is almost certainly something wrong with your local copy of grpc.  This error should not be possible, as the initialization for the status package should be setting this global in internal before http2_server.go attempts to reference it.  I see you have grpc vendored.  Please delete that whole path and update it with a clean version of grpc.
