### ISSUE TITLE
Test grpc connection failure in docker container

### ISSUE THREAD

**Issue by pigeon1990** [grpc/grpc-go#3009]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
v1.17.0
### What version of Go are you using (`go version`)?
go version go1.12.7 darwin/amd64
### What operating system (Linux, Windows, …) and version?
macOS Mojave 10.14.6
### What did you do?
If possible, provide a recipe for reproducing the error.
* Create a gRPC server using the code for this page https://github.com/grpc/grpc-go/blob/master/examples/helloworld/greeter_server/main.go
* Then copy the executable file to the docker container. (alpine:3.6)
* Testing the connection using ```telnet``` command, inside the container
### What did you expect to see?
Connected 
### What did you see instead?
Blocked

I tried to use the ```centos:latest``` image test and it worked well.

**Comment by menghanl** [comment]
The connection will be closed if it's not an http2 connection. That's probably why telnet doesn't work.

Can you try greeter_client instead?

**Comment by pigeon1990** [comment]
The connection works well, when I try to use greeter_client, but I don't understand that ```telnet``` has two results.🤔️

**Comment by menghanl** [comment]
Try turning on logs on the server side: https://github.com/grpc/grpc-go#how-to-turn-on-logging

If that doesn't help, try turning on golang debugging log: `GODEBUG=http2debug=2`

**Comment by dfawley** [comment]
Ping @pigeon1990
