### ISSUE TITLE
Ability to tie incoming call's Context to an outgoing calls

### ISSUE THREAD

**Issue by mwitkow-io** [grpc/grpc-go#301]
I'd like to be able to chain RPCs, i.e. make outgoing calls that result from incoming RPCs. 

Currently, I see no way that I could set the `Context` for an outgoing call that would have it's lifecycle tied to the incoming call. I.e. if the incoming RPC's Context deadlines or is cancelled, the outgoing ones will be cancelled. Ideally, the deadlines set of outgoing RPCs would be set to the remaining deadline of the incoming `Context`

Additionally, propagating per-RPC credentials should be easy for both unary and streaming RPCs. Currently it's only possible through manual calls to extract `metadata.MD` from the `Context` and set it on `CallOption.Header`, which only works on unary RPCs.

**Comment by iamqizhao** [comment]
1. This belongs to application logic. In your service impl handler, you can simply take the context and pass it the downstream rpc calls. In this way, the upstream rpc is chained with dwonstream rpcs.

2. It works for both. I am not sure what you missed. Can you take a look at https://github.com/grpc/grpc-go/blob/master/test/end2end_test.go#L767 as an example for metadata on streaming rpc?

**Comment by mwitkow-io** [comment]
2. Then the Header CallOption documentation is wrong as it only states
unary RPCs.

1. I'm slightly confused how can you pass in the Context to the call. Can
you provide an example?

The only thing the call accepts on a generated Client interface is the
Proto msg and CallOptions? I haven't seen a CallOption for Context.

Is it a DialOption? If so, this kinda would break my abstraction, as the
Application layer should rarely know what address it needs to dial.

**Comment by iamqizhao** [comment]
2. Because streaming rpc does not support CallOption yet.

1. For unary rpc:

	ctx := metadata.NewContext(context.Background(), testMetadata)
	if _, err := tc.EmptyCall(ctx, &testpb.Empty{});

for streaming rpc:

       	tc := testpb.NewTestServiceClient(cc)
        ctx := metadata.NewContext(context.Background(), testMetadata)
	stream, err := tc.FullDuplexCall(ctx)
