### ISSUE TITLE
examples: create an example for enabling and configuring retry

### ISSUE THREAD

**Issue by yhyddr** [grpc/grpc-go#3020]
### Use case(s) - what problem will this feature solve?
auto-retry ,use to config like max retry times
### Proposed Solution
a example in grpc-go to guide this operation

**Comment by dfawley** [comment]
@yhyddr, that is a good idea.  Would you be interesting in contributing an example client/server pair in https://github.com/grpc/grpc-go/tree/master/examples/features for this?  You can use the other clients/servers for reference.  To enable retry, you need to set `GRPC_GO_RETRY=on` in your environment, and then the easiest way to configure retry is via [`WithDefaultServiceConfig`](https://godoc.org/google.golang.org/grpc#WithDefaultServiceConfig), setting the appropriate [retry options](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#retry-policy-capabilities).

**Comment by yhyddr** [comment]
Hi,I'm very glad to do this things, your guide is very helpful for me.after I learn your recommend source.I wonder if the example use the go-grpc-middleware https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/retry.

**Comment by yhyddr** [comment]
@dfawley Hi, I recently learn how to use grpc-go and try to code this example.But I get confused by set ServiceConfig with my little know about grpc.
I write a example here:https://github.com/yhyddr/grpc-go/tree/retry-example/examples/features/retry
and set a retry ServiceConfig like this 

![image](https://user-images.githubusercontent.com/32089134/64953487-86936e80-d8b5-11e9-963f-cc3d64aeac75.png)

and this is my environment setting
![image](https://user-images.githubusercontent.com/32089134/64953584-be021b00-d8b5-11e9-83da-ab46a229f8f5.png)

do I had something wrong on use ServiceConfig?

**Comment by dfawley** [comment]
@yhyddr can you enable logging and see if anything useful is printed:
```
export GRPC_GO_LOG_VERBOSITY_LEVEL=99
export GRPC_GO_LOG_SEVERITY_LEVEL=info
```

Also, hedging is not implemented yet in gRPC-Go, so you can remove that from your example.

**Comment by yhyddr** [comment]
after i use these i Run it 
![image](https://user-images.githubusercontent.com/32089134/65065082-58e11f00-d9b4-11e9-876d-bbe7d71d41e2.png)

I found that phrase ServiceConfig didn't phrase retry Policy but just RetryThrottling .
is there else func to phrase it and configure retry Policy?
Or other branch has this feature.

Thanks for help,I'll sleep and research it tomorrow

![image](https://user-images.githubusercontent.com/32089134/65065040-40710480-d9b4-11e9-878d-b364184e3535.png)

![image](https://user-images.githubusercontent.com/32089134/65065054-48c93f80-d9b4-11e9-8ead-8546da8997e3.png)

**Comment by yhyddr** [comment]
after I use 
![image](https://user-images.githubusercontent.com/32089134/65103952-64f3cd80-da02-11e9-83e1-4214c5f50d82.png)

i got it success retry.
![image](https://user-images.githubusercontent.com/32089134/65103982-763cda00-da02-11e9-92e0-442b2a613246.png)
