### ISSUE TITLE
GRPC consuming memory and dont release them

### ISSUE THREAD

**Issue by ShiehShieh** [grpc/grpc-go#3022]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
v1.9.2

### What version of Go are you using (`go version`)?
1.12

### What operating system (Linux, Windows, …) and version?
Docker container of Ubuntu 16.04

**What did you do?**
One of my GRPC service is gradually consuming my container's memory.
![image](https://user-images.githubusercontent.com/6049252/64902338-1ed3fc80-d6d8-11e9-9d5e-6957179372f9.png)
![image](https://user-images.githubusercontent.com/6049252/64902421-96565b80-d6d9-11e9-9eb2-83dfb3e839fa.png)
![image](https://user-images.githubusercontent.com/6049252/64902345-2b585500-d6d8-11e9-95aa-aaae5df1f140.png)
The QPS of this GRPC service is about 1, a pretty small number for online serving, right?

**What did you expect to see?**
*Buffer.grow should not use such amount of memory.
https://github.com/grpc/grpc-go/blob/master/encoding/proto/proto.go#L76
It seems that the ref of this buffer slice is set to nil. I thought GC will return these memory to OS after mins.

**What did you see instead?**
As we can see from the picture above, none of my own code is consuming these memory. Actually, it looks like *Buffer.grow allocate these memory and never/seldom release them.

Please let me know if you want more detailed info. Thanks for your time! grpc is a really awesome project!

**Comment by strobil** [comment]
Hello!
The same problem i've expirienced on grpc-go v1.23.1
Allocated memory is not returning to OS

My heap profile:

![image](https://user-images.githubusercontent.com/6442572/65417779-8dfdcf00-de03-11e9-8e09-1fce74a9850c.png)

**Comment by ShiehShieh** [comment]
This fixed my issue: 

https://github.com/grpc/grpc-go/issues/2444

https://github.com/grpc/grpc-go/pull/2765

**Comment by dfawley** [comment]
@ShiehShieh, glad to hear the problems are resolved.

@strobil, if you are having more problems, please file another bug so we can track it there separately.  However, 28MB doesn't seem excessive given that this is allocating memory for your messages.
