### ISSUE TITLE
issue to handle wildcard certificate in grpc with nginx

### ISSUE THREAD

**Issue by hamidabdul1994** [grpc/grpc-go#3045]
We are beginner in grpc , but not able to host project with wildcard certificate. Please give me alternative solve with wild card certificate.

**Comment by dfawley** [comment]
We need more information to be able to help.  Please be specific in what you are trying to do, how you are trying to do it, what is happening, and what you are expecting.  Minimal code to demonstrate and reproduce the problem may also help.

**Comment by hamidabdul1994** [comment]
I have hosted api.sample.com, but not able to connect because we have issued *.simple.com certificate. 

I works with another single name domain certificate, smita.com


Our grpc will be host on grpc.sample.com, we don't want to create another certificate for grpc host machine, because we already have wildcard certificate. 

Please help me to configure wildcard ssl

**Comment by dfawley** [comment]
Are you asking about the client side or the server side or with the nginx configuration?  Is there any other information you can provide?

**Comment by dfawley** [comment]
FYI: grpc-go has interop tests in https://github.com/grpc/grpc-go/tree/master/interop (client and server) using certs from https://github.com/grpc/grpc-go/tree/master/testdata, which specify a wildcard.  You could look at those as an example.

**Comment by hamidabdul1994** [comment]
Client is not able to do grpc call

**Comment by dfawley** [comment]
gRPC should work fine with wildcard certs, and the example referenced above demonstrates this.  Maybe this is an nginx configuration issue you are running into.  Have you tried their mailing list, or possibly people on stackoverflow could help?

**Comment by menghanl** [comment]
Turning on logs (https://github.com/grpc/grpc-go#how-to-turn-on-logging) might show the reason why client isn't working.

**Comment by hamidabdul1994** [comment]
There was certificate issue. Thanks for discussing and supporting
