### ISSUE TITLE
Status from error cause

### ISSUE THREAD

**Issue by FUSAKLA** [grpc/grpc-go#3049]
### Use case(s) - what problem will this feature solve?
When using [`errors.Wrap`](https://godoc.org/github.com/pkg/errors#Wrap) on errors, then [`status.FromError`](https://godoc.org/google.golang.org/grpc/status#FromError) does not identify the error as a gRPC error since it does not implement the `GRPCStatus()` function.

The particular case I'm hitting is when using the `go-grpc-prometheus` interceptor [it sets the metrics label with gRPC status using the `status.FromError` function](https://github.com/grpc-ecosystem/go-grpc-prometheus/blob/master/server_metrics.go#L109). So, when error is wrapped, it sets the label value to the default `Unknown` status.

### Proposed Solution
Before checking if the error implements the function `GRPCStatus` use the [`errors.Cause()`](https://godoc.org/github.com/pkg/errors#Cause) to get the error root cause error and check that one instead.

The downside could be if any of the wrapped errors would implement the function it would be unwrapped anyway.  

### Alternatives Considered
Other possibility could be to implement own `Cause()` function in the `status` package which would also check if the error implements the `GRPCStatus` function to stop the recursion earlier. 

### Additional Context
I'm a bit afraid how much of a change would it be to the current behavior. Hopefully it would lead just to more precise gRPC status detection not causing any issues.

**Comment by dfawley** [comment]
Let's keep all discussion related to error wrapping in #2934. 

It was recommended to me to not pursue the change suggested here, to avoid any behavior change.
