### ISSUE TITLE
stabalize XxxServer and XxxClient

### ISSUE THREAD

**Issue by arnottcr** [grpc/grpc-go#3055]
## Use case(s) - what problem will this feature solve?
I find the resolutions provided for the unstable `XxxServer` and `XxxClient` interfaces to be tricky and place a large burden on the implementer. See #3024 and #2318 for more context. It would be nice if the generated code did not fight with Go's type system so much.

#### `type XxxServer interface { xxxServer() }`
This type must be an `interface` because `RegisterXxxServer` cannot know the concrete type that will implement the gRPC service.

To provide stability guarantees, if we added a unexported method to the `interface`, this would stabilize the `interface`, by preventing external packages from implementing it. As such, it would enforce the embedding of an anonymous `UnimplementedXxxServer`.

The approach above has the notable downside that for servers that implement the `XxxServer interface` within the same module, there may be desire to have the compiler prevent one from forgetting to implement a given rpc. This could be resolved by adding a new `struct`, say `UnstableXxxServer`, that would only implement the unexported method, unlike `UnimplementedXxxServer` that implements the full `XxxServer interface`.

#### `type XxxClient struct {}`
The service client it not intended to be implemented, hence the reason #785 did not add an `UnimplementedXxxClient struct`. I am unclear why exactly this is an interface, but it seems like directly exposing the `xxxClient struct` as `XxxClient`, while removing the current `XxxClient interface`, will add stability guarantees to the generated code without any measurable downsides.

#### `internal.XxxServer`
The complexity of the private method and additional type could be undesirable, thus an alternative would be to place the generate `XxxServer interface` behind an `internal` package. This restricts the implementability of the unstable `interface`s to trusted packages.

Unfortunately, this would involve generating more than one `*.pb.go`, since some exported symbols should be public. This seems like the most rigorous solution, but needs more proving to ensure that it is not too complex.

#### ` type XxxServer_Yyyer interface { Yyy(Aaa) Zzz }`
Instead of having a single interface for every service we could flow the pattern of single purpose interfaces, like `io.Reader`. This tends to be more idiomatic and flexible, but would force the creation of many registration methods, or use of `interface{}` as the parameter type, and will further clutter generated code with even more exposed types. The heading maps to the following proto:
```proto
service Xxx {
  rpc Yyy(Aaa) returns (Zzz);
}
```

#### `type XxxClient interface { xxxClient() }`
Similar to the service server, we can add an unexported method to the `XxxClient interface`. This should be pretty a straightforward change, and because we do not expect customers to implement `XxxClient`, there is no need for `UnimplementedXxxClient` or `UnstableXxxClient struct`s.

This approach is probably the closest to the current generated code, but feels non-ideomatic, thus I prefer the `struct`option.

#### `internal.XxxClient`
Again, ass with the service server we could stuff the `XxxClient` interface behind an `internal` package. This should work, but adds all the complexity explained above.

### Additional Context
Because the intention of all changes prevent the usage of the existing, unstable `interface`s, there may be concerns about the implications to mocking. My understanding is that, with the caveat that customers must define their own `interface`s, this is totally achievable and forces consumers to understand what parts of the service they care about, a net win for all.

**Comment by dfawley** [comment]
Adding an unexported method to the generated Server interfaces would be a breaking change, and would need to happen with a new major version.  Same with changing the Client interface into a struct.  Both seem like reasonable changes, although for the server we might move to per-method registration instead if we are making breaking changes here.

**Comment by arnottcr** [comment]
> Adding an unexported method to the generated Server interfaces would be a breaking change, and would need to happen with a new major version.

Considering that adding a new RPC  is also a breaking change, I am unclear what constitutes a compatible change. I agree this would not be a patch release, but since you are not currently following the go1 compatibility guarantees, I am unsure what the line should be.

> Same with changing the Client interface into a struct.

IIRC, it is expected that consumers not be implementing this interface, thus we only need to be concerned with callsite compatibility?

> Both seem like reasonable changes, although for the server we might move to per-method registration instead if we are making breaking changes here.

I recall discussing the as another alternative, I will add it to the pile.

**Comment by dfawley** [comment]
This would be *our action* breaking the user, not the user's action.  We can't control whether users add RPCs to services, but by making this change we will break every single server at the same time.

> since you are not currently following the go1 compatibility guarantees, I am unsure what the line should be.

Our [versioning policy](https://github.com/grpc/grpc-go/blob/master/Documentation/versioning.md) is largely aligned with semver with a few exceptions to avoid frequent major releases, for practical software development reasons.

> IIRC, it is expected that consumers not be implementing this interface, thus we only need to be concerned with callsite compatibility?

Many users do implement this interface for testing purposes.  (I should probably delete this, but we do have a [doc](https://github.com/grpc/grpc-go/blob/master/Documentation/gomock-example.md) describing how to use gomock with this interface for testing.)  This would be a breaking change.

**Comment by arnottcr** [comment]
Is there no longer interest to pursue this in the v2 interface?

**Comment by dfawley** [comment]
The generated code was revamped significantly after considerable design iteration.  I think what we have is as good as it will get, but if there are suggestions they would need to be backward compatible and use the current state as a reference.  Thanks for the issue.
