### ISSUE TITLE
stats.Handler: detecting client discon

### ISSUE THREAD

**Issue by utrack** [grpc/grpc-go#3060]
Hi! I want to detect if a client disconnected before the request was completed in stats.Handler.
I've tried doing it like this by detecting if `ctx.Err() == context.Canceled`:
```
func (h *StatsHandler) HandleRPC(ctx context.Context, s stats.RPCStats) {
	switch hook := s.(type) {
		case *stats.End:
		ctxErr := ctx.Err()
```
but, the context is always canceled there if handler returns an error. Is there any proper way to detect client discon (assuming TCP conn was closed cleanly)?

**Comment by menghanl** [comment]
What do you plan to do if it's a connection before RPC finishes?
If just for logging, checking the status code should be enough. All connection errors should have code `unavailable`.
