### ISSUE TITLE
examples: add regression tests for examples

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#3072]
This could be, e.g., a shell script for each example (or a larger one for everything) that starts the server, runs the client, and expects no errors.

**Comment by le-michael** [comment]
I wrote a bash script that tests the hello world example.

https://github.com/grpc/grpc-go/pull/3092

Let me know if this is in the right direction, I can add more tests as well if more coverage is needed.

**Comment by dfawley** [comment]
@le-michael thanks for the first test script!  Do you have any interest in generalizing this a bit (e.g. turn server/client wanted log messages into parameters) and using it for all the examples?

**Comment by le-michael** [comment]
@dfawley Yeah sure I don't mind generalizing it for the other examples. You can make me an assignee for this issue.

**Comment by dfawley** [comment]
Excellent, thank you!
