### ISSUE TITLE
github.com/coreos/etcd/clientv3 go/src/github.com/coreos/etcd/clientv3/auth.go:121:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthEnable

### ISSUE THREAD

**Issue by hamidabdul1994** [grpc/grpc-go#3078]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What did you do?
If possible, provide a recipe for reproducing the error.

**Comment by dfawley** [comment]
From the error it looks like both coreos and etcd are vendoring grpc, and attempting to work together.  This seems problematic, but is not a grpc issue.  Please file a bug in the coreos and/or etcd repos.  Thanks!
