### ISSUE TITLE
How can I register and find a service without using other tools

### ISSUE THREAD

**Issue by CulionBEAR** [grpc/grpc-go#3088]
On the Internet,I found that I cound use consul to register or find a service.
but i want to use gRPC without using other tools to implement finding services.
because I want to achieve dynamic load balancing for microservices。
thank u

**Comment by dfawley** [comment]
gRPC is not a full microservice management system.  You will need *some* name resolution / discovery system, whether it's DNS, consul, nginx, istio, etc.  (gRPC has gRPC-LB, but client support is deprecated and the gRPC team does not provide any gRPC-LB service implementation.)
