### ISSUE TITLE
Can I implementate conn-pool by reslover?

### ISSUE THREAD

**Issue by jingyugao** [grpc/grpc-go#3103]
I try to implementate a conn-pool of grpc by reslover.
Reslover one ip address into more `reslover.Address`, distinguish these `reslover.Address` by the `Metadata` field.
for example,"myschema:///localhost:12345" will reslover into 
```
reslover.Address{Addr:"localhost:12345",Metadata:0},
reslover.Address{Addr:"localhost:12345",Metadata:1},
reslover.Address{Addr:"localhost:12345",Metadata:2},
```
Then we have a pool of three connections.

**Comment by dfawley** [comment]
Something like that may work, but note that the resolver API is experimental, and the `Metadata` field is becoming deprecated in an upcoming PR.  A better way to do this would be to implement a custom load balancing policy and create multiple connections to the same address in it.  https://godoc.org/google.golang.org/grpc/balancer

(The balancer package is also experimental, but we don't have any planned changes to the balancer.V2Balancer interface.)
