### ISSUE TITLE
How to write a local client to call a remote server

### ISSUE THREAD

**Issue by ObrookO** [grpc/grpc-go#3104]
If I have a remote grpc server, I want to call the server from a local client.How should I write the client ?
For example, I have a local helloworld client,  I want to call a remote helloworld server, how should I write to replace the code:

```
conn, err := grpc.Dial(addr, grpc.WithInsecure())
if err != nil {
	log.Fatalf("connect failed: %v", err)
}

defer conn.Close()

client := pb.NewGreeterClient(conn)
ctx, cancel := context.WithTimeout(context.Background(), time.Second)
defer cancel()

response, err := client.SayHello(ctx, &pb.HelloRequest{Name: "world"})
if err != nil {
	log.Fatalf("could not greet: %v", err)
}
````

The method "NewGreeterClient()" can't find at local.

**Comment by dfawley** [comment]
@ObrookO sorry for the delay.  Have you been able to make progress on this since you filed it?  If not, we would need more information to be able to help.  E.g. a demonstration of your problems as a git branch / gist.
