### ISSUE TITLE
status: support %w in Errorf for wrapping other errors

### ISSUE THREAD

**Issue by benfdking** [grpc/grpc-go#3115]
### Use case(s) - what problem will this feature solve?

The aim of this is to: 

1. Align `status.Errorf` with Go's new wrapping verb `%w` in `fmt.Errorf`, so that it may be used in `status.Errorf`. Reducing confusion because of this hidden discrepancy.  
2.  Use of `%w` for wrapping errors in `status.Errorf()`, rather than using `%s` with `err.Error()` which would make code more concise. 

### Proposed Solution

Use of `fmt.Errorf()` followed by `.String()` in the function`status.Errorf()` instead of `fmt.Sprintf()`/

### Alternatives Considered

The only real alternative at the moment is using `%s` with `err.Error()` which is more verbose and may be confusing as mentioned above. 

### Additional Context

This may initially cause some backwards incompatibility concerns.

I think though these are mitigated by the fact that this is a feature that is only available with Go 1.13 and thus users should only use the verb `%w` if they have updated to Go 1.13.

**Comment by dfawley** [comment]
One complication here is that wrapped errors would not be serialized and transmitted on the wire, so if a server were to use this, the client would only see the resulting text and not the wrapped error.  gRPC statuses should be able to be transmitted with full fidelity from server to client, since that is their primary purpose.

**Comment by snargleplax** [comment]
Wouldn't this still be useful on the client side, though? If I call some code that invokes a gRPC client, gets an error, and then wraps that and returns it to me, I'd still like to be able to figure out whether I'm dealing with a wrapped gRPC error and determine the status code to handle. That's the primary need this feature request would fill for me, and it doesn't depend on wrapped errors going across the wire.

Any chance we could reopen this issue and give it a bit more consideration?

**Comment by dfawley** [comment]
@snargleplax - it's unclear why you'd want to wrap another error inside a grpc status in that case.  It sounds like you want to wrap a grpc status inside another error, which is already possible via `fmt.Errorf("....: %w", grpcStatusError)`.

Generally, it's going to cause problems if you are able to construct a status which cannot be transmitted on the wire.

**Comment by snargleplax** [comment]
Ah, I see now that I was misreading the description here. For me the issue title is confusing (since it talks about `fmt.Errorf` rather than `status.Errorf`; an implementation rather than interface perspective, I guess.), though I see how it was arrived at. What I need is covered by https://github.com/grpc/grpc-go/issues/2934.

**Comment by dfawley** [comment]
Actually, re-reading the proposal, I did rethink this part:

> The only real alternative at the moment is using %s with err.Error() which is more verbose and may be confusing as mentioned above.

You could use `%v` and `err` instead to avoid the manual call to `Error` that would be required if you used `%s`.

Supporting `%w` has the implication that the original error will be wrapped by the `status` error, and could be retrieved by `errors.Unwrap`, which would not actually be possible with the proposed solution above.
