### ISSUE TITLE
On the two way RPC streaming example, how do we know what the client is?

### ISSUE THREAD

**Issue by wari** [grpc/grpc-go#312]
Given the function signature:
``` go
func (s *routeGuideServer) RecordRoute(stream pb.RouteGuide_RecordRouteServer) error
```

`stream` only exposes `Send()` and `Recv()`. There's no notion of getting the information of what (or who) the actual client is, or should I gather this information on the actual message as part of the data that is sent?

**Comment by iamqizhao** [comment]
We have not constructed peer info yet (we will). For now applications need to use metadata to achieve this by themselves.

**Comment by zj8487** [comment]
+1 for peer info

**Comment by iamqizhao** [comment]
close this. Leave #334 ope for this issue.
