### ISSUE TITLE
how to set cookie?

### ISSUE THREAD

**Issue by dewei12138** [grpc/grpc-go#3126]
hello, how to set cookie on service side, I want to set key value and domain and expire. thank you.

**Comment by dewei12138** [comment]
@dfawley In our also powerless grpc is placed on the upper layer, and the front end directly interacts (web), the business does user login, so we need setcookie, we use envoy and google plugin, so that the front end can be accessed through restful form. I know grpcgo is metadata to get headers and cookies, but I am not quite sure how to set cookies in the regular manager of grpc.

**Comment by dewei12138** [comment]
@dfawley In our business, grpc is placed on the upper layer, interacts directly with the front end (web), and the business does user login, so we need setcookie. We use envoy and google plugin to make the front end accessible through restful form. I know grpcgo is metadata to get headers and cookies, but I am not quite sure how to set cookies in the regular manager of grpc.

**Comment by dfawley** [comment]
Are you using grpc-web for this?  If so, I think you might need to file an issue on that repo instead.  https://github.com/grpc/grpc-web  Or possibly envoy.

**Comment by dfawley** [comment]
There may be some information here that could help: 
https://github.com/envoyproxy/envoy/issues/2250
