### ISSUE TITLE
Add Header to client-side stats.End

### ISSUE THREAD

**Issue by MatthewDolan** [grpc/grpc-go#3132]
Currently, it is not possible to access headers from within a `stats.Handler`. The standard ways of accessing headers (using the client stream or the header call option) don't appear to be accessible with the stats handler.

# Use case(s) - what problem will this feature solve?

An interceptor that processes header metadata for each streaming RPC after the stream has finished. I return server information (like region) in the response header and using that to tag the statistics output by the handler on the client side.

### Proposed Solution

I noticed that trailer information was added to the `stats.End` struct: https://github.com/grpc/grpc-go/pull/2639. Would it be possible to add header information as well?

**Comment by MatthewDolan** [comment]
Yes, I have tried using an interceptor. In fact, I am migrating some metrics & tracing code from an interceptor to a stats handler. The reason for the migration is that I wanted access to the fields that the stats handler exposes (like the size of the message, compression, etc.).

It's not clear to me when an interceptor should be used or a stats handler should be used. One of my specific use cases is that I want to report a metric for the size of a response body and tag that metric with information passed back in the header (like the service name, version, region, etc. of the server code which returned that response) as well as information about the client process like the service name, version, region, etc. of the client code which received that response).

Let me know if I can be more specific about the use case or if you have any feedback about using a different approach.

**Comment by dfawley** [comment]
@MatthewDolan how about if the header metadata is added to `stats.InHeader` instead?  Would that be sufficient for your needs?

**Comment by MatthewDolan** [comment]
Yes. That would work for my needs.

**Comment by dfawley** [comment]
OK, we would be happy with that option.  (Probably the trailer metadata should have been added to `InTrailer` instead of `End`, but I don't think we considered that option at the time.)  Are you interested in contributing the implementation?

**Comment by MatthewDolan** [comment]
> Are you interested in contributing the implementation?

Sure. I made an initial attempt at an implementation: https://github.com/grpc/grpc-go/pull/3169. Let me know if you have any feedback.

**Comment by MatthewDolan** [comment]
This has now been release and is resolved.
