### ISSUE TITLE
Is possible to create grpc server secure TLS by golang and the client access by nodejs ?

### ISSUE THREAD

**Issue by kieugol** [grpc/grpc-go#3150]
I had a trouble when created grpc server by golang with secure TLS as below:

- Here is grpc server by golang:

```
	// Create the TLS credentials
		creds, err := credentials.NewServerTLSFromFile(certFile, certFileKey)
		if err != nil {
			fmt.Println("could not load TLS keys:", err)
			return err
		}
		// Create an array of gRPC options with the credentials
		opts := []grpc.ServerOption{grpc.Creds(creds)}

		// register service
		server = grpc.NewServer(opts...)
```

- here is grpc client with nodejs:
```
credentials = grpc.credentials.createSsl(
  fs.readFileSync(`./server/certs/${env}/ca.crt`),
  fs.readFileSync(`./server/certs/${env}/client.key`),
  fs.readFileSync(`./server/certs/${env}/client.crt`)
);
const client = new userProto.UserService(config.user_grpc, credentials);
```

Since I saw golang created secure with **TLS** but nodejs created secure with **SSL**.
So I guess It does not support server and client between two languages ... ?
Please help me find out the solution in this case.
Thanks everyone.

**Comment by menghanl** [comment]
In this context, TLS and SSL are interchangable. The client should be able to talk to the server.

Can you try running this client with the server, and post any errors if it doesn't work?

**Comment by kieugol** [comment]
Thanks a lot @menghanl 
But I still confuse about nodejs client authentication.

As u can see, Golang server just use two key for authentication is
`server.crt and server.key`
while nodejs client need three keys on function
```
 grpc.credentials.createSsl(
    fs.readFileSync(`./server/certs/${env}/ca.crt`),
    fs.readFileSync(`./server/certs/${env}/client.key`),
    fs.readFileSync(`./server/certs/${env}/client.crt`)
  );
```.
How about this case, pls help me clarify it

**Comment by menghanl** [comment]
I believe in most cases only "ca.crt" is required on the client side. The other two files are for mutual TLS.
This is better clarified in https://github.com/grpc/grpc-node/issues/273#issuecomment-399506158
