### ISSUE TITLE
Expose reflection server

### ISSUE THREAD

**Issue by dtaniwaki** [grpc/grpc-go#3163]
I'd like to implement `ServiceAuthFuncOverride` interface on a reflection service, but it's not possible as the object is not exposed.

https://github.com/grpc-ecosystem/go-grpc-middleware/blob/4e03c1a66b1704dc897b18fd7d7c2a7f3093819a/auth/auth.go#L30-L32

https://github.com/grpc/grpc-go/blob/4f70de23e6d83e800fe1b15bdd6e3e11b9a1f27a/reflection/serverreflection.go#L59

I'd like to access the object so I can make a type alias to add methods to the object.

### Use case(s) - what problem will this feature solve?

Avoid authentication check of grpc-middleware/auth for a reflection service.

### Proposed Solution

Expose `serverReflectionServer`.

### Alternatives Considered

N/A

### Additional Context

N/A

**Comment by menghanl** [comment]
Can you try wrapping `grpc_auth.UnaryServerInterceptor(myAuthFunction)`? The wrapper will only call the authInteceptor if the call is not reflection.

```go
// filterReflection skips the interceptor for reflection service.
func filterReflection(in grpc.StreamServerInterceptor) grpc.StreamServerInterceptor {
  return func(srv interface{}, ss grpc.ServerStream, info *grpc.StreamServerInfo, handler grpc.StreamHandler) error {
    if info.FullName == "/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo" {
      // Skip interceptor for reflection.
      return handler(srv, ss)
    }
    return in(srv, ss, info, handler)
  }
}
```

---

Exporting `serverReflectionServer` isn't too bad.
But because reflection needs a pointer to the gRPC server as well, exporting the type results in the possibility of having a reflection service pointing to a different gRPC server, with confusing behaviors.
We can revisit this option if the wrapping interceptor solution doesn't work for you.

**Comment by dtaniwaki** [comment]
@menghanl Thank you for the suggestion!

I implemented something like below and it works as expected.

```go
package grpc

import (
	"context"

	"google.golang.org/grpc"
)

type UnaryFilter func(info *grpc.UnaryServerInfo) bool
type StreamFilter func(info *grpc.StreamServerInfo) bool

func MyUnaryServerInterceptorWithFilter(in grpc.UnaryServerInterceptor, filter UnaryFilter) grpc.UnaryServerInterceptor {
	return func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
		if filter(info) {
			// Skip interceptor for reflection.
			return handler(ctx, req)
		}
		return in(ctx, req, info, handler)
	}
}

func MyStreamServerInterceptorWithFilter(in grpc.StreamServerInterceptor, filter StreamFilter) grpc.StreamServerInterceptor {
	return func(srv interface{}, ss grpc.ServerStream, info *grpc.StreamServerInfo, handler grpc.StreamHandler) error {
		if filter(info) {
			// Skip interceptor for reflection.
			return handler(srv, ss)
		}
		return in(srv, ss, info, handler)
	}
}

func UnaryReflectionFilter(info *grpc.UnaryServerInfo) bool {
	return info.FullMethod == "/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo"
}

func StreamReflectionFilter(info *grpc.StreamServerInfo) bool {
	return info.FullMethod == "/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo"
}
```

Usage:

```
MyUnaryServerInterceptorWithFilter(
	grpc_auth.UnaryServerInterceptor(auth.GetAuthFunction(conn, config.JWTSigningKey)), UnaryReflectionFilter)
```
