### ISSUE TITLE
Use grpc, go-micro with gateway cause problems

### ISSUE THREAD

**Issue by EgorkZe** [grpc/grpc-go#3164]
Hi! Trying to make service with micro, grpc and gateway.
have such model.
```
syntax = "proto3";

import "google/api/annotations.proto";

package myhello;

service Greeter {
	rpc SayHello (HelloRequest) returns (HelloReply) {
		option(google.api.http) = {
			get: "/api/hello/{name}",
		};
	}
}

message HelloRequest {
	string name = 1;
}

message HelloReply {
	string message = 1;
}
```

and Makefile

```
build: 
	protoc -I${GOPATH}/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
	 --plugin=protoc-gen-go=$(GOPATH)/bin/protoc-gen-go \
	 --plugin=protoc-gen-micro=$(GOPATH)/bin/protoc-gen-micro \
	 --proto_path=$(GOPATH)/src:. \
	 --micro_out=. --go_out=plugins=grpc:. \
	 --grpc-gateway_out=logtostderr=true:. \
	 proto/myhello/hello.proto
```

All creates without errors but appears one problem - gateway and micro generate same methods RegisterGreeterHandler and error RegisterGreeterHandler redeclared in this block.
As I understand I should use different Proto models for micro and grpc, but it is not good option, because I should support both models at the same time. Is there a way to handle this situation?

**Comment by dfawley** [comment]
We don't support go-micro, so can't really help with this situation.  It's possible doing separate `protoc` commands and separating the output files into different packages would help, but that's the only thing I can think of.  You may want to file an issue in the go-micro repo if you still are having problems.
