### ISSUE TITLE
add API similar to net/http.ConnState

### ISSUE THREAD

**Issue by tamird** [grpc/grpc-go#317]
An API like [ConnState](http://golang.org/pkg/net/http/#ConnState) is needed for the same reasons it was needed in net/http.

**Comment by iamqizhao** [comment]
Check out https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md and find out the corresponding API in grpc.ClientConn in order to find out the state of a ClientConn.

**Comment by tamird** [comment]
@iamqizhao it doesn't seem to be possible to interact with `ClientConn` from the server side, which is necessary; is that correct?

**Comment by iamqizhao** [comment]
Yup this is client side only. On server, we do not expose any underlying connection to the users. This is by design. We have not found a compelling reason to do it on server side because server side situation is much simpler: you either can send a response successfully meaning the connection is fine or fail to send because of a connection error.

**Comment by tamird** [comment]
Without server side connection tracking it's not possible to implement e.g. rate limiting. Is it possible to work around this in some way that I'm not aware of?

**Comment by iamqizhao** [comment]
I am almost sure that the rate limiting of server connection should be done by registering a rate limiting handler into the server without exposing connection state outside. Keep in mind that this type of API is always racy. When you get the state, the real state could be changed already.

**Comment by tamird** [comment]
Are you suggesting a specific rate limiting API? What about graceful shutdown? Will you implement a separate API for each feature that requires a callback when connections change state?

**Comment by iamqizhao** [comment]
Server will have a graceful shutdown API to shutdown a server gracefully. There won't be per-connection graceful shutdown. 

If a feature requires the instant and accurate connection state to take action, it has to use callback type approach. It is possible to have a common hook for all these features.

**Comment by tamird** [comment]
Great! That's exactly what ConnState is. Were you planning to add this hook?

**Comment by iamqizhao** [comment]
I do not have plan. To be clear, like what we did for client side connection state, this should not be Go specific. If you really need it, please file a issue at grpc/grpc and we will coordinate on it across languages.
