### ISSUE TITLE
set balancer name in version 1.25.1

### ISSUE THREAD

**Issue by ya0yy** [grpc/grpc-go#3177]
grpc.WithBalancerName("") was deprecated, and loadBalancingPolicy in service config  was deprecated. how i change balancer name.

**Comment by dfawley** [comment]
Use the `loadBalancingConfig` field in the service config:
https://github.com/grpc/proposal/blob/master/A24-lb-policy-config.md

To select a policy, you can use a service config containing:

```
{
  "loadBalancingConfig": [
     {"MyLBPolicy": {<optional JSON configuration for policy goes here>}
  ]
}
```
