### ISSUE TITLE
Allow Server to handle non-gRPC traffic

### ISSUE THREAD

**Issue by nvcnvn** [grpc/grpc-go#3179]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?
Our service handling gRPC request.
But we need to implement Prometheus endpoint to export metrics.
Right now we starting 2 listener to handle both

### Proposed Solution
Similar but opposite with current experimental [Server.ServeHTTP](https://godoc.org/google.golang.org/grpc#Server.ServeHTTP)

You can provide a `Server.RegisterHTTPHandler(http.Handler)` to serve non gRPC traffic

### Alternatives Considered
We can use  [Server.ServeHTTP](https://godoc.org/google.golang.org/grpc#Server.ServeHTTP) to archive same goal.
But seem it is more risky.

**Comment by utrack** [comment]
You could use [cmux](https://github.com/soheilhy/cmux) to accomplish smth like that

**Comment by nvcnvn** [comment]
> You could use [cmux](https://github.com/soheilhy/cmux) to accomplish smth like that

Hi, thanks for the suggestion. Is there any advantage of using https://godoc.org/google.golang.org/grpc#Server.ServeHTTP ?

**Comment by menghanl** [comment]
The support for `ServeHTTP` is limited, and there could be missing features/performance issues. Please see the note in the godoc: https://godoc.org/google.golang.org/grpc#Server.ServeHTTP

**Comment by dfawley** [comment]
As far as extending the gRPC server to call external handlers, this is not something we are planning to pursue for the foreseeable future.  cmux is traditionally how users solve this problem if they cannot serve multiple ports.
