### ISSUE TITLE
http2server HandleStreams failed

### ISSUE THREAD

**Issue by mmihir82** [grpc/grpc-go#3182]
### What version of Go are you using (`go version`)?
go1.13 linux/amd64

### What operating system (Linux, Windows, …) and version?
centos 7

### What did you do?
If possible, provide a recipe for reproducing the error.
Creating pipeline for the telemetry using the following guide: 
https://github.com/cisco/bigmuddy-network-telemetry-pipeline

Getting errors:
```
2019/11/14 18:27:17 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
2019/11/14 18:27:29 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
2019/11/14 18:27:37 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
2019/11/14 18:27:47 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
```

Debugs:
```
INFO[2019-11-14 18:28:27.483725] gRPC: Receiving dialout stream                
encap=gpb name=grpcdialout peer="192.168.2.11:19995" server=192.168.1.11:58001 tag=pipeline type="pipeline is SERVER"
DEBU[2019-11-14 18:28:27.499230] gRPC server logdata                           
encap=gpb msg="00000000  0a 09 63 73 30 31 2e 6c  61 62 31 1a 03 32 30 30  |..host01.lab1..200|\n00000010  32 0e 73 68 6f 77 20 69  6e 74 65 72 66 61 63 65  |2.show interface . . . 
4:19995" reqID=0 server=192.168.1.11:58001 tag=pipeline type="pipeline is SERVER"
ERRO[2019-11-14 18:28:19.337246] gRPC: session closed                          
encap=gpb error=EOF name=grpcdialout server=10.2.240.37:58001 tag=pipeline type="pipeline is SERVER"
```

**Comment by dfawley** [comment]
The error you're seeing means the client is disconnecting before sending the full HTTP/2 handshake preface.  Are you sure things are configured correctly?  I'm not familiar with the framework you are using - have you tried directly connecting a pure grpc client to the server?

**Comment by mmihir82** [comment]
Hi, Thank you for your response,
the framework I'm using is
https://github.com/cisco/bigmuddy-network-telemetry-pipeline
No I have not tried directly grpc to client. Server is listener on certain
port and Switch/Router are the client. I don't know how to connect via grpc.
Do you think it is running an old go version, when it was compiler?

**Comment by dfawley** [comment]
> Do you think it is running an old go version, when it was compiler?

Unlikely.  Servers and clients should be wire-compatible no matter what Go or gRPC versions they were using.  My guess is something is not configured correctly in your framework/environment, but this is not something we're familiar with so I don't think we can help.  Have you asked for help in https://github.com/cisco/bigmuddy-network-telemetry-pipeline?

**Comment by mmihir82** [comment]
Yes, not respond. I will try to test it out to directly connected gRPC.
Thank you for the response.

**Comment by sudhirski** [comment]
Hi @mmihir82 , I'm facing the same issue ! Pls let me know if you could get this resolved from https://github.com/cisco/bigmuddy-network-telemetry-pipeline

**Comment by mmihir82** [comment]
Hello, I was able to resolve it, here what I done:
1. update the code file: `xport_grpc.go`
Line: 460 to 477 
```
	for {
		//
		// Recv will error out if server is stopped so we do not
		// have to handle local context explicitly
		reply, err := stream.Recv()
		if err != nil {
			if err == io.EOF {
				/*
				logctx.WithError(err).Error(GRPCLOGPRE +
				"session closed")
				*/
				} else {
					logctx.WithError(err).Error(GRPCLOGPRE +
						"session error")
				}
				//return err
				return nil
			}
```
2. I had to install go packaging, (google search: setup go) 
3. create a folder `pipeline` in the go `/usr/local/go` 
4. go to the folder `bigmuddy-network..` 
5. Set the env: 
`export GOPATH=/usr/local/go/ `
`export GOBIN=/usr/local/go/pipeline/bin`
`export GOROOT=vendor`
6. cp the content into `/usr/local/go/pipeline` 
7. also I had to cp following into 
`cp -r vendor/github.com /usr/local/go/src/`
`cp -r vendor/golang.org /usr/local/go/src/`
`cp -r vendor/gopkg.in /usr/local/go/src/`
8. run go `go build pipeline` 
Once you have new binary file, you can run the pipeline. 

I was able to get the switch connected with the pipeline, but I don't see data add into the influxdb 
so I'm stuck at that point.. 

I hope this helps, and if someone figures out how to get the data into influxdb, please msg me 
thank you
