### ISSUE TITLE
Add helper functions to chain server interceptors

### ISSUE THREAD

**Issue by fho** [grpc/grpc-go#3185]
PR https://github.com/grpc/grpc-go/pull/2696 added helpers to chain client interceptors.
No analogous helper for server interceptors exist. To chain server interceptor the helpers from go-grpc-middleware or own helpers needs to be used.

To have a consistent API go-grpc should also provide helpers to chain server interceptors.

**Comment by dfawley** [comment]
@fho, this is reasonable, but the team does not currently have time to work on this.  If you interested in sending a PR, we can review it and merge it.

**Comment by tukeJonny** [comment]
I want to try this issue.

**Comment by fho** [comment]
thank you @tukeJonny :-)
