### ISSUE TITLE
Need help. Dont know why it doesnt connect.

### ISSUE THREAD

**Issue by jkrovnl** [grpc/grpc-go#3188]
I get this error while doing tutorial on udemy, cant figure out why there is error on dial. 
```
jkrov@LAPTOP-8VSU5ELH MINGW64 ~/Documents/go/src/github.com/jkrovnl/golearn2 (master)
$ go run main.go
panic: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connectionerror: connection error: desc = "transport: Error while dialing dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it."
```
[github code](https://github.com/jkrovnl/golearn2)
working on windows

**Comment by dfawley** [comment]
The connection error is reported above: Error while dialing dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.

Is your server running on port 8080 on localhost?  As a sanity test: can you just do a `net.Dial("tcp", "localhost:8080")` and get a `net.Conn` with no error?

**Comment by jkrovnl** [comment]
`package main

import (
	"context"
	"fmt"
	"net"

	"github.com/GoesToEleven/golang-project/005-grpc/02-server/echo"
	"google.golang.org/grpc"
)

type EchoServer struct{}

func (e *EchoServer) Echo(ctx context.Context, req *echo.EchoRequest) (*echo.EchoResponse, error) {
	return &echo.EchoResponse{
		Response: "My Echo: " + req.Message,
	}, nil
}

func main() {
	lst, err := net.Listen("tcp", ":8080")
	if err != nil {
		panic(err)
	}

	s := grpc.NewServer()

	srv := &EchoServer{}
	echo.RegisterEchoServerServer(s, srv)

	fmt.Println("Now serving at port 8080")
	err = s.Serve(lst)
	if err != nil {
		panic(err)
	}
}`
Now serving at port 8080
`func main() {
	conn, err := net.Listen("tcp", "localhost:8080")
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()
}`
don't get error

**Comment by dfawley** [comment]
> Is your server running on port 8080 on localhost? As a sanity test: can you just do a `net.Dial("tcp", "localhost:8080")` and get a `net.Conn` with no error?

Please note I was suggesting using `net.Dial` as a sanity test to make sure your server is running and reachable.  Your code above is doing a `net.Listen`, which should fail if your server is also running and listening on the same port.
