### ISSUE TITLE
import common types

### ISSUE THREAD

**Issue by danjenson** [grpc/grpc-go#3189]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
1.25.1

### What version of Go are you using (`go version`)?
go version go1.11.13 linux/amd64

### What operating system (Linux, Windows, …) and version?
Fedora 29

### What did you do?
In my project I have a `service_x.proto` file for each service and a `types.proto` file for types shared across all services. However, when I compile for go, it puts them in separate packages; I also can't put `go_package = 'service_x'` at the top of the `types.proto` file because it will change for every service `x` where it is used. Furthermore, it looks like the package prefix for `types.Result` is completely wiped in the `service_a.pb.go` file, creating a syntax error / undefined symbol. I would expect at the very least that there is a reference to a `types.pb.go` file, even if it's not output in the same `protoc` command. Is there any way compile my service and have access to the message types from `types.proto` in `service_a.pb.go`? Here is an example setup:

`service_a.proto`:
```
syntax = "proto3";
package service_a;

import "types.proto";

service ServiceA {
  rpc SomeRPC (SomeRPCRequest) returns (types.Result)
}

message SomeRPCRequest {
  string x = 1;
}
```

`types.proto`:
```
syntax = "proto3";
package types;

message Result {
  bool success = 1;
}
```

**Comment by dfawley** [comment]
Make sure the proto files are in different directories (or at least the .pb.go files you generate), since they will get their own Go packages.

**Comment by danjenson** [comment]
That doesn't seem to change anything? It still erases any reference to the `types` package. Neither of these directory structures works:
```
project/
  pb/
    service_a/
      service_a.pb.proto
    types/
      types.pb.proto
```
```
project/
  pb/
    service_a/
      service_a.pb.proto
      types/
        types.pb.proto
```
This is a sample where `Result` is used in `service_a.pb.go`:
```
type ServiceAClient interface {                                                                                                                                                            
  SomeRPC(ctx context.Context, in *SomeRPCRequest, opts ...grpc.CallOption) (*Result, error)    
}
```

**Comment by dfawley** [comment]
Try putting the proto files in their own directories: 
```
project/
  protos/
    service_a/
      service_a.proto
    types/
      types.proto
  pb/
    service_a/
      service_a.pb.proto
    types/
      types.pb.proto
```
(Make sure you `import "../types/types.proto"` in `service_a.proto`.)

If that doesn't fix it, it would also help to know how you're running `protoc`.

**Comment by danjenson** [comment]
Directory structure:
```
project/
  protos/
    service_a/
      service_a.proto
    common/
      types.proto
  pb/
    service_a/
      service_a.pb.proto
    common/
      types.pb.proto
```

`service_a.proto`:
```
syntax = "proto3";
package service_a;

import "../common/types.proto";

service ServiceA {
  rpc SomeRPC (SomeRPCRequest) returns (types.Result);
}

message SomeRPCRequest {
  string x = 1;
}
```

Output:
```
project/service_a $ protoc -I ../protos ../protos/service_a/service_a.proto --go_out=plugins=grpc:pb 
../common/types.proto: Backslashes, consecutive slashes, ".", or ".." are not allowed in the virtual path
service_a/service_a.proto: Import "../common/types.proto" was not found or had errors.
service_a/service_a.proto:7:41: "types.Result" is not defined.
```

**Comment by danjenson** [comment]
I'm part way there with this:
```
project
├── protos
│   ├── common
│   │   └── types.proto
│   └── service_a
│       └── service_a.proto
└── service_a
    └── pb
        └── service_a
            ├── common
            │   └── types.pb.go
            └── service_a.pb.go
```
`service_a.proto`:
```
syntax = "proto3";
package service_a;

import "common/types.proto";

service ServiceA {
  rpc SomeRPC (SomeRPCRequest) returns (common.Result);
}

message SomeRPCRequest {
  string x = 1;
}
```
However, regardless of whether I make `common` a sibling or subdirectory, `service_a.pb.go` can't find package `common`:
```
package service_a

import (
	common "common"
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)
...
```

**Comment by dfawley** [comment]
Hmm, looks like imports need to be relative to the directory where you run `protoc` from, and cannot reference parent directories.  So try:

`service_a.proto`
```
import "common/types.proto"
```

```
$ cd project/protos
$ protoc --go_out=plugins=grpc,paths=source_relative:pb service_a/*.proto
```

Something like that should work.  The `import_path` and `M` options in `--go_out` may also be useful depending on the exact contents of your proto files.  You may also want to use the `go_package` option in your proto files to declare the Go name for the generated package.  The documentation is pretty thorough in the protobuf repo's main `README.md`: https://github.com/golang/protobuf, but it can be tricky to get things working the first time.

**Comment by danjenson** [comment]
This was solved by making them both part of the same package in the proto files, then they can be compiled to the same output directory and have access to one another.
