### ISSUE TITLE
balancer: create many tcp connections use the same endpoints

### ISSUE THREAD

**Issue by cfc4n** [grpc/grpc-go#3192]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
1.21.x\1.23.x (etcd 3.3.x\etcd 3.4.x)
### What version of Go are you using (`go version`)?
go version go1.11.5
### What operating system (Linux, Windows, …) and version?
centos 7 
### What did you do?
If possible, provide a recipe for reproducing the error.
/cc @cfc4n will send codes. (sample by etcd)

### What did you expect to see?
create many tcp connects with the same endpoint.
```
cfc4n@cnxct:~/Project/grpc-go$ netstat -antp tcp|grep 2379
tcp4       0      0  172.23.46.79.53761     10.21.128.32.2379      SYN_SENT
tcp4       0      0  172.23.46.79.53760     10.21.128.32.2379      SYN_SENT
tcp4       0      0  172.23.46.79.53759     10.21.128.32.2379      SYN_SENT
tcp4       0      0  172.23.46.79.53758     10.21.128.32.2379      SYN_SENT
tcp4       0      0  172.23.46.79.53757     10.21.128.32.2379      SYN_SENT
tcp4       0      0  172.23.46.79.53756     10.21.128.32.2379      SYN_SENT
tcp4       0      0  172.23.46.79.53755     10.21.128.32.2379      SYN_SENT
```
### What did you see instead?
create a tcp connection only until tcp socket connect failed.

### More detail
[balancer: create many tcp connections use the same endpoint](https://github.com/etcd-io/etcd/issues/11371)

**Comment by menghanl** [comment]
It's a feature for the users to create multiple TCP connections to same endpoint, and the users have the full control. I don't think this is a problem in gRPC.

Closing. Please reply if you have more updates.

**Comment by cfc4n** [comment]
ummm...OK. It's a feature. I got it and I reply this issue to etcd community.
