### ISSUE TITLE
Dependency on honnef.co/go/tools is broken

### ISSUE THREAD

**Issue by Minnozz** [grpc/grpc-go#3194]
### What version of gRPC are you using?
`v1.25.1`

### What version of Go are you using (`go version`)?
`go version go1.13.4 linux/amd64`

with environment variables:

```
GOPROXY="direct"
GOSUMDB="off"
```

### What operating system (Linux, Windows, …) and version?
`Ubuntu 16.04.6 LTS`

### What did you do?
```$ go get -u google.golang.org/grpc```

### What did you expect to see?
A successful download of the grpc package.

### What did you see instead?
```
$ export GOPROXY="direct"
$ export GOSUMDB="off"
$ go get -u google.golang.org/grpc
go: finding google.golang.org/grpc v1.25.1
go get: google.golang.org/grpc@v1.25.1 requires
        github.com/envoyproxy/go-control-plane@v0.9.0 requires
        google.golang.org/grpc@v1.23.0 requires
        honnef.co/go/tools@v0.0.0-20190523083050-ea95bdfd59fc: unrecognized import path "honnef.co/go/tools" (https fetch: Get https://honnef.co/go/tools?go-get=1: x509: certificate is valid for *.netlify.com, netlify.com, not honnef.co)

```

**Comment by mec07** [comment]
This has been resolved: https://github.com/dominikh/go-tools/issues/658

**Comment by dfawley** [comment]
FWIW I'd recommend using go modules instead of `go get`.  Our 1.25 module does not reference `honnef.co` (it's in a sub-module since it isn't actually needed by grpc itself).
