### ISSUE TITLE
Is it possible that gRPC server serving 2 domain names in server options?

### ISSUE THREAD

**Issue by shaobovaltix** [grpc/grpc-go#3198]
Hi,

We are using gRPC for client-server communication and TLS is used for authentication. Now we are trying adding 2 TLS credentials in the server options to serve 2 domain names and we are doing something like this:

    creds1 := credentials.NewTLS(tlsConfig1)      
    creds2 := credentials.NewTLS(tlsConfig2)      

    // add options  
    opts := []grpc.ServerOption{
        grpc.Creds(creds1),
        grpc.Creds(creds2),
	    // other server options
    }

But look like it doesn't work. The server always uses the 2nd creds for authentication. Is there any way we can serve 2 domain names in gRPC server?

**Comment by easwars** [comment]
You could possibly use the `WithTransportCredential` dial option defined [here](https://godoc.org/google.golang.org/grpc#WithTransportCredentials) and override either/both of `ServerHandshake` or `OverrideServerName` defined [here](https://godoc.org/google.golang.org/grpc/credentials#TransportCredentials) and have full control of the TLS handshake process.

**Comment by menghanl** [comment]
[Server_Name_Indication](https://en.wikipedia.org/wiki/Server_Name_Indication) allows a server to present multiple certificates. If you create a TLS config with SNI ([like this](https://stackoverflow.com/questions/35641888/is-it-possible-to-host-multiple-domain-tls-in-golang-with-net-http)), if should work with gRPC.
Can you give it a try?
