### ISSUE TITLE
DNS resolver has started looking for TXT records

### ISSUE THREAD

**Issue by arcana261** [grpc/grpc-go#3207]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?

master (e5e980f)

### What version of Go are you using (`go version`)?

go version go1.11.4 linux/amd64

### What operating system (Linux, Windows, …) and version?

Linux, Ubuntu 18.04

### What did you do?

Try to call gRPC method. Using DNS resolver scheme and round robin balancer under Kubernetes and CoreDNS.

### What did you expect to see?

Successful DNS resolution

### What did you see instead?

```
{"error":"error parsing service config: error from DNS TXT record lookup: lookup _grpc_config.naghshe-grpc.divar-explorers on 10.233.0.3:53: no such host","code":14,"message":"error parsing service config: error from DNS TXT record lookup: lookup _grpc_config.naghshe-grpc.divar-explorers on 10.233.0.3:53: no such host","details":[]}
```

**Comment by Gobonoid** [comment]
Observing the same thing
```
INFO: 2019/11/25 11:59:09 grpc: error from DNS TXT record lookup: lookup _grpc_config.cashback-card-fis-adapter on 10.3.0.10:53: no such host
```

**Comment by Gobonoid** [comment]
As talked to my team members, late changes to grpc pkg are causing TXT lookup to fail. TXT lookup can be now disabled by using DialOption
`grpc.WithDisableServiceConfig()`

**Comment by menghanl** [comment]
Thanks for reporting!

TXT lookup was already enabled before. The change was to propagate the error to ClientConn. But an unexpected side effect is it causes ClientConn to ignore the addresses as well.

The change has been reverted in #3213.

Closing issue now. Please reply if you have questions.
