### ISSUE TITLE
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: timed out waiting for server handshake

### ISSUE THREAD

**Issue by darmawan01** [grpc/grpc-go#3215]
try to run golang with grpc healt check in container with `docker run`, 
get som problem ` timed out waiting for server handshake`. I was added 
` GRPC_GO_REQUIRE_HANDSHAKE=off` but it still error

Here is my specifications:
- Go version 1.12
- grpc 1.25.1
- google.golang.org/grpc/health/grpc_health_v1 latest version

log when i added `GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info`
```
INFO: 2019/11/28 12:35:09 parsed scheme: ""
INFO: 2019/11/28 12:35:09 scheme "" not registered, fallback to default scheme
INFO: 2019/11/28 12:35:09 ccResolverWrapper: sending update to cc: {[{localhost:8000 0  <nil>}] <nil>}
INFO: 2019/11/28 12:35:09 ClientConn switching balancer to "pick_first"
INFO: 2019/11/28 12:35:09 pickfirstBalancer: HandleSubConnStateChange: 0xc000021540, CONNECTING
INFO: 2019/11/28 12:35:29 transport: loopyWriter.run returning. connection error: desc = "transport is closing"
WARNING: 2019/11/28 12:35:29 grpc: addrConn.createTransport failed to connect to {localhost:8000 0  <nil>}: didn't receive server preface in time. Reconnecting...
INFO: 2019/11/28 12:35:29 pickfirstBalancer: HandleSubConnStateChange: 0xc000021540, TRANSIENT_FAILURE
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: timed out waiting for server handshake
```

**Comment by menghanl** [comment]
As said in https://github.com/grpc/grpc-go/issues/2406, the option to not wait for handshake was entirely removed, and the client always expect server to send handshake now.

What server is the client talking to? If you are using cmux, please try https://github.com/soheilhy/cmux/issues/64#issuecomment-461982271.

**Comment by darmawan01** [comment]
It's working fine if using grpc 1.20.1

**Comment by menghanl** [comment]
I believe the option was removed in https://github.com/grpc/grpc-go/releases/tag/v1.23.0
 - xds: move code to a root level xds directory (#2950)

**Comment by darmawan01** [comment]
thanks @menghanl , i will learn about the issues your given.
