### ISSUE TITLE
My vendor import has 20K lines of Golang code, however the grpc-go repo has got 100K

### ISSUE THREAD

**Issue by beef9999** [grpc/grpc-go#3218]
`import "google.golang.org/grpc"`

What is the rest of the code used for?

**Comment by andyxning** [comment]
What do you concern? The code is needed since grpc import it.

**Comment by beef9999** [comment]
Just curious, in terms of the Go language perspective.

For instance, CPP needs to export some .h files and hide detailed implementations inside .so files.

So this mechanism also applies to Golang?

**Comment by andyxning** [comment]
In golang, a package can also be pre-compiled and distributed. See your `$GOPATH/pkg` contents. But i do not think that with only a lib users can import and reference the golang variables. Actually, Golang is different from CPP which is definitely not related with grpc. You can reach to https://golang.org for more info. :)

**Comment by menghanl** [comment]
Closing as it's not grpc related.
https://groups.google.com/forum/#!forum/golang-nuts is also a good place for this kind of questions.
