### ISSUE TITLE
resolverMu is not unlocked when a build error happens

### ISSUE THREAD

**Issue by jiwen624** [grpc/grpc-go#3244]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
Release 1.25.1

### What version of Go are you using (`go version`)?
go version go1.13.4 darwin/amd64

### What operating system (Linux, Windows, …) and version?
I think it applies to all operating systems

### What did you do?
If possible, provide a recipe for reproducing the error.
code read and test

### What did you expect to see?
ccr.resolverMu should be unlocked before the method returns when an error happens

### What did you see instead?
ccr.resolverMu is not unlocked.

I'm looking into this method `newCCResolverWrapper` :
https://github.com/grpc/grpc-go/blob/505c0d6440ba0123bc0e443ce293372bcf49359f/resolver_conn_wrapper.go#L107-L112

I think the lock `ccr.resolverMu` wouldn't be unlocked if there is a build error in `rb.Build()` (for example, a parse error in the dnsBuilder). This can cause another goroutine (in method `resolveNow`) to get blocked forever. I also checked all the usages of `ccr.resolverMu` and didn't find it could be unlocked somewhere else. 

I'm not a pro of gRPC so I may be wrong. Please let me know if my understanding is correct and you need me to submit a PR for it. Thanks.

**Comment by easwars** [comment]
You are correct in pointing out that `ccr.resolverMu` is not unlocked if `rb.Build()` returns an error. But when that happens, we return a `nil` `ccResolverWrapper` from the `newCCResolverWrapper`, and therefore no other methods of this `ccResolverWrapper` object can ever be called, and this object will eventually be garbage collected since there are no references to it.

I think this is working as intended. Please let us know if you are actually seeing some problems because of this behavior. Thanks.

**Comment by jiwen624** [comment]
> You are correct in pointing out that `ccr.resolverMu` is not unlocked if `rb.Build()` returns an error. But when that happens, we return a `nil` `ccResolverWrapper` from the `newCCResolverWrapper`, and therefore no other methods of this `ccResolverWrapper` object can ever be called, and this object will eventually be garbage collected since there are no references to it.
> 
> I think this is working as intended. Please let us know if you are actually seeing some problems because of this behavior. Thanks.

Thanks for the clarification. Yes, this `ccResolverWrapper` is not referenced by this goroutine when an error happens. My concern was because it gets passed into a resolver builder (`rb.Build()`), not necessarily "unreferenceable" at the time the execution returns from `newCCResolverWrapper`, it can easily be broken if, say, a future change in a builder makes that object be kept for a long time (accidentally) in another goroutine or global variable (for example a global map), without noticing that this object is locked in a different goroutine. Then the whole goroutine will be blocked silently. It's somewhat unpredictable and hard to debug.

But I checked the existing resolver builders and agree with you that they are all working fine for now. Thanks for pointing it out.

**Comment by easwars** [comment]
@jiwen624 
Thanks for pointing this out.
