### ISSUE TITLE
too much cpu cost on runtime

### ISSUE THREAD

**Issue by seven7777777** [grpc/grpc-go#3245]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
1.2
### What version of Go are you using (`go version`)?
1.12
### What operating system (Linux, Windows, …) and version?
centos 7.6
### What did you do?
If possible, provide a recipe for reproducing the error.
1.a go grpc stream server
2.about 140 stream clients request concurrently
3.go tool [pprof:](https://github.com/seven7777777/funbox/blob/master/pprof.png)
### What did you expect to see?
1.low cpu
### What did you see instead?
high cpu to 80% of total  64 cores spent on  runtime.schedule and runtime.findrunable.

**Comment by seven7777777** [comment]
i tried like this, just comment request processing code and have only recv and send ack code left, but still high cpu
func (this *Node) Processor(stream np.Node_ProcessServer) error {
    ack:=&ProcessAck{}
    for{
      req, err:=stream.Recv()
      if err!=nil{
            return err
      }
      //if  err=this.Do(req);err!=nil{
       //     return err
       //}
       	if err := stream.Send(ack); err != nil {
		return err
	}
    }
}

**Comment by easwars** [comment]
I don't this is directly related to gRPC. When you have 140 concurrent stream clients, you will have `O(140)` goroutines on the server handling requests from these clients and sending back replies. So, you are bound to spend sometime in `runtime.schedule` and `runtime.findrunable` which is essentially the go runtime trying to find the next runnable goroutine. Please let us know if you find particular gRPC code paths hogging the CPU. Thanks.

As a side note: You are using gRPC version `1.2` which is more than 2.5 years old.  You could consider updating your gRPC version.

**Comment by seven7777777** [comment]
For now, we batch our small stream requests in size of  tens of bytes  to bigger request in size of  thousands of bytes. By doing this, we reduce the thundering herd at the server side, less scheduling on grpc server goroutine.

**Comment by seven7777777** [comment]
And it works now.
