### ISSUE TITLE
What can I do to let it notify me when it succeeds

### ISSUE THREAD

**Issue by CulionBEAR** [grpc/grpc-go#3246]
i want to send a package to my gateway after xxx.serve() starts listen in main function.
but when xxx.serve() starts, the main function starts blocking.
I can only create a new coroutine and start sending package after a delay of 5 seconds.
Is there a better way?

**Comment by easwars** [comment]
Could you please provide code samples for what you are trying to do.

Also `Server.Serve` is expected to block. So, you should run it in its own goroutine.

**Comment by CulionBEAR** [comment]
@easwars 
thank you for answer my question!^_^
about this code:
```
	if err!=nil{
		log.Fatal(err)
	}
	joinServer:=grpc.NewServer()
	join.RegisterJoinServiceServer(joinServer,new(rpcHandle))
	lis,err:=net.Listen("tcp",serverUrl)
	if err!=nil{
		log.Fatal(err)
	}
	go serverRegister()
	joinServer.Serve(lis)
```
i want to run serverRegister() when joinServer.Serve(lis) has not error.
but joinServer.Serve(lis) is blocked,i can not run serverRegister after it;
i can only write "time.Sleep(time.Second)" in serverRegister();

**Comment by dfawley** [comment]
The port is available after `Listen` returns.  Also, gRPC clients will retry connections even if the port is not ready yet.  So I don't think you need to send any signals after `Serve()` has been called.  Please let us know if you have any further questions.
