### ISSUE TITLE
hello, i use type of  any in file.proto, how can i transport to type of interface in golang 

### ISSUE THREAD

**Issue by srlemon** [grpc/grpc-go#3250]
Please see the FAQ in our main README.md before submitting your issue.

**Comment by easwars** [comment]
The protobuf library does provide some helper methods to deal with the Any type here:
https://github.com/golang/protobuf/blob/master/ptypes/any.go

This doesn't seem like a gRPC specific question to me. Hence I'm closing this. Feel free to reopen if you have a gRPC specific issue.
