### ISSUE TITLE
Is it possiable moving implemetion to client, and calling api as local function call instead of rpc calling

### ISSUE THREAD

**Issue by RaymondReddington** [grpc/grpc-go#3268]
Is it possiable moving implemetion to client, and calling api as local function call instead of rpc calling

**Comment by dfawley** [comment]
@RaymondReddington I'm not quite sure what you're asking here.  Can you please be more specific?

**Comment by RaymondReddington** [comment]
i have grpc server written in go.
and an go grpc client.
now i want to move the code on server side to client.
and client can call the rpc api as normal. but only local implemation will be execute( the code moved from server side.)
for example:
before:
cli -> net -> svr
cli.SvrCallA(a1, a2) -> net/tcp/http2 -> svr -> svr.SvrCallA(a1,a2)
function SvrCallA will be executed in server side. 
after move:
cli -> (...) -> svr
cli.SvrCallA(a1, a2) -> (client local call) -> svr -> svr.SvrCallA(a1,a2)
all functions are executed only in client side.

**Comment by dfawley** [comment]
There are a few different options for this:

1. Use a localhost network connection.  `grpc.Dial("localhost:"+<listener's port>)`.  This is the easiest option.
2. Use a `net.Conn` created from `net.Pipe`s, given to gRPC via custom dialers (`grpc.WithContextDialer`).  E.g. https://godoc.org/google.golang.org/grpc/test/bufconn.  This would be more efficient than 1, but requires a little more setup.
3. Depending on your needs and the service implementation's requirements/behavior, it _may_ be possible to invoke the service's handlers directly.  This only works for unary RPCs, will lose some things like headers and trailers, and it is a little more dangerous as it allows the service handler to modify the request message, which affects the client.  This would be the most efficient and also very easy to implement, if it works for you.

Also, we are working on an in-process transport that will avoid the need to encode/decode the messages, so when that is done it will be preferred over 1 or 2.  #906

**Comment by RaymondReddington** [comment]
thanks. 
in-process transport , avoiding encoding/decoding will have a better performance.
and for rpc calling. updating is easy. for go, in-process implemention updating would be hard.
i want to have an implemention that avoids encoding/decoding, calling locally, in-process, and updating easily.(hotfix, not sdk updaing, which must compile fist and then restart server.)
is this possible?

**Comment by dfawley** [comment]
> updating easily.(hotfix, not sdk updaing, which must compile fist and then restart server.)

I'm not sure what you mean by this.  Go doesn't have dynamic loading of code, so you will always need to recompile & restart to deploy updates.  If you separate your client and server then you can restart one without restarting the other, but then you can't use an in-process transport (you'd need a localhost network or a unix socket).

**Comment by RaymondReddington** [comment]
unix socket or pipe is good choice. these can be the way for in process communaction.
dynamic loading is very important for online service. 
for one go program. recompiling and restart is the only way to update.
but how about seperating them into two program. but one is managed by main program(which is the grpc client in), the one managed is the program containing servce implemation. 
and then. the two program can commucate, and the one managed can be updated dynamicly.

how to seperate one program into two? i think one method is in compileing time. and another way is in runtime.
the way in runtime: can pack two program into one. the sub one can be something like resource.
in runtime. main program will extract the sub one. and execute by system call.
crazy idea...

**Comment by dfawley** [comment]
Yes, something like that should be possible.  And you can use grpc to communicate between the two programs, using either a unix socket or a localhost TCP conneciton (number 1 from the list above).  Good luck!

**Comment by RaymondReddington** [comment]
@dfawley Thanks a lot
