### ISSUE TITLE
Add setter methods to requests and responses

### ISSUE THREAD

**Issue by sidh** [grpc/grpc-go#3276]
Right now requests and responses have getter functions that allow defining interfaces for types with identical fields. It would be very useful to have setter functions for the same purposes.

### Use case(s) - what problem will this feature solve?
Ability to define interfaces in user code and then modify multiple types of requests/responses with same setter functions using those interfaces.

**Comment by dfawley** [comment]
Can you please clarify?  It sounds like it would be more appropriate in the [proto repo](https://github.com/golang/protobuf), but I'm not entirely sure.
