### ISSUE TITLE
Testing gRPC with mocks example clarification

### ISSUE THREAD

**Issue by ksonbol** [grpc/grpc-go#3281]
Hello, I was trying to understand the mocking examples given [here](https://github.com/grpc/grpc-go/tree/master/examples/helloworld/mock_helloworld) and [here](https://github.com/grpc/grpc-go/tree/master/examples/route_guide/mock_routeguide) but one thing was quite confusing:

Using the `testSayHello` or `testRouteChat` functions in this way confused me. I think it would be easier to understand if we are testing a function in the main code (not the testing code) that receives the client interface as a parameter and no testing-related parameters. Then in testing code, we can call that function and test its output.

For example, instead of:

```
func TestSayHello(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()
	mockGreeterClient := hwmock.NewMockGreeterClient(ctrl)
	req := &helloworld.HelloRequest{Name: "unit_test"}
	mockGreeterClient.EXPECT().SayHello(
		gomock.Any(),
		&rpcMsg{msg: req},
	).Return(&helloworld.HelloReply{Message: "Mocked Interface"}, nil)
	testSayHello(t, mockGreeterClient)
}

func testSayHello(t *testing.T, client helloworld.GreeterClient) {
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	r, err := client.SayHello(ctx, &helloworld.HelloRequest{Name: "unit_test"})
	if err != nil || r.Message != "Mocked Interface" {
		t.Errorf("mocking failed")
	}
	t.Log("Reply : ", r.Message)
}
```

We write something like this:
```
func TestSayHello(t *testing.T) {
        ctrl := gomock.NewController(t)
	defer ctrl.Finish()
	mockGreeterClient := hwmock.NewMockGreeterClient(ctrl)
	req := &helloworld.HelloRequest{Name: "unit_test"}
	mockGreeterClient.EXPECT().SayHello(
		gomock.Any(),
		&rpcMsg{msg: req},
	).Return(&helloworld.HelloReply{Message: "Mocked Interface"}, nil)
	r, err := SayHello(mockGreeterClient, req)
	if err != nil || r.Message != "Mocked Interface" {
		t.Errorf("mocking failed")
	}
	t.Log("Reply : ", r.Message)
}
```
And in another file (e.g., in the main package), we have such a function:
```
func SayHello(client helloworld.GreeterClient, req *helloWorld.HelloRequest) {
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	r, err := client.SayHello(ctx, &helloworld.HelloRequest{Name: "unit_test"})
        ...
}
```

**Comment by menghanl** [comment]
I believe the idea was to show that mock creation can be separated from mock usages. Feel free to send a PR to improve the code.

And if you do so, please also do a sanity check to make sure the doc is in sync (https://github.com/grpc/grpc-go/blob/master/Documentation/gomock-example.md). Thanks!
