### ISSUE TITLE
grpc.WithWaitForHandshake not found

### ISSUE THREAD

**Issue by bondhan** [grpc/grpc-go#3282]
Hello,

When I run my main.go I got this error:

```
# google.golang.org/api/transport/grpc
../../../google.golang.org/api/transport/grpc/dial.go:64:3: undefined: grpc.WithWaitForHandshake
```

Deleting the folder ~/go/src/google.golang.org/grpc and updating go get -v did not solve the problem. Any ideas?

Why there is google.golang.org/grpc and github.com/grpc-go in go src folder? any help please?

**Comment by menghanl** [comment]
`grpc.WithWaitForHandshake` was removed in #2904, as tracked in #2406.

Please try to update `google.golang.org/api`. Or find what version of gRPC to use with it.
