### ISSUE TITLE
Many different errors when running gRPC on high load - how to prevent them?

### ISSUE THREAD

**Issue by Codehardt** [grpc/grpc-go#3291]
Hi,

I created a gRPC server with the following config:

```golang
opts := []grpc.ServerOption{
	grpc.Creds(credentials.NewServerTLSFromCert(&cert)),
	grpc.StreamInterceptor(func(srv interface{}, ss grpc.ServerStream, info *grpc.StreamServerInfo, handler grpc.StreamHandler) error {
		// irrelevant code
		err := handler(srv, ss)
		 // irrelevant code
		return err
	}),
	grpc.UnaryInterceptor(func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
		// irrelevant code
		resp, err := handler(ctx, req)
		// irrelevant code
		return resp, err
	}),
}
```

and ran **8000** gRPC clients using Docker and multiple Docker hosts (1 host = 1000 Clients) with the following config:

```golang
opts := []grpc.DialOption{
	grpc.WithPerRPCCredentials(perRPC),
	grpc.WithTransportCredentials(creds),
	grpc.WithBlock(),
}
```

Now all **8000** clients start a download request of a ~50MB file at an interval of 2 seconds but the download of the ~50MB file takes more than 2 seconds. Over the time the number of concurrent streams increase more and more until I can see the first errors server- and clientside:

## Clientside

```
write tcp 172.17.0.216:43376->172.28.30.48:443: write: broken pipe
```

```
connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"
```

```
connection error: desc = "transport: authentication handshake failed: context deadline exceeded"
```

```
timed out waiting for server handshake
```

## Serverside

```
Server.Serve failed to create ServerTransport:  connection error: desc = "transport: http2Server.HandleStreams failed to receive the preface from client: read tcp 172.28.30.48:443->172.28.30.96:47808: i/o timeout"
```

```
Server.Serve failed to complete security handshake from "172.28.30.98:48822": EOF
```

```
Server.Serve failed to complete security handshake from "172.28.30.96:52334": read tcp 172.28.30.48:443->172.28.30.96:52334: read: connection reset by peer
```

```
Server.Serve failed to complete security handshake from "172.28.30.96:57462": read tcp 172.28.30.48:443->172.28.30.96:57462: i/o timeout
```

```
http2Server.HandleStreams failed to read frame: read tcp 172.28.30.48:443->172.28.30.25:44010: read: connection reset by peer
```

**So my questions are:**

- Is there a way to limit the **global** number of concurrent streams? I am aware of `MaxConcurrentStreams`, but this limit can only be used to limit the max streams per transport. In my scenario every client only creates one download request.

- If there is a way to configure a global limit, how will the client be notified when the limit is reached? Is there a way to do tell the client to retry few seconds later every time the limit is reached?

- Where do all this timeouts come from, is there a way to increase those or wouldn't it be a good idea?

In my scenario I don't care how long it takes until all 8000 clients downloaded their file but I don't want that 4000 / 8000 fail due to timeouts and broken pipes.

Thanks.

**Comment by easwars** [comment]
You could limit the number of simultaneous connections at the server by using a [LimitListener](https://godoc.org/golang.org/x/net/netutil#LimitListener). But this approach does not send a signal to the client that the server is overloaded and that it should retry with a possible backoff.

You could also try setting the [connection timeout](https://godoc.org/google.golang.org/grpc#ConnectionTimeout) option on the server to a higher value. The default is 120 seconds. Does that match with the timing of your errors?

**Comment by Codehardt** [comment]
Limiting the Listener is no option for me, you already described the cons.

Setting connection timeouts is only half of the solution. Increasing timeouts will only reduce the amount of errors but will not prevent them. 

Currently I experiment with interceptors that send a status error on overload by counting a stream stack counter, e.g.:

**Serverside**

```golang
func (s *Server) StreamInterceptor(srv interface{}, ss grpc.ServerStream, info *grpc.StreamServerInfo, handler grpc.StreamHandler) (err error) {
	s.loadmu.Lock()
	s.streamStack++
	overload := s.streamStack > s.maxStreamStack
	s.loadmu.Unlock()
	if overload {
		err = status.New(...) // return an overload error that will be catched client side
	} else {
		err = handler(srv, ss)
	}
	s.loadmu.Lock()
	s.streamStack--
	s.loadmu.Unlock()
	return err
}
```

..but catching that error **cliendside** is not easy, especially for upload streams due to grpc's send buffer logic. 

I decided to send an `&empty.Empty{}` message from server to client in front of all streams for uploads as well as downloads and bidirectional streams. This allows me to check **clientside** weather the empty message could be received or an overload error was raised:

```golang
func StreamInterceptor(ctx context.Context, desc *grpc.StreamDesc,
	cc *grpc.ClientConn, method string, streamer grpc.Streamer, opts ...grpc.CallOption) (grpc.ClientStream, error) {
	cs, err := streamer(ctx, desc, cc, method, opts...)
retry:
	if err != nil {
		return cs, err
	}
	var empty empty.Empty
	err = cs.RecvMsg(&empty)
	if status.Code(err) == ... {
		RandSleep()
		cs, err = streamer(ctx, desc, cc, method, opts...)
		goto retry
	}
	return cs, err
}
```

and the following adjustment to server interceptor:

```golang
	...
	if overload {
		err = status.New(...) // return an overload error that will be catched client side
	} else {
		if err := ss.SendMsg(&empty.Empty{}); err != nil {
			return err
		}
		err = handler(srv, ss)
	}
```

I will test and improve the above approach in the next days. The above code does not cover `context.Context` cancellation and expiration yet.

I don't know if above solution will bring other problems with it.

**Comment by easwars** [comment]
I'm a little unclear about your usage of connections and streams. 
* When you say you have a thousand clients on each Docker host, do you mean a thousand [grpc.ClientConns](https://godoc.org/google.golang.org/grpc#ClientConn)?
* When you say that each client starts a download request every 2 seconds:
  * Does the client wait for the current request to complete before starting the next one?
  * Do subsequent requests use the same [grpc.ClientConn](https://godoc.org/google.golang.org/grpc#ClientConn)


Even though the mentioned [LimitListener](https://godoc.org/golang.org/x/net/netutil#LimitListener) does not help with propagating the error immediately to the client, it might still be useful to have some sort of a limited listener on your server. The mentioned limited listener blocks on the `Accept` when the connection limit has been reached. You could write your own limited listener which actually closes the connection immediately when the limit has been reached, forcing the client to backoff and reconnect.

And wrt to changing your API to bidirectional just to support sending the error status from the server, I think it should not be required. You could still have use the client-side streaming API, and if the `Send` fails, you could then call `Receive` to read the error status from the server.

**Comment by Codehardt** [comment]
> When you say you have a thousand clients on each Docker host, do you mean a thousand grpc.ClientConns?

Yes. Thousands of clients that connect with `grpc.Dial(...)`.

> Does the client wait for the current request to complete before starting the next one?

Each client only does one RPC at a time. There are no go routines that start concurrent streams for one `grpc.ClientConn`.

> Do subsequent requests use the same grpc.ClientConn

Yes, at the moment I create a `grpc.ClientConn` at start and let the conn open until the client terminates (but he doesn't, because it runs as a service).

The clients are doing the following routine in an infinity loop (simplified):

 - The client pings the server and checks if the client has to download something, e.g. a 50 MB file.
 - If the client has to download that file, it starts the download request
 - Do something with that file 
 - Uploads a result (e.g. 2 MB upload)
 - If client doesn't have to download something, then just wait X minutes before pinging again.

> Even though the mentioned LimitListener does not help with propagating the error immediately to the client, it might still be useful to have some sort of a limited listener on your server. The mentioned limited listener blocks on the Accept when the connection limit has been reached. You could write your own limited listener which actually closes the connection immediately when the limit has been reached, forcing the client to backoff and reconnect.

Rejecting connections when a limit has been reached will also limit unary RPCs. This would mean that when all Listeners are busy with stream requests, no unary request could be sent. Using two listeners on two different ports wouldn't be a solution, because I want to use :443 port only. 

> And wrt to changing your API to bidirectional just to support sending the error status from the server, I think it should not be required. You could still have use the client-side streaming API, and if the Send fails, you could then call Receive to read the error status from the server.

Yes, but then I would have to buffer all bytes that has been sent client-side, until the `Recv` function or a `Send` function tells me that server is overloaded and rejects or accepts my upload stream. Also, this logic is hard to implement generically in a `StreamInterceptor`, it would be easier for a single RPC upload but my problem is that I have dozens of different stream RPCs defined in my proto and I would have to implement the logic multiple times.

**Comment by easwars** [comment]
> 
> The clients are doing the following routine in an infinity loop (simplified):
> 
> * The client pings the server and checks if the client has to download something, e.g. a 50 MB file.
> * If the client has to download that file, it starts the download request
> * Do something with that file
> * Uploads a result (e.g. 2 MB upload)
> * If client doesn't have to download something, then just wait X minutes before pinging again.

If the clients open up a single grpc.ClientConn at startup and use that to make all these RPCs (the unary one to ask for work, the server-side streaming to download, and client-side streaming to upload), they should not have to re-establish connections during their lifetime, and should not run into connection handshake problems once the server load increases, assuming the attempt to create the grpc.ClientConn at startup succeeded. Each new RPC on the existing ClientConn will only create a new stream (which is very lightweight compared to a new connection).

Please let us know if you have other questions. Thanks.

**Comment by Codehardt** [comment]
> If the clients open up a single grpc.ClientConn at startup and use that to make all these RPCs (the unary one to ask for work, the server-side streaming to download, and client-side streaming to upload), they should not have to re-establish connections during their lifetime, and should not run into connection handshake problems once the server load increases, assuming the attempt to create the grpc.ClientConn at startup succeeded.

Yes that is right but in my workflow I only described half the truth. Some of the "download files" are executables and create an own gRPC client conn to the same server. 

Nevertheless, I was able to **fix I/O timeouts by increasing server- and clientside timeouts** from 20 sec (default) to few minutes. 

All other errors could be **fixed by the interceptors** described above. 

I think that I added enough workarounds to satisfy my claims.

Thanks for help!

Kind regards.

**Comment by rameshb444** [comment]
Hi Codehardt,

How did you fixed this error at server side?

**Server.Serve failed to create ServerTransport:  connection error: desc = "transport: http2Server.HandleStreams failed to receive the preface from client: read tcp 172.28.30.48:443->172.28.30.96:47808: i/o timeout"**

**Comment by Codehardt** [comment]
There is no way to fix this issue server-side. If your timeout only occurs on too many simultaneous requests you need a way to balance your load. I balanced it by detecting a possible overload server-side and notifying new clients to wait with their requests until the overload reduces. 

If your timeout occurs without server-side overloads, you may have an other issue that has nothing to do with this issue.
