### ISSUE TITLE
GetRequestMetadata should return metadata.MD not map[string]string

### ISSUE THREAD

**Issue by james-lawrence** [grpc/grpc-go#3295]
### Use case(s) - what problem will this feature solve?
ability to proxy metadata as is from a client to another client for an internal service.

metadata.MD and map[string]string are not interchangeable.

**Comment by menghanl** [comment]
API for `PerRPCCredentials` is fixed, and can't be easily modified. `metadata.MD` is a very similar map, if you don't have duplicate keys, it can be converted to a `map[string]string`.

Why do you use `PerRPCCredentials` to proxy metadata? Did you try [interceptors](https://github.com/grpc/grpc-go/tree/master/examples/features/interceptor)?
