### ISSUE TITLE
Server streaming to all connected users

### ISSUE THREAD

**Issue by coilnovasince1985** [grpc/grpc-go#3296]
I do have a simple service which provides a server streaming to all users connected via grpc-web and a simple unary call to send a message to a specific user.

My question is, how can I send something to all grpc connected users ? what is the best approach?
I was thinking to store all connected users in a go map structure and then iterate over it, but this method doesn't really scale in case if I have multiple services.

```
service NotificationsService {
    rpc SendNotificationMessage(NotificationMessageRequest) returns (NotificationMessageResponse) {};
    rpc GetLatestNotifications(NotificationsRequest) returns (stream NotificationsResponse) {};
}
```

**Comment by menghanl** [comment]
> I was thinking to store all connected users in a go map structure and then iterate over it

You will need to do something similar to this. You don't necessarily need to keep all the streams in the map, you can have a goroutine to manage each stream, that also reads from a channel. The broadcast message can be pushed to all the channels.

> doesn't really scale in case if I have multiple services

Different services need to be managed separately, or they can be merged to one service?

**Comment by coilnovasince1985** [comment]
@menghanl well, basically what I'm trying to achieve is to do a push notifications. 
The idea is following, I'm waiting for a request message which is coming from a php backend and check message sender, then based on sender id I find a corresponding stream which is saved to map and I then can send a message to a particular user.

When user connects to server stream, server running an infinite loop and listening for a message in a channel, then i read message and send to the connected user. 
The problem number one is that when I disconnect or reload the page, the stream in map is no longer valid, and if I try to send a message to that stream the panic error appears. So that I also don't know a way on how to clean up map or channel from a closed streams.

`Different services need to be managed separately, or they can be merged to one service?`

The main goal is to make a scalable service so that if I decide to spawn more instances of this particular service, I should be able to handle the connections properly too.

Unfortunately I haven't found any sample apps for my task and not sure whether I'm doing it wrong or right ))

**Comment by menghanl** [comment]
The server needs to register/unregister the clients whenever they connect/disconnect, to maintain a list of only the connected ones. A simple way is to register at the beginning of the service handler, and unregister when the service handler returns.

What you are trying to do is very similar to pubsub. Maybe try searching for "golang broadcast" or "golang pubsub", you will find examples.

**Comment by coilnovasince1985** [comment]
@menghanl alright, thanks. Will look into it
