### ISSUE TITLE
Move status.statusError to internal and export

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#3304]
This type would be useful for internal use in other package.  E.g. in #3301, `balancer.dropRPCError` could embed this instead of `error` + implementing `GRPCStatus`.

**Comment by JNProtzman** [comment]
I'd like to help with this. Should this be in internal.go, or should the entire status folder be moved to internal?

**Comment by dfawley** [comment]
Great, thanks!  I would say a separate package would be better to prevent the base internal package from growing.

**Comment by JNProtzman** [comment]
One more question - I've moved the package into internal but I can't figure out how to regenerate the protos to point at `"google.golang.org/grpc/internal/status"`. 

Do you have any tips?

**Comment by dfawley** [comment]
What protos are you trying to regenerate and why?  No public APIs should be affected by this change.

**Comment by JNProtzman** [comment]
There's a bunch of internal testing protos that point to `google.golang.org/grpc/status` need to be regenerated to point to the moved package: `google.golang.org/grpc/internal/status`.

One example [test protos](https://github.com/grpc/grpc-go/blob/master/test/grpc_testing/test.pb.go) that needs to be regenerated.

**Comment by dfawley** [comment]
No exported symbols in `grpc/status` should be affected by this change (`statusError` is not exported), so no other code should need to change.

**Comment by JNProtzman** [comment]
Let me clarify what I was thinking then:
Move the folder `grpc/status` to `grpc/internal/status` and export `statusError`. 
If I do this, the test protos pointing to `grpc/status` will need to be directed to `grpc/internal/status`?

Unless I'm copying the folder and exporting in internal, instead of moving it.

**Comment by dfawley** [comment]
> Move the folder grpc/status to grpc/internal/status and export statusError.

The `status` package has externally-visible functionality that needs to continue working.

This issue is about creating a new package, `grpc/internal/status`, and moving just the `statusError` type there, exporting it (rename to `StatusError`), and updating the references to it in `grpc/status` accordingly.
