### ISSUE TITLE
Underscores in metadata keys

### ISSUE THREAD

**Issue by asad-awadia** [grpc/grpc-go#3311]
When I make a request with metadata that has `_` in the key - it gets dropped on server side

`val client = Metadata.Key.of("client", Metadata.ASCII_STRING_MARSHALLER)` <-- goes through

`val client = Metadata.Key.of("cli_ent", Metadata.ASCII_STRING_MARSHALLER)` <-- gets dropped

Is there a reason for this?

**Comment by menghanl** [comment]
This doesn't seems like a gRPC-Go question. Please ask in http://github.com/grpc/grpc or http://github.com/grpc/grpc-java.
