### ISSUE TITLE
Does commit #336cf8d76145dc5ebd517fd9c19e14c6822450b3 break google.golang.org/api?

### ISSUE THREAD

**Issue by jherman** [grpc/grpc-go#3312]
I recently pulled latest, and now can't compile:

```
# google.golang.org/api/option
..\..\..\google.golang.org\api\option\option.go:153:14: undefined: grpc.RoundRobin
..\..\..\google.golang.org\api\option\option.go:154:42: undefined: grpc.WithBalancer
```
This commit https://github.com/grpc/grpc-go/commit/336cf8d76145dc5ebd517fd9c19e14c6822450b3 seems to remove the balancer.go file (and moves it under the balancer dir) so these definitions are now gone. Any advice?

**Comment by jherman** [comment]
Paging @dfawley since he committed this change.

**Comment by jherman** [comment]
Just noticed this case is related to https://github.com/googleapis/google-api-go-client/issues/441

**Comment by thoratou** [comment]
+1, completely blocks https://github.com/google/skicka installation

**Comment by aratic** [comment]
i just do 'git revert 336cf8d' at 'src\google.golang.org\grpc` and things works for me : ) , thanks @jherman

**Comment by max202021** [comment]
This issue completely breaks all docker build and automated builds

**Comment by zdenham** [comment]
I was able to resolve this by using go modules to version dependencies rather than pulling latest (which standard package manager now anyhow). 

Also needed to upgrade my docker image to pull from one which supports modules `FROM golang:1.13` < golang 1.11  won't have support for modules

**Comment by aratic** [comment]
was it applicable to revert this change, and only merge this (along with unit test / compatible check / wrapper if any ) when corresponding subsequent modules compile / usage went smooth ?

**Comment by dfawley** [comment]
Let's track this under https://github.com/googleapis/google-api-go-client/issues/441, as this is an issue caused by the usage of our experimental (and now deleted) APIs.
