### ISSUE TITLE
Server stream handler return value is mapped to status code of OutOfRange 

### ISSUE THREAD

**Issue by arshanh** [grpc/grpc-go#3325]
When I return io.EOF in a stream handler the client side code sees OUT_OF_RANGE error as the status code of the RPC error.  I understand it is incorrect to return an EOF from a stream handler, and you should return nil, but that aside where is the OUT_OF_RANGE code coming from?

Note: this issue seems fixed on the master branch. Is this tracked by another bug?

### What version of gRPC are you using?
1.9.1
### What version of Go are you using (`go version`)?
go1.13.3
### What operating system (Linux, Windows, …) and version?
Mac OSx 10.14.6
### What did you do?
If possible, provide a recipe for reproducing the error.
Take the route_guide example as is and make the following modifications:

in grpc/examples/route_guide/server/server.go change RouteChat to return different values on EOF. Shown below:
```
 // RouteChat receives a stream of message/location pairs, and responds with a stream of all
 // previous messages at each of those locations.
 func (s *routeGuideServer) RouteChat(stream pb.RouteGuide_RouteChatServer) error {
     for {
         in, err := stream.Recv()
         if err == io.EOF {
             return io.EOF // Client receives: rpc error: code = OutOfRange desc = EOF
             // return errors.New("EOF") // Client recieves: rpc error: code = Unknown desc = EOF
             // return errors.New("foo") // Client recieves: rpc error: code = Unknown desc = foo
             // return nil
         }
         if err != nil {
             return err
         }
         key := serialize(in.Location)

         s.mu.Lock()
         s.routeNotes[key] = append(s.routeNotes[key], in)
         // Note: this copy prevents blocking other clients while serving this one.
         // We don't need to do a deep copy, because elements in the slice are
         // insert-only and never modified.
         rn := make([]*pb.RouteNote, len(s.routeNotes[key]))
         copy(rn, s.routeNotes[key])
         s.mu.Unlock()

         for _, note := range rn {
             if err := stream.Send(note); err != nil {
                 return err
             }
         }
     }
 }
```
In grpc/examples/route_guide/client/client.go:
In runRouteChat() Simply print out the err code:
```
in, err := stream.Recv()
fmt.Printf("%v\n", err)
```
Then run the server and then the client

### What did you expect to see?
I expect to see 
```
rpc error: code = Unknown desc = EOF
```

### What did you see instead?
Instead I see
```
rpc error: code = OutOfRange desc = EOF
```

**Comment by easwars** [comment]
`v1.9.1` is more than two years old at this point. I tried spending some time to dig out when things changed, but couldn't and given that `master` is working as expected, I do not see much value in spending more time on tracking down when this changed.

Since `io.EOF` indicates that the message stream has ended without any errors, if there a specific reason you want to return an `error` at that point?

Also, is updating to a more recent gRPC version an option for you?
