### ISSUE TITLE
../../go.etcd.io/etcd/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:28:2: use of internal package google.golang.org/grpc/internal/buffer not allowed ../../go.etcd.io/etcd/vendor/google.golang.org/grpc/resolver/dns/dns_resolver.go:27:2: use of internal package google.golang.org/grpc/internal/resolver/dns not allowed ../../go.etcd.io/etcd/vendor/google.golang.org/grpc/resolver/passthrough/passthrough.go:26:8: use of internal package google.golang.org/grpc/internal/resolver/passthrough not allowed

### ISSUE THREAD

**Issue by shumintao** [grpc/grpc-go#3327]
When I used go-micro, etcd was discovered as a service.
I found this problem when I went run main.go
I hope someone can help solve this problem

############*************** #####
/Users/facebook/go/src/github.com/coreos/etcd/vendor/google.golang.org/grpc/internal/buffer
/Users/facebook/go/src/github.com/coreos/etcd/vendor/google.golang.org/grpc/resolver/dns

**Comment by thomasbielagk** [comment]
try setting GO111MODULE=on as environment variable, that did it for me

**Comment by dfawley** [comment]
If that doesn't fix your problem, please make sure to fill in the template that appears when filing a bug so we can help:

----

Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?

### What version of Go are you using (`go version`)?

### What operating system (Linux, Windows, …) and version?

### What did you do?
If possible, provide a recipe for reproducing the error.

### What did you expect to see?

### What did you see instead?
