### ISSUE TITLE
Utilize grpc.ClientConnInterace in inteceptor.go

### ISSUE THREAD

**Issue by edwarnicke** [grpc/grpc-go#3349]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?

I was incredible happy to see the grpc.ClientConnInterface, which is now being used in proto-gen-go, but I noticed that the grpc.*ClientInterceptor are still using grpc.ClientConn.  I would like to also be able to use grpc.ClientConn with Interceptors.

### Proposed Solution
Switch over grpc.*ClientInterceptor to using grpc.ClientConnInteraface.   If switching them over is acceptable, I'd be delighted to submit a PR.  I wanted to check first to see if there was a reason they have not been switched.

### Additional Context

grpc.ClientConnInterface makes it possible to mock grpc.ClientConn and thus improve unit testing of GRPCs written in go :)

**Comment by dfawley** [comment]
Unfortunately, this would be a breaking change.  `ClientConnInterface` does not have a method for every `ClientConn` method, only the two required to start unary and streaming RPCs.  So any users relying upon those methods (e.g. to check connectivity state) would be broken.

If you can explain a little more about what you're trying to do, we may be able to suggest alternative solutions.

**Comment by edwarnicke** [comment]
@dfawley I sort of expected that was the case :)

I trying to transition my code base to using the ClientConnInterface pervasively, because it lets me do some very very nice things around unit testing.  I am using the OpenTracing GRPC Interceptors.  Therefore, I wanted to be able to utilize ClientConnInterface with them.  Upon investigation, I discovered the continued use of ClientConn in grpc... and suspected things were as you indicated (avoiding a breaking change)... but thought it worth asking.

**Comment by edwarnicke** [comment]
To put a bit more color on it...

I have grpc Servers - unit testing those is usually lovely.

Because I have needs within our broader community for folks to build *slight* variations of some of those servers ( think 90% common functionality, 10% unique) I've been structuring those GRPC servers in chains... so when you need to write an instance of that server, you can write the 10% of your unique functionality as a chain element, and then just string the pieces together.

I've ended up doing much the same chaining on the Client side as well... but obviously at the end there's a 'real' Client.

Because some of my servers need to invoke clients... not being able to mock out grpc.ClientConnInterface makes it difficult to unit test the servers.

Which is why I got so excited to see the *grpc.ClientConn -> grpc.ClientConnInterface shift :)

**Comment by edwarnicke** [comment]
OK... I've poked around a bit more... it does not appear that my ability to do my unit testing is inhibited by the inability to use grpc.ClientConnInterface with Interceptors at this time (I'm more or less a Consumer of Interceptors, not a provider).

I do appreciate your prompt response to this issue.  Count me as a (perhaps overenthusiastic) user of the grpc.ClientConnInterface!
