### ISSUE TITLE
Can I use single connection for client unary call?

### ISSUE THREAD

**Issue by LennonRuangjaroon** [grpc/grpc-go#3358]
This is my sample code.
It establishes a single gRPC connection for request to gRPC server and when HTTP request to '/users', The Handler will call to gRPC Server. 

Is this the correct way to use a single gRPC connection?
```

func (h *Handler) createUser() {
	clientCtx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	h.userServiceClient.CreateUser(clientCtx, &user.CreateUserRequest{})
}

type Handler struct {
	userServiceClient user.UserServiceClient
}

func NewHandler(u user.UserServiceClient) *Handler {
	return &Handler{userServiceClient: u}
}

func main() {
	conn, _ := connectGRPC("localhost:50032")
	handler := NewHandler(user.NewUserServiceClient(conn))

	router := http.NewServeMux()
	router.HandleFunc("/users", func(res http.ResponseWriter, req *http.Request) {
		handler.createUser()
	})

	server := &http.Server{
		Handler: router,
		Addr:    fmt.Sprintf(":%s", "8080"),
	}

	go func() {
		fmt.Println(server.ListenAndServe())
	}()

	gracefulStop := make(chan os.Signal, 1)
	signal.Notify(gracefulStop, syscall.SIGTERM, syscall.SIGINT)

	select {
	case <-gracefulStop:
		disConnectGRPC(conn)
	}

}

func connectGRPC(url string) (*grpc.ClientConn, error) {
	opts := []grpc.DialOption{grpc.WithInsecure()}
	return grpc.Dial(url, opts...)
}

func disConnectGRPC(conn *grpc.ClientConn) {
	err := conn.Close()
	if err != nil {
		logger.Errorf("cannot close connection, %v", err)
	}
}

```

**Comment by dfawley** [comment]
This seems OK to me.  Are you asking because you are having problems?

**Comment by LennonRuangjaroon** [comment]
@dfawley I don't have problems but I'm not sure when I used a single connection. Because before, I used one connection per one client request, Then I open and close connection every client request to a server.
if my code is ok and I should configure keepalive or handle long idle session?

**Comment by dfawley** [comment]
Keepalive is available in case you have a proxy in the middle of your connection that might close the connection.  If that's not the case, you shouldn't have to worry about it.  Even if the connection is lost, grpc will reconnect automatically.

I'll close this issue; let us know if you have any problems.

**Comment by LennonRuangjaroon** [comment]
@dfawley Thank you so much for your answer.
