### ISSUE TITLE
Grpc server errors not reaching client

### ISSUE THREAD

**Issue by jnvillar** [grpc/grpc-go#3363]
go-micro version: 1.15
go version: 1.12
os: devian

My grpc server returns a custom error, for example

type error struct{
 code int
 customField int
}

In my client, the error received is the go-micro error instead of my custom error. Only the shared fields are mapped (for example the code field). 

I would like to have my custom error embebed into the go-micro error or receive my custom error instead

**Comment by vtolstov** [comment]
this issue must be in go-micro repo.
