### ISSUE TITLE
Questions about grpc load balance

### ISSUE THREAD

**Issue by harlanc** [grpc/grpc-go#3367]
About some LB ways mentioned in the [md](https://github.com/grpc/grpc/blob/master/doc/load-balancing.md)

- Proxy Model
- Balancing-aware Client
- External Load Balancing Service

Which one has grcp-go implemented already?

As I understand, only some parts of balancing feathers are implemented, but not all,Some has implement a full [demo](https://github.com/liyue201/grpc-lb) for Balancing-aware Client using etcd3/consul. And External Load Balancing Service is not yet implemented ? that's right?

What's your plan?

**Comment by menghanl** [comment]
Sorry for the delay. gRPC does have support for load balancing.

> Proxy Model

This would be a separate proxy process (or machine) that intercept and forward the traffic. This will be out of gRPC.

> Balancing-aware Client
> External Load Balancing Service

These two would be balancing policies as plugins. gRPC supports [`balancer` API](https://github.com/grpc/grpc-go/blob/master/balancer/balancer.go). You can implement your own balancers, or use those come with gRPC (`pickfirst` and `roundrobin`).

There's a balancer ["grpclb"](https://github.com/grpc/grpc-go/tree/master/balancer/grpclb) that supports external load balancing service. But it's deprecated and there's no official server side implementation for it.
We are now working on an `xds` based balancer for external load balancing service.

The demo you pointed to is using `roundrobin` balancer, with a name resolver that discovers addresses from etcd.

You can also find examples of [name_resolving](https://github.com/grpc/grpc-go/tree/master/examples/features/name_resolving) and [load_balancing](https://github.com/grpc/grpc-go/tree/master/examples/features/load_balancing).
