### ISSUE TITLE
is there a method to accept and send variables of any type in grpc?

### ISSUE THREAD

**Issue by CulionBEAR** [grpc/grpc-go#3369]
in the normal,i want to write a method:

```
message a{
    int32 id=1;
}

message b{
    string name=1;
}

service b{
    rpc c(a) returns (a);
}
```

in the method 'c',it can accept a type 'a' and send it,but method 'c' can't accept and send message 'b'.
now,i want to write a method that can accept and send variables of any type...
is there any way?

**Comment by menghanl** [comment]
You need wrap the message in an `oneof`:
https://developers.google.com/protocol-buffers/docs/proto3#oneof

Or use `Any`:
https://developers.google.com/protocol-buffers/docs/proto3#any

This is more of a protobuf question, not a gRPC question. Closing the issue now.
