### ISSUE TITLE
cleanup: replace manual.GenerateAndRegisterManualResolver with grpc.WithResolvers

### ISSUE THREAD

**Issue by menghanl** [grpc/grpc-go#3380]
In many tests, `manual.GenerateAndRegisterManualResolver` registers a testing resolver, which is removed after the test.

`grpc.WithResolvers` should have the same effect, but in a much cleaner way.
Example:
https://github.com/grpc/grpc-go/blob/6b9bf4296edc5fae722a5dff887a954ffc599b12/clientconn_test.go#L537-L546

**Comment by dwalker-va** [comment]
Feedback:
As far as Semver and Go Mod goes, removing this function was actually a breaking change. We had some of our libraries using it and were surprised when it was removed in a minor version bump.

**Comment by dfawley** [comment]
Looks like we botched the "Experimental" warning on this package - there isn't one here at all.  It does declare things from the `resolver` package (which is experimental) as part of its API, but it doesn't explicitly declare *itself* as being experimental.  We should mark it as such.  I'm not completely sure, but we may have intended this to be for internal testing purposes only.

Sorry for the breakage.  Note that this package should be considered unstable moving forward, so if you can't tolerate breakages, we should talk about your use cases so we can find a stable way to do what you need.
