### ISSUE TITLE
how to use health check service

### ISSUE THREAD

**Issue by mattharrigan** [grpc/grpc-go#3382]
Hello,

I am new to go and grpc. I would like to add a health check to a grpc server. I have reviewed https://pkg.go.dev/google.golang.org/grpc/health?tab=doc. However I am not sure how I am supposed to actually use it. Is there an example of that? It seems like the following would be close, but I am not sure what to use for the service description. If this is the intended way to use the health check, then exporting this description would be very helpful. Thank you

```
grpcServer := grpc.NewServer()
healthServer := health.NewServer()
grpcServer .RegisterService(&_Health_serviceDesc, healthServer)
```

**Comment by mattharrigan** [comment]
The [reflection](https://github.com/grpc/grpc-go/blob/master/Documentation/server-reflection-tutorial.md#enable-server-reflection) documentation has what I think is the ideal content in this respect.

**Comment by menghanl** [comment]
This is a dup of https://github.com/grpc/grpc-go/issues/2770, and there's a PR in progress (#3381). Closing.
