### ISSUE TITLE
Building Your First Network

### ISSUE THREAD

**Issue by Tribitbo** [grpc/grpc-go#3384]
I'm Building Your First Network but 
**Error: got unexpected status: SERVICE_UNAVAILABLE -- backing Kafka cluster has not completed booting; try again later.** 
Help me !

**Comment by menghanl** [comment]
Can you provide more details of what you did and what you expected to see?

And can you confirm this is the gRPC issue (because you mentioned `Kafka`, and the error message doesn't look like something generated by gRPC)

**Comment by Tribitbo** [comment]
Hi Menghan Li,
I have built it successfully before, but when I load and run from the
beginning again, i gets an error like this:



*Error: got unexpected status: BAD_REQUEST -- error applying config update
to existing channel 'mychannel': error authorizing update: error validating
ReadSet: proposed update requires that key [Group]  /Channel/Application be
at version 0, but it is currently at version 1!!!!!!!!!!!!!!! Channel
creation failed !!!!!!!!!!!!!!!!========= ERROR !!! FAILED to execute
End-2-End Scenario ===========*

I tried to fix it thanks to google but it failed, can you help me fix this
error?

Best regards,

Trí.


Vào Th 6, 21 thg 2, 2020 vào lúc 04:21 Menghan Li <
notifications@github.com> đã viết:

**Comment by menghanl** [comment]
From the log, it's not clear what environment this is, or if gRPC is involved. There's no much we can help with here.

Closing as this doesn't look as a gRPC issue.
