### ISSUE TITLE
how to use compose UnaryServerInterceptor's that pass values

### ISSUE THREAD

**Issue by mattharrigan** [grpc/grpc-go#3388]
Hello,

I am writing a caching interceptor using grpc.UnaryServerInterceptor.  The basic functionality is working as expected.  How can I pass info such as whether there was a cache hit to another interceptor that does logging or metrics?

My ideal interface would be:
`type UnaryServerInterceptor func(ctx context.Context, req interface{}, info *UnaryServerInfo, handler UnaryHandler) (context.Context, interface{}, error)`

`type UnaryHandler func(ctx context.Context, req interface{}) (context.Context, interface{}, error)`

The returned context could be a child context with values that the logging or metrics (or whatever really) interceptor could use.  I believe this would be a good use of context since the values are both request specific and not essential to basic functionality.

I recognize that the above interface would be a major breaking change.  Is there another way to achieve the goal of passing values to another interceptor when returning from an interceptor or handler using the existing api?

Thank you

**Comment by menghanl** [comment]
If you make sure the logging interceptor is called after the caching interceptor, logging should be able to get the information from context. See the interceptor test: https://github.com/grpc/grpc-go/blob/7392afe7d20560a41a1c7f833fc6d48242608645/test/server_test.go#L66-L69

**Comment by mattharrigan** [comment]
That example works for passing values down the call chain, but I want to pass them back up the call chain.  Specifically for metrics, that should probably be the outermost interceptor so the timer can start at the beginning of the request.  But it would also need to be inside the cache interceptor to get that information.  Basically I want to compose interceptors and pass values both down and back up the chain.  However I don't see a way to pass them back up without ugly hacks

**Comment by menghanl** [comment]
There is a (bit hacky) way to do this: pass a pointer to the context to be populated by the inner interceptor.

```go
// Outer (metric) interceptor
type key struct{}
type data struct {
  cacheHit bool
}

d := &data{}
ctx = context.WithValue(ctx, key{}, d)

// Call handler, which will call the inner interceptor

fmt.Printf("cache hit: %v\n", d.cacheHit)
```

```go
// Inner interceptor
d := ctx.Value(key{}).(*data)
resp, cacheHit := cache.Get(req)

d.cacheHit = cacheHit

// Other things
return resp
```

**Comment by mattharrigan** [comment]
That definitely isn't the hackiest thing I've ever seen and should work.  Thank you for answering my question.
