### ISSUE TITLE
Client: Pending requests wait forever after connection failure

### ISSUE THREAD

**Issue by floridoo** [grpc/grpc-go#339]
**Go version:**  go1.5 darwin/amd64

**What did you do?**
* Send an RPC call to the server
* Before the server can answer, shut down the server (e.g. have a `time.Sleep()` on the server to reproduce)
* Restart the server

**What did you expect to see?**
* Client should resend the request when the connection is back up

**What did you see instead?**
* Client waits forever ([call.go#L158](https://github.com/grpc/grpc-go/blob/master/call.go#L158)), even though the connection is back up
* Happens because `transportSeq` is reset on each reconnect here: [clientconn.go#L307](https://github.com/grpc/grpc-go/blob/master/clientconn.go#L307). Removing this line resolves the issue.

**Comment by iamqizhao** [comment]
Thanks for reporting. Looking ...

**Comment by iamqizhao** [comment]
Sent #340 to fix. Let me know if the problem sustains.

**Comment by floridoo** [comment]
That fixed it. Thanks!
