### ISSUE TITLE
Limit grpc-server connection 

### ISSUE THREAD

**Issue by yabetsu93** [grpc/grpc-go#3398]
Please see the FAQ in our main README.md before submitting your issue.
One problem for the grpc is that when limiting the memory size to 50mb or < 2Gb,
it would be better to set a limit of number of connection in grpc-server.
In this way the developer can be able to manage and persist the number of 
connection working on specific apps, services or any type of task what the devs wants,
Currently only setting the max receive and send message size is possible but hope this
would be possible in grpc-golang.

### Use case(s) - what problem will this feature solve?
This would be able to control the grpc-server connection by limiting it and also to
avoid memory constrain.

### Proposed Solution
Possibility to set a grpc-server connection limit

**Comment by easwars** [comment]
You could possibly limit the number of simultaneous connections on the gRPC server by passing it a [LimitListener](https://godoc.org/golang.org/x/net/netutil) instead of a regular `net.Listener`.

**Comment by yabetsu93** [comment]
LimitListener do we have documentation with this in grpc-go?

**Comment by menghanl** [comment]
LimitListener is not a gRPC feature. It's from the official `x/net/` package.

**Comment by yabetsu93** [comment]
Yeah i searched it thanks but this means it limits the server and grpc
connection as well?

**Comment by yabetsu93** [comment]
rather would be nice if this also available option in grpc-server
