### ISSUE TITLE
transport: Error while dialing dial tcp: address ::1:12345: too many colons in address

### ISSUE THREAD

**Issue by kvaradhan3** [grpc/grpc-go#3399]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
goHW ➜ go list -m all 
...
google.golang.org/grpc v1.27.1

### What version of Go are you using (`go version`)?
goHW ➜ go version 
go version go1.13.8 darwin/amd64

### What operating system (Linux, Windows, …) and version?
goHW ➜ uname -a 
Darwin kvaradhan-mbp 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

### What did you do?
If possible, provide a recipe for reproducing the error.

Following code snippet:

    fmt.Printf("Addresses returned by LookupHost(%s): %v\n", "localhost", addrs)
    fmt.Printf("ipaddr: %s, port %s\n", ipaddr, port)
    conn, err := grpc.Dial(ipaddr+port, grpc.WithInsecure())
    if err != nil {
        log.Fatalf("did not connect: %v", err)
    }

    h := pb.NewHelloWorldClient(conn)
    ctx, _ := context.WithTimeout(context.Background(), time.Second)
    r, err := h.HelloWorld(ctx, &pb.Hello{ Rqst: name })
    if err != nil {
        log.Fatalf("could not greet: %v", err)
    }
    log.Printf(">msg: %s <cookie: %d", name, r.Cookie)j

Works when IPv4 addresses are used, fails when IPv6 addresses are used.

The entirety of the code sends a message to an echo server and prints the response.

### What did you expect to see?

When working, i.e. with IPv4 address for localhost: 127.0.0.1, we see:

```
goHW ➜ go run client1/HW-grpcClient-1.go
Addresses returned by LookupHost(localhost): [::1 127.0.0.1]
ipaddr: 127.0.0.1, port :12345
INFO: 2020/02/25 23:35:17 parsed scheme: ""
INFO: 2020/02/25 23:35:17 scheme "" not registered, fallback to default scheme
INFO: 2020/02/25 23:35:17 ccResolverWrapper: sending update to cc: {[{127.0.0.1:12345  <nil> 0 <nil>}] <nil> <nil>}
INFO: 2020/02/25 23:35:17 ClientConn switching balancer to "pick_first"
INFO: 2020/02/25 23:35:17 blockingPicker: the picked transport is not ready, loop back to repick
INFO: 2020/02/25 23:35:17 pickfirstBalancer: HandleSubConnStateChange: 0xc0000ad960, {CONNECTING <nil>}
INFO: 2020/02/25 23:35:17 pickfirstBalancer: HandleSubConnStateChange: 0xc0000ad960, {READY <nil>}
**2020/02/25 23:35:17 >msg: XYZ425794 <cookie: 140954425**
```

### What did you see instead?
When the IPv6 address is picked, we get:

```
goHW ➜ go run client1/HW-grpcClient-1.go
Addresses returned by LookupHost(localhost): [::1 127.0.0.1]
ipaddr: ::1, port :12345
INFO: 2020/02/25 23:35:21 parsed scheme: ""
INFO: 2020/02/25 23:35:21 scheme "" not registered, fallback to default scheme
INFO: 2020/02/25 23:35:21 ccResolverWrapper: sending update to cc: {[{::1:12345  <nil> 0 <nil>}] <nil> <nil>}
INFO: 2020/02/25 23:35:21 ClientConn switching balancer to "pick_first"
INFO: 2020/02/25 23:35:21 pickfirstBalancer: HandleSubConnStateChange: 0xc000021980, {CONNECTING <nil>}
INFO: 2020/02/25 23:35:21 blockingPicker: the picked transport is not ready, loop back to repick
WARNING: 2020/02/25 23:35:21 grpc: addrConn.createTransport failed to connect to {::1:12345  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp: address ::1:12345: too many colons in address". Reconnecting...
INFO: 2020/02/25 23:35:21 pickfirstBalancer: HandleSubConnStateChange: 0xc000021980, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial tcp: address ::1:12345: too many colons in address"}
**2020/02/25 23:35:21 could not greet: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address ::1:12345: too many colons in address"**
```

**Comment by menghanl** [comment]
IPv6 address needs to be surrounded by `[::1]:12345`.
Use [net.JoinHostPort](https://pkg.go.dev/net?tab=doc#JoinHostPort) to join host and port instead of `+` or `fmt.Sprintf`.

**Comment by kvaradhan3** [comment]
Yep  I had it working brute force, by always tagging "[]" to the ip address,
but I like @menghanl's suggestion better.
Thanks,
