### ISSUE TITLE
Understanding how the `newFuncServerOption` function works.

### ISSUE THREAD

**Issue by margach** [grpc/grpc-go#3404]
I would like to understand how the `newFuncServerOption` function works, it is called by say `WriteBufferSize` function, it takes in a function definition and returns a reference to the `funcServerOption` creating an instance of the object.

How then is the passed function called, this is the part I don't get.

**Comment by easwars** [comment]
The `funcServerOption` struct implements the [ServerOption](https://github.com/grpc/grpc-go/blob/master/server.go#L147) interface.

In [NewServer](https://github.com/grpc/grpc-go/blob/master/server.go#L415) which is passed a bunch of `ServerOption`s, the `apply` method on each of those options is called. This ends up calling the function stored within the `funcServerOption`.

HTH.
