### ISSUE TITLE
encoding.Codec type not present in package encoding

### ISSUE THREAD

**Issue by margach** [grpc/grpc-go#3419]
After describing type `type Codec`, it states that it's deprecated and that `encoding.Codec` should be used, thing is, they is no type Codec in package `encoding`.

**Comment by dfawley** [comment]
There must be something wrong with your copy of grpc, because it is there in our repo and visible in godoc:

https://github.com/grpc/grpc-go/blob/master/encoding/encoding.go#L78
https://godoc.org/google.golang.org/grpc/encoding#Codec

**Comment by margach** [comment]
Yes, the type is defined in the grpc package but in the package documentation, it states that the type is deprecated and we should use `encoding.Codec`

https://godoc.org/google.golang.org/grpc#Codec

**Comment by dfawley** [comment]
Correct.  The type you referenced (`grpc.Codec`) is deprecated in favor of using the one I referenced in my comment above (`encoding.Codec`).
