### ISSUE TITLE
transport.NewFramer  consume too much memory

### ISSUE THREAD

**Issue by t57root** [grpc/grpc-go#3421]
### What version of gRPC are you using?

v1.27.1 (v1.26.0 too)

### What version of Go are you using (`go version`)?

go version go1.13.5 linux/amd64

### What operating system (Linux, Windows, …) and version?

centos 7.2

I implement a grpc for data collecting, the network traffic the server dealing with is about 200M,(including both receiving and sending，shown in the result of `dstat` command) , but the memory the grpc server consuming is keep growing up to 120G(RSS) untill killed by OOM.

Is this normal?  Thanks in advance!
<pre>
(pprof) top -cum 20
Showing nodes accounting for 4495.46MB, 86.89% of 5173.85MB total
Dropped 266 nodes (cum <= 25.87MB)
Showing top 20 nodes out of 77
      flat  flat%   sum%        cum   cum%
         0     0%     0%  3999.20MB 77.30%  google.golang.org/grpc.(*Server).Serve.func3
         0     0%     0%  3999.20MB 77.30%  google.golang.org/grpc.(*Server).handleRawConn
         0     0%     0%  3837.70MB 74.17%  google.golang.org/grpc.(*Server).newHTTP2Transport
         0     0%     0%  3837.70MB 74.17%  google.golang.org/grpc/internal/transport.NewServerTransport
   32.51MB  0.63%  0.63%  3837.70MB 74.17%  google.golang.org/grpc/internal/transport.newHTTP2Server
         0     0%  0.63%  3796.70MB 73.38%  google.golang.org/grpc/internal/transport.newFramer
 2484.75MB 48.03% 48.65%  2484.75MB 48.03%  google.golang.org/grpc/internal/transport.newBufWriter
 1293.44MB 25.00% 73.65%  1293.44MB 25.00%  bufio.NewReaderSize
         0     0% 73.65%   838.03MB 16.20%  google.golang.org/grpc.(*Server).handleRawConn.func1
    1.50MB 0.029% 73.68%   838.03MB 16.20%  google.golang.org/grpc.(*Server).serveStreams
         0     0% 73.68%   836.53MB 16.17%  google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams
         0     0% 73.68%   643.88MB 12.44%  golang.org/x/net/http2.(*Framer).ReadFrame
       3MB 0.058% 73.74%   379.77MB  7.34%  bytes.(*Buffer).grow
  376.77MB  7.28% 81.02%   376.77MB  7.28%  bytes.makeSlice
      14MB  0.27% 81.29%   307.98MB  5.95%  golang.org/x/net/http2.(*Framer).readMetaFrame
         0     0% 81.29%   293.98MB  5.68%  golang.org/x/net/http2/hpack.(*Decoder).Write
         0     0% 81.29%   293.98MB  5.68%  golang.org/x/net/http2/hpack.(*Decoder).parseHeaderFieldRepr
         0     0% 81.29%   290.48MB  5.61%  golang.org/x/net/http2/hpack.(*Decoder).parseFieldLiteral
         0     0% 81.29%   289.49MB  5.60%  golang.org/x/net/http2/hpack.(*dynamicTable).add
  289.49MB  5.60% 86.89%   289.49MB  5.60%  golang.org/x/net/http2/hpack.(*headerFieldTable).addEntry
</pre>

**Comment by t57root** [comment]
@easwars  This grpc server basically does three types of work:  1) receive data and pass them into a message queue, 2) receive data and store them into a database,  and 3) receive request then return the requested data which is retrieved from database to the clients. 
The code is kinda large and I'm working on figuring out which grpc endpoint is causing the problem.
I found someone also encounter this problem [link](https://stackoverflow.com/questions/60107401/golang-grpc-transport-newbufwriter-and-bufio-newreadersize-not-releasing-memory)

**Comment by easwars** [comment]
1. Are you setting `ReadBufferSize` or `WriteBufferSize` to a non-default value using a `ServerOption?
2. Could you grab a pprof heap profile and goroutine when your server is about to OOM?
3. How many connections is your server handling? Do you use a limit listener?
4. Is it possible that your server is receiving the frames, but the serviceHandler is not fast enough to read those messages?
5. Also, do you have gRPC keepalives enabled? I'm thinking if it's possible that the client connection dies, but your service handler isn't aware of it and is blocked somewhere and the received frames are not getting cleaned up.

**Comment by t57root** [comment]
@easwars Thanks for the reply, which helps me a lot. I found out there're 30k handler goroutines blocking on awaiting a read lock somehow while no one is holding the write lock, which I can't figure out the reason. Nevertheless I rewrite the handler code to remove the lock, and the number of goroutines become normal and the memory growth rate drops down.

But the memory usage is still 10GB while handling 26k connections(57% used by `transport.newFramer` and 32% by `http2.(*Framer).ReadFrame`).  And keep growing about 300M per day. Is this normal again?

**Comment by menghanl** [comment]
Transport has read and write buffers, default is 32k each. They can be control by server options:
https://godoc.org/google.golang.org/grpc#ReadBufferSize https://godoc.org/google.golang.org/grpc#WriteBufferSize
Try setting them to a smaller number?

**Comment by t57root** [comment]
@menghanl  I am not setting `ReadBufferSize` or `WriteBufferSize`. I think the default value 32k is small enough for the messages, do I still need to set them to a smaller number?  Also what's bothering me mostly is the growth of memory everyday. Thanks!

**Comment by menghanl** [comment]
You don't need to set the size to a small number in production if you think it's small enough.
But as an experiment, try to set it to a small number and see how it affects the memory usage?

Memory shouldn't keep growing, it should be release after the connection is closed. Do you use streaming RPCs? Do the RPCs stay connected but idle?

Another thing to consider is that connection can be shared by RPCs, by making RPCs on the same ClientConn. Doing this on the client side may reduce the number of connections.
