### ISSUE TITLE
Unary rpc requests will leak memory in a weak network environment on the server

### ISSUE THREAD

**Issue by xinxindu** [grpc/grpc-go#3455]
What version of gRPC are you using?
the v1.28.0 version

What version of Go are you using (go version)?
go version go1.12.4 linux/amd64

What operating system (Linux, Windows, …) and version?
l linux/amd64

What did you do?
Unary rpc requests will leak memory in a weak network environment on the server, when qps is more than 1k.  
Finally, when qps is 0, the memory cannot be reduced.

What did you expect to see?
What parameters does grpc have to control this kind of memory leak.

![image](https://user-images.githubusercontent.com/40918825/76584610-27867d80-6517-11ea-8f90-04a4f72b44ca.png)
![image](https://user-images.githubusercontent.com/40918825/76584619-2fdeb880-6517-11ea-8be2-915449919f38.png)

**Comment by menghanl** [comment]
How many connections do you have?

Each connection has send and receive buffers. They can be configured by:
https://godoc.org/google.golang.org/grpc#ReadBufferSize
https://godoc.org/google.golang.org/grpc#WriteBufferSize

The memory should be garbage collected eventually, when the connections are done, and if there's no reference.

**Comment by xinxindu** [comment]
@menghanl

**Comment by xinxindu** [comment]
Finally,  when qps is 0, the memory cannot be reduced.
I found 5-10 socket connections in centos, but has not request for grpc server.
Please help to see if there is a problem with the calling method.

Place of use:
`conn, err := grpc.Dial(address, grpc.WithInsecure(), grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(1024*1024*512)))
if err != nil {
	return nil, nil, fmt.Errorf("dial to %s error: %v", address, err)
}
client := traffic_agent.NewTrafficAgentServiceClient(conn)
ctx, cancel := context.WithDeadline(context.Background(), time.Now().Add(time.Second*time.Duration(5)))
client.GetFile(ctx, &traffic_agent.GetFileRequest{
		Domain: domain1,
		Uri:    urlWithoutDomain, 
})
cancel()
`

**Comment by menghanl** [comment]
This client code look right.

But I thought the memory usage we are talking about is the server side. The server code would be more interesting.

**Comment by xinxindu** [comment]
Please look at it.
```
func (g *GrpcServer) Start() {
       go func() {
		listener, err := net.Listen("tcp", fmt.Sprintf(":%d", g.port))
		if err != nil {
			return
		}

		grpcServer := grpc.NewServer(grpc.MaxRecvMsgSize(256 * 1024 * 1024))
		trafficAgentProtos.RegisterTrafficAgentServiceServer(grpcServer, g)
		err = grpcServer.Serve(listener)
		if err != nil {
			return
		}
   }()
}

func (g *GrpcServer) GetFile(cxt context.Context, req *trafficAgentProtos.GetFileRequest) (*trafficAgentProtos.GetFileResponse, error) {
       res := &trafficAgentProtos.GetFileResponse{
		IsExist: true
	}
	return res, nil
}
```

**Comment by menghanl** [comment]
The server code doesn't show anything abnormal.

Actually, the code you sent doesn't have much more information than a simple helloworld. So it doesn't show how you use the server.

It might be hard for you to come up with a skeleton of service code that also shows the problem.
I would suggest do more investigation on your side, try to disable different component and see if the memory usage is different. This can help nail down to the root cause.
