### ISSUE TITLE
ServerStream.SendMsg(m interface{}): reusing messages safe?

### ISSUE THREAD

**Issue by asido** [grpc/grpc-go#3458]
Suppose there is protobuf struct `mypb.Message`. If I call `ServerStream.SendMsg(m interface{})`, where `m` is an instance of that struct, gRPC will use `mypb.Message.Marshal()` method, which allocates a new `[]byte`, to marshal itself.

If one sends many `mypb.Message` , for example in a tight loop, it results in high RAM usage and pressure to GC. I could think of creating a reusable message, that can marshals itself into a single buffer multiple times. For example:

```
type ReusableMessage struct {
	PB     mypb.Message
	buffer []byte
}

// gRPC encoder uses this interface to discover the marshal method.
var _ proto.Marshaler = &ReusableMessage{}

func (m *ReusableMessage) Marshal() ([]byte, error) {
	sz := m.PB.Size()
	if len(m.buffer) < sz {
		m.buffer = make([]byte, sz)
	}
	n, err := m.PB.MarshalTo(m.buffer)
	return m.buffer[:n], err
}
```

Now I can send the messages without allocate a new `[]byte` for each.
```
reusable := ReusableMessage{}
for _, m := range messages {
	reusable.PB = m
	ServerStream.SendMsg(reusable)
}
```

But the question comes is that safe? Can I be sure the buffer won't be read once `ServerStream.SendMsg` returns?

**Comment by menghanl** [comment]
The buffer could be read after `SendMsg` returns. It only pushs the transport write action into a queue.

There was #3167 to reuse the buffer for sending messages. It was reverted (#3338). But we plan to roll it forwarded with the bug fixed.

**Comment by menghanl** [comment]
Closing this as a dup of the issue tracking rolling forward the buffer reuse change (https://github.com/grpc/grpc-go/issues/3307#issuecomment-583118822)
