### ISSUE TITLE
grpclb and round_robin

### ISSUE THREAD

**Issue by amenzhinsky** [grpc/grpc-go#3462]
Hi there,
Is there a way to roundrobin connections across multiple grpclb balancers?

I have a resolver that returns two balancers:
```
{
	Addr: "127.0.0.1:8080",
	Type: resolver.GRPCLB,
},
{
	Addr: "127.0.0.1:8181",
	Type: resolver.GRPCLB,
},
```
client requests reach only the first. I do understand that I can shuffle them every lookup but I was wondering whether there's a nicer way to do this, e.g. through service config, `{"loadBalancingConfig":[{"grpclb":{"childPolicy":[{"round_robin":{}}]}}]}` seem to have no effect (probably I misusing it).

Log:
```
INFO: 2020/03/17 15:31:43 parsed scheme: "grpclb-internal"
INFO: 2020/03/17 15:31:43 ccResolverWrapper: sending update to cc: {[{127.0.0.1:8080  <nil> 0 <nil>} {127.0.0.1:8181  <nil> 0 <nil>}] <nil> <nil>}
INFO: 2020/03/17 15:31:43 ClientConn switching balancer to "pick_first"
INFO: 2020/03/17 15:31:43 Channel switches to new LB policy "pick_first"
INFO: 2020/03/17 15:31:43 Subchannel Connectivity change to CONNECTING
INFO: 2020/03/17 15:31:43 Subchannel picks a new address "127.0.0.1:8080" to connect
```

Thanks in advance.

**Comment by menghanl** [comment]
This is not supported. The clientconn inside grpclb uses pick_first, so it will always connect to the first address. The child policy in balancer config is for the backend addresses.

Why do you want to shuffle between two grpclb servers?
If they return different backend addresses, what do you want the client to do? Do you want the client to disconnect and connect to the new backends?
If they always return the same backend addresses, then what's the purpose?

If you want to balance the loads when there are multiple clients, shuffling in the resolver would help.

**Comment by amenzhinsky** [comment]
Just realized that round_robin wouldn't help here because grpclb is a single stream.

The idea is to spread clients among multiple load-balancers, shuffling should work just fine.

Thanks for the response.
