### ISSUE TITLE
Empty->nil in `repeated` serialization

### ISSUE THREAD

**Issue by zblach** [grpc/grpc-go#3464]
When serializing and empty list as a repeating value in a protobuf, the deserialized version of this protobuf contains a `nil` instead of an empty list.

This is unexpected, as an empty list is iterable and a `nil` is not. 

Similar bugs have pointed out the `json:"omitempty"` directive in the generated code, but I'm not using json in this example.

### What version of gRPC are you using?
libprotoc 3.11.4

### What version of Go are you using (`go version`)?
go1.14

### What operating system (Linux, Windows, …) and version?
osx catalina 10.15.3

### What did you do?
Sample protobuf definition:
```
message Items {
    string name = 1;
    repeated string item = 2;
}
```

Test code:
```
import (
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"google.golang.org/grpc/encoding"
	encodingProto "google.golang.org/grpc/encoding/proto"
)

func TestEmptyVersusNil(t *testing.T) {
	items := &Items{
		Name: "example",
		Item: []string{},
	}

	nativeSerializer := encoding.GetCodec(encodingProto.Name)
	bs, err := nativeSerializer.Marshal(items)

	require.NoError(t, err)

	items2 := &Items{}

	require.NoError(t, nativeSerializer.Unmarshal(bs, items2))

	assert.Equal(t, items.Name, items2.Name)
	assert.NotNil(t, items.Item)
	assert.Nil(t, items2.Item)
}
```

### What did you expect to see?
An empty slice.

### What did you see instead?
nil

**Comment by menghanl** [comment]
Both nil and empty slice should be iterable: https://play.golang.org/p/kk2ISMoYP-Q

And this is not a gRPC issue. For protobuf issues, please use https://github.com/golang/protobuf
