### ISSUE TITLE
stats: add method streaming type info to RPCTagInfo

### ISSUE THREAD

**Issue by abursavich** [grpc/grpc-go#3481]
### Use case(s) - what problem will this feature solve?

I use a `stats.Handler` to record Prometheus metrics for which I would like to include `grpc_type` labels (e.g. `Unary`, `ClientStream`, `ServerStream`, `BidiStream`), but this basic method information is not natively available to the `stats.Handler`.

### Proposed Solution

Add `IsClientStream, IsServerStream bool` to the `stats.RPCTagInfo` struct.

### Alternatives Considered

My current workaround is to add Unary and Stream Interceptors, which use context values to pass the method type down to the handler.

**Comment by dfawley** [comment]
Can you explain more about your use case?  Why is the RPC type useful to have in your metrics?
