### ISSUE TITLE
PickFirst load balancer won't try the next address even if the connect to first address keeps timeout.

### ISSUE THREAD

**Issue by t57root** [grpc/grpc-go#3482]
If the connect to the first address keeps time out, the load balancer seems to keep trying the same address forever without moving on to the next address.
I have a firewall between client and server, this behavior makes the clients never connect to the server if the first address is blocked. I think it's better to move to next address after some timeouts just like when it meets connection refused. 
Using a custom dialer with `WithContextDialer`, to wrap timeout as an non-tempory Error is a solution.
But I think maybe providing an option to treat a number of timeouts as non-tempory error is better.

**Comment by dfawley** [comment]
@t57root 

Are you using the DNS name resolver?  By default, grpc-go uses "passthrough" which passes the dial target (the parameter to `grpc.Dial`) directly to gRPC, meaning pick-first will only see that one "address", and the underlying `net.Dial` will only ever try the first entry in DNS.  Make sure you are doing `grpc.Dial("dns:///<hostname>")`.

**Comment by t57root** [comment]
@dfawley I'm using a custom name resolver with a custom url schema, which fetches address list from a grpc server(using dns:///). The address list is ordered by server load. I newly added one server(but forgot to add the ip into the firewall rule), and its load is very low, so it's always the first address in the address list for a period of time.
Now I implement a custom dialer to wrap timeout as non-tempory error, the pick_first does try next address.

**Comment by dfawley** [comment]
> Now I implement a custom dialer to wrap timeout as non-tempory error, the pick_first does try next address.

This doesn't sound right to me.  The only thing temporary dial errors do on the client side is affect the behavior of `grpc.Dial` with the `WithFailOnNonTempDialError` `DialOption`.  So I don't think that should have any effect like you mentioned.  Either way, it sounds like you have resolved the issue, and if so, feel free to close it.
