### ISSUE TITLE
Using PrepareMsg API in ServerStream

### ISSUE THREAD

**Issue by eafzali** [grpc/grpc-go#3489]
### Use case(s) - what problem will this feature solve?
We have server that sends really large payloads, our benchmarks shows that most of the cpu time on server is used for serialization. we tried caching the `PreparedMsg`s and sending them and we saw a huge improvement.

### Proposed Solution
https://github.com/grpc/grpc-go/pull/3480

### Alternatives Considered
We are now using a custom Codec and send `[]byte` in `stream.SendMsg()` as a workaround. 

### Additional Context
https://github.com/grpc/grpc-go/issues/2432

**Comment by easwars** [comment]
Assigning to @dfawley who is the assigned reviewer of #3480.

**Comment by easwars** [comment]
Assigning the `fixit` label to make a decision on whether we want to proceed with this change or not.
