### ISSUE TITLE
Can messages be lost in grpc send even though the stream is not closed?

### ISSUE THREAD

**Issue by arjunsingri** [grpc/grpc-go#3492]
We are using grpc for pushing messages from server to client. Is there a possibility that after the server calls grpc stream send, the messages are not received by the client even though the client/sever hasn't closed the stream?

**Comment by dfawley** [comment]
Yes, such a condition is possible.  The client may be busy, could hang or crash, or the network could become disconnected before the message reaches it.

In gRPC, the server doesn't know whether the client received the messages unless there is an explicit ack from the client in your protocol for it.

**Comment by dfawley** [comment]
If the client is still connected, and is just not reading from the stream, nothing in keepalive will kill the connection.  MaxConnectionIdle only activates when there are no streams, and if the client responds to the server's keepalive pings, then the connection will not be closed.  If it has crashed or hung so badly pings cannot be acked, then the connection would be closed.

My recommendation, based on what I can tell you're trying to do, is have the client explicitly tell the server the last data it received when it reconnects.  OR, send acks in the messages it streams to the server so the server will be able to keep track of that.

**Comment by arjunsingri** [comment]
I apologize for commenting on a closed issue. But what would be the behavior when the server keeps sending data on a stream that has been opened by the client, but the client never calls the `Recv` function?

**Comment by dfawley** [comment]
Eventually the flow control on the stream would cause the server's `Send` call to block.  It would stay in that state until the RPC deadline (if any) is reached, or the connection dies, or the client starts calling `Recv`.
