### ISSUE TITLE
Need the whole library be go get-able from github.com

### ISSUE THREAD

**Issue by soltanmm** [grpc/grpc-go#350]
_From @xtaci on September 18, 2015 7:33_

In Mainland China we CANNOT access google.golang.org/grpc and related golang.org/x/net/context without VPN. It's so painful for building automatic process.

_Copied from original issue: grpc/grpc#3376_

**Comment by soltanmm** [comment]
_From @johnnyluo586 on September 18, 2015 7:39_

I often encounter this problem, very upset, it is strongly recommended that stored in github.com

**Comment by dsymonds** [comment]
Sorry that your network situation sucks.

However, you can still fetch everything okay if you side-step `go get`:

```
git clone https://github.com/grpc/grpc-go $GOPATH/src/google.golang.org/grpc
git clone https://go.googlesource.com/net $GOPATH/src/golang.org/x/net
```

**Comment by iamqizhao** [comment]
If my memory works, I remember I could not access github at all without VPN
when I was in China ... Unfortunately, this is a problem you have to figure
out by yourself. :)

**Comment by xiang90** [comment]
@iamqizhao You can access github, but not google service in China mainland.
