### ISSUE TITLE
Go gRPC Gateway - Type of one field in JSON is not same as in proto.

### ISSUE THREAD

**Issue by xs2tarunkukreja** [grpc/grpc-go#3503]
We have one gRPC Go server which is wrapped by Grpc Gateway. So, out web portal is communicated with Gateway in Http protocol and internally gRPC gateway and gRPC server are communicating by gRPC protocol.

Most of the call is working fine. Only one call response is having an issue. Type specified in proto file is integer but JSON response having type as String. 

Some useful details -
We are having 2 protos file - One file is imported in another proto file.

Type issue is coming in imported file message.

**Comment by menghanl** [comment]
This doesn't sound like a gRPC issue. Please file an issue at https://github.com/grpc-ecosystem/grpc-gateway instead. Thanks.
