### ISSUE TITLE
credentials: suggest updating doc strings for NewClientTLSFromCert et. al.

### ISSUE THREAD

**Issue by Capstan** [grpc/grpc-go#3507]
Both [`NewClientTLSFromCert`](https://godoc.org/google.golang.org/grpc/credentials#NewClientTLSFromCert) and [`NewClientTLSFromFile`](https://godoc.org/google.golang.org/grpc/credentials#NewClientTLSFromFile)'s doc strings are misleading:

> NewClientTLSFromCert constructs TLS credentials from the input certificate for client.

To me, a "certificate for client" implies a client certificate, aka mutual TLS, and something that would be put in the [`tls.Config`](https://godoc.org/crypto/tls#Config)`.Certificates` for use in authenticating the client to the server. As a result, I'd been repeatedly manually recreating `NewClientTLSFromCert`, especially in test code. I realize, post-facto, that it was written in comparison to [`NewServerTLSFromCert`](https://godoc.org/google.golang.org/grpc/credentials#NewServerTLSFromCert) which reads

> NewServerTLSFromCert constructs TLS credentials from the input certificate for server.

but it is ambiguous when considered independently. I suggest that these change the doc string to read

> NewClientTLSFromCert constructs TLS credentials from the provided root certificate authority certificate(s) to validate server connections.

**Comment by easwars** [comment]
I agree with you. I think this should be changed.
