### ISSUE TITLE
Auto-reconnect for Go clients?

### ISSUE THREAD

**Issue by proteneer** [grpc/grpc-go#351]
@iamqizhao 

What is the the correct way for Go clients to recover EOF errors upon closing a server connection?

eg:

http2Client.notifyError got notified that the client transport was broken EOF.

This error happens when the server is restarted, but upon restarting the client doesn't recognize this and all subsequent connections hang. What is the reconnect/retry time? It seems way too slow right now.

**Comment by dsymonds** [comment]
A Go client should automatically reconnect. Getting back an EOF (because the TCP connection died) should cause an immediate reconnect, I believe.

**Comment by proteneer** [comment]
Should it cause an immediate reconnect? I assume the first time it tries to reconnect it will fail, (since it probably happens in between the server restart). I'm trying to figure out where the reconnect/retry code is.

**Comment by iamqizhao** [comment]
grpc has a backoff strategy for reconnecting (
https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md). The go
impl is at https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L288.

**Comment by proteneer** [comment]
I'm debugging this still - I stuck a bunch of fmt.Println's in backoff() and it's only ever being called once. Even the server's connection breaks it's not automatically reconnecting for some reason.

**Comment by proteneer** [comment]
It looks like resetTransport poll only works when the client initially tries to connect to the server upon startup.

When a previously working server is disconnected, it looks like notifyError() is called, which closes the http2Client's errorChan (which doesn't seem to actually do anything), and sets its state to unreachable.

But I'm not seeing how this is triggering resetTransport() to resume the connection.

**Comment by iamqizhao** [comment]
see https://github.com/grpc/grpc-go/blob/master/clientconn.go#L384.

**Comment by proteneer** [comment]
I stuck a print in the select statement:
```
	for {
		fmt.Println("polling")
		select {
		// shutdownChan is needed to detect the teardown when
		// the ClientConn is idle (i.e., no RPC in flight).
		case <-cc.shutdownChan:
			fmt.Println("shutdown chan invoked!")
			return
		case <-cc.transport.Error():

			fmt.Println("transport error detected")

			cc.mu.Lock()
			cc.state = TransientFailure
			cc.stateCV.Broadcast()
			cc.mu.Unlock()
			if err := cc.resetTransport(true); err != nil {
				// The ClientConn is closing.
				grpclog.Printf("grpc: ClientConn.transportMonitor exits due to: %v", err)
				return
			}
			continue
		}
	}
```

It looks like shutdownChan is closed immediately, causing transportMonitor() code to return. Something is calling ClientConn.Close() immediately.

**Comment by iamqizhao** [comment]
I guess you set a timeout for the connection via https://github.com/grpc/grpc-go/blob/master/clientconn.go#L122. Did u?

**Comment by proteneer** [comment]
This was my fuck up.

I deferred a conn.Close() prematurely. What was unexpected was that the connection was still semi-working even after I call ClientConn.Close() it, hence the confusion.

Closing for now.


conn, err := grpc.Dial(config.RpcUri, grpc.WithInsecure())
