### ISSUE TITLE
How to make grpc receive max message size to unlimit by using MaxCallRecvMsgSize

### ISSUE THREAD

**Issue by fishpenguin** [grpc/grpc-go#3521]
### What did you do?
In C++ and python, I can set max receive message size value to -1 to make grpc receive message size to unlimit. I wonder how to achieve this in grpc-go.
I know that the size can be set using MaxCallRecvMsgSize, but it seems that the value cannot be set to -1.

**Comment by menghanl** [comment]
`-1` isn't supported, but you can set it to max-int.
The question is: do you care about the difference between "unlimited" and "a very big number"?

Even if `-1` is accepted, there will still be a limit somewhere along the process, and I guess we will end up using max-int.

**Comment by fishpenguin** [comment]
> `-1` isn't supported, but you can set it to max-int.
> The question is: do you care about the difference between "unlimited" and "a very big number"?
> 
> Even if `-1` is accepted, there will still be a limit somewhere along the process, and I guess we will end up using max-int.

In my case, I don't know how large dataset my grpc-go client will receive, it may be a pretty large pack.
I alse use grpc-python and grpc-C++, which can solve this problem by using -1. So I hope that grpc-go can achieve this propose.

**Comment by menghanl** [comment]
In that case, just use `math.MaxInt32`.
