### ISSUE TITLE
An event message when a client connected ?

### ISSUE THREAD

**Issue by bcashier** [grpc/grpc-go#3531]
Hi,

Is there a way to send a message to the first connection of a client in order to load datas on the page ?

See it like a welcome message.

Thank you

**Comment by menghanl** [comment]
The server doesn't send messages on the connections, they wait for streams (RPCs). Servers cannot start RPCs.

Can you provide more info about what you are trying to do? Examples with concrete scenarios/RPCs would be good. Thanks!

**Comment by bcashier** [comment]
> 
> 
> The server doesn't send messages on the connections, they wait for streams (RPCs). Servers cannot start RPCs.
> 
> Can you provide more info about what you are trying to do? Examples with concrete scenarios/RPCs would be good. Thanks!

Hi, thank you for your answer !

I have a website that listen to websocket message from the backend, and in order to show datas on first page load I have to fetch them from database (and this for each client).

So, the goal is to send the datas (first data that must be loaded on the page) from the backend directly through websockets on client connect and show them to users.

Unfortunately I don't have a code to show, just looking for if this scenario is possible with GRPC.

Thank you.

**Comment by menghanl** [comment]
I don't fully understand all your requirements.

But based on my understanding (and guess), you can send an RPC to the server as soon as the connection is created, and server can start to send responses when receives the RPC.

There are [4 types](https://grpc.io/docs/guides/concepts/#service-definition) of RPCs. If the client has something to send, put it in the request. If the client has nothing to send, send an empty request, or use a bidirectional streaming RPCs instead.

You also mentioned website, if you want to show the page in a browser, you will need to look into https://github.com/grpc/grpc-web

**Comment by bcashier** [comment]
This answer my question, I appreciate it ! Thank you.
