### ISSUE TITLE
Reduce garbage generation in http send of streaming messages

### ISSUE THREAD

**Issue by bboreham** [grpc/grpc-go#3560]
### Use case(s) - what problem will this feature solve?
Where streaming clients send messages under 16KB, `http2Client.Write()` doubles the memory used for serialisation by copying every message into a fresh allocation.

On this line, `hdr` is a 5-byte slice allocated in `msgHeader()`:
https://github.com/grpc/grpc-go/blob/03def2a1f3d4fd22fb566d561195c31330984c29/internal/transport/http2_client.go#L866

### Proposed Solution
Apologies, I don't know the codebase well.  Maybe `loopyWriter` could hold a single 16KB buffer to do the copy just before each frame write?

Or, if `PreparedMsg` allowed the re-use of `hdr`, it could be pre-allocated at 16KB.

### Additional Context
#2432 suggests the above direction - "would allow users to re-use a PreparedMsg, and may save allocations of internal buffers"

Excerpt from profile which prompted me to open this issue:
```
google.golang.org/grpc/internal/transport.(*http2Client).Write
/go/pkg/mod/google.golang.org/grpc@v1.25.1/internal/transport/http2_client.go

  Total:      5.53GB     5.64GB (flat, cum) 28.47%

    839            .          .           		// Add some data to grpc message header so that we can equally 
    840            .          .           		// distribute bytes across frames. 
    841            .          .           		emptyLen := http2MaxFrameLen - len(hdr) 
    842            .          .           		if emptyLen > len(data) { 
    843            .          .           			emptyLen = len(data) 
    844            .          .           		} 
    845       5.30GB     5.30GB           		hdr = append(hdr, data[:emptyLen]...) 
    846            .          .           		data = data[emptyLen:] 
    847            .          .           		df.h, df.d = hdr, data 
```

**Comment by easwars** [comment]
@bboreham 
What you are suggesting here doesn't seem to be off the mark. But the team does not have the resources at this point in time to work on this. We would be happy to review PRs if anyone wants to work on this.
Thank you for the report.
