### ISSUE TITLE
Need an option to wait until items are sent before closing connection

### ISSUE THREAD

**Issue by newrelic-eheinlein** [grpc/grpc-go#3578]
### Use case(s) - what problem will this feature solve?

When using `grpc.ClientStream`, I need a way to wait until data has been sent by the client (NOT received by the server) before I close the connection.

### Proposed Solution

Add a way to indicate that you want to block until all data has been flushed and sent before closing a connection - so something like `conn.FlushAndClose()` in place of just `conn.Close()`

### Alternatives Considered

In order to get this to work in our use case, we have added a `time.Sleep` call after calling `Send` on the last piece of data but before calling `conn.Close()`

### Additional Context

This is related to this issue: https://github.com/grpc/grpc-go/issues/2159

The summary is that I need a way to wait until data has been sent by the client (NOT received by the server) before I close the connection.

From the related issue, it seems like there are two options:
- Make sure to check to make sure EVERY span is received by the server, or
- Don't care whether the data is even sent at all

I am looking for a middle ground, where we wait until the data has been flushed and sent before closing the connection, but we don't wait to make sure that the server received it.

I have an example that demonstrates the issue that we are seeing here:

https://github.com/newrelic-eheinlein/grpc-example/blob/7a4c17c5b95f82f20ffff81636b7da4e42308748/grpc_example_test.go#L41-L42

This example test creates an in-memory gRPC server, then in a separate goroutine creates a client that connects to it, tries to send 5 things, and then closes the connection.  The key client code looks like this:
```go
	conn, _ := grpc.Dial("bufnet",
		grpc.WithDialer(dialer),
		grpc.WithInsecure(),
	)
	defer func() {
		// This is the key sleep here
		time.Sleep(500 * time.Millisecond)
		_ = conn.Close()
	}()
```

In this example, there is an optional call to `Sleep` before calling `conn.Close()`
Without the call to `Sleep`, I see output like this when running the test:
```
=== RUN   TestTraceObserverRoundTrip
    TestTraceObserverRoundTrip: grpc_example_test.go:133: Did not receive expected spans before timeout - expected 5 but got 2
    TestTraceObserverRoundTrip: grpc_example_test.go:133: Did not receive expected spans before timeout - expected 5 but got 0
(...some lines omitted, there are many of these lines...)
    TestTraceObserverRoundTrip: grpc_example_test.go:133: Did not receive expected spans before timeout - expected 5 but got 1

--- FAIL: TestTraceObserverRoundTrip (98.14s)
FAIL

Process finished with exit code 1
```

If I uncomment the `Sleep` call so that my client waits the arbitrary amount of time before closing, I get this output every time:
```
=== RUN   TestTraceObserverRoundTrip
--- PASS: TestTraceObserverRoundTrip (25.12s)
PASS

Process finished with exit code 0
```

But I do not want to add in an arbitrary `Sleep` call to make sure things are sent - I just want a way to specify that I want to flush out any pending data before closing. Something like `conn.FlushAndClose()`, so that it will only wait as long as necessary (or until a timeout is reached). 

Is there any existing option to do what I want, or can it be added in the future?

**Comment by menghanl** [comment]
This is a dup of #1104 to add cliend side graceful close.

And the only way to make sure a message is received by the server is receiving a server response. So instead of sleeping, you should wait for a server response.

**Comment by newrelic-eheinlein** [comment]
> the only way to make sure a message is received by the server 

But I do not want to ensure that the message is received by the server; I only want to ensure that everything that is buffered to be sent has actually been sent before closing the connection. In our case we accept that some messages may get dropped and we don't want the overhead of checking for a response from the server, however testing has shown that without adding in a sleep, the *majority* of the time data that was already buffered is lost when we shutdown. We are willing to accept some dropped messages in unusual circumstances, but we are not willing to drop data pretty much every time we close the connection. This seems like pretty basic functionality and it really surprises me that it's not available.

The linked issue was opened over 3 years ago and closed over a year ago; is it safe to say that this will not be addressed in the foreseeable future?

**Comment by menghanl** [comment]
The issue #1104 is still open, but with a low priority. There was an attempt in 2019 (#2738) that didn't finish.
If you want, you can share you use case in the original issue, and it could be picked up by other contributors.

One option that may make the situation better is to change the [buffer size](https://godoc.org/google.golang.org/grpc#WithWriteBufferSize).

**Comment by newrelic-eheinlein** [comment]
Thank you for that additional information!  I will do some testing to see if a change to the buffer size will allow us to work around the issue without adding too much overhead.
