### ISSUE TITLE
What happens when server calls Send but client never calls Recv?

### ISSUE THREAD

**Issue by arjunsingri** [grpc/grpc-go#3586]
What would be the behavior when the server keeps sending data on a stream that has been opened by the client, but the client never calls the `Recv` function?

**Comment by dfawley** [comment]
As answered in #3492:

> Eventually the flow control on the stream would cause the server's Send call to block. It would stay in that state until the RPC deadline (if any) is reached, or the connection dies, or the client starts calling Recv.
