### ISSUE TITLE
protoc-gen-go: Regression in generated output

### ISSUE THREAD

**Issue by aldelucca1** [grpc/grpc-go#3591]
This issue was originally opened https://github.com/golang/protobuf/issues/1100 and copied over here upon request

### What version of gRPC are you using?
v1.29.1

### What version of Go are you using (`go version`)?
1.14.2

### What operating system (Linux, Windows, …) and version?
darwin/amd64

### What did you expect to see?
Protoc would generate a default implementation of the service interface in the form of
```go
type UnimplementedXXXServer struct {
}
```
with all methods implemented to return an error with code `codes.Unimplemented`.

In addition, the NewXXXClient would take an `grpc.ClientConnInterface` instead of the concrete `*grpc.ClientConn`

```go
func NewXXXClient(cc grpc.ClientConnInterface) XXXClient {
	return &xxxClient{cc}
}
```
### What did you see instead?

Instead there is no Unimplemented server type put out and the client stub relies on the `*grpc.ClientConn` directly
```go
func NewXXXClient(cc *grpc.ClientConn) XXXClient {
	return &xxxClient{cc}
}
```
It appears this regression occurred between the protobuf **1.3.5** and **1.4.0-rc1** tags

**Comment by menghanl** [comment]
Those are new features:
 - unimplemented service: https://github.com/grpc/grpc-go/issues/2318
 - ClientConnInterface: https://github.com/grpc/grpc-go/issues/1287

The generated code should be used as before, and the difference shouldn't cause any change in the application. Please reply to this if you have other questions.

**Comment by aldelucca1** [comment]
So the changes mentioned above were being generated as of 1.28.0 and are no longer being generated as of 1.29. And i appreciate that in most cases the code depending on the generated parts will continue to work. But in our case we began leveraging the exported Unimplemented service type, so the lack of it is causing issues

**Comment by menghanl** [comment]
Oh, I see. This is indeed a regression. It seems the proto v1.4.0 release has an old grpc generator. This is not expected.

I will open an issue in the proto repo to investigate.

**Comment by menghanl** [comment]
How do you run the code generator? Are you using the binary or the grpc package as a library?

From the reply in https://github.com/golang/protobuf/issues/1111, grpc codegen was moved to an internal package, and the exported package is outdated (and dead).

**Comment by aldelucca1** [comment]
We run the code generator via the protoc plugin installed by running go get github.com/golang/protobuf/protoc-gen-go as described in the quick start https://grpc.io/docs/quickstart/go/

**Comment by menghanl** [comment]
Then this shouldn't be a problem.

Can you try to make a small reproduction with steps? With the helloworld proto should be good. Thanks!

**Comment by aldelucca1** [comment]
Looks like this was fixed in https://github.com/golang/protobuf/commit/8d9af285403e1acdb3b235d3dcca77099325f417 and released as part of https://github.com/golang/protobuf/releases/tag/v1.4.1

**Comment by menghanl** [comment]
Glad that it works for you.

Since the fix works for you, I'm pretty sure you are using the grpc generator as a library. Just a note that this is not a supported usage. The package was moved to internal, and the exported one will not get updates.
