### ISSUE TITLE
grpc error : blockingPicker the picked transport is not ready, loop back to repick

### ISSUE THREAD

**Issue by cloudtrends** [grpc/grpc-go#3597]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?

    // Code generated by protoc-gen-go. DO NOT EDIT.
    // versions:
    // 	protoc-gen-go v1.21.0
    // 	protoc        v3.11.4
    // source: myproto.proto

### What version of Go are you using (`go version`)?
    go version go1.14.2 linux/amd64
### What operating system (Linux, Windows, …) and version?
    Ubuntu 20.04 
### What did you do?

    When I run both server and client by using " go run xxxxx.go " , the rpc can communication as expected , such as sending a ping-pong message.
    When I build server and client to binary file format , It shows above error message .

If possible, provide a recipe for reproducing the error.
    
rpc client side log 
===========

    INFO:  parsed scheme: ""
    INFO:  scheme "" not registered, fallback to default scheme
    INFO:  ccResolverWrapper: sending update to cc: {[{127.0.0.1:7777  <nil> 0 <nil>}] <nil> <nil>}
    INFO:  ClientConn switching balancer to "pick_first"
    INFO:  Channel switches to new LB policy "pick_first"
    INFO:  Subchannel Connectivity change to CONNECTING
    INFO:  blockingPicker: the picked transport is not ready, loop back to repick
    INFO:  Subchannel picks a new address "127.0.0.1:7777" to connect
    INFO:  pickfirstBalancer: HandleSubConnStateChange: 0xc0001c9180, {CONNECTING <nil>}
    INFO:  Channel Connectivity change to CONNECTING
    INFO:  Subchannel Connectivity change to READY
    INFO:  pickfirstBalancer: HandleSubConnStateChange: 0xc0001c9180, {READY <nil>}
    INFO:  Channel Connectivity change to READY
    INFO:  Subchannel Connectivity change to CONNECTING
    INFO:  Channel Connectivity change to SHUTDOWN
    INFO:  Subchannel Connectivity change to SHUTDOWN
    grpc: addrConn.createTransport failed to connect to {127.0.0.1:7777  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: operation was canceled". Reconnecting...
    transport: loopyWriter.run returning. connection error: desc = "transport is closing"

   rpc server side log 
   ========
    ERROR: 2020/05/04 23:37:06 transport: loopyWriter.run returning. Err: write tcp 127.0.0.1:7777->127.0.0.1:35574: write: bad file descriptor
    WARNING: 2020/05/04 23:37:06 transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:7777->127.0.0.1:35574: use of closed network connection

### What did you expect to see?
    
    I want client and server can communicating ...

### What did you see instead?

    "transport is closing"

**Comment by menghanl** [comment]
> use of closed network connection

Connection is closed before RPC finishes. Did you close ClientConn before the RPC ends?
Can you provide more details? Client and server code would be good.

**Comment by cloudtrends** [comment]
thanks for help, below is my client side pseudo code:

    conn, err = grpc.Dial(serverAddr, grpc.WithInsecure())  
    // this step is ok 
    defer conn.Close()
    //
    result, err = client.Call(context.Background(), reqParams)
    // after running the Call method 
    // there are two things :
    1)  the rpc server side could received the reqParams and running as expected
    2)  at client side with error :  code = Unavailable desc = transport is closing  .

**Comment by menghanl** [comment]
The code you shared is basically the helloworld client: https://github.com/grpc/grpc-go/blob/master/examples/helloworld/greeter_client/main.go#L43, and nothing seems wrong.

There must be some slight difference causing the error. I would suggest finding the line of root cause first.

**Comment by cloudtrends** [comment]
Thanks for help 
The issue is still occures on my own network ,I will do more test for make sure .  I close the issue for now .

**Comment by maxmeyer** [comment]
@cloudtrends I see this error on k3s as well
