### ISSUE TITLE
Is there a way to send customized error from load balancer to client and pops up to applicaiton level?

### ISSUE THREAD

**Issue by susanhuhu** [grpc/grpc-go#3598]
Current protocal allows sending load balance response back but it doesn't contain any error code.  When load balancer meets error, our implmentation returns error in Balanced method and client gets "Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Failed to create subchannel)"    Wondering if there is a way (even a hacky way) to let load balancer return a customized error.  In our scenario, we have zero scale logic for services.  So if load balancer finds a service is zero scaled and cannot get server list back, we hope to let client side application aware of this.   Wondering if this is acehiveable, and if code change is needed in grpc to achieve this, how big effort it will be.

**Comment by menghanl** [comment]
This repo is specific for gRPC-Go.

It seems you are using other language. Please file issue in the corresponding repo (grpc/grpc or grpc/grpc-java). Thanks.

**Comment by susanhuhu** [comment]
We are using gPRC-go for load balancer implementation and c# at client side.  So this issue still applies here.

**Comment by susanhuhu** [comment]
@menghanl ,  would you please help reopen the issue? seems I don't have permission to do it.

**Comment by menghanl** [comment]
So server side is gRPC-Go? How is the error with "Failed to create subchannel" created? If the error is a status error (https://pkg.go.dev/google.golang.org/grpc/status?tab=doc#Errorf), the client will receive the status code.

**Comment by susanhuhu** [comment]
great.  currently we return an error in below code, and error is  "return errors.New("PodNotReady for service - " + serviceName)".   So looks like if we return a status error,  client will pop it up to application? 
``` code
// BalanceLoad is an implementation of grpclb protocol and is called once per client
// this grpc is streaming and only returns on error or service disconnection
func (lb *loadBalancerService) BalanceLoad(stream grpc_lb_v1.LoadBalancer_BalanceLoadServer) error {
```

**Comment by menghanl** [comment]
Yes. `errors.New` creates a string error, and the status code for any non-status error is `Unknown`. Please try `status.Errorf()`.

**Comment by susanhuhu** [comment]
Thanks. will try this out.

**Comment by menghanl** [comment]
I think that should solve the problem.

I'm going to close the issue now. If you have further question, please reply. Thanks.
