### ISSUE TITLE
Error when I tried to run mockgen

### ISSUE THREAD

**Issue by NickTaporuk** [grpc/grpc-go#3599]
### What version of gRPC are you using?
    v1.29.1
### What version of Go are you using (`go version`)?
    go version go1.14.1 darwin/amd64
### What operating system (Linux, Windows, …) and version?
  MacOS Catalina 10.15.4
### What did you do?
I was tried to make mockgen generation of the mock file from the account.proto .
To build go file run :

	protoc \
		-I $(GOPATH)/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
		-I $(PROTO_DIR) \
		--go_out=plugins=grpc,paths=source_relative:$(PROTO_DIR) \
		$(PROTO_FILE_NAME)
That command built the file account.pb.go without any problem.
 
But when I tried to run mockgen in CLI: 
  mockgen -source=./proto/account.pb.go -destination ./mocks/account_mock.go -package mocks
I saw an error: 
  **imported package collision: "backoff" imported twice**
account.proto :

```
syntax = "proto3";

package account.v1 ;
option go_package = ".;account_v1";

import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";
import "google/api/annotations.proto";

// Account
service Account {
  // ListAccounts
  rpc ListAccounts(ListAccountsRequest) returns (ListAccountsResponse) {
    option (google.api.http) = {
      get: "/api/v1/users"
    };
  }
  // CreateAccount
  rpc CreateAccount(AccountCreateRequest) returns (AccountResponse) {
    option (google.api.http) = {
      post: "/api/v1/users"
      body:"*"
    };
  }
  // UpdateAccount
  rpc UpdateAccount(AccountRequest) returns (AccountResponse) {
    option (google.api.http) = {
      patch: "/api/v1/users/{id}"
      body: "*"
    };
  }

  // DeleteAccount
  rpc DeleteAccount(AccountDeleteRequest) returns (AccountResponse) {
    option (google.api.http) = {delete: "/api/v1/users/{id}"};
  }
  // AccountBalance
  rpc AccountBalance(AccountBalanceRequest) returns (AccountBalanceResponse) {
    option (google.api.http) = {get: "/api/v1/users/{id}/balance"};
  }

  // UpdateAccountBalance
  rpc UpdateAccountBalance(stream AccountUpdateBalanceRequest) returns ( stream AccountUpdateBalanceResponse) {}
}

// User
message User {
  uint64 id = 1;
  string name = 2;
  double balance = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
}


// UserCreate
message UserCreate {
  uint64 name = 1;
}

// UserAction
message UserDelete {
  uint64 id = 1;
}
// ListAccountsRequest
message ListAccountsRequest {
  // Only list users created after this timestamp
  google.protobuf.Timestamp created_since = 1;
  // Only list users older than this Duration
  google.protobuf.Duration older_than = 2;
}

// ListAccountsResponse
message ListAccountsResponse {
  repeated User users = 1;
}

// AccountResponse
message AccountRequest {
  uint64 id = 1;
  string name = 2;
  double balance = 3;
}

// AccountCreateRequest
message AccountCreateRequest {
  string name = 1;
}
//
message AccountDeleteRequest {
  uint64 id = 1;
}
// AccountResponse
message AccountResponse {
  User user = 1;
}

// AccountBalanceRequest
message AccountBalanceRequest {
  uint64 id = 1;
}

// AccountBalanceResponse
message AccountBalanceResponse {
  double balance = 1;
}

// AccountBalanceRequest
message AccountUpdateBalanceRequest {
  uint64 id = 1;
  double balance = 2;
}
// AccountUpdateBalanceResponse
message AccountUpdateBalanceResponse {
  uint64 id = 1;
  double balance = 2;
}
```

### What did you expect to see?
I did expect to see mock file for the my proto file
### What did you see instead?
I see error  **imported package collision: "backoff" imported twice**

**Comment by dfawley** [comment]
Does `proto/account.pb.go` build successfully?  (`go build ./proto/account.pb.go`)

**Comment by NickTaporuk** [comment]
Yes, ./proto/account.pb.go file built successfully.

**Comment by dfawley** [comment]
@NickTaporuk this sounds like a problem with `mockgen`, then, or your usage of it.  I'm afraid we can't help with this.

We do have a document covering how to use it with proto services ([link](https://github.com/grpc/grpc-go/blob/master/Documentation/gomock-example.md)), although I wouldn't personally recommend using mocks for this purpose.  It is more realistic and not significantly harder or more compute-intensive to create a fake service implementation and use a real gRPC server and client to test the client application.

**Comment by NickTaporuk** [comment]
When I tried to build account.pb.go without part of stream:
```
rpc UpdateAccountBalance(stream AccountUpdateBalanceRequest) returns ( stream 
       AccountUpdateBalanceResponse) {}
})
``` 

mockgen work correctly. I think it related to the stream part of the file.

**Comment by NickTaporuk** [comment]
@dfawley  I tried to build by this link. But result was the same. Error imported package collision: "backoff" imported twice. [link to the screenshot](https://prnt.sc/sax42a)

**Comment by dfawley** [comment]
If the example in our docs is wrong then that would be something we need to fix. I'll take a look.

**Comment by dfawley** [comment]
I can't reproduce the error you are seeing.  When I run the command the same way you do, I get a different error:
```
$ mockgen -source=./routeguide/route_guide.pb.go -destination ./mock_routeguide/account_mock.go -package mocks
2020/05/04 15:07:56 Loading input failed: loading package failed
```

However, when I run it the way instructed by our documentation, it works:

```
$ mockgen google.golang.org/grpc/examples/route_guide/routeguide RouteGuideClient,RouteGuide_RouteChatClient >| mock_routeguide/rg_mock.go
```

I'm not really familiar with `mockgen`, so I'm sorry I can't help with your usage.

**Comment by NickTaporuk** [comment]
Hi, guys. Thanks for your work. I have apriciated your fast answer. Thanks
a lot. I decided to use mockery. It helped to write tests without any
problems. Thanks.

вт, 5 мая 2020 г., 01:09 Doug Fawley <notifications@github.com>:
