### ISSUE TITLE
xds/internal: conflicting lock order in Remove() and Clear()

### ISSUE THREAD

**Issue by BurtonQin** [grpc/grpc-go#3602]
### What version of gRPC are you using?
master branch, commit c8482678eb49c6f3a6ab9288a5d61e4b8af3cae6
### What version of Go are you using (`go version`)?
Go 1.14.2
### What operating system (Linux, Windows, …) and version?
Linux
### What did you do?
I analyzed the code in xds/internal and found a case where the lock orders are conflicting, which may lead to deadlock.

The conflicting lock order may happen when `BalancerGroup.Remove()` and `TimeoutCache.Clear()` are called concurrently in two threads.

One mutex is `BalancerGroup.outgoingMu` on L207:
https://github.com/grpc/grpc-go/blob/a906ca0441ceb1f7cd4f5c7de30b8e81ce2ff5e8/xds/internal/balancer/balancergroup/balancergroup.go#L196-L207
The other mutex is `TimeoutCache.mu` on L37:
https://github.com/grpc/grpc-go/blob/c8482678eb49c6f3a6ab9288a5d61e4b8af3cae6/internal/cache/timeoutCache.go#L36-L40

1. **`BalancerGroup.outgoingMu` -> `TimeoutCache.mu`**
`BalancerGroup.outgoingMu.Lock()` is on L368, `TimeoutCache.Add()` is on L371:
https://github.com/grpc/grpc-go/blob/c8482678eb49c6f3a6ab9288a5d61e4b8af3cae6/xds/internal/balancer/balancergroup/balancergroup.go#L367-L371
`TimeoutCache.mu.Lock()` is on L59:
https://github.com/grpc/grpc-go/blob/c8482678eb49c6f3a6ab9288a5d61e4b8af3cae6/internal/cache/timeoutCache.go#L58-L82
Besides, we can find that `callback` is stored to `entry.callback` on L67. Then `entry` is stored to `c.cache` on L80.
2.  **`TimeoutCache.mu` -> `BalancerGroup.outgoingMu`**
`TimeoutCache.mu.Lock()` is on 126. `c.removeInternal()` is on L129:
https://github.com/grpc/grpc-go/blob/c8482678eb49c6f3a6ab9288a5d61e4b8af3cae6/internal/cache/timeoutCache.go#L125-L129
`c.removeInternal()` gets `entry` from `c.cache` on L103, then calls `entry.callback` on L119.
https://github.com/grpc/grpc-go/blob/c8482678eb49c6f3a6ab9288a5d61e4b8af3cae6/internal/cache/timeoutCache.go#L102-L122
`Remove()` calls `Add()` to add anonymous function to `cache`. So the above `entry.callback` can be this anonymous function. The anonymous function contains `BalancerGroup.outgoingMu.Lock()` on L375. 
https://github.com/grpc/grpc-go/blob/c8482678eb49c6f3a6ab9288a5d61e4b8af3cae6/xds/internal/balancer/balancergroup/balancergroup.go#L367-L375

### What did you expect to see?

--

### What did you see instead?

--

**Comment by menghanl** [comment]
Thanks a lot for detailed bug report.

The fix I think is that cache should call `callback` without holding the mutex. In fact, this should be the general case because `callback` usually holds a lock in case it's called in a goroutine (in this case, `time.After`). So the cache should always release the lock before `callback()`.

I have a fix in #3603. Please take a look. Thanks!

**Comment by BurtonQin** [comment]
Closed by #3603.
