### ISSUE TITLE
Where's the error? 

### ISSUE THREAD

**Issue by Codebreaker101** [grpc/grpc-go#3604]
I've been digging trough the source for the past two hours trying to find out where can I _plug_ myself in to see the raw error message bytes.

I have these questions:
1. When I return error from Unary handler where exactly is it marshaled? 
From what I've found out it uses [error_details.proto](https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto) but I can't find where is the call to marshal the object 
2. Where is it placed in HTTP/2 response? The [protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)  definition states that it is placed in the `Trailer` but when I read trailer metadata it is not there. 
3. What happens when using a custom codec? I use my own codec but only the response is Marshaled/Unmarshaled there, not the error message. 
4. Where can I _plug_ custom error Marshaler/Unmarshaler?

**Comment by dfawley** [comment]
The marshalling of the `grpc-status-details-bin` header field cannot be overridden.  Is there a reason you'd like to do this?

**Comment by Codebreaker101** [comment]
The reason for wanting to extend or create a new error model to include more data in the error response. For example
1. Validation errors
this has a form of _cca_ `[]struct { Field, Rule, Namespace, Message }`. I can't represent this with just the build-in error model. I could achieve this by setting error code `InvalidArgument` and then reading JSON string, or some other type, from metadata. Or I can set the error message to be a JSON string. 
2. Differentiating between different errors of the same status code. 
If I would to have a service that compares two CPU's and if one or both of the CPU's are not found, I would return the error code `NotFound`. But, which CPU was not found? Again, solved with additional metadata, or, perhaps, parsing the returned error message.

There are [some docs](https://grpc.io/docs/guides/error/#richer-error-model) regarding a richer error model, but it is quite limiting.

**Comment by dfawley** [comment]
Aha, I think I understand now.  I think what you're looking for is:

To attach details to a status:
https://godoc.org/google.golang.org/grpc/internal/status#Status.WithDetails

To read them back:
https://godoc.org/google.golang.org/grpc/internal/status#Status.Details

Yes, these are in an `internal` package, which is an unfortunate effect of how we needed to structure these and how godoc works with type aliases - this type and these methods are fully exposed to users via the type alias https://godoc.org/google.golang.org/grpc/status#Status.

**Comment by Codebreaker101** [comment]
Thank you for the links! 

Reading them I was unable to find a way to send my custom error object. 
There are [googleapis error_detail types](https://github.com/googleapis/go-genproto/blob/master/googleapis/rpc/errdetails/error_details.pb.go) that I can import. I can also create my own from `.proto` definition that will then be (internally) decoded based on the generated `.pb.go` on the client side (if I got this right). But I wish to use my own object with my own marshaler, without using `protobuf`. 

Since I can't  integrate my own marshaler, is there a way to put raw bytes as an entry to the `WithDetails` method? 

While writing this I have found the method of doing that. This does generate errors when trying to get details form status type (proto: not found), but I can access the underlying Proto message with the bytes. And I can use the `TypeUrl` as an indication of a ex. `NotFound` error type. 
It's neat, but it is hacky to say the least. 

``` go
type cpuNotFound struct {
	CPUOne bool
	CPUTwo bool
}

cpuNotFoundErrDetails := &cpuNotFound{
	CPUOne: false,
	CPUTwo: true,
}

err := status.ErrorProto(&spb.Status{
	Code:    888, // custom code
	Message: "Validation error has occurred",
	Details: []*any.Any{
		{Value: marshal(cpuNotFoundErrDetails), TypeUrl: "cpuNotFound"},
	},
})
```

**Comment by dfawley** [comment]
Sorry, but there is no way to attach raw bytes to `WithDetails`.  You could wrap whatever you came up with in a proto by encoding it as `bytes`, but `grpc-status-details-bin` itself must be a `google.rpc.Status proto` message for interoperability reasons.
