### ISSUE TITLE
grpc: failed dns A record lookup due to lookup

### ISSUE THREAD

**Issue by kgtom** [grpc/grpc-go#3609]
hello:
 When using grpc.WithBalancerName(roundrobin.Name), with a dns:/// Dial target, got this log:
grpc version:1.24.0
golang version:go1.12.16 darwin/amd64
k8s:1.15

my client code:
ps：
serviceName:hello-svc-headless
test is my k8s namespaces
grpc port:9090

~~~go
      ctx, _ := context.WithTimeout(context.Background(), 3*time.Second)
	conn, err := grpc.DialContext(ctx,"dns:///hello-svc-headless.test:9090", grpc.WithInsecure(), grpc.WithBalancerName(roundrobin.Name)) 
	if err != nil {
		log.WithField(log.Fields{
			"err": err,
		}).Fatal("Init hello-srv client failed")
	}
  client = NewHelloSvcServerClient(conn)
~~~
I got this info log:

{"level":"info","ts":"2020-05-07T15:36:35.364Z","caller":"grpclog/logger.go:67","msg":"grpc: failed dns A record lookup due to lookup hello-svc on 10.254.0.10:53: no such host.\n","env":"dev","serviceName":"pontus.dev","system":"grpc","grpc_log":true}

10.254.0.10 is k8s coredns  IP address.

I can't make it work - could you help? why i got this info log.

**Comment by dfawley** [comment]
Is it possible this is the same issue as #3572 ?
