### ISSUE TITLE
Potential bugs on old cores: using 64-bit functions sync/atomic

### ISSUE THREAD

**Issue by BurtonQin** [grpc/grpc-go#3612]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
master branch,
commit: a6ab4473c5a469332c1bdee691293affeaaece25

### What version of Go are you using (`go version`)?
go1.14.2

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?

I noticed that there are usages of atomic.LoadInt64, atomic.AddInt64, etc.
These 64-bit functions in sync/atomic can cause errors on old cores. Please see: https://golang.org/pkg/sync/atomic/#pkg-note-BUG
I am not sure if some users are running grpc-go on these old cores.

I reported this bug because I saw grpc-go developers viewed the usage of atomic64 functions as a bug and they easily fixed it in this [pull](https://github.com/grpc/grpc-go/pull/1411).
Maybe it is not a problem for grpc-go if users rarely use [those old cores](https://golang.org/pkg/sync/atomic/#pkg-note-BUG) mentioned by golang. Feel free to close this issue if you want.

Usage Position: (There may be more)
https://github.com/grpc/grpc-go/blob/a6ab4473c5a469332c1bdee691293affeaaece25/benchmark/primitives/syncmap_test.go#L66
https://github.com/grpc/grpc-go/blob/a6ab4473c5a469332c1bdee691293affeaaece25/benchmark/primitives/syncmap_test.go#L74

### What did you expect to see?

--

### What did you see instead?

--

**Comment by puellanivis** [comment]
ARMv6K looks like it was first used in ARM11MPCore which was announced in 2005.

Pentium MMX is even older and released in 1997.

At least insofar as the minimum Pentium MMX is concerned, I think it’s safe to say that no one is really going to be trying to use it.

As for ARMv6K, I don’t have enough history with ARM chips to say how likely it might be that someone is using such a chip.

**Comment by BurtonQin** [comment]
Thanks for your reply. I will close this issue.
