### ISSUE TITLE
Http Util Decode Header should not return error if the HTTP status code set is 200

### ISSUE THREAD

**Issue by a9kitkumarsinha** [grpc/grpc-go#3622]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
1.27.0

### What version of Go are you using (`go version`)?
1.14.1

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
We have a grpc server setup that is behind aws NLB and an envoy proxy. At high concurrency, we get this error.
`"rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field": 3268`
I digged into the code of grpc-golang to check this error. I found this error is coming from 
https://github.com/grpc/grpc-go/blob/master/internal/transport/http_util.go#L304

### What did you expect to see?
I expect that for status code 200, there will not be any error. 

### What did you see instead?
I got `"rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field"`

The decodeHeader method checks if the HTTP status is set and if it is set then it see if code exists in this mapping
`// HTTPStatusConvTab is the HTTP status code to gRPC error code conversion table.
	HTTPStatusConvTab = map[int]codes.Code{
		// 400 Bad Request - INTERNAL.
		http.StatusBadRequest: codes.Internal,
		// 401 Unauthorized  - UNAUTHENTICATED.
		http.StatusUnauthorized: codes.Unauthenticated,
		// 403 Forbidden - PERMISSION_DENIED.
		http.StatusForbidden: codes.PermissionDenied,
		// 404 Not Found - UNIMPLEMENTED.
		http.StatusNotFound: codes.Unimplemented,
		// 429 Too Many Requests - UNAVAILABLE.
		http.StatusTooManyRequests: codes.Unavailable,
		// 502 Bad Gateway - UNAVAILABLE.
		http.StatusBadGateway: codes.Unavailable,
		// 503 Service Unavailable - UNAVAILABLE.
		http.StatusServiceUnavailable: codes.Unavailable,
		// 504 Gateway timeout - UNAVAILABLE.
		http.StatusGatewayTimeout: codes.Unavailable,
	}`

If the status code is 200 then it will throw error with code UNKNOWN.

**Comment by menghanl** [comment]
It's working as intended for gRPC to return error, if the response doesn't have `content-type'. It's violating the spec: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses

The error code `unknown` is interesting. We should figure out what's the best error code to return.

**Comment by menghanl** [comment]
200 generating code unknown is also right, as mentioned here: https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md
> 200 is UNKNOWN because there should be a grpc-status in case of truly OK response
