### ISSUE TITLE
package .../googleapis/rpc/status: ...\genproto exists but ...\genproto\.git does not - stale checkout?

### ISSUE THREAD

**Issue by bcashier** [grpc/grpc-go#3624]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
Installing it like this: 

`
go get -u google.golang.org/grpc
`

### What version of Go are you using (`go version`)?
`
go version go1.12.6 windows/amd64
`

### What operating system (Linux, Windows, …) and version?
`
Windows 7 64bit
`
### What did you do?

Just tried to import gRPC packages in order to make tests and learn on it.

### What did you expect to see?

A clean and working import.

### What did you see instead?

Instead, I am getting this error message:
`
package google.golang.org/genproto/googleapis/rpc/status: C:\gorpc\src\google.golang.org\genproto exists but C:\gorpc\src\google.golang.org\genproto\.git does not - stale checkout?
`

I removed the folder: `src/golang.org/x/` many times, and retried but still getting the same thing.

Please help to solve this issue.

**Comment by menghanl** [comment]
Try removing `src/google.golang.org/genproto`?

And this is not a grpc specific problem. golang-nuts google group would be a good place to get help.
Closing the issue now.
