### ISSUE TITLE
Support Closer and Shutdowner interfaces, like http.Server

### ISSUE THREAD

**Issue by sfllaw** [grpc/grpc-go#3627]
# Use case(s) - what problem will this feature solve?

The standard library’s [`http.Server.Close`](https://pkg.go.dev/net/http/?tab=doc#Server.Close) and [`http.Server.Shutdown`](https://pkg.go.dev/net/http/?tab=doc#Server.Shutdown) methods are analogous to [`grpc.Server.Stop`](https://pkg.go.dev/google.golang.org/grpc?tab=doc#Server.Stop) and [`grpc.Server.GracefulStop`](https://pkg.go.dev/google.golang.org/grpc?tab=doc#Server.Stop).

When writing a program that wants to shutdown and/or stop both types of servers, it would be nice to be able to loop over them:

``` go
type Shutdowner interface {
	Shutdown(ctx context.Context) error
}

func shutdownAll(ctx context.Context, servers []Shutdowner) error {
	errch := make(chan error, len(servers))
	defer close(errch)

	var wg sync.WaitGroup
	for _, s := range servers {
		wg.Add(1)
		go func() {
			errch <- s.Shutdown(ctx)
			wg.Done()
		}()
	}
	wg.Wait()

	for _, err := range errch {
		if err != nil {
			return err
		}
	}
	return nil
}

type Closer interface {
	Close() error
}

func closeAll(servers []Closer) error {
	errch := make(chan error, len(servers))
	defer close(errch)

	var wg sync.WaitGroup()
	for _, s := range servers {
		wg.Add(1)
		go func() {
			errch <- s.Close()
			wg.Done()
		}()
	}
	wg.Wait()

	for _, err := range errch {
		if err != nil {
			return err
		}
	}
	return nil
}
```

### Proposed Solution

1. Implement `Close` as an alias to  `Stop`:
	``` go
	// Close is a convenience method that calls Stop.
	func (s *Server) Close() error {
		s.Stop()
		return nil
	}
	```

2. Implement `Shutdown`:
	``` go
	// Shutdown gracefully shuts down the server without interrupting any active connections.
	// Shutdown works by first closing all open listeners,
	// then closing all idle connections,
	// and then waiting indefinitely for connections to return to idle and then shut down.
	// If the provided context expires before the shutdown is complete,
	// Shutdown returns the context's error,
	// otherwise it returns any error returned from closing the Server's underlying listener(s).
	//
	// When Shutdown is called, Serve immediately returns ErrServerStopped.
	// Make sure the program doesn't exit and waits instead for Shutdown to return.
	//
	// Once Shutdown has been called on a server, it may not be reused;
	// future calls to Serve will return ErrServerStopped.
	func (s *Server) Shutdown(ctx context) error {
		// Close listener and drain connections:
		// ...

		// Wait for connections to finish or context cancellation.
		ticker := time.NewTicker(shutdownPollInterval)
		defer ticker.Stop()
		for {
			if len(s.conns) == 0 {
				break
			}

			select {
			case ctx<-Done():
				return ctx.Err()
			case <-ticker.C:
			}
		}

		// Finish events:
		// ...
	}
	```

3. Rewrite `GracefulStop` as a wrapper around `Shutdown` with a background context:
	``` go
	func (s *Server) GracefulStop() {
		if err := s.Shutdown(context.Background()); err != nil {
			panic(err)
		}
	}
	```

Alternatively, `Stop` could be a wrapper around `Close`. :shrug: 

### Additional Context

`http.Server.Shutdown` was introduced in Go 1.8 ([release notes](https://golang.org/doc/go1.8#http_shutdown)) which was released six months after `grpc.Server.GracefulStop` was implemented.

Generally, implementing the standard library interfaces increases the utility of a library. [`grpc.Server.ServeHTTP`](https://pkg.go.dev/google.golang.org/grpc?tab=doc#Server.ServeHTTP) is a good example of implementing the standard [`http.Handler`](https://pkg.go.dev/net/http/?tab=doc#Handler). This feature request is meant to increase the compatibility of `grpc.Server` with `http.Server`, especially when they are multiplexed over `ServeHTTP`.

**Comment by sfllaw** [comment]
This will also address #2448 which asked for a timeout on `GracefulStop`.

**Comment by dfawley** [comment]
Unfortunately, I don't believe we should extend our API with aliases to satisfy foreign interfaces.  However, it seems like you could wrap a `grpc.Server` in another struct that has these methods defined.

Also, note that the grpc-go team does not recommend using the grpc server as an `http.Handler`, due to a variety of reasons, as mentioned in the godoc for `ServeHTTP`.

**Comment by sfllaw** [comment]
> Unfortunately, I don't believe we should extend our API with aliases to satisfy foreign interfaces.

I am surprised by this response! The Go standard library is not exactly a foreign interface. I’d argue that it is the fount of all interfaces. :wink:

Since [`grpc.Server.Serve`](https://pkg.go.dev/google.golang.org/grpc?tab=doc#Server.Serve) implements `interface { Serve(net.Listener) error }` like [`http.Server.Serve`](https://pkg.go.dev/net/http/?tab=doc#Server.Serve), it seems reasonable to implement the `Closer` interface to match [`http.Server.Close`](https://pkg.go.dev/net/http/?tab=doc#Server.Close). I would have suggesting removing `grpc.Server.Stop` but that is a backwards incompatible change.

As for adding `grpc.Server.Shutdown`, [`http.Server.Shutdown`](https://pkg.go.dev/net/http/?tab=doc#Server.Shutdown) takes a `context.Context` while `grpc.Server.GracefulStop` blocks forever, which makes shutting down by a certain deadline more complicated than necessary.

> However, it seems like you could wrap a `grpc.Server` in another struct that has these methods defined.

When we added a gRPC server to our application, we discovered this impedance mismatch and wrote an adaptor to make `grpc.Server` fit into the standard library interface. We filed this issue because the adaptor was quite messy for `Shutdown` and thought you might agree to make this library more compatible.

If your objection is that you don’t have time to implement this functionality, then please reopen this issue and we will go through your CLA process and submit a pull request. If your objection is philosophical, then I guess this issue will just record your decision so others can find it.

> Also, note that the grpc-go team does not recommend using the grpc server as an `http.Handler`, due to a variety of reasons, as mentioned in the godoc for `ServeHTTP`.

Sorry, I shouldn’t have distracted this discussion with `ServeHTTP`, as that code path doesn’t require `Serve` at all.
