### ISSUE TITLE
xds: client close not safe to call concurrently

### ISSUE THREAD

**Issue by Astone-Chou** [grpc/grpc-go#3635]
https://github.com/grpc/grpc-go/blob/ff40ef4227c9e291b74f4cb81cdc74d57337c77a/xds/internal/client/client.go#L162-L172

maybe 
```
// Close closes the gRPC connection to the xDS server.
func (c *Client) Close() {
	if c.done.Fire() {
		// TODO: Should we invoke the registered callbacks here with an error that
		// the client is closed?
		c.v2c.close()
		c.cc.Close()
		c.logger.Infof("Shutdown")
        }
}
```

**Comment by menghanl** [comment]
This isn't a problem because `v2c.close` and `cc.close` are both safe.
Worst case is we get two "shutdown" logs.

And also, the xds client is never closed, until the parent clientconn is closed, and is only called once.
