### ISSUE TITLE
alts: Running on GKE gVisor gives error "ALTS is only supported on GCP"

### ISSUE THREAD

**Issue by Capstan** [grpc/grpc-go#3666]
I'm running a Go server in a fairly minimal docker image on GKE on GCP, and trying to authorize with ALTS yields the odd error that "ALTS is only supported on GCP".

https://github.com/grpc/grpc-go/blob/479df5ea818c360b6c5bb3db292ec0afb354c226/credentials/alts/utils.go#L88 currently tries to read `/sys/class/dmi/id/product_name`, which doesn't exist in the minimal container image I'm using.

Should there be an alternative model for not early erroring-out for Kubernetes containers, or is the requirement that Kubernetes always re-expose the Node's `/sys` mount to the Pods ([`hostPath` docs](https://kubernetes.io/docs/concepts/storage/#hostpath)) so that this business logic can continue to work?

**Comment by Capstan** [comment]
Also, even I wanted to add `/sys`, because we're using gVisor, it's not permitted. https://cloud.google.com/kubernetes-engine/docs/concepts/sandbox-pods#limitations-incompatible

**Comment by jiangtaoli2016** [comment]
We ran ALTS on GKE continuously and did not hit such problem. Did you have something special on your GKE config?

@apolcyn  FYI

**Comment by Capstan** [comment]
We have a variety of features on, from GKE Sandbox to WorkloadIdentity. That said, this seems to be very specifically related to code looking for a specifically existing file, which isn't part of the standard docker images we build.

@jiangtaoli2016 How are your images set up? How are your Deployments' PodSpec set up? Do you add in custom mounts of various things?

**Comment by Capstan** [comment]
After rebuilding our cluster w/o kubernetes alpha turned on, modern builds still fail in this manner, but amazingly the last "prod" build recovered, so this appears to have been introduced fairly recently (since May 3rd in the monorepo). Exactly when is unclear since our cluster had been failing since the 1.17 was pushed to the rapid channel. I'll see if I can binary search and figure it out.

**Comment by Capstan** [comment]
Looks like this was when we enabled GKE Sandbox / gVisor. Unfortunately, it was mostly hidden behind other issues in this cluster.

**Comment by easwars** [comment]
@cesarghali @jiangtaoli2016 
Is this still being looked at? Should this be closed? Thanks.

**Comment by jiangtaoli2016** [comment]
@Capstan Is GKE Sandbox/gVisor based on GCE VM? If yes, then we can find a way to make it work. If not, the underlying system may not support ALTS handshake.

**Comment by Capstan** [comment]
@jiangtaoli2016 Yes, this is all running on GKE on GCP.

**Comment by Capstan** [comment]
We know it supports the ALTS handshake because we kludged around this particular issue by faking the missing file using a `ConfigMap` mount.

**Comment by Capstan** [comment]
https://issuetracker.google.com/issues/158454608 tracks gVisor maybe doing something to expose this. Meanwhile grpc-java elected to close their bug because there's nothing actionable on the gRPC-side.

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/issues/5343 has more recent state on this issue. Closing this in favor of the former.
