### ISSUE TITLE
Unable to install protoc-gen-go-grpc

### ISSUE THREAD

**Issue by karthikraobr** [grpc/grpc-go#3668]
### What version of gRPC are you using?
v1.29.0
### What version of Go are you using (`go version`)?
go version go1.14.2 darwin/amd64
### What operating system (Linux, Windows, …) and version?
macOS Mojave
### What did you do?
I ran the following command:
`GO111MODULE=on go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.29.0`
If possible, provide a recipe for reproducing the error.

### What did you expect to see?
Nothing. If the installation of the tool was successful, the go command would have just exited
### What did you see instead?
` go get google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.29.0: module google.golang.org/grpc@v1.29.0 found, but does not contain package google.golang.org/grpc/cmd/protoc-gen-go-grpc `

**Comment by fabstu** [comment]
There was no new release yet since the merging of `protoc-gen-go-grpc`.

**Comment by dfawley** [comment]
Also, when it is released, it will have its own versioning, independent from gRPC-Go itself.
