### ISSUE TITLE
Require Unimplemented services to be embedded in our canonical generated code packages?

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#3674]
#3657 avoided this question, but we may need to do this, ultimately.  Observations:

1. Adding a method to a service is a backward-compatible _proto_ change.
2. Adding a method to a service is _not_ a backward-compatible change in grpc-go generated code, unless the `Unimplemented...Service` is embedded.
3. Changing the generated code to require users to embed `Unimplemented...Service` is also not backward-compatible.

However, doing (3) prevents (2) from breaking.  It's better to have a one-time breakage than cause a breakage upon the introduction of every new method.

Some options:

1. Do nothing.  When new methods are added to the existing services, they will break users.
2. Add the `Unimplemented` requirement now to force the breakage.  This allows us to add methods in the future without worrying about backward compatibility.
3. Do nothing, but once a new method is added, _also_ add the requirement to embed `Unimplemented`.
4. Create new canonical generated code packages for everything existing, with the services only, and deprecate the existing generated services.

(1) would allow breaking backward compatibility repeatedly.
(2) would be the cleanest, but forces a breakage when none is required.
(3) is like a lazy version of (2), and avoids breaking anything until required.
(4) has the potential for causing confusion (forever!), and makes things harder for users, but avoids making any breaking change, ever.

Any other options?  Thoughts?

**Comment by belak** [comment]
This seems directly related to #3669 and is a result of the previously mentioned change.

My personal preference is that if someone is implementing a service, it should be their choice on if they want to embed the Unimplemented implementation. It could be considered best practice to do so when relying on external protos for service definitions. However, maybe that's different for some of the canonical packages.

**Comment by dfawley** [comment]
Let's go with (3) for now, and only make changes when there is a need to.  For internal packages and examples / testing, we should regenerate our `pb.go`s when the new generator is available.
