### ISSUE TITLE
Latency is higher at low QPS

### ISSUE THREAD

**Issue by fpmchu** [grpc/grpc-go#3676]
We're designing a service where we're using gRPC as a nice API for inter-process communication.  Basically, we're running a server as a sidecar inside a k8s pod, and the client talks to it using gRPC via localhost.  The main motivation is a clean separation of services (especially across language boundary) while retaining low latency.

This works pretty well.  But we notice that at lower QPS (<=100), we observe **higher** latency than at higher QPS (150-300).  The latency ranges are 10-12ms for <= 100 QPS, and 6-8ms for 150-300 QPS.  This seems pretty consistent in all our testing, and we're suspecting that Go's gRPC implementation has some sort of buffering that is adding a minimum latency of say 2-3ms at lower QPS.  Do you think this can be possible?  I've searched a few forums and I do see some discussions of buffering as an internal implementation in Go's gRPC, but I can't confirm.

If so, is there a way to disable this?  I tried setting `WriteBufferSize(0)` but that didn't seem to help.

Thanks.

**Comment by dfawley** [comment]
This is unexpected.  We do a small amount of buffering internally in order to reduce syscalls (which should consequently lower latency unless it's pathologically unlucky).  Even this I would expect to impact it only by tens or hundreds of microseconds, not 4-6ms.  It may be worthwhile generating flame graphs with high & low QPS to see where the extra time is being spent.

**Comment by fpmchu** [comment]
What are flame graphs?  How do I generate them?

**Comment by fpmchu** [comment]
I apologise. It turns out it was my server that was misbehaving.

**Comment by dfawley** [comment]
To answer your question, this page has some information about flame graphs, which show you where time is being spent in your application: https://brendanjryan.com/2018/02/28/profiling-go-applications.html
