### ISSUE TITLE
user-agent not available in stats.HandleConn()

### ISSUE THREAD

**Issue by 7AC** [grpc/grpc-go#3678]
`user-agent` is a `DialOption` per https://godoc.org/google.golang.org/grpc#WithUserAgent

Yet the metadata that contains it is not available in `stats.HandleConn()` but only in `stats.HandleRPC()`. Wouldn't it make sense to have it available in `HandleConn()` instead since it's a connection option and it doesn't change per RPC? Having to parse it out of RPC calls puts the burden on things like handling concurrency on the user, when really that particular field is not expected to change.

**Comment by dfawley** [comment]
@7AC, `user-agent` is a DialOption in gRPC, so it impacts all RPCs on all connections.  However, it is transmitted between the client and server per-RPC.  There is no metadata transmitted per-connection.

I don't understand your comment about "handling concurrency".

**Comment by 7AC** [comment]
I mean if we have to wait for the first `HandleRPC()` call to get a hold of the `user-agent`, we'd have to store it somewhere and serialize access to that storage among all possible `HandleRPC()` that are coming in since they go in parallel. That affects the server's performance for no good reason, since the information is already available when the connection is initialized before any RPC and cannot change.

**Comment by dfawley** [comment]
`user-agent` could potentially be overridden per-call if we wanted to allow it.  We don't have an option for that today, but we may in the future.  Such a feature could be useful for, e.g., a proxy, forwarding calls on the behalf of multiple clients.

Is there a reason your connection-level stats handler needs to know the user agent?  There may be a false assumption being made.

**Comment by 7AC** [comment]
That makes sense then. In our case we use it to identify the type of client among a handful (3 at the moment) and draw stats such as number of active connections per type of client. Also the type of client never changes for us, the version could but that would result in a new connection.
