### ISSUE TITLE
two server binaries

### ISSUE THREAD

**Issue by awalterschulze** [grpc/grpc-go#368]
It happens intermittently, very rarely, but its becoming quite irritating.

We get the following error:

```
go install google.golang.org/grpc/interop/server: build output "/home/slave/workspace/branch_long_test/next/bin/server" already exists and is not an object file
```

When we run

```
go install -v ./...
```

On our repo.

I think its because there are two server binaries in grpc-go
interop/server and benchmark/server

Maybe I am wrong?

**Comment by iamqizhao** [comment]
not sure. I guess the later install should overwrite the former one. Running
go install ./... at google.golang.org/grpc seems working fine. You probably should decompose the installation to find the root cause.

**Comment by awalterschulze** [comment]
I am thinking it happens during a parallel build.  Where the two are trying to be built at the same time.

**Comment by iamqizhao** [comment]
Feel free to rename one of them and send me a pull request if this still bothers u.

**Comment by dfawley** [comment]
Closing stale PR.
