### ISSUE TITLE
Quickstart docs generate conflicting client

### ISSUE THREAD

**Issue by wlynch** [grpc/grpc-go#3688]
# What version of gRPC are you using?

grpc-go: 6f5ecbe (master)
protoc-gen-go: v1.3
protoc: libprotoc 3.11.2

### What version of Go are you using (`go version`)?

go version go1.14.2 darwin/amd64

### What operating system (Linux, Windows, …) and version?

macOS 10.15.4

### What did you do?
If possible, provide a recipe for reproducing the error.

Tried following the quickstart guide at https://grpc.io/docs/languages/go/quickstart/.

### What did you expect to see?

Be able to follow the instructions to modify and build the Go gRPC server.

### What did you see instead?

The [protoc regeneration](https://grpc.io/docs/languages/go/quickstart/#regenerate-grpc-code) does not generate client code cleanly. It attempts to put [all client code in helloworld.pb.go](https://gist.github.com/wlynch/3176cfa693caa49aca77475e1b2d7a25) and leaves helloworld_grpc.pb.go unmodified, instead of splitting client code between the files. This causes conflicts since client structs are declared multiple times.

I suspect that https://github.com/grpc/grpc-go/pull/3646 caused this change, and we just need to update the documentation to reflect the usage of protoc-gen-go-grpc.

@yuege01 also reported that he was having difficulty using the protoc command with `libprotoc 3.6.1` not generating the `UnimplementedGreeterServer` (https://gist.github.com/wlynch/3176cfa693caa49aca77475e1b2d7a25), even though the guide specifies `Protocol buffer compiler, protoc, version 3`. Updating protoc fixed this issue.

**Comment by dfawley** [comment]
@chalin could you take a look at this?  We started using the codegen in our repo to generate the `pb.go` files, but it isn't ready for other people to use yet.  Maybe the quickstart guide should recommend deleting the existing `.pb.go`s?  Or should we keep generating this `.pb.go` file the old way?

**Comment by chalin** [comment]
Thanks for the issue @wlynch.

This was bound to happen. Quick start instructions for other languages (like C++ and Java) have the user clone a specific release. I suggest we do the same in the [Get the example code](https://grpc.io/docs/languages/go/quickstart/#get-the-example-code) instructions of the **Go quickstart**.

I think that we should require [v1.30.0-dev.1](https://github.com/grpc/grpc-go/releases/tag/v1.30.0-dev.1). WDYT @dfawley?

**Comment by chalin** [comment]
I opened https://github.com/grpc/grpc.io/issues/296 to track the Go quick start changes.

**Comment by chalin** [comment]
Here's the PR: https://github.com/grpc/grpc.io/pull/297. As I mention in the opening comment of the PR: I've run through the quick start (using v1.30.0-dev.1) and it works fine.

**Comment by dfawley** [comment]
That approach makes sense to me.  I was worried about the go tooling for modules getting in the way and pulling 1.30.0 (not the -dev version) when it's released, but since you're using `git` directly then that should work.  Thanks!

**Comment by chalin** [comment]
@dfawley - The main issue (as I see it), has been addressed via https://github.com/grpc/grpc.io/pull/297. Do you want to close this issue?

I've create the following issue to ensure that the Quick Start is updated once the next release of grpc-go is made available: https://github.com/grpc/grpc.io/issues/298

**Comment by menghanl** [comment]
Thanks @chalin
Closing this issue now.
