### ISSUE TITLE
Way of import google.golang.org/grpc/internal/grpctest

### ISSUE THREAD

**Issue by takat0-h0rikosh1** [grpc/grpc-go#3690]
I'm trying mocking gRPC client when do test. But I can't find "google.golang.org/grpc/internal/grpctest" package.

I tried the command in follow.

`go get -u google.golang.org/grpc/internal/grpctest` 

But It was not able to use in testing source code.

**Comment by dfawley** [comment]
This is an internal testing package intended for grpc use only; you should not be using it.  If there is something in there you find useful, feel free to make a copy of it and maintain it for yourself.
