### ISSUE TITLE
pick_first

### ISSUE THREAD

**Issue by kgtom** [grpc/grpc-go#3692]
Hi: 
 When i see in  grpc/pick_first.go (grpc version  "1.24.0").
   “PickFirstBalancerName is the name of the pick_first balancer.”
but i not find  first_pick what the selection rules? By subConn alphabetical order or when the service started?

Looking forward to your reply. Thank you

**Comment by menghanl** [comment]
The addresses are tried in the order that name resolver (e.g. DNS) returns them.
