### ISSUE TITLE
Any news on client interceptors becoming stable?

### ISSUE THREAD

**Issue by phil-f** [grpc/grpc-go#3693]
https://github.com/grpc/grpc-go/blob/04ea82009cdb9ecdefc6289f4c93ec919a10b3b6/interceptor.go#L31

https://github.com/grpc/grpc-go/blob/04ea82009cdb9ecdefc6289f4c93ec919a10b3b6/interceptor.go#L39

As the title says, these extremely useful pieces of functionality have been labelled as experimental for a while.

Would be nice to hear if there's any news on them becoming stable as using outgoing middleware in prod would be great :). If there's another way to implement outgoing middleware that isn't experimental then pointers to that would be much appreciated.

**Comment by dfawley** [comment]
My guess is, at this point, enough people are using it that it would be extremely difficult to change, even though it's technically allowed by our versioning policy.  Also, some interceptors are experimental and some are not, probably due to an oversight before GA.  We can go ahead and call these "stable".

**Comment by phil-f** [comment]
ah that's great news! thanks for the info :)

**Comment by dfawley** [comment]
Let's leave this open to cover making them stable.

**Comment by hypnoglow** [comment]
Hi!

What needs to be done to close this issue? Is it just removing comments about experimental API or anything else?

Thanks

**Comment by dfawley** [comment]
In addition to removing the "experimental" comments, we should improve their documentation comments a bit -- e.g. what the parameters/return values are, when they are called, etc.

**Comment by hypnoglow** [comment]
@dfawley I opened #3948 

I added additional commentary on parameters and return values etc. as far as I understand them. Please let me know if we need to rephrase/add/remove something in those comments.

**Comment by hypnoglow** [comment]
@dfawley As the PR with updates to documentation is merged, I think this issue can be closed.

**Comment by dfawley** [comment]
That's right, thanks for following up.
