### ISSUE TITLE
*.grpc.pb.go in example folder is confusing & unnecessary

### ISSUE THREAD

**Issue by 2kindsofcs** [grpc/grpc-go#3703]
### What version of gRPC are you using?
v1.30.0

### What version of Go are you using (`go version`)?
 go1.13.7 darwin/amd64

### What operating system (Linux, Windows, …) and version?
Mac OS, Catalina

### What did you do?
Tried to go through [gRPC quick start](https://grpc.io/docs/languages/go/quickstart/) in Go.
I edited .proto, server/main.go, client/main.go as the tutorial says and then tried to run the server.

### What did you expect to see?
hello-world server working fine without errors.

### What did you see instead?
 
```
 > go run greeter_server/main.go

helloworld/helloworld_grpc.pb.go:19:6: GreeterClient redeclared in this block
        previous declaration at helloworld/helloworld.pb.go:262:6
helloworld/helloworld_grpc.pb.go:24:6: greeterClient redeclared in this block
        previous declaration at helloworld/helloworld.pb.go:268:6
helloworld/helloworld_grpc.pb.go:28:6: NewGreeterClient redeclared in this block
        previous declaration at helloworld/helloworld.pb.go:272:52
helloworld/helloworld_grpc.pb.go:32:25: (*greeterClient).SayHello redeclared in this block
        previous declaration at helloworld/helloworld.pb.go:276:6
helloworld/helloworld_grpc.pb.go:44:6: GreeterServer redeclared in this block
        previous declaration at helloworld/helloworld.pb.go:295:6
helloworld/helloworld_grpc.pb.go:50:6: UnimplementedGreeterServer redeclared in this block
        previous declaration at helloworld/helloworld.pb.go:302:6
helloworld/helloworld_grpc.pb.go:53:36: (*UnimplementedGreeterServer).SayHello redeclared in this block
        previous declaration at helloworld/helloworld.pb.go:305:6
helloworld/helloworld_grpc.pb.go:57:6: RegisterGreeterServer redeclared in this block
        previous declaration at helloworld/helloworld.pb.go:312:48
helloworld/helloworld_grpc.pb.go:61:6: _Greeter_SayHello_Handler redeclared in this block
        previous declaration at helloworld/helloworld.pb.go:316:154
helloworld/helloworld_grpc.pb.go:79:5: _Greeter_serviceDesc redeclared in this block
        previous declaration at helloworld/helloworld.pb.go:352:5
helloworld/helloworld_grpc.pb.go:53:36: too many errors
```

as the quick start tutorial says, after recompile only helloworld.pb.go got regenerated. 
After modifying server side code and client side code, it should work out without errors.
But when you try to run the server, even though you did just as same as the tutorial says, 
server won't run due to `helloworld.grpc.pb.go`. if you remove this file, it just works fine. 
as server side code and client side code is in helloworld.pb.go, we don't need helloworld.grpc.pb.go anymore.

**Comment by menghanl** [comment]
This seems like a dup of https://github.com/grpc/grpc-go/issues/3688

There was a change in the codegen, and the quickstart has been updated. Please try again. Thanks!
