### ISSUE TITLE
Make parseDialTarget (or something like it) publicly available

### ISSUE THREAD

**Issue by edwarnicke** [grpc/grpc-go#3705]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?

I would like to be able to use the same url structure consistently both for grpc.DialContext and for net.Listen(net, address) (for setting up to run a GRPC server).

### Proposed Solution

[parseDialTarget](https://github.com/grpc/grpc-go/blob/9aa97f9/rpc_util.go#L821) is being used internally to convert 'target' to (net,addr).  It would be very handy to be able to use that externally for this purpose. 

### Alternatives Considered

Copying [parseDialTarget](https://github.com/grpc/grpc-go/blob/9aa97f9/rpc_util.go#L821) with careful attribution and consideration of license compatibility.  This has the disadvantage of being able to fall out of sync with grpc in general.

**Comment by menghanl** [comment]
`parseDialTarget` isn't a general purpose function. It doesn't handle all network right, and the only guarantee is that it recognizes `unix`. I don't think we should export it as a grpc function for users. Guessing network type based on scheme is also very specific to the use case, where gRPC makes no guarantee.

Also, the target format only makes sense on the client side (e.g. `scheme` has no meaning to a server).
