### ISSUE TITLE
protoc-gen-go-grpc should show version when invoked standalone

### ISSUE THREAD

**Issue by meling** [grpc/grpc-go#3706]
It would be convenient to be able to determine the version of `protoc-gen-go-grpc` is installed by invoking it standalone, as is possible with [`protoc-gen-go --version`](https://github.com/protocolbuffers/protobuf-go/blob/master/cmd/protoc-gen-go/main.go#L25), which currently gives: 
```text
protoc-gen-go v1.24.0
```

**Comment by xin-au** [comment]
Hi @meling , @menghanl ,
I would like to help on this issue. I created a small PR. When you have time, could you take a look? Thank you so much!

**Comment by dfawley** [comment]
Fixed by #3921
