### ISSUE TITLE
Does protoc take go modules into consideration ?

### ISSUE THREAD

**Issue by Clement-Jean** [grpc/grpc-go#3708]
I built a module with the `go mod init` and called it "my-site.com/api"

As my current repository has a directory called "protos", I basically wanted my generated code to end up in it. So I used the go_package option like this: `option go_package = "my-site.com/api/protos/helloworld";` (see Code version 1).

This ended up in creating a my-site.com directory in the root. I then change the option go_package option like this: `option go_package = "protos/helloworld";` to be able to generate in the protos directory. And it works (see Code version 2).

However, now if I want to import this helloworld into my routes.proto (I do not want to have a big proto file, I want to separate my models), it says it can't find the package protos/helloworld. That's totally normal because in the generated code the import looks like `import protos/helloworld` and not like `my-site.com/api/protos/helloworld`.

Is there any way to include the module name in the import of the generated code and still being able to generate the code in a specific subdirectory of root ?

### routes.proto
```
syntax = "proto3";

option go_package = "my-site.com/api/protos/routes";

package routes;

import "helloworld.proto";

service Routes {
        rpc SayHello(helloworld.HelloRequest) returns (helloworld.HelloReply) {}
}
```

### helloworld.proto
```
syntax = "proto3";

option go_package = "my-site.com/api/protos/helloworld";

package helloworld;

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
}

```
### routes.proto
```
syntax = "proto3";

option go_package = "protos/routes";

package routes;

import "helloworld.proto";

service Routes {
        rpc SayHello(helloworld.HelloRequest) returns (helloworld.HelloReply) {}
}
```

### helloworld.proto
```
syntax = "proto3";

option go_package = "protos/helloworld";

package helloworld;

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
}

```

## Command line

```
protoc -I ./protos ./protos/routes.proto --go_out=plugins=grpc:.
protoc -I ./protos ./protos/helloworld.proto --go_out=plugins=grpc:.
```

**Comment by menghanl** [comment]
Can you try `source_relative`?

```
# With go_package
option go_package = "my-site.com/api/protos/helloworld";
```

Command should look like
```
protoc -I ./protos ./protos/routes.proto --go_out=plugins=grpc:paths=source_relative:.
```

Another way is to generate `.pb.go` files in `/tmp` and copy to your directory.

**Comment by Clement-Jean** [comment]
I will go with the `--go_opt=paths=source_relative`, thanks !
