### ISSUE TITLE
Validating request in StreamServerInterceptor

### ISSUE THREAD

**Issue by parmen789** [grpc/grpc-go#3716]
Hello, I am currently trying to figure elegant interceptor solution, which would validate incoming requests (pure serverside), both for streaming and non-streaming RPC calls, as for non-streaming, in Unary Interceptors I have access to request - it comes as a parameter while creating unary interceptor, but in Stream Interceptors, I was not able to find a way how to obtain the request. 

Is there a way how can I obtain the request information in server Interceptor for a streaming call? I would basically need to check purely the request, but unary interceptor cannot be used for streaming calls. (It can but it wont work).

**Comment by menghanl** [comment]
You need to wrap the stream, and intercept `RecvMsg()`. See the [example](https://github.com/grpc/grpc-go/blob/c95dc4da23cb6f3d4c8bedd53d4af72b46f55616/examples/features/interceptor/server/main.go#L126)
