### ISSUE TITLE
Feature request: put generateFile from protoc-gen-go-grpc into its own package

### ISSUE THREAD

**Issue by ydnar** [grpc/grpc-go#3717]
This is a feature request to move the existing `generateFile` method in `protoc-gen-go-gprc` to a package that can be imported by another program, so the generated code can be adapted. Additional background:

As the `protogen` package allows for `protoc` plugins to adapt the Protobuf AST prior to Go code generation, I think splitting out the [`generateFile`](https://github.com/grpc/grpc-go/blob/HEAD/cmd/protoc-gen-go-grpc/grpc.go#L39) function into its own package would allow adaptation of the AST prior to serialization without forking the entire repo or command.

e.g. something like a `cmd/protoc-gen-go-grpc/grpcgen` package, with a single entry point (`GenerateFile`) with the same method signature as the existing `generateFile`.

A caller would have two opportunities to adapt the output:

1. Modify the input in the `protogen.Plugin`
2. Modify the output in the response.

----

> Interesting.  This is a very high level function.  Since it's so high level, it should be possible to accomplish these things as a separate step before/after running the generator as a binary.  But on the other hand, it would be possible to support this kind of API with minimal effort.  Would you mind filing an issue for this?

_Originally posted by @dfawley in https://github.com/grpc/grpc-go/pull/3453#issuecomment-650304536_

**Comment by dfawley** [comment]
FWIW there is still some interesting discussion happening in #3453 that is relevant.  To avoid forking the discussion, let's just let it play out there and use this bug to track the request and follow-up here with the result of the other thread once it wraps up.

**Comment by dfawley** [comment]
Per the reasoning in https://github.com/grpc/grpc-go/pull/3453#issuecomment-650391303, I don't think we will be implementing this:

> mutation of data structures returned by protogen is not a supported use case and subject to breakage in the future as it will likely violate consistency invariants.
