### ISSUE TITLE
Allow Omitempty to be toggleable in protobuf

### ISSUE THREAD

**Issue by mornindew** [grpc/grpc-go#3722]
There are some cases where I marshal my generated protobuf struct directly over to JSON.  It can get a bit confusing when zero/default values are not marshalled into JSON.  Especially when they were explicitly set as such (e.g. false in the database or 0 is a valid value).  If the consumer of the API has properly set their default values then this isn't an issue but that is a major assumption.

Alternatively, I can marshal the protobuf struct to a different struct (with identical values) and not use the "omitempty" tag before marshaling over to json but this will impact performance.

In addition, I have seen solutions/scripts that will update any generated protobuf files to remove the "omitempty" tag.  This is a bit of a hack and an anti-pattern to modify autogenerated files.

I understand the desire to not send over default values and ensure that they aren't necessarily marshaled over but there are cases where I would be willing to sacrifice some performance implications for simplicity in the code. 

### Proposed Solution

I propose that we add a mechanism to our proto files to not allow the omitempty tag to get set.  Without the toggle then omitempty will be set but allowing it to be overwritten seems more flexible for the development community.

Please let me know if I am under thinking the solution and the ramifications of it.

**Comment by menghanl** [comment]
For protobuf issues, please use https://github.com/golang/protobuf/issues instead.

**Comment by mornindew** [comment]
@menghanl - Do you consider this an issue?  I think that this is working as built or designed and would be a feature request.  Apologies if I am missing something.

**Comment by menghanl** [comment]
I'm not familiar enough with Omitempty to comment. Please file another issue in the protobuf repo.

**Comment by xxjwxc** [comment]
I used command line substitution ：
sed -i '' 's/,omitempty//g' *.pb.go
