### ISSUE TITLE
Add removal of `naming` package to release notes of v1.30.0

### ISSUE THREAD

**Issue by philippgille** [grpc/grpc-go#3724]
Hi, just a quick one: I was checking the release notes of the latest releases for breaking changes but didn't find any, but updating the package then lead to a compile error. The reason was the removal of the `naming` package in `v1.30.0`, which isn't mentioned in the release notes. Does it make sense to add that?

**Comment by menghanl** [comment]
Thanks for reporting. This change is part of `balancer: move Balancer and Picker to V2; delete legacy API`, but apparently it's missing information.

Release notes updated: https://github.com/grpc/grpc-go/releases/tag/v1.30.0
