### ISSUE TITLE
How to disable compression on the server per-RPC?

### ISSUE THREAD

**Issue by peterebden** [grpc/grpc-go#3725]
The [generic gRPC documentation](https://github.com/grpc/grpc/blob/master/doc/compression.md) suggests this is possible ("A gRPC peer MAY choose to respond using a different compression method to that of the request..."). I have a case where it might be interesting to experiment with this, i.e. the server may be able to determine that the payload is already compressed and attempting to gzip it again won't achieve anything.

However I can't work out how to do this using grpc-go. It seems like I could register a custom Compressor but it isn't allowed to change its name, which I think it would have to do for a client to understand how it should handle the response. Am I barking up the wrong tree here?

**Comment by dfawley** [comment]
You could do something like this with #3694.  But that would require it for all responses from the server, not conditionally per-response.  Even though the spec allows for servers to do this, there is currently no way to do so in gRPC-Go (I'm not sure about the other gRPC languages, but it would not surprise me if they don't support it, either).

**Comment by peterebden** [comment]
OK thanks; for now I have managed to handle this sufficiently on the client side, but will keep an eye on that issue too. Thanks!
