### ISSUE TITLE
Breaking change in non-major release

### ISSUE THREAD

**Issue by gbbr** [grpc/grpc-go#3726]
You have removed the `naming` package. A deprecated package (or method, function, type for that matter) means that it will be removed in _the next major version_, which means `v2.0.0`.

This in turn breaks `google.golang.org/api` which uses it. Now, it is no longer possible to use the latest `grpc` release along side this package.

Would you consider adding it back in a patch release? With this change you have technically broken semver.

**Comment by dfawley** [comment]
Please see our published [versioning policy](https://github.com/grpc/grpc-go/blob/master/Documentation/versioning.md).  The package was clearly marked as experimental at GA, so it could be removed according to the policy.
