### ISSUE TITLE
Memory leak in GRPC streaming connections

### ISSUE THREAD

**Issue by xdire** [grpc/grpc-go#3728]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
1.29.1

### What version of Go are you using (`go version`)?
1.13

### What operating system (Linux, Windows, …) and version?
OSX/Debian docker

### What did you do?
Added 3 long-lasting streaming always-connected clients chatting between each other every 0.5 second

### What did you expect to see?
Normal execution

### What did you see instead?
Out of memory errors

### Heap pprof
<img width="908" alt="Screen Shot 2020-07-06 at 10 30 20 AM" src="https://user-images.githubusercontent.com/11039780/86622293-85cae680-bf74-11ea-8e4c-8741ffec0291.png">

I was trying to find some answers reading the issues, but it was mostly stalled questions.

The issue is very tricky to understand. After killing all streaming connections (from the side of the client) the memory doesn't go away on the server.

Still trying to debug it in hopes that it's my fault somewhere. Any help appreciated.

**Comment by william-lg** [comment]
Met the same problem and don't know why the memory used by newHTTPTransport/newFramer is increasing.
There is no connection leaks.

**Comment by xdire** [comment]
> Met the same problem and don't know why the memory used by newHTTPTransport/newFramer is increasing.
> There are no connection leaks.

Yeah it looks really weird, basically what I see is when the client reconnects the stream it starts to bloat underlying buffers in GRPC subsystem.

I was trying to zero the buffers:
```
server := grpc.NewServer(keepalive, creds, streamInterceptors, unaryInterceptors, grpc.ReadBufferSize(0), grpc.WriteBufferSize(0))
``` 
Still ate the whole bulk of memory.

**Comment by xdire** [comment]
Heap pprof with single connected stream client and `grpc.ReadBufferSize(0), grpc.WriteBufferSize(0)`, the memory growth was significantly slower, however kept pushing the limits.
<img width="1069" alt="Screen Shot 2020-07-06 at 10 14 10 PM" src="https://user-images.githubusercontent.com/11039780/86716534-21d90a00-bfd6-11ea-8a71-5420ceea4300.png">

**Comment by dfawley** [comment]
Please reduce your code to the smallest possible form that exhibits the problem and post it here so we can take a look at what you're doing.  Thanks!

**Comment by william-lg** [comment]
> Please reduce your code to the smallest possible form that exhibits the problem and post it here so we can take a look at what you're doing. Thanks!

@dfawley Hi, I doubt that there're some clients that don't close the grpc connection, cause the memeory leak, for the newHttp2Server and newFramer occupy the most of the memory. And I'll test it later. Btw, is there a way to protect server? I see I can set the idle keepalive timeout of server(don't know if this can reduce the memory leak). And Is there a way for the server to check memory leak?
And if this don't work, I'll paste the reduced code here for your help.
Many thanks.

**Comment by dfawley** [comment]
Yes, setting keepalive settings (max idleness and max connection age) would help protect the server, and is recommended.  If that's not enough, you could also limit the maximum number of connections your server allows at one time (by using a [`LimitListener`](https://godoc.org/golang.org/x/net/netutil#LimitListener)).

**Comment by xdire** [comment]
> Please reduce your code to the smallest possible form that exhibits the problem and post it here so we can take a look at what you're doing. Thanks!

I will try to find the time to simulate the behavior, but cannot guarantee this.

Probably one thing that could be useful is the ability to peek in or report the number of messages currently residing in those buffers, to see if it could possibly be the absence of read-capacity with the presence of high data inflow.

It's really hard to tell what happens with those when you place it under the chatty load.

**Comment by michelaquino** [comment]
Hi all,

I'm have the same problem. Any update about it?
How you fix it?

Thank you

**Comment by clarkmcc** [comment]
I'm seeing the same issues here, my situation is a little bit complicated so I'll show and explain my results but I can't provide too much more information besides just confirming this issue.

I've attached a pprof dump illustrating that the majority of the memory usage is coming from the `newFramer` per @william-lg 's message earlier.

![image](https://user-images.githubusercontent.com/6639685/88683131-b8b65500-d0b0-11ea-8154-4190e2a0ef44.png)



  |  
-- | --
**Top Chart** | Connections to gRPC Server
Blue Line | Unary Connections
Orange Line | Stream Connections
**Second Chart** | gRPC Server Resource Usage
Yellow Line | Istio Proxy
Light Orange Line | Memory Usage
Dark Orange Line | CPU Usage
**Third Chart** | Average gRPC Resource Per Connection
Light Orange Line | Memory Usage
Dark Orange Line | CPU Usage
**Fourth Chart** | Attempts to Start Streaming
Light Orange Line | Avg reqps to start gRPC stream

![image](https://user-images.githubusercontent.com/6639685/88683714-56118900-d0b1-11ea-97c6-0b9771c10fde.png)

Based on my observations, you can see over the course of the last nine days, around 200 attempts to reconnect happen every day, on top of (not shown) **108,796** requests to start streams, this number would include those 200 clients that are connecting every day as well as all the retries over the last nine days.

The number of total clients is not increasing while the resource was steadily increasing until I restarted the gRPC server at the end of 7/27.

**Comment by dfawley** [comment]
I can't really determine anything from the numbers presented in this issue.  First, it seems there's a terminology mismatch.  When we talk about "connections", we mean TCP connections.  Not RPCs/streams on a connection.  This means there is no such thing as a "unary connection" or a "stream connection", only "connections", "unary RPCs", and "streaming RPCs".  The read/write buffers in the pprof flame graph above are created _per-TCP connection_, although there are also additional buffers allocated per-stream.

The default per-connection write buffer size is 32KB -- but note that we multiply this buffer by two for performance reasons -- and the default per-connection read buffer size is also 32KB.  Have these been [overridden](https://godoc.org/google.golang.org/grpc#WriteBufferSize) ([read option](https://godoc.org/google.golang.org/grpc#ReadBufferSize)) in your server @clarkmcc?

We would expect 96KB per connection with the defaults in place.  411MB total * 2/3 (approx. percentage used by `NewFramer`) = 274MB. / 96KB = ~2800 connections, which is much higher than the mention of "200 clients" but also not quite as far off from the first graph showing ~1600 total connections (though terminology here may be mistaken).

Note also that "number of clients" != "number of connections".  A single client could be connected many times depending upon how a `ClientConn` is being used by the application (i.e. is the client creating a new one for each RPC?).  It's also possible to configure the server to send GOAWAYs but never ultimately kill the connection (via the [keepalive options](https://godoc.org/google.golang.org/grpc/keepalive#ServerParameters) if `MaxConnectionAge` is set without a relatively short & finite `MaxConnectionAgeGrace` also being set).

**Comment by clarkmcc** [comment]
@dfawley Yes, the connection used in these graphs refers to a connection from one of our agents deployed somewhere in the world, not TCP connections. We have some clients that check in every few minutes using unary requests as an alternative to maintaining open streams (some of our customers feel uncomfortable with the idea of a constant connection so we provide a polling alternative).

No we have not overridden the option you provided.

Our clients are _supposed_ to only have a single open connection at any given time. Whenever we attempt to connect/reconnect, we close the previous connection if it exists. Theoretically, if the clients were not closing RPC connections, would we see the behavior in those charts (resource usage increasing while the number of total clients is relatively constant).

**Comment by michelaquino** [comment]
Hi there, I found some issues that can help you to understand what is happening.

The Go 1.12 introduces a new release memory strategy that use `MADV_FREE` instruction instead of `MADV_DONTNEED`:
[On Linux, the runtime now uses MADV_FREE to release unused memory. This is more efficient but may result in higher reported RSS. The kernel will reclaim the unused data when it is needed. To revert to the Go 1.11 behavior (MADV_DONTNEED), set the environment variable GODEBUG=madvdontneed=1](https://golang.org/doc/go1.12)

To understand what it means, you can read the `madvise` documentation [here](https://www.man7.org/linux/man-pages/man2/madvise.2.html).

The problem is that according to [this](https://github.com/golang/go/blob/master/src/runtime/mem_linux.go#L112) comment on `runtime.go` this new strategy was added on version 4.5 of Linux kernel:
`MADV_FREE was added in Linux 4.5. Fall back to MADV_DONTNEED if it is not supported.`

So, the cause of memory increase can be that you are using a Linux kernel minor than 4.5 and Go is using the memory release strategy that uses `MADV_FREE` instruction.

**Comment by dfawley** [comment]
> Whenever we attempt to connect/reconnect, we close the previous connection if it exists.

When/under what conditions do you manually reconnect?  How do you close the previous connection?  In general a `ClientConn` is meant to live as long as you want to be able to make RPCs, and doesn't need to be restarted or refreshed.

> Theoretically, if the clients were not closing RPC connections, would we see the behavior in those charts (resource usage increasing while the number of total clients is relatively constant)?

Yes, that's quite possible.  For your servers' benefit, it would be a good idea to set `MaxConnectionAge` and a finite `MaxConnectionAgeGrace` in [keepalive](https://godoc.org/google.golang.org/grpc/keepalive) so clients will be forced to reconnect periodically (this would be transparent to the client, except after `MaxConnectionAgeGrace`, all active streams will be forcibly terminated).

**Comment by william-lg** [comment]
> Yes, setting keepalive settings (max idleness and max connection age) would help protect the server, and is recommended. If that's not enough, you could also limit the maximum number of connections your server allows at one time (by using a [`LimitListener`](https://godoc.org/golang.org/x/net/netutil#LimitListener)).

So when idle keepalive timeout of server triggers, will grpc server release the resource that keeped by the idle connection? 
I see your reply " It's also possible to configure the server to send GOAWAYs but never ultimately kill the connection (via the keepalive options if MaxConnectionAge is set without a relatively short & finite MaxConnectionAgeGrace also being set)."
I'm confused about this, you mean grpc-server just send goaway but not close the tcp connection and not release the buffers allocated by the grpc connection?

**Comment by dfawley** [comment]
> @dfawley So when idle keepalive timeout of server triggers, will grpc server release the resource that keeped by the idle connection?

Once the connection is closed it will free the resources.  (Technically Go is garbage collected, so it will no longer reference the resources and Go will free it according to its schedule.)

> I'm confused about this, you mean grpc-server just send goaway but not close the tcp connection and not release the buffers allocated by the grpc connection?

Correct.  The active connection will remain open until all active streams on it stop.  No new streams will be started on that connection in the meantime, however -- the client will see the GOAWAY and establish a new connection for new RPCs.  This can be forced after some timeout by setting `MaxConnectionAgeGrace`.

**Comment by clarkmcc** [comment]
@dfawley I ran a test with one of our servers and one of our agents on my local machine. I set the `MaxConnectionAge` to `30 * time.Second` and the `MaxConnectionAgeGrace` to `30 * time.Second` and then opened a stream between the agent and the server. What should I expect to see from my stream errors on the agent? I expected a `transport is closing` or something but I didn't see anything after 30 seconds, and nothing was forcibly closed after the full minute. Am I misunderstanding how this works? Should I see stream errors when a client receives a `GOAWAY` or is forcibly closed?

**Comment by dfawley** [comment]
@clarkmcc With your settings you should see nothing after 30 seconds; after the grace period is over (1 minute), any open streams should start returning errors from their `RecvMsg` methods.

**Comment by william-lg** [comment]
@dfawley  I provide a case that may cause the memory leak of GRPC:
1. The application buffer that grpc server allocate is released by golang-GC, as you mentioned above.
2. So if the application buffer leaks, there must be many connections open and close, sometimes frequently.
3. There're many streams running on a tcp connection. And when creating a stream, grpc server will create a cancel context, binding with the stream, which can be found at struct Stream at internal/transport.go.
4. The context will be delivered to the method handlers. We can get this at processUnaryRPC and the server interceptors(there is a context parameter)
5. The context in golang is bidirectional referenced. The children context reference to the parent and the parent reference to the children. But when the parent invokes cancel function, it only release the reference to the children.
6. The problem is on the children contexts. If the contexts leak, then the application buffers leak. For our case, we create a struct A, and set the context as a member, and the context comes from the children context. just like this:
 type A struct {
  ...
  Ctx Contex
 }
 A.Ctx = context.WithValue(ctxFromStream, ...)
When A and A.Ctx leaks, golang won't free the application buffer. As time goes by, the application buffers grows, but we cannot get the true leaked source using pprof.

@xdire The above is what I discovered. Hope it is useful and may you solve the memory leak.
