### ISSUE TITLE
best practices to share proto to other gRPC services

### ISSUE THREAD

**Issue by kabaluyot** [grpc/grpc-go#3735]
What are the recommended ways to share proto files to microservices (gRPC). A stackoverflow question is raised here [how-do-i-share-protocol-buffer-proto-files-between-multiple-repositories](https://stackoverflow.com/questions/38862101/how-do-i-share-protocol-buffer-proto-files-between-multiple-repositories). If say you proceed with git submodules,

1. should I create a repo for each proto and add them as git submodule in each project, 
2. or a single repo for proto and add them as git submodule in each project (this may include other proto that are not needed)

I'm planning my internal communication (microservices) for this use case using polyrepo. Thanks

**Comment by dfawley** [comment]
This would be up to you; I believe both would work.  What we've done for gRPC is create one repo to hold all our `.proto` files: https://github.com/grpc/grpc-proto
