### ISSUE TITLE
Using a specific version of protoc-gen-go-grpc

### ISSUE THREAD

**Issue by TheCount** [grpc/grpc-go#3758]
I'm not sure whether this is a bug in this repo, in `go mod`, or a misunderstanding on my part, but I have difficulty getting a specific version of the `protoc-gen-go-grpc` plugin in terms of git tags:

This works fine:
````
$ GO111MODULE=on go get -v google.golang.org/grpc@v1.30.0
…
````

This doesn't:

````
$ GO111MODULE=on go get -v google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.30.0
go get google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.30.0: module google.golang.org/grpc@v1.30.0 found, but does not contain package google.golang.org/grpc/cmd/protoc-gen-go-grpc
````

However, it works without the tag:

````
$ GO111MODULE=on go get -v google.golang.org/grpc/cmd/protoc-gen-go-grpc
go: google.golang.org/grpc/cmd/protoc-gen-go-grpc upgrade => v0.0.0-20200723182653-9106c3fff523
````

Indeed, the plugin module [only has pseudo-versions](https://pkg.go.dev/google.golang.org/grpc/cmd/protoc-gen-go-grpc?tab=versions), while the root module [has the git tags as expected](https://pkg.go.dev/google.golang.org/grpc?tab=versions).

I thought the presence of a git tag would imply that I can use that as a version identifier for all the Go modules in the same repo, but perhaps that's a misconception of mine?

How would one best use a specific version in a project? Preferably a better way than just use the pseudo-version and document somewhere, "oh, that's actually v1.30.0"?

**Comment by menghanl** [comment]
protoc-gen-go-grpc isn't released yet. It doesn't have a version.

(Dup of #3727)
