### ISSUE TITLE
Permission Denied errors not being reported to client for bi-directional streams

### ISSUE THREAD

**Issue by the4thamigo-uk** [grpc/grpc-go#3759]
Hi, we have a grpc service that implements token-based authorization using a stream interceptor. I have been using this for a client streaming rpc call, and I correctly see 'permission denied' errors when the client has an incorrect token. However, I have recently converted this rpc function to use bi-directional streaming, but the client no longer receives the 'permission denied' error. 

I can see the server-side stream interceptor rejecting the call on the rpc method, and the method definitely does not get called, however, the client-side function returns a `nil` error.

Is this kind of error supported for bidirectional streaming? Or am I doing something wrong?

P.S. I am using : 

google.golang.org/grpc v1.30.0

**Comment by menghanl** [comment]
Does the server side code (interceptor in this case) return the 'permission denied' error to grpc? If so, the error should be sent to the client.

And can you get a minimum reproduction.

**Comment by the4thamigo-uk** [comment]
Ok, Ive modifed the route_guide example https://github.com/the4thamigo-uk/grpc-interceptor-errors-demo/tree/master/route_guide.

Ive added interceptors in the server here https://github.com/the4thamigo-uk/grpc-interceptor-errors-demo/blob/master/route_guide/server/server.go#L241-L242

Intuition tells me I ought to see errors in these places :
https://github.com/the4thamigo-uk/grpc-interceptor-errors-demo/blob/master/route_guide/client/client.go#L91
https://github.com/the4thamigo-uk/grpc-interceptor-errors-demo/blob/master/route_guide/client/client.go#L96
https://github.com/the4thamigo-uk/grpc-interceptor-errors-demo/blob/master/route_guide/client/client.go#L120
https://github.com/the4thamigo-uk/grpc-interceptor-errors-demo/blob/master/route_guide/client/client.go#L142

But I only see permission denied errors here :
https://github.com/the4thamigo-uk/grpc-interceptor-errors-demo/blob/master/route_guide/client/client.go#L100
https://github.com/the4thamigo-uk/grpc-interceptor-errors-demo/blob/master/route_guide/client/client.go#L127

**Comment by menghanl** [comment]
This is working as intended. The server error is returned from recv().
Send doesn't return the status errors. https://godoc.org/google.golang.org/grpc#ClientStream
