### ISSUE TITLE
1.31.0 broke CircleCI build

### ISSUE THREAD

**Issue by amaraliou** [grpc/grpc-go#3782]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?

1.31.0

### What version of Go are you using (`go version`)?

1.10.3 (Version that comes with the `machine` executor in CircleCI, see [here](https://raw.githubusercontent.com/circleci/image-builder/picard-vm-image/provision.sh))

### What operating system (Linux, Windows, …) and version?

Ubuntu 16.04 (again, comes with the `machine` executor in CircleCI)

### What did you do?

Run this step as part of the CI workflow

```
- run:
    name: compile internal tools
    command: |
      export GOPATH=/home/circleci/go
      cd ~/go/src/github.com/dummy-profile/dummy-repo
      go get -v ./...
      go build ./tools/cmd/...; go install ./tools/cmd/...
```

### What did you expect to see?

Things to build to completion

### What did you see instead?

```
...
google.golang.org/grpc/serviceconfig
google.golang.org/grpc/internal
google.golang.org/grpc/internal/credentials
# google.golang.org/grpc/internal/credentials
../../../google.golang.org/grpc/internal/credentials/spiffe.go:34:70: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)
../../../google.golang.org/grpc/internal/credentials/spiffe.go:38:47: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)
../../../google.golang.org/grpc/internal/credentials/spiffe.go:56:35: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)
google.golang.org/grpc/metadata
google.golang.org/grpc/internal/grpcrand
google.golang.org/grpc/codes
...
```

This issue is similar to #3775 with the difference that, instead of `tls` errors appearing, it's `spiffe`. I can already see that some stuff had been reverted for that, but `spiffe` seems to be still unchanged (see [here](https://github.com/grpc/grpc-go/pull/3767))

**Comment by dfawley** [comment]
Go 1.10 is no longer supported by the latest releases of grpc-go.  We only support the last three major releases of Go per our [README](https://github.com/grpc/grpc-go#prerequisites).  If you'd like to continue using an older version of Go, you will need to vendor grpc-go to an older version.
