### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by sath33sh** [grpc/grpc-go#379]
Getting the following error. Whoever is committing code should at least compile the code before pushing it upstream. :-)

---
go/src/google.golang.org/grpc/rpc_util.go:195: syntax error: unexpected default, expecting semicolon or newline or }
go/src/google.golang.org/grpc/rpc_util.go:207: syntax error: unexpected )

**Comment by kujenga** [comment]
I'm seeing the same issue. The following line doesn't have a closing curly brace...

https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L189

**Comment by iamqizhao** [comment]
reverted that change.
