### ISSUE TITLE
EDF scheduler should degenerate to simple round robin if all endpoints have same weight

### ISSUE THREAD

**Issue by yishuT** [grpc/grpc-go#3793]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
tip of master

### What version of Go are you using (`go version`)?
go version go1.13 darwin/amd64

### What operating system (Linux, Windows, …) and version?
macOS Catalina

### What did you do?
```
func (s) TestEDFOnSameWeight(t *testing.T) {
	wrr := NewEDF()
	wrr.Add("1", 1)
	wrr.Add("2", 1)
	expected := []string{"1", "2", "1", "2", "1", "2", "1", "2", "1", "2"}
	for i := 0; i < 10; i++ {
		item := wrr.Next().(string)
		if item != expected[i] {
			t.Errorf("wrr Next=%s, want=%s", item, expected[i])
		}
	}
}
```

### What did you expect to see?
test passed.
I expected edf returned 1212121212, but got 1122112211 instead. 

I think edf scheduler should degenerate to simple round robin if all endpoints have same weight. Does it make sense? I can submit a pull request it if you agree.

### What did you see instead?
test failed

**Comment by easwars** [comment]
@menghanl 
Do you think EDF should degenerate to simple round robin here? When looked at over a larger time frame, the backends seem to receive the same number of RPCs, but not in the same order.

**Comment by easwars** [comment]
@echo80313 : Please do send us a PR if you like.

**Comment by menghanl** [comment]
Also note that EDS implementation is not complete (it doesn't support updating weights), and is not used anywhere in the code.

**Comment by echo80313** [comment]
As a note that, I started a discussion in grpc-io https://groups.google.com/u/1/g/grpc-io/c/wf-IvQiBt80/m/HIZ_vpjFAwAJ for per endpoint weight. Is there any timeline about EDS implementation? I found this issue (https://github.com/grpc/grpc-go/issues/2827) btw. We (Dropbox) can help with the implementation if the issue still valid.
