### ISSUE TITLE
Is it possible to use another DNS resolved IP to communicate with gRPC server when first resolved IP is unavailable?

### ISSUE THREAD

**Issue by linqh1** [grpc/grpc-go#3795]
We have a gRPC server run on 2 host, and we have a domain name for these 2 host. This domain name could resolve to 2 available IP: IPA and IPB.

At some time, service run on IPA could be down due to some problem, in this situation I want do a retry and choose dial to IPB instead of unavailable IPA;

But I can not found any related configuration, it's seems that gRPC always uses first resolved IP?

Sample code:

```
func main() {
	dialConn, _ := grpc.Dial("domain-could-resolve-multip-ip:8080", grpc.WithInsecure())
	client := model.NewFeedbackResultClient(dialConn) 
	retryCnt := 0
	for {
		ctx, _ := context.WithTimeout(context.TODO(), time.Second*10)
		feedbackClient, err := client.Feedback(ctx,grpc.WaitForReady(true))
		if err != nil {
			retryCnt++
			log.Printf("start stream error:%v",err)
			if retryCnt > 5 {
				break
			}
			continue
		}
		log.Printf("start send message...")
		err = feedbackClient.Send(&model.PurgeResultPb{
			Status: "abc",
		})
		if err != nil {
			log.Printf("send error:%v",err)
		}
		pb, err := feedbackClient.CloseAndRecv()
		fmt.Printf("response:%#v, err:%v",pb,err)
		break
	}
}
```

**Comment by linqh1** [comment]
It seems duplicate with #3482

**Comment by easwars** [comment]
> But I can not found any related configuration, it's seems that gRPC always uses first resolved IP?
The default load balancing policy used by gRPC picks the first available server address.

One option would be to use an external load balancer which implements the `grpclb` load balancing protocol, and have the load balancer monitor the health and load on the backends and update the clients whenever the backend endpoints change. The external load balancer can also specify child policies which can either be `pick_first` or `round_robin`.

**Comment by easwars** [comment]
> It seems duplicate with #3482

Yes, please append `dns:///` to the dial target in `grpc.Dial` to get DNS functionality.
