### ISSUE TITLE
Update your SemVer Policy Please - Breaking changes in minor versions causing heartache

### ISSUE THREAD

**Issue by sethgrid** [grpc/grpc-go#3798]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
google.golang.org/grpc v1.21.1, attempted upgrade to v1.30.0

### What version of Go are you using (`go version`)?
go1.14

### What operating system (Linux, Windows, …) and version?
dev on mac, but builds and runs in linux

### What did you do?

We have an internal package that calls:
```
google.golang.org/grpc/dialoptions.go:108:func WithWaitForHandshake() DialOption {
```
I can see that the method is marked for deprecation after the 1.18 release. 
I also see that you call out in https://github.com/grpc/grpc-go/blob/master/Documentation/versioning.md that methods marked for deprecation can be removed in a minor version change.

You don't get to claim to "use semver" but ignore parts you don't like. From semver: https://semver.org/#how-should-i-handle-deprecating-functionality - it specifically calls out bumping minor versions for deprecation. 

This broke our MTA (mail transfer agent) build process at Twilio SendGrid. 

We have an internal package that calls that removed function. I added a new redis client ("github.com/go-redis/redis/v8"). This has a dependency chain that eventually causes a need to bump from 1.21.1 to 1.30.0 of grpc. I tried to pin grpc to 1.21.1, but that caused the following issue:
```
vendor/golang.org/x/sys/unix/syscall_unix.go:16:2: cannot find package "." in:
/go/src/github.com/sendgrid/postman/vendor/golang.org/x/sys/internal/unsafeheader
```
Something in the dependency chain is now borked. I cannot include a redis client because of some chain of events that is broken by misuse of semver. 

My understanding is that if this project property used semver instead of some strange "semver when we feel like it," then go mod would have handled things fine.

I apologize if this sounds salty - but it is because I am. I was working an incident over night and this issue made my life harder. 

### What did you expect to see?

I expected to not have breaking changes on a minor version upgrade

### What did you see instead?

I saw breaking changes on a minor version upgrade

**Comment by dfawley** [comment]
This function was clearly documented as experimental upon its introduction:

**Comment by dfawley** [comment]
To fix your actual issue, just remove the callsite.  `WithWaitForHandshake` is now the default behavior.

**Comment by sethgrid** [comment]
Thanks for the response. The team responsible for our internal system that
uses that call has a ticket to remove our call to the deprecated feature.
Again, thanks for your response. I do want to dig on it however.

From https://semver.org/spec/v2.0.0-rc.1.html#spec-item-9:
Major version X (X.y.z | X > 0) MUST be incremented if any backwards
incompatible changes are introduced to the public API. It MAY include minor
and patch level changes. Patch and minor version MUST be reset to 0 when
major version is incremented.

We don't get to pick and choose what counts as a breaking change. Being
experimental or marked for deprecation is unrelated. If it is in the API,
it is there. If we remove it, it breaks things. Why not bump a major
version for that as semver requires? The only reasons to not bump major
feel political.

Also, looking at the code in question, its docblock does not say
experimental, just that it is deprecated (I def could be looking in the
wrong place I guess):
```
103 // WithWaitForHandshake blocks until the initial settings frame is
received from
104 // the server before assigning RPCs to the connection.
105 //
106 // Deprecated: this is the default behavior, and this option will be
removed
107 // after the 1.18 release.
108 func WithWaitForHandshake() DialOption {
109     return newFuncDialOption(func(o *dialOptions) {
110         o.reqHandshake = envconfig.RequireHandshakeOn
111     })
```

I really appreciate all the work everyone has done to create the grpc lib
and that it is available. By ignoring semver (which what Go uses aside from
the prefix 'v'), you can unexpectedly break packages not directly related
to grpc.

Going with the "it is our policy" is a user hostile response.

**Comment by MaerF0x0** [comment]
Just for kicks https://www.hyrumslaw.com/ 

```
With a sufficient number of users of an API,
  it does not matter what you promise in the contract:
  all observable behaviors of your system
  will be depended on by somebody.
```
