### ISSUE TITLE
Why we have a lot of examples in grpc-dotnet but just one example  in grpc-go

### ISSUE THREAD

**Issue by thisismz** [grpc/grpc-go#3806]
Hello
Unfortunately, there are **many simple and advanced examples** on the _https://github.com/grpc/grpc-dotnet/tree/master/examples_ , but there is **only one example** (Hello World) on the _https://github.com/grpc/grpc-go/tree/master/examples_. What is the reason for this?
Please implement the examples on the dotnet on the grpc-go as well
thanks a lot

**Comment by menghanl** [comment]
Basic gRPC usages are covered by examples hello-world and route-guide.
Many features are shown by examples in the features directory.
Please file an issue if you need a specific example that doesn't exist. Thanks.
