### ISSUE TITLE
API stability guarantees

### ISSUE THREAD

**Issue by tamalsaha** [grpc/grpc-go#3808]
I see that grpc-go projects breaking API changes with minor releases. This is a major problem for anyone who wants to use grpc-go for public facing api. The problem usually happens because as a user I am trying to use 2 different libraries which needs 2 different version of grpc-go.

What kind of API stability guarantees does grpc-go provide? Is there any documentation on this?

**Comment by dfawley** [comment]
https://github.com/grpc/grpc-go/blob/master/Documentation/versioning.md has our official versioning policy.  Related: https://github.com/golang/go/issues/34409
