### ISSUE TITLE
internal/wrr: edf scheduler to support UpdateWeight and Remove

### ISSUE THREAD

**Issue by yishuT** [grpc/grpc-go#3810]
### Use case(s) - what problem will this feature solve?

On ClusterLoadAssignment update, xDS balancer does not need to rebuild the edf scheduler on any weight change. also on ConnectivityState change, balancer can remove the subconn from edf.

### Proposed Solution
Add two functions, `UpdateWeight` and `Remove` to edf scheduler

**Comment by easwars** [comment]
@menghanl :
Is the `weightedroundrobin` balancer even used?

I see the EDS balancer sets the address attribute for the weight here
https://github.com/grpc/grpc-go/blob/master/xds/internal/balancer/edsbalancer/eds_impl.go#L324-L335

But there is no callers for [GetAddrInfo](https://github.com/grpc/grpc-go/blob/master/balancer/weightedroundrobin/weightedroundrobin.go#L57).

Am I missing something?
