### ISSUE TITLE
Server reports INTERNAL_ERROR on malformed requests

### ISSUE THREAD

**Issue by lych77** [grpc/grpc-go#3819]
### What version of gRPC are you using?

google.golang.org/grpc v1.27.0

### What version of Go are you using (`go version`)?

go 1.15

### What operating system (Linux, Windows, …) and version?

Windows 10 x64
Ubuntu 18.04.1 x64

### What did you do?

Any simplest gRPC server, like:

```protobuf
message Empty {}

service Demo {
  rpc foo(Empty) returns (Empty) {}
}
```

```go
type server struct{}

func (svr *server) Foo(ctx context.Context, req *demo.Empty) (*demo.Empty, error) {
	return &demo.Empty{}, nil
}

func main() {
	svr := grpc.NewServer()
	demo.RegisterDemoServer(svr, &server{})

	lis, err := net.Listen("tcp", "[::]:9000")
	if err != nil {
		panic(err)
	}
	svr.Serve(lis)
}
```

Sending to it some malformed request manually, e.g. one arbitarily composed with `golang.org/x/net/http2` that lacks the `content-type` header or has an improper value of it.

### What did you expect to see?

According to the HTTP/2 spec, I expect to get a PROTOCOL_ERROR response from the server.

### What did you see instead?

I always get an INTERNAL_ERROR response.

---

While debugging an application I think it's important to be able to quickly distinguish whether a problem is server-side or client-side, and a similar response for all cases will be confusing. The example above is just a simplified demonstration and the original circumstance I've run into involves Envoy proxy sidecars and the gRPC-JSON transcoder, which took me time to pinpoint the problem. It would be nice if this behavior could be improved.

**Comment by GarrettGutierrez1** [comment]
Hi lych77. Could you please attach some client code that reproduces this error, so we can be sure we are debugging the exact error? Also, can you specify what part of the HTTP/2 spec this behavior violates?

**Comment by lych77** [comment]
Client code:

```go
client := http.Client{
	Transport: &http2.Transport{
		AllowHTTP: true,
		DialTLS: func(network, addr string, cfg *tls.Config) (net.Conn, error) {
			return net.Dial(network, addr)
		},
	},
}

res, err := client.Post("http://localhost:9000/absent", "application/json", bytes.NewReader([]byte{}))
fmt.Printf("Res: %#v\nErr: %#v\n", res, err)
```

The request path is obviously invalid but it's okay as what expected is just the error response, and such mistakes do happen in practice when mapping gRPC to a REST interface using option `google.api.http`. The real key is the content type `application/json`, that's also invalid for a gRPC server. The output of this example will be:

```
Res: (*http.Response)(nil)
Err: &url.Error{Op:"Post", URL:"http://localhost:9000/absent", Err:http2.StreamError{StreamID:0x3, Code:0x2, Cause:error(nil)}}
```

Where the Code 0x2 is `INTERNAL_ERROR`.

Then, let's just correct the content type to `application/grpc` and leave all other unchanged, the output will become:

```
Res: &http.Response{Status:"200 OK", StatusCode:200, Proto:"HTTP/2.0", ProtoMajor:2, ProtoMinor:0, Header:http.Header{"Content-Type":[]string{"application/grpc"}, "Grpc-Message":[]string{"malformed method name: \"/absent\""}, "Grpc-Status":[]string{"8"}}, Body:ioutil.nopCloser{Reader:(*bytes.Reader)(0xc000070ea0)}, ContentLength:0, TransferEncoding:[]string(nil), Close:false, Uncompressed:false, Trailer:http.Header(nil), Request:(*http.Request)(0xc00013c000), TLS:(*tls.ConnectionState)(nil)}
Err: <nil>
```

It's acceptable that invalid content types are treated as severer errors and the stream has to be reset, but an error code that can inform the client developer of the problem domain will be appreciated.

And about the [HTTP/2 spec](https://tools.ietf.org/html/rfc7540):

```
7.  Error Codes

   Error codes are 32-bit fields that are used in RST_STREAM and GOAWAY
   frames to convey the reasons for the stream or connection error.

   Error codes share a common code space.  Some error codes apply only
   to either streams or the entire connection and have no defined
   semantics in the other context.

   The following error codes are defined:

   NO_ERROR (0x0):  The associated condition is not a result of an
      error.  For example, a GOAWAY might include this code to indicate
      graceful shutdown of a connection.

   PROTOCOL_ERROR (0x1):  The endpoint detected an unspecific protocol
      error.  This error is for use when a more specific error code is
      not available.

   INTERNAL_ERROR (0x2):  The endpoint encountered an unexpected
      internal error.
```

A malformed request is actually an error neither 'internal' (it's the client's fault) nor 'unexpected' (it's not a bug of the server needing to be fixed).

And more specifically:

```
8.1.2.6.  Malformed Requests and Responses

   A malformed request or response is one that is an otherwise valid
   sequence of HTTP/2 frames but is invalid due to the presence of
   extraneous frames, prohibited header fields, the absence of mandatory
   header fields, or the inclusion of uppercase header field names.

   A request or response that includes a payload body can include a
   content-length header field.  A request or response is also malformed
   if the value of a content-length header field does not equal the sum
   of the DATA frame payload lengths that form the body.  A response
   that is defined to have no payload, as described in [RFC7230],
   Section 3.3.2, can have a non-zero content-length header field, even
   though no content is included in DATA frames.

   Intermediaries that process HTTP requests or responses (i.e., any
   intermediary not acting as a tunnel) MUST NOT forward a malformed
   request or response.  Malformed requests or responses that are
   detected MUST be treated as a stream error (Section 5.4.2) of type
   PROTOCOL_ERROR.

   For malformed requests, a server MAY send an HTTP response prior to
   closing or resetting the stream.  Clients MUST NOT accept a malformed
   response.  Note that these requirements are intended to protect
   against several types of common attacks against HTTP; they are
   deliberately strict because being permissive can expose
   implementations to these vulnerabilities.
```
