### ISSUE TITLE
GRPC_GO_RETRY with write log for each retry request

### ISSUE THREAD

**Issue by mirecl** [grpc/grpc-go#3824]
Hi.
I`m use native retry function in gRPC (https://github.com/abserari/grpc-go/tree/retry-example/examples/features/retry).
How to write log in file or stdout for each retry request on gRPC client side?
I want use for example logrus.

**Comment by GarrettGutierrez1** [comment]
Hi mirecl. The intention of retry it for it to be transparent to the client, in other words it happens behind the scenes. Can you clarify what it is exactly you are trying to do, I.E. for what purpose you are logging retries? There may be a better way to achieve it. You can refer to the RFC for retry here: https://github.com/grpc/proposal/blob/master/A6-client-retries.md
