### ISSUE TITLE
gRPC bi-directional streaming: Close stream from server side.

### ISSUE THREAD

**Issue by CodingSinger** [grpc/grpc-go#3825]
How can I close a stream on the server side as follows？

```
for {
		select {
		case <-ctx.Done():
			return ctx.Err()
                case <- exitChan:
                       
		default:
		}

		// block until request comes
		req, err := realStream.Recv()

	}
```
I want exit the for loop when get the msg from `exitChan`,But the `Recv` method is blocking,  I cannot enter the select unless EOF or a new message is received.

**Comment by GarrettGutierrez1** [comment]
Hi CodingSinger. You could try putting the `Recv()` on separate goroutine. That way you can close the stream by returning in the stream handler without it blocking on `Recv()`.
