### ISSUE TITLE
use grpc register multi service or once service multi methods, which one I should do?

### ISSUE THREAD

**Issue by apptut** [grpc/grpc-go#3829]
I‘m a new one for grpc. register multi service in server  or one service with multi methods, which is better? Could you give me some advise ?

**Comment by GarrettGutierrez1** [comment]
Hi apptut. Services are just collections of methods, so whatever you think makes the most sense for your particular use case is probably correct. There aren't significant differences between the two schemes beyond what you feel is more correct organizationally.
