### ISSUE TITLE
How to install protoc-gen-go-grpc with required version?

### ISSUE THREAD

**Issue by wtask** [grpc/grpc-go#3843]
Due to grpc-go team makes incompatible changes to the gRPC service generator could you please follow semver-tags for main package? If my module used google.golang.org/grpc v1.31.0 I will be very appreciated to know how I can install appropriate `proto-gen-go-grpc` version which not break my code?

Today doesn't work:
```
> go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.31.0
go get google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.31.0: module google.golang.org/grpc@v1.31.0 found, but does not contain package google.golang.org/grpc/cmd/protoc-gen-go-grpc
```
I really hate the situation, when I cannot determine which version of this generator will be installed and what will happen after!

**Comment by dfawley** [comment]
`protoc-gen-go-grpc` is in its own, new module and has never been released.  It is still v0.  Backward-incompatible changes are to be expected.

If you want the old service registration pattern, you need to use the legacy codegen tool which is stable but deprecated (i.e. it will not receive any updates).  E.g.:

```
go install github.com/golang/protobuf/protoc-gen-go
protoc --go_out=plugins=grpc:.
```

**Comment by wtask** [comment]
@dfawley  `go install` brings latest plugin version from master in my case.
Only `get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc@cee815d` helps.
