### ISSUE TITLE
BiDi stream error not propagated to client?

### ISSUE THREAD

**Issue by ivanjaros** [grpc/grpc-go#3848]
I have a bidirectional stream where the client streams id into the server and the server then starts streaming data to the client. Client then periodically streams back id and counter of some local stuff.

The thing is thas when the first message is sent from the client to the server, with the id, and the id does not exist on the server, the server returns(not streams but ends the handler with error return value) not found grpc error. The thing is that the client does not receive this error and proceeds to execute the further logic. 

So the clieint does:
```
if err := conn.Send(&api.Foo{Id: 123}); err != nil {
  return nil, err // grpc error
}
```

the server does:
```
if req, err := s.Recv(); err != nil {
	return nil
} else {
	id = req.GetId()
}
if idDoesNotExist {
	return status.Error(codes.NotFound, id)
}
```

but the client code above will not receive that not found error. So I am wondering if that conn.Send() error is not the returned error but connection error. And since connection was made, the error is nil. And so I am asking if this is correct and that if I have to check for closed connection by doing dummy send?

**Comment by menghanl** [comment]
`send` doesn't see the errors. You will need to call `recv` to get the RPC status, which will be the not found error in your case.

And note that you can call `send` and `recv` in two goroutines.
