### ISSUE TITLE
How to measure compressor?

### ISSUE THREAD

**Issue by ivanjaros** [grpc/grpc-go#3857]
I would like to compare messages with various de/compressing algorithms but I am not sure where I can get the message size from since I need to get the message before it gets decompressed when icoming and compare afterwards, same when outgoing.

I'd like to avoid wirintg compressor wrapper and just hook into the flow, just like one can do with interceptors.

**Comment by dfawley** [comment]
If you want to check the stats live, you can compare the `Length` and `WireLength` in a stats handler:

https://godoc.org/google.golang.org/grpc/stats#OutPayload

(Please note the comment at the top of the package - the APIs in this package are still experimental and subject to change in the future, so don't rely on them for anything long-term if you are unwilling to accept breaking changes.)
