### ISSUE TITLE
Interop: Use --use_test_ca   instead of --tls_ca_file

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-go#386]
Go interop client uses --tls_ca_file cmdline options instead of --use_test_ca (which is required by spec).

https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md

**Comment by jtattermusch** [comment]
Friendly ping. We are trying to make all interop client and servers uniform in terms of cmdline args and addressing this asap would help.

**Comment by jtattermusch** [comment]
Ping?

**Comment by iamqizhao** [comment]
Thanks for taking care of it.
