### ISSUE TITLE
Define gRPC package version required by protoc-gen-go-grpc

### ISSUE THREAD

**Issue by chrisdoherty4** [grpc/grpc-go#3861]
_Disclaimer: I appreciate this is on-going work._

### What version of gRPC are you using?

v1.31.1

### What version of Go are you using (`go version`)?

v1.4

### What operating system (Linux, Windows, …) and version?

Linux

### What did you do?

Installed `protoc-gen-go-grpc` as per the documentation and generated the stubs. This installed the latest versions, `v0.0.0-20200902070140-9a132e444fbe`, but none of the versions listed in https://pkg.go.dev/google.golang.org/grpc/cmd/protoc-gen-go-grpc?tab=versions work anyway.

### What did you expect to see?

The stubs build successfully.

### What did you see instead?

When trying to build the stubs I get the `SupportPackageIsVersion7` error. 

### What did I find?

The go.mod file located in https://github.com/grpc/grpc-go/tree/master/cmd/protoc-gen-go-grpc doesn't specify a google.golang.org/grpc version that it's using. This seems to result in it using the latest tag which is 1.33.0-dev which includes the `SupportPackageIsVersion7` symbol. 

However, when trying to build the stubs as part of their own module it takes the latest release which is 1.31.1 and fails to build. (I can manually update the go.mod and force it to 1.33.0-dev, but that seems awfully wrong and finding out that the `protoc-gen-go-grpc` uses 1.33.0-dev was painful hence my proposal below).

I'm proposing that the go.mod explicitly states what grpc version it's using so we don't get unexpected errors to do with the support package version as we do now.

**Comment by dfawley** [comment]
`protoc-gen-go-grpc` doesn't depend upon `grpc` to build, so it is not listed in its `go.mod`.  And even if we did add this as a blank import and add it to `go.mod`, it wouldn't help you.  The code that `protoc-gen-go-grpc` generates is what needs `grpc` to build, so wherever you output your generated files is where the `go.mod` needs to reference the proper version of `grpc`.

Note also that the current version of `protoc-gen-go-grpc` is still v0 and is subject to change (and it likely will change a bit in the next week or two).  We're happy to have you test it and let us know your thoughts (in [this issue](https://github.com/grpc/grpc-go/issues/3669)). We expect to stabilize it and release v1 this month, at which point you can switch over to it for production code.  Until then, we recommend using the legacy `protoc-gen-go` from https://github.com/golang/protobuf.

**Comment by chrisdoherty4** [comment]
@dfawley Thanks for the comments.

I'm unclear as to how I control the grpc version used in the grpc stubs? If I install `protoc-gen-go-grpc` and generate stubs with it how do I know what grpc version was used so as to avoid this support package error?

**Comment by dfawley** [comment]
The `SupportPackageIsVersion` number (indirectly) lets you know the minimum version required.  The 1.32.0 release (note: this is the latest release, not 1.31.1) has `SupportPackageIsVersion7`, which the current (dev, v0) version of the codegen requires.

As a rule: as long as your `grpc` version is newer than your `protoc-gen-go-grpc` version, everything will work.  For backward compatibility reasons, we will never remove support for an older version of the generated code in a newer version of `grpc`.

There are only rare times where we update `protoc-gen-go-grpc` in a way that requires an update to `grpc`.  This did happen recently, but typically happens much less than once a year.

**Comment by chrisdoherty4** [comment]
Thank you!

**Comment by chrisdoherty4** [comment]
@dfawley 1.32.0 seems to be unreleased and is sat as 1.32.0-dev at the moment.

**Comment by dfawley** [comment]
My apologies; you are correct.  That release is scheduled for next week; I saw the "draft" release notes and mistakenly thought it was already live.  So, for now you will need the 1.33.0-dev version to work with the current `protoc-gen-go-grpc` version.

**Comment by chrisdoherty4** [comment]
No bother, thanks again.
