### ISSUE TITLE
Quickstart instructions do not work

### ISSUE THREAD

**Issue by mipnw** [grpc/grpc-go#3864]
The instructions on page https://grpc.io/docs/languages/go/quickstart/ do not seem to work

The following dockerfile installs all the prerequisites: 
- latest major release of golang in the form of official golang:1.15 docker image
- protoc version 3 (apk add protoc installs version 3.12.2)
- protoc-gen-go (skipped updating the PATH according to instructions since I verified $GOPATH/bin is already in the path in golang:1.15-apline)

```
$ cd grpc-go/examples/helloworld
$ cat <<EOF >Dockerfile
FROM golang:1.15-alpine

# Install protoc
RUN apk update && apk add protoc

# Install protoc-gen-go
ENV GO111MODULE=on
RUN go get github.com/golang/protobuf/protoc-gen-go

# Run go run greeter_server/main.go
COPY . .
ENTRYPOINT [ "go", "run", "greeter_server/main.go" ]
EOF

$ docker build -t grpc-go-helloworld .
$ docker run grpc-go-helloworld
```
yields
```
greeter_server/main.go:27:2: cannot find module providing package google.golang.org/grpc: working directory is not part of a module
greeter_server/main.go:28:2: cannot find module providing package google.golang.org/grpc/examples/helloworld/helloworld: working directory is not part of a module
```

I assume the quickstart needs one more prerequisite, some list of `go get` commands to get all the dependent go packages.

Or perhaps the helloworld project needs to have a go.mod file, and `go mod vendor` needs to be added to the quickstart instructions along with a `-mod=vendor` argument added to the `go run` command. Something like that. 

One can't assume everyone is familiar with how to get the dependencies given this is a quickstart tutorial. Also, Golang happens to be particularly hard for beginners when it comes to handling these sorts of dependency problems, we might as well have this tutorial run free of errors without any "hacking".

I tried to alter the tutorial instructions by first running
```
$ go mod init github.com/grpc/grpc-go/examples/helloworld
$ go mod vendor
```
then update the entrypoint to `ENTRYPOINT [ "go", "run", "-mod=vendor", "greeter_server/main.go" ]`
the server still fails to start because
```
vendor/google.golang.org/grpc/examples/helloworld/helloworld/helloworld_grpc.pb.go:14:11: undefined: grpc.SupportPackageIsVersion7
vendor/google.golang.org/grpc/examples/helloworld/helloworld/helloworld_grpc.pb.go:73:31: undefined: grpc.ServiceRegistrar
```
Then tried adding `RUN go get ./...` right before the `ENTRYPOINT`. Did not solve the problem, which I think proves my point about the difficulty for beginners to get started with Golang.

**Comment by dfawley** [comment]
Are you using the right version of grpc-go?  `git clone -b v1.31.0 https://github.com/grpc/grpc-go`

**Comment by mipnw** [comment]
I wasn't on v1.31.0, I was on the tip of master. After a `git checkout tags/v1.31.0 -b v1.31.0` I can confirm the issue still repros.

```
$ git log -n 1
commit bde0263672f027525e2950992a4c7db7af572b59 (HEAD -> v1.31.0, tag: v1.31.0)

$ docker build -t grpc-go-example .
$ docker run grpc-go-example

greeter_server/main.go:27:2: cannot find package "google.golang.org/grpc" in any of:
        /usr/local/go/src/google.golang.org/grpc (from $GOROOT)
        /go/src/google.golang.org/grpc (from $GOPATH)
greeter_server/main.go:28:2: cannot find package "google.golang.org/grpc/examples/helloworld/helloworld" in any of:
        /usr/local/go/src/google.golang.org/grpc/examples/helloworld/helloworld (from $GOROOT)
        /go/src/google.golang.org/grpc/examples/helloworld/helloworld (from $GOPATH)
```

**Comment by mipnw** [comment]
Found what was causing this issue, it was my very first step, `$ cd grpc-go/examples/helloworld`. The helloworld example is not a standalone example. 

The working directory for my repro to work needs to be `$ cd grpc-go/examples`, the Dockerfile adjusted with `ENTRYPOINT [ "go", "run", "helloworld/greeter_server/main.go" ]`.

This comes from the existence of a go.mod file up at the `grpc-go/examples` folder that is not present in the `grpc-go/examples/helloworld` project.

**Comment by dfawley** [comment]
`go` searches your working directory *and parents* for a `go.mod` file.  So I don't understand why it wouldn't work if you ran from the `helloworld` directory.  But, glad to hear you got things worked out.

**Comment by mipnw** [comment]
Indeed. My docker context was the examples/helloworld folder, this meant that any file higher up that source tree was not copied into the docker image. At runtime the docker container had no go.mod in the helloworld working directory.

**Comment by caoruidong** [comment]
I think https://github.com/grpc/grpc-go/blob/f005af03c24d49a4ec379884392cc4a557a0d047/examples/go.mod#L9 is the reason. It spcifies grpc 1.31.0 but https://github.com/grpc/grpc-go/blob/f005af03c24d49a4ec379884392cc4a557a0d047/examples/helloworld/helloworld/helloworld_grpc.pb.go#L14-L15 needs grpc later than 1.32.0
