### ISSUE TITLE
Having issues with handling failures and can't tell if retry is working as intended - would like assistance digesting information

### ISSUE THREAD

**Issue by JoeHFB** [grpc/grpc-go#3866]
Hi grpc-go folks,

Pretty new to go and grpc here.  I'm having some issues with the clients more gracefully handling servers shutting down as they get scaled up and down... and I'm getting no evidence whether retry is happening or not.  Would you guys be able to give me pointers as to how to debug this further?

_Note:_ This is unary calls

## Background
1. We work with containers that get autoscaled, so most of the grpc servers and clients are fair game to be spun up and spun down at any moment. 
2. In this particular case, there is a long running job that is the client, and it calls a couple other services that are the servers in this case.  

## Problems observed
As the server containers get spun up due to traffic and then scaled back down, the container termination results in the clients reporting the following three errors:
1. `code = Unavailable desc = transport is closing`
2. `"transport: Error while dialing dial tcp {some ip address}: connect: connection refused"`
3. `"rpc error: code = Unavailable desc = connection closed"`

I tried to add [retry](https://github.com/grpc/grpc-go/blob/master/examples/features/retry/README.md), but I couldn't see any evidence that retrying or not in the logs. (more info below)

## What we want it to do
1. Since the servers could be terminated at any moment, I want the client to be able to handle this more gracefully instead of dying right away on the first error.
2. For example, I'd want to have the retry mechanism built in.

### Questions about retry
1. Is the grpc-go's retry capable of handling this problem where server could be terminated during dial, during an active ongoing request, and/or during the sending the request stage?
2. If it is, how can I debug the retry?
3. What is supposed to be the value of the grpc server if I want to set it as retry for all endpoints on a given service? (I described how I set the value below)

## What we've tried with retry
1.  Enabled the `GRPC_GO_RETRY=on` env var
2.  Got the service name from the package name in proto file. 

Ex: Suppose we have `users` service.  Proto file for it says `package usersPB`, so I used that in step below.

3.  Added the following retry policy block to retry on unavailable and unknown for everything in `users` service
```
var retryPolicy = `{
            "methodConfig": [{
		"name": [{"service": "usersPB"}],
                "waitForReady": true,
                "retryPolicy": {
                    "MaxAttempts": 5,
                    "InitialBackoff": "1s",
                    "MaxBackoff": "5s",
                    "BackoffMultiplier": 1.0,
                    "RetryableStatusCodes": [ "UNAVAILABLE", "UNKNOWN" ]
                }
            }]
        }`
connection, err := grpc.Dial(targetServer, grpc.WithInsecure(), grpc.WithDefaultServiceConfig(retryPolicy))

...

users, err := client.GetUsers(ctx, request)
```

4. Only got the error log reported by the connection or the get users request :( 
Examples:
![image](https://user-images.githubusercontent.com/60893676/92623927-ecca8b80-f294-11ea-8930-13395965ef62.png)
![image](https://user-images.githubusercontent.com/60893676/92624091-197ea300-f295-11ea-82ac-f8bea0b8fa67.png)

5. Tried again after setting the following two env vars to turn on grpc logging
```
$ export GRPC_GO_LOG_VERBOSITY_LEVEL=99
$ export GRPC_GO_LOG_SEVERITY_LEVEL=info
```

6. This is where I am having trouble digesting the information - 
EDIT: To help clarify, here is an example. 
- I see this block repeated over and over - note that `transport is closing` line IS THERE
- BUT our application debug logs indicate _success_ (wat)
```
INFO: 2020/09/09 16:55:41 [core] parsed scheme: ""
INFO: 2020/09/09 16:55:41 [core] scheme "" not registered, fallback to default scheme
INFO: 2020/09/09 16:55:41 [core] ccResolverWrapper: sending update to cc: {[{users:8001  <nil> 0 <nil>}] <nil> <nil>}
INFO: 2020/09/09 16:55:41 [core] ClientConn switching balancer to "pick_first"
INFO: 2020/09/09 16:55:41 [core] Channel switches to new LB policy "pick_first"
INFO: 2020/09/09 16:55:41 [core] Subchannel Connectivity change to CONNECTING
INFO: 2020/09/09 16:55:41 [core] blockingPicker: the picked transport is not ready, loop back to repick
INFO: 2020/09/09 16:55:41 [core] Subchannel picks a new address "users:8001" to connect
INFO: 2020/09/09 16:55:41 [core] pickfirstBalancer: UpdateSubConnState: 0xc001b9bf70, {CONNECTING <nil>}
INFO: 2020/09/09 16:55:41 [core] Channel Connectivity change to CONNECTING
INFO: 2020/09/09 16:55:41 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
INFO: 2020/09/09 16:55:41 [core] Subchannel Connectivity change to READY
INFO: 2020/09/09 16:55:41 [core] pickfirstBalancer: UpdateSubConnState: 0xc001b9bf70, {READY <nil>}
INFO: 2020/09/09 16:55:41 [core] Channel Connectivity change to READY
-- application debug log indicating SUCCESS
INFO: 2020/09/09 16:55:41 [core] Channel Connectivity change to SHUTDOWN
INFO: 2020/09/09 16:55:41 [core] Subchannel Connectivity change to SHUTDOWN
```
- Eventually I'd find this block
```
INFO: 2020/09/09 16:55:41 [core] parsed scheme: ""
INFO: 2020/09/09 16:55:41 [core] scheme "" not registered, fallback to default scheme
INFO: 2020/09/09 16:55:41 [core] ccResolverWrapper: sending update to cc: {[{users:8001  <nil> 0 <nil>}] <nil> <nil>}
INFO: 2020/09/09 16:55:41 [core] ClientConn switching balancer to "pick_first"
INFO: 2020/09/09 16:55:41 [core] Channel switches to new LB policy "pick_first"
INFO: 2020/09/09 16:55:41 [core] Subchannel Connectivity change to CONNECTING
INFO: 2020/09/09 16:55:41 [core] blockingPicker: the picked transport is not ready, loop back to repick
INFO: 2020/09/09 16:55:41 [core] Subchannel picks a new address "users:8001" to connect
INFO: 2020/09/09 16:55:41 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
INFO: 2020/09/09 16:55:41 [core] pickfirstBalancer: UpdateSubConnState: 0xc001c88020, {CONNECTING <nil>}
INFO: 2020/09/09 16:55:41 [core] Channel Connectivity change to CONNECTING
-- application log indicating ERROR
WARNING: 2020/09/09 16:55:41 [core] grpc: addrConn.createTransport failed to connect to {users:8001 users:8001 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 172.20.190.186:8001: connect: connection refused". Reconnecting...
INFO: 2020/09/09 16:55:41 [core] Subchannel Connectivity change to TRANSIENT_FAILURE
INFO: 2020/09/09 16:55:41 [core] pickfirstBalancer: UpdateSubConnState: 0xc001c88020, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial tcp {IP ADDRESS}: connect: connection refused"}
INFO: 2020/09/09 16:55:41 [core] Channel Connectivity change to TRANSIENT_FAILURE
-- application error log indicating ERROR
INFO: 2020/09/09 16:55:41 [core] Channel Connectivity change to SHUTDOWN
INFO: 2020/09/09 16:55:41 [core] Subchannel Connectivity change to SHUTDOWN
```

- But then in a different attempt to reproduce an issue, I'd find that the error block mentions nothing about retrying
```
INFO: 2020/09/09 17:35:24 [core] parsed scheme: ""
INFO: 2020/09/09 17:35:24 [core] scheme "" not registered, fallback to default scheme
INFO: 2020/09/09 17:35:24 [core] ccResolverWrapper: sending update to cc: {[{users:8001  <nil> 0 <nil>}] <nil> <nil>}
INFO: 2020/09/09 17:35:24 [core] ClientConn switching balancer to "pick_first"
INFO: 2020/09/09 17:35:24 [core] Channel switches to new LB policy "pick_first"
INFO: 2020/09/09 17:35:24 [core] Subchannel Connectivity change to CONNECTING
INFO: 2020/09/09 17:35:24 [core] pickfirstBalancer: UpdateSubConnState: 0xc00542ccf0, {CONNECTING <nil>}
INFO: 2020/09/09 17:35:24 [core] Channel Connectivity change to CONNECTING
INFO: 2020/09/09 17:35:24 [core] Subchannel picks a new address "users:8001" to connect
INFO: 2020/09/09 17:35:24 [core] Subchannel Connectivity change to READY
INFO: 2020/09/09 17:35:24 [core] pickfirstBalancer: UpdateSubConnState: 0xc00542ccf0, {READY <nil>}
INFO: 2020/09/09 17:35:24 [core] Channel Connectivity change to READY
INFO: 2020/09/09 17:35:36 [core] Subchannel Connectivity change to CONNECTING
-- application error log
-- "grpc.error":"rpc error: code = Unavailable desc = transport is closing","grpc.kind":"client","grpc.stream":"false","grpc.success":false,"level":"error"...
INFO: 2020/09/09 17:35:36 [core] Channel Connectivity change to SHUTDOWN
INFO: 2020/09/09 17:35:36 [core] Subchannel Connectivity change to SHUTDOWN
INFO: 2020/09/09 17:35:36 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```

How can I debug this to get an understanding of _exactly what happened_ here?  Am I doing something wrong with the retry configuration?

For example, here are questions that pop up to my mind when I read that block:
1. What's going on with those blocks repeated over and over where grpc logs say transport is closing, but our application detects no error? Did retry attempts happen there?  Are the retries why this succeeded?
2. There is ONE warning log saying retry on the first error block.  I said retry max 5 times though in my config - did it retry 5 times?  What was the delay per retry attempt?  Or did this one have the warning log show up because this one failed enough times that even retry couldn't help?
3. Why did the second error block have no logs related to retries whereas the firsts one did?

**Comment by GarrettGutierrez1** [comment]
Hi @JoeHFB,

grpc-go's retry happens on a per-RPC basis, so it will not retry during dialing, or after an RPC has been initiated to the point that the client has received the headers from the server. You should be able to see retries indicated in the logs. The retry policy you set should work, except that the service name should be the name of the service as defined in the proto file, rather than the name of the go package (so I believe in the case you provided it should be `users`). The logs you are seeing over and over again appear to be from inside a call to `grpc.Dial`. Are you dialing multiple times? This should not be necessary, depending on what you are trying to do (the client is long running as you said, and so should only need to dial once). The logs are likely different because the connection closed error is happening at different times during the lifetime of your client. If you are mostly seeing your application report success, it could be because the connection is closing after the server finishes the RPC (and has sent all the necessary frames), but before the connection is gracefully closed. A lot of the log activity you are seeing is on different goroutines, so it should not concern you so much if you see a grpc log reporting an error before your application reports a successful RPC. Regardless, this is likely not due to retrying because retrying is not indicated in the logs. Let me know if you have any more questions or if what I commented here does not fully answer any of your existing questions.

**Comment by JoeHFB** [comment]
Hi @GarrettGutierrez1 -

Thanks for the response here.  I'll try to clarify - 

Unfortunately our services can be terminated at any moment because of the environment setup.  It could be kubernetes scaling pods up and then back down, or it could be CI/CD pipeline killing the existing servers and replacing them with new ones with new code.

While I was waiting I was able to test a few more scenarios - here is what I observed.

Scenario 1
- Client dials to server successfully
- Client sends a get a bunch of rows request to server
- Server starts processing, but kubernetes terminates this pod
- Client receives `transport is closing` error, but no logs of retries.  I do see logs like `INFO: 2020/09/10 21:40:05 [core] Subchannel Connectivity change to SHUTDOWN`

**Does this fall under the scenario you described as** `after an RPC has been initiated to the point that the client has received the headers from the server`**?**  And therefore does this mean grpc-go's retry feature does NOT cover this scenario?

Scenario 2 (see where I said `Eventually I'd find this block` in original description - this is same scenario)
- Client dials to server successfully
- Server is terminated by kubernetes **right before** the request is sent
- I see logs like `Err: connection error: desc = "transport: Error while dialing dial tcp 172.20.190.186:8001: connect: connection refused". Reconnecting...`, **but only once** - and it's not clear what happened on the retry.  I would've expected to see it happen 5 times if retries generate a log per retry.

**What should I expect to see here?**  Am I right to expect `MaxAttempts` number of `Reconnecting...` assuming it failed all those 5 times?

**Comment by dfawley** [comment]
Is this a streaming RPC or unary?

Did you correct the service name in your service config to be the full proto path + service name ("usersPB" -> "usersPB.users"; double-check that the case matches the package+service in the proto file)?

> I see logs like Err: connection error: desc = "transport: Error while dialing dial tcp 172.20.190.186:8001: connect: connection refused". Reconnecting...

Where is this log line coming from?  The gRPC logging (is there a file+line number?) or from your application's logs as a result of your RPC?

A gRPC `ClientConn` maintains a persistent connection with the server(s).  This is completely independent of the retry feature, which will retry RPC calls over these connections.  If a connection is lost, we will re-dial the address.  You should see the connectivity state in the logs changing from READY to CONNECTING and back to READY in these cases.

You might also be interested in round robin load balancing, allowing you to connect to multiple backends at once.  Right now you seem to be using pick_first, which means only one connection will be active at a time.  So when a connection is lost, you will need to wait for a new connection to become ready before your RPCs can continue.  With round robin you will have multiple connections and be able to immediately fail-over to a different one.

**Comment by JoeHFB** [comment]
Hi @dfawley - 

Thanks for the response here - here are my responses.

> Is this a streaming RPC or unary?

Unary - I also edited the description up top.

> Did you correct the...

Yes sir

> Where is this log line coming from? The gRPC logging (is there a file+line number?) or from your application's logs as a result of your RPC?

Here are a couple examples - these are def not our application logs.  They seem to be the grpc logs.
- `WARNING: 2020/09/10 21:45:56 [core] grpc: addrConn.createTransport failed to connect to {users:8001 users:8001 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 172.20.190.186:8001: connect: connection refused". Reconnecting...`
- `WARNING: 2020/09/10 21:45:58 [core] grpc: addrConn.createTransport failed to connect to {users:8001 users:8001 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 172.20.190.186:8001: connect: connection refused". Reconnecting...`

^ This particular example I dug out of our logs seemed to be the one time where the retry did seem to kick in (I had set the delay to be a second apart).

(will respond to rest in a second comment)

**Comment by JoeHFB** [comment]
> You might also be interested in round robin load balancing, allowing you to connect to multiple backends at once.

You're referring to this, correct?  https://github.com/grpc/proposal/blob/master/A6-client-retries.md#validation-of-hedgingpolicy

I had read about it, but unfortunately I don't think it will work for us - we have a couple write grpc calls that have this same problem that aren't safe for multiple identical concurrent calls unfortunately. 

The thing that makes it a bit tougher is that kubernetes autoscaling the `users` pods up and down can happen at any moment, and during scaling down _any of the users servers_ are complete fair game to be terminated without notice by kubernetes.

From what I could tell based on the evidence I was able to gather so far:
1. users pod(s) killed while client is waiting for users server to finish an active grpc request - this always seems to result in `transport is closing`.
2. users pod(s) killed right around the time client is trying to make a request to the users server - this seems to always result in `connection refused`
3. users pod(s) killed around the time of client connecting to the users server - this seems to result in `connection closed`.

Do you believe that grpc-go retry feature is suitable for all 3 scenarios? 

The response before - specifically this line - `grpc-go's retry happens on a per-RPC basis, so it will not retry during dialing` seemed to suggest scenario #3 would not be covered. 

In any of my tests so far I had been unable to see any evidence of retries in scenario #1 there.

The logs from my reply right before was from when I was testing scenario #2 - and this at least seems to work now :)

**Comment by dfawley** [comment]
> I had read about it, but unfortunately I don't think it will work for us - we have a couple write grpc calls that have this same problem that aren't safe for multiple identical concurrent calls unfortunately.

Hedging is a different thing (which is not implemented in gRPC-Go yet).  That sends concurrent requests on multiple connections.  Setting up a load balancing policy can allow your client to be connected to multiple servers at once, but without hedging, only one backend is used per RPC.  This means if one server goes down, you will instantly be able to use another backend.  If you're okay with the reconnection delays then what you're doing with "pick first" (the default load balancing policy) should work fine.

Glad to hear you worked things out.  Note that there is still a chance that an RPC could fail but not be retried if the connection dies between when the response headers are sent by the server and when the response body finishes sending.  This is typically a very small window, but it's worth mentioning that retry isn't always 100% guaranteed to activate.
