### ISSUE TITLE
binarylog: how to use?

### ISSUE THREAD

**Issue by Leboudin** [grpc/grpc-go#3878]
For now binarylog is internal package, everything we need (`Sink` interface, `SetDefaultSink` method) can not be accessed. So how to use it?

**Comment by menghanl** [comment]
It's controlled by env variables. See https://github.com/grpc/proposal/blob/master/A16-binary-logging.md#control-interface

**Comment by Leboudin** [comment]
You didn't get it. 

The config can only turn on this feature, but log to NOOP sink. Thers is no way to configure the Logger/Sink, or implementing new Sinks.

**Comment by menghanl** [comment]
Sorry. You are right.
This should be fixed by #3879. Please take a look.

**Comment by Leboudin** [comment]
Thx, lightspeed!
