### ISSUE TITLE
Empty service definition results in generated code not being compilable.

### ISSUE THREAD

**Issue by mostrows2** [grpc/grpc-go#3887]
https://github.com/grpc/grpc-go/blob/master/cmd/protoc-gen-go-grpc/grpc.go#L269

If the service definition is empty (i.e. no methods), then the generated reference to symbol "srvCopy" is never referenced and thus the generated code fails to compile.

**Comment by dfawley** [comment]
With the recent reversion to the codegen tool to the interface-based version, this is no longer an issue.  Thank you for the report.
