### ISSUE TITLE
How to create tls(ssl) with default public root certificate.

### ISSUE THREAD

**Issue by anykao** [grpc/grpc-go#3902]
I have nodejs sample like this
```node
const client = new hello_proto.Greeter(
  "myhost:443",
  grpc.credentials.createSsl()
);
```
How can I create the golang client?

**Comment by menghanl** [comment]
Set cert pool to `nil` in dial option [`NewClientTLSFromCert(nil, "")`](https://pkg.go.dev/google.golang.org/grpc/credentials#NewClientTLSFromCert).

See https://github.com/grpc/grpc-go/tree/master/examples/features/encryption#tls for how to use this dial option to create a ClientConn.
