### ISSUE TITLE
Disable log for a specific request

### ISSUE THREAD

**Issue by volezheng** [grpc/grpc-go#3903]
Is it possible to disable logging for a specific request (like based on its context)?

It seems default logger is global. I'm imagining to set logger for a specific request (or context) to a NoopLogger for a while (like calling a lib), and then reset it back to the default logger, so that I could disable logging of a lib I call. Is it doable somehow?

**Comment by menghanl** [comment]
There's currently no way to do that. https://pkg.go.dev/google.golang.org/grpc/grpclog#SetLoggerV2 can set logger, but it's not thread safe, so calling it while client is running can cause problems.

What logs are you trying to disable? Most logs today are for the client/connection. They are not bound to any RPCs.

**Comment by volezheng** [comment]
yeah, that’s what I found. And setlogger is a global behavior, while I only
want to disable logging for a while for each call.

My case is, I have a lib which would print some logs. I’d like to have it
print logs for some requests, not all. And I don’t want to affect other
parts of my code. So I want sth like:


If (badrequest(req)) {
  Setlogger(noopLogger);
}
CallLib();
If (badrequest(req)) {
  // set it back
}


Menghan Li <notifications@github.com>于2020年9月25日 周五上午1:48写道：

**Comment by menghanl** [comment]
The gRPC logs are not bound to a certain RPC. So even if you have a way to disable logging after seeing a back request, it's going to disable logs different from what you expect (e.g. it will disable connection retrying logs, but connections are shared by RPCs).

> I have a lib which would print some logs

You should control the logger used by this lib.
And one thing to note is that, if you are calling `grpclog.Info` from your lib, it's not expected. `grpclog.Info` should only be called by gRPC. If you want the logs to go to the same storage/format, you can set grpc and your lib to use the same logger.
