### ISSUE TITLE
Pass context to encoding.Codec Marshal() & Unmarshal()

### ISSUE THREAD

**Issue by paulhodson** [grpc/grpc-go#3906]
### Use case(s) - what problem will this feature solve?

I am working with a custom codec which partially encrypts, and then signs messages. For context, the codec repackages the message into another message along with signature information.

It would be handy if the caller (client) could send data (the signing key) via context which is visible to the codec. At the server end, the codec would send data (again, via context) to its handler.

### Proposed Solution

encoding.Codec signatures changed to:
```
Marshal(context.Context, v interface{}) ([]byte, error)
Unmarshal(context.Context, data []byte, v interface{}) error
```

### Alternatives Considered

- Registering a callback with the codec, which would return the signing key
- Singleton-ish lookup method

These alternatives increase the scope where the key can be visible, and are less developer-friendly in my opinion.

**Comment by menghanl** [comment]
Can you give more details about your usage? A more concrete example would be helpful.
Currently it sounds to me that this isn't what codec is intended for.
You can sign the message in the application code. And give gRPC the message with the signed message.

**Comment by paulhodson** [comment]
Certainly! I am working on a library which aims to add extra confidentiality to gRPC. It does 2 things:
- for fields which are so annotated, encrypts them (uses reflection) - currently `bytes` fields supported
- signs the whole message to prove that it was relayed unaltered

Why? This is designed for scenarios where the gRPC server is an intermediary between the client and a trusted endpoint. The gRPC server is just passing messages along, but interpreting some of the content.

Client —-gRPC—-> gRPC server —-other transport—-> trusted endpoint

The point of the codec here is to make this confidentiality and integrity nearly invisible to the client. The client codes against a totally normal looking gRPC call (spec in protobuf). The codec marshals and signs the request message and packs it into another transport-only message. It is this other message which is sent over the wire.

The receiving gRPC server’s codec does not have the key to decrypt any fields, nor to confirm the message is unaltered - it is the trusted endpoint which can do that, to which gRPC relays. But the gRPC server can unpack the message to do some processing on its contents. Critically, it has to be able to relay the message as generated by the client. So, ideally the codec would tack on the on-the-wire signed message to a `context.Context` which the business logic in the gRPC server could package up for the next hop.

________________________________

**Comment by paulhodson** [comment]
Re-reading my last comment it might not be obvious I have 2 uses for `context.Context`:
1. At client side, pass key from client to codec
2. At server side, pass original client-generated message `[]byte` to handling function

Basically having context parameters would make it a total breeze for me to implement behind-the-scenes confidentiality and integrity, without complicating the client-facing RPC API.

**Comment by menghanl** [comment]
How are keys interchanged between the client and the trusted endpoint?
What message type will the intermediary gRPC server see? Will it operate on []byte?

And it sounds that all of it can be done within the interceptor. This also hides the details for the application. What's the reason to use a codec?

Adding parameter to an existing interface is an API change. Though it might be a good idea, it will be very hard to add.

**Comment by paulhodson** [comment]
Thanks @menghanl for looking into this. There is another RPC to negotiate the keys.

The server has the codec also, so while on the wire the data is the signed message type (marshalled as []byte, certainly) it gets translated back to protobuf. It's symmetrical.

I agree an interceptor would have been a nice place to put this, but interceptor requires the in/out types to be the same, whereas here I'm changing the message type from the client-facing message type to the on-the-wire message type.

I guess I could put the signed message in a header, at the expense of essentially duplicating the traffic... hmm...

**Comment by menghanl** [comment]
> The server has the codec also, so while on the wire the data is the signed message type (marshalled as []byte, certainly) it gets translated back to protobuf. It's symmetrical.

I guess I still don't fully understand the use case here.
What's the difference between this and TLS then? If you are making it secure on wire, but the server sees the full message?

> interceptor requires the in/out types to be the same

There's a way to do this. You can change the message type to []byte, and pick a no-op byte codec (like [this](https://github.com/grpc/grpc-go/blob/master/benchmark/worker/main.go#L51)). But the less ideal part is, you need to make this interceptor is the last. Otherwise the next interceptor will get the wrong type.

> put the signed message in a header

Hmm, I wouldn't do this. I would probably do the opposite, put the message you want the gRPC server to see in headers (if you don't want it to see everything), but the encoded bytes in the message body.

**Comment by paulhodson** [comment]
> I guess I still don't fully understand the use case here.
> What's the difference between this and TLS then? If you are making it secure on wire, but the server sees the full message?
Parts of the message are encrypted also (they are annotated). This solution depends on partial confidentiality, and guaranteed integrity.
> There's a way to do this. You can change the message type to []byte, and pick a no-op byte codec (like [this](https://github.com/grpc/grpc-go/blob/master/benchmark/worker/main.go#L51)). But the less ideal part is, you need to make this interceptor is the last. Otherwise the next interceptor will get the wrong type.
Interesting. Sounds like users could easily err in getting this up and running... Plus they'd have to install both the client interceptor and the noop codec. It's doable, certainly, but realistically also error-prone.

Perhaps this point is up to debate, but I do think "codec" is the right term to apply to the message signing component - it is the part that serialises a message and transmits it over the wire in its own format. I hear your concern of course that API changes are harder to bring about.

What I really like about the codec approach too is that it changes the content-type. A client which doesn't care about the additional protection just calls normal RPC, which the server detects as grpc+proto. A client which wants the protection uses the codec which is sent as grpc+codecname. The server can handle both cases, which I believe is not true of an interceptor-based approach.

**Comment by dfawley** [comment]
One problem with the `context` approach is that there is no context from the method handler to pass on the server side -- the [`ServerStream`](https://godoc.org/google.golang.org/grpc#ServerStream) API doesn't have a context.  On the client side, all messages on a stream share the same context, which isn't a problem, but it means this isn't a per-message option even though it might appear like it is.

Another option that would not require an API change, and could be controlled per-message, would be to wrap your proto messages before calling `Send`:

```go
package myprotocodec

type WrappedProto struct {
	proto.Message
	OtherData interface{}
}

func (*MyProtoCodec) Marshal(v interface{}) ([]byte, error) {
	p, ok := v.(*WrappedProto)
	if !ok {
		// return error or fall back to standard proto codec
	}
	// use p.OtherData to encode the message
}

---
package main

func main() {
	// ...
	msg := pb.Request{...}
	wrapMsg := myprotocodec.WrappedProto{Message: msg, OtherData: ...}
	res, err := client.Call(ctx, wrapMsg)
	// ...
}
```

**Comment by paulhodson** [comment]
Thanks @dfawley. I have only been considering unary RPCs, so for me the lack of `context` in streaming RPCs isn't an issue.

In terms of wrapping the RPC call, I agree that's an option, though I've been reluctant to do that because it either forces the client to do more work (sign the message before the call, and package a type they "shouldn't" have to care about) or to use a library to do this for them, which hides away some of the gRPC goodness. I was hoping to package up those steps inside the gRPC integration points, in the name of usability.

In the short term, the interceptor + noop codec approach @menghanl [suggested](https://github.com/grpc/grpc-go/issues/3906#issuecomment-700296619) appears to be the likeliest candidate. In the longer term, perhaps I can still dream of having `context` in the codec!

**Comment by dfawley** [comment]
> Thanks @dfawley. I have only been considering unary RPCs, so for me the lack of context in streaming RPCs isn't an issue.

There is still the asymmetry with the server, which means the server method handler has no way to pass a context to the codec.

> In terms of wrapping the RPC call, I agree that's an option, though I've been reluctant to do that because it either forces the client to do more work (sign the message before the call, and package a type they "shouldn't" have to care about) or to use a library to do this for them

I don't understand your concerns here; possibly you don't understand my idea.

What you are asking for would be used like this:

```go
client.Call(WrapContextWithSigningOptions(ctx), msg)
```

What I'm suggesting would be used like this:

```go
client.Call(ctx, WrapMessageWithSigningOptions(msg))
```

**Comment by paulhodson** [comment]
> There is still the asymmetry with the server, which means the server method handler has no way to pass a context to the codec.

I must be missing something. I figured if the [interceptor](https://pkg.go.dev/google.golang.org/grpc#UnaryServerInterceptor) has a context then it exists.

> I don't understand your concerns here; possibly you don't understand my idea.

You are right! I did not understand your idea, sorry. I see now. It would expose a different type than I'm intending to the client, but maybe that's not a problem. I'll experiment with these approaches. Thank you.

**Comment by dfawley** [comment]
> I must be missing something. I figured if the interceptor has a context then it exists.

There *is* a context, but it is created by the grpc server.  The same context is passed to the method handler later.  (Actually, the native API could theoretically do this -- with an API change -- but in the proto generated API, the applications's method handler isn't invoked until after the message is decoded.)

If you *need* the context to have this data, e.g. so that the signing options can be transparent to the code that makes the calls, then a nice way to do that would be to combine these two options: put it in the context and move it from the context into the message via an interceptor.

```go
...
	ctx = WrapContextWithSigningOptions(ctx)
	helper(ctx)
}

func helper(ctx context.Context) {
	pb.Call(ctx, Request{...})  // doesn't know if signing is needed
}

// Set this as the UnaryClientInterceptor for the ClientConn:
func myInterceptor(ctx context.Context, method string, req, reply interface{}, cc *ClientConn, invoker UnaryInvoker, opts ...CallOption) error {
	opts := SigningOptionsFromContext(ctx)
	req = WrapMessageWithSigningOptions(req, opts)
	invoker(ctx, method, req, reply, cc, opts...)
}
```

**Comment by paulhodson** [comment]
> There _is_ a context, but it is created by the grpc server. The same context is passed to the method handler later. (Actually, the native API could theoretically do this -- with an API change -- but in the proto generated API, the applications's method handler isn't invoked until after the message is decoded.)

This sounds like what I'd expect and want (for the context to exist and be populated - tbd! - by the lower layers before the gRPC call is handled by the server. Admittedly I haven't spent much time yet on the server side.

> If you _need_ the context to have this data, e.g. so that the signing options can be transparent to the code that makes the calls, then a nice way to do that would be to combine these two options: put it in the context and move it from the context into the message via an interceptor.

That's a really neat idea, and solves the out-of-order interceptor problem with changing the output message type. I've got some experimentation to do.

**Comment by dfawley** [comment]
> That's a really neat idea, and solves the out-of-order interceptor problem with changing the output message type. I've got some experimentation to do.

Not *quite* - it would still alter the message type by wrapping it in another type.  I.e. if another interceptor was trying to do something with the request message (this should be quite rare), then it would either need to know about this transformation or be executed before this transforming interceptor.

I'm going to close this out.  It does seem reasonable, but it has some issues fitting into our streaming API.  It also would require a codec API change, and there is a viable workaround using the current API.  Thanks for the suggestion; it's something we should keep in mind if we ever do a full v2 gRPC API.
