### ISSUE TITLE
Need a way to interrupt ServerStream on the server

### ISSUE THREAD

**Issue by ItalyPaleAle** [grpc/grpc-go#3909]
### What version of gRPC are you using?
1.32.0

### What version of Go are you using (`go version`)?
1.15

### What operating system (Linux, Windows, …) and version?
Debian 10

### Issue description
There seems to be no way for the server to interrupt a stream.

On the client-side, it's possible to interrupt a stream with `stream.CloseSend()`.

On the server-side, it's not possible to interrupt a stream if you're currently listening for messages. The canonical way of doing that, with `stream.Recv` is blocking, and there's no way to un-block it:

```go
// Receive a message (the next call is blocking)
in, err := stream.Recv()
if err == io.EOF {
	return nil
}
if err != nil {
	return err
}
```

This is important because we need a way to gracefully shutting down servers.

There are (at least) two ways this can be achieved, but both of them require changes in grpc-go:

1. Offer another way to receive messages besides a blocking function call. For example, offer a way to receive messages via a channel (e.g. `stream.Messages` being a channel, so one could listen for messages using a `select` statement that also listens to a context).
2. While `ServerStream` offers access to its internal context, via `stream.Context()`, it doesn't offer access to the context's cancel function. Offering a way to cancel the context (which would then stop `stream.Recv`) would work too.

While both would work, I think option 1 should be the preferred as it's the most idiomatic Go.

**Comment by menghanl** [comment]
Returning from the service handler is the way to stop the server. The returned status will be sent to the client as RPC status. You can do the blocking Recv() in another goroutine.

**Comment by ItalyPaleAle** [comment]
When you talk about the service handler, what are you referring to?

**Comment by ItalyPaleAle** [comment]
Maybe I should have explained better. The `Recv` call is already in a goroutine and I can call `grpcServer.GracefulStop()`.

1. If no client is connected to a RPC that uses server streaming, then the graceful stop works well and the server stops correctly.
2. If there's even a single client connected to my RPC that uses server streaming, the graceful stop hangs and doesn't succeed (and I need to use a separate goroutine to wait on a timeout and then just call `grpcServer.Stop()`).

The reason why point 2 happens is because in the goroutine that's handling the RPC, the call to `Rec()` is a blocking one.

**Comment by menghanl** [comment]
Service handler is the method that you implement on the service struct, called to handle the service.  https://github.com/grpc/grpc-go/blob/master/examples/route_guide/server/server.go#L155

Returning from this function closes the stream. After the stream is closed, `Recv()` would return an error.

The behavior you described for `GracefulStop()` is working as intended. It waits for the existing streams to be done, but they never finish.

**Comment by ItalyPaleAle** [comment]
Got it. I rewrote the code as follows (irrelevant code omitted):

```go
func (s *server) HealthChannel(stream pb.ChannelServer) error {
	go func() {
		for {
			// This call is blocking
			in, err := stream.Recv()
			if err != nil {
				break
			}
            // Do something with in
		}
        fmt.Println("Goroutine done")
	}()
	for {
		select {
		// Exit if context is done
		case <-stream.Context().Done():
			fmt.Println("stream.Context().Done()")
			return nil
		// The server is shutting down
		case <-s.runningCtx.Done():
			fmt.Println("runningCtx.Done()")
			return nil
	}
}
```

When the server needs to be shut down, before calling `grpcServer.GracefulStop()`, I call the `cancel` function for `s.runningCtx`.

This doesn't seem to be working, however.

1. The `HealthChannel` function does return, in fact I see `runningCtx.Done()` in the console
2. The `stream` does end with a EOF, and the goroutine ends (in fact, I see `Goroutine done` in the console)
3. However, the transport isn't closing, and in fact the client isn't disconnected automatically.
4. Also, probably because of point 3, `GracefulStop` still doesn't succeed, and it continues blocking.

Aside from this specific issue, it would be **awesome** if gRPC could offer an alternative to `stream.Recv()` that is based on a channel. Ideally, we'd be able to write something like this:

```go
func (s *server) HealthChannel(stream pb.ChannelServer) error {
	for {
		select {
        // Received a new message
        case in <- stream.Channel():
            // Do something with in
		// Exit if context is done
		case <-stream.Context().Done():
			fmt.Println("stream.Context().Done()")
			return nil
		// The server is shutting down
		case <-s.runningCtx.Done():
			fmt.Println("runningCtx.Done()")
			return nil
	}
}
```

Not only this would solve the issues without the need for extra goroutines, but it is the most "gonic" way of doing things :)

**Comment by menghanl** [comment]
> 2. The stream does end with a EOF, and the goroutine ends (in fact, I see Goroutine done in the console)
> 3. However, the transport isn't closing, and in fact the client isn't disconnected automatically.

Does the client see the status after the server handler returns? It should get an `OK` if the service handler returns `nil`.

Are there other RPCs that the server is handling? When the last RPC finishes, the connection should be closed by `GracefulStop()`.

> it would be awesome if gRPC could offer an alternative to stream.Recv() that is based on a channel. Ideally

This won't happen unless we make gRPC-Go v2, and redesign the stream APIs.
There was in fact a very old issue #847, with label `v2`.

**Comment by menghanl** [comment]
Closing this issue now. Let's track the recv() channel proposal in the other issue.

**Comment by ItalyPaleAle** [comment]
Well, this issue is still relevant. I still don't have a way from the server to interrupt a RPC call. Because the `Recv()` method is blocking and doesn't accept a context (and the context returned by the stream doesn't expose a way to cancel it), the connection cannot be aborted.

Maybe another option is to expose the context cancel function that is part of the stream?

**Comment by menghanl** [comment]
Sorry for closing early.

Returning from the service handler is the way to cancel a stream. Using context and cancel as you have tried would be appropriate.
Exporting a cancel function will just be another way to end the stream, but then how to deal with the final status returned by service handler becomes tricky.

The reason that the connection is not closed is probably because there are other RPCs on the connection. Please check that. And if the problem persists, please try to make a minimum reproduction, so we can take a further look.

**Comment by ItalyPaleAle** [comment]
@menghanl Ok, I was able to get this to work. Here's the MVP for posterity: https://github.com/ItalyPaleAle/grpc-stream-go

Looks like something else might have caused my app's to hang, so I'll look into that. Thanks for the help
