### ISSUE TITLE
busy wait in NewClientStream

### ISSUE THREAD

**Issue by denquixote** [grpc/grpc-go#391]
I've noticed that my gRPC client consumes 100% cpu cycles on one core, when it tries to re-connect to a server which disappeared. pprof pointed me to this loop in stream.go that looks like busy wait to me:

    func NewClientStream(ctx context.Context, desc *StreamDesc, cc *ClientConn, method string, opts ...CallOption) (ClientStream, error) {
            var (
                    conn *Conn
                    t    transport.ClientTransport
                    err  error
            )
            for {
                    conn, err = cc.dopts.picker.Pick()
                    if err != nil {
                            return nil, toRPCErr(err)
                    }
                    t, err = conn.Wait(ctx)
                    if err != nil {
                            if err == ErrTransientFailure {
                                    time.Sleep(100 * time.Millisecond) // FIXME: dirty workaround, not a fix!
                                    continue
                            }
                            return nil, toRPCErr(err)
                    }
                    break
            }

I have added the time.Sleep(_), which "fixed" it for me.

**Comment by denquixote** [comment]
After digging into conn.Wait(ctx), I assume that I've somehow messed up the ctx in my code. I close this issue now and investigate down the context path.

**Comment by denquixote** [comment]
Sorry for the open/close/open noise, I've confused myself with my usage of context, but that was in fact not related. 

Also this is not related to "reconnect" as my client will re-start NewClientStream in case of any error (needed for my use case). So actually the problem manifests *whenever* a client tries to connect to a server, which does not listen (connection refused) and is easily reproducable with the stream example code:

    $ # start a route_guide client w/o starting a server first:
    $ go run $GOPATH/src/google.golang.org/grpc/examples/route_guide/client/client.go

Result: 100% consumed CPU cycles

The busy wait problem does appear to be in above quoted code. `conn.wait(ctx)` returns `ErrTransientFailue` "so that the caller gets chance to pick another transport to perform rpc instead of sticking to this transport," but apparently cc.dopts.picker.Pick() does not return "another transport," because obviously there is none at all.

**Comment by iamqizhao** [comment]
It seems my previous refactoring introduced this bug. It is actually fixed in my another bigger pr. But it is worth a separate fix. will send fix soon.
