### ISSUE TITLE
TRANSIENT_FAILURE state when moving from golang 1.13 to 1.14

### ISSUE THREAD

**Issue by ahamtat** [grpc/grpc-go#3910]
**What version of gRPC are you using?**
1.32.0

**What version of Go are you using (go version)?**
1.13.15 and 1.14.1

**What operating system (Linux, Windows, …) and version?**
Ubuntu 20.04

**What did you do?**
I set client connection with the following options:

	timeoutCtx, cancel := context.WithTimeout(ctx, connTimeout)
	defer cancel()

	keepaliveOpt := grpc.WithKeepaliveParams(keepalive.ClientParameters{
		Time:                20 * time.Second,
		PermitWithoutStream: true,
	})
	opts := []grpc.DialOption{c.certOpt(), keepaliveOpt, grpc.WithBlock()}
	opts = append(opts, c.logOpt()...)

	if c.authorizer != nil {
		creds, err := c.authorizer.GetTokenCredential(timeoutCtx, serviceAddress)
		if err != nil {
			return nil, err
		}
		opts = append(opts, grpc.WithPerRPCCredentials(creds))
	}
	grpc.DialContext(timeoutCtx, serviceAddress, opts...)

Then I moved my project from golang version 1.13.15 to 1.14.1

**What did you expect to see?**
With go1.13 client connected to server successfully and channel connectivity state was READY:

> INFO: 2020/09/28 17:24:24 [core] parsed scheme: ""
> INFO: 2020/09/28 17:24:24 [core] scheme "" not registered, fallback to default scheme
> INFO: 2020/09/28 17:24:24 [core] ccResolverWrapper: sending update to cc: {[{axxon-next:50051  <nil> 0 <nil>}] <nil> <nil>}
> INFO: 2020/09/28 17:24:24 [core] ClientConn switching balancer to "pick_first"
> INFO: 2020/09/28 17:24:24 [core] Channel switches to new LB policy "pick_first"
> INFO: 2020/09/28 17:24:24 [core] Subchannel Connectivity change to CONNECTING
> INFO: 2020/09/28 17:24:24 [core] blockingPicker: the picked transport is not ready, loop back to repick
> INFO: 2020/09/28 17:24:24 [core] Subchannel picks a new address "axxon-next:50051" to connect
> INFO: 2020/09/28 17:24:24 [core] pickfirstBalancer: UpdateSubConnState: 0xc00048c050, {CONNECTING <nil>}
> INFO: 2020/09/28 17:24:24 [core] Channel Connectivity change to CONNECTING
> INFO: 2020/09/28 17:24:24 [core] Subchannel Connectivity change to READY
> INFO: 2020/09/28 17:24:24 [core] pickfirstBalancer: UpdateSubConnState: 0xc00048c050, {READY <nil>}
> INFO: 2020/09/28 17:24:24 [core] Channel Connectivity change to READY
> INFO: 2020/09/28 17:24:24 [core] Channel Connectivity change to SHUTDOWN
> INFO: 2020/09/28 17:24:24 [core] Subchannel Connectivity change to SHUTDOWN
> INFO: 2020/09/28 17:24:24 [core] parsed scheme: ""
> INFO: 2020/09/28 17:24:24 [core] scheme "" not registered, fallback to default scheme
> INFO: 2020/09/28 17:24:24 [core] ccResolverWrapper: sending update to cc: {[{axxon-next:50051  <nil> 0 <nil>}] <nil> <nil>}
> INFO: 2020/09/28 17:24:24 [core] ClientConn switching balancer to "pick_first"
> INFO: 2020/09/28 17:24:24 [core] Channel switches to new LB policy "pick_first"
> INFO: 2020/09/28 17:24:24 [core] Subchannel Connectivity change to CONNECTING
> INFO: 2020/09/28 17:24:24 [core] Subchannel picks a new address "axxon-next:50051" to connect
> INFO: 2020/09/28 17:24:24 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
> INFO: 2020/09/28 17:24:24 [core] pickfirstBalancer: UpdateSubConnState: 0xc00048cb10, {CONNECTING <nil>}
> INFO: 2020/09/28 17:24:24 [core] Channel Connectivity change to CONNECTING
> INFO: 2020/09/28 17:24:24 [core] Subchannel Connectivity change to READY
> INFO: 2020/09/28 17:24:24 [core] pickfirstBalancer: UpdateSubConnState: 0xc00048cb10, {READY <nil>}
> INFO: 2020/09/28 17:24:24 [core] Channel Connectivity change to READY

**What did you see instead?**
When moved to go1.14 client started to fail with TRANSIENT_FAILURE state:
> INFO: 2020/09/28 17:54:56 [core] parsed scheme: ""
> INFO: 2020/09/28 17:54:56 [core] scheme "" not registered, fallback to default scheme
> INFO: 2020/09/28 17:54:56 [core] ccResolverWrapper: sending update to cc: {[{axxon-next:50051  <nil> 0 <nil>}] <nil> <nil>}
> INFO: 2020/09/28 17:54:56 [core] ClientConn switching balancer to "pick_first"
> INFO: 2020/09/28 17:54:56 [core] Channel switches to new LB policy "pick_first"
> INFO: 2020/09/28 17:54:56 [core] Subchannel Connectivity change to CONNECTING
> INFO: 2020/09/28 17:54:56 [core] blockingPicker: the picked transport is not ready, loop back to repick
> INFO: 2020/09/28 17:54:56 [core] Subchannel picks a new address "axxon-next:50051" to connect
> INFO: 2020/09/28 17:54:56 [core] pickfirstBalancer: UpdateSubConnState: 0xc00034e720, {CONNECTING <nil>}
> INFO: 2020/09/28 17:54:56 [core] Channel Connectivity change to CONNECTING
> INFO: 2020/09/28 17:54:56 [core] Subchannel Connectivity change to TRANSIENT_FAILURE
> INFO: 2020/09/28 17:54:56 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
> INFO: 2020/09/28 17:54:56 [core] pickfirstBalancer: UpdateSubConnState: 0xc00034e720, {TRANSIENT_FAILURE connection closed}
> INFO: 2020/09/28 17:54:56 [core] Channel Connectivity change to TRANSIENT_FAILURE
> INFO: 2020/09/28 17:54:56 [core] Channel Connectivity change to SHUTDOWN
> INFO: 2020/09/28 17:54:56 [core] Subchannel Connectivity change to SHUTDOWN

What golang changes can affect the behaviour of gRPC-Go client and how to fix this?

**Comment by dfawley** [comment]
> What golang changes can affect the behaviour of gRPC-Go client and how to fix this?

This is unusual.  Is it reproducible?  Does it happen 100% with go1.14?

> INFO: 2020/09/28 17:54:56 [core] Channel Connectivity change to SHUTDOWN

This means you called `ClientConn.Close()` - where/why does this happen?  Are you setting `FailOnNonTempDialError` (from `c.logOpt()`?)?

Is this a plaintext connection or are you using TLS?  I don't see transport credentials *or* WithInsecure specified, but one of the two is required.
