### ISSUE TITLE
Add only protoc-gen-go-grpc code in source code asset archives

### ISSUE THREAD

**Issue by amenzhinsky** [grpc/grpc-go#3927]
https://github.com/grpc/grpc-go/releases/tag/cmd%2Fprotoc-gen-go-grpc%2Fv1.0.0

Ships entire `grpc-go` repo in source code assets.

This would be useful to download smaller archives to build system packages, e.g. [aur](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=protoc-gen-go-grpc)

**Comment by dfawley** [comment]
Do you know if this is possible?  Github doesn't have many options while you are creating releases.

It is possible to get what you want from the release page:

1. Click the tag just under the release ("cmd/protoc-gen-...")
2. Click the `cmd/protoc-gen-go-grpc` directory
3. Click the "download" button, which has the following URL for this release:

https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Fgrpc%2Fgrpc-go%2Ftree%2Fcmd%2Fprotoc-gen-go-grpc%2Fv1.0.0%2Fcmd%2Fprotoc-gen-go-grpc

**Comment by amenzhinsky** [comment]
I see, github adds these archives automatically to every `git-tag`. 

It's possible to add custom assets only if releases are created using the github's proprietary releases feature, but I think this is not an option.

**Comment by amenzhinsky** [comment]
Thank you anyway.
