### ISSUE TITLE
Question: support getting both `protoc-gen-go` and `protoc-gen-go-grpc` at the same time?

### ISSUE THREAD

**Issue by chalin** [grpc/grpc-go#3928]
This is a follow up question to https://github.com/grpc/grpc.io/pull/436#discussion_r499963352. I'm asking the question here, because it concerns command bundling.

This is the [Quick start](https://grpc.io/docs/languages/go/quickstart/) excerpt I have a question about:

>   1. Install the protocol compiler plugin for Go using the following commands:
>
>      ```sh
>      $ export GO111MODULE=on  # Enable module mode
>      $ go get github.com/golang/protobuf/protoc-gen-go
>      $ go get google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.0
>      ```

For the majority of users, I'd expect that they'd always want to use both `protoc-gen-go` _and_ `protoc-gen-go-grpc`. If so, wouldn't it make sense to be able to `go get` a single entity that provides both?

**Comment by dfawley** [comment]
> For the majority of users, I'd expect that they'd always want to use both

Even stronger: if you are using `protoc-gen-go-grpc`, you *must* use `protoc-gen-go`.

> wouldn't it make sense to be able to go get a single entity that provides both?

I'm not sure such a thing is possible; do you know a way?

**Comment by menghanl** [comment]
I remember `protoc-gen-go` has a "library mode", so we can build a binary that runs both. But the flag processing would (likely?) become a mess. And also I think the library mode isn't officially supported.

Other the other side, maybe this is a good thing? So now users realize that proto and gRPC are two separate things...

**Comment by dfawley** [comment]
cc @dsnet @neild; maybe they can provide some insights into "library mode" and whether it's something we should do?

**Comment by neild** [comment]
Not sure exactly what is meant by "library mode".

Historically, `protoc-gen-go` supported generating both message and service definitions. Splitting out the gRPC service generation into a separate `protoc-gen-go-grpc` is a deliberate decision.

**Comment by menghanl** [comment]
> "library mode"

There was a way to import a package from `github.com/golang/protobuf/protoc-gen-go`, and call it's functions to generate code. But I think that was never intentionally done the way, and it's now moved to `internal` in the new library.

**Comment by chalin** [comment]
@dfawley wrote:
> > For the majority of users, I'd expect that they'd always want to use both
> 
> Even stronger: if you are using `protoc-gen-go-grpc`, you _must_ use `protoc-gen-go`.
> 
> > wouldn't it make sense to be able to go get a single entity that provides both?
> 
> I'm not sure such a thing is possible; do you know a way?

I'm no Go expert, but can't the `protoc-gen-go-grpc` module be marked as dependent on `protoc-gen-go` so that fetching `protoc-gen-go-grpc` also fetches all other executables it depends on?

@menghanl wrote:

> There was a way to import a package from `github.com/golang/protobuf/protoc-gen-go`, and call it's functions to generate code. But I think that was never intentionally done the way, and it's now moved to `internal` in the new library.

As far as I understand, we aren't wanting to introduce a compile-time dependency, but rather a runtime dependency -- i.e., to run `protoc-gen-go-grpc` one also needs `protoc-gen-go` to be somewhere in one's path.

**Comment by dfawley** [comment]
I don't think such a thing is technically possible.

FWIW, we can reduce this to one command to simplify:
```
GO111MODULE=on go get github.com/golang/protobuf/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.0
```

**Comment by dfawley** [comment]
Also we shouldn't prescribe the version number here, so it picks up new updates (which should be backward compatible).  So:
```
GO111MODULE=on go get github.com/golang/protobuf/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
```

**Comment by menghanl** [comment]
As a side note, I don't think we want `@v1.0` when `go get protoc-gen-go-grpc`. `@v1.0` pins the version to 1.0. Without that, I think `go get` downloads the latest release.

**Comment by chalin** [comment]
> Also we shouldn't prescribe the version number here, so it picks up new updates (which should be backward compatible). So:
> 
> ```
> GO111MODULE=on go get github.com/golang/protobuf/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
> ```

Thanks. Ok, I'll follow up via https://github.com/grpc/grpc.io/issues/446.
