### ISSUE TITLE
Fix Basics Tutorial Go documentation: update protoc command for generating client and server code

### ISSUE THREAD

**Issue by pdecks** [grpc/grpc-go#3933]
### What version of gRPC are you using?
v1.32.0

### What version of Go are you using (`go version`)?
go1.15.2 darwin/amd64

### What operating system (Linux, Windows, …) and version?
Mac OS 10.15.7

### What did you do?
Working through the [Basics Tutorial for Go](https://grpc.io/docs/languages/go/basics/), the current tutorial documentation directs the reader to run the following from the `route_guide` example directory:

`protoc -I routeguide/ routeguide/route_guide.proto --go_out=plugins=grpc:routeguide`

### What did you expect to see?
Generation of `route_guide.pb.go` and `route_guide_grpc.pb.go` in the directory `examples/route_guide/routeguide`.

### What did you see instead?
The following error:

`--go_out: protoc-gen-go plugins are not supported; use 'protoc --go-grpc_out=...' to generate gRPC`

### Proposed Solution
From this closed [`golang/protobuf` issue #1070](https://github.com/golang/protobuf/issues/1070), the [workaround](https://github.com/golang/protobuf/issues/1070#issuecomment-607465055):

_"`google.golang.org/protobuf/cmd/protoc-gen-go` will never have explicit gRPC support. We've split it out into a separate program (`protoc-gen-go-grpc`), so the gRPC code generator can live in the gRPC repository and follow that repo's release cycle._

_The practical effect is that when using this generator you will need to specify two flags on the protoc command line (or run protoc twice)"_

For clarity's sake, the two calls to `protoc` are:

```
$ protoc --go_out=. --go_opt=paths=source_relative routeguide/route_guide.proto          
$ protoc --go-grpc_out=. --go-grpc_opt=paths=source_relative routeguide/route_guide.proto
```

This should be updated in the [Go Basics Tutorial documentation](https://grpc.io/docs/languages/go/basics/), which would then match the [Go Quickstart documentation](https://grpc.io/docs/languages/go/quickstart/):

```
$ protoc --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    helloworld/helloworld.proto
```

**Comment by dfawley** [comment]
You most likely have the wrong version of protoc-gen-go (yours is from google.golang.org/protobuf, but the expected one is from github.com/golang/protobuf).

@chalin could you take a look at this, please?  This is the "basics" tutorial, not the quick start guide.

**Comment by chalin** [comment]
@dfawley - yes, I'll take a look tomorrow.

**Comment by chalin** [comment]
@dfawley - could you transfer this issue to [grpc/grpc.io](https://github.com/grpc/grpc.io)?

**Comment by chalin** [comment]
Actually, I'll just use https://github.com/grpc/grpc.io/issues/449.

**Comment by chalin** [comment]
Updates made via https://github.com/grpc/grpc.io/pull/450. PTAL

**Comment by chalin** [comment]
Closed via https://github.com/grpc/grpc.io/pull/450. cc @dfawley

**Comment by dfawley** [comment]
Thanks @chalin!
