### ISSUE TITLE
Bidirectional streaming RPC Retry policy

### ISSUE THREAD

**Issue by go-lumberjack** [grpc/grpc-go#3946]
Hi, Please tell me how I can use retry policy for Bidirectional streaming?

**Comment by easwars** [comment]
Specifying the retry policy through the `ServiceConfig` is the only supported way for doing retries in gRPC-Go.
More details can be found here: https://github.com/grpc/proposal/blob/master/A6-client-retries.md

Please let us know if you have further questions.
