### ISSUE TITLE
Remove log.Fatals from all example server method handlers

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#3952]
E.g. in the route guide server, we `log.Fatal` when errors occur sending/receiving.  This fairly normal case, if it results in a `log.Fatal`/`panic`, would take down the server.  This does not set a good example.

**Comment by HemantJoshi11** [comment]
Is this still open ?

**Comment by dfawley** [comment]
@HemantJoshi11 yes, are you interested in doing this?

**Comment by HemantJoshi11** [comment]
@dfawley I was checking ...\grpc-go\examples\route_guide\server\server.go but I could not find which log.Fatal needs to be removed. Could you please help me to understand this better?

**Comment by dfawley** [comment]
Hmmm, I must have misunderstood the changes @chalin was referencing in https://github.com/grpc/grpc.io/pull/450.  It seems the `log.Fatal`s are only in the client, not the server.  I'm fine with the client having them, since it's a cli-style client that is easier to exit on error than attempt a retry.  I did a quick `find|grep` for all the server files in our examples, and I don't see any `log.Fatal`s in method handlers.  Sorry for the misunderstanding!
