### ISSUE TITLE
Client stream (sent count packets)

### ISSUE THREAD

**Issue by mirecl** [grpc/grpc-go#3956]
Hi, how to control the number of packets sent from client.
I want send to server no more than 2 packets and wait next iterator.

**Comment by easwars** [comment]
Please provide more information for us to be able to assist you here.

What do you mean by packets? gRPC deals at message granularity. In the case of a bi-directional stream, one can apply any application logic to control what and how many messages each side sends. But if one is having to do complex application logic to control the number or order of messages sent by each end, that could very well indicate that gRPC service definition needs refactoring.

At the stream layer, gRPC sends as many messages as possible to the other end as allowed by the flow control.

**Comment by mirecl** [comment]
I don't want send  all messages at once. I want limit count send messages - for example only 3.
Pls answer, when save all message in client or server?

P.S. I am use docker-compose (apps: server - python, client - Golang) and all messages send in server at once without wait.

**Comment by easwars** [comment]
I'm not very familiar with docker-compose. And unfortunately I'm not able to understand your questions very well. 

Please take a look at https://grpc.io/docs/what-is-grpc/core-concepts/#rpc-life-cycle to familiarize yourself with the different types of RPCs supported by gRPC. And if none of these RPC types directly support what you are looking for, you might have to refactor your service definition.
