### ISSUE TITLE
Panic:  id (86) <= evictCount (158)

### ISSUE THREAD

**Issue by tigrato** [grpc/grpc-go#3957]
### What version of gRPC are you using?
v1.32
### What version of Go are you using (`go version`)?
v1.14.3
### What operating system (Linux, Windows, …) and version?
Linux 5.4

### What did you do?
Tested 50 clients on a HTTP application that does 2 gRPC calls per user.
The gRPC calls share the same contex: 
```
		ctx, cancel = context.WithTimeout(
			metadata.NewOutgoingContext(
				context.Background(),
				metadata.Pairs("key", "value"),
			),
			5*time.Second,
		)
```

### What did you expect to see?
Not to panic
### What did you see instead?
```
panic: id (86) <= evictCount (158)

goroutine 170 [running]:
golang.org/x/net/http2/hpack.(*headerFieldTable).idToIndex(0xc00033aa80, 0x56, 0xc000ec7b68)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20200707034311-ab3426394381/http2/hpack/tables.go:119 +0x12d
golang.org/x/net/http2/hpack.(*headerFieldTable).search(0xc00033aa80, 0x13fc029, 0x9, 0xc0002a6390, 0x24, 0x0, 0x0, 0x0)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20200707034311-ab3426394381/http2/hpack/tables.go:106 +0x14c
golang.org/x/net/http2/hpack.(*Encoder).searchTable(0xc00033aa80, 0x13fc029, 0x9, 0xc0002a6390, 0x24, 0x0, 0x0, 0x0)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20200707034311-ab3426394381/http2/hpack/encode.go:97 +0x92
golang.org/x/net/http2/hpack.(*Encoder).WriteField(0xc00033aa80, 0x13fc029, 0x9, 0xc0002a6390, 0x24, 0x0, 0x0, 0x0)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20200707034311-ab3426394381/http2/hpack/encode.go:62 +0x110
google.golang.org/grpc/internal/transport.(*loopyWriter).writeHeader(0xc00036e900, 0xbf, 0xc0000ac000, 0xc, 0xe, 0x0, 0x40e008, 0x20)
        /go/pkg/mod/google.golang.org/grpc@v1.32.0/internal/transport/controlbuf.go:664 +0x11c
google.golang.org/grpc/internal/transport.(*loopyWriter).originateStream(0xc00036e900, 0xc001401100, 0xc000ec7f18, 0xa4fc85)
        /go/pkg/mod/google.golang.org/grpc@v1.32.0/internal/transport/controlbuf.go:651 +0x1d0
google.golang.org/grpc/internal/transport.(*loopyWriter).headerHandler(0xc00036e900, 0xc00045b7c0, 0x0, 0x1)
        /go/pkg/mod/google.golang.org/grpc@v1.32.0/internal/transport/controlbuf.go:639 +0x416
google.golang.org/grpc/internal/transport.(*loopyWriter).handle(0xc00036e900, 0x1238480, 0xc00045b7c0, 0xc00045b7c0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.32.0/internal/transport/controlbuf.go:785 +0x60f
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc00036e900, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.32.0/internal/transport/controlbuf.go:519 +0x202
google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc00023ae00)
        /go/pkg/mod/google.golang.org/grpc@v1.32.0/internal/transport/http2_client.go:356 +0x7b
created by google.golang.org/grpc/internal/transport.newHTTP2Client
        /go/pkg/mod/google.golang.org/grpc@v1.32.0/internal/transport/http2_client.go:354 +0x120a
```

**Comment by JordyBaylac** [comment]
@tigrato , this is also happening to me, is there any solution?

**Comment by Heath68** [comment]
How did you fix this problem?This happens to me, too.

**Comment by JordyBaylac** [comment]
@Heath68 in my case it looks like http2 golang implementation was failing. Still I am trying to figure it out why, as a workaround I enable only http for the client, like this

`go
var HTTPTransport http.RoundTripper = &http.Transport{
	Proxy: http.ProxyFromEnvironment,
	DialContext: (&net.Dialer{
		Timeout:   30 * time.Second,
		KeepAlive: 30 * time.Second,
	}).DialContext,
	ForceAttemptHTTP2:     false, // <- this is my adjustment
	MaxIdleConns:          100,
	IdleConnTimeout:       90 * time.Second,
	TLSHandshakeTimeout:   10 * time.Second,
	ExpectContinueTimeout: 1 * time.Second,
}

var HTTPClient = http.Client{
	Transport: HTTPTransport,
}
`

Now you can use HTTPClient instead of the default client.

**Comment by Heath68** [comment]
> @Heath68 in my case it looks like http2 golang implementation was failing. Still I am trying to figure it out why, as a workaround I enabled only http for the client, like this:
> 
> ```go
> var HTTPTransport http.RoundTripper = &http.Transport{
> 	Proxy: http.ProxyFromEnvironment,
> 	DialContext: (&net.Dialer{
> 		Timeout:   30 * time.Second,
> 		KeepAlive: 30 * time.Second,
> 	}).DialContext,
> 	ForceAttemptHTTP2:     false, // <- this is my adjustment
> 	MaxIdleConns:          100,
> 	IdleConnTimeout:       90 * time.Second,
> 	TLSHandshakeTimeout:   10 * time.Second,
> 	ExpectContinueTimeout: 1 * time.Second,
> }
> 
> var HTTPClient = http.Client{
> 	Transport: HTTPTransport,
> }
> ```
> 
> Now you can use HTTPClient instead of the default client.
Thank you so much, I fixed this problem with sync.WaitGroup.
`var wg sync.WaitGroup
	wg.Add(1)
	segmentaddr := segmentURL
	go func(segmentaddr string) {
		log.Printf("GET %s", segmentaddr)
		rsp, err := hclient.Get(segmentaddr)
		if err != nil {
			panic(err)
		}
		_, err = io.Copy(body, rsp.Body)
		if err != nil {
			log.Println(logTag, "segment download error : ", err)
			return 
		}
		rsp.Body.Close()
		wg.Done()
	}(segmentaddr)
	wg.Wait()`

**Comment by dfawley** [comment]
@Heath68 FWIW if you ever get the `segment download error` your program will hang forever because it misses a `wg.Done`.  Further, the waitgroup + goroutine here are unnecessary -- just do the code inline instead and it is equivalent:

```go
segmentaddr := segmentURL
log.Printf("GET %s", segmentaddr)
rsp, err := hclient.Get(segmentaddr)
if err != nil {
	panic(err)
}
_, err = io.Copy(body, rsp.Body)
if err != nil {
	log.Println(logTag, "segment download error : ", err)
	return // ?? break? remove this? panic instead on error?
}
rsp.Body.Close()
```
