### ISSUE TITLE
How to deal with the mustEmbedUnimplemented method ?

### ISSUE THREAD

**Issue by eljoth** [grpc/grpc-go#3973]
Hey there,
I just came back to grpc not using it for a while now. I cannot find any guide on how to use the interface with the `mustEmbedUnimplementedFooServer`-method.

My structure is as follows:
- a dedicated go module for generated grpc file
- a go modue for the server
- a go module for the clients

Implementing the server, I have the problem to not being able to register a new server, since the `mustEmbedUnimplementedFooServer`-method is private and the type definition is in another package.
Are there any best practices to get around with that ?

The detailed error from GoLand is:
>Type cannot implement 'DataServiceServer' as **it has a non-exported method and is defined in a different package**

Best Regards!

**Comment by dfawley** [comment]
`mustEmbedUnimplementedFooServer` means you must embed the `UnimplementedFooServer` from the generated grpc package into your service implementation.  Example:

https://github.com/grpc/grpc-go/blob/9519efffeb5d1897ae8671568871a6d476986524/examples/route_guide/server/server.go#L56-L62

Feel free to reply here if you have any further questions; closing for now.
