### ISSUE TITLE
Legacy PerRPCCredentials with RequireTransportSecurity don't consider TransportCredentials SecurityLevel

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#3974]

**Comment by dfawley** [comment]
From #3964:

> Yes, that all sounds right to me. But note that the check in clientconn.go can't be improved since the TransportCredentials don't report their security level until after the connection is established. So the only place we can do this is in http2_client.go, and it will have to be a connection failure and not a channel-creation failure.

Actually -- would this be a *per-call* failure?  I believe we can check at connection time or call time (or both).

**Comment by yihuazhang** [comment]
You are right. We should do checks at both connection and call times as it is always preferred to reject early if possible. For per-connection check, I believe you should add a similar check in `DialContext()` API in `clientconn.go`.

**Comment by yihuazhang** [comment]
Sorry, I missed your previous comment on "not being able to improve the check in clientconn.go", and I agree with it. And if `PerRPCCredentials.RequireTransportSecurity()==true`, I believe we should require `==PrivacyAndIntegrity`.

**Comment by easwars** [comment]
Can this be closed now?
