### ISSUE TITLE
--go-grpc_out: server/api/user/user_grpc.pb.go: unparsable Go source: 13:18: illegal UTF-8 encoding (and 3 more errors)

### ISSUE THREAD

**Issue by chaunsin** [grpc/grpc-go#3977]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
grpc v1.32.0
protoc-gen-go v1.25.0
protoc        v3.9.0
protoc-gen-go-grpc 1.0

### What version of Go are you using (`go version`)?
1.14.2
### What operating system (Linux, Windows, …) and version?
windows
### What did you do?
With the `protoc-gen-go-grpc` command, Chinese annotations in the Proto file will report an error, such as:

> service User{
  // get user info 获取用户信息
  rpc Info(InfoReq) returns(InfoReply);
}

error occured:
--go-grpc_out: server/api/user/user_grpc.pb.go: unparsable Go source: 13:18: illegal UTF-8 encoding (and 3 more errors)......

But there is no mistake about it

>  service User{
  // get user info
  rpc Info(InfoReq) returns(InfoReply);
}

**Comment by menghanl** [comment]
I don't think Chinese annotations are _illegal_ UTF-8 encoding. I also tried this locally, and it worked for me.

Some guess:
 - Do you have other invisible characters in the line?
 - What Chinese encoding do you use? Could it be encodings other than UTF-8?

If this problem still exists, please provide an example `.proto` file so we can try out.

**Comment by chaunsin** [comment]
> I don't think Chinese annotations are _illegal_ UTF-8 encoding. I also tried this locally, and it worked for me.
> 
> Some guess:
> 
> * Do you have other invisible characters in the line?
> * What Chinese encoding do you use? Could it be encodings other than UTF-8? (Especially on windows)
> 
> If this problem still exists, please provide an example `.proto` file so we can try out.

**Comment by chaunsin** [comment]
> I don't think Chinese annotations are _illegal_ UTF-8 encoding. I also tried this locally, and it worked for me.
> 
> Some guess:
> 
> * Do you have other invisible characters in the line?
> * What Chinese encoding do you use? Could it be encodings other than UTF-8? (Especially on windows)
> 
> If this problem still exists, please provide an example `.proto` file so we can try out.

The contents are as follows：
`syntax = "proto3";

option go_package = "api/user;user";

message InfoReq{
  string username = 1;
}

message InfoReply{
  enum Sex {
    unknown = 0;
    man = 1;
    woman = 2;
  }

  string name = 1;
  int64 age = 2;
  Sex sex = 3;
}

service User{
  // 获取用户信息
  rpc Info(InfoReq) returns(InfoReply);
}`

The .proto file are as follows：
[proto.zip](https://github.com/grpc/grpc-go/files/5427075/proto.zip)

you try it thank you！

**Comment by menghanl** [comment]
The encoding of your file is GB2312

```
> enca -L chinese user.proto
Simplified Chinese National Standard; GB2312
  CRLF line terminators
```

You can convert it to UTF8 with

```
> iconv -t utf8 -f gb2312 < user.proto > user_utf8.proto

> enca -L chinese user_utf8.proto 
Universal transformation format 8 bits; UTF-8
  CRLF line terminators
```
