### ISSUE TITLE
Is there openssl engine support for grpc-go?

### ISSUE THREAD

**Issue by fbdlampayan** [grpc/grpc-go#3978]
In the grpc c repo, there was this merged PR for openssl engine support: https://github.com/grpc/grpc/pull/20316

Is this also reflected now in grpc-go? And if it already is, is there an existing documentation somewhere on how to use it?

(I've browsed through the examples and I haven't had the luck to find one)

**Comment by menghanl** [comment]
gRPC-Go's TLS implementation is based on golang's default TLS. There's currently no plan to add official TLS implementation.

What features do you need from openssl are not available in official library?
Alternatively, you can write your own credentials wrapper for openssl.

**Comment by fbdlampayan** [comment]
Thanks @menghanl  
I was aiming to have a grpc client TLS backed with TPM, so was wondering if grpc-go has an engine/plugin similar to openssl engine where one could use the tpm to store the keys and programmatically load the engine and have the engine access/load the keys.

**Comment by menghanl** [comment]
You may be able to modify [tls.Config](https://golang.org/pkg/crypto/tls/#Config) to work with TPM (with this [library](https://pkg.go.dev/github.com/google/go-tpm/tpm)).

Or, you can wrap openssl into gRPC-Go's [TransportCredentials](https://pkg.go.dev/google.golang.org/grpc/credentials#TransportCredentials) interface if that ends up easier.

There's no plan to add an openssl based TLS support, so I'm closing this issue now.
If you have further question, please comment. Thanks.

**Comment by fbdlampayan** [comment]
Alright, thanks for the information! Will look into these.
