### ISSUE TITLE
Content-type not included for trailer-only responses

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-go#398]
As seen in grpc/grpc-java#1113. Go should include content-type for trailer-only responses, as required by the spec.

**Comment by jtattermusch** [comment]
I confirm that the test started passing on Jenkins https://grpc-testing.appspot.com/job/gRPC_interop_master

Thanks for fixing this.
```
PASSED: cloud_to_cloud:java:go_server:empty_stream [time=1.3sec; retries=0;0].
```
