### ISSUE TITLE
Missing support for ipv4 and ipv6 scheme

### ISSUE THREAD

**Issue by jasiustasiu** [grpc/grpc-go#3982]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?

1.33.1

### What version of Go are you using (`go version`)?

1.13.4

### What operating system (Linux, Windows, …) and version?

Ubuntu 20.04 LTS

### What did you do?

I tried to follow https://github.com/grpc/grpc/blob/master/doc/naming.md#name-syntax 
I passed `ipv4:1.2.3.4:8888` as target in 
`grpc.DialContext(ctx context.Context, target string, opts ...DialOption)`
It failed to connect because of ipv4 scheme. If I pass `1.2.3.4:8888` it works but it's not valid according to document above (and `url.Parse()` function that we use to validate uri)

### What did you expect to see?

I expect this function to support ipv4 and ipv6 scheme

### What did you see instead?

connection timeout

**Comment by menghanl** [comment]
Thanks for reporting. We will add the support.

At the mean time, can you try `ipv4:///1.2.3.4:8888` and see if that works?

**Comment by dfawley** [comment]
Per https://github.com/grpc/grpc/blob/master/doc/naming.md, `ipv4` and `ipv6` are only supported by c-core.  You can use `"dns:///IP:PORT"` (or just `"IP:PORT"`) and it should work.

> If I pass 1.2.3.4:8888 it works but it's not valid according to document above

What part of the doc says that is not valid?

**Comment by jasiustasiu** [comment]
I tried with `ipv4:///1.2.3.4:8888` and `dns://1.2.3.4:8888` and both failed. Actually docs say ipv4 and ipv6 are supported by c-core and may or may not be supported by other implementations.
"A fully qualified, self contained name used for gRPC channel construction uses URI syntax as defined in RFC 3986."
"Each URI begins with a scheme..." https://tools.ietf.org/html/rfc3986#section-3.1
1.2.3.4:8888 doesn't have scheme and dns seems inapropriate as raw IP is not a DNS name

**Comment by dfawley** [comment]
> dns://1.2.3.4:8888 

This needs to be `dns:///1.2.3.4:8888`.  We *should* also support `dns:1.2.3.4:8888` but that doesn't work in Go (yet?).

> 1.2.3.4:8888 doesn't have scheme 

Without a scheme, the default resolver will be used.  For Go this is `passthrough` which just hands the target to `net.Dial`.  In Java and C the default dialer is "dns".  (Aside: we would like to change ours to match if we have a story around backward compatibility.)

> and dns seems inapropriate as raw IP is not a DNS name

True, but the DNS resolver handles IP addresses.  I believe this is true in the other languages as well, but I'm not 100% sure.

We will not be adding an `ipv4`/`ipv6` scheme in Go.  IIRC the C devs said they would have preferred if they had never added these schemes.

**Comment by jasiustasiu** [comment]
`dns:///1.2.3.4:8888` works but it looks like a workaround. 
https://tools.ietf.org/html/rfc4501#section-3 states  
`dnsurl = "dns:" [ "//" dnsauthority "/" ] dnsname ["?" dnsquery]` 
and 
`dnsauthority    = host [ ":" port ]` 
where 
`host = IP-literal / IPv4address / reg-name`
so `dns://1.2.3.4:8888` looks like a proper final solution

**Comment by dfawley** [comment]
The IP address you are specifying here is not a DNS server address, which is what `dnsauthority` is in RFC4501.  `dns://1.2.3.4:8888` is not valid.  With the `dns` scheme per RFC4501, you must have a `dnsname` to resolve, e.g. `dns://1.2.3.4:8888/myhost.com`.  Note also that RFC4501 doesn't support a `:port` in the `dnsname`.

gRPC doesn't implement RFC4501 exactly; we implement it with two very minor changes: 1. gRPC supports a `:port` suffix to specify the gRPC server's port, and 2. gRPC supports `IP:port` in addition to `dnsname:port`.

Another option: if you are using an IP address, you can omit the scheme entirely, in which case the default of `passthrough` will be used.  `passthrough` just sends the target to `net.Dial` directly, no matter what it is.
