### ISSUE TITLE
Client sends an invalid authority when target is ":5000"

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-go#3983]
I noticed that grpc-health-probe, which uses grpc-go client internally, sends an invalid authority if only a port is specified as the target

> grpc-health-probe -addr=:5000 -v

Wireshark capture of headers:

![image](https://user-images.githubusercontent.com/303201/96990805-14935b80-1584-11eb-97cf-828611ba2919.png)

`:5000` is not a valid value according to the HTTP/2 spec - https://www.rfc-editor.org/rfc/rfc3986.html#section-3.2. A host is required with the port. The gRPC server (.NET Kestrel) rejects the HTTP/2 request as invalid because of the authority.

If `:5000` is specified then the authority should be sent as `localhost:5000`

**Comment by GarrettGutierrez1** [comment]
Hi @JamesNK. Thanks for reporting this. I have assigned myself to this issue and will take a look at resolving the bug.
