### ISSUE TITLE
Very large messages can result in "gprc: compression is not supported yet." errors

### ISSUE THREAD

**Issue by jcgregorio** [grpc/grpc-go#399]
I have boiled this down to this reproducible case, which I've uploaded here as a patch against the helloworld example in grpc-go:

  https://codereview.chromium.org/1407753003

When I run this I get:
$ greeter_client
2015/10/15 02:48:46 could not greet: rpc error: code = 2 desc = "rpc error: code = 13 desc = \"gprc: compression is not supported yet.\""

If, on the other hand I reduce the number of key-value pairs stored in the map from 200,000 down to 20,000 the call succeeds.

**Comment by dsymonds** [comment]
Interesting. That message originates from rpc_util.go:209, but should only arise if (*parser).recvMsg returned something odd.

I bet I know: it's probably an overflow. gRPC messages have a fixed size header, with a 32-bit length. I reckon your code is producing a message that breaks over that limit, and is being encoded incorrectly as a result, leading to a confused decoder.

**Comment by dsymonds** [comment]
Nope. That's not it. Your message is ending up ~18MB big, well short of 32 bits, and the encoder code wouldn't break on it that way either.

**Comment by iamqizhao** [comment]
It is odd. will take a close look tomorrow.

**Comment by dsymonds** [comment]
A quick binary search shows it breaks somewhere between length=16513903 (0xFBFB6F) and length=16988903 (0x1033AE7), so I'm back to the overflow suspect, but at 24-bits, which is weird.

**Comment by dsymonds** [comment]
Oh, I found the bug. I think it was caused by overuse of constants, which hid the problem.
