### ISSUE TITLE
rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by YZherebukh** [grpc/grpc-go#3994]
I have a server with gRPC stream. And after a client, who had previously subscribed on that stream, unsubscribing, I'm getting this error rpc error: code = Unavailable desc = transport is closing

After I've enabled more detailed logs, I saw this warning grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: http2Server.HandleStreams failed to receive the preface from client: EOF" And I'm getting it a couple times per second. What can be a problem?

**Comment by GarrettGutierrez1** [comment]
Hello @YZherebukh. Can you provide more details on your situation? What is the nature of your clients? Sometimes this error happens if the client and server are differently configured with regards to auth. This can also be indicative of connectivity problems, but that is less likely.

**Comment by YZherebukh** [comment]
@GarrettGutierrez1 
This is how it works. 

Client calls server's endpoint and server starts the stream. Everything is on AWS and authorisation is in place.

Server
`
GetStreamClient(req *sub.StreamRequest, stream pb.StreamClient) error { 
for {
    err := stream.Send()
    if err != nil {
    //log error
    return
    }
  }
} 
`

Client 
`
func One() {
conn, err := grpc.Dial(c.host, grpc.WithTransportCredentials(credentials.NewClientTLSFromCert(nil, "")))
if err != nil {
	return nil, fmt.Errorf("failed to create grpc client, error: %w", err)
}

return sub.NewSubscribeServiceClient(conn), nil
...
}

func Two() {
    stream, err := s.stream.GetStreamClient(metadata.AppendToOutgoingContext(ctx,"key","value"),&sub.StreamRequest{})
    for {
       resp, err := stream.Recv()
       if err != nil {
           stream.CloseSend()
           return
        }
....
    }
}
`

**Comment by GarrettGutierrez1** [comment]
The client looks like it is using TLS. Is it possible your server is not doing the same?

**Comment by YZherebukh** [comment]
@GarrettGutierrez1 the server does that too

**Comment by GarrettGutierrez1** [comment]
Hello @YZherebukh. Is it possible for you to reproduce this error locally? Something network related might be the issue here, so perhaps run them on the same machine.
