### ISSUE TITLE
xds: Handle SubConn interface in cdsBalancer

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#4000]
https://github.com/grpc/grpc-go/pull/3955 adds logic in cdsBalancer to add address attributes to the `NewSubConn` call. The same might be required for `UpdateAddresses()` method, which is part of the `SubConn` interface.

**Comment by easwars** [comment]
Currently the `cdsBalancer` wraps the `balancer.ClientConn` passed to it in a type named `ccWrapper` and passes this to its child policy.

```golang
type ccWrapper struct {
  balancer.ClientConn
  xdsHI *xdsinternal.HandshakeInfo
}
```

The `ccWrapper` type overrides only the `NewSubConn` method of the `balancer.ClientConn` interface, and adds address attributes (which contain handshake info for the xds credentials implementation) to the addresses passed in by the child policy. But it passes the `SubConn` returned by gRPC as-is to its child policy.

If the child policy ends up calling `UpdateAddresses()` on the received `SubConn`, the `cdsBalancer` has no way to add the required attributes. This would mean that `xdsCredentials` would end up using the configured fallback credentials (which could possibly be insecure creds).

I plan on making the following changes:
1. Add a new wrapped subConn type, and override the `UpdateAddresses` to add address attributes as currently being done in `ccWrapper.NewSubConn`
```golang
type scWrapper struct {
  balancer.SubConn
}
func (scw *scWrapper) UpdateAddresses([]resolver.Address) { ... }
```

2. Keep track of the association between the `SubConn` returned by gRPC and wrapped subConns in `ccWrapper`:
```golang
type ccWrapper struct {
  ...
  mu sync.Mutex
  scMap map[balancer.SubConn]*scWrapper
}
```

3. Change `ccWrapper.NewSubConn` as follows:
```golang
func (ccw *ccWrapper) NewSubConn([]resolver.Address, balancer.NewSubConnOptions) (balancer.SubConn, error) {
  Add address attributes
  Call NewSubConn on parent
  Create a wrapped subConn, add it to the map and return it
}
```

4. Override `ccWrapper.RemoveSubConn` to lookup the underlying `SubConn` from the map and use that when calling `RemoveSubConn` on the parent.

5. Currently `SubConnStateChange` in `cdsBalancer` simply forwards the call to its child policy. This needs to also delete the entry from the `scMap` if the new state is `Shutdown`.

**Comment by dfawley** [comment]
I would say difficulty / complexity in intercepting is justification for changes in the API.

Ideally we wouldn't need to both wrap `SubConn` and keep a map from the wrapped `SubConn` to the real `SubConn`.  Either `SubConn` could have a `Remove/Stop/Close` method (instead of `ClientConn.RemoveSubConn`, or `ClientConn` could have `UpdateAddresses(SubConn, []resolver.Address)` instead.

**Comment by dfawley** [comment]
Looks like moving `RemoveSubConn` to `SubConn.Close` doesn't buy us anything, as the real issue is that needing to wrap the `SubConn` at all means that we need a map to handle propagation of `UpdateSubConnState` calls.

So, we would need to move `UpdateAddresses` into `balancer.ClientConn`.  This would avoid the need to wrap `SubConn` entirely -- the only method left would be `Connect`, and there are not many scenarios where wrapping `Connect` is important (none in the current plans for xds that I am aware of).

**Comment by easwars** [comment]
Moving `UpdateAddresses` into `balancer.ClientConn` seems straight-forward enough.
This [commit](https://github.com/easwars/grpc-go/commit/2fb90b4a71ba5b10cd83d46e33598ccb04161284) has all tests passing. I didn't remove `UpdateAddresses` from the `balancer.SubConn` interface as part of this commit based on our discussion that it needs to be a multi-step process as we are breaking the API.

I tried the other option as well, where we would delete the `RemoveSubConn` method from `balancer.ClientConn` and add a `Close` method to the `balancer.SubConn` interface. This seemed like more work (although I had done the work to remove the method also here), and as mentioned in your previous comment, it does not buy us enough.

Please let me know your thoughts. Thanks.

**Comment by dfawley** [comment]
> This commit has all tests passing. 

Were those all of the uses of `UpdateAddresses` in grpc-go?  If so, this LGTM.  @menghanl?

**Comment by easwars** [comment]
> > This commit has all tests passing.
> 
> Were those all of the uses of `UpdateAddresses` in grpc-go? If so, this LGTM. @menghanl?

Since everything built and tests passed, I'm assuming that these are all the changes that we would need.

I was initially under the wrong assumption that adding `UpdateAddresses` to the `balancer.ClientConn` interface would require changes to all LB policies. But then realized that this interface is not implemented by the LB policies, but is implemented by gRPC. And I think wherever an LB policy wraps this interface and passes it to a child policy, we usually embed this interface and only override the specific functionality that we need.

**Comment by dfawley** [comment]
> Since everything built and tests passed, I'm assuming that these are all the changes that we would need.

You may also want to remove the `UpdateAddresses` method from `balancer.SubConn` temporarily to make sure everything keeps passing.  If `vet.sh` passes, it's *probably* good enough because of the `Deprecated` comment, but that will make doubly-sure.

**Comment by easwars** [comment]
Here is the [commit](https://github.com/grpc/grpc-go/commit/6e98c25e1b175892ab78576b84af417a9ce572f5) to remove `UpdateAddresses` from `balancer.SubConn`. Seems reasonably straight-forward as well. If there are no major objections, I can file an issue for the API change and send PRs.
Thanks.

**Comment by dfawley** [comment]
SGTM.  @menghanl ?

**Comment by menghanl** [comment]
SGTM overall.

Would it make life easier (or harder?) if we make `UpdateAddress` return a new `SubConn`? So that the balancers can still wrap SubConn if they need to.
```go
UpdateAddress(SubConn, []addr) SubConn
```

**Comment by easwars** [comment]
> SGTM overall.
> 
> Would it make life easier (or harder?) if we make `UpdateAddress` return a new `SubConn`? So that the balancers can still wrap SubConn if they need to.
> 
> ```go
> UpdateAddress(SubConn, []addr) SubConn
> ```

It does look to me that making `UpdateAddress` return a new `SubConn` would be more work because our `baseBalancer` and `pickFirst` implementations simply update the address on the subConn that they have. But with the approach of returning a new `SubConn`, they would need to overwrite the subConns that they store and I don't clearly understand if the same has any ramifications for LB policies that sit on top of them in the hierarchy.
