### ISSUE TITLE
 Does gRPC provide a function to manage handlers in common?

### ISSUE THREAD

**Issue by HanHoRang** [grpc/grpc-go#4003]
Hi, 
Does gRPC have a proxy function that can be provided to multiple  handlers in common?
 I would like to attach a security module in common for each handlers implemented through gRPC. 
In addition, I would like to have a common feature that will be updated later.

Or is there a function that can manage each API in common?

**Comment by dfawley** [comment]
You might be looking for interceptors?

https://godoc.org/google.golang.org/grpc#StreamServerInterceptor
https://godoc.org/google.golang.org/grpc#UnaryServerInterceptor
