### ISSUE TITLE
Segmentation violation when conn.Close() is called

### ISSUE THREAD

**Issue by tomoechan** [grpc/grpc-go#4010]
### What version of gRPC are you using?
v1.31.0

### What version of Go are you using (`go version`)?
go1.15.2 linux/amd64

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
So I spawn a goroutine to handle every new gRPC connection. Everything works fine, except that the client will always seg-fault if conn.Close() is called in order to handle the err arising from an abrupt reverse proxy shutdown, the reverse proxy is HAPROXY which terminates tls and communicates with backend gRPC server in plain text. If conn.Close() is not called, seg-fault won't happen and the goroutine just returns but the connection between client and the reverse proxy will stay forever, wasting server resources. The panic call stack is as below:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x776da4]

goroutine 27 [running]:
google.golang.org/grpc/internal/transport.newHTTP2Client(0xa1ce40, 0xc000228de0, 0xa1cdc0, 0xc0002fa4c0, 0x98ab39, 0x15, 0x98ab39, 0x15, 0x0, 0x0, ...)
	/go/src/google.golang.org/grpc/internal/transport/http2_client.go:261 +0xa04
google.golang.org/grpc/internal/transport.NewClientTransport(...)
	/go/src/google.golang.org/grpc/internal/transport/transport.go:579
google.golang.org/grpc.(*addrConn).createTransport(0xc0000b62c0, 0x98ab39, 0x15, 0x98ab39, 0x15, 0x0, 0x0, 0x0, 0x0, 0x9894ac, ...)
	/go/src/google.golang.org/grpc/clientconn.go:1286 +0x40f
google.golang.org/grpc.(*addrConn).tryAllAddrs(0xc0000b62c0, 0xc000066c40, 0x1, 0x1, 0xbfe05ef610ddfe0a, 0x184e0b70dd, 0xcf00e0, 0xa220c0, 0xc000544540, 0x0, ...)
	/go/src/google.golang.org/grpc/clientconn.go:1216 +0x38d
google.golang.org/grpc.(*addrConn).resetTransport(0xc0000b62c0)
	/go/src/google.golang.org/grpc/clientconn.go:1131 +0x23f
created by google.golang.org/grpc.(*addrConn).connect
	/go/src/google.golang.org/grpc/clientconn.go:814 +0x12a

My client options:
```

		var connectParams = grpc.ConnectParams{
			backoff.Config {
			3*time.Second,
			1.8,
			0,
			20*time.Second,
			},
			10*time.Second,
		}

		opts = append(opts,grpc.WithConnectParams(connectParams))
		opts = append(opts,grpc.WithContextDialer(utlsDial)) // dial is handled by utls(https://github.com/refraction-networking/utls)
		opts = append(opts,grpc.WithInsecure())
		opts = append(opts,grpc.WithBlock())

```
No server options are configured, the server listens on a plain net.Listener, as TLS has been terminated by the reverse proxy. Interestingly, If I shut down the server instead of reverse proxy, the client won't panic. The goroutine just exits successfully after conn.Close() returns.

### What did you expect to see?
No panic when conn.Close() is called as a wrap-up measure to handle abrupt reverse proxy shutdown.

### What did you see instead?
Seg-fault panics with above call stack all the time.

**Comment by dfawley** [comment]
Can you provide a minimal example that will allow us to reproduce this?  As is, things seem a little odd:

v1.31.0, http2_client.go:261:

https://github.com/grpc/grpc-go/blob/bde0263672f027525e2950992a4c7db7af572b59/internal/transport/http2_client.go#L261

`scheme` is a string, so can't cause a seg fault.  Maybe this error was from a different version?

Also, the segfault is happening in `NewClientTransport`, implying it is failing when a new connection is starting, but the failure happens because of a `Close()` call.  Not that this is impossible, it just seems unusual.

**Comment by tomoechan** [comment]
Hi, @dfawley 

Sorry for the typo, my grpc version is 1.34.0-dev as per version.go

I investigated this bug a bit last week, it seemed the `opts = append(opts,grpc.WithContextDialer(utlsDial))` dial option caused this problem, as when I removed this option and used 'opts = append(opts, grpc.WithTransportCredentials(creds))' instead for dial, the problem vanished. While I can do with this change in my use case and this bug may have more to do with the package I import to dial, I'd still like to post my implement of the utlsDial function for debug purpose. Thanks for your help.


`
import "github.com/refraction-networking/utls"

func utlsDial(ctx context.Context, addr string) (net.Conn, error) {

	tcpConn,err := net.Dial("tcp4",addr)
	if err != nil {
		log.Println("tcp handshake failed")
		return nil,err
	}

	root,_ := x509.SystemCertPool()
	config := &tls.Config {
		RootCAs:root,
		MinVersion: tls.VersionTLS13,
		MaxVersion: tls.VersionTLS13,
		ServerName:"re.dact.ed",
		NextProtos:[]string{"h2"},
	}

	uConn := tls.UClient(tcpConn,config,tls.HelloRandomizedALPN)

	errChan := make(chan error,1)
	go func() {
		errChan <- uConn.Handshake()
	}()

	select {
	case <- ctx.Done():
		return nil,err
	case err =<-errChan:
		if err != nil {
			log.Println("tls handshake failed")
			return nil,err
		}
		return uConn,nil
	}
}`

**Comment by tomoechan** [comment]
Hi, @dfawley 

Sorry for the typo, my grpc version is 1.34.0-dev as per version.go

I investigated this bug a bit last week, it seemed the `opts = append(opts,grpc.WithContextDialer(utlsDial))` dial option caused this problem, as when I removed this option and used `opts = append(opts, grpc.WithTransportCredentials(creds))` instead for dial, the problem vanished. While I can do with this change in my use case and this bug may have more to do with the package I import to dial, I'd still like to post my implement of the utlsDial function for debug purpose. Thanks for your help.

`func utlsDial(ctx context.Context, addr string) (net.Conn, error) {

	tcpConn,err := net.Dial("tcp4",addr)
	if err != nil {
		log.Println("tcp handshake failed")
		return nil,err
	}

	root,_ := x509.SystemCertPool()
	config := &tls.Config {
		RootCAs:root,
		MinVersion: tls.VersionTLS13,
		MaxVersion: tls.VersionTLS13,
		ServerName:"redacted.xyz",
		NextProtos:[]string{"h2"},
	}

	uConn := tls.UClient(tcpConn,config,tls.HelloRandomizedALPN)

	errChan := make(chan error,1)
	go func() {
		errChan <- uConn.Handshake()
	}()

	select {
	case <- ctx.Done():
		return nil,err
	case err =<-errChan:
		if err != nil {
			log.Println("tls handshake failed")
			return nil,err
		}
		return uConn,nil
	}
}`

**Comment by dfawley** [comment]
> Sorry for the typo, my grpc version is 1.34.0-dev as per version.go

Do you have the git commit hash in that case?

I'm not familiar with utls, but TLS should be handled via the handshaker and not the dialer.  Was your client also using `grpc.WithInsecure` in order to work in that case?

**Comment by tomoechan** [comment]
I searched a bit and found the following info when I ran 'git log' in the grpc directory, this entry has the latest timestamp.

`commit 4be647f7f6dbe8e956014c93a79b9032e5a8b613 (HEAD -> master, origin/master, origin/HEAD)
Author: Garrett Gutierrez <gargut@google.com>
Date:   Fri Oct 16 11:52:54 2020 -0700

    internal/resolver/unix: Implemented unix resolver. (#3890)`

Not sure if this alone could pinpoint the grpc version on my machine.

And yes, I had `grpc.WithInsecure` dial option along with the `grpc.WithContextDialer(utlsDial)`, the option combination which could produce this bug is inserted in the issue. Having them both at once felt hacky to me so I changed them to `grpc.WithTransportCredentials(creds)` and the problem was solved.

**Comment by dfawley** [comment]
I'm not sure if it's the root cause, but I do see a bug:
```
	select {
	case <- ctx.Done():
		return nil,err
```

This should be `return nil, ctx.Err()`.  You may be returning a nil `net.Conn` and a nil error -- this would make grpc-go call methods on the nil `tls.Conn` which may not be able to handle it.

**Comment by tomoechan** [comment]
Brilliant, you hit the bug on the head. The seg fault doesn't occur any more. Thank you very much!
