### ISSUE TITLE
Memory retained after all connections closed

### ISSUE THREAD

**Issue by howardjohn** [grpc/grpc-go#4013]
I have a bidi streaming service (XDS server). I opened 10k connections, and sent a LOT of data over an hour or so, then closed all connections. I can see from my app code I have 0 connections, as well as from netstat.

After this, I see lots of memory retained by RecvMsg and newFramer.

Heap profile:
[pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.011.pb.gz](https://github.com/grpc/grpc-go/files/5485243/pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.011.pb.gz)

Goroutine dump:
[goroutine.txt](https://github.com/grpc/grpc-go/files/5485246/goroutine.txt)

I am not sure if I can reproduce this 100% of the time, but I know for sure I have seen it before. I have not yet ruled out the possibility that my application is holding onto a message which somehow causes the entire connection stack to not be GCd, but will attempt to add some additional debugging to investigate this.

I realize this is probably too vague to make any action, mostly looking for some guidance on what info/debugging steps to move forward with. Thanks!

**Comment by howardjohn** [comment]
I can trivially reproduce this in ~1 or so by opening and closing 1000 connections. going to try to instrument things a bit to get more info

**Comment by howardjohn** [comment]
nevermind, my trivial one was just GC not running. For original report I am fairly confident this was not the cause since GC should be triggered every 2min if I understand correctly, and I was manually triggering gc with `pprof/heap?gc=1`

**Comment by dfawley** [comment]
@howardjohn what version of grpc were you running with when you generated the heap profile?

**Comment by howardjohn** [comment]
@dfawley that would be google.golang.org/grpc v1.33.1. Sorry, forgot its not in the profile
