### ISSUE TITLE
rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by Able5** [grpc/grpc-go#4040]
Please see the FAQ in our main README.md before submitting your issue.
Hello, I have encountered a problem. During the software development process, when the client is calling, it will occasionally appear on the caller, `rpc error: code = Unavailable desc = transport is closing`). During the stress test, the The scope has appeared, and the ending method has not been found so far. I saw the questions in the issues.
`server = grpc.NewServer(
grpc.KeepaliveParams(keepalive.ServerParameters{
MaxConnectionIdle: 5 * time.Minute, // <--- This fixes it!}),`) does not solve my current problem, my Go version is go1.15.3 windows/amd64

**Comment by menghanl** [comment]
Please try to turn on logging on both sides. If the client failed with this error, the root cause is usually on the server side. https://github.com/grpc/grpc-go#the-rpc-failed-with-error-code--unavailable-desc--transport-is-closing

**Comment by Able5** [comment]
Thank you for your answer, but from the diary of the called server, there are no errors or exceptions, but the caller returns this error when it is called. It occurs probabilistically under normal circumstances, but on a large scale under stress testing, Is it due to the upper limit of RPC connections

**Comment by menghanl** [comment]
There's no limit of connections. There could be a limit of streams on each connection, but that won't cause this error.

The cause could be problems with the TCP connections. Try to turn on keepalive on the client side and see if that helps? 
https://github.com/grpc/grpc-go/blob/master/Documentation/keepalive.md
https://github.com/grpc/grpc-go/tree/master/examples/features/keepalive
