### ISSUE TITLE
Frequent ALTS interop test failures caused by golang package missing

### ISSUE THREAD

**Issue by yihuazhang** [grpc/grpc-go#4067]
In the past two weeks, ALTS interop test has frequently failed due to missing essential golang packages as shown in [this error log](https://source.cloud.google.com/results/invocations/77882453-9ee6-4477-acf3-204db482bfc6/log). 

@dfawley, @jtattermusch, do you have any clue on what might go wrong?

@jiangtaoli2016, @cesarghali F.Y.I.

**Comment by jtattermusch** [comment]
See internal b/174073491 for details.
Should be fixed by https://github.com/grpc/grpc/pull/24831 which was already merged.
