### ISSUE TITLE
advancedtls and CertAndHostVerification in ClientOptions does not work

### ISSUE THREAD

**Issue by godfryd** [grpc/grpc-go#4068]
### What version of gRPC are you using?
- google.golang.org/grpc v1.33.2
- google.golang.org/grpc/security/advancedtls v0.0.0-20201125005357-44e408dab41e

### What version of Go are you using (`go version`)?
1.15.5

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
Enabling host verification on client side does not work. I build client options as follows:
```go
	options := &advancedtls.ClientOptions{
		IdentityOptions: advancedtls.IdentityCertificateOptions{
			Certificates: []tls.Certificate{certificate},
		},
		RootOptions: advancedtls.RootCertificateOptions{
			RootCACerts: certPool,
		},
		VType: advancedtls.CertAndHostVerification,
	}
	creds, err := advancedtls.NewClientCreds(options)
```

If I use `advancedtls.CertVerification` then it works. But with `advancedtls.CertAndHostVerification`
it doesnt work. The error trace returned is as follows:
```
grpc manager is unable to re-establish connection with the agent 10.45.58.108:8080: rpc error: 
code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: 
x509: certificate is valid for localhost, u2004.lxd., localhost, u2004, not 10.45.58.108:8080"
```
The suspicious part in the log is `10.45.58.108:8080`. Why does it include the port?
Looking at the code reveals that in 
https://github.com/grpc/grpc-go/blob/master/security/advancedtls/advancedtls.go
in ClientHandshake function, there is a comment:
```
     // We return the full authority name to users if ServerName is empty without
     // stripping the trailing port.
```
Why is port not stripped? I'm not sure if this is correct but because of this it does not work.

So I build custom verification function that strips port:
```go
	VerifyPeer: func(params *advancedtls.VerificationFuncParams) (*advancedtls.VerificationResults, error) {
		opts := x509.VerifyOptions{
			Roots:         certPool,
			CurrentTime:   time.Now(),
			Intermediates: x509.NewCertPool(),
			KeyUsages:     []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth},
			DNSName:       strings.Split(params.ServerName, ":")[0],
		}
		_, err := params.VerifiedChains[0][0].Verify(opts)
		return &advancedtls.VerificationResults{}, err
	},
```
This verification passes now.

Could you remove port from ServerName so it works by default for CertAndHostVerification?

**Comment by jiangtaoli2016** [comment]
@ZhenLian Please take a look

**Comment by ZhenLian** [comment]
Yes, this seems a bug in code. I will work on a fix for this. @godfryd Thank you for pointing it out!

**Comment by ZhenLian** [comment]
Now the fix is merged. @godfryd Can you please point your code to the master branch and verify if it works? I will close this issue for now but feel free to reopen it if you find anything wrong. Thanks!

**Comment by godfryd** [comment]
Hello,

I checked. It works now.
Thanks a lot for your help.

Regards,
Michał Nowikowski

**Comment by ZhenLian** [comment]
Great, thanks for confirming!
