### ISSUE TITLE
Make "golint" Applied to Sub-modules as well

### ISSUE THREAD

**Issue by ZhenLian** [grpc/grpc-go#4075]
According to https://github.com/grpc/grpc-go/pull/4018#discussion_r535428151, golint might not work on the sub-modules. This is to verify whether it works, and if not, update `vet.sh` to make it works on sub-modules also.

**Comment by dfawley** [comment]
Did you mean for #4018 to close this?

**Comment by ZhenLian** [comment]
> Did you mean for #4018 to close this?

Ah no, I didn't notice this was closed. Thanks for reopening it!

**Comment by ZhenLian** [comment]
Fixed by https://github.com/grpc/grpc-go/pull/4302
