### ISSUE TITLE
There is an error on the golang http handshake, when the grpc url as 'grpc://ip:port/path' and no http_proxy in the System environment variables

### ISSUE THREAD

**Issue by stonexli** [grpc/grpc-go#4078]
There is an error on the golang http handshake, when the grpc url as 'grpc://ip:port/path' and no http_proxy in the System environment variables. In the version as '1.23.x'，I fix the error on the code in 'proxy.go', as follow:
```
func newProxyDialer(dialer func(context.Context, string) (net.Conn, error)) func(context.Context, string) (net.Conn, error) {
  return func(ctx context.Context, addr string) (conn net.Conn, err error) {
    var newAddr string
    proxyURL, err := mapAddress(ctx, addr)
    if err != nil {
      if err != errDisabled {
        return nil, err
      }
      newAddr = addr
      //delete the path from the 'addr'
      dot := strings.Index(newAddr, "/")
      if dot > 0 {
        newAddr = newAddr[0 : dot]
      }
  ... ... 
```

when I learn the version as '1.34.x', I find than the 'proxy.go' has been moved to 'internal/transport/proxy.go'. But there is the error in the 'func proxyDial' impl. So I submit it. 
Thanks.

**Comment by easwars** [comment]
Could you please provide more information on what exactly you were trying and what you expected to see.
