### ISSUE TITLE
does grpc go support reconnection via retry throttler?

### ISSUE THREAD

**Issue by SamYuan1990** [grpc/grpc-go#4085]
https://github.com/grpc/grpc-go/blob/2cf12a82ed4381ce0b0f7d487ee2eca772ee18e3/clientconn.go#L145

Hi,

for my understanding, if I want my grpc connection auto retry for N times before throws a lost connection exception, whenever init connection phase or after connection set up.
I just config with this retry throttler with a number N?

thanks and regards
Sam

**Comment by easwars** [comment]
You can configure retries by setting an appropriate `RetryPolicy` in the `ServiceConfig` for your service.
See: https://github.com/grpc/grpc-proto/blob/master/grpc/service_config/service_config.proto#L130-L151

**Comment by SamYuan1990** [comment]
I am developing a performance testing tool which targeting a grpc server. And when I am going to start M connections at a short time, some connections fails. So I want to have a retry N times. To make all M connections creation succeeded.
