### ISSUE TITLE
advancedtls: test fails on IPv6 only environment

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#4095]
The following test is failing in google3: https://github.com/grpc/grpc-go/blob/master/security/advancedtls/advancedtls_test.go#L406-L420

The reason is that the cert has a SANs only for localhost and `127.0.0.1`, it probably needs an entry for `::1` so that it can succeed on IPv6 only environments.
https://github.com/grpc/grpc-go/blob/master/security/advancedtls/testdata/server_cert_localhost_1.pem#L62

**Comment by menghanl** [comment]
Note that instead of adding `::1` to SANs, I think it's better to use a real name, instead of IPs.

**Comment by easwars** [comment]
@ZhenLian 
I'm bumping this up to P1 because this needs to be fixed before our next import into google3. We pushed the current import by deleting this test in google3.
Thanks.

**Comment by ZhenLian** [comment]
Thanks for bringing up the issue and for the inputs! I will work on a fix right now.
