### ISSUE TITLE
java allows to set an authority CallOption, but Golang does not

### ISSUE THREAD

**Issue by Ivansamara109** [grpc/grpc-go#4096]
Hello.

We use gRPC in a service mesh in which our applications connect insecurely to a sidecar on the local network and the sidecar does the work of initiating TLS to backends and load balancing/routing based on the :authority pseudo header.

We use this [java grpc implementation feature](https://github.com/grpc/grpc-java/blob/4be68f32873655fd4fc243eaa636549f4278fb62/api/src/main/java/io/grpc/CallOptions.java#L90) in our java application. It allows us to re-use a single Channel for multiple services, even if those services are hosted on different domain names.

Is it possible to add the same feature for go implementation of gRPC?

**Comment by easwars** [comment]
This has been discussed earlier. Please see: https://github.com/grpc/grpc-go/issues/3444.

Closing this a duplicate.
