### ISSUE TITLE
transport: tests take too long to complete

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#4097]
Transport tests seem to take between 160-180s which is the biggest contributor to overall test time. 

We should try and see if this can be reduced.

**Comment by arvindbr8** [comment]
There was another issue tacking this https://github.com/grpc/grpc-go/issues/6043 and we should shaved a good amount of time off with this PR https://github.com/grpc/grpc-go/pull/6088. there are more PRs in flight addressing this issue, but this issue need not be kept open
