### ISSUE TITLE
Server side Per-RPC TLS access

### ISSUE THREAD

**Issue by ivanjaros** [grpc/grpc-go#4107]
I have a server which should be accessible only with configured list of tls certificates. This can be done via `grpc.Creds()` or by simply wrapping the net.Listener with tls.Config-configured tls connection. What I need now is to be able to allow only certain RPCs per individual certificate. In other words some certificates/clients will have only read access and some will have read-write access.

I am not seeing any way to add this on the server side, even though the client has per-rpc option. What am I missing here? Maybe there is access to this info on the server side through the context via interceptor, like grpc metadata, for example, but for auth?

**Comment by jiangtaoli2016** [comment]
@ZhenLian

**Comment by ZhenLian** [comment]
AFAIK, the way to do per-rpc authentication is through [grpc.WithPerRPCCredentials](https://godoc.org/google.golang.org/grpc#WithPerRPCCredentials), as stated [here](https://github.com/grpc/grpc-go/blob/23ef1279c18467fa15375bb307a9de513d4f57bd/Documentation/grpc-auth-support.md#oauth2). Assign to @dfawley in case I missed anything.

**Comment by ivanjaros** [comment]
grpc.WithPerRPCCredentials is dial option, not server option.

**Comment by ivanjaros** [comment]
i think what i was looking for was the `peer.PeerInfo.AuthInfo`
