### ISSUE TITLE
xds: client should notify the callback of the error if a response is NACK'ed

### ISSUE THREAD

**Issue by menghanl** [grpc/grpc-go#4121]
This is similar as service config error handling.
The resolver can decide what to do with this error.
If there was a good response, it can keep using it. Otherwise, it should start to fail RPCs.

**Comment by menghanl** [comment]
Currently, resolver doesn't know of the NACK'ed responses. So if there's no good response, the resolver will eventually see a timeout error, and then RPCs will fail.

**Comment by easwars** [comment]
This does seem like a big enough change that cannot be done as part of the fixit.

@menghanl : Is this something that you had discussed with C/Java? Do you know what their current behavior is and if they plan on supporting something like this?

Also, given that we have added CSDS support, and that information about errors are maintained, is this something that we still want to do?
