### ISSUE TITLE
xds: allow usage without specific import of xds package

### ISSUE THREAD

**Issue by howardjohn** [grpc/grpc-go#4123]
One of the key selling points of a service mesh is that it can be dropped in place into existing (perhaps legacy) deployments with zero changes to the application.

With XDS, gRPC is extremely closing to matching this to some extent. A user could, for example, just swap out the scheme in a config file to `xds` and set up a bootstrap file and automatically get value added. However, the import of the xds package requirement (https://github.com/grpc/grpc-go/tree/master/examples/features/xds#the-client) breaks this, as a user needs to modify their application.

It is admittedly super easy to add a single import - the real issue is using off-the-shelf or legacy software that cannot be changed.

I am assuming this is a tradeoff to avoid bloating binaries due to XDS imports, by making the massive go-control-plane import opt-in.

With my limited knowledge of the problem, I could see a few ways this plays out:
1) The import requirement is dropped.
2) OSS apps that use gRPC clients get PRs to import the xds package, and maintainers of these packages accept the PRs and release new versions with the import.
3) gRPC+XDS adoption is impaired, as users will either not be able to use it with off the shelf packages or need to maintain forks to add a single import.

Some alternatives to just importing it automatically would be to make it opt-out (I think the only way to do this is via build tags, which isn't a great solution) or to find some way to make the XDS imports have less of an impact on the resulting binary size (or otherwise mitigate whatever is preventing this).

**Comment by menghanl** [comment]
Binary size is one important reason we don't import xds package by default.

Another big reason is, this import will cause a circular dependency: `grpc -> xds -> generated xds proto packages -> grpc`. The `generated xds proto packages -> grpc` dependency is because the generated packages also define gRPC services.

**Comment by howardjohn** [comment]
I personally think this is a *massive* barrier to entry that may warrant a closer look, even if its not trivial to implement. From my experience with Istio, we required users to declare the protocol of their applications (change 1 line of yaml) to get the full experience. This was seen as a major blocker to adoption.

Here, its far worse - you need to rebuild all of your applications (may not even be possible if its a third party application). I fear this will block adoption quite a bit.

**Comment by dfawley** [comment]
The requirement to `import "xds"` was a conscious decision, as @menghanl mentioned [above](https://github.com/grpc/grpc-go/issues/4123#issuecomment-756462270).  Some users will be unhappy if we bloat their binary size (I'm not sure how much this is right now), and the circular dependency problem would be quite difficult to workaround, since the protos we use for xds that depend on grpc are owned by another project.  I have an idea for how to change the codegen such that it doesn't depend on the base grpc package, but: 1. it wouldn't be compatible with current grpc versions, 2. it would require them to regenerate all their protos, and 3. there are still some details I am not sure how to solve without spending more time on it.

What are your thoughts @srini100?

**Comment by srini100** [comment]
I am not sure how big of a barrier this is. Applications anyway need to be modified to take channel scheme (xds or DNS) as input  on a per-destination basis. A client could be connecting to multiple services, some via xDS and some via DNS. When mTLS support comes out, you also have to specify the type of channel creds (xds, tls etc.). And this is just on the client side. Most applications in a mesh are also servers that also need to be modified to take the type of the gRPC server as input. 

That said, this is definitely worth keeping on the back burner and revisit this if see more demand. Meanwhile, it will be useful to publish something on how to write a gRPC application to make it " service mesh drop-in ready".

**Comment by howardjohn** [comment]
> Applications anyway need to be modified to take channel scheme (xds or DNS) as input on a per-destination basis.

My (perhaps incorrect) assumption is that a large portion of applications are not hard coding their destination and taking it in as a configuration, so the changes required would be tweaking that which is generally lightweight. I agree if the address is embedded in the binary they would need to rebuild anyways.

Certainly any third party software, which I imagine is quite a bit harder to rebuild yourself (required source access and maintaining a fork) would be likely to be configurable in this way

> mtls

I had assumed that this was configured via xds as it is in Envoy? If this is not how it's being designed I would love to take a look at the design to learn more. I looked around https://github.com/grpc/proposal/ and didn't see anything but may have missed it/looked in the wrong place.

> gRPC server

That's a great point, I have only been looking into the client side. Is there any info on how to configure the server side (currently or planned)

Thanks for all your feedback

**Comment by srini100** [comment]
> I had assumed that this was configured via xds as it is in Envoy?

In gRPC, xDS control plane provided security is used only if user explicitly specifies "xds creds" in the channel or the server. This gives the flexibility to use xDS for service discovery and traffic management while using a different security framework. The mTLS gRFC (in progress) is here: https://github.com/grpc/proposal/pull/184

The server side xds gRFC (in progress) is here: https://github.com/grpc/proposal/pull/214

**Comment by howardjohn** [comment]
Also one thing to note about requiring to switch `dns:///` to `xds:///`. grpc offers the ability to override the default via `resolver.SetDefaultScheme()`, which can be utilized.

Stepping back a bit, this is how I envision a completely frictionless rollout of XDS to work (in Kubernetes):

* User sets up an XDS control plane + mutating webhook. If they are already using a service mesh they probably already have it.
* The webhook automatically injects either all pods, or all pods with some label opting in with env vars required to get started, like `GRPC_XDS_BOOTSTRAP` and whatever else is needed, that point to the XDS control plane

So the two gaps here are the required import discussed above, and the scheme. Possibilities to remove the import requirement are already discussed here. One possibility for the resolver default scheme is to also allow the default to be set by an environment variable, allowing us to automatically set it for a user.

With both of those done, from an application developers perspective they could have XDS enabled automatically and get all of the additional benefits for "free". I am not necessarily suggesting we do those things above, but I think that its feasible to have a "zero friction" adoption if we make that a goal, and its probably important to decide if that is a goal or not before we go too far down the API design path of adding more required code changes to adopt XDS.

**Comment by easwars** [comment]
It doesn't look like the team has the cycles to work on this. And given that it was a conscious decision to make the import a requirement, can we close this?
@dfawley @menghanl @srini100

**Comment by srini100** [comment]
I am fine to close this for now.
