### ISSUE TITLE
xds: need a way to configure the bootstrap file from within code

### ISSUE THREAD

**Issue by howardjohn** [grpc/grpc-go#4124]
In gRPC 1.33, it was possible to configure the bootstrap env var from within the code with os.Setenv. This wasn't ideal, but at least it worked.

In gRPC 1.34, this is no longer possible, as the env var is not lazy loaded (https://github.com/grpc/grpc-go/blame/master/xds/internal/env/env.go#L39), so it needs to be configured *before* startup.

Among other use cases, this makes it extremely challenging to actually test, which is a hard blocker on us updating to 1.34

**Comment by menghanl** [comment]
How are you setting this env variable within code? Do you make sure it's set before you call any gRPC functions? And do you change its value between tests?

**Comment by howardjohn** [comment]
We use os.SetEnv. In order for it to work in 1.34, we would need to somehow set that before the import is loaded, which I don't think is possible. And we do want to change it between tests to test different bootstrap settings, so that is also not possible currently.

**Comment by menghanl** [comment]
Two options:
1. Revert back to 1.33. The env variable will be read when the xds client is created. And since now the xds client is shared by all gRPC clients in the same binary, the env variable will be read only once.
2. Add a `xdstesting` package, with exported functions to set the value.

**Comment by easwars** [comment]
@dfawley :
Could you explain how we would support "injecting the bootstrap into the resolver": https://github.com/grpc/grpc-java/issues/7819#issuecomment-811452777

**Comment by costinm** [comment]
This is not only needed for tests. Istio bootstrap has a pretty complex structure that is extracted from env ( like pod labels, etc). 
It is possible to do it with a helper - but it is simpler for the user to use a library that constructs the env.

**Comment by dfawley** [comment]
> Could you explain how we would support "injecting the bootstrap into the resolver": grpc/grpc-java#7819 (comment)

Did we talk about this offline?  I seem to remember discussing.  Anyway, it sounds like the concern here is about production code, not testing, so that would not apply here.

**Comment by dfawley** [comment]
I don't really understand the motivation here, if it's about lazy loading the environment variable.  If you aren't planning on changing it during runtime, then set it before you launch the binary.  That's SOP for environment variables as far as I'm aware, anyway.

If it's for testing and you need to inject a different config into each ClientConn, that is something we will need to add support for.  Basically the idea there is we would provide an "xds resolver builder builder" (for testing purposes only) that would store the xds config inside the resolver builder, which could then be passed to `grpc.Dial` via `grpc.WithResolvers`.
