### ISSUE TITLE
xds: support YAML GRPC_XDS_BOOTSTRAP file config

### ISSUE THREAD

**Issue by howardjohn** [grpc/grpc-go#4126]
It would be nice if GRPC_XDS_BOOTSTRAP was parsed as YAML. Since its a superset of json, I think this may be possible by just swapping out `json.Unmarshal` with `yaml.Unmarshal`.

The benefit is that in some environments its easier to deal with YAML, and it mirrors existing Envoy expectations of being able to use JSON or YAML

**Comment by dfawley** [comment]
This feature request was discussed internally a few weeks ago, and I believe we decided it was infeasible to implement in all gRPC languages.

cc @srini100, @markdroth

**Comment by markdroth** [comment]
Yes, that's correct.  gRPC has standardized on JSON; we don't want to also have to support YAML.

**Comment by dfawley** [comment]
For something like this, we wouldn't want to support it in one language and not have it in all of the major languages.  So, closing.

**Comment by howardjohn** [comment]
Makes sense, thanks.
