### ISSUE TITLE
xds: support env variable GRPC_XDS_BOOTSTRAP_CONFIG for bootstrap config content

### ISSUE THREAD

**Issue by howardjohn** [grpc/grpc-go#4127]
Currently, GRPC_XDS_BOOTSTRAP points to a file. In some cases, it much easier to stick the entire configuration in an env var than configure both an env var and a file. For example, with docker, its a simple `--env` for the former, and both `--env` and `--volume` (as well as maintaining the folder, potentially many bootstraps for many containers).

Some other motivations for this can be found in https://12factor.net/config.

**Comment by howardjohn** [comment]
Somewhat related to https://github.com/grpc/grpc-go/issues/4124

**Comment by srini100** [comment]
Thanks for the suggestion. Also related to https://github.com/grpc/grpc-java/issues/7605#issuecomment-724433125.

We'll add this in all supports languages.
