### ISSUE TITLE
healthpb.HealthCheckResponse only provides the status value. 

### ISSUE THREAD

**Issue by fananchong** [grpc/grpc-go#4132]
healthpb.HealthCheckResponse only provides the status value. 

The lack of some custom information from the server can be passed to the client through healthpb.HealthCheckResponse for load balancing.

For example, load balancing based on weight

**Comment by dfawley** [comment]
Health checking is a gRPC feature, not limited to grpc-go.  Please file this issue in [grpc/grpc](http://github.com/grpc/grpc) instead, thank you!
