### ISSUE TITLE
xds: Wrong type for http_connection_manager in v3 resource

### ISSUE THREAD

**Issue by pradeepmvn** [grpc/grpc-go#4136]
### What version of gRPC are you using?
1.34.0
### What version of Go are you using (`go version`)?
1.15.3
### What operating system (Linux, Windows, …) and version?
Linux

Minor issue with http_connection_manager @ https://github.com/grpc/grpc-go/blob/f4a20d2f414ffe9ca43416e6980831bde3140404/xds/internal/version/version.go#L48
This is causing validation failures and nacks on the xds response for envoy v3 resources. This should instead be..
```
V3HTTPConnManagerURL      = "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
```
Would be happy to submit a PR if it helps.. https://github.com/pradeepmvn/grpc-go/blob/90d23d53d5be6785267882cbe283461c27df071e/xds/internal/version/version.go#L48

**Comment by menghanl** [comment]
Thanks for the issue. And yes, please send a PR.

We build `Any` manually in the test. And I don't remember the reason why.
https://github.com/grpc/grpc-go/blob/f4a20d2f414ffe9ca43416e6980831bde3140404/xds/internal/client/client_lds_test.go#L94-L97

Can you try changing this to a `MarshalAny` and see if it would catch this bug?

**Comment by pradeepmvn** [comment]
Not sure if i understood it, This wouldn't cause an issue in the unit tests as both (creation and comparison) use same constant. I found this issue while working on a v3 xds-controller . The control plane was sending a different type and grpc-go was failing while validating type with its constants. 
Updating the test to this below caused a failure though..

```
ApiListener: &anypb.Any{
	TypeUrl: "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
	Value:   mcm,
},
```
I can update in the PR #4137  if needed

**Comment by pradeepmvn** [comment]
Thanks for accepting PR.Fixed.
