### ISSUE TITLE
How to acquire an older version of `protoc-gen-go-grpc`?

### ISSUE THREAD

**Issue by cannium** [grpc/grpc-go#4139]
For compatibility reasons, I need to generate an older pb.go file other than `grpc.SupportPackageIsVersion7`. But I cannot figure out how to build the binary, any references?

**Comment by dfawley** [comment]
The commit before we updated to v7 was 410880dd7d91952bbc9dfb756f3e03a90c87f8ed.  This was never released in this repo.  If you want a released version, you will need https://github.com/golang/protobuf/tree/master/protoc-gen-go; not protoc-gen-go-grpc.  You should be able to find pre-built binaries on their "Releases" tab.
