### ISSUE TITLE
provide `Redirect` method for serverStream

### ISSUE THREAD

**Issue by fumeboy** [grpc/grpc-go#4146]
forward messages from one serverStream to another conn. 

It is designed for the sidecar in the service mesh architecture

we can make a grpc proxy as simple as  this:

```go
func handler(_ interface{}, StreamAnP grpc.ServerStream) (err error) {
	fullMethodName, ok := grpc.MethodFromServerStream(StreamAnP)
	if !ok {
		return status.Errorf(codes.Internal, "failed to get method from server stream")
	}
	
	endpoint, err := director(fullMethodName)
	if err != nil {
		return err
	}
	
	var conn *grpc.ClientConn
	if conn,ok = conns[endpoint]; !ok { 
		conn, err = grpc.DialContext(globalContext, endpoint, grpc.WithInsecure(), grpc.WithTimeout(10*time.Millisecond))
		if err != nil {
			return err
		}
		conns[endpoint] = conn
	}
	
	err = StreamAnP.(grpc.ServerStreamRedirect).Redirect(conn, fullMethodName)
	if err != nil {
		panic(err)
	}
	return nil
}
```

**Comment by dfawley** [comment]
Please provide more context:

1. What problem are you trying to solve?
2. What are you proposing?
3. What are the alternatives?
4. Why is your proposal better than the alternatives?

From what I can tell, this can be achieved just as easily without any changes to grpc-go itself.  Also, I don't believe this is a feature likely to be used by many people.  If that's true, why not put this kind of functionality in a separate project (e.g. we could explore a repo in [grpc-ecosystem](https://github.com/grpc-ecosystem), or we could link to your repo from [grpc-community](https://github.com/grpc/grpc-community))
