### ISSUE TITLE
Is there any way to force a new balancer picker to be created when new addresses are resolved?

### ISSUE THREAD

**Issue by richardartoul** [grpc/grpc-go#4147]
I'm trying to upgrade from `v1.19.1` to `v.1.27.1` and I'm running into a nasty issue I'm not sure how to solve. My service runs in k8s and so I implemented a custom, polling DNS resolver that polls a DNS target every minute and calls `UpdateState` on the `resolver.ClientConn` (I've modified my implementation to use the new APIs instead of `resolver.NewAddress`).

Polling DNS and having that updated in the load balancing strategy is really important because our service scales itself up and down automatically based on load. When I tested the upgrade I found that the load balancer was no longer correctly updated on scale up. In other words if I had 10 pods and it scaled to 20, the old version would handle this properly whereas the new version will keep only routing to the same 10 pods.

I've been digging through the code and the source of my problem appears to be in `base/balancer.go`:

The implementation of `UpdateClientConnState` will create new sub-connections, but not construct a new picker, even if new addresses have appeared. I also can't "force" a new picker to be created by "faking" an error from the DNS polling resolver because `ResolverError()` will only create a new picker if at least one of its connections experiences a transient failure:

```golang
func (b *baseBalancer) ResolverError(err error) {
	b.resolverErr = err
	if len(b.subConns) == 0 {
		b.state = connectivity.TransientFailure
	}
	if b.state != connectivity.TransientFailure {
		// The picker will not change since the balancer does not currently
		// report an error.
		return
	}
	b.regeneratePicker()
	if b.picker != nil {
		b.cc.UpdateBalancerState(b.state, b.picker)
	} else {
		b.cc.UpdateState(balancer.State{
			ConnectivityState: b.state,
			Picker:            b.v2Picker,
		})
	}
}
```

Do you have any suggestions?

**Comment by dfawley** [comment]
> The implementation of UpdateClientConnState will create new sub-connections, but not construct a new picker

This is by design, but a new picker *will* eventually be created when the subconns are reported as ready:

https://github.com/grpc/grpc-go/blob/4cf4a98505bcdfb27ea2a5427b6e5a2d143dd060/balancer/base/balancer.go#L228-L237

**Comment by richardartoul** [comment]
Does that mean that the expected behavior is that when a new address is reported a new picker should be created as soon as the connection is established? I believe thats not happening in my case, but if thats what the code you linked above does I will dig deeper to reproduce whats going on

**Comment by dfawley** [comment]
Yes, the flow is:

- Name resolver detects new addresses; calls `ClientConn.UpdateState`
- Parent `ClientConn`/channel calls the LB policy's `UpdateClientConnState` containing this `resolver.State`.
- LB policy instructs `ClientConn`/channel to create new connections to new addresses by calling `ClientConn.NewSubConn`.
- Parent `ClientConn`/channel creates `SubConn`s/subchannels and when they make state transitions, calls `UpdateSubConnState`
- LB policy generates a new picker and calls `ClientConn.UpdateState` with the new picker.

Somewhere along that path, something must be going wrong.  If you turn on logging, you should see messages for many of these events.

**Comment by richardartoul** [comment]
🤦 Somewhere during our refactor `time.Ticker` got replaced with `time.Timer` which of course broke everything. I fixed this on our end, sorry to waste your time, but thank you for explaining how it works, once I understood that it was much easier to narrow down the bug to our own code.
