### ISSUE TITLE
Release the v1.0.2 proto-gen-go

### ISSUE THREAD

**Issue by resec** [grpc/grpc-go#4151]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?

To include change of #4035 

### Proposed Solution

Release v1.0.2

### Alternatives Considered

Build the proto-gen-go myself from master, which can be broken because master may contains expected change.

**Comment by dfawley** [comment]
Released as v1.1.0: https://github.com/grpc/grpc-go/releases/tag/cmd%2Fprotoc-gen-go-grpc%2Fv1.1.0
