### ISSUE TITLE
Wrap last connection error

### ISSUE THREAD

**Issue by avalchev94** [grpc/grpc-go#4155]
Hi all! First, I want to thank you for listening to the community and adding `WithReturnConnectionError`, it's really useful! 
I have an idea how we can make it even better. Currently, the connection error's type is lost and only the error's text is used:

```
	conn, err = nil, fmt.Errorf("%v: %v", ctx.Err(), err)
```

At the end we have an error from type `errors.errorString` and the only way to check the underlying error is string comparison, which is unreliable.

### Use case(s) - what problem will this feature solve?
- checking error type
- getting additional details from the custom error type 

### Proposed Solution
1. Easiest solution is using the `%w` modifier, which wraps the error. Later, that error can be unwrapped with `errors.Unwrap`:
```
	conn, err = nil, fmt.Errorf("%v: %w", ctx.Err(), err)
```
However, from what I see in go.mod, the minimum supported go version is 1.11 and that's a problem, because above features were added in 1.13

2. Creating custom error type which implements Unwrap interface from errors package. In that way:
- if user is using version >=1.13, `errors.Unwrap` can be used directly;
- if user is using version < 1.13, anonymous Unwrap interface can be defined and used for obtaining the underlying error;
```
 type wrapError struct {
     msg string
     err error
}

func (e *wrapError) Unwrap() error {
   return e.msg
}

// func (e *wrapError) Error() string
```
Sorry for the pseudo code, if that idea is approved, I can do a better version.

**Comment by dfawley** [comment]
This is fixed.
