### ISSUE TITLE
Able to add values lower than min limit in histogram stats and wrong printing of upper bound of last bucket.

### ISSUE THREAD

**Issue by msinghal34** [grpc/grpc-go#4158]
**Expected Behavior:**
1. On printing histogram, the upper bound of last bucket should have been:
Bucket i (i>=1) contains [min + n * m^(i-1), min + n * m^i), where m = 1+GrowthFactor. 
According to the comment [here](https://github.com/grpc/grpc-go/blob/master/benchmark/stats/histogram.go#L55) and the implementation of Add function [here](https://github.com/grpc/grpc-go/blob/master/benchmark/stats/histogram.go#L199)
2. While trying to add a value lower than opts.MinValue, it should have returned an error.

**Actual Behavior:**
1. I was seeing "inf" getting printed because of [this](https://github.com/grpc/grpc-go/blob/master/benchmark/stats/histogram.go#L134) line of code.
2. There is no check for this, thus allowing to add values lower than the minimum allowed for histogram.

**Comment by easwars** [comment]
@msinghal34 
Unfortunately, this is not something that the team has cycles to fix. Please let us know if you are interested in sending a PR to fix this and we would be happy to review it.
Thanks.

**Comment by msinghal34** [comment]
@easwars
Can I send a PR this weekend?

**Comment by easwars** [comment]
> @easwars
> Can I send a PR this weekend?

Sure. Thanks.

**Comment by msinghal34** [comment]
@easwars Can you please take a look at #4408
