### ISSUE TITLE
How can the server detect that the client has stopped listening to a specific stream?

### ISSUE THREAD

**Issue by delmotteo** [grpc/grpc-go#4159]
I'm implementing (in go) the client and server code for a gRPC service defined in a proto file.
The proto file is a given and I can't modify it.
One of the rpc has the following structure:

    rpc someRPC(request_message) returns (stream response_message) {}

So the client sends 1 message and receives multiple responses.
It is requested to reduce as much as possible the number of http2 connections handled by the server.
However, any given client may need to send several request messages.
So the client creates several streams within the same http2 connection.

Sometimes, a request need to be changed.
Since the specification of the rpc does not allow to send another request in the same stream, what I did was to create a new stream and send the new request in it. The thread that is receiving the responses to the original request is stopped on the client side.
The problem I'm having is that the server does not seem to notice that the client is not listening anymore. It keeps on sending the responses even though nobody is listening on the other end.

This is a real issue because the http2 connection may be up for days, weeks or even months.
At any given time I normally have dozens of active client streams listening to what the server is sending.
But since the client sometimes shuts down some streams and replace them with others, the number of streams handled by the server keeps growing.

My question is: how can the server thread be stopped when the client stops listening to the associated stream?
I have tried to use ctx.Done() but that does not work because it only detects when the whole http2 connection goes down, not when an individual stream goes down.
Any help would be rally appreciated! Thank you!

Here's a simplified version of my code to illustrate the issue I have:

SERVER SIDE:

func main() {

	// Create the listener
	lis, err := net.Listen("tcp", address)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}

	// Create the gRPC server
	opts, err := getServerOptions()
	if err != nil {
		log.Fatalf("Failed to get the gRPC server options: %v", err)
	}
	grpcServer := grpc.NewServer(opts...)

	// Register the service in the gRPC server and start to serve
	pb.RegisterSomeService(grpcServer, &Server{})
	if err := grpcServer.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}

func (s *server) SomeRPC(request *pb.SomeRequest, stream pb.SomeServiceServer) error {

	// Get the context
	ctx := stream.Context()

	// Build and send the responses when appropriate
	var secs int64 = 0
	for {

		select {
		case <-ctx.Done():
			log.Printf("The http2 connection was closed\n")
			return nil
		default:
			// Generate a response
			...

			// Send the response
			if err := stream.Send(response); err != nil {
				return err
			}

			// stream.Send() does not give an error even if the client is not listening anymore
			// HOW CAN WE DETECT THE CLIENT IS NOT LISTENING ANYMORE ON THE STREAM AND RETURN????
		}
	}
}

CLIENT SIDE

func main() {

	// Connect to the gRPC server
	opts, err := getDialOption()
	if err != nil {
		log.Fatalf("failed to get the dial options: %v", err)
	}
	conn, err := grpc.Dial(address, opts...)
	if err != nil {
		log.Fatalf("fail to dial: %v", err)
	}
	defer conn.Close()

	// Create the client(s)
	var wg sync.WaitGroup
	clients := make([]pb.SomeServiceClient, clientCount)
	for i := 0; i < clientCount; i++ {

		clients[i] = pb.NewSomeServiceClient(conn)
		go launchClient(clients[i], i, &wg)
		wg.Add(1)
	}
	wg.Wait()
}

func launchClient(client pb.SomeServiceClient, clientIdx int, wg *sync.WaitGroup) {

	defer wg.Done()

	// Generate the requests to be sent by this client
	requests, err := GetRequests(clientIdx)
	if err != nil {
		log.Fatalf("Failed to create the requests: %v\n", err)
	}

	// Loop thru the generated requests
	requestCount := len(requests)
	for i := 0; i < requestCount; i++ {

		// Send a single request at a time
		execSomeRPC(client, clientIdx, requests[i])
	}
}

func execSomeRPC(client pb.SomeServiceClient, clientIdx int, request *pb.SomeRequest) {

	// Create the stream and send the request
	ctx := context.Background()
	stream, err := client.someRPC(ctx, request)
	if err != nil {
		log.Fatalf("%v.Subscribe(_) = _, %v\n", client, err)
	}
	stream.CloseSend() // We can only send one request so let's close the stream in that direction

	// Create the channel to make current thread wait until the response thread is shut down
	waitc := make(chan struct{})

	// Launch the response thread to collect the responses
	go func() {
		for {
			// Perform some logic to know when the current stream needs to be torn down
			if some criteria is met {
				// Close the channel to let the main thread exit the function
				close(waitc)
				return // AT THIS POINT THE CLIENT STOPS LISTENING ON THIS STREAM => THE SERVER SHOULD STOP SENDING DATA
			}

			// Get the response
			in, err := stream.Recv()
			if err == io.EOF {
				close(waitc)
				return
			}
			if err != nil {
				log.Fatalf("Failed to receive a Subscribe response : %v\n", err)
			}

			// Do some stuff with the response
			log.Printf("Client #%d received response: %v\n", idx+1, in)
		}
	}()

	// Wait for the channel to be closed by the response thread and then exit
	<-waitc
}

**Comment by delmotteo** [comment]
Note that if I could change the proto file, I could solve this problem by changing the rpc allowing multiple requests, as shown below:
rpc someRPC(stream request_message) returns (stream response_message) {}

In that case, the server would be listening to potential new requests using stream.Recv().
When the client exits the function, the stream.Recv() would fail on the server side.
But since I can't change the proto file, I need a solution for the original rpc:

rpc someRPC(request_message) returns (stream response_message) {}

**Comment by dfawley** [comment]
When the client is done with a stream, it should cancel the context used to create the stream.  This will eventually make the server return an error from its `stream.Send`:

```go
   ctx, cancel := context.WithCancel(context.Background())
   defer cancel()
   stream, err := client.someRPC(ctx, request)
```

Also:

```go
	clients[i] = pb.NewSomeServiceClient(conn)
```

This isn't doing what you think it is.  There's no need to have multiple client wrappers of a single `ClientConn`.  Feel free to create one and pass it around everywhere.

**Comment by delmotteo** [comment]
Thank you Doug! It is indeed working!!
