### ISSUE TITLE
goroutine leak when using context.Background() during Table.ReadRows

### ISSUE THREAD

**Issue by smreed** [grpc/grpc-go#416]
Commit afca514667a08f9be29e0e2f4640576a0a8972e4 adds a goroutine for every new client stream that waits on the given `context.Context`'s `Done` channel.

`context.Background()` returns a `Context` which returns `nil`, and receives from a nil channel block forever.

**Comment by smreed** [comment]
This is using go 1.5.1 on linux/amd-64 fwiw.

**Comment by iamqizhao** [comment]
not really. That goroutine works on the ctx from
https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L222
which is not context.Background(). Let me know if I missed anything.

**Comment by smreed** [comment]
You're right, and I also have filed this issue w/ the wrong project. Got the grpc and cloud/bigtable stuff mixed up. Closing this issue.
