### ISSUE TITLE
How to get roundtrip time ?

### ISSUE THREAD

**Issue by cuongngo-orientsoftware** [grpc/grpc-go#4176]
There are any way to get roundtrip time integrated in library without canculate manually ?

Update:
Currently, I test response time of function as:
`startTime := time.Now()`
`r, err := c.Get(ctx, &pb.ProtoRequest{Key: &id}, grpc.MaxCallRecvMsgSize(1024 * 1024 * 100))`
`endTime := time.Now()`
`endTime.Sub(startTime)`

Have any way to get response time same with Rest API ?
`e.GET("/api").Expect().RoundTripTime()`

**Comment by easwars** [comment]
We do have a BDP estimator [here](https://github.com/grpc/grpc-go/blob/master/internal/transport/bdp_estimator.go). But this functionality is not exposed to the users.

Could you be more specific about what you are trying to do? Thanks.

**Comment by cuongngo-orientsoftware** [comment]
@easwars updated

**Comment by dfawley** [comment]
Sorry, this isn't something we support, and probably will not if it's something that is feasible to do outside the library as in your example code.  Another option, if you don't want to write this at every call site, would be to use an interceptor to calculate it.
