### ISSUE TITLE
Detect the authority header on the Server

### ISSUE THREAD

**Issue by hbagdi** [grpc/grpc-go#4179]
Hello there,
Thank you for this project. It has been very useful and is of high quality.
I'm working on a GRPC-based service whose business logic changes based on the authority header (or the SNI) of the request. 

I've two questions:
1. I want to be able to detect the the SNI/Authority header used by the client in my handler. How to access this field?
2. Is it possible to register multiple services of same type but on different hostnames?

I'm essentially trying to figure out how to do an in-process proxy based on the request content.
Any help would be appreciated!
Thanks again.

**Comment by menghanl** [comment]
Did you try reading the metadata? I believe authority should be available with key `:authority`.
Or you can just print the full metadata to see what's there.

You can dispatch the request to different handlers based on the authority if you want to do the proxy at gRPC level.

**Comment by hbagdi** [comment]
Let me try that.

What about the second part?
I want to change the Service being used for the response based on the `:authority` header. Is that even possible?

The other option would be to put that logic into the code of the Service itself but I'd like to avoid it if possible.

**Comment by menghanl** [comment]
> I want to change the Service being used for the response based on the :authority header. Is that even possible?

gRPC doesn't have support for that. You will need to do the dispatching yourself. You can do it in an interceptor.

Or, this might also help:
https://pkg.go.dev/google.golang.org/grpc#UnknownServiceHandler

**Comment by hbagdi** [comment]
Thanks!
