### ISSUE TITLE
Client authentication in gRPC

### ISSUE THREAD

**Issue by delmotteo** [grpc/grpc-go#4181]
I'm struggling with client authentication in gRPC.
I have developed a pair of client/server programs that is working just fine as long as I don't require client authentication.
On the client side, I manage to validate the server certificate .
But as soon as I try to validate the client certificate on the server side, the client hangs.
Not sure what I'm doing wrong.

On the server side, I have this (I have stripped the error handling to improve readability):

	// Create the listener
	lis, err := net.Listen("tcp", address)

	// Load the server key pair
	serverCrt, err := tls.LoadX509KeyPair("/path/to/server/certificate.crt", "/path/to/server/key.key")

	// Generate the TLS config struct
	tlsCfg := &tls.Config{
		ClientAuth:   tls.ClientAuthType(cfg.clientAuthType), // Valid values for cfg.clientAuthType are 0 to 4. 3 & 4 makes the client hangs
		Certificates: []tls.Certificate{serverCrt},
	}

	// Add the CA certificate in case the client must be authenticated
	if (tls.VerifyClientCertIfGiven == tlsCfg.ClientAuth) || (tls.RequireAndVerifyClientCert == tlsCfg.ClientAuth) {

		ca, err := ioutil.ReadFile("/path/to/ca/certificate.pem")
		caPool := x509.NewCertPool()
		ok := caPool.AppendCertsFromPEM(ca)
		tlsCfg.ClientCAs = caPool
	}

	// Create the gRPC server options with the security parameters
	opts := []grpc.ServerOption{grpc.Creds(credentials.NewTLS(tlsCfg))}

	// Create the gRPC server
	grpcServer := grpc.NewServer(opts...)

	// Register the service in the gRPC server
	pb.RegisterMyServiceServer(grpcServer, &server{})

	// Start to serve
	grpcServer.Serve(lis)

The server starts without problem and seems to be ready serving.

On the client side, I have the following:

	// Initialize dial options
	opts := []grpc.DialOption{grpc.WithBlock()}

	if cfg.Security.Enabled {

		// Load the client key pair
		clientCrt, err := tls.LoadX509KeyPair("/path/to/client/certificate.crt", "/path/to/client/key.key")
		tlsConfig := &tls.Config{Certificates: []tls.Certificate{clientCrt}}
		if cfg.ServerAuth {

			ca, err := ioutil.ReadFile(cfg.Security.CaCert)
			certPool := x509.NewCertPool()
			certPool.AppendCertsFromPEM(ca)
			tlsConfig.RootCAs = certPool

		} else {

			tlsConfig.InsecureSkipVerify = true
		}
		tlsConfig.ServerName = cfg.Host
		opts = append(opts, grpc.WithTransportCredentials(credentials.NewTLS(tlsConfig)))

	} else {
		opts = append(opts, grpc.WithInsecure())
	}

	// Connect to the gRPC server
	conn, err := grpc.Dial(address, opts...) // If servertries to validate certificate, client code hangs here
	defer conn.Close()

What am I doing wrong?

Thank you

**Comment by dfawley** [comment]
@ZhenLian maybe you can help with this?

**Comment by ZhenLian** [comment]
Hey Olivier, thanks for asking this question in gRPC community! I noticed that you were trying to enable mTLS on the client-server communication. Is it possible that your client cert stored in "/path/to/client/certificate.crt" is not trusted(signed) by the root ca cert stored in "/path/to/ca/certificate.pem"? You can check this by using the OpenSSL command, like [this](https://kb.wisc.edu/iam/page.php?id=4543).
If that's not the problem, you can open full logging mode by following this [instruction](https://github.com/grpc/grpc-go#how-to-turn-on-logging). That should provide you with more error information, and we can investigate from there. Hope that helps!

**Comment by delmotteo** [comment]
Hi @ZhenLian, thanks a lot for the instructions on how to increase the log level. It showed me that there was something wrong with my client certificate (the code was actually ok):
WARNING: 2021/02/03 10:25:16 [core] grpc: Server.Serve failed to complete security handshake from "127.0.0.1:58772": tls: failed to verify client certificate: x509: certificate specifies an incompatible key usage
I noticed that the client certificate was tagged as a "server" certificate. So recreated it with the correct properties and it worked just fine.
I think it might be a good idea to have the grpc.dial() to return an error in that case instead of hanging. What do you think?
Anyway, thank you very much for your help!

**Comment by dfawley** [comment]
`grpc.Dial` was mis-named from the start of the project.  In the other languages, clients start "idle", meaning they don't even attempt to connect until the first RPC comes in.  We do actively connect in Go, but we return before it finishes.

If you *really* want, you can use `WithBlock()` and `WithReturnConnectionError()` to see these errors.  But this is not similar to gRPC in other languages, so I don't really recommend it.

Generally what we expect would happen in all languages is:

1. `grpc.Dial`.
1. Send an RPC (without setting `WaitForReady(true)` as a `CallOption`).
1. See connection error information in the RPC status.

Unfortunately, we can't send detailed error information back from the server to the client when the TLS handshake fails, so I'm not sure what kind of info will show up in (3).  Right now, I think it will be very vague.  We hope to make a change soon to improve this (#4163), but I'm not sure how much detail will appear once it's done (it would depend on the TLS library which produces the error we'd forward).

**Comment by delmotteo** [comment]
Thank you for the clarifications @dfawley .
I will play around with the options you mention, even if you don't recommend it.
I'll figure out what's the best approach for my project.
And I'll be on the lookout for the enhancement you mentioned.
