### ISSUE TITLE
How to check deadlines in server middleware?

### ISSUE THREAD

**Issue by richzw** [grpc/grpc-go#4187]
Per [doc](https://grpc.io/blog/deadlines/#checking-deadlines), gRPC server could check deadlines as

```golang
if ctx.Err() == context.Canceled {
	return status.New(codes.Canceled, "Client cancelled, abandoning.")
}
```

And I try to handle it in hello example

```go
// SayHello implements helloworld.GreeterServer
func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
	log.Printf("Received: %v", in.GetName())

	select {
	case <- time.After(time.Second):
		// simulate some operation here
	case <- ctx.Done():
		if ctx.Err() == context.Canceled || ctx.Err() == context.DeadlineExceeded{
			return nil, status.New(codes.Canceled, "Client cancelled, abandoning.").Err()
		}
	}

	return &pb.HelloReply{Message: "Hello " + in.GetName()}, nil
}
```

With test client codes

```go
	ctx, cancel := context.WithTimeout(context.Background(), time.Millisecond*600)
	defer cancel()
	r, err := c.SayHello(ctx, &pb.HelloRequest{Name: name})
```

My question: how to check the deadline in middleware (or interceptor) in the gRPC server?

What I have tried

```go
type serverStats struct {}

func (h *serverStats) TagRPC(ctx context.Context, info *stats.RPCTagInfo) context.Context {
	fmt.Println("tag rpc")
	return ctx
}

func (h *serverStats) HandleRPC(ctx context.Context, s stats.RPCStats) {
	fmt.Println("handle rpc")
	if ctx.Err() == context.Canceled || ctx.Err() == context.DeadlineExceeded {
		fmt.Printf("HandleRPC: Client err %+v \n", ctx.Err())
	}
}

...

	s := grpc.NewServer(grpc.StatsHandler(&serverStats{}))
```

However, the `HandleRPC` is triggered multiple times, and it can NOT return error status codes.

**Comment by dfawley** [comment]
> My question: how to check the deadline in middleware (or interceptor) in the gRPC server?

Interceptors can return errors, so they can block on the context whenever blocking operations are necessary and return the appropriate error for the RPC.

`TagRPC`/`HandleRPC` don't allow returning an error, as you noticed.  In this case, it's probably best to not perform any blocking operations in stats handlers, and drop stats collection for RPCs if your processing queues are full.  Stats are typically considered non-essential, and shouldn't cause RPCs to fail.  If you absolutely needed these RPCs to fail, you could do so by having an interceptor that coordinated with the stats handlers to do so.

A minor thing: I would simplify some of your sample code as follows:

```go
	case <- ctx.Done():
		return nil, err // grpc will convert this to the appropriate status code
```
