### ISSUE TITLE
Stream context not done after client disconnect

### ISSUE THREAD

**Issue by pjvds** [grpc/grpc-go#419]
I'm receiving a stream request on the server to stream updates to the client. Here is the simplified code:

``` go
func (this *Controller) Read(request *api.ReadRequest, stream api.ReadServer) error {
	for {
		select{
			case <-stream.Context.Done():
				return stream.Context.Err()
			case update := <-this.updates:
				reply := &api.ReadReply{update}
				if err := stream.Send(reply); err != nil {
					return err
				}
		}
	}
```

I expect the `context` to signal done when the client left/disconnected, but for some reason this never happens. Is this by design? Is there any simple way to get a signal when the client disconnected?

**Comment by iamqizhao** [comment]
Can u elaborate "the client left/disconnected"?

**Comment by pjvds** [comment]
@iamqizhao: the client process died.

**Comment by iamqizhao** [comment]
I probably should add it. I intentionally did not do that previously to
avoid complexity. But it seems it is needed for "idle" (i.e., no pending
I/O) streaming rpcs in some cases. Making a PR...

**Comment by pjvds** [comment]
@iamqizhao Perfect! That totally fixed the problems I ran into. :+1:
