### ISSUE TITLE
go get -u -v google.golang.org/grpc always failed on mac

### ISSUE THREAD

**Issue by wengyanqing** [grpc/grpc-go#421]
I install grpc with command "go get -u -v google.golang.org/grpc", but it always failed. The error message is below

Fetching https://google.golang.org/grpc?go-get=1
https fetch failed.
Fetching http://google.golang.org/grpc?go-get=1
import "google.golang.org/grpc": http/https fetch: Get http://google.golang.org/grpc?go-get=1: EOF
package google.golang.org/grpc: unrecognized import path "google.golang.org/grpc"

**Comment by iamqizhao** [comment]
Did u do this in China? If yes, you probably need a VPN to install it.

**Comment by iamqizhao** [comment]
The problem is that google.golang.org/grpc does not work in China. The workaround is that you can git clone but make sure you put it into the right directory so that it can build.

**Comment by Xiaoshuai** [comment]
does "go get github.com/grpc/grpc-go" work?

**Comment by menghanl** [comment]
@Xiaoshuai I believe you can download the source code with this, but then you need to move the code to the right location to match the import path.
Please do `go get google.golang.org/grpc` if possible.

**Comment by kissgyorgy** [comment]
I get this when I `go get google.golang.org/grpc`:

```
# google.golang.org/grpc/transport
../../../../go/src/google.golang.org/grpc/transport/handler_server.go:220: undefined: http2.TrailerPrefix
../../../../go/src/google.golang.org/grpc/transport/http2_client.go:1070: undefined: http2.MetaHeadersFrame
../../../../go/src/google.golang.org/grpc/transport/http2_client.go:1191: undefined: http2.MetaHeadersFrame
../../../../go/src/google.golang.org/grpc/transport/http2_server.go:232: undefined: http2.MetaHeadersFrame
../../../../go/src/google.golang.org/grpc/transport/http2_server.go:404: undefined: http2.MetaHeadersFrame
../../../../go/src/google.golang.org/grpc/transport/http_util.go:200: undefined: http2.MetaHeadersFrame
../../../../go/src/google.golang.org/grpc/transport/http_util.go:465: f.fr.SetReuseFrames undefined (type *http2.Framer has no field or method SetReuseFrames)
../../../../go/src/google.golang.org/grpc/transport/http_util.go:466: f.fr.ReadMetaHeaders undefined (type *http2.Framer has no field or method ReadMetaHeaders)
../../../../go/src/google.golang.org/grpc/transport/http_util.go:596: f.fr.ErrorDetail undefined (type *http2.Framer has no field or method ErrorDetail)
```

**Comment by irfansharif** [comment]
@kissgyorgy: try `go get -u -v google.golang.org/grpc`?

**Comment by kissgyorgy** [comment]
That worked, thank you!

**Comment by irfansharif** [comment]
no problemo! for future context the `-u` switch updates the named packages and their dependencies. By default, `go get` only pulls in missing packages (from your local `GOPATH`) but does not use it to look for updates to existing packages, which seems was the case for the `http2` dependency.

**Comment by dfawley** [comment]
Thanks for helping, @irfansharif.  @kissgyorgy, in the future, please create new issues (https://github.com/grpc/grpc-go/issues/new) unless the symptoms you see are closely related to the original issue.  Thanks.
