### ISSUE TITLE
Support Onion name resolution

### ISSUE THREAD

**Issue by tiero** [grpc/grpc-go#4211]
### Use case(s) - what problem will this feature solve?
I run my `grpc-go` server as an Onion Hidden Service and I want be able to accept connection on *.onion interfaces.

### Proposed Solution

Make name resolution smarter 

### Alternatives Considered

Running a reverse proxy .onion -> localhost grpc

**Comment by menghanl** [comment]
There's no plan to add onion support to gRPC. But it should be fairly easy to implement your own onion resolver.

See examples:
https://github.com/grpc/grpc-go/tree/master/examples/features/name_resolving
gRPC's naming format:
https://github.com/grpc/grpc/blob/master/doc/naming.md
