### ISSUE TITLE
Flaky test: Test/RequestsCounter

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#4216]
--- FAIL: Test (2.95s)
    --- FAIL: Test/RequestsCounter (0.21s)
        --- FAIL: Test/RequestsCounter/exceeds-max-requests (0.01s)
            requests_counter_test.go:95: unexpected number of (successes, errors), expected (32, 32), encountered (33, 31)
FAIL
FAIL	google.golang.org/grpc/xds/internal/client	7.109s

From run: https://github.com/grpc/grpc-go/pull/4215/checks?check_run_id=1928775875

**Comment by menghanl** [comment]
Happened again: https://github.com/grpc/grpc-go/pull/4199/checks?check_run_id=1974487279

**Comment by easwars** [comment]
Again: https://github.com/grpc/grpc-go/pull/4318/checks?check_run_id=2272902721

**Comment by dfawley** [comment]
Is it possible this is a real bug and not just a flaky test?

**Comment by menghanl** [comment]
Hmm, it actually looks like a bug.
https://github.com/grpc/grpc-go/blob/8892a7b247c0aef5059175bacee30f2b055aac88/xds/internal/client/requests_counter.go#L56-L64

**Comment by easwars** [comment]
> Hmm, it actually looks like a bug.
> https://github.com/grpc/grpc-go/blob/8892a7b247c0aef5059175bacee30f2b055aac88/xds/internal/client/requests_counter.go#L56-L64

Are you saying it should ">" and not ">=" ?

**Comment by menghanl** [comment]
No. It's a race between `>=` on line 58 and `AddUint32` on line 62. See #4321
