### ISSUE TITLE
panic in Close()

### ISSUE THREAD

**Issue by KaiBackman** [grpc/grpc-go#422]
We are seeing the following panic consistently in production:

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x0 pc=0x5149dc]
    
    goroutine 269 [running]:
    google.golang.org/grpc.(*ClientConn).Close(0x0, 0x0, 0x0)
    src/google.golang.org/grpc/clientconn.go:225 +0x6c

It occurs a few times every hour on a system that that has a medium load of RPCs. There is no reliable short repro for the issue. Recovering from the panic seems to put the gRPC system into an incorrect state and results in further panics a few hours later.

I'm happy to test candidate patches or to do more diagnostics if required.

go version: 1.4.2
os: linux/mac

**Comment by iamqizhao** [comment]
This seems a misuse because once grpc.Dial returns picker is never nil (
https://github.com/grpc/grpc-go/blob/master/clientconn.go#L157). Can you
show me the corresponding code?

**Comment by iamqizhao** [comment]
closes due to no update.
