### ISSUE TITLE
How to change loglevel / disable logs

### ISSUE THREAD

**Issue by zetaab** [grpc/grpc-go#4231]
Kubernetes apiserver is using this grpc-go library and I am wondering is there way to disable logging from few rows, or are these hardcoded to be printed always. 

see issue https://github.com/kubernetes/kubernetes/issues/98720

When I am going through code in this library, it seems that all log rows are using same loglevel 1?

**Comment by easwars** [comment]
What version of gRPC are you using?

Are any of these environment variables set in your environment? `GRPC_GO_LOG_VERBOSITY_LEVEL` `GRPC_GO_LOG_SEVERITY_LEVEL`

**Comment by BenTheElder** [comment]
We're not setting those env. https://cs.k8s.io/?q=GRPC_GO_LOG_VERBOSITY_LEVEL&i=nope&files=&excludeFiles=&repos=kubernetes/kubernetes

Version: [google.golang.org/grpc v1.27.1](https://github.com/kubernetes/kubernetes/blob/1a983bb958ba663e5d86983c55a187fb8c429c51/go.mod#L474)

**Comment by dfawley** [comment]
If you are using a non-default logger (https://pkg.go.dev/google.golang.org/grpc/grpclog#SetLogger or SetLoggerV2), then that can control whether `Info` logs are printed, and at what verbosity.

**Comment by BenTheElder** [comment]
closing the loop: https://github.com/kubernetes/kubernetes/pull/102896
