### ISSUE TITLE
grpc client timeout after a week of success but never succeed again

### ISSUE THREAD

**Issue by amer-saffo-careem** [grpc/grpc-go#4244]
We have a service where a grpc client make an api call to a grpc server at a rate of 20k rpm.
very few calls timeout with the following error (which is OK):
    rpc error: code = DeadlineExceeded desc = context deadline exceeded
However, after a week or so, the client suddenly stops finding the server at all, and all calls timeout with the exact error stated above. But the strange thing is that it happens only to one instance of the client service (the client service has 4 instances or more depending on traffic). Then a day after, it happens to another instance and so on. Restarting the instance (of the client service) solves the issue (for a week).
Watching Go metrics of the instance in question during the incident, the memory-used (go_memstats_sys_bytes and other memory metrics) starts to accumulate and rise non-stop (from 200 MB to 6GB in 1 hour). 

We tried having better logs by using grpc.WithReturnConnectionError(), but we only got the same error above, nothing more.

Is there some kind of a queue that fills up over time and need to be cleared? for example, we had a similar issue with a kafka producer, but then it was an acknowledge message we were not consuming, which accumulated and queue would become full. I wonder if there is a similar mechanism I am not aware of, is there?
What can cause the client to wait a week before failing?
Also, it would help if there is a way to get better visibility over the error as grpc.WithReturnConnectionError didn't help at all.

Go ver 1.15
GRPC ver v1.32.0

**Comment by easwars** [comment]
We would need more information to better help you here:
- Could you run pprof on your client application to see where the memory is being leaked?
- how often does your client application open a `grpc.ClientConn`? Do you use the same `ClientConn` to make all your 20K RPCs/hr?

**Comment by amer-saffo-careem** [comment]
Yes, the client application creates a grpc.ClientConn only once at startup (created by calling grpc.DialContext). And then all calls are made through that client.
As for the memory leak, it only happens when there is an incident.

**Comment by easwars** [comment]
> Yes, the client application creates a grpc.ClientConn only once at startup (created by calling grpc.DialContext). And then all calls are made through that client.

That's good to know.

> As for the memory leak, it only happens when there is an incident.

What incident are you referring to?
We would need to see the heapdump from pprof to narrow down this issue. Thanks.

**Comment by amer-saffo-careem** [comment]
The latest update is that the memory issue was revolved by adding a circuit breaker and closing the connection when the circuit opens, and then establish a new connection with DialContext(). This however did not solve the connectivity problem; the client never succeeded to connect to the server again.

**Comment by easwars** [comment]
Were you able to narrow this down to a specific area within gRPC-Go?
Were you able to run pprof on your client to see who is eating up all the memory?
