### ISSUE TITLE
go-grpc uses https_proxy as proxy even with grpc.WithInsecure()

### ISSUE THREAD

**Issue by YuJuncen** [grpc/grpc-go#4255]
### What version of gRPC are you using?
Current master. (UA: grpc-go/1.37.0-dev)

### What version of Go are you using (`go version`)?
`go version go1.16 darwin/arm64`

### What operating system (Linux, Windows, …) and version?
macOS Big Sur 11.2.2

### What did you do?
1. Start the server at `google.golang.org/grpc/examples/helloworld/greeter_server`.
2. Change the `localhost` here to my LAN address, for bypassing the no proxy rule of `localhost`:

https://github.com/grpc/grpc-go/blob/d5b628860d4e17d106f1964097c0a297659e8110/examples/helloworld/greeter_client/main.go#L33

3. Start a [grpc-dump](https://github.com/bradleyjkemp/grpc-tools#grpc-dump) proxy at port `12345`.
```bash
grpc-dump --port=12345
```

4. Run the client at `google.golang.org/grpc/examples/helloworld/greeter_server` twice, each time with one of `http_proxy=http://localhost:12345` and `https_proxy=http://localhost:12345`.

### What did you expect to see?
grpc-dump should capture the gRPC packet when using `http_proxy`. And nothing should be captured when using `https_proxy`. Because with `grpc.WithInsecure()`, there should be plain HTTP/2 connections only.

### What did you see instead?
Only the `https_proxy` case the packet was captured. In my opinion, this would be a little strange since there is only http connections.

### NOTE

Seems `mapAddress` created a url with `https` scheme anyway. Even `grpc.WithInsecure()` was enabled.

https://github.com/grpc/grpc-go/blob/d5b628860d4e17d106f1964097c0a297659e8110/internal/transport/proxy.go#L40-L46

**Comment by Arian-p1** [comment]
Hey Im really interested in this Issue 
can you give me more information if it's needed and assign it to me?

**Comment by Arian-p1** [comment]
@dfawley Are you sure the problem is not from grpc-dump?

**Comment by dfawley** [comment]
I'm not sure there's actually any problem here at all?  We don't claim to use `http_proxy` or `https_proxy` discriminately.  Maybe the documentation should be cleaned up a bit?

https://github.com/grpc/grpc-go/blob/master/Documentation/proxy.md
