### ISSUE TITLE
"grpc: timed out trying to connect" error occurs

### ISSUE THREAD

**Issue by anzw** [grpc/grpc-go#426]
When "TLS clientAuth: tls.RequireAndVerifyClientCert" and "grpc.WithTimeout" are used together, the "grpc: timed out trying to connect" error occurs.

**Comment by iamqizhao** [comment]
it should be because the timeout u set is too short. Please enlarge it and
retry. In addition, WithTime should not be used in most of cases. Use it
only when you really need it and have a good sense what value it should be
set.

**Comment by anzw** [comment]
It is the cause, thanks a lot.
