### ISSUE TITLE
A weird question index out of range: 3 + 116> 76

### ISSUE THREAD

**Issue by ligaoyong** [grpc/grpc-go#4261]
Please see the FAQ in our main README.md before submitting your issue.
I encountered a weird problem using grpc-go. An error is reported when calling the grpc interface, and the error message is "Internal desc = index out of range: 3 + 116> 76". Sometimes it is normal, sometimes an error is reported.
My gateway application will parse the http request body and then call the remote rpc method.
This is my request body
![image](https://user-images.githubusercontent.com/34147298/110930665-591d6900-8364-11eb-817b-f274bd71d4a2.png)
This is my protocol conversion code
![image](https://user-images.githubusercontent.com/34147298/110930723-6cc8cf80-8364-11eb-91c6-1b7013ad65a4.png)
![image](https://user-images.githubusercontent.com/34147298/110930732-70f4ed00-8364-11eb-8b01-ce0edaf40e81.png)
Can anyone help me?

**Comment by ligaoyong** [comment]
I have no problems running locally, but when I deploy the application to kubernetes, the above problems sometimes occur, but in most cases it works normally

**Comment by ligaoyong** [comment]
Under what circumstances will an error in this format appear?

**Comment by ligaoyong** [comment]
![image](https://user-images.githubusercontent.com/34147298/110931522-53745300-8365-11eb-8dad-40206b35b957.png)
这个时我的依赖be版本信息

**Comment by easwars** [comment]
I'm sorry, but the screenshots of your code are so tiny that I can't make out anything. Please pose snippets of your code that we can look at.

Unrelated: v1.27.0 gRPC-Go release is reasonably old.

**Comment by ligaoyong** [comment]
![WechatIMG57](https://user-images.githubusercontent.com/34147298/111719527-04fc1280-8897-11eb-9fc6-3406b8c75e3d.png)

**Comment by ligaoyong** [comment]
![WechatIMG56](https://user-images.githubusercontent.com/34147298/111719550-0f1e1100-8897-11eb-8523-49f12994c6c5.png)

**Comment by ligaoyong** [comment]
this is my code

**Comment by dfawley** [comment]
It seems like you are using a custom JSON codec and the error you are getting is most likely from that.  Please see if you can continue debugging this on your side and feel free to ping this bug if you narrow things down to a gRPC-Go issue.
