### ISSUE TITLE
Make debugging client keepalive misconfigurations easier

### ISSUE THREAD

**Issue by evanj** [grpc/grpc-go#4266]
### What version of gRPC are you using?

1.36.0

### What version of Go are you using (`go version`)?

```
~$ go version
go version go1.16.2 linux/amd64
```

### What operating system (Linux, Windows, …) and version?

Linux Debian version 10.8 on Kernel 5.4.74-10576-gb6cc41974db3

### What did you do?

Mis-configured client keepalive so it is more aggressive than what was permitted on the server. This is an incredibly easy error to make. For example, if you deploy the clients with the new configuration before the server, or if you accidentally change the server to no longer configure it, so it reverts to the default configuration. When this happens, RPCs fail at weird intervals, particularly when there are "slow" requests.

This is tricky enough that it is mentioned as being "hard to debug" in [grpc-go's README](https://github.com/grpc/grpc-go/blob/master/README.md). I lost many hours debugging the source of this one.

### What did you expect to see?

Some message with `too_many_pings` since the server sends it in the HTTP2 GOAWAY frame as "Additional Debug Data".

### What did you see instead?

* The RPC itself fails with `code = Unavailable desc = transport is closing`. Ideally, the `too_many_pings` message from the HTTP2 GOAWAY frame Additional Debug Data should be included.

If you enable gRPC verbose logging, you will see:

```
INFO: 2021/03/14 11:45:11 [transport] Client received GoAway with http2.ErrCodeEnhanceYourCalm.
```

* Increase this log message from INFO to ERROR level. Maybe all `GOAWAY` frames, or maybe only specifically the ones with `http2.ErrCodeEnhanceYourCalm`? In either, case, this would make this message be logged by default on the client, which would help to debug the error without reading any documentation.

* This log message should include the `too_many_pings` debug info. That would make it much easier to search for this error.

**Comment by ejona86** [comment]
Java fails RPCs with something like `io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Abrupt GOAWAY closed sent stream. HTTP/2 error code: ENHANCE_YOUR_CALM (Bandwidth exhausted), debug data: too_many_pings` and for ENHANCE_YOUR_CALM it also logs a warning like `Received GOAWAY with ENHANCE_YOUR_CALM. Debug data: too_many_pings` since there may not be any RPCs on the connection when the fault occurs.

**Comment by easwars** [comment]
Thanks for reporting this issue. We will try to take care of this as soon as feasible.
