### ISSUE TITLE
Problems with receiving metadata on server

### ISSUE THREAD

**Issue by janiskemper** [grpc/grpc-go#4268]
I am not able to send metadata from a client to the server. The relevant code snippets are the following:
On the server I have ```headers, ok := metadata.FromIncomingContext(ctx)``` and on the client ```ctx := metadata.AppendToOutgoingContext(context.Background(), "custom-header-1", "test")```. 

I tried it with a client written in Go (like the above snippets) and with grpc-web. With the latter one I could confirm that the metadata has been sent and in my Envoy proxy I had ```custom-header-1``` in ```expose_headers```.

Taking both cases together (Go client and grpc-web client), I would say that it is a problem on server-side. I don't know what it could be though. Any ideas?

**Comment by easwars** [comment]
Are you using a gRPC-Go client with a gRPC-Go server? 
Is it a unary RPC or a streaming RPC?

**Comment by menghanl** [comment]
And, the metadata example could be useful: https://github.com/grpc/grpc-go/tree/master/examples/features/metadata
