### ISSUE TITLE
earthly for builds?

### ISSUE THREAD

**Issue by vladaionescu** [grpc/grpc-go#4269]
Hi there,

I'm wondering if you're interested in trying out [Earthly](https://github.com/earthly/earthly) for builds. I'd be happy to help with a PR.

Earthly could help with:
* reproducing CI failures locally, via containers
* testing against multiple versions of Go in parallel

It works well on top of [GitHub actions](https://docs.earthly.dev/).

Happy to do this work myself if this is of interest. Let me know!

**Comment by easwars** [comment]
Thanks for the offer. But we are currently happy with the setup that we have.
