### ISSUE TITLE
The attributes of the address is removed when passing to the picker.

### ISSUE THREAD

**Issue by MooooonStar** [grpc/grpc-go#4276]
I am using  my own balancer.PickerBuilder  in my program.  I attach some info to the address with the func SetAddrInfo in weightedroundrobin.go and read it from `Build(info PickerBuildInfo) balancer.Picker`.

 It works well in grpc-go@v1.34.0, but failed in grpc-go@v1.35.0. 

I read the release note and find this [strip attributes from addresses](https://github.com/grpc/grpc-go/pull/4024).  

In the function 

```golang 
func (b *baseBalancer) regeneratePicker() {
	if b.state == connectivity.TransientFailure {
		b.picker = NewErrPicker(b.mergeErrors())
		return
	}
	readySCs := make(map[balancer.SubConn]SubConnInfo)

	// Filter out all ready SCs from full subConn map.
	for addr, sc := range b.subConns {
		if st, ok := b.scStates[sc]; ok && st == connectivity.Ready {
			readySCs[sc] = SubConnInfo{Address: addr}
		}
	}
	b.picker = b.pickerBuilder.Build(PickerBuildInfo{ReadySCs: readySCs})
}
```
It uses b.subConns to pass ready connections to the picker. But the key in b.subConns contains no attributes now. So I got 

empty  attributes and my program failed.

It is a feature or a bug? What should I do?

**Comment by menghanl** [comment]
There's a PR for this: #4253
Can you take a look and see if it solves the problem?

**Comment by MooooonStar** [comment]
oh, yes! I works. It seems that he got the same problem as me.
