### ISSUE TITLE
TagConn() how to get "X-Forwarded-For"

### ISSUE THREAD

**Issue by sleepreading** [grpc/grpc-go#4288]
```
// grpc server. wanna manage every connection
TagConn(ctx context.Context, info *stats.ConnTagInfo) context.Context {
  md, ok := metadata.FromIncomingContext(ctx)
  ...
  md.Get("X-Forwarded-For")  // can't get the value.
  // I don't wanna use the value of info.RemoteAddr, because its value is '127.0.0.1'
}

// grpc server. on every rpc call
TagRPC(ctx context.Context, info *stats.RPCTagInfo) context.Context {
  md, ok := metadata.FromIncomingContext(ctx)
  ...
  md.Get("X-Forwarded-For")  // here we can get the forwarded address!
}

// nginx reverse proxy:
grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
grpc_pass grpc://news_srvs;
```

**Comment by dfawley** [comment]
`TagConn` allows the application to provide a `context.Context` for use with all RPCs that occur on that connection.  It does not have any per-RPC information.

If you want to read RPC metadata, either use an interceptor ([e.g.](https://pkg.go.dev/google.golang.org/grpc#UnaryInterceptor)) or if you must use the stats handlers (which are experimental and subject to change), that would be captured in `HandleRPC` when the `RPCStats` are of type `InHeader`.
