### ISSUE TITLE
Test/FaultInjection_Unary is flaky

### ISSUE THREAD

**Issue by menghanl** [grpc/grpc-go#4289]
https://github.com/grpc/grpc-go/runs/2185090807?check_suite_focus=true

**Comment by easwars** [comment]
Failed again: https://github.com/grpc/grpc-go/pull/4281/checks?check_run_id=2223253518

**Comment by easwars** [comment]
Another failed run:
https://github.com/grpc/grpc-go/pull/4315/checks?check_run_id=2250813771
@dfawley

**Comment by easwars** [comment]
Another:
https://github.com/grpc/grpc-go/pull/4309/checks?check_run_id=2241006263

I think this is happening frequently enough that it needs to be made P1. What do you think?

**Comment by easwars** [comment]
Another:
https://github.com/grpc/grpc-go/pull/4256/checks?check_run_id=2298761703

**Comment by menghanl** [comment]
This might be a similar race as in #4216

**Comment by easwars** [comment]
Another failure: https://github.com/grpc/grpc-go/pull/4406/checks?check_run_id=2531706845
I haven't looked into it yet to see if its the same reason as before or something new.

**Comment by dfawley** [comment]
This has the same failure result as before (timeout of the first RPC on a new client):

```
fault_test.go:558: 50% delay and abort: RPC 0: err: rpc error: code = DeadlineExceeded desc = context deadline exceeded, intnCalls: [], newTimerCalls: []
fault_test.go:560: WANTED code: Unimplemented, intnCalls: [100 100], newTimerCalls: [3s]
```

**Comment by dfawley** [comment]
I tried to reproduce this locally for over an hour without success.  Closing for now.
