### ISSUE TITLE
Add protoc-gen-go-grpc and protoc versions

### ISSUE THREAD

**Issue by amenzhinsky** [grpc/grpc-go#4303]
Hi there,

It would be helpful to have protoc-gen-go-grpc and protoc versions in the top comment in files generated protoc-gen-go-grpc because it helps to track version differences in change requests.

Just like what protoc-gen-go already [does](https://github.com/protocolbuffers/protobuf-go/blob/31610fd9139106e5b7432e3533ca1254bfa32433/cmd/protoc-gen-go/internal_gengo/main.go#L125)

If this accepted I can implement it.

**Comment by menghanl** [comment]
Thanks for the issue. The feature sounds good!

It will be great if you can make a PR. Thanks a lot!
