### ISSUE TITLE
ServerInterceptor how to get header/trailer data

### ISSUE THREAD

**Issue by zhenjunMa** [grpc/grpc-go#4317]
# scene

I use `grpc.UnaryServerInterceptor`/`grpc.StreamServerInterceptor` to do some common logic before/after the biz code.

in the common logic, i want to get request header before biz code and get response header/trailer after biz code, but i found i can't do the latter.

# my implementation

```
var unaryInterceptor grpc.UnaryServerInterceptor
unaryInterceptor = func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp interface{}, err error){
                 //here i can get the header when request come
		md, ok := metadata.FromIncomingContext(ctx)
		if ok {
			//do something...
		}

                 //do biz logic
		resp, err = handler(ctx, req)

                 //here,i want get header/trailer to do something
                 //finally i use reflect achieve the goal
		stream := grpc.ServerTransportStreamFromContext(ctx)
		v := reflect.ValueOf(stream)
		fmt.Printf("header: %v", reflect.Indirect(v).FieldByName("header"))
		fmt.Printf("trailer: %v", reflect.Indirect(v).FieldByName("trailer"))

		return
	}

```

# question

I can't find an easy way to get header/trailer after the biz logic, so i use reflect.
In my opinion, get header/trailer after the biz logic maybe a feature that many people need, so did i lost some doc about this or this feature is indeed unavailable now, need a PR? :)

looking forward reply.

**Comment by menghanl** [comment]
This can be achieved by replacing the ServerTransportStreamFromContext in the context with a wrapped one, and override `SetHeader()`, `SendHeader()`, `SetTrailer()`.

```go
type wrapper struct {
    grpc.ServerTransportStream
}

stream := grpc.ServerTransportStreamFromContext(ctx)
wrappedStream = &wrapper{stream}
newCtx := grpc.NewContextWithServerTransportStream(ctx, wrappedStream)
```

**Comment by zhenjunMa** [comment]
@menghanl 
Sorry, i can't get your point. 

you mean this?
```
type wrapper struct {
	grpc.ServerTransportStream
}

func (w *wrapper) Method() string {

}
func (w *wrapper) SetHeader(md metadata.MD) error{
     //i have no idea about the implementation
     //any tips?
}
func (w *wrapper) SendHeader(md metadata.MD) error{

}
func (w *wrapper) SetTrailer(md metadata.MD) error{

}

```

my problem is how can i override `SetHeader`/`SetTrailer` to get the `header`/`trailer` fields in `grpc.internal.transport.Stream`

**Comment by menghanl** [comment]
You are not implementing `SetHeader`. You just need to call the SetHeader, but at the same time, keep a copy of the header that's being sent.

```go
type wrapper struct {
	grpc.ServerTransportStream

	header, trailer metadata.MD
}

func (w *wrapper) Method() string {
}
func (w *wrapper) SetHeader(md metadata.MD) error{
  if err := w.ServerTransportStream.SetHeader(md); err != nil {
    return err
  }
  w.header = md
  return nil
}
func (w *wrapper) SendHeader(md metadata.MD) error{
  ...
}
func (w *wrapper) SetTrailer(md metadata.MD) error{
  ...
}

stream := grpc.ServerTransportStreamFromContext(ctx)
wrappedStream = &wrapper{stream}
newCtx := grpc.NewContextWithServerTransportStream(ctx, wrappedStream)

hander(newCtx, ...)

fmt.Println(wrappedStream.header)
```

**Comment by zhenjunMa** [comment]
@menghanl 

Thank you for your reply,  this indeed solve my problem, now this issue can be closed.

At last, I really hope you can think to expose more APIs in `ServerTransportStream` interface,

such as `GetHeader()`/`GetTrailer()`, which will make get info after biz logic easier.

And maybe this is also a common scene for other users.

**Comment by menghanl** [comment]
I agree that ideally there should be an easier way to do this, but that will need a closer look.

The `transport.Stream` has internal methods to return [`Header`](https://github.com/grpc/grpc-go/blob/5730f8d113ee31f14709a787572c4a3f3af5d3dd/internal/transport/transport.go#L360) and [`Trailer`](https://github.com/grpc/grpc-go/blob/5730f8d113ee31f14709a787572c4a3f3af5d3dd/internal/transport/transport.go#L386), but they all have assumptions about when they can be called.

Or, we can always wrap as mentioned above, so that it's available to all user interceptors.
