### ISSUE TITLE
Deprecate github.com/golang/protobuf

### ISSUE THREAD

**Issue by amenzhinsky** [grpc/grpc-go#4319]
https://github.com/golang/protobuf/pull/1306 deprecates `github.com/golang/protobuf` in favor of `google.golang.org/protobuf` 

https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.26.0 alreary removes it from generated code.

**Comment by easwars** [comment]
This is tracked in https://github.com/grpc/grpc-go/issues/3554.
