### ISSUE TITLE
HTTPS_PROXY is ignored (gRPC client)

### ISSUE THREAD

**Issue by eidans** [grpc/grpc-go#4329]
### What version of gRPC are you using?
google.golang.org/grpc v1.37.0

### What version of Go are you using (`go version`)?
go 1.16

### What operating system (Linux, Windows, …) and version?
Linux ubuntu 5.4.0-70-generic x86_64 GNU/Linux

### What did you do?
I was testing gRPC with an HTTP proxy using 'https_proxy' environment variable (gRPC client -> HTTP(s) proxy -> gRPC Server). I brought up a local proxy listening on _localhost:8444_, and configured _https_proxy=http://localhost:8444_. The server listens on _localhost:8449_.

```
const (                                                                          
         address     = "localhost:8449"                                          
)                                                                                

1         tlsConfig := &tls.Config{                                                
2              ServerName:         strings.Split(address, ":")[0],                 
3              MinVersion:         tls.VersionTLS12,                               
4              Certificates:       []tls.Certificate{},                            
5              InsecureSkipVerify: true,                                           
6         }                                                                        
7                                                                                  
8         opts := []grpc.DialOption{                                               
9                 grpc.WithTransportCredentials(credentials.NewTLS(tlsConfig)),    
10        }                                                                        
11                                                                                  
12        // Set up a connection to the server.                                    
13        conn, err := grpc.DialContext(context.TODO(), address, opts...)          
14        if err != nil {                                                          
15                log.Fatalf("did not connect: %v", err)                           
16        }                                                                        
17        defer conn.Close()                                                       
 ```                                                     

I ran my client with the following command: https_proxy=http://localhost:8444 ./client

### What did you expect to see?
I expected my client to send a CONNECT request to the local proxy.

### What did you see instead?
the client communicated directly with the local server; the gRPC library ignored the 'http_proxy' environment variable.

### Additional insights
* I found out that if I set the server address to "localhost:8449/" (adding '/') as a suffix, the library works as expected as the client connects to the proxy.
* In addition, if the address is prefixes with http (http://localhost:8449), the library connects to the proxy but the proxy returns 'Bad Gateway 502'. This is because the CONNECT that the gRPC library generates is malformed:

![image](https://user-images.githubusercontent.com/19627192/114244925-13ba7e80-9998-11eb-8dd6-4be887e0c054.png)

**Comment by Jun10ng** [comment]
HTTPS_PROXY or HTTP_PROXY ?

**Comment by Jun10ng** [comment]
I see that the URL in your command(http://localhost:8449) starts with "http",  maybe you should use "HTTP_PROXY" instead of "HTTPS_PROXY".

**Comment by dfawley** [comment]
> the client communicated directly with the local server; the gRPC library ignored the 'http_proxy' environment variable.

This is the correct behavior.  When you are dialing "localhost", your proxy will be bypassed, by design:

https://golang.org/pkg/net/http/#ProxyFromEnvironment

> As a special case, if req.URL.Host is "localhost" (with or without a port number), then a nil URL and nil error will be returned.

--

> I found out that if I set the server address to "localhost:8449/" (adding '/') as a suffix, the library works as expected as the client connects to the proxy.

I'm surprised this works at all.  *this* may be a bug.

> In addition, if the address is prefixes with http (http://localhost:8449), the library connects to the proxy but the proxy returns 'Bad Gateway 502'. This is because the CONNECT that the gRPC library generates is malformed:

This is not how addresses work in gRPC.  gRPC URIs are used to instruct gRPC how to resolve addresses for the target.  See https://github.com/grpc/grpc/blob/master/doc/naming.md for more information.
