### ISSUE TITLE
run server as a daemon：code = Unavailable desc = timed out waiting for server handshake

### ISSUE THREAD

**Issue by lixiaoxi-coder** [grpc/grpc-go#4331]
grpc version: v1.37.0
protobuf version: v1.26.0
go version: 1.13

I want the server to become a daemon, The code is as follows：
`
        func daemon() int {
	// already a daemon
	if syscall.Getppid() == 1 {
		return 0
	}

	// fork off the parent process
	pid, _, err := syscall.Syscall(syscall.SYS_FORK, 0, 0, 0)
	if err != 0 {
		fmt.Printf("fork error! %v\n", err)
		return -1
	}

	//fork failure
	if pid < 0 {
		fmt.Println("fork fail!")
		os.Exit(-1)
	}

	// if fork success,then we call exit the parent process.
	if pid > 0 {
		os.Exit(0)
	}

	/* Change the file mode mask */
	_ = syscall.Umask(0)

	// create a new SID for the child process
	sid, s_errno := syscall.Setsid()
	if s_errno != nil {
		fmt.Printf("Error: syscall.Setsid errno: %d", s_errno)
	}

	if sid < 0 {
		fmt.Println("Error: syscall.Setsid fail")
		return -1
	}

	//change work dir
	os.Chdir("/")

	//duplicate stdin、stdout、stderr to /dev/null
	f, op_err := os.OpenFile("/dev/null", os.O_RDWR, 0)
	if op_err != nil {
		fmt.Printf("Error: open /dev/null fail, err:%v\n", op_err)
		return -1
	}

	fd := f.Fd()
	dup_err := syscall.Dup2(int(fd), int(os.Stdin.Fd()))
	if dup_err != nil {
		fmt.Printf("Error: syscall.Dup2 errno: %d", s_errno)
		return -1
	}

	dup_err = syscall.Dup2(int(fd), int(os.Stdout.Fd()))
	if dup_err != nil {
		fmt.Printf("Error: syscall.Dup2 errno: %d", s_errno)
		return -1
	}

	dup_err = syscall.Dup2(int(fd), int(os.Stderr.Fd()))
	if dup_err != nil {
		fmt.Printf("Error: syscall.Dup2 errno: %d", s_errno)
		return -1
	}

	return 0
}`

then i start the daemon and grpc server in main package
`	
        ret := daemon()
	if ret != 0 {
                log.Fatal("create daemon failed")
	 	return
	 }

	listener, err := net.Listen("tcp", ":19528")
	if err != nil {
		log.Fatal("ListenTCP error:", err)
	}

	gRPCServer := grpc.NewServer()
	TestServiceGrpcImpl := server.NewTestServiceGrpcImpl()
	server.RegisterTestServiceServer(gRPCServer, TestServiceGrpcImpl)

	// start the server
	if err := gRPCServer.Serve(listener); err != nil {
		log.Fatalf("failed to serve: %s", err)
	}`

there's a problem：
      1. When I write  `package server`   in proto file and use daemon function, rpc error: code = Unavailable desc = timed out waiting for server handshake on client
      2. When I write  `package main`   in proto file and use daemon function, client communication is ok
      3. When I write  `package server`   in proto file and don't use daemon  function, client communication is ok
   
So is grpc affected by daemon or package names? What's the principle?

**Comment by dfawley** [comment]
> So is grpc affected by daemon or package names? What's the principle?

No, your errors appear unrelated to gRPC.  There must be something else going on.  You may want to look at the logs (https://github.com/grpc/grpc-go#how-to-turn-on-logging).

**Comment by lixiaoxi-coder** [comment]
> > So is grpc affected by daemon or package names? What's the principle?
> 
> No, your errors appear unrelated to gRPC. There must be something else going on. You may want to look at the logs (https://github.com/grpc/grpc-go#how-to-turn-on-logging).

Hello, I opened the log, but I can't analyze the problems. Can you take a look at it ? It's as follows
INFO: 2021/04/16 11:57:37 [core] parsed scheme: ""
INFO: 2021/04/16 11:57:37 [core] scheme "" not registered, fallback to default scheme
INFO: 2021/04/16 11:57:37 [core] ccResolverWrapper: sending update to cc: {[{localhost:9527  <nil> 0 <nil>}] <nil> <nil>}
INFO: 2021/04/16 11:57:37 [core] ClientConn switching balancer to "pick_first"
INFO: 2021/04/16 11:57:37 [core] Channel switches to new LB policy "pick_first"
INFO: 2021/04/16 11:57:37 [core] Subchannel Connectivity change to CONNECTING
INFO: 2021/04/16 11:57:37 [core] blockingPicker: the picked transport is not ready, loop back to repick
INFO: 2021/04/16 11:57:37 [core] pickfirstBalancer: UpdateSubConnState: 0xc000099f90, {CONNECTING <nil>}
INFO: 2021/04/16 11:57:37 [core] Channel Connectivity change to CONNECTING
INFO: 2021/04/16 11:57:37 [core] Subchannel picks a new address "localhost:9527" to connect
INFO: 2021/04/16 11:58:01 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
WARNING: 2021/04/16 11:58:01 [core] grpc: addrConn.createTransport failed to connect to {localhost:9527 localhost:9527 <nil> 0 <nil>}: didn't receive server preface in time. Reconnecting...
INFO: 2021/04/16 11:58:01 [core] Subchannel Connectivity change to TRANSIENT_FAILURE
INFO: 2021/04/16 11:58:01 [core] pickfirstBalancer: UpdateSubConnState: 0xc000099f90, {TRANSIENT_FAILURE timed out waiting for server handshake}
INFO: 2021/04/16 11:58:01 [core] Channel Connectivity change to TRANSIENT_FAILURE
req fail, err:rpc error: code = Unavailable desc = timed out waiting for server handshake
INFO: 2021/04/16 11:58:01 [core] Channel Connectivity change to SHUTDOWN
INFO: 2021/04/16 11:58:01 [core] Subchannel Connectivity change to SHUTDOWN

**Comment by menghanl** [comment]
> grpc: addrConn.createTransport failed to connect to {localhost:9527 localhost:9527 0 }: didn't receive server preface in time

> TRANSIENT_FAILURE timed out waiting for server handshake

> error: code = Unavailable desc = timed out waiting for server handshake

The client didn't connect to the server successfully.
And it looks like the server was not speaking http2 (it could receive bytes, but didn't send bytes out).

If "use daemon function" is what made the connection fail, maybe try to remove code from `daemon()` to find which line is causing the problem.

**Comment by lixiaoxi-coder** [comment]
> > grpc: addrConn.createTransport failed to connect to {localhost:9527 localhost:9527 0 }: didn't receive server preface in time
> 
> > TRANSIENT_FAILURE timed out waiting for server handshake
> 
> > error: code = Unavailable desc = timed out waiting for server handshake
> 
> The client didn't connect to the server successfully.
> And it looks like the server was not speaking http2 (it could receive bytes, but didn't send bytes out).
> 
> If "use daemon function" is what made the connection fail, maybe try to remove code from `daemon()` to find which line is causing the problem.

Yes, I've tried that. The problem is on `syscall.Syscall(syscall.SYS_FORK, 0, 0, 0)`,  as you know, I just want grpc server to run without the control of the terminal, so fork() is essential.

**Comment by ZekeLu** [comment]
According to this closed issue https://github.com/golang/go/issues/227, it's not a good idea to implement daemon in golang.

**Comment by lixiaoxi-coder** [comment]
> According to this closed issue [golang/go#227](https://github.com/golang/go/issues/227), it's not a good idea to implement daemon in golang.
Thank you for sharing the issue .  I have used `os.StartProcess(binary, os.Args, &os.ProcAttr{Dir: "", Env: nil, Files: []*os.File{os.Stdin, os.Stdout, os.Stderr}, Sys: nil})`  instead of  `syscall.Syscall(syscall.SYS_FORK, 0, 0, 0)`.  It's OK.
