### ISSUE TITLE
Make `maxPingStrikes` configurable

### ISSUE THREAD

**Issue by jandersen-plaid** [grpc/grpc-go#4348]
### Use case(s) - what problem will this feature solve?

Within our organization, we use gRPC to orchestrate a variety of different operations. Some of those core operations are performed over long-lived unary request and responses: clients fire off payloads , wait for a response while doing some other work, and then proceed onwards once the work is returned.

Due to the long-lived nature of these requests (which, in some cases, can range up to an absolute worst case of 60 minutes), we set strict keepalive policies and enforcements across all servers and clients. Every server and client is set to a specific interval and, when the policies are violated and servers accumulate more than 2 ping strikes for a client, a GOAWAY frame is sent and the transport is closed (as expected). Overall, everything works as planned.

Unfortunately, we have come to the realization that we cannot change the keepalive interval without changing it across the entire organization at the exact same time.

For example, if we have a sample architecture of services A, B, and C:
![grpc_stable](https://user-images.githubusercontent.com/52045989/115459140-b246ab00-a1f4-11eb-82fa-065b52ce0ab2.png)

In the above diagram, service A is a client of service B and service C, and service C is a client of service A.

Each of these services has a 15 second keepalive interval (`keepalive.ClientParameters.Time = 15 * time.Second` client and `keepalive.EnforcementPolicy.MinTime = 15 * time.Second` server) that we would like to move to 10 seconds due to changed network conditions and load shape (for example: a newly aggressive load balancer, rockier network, etc.). Assuming that the deployments are magical and immediately come up and down:

* If we deploy service A first, and then service B or service C, we would see dropped connections from service A to service B/C (if the time it takes to deploy service B and service C exceeds about 40 seconds, if I have my math right) as a result of too many PINGs being sent from service A ahead of the keepalive intervals set on service B/C.
* If we deploy service C first, and then service A or service B, service A could see failures by not sending enough PINGs, and service C would see failures with service B due to sending too many PINGs to service B.
* If we deploy service B first, and then service A or service C, then service B could see failures when service A or service C do not respond fast enough.

To be completely safe and have 0 unavailable connections, we would need to deploy all 3 services at the same time which is not practical.

### Proposed Solution

To cope with this, it would be helpful to have a configurable `MaxPingStrikes` setting on the `keepalive.EnforcementPolicy`. This will alleviate the problem by allowing `MaxPingStrikes` to be raised to a higher than normal level while moving all keepalive settings into place, and the returning it to the original value of 2 when that is done.

Furthermore, making this setting configurable would create a setting that is [already available in the gRPC Core keepalive configuration.](https://github.com/grpc/grpc/blob/master/doc/keepalive.md)

### Alternatives Considered

Alternatively, we could create a dependency tree (ensuring it is acyclic) and then try and nudge the keepalive down by appropriate increments (ensuring that max ping strikes will only be accumulated after the time it takes to deploy) for each service. This would be time consuming and problematic.

Additionally, we could just deploy it all at once and eat all the lost connections -- expecting retries to catch up -- but this is not a viable solution because it results in an unknown amount of latency within the system that could have consequences elsewhere.

**Comment by dfawley** [comment]
@ejona86 was this supposed to be configurable? Would this require a gRFC / change to the keepalive gRFC?

**Comment by ejona86** [comment]
> To be completely safe and have 0 unavailable connections, we would need to deploy all 3 services at the same time which is not practical.

Not at all. The configuration is independent on client-side and server-side. First, change the servers to lower their limit. Then, separately, change the clients to make use of the limit.

> This will alleviate the problem by allowing MaxPingStrikes to be raised to a higher than normal level while moving all keepalive settings into place, and the returning it to the original value of 2 when that is done.

The connections would still fail. It would just take 15-30 seconds longer, depending on how high you raised the limit. This seems neither here nor there, as you could just change the server's keepalive limit _instead_ of changing the limit of ping strikes.

**Comment by jandersen-plaid** [comment]
Thanks for the clarification and explanation @ejona86!

> Not at all. The configuration is independent on client-side and server-side. First, change the servers to lower their limit. Then, separately, change the clients to make use of the limit.

This is particularly illuminating. I think we had the illusion on our end that clients would send a GOAWAY frame if they were overloaded, which is not the case (after your message and [a more careful reading of the gRFC](https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md#server-enforcement)).

> The connections would still fail. It would just take 15-30 seconds longer, depending on how high you raised the limit. This seems neither here nor there, as you could just change the server's keepalive limit instead of changing the limit of ping strikes.

The thought here was to set `MaxPingStrikes` to infinity rather than purely something higher (which I misinterpreted when creating the issue). Regardless, the appropriate approach is, as you pointed out, to alter the server side enforcement before the client(s) configuration for each client-server relationship.

**Comment by ejona86** [comment]
> I think we had the illusion on our end that clients would send a GOAWAY frame if they were overloaded, which is not the case (after your message and a more careful reading of the gRFC).

The limits servers impose should still be separate configuration from the keepalives servers send. Taking C's configurations as an example, you can change `GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS` which will adjust the limits enforced, but nothing else. So _even if clients imposed limits_ (which I agree that they don't) it'd be safe to first adjust that configuration option everywhere is the first stage. Then, after it is rolled out, you could safely reduce `GRPC_ARG_KEEPALIVE_TIME_MS`.

On a separate note, if you are using 10ish seconds for `GRPC_ARG_KEEPALIVE_TIME_MS`, I'd generally call that rather low. Normally I'd expect the server to be more conservative, just because it isn't waiting for any "responses" and it can't do anything if something goes wrong; keepalive on server-side is more about garbage collection or about things like "prevent the load balancer from closing the 'idle' connection."

If you are doing long-lived RPCs (such that keepalives would be frequent), a small optimization would be to make the server's keepalive time slightly longer than client side (e.g., 1 second); that will prevent both the client and server from sending a keepalive simultaneously (and would actually prevent the server from sending keepalives except for actual failures as the client's keepalive counts as activity and resets the inactivity timer). If you aren't doing long-lived RPCs, then it wouldn't matter much as keepalives in general will be relatively rare.

> The thought here was to set MaxPingStrikes to infinity rather than purely something higher (which I misinterpreted when creating the issue)

I see. Disable the verification. Yeah, that would work, but isn't necessary.

**Comment by jandersen-plaid** [comment]
> On a separate note, if you are using 10ish seconds for GRPC_ARG_KEEPALIVE_TIME_MS, I'd generally call that rather low.

Agreed. Unfortunately, we have an external client (which we don't control) sending keepalives at a 2.5 second interval, which is... not optimal. We are working with them on removing their hardcoded interval (or, at least, making it configurable), but it will be a while until the next release so we were looking into adjusting specific client-server keepalive intervals or ping strikes to triage the issue. 

> If you are doing long-lived RPCs (such that keepalives would be frequent), a small optimization would be to make the server's keepalive time slightly longer than client side (e.g., 1 second)

I am curious about this as our use-case is exactly that: long-lived RPCs. If the server's keepalive time is slightly longer than the client side (e.g. 10 seconds on the client side, and 11 seconds on the server side), wouldn't the client pings count as ping strikes? The client would send a ping at 10 seconds, and the server would read that at 10 seconds + network latency which is before the minimum time (11 seconds) that the server wants. That is, unless I am misreading which server keepalive setting should be set slightly longer.

**Comment by dfawley** [comment]
> The client would send a ping at 10 seconds, and the server would read that at 10 seconds + network latency which is before the minimum time (11 seconds) that the server wants. That is, unless I am misreading which server keepalive setting should be set slightly longer.

It seems you may be confusing the server's [`keepalive.ServerParameters.Time`](https://pkg.go.dev/google.golang.org/grpc/keepalive#ServerParameters) with the server's [`keepalive.EnforcementPolicy.MinTime`](https://pkg.go.dev/google.golang.org/grpc/keepalive#EnforcementPolicy).  The former is for the server to initiate a ping and the latter is to enforce that the client isn't sending pings any faster than that rate.  @ejona86 was suggesting to set the former to 11 seconds, and then it would detect the connection as lost 1 second after the client.  If the client keepalive ping time is set to the example of 10 seconds, a server enforcement rate (the latter setting) of 9 seconds may be appropriate, to avoid disconnects in case the client and server disagree slightly about the rate of time or if there is some network jitter.

**Comment by jandersen-plaid** [comment]
Ah, I see, I see. Thank you for clarifying @dfawley!

**Comment by ejona86** [comment]
> > On a separate note, if you are using 10ish seconds for GRPC_ARG_KEEPALIVE_TIME_MS, I'd generally call that rather low.
>
> Agreed. Unfortunately, we have an external client (which we don't control) sending keepalives at a 2.5 second interval, which is... not optimal.

Doh. I meant to say 10ish seconds for GRPC_ARG_KEEPALIVE_TIME_MS for _a server_ was rather low. 10s for a client is low and you may encounter see limitations of what it can handle (not implementation-wise, but just practically the way networks behave), but I had been trying to call out having a server-side send out a keepalive ping so soon after inactivity was low.

If you have a client wanting 2.5s keepalive, that would only impact GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS.

> I am curious about this as our use-case is exactly that: long-lived RPCs. If the server's keepalive time is slightly longer than the client side (e.g. 10 seconds on the client side, and 11 seconds on the server side), wouldn't the client pings count as ping strikes?

No. This shows that we're still not quite to an understanding.

I'm going to leverage the gRFCs. Both client and server have KEEPLIVE_TIME and KEEPALIVE_TIMEOUT (client via [A8](https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md) and server via [A9](https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md)). They have essentially the same semantics (excepting KEEPALIVE_WITHOUT_CALLS behavior). Those two options control _sending of PINGs_ after periods of inactivity and determining when a connection is dead. They have no impact on the behavior when receiving PINGs.

To detect and address overzealous clients, the server has PERMIT_KEEPALIVE_TIME (defined in A8). This detects a client sending pings too frequently and killing the connection. _This_ is the key configuration that is important to change to allow more aggressive clients.

I know those weren't the terms you are used to in the C API. Take a look at the [end of the gRFC](https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md#implementation) to see the C core names. (I just saw Doug's posted a comment, and it seems to mention the Go names.)

**Comment by jandersen-plaid** [comment]
> To detect and address overzealous clients, the server has PERMIT_KEEPALIVE_TIME (defined in A8). This detects a client sending pings too frequently and killing the connection. This is the key configuration that is important to change to allow more aggressive clients.

Nice! Okay, this is fitting together more nicely in my brain. Thank you for taking the time to explain this!
