### ISSUE TITLE
Short Connection Prefaces should cause the connection to fail

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-go#435]
The tests here: https://github.com/grpc/grpc/blob/master/test/core/bad_client/tests/connection_prefix.c and here https://github.com/grpc/grpc/blob/master/tools/http2_interop/http2interop.go#L197  should cause a Server to terminate an inbound connection.  Currently, running these tests against the Go server hang, waiting for the server to close the connection.

**Comment by dfawley** [comment]
We have timeouts on connection establishment now, so this should no longer be a problem.  #1646
