### ISSUE TITLE
ResourceExhausted error for servers with GRPC_COMPRESS_STREAM_GZIP compression

### ISSUE THREAD

**Issue by pavelsimo** [grpc/grpc-go#4357]
### What version of gRPC and what language are you using?

google.golang.org/grpc v1.34.0

### What operating system (Linux, Windows,...) and version?

macOS Big Sur 11.1

### What did you do?

Using a C++ gRPC server with experimental compression `GRPC_COMPRESS_STREAM_GZIP `:
https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/compression_types.h#L62

Ran:

```
ghz --proto=myproto.proto --call <endpoint> -d ‘<json_request>’ -c 5 -n10 --insecure 127.0.0.1:8888
```

### What did you expect to see?

A proper gRPC response

### What did you see instead?

```
Error distribution:
  [10]   rpc error: code = ResourceExhausted desc = grpc: received message larger than max (2332557312 vs. 2147483647)
```

**Comment by menghanl** [comment]
Can you try to set the max recv size to a bigger number?
https://pkg.go.dev/google.golang.org/grpc#MaxCallRecvMsgSize

**Comment by pavelsimo** [comment]
That does not seem to be the problem, by default `ghz` sets `MaxCallRecvMsgSize` to `math.MaxInt32`.

```go
// increase max receive and send message sizes
opts = append(opts,
    grpc.WithDefaultCallOptions(
	grpc.MaxCallRecvMsgSize(math.MaxInt32),
	grpc.MaxCallSendMsgSize(math.MaxInt32),
))
```

https://github.com/bojand/ghz/blob/532fb1e6211266eced3e4fe6454df6d907e4a052/runner/requester.go#L329

In addition, my server is not streaming messages bigger than 10mb.

**Comment by menghanl** [comment]
I just noticed that you are testing `GRPC_COMPRESS_STREAM_GZIP`.

This feature (stream level compression) isn't support in gRPC-Go (#2105). And there's currently no plan to work on that.

I believe it's only C-core to C-core. I think Java also doesn't support it yet.

**Comment by menghanl** [comment]
I closing this as a dup of #2105 now. Please comment on the original issue if you need this feature.
