### ISSUE TITLE
client gets "canceled context" error for successful server processing 

### ISSUE THREAD

**Issue by grasparv** [grpc/grpc-go#4371]
### What version of gRPC are you using?

91d8f0c916d76f2a5aac9e846cd7ffcb838db769

### What version of Go are you using (`go version`)?

go version go1.16.1 linux/amd64

### What operating system (Linux, Windows, …) and version?

debian bullseye

### What did you do?

I am arbitrarily cancelling the context in the middle of the remote procedure call.

It can be reproduced with the following modification to the hello world program in the repository:

```
~/grpc-go/examples/helloworld/greeter_client$ git diff
diff --git examples/helloworld/greeter_client/main.go examples/helloworld/greeter_client/main.go
index 0ca4cbaa..0d8f96b7 100644
--- examples/helloworld/greeter_client/main.go
+++ examples/helloworld/greeter_client/main.go
@@ -21,8 +21,8 @@ package main

 import (
        "context"
+       "fmt"
        "log"
-       "os"
        "time"

        "google.golang.org/grpc"
@@ -43,16 +43,17 @@ func main() {
        defer conn.Close()
        c := pb.NewGreeterClient(conn)

-       // Contact the server and print out its response.
-       name := defaultName
-       if len(os.Args) > 1 {
-               name = os.Args[1]
+       for i := 0; i < 10000; i++ {
+               name := fmt.Sprintf("%d", time.Now().UnixNano())
+               ctx, cancel := context.WithCancel(context.Background())
+               dur := time.Nanosecond * time.Duration(i)
+               go func() {
+                       time.Sleep(dur) // arbitrary delay into the call
+                       cancel()        // perform cancellation mid-call
+               }()
+               _, err := c.SayHello(ctx, &pb.HelloRequest{Name: name})
+               if err != nil && ctx.Err() != nil {
+                       log.Printf("call %s canceled after %v got %s", name, dur, err.Error())
+               }
        }
-       ctx, cancel := context.WithTimeout(context.Background(), time.Second)
-       defer cancel()
-       r, err := c.SayHello(ctx, &pb.HelloRequest{Name: name})
-       if err != nil {
-               log.Fatalf("could not greet: %v", err)
-       }
-       log.Printf("Greeting: %s", r.GetMessage())
 }
```

Here you can cross-reference the IDs printed:
- Some call IDs that were cancellel _are_ printed on the server.
- Other call IDs that were cancelled _are not_ printed on the server.

### What did you expect to see?

I expect `SayHello` to return `rpc error: code = Canceled desc = context canceled`  **only if** the server did **not** successfully receive and process the call.

If the server did **not** receive and process the call due to the cancellation, I expect to see  `rpc error: code = Canceled desc = context canceled`.

### What did you see instead?

I see the error from SayHello as `rpc error: code = Canceled desc = context canceled` even when the hello world server prints the call ID.

My _guess_ is that either two happens:
- The cancellation happens before the message is put on the network => Server does not receive the request
- The cancellation happens after the message is put on the network => Server receives and processes the request

Maybe in the second case, the cancellation should not be returned as an error.

Alternatively, there should be a way to see if the server processed the call in the return data so that the client _at least_ knows whether it occured or not and can take appropriate decisions.

I am interested in hearing whether you consider this to be a bug.

**Comment by grasparv** [comment]
Reading a little bit of code and it seems like gRPC actually marshals and passes contexts from client->server and vice-versa. So on the server side you can see that sometimes the context is cancelled. This is interesting.

**Comment by grasparv** [comment]
Refining my hello world example above with the following:
```
diff --git examples/helloworld/greeter_server/main.go examples/helloworld/greeter_server/main.go
index 15604f9f..e081613f 100644
--- examples/helloworld/greeter_server/main.go
+++ examples/helloworld/greeter_server/main.go
@@ -39,7 +39,9 @@ type server struct {

 // SayHello implements helloworld.GreeterServer
 func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
-       log.Printf("Received: %v", in.GetName())
+       if ctx.Err() == nil {
+               log.Printf("Received: %v", in.GetName())
+       }
        return &pb.HelloReply{Message: "Hello " + in.GetName()}, nil
 }
```
.. the server now only prints "Received" if context was not cancelled before sending.  And here you still get `rpc error: code = Canceled desc = context canceled` returned back for call IDs that were printed on the server. In other words, the client gets an error even when the server handled the request successfully.

Still a bit unsure about the exact implementation in gRPC. Maybe it is something like this:
```
+--+--------------------------------+------------------------------------------+
|  |CLIENT                          | SERVER                                   |
+--+--------------------------------+------------------------------------------+
|t0|ctx1 := some background ctx     |                                          |
|t1|data, err := call rpc SayHello  |                                          |
|t2|                                | ctx2 := ctx1 (copied over network)       |
|t3|                                | ctx2 not cancelled, go ahead with work   |
|t3|ctx1 cancel                     |                                          |
|t4|                                | update database                          |
|t5|                                | return ok                                |
|t6|rpc SayHello gets response      |                                          |
|t7|err = context cancelled         |                                          |
|  |because of some cancellation    |                                          |
+--+--------------------------------+------------------------------------------+

```
The database is updated here, but the client still sees an error.

Although from what I could see, a context was returned back to the client through the stream. Not sure how that context which is returned to the client is modified to be canceled, if it goes to the server, gets re-synched and then is returned, if it is the client's context that is returned into the stream or however this framework works. Either way, I hope the general problem is stated clear enough :-)

**Comment by grasparv** [comment]
@dfawley Seeing that you were active in https://github.com/grpc/grpc-go/issues/3328, you may find this one interesting.

**Comment by dfawley** [comment]
Context propagation doesn't work quite like you are thinking, but the idea is similar.  The context is not shared directly at all, but when the call's context ("ctx1") is canceled client-side, the gRPC library on the client cancels the RPC by sending a RST_STREAM HTTP/2 frame, which results in the gRPC library on the server canceling the server's context ("ctx2").

Races are inherent in any concurrent system, particularly when relatively slow (milliseconds instead of nanoseconds) networks are involved.  If the client cancels its context, it cannot instantaneously cancel the server's context, nor is it correct to wait for the server response to determine whether the cancelation happened before or after the server's work.  Generally, you should expect that if your RPC was sent that the server may do the work, even if you cancel the RPC *or even receive a deadline exceeded error*.  ("Deadline exceeded" is also generated client-side, and the response may have been on the wire before this occurred.)

Hopefully this answers your question.

**Comment by grasparv** [comment]
@dfawley Thanks for the reply. It makes sense to me.

I suppose then the correct way of finding out whether the server did the work is to try to detect this outside of the call entirely? Or would you say there is a feature in gRPC itself to do some kind of blocking call?

**Comment by dfawley** [comment]
There is no way for gRPC to handle this kind of scenario.  You need to either perform the operation again until it succeeds (hopefully the operation is idempotent!) or do some kind of query to determine whether it happened.
