### ISSUE TITLE
Question: Ordering between two streaming RPCs in one client

### ISSUE THREAD

**Issue by aaronbee** [grpc/grpc-go#4374]
Hello, I have a question about a single client connected to a single server with t two different bidirectional streaming RPCs running in different goroutines.

Imagine I have code like the following:

```go
conn, _ := grpc.DialContext(ctx, addr)
client := foopb.NewFooClient(conn)
sent := make(chan struct{})
go func() {
    stream, _ := client.StreamingRPC()
    stream.Send(req1)
    close(sent)
    for { resp, _ := stream.Recv(); handle(resp) }
}()
<-sent // waits for Send to return in above goroutine
stream, _ := client.StreamingRPC()
stream.Send(req2)
```

Is it guaranteed that `req1` will be queued to be sent to the server before `req2` assuming there are no errors? Another way to phrase my question: what is guaranteed to have occurred by the time that stream.Send returns?

**Comment by menghanl** [comment]
(This is more on the implementation details, not API, so the behavior is not guaranteed to not change)

If the RPCs pick different SubConns, the order is not guaranteed.

If both RPCs pick the same SubConn (the same transport, the same TCP connection), the messages will be queued in order (req1 before req2).
But this is not a behavior to rely on. There's a sending queue in each transport for performance reasons. There was a time that those two Send() would race, and order was non-determined.

Send() doesn't wait for the message to be written on wire. It's also possible that After Send() returns, a connection error happens, and the message will never be actually sent.

**Comment by aaronbee** [comment]
Thanks for the explanation, makes sense.
