### ISSUE TITLE
errors.Is(err, context.Canceled) does not work

### ISSUE THREAD

**Issue by dtbartle** [grpc/grpc-go#4375]
### What version of gRPC are you using?
master

### What version of Go are you using (`go version`)?
1.16

### What operating system (Linux, Windows, …) and version?
MacOS X Big Sur

### What did you do?
```
package main

import (
	"context"
	"errors"
	"fmt"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func main() {
	err := status.Errorf(codes.Canceled, "canceled")
	fmt.Println(errors.Is(err, context.Canceled))
}

```

### What did you expect to see?
`true`

### What did you see instead?
`false`

I believe this would be fixed by having https://github.com/grpc/grpc-go/blob/master/internal/status/status.go#L156 check if `err == context.Canceled && tse.s.Code == codes.Canceled`.

**Comment by dfawley** [comment]
This does not seem appropriate to me.  The server returning a codes.Canceled status is not the same as context cancelation, and we can't distinguish the two from the status package.  Why not use `status.Code(err) == codes.Canceled`?
