### ISSUE TITLE
Allow StreamClientInterceptor to cancel a context when streaming is finished

### ISSUE THREAD

**Issue by greg-dennis** [grpc/grpc-go#4379]
### Use case(s) - what problem will this feature solve?

A `StreamClientInterceptor` may want to create a child context before invoking the streamer, e.g. to add a default timeout if one is not specified. But if it does so, the interceptor API gives no way to reliably way to ensure the context is canceled when streaming is done. With a `UnaryClientInterceptor` this is simple (just defer the cancel call), and there should be a straightforward mechanism in a `StreamClientInterceptor` as well.

### Proposed Solution

Add a new call option to cancel a context when the RPC is complete, i.e.:

```
func ContextCancel(cancelFn context.CancelFunc) CallOption {
	return ContextCancelCallOption{CancelFn: cancelFn}
}
type ContextCancelCallOption struct {
	CancelFn context.CancelFunc
}
func (o ContextCancelCallOption) before(c *callInfo) error { return nil }
func (o ContextCancelCallOption) after(c *callInfo, attempt *csAttempt) {
	o.CancelFn()
}
```

### Alternatives Considered

Export an `OnFinish` method in `ClientStream` that is called when streaming is finished. Implementors of `StreamClientInterceptor` could wrap the `ClientStream` returned by `streamer` with an OnFinish method that cancels the context. This would be less backwards-compatible and more complicated for the implementor.

### Additional Context

None

**Comment by dfawley** [comment]
Please see discussion in #1717.
