### ISSUE TITLE
admin service errors if xds imported but no bootstrap exists

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#4400]
Not sure what the best fix is here: we should check with other languages.

- We could silently skip it.
- We could skip it and return something to indicate it was skipped.
- We could register the service and return empty data or errors.

**Comment by menghanl** [comment]
Java's CSDS doesn't fail on missing xDS client. It will always return an empty response: https://github.com/grpc/grpc-java/blob/8e18c11bbda78e75d18f8148dab42e409054c83a/xds/src/main/java/io/grpc/xds/CsdsService.java#L135
