### ISSUE TITLE
xds client sometimes loses updates when canceling/re-subscribing to same resource concurrently

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#4409]
This was causing a test to be flaky but was worked around via #4377

**Comment by menghanl** [comment]
Client is watch for resource A
```
req(A, "")
resp(A, v1)
req(A, v1) // this is ACK
```

user cancels watch for A
```
req([], v1) // this removes A from the requested resources
```

user re-adds watch for A
What version to send with the request?
We will send
```
req(A, v1)
```

In the failed test, the controller (go-control-plane) doesn't resend (A, v1) to the client.

**Comment by menghanl** [comment]
Yes. Closing now.
