### ISSUE TITLE
status.FromError(err error) behaves differently than its documentation states

### ISSUE THREAD

**Issue by amarine7882** [grpc/grpc-go#4410]
The docs state that status with `codes.OK` is returned if `err == nil` but in fact `nil` is returned. 
https://github.com/grpc/grpc-go/blob/daba80583807e692013f3fd884092e77413705f1/status/status.go#L78

https://github.com/grpc/grpc-go/blob/daba80583807e692013f3fd884092e77413705f1/status/status.go#L81-L84

**Comment by dfawley** [comment]
This is correct:

```go
(*status.Status)(nil).Code() == codes.OK
(*status.Status)(nil).Message() == ""
```
