### ISSUE TITLE
large errors (>= ~16 kiB) are never received by the client

### ISSUE THREAD

**Issue by michael-berlin** [grpc/grpc-go#443]
When this issue occurs, the call on the client side times out eventually and returns with 'code = 4 desc = "context deadline exceeded"'.

I've added an end2end test to reproduce the issue:

https://github.com/michael-berlin/grpc-go/tree/large_error_gets_swallowed

Diff: https://github.com/grpc/grpc-go/compare/master...michael-berlin:large_error_gets_swallowed?expand=1

As far as I can tell, the issue has always been present. I've spot checked older commits up to Sep 17 (5e5f5df2bbfed81a191eb0484831738cc729f3b9). (I didn't check commits before Sep 17 because my test patch didn't apply cleanly to these.)

**Comment by dsymonds** [comment]
The [gRPC spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) seems to imply that clients may limit the size of an RPC that it'll accept back (in the `Trailers` production). Maybe this is a bug in the behaviour of handling that limit, rather than a bug in accepting a large error at all.

(In other words, perhaps such large errors are simply not permitted, but the Go client is not passing that on properly.)

**Comment by michael-berlin** [comment]
I agree. There's always a limit somewhere.

The biggest problem here was that I didn't get any feedback at all from gRPC. One solution might be to ignore the original (too big) error and respond with an internal error instead which clearly states the problem? That internal error could also contain a truncated version of the original error.

The other alternative would be to send the original error, but truncate it. However, that may corrupt data when the error is more than just a simple string.

**Comment by aaijazi** [comment]
I would advocate against truncating the Trailers field. I believe it should currently be possible to send other structured data through the Trailers field, not only errors.

**Comment by iamqizhao** [comment]
Thanks for pointing out. I think this is a corner case worth an explicit spec in the designdoc and behave consistently across grpc impl in various languages. will initiate some discussion in the team once I am back from the travel next week.

**Comment by michael-berlin** [comment]
Thanks for the fix :-)

Which assumptions should we make about size limits in the Go gRPC implementation? Should we stick with the 8 KiB limit from the gRPC specification or is it safe to assume that there aren't limits on gRPC error messages anymore? (At least, when using the Go implementation.)
