### ISSUE TITLE
Determine stream cancellation was issued by client

### ISSUE THREAD

**Issue by steeling** [grpc/grpc-go#4442]
Is there a way to determine if the client explicitly cancelled a stream vs some other network issue?

**Comment by easwars** [comment]
Can you please provide us with more information about what you are trying to do so that we can help you better.

**Comment by steeling** [comment]
I have a server side streaming object that listens to updates on a collection. I'm wondering what the best way to cancel that stream is?

Should I switch to bidi streaming, and send a one time, "complete" request? Or is there a way for my client to close out the stream and I can tell the difference between a conn.Close(), and an intermittent network failure that closed the connection.

Right now I can check stream.Context().Done(), but that is just a boolean done value. Do you set the stream.Context().Err()?

**Comment by dfawley** [comment]
If it's important to the server, then you should use a bidi stream for this.  There is no way to distinguish client-side cancelation from connectivity loss on the server side.  I checked with Java & C++, and they are the same in this regard.

With a bidi stream, you don't need a special message for this; `ClientStream.CloseSend()` is propagated to the server, visible via `ServerStream.Recv()` returning `io.EOF`.
