### ISSUE TITLE
how to set stream.Recv() timeout? 

### ISSUE THREAD

**Issue by xtaci** [grpc/grpc-go#445]
how to set stream.Recv() timeout?

**Comment by iamqizhao** [comment]
You can wait on another goroutine and cancel the stream if the timer fires.

**Comment by shafreeck** [comment]
I don't think its a good way to rely on a separate goroutine. Why not build the timeout feature in like using context ?

**Comment by iamqizhao** [comment]
To be clear, the scope of context is rpc (either unary or streaming) instead of a particular message.

**Comment by Julio-Guerra** [comment]
I'm wondering if this is that clear on the documentation. It really deserves a "Synchronization" and "error-handling" chapters.

**Comment by xtaci** [comment]
absolutly, doc is not clear enough

**Comment by jan4984** [comment]
@iamqizhao how to cancel a strem.recv() for bidi-streaming rpc at server side. I not find any stream mehtod.

**Comment by MakMukhi** [comment]
@jan4984  You can cancel a stream by canceling the context used to create it.

**Comment by jan4984** [comment]
@MakMukhi no, I mean the server side.  The stream is allocated by gRPC framewok.

**Comment by nhooyr** [comment]
@jan4984 You would exit the goroutine that received the stream.

**Comment by jan4984** [comment]
@nhooyr but how can I return if I'm blocking at recv() call

**Comment by nhooyr** [comment]
@jan4984 recv in a different goroutine.

**Comment by dfawley** [comment]
See also #1229 (esp. [this comment](https://github.com/grpc/grpc-go/issues/1229#issuecomment-300938770) and below), which is about Send() deadlines but the same concepts/techniques apply.
