### ISSUE TITLE
Server should not return ResourceExhausted on seeing a malformed method name

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#4456]
See [here](https://github.com/grpc/grpc-go/blob/c9c9a7536f5756744347acaba907189e53c38468/server.go#L1591).

It should instead be returning `codes.Unimplemented`.

**Comment by dfawley** [comment]
UNIMPLEMENTED?

https://github.com/grpc/grpc/blob/master/doc/statuscodes.md ("Method not found at server")

**Comment by easwars** [comment]
We do return `UNIMPLEMENTED` when we can't find the service or method [here](https://github.com/grpc/grpc-go/blob/c9c9a7536f5756744347acaba907189e53c38468/server.go#L1632).

But this one is specifically where the URL path can't be parsed as a valid `service` and `method` pair.

**Comment by dfawley** [comment]
Let's make sure we do the same thing as C/Java (especially if they agree) in any case.  From an HTTP perspective, "/foo" is a valid method name, so INVALID_ARGUMENT doesn't make the most sense to me.

**Comment by easwars** [comment]
@ejona86 @markdroth 
What does Java/C do here? Thanks.

**Comment by markdroth** [comment]
As per https://github.com/grpc/grpc/blob/master/doc/statuscodes.md, INVALID_ARGUMENT is not one of the codes that gRPC is allowed to generate internally.

Why does go try to parse the HTTP/2 path to a service/method pair in the first place?  I don't think C-core does that at all.  That parsing is valid when protobuf is used as the IDL, but gRPC can be used with other IDLs for which that assumption might not be true.

**Comment by dfawley** [comment]
> Why does go try to parse the HTTP/2 path to a service/method pair in the first place?

This is just the way our registration works... it's structured and we can't change that:

https://pkg.go.dev/google.golang.org/grpc#Server.RegisterService
https://pkg.go.dev/google.golang.org/grpc#ServiceDesc

We could go the other direction and convert registered services+methods into paths and then match the path alone when the RPC comes in.  It's unclear if such a change is really worth making, given registration is required to be structured anyway.  It would save some minor logic per-RPC, though...

So does C use UNIMPLEMENTED for this kind of situation?

**Comment by markdroth** [comment]
Yes, I believe we use UNIMPLEMENTED for any path that does not have a registered handler.  I think that's done at the C++ layer, not inside of core, so other wrapped languages might do something different.  But in general, I think UNIMPLEMENTED is the right code to use in this case.

**Comment by ejona86** [comment]
Java would use UNIMPLEMENTED since there is nothing registered for that name. The only other option in my mind is HTTP 404, which would open a can of worms ("why don't we do 404 for case X?").
