### ISSUE TITLE
Health: Health server should use gRPC status codes

### ISSUE THREAD

**Issue by aranw** [grpc/grpc-go#4460]
### Use case(s) - what problem will this feature solve?

Not all systems currently use gRPC Health Protobuf format to check the status of a running server and instead rely on the gRPC Status Codes outlined [here](https://grpc.github.io/grpc/core/md_doc_statuscodes.html)

It would be nice if the server could check the status that has been set and then return the approach status code as well 

### Additional Context

AWS ALB is one example of a service not using the protobuf format to check the status but instead using the status code https://aws.amazon.com/blogs/aws/new-application-load-balancer-support-for-end-to-end-http-2-and-grpc/

**Comment by dfawley** [comment]
This sounds like a proposal that would impact all gRPC language implementations.  Please file this in the [main grpc repo](https://github.com/grpc/grpc/issues/new/choose) instead, thank you!
