### ISSUE TITLE
state of gogo protobuf support?

### ISSUE THREAD

**Issue by newhook** [grpc/grpc-go#4466]
This commit removed `proto.Marshaler`, which seems to drop support for gogo protobuf definitions from working correctly with grpc since the code ends up using the `github.com/golang/protobuf/proto.Marshal` API and protobuf reflection.

What was intended, if anything, to replace this?

commit 7b167fd6eca1ab8f05ec14085d63197cacd41438
Author: Doug Fawley <dfawley@google.com>
Date:   Wed Oct 14 14:51:13 2020 -0700

    encoding/proto: simplify & optimize proto codec (#3958)

**Comment by dfawley** [comment]
gRPC-Go doesn't explicitly support gogo proto.  However, it should be straightforward to implement and register your own proto codec (following https://github.com/grpc/grpc-go/blob/master/Documentation/encoding.md and https://github.com/grpc/grpc-go/blob/master/encoding/proto/proto.go as an example) that does work correctly with gogo proto.

**Comment by newhook** [comment]
Thanks Doug.

```
cannot use grpc.CallContentSubtype("gogo") (type grpc.CallOption) as type grpc.DialOption in argument to grpc.Dial:
	grpc.CallOption does not implement grpc.DialOption (missing grpc.apply method)
```
It is unfortunate that this doesn't work as documented.

> As a reminder, all CallOptions may be converted into DialOptions that become the default for all RPCs sent through a client using grpc.WithDefaultCallOptions:

Should this actually recommend `grpc.WithDefaultCallOptions(grpc.CallContentSubtype("gogo")),`?

**Comment by newhook** [comment]
Hey Doug, I was looking at this today. My understanding is that I can now register a codec for gogo as follows:

```
const Name = "gogo"

func init() {
        encoding.RegisterCodec(codec{})
}

type marshaler interface {
        Marshal() ([]byte, error)
}

type unmarshaler interface {
        Unmarshal(data []byte) error
}

// codec is a Codec implementation with protobuf. It is the default codec for gRPC.
type codec struct{}

func (codec) Marshal(v interface{}) ([]byte, error) {
        m, ok := v.(marshaler)
        if !ok {
                return nil, fmt.Errorf("failed to marshal, message is %T, want gogo proto", v)
        }
        return m.Marshal()
}

func (codec) Unmarshal(data []byte, v interface{}) error {
        m, ok := v.(unmarshaler)
        if !ok {
                return fmt.Errorf("failed to unmarshal, message is %T, want gogo proto", v)
        }
        return m.Unmarshal(data)
}

func (codec) Name() string {
        return Name
}
```

Then to use that codec on the client side:

```
grpc.DialContext(context.Background(), "localhost:11111", grpc.WithInsecure(),
                grpc.WithDefaultCallOptions(
                        grpc.CallContentSubtype("gogo"),
                ),
        )
```

I've tested that and it works, which is great.

However, after thinking a bit more about our environment and looking at how this works, selecting a new codec seems to change the contnet type encoding. In this case, to `application/grpc+gogo`.

That leads me to wonder what happens with backwards compatibility and foreign language client/server compatibility. Now the wire format hasn't changed -- the encoding is actually still protobuf. However, the content types have changed (from `application/grpc` to ``application/grpc+gogo`).

Is that all going to work as expected? Can, for example, a python grpc server work with no changes with a new grpc client that is using this codec?

I'm suspecting that it does not because the content type will be unrecognized. If so, that is pretty annoying because actually the wire format is entirely compatible.

It appears to me what I really want to do is replace the proto codec, not register a new specialized codec just for gogo.

**Comment by menghanl** [comment]
You can register the new codec with name "proto", then it will replace the default, and you won't need the content subtype.
(There might be some problems if you need both gogo/proto and golang/proto. But I assume that's not what you want, right?)
