### ISSUE TITLE
How to Enable SRV Lookups in DNS Resolver?

### ISSUE THREAD

**Issue by aranw** [grpc/grpc-go#4467]
So I'm wanting to use the DNS Resolver to lookup services using SRV records and I can see the config option for SRV Lookups is disable by default? https://github.com/grpc/grpc-go/blob/master/internal/resolver/dns/dns_resolver.go#L46

I've tried enabling this but it errors with `use of internal package google.golang.org/grpc/internal/resolver/dns not allowed` 

So I was wondering am I missing something when using the DNS Resolver as I can't find any documentation on this feature?

**Comment by dfawley** [comment]
Are you trying to use SRV records to provide gRPC-LB addresses?  That is how the default DNS resolver uses them.  This happens automatically when the `grpclb` package is imported, via: https://github.com/grpc/grpc-go/blob/359fdbb7b310c71882a354675949a4ca95957d75/balancer/grpclb/grpclb.go#L99-L102

If you are trying to use SRV records for another purpose, you'll probably need to implement your own name resolver.
