### ISSUE TITLE
How can we make sure Server.Stop() always cancels Server.Serve()

### ISSUE THREAD

**Issue by timmyyuan** [grpc/grpc-go#4473]
I have a program, probably like:

```go
package main
import "google.golang.org/grpc"

func main() {
      s := grpc.NewServer(nil)
      go s.Serve()
      s.Stop()
}
```

How to design this program that can make sure the `Stop()` always cancels `s.Serve()` to avoid a goroutine leak?

**Comment by DMwangnima** [comment]
When you invoke s.Stop(), s.lis will be closed so that s.Serve will stop. And s.quit plays a role as signal so that deriving goroutine will be stopped automatically. You needn't worry about the goroutine leak once you invoke s.Stop().
