### ISSUE TITLE
Example/Documentation for health package

### ISSUE THREAD

**Issue by ppg** [grpc/grpc-go#448]
Is there any documentation or examples of how the health package is intended to be used: https://godoc.org/google.golang.org/grpc/health ? I'm particular interested in how/if that can integrate with things like consul service checks, etc. but just a code example of what the intended usage was would be a good starting point.

Thanks,
\Peter

**Comment by iamqizhao** [comment]
hope this (https://github.com/grpc/grpc/blob/master/doc/health-checking.md) helps.

**Comment by ppg** [comment]
This does help, thank you; I had missed the doc directory at first, that's a good reference point.

I had a few follow on questions:

1. A lot of existing things that care about health checks make it easy to query HTTP style services via a check URL. They mainly pay attention to status code, but can also look for response body matching. I think because this endpoint always returns 200 and the body is binary encoded they can't tie into that, but I was curious if there's some creativity I'm missing that would allow me to tie in say haproxy into checking this endpoint?
2. Due to 1, it seems like it'd be prudent for most services to build a 'health checker' app that hits that RPC and returns an exit code that service monitors could use (i.e. ala nagios style). Does that sound correct, i.e. is that the anticipated usage pattern? Or is there a different way one would expect to integrate the health endpoint to nagios, consul, etc.?
3. It seems like 2 would be a consistent enough pattern that it might be something worth investigating adding to either grpc-go or grpc in general, where `grpc_health_checker` (or whatever) calls the health check endpoint on a server (optional CLI arguments for service names) and then translates the response into a return code?

Thanks,
\Peter

**Comment by therc** [comment]
I am going to implement client support for this in Kubernetes: https://github.com/kubernetes/kubernetes/issues/21493

My main concern is about the "v1alpha". Is it going to be supported when e.g. gRPC hits 1.0? What do you recommend doing, @iamqizhao?

**Comment by iamqizhao** [comment]
Yeah, we are about to change it to V1 now.  Let me talk to the team -- some coordination across languages is needed to minimize the chance of breakage. Should be done in a couple of days.

**Comment by therc** [comment]
@ppg this is an example of the haproxy creativity you were asking about: http://www.juhonkoti.net/2015/11/26/using-haproxy-to-do-health-checks-to-grpc-services

**Comment by therc** [comment]
Awesome, I was not in a hurry. :-) We use mainly Go and Python, so, yeah, I understand your need for coordination.

**Comment by ppg** [comment]
@therc thanks for the follow up, I'll give it a read and try it out.

**Comment by hsaliak** [comment]
@ppq I am closing this issue as there exists document and is stale. If you are still waiting for enhancements to this doc, please reopen.
