### ISSUE TITLE
metadata: move FromOutgoingContextRaw to an internal package

### ISSUE THREAD

**Issue by menghanl** [grpc/grpc-go#4487]
This function is for gRPC's use only (mentioned in its godoc).

https://github.com/grpc/grpc-go/pull/4416/files#r631494667

**Comment by Aditya-Sood** [comment]
hi @menghanl @ginayeh, can I pick this up?

**Comment by dfawley** [comment]
Yes, that should be fine.  There may be difficulty avoiding circular dependencies...I haven't fully figured out how this would work.

**Comment by Aditya-Sood** [comment]
adding comment to prevent issue being closed
working on 5360 in parallel
