### ISSUE TITLE
Impossible to satisfy an interface with an external implementation (due to unexported mustEmbedUnimplemented*)

### ISSUE THREAD

**Issue by absoludity** [grpc/grpc-go#4500]
### What version of gRPC are you using?

1.38.8

### What version of Go are you using (`go version`)?

go version go1.16.3 linux/amd64

### What operating system (Linux, Windows, …) and version?

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

### What did you do?

Used the reflect package to determine if a gRPC server implementation satisfies a generated interface from a separate package:

```
	// The following check if the service implements an interface is what
    	// grpc-go itself does, see:
    	// https://github.com/grpc/grpc-go/blob/v1.38.0/server.go#L621
    	serverType := reflect.TypeOf(pluginSrv)
    	corePackagesType := reflect.TypeOf((*packages.PackagesServiceServer)(nil)).Elem()

    	if serverType.Implements(corePackagesType) {
    	...
    	}
```

### What did you expect to see?

Expected to be able to verify that a server implementation satisfies a generated interface.

### What did you see instead?

I'm unable to satisfy the interface specifically because the `mustEmbedUnimplemented...` function is unexported, and go's reflect package explicitly ensures that [if an interface includes unexported methods, then the implementation of those methods must be from the same package](https://golang.org/src/reflect/type.go?s=1335:7651#L1494):

```
			if !tmName.isExported() {
				tmPkgPath := tmName.pkgPath()
				if tmPkgPath == "" {
					tmPkgPath = t.pkgPath.name()
				}
				vmPkgPath := vmName.pkgPath()
				if vmPkgPath == "" {
					vmPkgPath = V.nameOff(v.pkgPath).name()
				}
				if tmPkgPath != vmPkgPath {
					continue
				}
			}
```

I can work around this by using `- require_unimplemented_servers=false` (while still including the unimplemented servers for the intended behavior of providing the unimplemented methods),  but this would not be necessary if the method added to the interface was exported, ie. `MustEmbedUnimplemented*()`.

Is the fact that I cannot satisfy a generated interface from an external server implementation an unintended side-effect of adding the unexported method in the interfaces, or is it intended that people cannot create implementations satisfying a generated interface from a different package?

Scenario:
package A defines `CorePackageServer` and `CoreOtherServer`
package B includes `SpecificPackageServer` which may implement one or both of the core server interfaces.

**Comment by dfawley** [comment]
It was intended to be impossible to satisfy the requirement without embedding the `Unimplemented` struct.

However, we later decided to add an `Unsafe` version for people that prefer for their code to break when new methods are added (which is otherwise a backward compatible change).  So some change here _may_ be possible.

> Used the reflect package to determine if a gRPC server implementation satisfies a generated interface from a separate package:

Why are you trying to use the `reflect` package for this?  Why not a simple type assertion:

```
   	if _, ok := impl.(pb.FooServer); ok {
		// Yes impl implements pb.FooServer
   		...
   	}
```

Also I'm not sure why you're seeing the `reflect` calls fail for this reason.  As you say, the grpc package is doing the exact same thing, and the `mustEmbed` function doesn't exist in the grpc package, either.  Are you trying to declare a `mustEmbed` function directly on the server implementation?

**Comment by absoludity** [comment]
> It was intended to be impossible to satisfy the requirement without embedding the `Unimplemented` struct.

or implementing those methods, I think? Or do you mean that it is intended that even if an implementation satisfies all the exposed methods of the interface (ie. all the gRPC calls) it should still not satisfy the requirement of the interface because it doesn't have the `mustEmbed...` function defined in the package of the interface class? 

Note that I am embedding the `Unimplemented` struct of my gRPC plugin packages (which have the same required functions, but may have added extra methods to their specific interfaces) - I like the functionality of ensuring that new methods can be added without breaking the implementations (and having default unimplemented versions), but because the `mustEmbedUnimplemented...` methods are unexposed, when including this unexposed method I'm unable to verify if one grpc server also satisfies another interface from another package (as even though my implementation has the same signature, the `mustEmbedUnimplemented...` function is from a different package).

> 
> However, we later decided to add an `Unsafe` version for people that prefer for their code to break when new methods are added (which is otherwise a backward compatible change). So some change here _may_ be possible.

As above, I am embedding an `Unimplemented` struct because I do want that functionality, just not the one from the package of an interface that I want to check (more below). It does implement all the required methods of the interface that I'm checking, and I can run with `- require_unimplemented_servers=false` while still embedding the relevant unimplemented structs (what I'm currently doing) and then I can verify that a specific implementation satisfies multiple interfaces from different packages without issue.

> 
> > Used the reflect package to determine if a gRPC server implementation satisfies a generated interface from a separate package:
> 
> Why are you trying to use the `reflect` package for this? Why not a simple type assertion:
> 
> ```
>    	if _, ok := impl.(pb.FooServer); ok {
> 		// Yes impl implements pb.FooServer
>    		...
>    	}
> ```

Because I don't have access to the type - it's defined in a dynamically loaded plugin (sorry, I failed to mention that in the original description). A [go plugin](https://golang.org/pkg/plugin/) allows you to load symbols (variables including functions). Our plugins expose a function to register themselves with a provided grpc server and return their implementation (ie. they return an instance of the server struct, as an `*interface{}`). The reflect package allows us to determine whether that instance additionally implements other core interfaces, in exactly the same way that the grpc code does.

> 
> Also I'm not sure why you're seeing the `reflect` calls fail for this reason. As you say, the grpc package is doing the exact same thing, and the `mustEmbed` function doesn't exist in the grpc package, either.

That maybe more obvious now that I've mentioned I'm loading some grpc servers dynamically as go plugins. When not using dynamically-loaded plugins, a gRPC server implementation imports the `UnImplemented...` from the generated code and embeds it - so the unexposed `mustEmbed...` function *is* from the original package. In my use-case I have:

package A defining CorePackageServer and CoreOtherServer
package B defining SpecificPackageServer, an externally-defined grpc server (with its own proto) that is loaded dynamically as a go plugin, which when registered returns an implementation (a struct) for  SpecificPackageServer. The key is that this struct may implement one or both of the core server interfaces, and I can verify this easily as above. The only issue is that an unexposed method (`mustEmbed...`) ensures that I *cannot* verify this (and hence the work-around).

Of course the `SpecificPackageServer` plugin code could import the `Unimplemented...` struct from either `CorePackageServer` or `CoreOtherServer` and embed one of them (but only one) instead of its own `Unimplemented...`, but that would defeat the purpose, since the plugin should be using its own `Unimplpemented..` struct and additionally, I'm checking whether a plugin satisfies multiple core services. This all works fine and is inline with [go's interface definition](https://golang.org/doc/effective_go#interfaces) of "if something can do *this*, then it can be used *here*.", as long as I don't have the unexposed `mustEmbed...` function on the interfaces.


> Are you trying to declare a `mustEmbed` function directly on the server implementation?

No, hopefully that's clearer from the above. Sorry, I understand that loading gRPC server implementations as go plugins isn't a normal use-case, which is why I'm trying to ask the question instead as: is it intended that even if an implementation satisfies all the exposed methods of the interface (ie. all the gRPC calls) it should still not satisfy the requirement of the interface? As this appears to go against the above definition of go interfaces. It *looks* like an implementation detail with unexpected consequences to me, but I'm not sure, hence the question :)

I'm quite happy with the current solution, that I can run with `- require_unimplemented_servers=false` while still embedding the relevant `Unimplemented...` structs, but just wanted to be clear about the potentially unintended consequence of the unexposed methods, and see if there's a better solution moving forward (such as exposing the method with a generic name: `MustEmbedUnimplementedImplementation()`, so that it is satisfied and not influencing the interface checks above.

**Comment by dfawley** [comment]
> do you mean that it is intended that even if an implementation satisfies all the exposed methods of the interface (ie. all the gRPC calls) it should still not satisfy the requirement of the interface because it doesn't have the `mustEmbed...` function defined in the package of the interface class?

Correct.  You _must_ embed the `Unimplemented...` struct to satisfy the interface.  You don't need to implement all the RPCs; unimplemented methods will return UNIMPLEMENTED status errors if called.  It _may_ be possible to export the `mustEmbed...` function (`MustEmbed...`).  The idea being that if anyone actually "implemented" that function themselves, it would essentially be the equivalent of embedding the `Unsafe...` struct: it will work today, but if you add an RPC method, it will fail to compile.

Do you have / can you make a minimal example of what you are doing, so that I can play around with it?  I think I now understand what you're trying to do, but would like to be sure and also have a demo I can play around with to see how to potentially make it work.

**Comment by absoludity** [comment]
I am keen to provide a minimal example, just haven't had the time yet.
