### ISSUE TITLE
resolver.GetConfigSelector return not nil interface

### ISSUE THREAD

**Issue by alpha-baby** [grpc/grpc-go#4502]
### What version of gRPC are you using?

latest version

### What version of Go are you using (`go version`)?

1.16.2

### What operating system (Linux, Windows, …) and version?

macos

### What did you do?

if watch resoruce error, call here https://github.com/grpc/grpc-go/blob/2de42fcbbce31dcdf14ee24836a713b65fc06dae/xds/internal/resolver/xds_resolver.go#L202 to set nil `*configSelector`

when we call 
https://github.com/grpc/grpc-go/blob/2de42fcbbc/internal/resolver/config_selector.go#L138
 will return not nil interface `ConfigSelector`。

becase golang interface source code:
```go
type eface struct {
    _type *_type
    data  unsafe.Pointer
}

type iface struct {
    tab  *itab
    data unsafe.Pointer
}
```

so, when calling `SetConfigSelector`，we wil not set if it is nil.

like:

```golang
func (r *xdsResolver) sendNewServiceConfig(cs *configSelector) bool {
//  .......
	// Send the update to the ClientConn.
	state := resolver.State{
		ServiceConfig: r.cc.ParseServiceConfig(string(sc)),
	}
	if cs != nil {
		iresolver.SetConfigSelector(state, cs)
	}
	r.cc.UpdateState(state)
	return true
}
```

**Comment by menghanl** [comment]
Sorry, I don't understand this issue. I don't think you use `ConfigSelector`, because it's in `internal`.

Or is it a question about why it's done this way in gRPC (why setting cs to nil)?

Or are you saying there's a bug when setting `cs` to `nil`, so you are suggesting that we should only call `SetConfigSelector` when `cs != nil`?

**Comment by alpha-baby** [comment]
i wirte a unit test to help you understand this.

```go
type mockConfigSelector struct {
}

func (m *mockConfigSelector) SelectConfig(info RPCInfo) (*RPCConfig, error) {
	return nil, nil
}

func (m *mockConfigSelector) GetLDSName() string {
	return ""
}

func (m *mockConfigSelector) GetRDSName() string {
	return ""
}

func TestGetConfigSelector(t *testing.T) {
	type args struct {
		state resolver.State
	}
	var mConfigSelector *mockConfigSelector
	if mConfigSelector != nil {
		t.Errorf("mConfigSelector is not nil")
	}
	tests := []struct {
		name    string
		args    args
		want    ConfigSelector
		wantNil bool
	}{
		{
			name: "set-nil-mockconfigselector",
			args: args{
				state: SetConfigSelector(resolver.State{
					Attributes: attributes.New("key", "value"),
				}, mConfigSelector),
			},
			want:    mConfigSelector,
			wantNil: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := GetConfigSelector(tt.args.state)
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("GetConfigSelector() = %v, want %v", got, tt.want)
			}

			if (got == nil) != tt.wantNil {
				t.Errorf("GetConfigSelector() = %v, want %v", got, tt.want)
			}
		})
	}
}
```

when call here : https://github.com/grpc/grpc-go/blob/master/xds/internal/resolver/xds_resolver.go#L227
and gRPC will get not nil interface. process will into here : https://github.com/grpc/grpc-go/blob/master/clientconn.go#L643

**Comment by alpha-baby** [comment]
@menghanl thx, review this problem

**Comment by dfawley** [comment]
I think I see the problem.  I'll send a fix.

**Comment by dfawley** [comment]
Actually, I don't see any problem here.

When we send a `nil` `*configSelector`, we intend for it to be called, and to produce RPC errors (gracefully), because the resource was deleted.

Are you seeing any actual behavior problems here?

**Comment by menghanl** [comment]
I haven't run the given tests. A thought: is this another typed nil?
- `nil` in `r.sendNewServiceConfig(nil)` is type `*configSelector`
- `GetConfigSelector` returns `ConfigSelector` interface.

**Comment by dfawley** [comment]
> A thought: is this another typed nil?

Yes it's a typed `nil`, but that is intentional and should be working as expected.

**Comment by alpha-baby** [comment]
> When we send a nil *configSelector, we intend for it to be called, and to produce RPC errors (gracefully), because the resource was deleted.

Sorry, I think this bug has been fixed.

code in here: https://github.com/grpc/grpc-go/blob/master/xds/internal/resolver/serviceconfig.go#L137

Thank you for your replies
