### ISSUE TITLE
How to reconnect gRPC connection from DNS resolve by client-side

### ISSUE THREAD

**Issue by akihiro** [grpc/grpc-go#4513]
I use grpc-go by clinet. Our system use gRPC over TLS and reverse proxy(traefik).
the gRPC endpoint was migrated by DNS record(same FQDN, different IP address).
grpc-go client had 404 error when the gRPC endpoint virtual host configuration is deleted on reverse proxy(traefik) of old IP address.

```
error:rpc error: code = Unimplemented desc = Not Found: HTTP status code 404; transport: received the unexpected content-type "text/plain; charset=utf-8"
```

A gRPC over TLS connection is keep-alived to old IP address, not reconnected to new IP address.
I implement the client-side workaround reconnect a gRPC connection on 404 error.
How to reconnect gRPC connection from DNS resolver by client-side ?

**Comment by menghanl** [comment]
The default DNS resolver doesn't periodically pull. Re-resolution happens on connection errors.

What's going to happen to the old server after migration? Do you plan to close it? Can you try `GracefulStop()` (or even, `Stop()`)?

**Comment by akihiro** [comment]
> The default DNS resolver doesn't periodically pull.

Yes, I agree.

> Re-resolution happens on connection errors.

Yes, I agree.
This error is not a connection error(under L4 error), not a HTTP error(status 404 is normal response for HTTP) also.
But this error is a gRPC error(under layer response status 404).

If the reverse proxy correctly disconnects the connection to the undefined virtual host, the problem will not occur.

> What's going to happen to the old server after migration?

Timeline

1. Add the IngressRoute manifest in new reverseproxy(traefik2.x).
2. Change the DNS A record for endpoint FQDN(change IP adderess from old proxy to new proxy).
3. Wait double time of TTL of DNS record.
4. Delete the Ingress manifest in old revrseproxy(traefik1.x).
5. the gRPC client use keep-alived connection to the old proxy.
6. the old proxy response status 404.
7. the client return error: `error:rpc error: code = Unimplemented desc = Not Found: HTTP status code 404; transport: received the unexpected content-type "text/plain; charset=utf-8"`.
8. clinet retry by application code like this. but the client has same errors.
9. I restart client process by hand. the new process connect to the new proxy.
```golang
func (end *Endpoint) CreateAlerts(ctx context.Context, alerts []*pb.NewAlert) error {
	c := pb.NewAlertStoreClient(end.conn)
	var err error
	for i := 0; i < end.Retry+1; i++ {
		ctxTimeout, cancel := context.WithTimeout(ctx, end.Timeout.Duration)
		_, err = c.CreateAlerts(ctxTimeout, &pb.CreateAlertsRequest{Alerts: alerts})
		cancel()
		if err == nil {
			break
		}
	}
	return err
}
```

> Do you plan to close it?

I have no idea.
I try to replace http.Tranport. but grpc-go is not use http.Transport, implement [http2 client](https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_client.go)

> Can you try `GracefulStop()` (or even, `Stop()`)?

No, this migration is replace reverse-proxy not replace gRPC backend.

**Comment by menghanl** [comment]
> Wait double time of TTL of DNS record.

This doesn't make any difference, because the default DNS resolver doesn't track DNS TTL.

> the old proxy response status 404

Does this mean the proxy keeps the connection open, but just send http errors?

The DNS resolver doesn't re-resolve based on DNS TTL, nor periodically.
The client only re-resolves when there's a connection error. So if the proxy disconnects from the client, the client will pick up the new entries from DNS.

You may also be interested in https://github.com/grpc/grpc/issues/12295, #1663

**Comment by jwrookie** [comment]
> The default DNS resolver doesn't periodically pull. Re-resolution happens on connection errors.
> 
> What's going to happen to the old server after migration? Do you plan to close it? Can you try `GracefulStop()` (or even, `Stop()`)?

why? If the pod is expanded, the client-side is not aware of it
