### ISSUE TITLE
rpc error Unavailable with no description

### ISSUE THREAD

**Issue by haani-niyaz** [grpc/grpc-go#4514]
I am getting the following  non descriptive error for a particular endpoint: `rpc error: code = Unavailable desc =`

In an effort troubleshoot the issue I enabled the necessary logging however it I can't seem to identify a fault. The logging has been truncated for relevance:

```
INFO: 2021/06/04 07:37:33 [core] ccResolverWrapper: sending update to cc: {[{mysvc.backend.svc.cluster.local:8443  <nil> 0 <nil>}] <nil> <nil>}
INFO: 2021/06/04 07:37:33 [core] ClientConn switching balancer to "pick_first"
INFO: 2021/06/04 07:37:33 [core] Channel switches to new LB policy "pick_first"
INFO: 2021/06/04 07:37:33 [core] Subchannel Connectivity change to CONNECTING
INFO: 2021/06/04 07:37:33 [core] pickfirstBalancer: UpdateSubConnState: 0xc0002bf090, {CONNECTING <nil>}
INFO: 2021/06/04 07:37:33 [core] Channel Connectivity change to CONNECTING
INFO: 2021/06/04 07:37:33 [core] Subchannel picks a new address "mysvc.backend.svc.cluster.local:8443" to connect
INFO: 2021/06/04 07:37:33 [core] Subchannel Connectivity change to READY
INFO: 2021/06/04 07:37:33 [core] pickfirstBalancer: UpdateSubConnState: 0xc0002bf090, {READY <nil>}
INFO: 2021/06/04 07:37:33 [core] Channel Connectivity change to READY

...
INFO: 2021/06/04 07:37:34 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```
Any suggestions on what may be causing this? 

Note: the `transport is closing` log message is also present for successful rpc calls.

grpc version: v1.37.0

**Comment by menghanl** [comment]
Can you confirm that the unavailable error is not returned from the application?

Unavailable errors from gRPC mean connection errors, they should all have a description. Sometimes with not-so-useful description like "transport is closing", but it shouldn't be empty.
(I briefly scanned where codes.Unavailable is returned, but didn't notice any problem.)

How reliable can you reproduce this? Does it always happen with "transport is closing"?
What's the server you are talking to? Is there a proxy in between?

**Comment by haani-niyaz** [comment]
> Can you confirm that the unavailable error is not returned from the application?

Yes, it is a gRPC error on an attempt to connect to the server. 
 
> How reliable can you reproduce this? Does it always happen with "transport is closing"?

It is consistent. If the client  service is A, it consistently cannot connect to server B (never worked). However, it can connect to server C, D etc. 
"transport is closing" is also returned on successful connections to other servers. 
I enabled gRPC logging on the server which does not produce any logs which tells me the connection is probably failing before it even reaches it.

> What's the server you are talking to? Is there a proxy in between?

This is running inside a k8s cluster with istio proxy sidecar. Although as briefly mentioned above, they all run in the same cluster/namespace and the client service can connect to other gPRC servers successfully.

**Comment by haani-niyaz** [comment]
Further investigation revealed that this was indeed a proxy issue, istio sidecar referencing an invalid virtual service to be exact. gRPC error description is indeed empty in this case.

**Comment by menghanl** [comment]
Thanks for the update. I'm closing the issue now. Please reply if you have further questions.
