### ISSUE TITLE
metadata: support sensitive flag for HPACK encode with Literal Header Field Never Indexed

### ISSUE THREAD

**Issue by KeiichiHirobe** [grpc/grpc-go#4520]
net/http2/hpack supports sensitive.  HeaderField struct has a [field sensitive](https://github.com/golang/net/blob/abc453219eb586afb3fc1742e8c685c28b9f7eea/http2/hpack/hpack.go#L39-L41).

Now,  grpc/go never set sensitive to true, so user can't choose whether to use dynamic table or not.
This leads to evict more useful entries from the dynamic table.

For example, if client must add signature for every request, and header name is `Signature` and header value is `base64(shaHMAC-SHA256(body))`, the size of entry for that header is 9+44+32=85 byte. The default table size is [4096byte](https://github.com/golang/net/blob/abc453219eb586afb3fc1742e8c685c28b9f7eea/http2/hpack/encode.go#L13), so all entries of  dynamic table is evicted unfortunately for every about 50 requests even though entries whose header name is `Signature`  never reused.

If you have no reason for not supporting sensitive flag, I think it would be better for metadata to support sensitive flag option.

**Comment by zasweq** [comment]
Our Metadata API does not support adding flags to Metadata currently. This would require a significant API change.
