### ISSUE TITLE
Add streaming info in stats package

### ISSUE THREAD

**Issue by leviska** [grpc/grpc-go#4526]
### Use case(s) - what problem will this feature solve?

Right now there is no way to determine, is the method unary or streaming inside grpc/stats package  
But it is useful when collecting metrics to know, what kind of method is currently reported, because logic for handling can differ depending on the type of the method

### Proposed Solution

I propose to add two flags for `ClientStream` and `ServerStream` inside [`RPCTagInfo`](https://pkg.go.dev/google.golang.org/grpc/stats#RPCTagInfo) struct like with [`StreamServerInfo`](https://pkg.go.dev/google.golang.org/grpc#StreamServerInfo) struct  
It seems like there is enough information in each call of `TagRPC` to fill these

**Comment by zasweq** [comment]
On the server side, the transport doesn't know if the RPC it is handling is Unary or Streaming. Thus, we cannot add it to RPCTagInfo, but we can add it to stats.Begin.

**Comment by leviska** [comment]
I'll do it myself :)
