### ISSUE TITLE
xds godoc nit: bootstrap example is innacurate

### ISSUE THREAD

**Issue by stevenctl** [grpc/grpc-go#4544]
https://github.com/grpc/grpc-go/blob/5c164e2b8f227a29f4aa6b2de3afb2afa38880ba/xds/internal/xdsclient/bootstrap/bootstrap.go#L130

This doesn't math the `xds_servers` that is actually expected.

**Comment by dfawley** [comment]
@easwars could you take care of updating the comment here, please?
