### ISSUE TITLE
xds: Router filter is required in gRFC and c/c++ client but not in go

### ISSUE THREAD

**Issue by amenzhinsky** [grpc/grpc-go#4547]
Hi there,

We're experiencing inconsistency in go and cpp clients, we have a xDS server that was initially developed for go clients, but now we're trying to use it with a cpp client but it produces the following error `Code: 14 Message: no xDS HTTP router filter configured` 

https://github.com/grpc/proposal/blob/master/A39-xds-http-filters.md#the-router-filter

>  this filter is required and must be last in the filter list

https://github.com/grpc/grpc/blob/v1.38.0/src/core/ext/filters/client_channel/resolver/xds/xds_resolver.cc#L404

I think it has to be obligatory in go as well.

v1.38.0

**Comment by dfawley** [comment]
Interesting, how sure are you about this?  We have a test case for exactly this:

https://github.com/grpc/grpc-go/blob/549c53a90c2a61a4bbe4e067b21f709ead03e2de/xds/internal/resolver/xds_resolver_test.go#L1132-L1141

**Comment by dfawley** [comment]
The fix in #4553 is incomplete; it needs to allow no HTTP filters when using xDS v2.

**Comment by zasweq** [comment]
Fixed by #4676.
