### ISSUE TITLE
Using TLS with xDS resolver/balancer

### ISSUE THREAD

**Issue by grobza** [grpc/grpc-go#4557]
GRPC version 1.38.0
go version 1.16

Hello
I am trying to use GRPC with xDS resolver/balancer with TLS, snippet below (client side)
```
        pemServerCA, err := ioutil.ReadFile(path.Join(certPath, "ca-cert.pem"))
	if err != nil {
		return nil, err
	}

	certPool := x509.NewCertPool()
	if !certPool.AppendCertsFromPEM(pemServerCA) {
		return nil, fmt.Errorf("failed to add server CA's certificate")
	}

	config := &tls.Config{
		RootCAs:      certPool,
	}
        tlsCredentials = credentials.NewTLS(config)

       grpc.Dial("xds:///servername", grpc.WithTransportCredentials(tlsCredentials))
```
I always get `rpc error: code = Unavailable desc = all SubConns are in TransientFailure`

Several point's I like to make:
1. I mean to encrypt the connection between the client and the server, not between client and the xDS-server.
1.1 although if there is a way to use TLS enctyption on client-xDS channel, I'd like to do that too.
2. xDS-server sends valid info about present server instances, and that info is read correctly by `v3.Client`
3. Everything works fine if I switch to `grpc.WithInsecure()` on both sides
4. Everything works fine if I change dial target from `xds:///servername` to `server_ip:port`, e.g. not using xDS resolving

Is there something I am missing? What is the correct way to use GRPC with TLS and xDS discovery?
Thank you

**Comment by menghanl** [comment]
Can you turn on logging: https://github.com/grpc/grpc-go#how-to-turn-on-logging?
What you did should work. If there's a handshake failure, you should be able to find it in the logs.

My guess is that it failed with server name verification. Your cert is signed for `server_ip:port`, but when using xds, it will be verified using `servername`, which will fail.

If that _is_ the cause, I would suggest signing the cert using `servername`, not `ip:port`.
There's also a field `ServerName` in `tls.Config`. gRPC's credentials functions take a parameter to override that name. See how it used: https://github.com/grpc/grpc-go/blob/master/credentials/tls.go#L177

**Comment by grobza** [comment]
Thank you very much, @menghanl 
Your guess turned out to be correct, it was all about CN of the certificate.
