### ISSUE TITLE
Unary gRPC calls is cancelled explicitly but server still receives it  

### ISSUE THREAD

**Issue by ahtsan** [grpc/grpc-go#4577]
I have a client invoking unary gRPC request and retrying when each request times out, like

```
conn, err := grpc.Dial(serverURL, grpc.WithInsecure()
client = NewClient(conn)
...
for i := 1; i <= 10; i++ {
  ctx, cancel := context.WithTimeout(context.Background(), time.Second * 5)
  
  rep, err = UnaryRPC(ctx)
  if err != nil {
    // explicitly cancel the request
    cancel()
    // retry after 5 sec
    time.Sleep(time.Second * 5);
  }
}
```

However, the server is still getting more than one (usually two) RPC calls. I checked all these requests and see if the context is cancelled but all of them are not.

Is this the expected behavior?

**Comment by zasweq** [comment]
By the time that UnaryRPC returns, the RPC call is complete. Thus, with your error check, the unary call was done. This is expected behavior. The cancel() call you have doesn't cancel the call because the call already happened.

**Comment by ahtsan** [comment]
Thanks! As a follow up, when it hits the context timeout, is the gRPC call cancelled? If not, is there any way I can configure gRPC to cancel the request so that server can know that the call is timeout and drop that request?

**Comment by zasweq** [comment]
Yes, assuming the context times out, the gRPC call with be cancelled. From your code, it seems like the call doesn't timeout, but returns an err, and then when you call cancel() you're "cancelling"/collecting things that already happened.

**Comment by ahtsan** [comment]
I didn't see the gRPC call being cancelled on the server side. When the call timeout, I got error code `grpc::UNAVAILABLE`. Can you link me to the relevant source code where gRPC cancels the context when the call is timeout?

**Comment by ahtsan** [comment]
> By the time that UnaryRPC returns, the RPC call is complete. Thus, with your error check, the unary call was done. This is expected behavior. The cancel() call you have doesn't cancel the call because the call already happened.

Even if UnaryRPC timeout, it will return an error right?

**Comment by ahtsan** [comment]
Can you reopen this issue? I think the question is still not answered.

**Comment by ahtsan** [comment]
I've opened another issue and modify the question a bit to make it more clear, thanks!
https://github.com/grpc/grpc-go/issues/4580
