### ISSUE TITLE
Recommended/Safe to use https://github.com/grpc/grpc-go/tree/master/health ?

### ISSUE THREAD

**Issue by amitsaha** [grpc/grpc-go#4585]
Hi - i came across `https://github.com/grpc/grpc-go/tree/master/health` - which is an implementation of the google.golang.org/grpc/health/grpc_health_v1 service. Is it safe/recommended to use that as I couldn't find any user facing documentation around it?

**Comment by easwars** [comment]
Yes, this is safe to use. 

See overall health check documentation here: https://github.com/grpc/grpc/blob/master/doc/health-checking.md
See Go specific doc here: https://pkg.go.dev/google.golang.org/grpc/health

**Comment by amitsaha** [comment]
Thanks.

**Comment by easwars** [comment]
Forgot to mention. We also have an example of setting up the health service here: https://github.com/grpc/grpc-go/tree/master/examples/features/health
HTH.

**Comment by amitsaha** [comment]
Perfect thank you. Is there somewhere in the user facing documentation I can contribute to?

**Comment by easwars** [comment]
> Perfect thank you. Is there somewhere in the user facing documentation I can contribute to?

For the overall [health check doc](https://github.com/grpc/grpc/blob/master/doc/health-checking.md), you could send a PR to the grpc/grpc repo.

For Go specific [package doc](https://pkg.go.dev/google.golang.org/grpc/health), this is generated from the comments in [code](https://github.com/grpc/grpc-go/tree/master/health). If you want that improved, you could send a PR to grpc/grpc-go repo.

And if you would like to improve the [example](https://github.com/grpc/grpc-go/tree/master/examples/features/health), you could send a PR to grpc/grpc-go repo.

Thanks
