### ISSUE TITLE
Always return error nil even server is not available

### ISSUE THREAD

**Issue by surya4crowde** [grpc/grpc-go#4589]
```
conn, err := grpc.Dial("localhost:50051", grpc.WithInsecure())
if err != nil {
    log.Fatalf("Did not connect: %v", err)
}

defer conn.Close()

```

The `if` block is never execute even server is down. This is bug or we need some option to handle it?

**Comment by easwars** [comment]
This is working as intended. `grpc.Dial` returns a `grpc.ClientConn` which is an abstraction of a connection pool and handles many things like connecting to multiple backends, retrying when connections go down etc.

If you want to make sure that at least one connection is up before `grpc.Dial` returns, you could use the [WithBlock](https://pkg.go.dev/google.golang.org/grpc#WithBlock) dial option. In this case though, if the server never comes up, `Dial` will be blocked forever. [DialContext](https://pkg.go.dev/google.golang.org/grpc#DialContext) could be handy.
