### ISSUE TITLE
Client and server stub not getting generated

### ISSUE THREAD

**Issue by mahendrakariya** [grpc/grpc-go#459]
I am trying to generate go code from the proto files. After cloning the repo, I ran the command 
```
./codegen.sh ./examples/route_guide/routeguide/route_guide.proto
``` 

The generated file `route_guide.pb.go` doesn't have the `RouteGuideServer` and `RouteGuideClient` interfaces. The generated code is attached here as [route_guide.pb.go.txt](https://github.com/grpc/grpc-go/files/50605/route_guide.pb.go.txt).

Am I missing something?

**Environment Info:**
OS: OS X 10.9.5 64 bit
Golang version: 1.5.1
protoc version: 3.0.0 (installed via homebrew)

P.S. It's working fine on Ubuntu.

**Comment by iamqizhao** [comment]
I think you do not install https://github.com/golang/protobuf properly.

**Comment by mahendrakariya** [comment]
Reinstalling protobuf solved the problem. Thanks a lot!

**Comment by MarcMagnin** [comment]
Hi,

I have the same issue (Ubuntu 16, Go 1.7, protoc 3)
Any ideas ?

**Comment by MakMukhi** [comment]
Check your protobuf installation. Are there any errors?

**Comment by mangrep** [comment]
same issue

▶ uname -a
Darwin MacBook 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

▶ protoc --version
libprotoc 3.6.1

**Comment by dfawley** [comment]
@mangrep can you be more specific about exactly what command(s) you are running and what error(s) you are getting?

**Comment by mangrep** [comment]
I did not get any error. It just created Java beans. Service class was not created.

**Comment by dfawley** [comment]
@mangrep this is the Go repo, not Java.  Can you file an issue asking for help there?  https://github.com/grpc/grpc-java/issues/new
