### ISSUE TITLE
Connection age context

### ISSUE THREAD

**Issue by ash2k** [grpc/grpc-go#4597]
### Use case(s) - what problem will this feature solve?

I have a server that handles long running bi-directional streams. Clients establishes a connection and then server may eventually have something to reply with. The request may be open for minutes, hours, days. In the middle there is a load balancer so I have to ensure the connection is closed before the timeout setting on the load balancer, otherwise it aborts the connection. To do that server has max connection age set to a number and in addition to that on each request code starts a timing out context. Once it times out, the server just returns `nil` from the handler, closing the connection cleanly. Client sees `io.EOF` and reconnects immediatelly, likely using a different TCP connection.

The problem is that sometimes the server has multiple things to reply with over a period of time that is smaller than max connection age. In this case the underlying TCP connection is reused and my timeout context only signals "done" when it's too late and the max connection age grace has also expired. Actually, the request's context signals sooner than my own context. The client gets an error (`rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data:`) rather than `io.EOF`.

### Proposed Solution

Let the request handler know how much time it can occupy the connection for without breaching the max connection age. Ideally it's a context that is canceled when max connection age duration elapses.

Request context is a different thing. It's "done" when max connection age grace duration elapses and the connection is aborted. Even if handler returns `nil`, client gets an error.

### Alternatives Considered

For now I have came up with a workaround - max poll duration that a handler can wait for an event is just a little under 50% of the max connection age. And then max connection age for gRPC is set to 35% of the max connection age for the load balancer. This way even if some time is "consumed" by the "fast" requests, a long request that starts right before 
max connection age for gRPC expires, can still run for ~50% of time and end without breaching the overall max connection age of the load balancer. 35% is because it's 35% +/- 10% jitter - must be under 50%.

The above works but it's wasteful as connections could be sitting idle for much longer. Instead, both server and client have to do work to re-establish the network and logic connection/etc.

### Additional Context

Fix/workaround is here https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent/-/merge_requests/424, perhaps it can help understand the issue I'm having. Thank you.

**Comment by dfawley** [comment]
> Let the request handler know how much time it can occupy the connection for without breaching the max connection age. Ideally it's a context that is canceled when max connection age duration elapses.

It seems to me a simpler and better option would be to make the client resilient to connections being broken due to an LB timeout, and restarting the stream in that case.  Presumably your client also needs to cope with other types of temporary network hiccups.  I.e. any time you receive an UNAVAILABLE error, simply recreate the stream:

```go
restartRPC:
for {
	ctx, cancel := context.WithCancel(context.Background())
	stream, err := client.MyBiDiStream(ctx)
	if err != nil {
		// Error creating stream. Try again.
		cancel()
		continue
	}
	stream.Send(request)
	for {
		resp, err := stream.Recv()
		if err != nil {
			cancel()
			if err == io.EOF || status.Code(err) == codes.Unavailable {
				// Server ended the RPC early or there was a temporary network issue.
				// Restart the RPC.
				continue restartRPC
			}
			return err  // some other real error from the server
		}
		// Handle resp.
	}
}
```

You would also want to put some backoff in the retrying code above.

**Comment by ash2k** [comment]
> It seems to me a simpler and better option would be to make the client resilient to connections being broken due to an LB timeout, and restarting the stream in that case. Presumably your client also needs to cope with other types of temporary network hiccups. I.e. any time you receive an UNAVAILABLE error, simply recreate the stream:

Thank you for the advice, it makes sense and the client already does all of that. The problem with this situation is that now each client for almost each connection (there are usually no events) eventually gets the `Unavailable` status and my client-side prometheus metrics (that I collect via interceptors) are almost useless because any other `Unavailable` errors are drowned in these "fake" `Unavailable` errors. On the serve side I have a similar situation but with `Canceled` status (if I remember correctly, maybe its `Unavailable` too).

I think my use case is a valid one and it should be possible to gracefully handle "long polling" connections without having to deal with errors for the "normal flow". Thank you!

**Comment by dfawley** [comment]
> my client-side prometheus metrics (that I collect via interceptors) are almost useless

That makes sense.  You could probably use a different metric to determine whether you are experiencing intermittent connectivity issues, e.g. "average long poll stream duration" or look at the rate of Unavailable errors, which should be expected to be approximately once per keepalive time with this solution.

> I think my use case is a valid one and it should be possible to gracefully handle "long polling" connections without having to deal with errors for the "normal flow". Thank you!

Something like this would need to be designed & implemented cross-language.  I'd recommend filing an issue in the main grpc repo for your proposal.

If you want something a little less ideal, but more in line with what I think you are looking for, it could be achieved now by using a stats handler that attaches the connection establishment time to the context from [Handler.TagConn](https://pkg.go.dev/google.golang.org/grpc/stats#Handler).  If the service handler knows how long the keepalive time is set for, it can make sure to terminate all RPCs cleanly after then but before the grace period expires.  Note, however, that the stats handler APIs are technically experimental and subject to breaking changes.

**Comment by ash2k** [comment]
Thanks, I'll try the `TagConn` approach, it should work better than what I have. I've created the feature request issue too. Cheers.
