### ISSUE TITLE
Inconsistent client connection.

### ISSUE THREAD

**Issue by martindekov** [grpc/grpc-go#4599]
Hello, thanks for the awesome project. The general context is that I cannot consistently create a connection and execute requests against a very simple grpc server. There is *consistent* connection refused error which leaks in the test I've written and *sometimes* the error is returned to the client and I am not sure why this happens.

### What version of gRPC are you using?

v1.39.0

### What version of Go are you using (`go version`)?

go version go1.14.15 linux/amd64

### What operating system (Linux, Windows, …) and version?

Linux
```
Operating System: Ubuntu 18.04.5 LTS
Kernel: Linux 4.15.0-147-generic
```
Docker container:
```
https://hub.docker.com/layers/golang/library/golang/1.14.15/images/sha256-93dd6ad8909cb192a2a0f113521d4ec08e9dd35d02d33e4ae1eca2db3c269eff?context=explore
```

### What did you do?

I've written a basic GRPC server with contains a single method which contains a single object in the request body. I will omit the details around that, as they are redundant, the method and body are basically HelloWorld but the steps on creation of the server and the connection are as follow:

1. Started up GRPC server the following two ways:
```
                lis, err := net.Listen("tcp", ":11111")
		if err != nil {
			return fmt.Errorf("%v", err)
		}
		if err := s.grpcServer.Serve(lis); err != nil {
			return fmt.Errorf("%v", err)
		}
		return nil
```
as alternative tried:
```
		lis, err := net.Listen("tcp", "0.0.0.0:11111")
		...
```
2. Created a client with the following connection configuration:
```
                dialCtx, cancel := context.WithTimeout(context.Background(),
			time.Second*s.dialTimeout)
		defer cancel()
		conn, err := grpc.DialContext(dialCtx, "127.0.0.1:11111", grpc.WithInsecure())
		if err != nil {
			return err
		}
```
3. Instantiated client and created a request agains the server with the client (I pointed 127.0.0.1 explicitly as I saw basically the same issue here: https://github.com/grpc/grpc-go/issues/2678)
4. Enabled debug logging through `GRPC_GO_LOG_VERBOSITY_LEVEL=99` `GRPC_GO_LOG_SEVERITY_LEVEL=info`
5. Written a test which starts up the server and executes a request with the code mentioned above.
6. Saw the logs:
```
...
INFO: 2021/07/16 11:09:00 [core] parsed scheme: ""
INFO: 2021/07/16 11:09:00 [core] scheme "" not registered, fallback to default scheme
INFO: 2021/07/16 11:09:00 [core] ccResolverWrapper: sending update to cc: {[{127.0.0.1:11111  <nil> 0 <nil>}] <nil> <nil>}
INFO: 2021/07/16 11:09:00 [core] ClientConn switching balancer to "pick_first"
INFO: 2021/07/16 11:09:00 [core] Channel switches to new LB policy "pick_first"
INFO: 2021/07/16 11:09:00 [core] Subchannel Connectivity change to CONNECTING
INFO: 2021/07/16 11:09:00 [core] blockingPicker: the picked transport is not ready, loop back to repick
INFO: 2021/07/16 11:09:00 [core] Subchannel picks a new address "127.0.0.1:11111" to connect
WARNING: 2021/07/16 11:09:00 [core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:11111 127.0.0.1:11111 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:11111: connect: connection refused". Reconnecting...
INFO: 2021/07/16 11:09:00 [core] Subchannel Connectivity change to TRANSIENT_FAILURE
INFO: 2021/07/16 11:09:00 [core] pickfirstBalancer: UpdateSubConnState: 0xc0001ac6f0, {CONNECTING <nil>}
INFO: 2021/07/16 11:09:00 [core] Channel Connectivity change to CONNECTING
INFO: 2021/07/16 11:09:00 [core] pickfirstBalancer: UpdateSubConnState: 0xc0001ac6f0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:11111: connect: connection refused"}
INFO: 2021/07/16 11:09:00 [core] Channel Connectivity change to TRANSIENT_FAILURE
INFO: 2021/07/16 11:09:01 [core] Subchannel Connectivity change to CONNECTING
INFO: 2021/07/16 11:09:01 [core] Subchannel picks a new address "127.0.0.1:11111" to connect
INFO: 2021/07/16 11:09:01 [core] pickfirstBalancer: UpdateSubConnState: 0xc0001ac6f0, {CONNECTING <nil>}
INFO: 2021/07/16 11:09:01 [core] Channel Connectivity change to CONNECTING
INFO: 2021/07/16 11:09:01 [core] Subchannel Connectivity change to READY
INFO: 2021/07/16 11:09:01 [core] pickfirstBalancer: UpdateSubConnState: 0xc0001ac6f0, {READY <nil>}
INFO: 2021/07/16 11:09:01 [core] Channel Connectivity change to READY
INFO: 2021/07/16 11:09:03 [core] Channel Connectivity change to SHUTDOWN
INFO: 2021/07/16 11:09:03 [core] Subchannel Connectivity change to SHUTDOWN
...
```
7. The test sometimes lets: `connect: connection refused` slip and fails (around 25% of the time) and the other sometimes it retries (I think it retries successfully, but not sure what it does behind the scenes).

### What did you expect to see?

Consistent establishing connection with the server and no errors like: 
1. `Subchannel Connectivity change to TRANSIENT_FAILURE`
2. `grpc: addrConn.createTransport failed to connect to {127.0.0.1:11111 127.0.0.1:11111 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:11111: connect: connection refused". Reconnecting...`

GRPC have consistent behavior in terms of establishing a client connection and my simple request passing 100% of the time

### What did you see instead?

Inconsistent client establishing connection with the server the following errors are always present:
1. `Subchannel Connectivity change to TRANSIENT_FAILURE`
2. `grpc: addrConn.createTransport failed to connect to {127.0.0.1:11111 127.0.0.1:11111 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:11111: connect: connection refused". Reconnecting...`

My test which starts the server and sends a simple request with the code excerpt I showed above is inconsistent. The failure can be seen both in docker container and on my local linux machine.

### What I've tried
* Binding server startup to `0.0.0.0:<port>` explicitly.
* Creating a client explicitly with `127.0.0.1:<port>` `localhost:<port>` `0.0.0.0:<port>`
* Different dial options like `grpc.FailOnNonTempDialError(true)` `grpc.WithBlock()`
* Different request dial options like `grpc.WaitForReady(true)`
* Assign random port so no collisions happen, though I believe there is explicit error when you start up grpc server on port that's already taken.

**Comment by martindekov** [comment]
Also as this is in my interest I would like to step forward and propose a helping hand and submit a fix for the issue in case there is such and it's not a problem with the way I start the server or instantiate the connection for the client. I can work with someone to navigate me where the problem might be in case you have slack channel or any other communication channel apart from the github issues.

**Comment by dfawley** [comment]
> ```
> WARNING: 2021/07/16 11:09:00 [core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:11111 127.0.0.1:11111 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:11111: connect: connection refused". > Reconnecting...
> INFO: 2021/07/16 11:09:00 [core] Subchannel Connectivity change to TRANSIENT_FAILURE
> INFO: 2021/07/16 11:09:00 [core] pickfirstBalancer: UpdateSubConnState: 0xc0001ac6f0, {CONNECTING <nil>}
> INFO: 2021/07/16 11:09:00 [core] Channel Connectivity change to CONNECTING
> INFO: 2021/07/16 11:09:00 [core] pickfirstBalancer: UpdateSubConnState: 0xc0001ac6f0, {TRANSIENT_FAILURE connection > error: desc = "transport: Error while dialing dial tcp 127.0.0.1:11111: connect: connection refused"}
> INFO: 2021/07/16 11:09:00 [core] Channel Connectivity change to TRANSIENT_FAILURE
> INFO: 2021/07/16 11:09:01 [core] Subchannel Connectivity change to CONNECTING
> INFO: 2021/07/16 11:09:01 [core] Subchannel picks a new address "127.0.0.1:11111" to connect
> INFO: 2021/07/16 11:09:01 [core] pickfirstBalancer: UpdateSubConnState: 0xc0001ac6f0, {CONNECTING <nil>}
> INFO: 2021/07/16 11:09:01 [core] Channel Connectivity change to CONNECTING
> INFO: 2021/07/16 11:09:01 [core] Subchannel Connectivity change to READY
> ```

It almost seems like you are having some kind of intermittent problem on your local machine, and when it occurs, the connection fails.  When this happens, there is now a race: if the RPC is issued quickly enough (at 11:09:00 above), then the RPC will fail instantly because the channel is in TRANSIENT_FAILURE.  But if the RPC is issued 1s later (or maybe even sooner?), then the RPC will succeed.  Obviously, if the issue does not occur, then the connection is successful from the start and the RPC succeeds.

I'm not really sure how to debug the cause of that intermittent connection issue.  There might be something in your kernel logs when this occurs?

Can you post a version of your test that shows the problem that we can run?

**Comment by martindekov** [comment]
Thanks for the input @dfawley really appreciate it. After your response and a little bit of digging I’ve started adding logs and I found out that the issue is present in case the server is not started and after `s.grpcServer.Serve(lis)` is called (server is ready), the error disappears. I still see the error in the logs before that though, but now I realise that the error is there due to server not being started yet and I fixed my test to wait.

Now I do believe we can improve the code base either by updating the [debugging page](https://github.com/grpc/grpc-go/tree/master/examples/features/debugging) to include comment about how the logs should be red. I though `[core]` denotes logs from the backend and `[transport]` denotes logs from the client and since I am starting the client and server as part of the same test I was confused.

Another thing would be adding a sentence in the [readme](https://github.com/grpc/grpc-go#the-rpc-failed-with-error-code--unavailable-desc--transport-is-closing) that `connection refused` error might potentially be connected with the server not being started similar to how its noted for the `transport is closing` scenario.

Alternative is to augment the error with more information given the context in which the warning is logged so if I am looking at the logs I can see that this is happening probably due to my server not being started.

Anyways feel free to close this in case my proposals above are not in line with the project's goals. I just decided to give my input and experience in the role of a fresh user in case it helps.

**Comment by dfawley** [comment]
> I still see the error in the logs before that though, but now I realise that the error is there due to server not being started yet and I fixed my test to wait.

FWIW, one way to fix this would be to use `grpc.WaitForReady` on your RPC - then it won't fail if there isn't a connection until the RPC's deadline.

I'm fine with adding more information to the debugging doc / README, if you'd like to send a PR.  For the errors / log messages themselves, I'm not sure we want to add things like "(Is your server started?)" to the error messages, because there are other reasons you might get "connection refused" errors, and we don't have room to list all of them.  Searching Google for "why connection refused" gives something extremely helpful right at the top:

> Connection refused means that the port you are trying to connect to is not actually open. So either you are connecting to the wrong IP address, or to the wrong port, or the server is listening on the wrong port, or is not actually running.
