### ISSUE TITLE
Stream handling differences between Java and Go

### ISSUE THREAD

**Issue by jronak** [grpc/grpc-go#4608]
Unary/Server streaming method handling seems to be different between Go and Java. In Go server stream internal handler receives a message and immediately invokes the service handler, whereas the Java server stream handler waits until the stream half-closes and then invokes the service handler. If the client sends more than one message, the [Java server](https://github.com/grpc/grpc-java/blob/d4fa0ecc07495097453b0a2848765f076b9e714c/stub/src/main/java/io/grpc/stub/ServerCalls.java#L131) rejects with `TOO_MANY_REQUESTS` error description while Go does not. 

I stumbled upon this when my custom gRPC client worked fine with Go servers, but it failed with deadline-exceeded errors with Java servers. Eventually figured Java expects a half-closed connection before invoking the handler. 

Shouldn't the handling remain consistent across gRPC servers?

**Comment by menghanl** [comment]
The server side behavior might be different. But the overall behavior should be the same.
Go's server doesn't check for multiple messages in ServerStreaming, but the client `send` checks for that: https://github.com/grpc/grpc-go/blob/master/stream.go#L765

And the generate code calls `CloseSend()` for you: https://github.com/grpc/grpc-go/blob/master/examples/route_guide/routeguide/route_guide_grpc.pb.go#L77

Can you provide a small reproduction? Or just show what your client code looks like?

**Comment by menghanl** [comment]
I just noticed that you mentioned "custom gRPC client".
I don't think there's a detailed spec documenting the RPC behaviors, but at high level, client should only send one message in unary/server-streaming.
