### ISSUE TITLE
Append Metadata after Pick Node

### ISSUE THREAD

**Issue by storyicon** [grpc/grpc-go#4612]
When I customized the load balancer, I found that: `PickInfo` of `balancer.Picker` has the Context for the RPC request, but I can't modify the metadata at `Pick` time by a method like `metadata.AppendToOutgoingContext`.
Is there any way to modify the request metadata based on the selected node (eg: during load balancing)?
If not, do you have any plans to provide support?

**Comment by storyicon** [comment]
So far I've found that I can modify it to some extent with `FromOutgoingContextRaw`.

**Comment by menghanl** [comment]
Picker doesn't have much ability to alter the RPC.
Can you explain what metadata you are trying to append, and what purpose they are for?
