### ISSUE TITLE
Returning a service config from a manual resolver is hard

### ISSUE THREAD

**Issue by Jille** [grpc/grpc-go#4618]
[X] Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?
I'm using a manual resolver and I want to tell gRPC to use a custom balancer as well. This can be achieved by setting ServiceConfig in resolver.State, but there is no way to create a *serviceconfig.ParseResult. https://github.com/grpc/grpc-go/blob/ebf6a4b476dc7c1bcb57c82e9c74529a7f046710/service_config.go#L223 does it, but is a private function.

### Proposed Solution
Should we simply expose parseServiceConfig from https://github.com/grpc/grpc-go/blob/ebf6a4b476dc7c1bcb57c82e9c74529a7f046710/service_config.go#L223 ?

### Alternatives Considered

My application can use grpc.WithDefaultServiceConfig() but it seems less clean.

**Comment by menghanl** [comment]
`parseServiceConfig` is exported as part of the `resolver.ClientConn` interface: https://github.com/grpc/grpc-go/blob/master/resolver/resolver.go#L202
With manual resolver, it's accessible as `r.CC` after `Build()`.

> My application can use grpc.WithDefaultServiceConfig() but it seems less clean.

Why do you think this is less clean? If there's no intention to update the balancer, this should work just fine.
