### ISSUE TITLE
how to decrease the proto feature

### ISSUE THREAD

**Issue by ohmygd** [grpc/grpc-go#4619]
my company's online project , use grpc to communicate, but there has some useless filed just like
message A{
   int64 a =1;
   string b=2;
   repeated string c = 3;
}
client and server are all this, but if b which i want to decrease, it would be 
message A{
   int64 a =1;
   repeated string c = 2;
}
when the project goes on, if the server and client, one is old, one is new
their communication will occur en error
rpc error: code = Internal desc = grpc: error unmarshalling request: proto: wrong wireType = 0 for field

but my project can't obey this.

there is no answer online, please help
my grpc version is v1.29.1

**Comment by menghanl** [comment]
Don't change the field number.
https://developers.google.com/protocol-buffers/docs/proto#assigning_field_numbers

```
message A{
  int64 a =1;
  repeated string c = 3; // Keep using 3, not 2
}
```

You may also want to mark `2` as reserved, so it's not accidentally used

```
message A{
  int64 a =1;
  repeated string c = 3;

  reserved 2;
}
```
