### ISSUE TITLE
benchmark crash when runtime.GOMAXPROCS(runtime.NumCPU())

### ISSUE THREAD

**Issue by peanutgyz** [grpc/grpc-go#462]
how to run benchmark with more than 1 CPU ?

2015/12/11 20:14:31 Client profiling address:  [::]:56108
2015/12/11 20:14:31 StreamingCall(_).Send: rpc error: code = 1 desc = "context canceled"

**Comment by peanutgyz** [comment]
use grpc-go/benchmark/server/main.go  and  client/main.go
when runtime.GOMAXPPROCS(runtime.NumCPU()), benchmark failed. 
and go 1.5 also fail

**Comment by iamqizhao** [comment]
it runs fine on my desktop by setting  runtime.GOMAXPPROCS(runtime.NumCPU()) on both client and server. I guess probably you let your client talk to a wrong port on server (maybe you use the profiling port)?

**Comment by peanutgyz** [comment]
crash when use stream mode. 
try set rpc_type =1 ?

**Comment by peanutgyz** [comment]
![image](https://cloud.githubusercontent.com/assets/4225291/11953898/e3f89fb0-a8de-11e5-9f8b-dd0ddfc0b7ed.png)
