### ISSUE TITLE
Long term support for ServeHTTP interface?

### ISSUE THREAD

**Issue by a-feld** [grpc/grpc-go#4620]
Hi There! I'm working on the [OpenTelemetry Collector project](https://github.com/open-telemetry/opentelemetry-collector). For a variety of reasons, there is a desire to use the [Server.ServeHTTP](https://github.com/grpc/grpc-go/blob/1ddab338690a578975747239ad4ecd2ae63b1965/server.go#L955-L994) interface, however the interface is marked as experimental today.

Are there any current plans to remove or change this interface?

Any objections to marking this interface as supported rather than experimental?

**Comment by zasweq** [comment]
Long term, there are no plans to change this interface or change any functionality. Due to this, it will stay experimental.

**Comment by punya** [comment]
@zasweq could you explain the rationale a bit more? If there's no plan to change it, then wouldn't that make it stable rather than experimental?

**Comment by zasweq** [comment]
This API is marked as experimental as it's something that's been there for a while...but it's an eh in terms of how the team feels about it, and there are no plans to touch that codepath/actively develop on it.

**Comment by menghanl** [comment]
This API has its problems (as mentioned in its godoc). We don't want to encourage people to use it.

What do you need it for?
Is it for port sharing (between gRPC and http)? The general solution for that is to put a mux (e.g. https://github.com/soheilhy/cmux) in front of the server.

**Comment by menghanl** [comment]
Closing this after offline discussion (several days ago). See #906 for custom transport.
