### ISSUE TITLE
Get ip on client side

### ISSUE THREAD

**Issue by Jiw0cha** [grpc/grpc-go#4637]
Hello.

Pseudo code:
```conn, _ := grpc.Dial(`127.0.0.1:80`, opts...)
localAddr := conn.LocalAddr()```

Is there a way to get ip address on client side?

**Comment by easwars** [comment]
A `ClientConn` represents a virtual connection to a conceptual endpoint, to perform RPCs. We do not expose information about the local address. In fact, the `ClientConn` is free to have more than one connection to the actual endpoint.

Could you give us more information about what you are trying and why you require the local IP on the client side?

**Comment by Jiw0cha** [comment]
> why you require the local IP on the client side?

Use NAT or not.

**Comment by Jiw0cha** [comment]
@easwars

**Comment by easwars** [comment]
> > why you require the local IP on the client side?
> 
> Use NAT or not.

What do you expect to do based on whether you are running behind a NAT or not? Please provide as much information as possible for us to be able to help you.
