### ISSUE TITLE
go-control-plane protobuf lib upgrade

### ISSUE THREAD

**Issue by alecholmez** [grpc/grpc-go#4640]
We're looking to upgrade the underlying protobuf libraries in go-control-plane and we were curious if doing so would break some of the backwards compatibility upstream. I've opened this [PR](https://github.com/envoyproxy/go-control-plane/pull/480) which address some of the lower hanging fruit but the protobuf generation will need to be address as well. `github.com/golang/protobuf` has been mostly deprecated and I'd like to move off of it.

@dfawley any thoughts?

**Comment by dfawley** [comment]
The new generated code should work seamlessly with existing code using the old generated code.  We switched to the new codegen awhile back in this repo in #3932.  There were some minor string formatting differences which that PR had to work around for our tests, but production code shouldn't be relying upon proto->string formatting.

Thanks for checking in first.

**Comment by alecholmez** [comment]
Great thanks @dfawley!
