### ISSUE TITLE
A warning that I don’t know how to correct

### ISSUE THREAD

**Issue by leolin49** [grpc/grpc-go#4648]
I use vscode. I defined a structure in the proto file and tried to encode with json. vscode raised this warning. How can I correct it?

![image](https://user-images.githubusercontent.com/58925286/128153848-437b1df2-eed8-4e7a-bc98-f51483ea3991.png)

call of json.Marshal copies lock value: paopao/server/usercmd.RoomServerInfo contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex

**Comment by easwars** [comment]
This doesn't look like it is a gRPC-Go issue.

In general, you cannot copy a struct which contains a `sync.Mutex`. You need to use a pointer to that struct instead.
