### ISSUE TITLE
ServerStream.Recv () could not be interrupted or cancelled

### ISSUE THREAD

**Issue by wencan** [grpc/grpc-go#465]
ServerStream.Recv () can not be interrupted or canceled

In multiple coroutines environment, it is very important

**Comment by iamqizhao** [comment]
I do not quite get it. Can you elaborate what you want and why you think the current code cannot achieve?

**Comment by wencan** [comment]
such as: Close, Cancel, setDeadLine

**Comment by bradfitz** [comment]
Use `context.WithCancel` and call the `CancelFunc` to abort a long-lived operation.

**Comment by tamird** [comment]
@bradfitz where do you pass the context?

**Comment by xiang90** [comment]
@tamird We have to call stream.Close or cancel the context of the entire stream to stop recv. But this will destroy the stream...

**Comment by tamird** [comment]
Ah, yes. Interrupting Recv on either client or server is not possible without tearing down the stream.

Still, how do you even cancel the stream's context? How do you get the cancel function?

**Comment by xiang90** [comment]
@tamird 
https://github.com/coreos/etcd/blob/master/clientv3/lease.go#L343-L344

**Comment by tamird** [comment]
Right, that's on the client. How about on the server?

**Comment by xiang90** [comment]
@tamird Sorry. I should have checked your previous comment more carefully. On server side, we cannot... We just spin a routine to close the stream at server side when receive the rpc call.

**Comment by iamqizhao** [comment]
On server side, exiting from the service handler is the way to go. You can run Recv in a separate goroutine spawn in the service handler. Once the service handler is returned, Recv is interrupted.

Beyond this, we will flesh out a service interceptor mechanism so that you will have more different ways to achieve this.

**Comment by erikfrey** [comment]
Similarly, I'd love to be able to cancel a ServerStream SendMsg from a client that's hung, but it's not clear how.

I was excited to find that I could grab the underlying transport stream by calling StreamFromContext but it seems you've purposefully chosen not to expose the cancel func.

Canceling a misbehaving client seems like a common need - what's the right way to do this?

**Comment by tamird** [comment]
Cancelling from the client can be done by cancelling the RPC context you
passed in.

Cancelling from the server can be done by returning from the handler
method. That means you'll need to call Recv() from a different goroutine.

**Comment by ldelossa** [comment]
Does a cancel of the context on the client side evaluate to an io.EOF error?

For example

...
```
func (c *Client) Proxy() {
	// begin proxy loop
	for {
		msg, err := c.stream.Recv()
		if err != nil {
			if err == io.EOF {
				log.Printf("received EOF. stream closed. exiting proxy loop")
				return
			}
			log.Printf("failed to call Recv on stream: %s", err)
			continue
		}
```

Is valid to remove me from my loop if I was to call "cancel" in the main go routine?
