### ISSUE TITLE
K8S rolling update will cause client side unavailable error

### ISSUE THREAD

**Issue by hijerusalem** [grpc/grpc-go#4650]
### What version of gRPC are you using?
1.36.0

### What version of Go are you using (`go version`)?
1.16.0

### What did you do?
Both client and server run in K8S

Client requests headless gRPC service in a loop, while grpc server is performing a rolling update

Client load balancing policy: round robin

Client GRPC_GO_RETRY: on

Client minDNSResRate: 30s

Number of server pod: 1

Server MaxConnectionAge: 120s

Server MaxConnectionAgeGrace: 500ms

Server pod preStop hook: sleep 40s

Server pod terminationGracePeriodSeconds: 50s

Server rolling update maxUnavailable: 25%

Server rolling update maxSurge: 25%

CoreDNS server cache: 5s

### What did you expect to see?
Upon receiving a connection refused, DNS should be re-queried for an updated endpoint list and client should connect to new endpoint retry failed RPC
### What did you see instead?
```rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing dial tcp 10.244.1.47:9000: connect: connection refused"```

###  log:
```
INFO: 2021/08/05 14:50:08 [core] parsed scheme: "dns"
INFO: 2021/08/05 14:50:08 [core] ccResolverWrapper: sending update to cc: {[{10.244.1.47:9000  <nil> 0 }]  }
INFO: 2021/08/05 14:50:08 [core] ClientConn switching balancer to "round_robin"
INFO: 2021/08/05 14:50:08 [core] Channel switches to new LB policy "round_robin"
INFO: 2021/08/05 14:50:08 [balancer] base.baseBalancer: got new ClientConn state:  {{[{10.244.1.47:9000  <nil> 0 }]  } }
INFO: 2021/08/05 14:50:08 [core] Subchannel Connectivity change to CONNECTING
INFO: 2021/08/05 14:50:08 [balancer] base.baseBalancer: handle SubConn state change: 0xc00007f200, CONNECTING
INFO: 2021/08/05 14:50:08 [core] Channel Connectivity change to CONNECTING
INFO: 2021/08/05 14:50:08 [core] Subchannel picks a new address "10.244.1.47:9000" to connect
INFO: 2021/08/05 14:50:08 [core] Subchannel Connectivity change to READY
INFO: 2021/08/05 14:50:08 [balancer] base.baseBalancer: handle SubConn state change: 0xc00007f200, READY
INFO: 2021/08/05 14:50:08 [roundrobin] roundrobinPicker: newPicker called with info: {map[0xc00007f200:{{10.244.1.47:9000  <nil> 0 }}]}
INFO: 2021/08/05 14:50:08 [core] Channel Connectivity change to READY

INFO: 2021/08/05 14:51:08 [core] Subchannel Connectivity change to CONNECTING
INFO: 2021/08/05 14:51:08 [balancer] base.baseBalancer: handle SubConn state change: 0xc00007f200, CONNECTING
INFO: 2021/08/05 14:51:08 [roundrobin] roundrobinPicker: newPicker called with info: {map[]}
INFO: 2021/08/05 14:51:08 [core] blockingPicker: the picked transport is not ready, loop back to repick
INFO: 2021/08/05 14:51:08 [core] Channel Connectivity change to CONNECTING
INFO: 2021/08/05 14:51:08 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
INFO: 2021/08/05 14:51:08 [core] Subchannel picks a new address "10.244.1.47:9000" to connect
WARNING: 2021/08/05 14:51:08 [core] grpc: addrConn.createTransport failed to connect to {10.244.1.47:9000 grpc-headless.default.svc:9000 <nil> 0 }. Err: connection error: desc = "transport: Error while dialing dial tcp 10.244.1.47:9000: connect: connection refused". Reconnecting...
INFO: 2021/08/05 14:51:08 [core] Subchannel Connectivity change to TRANSIENT_FAILURE
INFO: 2021/08/05 14:51:08 [balancer] base.baseBalancer: handle SubConn state change: 0xc00007f200, TRANSIENT_FAILURE
INFO: 2021/08/05 14:51:08 [core] Channel Connectivity change to TRANSIENT_FAILURE

2021/08/05 14:51:08 Looping err: rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing dial tcp 10.244.1.47:9000: connect: connection refused"

INFO: 2021/08/05 14:51:08 [core] ccResolverWrapper: sending update to cc: {[{10.244.6.52:9000  <nil> 0 }]  }
INFO: 2021/08/05 14:51:08 [balancer] base.baseBalancer: got new ClientConn state:  {{[{10.244.6.52:9000  <nil> 0 }]  } }
INFO: 2021/08/05 14:51:08 [core] Subchannel Connectivity change to CONNECTING
INFO: 2021/08/05 14:51:08 [core] Subchannel Connectivity change to SHUTDOWN
INFO: 2021/08/05 14:51:08 [balancer] base.baseBalancer: handle SubConn state change: 0xc000d3d0a0, CONNECTING
INFO: 2021/08/05 14:51:08 [core] Subchannel picks a new address "10.244.6.52:9000" to connect
INFO: 2021/08/05 14:51:08 [core] Channel Connectivity change to CONNECTING
INFO: 2021/08/05 14:51:08 [balancer] base.baseBalancer: handle SubConn state change: 0xc00007f200, SHUTDOWN
INFO: 2021/08/05 14:51:08 [core] Subchannel Connectivity change to READY
INFO: 2021/08/05 14:51:08 [balancer] base.baseBalancer: handle SubConn state change: 0xc000d3d0a0, READY
INFO: 2021/08/05 14:51:08 [roundrobin] roundrobinPicker: newPicker called with info: {map[0xc000d3d0a0:{{10.244.6.52:9000  <nil> 0 }}]}
INFO: 2021/08/05 14:51:08 [core] Channel Connectivity change to READY
INFO: 2021/08/05 14:51:09 [core] Channel Connectivity change to SHUTDOWN
INFO: 2021/08/05 14:51:09 [core] Subchannel Connectivity change to SHUTDOWN
```

From 14:50:08 to 14:51:08 several things happened 
1. New server pod created ip: 10.244.6.52
2. New server pod ready ip: 10.244.6.52,  CoreDNS notified about address change
3. Old server pod marked as terminating ip: 10.244.1.47, CoreDNS notified about address change
4. Old server pod preStop hook triggered (sleep 40s, kubelete will wait 40s then send SIGTERM), while old pod serving requests normally as expected
5. After 40s, old server pod received SIGTERM，exit

After step 5, grpc client received connection error,  I expected it would requery DNS to discover new address first then try to connect to address returned by DNS server, but it didn't, it still tried to connect to old server pod(10.244.1.47) which was destroyed already.

**Comment by easwars** [comment]
From the logs you provided, the gRPC client initially had a successful connection to your old pod address
```
INFO: 2021/08/05 14:50:08 [core] Subchannel picks a new address "10.244.1.47:9000" to connect
INFO: 2021/08/05 14:50:08 [core] Subchannel Connectivity change to READY
```

It then sees the connection being closed, and attempts to reconnect, but that attempt is refused. So the connectivity state moved to transient_failure
```
INFO: 2021/08/05 14:51:08 [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
INFO: 2021/08/05 14:51:08 [core] Subchannel picks a new address "10.244.1.47:9000" to connect
WARNING: 2021/08/05 14:51:08 [core] grpc: addrConn.createTransport failed to connect to {10.244.1.47:9000 grpc-headless.default.svc:9000 <nil> 0 }. Err: connection error: desc = "transport: Error while dialing dial tcp 10.244.1.47:9000: connect: connection refused". Reconnecting...
INFO: 2021/08/05 14:51:08 [core] Subchannel Connectivity change to TRANSIENT_FAILURE
```

It then gets the new pod address from the resolver, and connectivity state moved to connecting
```
INFO: 2021/08/05 14:51:08 [core] ccResolverWrapper: sending update to cc: {[{10.244.6.52:9000  <nil> 0 }]  }
INFO: 2021/08/05 14:51:08 [balancer] base.baseBalancer: got new ClientConn state:  {{[{10.244.6.52:9000  <nil> 0 }]  } }
INFO: 2021/08/05 14:51:08 [core] Subchannel Connectivity change to CONNECTING
```

We see the old connection moving to shutdown:
```
INFO: 2021/08/05 14:51:08 [core] Subchannel Connectivity change to SHUTDOWN
```

And the new one moving to ready:
```
INFO: 2021/08/05 14:51:08 [roundrobin] roundrobinPicker: newPicker called with info: {map[0xc000d3d0a0:{{10.244.6.52:9000  <nil> 0 }}]}
INFO: 2021/08/05 14:51:08 [core] Channel Connectivity change to READY
```

And we see the gRPC ClientConn being shutdown here:
```
INFO: 2021/08/05 14:51:09 [core] Channel Connectivity change to SHUTDOWN
```

Is your application shutting down the gRPC client for some reason?

**Comment by easwars** [comment]
@menghanl @dfawley 
I think the following log messages should have some identifier in them, otherwise it is really hard to figure out which channel/subChannel's state is changing:
```
INFO: 2021/08/05 14:51:09 [core] Channel Connectivity change to SHUTDOWN
INFO: 2021/08/05 14:51:09 [core] Subchannel Connectivity change to SHUTDOWN
```

**Comment by hijerusalem** [comment]
```
for i := 0; i < loopTimes; i++ {
				request := &ip.GetLocationRequest{Ip: ip}
				_, err := client.GetLocation(context.Background(), request)
				if err != nil {
					log.Printf("Looping err: %v", err) //err is Unavailable in my case
					time.Sleep(time.Second)
					conn.Close()
					break
				}
			}
```
Upon receiving err returned by grpc client, application code will sleep 1 sec and close connection which shuts down the channel.

From the log,  gRPC discovered new pod address after returning unavailable err to application code


```
2021/08/05 14:51:08 Looping err: rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing dial tcp 10.244.1.47:9000: connect: connection refused"

INFO: 2021/08/05 14:51:08 [core] ccResolverWrapper: sending update to cc: {[{10.244.6.52:9000  <nil> 0 }]  }
INFO: 2021/08/05 14:51:08 [balancer] base.baseBalancer: got new ClientConn state:  {{[{10.244.6.52:9000  <nil> 0 }]  } }
INFO: 2021/08/05 14:51:08 [core] Subchannel Connectivity change to CONNECTING
```

**Comment by easwars** [comment]
The DNS resolver implementation in gRPC-Go waits for configured duration, `minDNSResRate` which is set to `30s`, before attempting to perform a DNS resolution when asked to do so by the `ClientConn`. This is to prevent the resolver from constantly performing re-resolutions.

**Comment by easwars** [comment]
You *should* not close your `ClientConn` unless you plan not to use it anymore. A `ClientConn` can handle connections going down and coming up, and will return appropriate errors for your RPCs if the connections are down.

**Comment by hijerusalem** [comment]
> The DNS resolver implementation in gRPC-Go waits for configured duration, `minDNSResRate` which is set to `30s`, before attempting to perform a DNS resolution when asked to do so by the `ClientConn`. This is to prevent the resolver from constantly performing re-resolutions.

I understand there is certain limitation for DNS query frequency and I listed it in `What did you do` section

From the log, the first dns resolution happened at 2021/08/05 14:50:08
```
INFO: 2021/08/05 14:50:08 [core] ccResolverWrapper: sending update to cc: {[{10.244.1.47:9000  <nil> 0 }]  }
```
Since then, client connected to 10.244.1.47:9000 sending RPCs receiving responses, no DNS re-resolution as expected until
`INFO: 2021/08/05 14:51:08` when old exited connection was shut down.

Because

(a) connection was shutdown (b) 14:51:08- 14:50:08=60s> minDNSResRate=30s,

so gRPC could perform a DNS re-resolution at this point of time and it did **after returning an Unavailable error to application code at the same second** with `GRPC_GO_RETRY=on`

```
2021/08/05 14:51:08 Looping err: rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing dial tcp 10.244.1.47:9000: connect: connection refused"
INFO: 2021/08/05 14:51:08 [core] ccResolverWrapper: sending update to cc: {[{10.244.6.52:9000  <nil> 0 }]  }
```

At 14:51:08 if client **re-resolve DNS before returning Unavailable to application**, (two conditions were met, legal to do DNS lookup), it would discover new healthy server pod and there wouldn't be an Unavailable error. 

Maybe there is an order issue?



> You _should_ not close your `ClientConn` unless you plan not to use it anymore. A `ClientConn` can handle connections going down and coming up, and will return appropriate errors for your RPCs if the connections are down.

I initialize an `ClientConn` as a local variable in a test function so I close it when any gRPC error occours and return

**Comment by easwars** [comment]
> At 14:51:08 if client re-resolve DNS before returning Unavailable to application, (two conditions were met, legal to do DNS lookup), it would discover new healthy server pod and there wouldn't be an Unavailable error.

gRPC *does* attempt to re-resolve. But this is clearly a special case where there is a single backend. gRPC cannot wait for the re-resolution to happen before attempting to reconnect to other existing backends. So, both of these happen in parallel. And in this case, the reconnect finishes first with a connection refused error. 

I have summarized the issue in greater detail along with a potential suggestion to workaround this issue. I'm going to close this as there is not much more that can be done here. Thanks.


```
INFO: 2021/08/05 14:50:08 [core] Channel Connectivity change to READY
```
At this point, the `ClientConn` is in READY state. The dns resolver will block at this point waiting for either a resolution request from gRPC or a close.

```
INFO: 2021/08/05 14:51:08 [core] Subchannel Connectivity change to CONNECTING
```
Here, gRPC realizes that the transport is broken. It spawns a goroutine to trigger re-resolution by the dns resolver. But it does not wait to hear back from the resolver. It goes ahead and tries to reset the transport by connecting to all available addresses. Here we have a single address and it is down. So, the subChannel and the channel move to `TRANSIENT_FAILURE`, as can be seen from this log:
```
INFO: 2021/08/05 14:51:08 [core] Subchannel Connectivity change to TRANSIENT_FAILURE
INFO: 2021/08/05 14:51:08 [balancer] base.baseBalancer: handle SubConn state change: 0xc00007f200, TRANSIENT_FAILURE
INFO: 2021/08/05 14:51:08 [core] Channel Connectivity change to TRANSIENT_FAILURE
```

Since more than `minDNSResRate` has elapsed since the last resolution, the dns resolver *does* attempt to immediately re-resolve, and succeeds as well.
```
INFO: 2021/08/05 14:51:08 [core] ccResolverWrapper: sending update to cc: {[{10.244.6.52:9000  <nil> 0 }]  }
```

And based on this update, the `ClientConn` does become healthy again:
```
INFO: 2021/08/05 14:51:08 [core] Subchannel Connectivity change to READY
INFO: 2021/08/05 14:51:08 [balancer] base.baseBalancer: handle SubConn state change: 0xc000d3d0a0, READY
INFO: 2021/08/05 14:51:08 [roundrobin] roundrobinPicker: newPicker called with info: {map[0xc000d3d0a0:{{10.244.6.52:9000  <nil> 0 }}]}
INFO: 2021/08/05 14:51:08 [core] Channel Connectivity change to READY
```

But since you are closing the `ClientConn` on the first RPC error that you see, it gets shutdown.

My suggestion would be to not close the `ClientConn` upon seeing the first error. Instead, do some retries before deciding that this `ClientConn` will not recover and therefore fail the test. Or [wait for the ClientConn state to change](https://pkg.go.dev/google.golang.org/grpc#ClientConn.WaitForStateChange) with a reasonable timeout.

**Comment by hijerusalem** [comment]
Thank you for your suggestion. I think we can solve this by writing a retry interceptor. 

I'm wondering can grpc-go built-in retry mechanism solve this case so that users write configuration instead of implementing another retry functionality

**Comment by dfawley** [comment]
> I'm wondering can grpc-go built-in retry mechanism solve this case so that users write configuration to retry instead of implementing another retry functionality

You can use retry to retry on UNAVAILABLE errors.  However, it won't help here, as the RPC will just fail N times more quickly than your system is able to do DNS re-resolution and reconnect.  Instead, probably what you want is to use [WaitForReady](https://pkg.go.dev/google.golang.org/grpc#WaitForReady) on your RPCs.

**Comment by hijerusalem** [comment]
@dfawley Tested with  `WaitForReady`,  problem solved. Thanks
