### ISSUE TITLE
Should we add 'timer.Stop()' here to avoid leaking a timer? 

### ISSUE THREAD

**Issue by hitzhangjie** [grpc/grpc-go#4659]
https://sourcegraph.com/github.com/grpc/grpc-go@574137db7de3c10e010d5023626169f13540cef1/-/blob/server.go?L804

**Comment by easwars** [comment]
A `Timer` type represents a single event. https://pkg.go.dev/time#Timer

Once the timer has fired, there is nothing that needs to be done to release associated resources. 

A [Ticker](https://pkg.go.dev/time#Ticker) on the other hand needs to be stopped to release associated resources.
