### ISSUE TITLE
Expose the underlying channel from testutils.Channel

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#4662]
[testutils.Channel](https://github.com/grpc/grpc-go/blob/997ce619eb555b6a481e741afa6390ad3cd80d5c/internal/testutils/channel.go#L28) provides a useful timed receive operation for tests.

There are some tests though where access to the underlying channel is required, because it is passed to some other component which receives on the channel. For example: `readyCh` in [this test](https://github.com/grpc/grpc-go/blob/997ce619eb555b6a481e741afa6390ad3cd80d5c/xds/internal/server/listener_wrapper_test.go#L211).

It would be nice to expose this underlying channel for tests that really need it. Something along the lines of [timer.C](https://pkg.go.dev/time#Timer) would suffice.

**Comment by jackwener** [comment]
Hi, I willing to take this task up.

**Comment by easwars** [comment]
Thanks.

**Comment by jackwener** [comment]
I'm not sure whether I got the right point of issue.
In order to expose the underlying channel,  Is it enough that modify [ch](ch chan interface{}) into Ch?
I think that I may not understand correctly. Maybe I need some tips, thanks.

**Comment by easwars** [comment]
Yes, rename `ch` to `C` and add a comment, something to this effect

```
// C is the underlying channel on which values sent using the SendXxx() methods are delivered.
// Tests which cannot use ReceiveXxx() for whatever reasons can use C to read the values.
```

And also try to change the example test which I pointed to in the original description.

Hope this helps.

**Comment by jackwener** [comment]
> And also try to change the example test which I pointed to in the original description.

The test should be changed, but it will be easy for me if the instruction and problem about test file is more clear.

**Comment by jackwener** [comment]
Maybe I get the point.
because underlying channel  is't exposed, there aren't some tests.

https://github.com/grpc/grpc-go/blob/997ce619eb555b6a481e741afa6390ad3cd80d5c/xds/internal/server/listener_wrapper_test.go#L212

change into `lw, readyCh, xdsC, lis, cleanup := newListenerWrapper(t)`

And I should add some tests about underlying channel in `xdsC` and `lis`.

**Comment by Aditya-Sood** [comment]
hi @dfawley @easwars , is this issue still relevant?

**Comment by easwars** [comment]
@Aditya-Sood 
Yes, this is still relevant, but very low priority. I replied on your other PR about some additional changes that we require on the xDS client and config_selector. That work is higher priority and definitely more interesting than this one.

**Comment by Aditya-Sood** [comment]
hi @easwars, shall I pick this up now?

**Comment by easwars** [comment]
Sure, the other one with the LRS loads would be higher priority for sure. I'll let you pick which one you want to work on.

**Comment by Aditya-Sood** [comment]
sure I'll start with the LRS issue first and then work on this
