### ISSUE TITLE
concurrent map r & w in TestAccountCheckDynamicWindowLargeMessage

### ISSUE THREAD

**Issue by charlesxsh** [grpc/grpc-go#4665]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
9280052d36656451dd7568a18a836c2a74edaf6c

### What version of Go are you using (`go version`)?
1.16.4

### What operating system (Linux, Windows, …) and version?
Debian

### What did you do?
We found this potential data race issue by exploring a fuzzing project.

### What did you expect to see?
no fatal error

### What did you see instead?
=== RUN   TestAccountCheckDynamicWindowLargeMessage
    transport_test.go:2124: Error on client while reading data frame header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    transport_test.go:2124: Error on client while reading data frame header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    transport_test.go:2124: Error on client while reading data frame header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    transport_test.go:2124: Error on client while reading data frame header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    transport_test.go:2124: Error on client while reading data frame header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    transport_test.go:176: Error on server while reading message: rpc error: code = Canceled desc = context canceled
    transport_test.go:2124: Error on client while reading data frame header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    transport_test.go:2124: Error on client while reading data frame header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    transport_test.go:176: Error on server while reading message: rpc error: code = Canceled desc = context canceled
    transport_test.go:2124: Error on client while reading data frame header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    transport_test.go:176: Error on server while reading message: rpc error: code = Canceled desc = context canceled
    transport_test.go:2124: Error on client while reading data frame header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    transport_test.go:2124: Error on client while reading data frame header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
fatal error: concurrent map read and map write

goroutine 6 [running]:
runtime.throw(0x899c38, 0x21)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc00019f8f8 sp=0xc00019f8c8 pc=0x441bb2
runtime.mapaccess1_fast32(0x819f20, 0xc0002fdd40, 0xc000000013, 0xc00022a218)
	/usr/local/go/src/runtime/map_fast32.go:21 +0x196 fp=0xc00019f920 sp=0xc00019f8f8 pc=0x414876
google.golang.org/grpc/internal/transport.testFlowControlAccountCheck(0xc000344000, 0x100000, 0x0, 0x0)
	/fuzz/target/internal/transport/transport_test.go:2154 +0x9a5 fp=0xc00019ff38 sp=0xc00019f920 pc=0x7b2825
google.golang.org/grpc/internal/transport.TestAccountCheckDynamicWindowLargeMessage(0xc000344000)
	/fuzz/target/internal/transport/transport_test.go:2062 +0x6c fp=0xc00019ff80 sp=0xc00019ff38 pc=0x7b1e2c
testing.tRunner(0xc000344000, 0x8aabc8)
	/usr/local/go/src/testing/testing.go:1193 +0xef fp=0xc00019ffd0 sp=0xc00019ff80 pc=0x516fef
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00019ffd8 sp=0xc00019ffd0 pc=0x47b781
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b5

The line number here might be inaccurate because of instrumentation, internal/transport/transport_test.go:2154 indicates 
```go
	for _, stream := range clientStreams {
		id := stream.id
		serverStreams[id] = st.activeStreams[id]
		loopyServerStreams[id] = st.loopy.estdStreams[id]
		loopyClientStreams[id] = client.loopy.estdStreams[id]  <----- line 2154

	}
```

**Comment by easwars** [comment]
Does your fuzzing project indicate where the concurrent map read and map write are happening? You have indicated one line in the code base. Is that the place of the read or the write?

**Comment by charlesxsh** [comment]
@easwars Sorry for the late response. Yes this is the place of read/write.

**Comment by songlh-psu** [comment]
There are unsynchronized read and write operations on the map. The read operations are in the unit test. The write operations are `delete(l.estdStreams, c.streamID)`  in function `cleanupStreamHandler(c *cleanupStream)`.
