### ISSUE TITLE
Go has broken -bin metadata processing

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-go#467]
`encodeKeyValue` chooses whether to use base64 based on whether each rune is <= 127. However, it should choose _only_ based on whether the key ends in `-bin`, and _not_ modify the key based on the value.

The current scheme does not make it clear how it should be used. For example, let's say I want to encode a binary header with a big-ending 2-byte integer. If I test with "myint" -> 0x00FF, then it will become base64-encoded. But then in production it could be "myint" -> 0x0000 which won't be base64 encoded. Whether the value is binary is very important, and should explicitly be specified by the user via the -bin suffix.

https://github.com/grpc/grpc-go/blob/master/metadata/metadata.go#L63
https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L334

@ctiller

**Comment by ctiller** [comment]
Part of fixing this should include extending the interop suites so that such bugs are impossible in the future.
