### ISSUE TITLE
potential blocking issues

### ISSUE THREAD

**Issue by charlesxsh** [grpc/grpc-go#4672]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
commit 9280052d36656451dd7568a18a836c2a74edaf6c

### What version of Go are you using (`go version`)?
1.16

### What operating system (Linux, Windows, …) and version?
Linux/Debian

### What did you do?
If possible, provide a recipe for reproducing the error.
These potential blocking issues are found by our current WIP project. Some issues are hard to reproduce without our tool/instrumentation. We will release it as soon as it is ready.

### What did you expect to see?
no blocking issue

### What did you see instead?

During the execution of following tests, the program might have blocking issues/deadlock at following positions if some selects/timeout are chosen/happened:

1.  TestGRPCLBStatsUnaryFailedToSend (balancer/grpclb/grpclb_test.go)
https://github.com/grpc/grpc-go/blob/87eb5b7502493f758e76c4d09430c0049a81a557/balancer/grpclb/grpclb_remote_balancer.go#L263-L267
Line 266

2. TestV2ClientAckFirstIsNack (xds/internal/client/v2/ack_test.go)
https://github.com/grpc/grpc-go/blob/997ce619eb555b6a481e741afa6390ad3cd80d5c/balancer_conn_wrappers.go#L69-L72
Line 71

3. TestSafeConfigSelector (internal/resolver/config_selector_test.go)
https://github.com/grpc/grpc-go/blob/997ce619eb555b6a481e741afa6390ad3cd80d5c/internal/resolver/config_selector.go#L153-L157

https://github.com/grpc/grpc-go/blob/997ce619eb555b6a481e741afa6390ad3cd80d5c/internal/resolver/config_selector_test.go#L63-L67

https://github.com/grpc/grpc-go/blob/997ce619eb555b6a481e741afa6390ad3cd80d5c/internal/resolver/config_selector_test.go#L114-L123

If internal/resolver/config_selector_test line 121 is chosen, then g1 will be blocked at sending to cs1Called so 
https://github.com/grpc/grpc-go/blob/997ce619eb555b6a481e741afa6390ad3cd80d5c/internal/resolver/config_selector.go#L161
cannot be unlocked. This also lead  `UpdateConfigSelector`,  will be blocked at lock.
 |main   | g1( SelectConfig)       |               g2 (UpdateConfigSelector) |
| ------------- |:-------------:| -----:|
|           |          mu.RLock() |  |
|            |        |                        mu.Lock() //blocked |
 |            |      cs1Called <- struct{}{} // blocked | |

//  g1 blocked at sending to cs1Called, mu cannot be unlock, so g2 also blocked at mu.Lock()

4. TestCreateCertificateWithRefresh (credentials/tls/certprovider/meshca/plugin_test.go)
https://github.com/grpc/grpc-go/blob/997ce619eb555b6a481e741afa6390ad3cd80d5c/internal/testutils/channel.go#L33-L35
Line 34

5. TestServerGoAway (test/end2end_test.go)
https://github.com/grpc/grpc-go/blob/84d0920b59e5f138ffd4da11f7b2ab51e862b581/internal/transport/controlbuf.go#L406

6. TestHandlerTransport_HandleStreams_MultiWriteStatus (internal/transport/handler_server_test.go)

https://github.com/grpc/grpc-go/blob/84d0920b59e5f138ffd4da11f7b2ab51e862b581/internal/transport/handler_server.go#L185

https://github.com/grpc/grpc-go/blob/728364accfb93cd52003fb38a6412c8e4965116b/internal/transport/handler_server.go#L73

we can see the `writes` channel has no buffer.
`ht.WriteStatus` => `err := ht.do(...)`

`ht.do` send func to writes, but writes has no receiver if
https://github.com/grpc/grpc-go/blob/728364accfb93cd52003fb38a6412c8e4965116b/internal/transport/handler_server.go#L428 is chosen.
So it blocks at sending. So later goroutine will be blocked before previous ht.writeStatusMu is still locked.

https://github.com/grpc/grpc-go/blob/728364accfb93cd52003fb38a6412c8e4965116b/internal/transport/handler_server_test.go#L403-L407

7. TestServerGoAway (test/end2end_test.go)

https://github.com/grpc/grpc-go/blob/728364accfb93cd52003fb38a6412c8e4965116b/internal/transport/transport.go#L177

8. TestGRPCLBStatsUnaryFailedToSend (balancer/grpclb/grpclb_test.go)

https://github.com/grpc/grpc-go/blob/728364accfb93cd52003fb38a6412c8e4965116b/internal/transport/transport.go#L189

9. TestServerGoAway (test/end2end_test.go)

https://github.com/grpc/grpc-go/blob/728364accfb93cd52003fb38a6412c8e4965116b/server.go#L1777

10. TestV2ClientAckFirstIsNack (xds/internal/client/v2/ack_test.go)
https://github.com/grpc/grpc-go/blob/c052940bcd91bba85050ac193aeeca6e1c588e8a/server.go#L762

11. TestRPCTimeout (test/end2end_test.go)
https://github.com/grpc/grpc-go/blob/c052940bcd91bba85050ac193aeeca6e1c588e8a/server.go#L951

12. TestV2ClientAckFirstIsNack (xds/internal/client/v2/ack_test.go)
https://github.com/grpc/grpc-go/blob/9c668aeab86903a70e291eb47a04f48d84e67006/xds/internal/xdsclient/transport_helper.go#L240

13. TestV2ClientAckFirstIsNack (xds/internal/client/v2/ack_test.go)

https://github.com/grpc/grpc-go/blob/9c668aeab86903a70e291eb47a04f48d84e67006/xds/internal/testutils/fakeserver/server.go#L173

14. TestEDSHandleResponseWithoutWatch (xds/internal/client/v2/eds_test.go)

https://github.com/grpc/grpc-go/blob/9c668aeab86903a70e291eb47a04f48d84e67006/xds/internal/testutils/fakeserver/server.go#L190

**Comment by menghanl** [comment]
There doesn't seem to be anything to do for this issue.
E.g. buffer 0 channels are perfectly OK to use, if the reader stops after the writer.

If you ran into deadlocks, please file an issue for the specific bug.
