### ISSUE TITLE
Send message from server to specific client.

### ISSUE THREAD

**Issue by Jiw0cha** [grpc/grpc-go#4675]
Hello.

If use Unary mode. 
Is there a method to send a message to a specific client?
In Stream mode there is  - Send. 
example:
```
type ChatRoom_ChatServer interface {
	Send(*ChatResponse) error
	Recv() (*ChatRequest, error)
	grpc.ServerStream
}

```
How to do it in Unary mode.

**Comment by menghanl** [comment]
Unary RPCs don't "send" message. The return value of the service handler is sent back to the client as the response.

See examples of all types of RPCs here: https://github.com/grpc/grpc-go/tree/master/examples/route_guide

**Comment by Jiw0cha** [comment]
> Unary RPCs don't "send" message. The return value of the service handler is sent back to the client as the response.
> 
> See examples of all types of RPCs here: https://github.com/grpc/grpc-go/tree/master/examples/route_guide

Here's an example https://github.com/Jiw0cha/mini 

Run server, run incomclient, run incomclient, run client.
How, at the server side, send a message to a specific client(incomclient)? Now messages are sent one by one.

**Comment by menghanl** [comment]
For unary RPCs, the streams are closed after the response is sent back. You can make streaming RPCs, , keep the streams open, and send the message later when you want.
Or, you will need to make the client also a server, and sent it RPCs.
