### ISSUE TITLE
Question about mutil-core cpu usage

### ISSUE THREAD

**Issue by 89trillion-wenjie** [grpc/grpc-go#4678]
Please see the FAQ in our main README.md before submitting your issue.
Plz help me!
I am developing a grpc server and doing stress test, but now I meet a problem.
When the concurrency load grows the usage of mutil cores seems unnormal.

![image](https://user-images.githubusercontent.com/74045630/129453382-043c50aa-7ffb-4cd2-bc5b-22535f6905a3.png)

there is a core used more frequently than others and the whole performance stuck on that.

I have no idea why that happened.

**Comment by 89trillion-wenjie** [comment]
help!

**Comment by easwars** [comment]
Please provide more information about what you are trying to do and what is the exact nature of the problem you are seeing and why you think it might be related to gRPC.
