### ISSUE TITLE
SendMsg memory leak

### ISSUE THREAD

**Issue by iamzhoug37** [grpc/grpc-go#4679]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
google.golang.org/grpc@v1.39.1

### What version of Go are you using (`go version`)?
go 1.15

### What operating system (Linux, Windows, …) and version?
debian

### What did you do?
If possible, provide a recipe for reproducing the error.
```
func main() {
	for i := 0; i < 168; i++ {
		go confirmLoop()
	}
         time.Sleep(1 * time.Hour)
}
func confirmLoop() {
        conn, err = grpc.DialContext(
		ctx,
		cli.addr,
		grpc.WithDefaultCallOptions(grpc.MaxCallSendMsgSize(128<<20)),
		grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(128<<20)),
		grpc.WithInsecure(),
		grpc.WithBlock())
	var streamLock sync.Mutex
	stub := proto.NewServiceClient(conn)
	streamClient /* proto.StreamClient */ , _  := stub.ConsumerStream(ctx)

	for {
		confirmRequest := &proto.ConfirmRequest{
			Sequence: 0,
		}
		confirmPacket := &proto.ClientPacket{
			Type:           0,
			ConfirmRequest: confirmRequest,
		}

		streamLock.Lock()
		defer streamLock.Unlock()
		streamClient.Send(cmd)
		
		time.Sleep(1 * time.Second)
	}
}
```
### What did you expect to see?
`sendMsg ` should not use so many memory
### What did you see instead?
![image](https://user-images.githubusercontent.com/21154201/129552509-1b6c1e2e-e26f-4ecd-a550-fec041377325.png)

**Comment by easwars** [comment]
I'm trying to understand the reason behind setting the send and receive message size call options on the client.
```
	grpc.WithDefaultCallOptions(grpc.MaxCallSendMsgSize(128<<20)),
	grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(128<<20)),
```

If you end up sending a lot of data, `SendMsg` *will* consume memory.

Why do you think there is a memory leak though?
Does the memory utilization come down after you stop sending messages and the Garbage Collector has had a chance to clean things up?

If you feel this is a gRPC problem and if you can point us specifically to a place where you think we might be leaking memory, that would be very useful.
