### ISSUE TITLE
Flaky test: 148/10k: KeepaliveClientStaysHealthyWithResponsiveServer

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#4688]
https://github.com/grpc/grpc-go/pull/4685/checks?check_run_id=3366527552

--- FAIL: Test (80.35s)
    --- FAIL: Test/KeepaliveClientStaysHealthyWithResponsiveServer (4.00s)
        keepalive_test.go:375: client.NewStream() failed: connection error: desc = "transport is closing"
FAIL
FAIL	google.golang.org/grpc/internal/transport	162.225s

**Comment by easwars** [comment]
Another one: https://github.com/grpc/grpc-go/pull/4689/checks?check_run_id=3413667799

**Comment by easwars** [comment]
One more: https://github.com/grpc/grpc-go/pull/4747/checks?check_run_id=3559113704

**Comment by menghanl** [comment]
https://github.com/grpc/grpc-go/runs/3614851830

**Comment by menghanl** [comment]
https://github.com/grpc/grpc-go/runs/3616031834

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/pull/4807/checks?check_run_id=3681565656

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/runs/4158886243?check_suite_focus=true

**Comment by zasweq** [comment]
https://github.com/zasweq/grpc-go/runs/4435565689?check_suite_focus=true

**Comment by menghanl** [comment]
https://github.com/grpc/grpc-go/runs/4510141307?check_suite_focus=true

**Comment by menghanl** [comment]
https://github.com/grpc/grpc-go/runs/4955894427?check_suite_focus=true

**Comment by menghanl** [comment]
https://github.com/grpc/grpc-go/runs/5135830157?check_suite_focus=true

**Comment by dfawley** [comment]
https://github.com/grpc/grpc-go/runs/5558569509?check_suite_focus=true

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/runs/5652483299?check_suite_focus=true

**Comment by lidizheng** [comment]
https://github.com/grpc/grpc-go/runs/5669478619?check_suite_focus=true

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/runs/8040193880?check_suite_focus=true

**Comment by arvindbr8** [comment]
https://github.com/grpc/grpc-go/actions/runs/3284148252/jobs/5409750035

**Comment by zasweq** [comment]
Failed in 148/10000 runs on google3: [ ](http://sponge2/a695e889-a0f1-4f6c-8bcf-d29fa5583ccf)

**Comment by arvindbr8** [comment]
one more  https://github.com/grpc/grpc-go/actions/runs/3586371854/jobs/6035485798

```
--- FAIL: Test (81.66s)
    --- FAIL: Test/KeepaliveClientStaysHealthyWithResponsiveServer (4.00s)
        keepalive_test.go:388: client.NewStream() failed: connection error: desc = "transport is closing"
FAIL
```

**Comment by arvindbr8** [comment]
one more again https://github.com/grpc/grpc-go/actions/runs/3588462149/jobs/6039885922
```
--- FAIL: Test (81.66s)
    --- FAIL: Test/KeepaliveClientStaysHealthyWithResponsiveServer (4.00s)
        keepalive_test.go:388: client.NewStream() failed: connection error: desc = "transport is closing"
FAIL
```

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/3709225080/jobs/6287626091

```
--- FAIL: Test (80.42s)
    --- FAIL: Test/KeepaliveClientStaysHealthyWithResponsiveServer (4.00s)
        keepalive_test.go:388: client.NewStream() failed: connection error: desc = "transport is closing"
FAIL
FAIL	google.golang.org/grpc/internal/transport	162.200s
```

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/3742909549/jobs/6354439461

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/3889298809/jobs/6637443490

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/3898035161/jobs/6656341597

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/3898035161/jobs/6657145853

**Comment by dfawley** [comment]
https://github.com/grpc/grpc-go/actions/runs/3951627642/jobs/6765724679

**Comment by arvindbr8** [comment]
https://github.com/grpc/grpc-go/actions/runs/4208218420/jobs/7303990252

**Comment by arvindbr8** [comment]
https://github.com/grpc/grpc-go/actions/runs/4269148853/jobs/7432127990

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/4269145652/jobs/7432122601

**Comment by arvindbr8** [comment]
Fix merged.
