### ISSUE TITLE
Dependency on github.com/golang/protobuf/proto breaks encoding

### ISSUE THREAD

**Issue by ossareh** [grpc/grpc-go#469]
Hey there,

Go Version: 1.5.1
Operating Systems: Debian 8 (x64) & Mac OS X (latest version)
What did you do: Upgraded to a new github.com/golang/protobuf
What did you expect to see: No change
What did you see instead: Encoding of one_of is broken.

More detail:
Yesterday we discovered that something in [this change set](https://github.com/golang/protobuf/compare/d3d78384b82d449651d2435ed329d70f7c48aa56...68415e7123da32b07eab49c96d2c4d6158360e9b) is causing encoding `one_of` to break. We have a very simple Message including a one of an a string member decoding the message result in just the string member and not the `one_of`. If we roll back to d3d78384b82d449651d2435ed329d70f7c48aa56 the problem is resolved. I have not carefully stepped back through each commit to establish where the encoding issue comes about.

I'm opening this here because we use grpc-go directly where github.com/golang/protobuf is a transient dependency. If you'd like me to open the ticket in their issues instead I'll be glad to do that.

Given a bit more time I could pare this down to the exact lines of code - it was just easier to revert to a known good version. LMK if you'd like that done.

Cheers,

mike

**Comment by iamqizhao** [comment]
Yes, please open an issue to github.com/golang/protobuf and cc @dsymonds. Thanks.

**Comment by dsymonds** [comment]
Don't bother opening a new issue. In general, if you upgrade protobuf then you need to regenerate protos. I have a plan to make the failure mode if you don't more obvious, but it'll still end up the same: you'll need to regenerate protos if you update the protobuf package.

**Comment by ossareh** [comment]
@dsymonds I'm very sure I regenerated the protobufs after the upgrade. I'm going to run another test now and I'll let you know soon after that.

**Comment by dsymonds** [comment]
The only failure mode I can think of is if the .pb.go file containing the oneof wasn't regenerated, and that'd be due to commit `0879490`.

**Comment by ossareh** [comment]
OK, I can confirm that regenerating the protobufs worked. It required that I run `go get -u github.com/golang/protobuf/{proto,protoc-gen-go}` which while obvious in hindsight was not while debugging.

I'd like to discuss this in a non-noisy-for-others forum, @dsymonds would [the protobuf mailing list](https://groups.google.com/forum/#!forum/protobuf) be the most apt place? Ultimately I'm trying to understand what we can do to ensure we don't get bitten by this again. I see this as an unexpected and accidentally incorporated API change; which means there's a relationship which we do not have well encoded in our build flow, I'd be interested in establishing how others' mitigate this sort of issue.

**Comment by dsymonds** [comment]
Like I said earlier, I have a plan for how to improve the situation. It'll be something like the generated code verifying with the proto package that they are compatible (e.g. a versioning scheme).

**Comment by pires** [comment]
`go get -u github.com/golang/protobuf/{proto,protoc-gen-go}` did the trick for me, thanks for the tip.
