### ISSUE TITLE
Why grpc-go didn't use bazel as default build tool?

### ISSUE THREAD

**Issue by Hanggi** [grpc/grpc-go#4693]
I found that both grpc and grpc-java are using bazel as build tool.

Are there any benefits to using bazel build grpc-go?

Thank you.

**Comment by dfawley** [comment]
Go has its own build system which works perfectly well for most people's & OSS projects' needs.  Was there any reason in particular you wanted to use bazel with grpc-go?

**Comment by Hanggi** [comment]
I'm in a mono-repo project with multi-projects and multi-languages.
Someone proposed to use bazel to build all projects in all different languages.

I just want to know whehter it is a good idea.

( I found that grpc, grpc-java are using bazel, but grpc-go and grpc-node did not use bazel.
 Is bazel good enough to build golang or node.js)

**Comment by dfawley** [comment]
Bazel can handle building Go just fine, and it may make sense to use in your mono repo to be compatible with the rest of your build system.  Within Google, gRPC-Go is built using bazel (technically "blaze" but [they're equivalent](https://bazel.build/faq.html#whats-up-with-the-word-blaze-in-the-codebase)).

The big downside of bazel is that you would need to produce your own BUILD files for it, which is what we do at Google with some automation.  We use internal tooling, but a quick web search turned up https://brendanjryan.com/2018/05/12/building-go-applications-with-bazel.html which may be of interest in this regard.
