### ISSUE TITLE
gRPC server reports internal error when request is cancelled because of deadline/timeout

### ISSUE THREAD

**Issue by codesuki** [grpc/grpc-go#4696]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
v1.30.0

### What version of Go are you using (`go version`)?
1.14.2

### What operating system (Linux, Windows, …) and version?
linux

### What did you do?
Investigating 500 internal gRPC errors I found that the caller closes the context because it's over the deadline.
I tracked it down to here:
https://github.com/grpc/grpc-go/blob/1f12bf44284e6ba4be72cd028a2a1eb01c2d18bb/internal/transport/http2_server.go#L884

It seems WriteHeader is called on an already closed connection. 

### What did you expect to see?
No 500 errors on gRPC or Envoy.

My expectation is that as a gRPC service operator I should not see 500 errors if the client sets a very small deadline or cancels requests, hence I wonder if this is the correct behavior for the server.

### What did you see instead?
Lots of 500 errors on gRPC metrics but none on Envoy.

**Comment by dfawley** [comment]
Where are the 500s appearing for you?

If the deadline was exceeded, then on the network, the RPC should be terminated by the server (the gRPC library) with a `DeadlineExceeded` status code, so this `Internal` error would only be visible to the server application, I believe.  Is that right?

**Comment by codesuki** [comment]
Yes, we see the 500 on our Opencensus gRPC metrics. 
I forgot to mention it in the ticket but this is the error we get: 
https://github.com/grpc/grpc-go/blob/6bd8e8cf30e25b6cde3ec16389ff470680c107b1/internal/transport/http2_server.go#L55

Also to add more context because I just had another look at the traces.
ServiceFoo calls ServiceError.
The trace looks like this: 
```
ServiceFoo: context.deadlineExceededError: context deadline exceeded
ServiceFoo: errors.errorString: net/http: request canceled
ServiceError: INTERNAL: transport: transport: the stream is done or WriteHeader was already called
```

**Comment by codesuki** [comment]
Sorry for the late reply and thanks for you quick replies :) 

> > Yes, we see the 500 on our Opencensus gRPC metrics.
> 
> What is the source of those metrics exactly?

Not sure I am answering the right thing, but: the source is the gRPC server together with https://pkg.go.dev/go.opencensus.io/plugin/ocgrpc?utm_source=godoc#ServerHandler. 

I meant to answer this with my last post but just to clarify.
> this Internal error would only be visible to the server application, I believe. Is that right?
That is right.

**Comment by dfawley** [comment]
Thanks for clarifying.  Since this doesn't affect the status of the RPC as seen by the client, and the error handling paths around here seem a bit hairy, I think it will be lower priority to correct it.

**Comment by ash2k** [comment]
I'm also seeing this behavior and it's not great. Had to work it around to return `CANCELED` - otherwise my Prometheus interceptor is recording it as `INTERNAL` and that triggers alerts.

p.s. this issue looks like a duplicate of https://github.com/grpc/grpc-go/issues/3575.

**Comment by codesuki** [comment]
Obviously, I have limited context, but just looking at this piece of code. What about splitting up `ErrIllegalHeaderWrite` into a `ConnectionError` like 'StreamClosed' and a normal error 'HeaderAlreadyWritten'. Then the caller
https://github.com/grpc/grpc-go/blob/1f12bf44284e6ba4be72cd028a2a1eb01c2d18bb/internal/transport/http2_server.go#L1011

Would not return `Internal` but treat it as a connection error, which seems to be handled differently.

Anyway, I don't want to apply bandaid fixes because of my limited context but if you would judge this as OK I'd send a PR.

**Comment by highwayliu** [comment]
is there any progress here ? I have met this issue too.
