### ISSUE TITLE
DialContext() uses http_proxy when using port only and no hostname

### ISSUE THREAD

**Issue by skiptomyliu** [grpc/grpc-go#4719]
### What version of gRPC are you using?
v1.40.0

### What version of Go are you using (`go version`)?
go version go1.16.6 darwin/amd64
go version go1.16.6 linux/amd64

### What operating system (Linux, Windows, …) and version?
MacOS 10.15.7
Ubuntu 18.04.5 LTS (Bionic Beaver)

### What did you do?
```
cat proxytest.go
package main

import (
        "log"
        "google.golang.org/grpc"
)

func main() {
        _, err := grpc.Dial(":9901", grpc.WithInsecure(), grpc.WithBlock())
        if err != nil {
                log.Fatal(err)
        }
}
GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_GO_LOG_VERBOSITY_LEVEL=99  https_proxy=localhost:10001 go run proxytest.go
INFO: 2021/08/30 17:37:16 [core] parsed scheme: ""
INFO: 2021/08/30 17:37:16 [core] scheme "" not registered, fallback to default scheme
INFO: 2021/08/30 17:37:16 [core] ccResolverWrapper: sending update to cc: {[{:9901  <nil> 0 <nil>}] <nil> <nil>}
INFO: 2021/08/30 17:37:16 [core] ClientConn switching balancer to "pick_first"
INFO: 2021/08/30 17:37:16 [core] Channel switches to new LB policy "pick_first"
INFO: 2021/08/30 17:37:16 [core] Subchannel Connectivity change to CONNECTING
INFO: 2021/08/30 17:37:16 [core] Subchannel picks a new address ":9901" to connect
INFO: 2021/08/30 17:37:16 [core] pickfirstBalancer: UpdateSubConnState: 0xc000021af0, {CONNECTING <nil>}
INFO: 2021/08/30 17:37:16 [core] Channel Connectivity change to CONNECTING
WARNING: 2021/08/30 17:37:16 [core] grpc: addrConn.createTransport failed to connect to {:9901 localhost:9901 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:10001: connect: connection refused". Reconnecting...
INFO: 2021/08/30 17:37:16 [core] Subchannel Connectivity change to TRANSIENT_FAILURE
INFO: 2021/08/30 17:37:16 [core] pickfirstBalancer: UpdateSubConnState: 0xc000021af0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial tcp [::1]:10001: connect: connection refused"}
INFO: 2021/08/30 17:37:16 [core] Channel Connectivity change to TRANSIENT_FAILURE
```

### What did you expect to see?
When the IP/Hostname is omitted, gRPC seems to implicitly route to 0.0.0.0.  However, when the `https_proxy` is set, gRPC attempts to CONNECT to the proxy first.  I would expect traffic routing to local interfaces on 0.0.0.0 to not route through the proxy.

### What did you see instead?
Traffic was routed through the proxy instead.

**Comment by easwars** [comment]
When the host portion is omitted, gRPC does not route to `0.0.0.0`. It routes to `localhost` on IPv4, and `[::1]` on IPv6. 

> I would expect traffic routing to local interfaces on 0.0.0.0 to not route through the proxy.

Why do you expect that?

**Comment by skiptomyliu** [comment]
> When the host portion is omitted, gRPC does not route to 0.0.0.0. It routes to localhost on IPv4, and [::1] on IPv6.
Thanks for the reply and I appreciate the correction.

> Why do you expect that?
Ah, so we'd ultimately like to `no_proxy` localhost and 0.0.0.0, ::1.  However, when just using `:port`, it seems we aren't able to given that there is no hostname / ip to use. 

When explicitly specifying `127.0.0.1:9001`, gRPC respects the `no_proxy` env vars and doesn't attempt to use the proxy.

**Comment by menghanl** [comment]
The function handling proxy env vars (https://pkg.go.dev/net/http#ProxyFromEnvironment) deals with localhost addresses (including `127.0.0.1` and `[::1]`, but maybe it doesn't handle `:port`?).

I think you wouldn't even need `no_proxy` for `127.0.0.1:9001`.

**Comment by skiptomyliu** [comment]
> The function handling proxy env vars (https://pkg.go.dev/net/http#ProxyFromEnvironment) deals with localhost addresses (including `127.0.0.1` and `[::1]`, but maybe it doesn't handle `:port`?).
> 
> I think you wouldn't even need `no_proxy` for `127.0.0.1:9001`.

I think what we also want to avoid is broad-brush allowing `:port` for all hosts.  Just as an example, if `no_proxy=:9001`, we want gRPC to obey the `no_proxy` for `localhost:9001`, but we should still be using the proxy if we attempt to egress to `google.com:9001`.

I was hoping that gRPC would respect `no_proxy=localhost,127.0.0.1,::1`  if only `:port` is being used.

**Comment by menghanl** [comment]
The proxy env variables are handled by the `net/http` package, not by gRPC.
If you want, please file an issue in the official go repo.
