### ISSUE TITLE
Is it possible to add NOTICE file

### ISSUE THREAD

**Issue by Shnitzelil** [grpc/grpc-go#4733]
AFAIK, the MPL-2 license required NOTICE file.
Any chance to add such (this required from our legal department)?

**Comment by easwars** [comment]
We use an [Apache License](https://github.com/grpc/grpc-go/blob/master/LICENSE), and not the Mozilla License.

**Comment by easwars** [comment]
I do see that the [grpc-java](https://github.com/grpc/grpc-java) and [core](https://github.com/grpc/grpc) do have a `Notice.txt` file. If you can send a PR, we would be happy to review and merge it. Thanks.

**Comment by Shnitzelil** [comment]
Please review https://github.com/grpc/grpc-go/pull/4739
