### ISSUE TITLE
Unexplained panic in GRPCStatus() method

### ISSUE THREAD

**Issue by xstephen95x** [grpc/grpc-go#4742]
### What version of gRPC are you using?
Issue encountered in `grpc@v1.34.0` and `grpc@v1.36.0`

### What version of Go are you using (`go version`)?
Encountered in  `go1.14.15` and `go1.16.3`

### What operating system (Linux, Windows, …) and version?
`CentOS Linux 7`

### What did you do?
Viewed production logs emitting from our panic recovery handlers.

### What did you expect to see?
No panics handling gRPC messages.

### What did you see instead?

Panics emitted from the gRPC library.

Stack:
```
runtime.gopanic
runtime/panic.go:969
runtime.panicmem
runtime/panic.go:212
runtime.sigpanic
runtime/signal_unix.go:717
google.golang.org/grpc/internal/status.(*Error).GRPCStatus
google.golang.org/grpc@v1.36.0/internal/status/status.go:151
google.golang.org/grpc/status.FromError
google.golang.org/grpc@v1.36.0/status/status.go:88
google.golang.org/grpc.toRPCErr
google.golang.org/grpc@v1.36.0/rpc_util.go:836
google.golang.org/grpc.(*csAttempt).recvMsg
google.golang.org/grpc@v1.36.0/stream.go:937
google.golang.org/grpc.(*clientStream).RecvMsg.func1
google.golang.org/grpc@v1.36.0/stream.go:780
google.golang.org/grpc.(*clientStream).withRetry
google.golang.org/grpc@v1.36.0/stream.go:638
google.golang.org/grpc.(*clientStream).RecvMsg
google.golang.org/grpc@v1.36.0/stream.go:779
```
Further up the stack is internal code, calling `Recv` on the auto-generated clientStream. This is part of a bi-directional streaming RPC. 

Upon some investigation, the panic occurs here:
```
150 func (e *Error) GRPCStatus() *Status {
151   return FromProto(e.e)
152 }
```

on L151, indicating that the `e *Error` is `nil`. This seemingly violated the [invariant](https://github.com/grpc/grpc-go/blob/ad24ab52b1624d64554867408e11e74d546829ea/internal/status/status.go#L140) here, but after searching through the package, I can't find any violations. 

More interestingly, the proceeding frame has a nil-check that is passed on L82:

```
81 func FromError(err error) (s *Status, ok bool) {
82   if err == nil {
83     return nil, true
84   }
85   if se, ok := err.(interface {
86     GRPCStatus() *Status
87   }); ok {
88     return se.GRPCStatus(), true
89   }
```
At first we thought this could be a "[nil != nil](https://yourbasic.org/golang/gotcha-why-nil-error-not-equal-nil/)" issue, but the `Error` struct pointer type is never passed or returned, only the `error` interface type is ever used, so this seems unlikely.

So, we are unsure _why_ or _how_ this panic could be occurring. Our loggers have reported multiple panics in production in the last year, and the panic has never been encountered in any of our extensive test suites. 

Any help or guidance would be much appreciated.

**Comment by dfawley** [comment]
This is definitely bewildering.  Can you provide any other information about your setup that might help?

Are you using any custom codec / compressor, by any chance (https://pkg.go.dev/google.golang.org/grpc/encoding)?

**Comment by xstephen95x** [comment]
We do use `grpc/encoding`. Specifically:
`"google.golang.org/grpc/encoding/gzip"`
`grpc.UseCompressor(gzip.Name)` in our client call options.


We are using protobuf, with everything generated by 
```
PROTOC_VERSION=3.15.8
PROTOC_GEN_GO_VERSION=1.26.0
PROTOC_GEN_GO_GRPC_VERSION=1.1.0
```

In the environment where we're seeing these errors, we also have Envoy proxy nodes mediating the requests between hosts, although this is probably unrelated, and the envoy proxy logs were nominal.

**Comment by dfawley** [comment]
Looking more, I just don't see any way this is possible given the stack trace you have, except for memory corruption.  A `nil` `*Error` just isn't possible to exist at runtime in the code.

Can you reproduce on a newer gRPC release?

**Comment by xstephen95x** [comment]
We haven't been able to reproduce the issue. We've only seen the issue twice in the last year, with the stacktrace logged from our production services. Our latest release uses the latest gRPC release `v1.40.0`, but the issue hasn't shown up yet on this version.

We are also quite bewildered here. I concur that from a read of the code, a `nil` `*Error` is not possible to exist.
As curious as I am, the infrequency makes this fairly low priority, and we have no further data to help debug this issue.
So, we can probably just close this for now and we can re-open if it shows up again on a newer release of grpc.

Is there any other information we should try to capture if the issue shows up again?

While we can't rule out memory corruption, it feels unlikely in my opinion. The hosts where these panics occurred were processing other concurrent workloads in the same memory space and encountered no other issues. The same exact panic, with the same exact stack trace, ~6 months apart, with no other evidence of memory corruption seems more than coincidental. But, this doesn't 100% rule out very isolated bits of corruption.

**Comment by dfawley** [comment]
Thanks for the extra information.

> Is there any other information we should try to capture if the issue shows up again?

I can't think of anything else that will help, actually.  By the time we've gotten here, it's too late -- the problem is the creation of the `nil *Error`, not its usage.  Obviously anything unusual/suspicious in the logs would be of interest, especially if this was reasonably reproducible and patterns were noticed.

I'll close this but feel free to ping it or open a new one if this keeps happening.
