### ISSUE TITLE
Memory retained after connections closed

### ISSUE THREAD

**Issue by howardjohn** [grpc/grpc-go#4758]
### What version of gRPC are you using?
v1.40.0

### What version of Go are you using (`go version`)?
1.17

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
Running an bi-di streaming server (XDS server). Code is OSS, can be found at https://github.com/istio/istio/blob/2af5bfd55ad08d25ba7de634a723194b3af1382a/pilot/pkg/xds/ads.go#L253.

The server has default read/write buffers of 32kb (not set explicitly)

I open 6k clients, then abruptly disconnect them. The memory usage (by all memory metrics) of my application remains quite high.

![2021-10-09_16-32-17](https://user-images.githubusercontent.com/623453/132927871-3859848f-e085-48f3-8146-d6a86f07a83e.png)

Heap profile: 
[profile (1).pb.gz](https://github.com/grpc/grpc-go/files/7146879/profile.1.pb.gz)

I checked goroutine dump and see nothing related to the gRPC serving. All memory

After that, I manually triggered a bunch of GC's; no impact.

I opened more connections, and memory usage goes up but it was able to free after those closed.

### What did you expect to see?

Memory freed

### What did you see instead?

Memory retained

This is the same issue I opened a year ago: https://github.com/grpc/grpc-go/issues/4013. The issue is the ~same as it was back then.

**Comment by menghanl** [comment]
The heap can be seen in this internal pprof UI: http://pprof/?id=2467b46b03a10558ad944e675c655865&tab=flame&metric=inuse_space

The top 4
1. 515 MiB	31.69%	google.golang.org/protobuf/proto.MarshalOptions.marshal (encode.go)
   - This is allocated by the protobuf package. But it's not obvious to me if/how this memory is kept after Marshal() returns
2. 353 MiB	21.72%	google.golang.org/grpc/internal/transport.newBufWriter (http_util.go) inlined
   - This is server transport's buffer. But it's per-transport, and should be freed if the connections are closed
3. 181 MiB	11.10%	bufio.NewReaderSize (bufio.go) inlined
   - same as 2
4. 159 MiB	9.803%	google.golang.org/protobuf/internal/impl.consumeStringSliceValidateUTF8 (codec_gen.go)
   - This is also in protobuf, but by Unmarshal()

1 and 4 are allocated by protobuf.
I believe we don't keep any reference to the buffer. Or maybe the messages keep some kind of reference? And we are holding reference to the message?

2 and 3 are both in the server transport. Not clear what happened. Will need to look more.

**Comment by howardjohn** [comment]
I followed the technique in https://developer.squareup.com/blog/always-be-closing/ to add a finalizers for logging. I added them to `rpc_util.encode()`'s message and to the full `discovery.AggregatedDiscoveryService_StreamAggregatedResourcesServer` object at the top of my service.

During normal operations, everything is unallocated. However, _something_ triggers it to sometimes not unallocate. I can see the finalizer func is never called on _any_ of the streams I cancel.

Will play around with this more, I think its the most useful tool go offers. Unless there is some way to find all references to an object? That would be perfect

**Comment by howardjohn** [comment]
Will need more investigation next week, but it looks like when it leaks https://github.com/istio/istio/blob/2af5bfd55ad08d25ba7de634a723194b3af1382a/pilot/pkg/xds/ads.go#L315 is not freed (which stores the AggregatedDiscoveryService_StreamAggregatedResourcesServer object). It always seems correlated with https://github.com/istio/istio/blob/de3a8fc852b4ea2b420f083d74e533899f982c7c/pilot/pkg/xds/discovery.go#L533.

This suggests its actually plausibly an issue on our side.

**Comment by howardjohn** [comment]
Not easy to reproduce for someone other than me, but for my own memory:
* Get a big cluster
* Run Istiod locally
* Connect a moderate number of clients (`pilot-load adsc 300`)
* Trigger a config update so a push occurs
* `pkill 99 pilot-load` in the middle.

I can reproduce this now reliably in ~30s or so, so should help with debugging and testing

**Comment by howardjohn** [comment]
Will update with more details later but it turns out we are holding onto a reference to the `serverStream` which in turn leads to nothing being GCed

**Comment by howardjohn** [comment]
Ok so here is what is happening. We store the `serverStream` object (indirectly) in a queue (https://github.com/istio/istio/blob/a9d554a8ba/pilot/pkg/xds/pushqueue.go#L31). When we pop the queue we slice the queue (https://github.com/istio/istio/blob/a9d554a8ba/pilot/pkg/xds/pushqueue.go#L91). This leaves the underlying array around and thus doesn't GC what was formerly `p.queue[0]`. Because this is stores a `serverStream`, nothing is GCed.

So on our side, we have a bug. It is an *extremely* subtle bug though, and go tooling is not helpful at all; it will show who allocated the memory (proto/grpc library), but not who holds a reference. I even ran under a debugger and saw the queue had len==0 and assumed it was all good.

On the gRPC side, I would expect the read/write buffers to persist, but am a bit surprised that some SendMsg and RecvMsg stacks show up in the profile. I am a bit concerned that what is happening is the stream is terminated mid-send/recv, and then we never free the msg until `serverStream` itself is GCed. This makes the impact of this even larger.

This is a bug in our code, so feel free to close. However, it may make sense to add some documentation around this or even explicitly freeing this memory stored in the stream struct when the stream is closed. This would make user errors a lot lower impact (although harder to discover, perhaps).

**Comment by menghanl** [comment]
Thanks for the update!

I believe the messages could be cached in the stream for retries.
So I think that's expected. CC @dfawley

**Comment by dfawley** [comment]
Received messages that have not been read from the stream by the application need to be kept, in case the application wishes to read them later.  They still may be whole, valid messages, and useful for the application.  This is probably less true on the server side, since the server is unable to cleanly finish the RPC and the client will presumably always need to retry, but on the client side this is very important as the received messages may also include an OK RPC status at the end of them.  In this case, removing all the data from that stream would be destructive.

Sent messages _should_ be freed if the connection is dead.  (Note that this is server-side so retry is not involved at all.)  Note that the RPC write operation might "succeed", even if the data isn't written to the connection, if there is ample buffer locally.  Is the payload being cached by anything, perhaps?  Do you have tracing/stats collection/binary logging enabled?

**Comment by menghanl** [comment]
I'm closing this issue now. Please comment here or file an issue if you have other findings. Thanks!

**Comment by hzxuzhonghu** [comment]
@menghanl @dfawley another finding maybe relevant, this is the heap pprof  after grpc stream becomes idle and all the objects received from grpc server are not referrenced, but from the below,  grpc-->protobuf still holds the most memory. Is this normal?

```
(pprof) top20 -cum
Showing nodes accounting for 1996.65MB, 54.30% of 3676.95MB total
Dropped 356 nodes (cum <= 18.38MB)
Showing top 20 nodes out of 94
      flat  flat%   sum%        cum   cum%
    0.50MB 0.014% 0.014%  2044.78MB 55.61%  istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).receive
       5MB  0.14%  0.15%  2030.65MB 55.23%  github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3.(*aggregatedDiscoveryServiceStreamAggregatedResourcesServer).Recv
         0     0%  0.15%  2025.65MB 55.09%  github.com/golang/protobuf/proto.Unmarshal
         0     0%  0.15%  2025.65MB 55.09%  github.com/golang/protobuf/proto.UnmarshalMerge
         0     0%  0.15%  2025.65MB 55.09%  google.golang.org/grpc.(*serverStream).RecvMsg
         0     0%  0.15%  2025.65MB 55.09%  google.golang.org/grpc.recv
         0     0%  0.15%  2025.65MB 55.09%  google.golang.org/grpc/encoding/proto.codec.Unmarshal
         0     0%  0.15%  2025.65MB 55.09%  google.golang.org/protobuf/internal/impl.(*MessageInfo).unmarshal
         0     0%  0.15%  2025.65MB 55.09%  google.golang.org/protobuf/internal/impl.(*MessageInfo).unmarshalPointer
         0     0%  0.15%  2025.65MB 55.09%  google.golang.org/protobuf/proto.UnmarshalOptions.UnmarshalState (inline)
         0     0%  0.15%  2025.65MB 55.09%  google.golang.org/protobuf/proto.UnmarshalOptions.unmarshal
 1989.15MB 54.10% 54.25%  1989.15MB 54.10%  google.golang.org/protobuf/internal/impl.consumeStringSliceValidateUTF8
         0     0% 54.25%   778.62MB 21.18%  google.golang.org/grpc.(*Server).handleStream
    1.50MB 0.041% 54.29%   778.62MB 21.18%  google.golang.org/grpc.(*Server).processStreamingRPC
         0     0% 54.29%   778.62MB 21.18%  google.golang.org/grpc.(*Server).serveStreams.func1.2
    0.50MB 0.014% 54.30%   776.12MB 21.11%  github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3._AggregatedDiscoveryService_StreamAggregatedResources_Handler
         0     0% 54.30%   775.62MB 21.09%  istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Stream
         0     0% 54.30%   775.62MB 21.09%  istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).StreamAggregatedResources
         0     0% 54.30%   727.63MB 19.79%  istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).processRequest
         0     0% 54.30%   622.29MB 16.92%  istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).pushXds

```

**Comment by easwars** [comment]
Reopening to discuss if the new findings are relevant to us in anyway.

**Comment by hzxuzhonghu** [comment]
yeah, go pprof report is very implicit

**Comment by hzxuzhonghu** [comment]
Even with deepcopy of received object, the received object memory looks not released.   
 https://github.com/istio/istio/compare/release-1.12...hzxuzhonghu:12-09-debug?expand=1#diff-69a5c353ed87ca4dc51349c2e950da8e0514e36dbf46aa47ce39574ee1a19befR187 
```
(pprof) top30 -cum
Showing nodes accounting for 2472.35MB, 56.22% of 4397.83MB total
Dropped 333 nodes (cum <= 21.99MB)
Showing top 30 nodes out of 94
      flat  flat%   sum%        cum   cum%
         0     0%     0%  2904.17MB 66.04%  istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).receive
       3MB 0.068% 0.068%  2496.35MB 56.76%  github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3.(*aggregatedDiscoveryServiceStreamAggregatedResourcesServer).Recv
         0     0% 0.068%  2493.35MB 56.70%  github.com/golang/protobuf/proto.Unmarshal
         0     0% 0.068%  2493.35MB 56.70%  github.com/golang/protobuf/proto.UnmarshalMerge
         0     0% 0.068%  2493.35MB 56.70%  google.golang.org/grpc.(*serverStream).RecvMsg
         0     0% 0.068%  2493.35MB 56.70%  google.golang.org/grpc.recv
         0     0% 0.068%  2493.35MB 56.70%  google.golang.org/grpc/encoding/proto.codec.Unmarshal
         0     0% 0.068%  2493.35MB 56.70%  google.golang.org/protobuf/internal/impl.(*MessageInfo).unmarshal
         0     0% 0.068%  2493.35MB 56.70%  google.golang.org/protobuf/internal/impl.(*MessageInfo).unmarshalPointer
         0     0% 0.068%  2493.35MB 56.70%  google.golang.org/protobuf/proto.UnmarshalOptions.UnmarshalState (inline)
         0     0% 0.068%  2493.35MB 56.70%  google.golang.org/protobuf/proto.UnmarshalOptions.unmarshal
 2459.85MB 55.93% 56.00%  2459.85MB 55.93%  google.golang.org/protobuf/internal/impl.consumeStringSliceValidateUTF8  
```

**Comment by hzxuzhonghu** [comment]
Is there any special optimization to hold memory in grpc?

**Comment by hzxuzhonghu** [comment]
This is none of grpc problem, it is because  we shallow copied `DiscoveryRequest.ResourceNames []string` to a Istio struct. So go profile reported the memory if still hold by `google.golang.org/protobuf/internal/impl.consumeStringSliceValidateUTF8  `

**Comment by dfawley** [comment]
Interesting.  Thanks for following up.

Is there some way to make `pprof` (or some other tool) show memory usage ordered by what is _referencing_ the memory and keeping it alive instead of by what allocated it?  It seems like a lot of issues are filed against us as a memory leak, because others are holding onto memory that was created inside grpc-go, even though we are no longer referencing it ourselves.
