### ISSUE TITLE
Why grpc TLS must specify the certificate?

### ISSUE THREAD

**Issue by seaguest** [grpc/grpc-go#4759]
Hello,

I have a grpc service with TLS enabled, I have to use the following code to connect and it works:
```
	creds, err := credentials.NewClientTLSFromFile(*cert, "test.example.com")
	if err != nil {
		log.Fatalf("Failed to create TLS credentials %v", err)
	}

	// Set up a connection to the server.
	conn, err := grpc.Dial(*addr, grpc.WithTransportCredentials(creds))
	if err != nil {
		log.Errorf("did not connect: %v", err)
	}
	defer conn.Close()
```
However when I use python client to connect, I just need to create secure channel and it works, no need to specify the certificate.

I tried to open the target address (https://test.example.com/) with Firefox and I can download the certificate with which the above golang code works, the certificate is issued by Amazon.

Another concern is, we use grpc from android app to call the service directly, if the certificate expires one day, we need to force  app to upgrade to have a updated certificate, this is not reasonable, knowing the certificate can be retrieved through network (can be downloaded from Firefox), is there any way to not to store the certificate locally?

**Comment by menghanl** [comment]
Can you try `credentialsNewClientTLSFromCert(nil, "")`.
(Use `"test.example.com"` if you want to override the server name, otherwise just leave it as `""`)

**Comment by seaguest** [comment]
@menghanl 

great, it works, thanks.
