### ISSUE TITLE
ringhash: don't strip address.Attributes and stop using address.Metadata

### ISSUE THREAD

**Issue by menghanl** [grpc/grpc-go#4768]
ringhash policy currently strips Attributes from add the weight to address.Metadata.
The reason is that Attributes are not comparable, and the weight change cannot be detected.

https://github.com/grpc/grpc-go/pull/4741/files#diff-62641f60fa804eaaa0871705672007e07191dcdc95b3f74bba62bd89c2f75100R194

After #3611 is fixed, we should remove the special handling.

**Comment by easwars** [comment]
We switched to using [resolver.AddressMap](https://github.com/grpc/grpc-go/blob/0f02ca5cc927d2bc9dba043c9468779a2391ed4d/resolver/map.go#L30) which takes care of attributes.
