### ISSUE TITLE
Errors in `operateHeaders` should count stream ID for the purposes of new stream ID validation

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#4779]
The following max stream ID check / update:

https://github.com/grpc/grpc-go/blob/b186ee8975f3c69bc36333a99fc82d1388977012/internal/transport/http2_server.go#L460-L469

happens after other stream validation, and will be skipped if there are HTTP/gRPC errors.  This should be moved up, as the stream ID should not be reused in the face of any of these errors.

**Comment by uds5501** [comment]
@zasweq @dfawley Got a couple of questions.
1. Can I work on this issue?
2. Where should this validation take place instead?
