### ISSUE TITLE
Go - Write sample code for setting and reading error details

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc-go#478]
Go issue for https://github.com/grpc/grpc/issues/4543

**Comment by kelseyhightower** [comment]
Is this something I can take a shot at? I've been playing with grpc and wonder if the following example would work:

Creating a grpc error:
https://github.com/kelseyhightower/grpc-hello-service/blob/master/hello-server/main.go#L74

**Comment by jcanizales** [comment]
You're very very welcome to give it a shot!

More specifically, we'd want a sample that shows sending an error with metadata attached in the HTTP/2 trailers, as well as reading that metadata from the client. That being the recommended way to specify error details when the error code isn't enough to make the error actionable.

**Comment by kelseyhightower** [comment]
Fixed in https://github.com/grpc/grpc-go/pull/506. @jcanizales PTAL

**Comment by c4milo** [comment]
@dfawley, shouldn't this be closed since it seems addressed by https://github.com/grpc/grpc-go/pull/506?

**Comment by dfawley** [comment]
That PR was not merged.. A different sample is necessary with the recentish changes to status.

**Comment by enocom** [comment]
In #506, the APIs on display were `grpc.SetTrailer` on the server, and `grpc.Trailer` on the client.

With the helpers added in #1358, it seems the preferred way to transfer error details is `status.WithDetails` on the server and `status.Details` on the client.

Is that the gist of the issue here?

/cc @dfawley

**Comment by dfawley** [comment]
@enocom,

> Is that the gist of the issue here?

Correct!  Trailers are still useful.  However, for detailed _error_ information, `status.WithDetails` should be used instead.  (Trailers can be used to transmit additional data at the end of an RPC even on success.)
