### ISSUE TITLE
make omitempty optional

### ISSUE THREAD

**Issue by proteneer** [grpc/grpc-go#481]
I'd _really_ like just be able to serialize out the gRPC generated message structs directly to JSON (via some REST API, etc.). However, they all by default have omitempty, which is extremely inconvenient for some data types. So to circumvent this I've had to basically re-wrap everything that's been gRPC'd. Is there a good way to deal with this?

**Comment by dsymonds** [comment]
If you mean the generated protocol buffer messages, you need to use `github.com/golang/protobuf/jsonpb` to marshal them to JSON. There's several features that won't work with the standard `encoding/json` package.

**Comment by proteneer** [comment]
I saw this comment:

https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L110

// TODO: proto3 objects should have default values omitted.

Which seems to suggest that the behavior is intended to be similar, eg. a PB generated message that looks like
```
type Bar struct {
	Foo   int32  `protobuf:"varint,1,opt,name=foo" json:"foo,omitempty"`
}
```
still won't serialize out the "foo" field if Foo == 0 (the default value of int32)

**Comment by dsymonds** [comment]
Yes, that's the specified format for JSON and protocol buffers (https://developers.google.com/protocol-buffers/docs/proto3#json). If you have an existing JSON format to match, protocol buffers may not be the best choice.

**Comment by proteneer** [comment]
Thanks - I'll wrap around it.
