### ISSUE TITLE
Getting the clients public IP and other relevant information at the server side

### ISSUE THREAD

**Issue by abhi11** [grpc/grpc-go#482]
I have found the same issue for python[https://github.com/grpc/grpc/issues/1616]
I think, it has not yet been implemented for Go.
Is there a plan to do so ?

**Comment by iamqizhao** [comment]
https://github.com/grpc/grpc-go/pull/479 is under review.

**Comment by varshanbp** [comment]
In C# context.Host works well. Gets Host Address/IP and Port
