### ISSUE TITLE
proto file import does not generate valid go import

### ISSUE THREAD

**Issue by mgilbir** [grpc/grpc-go#483]
On go1.5.2 darwin/amd64, when adding an import in a proto file to another proto file in a different directory, the import path of the generated go grpc file is not correct.

For example with a file `test.proto`:
```
syntax = "proto3";

package pb;

message Time {
    uint64 timestamp = 1;
}

```

and a second file `test2.proto` in a **different directory**:
```
syntax = "proto3";

package pb;

import "pb/test.proto";

message TimeInterval {
    Time start = 1;
    Time end = 2;
}

```

when executing the command: `protoc -I ../../ -I . --go_out=plugins=grpc:. *.proto` generates a go file `test2.proto.go` with an import for the first file like `import pb1 "."`. The problem being that the dot import is not the correct path for the `test.proto.go` file.

**Comment by mgilbir** [comment]
This seems to be the same issue that was reported in https://github.com/golang/protobuf/issues/63

It is still unclear to me how to handle the situation

**Comment by dsymonds** [comment]
protoc-gen-go doesn't know what import path to use for `test.proto`. You need to tell it (via `M` parameters), or run `protoc` from a parent directory that is suitably relevant so it'll guess the right thing.

**Comment by mgilbir** [comment]
Thanks @dsymonds! I managed to get it working

**Comment by gwpp** [comment]
Hi, mgilbir. I get a problem like you. For example:
- `messag.proto`:

    ```
    syntax = "proto3";
    package pb;
    message Message {
        string text = 1;  
    }
    ```

- `logic.proto` in ***same directory***
    ```
    syntax = "proto3";
    package pb;    
    import "message.proto";
    
    service LogicServer {
        rpc PostMessage(Message) returns(Message){}
    }
    ```
    
After execute `protoc --proto_path=. --go_out=plugins=grpc:. logic.proto`, the `logic.pb.go` import message use `import pb1 "."`. 
How to fix it? Please help me. Thank you.
