### ISSUE TITLE
connection error: desc = "transport is closing" after every request

### ISSUE THREAD

**Issue by darrenparkinson** [grpc/grpc-go#4838]
### What version of gRPC are you using?

protoc --version = libprotoc 3.11.4
From go.mod:
google.golang.org/grpc v1.41.0
google.golang.org/protobuf v1.27.1

### What version of Go are you using (`go version`)?

1.16.4

### What operating system (Linux, Windows, …) and version?

MacOS 11.4

### What did you do?
If possible, provide a recipe for reproducing the error.

Essentially I've set up a super basic grpc server.  I have then turned on logging and after every request to the server I receive the `connection error: desc = "transport is closing"` error.

Logging:

```sh
$ export GRPC_GO_LOG_VERBOSITY_LEVEL=99
$ export GRPC_GO_LOG_SEVERITY_LEVEL=info
```

Super simple test service with this in main.go:

```go
l, err := net.Listen("tcp", fmt.Sprintf(":%s", "80"))
if err != nil {
    log.Fatal(err)
}
srv := grpc.NewServer()
svc := &peopleService{}
pb.RegisterPeopleServiceServer(srv, svc)
srv.Serve(l)
```

peopleService is:

```go
type peopleService struct {
	pb.UnimplementedPeopleServiceServer
}
```

And then a couple of methods are implemented on it which return hard coded values.

### What did you expect to see?

I expected not to see this error.  I'm basically having a similar issue with a deployed service and have broken it down to a more basic service on localhost and I still see the problem.

### What did you see instead?

Every single request results in `connection error: desc = "transport is closing"` on the server when logging is turned on which I believe to be causing me trouble with a deployed service.  For the deployed service, whilst I get the error on every request, some methods do return data.  On one method that returns a larger amount of data, I get the error and no data returned.

Any assistance greatly appreciated.  Many thanks.

**Comment by menghanl** [comment]
What does the client look like? Are you creating new clients for each RPC (instead of reusing, https://github.com/grpc/grpc-go/tree/master/examples/features/multiplex)?

But even with that, the RPCs should finish successfully, and get the full response. If this happens in the middle of the RPC, and cause lost data, then there's probably more than that.
Did you check client logs? Is there any more information on the connection errors?

Also if you can post a small reproduction, we can try it. Thanks!

**Comment by darrenparkinson** [comment]
Just by way of additional information, the production service sits behind consul.

Here is the client side log output from running against localhost vs the deployed service.

I'm starting to wonder if I'm just doing something stupid and the `transport is closing` error is just a red herring given I get that error on the examples too.

_Production (No Data Returned)_
```sh
INFO: 2021/10/08 17:37:49 [core] parsed scheme: ""
INFO: 2021/10/08 17:37:49 [core] scheme "" not registered, fallback to default scheme
INFO: 2021/10/08 17:37:49 [core] ccResolverWrapper: sending update to cc: {[{peopleservice.query.<redacted>.com:80  <nil> 0 <nil>}] <nil> <nil>}
INFO: 2021/10/08 17:37:49 [core] ClientConn switching balancer to "pick_first"
INFO: 2021/10/08 17:37:49 [core] Channel switches to new LB policy "pick_first"
INFO: 2021/10/08 17:37:49 [core] blockingPicker: the picked transport is not ready, loop back to repick
INFO: 2021/10/08 17:37:49 [core] Subchannel Connectivity change to CONNECTING
INFO: 2021/10/08 17:37:49 [core] Subchannel picks a new address "peopleservice.query.<redacted>.com:80" to connect
INFO: 2021/10/08 17:37:49 [core] pickfirstBalancer: UpdateSubConnState: 0xc000021b00, {CONNECTING <nil>}
INFO: 2021/10/08 17:37:49 [core] Channel Connectivity change to CONNECTING
INFO: 2021/10/08 17:37:49 [core] Subchannel Connectivity change to READY
INFO: 2021/10/08 17:37:49 [core] pickfirstBalancer: UpdateSubConnState: 0xc000021b00, {READY <nil>}
INFO: 2021/10/08 17:37:49 [core] Channel Connectivity change to READY
2021/10/08 17:37:49 rpc error: code = Internal desc = unexpected EOF
exit status 1
```

_Localhost (data returned)_
```sh
INFO: 2021/10/08 17:38:10 [core] parsed scheme: ""
INFO: 2021/10/08 17:38:10 [core] scheme "" not registered, fallback to default scheme
INFO: 2021/10/08 17:38:10 [core] ccResolverWrapper: sending update to cc: {[{localhost:80  <nil> 0 <nil>}] <nil> <nil>}
INFO: 2021/10/08 17:38:10 [core] ClientConn switching balancer to "pick_first"
INFO: 2021/10/08 17:38:10 [core] Channel switches to new LB policy "pick_first"
INFO: 2021/10/08 17:38:10 [core] Subchannel Connectivity change to CONNECTING
INFO: 2021/10/08 17:38:10 [core] Subchannel picks a new address "localhost:80" to connect
INFO: 2021/10/08 17:38:10 [core] blockingPicker: the picked transport is not ready, loop back to repick
INFO: 2021/10/08 17:38:10 [core] pickfirstBalancer: UpdateSubConnState: 0xc000021af0, {CONNECTING <nil>}
INFO: 2021/10/08 17:38:10 [core] Channel Connectivity change to CONNECTING
INFO: 2021/10/08 17:38:10 [core] Subchannel Connectivity change to READY
INFO: 2021/10/08 17:38:10 [core] pickfirstBalancer: UpdateSubConnState: 0xc000021af0, {READY <nil>}
INFO: 2021/10/08 17:38:10 [core] Channel Connectivity change to READY
<data output logged here>
INFO: 2021/10/08 17:38:10 [core] Channel Connectivity change to SHUTDOWN
INFO: 2021/10/08 17:38:10 [core] Subchannel Connectivity change to SHUTDOWN
```

**Comment by menghanl** [comment]
The options can be set by `ServerOptions`, e.g. https://pkg.go.dev/google.golang.org/grpc#HeaderTableSize

But they need to be explicitly set by the users.
If not set, it won't be included in the settings frame.
https://github.com/grpc/grpc-go/blob/01ed64857e3146000ec99cdea4f2932204f17cdd/internal/transport/http2_server.go#L197-L202

**Comment by darrenparkinson** [comment]
Yes, that's the conclusion I came to, so I'm very confused as to how they are being set?

**Comment by darrenparkinson** [comment]
Hi, thanks.  I've been off for a few days.  I'll see if I can take a look at it this week.
