### ISSUE TITLE
Get remote addr from ClientStream and ServerStream

### ISSUE THREAD

**Issue by chenjie199234** [grpc/grpc-go#4839]
In client side i want to known which addr is picked by ballancer.
In server side i want to get the client's addr.
Is there any way to get this?

The interceptor can get the ClientStream and ServerStream
So required to add a function to get the remote addr.

**Comment by menghanl** [comment]
Remote addresses can be fetched using peer
- server side: https://pkg.go.dev/google.golang.org/grpc/peer#FromContext
- client side: https://pkg.go.dev/google.golang.org/grpc#Peer
