### ISSUE TITLE
xds: safe_regex_match should require matching whole string

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-go#4852]
CC @dfawley, @menghanl, since it seems this would impact client-side routing as well. Should probably audit other regex usages.

As found via RBAC testing. An RPC with metadata `test=header-regex-ab` seems to have matched the following rule snippet (but it shouldn't match):

```
                              "header": {
                                "name": "test",
                                "safeRegexMatch": {
                                  "googleRe2": {
                                  },
                                  "regex": "header-regex-a+"
                                }
                              }
```

[`HeaderMatcher.safe_regex_match` is defined with](https://github.com/envoyproxy/envoy/blob/5423325ccf04c7f50069cb8662e51208526bd4a9/api/envoy/config/route/v3/route_components.proto#L1950-L1952):

    // If specified, this regex string is a regular expression rule which implies the entire request
    // header value must match the regex. The rule will not match if only a subsequence of the
    // request header value matches the regex.

However, the Go code uses `Regexp.MatchString`:

https://github.com/grpc/grpc-go/blob/404d8fd5139bfb7be9b4bf675e76eed53207dd8c/internal/xds/matcher/matcher_header.go#L87-L95

And MatchString [allows partial matches](https://play.golang.org/p/4QImMCyov6E).

**Comment by menghanl** [comment]
And string matcher: https://github.com/grpc/grpc-go/blob/404d8fd5139bfb7be9b4bf675e76eed53207dd8c/internal/xds/matcher/string_matcher.go#L60-L61

https://github.com/envoyproxy/envoy/blob/5423325ccf04c7f50069cb8662e51208526bd4a9/api/envoy/type/matcher/string.proto#L47-L67
```
    // * The regex ``\d{3}`` matches the value *123*
    // * The regex ``\d{3}`` does not match the value *1234*
    // * The regex ``\d{3}`` does not match the value *123.456*
```
