### ISSUE TITLE
Any Go alternate for EnableMultipleHttp2Connections

### ISSUE THREAD

**Issue by xqzhang2015** [grpc/grpc-go#4862]
```
There's a property called SocketsHttpHandler.EnableMultipleHttp2Connections in ASP.NET's grpc library 
which enables a channel to create additional http/2 connections when the concurrent stream limit is reached. 

Is there anything available in Go that could help me achieve the same?
```

I encounter the same challenge. Our grpc call QPS requirement is over the concurrent stream limit.

**So Any Go alternate for EnableMultipleHttp2Connections in ASP.NET?**

**Comment by xqzhang2015** [comment]
@dfawley thanks for the reply.

So if one connection hits the grpc limit or TCP limit, currently the only choice is to create multiple connections, right? The scenario in my app is server-to-server calling.

@easwars fyi

**Comment by dfawley** [comment]
> So if one connection hits the grpc limit or TCP limit, currently the only choice is to create multiple connections, right?

Right now the best way to do it is to create multiple `grpc.ClientConn`s and manually spread your RPCs across them.  You could also create a custom LB policy and create multiple `SubConn`s, but I wouldn't recommend it as that API is still unstable.
