### ISSUE TITLE
Gazelle dependency on grpc-go v1.41.0 does not build in Bazel

### ISSUE THREAD

**Issue by dontstabai** [grpc/grpc-go#4865]
In order to use this library in Bazel, I ran Gazelle to create the following external repo definition:
```bazel
go_repository(
  name = "org_golang_google_grpc",
  importpath = "google.golang.org/grpc",
  sum = "h1:f+PlOh7QV4iIJkPrx5NQ7qaNGFQ3OTse67yaDHfju4E=",
  version = "v1.41.0",
)
```

However, Bazel fails to build it because of a missing type assertion in [serverreflection.go](https://github.com/grpc/grpc-go/blob/2fe71180762478c66b0027f780b95c40fc563a55/reflection/serverreflection.go#L78):
> external/org_golang_google_grpc/reflection/serverreflection.go:78:36: cannot use s (type GRPCServer) as type *grpc.Server in argument to grpc_reflection_v1alpha.RegisterServerReflectionServer: need type assertion

Go version: `go1.17.1 darwin/amd64`
Gazelle version: `v0.24.0`
Bazel version: `4.2.1-homebrew`
OS: MacOS Big Sur `11.5.2`

**Comment by crockeo** [comment]
Also running into the same issue. Given that this is a protoc version error, and that Gazelle generates a `go_proto_library` target which pins the protoc compiler to one specifier in [bazelbuild/rules_go](https://github.com/bazelbuild/rules_go), it's probably a rules_go issue to solve.

There's actually already a ticket open from Jun 29th which addresses this https://github.com/bazelbuild/rules_go/issues/2901. One of [the comments](https://github.com/bazelbuild/rules_go/issues/2901#issuecomment-885176338) already proposes a workaround:

>I worked around this by adding build_file_proto_mode = "disable" to the go_repository rule in my WORKSPACE for org_golang_google_grpc.

But I haven't done my due diligence to verify that this doesn't have knock-on effects.
