### ISSUE TITLE
transport: max http2 frame size is hardcoded to 16k

### ISSUE THREAD

**Issue by hanjin-qiu** [grpc/grpc-go#4916]
See PR #3018 #4630

The max size is a const of 16k, and there doesn't seem to be a way to configure it(C language  can be set with GRPC_ARG_HTTP2_MAX_FRAME_SIZE).

Moreover, the size is sent from the server in the settings frame, but the client never reads and applies it. Is that correct?

**Comment by dfawley** [comment]
This is the same as #4630.
