### ISSUE TITLE
How to send a PING Frame?

### ISSUE THREAD

**Issue by svanharmelen** [grpc/grpc-go#493]
Is it currently possible to send PING frames to keep a connection alive?

We have a use case where a gRPC connection is load balanced using HAProxy (which we don't have access to), but the HAProxy config is set to timeout after 50 seconds (the default settings). Now some actions take longer then those 50 seconds, so the connection can be quiet for more then 50 seconds between calls which currently breaks the connection ending in a series of:

```
 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF
```

Any other pointers on how to solve that are of course welcome as well!

Thanks!

**Comment by svanharmelen** [comment]
Anyone any pointers?

Thx!

**Comment by iamqizhao** [comment]
There is no API to send PING frame. If you control the server side code, you can host a health check service on your server (https://github.com/grpc/grpc-go/blob/master/health/health.go) and then your clients can issue health checking rpcs periodically to keep the liveness of the connection.

**Comment by svanharmelen** [comment]
Thanks @iamqizhao! This was just the info and pointer we needed :grinning:

**Comment by svanharmelen** [comment]
@iamqizhao it works like a charm! I now make a health check call every 30 seconds which prevents HAProxy to timeout after 50 seconds :grinning: 

Thanks again!

**Comment by HuKeping** [comment]
hi @svanharmelen what's the best practise to add the health checker service into an exist service? Create another structure to hold the old one and the health checker or sth?

**Comment by svanharmelen** [comment]
I would keep any calls to the health endpoint separate from other calls (so not mix it with any of your own calls/endpoints).

As normally (IMO) you would like to use the health endpoint for periodically checking the health of your service and use that info in your client to make decisions based on the state of your service.

Or (like in my case) abuse this to keep open a TCP session when you use a gRPC stream that sends updates with a too big interval for some proxies you might pass (which causes your connection to be dropped).

**Comment by HuKeping** [comment]
@svanharmelen  Thanks!
