### ISSUE TITLE
grpc.Code and grpc.ErrorDesc do not work with error wrappers

### ISSUE THREAD

**Issue by nodirt** [grpc/grpc-go#494]
We often wrap errors to add extra behavior, for example to indicate that an error is transient. However, we cannot decorate `grpc.rpcError` because `grpc.Code` and `grpc.ErrorDesc` do not work with wrappers.

Proposal: 

* introduce an interface, public or internal

```go
type rpcErr interface {
  Code() codes.Code
  Desc() string
}
```

* Make `grpc.rpcError` implement it.
* in `grpc.Code` and `grpc.ErrorDesc`, check if an `err` implements the interface, rather than if it is `grpc.rpcErr`

**Comment by iamqizhao** [comment]
Can you give me an example of your use case of wrapper to demonstrate the
current facility is not sufficient?

**Comment by nodirt** [comment]
[`errors.WrapTransient`](https://github.com/luci/luci-go/blob/master/common/errors/transient.go#L36) is the wrapper function we use to mark errors as transient. 

```go
err := grpc.Errorf(codes.Internal, "Internal server error")
err = errors.WrapTransient(err)
actualCode := grpc.Code(err)
```

here `actualCode` is `codes.Unknown` instead of `codes.Internal`. We have other wrappers as well.

See also Dave Cheney's [tutorial on error inspection](http://dave.cheney.net/2014/12/24/inspecting-errors).

**Comment by iamqizhao** [comment]
I think instead of calling grpc.Code you should call

errors.Code(err)

where the error code is specified when the error is constructed in
errors.WrapTransient(...).

**Comment by nodirt** [comment]
Package errors is a general purpose package. Adding a grpc dependency to it is a wrong thing to do.

**Comment by nodirt** [comment]
My last comment contradicts the proposal. We worked around this by unwrapping an error.

**Comment by iamqizhao** [comment]
You can probably have another constructor which accepts two params:

err := errors.WrapTransient(err.Code(), err.ErrorDesc())
