### ISSUE TITLE
Function Dial() in clientconn.go does not make latter option override the former one

### ISSUE THREAD

**Issue by liujiongxin** [grpc/grpc-go#497]
Assuming in the arguments opts:
The first one is is generated with 
grpc.WithTransportCredentials(credentials.NewClientTLSFromCert(nil, ""))
The second one is generated with 
creds, err := credentials.NewClientTLSFromFile(*certificate, "")
grpc.WithTransportCredentials(creds)"

On a machine without root certificate, this first option will lead to connection error (x509: failed to load system roots and no roots provided). If I only have the second option, there is no error. But if I have both options in the order above, the connection error occurs again.

We hope the latter one can override the former one, as the opts are generally constructed with append(), where default options come first, then the customized options will follow.

**Comment by iamqizhao** [comment]
The behavior under this scenario is undefined/unspecified in gRPC protocol.
And it is debatable which order is preferred. Making your test rely on this
tricky behavior is unpleasant.

**Comment by liujiongxin** [comment]
Thanks, I think you are right, the call site should guarantee the options are valid, and do not trigger undefined behavior.
