### ISSUE TITLE
RPC connection occasionally not allowing calls

### ISSUE THREAD

**Issue by dpetersen** [grpc/grpc-go#498]
I've been struggling for a couple of days with a client and server that I've written. It seems that occasionally the server side doesn't get a header frame from the client, according to a log message I've dropped [here](https://github.com/grpc/grpc-go/blob/843cf836083053d69b704ec5a058deb437a63a28/transport/http2_server.go#L247). I do see the client end writing the header frame.

I have a simple repository that demonstrates the problem: https://github.com/dpetersen/headerbug/

You'll see that I never even call `RegisterFooServer` in my server-side code. That doesn't seem to matter. When I run the server and then the client, it will randomly give one of two results: 
  * **Bad**: Hang forever, with both sides seemingly waiting on the other.
  * **Good**: Print `rpc error: code = 12 desc = "unknown service Foo"`. This is expected, since I never registered the service (though registering the service has no effect on the likelihood of it freezing).

It seems very streaky, and you can get runs of a dozen times where you'll always get the same result, and other times where it will flip flop back and forth between working and freezing. The connection is definitely established, as killing the server while they're both frozen results in an `rpc error: code = 13 desc = "transport is closing"` on the client end.

In the debug statements I threw in, when it works the server side connection gets `WINDOW_UPDATE`, `HEADERS`, and `SETTINGS` frames. When it freezes, I only see `WINDOW_UPDATE` and `SETTINGS`.

I'm running this on Go 1.5.3, the latest version of every related library (including `protoc`/`protoc-gen-go`, which I recompiled/reinstalled this afternoon as a final act of desperation). I've tested this on my local ubuntu machine, an OSX machine, and a fresh DigitalOcean Ubuntu VM. All with the same results.

I've tried everything I know to troubleshoot the problem. I went back to the grpc.io tutorial and validated the way I was starting the server and client. I can not figure this out. Hopefully I'm screwing something up. Thanks for reading this long bug report!

**Comment by iamqizhao** [comment]
I just ran your code 1,000 times on my ubuntu desktop and have not seen any error.  Did you see any logs on client when it ran into bad case?

**Comment by dpetersen** [comment]
@iamqizhao thanks so much for looking at this. Here is the output I see, first from a successful run and then from an unsuccessful one:
```
root@ubuntu-2gb-sfo1-01:~# /root/gopath/bin/client localhost:4000
2016/01/22 22:13:09 connected
2016/01/22 22:13:09 rpc error: code = 12 desc = "unknown service Foo"
root@ubuntu-2gb-sfo1-01:~# /root/gopath/bin/client localhost:4000
2016/01/22 22:13:09 connected
```
It outputs the "connected" message and then sits until I Ctrl-c it. I just tried this fresh on a couple of brand new Ubuntu DigitalOcean instances, versions 14.04 and 15.10, with the same results. I've documented every keystroke I typed in after SSHing in this gist: https://gist.github.com/dpetersen/2f2149aa4fb939cb63d8

For fun I just installed Go via homebrew on my OSX laptop, which I never use for development, and did a `go get` and was able to run it 500 times in a row successfully. So I have no idea what the difference is.

**Comment by dpetersen** [comment]
If there are any debug or verbosity options I can use on the server or client end, I would love to try them out. In an earlier version of this code that wasn't so stripped down, I was running the `/debug/requests` and `/debug/events` endpoints and never saw a request for any of the failed connections.

**Comment by iamqizhao** [comment]
When it hangs in "bad" case, what does /debug/requests show on both client and server?

**Comment by dpetersen** [comment]
On the server you see nothing, on the client you see this, with that timestamp just spinning along indefinitely while the request is hung.
<img width="608" alt="screenshot" src="https://cloud.githubusercontent.com/assets/408/12563728/88e97864-c360-11e5-9eff-421a59e7a114.png">

I took some time trying to figure out why it says `to: <nil>`, but as far as I can tell it doesn't ever set the destination address. Successful requests also say `to: <nil>`.

**Comment by iamqizhao** [comment]
Can you also show me debug/pprof/block and debug/pprof/trace in the bad case?

**Comment by dpetersen** [comment]
The server block endpoint is:
```
--- contention:
cycles/second=1999821374
```
and the client is:
```
--- contention:
cycles/second=2000000938
```

The trace files are on S3:
  * [server](https://s3.amazonaws.com/g5engineering/dpetersen/server.trace)
  *  [client](https://s3.amazonaws.com/g5engineering/dpetersen/client.trace)

**Comment by dpetersen** [comment]
I've been looking at this further. If the client that I'm using to make the connection is not a streaming client, it always works as expected.

My real-life issue is with bidirectional streams. I've found that it works 100% of the time (in my small test case and in my real app) if I always send a message before I attempt to receive. I've updated my demo codebase. [With this commit](https://github.com/dpetersen/headerbug/commit/d46fd212f7d84506422e78c302b35ae84c521554), it always works. If you remove the `Send` call, it continues to periodically fail.

**Comment by iamqizhao** [comment]
I think I see what the problem is. Let me see how this can be fixed.

**Comment by dpetersen** [comment]
Your changes in #505 fixes my demo app and my real application, they connect consistently whether I send first or not. Thanks so much for looking at this so quickly! I really appreciate it, I don't think I could have found the fix.

**Comment by iamqizhao** [comment]
On Thu, Jan 28, 2016 at 10:51 AM, Don Petersen <notifications@github.com>
wrote:

> Your changes in #505 <https://github.com/grpc/grpc-go/pull/505> fixes my
> demo app and my real application, they connect consistently whether I send
> first or not. Thanks so much for looking at this so quickly! I really
> appreciate it, I don't think I could have found the fix.
>
Thanks for reporting and tons of effort trying to reproduce!
