### ISSUE TITLE
errMsg report

### ISSUE THREAD

**Issue by wittenjing** [grpc/grpc-go#4981]
Master branch, file: transport.go
line 107:  b.err = r.err
Should this line be put after line 101, like this:
if b.err != nil {
    b.err = r.err
    b.mu.Unlock()
    return
}
？

**Comment by easwars** [comment]
I don't think so. That's probably why have the explicit comment:
```
// An error had occurred earlier, don't accept more
// data or errors.
```

Are you seeing any issues because of this?

I'm closing this as I don't believe there is any issue with the code as it is now. Please feel free to reopen with more details if you think this causing an issue to you. Thanks.
