### ISSUE TITLE
Unary grpc interceptor shared state context

### ISSUE THREAD

**Issue by andriihrachov** [grpc/grpc-go#4988]
### Use case(s) - what problem will this feature solve?

Lets say we have "extracting" interceptor - which reads **x-request-id** header.  I'm attaching it to the context, so it will be available in my controllers/services/ etc. downstream

I want to have this request-id header not only in application code, but **inside other interceptors**, like  errorhandling(which is executed last). Right now there are no shared state between interceptors and this is impossible to implement.

### Proposed Solution

return possibly modified context from the previous interceptor alongside with response and error
```
type UnaryHandler func(ctx context.Context, req interface{}) (interface{}, error)
```
becomes
```
type UnaryHandler func(ctx context.Context, req interface{}) (context.Context, interface{}, error)
```

and then we call subsequent interceptors with context returned from previous function

**Comment by easwars** [comment]
Can you please elaborate on your use case. It is not very clear at this point.

Also, In your server interceptor, you could modify the context passed to it using something like https://pkg.go.dev/google.golang.org/grpc@v1.42.0/metadata#NewIncomingContext and pass the modified context to the `UnaryHandler`. Does that not work for you? And if so why?

**Comment by andriihrachov** [comment]
Ok so having code like this:

```
	grpcServer := grpc.NewServer(
		grpc.ChainUnaryInterceptor(
			NewPerformanceMeasureInterceptor(),
			NewAuthInterceptor(),
			NewErrorHandlingInterceptor(),
		))
```
	
I would like to modify context  in **performanceMeasureInterceptor** , like having execution time, headers,  etc.
I would like to modify context in **authInterceptor** , passing user_id to it
I would like to use execution time, headers, and userId in **errorhandlingInterceptor** enriching error reporting with information being gathered in previous interceptors 

**Non grpc examples:**

[golang gin http middlewares](https://github.com/gin-gonic/gin#custom-middleware)
[nodejs Koa request state](https://github.com/koajs/koa/blob/master/docs/api/context.md#ctxstate)

**Comment by andriihrachov** [comment]
up :)

**Comment by dfawley** [comment]
Each interceptor calls the handler (which may be another interceptor when chaining is in use):

```go
type UnaryServerInterceptor func(ctx context.Context, req interface{}, info *UnaryServerInfo, handler UnaryHandler) (resp interface{}, err error)

type UnaryHandler func(ctx context.Context, req interface{}) (interface{}, error)
```

So when you call it, you just need to modify the context first in the interceptor:

```go
func MyInterceptor(ctx context.Context, req interface{}, info *UnaryServerInfo, handler UnaryHandler) (resp interface{}, err error) {
	ctx, _ = context.WithTimeout(ctx, time.Second)  // or metadata.NewIncomingContext() or whatever
	return handler(ctx, req)
}
```

**Comment by andriihrachov** [comment]
Thanks @dfawley , I will try this, and provide the code sample if it doesnt

**Comment by andriihrachov** [comment]
Yep, I can confirm it works - somwthing was wrong with my previous setup. much thanks for your support guys! closing
