### ISSUE TITLE
Unbuffered Codec support

### ISSUE THREAD

**Issue by daaku** [grpc/grpc-go#499]
Currently the [`Codec`](https://godoc.org/google.golang.org/grpc#Codec) looks like this:

```go
type Codec interface {
    // Marshal returns the wire format of v.
    Marshal(v interface{}) ([]byte, error)
    // Unmarshal parses the wire format into v.
    Unmarshal(data []byte, v interface{}) error
    // String returns the name of the Codec implementation. The returned
    // string will be used as part of content type in transmission.
    String() string
}
```

This implies the `Codec` **must** work with a fully buffered serialized version of the request or response. This can be limiting. For example in one of our use cases we have a `[][]byte` where each `[]byte` can be in the MBs range and we may have up to a 1000 of these in a response.

As you're probably thinking, this could be done using streams. But is that restriction necessary? Would a `Codec` interface like such be acceptable?:

```go
type Codec interface {
    // Marshal writes the wire format of v to w.
    Marshal(w io.Writer, v interface{}) error
    // Unmarshal parses the wire format from r into v.
    Unmarshal(r io.Reader, v interface{}) error
    // String returns the name of the Codec implementation. The returned
    // string will be used as part of content type in transmission.
    String() string
}
```

Implementing the existing `Codec` in terms of this `io.Reader` / `io.Writer` based codec is of course trivial. The interface choice can indeed be different, maybe something more powerful. Maybe require `*bufio.Reader` like [`ReadRequest`](https://golang.org/pkg/net/http/#ReadRequest) or [`ReadResponse`](https://golang.org/pkg/net/http/#ReadResponse) uses.

Fundamentally a `Codec` that doesn't need a length prefix and is capable of working with streams directly still has to buffer due to the current design. It would be great if this wasn't the case.

**Comment by dsymonds** [comment]
The gRPC protocol is specified to require a length prefix, so it needs to know the serialised size before sending anything.

But if your protocol is merely sending chunks of []byte around, you could specify a streaming protocol, and send the []byte in smaller chunks. It's still not quite as efficient, but it avoids a complete copy.

**Comment by daaku** [comment]
Would you happen to know where this is sent? I'm looking at https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L507. I see the `Framer` writes the length in `endWrite` but that's just for the frame not the entire message right?

Digging into it so far it seemed like `protobuf` the `Codec` needs to encode the length of the serialized struct before it when it's considered a _Message_.

**Comment by daaku** [comment]
I also see http://www.grpc.io/docs/guides/wire.html which mentions Message-Length but unclear to me if "Delimited-Message" is one entire Message or the data frames for a single message and if the length refers to the former or the latter.

**Comment by iamqizhao** [comment]
"Delimited-Message" is one entire Message which may be split into multiple data frames. So the length refers to the the size of the entire Message.

In general transmission unit of gRPC is still message (instead of byte streaming) so that as David said it requires a length prefix.

**Comment by daaku** [comment]
I came across this which was super helpful to understand the wire protocol: https://github.com/bradfitz/grpc-go16-demo/blob/master/demo.go#L56

In that code it seems like the gRPC wire protocol requires the Message-Length prefix as part of the 5 byte header and then the payload itself has a message length prefix because that's what protobuf does. I guess that answers my question but I'm still left wondering why gRPC requires it.
