### ISSUE TITLE
Fatal error logging cannot be disabled

### ISSUE THREAD

**Issue by MKrupauskas** [grpc/grpc-go#5006]
even when using `grpclog.SetLoggerV2(grpclog.NewLoggerV2(io.Discard, io.Discard, io.Discard))` fatal errors are logged to stderr like `2021-11-24T12:43:08.216Z        ERROR   failed to dial  {"address": "..." }`

Info logging disabling/enabling does work using this method. The fatal logs cannot be disabled using ENV variables.

How can fatal error logging be disabled?

**Comment by dfawley** [comment]
Fatal logs are written to the same location as Error logs.  They will always unconditionally `os.Exit`, however.  Are you calling grpclog in your own code?  If so, that is not a supported use for the grpc logger - it is intended to be used by grpc only.

**Comment by MKrupauskas** [comment]
We are not doing any custom logging. The goal is just to silence all grpc logs, even the fatal ones when dials fails. Setting ENV variables or setting the logger like this `grpclog.SetLoggerV2(grpclog.NewLoggerV2(io.Discard, io.Discard, io.Discard))` both don't work. Is there another proper way of disabling all grpc logs?

**Comment by menghanl** [comment]
1. Silencing Fatal logs doesn't sound like a good idea, since the program is expected to stop. Mostly likely there will be nil panic afterwards.
2. If you really want to drop all the logs, implement this interface: https://pkg.go.dev/google.golang.org/grpc/grpclog#LoggerV2, and make all the methods noop. Then `grpclog.SetLoggerV2()` to set the noop logger.

**Comment by MKrupauskas** [comment]
The exact fatal error we are trying to silence is the failure to dial. This should be safe as we will be handling this error in another way. I'd have to think about how to handle other fatal errors but for now, this is not a big concern.

Regarding 2. this is exactly what I tried doing with `grpclog.SetLoggerV2(grpclog.NewLoggerV2(io.Discard, io.Discard, io.Discard))` but this approach still doesn't silence fatal errors from stderr for some reason. That is the main issue.

**Comment by menghanl** [comment]
Regarding 2. Implement your own logger.

```go
type noopLogger struct {}
func (*noopLogger) Info(args ...interface{}) {}
... // Implement the other methods the same

func init() {
  grpclog.SetLoggerV2(&noopLogger{})
}
```

**Comment by MKrupauskas** [comment]
even with the implementation below fatal errors are still logged to `stdout`. `2021-12-06T09:33:15.879Z        ERROR   failed to dial  {"address": "server", "error": "error dialing \"server\": ssh: rejected: connect failed (Connection refused)"}`

could the problem be in the setting of the logger or is the logger just ignored for fatal errors?

```
type noopLogger struct{}

func (*noopLogger) Info(args ...interface{})                    {}
func (*noopLogger) Infoln(args ...interface{})                  {}
func (*noopLogger) Infof(format string, args ...interface{})    {}
func (*noopLogger) Warning(args ...interface{})                 {}
func (*noopLogger) Warningln(args ...interface{})               {}
func (*noopLogger) Warningf(format string, args ...interface{}) {}
func (*noopLogger) Error(args ...interface{})                   {}
func (*noopLogger) Errorln(args ...interface{})                 {}
func (*noopLogger) Errorf(format string, args ...interface{})   {}
func (*noopLogger) Fatal(args ...interface{})                   {}
func (*noopLogger) Fatalln(args ...interface{})                 {}
func (*noopLogger) Fatalf(format string, args ...interface{})   {}
func (*noopLogger) V(l int) bool                                { return false }

func main() {
	grpclog.SetLoggerV2(&noopLogger{})
        // ...
}
```

**Comment by menghanl** [comment]
Hmm, sorry, I remember wrong. `os.Exit` is called by the fatal function, not the interface: https://github.com/grpc/grpc-go/blob/master/grpclog/grpclog.go#L94

There's no easy way to turn off fatal's `os.Exit()`.
Would it be easy change your application code to not call `grpclog.Fatal()` on errors? If you think this error is handled afterwards anyway, this fatal shouldn't be necessary.

**Comment by MKrupauskas** [comment]
it seems the issue was in our application code as the fatal logs were captured and re-logged by us. thanks for the help and maybe this will help out someone in the future
