### ISSUE TITLE
is there anyway to close tcp Conn when process one request fail？

### ISSUE THREAD

**Issue by projectindex** [grpc/grpc-go#5007]
Client-Server model, 
client send heartbeat message to server per minute, and send info message to server sometime.
when  server process info message, I need judge heartbeat; if too long no heartbeat message, I need to close the connection.
specially，for some reason, KeepaliveParams ServerOption is not my purpose; I need the application heartbeat.

I think it's two way:
1. get the ClientConn from  serverStream ,and then I can call Close()
2. send GOAWAY message
but I can not find the API what I need, can someone help me?

**Comment by dfawley** [comment]
Can you explain more about your use case?  From what we've found, `keepalive.ServerParameters.MaxConnectionIdle` is sufficient for detecting when to close the connection.  Why do you say this doesn't work for you?

**Comment by projectindex** [comment]
my purpost may be like this:
when server accept one new conn, 
context.WithValue(ctx, connectionKey{}, conn)

when process stream fail 
ctx.Value(connectionKey{}).(net.Conn)
I can get the conn,and call conn.Close

the server.go code
func (s *Server) handleRawConn(rawConn net.Conn)
do not set the ctx, sad =_=!

**Comment by projectindex** [comment]
finally,
I rewrite the lib source grpc/server.go,so that I can manage the connection.
export one API to get transport.ServerTransport, then I can call Close
