### ISSUE TITLE
Provide function to construct logger with default configuration

### ISSUE THREAD

**Issue by pavankrish123** [grpc/grpc-go#5011]
### Use case(s) - what problem will this feature solve?

We have a use case where we would like to switch between default logger from grpc and custom logger passed from our application based on runtime configuration dynamically. Switching to custom logger is of no problem but since the default logger is  not exported in the grpc log package we have an issue

### Proposed Solution

Perhaps a CreateDefault() function  can be implemented similar to what is done in init() https://github.com/grpc/grpc-go/blob/master/grpclog/grpclog.go#L36

**Comment by dfawley** [comment]
Is `grpclog.NewLoggerV2()` sufficient for you?  If not, why?

**Comment by pavankrish123** [comment]
Thanks @dfawley. Yes that would be sufficient. Please expose it and that would solve our use case.
