### ISSUE TITLE
how to write `unmarshalling request`  error log in grpc server ?

### ISSUE THREAD

**Issue by rfyiamcool** [grpc/grpc-go#5013]
how to write `grpc: error unmarshalling request: proto: wrong wireType = 2 for field F3`  in grpc server?  i try to use interceptor to log, but when client's request body is invalid,  grpc server don't call interceptor ? 

client:

```
2021/11/30 11:02:16 ping failed, err: rpc error: code = Internal desc = grpc: error unmarshalling request: proto: wrong wireType = 2 for field F3
exit status 1
```

**Comment by easwars** [comment]
Yes, on the server side, the received message needs to be unmarshaled before interceptors are invoked. And if the former fails, the latter will not happen.

But it is not clear from your description, as to what you are trying to do. Can you please be more specific about what you are trying to do and where things fail.

**Comment by rfyiamcool** [comment]
If a client use wrong protobuf,  i want to write the error request log in grpc server, only write the error log.

**Comment by easwars** [comment]
One option would be to install a stats handler on the server using this `ServerOption`: https://pkg.go.dev/google.golang.org/grpc#StatsHandler

The `HandleRPC` method gets invoked with the [OutTrailer](https://pkg.go.dev/google.golang.org/grpc@v1.42.0/stats#OutTrailer) at the end of the RPC on the server-side, and you should be able to access the trailer metadata.

Does this help?

@dfawley @menghanl  : Do you have any other ideas?

**Comment by rfyiamcool** [comment]
😁  thank u @easwars
