### ISSUE TITLE
Wrong run commands in README

### ISSUE THREAD

**Issue by gozeloglu** [grpc/grpc-go#5026]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of Go are you using (`go version`)?
`go1.17.3 darwin/amd64`

### What operating system (Linux, Windows, …) and version?
MacOS - Monterey 
### What did you do?
If possible, provide a recipe for reproducing the error.
I followed the commands in [examples/README.md](https://github.com/grpc/grpc-go/blob/master/examples/README.md) document. But, it did not work and code wasn't able to run.

### What did you expect to see?
I was expecting the code to work. (Actually, I guessed it wouldn't work, but I tried nevertheless.)

### What did you see instead?
```bash
$(go env GOPATH)/bin/greeter_server & 
zsh: no such file or directory: /Users/gokhan.ozeloglu/go/bin/greeter_server    
[1]  + 4951 exit 127   $(go env GOPATH)/bin/greeter_server
```
When I followed the commands [in quick start document](https://grpc.io/docs/languages/go/quickstart/#run-the-example), it works with no problem. So, I think the commands needs to be changed in README with the quick start document commands. If it is OK for you, I can change it.

**Comment by dfawley** [comment]
What was the output from running the `go get` commands?

`go get` is now deprecated for installing binaries, so it should be updated to `go install`, but for me it still works with 1.17:

```
$ go get google.golang.org/grpc/examples/helloworld/greeter_client
go: downloading google.golang.org/grpc/examples v0.0.0-20211130233114-c2bccd0b1594
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
go get: installing executables with 'go get' in module mode is deprecated.
	To adjust and download dependencies of the current module, use 'go get -d'.
	To install using requirements of the current module, use 'go install'.
	To install ignoring the current module, use 'go install' with a version,
	like 'go install example.com/cmd@latest'.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
go get: upgraded google.golang.org/genproto v0.0.0-20200526211855-cb27e3aa2013 => v0.0.0-20200806141610-86f49bd18e98
go get: added google.golang.org/grpc/examples v0.0.0-20211130233114-c2bccd0b1594

$ go get google.golang.org/grpc/examples/helloworld/greeter_server
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
go get: installing executables with 'go get' in module mode is deprecated.
	To adjust and download dependencies of the current module, use 'go get -d'.
	To install using requirements of the current module, use 'go install'.
	To install ignoring the current module, use 'go install' with a version,
	like 'go install example.com/cmd@latest'.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.

$ $(go env GOPATH)/bin/greeter_server &
[1] 69032
$ 2021/12/01 07:45:39 server listening at 127.0.0.1:50051
$ $(go env GOPATH)/bin/greeter_client
2021/12/01 07:45:47 Received: world
2021/12/01 07:45:47 Greeting: Hello world
```

But, we can't update to `go install` until the version that made that work is our oldest supported version.  I don't recall when that was off-hand.
