### ISSUE TITLE
Close the connection from the gRPC server side

### ISSUE THREAD

**Issue by mrproliu** [grpc/grpc-go#5045]
Hi, I wanna ask a question about how to close the connection from the server-side.

Now, some applications could only connect one gRPC server to transmit the data and don't close the connection because of the resource limit, such as Envoy. So Is there any way to close the gRPC connection from the server-side, so the client notices the connection is broken, pick another server address, and reconnect to the server again.

I'm using the grpc-go as the gRPC server, but I cannot find out any way to close the connection from the server-side, the data loss is acceptable. So, how to close? 

Thanks.

----
grpc-go: v1.40.0

**Comment by menghanl** [comment]
`MaxConnectionAge` in keepalive should do what you need:
https://pkg.go.dev/google.golang.org/grpc/keepalive?utm_source=godoc#ServerParameters

**Comment by mrproliu** [comment]
thank you for your reply.
But this parameter server must keep the connection time fixed and cannot be changed dynamically. What I want is for the server-side **dynamic** to close the connection with a single client, and this time is not fixed. For example, is there have an API that could call so I can manually stop the connection?

**Comment by menghanl** [comment]
There's no API to close a connection on the server side. You can probably make a listener wrapper and keep a list of connections, then find the one and close it (filter on local address maybe).

Can you explain a bit more on what problem you are trying to solve?
And how would you decided when to close a connection?

**Comment by mrproliu** [comment]
> There's no API to close a connection on the server side. You can probably make a listener wrapper and keep a list of connections, then find the one and close it (filter on local address maybe).

Could you more explain this? how can I do it?

> Can you explain a bit more on what problem you are trying to solve? And how would you decided when to close a connection?

Now I use envoy as the sidecar and use the gRPC stream to transmit Envoy ALS messages to the APM system (using grpc-go to collect messages). But once Envoy connects to an APM system instance, it will maintain a connection because the sidecar has resource constraints.

In this case, if the APM instance scales out to more instances, then the ALS message is not balanced to each APM Instance, because the link is maintained. So at this time, you need to make APM Instance aware of cluster instance changes, and the APM System actively closes some connections, allowing Envoy to re-select an Instance for connection. Also, the loss of ALS messages is acceptable.

**Comment by menghanl** [comment]
> I see all the connection in the server side is private and the ServerTransport is an internal struct, so we can't get.

You will need to wrap your `net.Listener`'s `Accept()` method, so you keep all the connections. Then you will need to find the corresponding connection for an RPC, by looking at RPC's peer and connection's IP address

> if the APM instance scales out to more instances, then the ALS message is not balanced to each APM Instance

`MaxConnectionAge` is designed exactly for this use case: https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md#abstract
The idea is you occasionally disconnect from the server side (not at the same time), to trigger the clients to re-balance the load.

**Comment by mrproliu** [comment]
> You will need to wrap your `net.Listener`'s `Accept()` method, so you keep all the connections. Then you will need to find the corresponding connection for an RPC, by looking at RPC's peer and connection's IP address

Understand. That's mean I need to hold all the raw connection, and manually close them. But is it safe for the grpc-go? will make some goroutine leak?

> `MaxConnectionAge` is designed exactly for this use case: https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md#abstract The idea is you occasionally disconnect from the server side (not at the same time), to trigger the clients to re-balance the load.

But If the server is scheduled a fixed timer to close the connection when they connected, that's mean the data always will be lost. I think it's a dangerous operation, only when the server instance scale-in/out maybe we need to close the connection. This lets the user could operate the connection through API maybe it's more appropriate. WDYT?

**Comment by menghanl** [comment]
Force closing raw connections should be OK. From grpc's point of view, it's the same as other connection failures.

Keepalive doesn't force close the connections immediately. It sends a GOAWAY to direct new RPCs to new connections.
The connection is force closed after a timeout, and all existing RPCs (usually long streaming RPCs) will abort.

In most cases, the assumption is that data loss (and retry) for critical RPCs should already be handled by the application (preparing for normal connection errors, not server closing connections).

> only when the server instance scale-in/out maybe we need to close the connection

A potential problem with this is that, all clients will reconnect at the same time, causing a surge in traffic.

**Comment by mrproliu** [comment]
Understand. Thanks for your help with the question. If I have any questions I will reopen this issue.

**Comment by ariden83** [comment]
I want to cleanly close the grpc stream connection from the server side in case of a Graceful shutdown, how can i do ?

**Comment by menghanl** [comment]
@ariden83  Server's graceful shutdown waits for all the existing RPCs to finish, so you can just proceed normally with the streams, and return normally: https://pkg.go.dev/google.golang.org/grpc#Server.GracefulStop

There's currently no way for the stream handlers know that the server is stopping. So if that's what you need, you will have to do that at the application level.
