### ISSUE TITLE
protoc-gen-go-grpc: generates wrong package name on macOS

### ISSUE THREAD

**Issue by sding3** [grpc/grpc-go#5049]
### What version of gRPC are you using?

current tip of the master branch: d35aff3c836a77e714eb1c86c8aab963560f043c

### What version of Go are you using (`go version`)?

```
go version go1.16.2 darwin/amd64
```

### What operating system (Linux, Windows, …) and version?

```
Darwin 20.6.0 x86_64
```

### What did you do?

I ran the following commands:

```shell
git clone https://github.com/grpc/grpc-go.git
cd grpc-go/examples/helloworld

sed -i 's/^option go_package.*$//' helloworld/helloworld.proto
sed -i 's/^package helloworld/package foo.bar.helloworld/' helloworld/helloworld.proto


protoc \
  --go_out=. \
  --go_opt=module=google.golang.org/grpc \
  --go_opt=Mhelloworld/helloworld.proto=google.golang.org/grpc/examples/helloworld \
  \
  --go-grpc_out=. \
  --go-grpc_opt=module=google.golang.org/grpc \
  --go-grpc_opt=Mhelloworld/helloworld.proto=google.golang.org/grpc/examples/helloworld \
  \
  ./helloworld/helloworld.proto \


go build ./examples/helloworld/
```

The first `sed` command removes the go package option from the proto file. But we later explicitly pass in our desired go package name via `--go-grpc_opt=M` in the `protoc` execution.

### What did you expect to see?

I expect the generated package ` ./examples/helloworld/` to be able to compile. In other words, I expect the `go build ./examples/helloworld/` command to succeed.

### What did you see instead?

`go build ./examples/helloworld/` fails with:

```
found packages helloworld (helloworld.pb.go) and foo_bar_helloworld (helloworld_grpc.pb.go) in /Users/sding/go/src/grpc-go/examples/helloworld/examples/helloworld
```

This is due to ` ./examples/helloworld/helloworld_grpc.pb.go` having a wrong package name of `foo_bar_helloworld`, which differs from the correct package name `helloworld`.

` ./examples/helloworld/helloworld.pb.go`, on the other hand, has the correct package name of `helloworld`.

This impacts macOS. I cannot reproduce this issue on Linux.

**Comment by menghanl** [comment]
What's your protoc version?
Are they the same on mac and Linux?
Maybe try a newer version on mac?

If this doesn't work, can you try updating protoc-gen-go-grpc's protobuf dependency to a newer version? https://github.com/grpc/grpc-go/blob/master/cmd/protoc-gen-go-grpc/go.mod#L5

**Comment by sding3** [comment]
@menghanl - let me know if you need other clarifications. It seems like the fix is to upgrade `google.golang.org/protobuf` to fix `protoc-gen-go-grpc`.

**Comment by menghanl** [comment]
Thanks for verifying.
If you don't mind, can you send us a PR to update the version? Updating to the latest `v1.27.1` would be good. Thanks!

**Comment by sding3** [comment]
alright, will do that later tonight.
