### ISSUE TITLE
Feature Parity: Suffix for Stats Capability on Client Stubs

### ISSUE THREAD

**Issue by matttproud** [grpc/grpc-go#5055]
### Use case(s) - what problem will this feature solve?

The use case is minimally equal to gRPC C++'s [`grpc::StubOptions`](https://grpc.github.io/grpc/cpp/classgrpc_1_1_stub_options.html), which provides accessors for `suffix_for_stats`.  This enables one to attach a suffix onto client stub names to differentiate them in debugging interfaces, monitoring telemetry, binary request logs, etc.

To further elaborate on a motivating use cases:

- Consider a hypothetical SOA interface similar to [AIP-151](https://google.aip.dev/151), where integrators must implement `google.longrunning.Operation`.  Now imagine a binary that has multiple RPC clients, where more than one client refers to a **different** backend that implements `google.longrunning.Operation`.  `suffix_for_stats` could be used to distinguish between the otherwise-identical RPC clients in the aforementioned sources.
- Consider a binary that has two or more RPC clients to the same backend.  The only difference between the two clients is the QoS traffic class where one client is used for batch requests and the other for important, latency-sensitive requests.  In this world, a user might suffix one client `-batch` and the other `-realtime`.

### Proposed Solution

I would add a [`grpc.DialOption`](https://pkg.go.dev/google.golang.org/grpc#DialOption) that adds extra data to `*grpc.ClientConn` to the public API.  I naively expect that exposing this as an exported field/accessor in `grpc.ClientConn` would be sufficient, because the interceptor API has access the `ClientConn` through its function signature.  Meaning we could amend the monitoring data there.

### Alternatives Considered

We have an internal patch to the `protoc` plugin that supports fully-qualified service renaming by substituting the service name in [`(*grpc.ClientConn).Invoke`](https://pkg.go.dev/google.golang.org/grpc#ClientConn.Invoke).  Unfortunately that is insufficient, because we don't want to mutate the service name as the server that receives the request sees it.  We only want to differentiate between multiple clients.

### Additional Context

/CC: @mklencke, @menghanl, @jadekler

**Comment by easwars** [comment]
@dfawley

**Comment by menghanl** [comment]
Would the context work?
Attaching the suffix to the context, while making the RPCs. Both interceptors and stats handlers have access to the RPC context. They can retrieve the suffix, and append to the RPC path before reporting data.

**Comment by matttproud** [comment]
I'll need to confer with others on this, but I don't facially think attaching a suffix with `context.WithValue` would be sufficient nor scalable, since we don't have control over how end-users make calls with the stub.  I'm also not 100% sure that accessing this in the interceptors is even correct; that was mere speculation.

Our team, specifically, provides a middleware into which teams build their business logic wherein we create and provide stubs to the user's business logic.  Ideally there would be as little extra dance required by the user per-call, and expecting each outbound caller to attach the context key-value pair would probably be error-prone.  Generally speaking, like `grpc::StubOptions`, a suffix is really an attribute of the stub, not the call.

**Comment by menghanl** [comment]
Adding an interceptor which attaches the suffix to the context wouldn't be that bad I think.
It's a DialOption, so it's per client. Users don't need to do anything when making RPCs.

**Comment by matttproud** [comment]
I will return to this pull request post-holiday break.

**Comment by zasweq** [comment]
@matttproud friendy ping.

**Comment by matttproud** [comment]
@mklencke and I spoke about this.  He's agreed to look into.

**Comment by mklencke** [comment]
Thanks for the suggestions!

The context should be usable, with the caveat that adding a value grows the context slightly, adding some overhead.

We might also want to use a different suffix per RPC client (not connection), while `DialOption`s are per connection.

I'll report back here soon.

**Comment by mklencke** [comment]
We can currently work with the `context` solution, thank you! It would be nice to be able to customize the suffix per service client (instead of per connection), but that might require significant changes to [generated client interfaces](https://github.com/grpc/grpc-go/blob/master/examples/route_guide/routeguide/route_guide_grpc.pb.go#L24) and [`ClientConnInterface`](https://github.com/grpc/grpc-go/blob/9cb411380883ddbf69467b4ba1099817c0fe6c61/clientconn.go#L443).

A per-client wrapper that adds the relevant context or, alternatively, using per-connection interceptors seems more viable.

This bug can be closed, thanks!

**Comment by menghanl** [comment]
On suffix per service client: the interceptor can apply different suffix based on the method name, **if** the interceptor knows all the services and their corresponding suffix beforehand.
