### ISSUE TITLE
is there a way to setup timeout in grpc server side ?

### ISSUE THREAD

**Issue by worldwalk** [grpc/grpc-go#5059]
I know we can set timeout from grpc client and it could be transferred to grpc server side... 
but could we *just* set timeout in grpc server side?

sorry i google a lot but failed.

**Comment by easwars** [comment]
Can you please be more specific about what sort of timeout you wish to set on the server side? 

We have a server option to set a timeout on connection establishment: https://pkg.go.dev/google.golang.org/grpc#ConnectionTimeout

We have ways to configure keepalive parameters on the server: https://pkg.go.dev/google.golang.org/grpc@v1.43.0/keepalive#ServerParameters

And if we wish to set timeouts on a per-RPC level, you could register a server interceptor using https://pkg.go.dev/google.golang.org/grpc#UnaryInterceptor and create a new `context` in there with a different timeout and pass it to the handler.
