### ISSUE TITLE
using go mod tidy , there is error: google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.43.0), but does not contain package google.golang.org/grpc/naming

### ISSUE THREAD

**Issue by ayanmw** [grpc/grpc-go#5072]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
v1.43.0

### What version of Go are you using (`go version`)?
go1.17.0

### What operating system (Linux, Windows, …) and version?
windows

### What did you do?
```shell
$ go mod tidy
go: finding module for package google.golang.org/grpc/naming
icefire/confer imports
        github.com/spf13/viper/remote imports
        github.com/xordataexchange/crypt/config imports
        github.com/xordataexchange/crypt/backend/etcd imports
        github.com/coreos/etcd/client tested by
        github.com/coreos/etcd/client.test imports
        github.com/coreos/etcd/integration imports
        github.com/coreos/etcd/proxy/grpcproxy imports
        google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.43.0), but does not contain package google.golang.org/grpc/naming
```

### What did you expect to see?
grpc v1.XXX is Ensures forward compatibility .

**Comment by ayanmw** [comment]
I try to fix problem with 
```
replace google.golang.org/grpc => github.com/grpc/grpc-go v1.26.0
``` int the `go.mod` file.
But got error:
```
        github.com/spf13/viper/remote imports
        github.com/sagikazarmark/crypt/config imports
        github.com/sagikazarmark/crypt/backend/firestore imports
        cloud.google.com/go/firestore imports
        cloud.google.com/go/firestore/apiv1 imports
        google.golang.org/api/transport/grpc imports
        google.golang.org/grpc/xds/googledirectpath: module google.golang.org/grpc@latest found (v1.43.0, replaced by github.com/grpc/grpc-go@v1.26.0), but does not contain package google.golang.org/grpc/xds/googledirectpath
```

IT IS VERY VERY VERY VERY VERY   CONFUSE  ME!!!!!!!!!!!

**Comment by dfawley** [comment]
The `naming` package was deleted long ago.  This was not a backward compatible change, but the package was marked as experimental, so it is a change that we reserve the right to make.

Whatever you are using that is (indirectly) using the `naming` package from grpc-go should either be updated in your `go.mod` (`go get <whatever@whatever>`) or needs to be updated.  The direct import that requires this package is `etcd`, but it has been patched (many months ago) to no longer require it.

It's also possible you could force the `etcd` version to be higher in your `go.mod`, but I'm not sure if there are breaking changes in `etcd` that would make that infeasible.  It would be best to just update all your dependencies.
