### ISSUE TITLE
Bazel build error with undefined symbols

### ISSUE THREAD

**Issue by saeidakbari** [grpc/grpc-go#5088]
### What version of gRPC are you using?
`v1.43.0`

### What version of Go are you using (`go version`)?
`v1.17.1`

### What operating system (Linux, Windows, …) and version?
macOS

### What did you do?
Trying to build a project with `Bazel` but when it reaches to compile generated `.pb.go` files it produces errors.

### What did you expect to see?
The program compiles and runs as normal

### What did you see instead?
Error logs indicate that `SupportPackageIsVersion7` and some other signatures are not found.
```
ERROR: /private/var/tmp/_bazel_saeidakbari/e0ed28972838cb37f8997d44e5aee099/external/com_github_abriot_pgo_genproto/abriot/cloud/iam/v1/BUILD.bazel:3:11: GoCompilePkg external/com_github_abriot_pgo_genproto/abriot/cloud/iam/v1/iam.a failed: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src external/com_github_abriot_pgo_genproto/abriot/cloud/iam/v1/iam.pb.go -src ... (remaining 49 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/com_github_abriot_pgo_genproto/abriot/cloud/iam/v1/iam_grpc.pb.go:21:11: undefined: grpc.SupportPackageIsVersion7
external/com_github_abriot_pgo_genproto/abriot/cloud/iam/v1/iam_grpc.pb.go:105:31: undefined: grpc.ServiceRegistrar
external/com_github_abriot_pgo_genproto/abriot/cloud/iam/v1/iam_grpc.pb.go:253:30: undefined: grpc.ServiceRegistrar
external/com_github_abriot_pgo_genproto/abriot/cloud/iam/v1/iam_grpc.pb.go:347:29: undefined: grpc.ServiceRegistrar
compilepkg: error running subcommand external/go_sdk/pkg/tool/darwin_amd64/compile: exit status 2
Target //services/guard:guard failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.354s, Critical Path: 0.51s
INFO: 5 processes: 2 internal, 3 darwin-sandbox
```

**Comment by saeidakbari** [comment]
Also considering this issue from `rules_go` fir Bazel: [#2815](https://github.com/bazelbuild/rules_go/issues/2815)

**Comment by menghanl** [comment]
`SupportPackageIsVersion7` was added in v1.32.0: https://github.com/grpc/grpc-go/commit/a3740e5ed326410515aa921bbfe5688595732b77.
So if you are using `v1.43.0`, it should be there.

The only explanation I think is that your bazel config is not using the gRPC version you want.
Maybe your `proto_library` or `go_proto_library` is not updated, and is forcing an old gRPC.

This is more like a bazel config problem, not a gRPC problem.
I'm closing this issue. Please reply if you have further questions.
