### ISSUE TITLE
Mismatch between the json field in the protobuf struct tag and in the json struct tag

### ISSUE THREAD

**Issue by doriandekoning** [grpc/grpc-go#5090]
### What version of gRPC are you using?

An example can be seen in the in the examples on the custom master version.
344b93a

### What version of Go are you using (`go version`)?

```
go version go1.17.2 darwin/amd64
```
### What operating system (Linux, Windows, …) and version?

MacOs 11.5.1

### What did you do?
Generated proto files, used the grpc-gateway package which exposed a mismatch in the json fields.
However, the exact steps are not that relevant I believe since they can be seen in the example in this repository (but if useful I could make a small example too).

### What did you expect to see?
Either (I'm not sure what the official spec is):
```
PointCount int32 `protobuf:"varint,1,opt,name=point_count,json=point_count,proto3" json:"point_count,omitempty"`
```
or:
```
PointCount int32 `protobuf:"varint,1,opt,name=point_count,json=pointCount,proto3" json:"pointCount,omitempty"`
```

This is a problem because some code (grpc-gateway for example) uses the `pointCount` field but the golang json package uses the `json` annotation. 

### What did you see instead?

The tags regarding json in on the fields of the generated structs.
```
PointCount int32 `protobuf:"varint,1,opt,name=point_count,json=pointCount,proto3" json:"point_count,omitempty"`
```
https://github.com/grpc/grpc-go/blob/master/examples/route_guide/routeguide/route_guide.pb.go#L289

My apologies if I misunderstood and this is not the correct place to report this (suspected) issue (of if this is intended behaviour)

**Comment by menghanl** [comment]
This is a protobuf issue, not gRPC.
Can you check https://github.com/protocolbuffers/protobuf-go instead?

**Comment by doriandekoning** [comment]
Thanks, for other people stumbling on this issue here: https://github.com/golang/protobuf/issues/1403
