### ISSUE TITLE
grpc-go resolver Scheme capital letters are not supported after a version update

### ISSUE THREAD

**Issue by tk-xiong** [grpc/grpc-go#5093]
### What version of gRPC are you using?
 v1.40.0
 v1.42.0
 v1.43.0

### What version of Go are you using (`go version`)?
go 1.16

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?

I'll use the example code in the project, resolver
https://github.com/grpc/grpc-go/blob/master/examples/features/name_resolving/client/main.go

It work on all version
```
const (
	exampleScheme      = "example"
	exampleServiceName = "resolver.example.grpc.io"

	backendAddr = "localhost:50051"
)

```

But when I change the first letter to uppercase
v1.40.0 work
v1.42.0 not work:
v1.43.0 not work:
```
const (
	exampleScheme      = "Example"
	exampleServiceName = "resolver.example.grpc.io"

	backendAddr = "localhost:50051"
)
```

### What did you expect to see?
If not specified on the upgrade instructions, it should be compatible.

### What did you see instead?
Scheme does not support uppercase characters after a version update.
```
func (*exampleResolverBuilder) Build(
	target resolver.Target,
	cc resolver.ClientConn,
	opts resolver.BuildOptions,
) (resolver.Resolver, error) {
	fmt.Printf("%s", debug.Stack())
	r := &exampleResolver{
		target: target,
		cc:     cc,
		addrsStore: map[string][]string{
			exampleServiceName: {backendAddr},
		},
	}
	r.start()
	return r, nil
}
```

The function is not called.

**Comment by menghanl** [comment]
I believe it's working as intended that schemes are case sensitive.

It's not clear to me though how it worked in 1.40. It seems to also be case sensitive in 1.40.1: https://github.com/grpc/grpc-go/blob/v1.40.1/resolver/resolver.go#L47
