### ISSUE TITLE
grpc server cannot read self channelz information by a public func

### ISSUE THREAD

**Issue by Patrick0308** [grpc/grpc-go#5096]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?
 Sometimes we wanna get channelz information in grpc server selfs. May be exporting it as metrics or using a different format provide to client.

### Proposed Solution
Adding public functions which read channelz information from memory db.

**Comment by menghanl** [comment]
channelz is designed to be a service, to be accessed by another gRPC client. So the APIs are internal.

The stats API is supposed to be used in these cases.
What information are you trying to get from channelz that's not available in stats?

**Comment by Patrick0308** [comment]
@menghanl Thanks for your reply. We wanna pull the informations by rest client. The stats API need server store the stats data by implement handler. The channelz has a memory store that is very convenient for developer and useful.

**Comment by menghanl** [comment]
Channelz as a service was a cross team decision (https://github.com/grpc/proposal/blob/master/A14-channelz.md).
If we make it a library, it needs to be change for all the languages. Can you send an issue in the grpc/grpc repo if you really want this?

For now, the option is to start a local server for channelz, and fetch the data using a gRPC client.
Then you can serve the data via REST.
