### ISSUE TITLE
Please add an example to NewServer

### ISSUE THREAD

**Issue by stapelberg** [grpc/grpc-go#51]
It’s unclear to me whether `ServerOptions` can be nil.

Also, it’s unclear to me how to initialize an empty `ServerOptions`, i.e. if I do not want to use `MaxConcurrentStreams`, what do I pass to NewServer?

An example (embedded into the docs!) would greatly help with this.

**Comment by iamqizhao** [comment]
more example can be found at grpc/grpc-go/examples and grpc/grpc-common/go now.
