### ISSUE TITLE
Automatic metadata accumulation to delegate calls seems dangerous...

### ISSUE THREAD

**Issue by danjacques** [grpc/grpc-go#510]
gRPC currently has this behavior:
- The gRPC server [embeds](https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L187) request metadata into the `Context` that it passes to the service handler method.
- The gRPC client [pulls metadata](https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L339) from the supplied `Context` when making a gRPC call and loads it into the request.

This leads to a situation where metadata is, by default, accumulated over the course of successive delegate calls. For example, in a simple call chain:

```
A => B => C
```
1. **A** includes metadata **X** in its request.
2. **B**'s Context has **X** installed by the gRPC server from **A**'s request.
3. **B** then calls **C** during its request handling, using its `Context`.
4. Since **X** is still in the `Context`, the gRPC call to **C** automatically loads **X** from the `Context` into the request made to **C**.
5. **C** receives a `Context` with metadata **X**.

This happens by default, so I wanted to ask for clarification:
- Is the intent that it is the responsibility of a client to explicitly _clear_ metadata from its `Context` if it makes a delegate call?
- Is the `Context` re-use itself discouraged? This seems unreasonable, as `Context` may include things that we do want to forward, such as deadlines/cancellation.

If this is an intentional design decision, it seems unexpected and dangerous, as metadata intended for one component is implicitly forwarded to all delegate components by default. This could include sensitive information or specific directives for one specific component.

My preference would be to not have this spooky behavior and, instead, to require each gRPC client call to explicitly set the metadata that it wants to send via a `CallOption` or equivalent. WDYT?

**Comment by dfawley** [comment]
This was fixed under #1148
