### ISSUE TITLE
xds: Is there any plan to export the package xds/internal/xdsclient from the internal directory

### ISSUE THREAD

**Issue by longXboy** [grpc/grpc-go#5100]
It is very cool that grpc-go supports the xds protocol.At the same time, I am a developer of the go microservice framework .Is there any plan to remove the package `xds/internal/xdsclient` from the internal directory so that I can import dicretly and members of our framework can also contribute codes to grpc-go's xds client

**Comment by menghanl** [comment]
There is no short term plan to export the `xdsclient`, because we may need to change the APIs when we add more xds features to gRPC.

In the long term, it could be an option. But it will require more work, and won't happen any time soon.

**Comment by longXboy** [comment]
@menghanl thx for your reply，I understand

**Comment by yufeiminds** [comment]
I look forward to it, too. Thanks for your work.
