### ISSUE TITLE
Any plans to remove the dependency on the legacy protobuf package?

### ISSUE THREAD

**Issue by pevans-lutron** [grpc/grpc-go#5110]
Currently the project depends on both the legacy protobuf package (located at https://github.com/golang/protobuf) and the new v2 protobuf package (located at https://github.com/protocolbuffers/protobuf-go).  It would appear that the primary dependencies on the legacy protobuf package boil down to the common types (ptypes) which are implemented as a passthrough to the new package in the legacy protobuf package.  As such, it would seem that the dependency on the old package could be removed by just updating the references to the old package to use the new package/naming convention.

Is there any other reason to maintain the dependency?  If not, I could look into making the changes for contribution.

**Comment by menghanl** [comment]
There was a plan to do this (#3554), but it didn't finish.
Mainly because it is not a trivial change as it seems, and the benefit is questionable (types in the old packages are alias of the new types).

Besides, migrating from v1 to v2 could break users in unexpected ways, see #4330

**Comment by pevans-lutron** [comment]
Ok, this makes sense.  Will need to think through it a bit more.  The benefit I see is primarily for users of grpc to minimize third-party dependencies.  More dependencies tends to be a negative as it increases the surface area to monitor for defects/bug fixes, security vulnerabilities, etc.  Thanks!
