### ISSUE TITLE
Any plans to remove the genproto external dependency from the project?

### ISSUE THREAD

**Issue by pevans-lutron** [grpc/grpc-go#5111]
The genproto package dependency maintained by this project has been perpetually "experimental" for several years now.  It seems like the main reason for the dependency is to get the generated code for the googleapis to get the status type used to manage error handling over protobuf.  Would another option be to start generating the code directly from the googleapis repo and put it directly into this repository?  Are there any downsides to this approach.  It would be nice to remove a dependency on an experimental project for production usage of grpc-go.

**Comment by menghanl** [comment]
If I didn't miss anything, this is infeasible.
The message types are registered by their names to support proto.Any. If two types have the same name, it used to panic at registering time (I didn't find the code of the new behavior)

And if we do that, there's also the unexpected breaking change as in #4330

**Comment by pevans-lutron** [comment]
Maybe I am missing something, but to be clear I am referring to usages like this: https://github.com/grpc/grpc-go/blob/ba41bbac225e6e1a9b822fe636c40c3b7d977894/internal/status/status.go#L36

It's not clear to me why the grpc project couldn't have its own generated version of googleapis (from this repo which is the real reference souce - https://github.com/googleapis/googleapis/) and use that instead.  Perhaps the grpc package public API exposed the usage of this third party package and its types so that it would be a breaking change?  But that would surprise me since the grpc project has its own status package which wraps it as a private member - https://github.com/grpc/grpc-go/blob/ba41bbac225e6e1a9b822fe636c40c3b7d977894/internal/status/status.go#L43

**Comment by menghanl** [comment]
Regenerating code defines another type (with the exact same fields as the "official" copy).
Both these have the same proto TypeURL (e.g. `"google.rpc.Status"` for the status message), which will be used by `proto.Any`: https://pkg.go.dev/google.golang.org/protobuf/types/known/anypb#Any

So whenever you have an `Any` with the type `"google.rpc.Status"`, you will have two go structs to pick from, and this will cause problems.
I remember the old behavior was to panic whenever two messages are registered for the same TypeURL, but I'm not exactly sure about the new behavior.

So in general, any "well-known" proto messages should be defined in one place and shared.
