### ISSUE TITLE
Intended usage of protoc-gen-go-grpc

### ISSUE THREAD

**Issue by nickcorin** [grpc/grpc-go#5116]
Hey guys,

I am trying to generate some Go code for my gRPC service.

I used to use the older `github.com/golang/protobuf` repo for both Protobuf and gRPC code generation. From the ReadMe of that repo, it says that it's since been superceded by `google.golang.org/protobuf` for Protobuf and `google.golang.org/grpc` (this repo) for gRPC. I understand the reason for the split and support it.

Compiling the Protobufs is working fine, as intended. gRPC on the other hand, I'm having trouble.

`google.golang.org/protobuf` provides `protoc-gen-go` for generating Go bindings for Protobufs.
`google.golang.org/grpc` provides `protoc-gen-go-grpc` for generating Go bindings for gRPC services.

When compiling with `protoc`, by default it is searching for `protoc-gen-go_grpc`. Note the underscore. This is failing because I don't have a binary with that name installed.

I haven't been able to find useful documention about how to use `protoc-gen-go-grpc` (note the dash) as of yet. I have followed everything that I have found, without any success.

I have deleted, and re-installed `protoc`, `protoc-gen-go` and `protoc-gen-go-grpc` to ensure I am not using incorrect binaries or paths. I am installing by using the commands below:

```
$ brew install protobuf
$ go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
$ go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
```

I am compiling using the following commands:

```
$ protoc --proto_path=. --go_grpc_out=. --go_grpc_opt=paths=source_relative <file>.proto

protoc-gen-go_grpc: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--go_grpc_out: protoc-gen-go_grpc: Plugin failed with status code 1.
```

For some additional info, here are some PATH outputs:

```
$ echo $GOPATH
/Users/<username/dev/go

$ echo $GOBIN
/Users/<username/dev/go/bin

$ which protoc
/opt/homebrew/bin/protoc

$ which protoc-gen-go
/Users/<username>/dev/go/bin/protoc-gen-go

$ which protoc-gen-go_grpc
protoc-gen-go_grpc not found

$ which protoc-gen-go-grpc
/Users/<username>/dev/go/bin/protoc-gen-go-grpc
```

Any assistance or documentation would be greatly appreiated. I'm more than happy to update dated documentation if need-be.

**Comment by tfidfwastaken** [comment]
Ran into the same problem, wondering what your solution was @nickcorin?

I did a hack to make this work:
```
ln -s ~/.go/bin/protoc-gen-go-grpc ~/.go/bin/protoc-gen-go_grpc
```

Just made a link to the binary with the underscored name, and that seems to have solved it for now.

**Comment by dfawley** [comment]
The commandline parameters should use `--go-grpc_out=.` not `--go_grpc_out=.`.  `protoc` looks for a binary with `protoc-gen-FLAG` where `FLAG` is `--FLAG_out`.  An example commandline is listed here: https://github.com/grpc/grpc-go/tree/master/cmd/protoc-gen-go-grpc

**Comment by nickcorin** [comment]
@dfawley is right.

You can see my answer to my quetion on [StackOverflow](https://stackoverflow.com/questions/70643183/how-am-i-supposed-to-use-protoc-gen-go-grpc).

**Comment by tfidfwastaken** [comment]
Thanks, both of you.
