### ISSUE TITLE
possibly incorrect integer bounds?

### ISSUE THREAD

**Issue by setharnold** [grpc/grpc-go#5137]
https://github.com/grpc/grpc-go/blob/a002994200f31f5b3e985e6b2cd2f12cb8b81389/service_config.go#L271

Hello, Coverity flagged this line:

```
			if *m.MaxRequestMessageBytes > int64(maxInt) {
```

as a constant expression:

> Operands don't affect result (CONSTANT_EXPRESSION_RESULT)result_independent_of_operands: `*m.MaxResponseMessageBytes > 9223372036854775807 /* (int64)maxInt */` is always false regardless of the values of its operands. This occurs as the logical operand of if.

I don't understand golang well enough myself to judge.

Thanks

**Comment by menghanl** [comment]
I think value of max int is based on the system (32bit vs 64bit).

**Comment by menghanl** [comment]
And there was a PR #5140 trying to fix this.
