### ISSUE TITLE
Q: msgpack supporting PB?

### ISSUE THREAD

**Issue by ivanjaros** [grpc/grpc-go#5139]
I am using PB messages for websocket and right now I am encoding them as JSON but would like to switch to more efficient message pack. But so far I have not found any library that would properly un/marshal PB messages. Mostly it is the issue if oneof fields and the field names/field tags. So I wonder if there is msgpack library that actually supports protocol buffers and can properly de/serialize them?

**Comment by menghanl** [comment]
This is a protobuf question. Can you try asking in this repo (https://github.com/protocolbuffers/protobuf-go)? Thanks!

**Comment by ivanjaros** [comment]
#facepalm, you're 100% correct.
