### ISSUE TITLE
namespace-conflict 

### ISSUE THREAD

**Issue by yiaw** [grpc/grpc-go#5147]
Hi. 
studying grpc, i have question and wirte 
```
:> cd $GOPATH/grpc-example 
:> tree protos
protos/
├── google
│   └── api
│       ├── annotations.proto
│       └── http.proto
├── v1
│   ├── chat
│   │   ├── chat_grpc.pb.go
│   │   ├── chat.pb.go
│   │   ├── chat.proto
│   │   └── Makefile
│   └── user
│       ├── Makefile
│       ├── README.md
│       ├── user_grpc.pb.go
│       ├── user.pb.go
│       └── user.proto
└── v2
    ├── chat
    │   ├── chat_grpc.pb.go
    │   ├── chat.pb.go
    │   ├── chat.pb.gw.go
    │   ├── chat.proto
    │   └── Makefile
    └── user
        ├── Makefile
        ├── user_grpc.pb.go
        ├── user.pb.go
        ├── user.pb.gw.go
        └── user.proto
```
v1 proto is only support rpc 
v2 proto is support http gateway 

i wrote  `package` and `go_package`  proto buffer 
| https://github.com/yiaw/grpc-example/protos
v1.chat.proto
```proto
syntax = "proto3";
package v1.chat;

option go_package = "github.com/yiaw/grpc-example/protos/v1/chat";

```
v2 chat.proto 
```proto
syntax = "proto3";
package v2.chat;

option go_package = "github.com/yiaw/grpc-example/protos/v2/chat";
 ... 
```

rpc is implemented hear . 
| https://github.com/yiaw/grpc-example/internal/app
v1chat
```go
package chat

import (
   ... 
    chatpb "github.com/yiaw/grpc-example/protos/v1/chat"
)

func NewChatServer(s *grpc.Server) *grpc.Server {
    if s == nil {
        return nil
    }

    chatpb.RegisterChatServiceServer(s, &ChatServer{})
    return s
}
```

v2chat
```go
package chat

import (
   ... 
    chatpb "github.com/yiaw/grpc-example/protos/v2/chat"
)

func NewChatServer(s *grpc.Server) *grpc.Server {
    if s == nil {
        return nil
    }

    chatpb.RegisterChatServiceServer(s, &ChatServer{})
    return s
}
```

some grpc package 

```go
func NewGRPCServer(tlsenable bool) (*grpc.Server, error) {
    s := grpc.NewServer()
    v1chat.NewChatServer(s)
    v2chat.NewChatServer(s)
    reflection.Register(s)

    return s, nil
}
```

i try go run 
```
:> go run main.go
panic: proto: file "chat.proto" is already registered
	previously from: "github.com/yiaw/grpc-example/protos/v2/chat"
	currently from:  "github.com/yiaw/grpc-example/protos/v1/chat"
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```
i solved the problem by modifying it from protos/v2/chat/chat.proto to  protos/v2/chat/v2chat.proto

so .. 
same for the user proto, i worte /v1/user/user.proto /v2/user/user.proto 
why didn't there be an error ??

**Comment by menghanl** [comment]
It's not clear to me how exactly the panic happened (or why it didn't happen for `user.proto`).
But it's in general a bad idea to declare duplicate proto types, for reason in https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict.

Did you try to reuse the types in v1 and v2?
What's different between `v1/chat/chat.pb.go` and `v2/chat/chat.pb.go`?
I would expect v2 (the http gateway version) to have have all the types in v1.

**Comment by yiaw** [comment]
Thanks you for answering the question.

`v1/chat/chat.pb.go` to `v2/chat/chat.pb.go` is not different 

The only difference between `v1/chat.proto` and `v2/chat.proto` is whether the `option(google.api.http)`  is used or not.

I understand which part was the problem.

Thanks again for your reply.
