### ISSUE TITLE
Allow disabling of GOAWAY response to too many client pings

### ISSUE THREAD

**Issue by stanhu** [grpc/grpc-go#5161]
### Use case(s) - what problem will this feature solve?

As discussed in https://github.com/grpc/grpc/issues/25713, it's very easy to wreak havoc by tweaking the gRPC keepalive interval on the client. Currently it appears gprc-go [hard-codes the limit to 2 pings within a period](https://github.com/grpc/grpc-go/blob/670c133e568e89c901d05b898af9f5ce72a88c6d/internal/transport/http2_server.go#L835-L836): if a client goes over this limit, a GOAWAY message is sent, and the server shuts down the connection.

https://github.com/grpc/grpc/issues/25722#issuecomment-799842384 recommends that gRPC core users set `GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA` to 0, and https://github.com/grpc/grpc/blob/master/doc/keepalive.md#keepalive-user-guide-for-grpc-core-and-dependents even mentions:

> This channel argument controls the maximum number of pings that can be sent when there is no data/header frame to be sent. gRPC Core will not continue sending pings if we run over the limit. Setting it to 0 allows sending pings without such a restriction. (Note that this is an unfortunate setting that does not agree with A8-client-side-keepalive.md. There should ideally be no such restriction on the keepalive ping and we plan to deprecate it in the future.)

### Proposed Solution

Allow users of grpc-go to configure this limit and/or disable it outright.

**Comment by dfawley** [comment]
cc @ejona86

> ...recommends that gRPC core users set `GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA` to 0

https://github.com/grpc/grpc/issues/25722#issuecomment-799842384 _also_ says:

> We intend to deprecate this channel arg as soon as we can fix this behavior

Go has the workaround that should avoid the need for this as explained [here](https://github.com/grpc/grpc/issues/25713#issuecomment-800507107).  I don't believe this is something you should need in general operation.

Can you explain what this is needed for?  It seems it should be added to the [gRFC](https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md) if it's necessary.

**Comment by stanhu** [comment]
>  Go has the workaround that should avoid the need for this as explained here. I don't believe this is something you should need in general operation.

@dfawley What is this workaround? On a Ruby gRPC client, we set `GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA` to 0, but then we found the grpc-go server would send the `GOAWAY` message quite often, prematurely aborting connections: https://github.com/grpc/grpc-go/blob/670c133e568e89c901d05b898af9f5ce72a88c6d/internal/transport/http2_server.go#L882-L887

**Comment by dfawley** [comment]
Oh I see; you want to change the server behavior to not mind clients that over-aggressively ping and don't scale back their pings?

Why?  The c-core client (and Ruby's wrapped version of it) should be throttling its pings now: https://github.com/grpc/grpc/pull/23313.  Are you running a version with that change?

**Comment by stanhu** [comment]
@dfawley Interesting, thanks! We were running gRPC v1.30.2--which does not appear to have https://github.com/grpc/grpc/pull/23313--but then recently upgraded to gRPC v1.42.0, which does. Ironically, we started seeing these `GOAWAY` messages after that upgrade. As you can see in [our production logs](https://gitlab.com/gitlab-org/gitlab/-/issues/350580#note_819852115), the server generated close to a million `GOAWAY` messages per day.

**Comment by dfawley** [comment]
Maybe you're setting other channel args that conflicts with the throttling?  Maybe _this_ channel arg conflicts?

Anyway, I think this is a client-side issue.  Disabling this check on the server does not seem appropriate.

**Comment by stanhu** [comment]
We haven't touch `grpc-go` settings after we upgraded the client. I'm not sure why throttling isn't working, but we have worked around the problem by disabling client keepalives and enabling the server keepalives instead.

**Comment by dfawley** [comment]
> We haven't touch grpc-go settings after we upgraded the client

I meant that it's possible you are setting other things on the _client_ that are interfering with the _client's_ ability to throttle pings.  It may still be worthwhile to file a bug in the grpc/grpc repo about this since it seems like there may be a bug.  The only exception I could see is if there is a channel arg you are setting that is documented as disabling the throttling or something.

**Comment by stanhu** [comment]
https://github.com/grpc/grpc/issues/28830 might explain why these GOAWAY messages are happening with the throttling. The client may be sending them a tad too fast since jitter is an issue.

**Comment by dfawley** [comment]
If that happens, then the client should be lowering its rate such that it won't happen even due to jitter eventually.

**Comment by ejona86** [comment]
There's an inherent "grace" period of 1 RTT, so that C problem looks like it should only impact low-RTT connections. That is to say, if you see the problem between machines that have 1ms+ RTT, then it may be a different issue. (Although, until we know why it is happening we can't be certain of the upper-bound of client inaccuracy.)
