### ISSUE TITLE
how to return context or header to client

### ISSUE THREAD

**Issue by iweixubin** [grpc/grpc-go#5163]
grpc base on http2
http can  respond response header

``` go
func (the *ServiceServer) Ask(ctx context.Context, req *pb.AskRequest) (*pb.AskResponse, error) {
	// how to respond context
	resp := &pb.AskResponse{}
	return resp, nil
}
```

**Comment by menghanl** [comment]
Sounds like metadata is what you want
https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md
https://github.com/grpc/grpc-go/tree/master/examples/features/metadata
