### ISSUE TITLE
Request 'gRPC-Go to support HTTP/3'

### ISSUE THREAD

**Issue by larspaulsen** [grpc/grpc-go#5186]
Request 'gRPC-Go to support HTTP/3'

### Use case(s) - what problem will this feature solve?
By gRPC-Go supporting HTTP/3 the following primary goals will be achieved:

1. Elimination of head-of-line issue.
2. Seamless switching between underlying IP infrastructure, such as Cellular and Wi-Fi media.
3. Support of zero round-trip connection reestablishment.

### Proposed Solution
gRPC-Go to support HTTP/3

### Alternatives Considered
None

### Additional Context
gRPC .NET 6 already provides support for HTTP/3:
https://devblogs.microsoft.com/dotnet/http-3-support-in-dotnet-6/#grpc-with-http-3

The .NET already implemented 'Proposal':
https://github.com/JamesNK/proposal/blob/jamesnk/http3/G2-http3-protocol.md

**Comment by easwars** [comment]
This is not something that is on the team's current plans for the foreseeable future.

@dfawley : Do you know if C/Java have this support or they have plans for this? Thanks.

**Comment by dfawley** [comment]
Along with https://github.com/grpc/grpc-java/issues/8897, let's close this in favor of the cross-language issue at https://github.com/grpc/grpc/issues/19126.

**Comment by larspaulsen** [comment]
Ok, I will move my arguments/request to the 'cross-language' thread.
