### ISSUE TITLE
Minor cleanups considered…

### ISSUE THREAD

**Issue by zellyn** [grpc/grpc-go#519]
I'd like to float the idea of tidying up some stuff slightly, and wanted to test the ideas out before working on PRs.

First, I noticed that there are a number of places contexts are passed as second arguments, which is against the guidelines and normal style. It seems slightly painful to clean up, because it needs a corresponding change in the protobuf generator, but on the other hand now is going to seem like a really good time to clean it up compared to later. (Contexts are saved in struct fields for Steams, which is also against the guidelines, but seems like it's probably okay/difficult to avoid.)

Second, there are places where the abundant use of one- and two-character names seems extreme even by normal Go standards, and makes the code difficult to read. Here's an example in [server.go](https://github.com/grpc/grpc-go/blob/a0f854fe/server.go#L474-L489).

I noticed both @bradfitz and @iamqizhao have been active recently in this code - I'd be interested in your opinions on both points. Are the abbreviations consistent/standard enough to be okay?

I'm also happy to do the work in fixing both…

**Comment by dsymonds** [comment]
Which places don't have contexts as their first arg?

It's fine for contexts to be stored in structs when they are inherently tied to the lifetime of the struct. In the case of a Stream, the context is for that stream (and created by grpc-go), so it's fine for it to be stored in that struct.

**Comment by zellyn** [comment]
Example: https://github.com/grpc/grpc-go/blob/master/server.go#L57

This is mirrored in generated grpc code with declarations like `func _ExampleService_SendData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {`

**Comment by iamqizhao** [comment]
I think the only place is

func _TestService_UnaryCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
  ...
}

And I think this is fine because ctx in this function is not different from a common param.

**Comment by zellyn** [comment]
Note: I'm increasingly un-up-to-date on current style now that I can't lurk the internal Google mailing lists, so happy to defer to you folks on style opinions. :-)

**Comment by dsymonds** [comment]
That one isn't so obvious. The first arg is really behaving like a curried receiver. At least it isn't an exported API, though, so I am not too bothered by it. Did you have any others?

**Comment by bradfitz** [comment]
Yeah, for private auto-generated code, I don't care too much about style.

**Comment by zellyn** [comment]
Nope, actually, now that I do a quick grep :-)

That one just jumped out at me because "handler" is one of the natural places to interpose wrapping functions / filters, which we're going to need to add as we convert from our in-house RPC mechanism to GRPC (it's Stubby-ish, called Sake). We'll probably need to wrap handlers in things that can do (a) per-method ACL checks, (b) insertion of things into the context that all our code currently expects, etc.

On the other hand, that `srv interface{}` feels a little like `self` / currying, as you mentioned, so it seems okay. The other reason I ask is that I've seen this pattern in our own internal code, and erred on the side of moving `ctx` to first position, but it made me curious.

**Comment by iamqizhao** [comment]
@zellyn 

I am talking to @dsymonds about the interceptor change (yes, handler :). I will keep you posted on that part.

**Comment by iamqizhao** [comment]
one- and two-character names are not rare in the standard package impl. But feel free to send me renaming PR if you feel you have better idea about naming. Closing this issue now.
