### ISSUE TITLE
Local Client?

### ISSUE THREAD

**Issue by jdoliner** [grpc/grpc-go#520]
There might be an easy way to do this that I'm missing but I've done a decent amount of searching.

Would it be possible to add something like:

```go
func NewLocalAPIClient(s APIServer) APIClient 
```

Right now the only way I know of to do this is binding to a local socket and connecting to it from within the same process but that feels quite hacky. Is there a more canonical way to accomplish it?

**Comment by dsymonds** [comment]
Dialing a localhost address is the recommended way. It's very efficient, and exercises all parts of the connection so that things are less likely to mysteriously break when you start operating over multiple machines.

**Comment by iamqizhao** [comment]
In-process server (or local client) is not supported (we have not had plan for that yet). As David said, dialing a unix domain socket (or a localhost address) is the way to go assuming you do not have high demanded performance requirements.
