### ISSUE TITLE
Retry Middleware not Honored

### ISSUE THREAD

**Issue by halspang** [grpc/grpc-go#5208]
### What version of gRPC are you using?
`google.golang.org/grpc v1.40.0`
`github.com/grpc-ecosystem/go-grpc-middleware v1.2.2`

### What version of Go are you using (`go version`)?
1.17.1

### What operating system (Linux, Windows, …) and version?
Mac 12.2.1

### What did you do?
If possible, provide a recipe for reproducing the error.

This happens during a gRPC proxying flow inside of [dapr](http://github.com/dapr/dapr).

Adding the `WithMax/WithPerRetryTimeout` to a `ClientStream` did not result in any retries. We added them as CallOptions here: https://github.com/dapr/dapr/blob/master/pkg/grpc/proxy/handler.go#L75

This called into a .NET gRPC app which threw a:

```csharp
throw new RpcException(new Status(StatusCode.ResourceExhausted, "Resource exhausted"));
```

Here's the ClientStream initialization:

```go
clientStream, err := grpc.NewClientStream(clientCtx, clientStreamDescForProxying, backendConn, fullMethodName, grpc.CallContentSubtype((&codec.Proxy{}).Name()), grpc_retry.WithMax(5), grpc_retry.WithPerRetryTimeout(time.Second), grpc_retry.WithCodes(codes.ResourceExhausted))
```

### What did you expect to see?
The request should have retried up to the max set (5) and with a timeout of 1 second between each call.

### What did you see instead?
No retries fired.

**Comment by menghanl** [comment]
This looks like a middleware issue.
Please file an issue at https://github.com/grpc-ecosystem/go-grpc-middleware. Thanks!
