### ISSUE TITLE
Add support for CORS on the server

### ISSUE THREAD

**Issue by nodirt** [grpc/grpc-go#521]
Please add support for CORS, so that a developer can control Access-Control-Allow-Origin header in responses.

Context: we are planning to make RPCs from a browser (javascript), from a different origin.

Thanks.

**Comment by bradfitz** [comment]
You can do this yourself once #75 and #514 land.

**Comment by hsaliak** [comment]
#75 and #514 have landed, if this is still an issue, @nodirt please reopen.

**Comment by hunnain** [comment]
Can you tell me how i request grpc server from browser whenever i called browser give me an error of cross origin i have seen 75 and 514 but didn't understand

**Comment by menghanl** [comment]
@hunnain For browser support, please take a look at https://github.com/grpc/grpc-web
