### ISSUE TITLE
Delay picker updates while updating children in priority, RLS, xds_cluster_manager, and weighted_target

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-go#5211]
To allow localities moving priorities within xDS atomically, when processing a config update, the priority policy should inhibit upward picker updates of its own until it has provided the configs to all of its children. Children update their picker synchronously when receiving the config update, so after passing down the new configuration to all children the priority policy will have updated pickers for each and should at that point propagate its own picker update upward. This was decided in the cross-language TL discussion on 2022-02-11.

We need to audit the code to ensure existing LBs update their picker synchronously, and tweak the docs.

grpc/grpc#28984 grpc/grpc-java#8952

**Comment by markdroth** [comment]
We've realized that we also need to do this for the xds_cluster_manager and weighted_target policies.

(Basically, our rule should be that we do this for any policy that has multiple active children at the same time.)

**Comment by dfawley** [comment]
Update: `xds_cluster_manager` uses `balancergroup` which synchronously handles `UpdateState` calls from children, and `UpdateClientConnState` is handled synchronously as well, so I believe this is already being handled properly.
