### ISSUE TITLE
how to get balancer picked endpoint on each call

### ISSUE THREAD

**Issue by rikewang** [grpc/grpc-go#5217]
## What version of gRPC are you using?
v1.26.0

## What version of Go are you using (go version)?
$ go version
go version go1.16.4 darwin/amd64

## What did you expect to see?
We wanna get picked result on each call for debuging which server to sent to

**Comment by menghanl** [comment]
Sounds that you need the peer address:
- Unary: https://pkg.go.dev/google.golang.org/grpc#Peer
- Streaming: https://pkg.go.dev/google.golang.org/grpc@v1.44.0/peer#FromContext

**Comment by heartlock** [comment]
Can you  enable env `GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_GO_LOG_VERBOSITY_LEVEL=2` on the client side? Maybe you can see the picked result in the client log.

**Comment by rikewang** [comment]
> Can you enable env `GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_GO_LOG_VERBOSITY_LEVEL=2` on the client side? Maybe you can see the picked result in the client log.

yes，thanks. 
it's enough for debugging. 
actually, we wanna to print picked endpint at our logs, having a api would be a better method.

**Comment by rikewang** [comment]
> Sounds that you need the peer address:
> 
> * Unary: https://pkg.go.dev/google.golang.org/grpc#Peer
> * Streaming: https://pkg.go.dev/google.golang.org/grpc@v1.44.0/peer#FromContext

we wannan the picked result after balancer, the request maybe not be sent or sent failed.  so `peer` not very valuable.

**Comment by dfawley** [comment]
The peer should be set even if there is an RPC error.  It's possible it does not get set if the RPC didn't get sent to a peer at all (e.g. error before picking), but then there just is no peer.
