### ISSUE TITLE
why the "loadBalancingPolicy“ must be used when "healthCheckConfig" in grpc

### ISSUE THREAD

**Issue by zhu121** [grpc/grpc-go#5224]
The code file is： https://github.com/grpc/grpc-go/blob/master/examples/features/health/client/main.go
```go
var serviceConfig = `{
    "loadBalancingPolicy": "round_robin",
    "healthCheckConfig": {
        "serviceName": ""
    }
}`
```
Why "serviceConfig" must have ""loadBalancingPolicy": "round_robin"", the client can check the health status of the server normally? 
I tried removing "loadBalancingPolicy", or not using "round_robin", it doesn't work.

**Comment by dfawley** [comment]
Conceptually, if you have `pick_first` as your LB policy (the default), health checking isn't going to help you at all.  Health checking leaves you connected to the server(s) even when they are unhealthy, and the round robin picker just chooses the healthy backends and skips the unhealthy ones.  If you're using pick first then the first connected backend will be used regardless of whether it's healthy.

For more details: https://github.com/grpc/proposal/blob/master/A17-client-side-health-checking.md
