### ISSUE TITLE
Referring to the go mod specification, add v1 v2 to the go module path when there is an incompatibility

### ISSUE THREAD

**Issue by zhijian-pro** [grpc/grpc-go#5226]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?
When multiple third-party libraries depend on different and incompatible `grpc`, the project cannot be used normally

eg `google.golang.org/grpc/v4 v4.0.0`

### Proposed Solution
Referring to the go mod specification, add v1 v2 to the go module path when there is an incompatibility

**Comment by dfawley** [comment]
Please refer to our [versioning policy](https://github.com/grpc/grpc-go/blob/master/Documentation%2Fversioning.md) and file a bug if you think we made a change that violates it.

**Comment by zhijian-pro** [comment]
@dfawley 
I have made a simple example repository [here](https://github.com/zhijian-pro/grpc-test) to demonstrate this problem, you can clone directly to the local and then `go mod tidy`.
error:
```
go mod tidy

go: finding module for package google.golang.org/grpc/naming
grpc-test imports
        github.com/tikv/client-go/v2/tikv imports
        go.etcd.io/etcd/clientv3 tested by
        go.etcd.io/etcd/clientv3.test imports
        go.etcd.io/etcd/integration imports
        go.etcd.io/etcd/proxy/grpcproxy imports
        google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.44.0), but does not contain package google.golang.org/grpc/naming

```

Suppose we have to use tikv v2.0.0-rc version and grpc v1.44.0 version.
If there is go module path, how to solve this problem ?
