### ISSUE TITLE
grpc version compatibility issue

### ISSUE THREAD

**Issue by zhijian-pro** [grpc/grpc-go#5230]
I have made a simple example repository [here](https://github.com/zhijian-pro/grpc-test) to demonstrate this problem, you can clone directly to the local and then go mod tidy.
error:
```
go mod tidy

go: finding module for package google.golang.org/grpc/naming
grpc-test imports
        github.com/tikv/client-go/v2/tikv imports
        go.etcd.io/etcd/clientv3 tested by
        go.etcd.io/etcd/clientv3.test imports
        go.etcd.io/etcd/integration imports
        go.etcd.io/etcd/proxy/grpcproxy imports
        google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.44.0), but does not contain package google.golang.org/grpc/naming
```
Suppose we have to use tikv v2.0.0-rc version and grpc v1.44.0 version.
If there is `go module` path, how to solve this problem ?

**Comment by zhijian-pro** [comment]
#5226

**Comment by dfawley** [comment]
The naming package was marked as experimental upon its initial introduction (https://pkg.go.dev/google.golang.org/grpc@v1.0.0/naming), and should not have been used in code that was intolerant to breakages.
