### ISSUE TITLE
Enum being discarded

### ISSUE THREAD

**Issue by chromosomaly** [grpc/grpc-go#5252]
### What version of gRPC are you using?
```v1.45.0```

### What version of Go are you using (`go version`)?
```
$ go version
go version go1.18 windows/amd64
```

### What operating system (Linux, Windows, …) and version?
```Windows 21H1 (OS Build 19043.1586)```

### What did you do?
In the proto file
```
...

service Broker {
  rpc QueueAPI (QueueAPIRequest) returns (stream QueueAPIReply) {}
}

message QueueAPIReply {
  string id = 1;
  enum StatusType {
    QUEUED = 0;
    ERROR_BEFORE_QUEUE = 1;
  }
  StatusType status = 2;
  string reason = 3;
  google.protobuf.Any data = 4;
}

...
```
When sending attempting to stream a reply from server to client with QUEUED:
```
elem := &pb.QueueAPIReply{Id: "123", Status: pb.QueueAPIReply_QUEUED, Reason: "test"}
stream.Send(elem)
```
The status enum disappears/gets discarded before .Send() is called with no errors or anything. Reaches client missing the field.

However, when sending:
```
elem := &pb.QueueAPIReply{Id: "123", Status: pb.QueueAPIReply_ERROR_BEFORE_QUEUE, Reason: "test"}
stream.Send(elem)
```
The status comes through fine.

### Fix
Only way I managed to get around it is changing the enum in the proto to:
```
enum StatusType {
  X = 0;
  QUEUED = 1;
  ERROR_BEFORE_QUEUE = 2;
}
```
And fully ignoring the X

**Seems like the enum with index = 0 doesn't work. Only similar issue I found was [*Issue #2533*](https://github.com/grpc/grpc-go/issues/2533)**

**Comment by menghanl** [comment]
If this is the same problem as in #2533, I assume you are coverting proto into json.
Did you try https://godoc.org/github.com/golang/protobuf/jsonpb?
