### ISSUE TITLE
xds/clusterresolver: reuse child policy names for the same locality to avoid SubConn churn

### ISSUE THREAD

**Issue by menghanl** [grpc/grpc-go#5268]
E.g. if a locality-A is moved from p1 to p0, the child policy should reuse the name for locality-A, to avoid recreating the SubConns.

**Comment by menghanl** [comment]
As mentioned in the internal doc: http://doc/13L2YVTGI2OrLpeCAPbgI4qEs0Oz02P7X0DKhk6Y9LMk#heading=h.r3twn1e6r8ct

**Comment by markdroth** [comment]
Note that you will also need to keep incrementing the counter for the next available child number to avoid incorrectly reusing a child name that the priority policy may still have around in deactivated state.  See internal bug b/225030722 and grpc/grpc#29316.
