### ISSUE TITLE
Flaky Test: 7/100k: Test/GoAwayThenClose

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc-go#5293]
https://github.com/grpc/grpc-go/runs/5838153283?check_suite_focus=true

**Comment by dfawley** [comment]
See also: #2822

**Comment by dfawley** [comment]
From #5663: 

> I can repro this on google3. About 7/100k times flakes. I think the test needs a bit of rewriting to ensure that when it fails, it fails fairly quickly. Now, the test just hangs until the go test timeout kicks in.

(I had 0/20k failures without tsan.)
