### ISSUE TITLE
Client-side Recv() blocked on waitOnHeader despite server's handler return

### ISSUE THREAD

**Issue by jameshartig** [grpc/grpc-go#5301]
### What version of gRPC are you using?
v1.45.0

### What version of Go are you using (`go version`)?
go 1.17

### What operating system (Linux, Windows, …) and version?
Linux (CentOS 7)

### What did you do?
Create a connection on the client with:
```
conn, err = grpc.Dial(
	addr,
	grpc.WithInsecure(),
	grpc.WithKeepaliveParams(keepalive.ClientParameters{
		Time:    time.Minute,
		Timeout: 5 * time.Second,
	}),
	grpc.WithBlock(),
)
if err != nil {
	return err
}

client, err := NewClient(conn).ServerRequests(ctx)
if err == nil {
	for {
		req, err := client.Recv()
		if err != nil {
			break
		}
		...
	}
}
```

Server Side:
```
server := grpc.NewServer(
	grpc.KeepaliveParams(
		keepalive.ServerParameters{
			Time:    5 * time.Minute,
			Timeout: 5 * time.Second,
		},
	),
)
...
func ServerRequests(srv coordinator_pb.Coordinator_ServerRequestsServer) error {
	...
	for {
		msg, err := srv.Recv()
		if err != nil {
			return err
		}
		switch imsg := msg.Msg.(type) {
		case *coordinator_pb.ServerRequestReply_Hello:
			...
		case *coordinator_pb.ServerRequestReply_Accept:
			...
		case *coordinator_pb.ServerRequestReply_Ready:
			...
		}
	}
}
```

### What did you expect to see?
When the server's Recv() fails with `rpc error: code = Canceled desc = context canceled`, I expect to also see the the Recv() fail on the client. I haven't quite determined why the server gets a context canceled as the client is not closing anything.

### What did you see instead?
The client's Recv() is stuck on `waitOnHeader` and there's still a keepalive going every 5 seconds. Why is the server responding to the keepalive if `ServerRequests` returned? Why was the stream not closed after the handler, `ServerRequests`, returned?

```
1 @ 0x43b896 0x44b672 0x809405 0x87f0db 0x87f0c8 0x87e685 0x87d2f3 0x87e3bf 0x8896ac 0xca57e2 0x46cda1
#       0x809404        google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader+0x84                                           google.golang.org/grpc@v1.45.0/internal/transport/transport.go:323
#       0x87f0da        google.golang.org/grpc/internal/transport.(*Stream).RecvCompress+0xba                                           google.golang.org/grpc@v1.45.0/internal/transport/transport.go:338
#       0x87f0c7        google.golang.org/grpc.(*csAttempt).recvMsg+0xa7                                                                google.golang.org/grpc@v1.45.0/stream.go:963
#       0x87e684        google.golang.org/grpc.(*clientStream).RecvMsg.func1+0x24                                                       google.golang.org/grpc@v1.45.0/stream.go:828
#       0x87d2f2        google.golang.org/grpc.(*clientStream).withRetry+0xd2                                                           google.golang.org/grpc@v1.45.0/stream.go:686
#       0x87e3be        google.golang.org/grpc.(*clientStream).RecvMsg+0x11e                                                            google.golang.org/grpc@v1.45.0/stream.go:827
#       0x8896ab        gitlab.com/levenlabs/infrastructure/llama/cluster/coordinator_pb.(*coordinatorServerRequestsClient).Recv+0x4b   gitlab.com/levenlabs/infrastructure/llama/cluster/coordinator_pb/coordinator_pb_grpc.pb.go:58
#       0xca57e1        main.(*server).RequestsSpin+0x4e1                                                                               gitlab.com/levenlabs/infrastructure/llama/cmd/llama-server/allocation.go:62
```

**Comment by dfawley** [comment]
> there's still a keepalive going every 5 seconds

From your configuration, it looks like keepalive pings are sent once per minute, with a timeout of 5s (the server must respond within that time to prevent the connection from closing).  This means it's possible the connection is lost but the client might not notice it for 1 minute.

> I haven't quite determined why the server gets a context canceled as the client is not closing anything.

If the server notices the connection is dead but the client does not, I believe this could happen.

> Why is the server responding to the keepalive if ServerRequests returned?

I don't understand.  How can you tell that the server is responding to keepalives?  And regardless of that, the server will respond to _all_ ping requests, even if there is no handler running.

How reproducible is this?  Do you know if there is a possible regression here from an older version of gRPC-Go?  Also if you can provide any more details of your scenario, it could help.

**Comment by jameshartig** [comment]
> This means it's possible the connection is lost but the client might not notice it for 1 minute.

I was seeing the client not notice for several hours, days even.

> How can you tell that the server is responding to keepalives?

I was inspecting traffic between the client and server and every 5 seconds I saw a ping back and forth.

> How reproducible is this?

Unfortunately, not easily. I'm still trying to determine the exact set of network events that cause this. I've started our application with grpc logging and started recording traffic to try and catch what happens when this occurs. I'll update this issue when it happens again.

> Do you know if there is a possible regression here from an older version of gRPC-Go?

As far as I'm aware this has been happening for several months now so I don't believe it to be a recent regression.

> Also if you can provide any more details of your scenario, it could help.

We have a bunch of GCE servers that connect to a single "coordinator" and wait for commands (jobs) to be passed to them over a GRPC stream. When the server starts up it opens a duplex stream over GRPC to accept and respond to commands. We're noticing that the coordinator thinks some servers are "dead" after a while and the servers themselves think they're still waiting for a job. This appears to only be happening with cross-region streams where the server rand coordinator live in different regions.

**Comment by dfawley** [comment]
One thing that might be helpful is enabling channelz, which keeps state and logs events at the connection level.

https://grpc.io/blog/a-short-introduction-to-channelz/

> I was inspecting traffic between the client and server and every 5 seconds I saw a ping back and forth.

Did you look at both the client and server, and see the pings were going back and forth?  And I see you have keepalives enabled on both sides, so are you seeing both sides sending and receiving pings and acks?

Do you have any kind of proxy in the middle of the connection?

As a workaround for now, you could have clients attempt to recreate streams every few minutes, even if they are working correctly.

>> How reproducible is this?
> Unfortunately, not easily

Can you say approximately how often it happens, taking into consideration the number of clients you have (I guess just the cross-region ones, since you say it never seems to happen intra-region)?  So if it happens once every day but you have 1000 clients, that would be much more rare than one failure every week but only 10 clients.

Another thing: the client is getting stuck waiting for a header response from the server -- do you manually send headers or a message from the server immediately upon stream creation?  Or do you wait until there is a job for the client, which could potentially take a very long time?  If the latter, you might try changing the server to send an empty header immediately (`stream.SendHeader(nil)`) just to see what happens.

**Comment by jameshartig** [comment]
> Did you look at both the client and server, and see the pings were going back and forth? And I see you have keepalives enabled on both sides, so are you seeing both sides sending and receiving pings and acks?

I wasn't capturing traffic on both ends until now. I'll update this thread when it happens again. Unfortunately I've been out the last few days so I'm trying to catch up.

> Do you have any kind of proxy in the middle of the connection?

It's going across 2 GCP regions using the private VPC IPs so I'm not sure what the internals of GCP looks like but afaik there's no proxy.

> Can you say approximately how often it happens, taking into consideration the number of clients you have (I guess just the cross-region ones, since you say it never seems to happen intra-region)? 

We only have 2 clients that are cross-region and it was happening every few days. Of course now that I'm debugging it, it hasn't happened in the last few days.

> do you manually send headers or a message from the server immediately upon stream creation?

Yes, the client immediately sends a message and wait for a response which the server should send immediately.

**Comment by JohnHuahuaZhan** [comment]
quit the kaspersky then everything will  be ok
