### ISSUE TITLE
server still working，client received “keepalive ping failed to receive ACK within timeout”

### ISSUE THREAD

**Issue by guangxuewu** [grpc/grpc-go#5308]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
v1.41.0
### What version of Go are you using (`go version`)?
golang 1.16.5
### What operating system (Linux, Windows, …) and version?
Linux Centos7.0
### What did you do?
If possible, provide a recipe for reproducing the error.
client setting
ClientParameters{
		Time:                10,
		Timeout:             20,
		PermitWithoutStream: true,
	}
server setting
grpc.KeepaliveEnforcementPolicy(keepalive.EnforcementPolicy{
			MinTime:             time.Millisecond,
			PermitWithoutStream: true,
		}
### What did you expect to see?
client work normal
### What did you see instead?
receive keepalive ping failed to receive ACK within timeout，and connection closeed

**Comment by menghanl** [comment]
> server still working

Did you mean that the server can receive messages from the client?

Or just that the server process is still running?
(In this case, there could be connection problems not detected by the server yet, and keepalive is designed to detect these problems)

**Comment by guangxuewu** [comment]
> > server still working
> 
> Did you mean that the server can receive messages from the client?
> 
> Or just that the server process is still running? (In this case, there could be connection problems not detected by the server yet, and keepalive is designed to detect these problems)

server can receive messages from the client
and Let me add one more piece of information.
When I roll back client the grpc module version to 1.29.1, there is no problem, and then upgrade to 1.41.0, the problem will reappear.

**Comment by menghanl** [comment]
Can you post the logs from both the client and server? https://github.com/grpc/grpc-go#how-to-turn-on-logging

Also, code where the problem can be reproduced would also be very helpful.
