### ISSUE TITLE
grpc golang output doesn't validate with goimport

### ISSUE THREAD

**Issue by Bluebugs** [grpc/grpc-go#5313]
### What version of gRPC are you using?
protoc-gen-go is v1.28.0

### What version of Go are you using (`go version`)?
1.18

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
Running `goimports -e -d examples/helloworld/helloworld/` on this project report errors. And this is true for all project using goimports and protoc-gen-go.

### What did you expect to see?
No error being reported.

### What did you see instead?
```
diff -u examples/helloworld/helloworld/helloworld.pb.go.orig examples/helloworld/helloworld/helloworld.pb.go
--- examples/helloworld/helloworld/helloworld.pb.go.orig	2022-04-18 13:07:38.358327018 -0600
+++ examples/helloworld/helloworld/helloworld.pb.go	2022-04-18 13:07:38.358327018 -0600
@@ -21,11 +21,12 @@
 package helloworld

 import (
+	reflect "reflect"
+	sync "sync"
+
 	proto "github.com/golang/protobuf/proto"
 	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
 	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
-	reflect "reflect"
-	sync "sync"
 )

 const (
diff -u examples/helloworld/helloworld/helloworld_grpc.pb.go.orig examples/helloworld/helloworld/helloworld_grpc.pb.go
--- examples/helloworld/helloworld/helloworld_grpc.pb.go.orig	2022-04-18 13:07:38.361660144 -0600
+++ examples/helloworld/helloworld/helloworld_grpc.pb.go	2022-04-18 13:07:38.361660144 -0600
@@ -8,6 +8,7 @@

 import (
 	context "context"
+
 	grpc "google.golang.org/grpc"
 	codes "google.golang.org/grpc/codes"
 	status "google.golang.org/grpc/status"
```

**Comment by menghanl** [comment]
`.pb.go` files are generated by the proto codegen. They may have code not compatible with goimports.
The suggestion is to not run goimports on all generated code.

And I believe many tools look for this magic line (containing `DO NOT EDIT`) and ignore generated code
https://github.com/grpc/grpc-go/blob/7567a5d96538a01715827a3eba57e70d8eedec37/examples/helloworld/helloworld/helloworld.pb.go#L15

Closing this issue now. Please reply if you further questions.
