### ISSUE TITLE
Server nil returns cause problems

### ISSUE THREAD

**Issue by ashishgandhi** [grpc/grpc-go#532]
In Go it is pretty idiomatic to return `nil, err` from a func when we encounter an error when the return values are a pointer and an error. The servers fail to marshal this `nil` while sending back a response to the client; and fatal logs. I think it might be better to do `new(T)` for the user before marshaling.

**Comment by iamqizhao** [comment]
I have no idea what func you are talking about. Can you elaborate?

**Comment by ashishgandhi** [comment]
Apologies, that was very vague of me. Here's more details.

**ProtoBuf**
```
syntax = "proto3";

package test;

service Nop {
  rpc Do(Empty) returns (Empty) {}
}

message Empty {}
```

**Server**
```
package main

import (
	"flag"
	"log"
	"net"
	"test"

	"golang.org/x/net/context"
	"google.golang.org/grpc"
)

var addr = flag.String("addr", ":1337", "listen addr")

func main() {
	flag.Parse()
	s := grpc.NewServer()
	test.RegisterNopServer(s, &server{})

	l, err := net.Listen("tcp", *addr)
	if err != nil {
		log.Fatalf("Cannot listen on %s: %v", *addr, err)
	}
	log.Fatalf("Server stopped: %v", s.Serve(l))
}

type server struct{}

// XXX: If you do this the server crashes. Instead, if you do a
//    return new(test.Empty), nil
// then life is okay. The error being nil or not does not make
// a difference.
func (*server) Do(context.Context, *test.Empty) (*test.Empty, error) { return nil, nil }
```

Any client is fine.

**Comment by xiang90** [comment]
@ashishgandhi It works fine I believe. You need to return the error correctly, not nil response + nil error.

**Comment by iamqizhao** [comment]
what prevents you from doing:

func (*server) Do(context.Context, *test.Empty) (*test.Empty, error) {
   return new(test.Empty), nil
 }
?

**Comment by ashishgandhi** [comment]
Well, nothing prevents me from doing that. But it'd be nice to not crash the server because of this? Like the standard library `http` standard does not crash even if you panic.

**Comment by iamqizhao** [comment]
I would think crash is right thing to do because this is a fatal error due to the local operations.

**Comment by theraphim** [comment]
I've just wasted a few hours on this, because in my case crash was happening without any diagnostic info or anything (just exit 1, I suppose).

**Comment by songshine** [comment]
I got this error:
```
grpc: Server failed to encode response proto: Marshal called with nil
```
Refer to https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L265,  the nil message case has been considered. So the `msg` is not a nil `interface{}` here but the real object of `msg` is nil.  Shouldn't this be fixed?

**Comment by menghanl** [comment]
> So the msg is not a nil interface{} here but the real object of msg is nil.

@songshine Can you give an example for this? Or a reproduction of the error?

**Comment by songshine** [comment]
@menghanl please think about the example from @ashishgandhi 
```
func (*server) Do(context.Context, *test.Empty) (*test.Empty, error) { return nil, nil }
```
so when the code run into the line https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L265,
```
if msg != nil {
...
}
```
 the `msg` is (*test.Empty)(nil), but `msg != nil` will return true. This is an expected behavior?

**Comment by menghanl** [comment]
I think the fix should be:
1. remove the check for `if msg != nil` in `rpc_util.go`
2. remove the [Fatalf](https://github.com/grpc/grpc-go/blob/master/server.go#L582) in `server.go` and return the error

So that the behavior will be, if the error returned by service handler is `nil`, the response will be passed to `Codec` to do Marshal, even if the response is `nil`.

In the case of using protobuf and `return nil, nil`, the marshal will still fail with `Marshal called with nil`, and the user will be notified of the error, but not a `Fatalf`.
