### ISSUE TITLE
xds client use

### ISSUE THREAD

**Issue by liuqi-sun** [grpc/grpc-go#5325]
I want to implement XDS client via GRPC-go, any examples? I see related functionality in the internal directory, but the internal package is not available. What should I do? Please help me. Also, is there any documentation of XDS architecture implementation principles, such as Balancer, Watcher's principles?

**Comment by menghanl** [comment]
> I want to implement XDS client via GRPC-go

I'm not sure what you meant by this.
Are you trying to use gRPC with xDS (as asked by your other issue #5327),
or try to re-implement the xDS features that's already in the internal directory?

If it's latter, the xds designs can be found at https://github.com/grpc/proposal

**Comment by liuqi-sun** [comment]
I mean I want to use the XDS feature in GRPC, not implement it.But Internal packages cannot be imported. How do I use these features, for example, if I want to process data from an XDS server

**Comment by menghanl** [comment]
The xdsclient is intended to be used by gRPC only, and we don't want to export it for (at least for now: discussed in https://github.com/grpc/grpc-go/issues/5100).

What data are you trying to process from the xDS server? And how to process them?

**Comment by liuqi-sun** [comment]
> The xdsclient is intended to be used by gRPC only, and we don't want to export it for (at least for now: discussed in #5100).
> 
> What data are you trying to process from the xDS server? And how to process them?

Process LDS, CDS, EDS, RDS, etc. data and convert them to NGINX configuration

**Comment by menghanl** [comment]
Closing. This is a dup of https://github.com/grpc/grpc-go/issues/5100, and the discussion is covered in #5327
