### ISSUE TITLE
"server streaming" client call not return error

### ISSUE THREAD

**Issue by Boklazhenko** [grpc/grpc-go#5326]
Hi, I have such service interface
`service MiddleTigerConnector {
  rpc AddOrder (NewOrder) returns (stream CoreMessages);
}`

when I have such a response from the server

<img width="1771" alt="Снимок экрана 2022-04-29 в 11 27 56" src="https://user-images.githubusercontent.com/19626029/165894808-e8e1e0c2-8a59-4008-89e1-117db1f4d84a.png">

in code - call NOT return error
`stream, err := NewConnectorClient(grpcConnection).AddOrder(ctx, someOrder)`

moreover, I have not found a way to get the error or headers in this place

the error ( 14, no healthy upstream ) is returned only when we call
`_, err :=stream.Recv()`

which is very late and the application thinks that the initial order has successfully reached the server
are there any ways to detect this? 

I will add that a "unary" call in exactly the same situation returns an error

Thanx

**Comment by menghanl** [comment]
This is working as intended. Streaming creation doesn't wait for the server responses (especially with server streaming RPCs, where it's not clear when the server will ever send any response).

And the correct way to get RPC status errors from a stream is to call `Recv()`.
