### ISSUE TITLE
xds client run error

### ISSUE THREAD

**Issue by liuqi-sun** [grpc/grpc-go#5327]
Hi,grpc-go/examples/features/xds/client fails to communicate with the ISTIOD.Error is as follows:
case 1,
![image](https://user-images.githubusercontent.com/48784730/165903224-f7fe65d2-52ef-4a3e-b1da-a95dd0de0ed4.png)

![image](https://user-images.githubusercontent.com/48784730/165903138-16b72728-b289-4349-b2e5-265cea6594a9.png)

case 2,
![image](https://user-images.githubusercontent.com/48784730/165903284-f465c514-cde4-4998-948c-d7acfab97bb0.png)
![image](https://user-images.githubusercontent.com/48784730/165903378-7497b6e1-35ef-40cf-954a-79977b9c9ac7.png)

istiod:
version v1.13.3
![image](https://user-images.githubusercontent.com/48784730/165903495-3c8d6d13-4c3e-4f6a-8f38-2b0d10f9afa7.png)

**Comment by menghanl** [comment]
It's not clear to me how you set up istio, but your dialing target, `localhost:6666`, is likely to be incorrect.

See https://istio.io/latest/blog/2021/proxyless-grpc/#example for an example with istio.

**Comment by liuqi-sun** [comment]
Istid uses the default configuration, which I have not changed. https://github.com/istio/istio/blob/1.13.3/pilot/tools/debug/pilot_cli.go can successfully access localhost: 6666, and can obtain the XDS resources successfully. So I think localhost:6666 is true.

**Comment by menghanl** [comment]
The client is failing because no LDS resource found for your target. So there must be some inconsistency between the client and server.
Maybe try turning on the logs in the client: https://github.com/grpc/grpc-go#how-to-turn-on-logging
And also check the xds server logs (from istio).

**Comment by liuqi-sun** [comment]
> It's not clear to me how you set up istio, but your dialing target, `localhost:6666`, is likely to be incorrect.
> 
> See https://istio.io/latest/blog/2021/proxyless-grpc/#example for an example with istio.


dialing target  is GRPC Service? Not istiod? So localhost: 6666 is incorrect?
My current requirement is to use XDS client to connect isTIOD and obtain XDS resources. Does GRPC library not support this scenario? Must A GRPC service be created to use the GRPC XDS feature?
Localhost: 6666 is the IP and port of IStiod  in my example.

**Comment by liuqi-sun** [comment]
> The client is failing because no LDS resource found for your target. So there must be some inconsistency between the client and server. Maybe try turning on the logs in the client: https://github.com/grpc/grpc-go#how-to-turn-on-logging And also check the xds server logs (from istio).

https://github.com/istio/istio/blob/1.13.3/pilot/tools/debug/pilot_cli.go can successfully access localhost: 6666,The test results are as follows  :
![image](https://user-images.githubusercontent.com/48784730/166857148-d5185f6a-9aed-4a70-b8aa-e5bb3b2d5fdd.png)
![image](https://user-images.githubusercontent.com/48784730/166857211-4f581131-1331-4a35-8202-0cc01c9e7547.png)


The GRPC client test fails as follows:
![image](https://user-images.githubusercontent.com/48784730/166857379-13244191-02bc-4369-8f80-dfcefd409f26.png)
![image](https://user-images.githubusercontent.com/48784730/166857391-6b089477-acb2-43c2-b31e-abf5d24d1e37.png)
![image](https://user-images.githubusercontent.com/48784730/166857587-bd424614-51c0-4760-b0a4-2e23963df0e0.png)


I do not understand that istiod project pilot_cli.go and GRPC project demo stream send() and receive() implementation is the same, why GRPC project demo accept failed? Send () and receive() are implemented in ads.pb.go.

**Comment by menghanl** [comment]
When you use the `xds` scheme (when dialing `xds:///<target>`), the gRPC client will create another gRPC client to talk to istio, to fetch the resources (addresses of the backends etc).

What you want is a gRPC client directly to istio. So you shouldn't use the `xds` scheme. Just make a dial to `localhost:6666`, you should be able to make ADS streams.

Then there's the problem you mentioned in #5325. The xdsclient is internal only, so you will need to make your own ADS calls, and build the requests.

**Comment by liuqi-sun** [comment]
> When you use the `xds` scheme (when dialing `xds:///<target>`), the gRPC client will create another gRPC client to talk to istio, to fetch the resources (addresses of the backends etc).
> 

Now I can understand that there are two clients, one connecting to the GRPC service in this example and one connecting to istiod, but the one connecting to IStiod uses localhost:6666. You can see the log, so far it is stream.recv () that always fails, I don't know why?

The server(grpc-go\examples\features\xds\server\main.go) in this example is as follows:
![image](https://user-images.githubusercontent.com/48784730/167145963-6c0327e6-dd75-4a0c-a56b-2741506f0a30.png)
![image](https://user-images.githubusercontent.com/48784730/167146016-de6aef3e-017b-496a-bbba-dcd48308d2e8.png)

The client(grpc-go\examples\features\xds\client\main.go) in this example is as follows:
![image](https://user-images.githubusercontent.com/48784730/167146233-99bfe68a-aea4-4be8-9c1c-7fa8215c569b.png)
![image](https://user-images.githubusercontent.com/48784730/167146315-fed38d31-2f2b-475b-a87d-29dfcef14e85.png)
ADS stream is closed with error: xds: stream.Recv() failed: rpc error: code = Unknown desc = missing parts in the service node "THIS_IS_THE_SNAPSHOT_ID_THAT_MATCHES_TO_XDS_CONTROLLER"

**Comment by liuqi-sun** [comment]
> What you want is a gRPC client directly to istio. So you shouldn't use the `xds` scheme. Just make a dial to `localhost:6666`, you should be able to make ADS streams.
> 
> Then there's the problem you mentioned in #5325. The xdsclient is internal only, so you will need to make your own ADS calls, and build the requests.

How to create a client directly connected to IStio, the function of the client is under the internal package, do not know how to use, can you give an example?

How do I make my own ADS calls?

**Comment by menghanl** [comment]
> missing parts in the service node "THIS_IS_THE_SNAPSHOT_ID_THAT_MATCHES_TO_XDS_CONTROLLER"

The node id (you specified in the bootstrap file) is invalid

> the function of the client is under the internal package, do not know how to use

The short answer is you cannot. As said https://github.com/grpc/grpc-go/issues/5100, the xdsclient is for gRPC internal use only.
You can make a copy if you really want. But there's no API stability guaranteed.

Or, to make you own, ADS is just another RPC. You can dial to `localhost:6666`, and start the RPC as shown here: https://github.com/grpc/grpc-go/blob/ee67b3d8e9521dd9f45b25ba1b09095e10b0db05/xds/internal/xdsclient/controller/version/v3/client.go#L77

**Comment by liuqi-sun** [comment]
Thank you very much for your answer
> 
> The node id (you specified in the bootstrap file) is invalid
> 

It is true that the node ID is invalid. I found that the node ID has specifications by checking istiod source code. But XDS doesn't have a specification, which makes it easy to make mistakes like mine and waste time.
Istiod specifications are as follows:
![1652093367(1)](https://user-images.githubusercontent.com/48784730/167395360-0eadcbcd-b408-4a8f-83e6-a818b20d1332.png)


In addition, parsing errors occurred after the response was received, Is it GRPC XDS that does not support responses containing this field?
![image](https://user-images.githubusercontent.com/48784730/167396187-791e06af-9e58-422a-90aa-18fa706cbfea.png)
![image](https://user-images.githubusercontent.com/48784730/167396347-48d46db1-ee01-47d8-a139-622f75585e56.png)


I found that GRPC ADS did not request the XDS server in the order of CDS, EDS, LDS and RDS. In the server and client, programs always watch Listener resources and always call LDS first

**Comment by menghanl** [comment]
The parsing error is because the listener resources are parsed as server side listener, but seems you are expecting client side. The difference is if field `APIListener` is set, and that's controlled by istio.

The order is always LDS, RDS, CDS, EDS. See https://github.com/grpc/proposal/blob/master/A27-xds-global-load-balancing.md
