### ISSUE TITLE
 go 1.6rc2: cgo error when executing non-cgo tests

### ISSUE THREAD

**Issue by aaronbee** [grpc/grpc-go#533]
What version of Go are you using (go version)?

go1.6rc2

What operating system and processor architecture are you using?

Mac OS 10.11.3 El Capitan

What did you do?

`go test -race -timeout 5s PACKAGE`

What did you expect to see?

`ok  	PACKAGE	1.303s`

What did you see instead?

```
# runtime/cgo
clang: error: couldn't open cache file '/var/folders/dh/8tf0gx091zs_02mw_s0c956w0000gp/T/xcrun_db' (errno=File exists)
ok  	PACKAGE	1.303s
```

As you can see above I got this seemingly harmless error related to cgo and clang, but the code I am executing has no cgo component at all. I have run these exact same tests before and after this instance and have not seen the error message again.

**Comment by iamqizhao** [comment]
This is not grpc issue. please file a bug to golang.
