### ISSUE TITLE
Flaky test: Test/FailFast

### ISSUE THREAD

**Issue by zasweq** [grpc/grpc-go#5341]
https://github.com/grpc/grpc-go/runs/6359093965?check_suite_focus=true

**Comment by menghanl** [comment]
https://github.com/grpc/grpc-go/runs/6530347908?check_suite_focus=true

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/runs/7079326088?check_suite_focus=true

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/runs/7310741721?check_suite_focus=true

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/runs/7311081755?check_suite_focus=true

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/runs/7326572694?check_suite_focus=true
