### ISSUE TITLE
Possible typo resulting in ErrConnClosing beeing logged?

### ISSUE THREAD

**Issue by hadrienk** [grpc/grpc-go#5346]
I am seeing a log of `transport: loopyWriter.run returning. connection error:  desc = "transport is closing"` in the logs of a grpc server.

Looking at the code, I sumbled upon this
https://github.com/grpc/grpc-go/blob/e8d06c51a523ba75f052cfaa56a1b8e0583ac589/internal/transport/controlbuf.go#L521-L531

Based on the comment (**Don't log** ErrConnClosing as error) , I wonder if the test should be `err != ErrConnClosing` instead?

**Comment by zasweq** [comment]
Yeah, I think you are correct.
