### ISSUE TITLE
Issue with stream send over 4kb size messages

### ISSUE THREAD

**Issue by l0k18** [grpc/grpc-go#5350]
Update:

It is not just large messages it seems to also be overall volume of concurrent requests, as increasing the number of messages in the stream also causes the stall to occur. Further experiments with increasing concurrent requests and larger bursts of messages both yield the stall problem. 

In the following test:

https://github.com/quanterall/kitchensink/blob/main/pkg/grpc/concurrency_test.go

If you change the value on line 169 to anything over 4, the message sizes are over 4kb in size and the stream.Send function blocks indefinitely.

Enable `-v` on the test to see the logging output.

If you exactly follow the prerequisites installation, specifically one of these:

    go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

I think it's the gRPC one, the second one, is now a newer version. If you use the exact version shown above, it bugs with that value set over 2, with the latest version, with it set over 4, which as you can read by the logging in the test, was 2kb message size before and now 4kb message size.

NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?

Current version in mainline Ubuntu 20 protoc, see text above for grpc generator

### What version of Go are you using (`go version`)?

go v1.18.1

### What operating system (Linux, Windows, …) and version?

Pop OS 20 (same as ubuntu 20.04)

**Comment by zasweq** [comment]
I see what you initially meant here:
https://github.com/quanterall/kitchensink/blob/c00e41f0922a25d902b0c4ce2b6a28a413ab356d/pkg/grpc/concurrency_test.go#L165. However, there have been multiple commits since you sent out this issue. Are you still seeing this problem?

**Comment by zasweq** [comment]
Also more than likely you are blocked on flow control because one side isn't receiving from another.
