### ISSUE TITLE
grpc: add optional interface to return channel authority

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5360]
This is one of the items mentioned in https://github.com/grpc/grpc-go/issues/4717 which did not get done. The below description has been copied over verbatim from #4717. Java and C already support this.

- [ ] Determining `:authority` from the target URI must be the responsibility of the name resolver. See: https://github.com/grpc/grpc-go/issues/4516
  - [ ] Add an optional interface, to be implemented by name resolvers or their builders, that contains a single method to return the channel’s authority.
    - [ ] This method must not perform any I/O, be non-blocking and the return value must not change over time.
    - [ ] This value will be used to populate the `:authority` pseudo-header, and `serverName` for TLS handshake by default.
    - [ ] gRPC will provide an implementation which conforms to RFC 3986 and returns the path portion of the target, after stripping query parameters. This will be used if the scheme’s name resolver does not provide a custom one.
      - [x] [grpcutil.ParseTarget](https://github.com/grpc/grpc-go/blob/85b9a1a0fa3fc7ce6677ac19267b380ef0cf59a7/internal/grpcutil/target.go#L47) will be enhanced for this purpose.
    - [x] This parsed target will be passed to load balancers in their BuildOptions, with the correct `authority` set.

**Comment by Aditya-Sood** [comment]
hi @dfawley @ginayeh, can I pick this up?

**Comment by dfawley** [comment]
Sure, thanks!  Let's name the interface:

```go
package resolver

// AuthorityOverrider is implemented by Builders that wish to override the
// default authority for the ClientConn.  By default, the authority used is
// target.Endpoint().
type AuthorityOverrider interface {
	// OverrideAuthority returns the authority to use for a ClientConn with the
	// given target.  It must not perform I/O or other blocking operaitons.
	OverrideAuthority(target Target) string
}
```

And I think the only real motivation for this feature is to move this special case into the function to be implemented by the unix resolver's builder:

https://github.com/grpc/grpc-go/blob/e14d5831b59b0f46853d076640ae85f964164b37/clientconn.go#L1990-L1993

Around here:

https://github.com/grpc/grpc-go/blob/e14d5831b59b0f46853d076640ae85f964164b37/internal/resolver/unix/unix.go#L60

Which would also be a pretty good test for this functionality in practice.

One thing we need to decide is: do we do the `escapeAuthority` on the result of this function, to ensure it complies with RFC 3986?  I'm of the opinion we should, but I'm not sure what Java and C++ do.  They probably just assume it's the responsibility of the name resolver.

**Comment by Aditya-Sood** [comment]
WIP, adding comment to prevent issue being closed

**Comment by easwars** [comment]
> One thing we need to decide is: do we do the `escapeAuthority` on the result of this function, to ensure it complies with RFC 3986?

Did we make a decision on this one? Thanks.
@dfawley

**Comment by Aditya-Sood** [comment]
hi @easwars, the PR doesn't include percent-encoding and expects it from the name resolver currently
(point 3 in https://github.com/grpc/grpc-go/pull/6752#issuecomment-1783213312)
