### ISSUE TITLE
how to close connection without affecting other goroutines to use?

### ISSUE THREAD

**Issue by xuyang1996** [grpc/grpc-go#5365]
# Background
since `grpc.ClientConn` can be safely used in mutiple goroutines.
I am writing a map for grpc connections to different hosts (key=>address, value=>connection) so that we can reuse the connection for the same address.

And if a address was not used for a while, I wanted to close it manually.
But here is the question:

how to to make sure that grpc.ClientConn isn't used in other goroutines so that i can close it safely...
Otherwise if i close the connection that other goroutines is using, there may be some error like 
`rpc error: code = Canceled desc = grpc: the client connection is closing`
`rpc error: code = Unavailable desc = error reading from server: read tcp 127.0.0.1:55280->127.0.0.1:6565: use of closed network connection`

**Comment by xuyang1996** [comment]
I use `conn.GetState()` but always return READY whether i use invoke or not...
And only return SHUTDOWN after i use `conn.Close()`...

**Comment by zasweq** [comment]
It is up to you, the user of grpc, to know how many goroutines are using a grpc.ClientConn. The grpc.ClientConn has no knowledge of how many goroutines are using it.
