### ISSUE TITLE
gracefulswitch: do not access the subConns map without the lock

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5383]
In `gsb.ExitIdle()`, we are accessing the `subConns` map without holding `gsb.mu`.
https://github.com/grpc/grpc-go/blob/master/internal/balancer/gracefulswitch/gracefulswitch.go#L196-L198

Currently, since all the LB policies that we have written implement the `ExitIdler` interface, this code path is never executed. But it can be executed for a custom LB policy implemented and used by our users.

The `subConns` map is accessed when the child policy calls `NewSubConn`. Other accesses to the map when handling calls from grpc are not an issue since they would be synchronized anyways.

**Comment by easwars** [comment]
@zasweq : Thoughts?

**Comment by zasweq** [comment]
Yeah, makes sense. I'll go ahead and do it. My only concern is that sc.Connect() call can't cause an inline callback causing deadlock right? That is only calls on the child balancer.
