### ISSUE TITLE
transport: perform blocking read of server preface while creating a new client transport

### ISSUE THREAD

**Issue by sfc-gh-jchacon** [grpc/grpc-go#5385]
### What version of gRPC are you using?
google.golang.org/grpc v1.46.2

### What version of Go are you using (`go version`)?
1.18.2

### What operating system (Linux, Windows, …) and version?
Linux and Mac OS/X

### What did you do?
See:

https://github.com/Snowflake-Labs/sansshell/tree/jchacon-bad-tls-error/echo

for the example code. Run demo.sh in there to see variations on the testing and being able to replicate the data below.

### What did you expect to see?
When the client sends a cert that the server doesn't have in it's CAPool I expect to get a CA error such as:

x509: certificate signed by unknown authority

i.e. the same thing the client will emit if the server serves up a certificate it can't validate.

### What did you see instead?
If I connect with a client sending a cert that cannot be validated I instead get:

rpc error: code = Unavailable desc = connection closed before server preface received

The output from Go GRPC debugging does show the server was unhappy with this cert:

2022/05/26 11:45:53 WARNING: [core] grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "ServerHandshake(\"127.0.0.1:56587\") failed: tls: client didn't provide a certificate"

The server should return a real error here and not just close the connection.

**Comment by easwars** [comment]
Thanks @sfc-gh-jchacon for the detailed problem report.

I was experimenting with one of the [examples](https://github.com/grpc/grpc-go/tree/master/examples/features/encryption/mTLS) from our code base and figured that
our TLS credentials implementation, as part of the `ClientHandshake()` method, calls the underlying `Handshake()` method on the `tls.Conn` here:
https://github.com/grpc/grpc-go/blob/ca5cc0bcad6e0270c565f8b08907212fc1c4a3e5/credentials/tls.go#L87

And it turns out that the call to `tlsConn.Handshake()` returns a `nil` error.

So, I switched to experimenting with a simple Go server and client (without the use of grpc).

<details>
    <summary>Here is the server code</summary>

```golang
var port = flag.Int("port", 50051, "the port to serve on")

func main() {
	flag.Parse()
	log.Printf("Server starting on port %d...\n", *port)

	cert, err := tls.LoadX509KeyPair(data.Path("x509/server_cert.pem"), data.Path("x509/server_key.pem"))
	if err != nil {
		log.Fatalf("Failed to load key pair: %s", err)
	}

	ca := x509.NewCertPool()
	caFilePath := data.Path("x509/ca_cert.pem")
	caBytes, err := ioutil.ReadFile(caFilePath)
	if err != nil {
		log.Fatalf("Failed to read ca cert %q: %v", caFilePath, err)
	}
	if ok := ca.AppendCertsFromPEM(caBytes); !ok {
		log.Fatalf("Failed to parse %q", caFilePath)
	}

	tlsConfig := &tls.Config{
		ClientAuth:   tls.RequireAndVerifyClientCert,
		Certificates: []tls.Certificate{cert},
		ClientCAs:    ca,
	}

	lis, err := tls.Listen("tcp", fmt.Sprintf("localhost:%d", *port), tlsConfig)
	if err != nil {
		log.Fatalf("Failed to listen: %v", err)
	}

	for {
		conn, err := lis.Accept()
		if err != nil {
			log.Println(err)
			continue
		}
		go handleConnection(conn)
	}
}

func handleConnection(c net.Conn) {
	log.Printf("Client %v connected.", c.RemoteAddr())
	defer func() {
		log.Printf("Connection from %v closed.", c.RemoteAddr())
	}()
	defer c.Close()

	buffer := make([]byte, 256)
	for {
		n, err := c.Read(buffer)
		if err == io.EOF {
			return
		}
		if err != nil {
			log.Printf("Failed to read data from client: %v", err)
			return
		}
		if _, err = c.Write(buffer[0:n]); err != nil {
			log.Printf("Failed to write data to client: %v", err)
			return
		}
	}
}
```
</details>

<details>
    <summary>Here is the client code</summary>

```golang
var addr = flag.String("addr", "localhost:50051", "the address to connect to")

func main() {
	flag.Parse()

	cert, err := tls.LoadX509KeyPair(data.Path("x509/client_cert.pem"), data.Path("x509/client_key.pem"))
	if err != nil {
		log.Fatalf("Failed to load client cert: %v", err)
	}

	ca := x509.NewCertPool()
	caFilePath := data.Path("x509/ca_cert.pem")
	caBytes, err := ioutil.ReadFile(caFilePath)
	if err != nil {
		log.Fatalf("failed to read ca cert %q: %v", caFilePath, err)
	}
	if ok := ca.AppendCertsFromPEM(caBytes); !ok {
		log.Fatalf("Failed to parse %q", caFilePath)
	}

	tlsConfig := &tls.Config{
		ServerName:   "x.test.example.com",
		Certificates: []tls.Certificate{cert},
		RootCAs:      ca,
	}

	conn, err := tls.Dial("tcp", *addr, tlsConfig)
	if err != nil {
		log.Fatalf("Failed to dial server: %v", err)
	}
	defer conn.Close()

	log.Printf("Connection established between %s and localhost.\n", *addr)
	log.Printf("Remote Address : %s \n", conn.RemoteAddr().String())
	log.Printf("Local Address : %s \n", conn.LocalAddr().String())

	sent := []byte("client-echo-data")
	if _, err := conn.Write(sent); err != nil {
		log.Fatalf("Failed to write data to server: %v", err)
	}

	recv := make([]byte, 256)
	n, err := conn.Read(recv)
	if err != nil {
		log.Fatalf("Failed to read data from server: %v", err)
	}

	if string(recv[:n]) != string(sent) {
		log.Fatalf("Received data from server %q, want %q", string(recv), string(sent))
	}
}
```
</details>

Some interesting observations here:
- Server fails with a useful error message: `Failed to read data from client: tls: client didn't provide a certificate`
- Client also fails with a useful error message: `Failed to read data from server: remote error: tls: bad certificate`, but this is after a call to `Write()` succeeded.

Then, I tried adding explicit calls to `Handshake()` on the client and the server:
```golang
if err := conn.Handshake(); err != nil {
  log.Fatalf("TLS handshake failure: %v", err)
}
```
- The client side handshake did not fail
- Server side failed with `TLS handshake failure: tls: client didn't provide a certificate`

@dfawley : Any thoughts on how to go about on this issue? Should we talk to the Go team?

**Comment by easwars** [comment]
Maybe this is expected behavior: https://github.com/golang/go/issues/32202#issuecomment-513781647

**Comment by dfawley** [comment]
> The error must either be checked on the first Read

Does this mean we need to propagate the error returned when we're trying to read the server's preface, then?

**Comment by dfawley** [comment]
Note that this would necessitate moving the reading of the preface from `reader` and to `newHTTP2Client`.  It would be done in blocking fashion, which we've discussed doing for awhile now, and would greatly simplify the logic in `clientconn.go` that deals with the "preface not received" errors asynchronously.

**Comment by easwars** [comment]
Do we have an open issue for that? I need to come up to speed on that.
