### ISSUE TITLE
how to use my own plugin?

### ISSUE THREAD

**Issue by le011** [grpc/grpc-go#5386]
hi everyone. As stated in the title, i want to use plugin before call grpc or after,but i didn't find document.

**Comment by zasweq** [comment]
What are you referring specifically to when you say "plugin"? grpc-go supports many types of plugins, so if you give us more specifics we can point you in the right direction.

**Comment by le011** [comment]
go2sky this https://github.com/SkyAPM/go2sky

**Comment by le011** [comment]
hi everyone.

**Comment by dfawley** [comment]
I don't think we can help with this.  I think you should try the people that maintain go2sky instead, perhaps.
