### ISSUE TITLE
How to create a gateway that supports grpc-streaming calls

### ISSUE THREAD

**Issue by sodaRyCN** [grpc/grpc-go#5388]
I want to build a gateway that code by go and supports grpc protocol, both client and server use grpc .
This gateway needs to meet the following points:
1. support no TLS, that is, the client uses plaintext
2. the gateway does not need to know the pb data definition of the client and the server, because the general gateway does not need to modify the request.body and response.body, and more styles are used for the header
3. support stream

so, i use x/net/http2 package to try, the main code is as follows:

      h2 := &http2.Server{}
      handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
                client := &http.Client{
                        Timeout: 0,
                        Transport: &http2.Transport{
                                AllowHTTP: true,
                                DialTLS: func(network, addr string, cfg *tls.Config) (net.Conn, error) {
                                        return net.Dial(network, addr)
                                },
                                TLSClientConfig: &tls.Config{
                                        InsecureSkipVerify: true,
                                },
                                DisableCompression: false,
                        },
                        CheckRedirect: func(req *http.Request, via []*http.Request) error {
                                return http.ErrUseLastResponse
                        },
                }
                newReq, err := http.NewRequestWithContext(r.Context(), r.Method, "endpoint from serviceregistry" + r.URL.Path, r.Body)
                if err != nil {
                        fmt.Printf("new request err is %v", err)
                }
                newReq.Header = r.Header
                newReq.Host = r.Host
                result, err := client.Do(newReq)
                if err != nil {
                        fmt.Printf("request provider err is %v", err)
                }
                defer func() {
                        r.Body.Close()
                        if body, ok := result.Body.(io.ReadCloser); ok {
                                // NOTE: Need to be read to completion and closed.
                                // Reference: https://golang.org/pkg/net/http/#Response
                                err := body.Close()
                                if err != nil {
                                        fmt.Printf("close result body fail %v", err)
                                }
                        }
                }()
                for k, v := range result.Header {
                        for _, v2 := range v {
                                w.Header().Add(k, v2)
                        }
                }
                w.Header().Set("Trailer", "grpc-status")
                w.Header().Set("grpc-status", "0")
                copyToClient := func(src io.Reader) (succeed bool) {
                        _, err := io.Copy(w, src)
                        if err != nil {
                                return false
                        }
                        return true
                }
                copyToClient(result.Body)
        })

        server := &http.Server{
                Addr: xxxx,
                Handler: h2c.NewHandler(handler, h2),
        }
        server.ListenAndServe()

in test, I found that it can support unary calls, but does not support streaming.
The preliminary conclusion is that when the server first calls `onNext()`, the gateway get a response from server and returns it to the client as a response `result, err := client.Do(newReq)`, if I debug here and stay for a certain time, then the client receives the complete message, otherwise it is incomplete. maybe I can wait here until I get a certain character of grpc protocol?

at the same time, when debugging`result, err := client.Do(newReq)`, I found that the response here does not have a trailer-related value

Is there a more recommended way to implement a gateway that meets the requirements.

**Comment by dfawley** [comment]
It sounds like you want a generic HTTP/2 proxy.  I can't really help with your implementation based on the golang http2 package, but it should be possible to do that way as long as you properly support streams (multiple requests/responses).

It should also be possible to implement this with a grpc server, though I haven't actually tried it.  You should be able to use the [`UnknownServiceHandler`](https://pkg.go.dev/google.golang.org/grpc#UnknownServiceHandler) and a `ClientConn` dialed to the backing service.  Both the server and client in the proxy would have no registered services, and the [codec](https://pkg.go.dev/google.golang.org/grpc/encoding#Codec) used would deal with raw bytes instead of proto messages.

Let us know if you have any further questions.
