### ISSUE TITLE
No support for Unix socket types?

### ISSUE THREAD

**Issue by AgentCoop** [grpc/grpc-go#5389]
I am a bit confused, but it looks like there is no support for socket types, the network type 'unix' is hard-coded here:
[https://github.com/grpc/grpc-go/blob/e41f868588c99493b35169e258a11b2ce128e139/internal/resolver/unix/unix.go#L55](https://github.com/grpc/grpc-go/blob/e41f868588c99493b35169e258a11b2ce128e139/internal/resolver/unix/unix.go#L55)
yet we can create a server listening on _unixpacket_ and _unixgram_ sockets. Any connection to such a server will be refused.

**Comment by dfawley** [comment]
Correct, these are not supported.  Can you explain more about your use case?  It may be possible to make them work using a custom dialer (https://pkg.go.dev/google.golang.org/grpc#WithContextDialer).

**Comment by dfawley** [comment]
What you're describing would be something that could be implemented using this proposal for custom transports: https://github.com/grpc/proposal/pull/103

Unfortunately, it became deprioritized, and hasn't been worked on in some time.

**Comment by dfawley** [comment]
Unix sockets are supported.  `unix:<path-to-socket>` will get that to work.  `unixpacket` and `unixgram` socket types are not supported, however.
