### ISSUE TITLE
Feature request: ability to use generateFile from protoc-gen-go-grpc in external package

### ISSUE THREAD

**Issue by mkarpusiewicz** [grpc/grpc-go#5394]
### Use case(s) - what problem will this feature solve?

I am writing a code generator to generate grpc services implementation. It first generates a .proto file from custom yaml config and then uses protoc-gen-go and protoc-gen-go-grpc plugins to generate code using that proto file as input. As a final step it uses custom logic to generate a implementation for that grpc server. I would like to be able to package it as a single binary and avoid having dependencies to protoc binary.  

I am able to call protoc-gen-go by creating a pluginpb.CodeGeneratorRequest and protogen.Plugin and calling https://github.com/golang/protobuf/blob/5d5e8c018a13017f9d5b8bf4fad64aaa42a87308/internal/gengogrpc/grpc.go#L26 by importing `gengo "google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo"`.  (honestly not sure if this intentional or not because the file is in /internal/gengogrpc/grpc.go just the redirect import url google.golang.org allows the import)

It would be awesome if the same could be achieved with protoc-gen-go-grpc but unfortunately generateFile in https://github.com/grpc/grpc-go/blob/70a80552d51f74bd2fb313cff7fea68cde4c2612/cmd/protoc-gen-go-grpc/grpc.go#L108 is not exported and in main package.

I am aware of the issue: https://github.com/grpc/grpc-go/issues/3717 and conversation on the pull request here: https://github.com/grpc/grpc-go/pull/3453 and understand the reasoning behind the decision made back then.

Can this be reconsidered? Especially that similar behavior is possible with protoc-gen-go.

### Proposed Solution

Extract generateFile to a package and make it exported so external code can import it.

### Alternatives Considered

Forking repository and making changes for my tool - has obvious downsides.

Packaging tool in a Docker container with protoc binary and plugins installed and just calling them from shell - previous version of my code generator used this approach and was found a bit cumbersome for some users and had other downsides.

**Comment by easwars** [comment]
The `GenerateFile` function in `protoc-gen-go` is also in an `internal` package. I'm not sure why/how you are able to use it. These plugins are not really meant to be used as a library. And the [rationale](https://github.com/grpc/grpc-go/issues/3717#issuecomment-666669345) mentioned for not exporting these is still valid.

My recommendation would be to fork these into your tool and use them for your needs. These tools are usually stable and don't get frequent changes made to them, so I think it wouldn't be too bad.

**Comment by easwars** [comment]
Thanks for the explanation.

> Packaging tool in a Docker container with protoc binary and plugins installed and just calling them from shell - previous version of my code generator used this approach and was found a bit cumbersome for some users and had other downsides.

Could you please elaborate a little on what you found cumbersome here and what the downsides were?

**Comment by mkarpusiewicz** [comment]
Sure, however note that some points are just specific to this util and it's users. Also I am experimenting so this doesn't mean I feel that this is a better solution in any way. So assuming that users/devs have both go and docker installed there is not that much difference between running `go install` or `docker pull` for the end user. There is IMO a bit more elegance to have a single binary and everything written in go in contrast with a docker container and some shell scripts to run other tools like protoc etc. but this is a subjective. However couple of issues I've had:

- important note is that users of this tool use different environments and machines like windows with wsl, linux, mac (x64 or m1 arm) with different setups, user accounts etc. which proved to be problematic in some cases mentioned below
- with M1 macs you have two options to run the docker image. You can run a x64 image but it goes through Rosetta translation and generally the performance is not great (an order of magnitude slower). You can quite easily package the image for x64 and arm and tools like protoc have binaries but some other things didn't and it was a bit problematic. So that's why the idea was to move fully to go to eliminate those issues.
- another annoyance that I hadn't found a good solution is file permissions. As the tool needs set of input files and generates a set of output files using stdin/stdout is not a solution so basically you have to mount the working dir into docker container. Ideally the docker container would not be run as root with user privileges but then there are problems with accessing some of the files or writing/creating dirs etc. Ignoring the fact that adding another switched to `docker run` to use users uid and gid is another annoyance (or case for creating a wrapper script) then it didn't work for some cases. Most of the solutions found online didn't work fully, like for example `cp -p`  that should preserve mode and ownership didn't work. A hack solution that did work was to do a ``chown `stat --format="%u:%g"` . -R`` on the output but again this just complicates stuff and I feel it may not work for every case. Generally I found operating with uids and gids inside docker trying to preserve users setup on the host problematic.
- there are also things like the tool needs connections to db for some operations, so docker has to be used with host network and have access to private github repositories so you have to replicate ssh conditions inside container from the host. So as it has to be done at runtime not build time of docker you can't easily mount ssh credentials, so you have to either pass them via env or some other way, and do `git config` url rewrite etc. another complication both for complexity of solution and users experience as again, there is another thing to configure and pass to docker run
- also some code bases used vendoring which meant that a huge amount of files had to be mounted to the container (as there was a need to do `go mod tidy` after some changes and some code used reflection etc. generally over complicated stuff but it meant again some performance loss especially on non linux environments where docker is run in a VM so both WSL and Macs suffered here)

That are the main annoyances I can think of now. Most of the problems were resolved one way or another however it increased complexity a lot and it prone to more problems on different environments and made the user experience a bit worse. That's why I was searching for a more elegant way of just having one binary and all inside go source code.
