### ISSUE TITLE
Please add context.Context support for RecvMsg()

### ISSUE THREAD

**Issue by GiedriusS** [grpc/grpc-go#5401]
### Use case(s) - what problem will this feature solve?

We want to write a high-performance loop that receives messages from a stream as fast as possible whilst at the same time protecting ourselves from one operation taking too long i.e. we want to return a partial response to our users if one stream is taking too long.

### Proposed Solution

RecvMsg() needs to accept a `context.Context`.

### Alternatives Considered

The proposed alternative to [spawn a goroutine ](https://github.com/grpc/grpc-go/issues/1229#issuecomment-302755717)for each RecvMsg() seems horrible for performance. Adding `context.Context` support seems straightforward and it isn't such a  huge breaking change for users to simply pass `context.Background()`.

### Additional Context

https://github.com/grpc/grpc-go/issues/445 it's really not a solution to spawn new goroutines for each RecvMsg() if you are receiving hundreds of thousands of messages potentially.

**Comment by GiedriusS** [comment]
Unfortunately but using a separate goroutine isn't a good solution performance-wise. There is a huge reduction in performance when you try to pass tens of thousands of received messages via the channel. In our case doing:

```go
for {
  res, err := stream.RecvMsg()
  ...
}
```

vs. doing that via a channel reduces the query duration by a few seconds (https://github.com/thanos-io/thanos/pull/5296). That's why I have created this issue (: perhaps there is some other solution?

**Comment by dfawley** [comment]
Other ideas which avoid the channel:

Using a per-operation timer:

```go
ctx, cancel := context.WithCancel(ctx)
defer cancel()
stream, err := client.StreamingRPC(ctx)

for {
	t := time.AfterFunc(2*time.Second, cancel)
	res, err := stream.RecvMsg()
	t.Stop()
	// Handle res/err inline as before
}
```

Using a monitoring goroutine to cancel the stream context when progress stops (may not work if stream response processing is slow/unpredictable):

```go
ctx, cancel := context.WithCancel(ctx)
defer cancel()
stream, err := client.StreamingRPC(ctx)

// Monitor messages received and cancel the stream if progress
// isn't made every two seconds.
msgs := int32(0)
go func() {
	lastMsgs := int32(0)
	for ctx.Err() == nil {
		time.Sleep(2*time.Seconds)
		t := atomic.LoadInt32(msgs)
		if lastMsgs == t {
			cancel()
			return
		}
		lastMsgs = t
	}
}()

for {
	res, err := stream.RecvMsg()
	atomic.AddInt32(msgs,1)
	// Handle res/err inline as before
}
```
