### ISSUE TITLE
os thread leak

### ISSUE THREAD

**Issue by simonyangcj** [grpc/grpc-go#5425]
### What version of gRPC are you using?
v1.47

### What version of Go are you using (`go version`)?
go version
go version go1.17.1 linux/amd64

### What operating system (Linux, Windows, …) and version?
ubuntu 20.04 / centos 7

### What did you do?
Use grpc lib dial a socket file which has no service provider over this socket file

### What did you expect to see?
os thread is released after grpc lib return context deadline exceed error

### What did you see instead?
os thread remain and keep growning 

### Following is my test code
when you run it you might see something like

try 1 timepid: 1138020, GOMAXPROCS: 12, NumCPU: 12, threads: 7, goroutines: 4
......
try 20 timepid: 1138020, GOMAXPROCS: 12, NumCPU: 12, threads: 9, goroutines: 2
......
try 132 timepid: 1138020, GOMAXPROCS: 12, NumCPU: 12, threads: 10, goroutines: 2
......
try 200 timepid: 1138020, GOMAXPROCS: 12, NumCPU: 12, threads: 10, goroutines: 2

```
package main

import (
	"context"
	"fmt"
	"google.golang.org/grpc"
	"io/ioutil"
	"net"
	"os"
	"path/filepath"
	"runtime"
	"time"
)


func DialSocketWithTimeout(socketPath string, timeout int) (*grpc.ClientConn, error) {
	options := []grpc.DialOption{
		grpc.WithInsecure(),
		grpc.WithDialer(func(addr string, timeout time.Duration) (net.Conn, error) {
			return net.DialTimeout("unix", addr, timeout)
		}),
		grpc.WithBlock(), // dial sync in order to catch errors early
	}

	if timeout > 0 {
		options = append(options,
			grpc.WithTimeout(time.Duration(500)*time.Millisecond),
		)
	}

	ctx, _ := context.WithTimeout(context.Background(), 500*time.Millisecond)
	return grpc.DialContext(ctx, socketPath, options...)

}

func printInfo() {
	pid := os.Getpid()
	task_path := fmt.Sprintf("/proc/%d/task", pid)
	files, _ := ioutil.ReadDir(task_path)
	fmt.Printf("pid: %d, GOMAXPROCS: %d, NumCPU: %d, threads: %d, goroutines: %d\n",
		pid, runtime.GOMAXPROCS(0), runtime.NumCPU(), len(files), runtime.NumGoroutine())
}


func MkdirAllWithNosec(pathName string) error {
	return os.MkdirAll(pathName, 0755)
}

func CreateSocket(socketPath string) (net.Listener, error) {
	os.RemoveAll(socketPath)

	err := MkdirAllWithNosec(filepath.Dir(socketPath))
	if err != nil {
		fmt.Printf("unable to create directory for unix socket %v due to error: %s", socketPath, err.Error())
		return nil, err
	}

	socket, err := net.Listen("unix", socketPath)

	if err != nil {
		fmt.Printf("failed to create unix socket %v due to error: %s", socketPath, err.Error())
		return nil, err
	}
	return socket, nil
}

func main() {
	maxOut := 200
	waitMaxOut := maxOut/2
	sockPath := "/var/run/test/test.sock"
	_, err := CreateSocket(sockPath)
	if err != nil {
		os.Exit(-1)
	}

	signalChan := make(chan int, 1000)
	resultChan := make(chan int, 1000)

	count := 1
	waitResultCount := 1

	go func() {
		for {
			select {
			case <-signalChan:
				DialSocketWithTimeout(sockPath, 0)
				fmt.Printf("try %d time", count)
				printInfo()
				count += 1
			case <- resultChan:
				fmt.Println(fmt.Sprintf("wait clear up %d", waitResultCount))
				printInfo()
				waitResultCount += 1
			}
/*			if count == maxOut {
				fmt.Println("Max out break it")
				break
			}*/
		}
		//return
	}()

	for i := 0; i < maxOut; i++ {
		signalChan <- 1
	}

	time.Sleep(time.Duration(waitMaxOut) * time.Second)
	fmt.Println("Final print start")
	printInfo()
	for i := 0; i < 10; i++ {
		printInfo()
		time.Sleep(2*time.Second)
	}

	time.Sleep(100000 * time.Second)
}
```

### Workaround 
My guess is goroutine get stuck on some cgo system call cause goroutine scheduler keep create new os thead, so i did some modification to the "google.golang.org/grpc/clientconn.go" change line 989 to following(not sure i was doing the right thing)

```
	go func() {
		runtime.LockOSThread()
		r.resolveNow(o)
		return
	}()
```

now run main.go again you might see os thread will not keep growning any more

**Comment by simonyangcj** [comment]
@[zasweq] thanks a lot for taking time watching this issue, depending on your result, i think it might be the problem of golang on certain kernel version, i`m going to close this issue now, again thanks for dig into it :)

**Comment by zasweq** [comment]
Btw, I ran this on debian as well (gLInux) and I couldn't reproduce. Sorry! Thanks for bringing it up though.
