### ISSUE TITLE
io.grpc.StatusRuntimeException: UNKNOWN: EOF 

### ISSUE THREAD

**Issue by gangxie112** [grpc/grpc-go#5432]
I'm using the grpc-java as grpc client to call golang grpc server. It's bidi stream。 After the client called oncomplete, and the server closed the stream directly. on client side, unknown eof exception is received. is it FAD? I think the grpc-java should handle this EOF after the oncomplete is called？

**Comment by zasweq** [comment]
Hello, can you please provide more information about this error? What versions of grpc-java and grpc-go are you using? Can you provide code to help us reproduce this? What does FAD stand for?

**Comment by ejona86** [comment]
We assumed FAD == functioning as designed
