### ISSUE TITLE
grpc request blocked on sendQuotaPool.get() 

### ISSUE THREAD

**Issue by seeadoog** [grpc/grpc-go#5436]
I encounter a problem using grpc .  When my grpc client is runing . it suddenty timeout and continue . only recovery when I restart the grpc client. I catch the goroutine stack when the problem reproduce .It shows many request is blocked on  sendQuotaPool.get() .  my server and client is running on the same machine ,so the network problem can be excluded
stack:

```
437 @ 0x432f70 0x442acb 0x8d0b22 0x8da901 0x8fb24e 0x8fc031 0x8fb7f6 0x94f85f 0x94f7cc 0x970692 0x96eed1 0x969002 0xd905a2 0xd910bb 0xd92ace 0xd9b6e8 0xd09d54 0xd9c94a 0xd09d54 0xd9d05e 0xd09d54 0xd9c58b 0xd09d54 0xd12888 0xd125ae 0xd11ff4 0x75b564 0x756e05 0x461481
#	0x8d0b21	google.golang.org/grpc/transport.(*quotaPool).get+0x1f1	google.golang.org/grpc/transport/control.go:191
#	0x8da900	google.golang.org/grpc/transport.(*http2Client).Write+0x370 google.golang.org/grpc/transport/http2_client.go:688
#	0x8fb24d	google.golang.org/grpc.sendRequest+0x20d	google.golang.org/grpc/call.go:130
#	0x8fc030	google.golang.org/grpc.invoke+0x800			
```

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
grpc  1.9.1
### What version of Go are you using (`go version`)?
go 1.13  
### What operating system (Linux, Windows, …) and version?
linux centos 7

**Comment by seeadoog** [comment]
when the problem occured. not all connection is abnormal . Some of the request can send to server successfully

**Comment by seeadoog** [comment]
I want to know if this is a known problem and how to avoid it。

**Comment by zasweq** [comment]
Can you please provide code to reproduce this error? The only concrete information provided is this line sendQuotaPool.get(), but the team would need some more context in order to help you

**Comment by easwars** [comment]
The grpc-go [version](https://github.com/grpc/grpc-go/releases/tag/v1.9.1) that you are using is ancient. And the Go version that you are using is not supported by us. Please update to a newer version of grpc-go and let us know if you are still seeing this issue. Thanks.
