### ISSUE TITLE
Access information about the request and response payloads in stat/HandleRPC

### ISSUE THREAD

**Issue by svakili** [grpc/grpc-go#5437]
I am using `stats/HandleRPC()` to emit some metrics about the RPC duration, when I receive the `stats/End` data, and I want to tag the metrics with some information that can be extracted from the incoming and outgoing payloads. What would be the best way to achieve this?

```go
func (h *myStatsHandler) HandleRPC(ctx context.Context, rpcStats stats.RPCStats) {
	switch stat := rpcStats.(type) {
	case *stats.End:
		durationMs := stat.EndTime.Sub(stat.BeginTime).Seconds() * 1000.0
		// Now before sending this value, I need to know, 
		// for example the value of a specific key in the request payload, 
		// or whether the response is nil or not 
	}
}
```

**Comment by easwars** [comment]
(metadata.FromOutgoingContext)[https://pkg.go.dev/google.golang.org/grpc@v1.47.0/metadata#FromOutgoingContext] returns metadata present in the outgoing request. I'm guessing this is what you mean by `value of a specific key in the request payload`. If you are talking about the actual contents of the request payload (like the contents of the protobuf message that was sent in the request), I don't think we will have that information here.

Also, it is not very clear to me exactly what you are trying to do and where you are stuck. Could you please provide some more concrete information about what you are trying and maybe we will be able to help you better. Thanks.
