### ISSUE TITLE
xdsclient: skip localities with zero weight when parsing the resource

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5453]
We do skip localities with zero weight here: https://github.com/grpc/grpc-go/blob/28de4866ce7440b675662abbdd5c43b476bd4dae/xds/internal/balancer/clusterresolver/configbuilder.go#L254

But, we have no tests for this.

**Comment by markdroth** [comment]
FWIW, in C-core, we skip these localities inside of XdsClient when parsing the EDS resource.  They never get returned from the XdsClient, so there's no need to deal with them in any of the LB policies.
