### ISSUE TITLE
examples: add an example to illustrate the usage of stats handler

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5454]

**Comment by Yash-Handa** [comment]
Hi @easwars,
I would love to contribute to **grpc-go** by providing an example that illustrates the usage of the **stats handler**
Please let me know if someone else is working on it or not, So that I can start with it :)

**Comment by easwars** [comment]
Great !! Go for it !!

**Comment by easwars** [comment]
Fixed by https://github.com/grpc/grpc-go/pull/5657.
