### ISSUE TITLE
Dial over an existing connection.

### ISSUE THREAD

**Issue by elongl** [grpc/grpc-go#5455]
I want to have a setup in which machine A connects to machine B, but A is the gRPC server and B is the client.  

My approach was to use a multiplexing library like [yamux](https://github.com/hashicorp/yamux) in order to first establish a regular TCP connection, and then to create a server stream on the client (machine A) and have the server (machine B) connect to it.

All of this would've been possible if gRPC had a way of dialing over an existing connection instead of necessarily receiving a target address. I wanted to know if there's a way to get this done, or altogether a different approach to solve this problem.

Thanks.

**Comment by noamApps** [comment]
@easwars hey there, this was possible up until (not including) v1.46, you could do something like 
```
var existingConn net.Conn
// initialize existingConn...
grpcConn, err := grpc.DialContext(ctx, "", []grpc.DialOption{
    grpc.WithTransportCredentials(insecure.NewCredentials()),
    grpc.WithContextDialer(func(ctx context.Context, addr string) (net.Conn, error) {
        return existingConn, nil
    }),
}...,)
```

( notice the "" passed as target addr )

there several use cases for this technique and examples in the community, there is this old discussion in the repo about how to achieve this (https://github.com/grpc/grpc-go/issues/484#issuecomment-388650314)

I still could not pinpoint what broke my example in 1.46, I suspected it was related to #5274 

Anyway, if you think I can still make the dial over reverse connection work in 1.46+ by changing the Dialer options it will be of great help 

@elongl if you can use older grpc versions, 1.45 should work for your use case if I understood it correctly
