### ISSUE TITLE
grpc server support HTTP Connect

### ISSUE THREAD

**Issue by sodaRyCN** [grpc/grpc-go#5472]
I build a simple grpc proxy by this issue's suggestion(https://github.com/grpc/grpc-go/issues/5388).
in my case, grpc client add real target address in header , and the grpc proxy (use the UnknownServiceHandler) would read that and create ClientConn of target address, and the proxy work well.

but now , we would like try use grpc client proxy option instead of add target addr in header，that seems to be common, lol. by the way , in test , client and server build with grpc-java , grpc-proxy build with grpc-go.

and then we got an exception: it's seem like the grpc proxy couldn't handle http method connect when grpc client used proxy option.

I would like to know if the idea is not feasible, or do you have any good suggestions.

**Comment by sodaRyCN** [comment]
My understanding of your reply is: If I expect to support the HTTP Connect method, I should implement a proxy server based on the net/http or net/http2 standard library, instead of using grpc.server as a proxy, although it is based on H2, it is not designed to support Connect?

I don't know if I understand it wrong

**Comment by dfawley** [comment]
That sounds right.  These are different types of proxies.  An http proxy only understands http semantics, but the grpc proxy you have built is a fully functioning grpc server that does not support CONNECT or HTTP forwarding; just the grpc forwarding you implemented.
