### ISSUE TITLE
Go generator assumes packed=true on repeated scalar fields

### ISSUE THREAD

**Issue by jhspaybar** [grpc/grpc-go#548]
Please see https://github.com/grpc/grpc/issues/5174 for context.

Long story short, it appears the generated code for Go is assuming a packed=true on repeated scalar fields(as did my Java server).

**Comment by dsymonds** [comment]
I think proto3 specifies that encoders should use packed=true by default, but that's moot since compliant proto parsers are meant to work with both non-packed and packed.

**Comment by iamqizhao** [comment]
Close since this is not a grpc issue.
