### ISSUE TITLE
Since v1.48.0: cannot configure XDS bootstrap in code for testing

### ISSUE THREAD

**Issue by howardjohn** [grpc/grpc-go#5501]
See https://github.com/grpc/grpc-go/issues/4124 for rationale, original implementation, etc. In v1.48.0 this was reverted in https://github.com/grpc/grpc-go/issues/4829, making the NewXDSResolverWithConfigForTesting method unaccessible.

cc @easwars

**Comment by easwars** [comment]
Sorry for breaking you. We will re-add this function asap and make a patch release for v1.48.

We also want to make it clear that we don't want this function in our main `xds` package. We really *should* be discussing and coming up with some alternatives for this.

**Comment by howardjohn** [comment]
Thanks for the quick fix!
