### ISSUE TITLE
Is there a proper way to reconnect in a stream interceptor?

### ISSUE THREAD

**Issue by sosborne1** [grpc/grpc-go#5507]
I'm trying to create an interceptor that can retry a stream client. Needs to be able to recover if the server goes restarts. As it is now, once the server comes back up the retrying stream is able to successfully create a new client stream without error. However the client stream seems to be in a bad state. When calling `RecvMsg` it will get stuck in `waitOnHeader()` in `transport.go` even when the server is continuously sending messages. It appears to the client stream that a header is never sent. Is there a proper way to reestablish the connection in an interceptor? 

Example: 
https://gist.github.com/sosborne1/9440ac18a5798cea91873caae0ccf1bf

**Comment by dfawley** [comment]
It seems that the high level approach he is fine.

This is definitely a race:

https://gist.github.com/sosborne1/9440ac18a5798cea91873caae0ccf1bf#file-interceptor_test-go-L58-L60

This should allow for `io.EOF`, which is the end of stream success condition:

https://gist.github.com/sosborne1/9440ac18a5798cea91873caae0ccf1bf#file-interceptor_test-go-L52-L54

Why sleep?

https://gist.github.com/sosborne1/9440ac18a5798cea91873caae0ccf1bf#file-interceptor_test-go-L61

Maybe you want to use gRPC's native retry support instead?

https://github.com/grpc/proposal/blob/master/A6-client-retries.md

**Comment by sosborne1** [comment]
> This is definitely a race:
> 
> https://gist.github.com/sosborne1/9440ac18a5798cea91873caae0ccf1bf#file-interceptor_test-go-L58-L60
> 
I have the getting/setting of the clientstream guarded by a mutex lock now
https://gist.github.com/sosborne1/9440ac18a5798cea91873caae0ccf1bf#file-interceptor_test-go-L49-L59

> This should allow for `io.EOF`, which is the end of stream success condition:
> 
> https://gist.github.com/sosborne1/9440ac18a5798cea91873caae0ccf1bf#file-interceptor_test-go-L52-L54
> 
Now checks for `io.EOF` using `errors.Is `
https://gist.github.com/sosborne1/9440ac18a5798cea91873caae0ccf1bf#file-interceptor_test-go-L64

> Why sleep?
> 
> https://gist.github.com/sosborne1/9440ac18a5798cea91873caae0ccf1bf#file-interceptor_test-go-L61
> 
I've removed the sleep, this was leftever when simplifying the interceptor from production code

> Maybe you want to use gRPC's native retry support instead?
> 
> https://github.com/grpc/proposal/blob/master/A6-client-retries.md
I've added a test using the native retry

**Comment by sosborne1** [comment]
> This is definitely a race:
> 
> https://gist.github.com/sosborne1/9440ac18a5798cea91873caae0ccf1bf#file-interceptor_test-go-L58-L60
> 
I have the getting/setting of the clientstream guarded by a mutex lock now
https://gist.github.com/sosborne1/9440ac18a5798cea91873caae0ccf1bf#file-interceptor_test-go-L49-L59

> This should allow for `io.EOF`, which is the end of stream success condition:
> 
> https://gist.github.com/sosborne1/9440ac18a5798cea91873caae0ccf1bf#file-interceptor_test-go-L52-L54
> 
Now checks for `io.EOF` using `errors.Is `
https://gist.github.com/sosborne1/9440ac18a5798cea91873caae0ccf1bf#file-interceptor_test-go-L64

The error I get once the server shuts down is `rpc error: code = Unavailable desc = error reading from server: EOF`, which isn't caught by the linked code. 

Is it possible to create and use a new stream in this interceptor after the above error?

> Why sleep?
> 
> https://gist.github.com/sosborne1/9440ac18a5798cea91873caae0ccf1bf#file-interceptor_test-go-L61
> 
I've removed the sleep, this was leftover when simplifying the interceptor from production code

> Maybe you want to use gRPC's native retry support instead?
> 
> https://github.com/grpc/proposal/blob/master/A6-client-retries.md
>

I've added a test using the native retry and the client fails to retry and returns the following error  `rpc error: code = Unavailable desc = error reading from server: EOF` when the test forces the server to go down and back up.
https://gist.github.com/sosborne1/9440ac18a5798cea91873caae0ccf1bf#file-interceptor_test-go-L204-L220

Is my retry policy in the link above correctly configured such that test client streaming calls are tolerant to intermittent server connection interruptions? Or is there something I'm missing?

**Comment by dfawley** [comment]
> Is my retry policy in the link above correctly configured such that test client streaming calls are tolerant to intermittent server connection interruptions? Or is there something I'm missing?

The config looks correct to me.  One thing that I didn't mention is if the server sends any data before it is stopped, the built-in retry support will not retry the RPC.  It will only retry if no headers or messages have been received.  If you want the client to be able to retry even after that, then something more like what you were trying with the interceptor would be needed.

> Now checks for io.EOF using errors.Is

I wouldn't use `errors.Is`; a pure equality check is fine and the proper thing to do.

> Is it possible to create and use a new stream in this interceptor after the above error?

Yes, I believe so.  You just have to make sure everything is thread safe.  E.g. if there is another goroutine sending on the stream, you need to wait for that to complete before restarting the stream, and you also need a strategy to retry the send operation.  (In this case, I see it's a server-streaming RPC, so that's not a concern for this example, but if you have bidi streaming RPCs that you need to use, using the interceptor approach will be much more complex.)

**Comment by sosborne1** [comment]
> > Now checks for io.EOF using errors.Is
> 
> I wouldn't use `errors.Is`; a pure equality check is fine and the proper thing to do.
> 
Done

> > Is it possible to create and use a new stream in this interceptor after the above error?
> 
> Yes, I believe so. You just have to make sure everything is thread safe. E.g. if there is another goroutine sending on the stream, you need to wait for that to complete before restarting the stream, and you also need a strategy to retry the send operation. (In this case, I see it's a server-streaming RPC, so that's not a concern for this example, but if you have bidi streaming RPCs that you need to use, using the interceptor approach will be much more complex.)

Is there something wrong with the test? I don't see the new client stream working. Right now the interceptor will retry until the server comes back up and a new client stream is able to be created without error, then the new client stream will call `RecvMsg` and get stuck in `waitOnHeader()` in `transport.go`. 

https://gist.github.com/sosborne1/9440ac18a5798cea91873caae0ccf1bf#file-interceptor_test-go-L75-L170

**Comment by sosborne1** [comment]
Thanks for your information so far. I was able to get a unary interceptor working with retry but I am still having trouble with the stream version. I'm still getting the same behavior described above. Any insight on this?

**Comment by dfawley** [comment]
> I am still having trouble with the stream version

Is the link above still the implementation you are trying for this or is there a newer snapshot?

I believe you'll want to serialize all operations inside the interceptors, at least if you want to support bidirectional streaming.  For server-side streaming, like in this example, it should be okay.

> Any insight on this?

What kinds of behaviors are you seeing, different from what is expected?

**Comment by sosborne1** [comment]
> 
> Is the link above still the implementation you are trying for this or is there a newer snapshot?
> 
I'm still using the same implementation. 
> I believe you'll want to serialize all operations inside the interceptors, at least if you want to support bidirectional streaming. For server-side streaming, like in this example, it should be okay.
> 
I just need server-side streaming. 

> 
> What kinds of behaviors are you seeing, different from what is expected?

I don't see the new client stream working. Right now the interceptor will retry until the server comes back up and a new client stream is able to be created without error, then the new client stream will call `RecvMsg` and get stuck in `waitOnHeader()` in `transport.go`. Even though the server should be constantly sending out messages.

**Comment by dfawley** [comment]
> Right now the interceptor will retry until the server comes back up and a new client stream is able to be created without error, then the new client stream will call RecvMsg and get stuck in waitOnHeader() in transport.go. Even though the server should be constantly sending out messages.

Aha, I bet I see what's happening.

A streaming interceptor assumes bidirectional streaming.  But your handler and client are using a server-streaming RPC.  So when the initial request is started, the `newStream` function passed to the interceptor creates the stream, but _other_ stream initiating code sends the client's initial request.  When it's called again, it only creates the stream and nothing will send the client's initial request.

You will need the interceptor to send the client's initial request and call `CloseSend` on the stream once it is created.  In order to know what that request is, you'll need to intercept the `SendMsg` call and save it.

**Comment by sosborne1** [comment]
> You will need the interceptor to send the client's initial request and call `CloseSend` on the stream once it is created. In order to know what that request is, you'll need to intercept the `SendMsg` call and save it.

That seems to have done the trick, thanks for your help!
