### ISSUE TITLE
Possible Leak

### ISSUE THREAD

**Issue by seiflotfy** [grpc/grpc-go#554]
Hey guys,

**1. What version of Go are you using (go version)?**
   I am using go 1.6rc2 (i also used 1.5.2).

**2. What operating system and processor architecture are you using?**
   I am using a Mac OSX 10.11

**3. What did you do?**
I have a grpc server implementing the interfaces of the following [protobuf](
https://github.com/skizzehq/skizze/blob/master/src/datamodel/protobuf/skizze.pb.go) but without any logic. I am feeding it via Add from client in a loop.

**4. What did you expect to see?**
Memory being freed.

**5. What did you see instead?**
Memory increase which seems like leaking memory. 
* [pprof top10](https://gist.github.com/seiflotfy/1e46f4074d3a1dbe81c3)
* [pprof list proto](https://gist.github.com/seiflotfy/41aacbf35294faa162a3)
* [pprof web] (https://www.dropbox.com/s/pjtl2zotjrc6z4n/skizze-leak.svg?dl=0)

The code I used on the server side can be found here (https://github.com/seiflotfy/skizze/blob/leak/src/server/todo.go#L43)

I am calling the Add method from the client found here (https://github.com/skizzehq/skizze-utils/blob/master/src/skizze-stress/main.go#L45) 

via AddToDomain which is provided by the following "wrapper" (https://github.com/skizzehq/goskizze/blob/master/skizze/client.go#L242)

**Comment by iamqizhao** [comment]
This does not help. Please show us your client and server code you were running.

**Comment by seiflotfy** [comment]
updated with code references and new pprof output (simplified the go code)

**Comment by seiflotfy** [comment]
I now tried to start the server and take a base.heap snapshot then run the client once and take a current.heap snapshot. https://www.dropbox.com/s/i8d6yhqz9m3mudf/skizze-mem.svg?dl=0

white top is saying
```
(pprof) top
33.62MB of 33.62MB total (  100%)
Dropped 11 nodes (cum <= 0.17MB)
Showing top 10 nodes out of 23 (cum >= 31.53MB)
      flat  flat%   sum%        cum   cum%
   23.53MB 69.99% 69.99%    31.53MB 93.78%  github.com/golang/protobuf/proto.(*Buffer).dec_slice_string
       8MB 23.79% 93.78%        8MB 23.79%  github.com/golang/protobuf/proto.(*Buffer).DecodeStringBytes
    1.09MB  3.24% 97.02%     1.09MB  3.24%  html.init
       1MB  2.98%   100%        1MB  2.98%  internal/golang.org/x/net/http2/hpack.addDecoderNode
         0     0%   100%    31.53MB 93.78%  datamodel/protobuf._Skizze_Add_Handler
         0     0%   100%    31.53MB 93.78%  github.com/golang/protobuf/proto.(*Buffer).Unmarshal
         0     0%   100%    31.53MB 93.78%  github.com/golang/protobuf/proto.(*Buffer).unmarshalType
         0     0%   100%    31.53MB 93.78%  github.com/golang/protobuf/proto.Unmarshal
         0     0%   100%    31.53MB 93.78%  github.com/golang/protobuf/proto.UnmarshalMerge
         0     0%   100%    31.53MB 93.78%  google.golang.org/grpc.(*Server).Serve.func2.1.1
```

**Comment by iamqizhao** [comment]
This is still not clear to me whether this is a leak. Can you do the following instead:
i) use fixed size  proto msg (e.g., 100k) instead of something random (i.e., zipf in your code) on client side;
ii) have a memory usage snapshot when the first rpc arrives on the server and have another when the last rpc arrvies. And show me the difference.

**Comment by iamqizhao** [comment]
@seiflotfy is this still an issue?

**Comment by iamqizhao** [comment]
close due to no response.
