### ISSUE TITLE
Publish protoc-gen-go-grpc binaries for arm64

### ISSUE THREAD

**Issue by anuraaga** [grpc/grpc-go#5544]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?

Allow native binaries for use on M1 laptops or cloud arm64 VMs used in build machines.

### Proposed Solution

Update release workflow to add arm64 as a goarch (could consider excluding windows arm64 similar to darwin i386 if not comfortable publishing it as it's not a readily usable platform yet)

https://github.com/grpc/grpc-go/blob/master/.github/workflows/release.yml#L15

### Additional Context

`protoc-gen-go` recently made this change so it would be nice if gRPC also followed the pattern

https://github.com/golang/protobuf/issues/1466

Also, let me know if it's worth a separate issue, but I wonder if the binaries could be published with every release in this repo instead of separate tags? I haven't seen other languages version their compiler separately from the runtime, and it seems to make things somewhat confusing here.

**Comment by zasweq** [comment]
Thank you for bringing this suggestion up. Would you be willing to contribute a PR for this?

**Comment by anuraaga** [comment]
Hi - I have a PR out for this so hopefully can be marked unatale
