### ISSUE TITLE
how can I know the server stream timeout or client disconnected on server side

### ISSUE THREAD

**Issue by shyandsy** [grpc/grpc-go#5554]
I have some server stream handler like the follow code
```
func (n *Handler) Subscribe(t *__.T, stream __.SubscribeServer) error {
	for {
		select {
		case payload, ok := <-ch:
			if !ok {
                               break
			}
			err = stream.Send(&__.Response{Payload: payload})
			if err != nil {
				return err
			}
		}
	}

	return nil
}
```

the problem is how can I know the client disconnected the call, or the server has been timeout and the connection has been closed?

**Comment by zasweq** [comment]
The error object itself should have information about the type of error. Could you try logging the error, if you paste the log here I can help you derive what it means.

**Comment by shyandsy** [comment]
if its the only way to know the client has been disconnected from server by checking the error returned by stream.Send, it means we cannot release the resource for connections if there is no information sending to client.

maybe we need a connection pool on server, and a notification mechiasm?
