### ISSUE TITLE
Multiple clients using same connection with KeepAlive leads to too many pings

### ISSUE THREAD

**Issue by zekth** [grpc/grpc-go#5564]
### What version of gRPC are you using?

```
google.golang.org/grpc v1.48.0
```

### What version of Go are you using (`go version`)?

```
go version go1.18.5 darwin/amd64
```

### What operating system (Linux, Windows, …) and version?

Linux

### What did you do?

Creating a connection with this king of parameters
```go
grpc.WithKeepaliveParams(keepalive.ClientParameters{
				Time:                1 * time.Minute,
				Timeout:             5 * time.Second,
				PermitWithoutStream: true,
			})
```
And reusing it with 2 different clients.

### What did you expect to see?

Connection working properly and smoothly

### What did you see instead?

Server kills the connection with `ENHANCE_YOUR_CALM` error. But when using 2 different connections with the 2 clients i use otherwise it works smoothly. Is there a way to enable keep-alive on the connection but having only one client sending the TCP ping? Or am i doing something wrong?

**Comment by easwars** [comment]
Do you have any keepalive configuration on the server, set using this [ServerOption](https://pkg.go.dev/google.golang.org/grpc#KeepaliveParams)?

And have you set an enforcement policy on the server, set using this [ServerOption](https://pkg.go.dev/google.golang.org/grpc#KeepaliveEnforcementPolicy)?

**Comment by zekth** [comment]
None of those were set, so the server uses the default ones.

**Comment by zekth** [comment]
hum? I'm pretty confused. I gave updates.

**Comment by easwars** [comment]
What do you mean by a connection and what do you mean by a client here? Could you please provide code samples and a way to reproduce this issue, so that we can better assist you. Thanks.
