### ISSUE TITLE
Client-side Recv() blocked on waitOnHeader after server's handler has stopped

### ISSUE THREAD

**Issue by alfa-alex** [grpc/grpc-go#5567]
### What version of gRPC are you using?
`google.golang.org/grpc v1.48.0`

### What version of Go are you using (`go version`)?
`go version go1.19 linux/amd64`

### What operating system (Linux, Windows, …) and version?
Linux, Ubuntu 22.04

### What did you do?
I called `runtime.Goexit()` in a gRPC handler.

### What did you expect to see?
The client calling that method would return from its call.

### What did you see instead?
The client is blocked on `waitOnHeader` (`transport.go:324`) until it times out.

### Step to reproduce:
Based on the [helloworld example](https://github.com/grpc/grpc-go/tree/master/examples/helloworld):
- Insert `runtime.Goexit()` after [L. 43 in `SayHello`](https://github.com/grpc/grpc-go/blob/master/examples/helloworld/greeter_server/main.go#L43)
- Increase the client timeout to say 10 seconds in [L. 43 in `main`](https://github.com/grpc/grpc-go/blob/master/examples/helloworld/greeter_client/main.go#L53)
- Run both server and client. You can see that the client blocks until it times out.

---

I know that it's usually a good idea to use timeouts. But given that there'll never be a response to the client in this case, couldn't the server somehow signal that to the client to let it continue earlier?

**Comment by easwars** [comment]
There is no way for the client to know that the server handler has crashed (this information cannot be communicated from the server to the client). The responsibility of the server handler is to run to completion and return an [RPC status](https://github.com/grpc/grpc-go/blob/3f5b7ab48ca0e597815c6ade7c6c43e8eee95893/status/status.go#L45). 

There is not much that can be done here. Feel free to comment if you think you want to see some specific change here. Thanks.
