### ISSUE TITLE
go get at tip fails with undefined: http2.TrailerPrefix on darwin/amd64

### ISSUE THREAD

**Issue by rjammala** [grpc/grpc-go#558]
$ go get google.golang.org/grpc
# google.golang.org/grpc/transport
gocode/src/google.golang.org/grpc/transport/handler_server.go:202: undefined: http2.TrailerPrefix
0700077782A:~ rajanikanth.j$ go version
go version devel +387d5b8 Sat Feb 13 17:33:22 2016 +0000 darwin/amd64

**Comment by bradfitz** [comment]
Update your http dep. Either:

```
$ go get -u golang.org/x/net/http2
```

Or:

```
$ go get -u google.golang.org/grpc
```

**Comment by rjammala** [comment]
Thanks @bradfitz
