### ISSUE TITLE
Peer information after handshake.

### ISSUE THREAD

**Issue by feihu-stripe** [grpc/grpc-go#5586]
Hi,

I am trying to track clients by their authInfo when connections are established (in HandleConn), but looks like Peer info is only available per each rpc (in HandleRPC).

So I wonder if it makes sense to make peer info available right after a successful [hand shake](https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_server.go#L144)?

It allows to only check peer once when connection is established for client tracking purpose.

Thanks,
Fei

**Comment by feihu-stripe** [comment]
Propose to append the following to the [http2_server.go](https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_server.go#L1442), I can submit a PR if this looks plausible.

```
type peerKey struct{}

// GetPeer gets the peer from the context.
func GetPeer(ctx context.Context) *peer.Peer {
	peer, _ := ctx.Value(peerKey{}).(*peer.Peer)
	return peer
}

// SetConnection adds the peer to the context to be able to get
// information about peer.
func setPeer(ctx context.Context, peer *peer.Peer) context.Context {
	return context.WithValue(ctx, peerKey{}, peer)
}

func (t *http2Server) getPeer() *peer.Peer {
	return &peer.Peer{
		Addr:     t.remoteAddr,
		AuthInfo: t.authInfo,
	}
}

**Comment by easwars** [comment]
Sure, feel free to send a PR and we will review it. Thanks.
