### ISSUE TITLE
rpc error: code = Canceled desc = context canceled

### ISSUE THREAD

**Issue by 393633905** [grpc/grpc-go#5604]
# Server:
```
type RankServer struct {
	sync.Mutex

	List map[string]*apis.Person
}

func (r *RankServer) Registers(server apis.RankService_RegistersServer) error {
	var ps = &apis.Persons{}

	for {
		p, err := server.Recv()
		if err != nil {
			if err == io.EOF {
				break
			}
			return err
		}

		ps.Persons = append(ps.Persons, p)
	
		r.Lock()
		r.List[p.Name] = p
		r.Unlock()
	}

	fmt.Println("ps", ps)

	return server.SendAndClose(ps)
}
```

# Client:
```
rgc, err := client.Registers(context.Background())
	if err != nil {
		log.Fatalf("Registers Error：%v\n", err)
	}
	rgc.Send(&apis.Person{
		Id:   2,
		Name: "Lisi",
		Age:  24,
	})

	rgc.Send(&apis.Person{
		Id:   3,
		Name: "Wangwu",
		Age:  25,
	})

	if err = rgc.CloseSend(); err != nil {
		log.Fatalf("registerClient.CloseSend Error：%v\n", err)
	}
```

**Comment by zasweq** [comment]
What exactly are you asking here? I see the type question label, but see two blocks of code. Are you asking why are you getting that error? If so, can you please provide more information, such as what version of gRPC-Go are you running, what version of Go are you running, and what operating system/version?

**Comment by 393633905** [comment]
> What exactly are you asking here? I see the type question label, but see two blocks of code. Are you asking why are you getting that error? If so, can you please provide more information, such as what version of gRPC-Go are you running, what version of Go are you running, and what operating system/version? Also I don't think these codeblocks provide enough information about the code itself, please include the full files (maybe push to an example repo).

Thanks ，I have solved the problem。

**Comment by zasweq** [comment]
Ok, great! Good to hear!
