### ISSUE TITLE
Whether these interfaces/functions marked deprecated will be removed in future

### ISSUE THREAD

**Issue by sodaRyCN** [grpc/grpc-go#5605]
grpc version:1.46.2
some interfaces/function (`WithCodec`/`CustomCodec`/`codec.Codec`) are marked as deprecated, `encoding.Codec` and its related interfaces are recommended.

q:
1.  whether these interfaces/functions marked deprecated will be removed in future
2.  If I only implement a custom encoding.CodeC on one end(client or server side), and the CodeC is actually the default Proto decoder used, then on the other end, will it report an error because there is no such a custom decoder locally? because I noticed this [document](https://github.com/grpc/grpc-go/blob/master/Documentation/encoding.md) there is a sentence `In an upcoming change (tracked in this issue), such requests will be rejected with status code Unimplemented instead`.

**Comment by dfawley** [comment]
> whether these interfaces/functions marked deprecated will be removed in future

The ones mentioned will not be removed unless we ever do a v2.  We still don't recommend using them, and there are other APIs marked as deprecated that may be removed in the future.  The difference is whether it was introduced as experimental or not.

https://github.com/grpc/grpc-go/blob/master/Documentation/versioning.md

Usually we have a better comment, but it's something we didn't always do, so some old APIs don't mention it.  E.g.s:

https://pkg.go.dev/google.golang.org/grpc#pkg-variables
> Deprecated: use ConnectParams instead. Will be supported throughout 1.x.
https://pkg.go.dev/google.golang.org/grpc#WithServiceConfig
> Deprecated: service config should be received through name resolver or via WithDefaultServiceConfig, as specified at https://github.com/grpc/grpc/blob/master/doc/service_config.md. Will be removed in a future 1.x release.

> If I only implement a custom encoding.CodeC on one end(client or server side), and the CodeC is actually the default Proto decoder used, then on the other end, will it report an error because there is no such a custom decoder locally?

If it's called "proto" then no.  The "proto" codec is and will always be installed by default.

What is probably changing one day is the server will stop using the "proto" codec to attempt to decode messages that have another message encoding if a codec with that name is not registered.  For now it tries to use the proto codec for everything it doesn't recognize.
