### ISSUE TITLE
insecure.NewCredentials() is not working

### ISSUE THREAD

**Issue by JonahLyu** [grpc/grpc-go#5609]
Hi,

I am trying to create a client connection with insecure dial option. But I find that the built-in `insecure.NewCredentials()` is not working. Instead, I pass my own `tls.Config` into the option func then it works. Am I missing anything when I use the `insecure` package?
```go
//this is working
conn, err := grpc.DialContext(ctx, conf.Target, grpc.WithBlock(), grpc.WithTransportCredentials(credentials.NewTLS(&tls.Config{InsecureSkipVerify: true})))
//this doesn't work
conn, err = grpc.DialContext(ctx, conf.Target, grpc.WithBlock(), grpc.WithTransportCredentials(insecure.NewCredentials()))                                  
```

**Comment by easwars** [comment]
What is not working? 
What credentials does the server expect?
What errors do you see on the client?
Can you please provide some details.

`insecure` credentials implies the use of no transport layer security. So, if your server expects the client to provide credentials, using `insecure` credentials on the client will not work.
