### ISSUE TITLE
https://godoc.org/google.golang.org/grpc reffers incorent github repository

### ISSUE THREAD

**Issue by ingvagabund** [grpc/grpc-go#561]
```vim
package grpc

import "google.golang.org/grpc"

Package grpc implements an RPC system called gRPC.

See https://github.com/grpc/grpc for more information about gRPC.
```

Correct link is ``https://github.com/grpc/grpc-go``

**Comment by dsymonds** [comment]
The link is correct (or could even be to grpc.io). It's a link for more information about gRPC in general, not about grpc-go specifically.

**Comment by iamqizhao** [comment]
I will change it to grpc.io.
