### ISSUE TITLE
First received frame was not SETTINGS. Hex dump for first 5 bytes: 0000000401

### ISSUE THREAD

**Issue by guyinyou** [grpc/grpc-go#5615]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
server(java):
<grpc.version>1.45.0</grpc.version>
<protobuf.version>3.20.1</protobuf.version>

client(go):
require google.golang.org/grpc v1.48.0

### What version of Go are you using (`go version`)?
go 1.17

### What operating system (Linux, Windows, …) and version?
MacOS 12.3 (21E230)

### What did you do?
If possible, provide a recipe for reproducing the error.

**Comment by guyinyou** [comment]
refer: https://github.com/apache/rocketmq-clients/issues/171

**Comment by dfawley** [comment]
Please fill out the template as much as possible.  There is not enough information here for us to reproduce or debug.
