### ISSUE TITLE
Git semver release tags

### ISSUE THREAD

**Issue by gdm85** [grpc/grpc-go#562]
When using vendoring, it is also needed to pin packages to specific versions.

Would it be possible to tag releases in this git repository using [semver](http://semver.org/) tags?

**Comment by zellyn** [comment]
+1  Docker, CoreOS, Kubernetes and many other prominent Go projects are doing this.

**Comment by bradfitz** [comment]
I vote no. Pin the hash you need after it's tested with your application. It's not like we're maintaining many branches. There is exactly one.

**Comment by gdm85** [comment]
@bradfitz tags make sense if you have a reported version, releases and a `CHANGELOG`, which I see you don't. So maybe one should first politely ask for those.

**Comment by bradfitz** [comment]
Sorry, this still sounds like a solution in search of a problem. `git log` is a pretty good changelog.

**Comment by gdm85** [comment]
@bradfitz wow. That means versioning software is such an useless flick. How could I not see this before :wink: Thanks anyways.

**Comment by bradfitz** [comment]
It makes sense when you're doing releases and maintaining branches. It doesn't makes sense when you're doing neither. Maybe one day, but not yet.

**Comment by onlyjob** [comment]
Tags/releases are useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Versioning provides additional benefits to encourage vendoring of a particular (e.g. latest stable) release contrary to random unreleased snapshots.

Please consider tagging releases.

Thank you.

See also

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning
