### ISSUE TITLE
HTTP_PROXY is not working

### ISSUE THREAD

**Issue by yangminzhu** [grpc/grpc-go#5624]
The `HTTP_PROXY` environmental variable listed in the documentation [here](https://github.com/grpc/grpc-go/blob/master/Documentation/proxy.md) is not working.

This can be easily verified with the hello_world example. Just run the following command:
```
$ HTTP_PROXY=10.0.0.1:8000 greeter_client -addr 10.0.0.2
```

It does not connect to the proxy at `10.0.0.1` but instead connects to the server `10.0.0.2` directly. However, the `HTTPS_PROXY` works as expected.

This seems due to the grpc code always sets the original URL scheme to `https`: https://github.com/grpc/grpc-go/blob/master/internal/transport/proxy.go#L43

And the underlying go library will only use the `HTTPS_PROXY` when the scheme is `https`: https://cs.opensource.google/go/x/net/+/master:http/httpproxy/proxy.go;l=129-130

Together, this means that the `HTTP_PROXY` can never be used.

Either the grpc-code should be fixed to support the `HTTP_PROXY` correctly or the [documentation](https://github.com/grpc/grpc-go/blob/master/Documentation/proxy.md) should be updated to mention that `HTTP_PROXY` is not supported. 

### What version of gRPC are you using? 
Tested in master but probably exist in previous versions as well.

### What version of Go are you using (`go version`)? 
1.19

### What operating system (Linux, Windows, …) and version? 
MacOS

### What did you do?
Can easily verify with the example `HTTP_PROXY=10.0.0.1:8000 greeter_client -addr 10.0.0.2`

### What did you expect to see?
The greeter_client connects to the HTTP_PROXY at `10.0.0.1`

### What did you see instead?
The greeter_client bypassed the HTTP_PROXY and connects directly to the address `10.0.0.2`

**Comment by dfawley** [comment]
Per the documentation of [ProxyFromEnvironment](https://pkg.go.dev/net/http#ProxyFromEnvironment), `HTTPS_PROXY` only "takes precedence over" `HTTP_PROXY` for `https` schemes.  From my naive understanding of their code, this doesn't seem to be the case, and it doesn't fall back to the `HTTP_PROXY` environment variable as that docstring would imply.  So it seems this is either a bug in the go `ProxyFromEnvironment` function or in their documentation.

**Comment by dfawley** [comment]
https://github.com/golang/go/issues/45227 Looks like they're calling this WAI.  But now their documentation is stale and that change affected our behavior as well.

**Comment by dfawley** [comment]
Filed https://github.com/golang/go/issues/54890 to get the Go team to update their docs.  We'll update our documentation to indicate the behavior is Go version dependent.

**Comment by yangminzhu** [comment]
@dfawley thank you for the investigation, but should `grpc-go` actually follow the rule mentioned in the `grpc/grpc` that (https://github.com/grpc/grpc/blob/master/doc/environment_variables.md):

`
grpc_proxy, https_proxy, http_proxy The URI of the proxy to use for HTTP CONNECT support. These variables are checked in order, and the first one that has a value is used.
`

The above means that HTTP_PROXY should also be checked and used if other variables do not have a value, if we just update the documentation it means the `go-grpc` behavior will diverge from the common standard and probably other implementations (grpc-java, grpc-c++, etc.) as well (if they are following the common standard).

**Comment by dfawley** [comment]
> should grpc-go actually follow the rule mentioned in the grpc/grpc that ([https://github.com/grpc/grpc/blob/master/doc/environment_variables.md](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md?rgh-link-date=2022-09-06T21%3A48%3A01Z)):

At the top of that document, it states:

> gRPC C core based implementations (those contained in this repository) expose some configuration as environment variables that can be set.

So I would say "no".  gRPC-Java doesn't support this behavior either; they support Java's conventions: https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html

In addition, HTTP_PROXY is probably inappropriate to use, because only HTTPS proxies support HTTP CONNECT, and there has been concern with gRPC-C using it.
