### ISSUE TITLE
flaky test: Test/LDSWatch

### ISSUE THREAD

**Issue by zasweq** [grpc/grpc-go#5643]
https://github.com/grpc/grpc-go/runs/8146662490?check_suite_focus=true

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/runs/8146662928?check_suite_focus=true

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/3148068369/jobs/5118211203

**Comment by easwars** [comment]
I have a fix for this as part of my generic xDS API changes, but if y'all are seeing this very often, I can fast track the fix. It's only a test issue anyways.
