### ISSUE TITLE
server: with TLS, TCP user timeout is not set on the underlying connection

### ISSUE THREAD

**Issue by costinm** [grpc/grpc-go#5646]
https://github.com/grpc/grpc-go/blob/60eecd9169ddc74ee6cf4bd52e2e06ef6766c5b7/internal/transport/http2_server.go#L235

I was looking at the write code - for net.Conn this works as expected, but if TLS is used conn will be tls.Conn so the line will
not set a timeout. I would guess rawconn should be passed ?

**Comment by dfawley** [comment]
Unassigning; I thought this was client-side, but it looks like the client is done correctly and only the server needs to be fixed.  I probably don't have cycles for this right now.

**Comment by tobotg** [comment]
@zasweq @dfawley Hello!
I could look into this issue if it's still available for fix. If it's ok, please feel free to assign it to me.
Thanks

**Comment by dfawley** [comment]
Sure, that would be great if you have time for it!

**Comment by tobotg** [comment]
@dfawley I've just submitted a PR now. Please have a look when you get a chance. Thanks
