### ISSUE TITLE
flaky test: Test/GoAwayThenClose

### ISSUE THREAD

**Issue by zasweq** [grpc/grpc-go#5663]
https://github.com/zasweq/grpc-go/actions/runs/3099894871/jobs/5019571243

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/3253038132/jobs/5339910147

**Comment by dfawley** [comment]
#5293

**Comment by easwars** [comment]
I can repro this on google3. About 7/100k times flakes. I think the test needs a bit of rewriting to ensure that when it fails, it fails fairly quickly. Now, the test just hangs until the `go test` timeout kicks in.
