### ISSUE TITLE
xds: implement `set_node_on_first_message_only` equivilent

### ISSUE THREAD

**Issue by howardjohn** [grpc/grpc-go#5668]
See https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/config_source.proto#config-core-v3-apiconfigsource.

This flag in Envoy creates a very substantial performance improvement in some cases. In enabling it in Istio we saw nearly 50% decrease in CPU cost of the control plane.

As far as I can tell, grpc-go XDS library is always sending the node. it would be great to have a similar optimization to only send it on the first message.

**Comment by easwars** [comment]
Thanks @howardjohn for bringing this up. I'm working on a major refactor of the xDS client implementation. I will either take care of this issue as part of it, or will do it after the refactor work is done.
