### ISSUE TITLE
Inconsistent behaviour of GRPC server for the "grpc-timeout" request header in grpc-go as compared to grpc-node & grpc-java

### ISSUE THREAD

**Issue by rahulsethione** [grpc/grpc-go#5671]
Hi.

I have observed that the "grpc-timeout" request header/metadata is not working for grpc-go (Go), but its working as expected for grpc-node (Node.js). Both servers using HTTP/2. The common knowledge based on the following document is that the "grpc-timeout" request header is used by the client to set a deadline for the server to end the stream. 

https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

### What version of gRPC are you using?
Go:
- google.golang.org/grpc v1.49.0

Node.js: 
- "@grpc/grpc-js": "^1.7.0"
- "@grpc/proto-loader": "^0.7.2"
- Node.js 14 LTS

### What version of Go are you using (`go version`)?
go version go1.18.1 darwin/arm64

### What operating system (Linux, Windows, …) and version?
Mac OS M1 Pro Arm64 Monterey

### What did you do?
First, I wrote a simple GRPC application with Node.js using npm libraries mentioned above, which I believe are the latest versions. Then I wrote a GRPC application with Go, grpc libraries mentioned above for go, everything latest. The Go application does exactly what the Node.js application does, both GRPC servers. I used postman as a client. For Node.js, I sent the "grpc-timeout: 1S" request header as metadata and it worked as expected out of the box. And I really liked it. It closed the stream in 1 second with DEADLINE_EXCEEDED. However, sadly this is not working with the Go GRPC server. Now, not sure would it work for other technologies like Java or Python.

### What did you expect to see?
Expected the ```grpc-timeout``` request header to work consistently, regardless of the technology/programming language. But its not working for Go and working as expected for Node.js.

### What did you see instead?
Mentioned already. Another observation, I tried printing the request header in Go application, but it was an empty array:
```
// Go
headers, ok := metadata.FromIncomingContext(stream.Context())
if ok {
    fmt.Println((len(headers.Get("other-header")))) // Prints 1
    fmt.Println((len(headers.Get("grpc-timeout")))) // Prints 0
}
```
Again, no such issue with Node.js. 

Please look into the issue.

**Comment by rahulsethione** [comment]
### Update (Java)
I verified the behaviour of the "grpc-timeout" header in Java as well. It works as expected, like Node.js. Please confirm if this problem is only with Go GRPC, and that for other programming languages Python and .NET C#, it will work as expected. Thanks.

**Comment by dfawley** [comment]
I'm not sure how such a basic feature like timeouts could be failing for you.  Are you setting this header by hand?  You should not ever need to do that if you are using a grpc library for sending the RPCs.  The library should take care of it for you.

**Comment by rahulsethione** [comment]
@dfawley Hi. I'd like to share the information what exactly I am doing and what is the expectation. 

I wrote some implementation for an RPC, that takes two parameters in the request: ```count``` and ```sleep```. The server generates random number and sends it in a message in the response stream to client, which here is postman. The server send ```count``` number of messages and sleeps between every message for ```sleep``` milliseconds.

 **Are you setting this header by hand?** - Just using postman. Sending header as metadata with the request. But I don't this client really matters here.

<img width="1133" alt="Screenshot 2022-09-27 at 11 35 53 PM" src="https://user-images.githubusercontent.com/19350872/192604766-00d6646b-b3fc-4c6b-9ed2-642d4730e57d.png">

Java GRPC server running on port 8200 over HTTP2:
<img width="1133" alt="Screenshot 2022-09-27 at 11 36 36 PM" src="https://user-images.githubusercontent.com/19350872/192604981-c47cdecd-8d20-4823-8bcd-bc09fab99a30.png">

Node.js GRPC server running on port 8900 over HTTP2:
<img width="1133" alt="Screenshot 2022-09-27 at 11 37 00 PM" src="https://user-images.githubusercontent.com/19350872/192605077-a5740787-7374-40f6-813f-ac00e60cacfa.png">

Go GRPC server running on port 8500 over HTTP2:
<img width="1132" alt="Screenshot 2022-09-27 at 11 37 43 PM" src="https://user-images.githubusercontent.com/19350872/192605165-a7b5f30b-7924-4e7f-81df-caadb522e55a.png">

Proto file:
```
syntax = "proto3";
package org.example.grpc;
option go_package = "./main";
option java_package = "org.example.grpc.proto";
option java_generic_services = true;
option java_multiple_files = true;
option java_outer_classname = "GrpcMain";

message Request {
    uint64 id = 1;
    string text = 2;
    uint64 sleep = 3;
    int32 count = 4;
}

message Response {
    string status = 1;
    uint64 value = 2;
}

service MainService {
    rpc Send (Request) returns (Response);
    rpc SendAndListen (Request) returns (stream Response);
    rpc SendAndListenWithSleep (Request) returns (stream Response);
}
```
Java code: 
```
public void sendAndListenWithSleep(Request request, StreamObserver<Response> responseObserver) {
        // super.sendAndListenWithSleep(request, responseObserver);
        int count = request.getCount();
        long sleep = request.getSleep();

        System.out.println(String.format("SendAndListenWithSleep[Count=%d, Sleep=%d]", count, sleep));

        for(int i = 0; i < count; i++) {
            responseObserver.onNext(Response.newBuilder().setStatus("Success").setValue(10000L + i * 10).build());
            try {
                // responseObserver.wait(sleep);
                Thread.sleep(sleep);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
        responseObserver.onCompleted();
    }
```

Node.js code:
```
// file: definitions.ts 
import { loadSync } from "@grpc/proto-loader"
import { loadPackageDefinition } from "@grpc/grpc-js"
import { resolve } from "path"

const protoFilePath = resolve("../main.proto");
const options = {
    keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true
}
const pkg = loadSync(protoFilePath, options);
const definition = loadPackageDefinition(pkg);

export default definition;

// file: server.ts
...
server.addService((mainService as any).service, {
...
sendAndListenWithSleep(call: any) {
        const count = call.request.count || 10;
        function* generator() {
            for (let i = 0; i < count; i++) {
                yield Math.floor(Math.random() * 1000000);
            }
            return;
        }

        (async () => {
            const iterator = generator();

            let iterable = iterator.next();
            while (!iterable.done) {
                call.write({ status: "Success", value: iterable.value });
                await sleep(call.request.sleep || 0);
                iterable = iterator.next();
            }

            call.end();
        })();
    }
}
```
Go code:
```
func (mainServer *MainServer) SendAndListenWithSleep(request *Request, stream MainService_SendAndListenWithSleepServer) error {
	count := request.Count
	sleep := request.Sleep
	if request.Count != 0 {
		count = 10
	}

	var i int32 = 0
	for i < count {
		response := &Response{
			Status: "Success",
			Value:  rand.Uint64(),
		}
		stream.Send(response)
		time.Sleep(time.Duration(sleep * 1000000))
		i++
	}

	stream.Context().Done()

	return nil
}
```

### Why I am doing all this? 
I am working on a cloud service that uses envoy, and this cloud service offers a platform to run application on kubernetes cluster, where users can configure traffic management with configurations for envoy proxy. I was testing the envoy request timeout as configuration parameter and this "grpc-timeout" header floated across. I tried to test the theory regarding the same with Go first, it just didn't work. So, I check the same for Node.js, followed by Java, and it is working as expected. I just wanted to confirm if the ```grpc-timeout``` is a standard, and it is what I am expecting it to be. I am new to Go, but this was pretty straight forward. Please point out if I did anything wrong. If further investigation is required, I'd be happy to provide more information.

**Comment by dfawley** [comment]
Aha, it seems your server-side code is incorrect:

- `stream.Context().Done()` is a channel (this is all described in the [context package](https://pkg.go.dev/context)) that is closed when the context has been canceled.  So, this should happen after 1 second in your example, because the RPC has a 1 second deadline.  This means you need to poll it; e.g. instead of sleeping:

```go
select {
	case <-time.After(time.Duration(sleep*1000000)):
	case <-stream.Context().Done():
		return stream.Context().Err()
}
```

What behavior do you see from the Go server?  Did it send response messages even after the 1 second timeout elapsed?  I would expect it not to, because the stream should be canceled.  If you are seeing it send successfully even after the deadline, then that would be a (minor) bug.  I say "minor" because: 1. any gRPC client also knows the deadline it set and will cancel the stream upon expiration, and 2. the server method handler should return and stop calling Send when the provided context expires.  That said, it would be very surprising to me if that was the case, and it would be something we'd like to fix quickly.

**Comment by dfawley** [comment]
The other thing is you are not checking the return value of `stream.Send(response)`.  This returns an error, and you should return from your method handler in that case as well.
