### ISSUE TITLE
Circuit Breaker recommendations

### ISSUE THREAD

**Issue by tjungblu** [grpc/grpc-go#5672]
Hi there,

I was investigating some cases of bad throughput on etcd caused by a slow cluster member (https://github.com/etcd-io/etcd/issues/14501). This case can be eliminated fairly easily using a client-side circuit breaker, yet I'm not entirely sure how I can make it work using the UnaryClientInterceptor. 

Tracking the success, latency and failures is clear - where it gets problematic is around picking another connection. Is there an elegant way to solve this in grpc-go? 

I found some references in https://github.com/grpc/grpc-java/issues/7281 that already has some implementations using the client interceptor, which I assume, works by throwing an exception inside the interceptor when the breaker opens which then gets treated as a transient failure. 

Background info on how etcd uses grpc-go:
----

etcd uses a dial conn with a manual resolver:
https://github.com/etcd-io/etcd/blob/main/client/v3/client.go#L53-L57

the resolver is just a proxy to the round robin load balancer:
https://github.com/etcd-io/etcd/blob/main/client/v3/internal/resolver/resolver.go

**Comment by easwars** [comment]
IIUC, the circuit breaking pattern discussed in https://github.com/grpc/grpc-java/issues/7281 only provides a way for the client to fail fast when the other end is not behaving as expected (latency is too high, or rate of failures is too high etc).

Also, in the lifecycle of a gRPC call, the interceptors are invoked before a transport (or connection to a real backend) is picked for the RPC. So, I don't see an easy way out for using interceptors to implement circuit-breaking and be able to retry the RPC on another transport when the circuit is open.

Is using a custom LB policy an option for you. This LB policy could keep track of the successes/failures/latency etc for the different transports to the real server, and pick transports which are healthy, and skip the ones which are not.

**Comment by tjungblu** [comment]
Thanks for the reply @easwars, indeed the Balancer looks like a better fit here and I'll play around a bit with this.

Quick question back, how do I configure such a custom load balancer? I assume that's the important line in the example?
https://github.com/grpc/grpc-go/blob/master/examples/features/load_balancing/client/main.go#L77

I would register first with `balancer.Register` and then in the dialopts I can define it by its `Name`. Correct?

**Comment by easwars** [comment]
Correct, you need to register your balancer builder using `balancer.Register`. And the registration is usually done in an `init()` function. Here are a couple of examples: [pickfirst](https://github.com/grpc/grpc-go/blob/12db695f1648ce84ad74c5240730fb9401f67844/pickfirst.go#L182), [roundrobin](https://github.com/grpc/grpc-go/blob/12db695f1648ce84ad74c5240730fb9401f67844/balancer/roundrobin/roundrobin.go#L44).

And in the `Dial` function, you would use [WithDefaultService](https://pkg.go.dev/google.golang.org/grpc#WithDefaultServiceConfig) dial option to specify the LB policy and any associated configuration. If you have total control over your resolver, then you could even have the resolver send a service config specifying your LB policy. 

Hope this helps. I'll keep this issue open for a while, so feel free to come back with any questions.

We do have an outlier-detection LB policy [here](https://github.com/grpc/grpc-go/tree/master/xds/internal/balancer/outlierdetection). But this is currently available only in the xDS context (even though the LB policy itself does not have any dependency on xDS). Once we are confident about the implementation of this LB policy and have seen enough usage of it, we would move it outside of the xDS tree. But I don't see that happening very soon.
