### ISSUE TITLE
ServerStream context seems never Done()?

### ISSUE THREAD

**Issue by valri11** [grpc/grpc-go#5681]
I need to detect client disconnection as early as possible and trying to select ServerStream context Done() channel, but my server code never reports context as Done()

example: 
```golang
func (s *counterServer) Count(req *comms.CounterReq, stream comms.Counter_CountServer) error {

	log.Println("counter started")

	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	count := int32(0)

	for {
		select {
		case <-stream.Context().Done():
			log.Println("stream context done")
			return stream.Context().Err()
		case <-ticker.C:
			count++
			resp := comms.CounterResp{Counter: count}
			err := stream.Send(&resp)
			if err != nil {
				log.Printf("Send err: %v", err)
				return err
			}
		}
	}
}
```

Complete example of server stream: https://github.com/valri11/testGrpcStream
- run server
- run client
- Ctrl-C in client - server stream function never signalled on `stream.Context().Done()`

**Comment by dfawley** [comment]
The server is probably not noticing the client disconnecting.  Try enabling periodic keepalive pings:

```go
grpc.NewServer(..., grpc.KeepaliveParams(&keepalive.ServerParameters{Time: 2*time.Second, Timeout: 2*time.Second}))
```

(Those are extremely aggressive values just for the purposes of this kind of test case; in production you would typically use much higher values.)

**Comment by valri11** [comment]
Thanks, will try out. But grpc stats handler correctly detects disconnection:
in  `HandleConn(c context.Context, s stats.ConnStats)` I receive connection close event

**Comment by dfawley** [comment]
This is your error:

https://github.com/valri11/testGrpcStream/blob/f97f8701e311414dba93bf50e38356c5a394219e/server/server.go#L77

Namely, you are overriding the stream's context with `context.Background()`, and so the server cannot cancel it.  Return the first parameter instead and it will work as expected.
