### ISSUE TITLE
support "v1" of the reflection protocol, not just "v1alpha"

### ISSUE THREAD

**Issue by jhump** [grpc/grpc-go#5684]
The server reflection service has a v1:
https://github.com/grpc/grpc/blob/master/src/proto/grpc/reflection/v1/reflection.proto

But this repo still only uses the [v1alpha version](https://github.com/grpc/grpc-go/blob/15653fec60abffdd4ed23ec7b488cbd6e1a34160/reflection/grpc_reflection_v1alpha/reflection.proto#L21).

Ideally, the implementation in the reflection sub-package would register implementations for _both_ (or at least accept an option to do so). That would support a transition to the v1 API while still supporting clients that continue to use the v1alpha version.

**Comment by dfawley** [comment]
@ejona86 @markdroth What is happening in grpc-java/c++ here?  Do you support both versions?  v1 was added to the grpc-proto repo 4 years ago, but we never picked it up in grpc-go.

**Comment by ejona86** [comment]
To my knowledge, no language is using v1. Carl added the v1 version, but nothing else happened with it.

It's one of those "how is nobody complaining about this" things, while simultaneously being "things work fine." I do expect this will be painful in many languages, as the API used to register the service commonly only supports a single service.

**Comment by ejona86** [comment]
See also: https://github.com/grpc/grpc-java/issues/6724

**Comment by buzzsurfr** [comment]
Requesting to take this one as a first-time contributor (in code) to grpc-go. (Still pumped from KubeCon NA 2022)

**Comment by dfawley** [comment]
@buzzsurfr SGTM, I think we can go ahead and support both v1 and v1alpha.

**Comment by easwars** [comment]
As part of this change, it would also be good to fix our [script](https://github.com/grpc/grpc-go/blob/master/regenerate.sh) which compiles the proto files. Currently we have a copy of this proto file in our [repo](https://github.com/grpc/grpc-go/blob/master/reflection/grpc_reflection_v1alpha/reflection.proto). We are trying to get rid of this approach where we have a copy of the proto file in our repo, but instead have the `regenerate.sh` pull protos from their canonical sources and only store the generated `pb.go`s in our repo.

**Comment by buzzsurfr** [comment]
@easwars Looking at the script, what's the difference between _legacy sources_ (Generates sources without the embed requirement) and _sources_ (Generates only the new gRPC Service symbols). What's the "embed requirement"?

https://github.com/grpc/grpc-go/blob/7f23df022299ea52c9cd00ebe77f5f5cccbb85dc/regenerate.sh#L53-L74

**Comment by buzzsurfr** [comment]
I did try moving v1alpha to use the protobuf from [grpc-proto/grpc/reflection/v1alpha](https://github.com/grpc/grpc-proto/blob/master/grpc/reflection/v1alpha/reflection.proto) but it's missing a `go_package` directive.

```
WARNING: Missing 'go_package' option in "grpc/reflection/v1alpha/reflection.proto"
```

I see that [v1 has it](https://github.com/grpc/grpc-proto/blob/d653c6d98105b2af937511aa6e46610c7e677e6e/grpc/reflection/v1/reflection.proto#L26)--should I open a separate PR to add a similar line to v1alpha?

**Comment by easwars** [comment]
> I see that [v1 has it](https://github.com/grpc/grpc-proto/blob/d653c6d98105b2af937511aa6e46610c7e677e6e/grpc/reflection/v1/reflection.proto#L26)--should I open a separate PR to add a similar line to v1alpha?

That would be cool if you could do it. Thank you so much.

**Comment by buzzsurfr** [comment]
From #5773:

> the implementation must import both packages (and import alias them appropriately, something like reflectionv1pb and reflectionv1alphapb), and export both services

Should there be two separate implementations--one for v1alpha and one for v1? I'm not sure how we can implement both without either changing the function names or swapping them out at some point.

**Comment by dfawley** [comment]
I think we will need one primary implementation and one wrapper implementation that adapts v1alpha requests & responses into v1 requests & responses.  I think we can use `proto.Marshal` + `proto.Unmarshal` to convert; it's not very efficient but reflection shouldn't be performance sensitive, either.

`Register` should register both.

**Comment by dfawley** [comment]
Sorry, one more thing: `NewServer` should continue returning a v1alpha server, and `NewServerV1` can return the v1 implementation.

**Comment by dfawley** [comment]
IMO that's a fine implementation detail, but the important part is: we should make the `Register` behavior register both v1 and v1alpha for now (ultimately only v1 in the distant future), and we should provide another API that returns the v1 `rpb.ServerReflectionServer`.

**Comment by easwars** [comment]
@buzzsurfr : Just checking in to see if there is any update here. Thanks.

**Comment by yurishkuro** [comment]
I am trying to upgrade to latest grpc-go version and `staticcheck` linter is breaking because #5799 started using a different proto file and all v1alpha types are now labeled `deprecated`. However, upgrading to `v1` is not possible because `reflection` package itself is using `v1alpha`.

**Comment by dfawley** [comment]
@yurishkuro you will need to work around this on your end.  We will need to compile in v1alpha protos for a very long time (possibly even forever?) for compatibility with other versions of gRPC.  Generally speaking, "deprecated" does not mean "should never be used", so these warnings from staticcheck should be advisory, not blocking.

**Comment by yurishkuro** [comment]
@dfawley yes, I've excluded the code path from the linter. But I do think the "deprecated" labeling is invalid, given that not only this "should be used" per your comment, but it's the only thing that *can* be used based on the code and comments above regarding usage in other languages.

**Comment by jhump** [comment]
@dfawley, what's the status of this? Is it being worked on? Would you accept a patch?

I've got a library that support v1 from the client, and a corresponding "patch" for the server-side, for testing. I wonder if an approach like this would be acceptable: https://github.com/jhump/protoreflect/blob/wip-v2/grpcreflect/client_test.go#L548
(Though maybe the other way around, where it uses the generated v1 types and adapts v1alpha to that, instead of vice versa.)
