### ISSUE TITLE
xds: NACK EDS resource if locality weights sum to greater than MaxUint32

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5699]
See documentation of the `load_balancing_weight` field: https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/endpoint/v3/endpoint_components.proto#L164-L175

Specifically it says:
```
The sum of the weights of all localities at the same priority level 
must not exceed uint32_t maximal value (4294967295).
```

This is where we need to use a uint64 to represent the sum of weights and check that it does not exceed MaxUint32.
https://github.com/grpc/grpc-go/blob/c03925db8d3c8adf6c6f708b5f9ef054de019749/xds/internal/xdsclient/xdsresource/unmarshal_eds.go#L126

**Comment by erni27** [comment]
Hi @easwars, is anyone working on this? May I take it?

**Comment by easwars** [comment]
Please go ahead. Thanks.
