### ISSUE TITLE
How to cancel streaming gRPC Send from server

### ISSUE THREAD

**Issue by Sreaper** [grpc/grpc-go#5705]
hi ,i use server stream to send data to client, there is sth wrong with the network, but the connection is not directly disconnected, then the stream.sent is blocking 15min , what i can do to interrupt it   ？ use keeplive ？why no serverStream.close()

**Comment by zasweq** [comment]
Hello. What you do here is pass in a context with a certain timeout. Example here https://github.com/grpc/grpc-go/blob/master/examples/route_guide/client/client.go#L121. If the network is down, I don't think there's any other way to propagate up an error.
