### ISSUE TITLE
internal/buffer: support a close/drain method on the `Unbounded` buffer type

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5708]
Types holding a reference to an `buffer.Unbounded` type could make use of a `Close()` method on the latter when the former is being shutdown.

The behavior of the existing methods would have to change appropriately:
- `Put()`/`Load()`: should be a NOP if buffer is closed
- `Get()`: if buffer is closed, should return a channel on which nothing would ever be pushed. The implementation of `Close()` should call `close` on the underlying channel defined [here](https://github.com/grpc/grpc-go/blob/e163a9085f6c004e3083e3f31a562f875e0cf9ae/internal/buffer/unbounded.go#L37). Users should be able to see that the returned channel is closed. So, something like this:
```golang
  // unbounded buffer variable `buf` is closed at this point
  val, ok := <-buf.Get()
  // Here `ok` should be `false`
```

Users of the `buffer.Unbounded` also need to be modified to call the `Close()` method when they are being shut down.

**Comment by MohabMohamed** [comment]
hello @easwars can you please assign this issue to me?

**Comment by easwars** [comment]
@MohabMohamed : I need to discuss a few things within the team. I will update the description once I'm done with that, and then will assign it to you. That way, there won't be any wasted effort on you part. Thanks.

**Comment by easwars** [comment]
@MohabMohamed : I have updated the description to reflect what we feel might be the way to go. Please let us know if you are still interested in this. Thanks.

**Comment by MohabMohamed** [comment]
@easwars  thanks for returning back with the update. yes, I'm still interested to implement this feature.

**Comment by erni27** [comment]
Hi @MohabMohamed, are you still working on this or may I take it over?

**Comment by easwars** [comment]
I'm assigning this to you @erni27.

**Comment by erni27** [comment]
I did the initial implementation and I realised that `Get()` method is always called as one of the cases inside the select statement. It makes me think if it should then return a closed read channel or a nil one.
A nil channel would disable that case inside the select, no action required by the users.
A closed channel requires some manual handling by the client side (probably getting the channel before entering the for loop with the select statement and set it to nil if closed) to disable the case to avoid wasting resources by falling into indefinite loop until the cleaning process is done.
There is a third option. Add a new method dedicated to the select statement like `GetForSelect()` returning a nil channel if the unbounded buffer is closed. But it seems like a huge overkill burdening the API.
What do you think @easwars?

**Comment by easwars** [comment]
Does the approach of checking the two return values from a channel read not work?

```golang
  // unbounded buffer variable `buf` is closed at this point
  val, ok := <-buf.Get()
  // Here `ok` should be `false`
```

An existing implementation like this:
```golang
func (t *callbackSerializer) run(ctx context.Context) {
	for ctx.Err() == nil {
		select {
		case <-ctx.Done():
			return
		case callback := <-t.callbacks.Get():
			t.callbacks.Load()
			callback.(func(ctx context.Context))(ctx)
		}
	}
}
```

would have to change to something like this:
```
func (t *callbackSerializer) run(ctx context.Context) {
	for ctx.Err() == nil {
		select {
		case <-ctx.Done():
			return
		case callback, ok := <-t.callbacks.Get():
			if !ok {
				return // Or break out of the for loop with a label
			}
			t.callbacks.Load()
			callback.(func(ctx context.Context))(ctx)
		}
	}
}
```

**Comment by erni27** [comment]
For simple cases, it works. But my concern is about more complex ones. If there are more cases within select statement or the one executed when a ctx is canceled contains more logic than basically returning or breaking a loop then things become a bit ambiguous. If we always return or break a loop then it becomes confusing from a client point of view.

Example:
```go
for {
	select {
	case update := <-b.pickerUpdateCh.Get():
		b.pickerUpdateCh.Load()
		b.mu.Lock()
		if b.closed.HasFired() {
			b.mu.Unlock()
			return
		}
		switch u := update.(type) {
		case balancer.State:
			b.childState = u
			b.ClientConn.UpdateState(balancer.State{
				ConnectivityState: b.childState.ConnectivityState,
				Picker: newPicker(b.childState, &dropConfigs{
					drops:           b.drops,
					requestCounter:  b.requestCounter,
					requestCountMax: b.requestCountMax,
				}, b.loadWrapper),
			})
		case *LBConfig:
			dc := b.handleDropAndRequestCount(u)
			if dc != nil && b.childState.Picker != nil {
				b.ClientConn.UpdateState(balancer.State{
					ConnectivityState: b.childState.ConnectivityState,
					Picker:            newPicker(b.childState, dc, b.loadWrapper),
				})
			}
		}
		b.mu.Unlock()
	case <-b.closed.Done():
		if b.cancelLoadReport != nil {
			b.cancelLoadReport()
			b.cancelLoadReport = nil
		}
		return
	}
}
```

**Comment by erni27** [comment]
@easwars: I took a closer look at all potential races and with current implementation there shouldn't be any issue. PR ready to review.
