### ISSUE TITLE
Flaky test: 5526/10k OutlierDetectionWithOutlier

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5709]
https://github.com/grpc/grpc-go/actions/runs/3230165748/jobs/5288298409

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/3277472576/jobs/5394795462

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/3415496460/jobs/5684685396

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/3424244241/jobs/5703697903

**Comment by zasweq** [comment]
Doesn't fail on google3 /10k runs. I'm leaving this open though because clearly it's happening in GA.

**Comment by zasweq** [comment]
[third_party/golang/grpc/test/xds/xds_client_outlier_detection_test.go:181](https://cs.corp.google.com/piper///depot/google3/third_party/golang/grpc/test/xds/xds_client_outlier_detection_test.go?l=181&cl=491436031): rpc EmptyCall() failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
