### ISSUE TITLE
xds: NACK EDS resources with duplicate addresses

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5710]
We recently made an update to the xDS gRFC: https://github.com/grpc/proposal/pull/332

The change of interest here is this:
```
        - The endpoint address must be unique within the cluster (across
          all priorities and localities); if an address is duplicated,
          the resource will be considered invalid.
```

Currently, the EDS response is parsed here: https://github.com/grpc/grpc-go/blob/c672451950653990bd607c8ba08733d6f36d85fc/xds/internal/xdsclient/xdsresource/unmarshal_eds.go#L116

The actual endpoints within a locality are parsed here:
https://github.com/grpc/grpc-go/blob/c672451950653990bd607c8ba08733d6f36d85fc/xds/internal/xdsclient/xdsresource/unmarshal_eds.go#L153

The ideal fix for this issue would be as follows:
- Change the signature of `parseEndpoints` to look something like this:
```golang
func parseEndpoints(lbEndpoints []*v3endpointpb.LbEndpoint, uniqueEndpointAddrs map[string]bool) ([]Endpoint, error) {...}
```
- Create a `map[string]bool` in `parseEDSRespProto()` and pass it to `parseEndpoints`
- `parseEndpoints` would check `uniqueEndpointAddrs` every time it parses an endpoint and if it sees an existing entry for the same address, it should return with an error. Else, it would add an entry to this map with the address of the endpoint.
- Add a test for this issue in `unmarshal_eds_test.go`.

**Comment by easwars** [comment]
@erni27 Just wanted to check with you to see if you are interested in this?

**Comment by erni27** [comment]
@easwars yeah, actually I'd love to help!
