### ISSUE TITLE
binding streaming client source ip

### ISSUE THREAD

**Issue by AYANGt** [grpc/grpc-go#5724]
How should the streaming client bind the IP that sends the request, that is, send the request with a fixed network card ip.

**Comment by AYANGt** [comment]
func withDialer, to solve this question?

**Comment by easwars** [comment]
Yes, [WithContextDialer](https://pkg.go.dev/google.golang.org/grpc#WithContextDialer) would be the way to go. [WithDialer](https://pkg.go.dev/google.golang.org/grpc#WithDialer) is deprecated in favor of the former.
