### ISSUE TITLE
Is it possible to bypass Codec?

### ISSUE THREAD

**Issue by jzelinskie** [grpc/grpc-go#5726]
I've got an gRPC service that caches responses in our handler implementations. For book-keeping purposes, our cache contains the marshaled form of the protobuf messages. It'd be great to be able to avoid unmarshaling and re-marshaling and instead write directly those bytes returned from the cache.

I've looked into implementing a custom Codec, but I wouldn't be able to return the `[]byte` from a regular typed handler (e.g. `func (s *service) MyRPC(req *v1.MyRPCRequest, resp v1.MyRPCResponse) error`).

Is there any guidance I could get for the ideal integration point? I could drop into a lower-level handler similar to what [grpc-proxy](https://github.com/mwitkow/grpc-proxy) does, but I feel like that "throws the baby out with the bathwater".

**Comment by dfawley** [comment]
Did you consider overriding the default proto codec?

```go
func Marshal(interface msg) ([]byte, err) {
	if bytes := CachedBytes(msg); bytes != nil {
		return bytes, nil
	}
	return proto.Marshal(msg.(proto.Message)) // add to cache first?
}
```

Or you could call into the grpc library directly via the `grpc.ServerStream` that is embedded in the proto generated `Stream` type (e.g. https://github.com/grpc/grpc-go/blob/e72cb1c13f9f80d4f3f1b06463096f2403682202/examples/route_guide/routeguide/route_guide_grpc.pb.go#L253).  You could then pass the `[]byte` directly to `SendMsg`, but you would again need to override the proto codec to do the proper type assertion to `[]byte` from `interface{}`.
```

**Comment by jzelinskie** [comment]
>Did you consider overriding the default proto codec?

This strategy would only make sense if the cache was purely avoiding serialization and not the work to produce the response. You'd need some signal to the codec that it should ignore the response you've provided and instead read from the cache.

It also depends on the cache being global/accessible from the codec, which might not be ideal.

> you could call into the grpc library directly via the grpc.ServerStream

I think this strategy is what I was referring to when I mentioned "throwing the baby out with the bathwater". Dropping down to this level of abstraction would forego typed service handlers, right? The service would have to be structure as a RecvMsg and SendMsg with a huge type switch, right?

**Comment by dfawley** [comment]
> This strategy would only make sense if the cache was purely avoiding serialization and not the work to produce the response

You indicated that you already have another caching layer to determine the response to send based on the request, so I was leaving that out.  You _could_ use an empty message to avoid storing as much data in your cache:

```go
var bytesCache = map[proto.Message][]byte // what is used by the custom codec

func (svc *myService) MyHandler(ctx, req MyRequestType) (MyResponseType, error) {
	if resp := GetRespFromCache(req); resp != nil {
		return resp.(MyResponseType /* presumably was a proto.Message to work with all handlers */), nil
	}
	resp := ComputeResponse(req) // <-- business logic here
	bytes, _ := proto.Marshal(resp)
	resp = &MyResponseType{} // use an empty message, so cache doesn't use as much memory in many cases
	bytesCache[resp] = bytes // so resp points to the serialized bytes
	PutRespIntoCache(resp)
	return resp, nil
}
```

That's admittedly pretty ugly, but it works at least.

> I think this strategy is what I was referring to when I mentioned "throwing the baby out with the bathwater". Dropping down to this level of abstraction would forego typed service handlers, right? The service would have to be structure as a RecvMsg and SendMsg with a huge type switch, right?

Ah, right, for streaming RPCs it would not be an issue, since the `grpc.ServerStream` could be used only for cached RPCs, but for unary RPCs it would need to produce an actual message of the right type.


Can you do this in interceptors instead?  Your interceptor could look up in the cache and return `[]byte` directly without calling the handler, and the codec would see the type of response message was `[]byte` via a type assertion per the second suggestion above and skip the marshaling step.
