### ISSUE TITLE
grpclog: data race found with go test -race when call SetLoggerV2

### ISSUE THREAD

**Issue by hnlq715** [grpc/grpc-go#5733]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
v1.50.1

### What version of Go are you using (`go version`)?
go version go1.18 linux/amd64

### What operating system (Linux, Windows, …) and version?
MacOS & Linux

### What did you do?
If possible, provide a recipe for reproducing the error.

go test -race ./...

### What did you expect to see?
no data race

### What did you see instead?

```
WARNING: DATA RACE
Write at 0x000001acc650 by goroutine 81:
  google.golang.org/grpc/grpclog.SetLoggerV2()
      /home/liqi/.gvm/pkgsets/go1.18/global/pkg/mod/google.golang.org/grpc@v1.50.1/grpclog/loggerv2.go:76 +0x364
  github.com/douyu/jupiter/pkg/xgrpclog.SetLogger()
      /home/liqi/workspace/jupiter/pkg/xgrpclog/logger.go:13 +0x2c5
  github.com/douyu/jupiter/pkg/client/grpc.init.0.func1()
      /home/liqi/workspace/jupiter/pkg/client/grpc/client.go:32 +0x36
  github.com/douyu/jupiter/pkg/conf.(*Configuration).Load()
      /home/liqi/workspace/jupiter/pkg/conf/conf.go:160 +0x130
  github.com/douyu/jupiter/pkg/conf.(*Configuration).LoadFromReader()
      /home/liqi/workspace/jupiter/pkg/conf/conf.go:171 +0x85
  github.com/douyu/jupiter/pkg/conf.LoadFromReader()
      /home/liqi/workspace/jupiter/pkg/conf/api.go:46 +0xfc
  github.com/douyu/jupiter/pkg/client/grpc.TestConfig()
      /home/liqi/workspace/jupiter/pkg/client/grpc/config_test.go:34 +0x18
  testing.tRunner()
      /home/liqi/.gvm/gos/go1.18/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /home/liqi/.gvm/gos/go1.18/src/testing/testing.go:1486 +0x47

Previous read at 0x000001acc650 by goroutine 86:
  google.golang.org/grpc/grpclog.V()
      /home/liqi/.gvm/pkgsets/go1.18/global/pkg/mod/google.golang.org/grpc@v1.50.1/grpclog/grpclog.go:41 +0x30
  google.golang.org/grpc/grpclog.(*componentData).V()
      /home/liqi/.gvm/pkgsets/go1.18/global/pkg/mod/google.golang.org/grpc@v1.50.1/grpclog/component.go:103 +0x4e
  google.golang.org/grpc/internal/transport.(*loopyWriter).run.func1()
      /home/liqi/.gvm/pkgsets/go1.18/global/pkg/mod/google.golang.org/grpc@v1.50.1/internal/transport/controlbuf.go:528 +0x1a1
  runtime.deferreturn()
      /home/liqi/.gvm/gos/go1.18/src/runtime/panic.go:436 +0x32
  google.golang.org/grpc/internal/transport.newHTTP2Client.func3()
      /home/liqi/.gvm/pkgsets/go1.18/global/pkg/mod/google.golang.org/grpc@v1.50.1/internal/transport/http2_client.go:419 +0x105

```

**Comment by dfawley** [comment]
Does this reproduce on master or only on 1.50.1?  Is it a regression from 1.50.0 or some older release?

**Comment by dfawley** [comment]
It seems like this is your test that has the race, and not a test in our repo?

It looks like you are calling `grpclog.SetLogger` at some time after `init`, which is not allowed per [its docstring comments](https://pkg.go.dev/google.golang.org/grpc/grpclog#SetLogger).

**Comment by hnlq715** [comment]
@dfawley Thanks for reply :-)

There are some situations we need to call grpclog.SetLogger after init, for example, we need to load logger configuration to decide the log level in NewLogger stage, and then SetLogger into grpc core.

What about adding mutex when we call SetLogger? just like zap did.

https://github.com/uber-go/zap/blob/9b86a50a3e27e0e12ccb6b47288de27df7fd3d5b/global.go#L66-L73

**Comment by hnlq715** [comment]
Seems like calling SetLogger before any gRPC functions (after init) would make sense, and this solved my problem, thanks again~
