### ISSUE TITLE
The go program started with systemed reported an error

### ISSUE THREAD

**Issue by lox139** [grpc/grpc-go#5741]
Executing shell script  with exec.Command is an error，this error only occurs when systemed is started，this works fine if you start main directly
Error is as follows：
```
Oct 25 13:38:26 host-172-16-13-238 main: panic: exit status 127
Oct 25 13:38:26 host-172-16-13-238 main: goroutine 35 [running]:
Oct 25 13:38:26 host-172-16-13-238 main: main.(*serverDba).ViewReplStatus(0xc63da0, 0x996540, 0xc0000909f0, 0xc000096480, 0xc63da0, 0xc0000909f0, 0xc000048af0)
Oct 25 13:38:26 host-172-16-13-238 main: /usr/local/src/go/src/mysqlagent/agent_server/main.go:101 +0x205
Oct 25 13:38:26 host-172-16-13-238 main: mysqlagent/dba._ReplMan_ViewReplStatus_Handler(0x893500, 0xc63da0, 0x996540, 0xc0000909f0, 0xc0000c8380, 0x0, 0x996540, 0xc0000909f0, 0x0, 0x0)
Oct 25 13:38:26 host-172-16-13-238 main: /usr/local/src/go/src/mysqlagent/dba/dba_grpc.pb.go:231 +0x214
Oct 25 13:38:26 host-172-16-13-238 main: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001d01e0, 0x99a858, 0xc0001196c0, 0xc0000c4240, 0xc0001d6900, 0xc29170, 0x0, 0x0, 0x0)
Oct 25 13:38:26 host-172-16-13-238 main: /usr/local/src/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:1340 +0x902
Oct 25 13:38:26 host-172-16-13-238 main: google.golang.org/grpc.(*Server).handleStream(0xc0001d01e0, 0x99a858, 0xc0001196c0, 0xc0000c4240, 0x0)
Oct 25 13:38:26 host-172-16-13-238 main: /usr/local/src/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:1713 +0xd0c
Oct 25 13:38:26 host-172-16-13-238 main: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00012ae10, 0xc0001d01e0, 0x99a858, 0xc0001196c0, 0xc0000c4240)
Oct 25 13:38:26 host-172-16-13-238 main: /usr/local/src/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:965 +0xab
Oct 25 13:38:26 host-172-16-13-238 main: created by google.golang.org/grpc.(*Server).serveStreams.func1
Oct 25 13:38:26 host-172-16-13-238 main: /usr/local/src/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:963 +0x1fd
Oct 25 13:38:26 host-172-16-13-238 systemd: mysqlagent1.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 25 13:38:26 host-172-16-13-238 systemd: Unit mysqlagent1.service entered failed state.
Oct 25 13:38:26 host-172-16-13-238 systemd: mysqlagent1.service failed.
Oct 25 13:38:26 host-172-16-13-238 systemd: mysqlagent1.service holdoff time over, scheduling restart.
Oct 25 13:38:26 host-172-16-13-238 systemd: Stopped MySQL Agent.
Oct 25 13:38:26 host-172-16-13-238 systemd: Starting MySQL Agent...
Oct 25 13:38:26 host-172-16-13-238 systemd: Started MySQL Agent.
```
/usr/local/src/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:965  is as follows：
![图片](https://user-images.githubusercontent.com/60485031/197693281-a3ae9b84-7a30-43fb-bb80-a77ef3541d44.png)

**Comment by lox139** [comment]
/usr/local/src/go/src/mysqlagent/agent_server/main.go:101  is as follows：
![图片](https://user-images.githubusercontent.com/60485031/197700240-16839bc7-c037-41d3-b224-a5bacacec2a1.png)

**Comment by dfawley** [comment]
Sorry, I can't follow your setup.

I am not sure why you're pointing to that line in server.go.  It's irrelevant AFAICT as it's just where your process was when the panic occurred.

The reason for the panic seems to be:
```
Oct 25 13:38:26 host-172-16-13-238 systemd: mysqlagent1.service: main process exited, code=exited, status=2/INVALIDARGUMENT
```

Or possibly it's the exit status of 127, which is "command not found" so maybe you just need a full path to your `mysql` binary you are execing.

In any case, it would be unlikely to be a grpc bug if things work when using it directly.

**Comment by lox139** [comment]
> Sorry, I can't follow your setup.
> 
> I am not sure why you're pointing to that line in server.go. It's irrelevant AFAICT as it's just where your process was when the panic occurred.
> 
> The reason for the panic seems to be:
> 
> ```
> Oct 25 13:38:26 host-172-16-13-238 systemd: mysqlagent1.service: main process exited, code=exited, status=2/INVALIDARGUMENT
> ```
> 
> Or possibly it's the exit status of 127, which is "command not found" so maybe you just need a full path to your `mysql` binary you are execing.
> 
> In any case, it would be unlikely to be a grpc bug if things work when using it directly.

It's done. You hit the problem，thks
