### ISSUE TITLE
Is it possible in grpc-go to do - server-side load balancing / Proxy load balancing

### ISSUE THREAD

**Issue by JCzz** [grpc/grpc-go#5742]
I am looking to create a server-side load-balancer, but only client side loadbalancer is shown in [examples][1]

It is mentioned in [grpc.io/blog/grpc-load-balancing][2] as if it is possible?

Do you have any examples, or am I missing something?  

I found [this][3], maybe this is the way to go?      

[1]: https://github.com/grpc/grpc-go/tree/master/examples/features/load_balancing  
[2]: https://grpc.io/blog/grpc-load-balancing/  
[3]: https://github.com/mwitkow/grpc-proxy

**Comment by dfawley** [comment]
Client-side, we provide an API (experimental) to control the routing of RPCs on the client.  It's typically there for either simple load balancing or for a coordinated (server+client / lookaside) load balancing strategies.  E.g. gRPCLB (which is deprecated, but as a concept is a good example) in which the client asks the gRPCLB server for a list of hosts, and the host provides a subset of hosts, which may change over time, that should be used by that client at that time.

If you want to do server-side/proxy load balancing, that can be done without the knowledge of the client at all.  Any L7 HTTP/2 reverse proxy will work.  Many people use nginx, haproxy, grpc-proxy, etc.
