### ISSUE TITLE
Question: does gRPC provides a way of updating per RPC credential of already created connections?

### ISSUE THREAD

**Issue by mitake** [grpc/grpc-go#575]
Hi, I have a question about per RPC credential. Does gRPC provides a way of updating credentials of existing (by grpc.Dial()) connections?

gRPC provides a way of configuring per RPC credentials with `grpc.WithPerRPCCredentials()`. However, it seems that the function cannot be used after creating a connection. Therefore, if we want to assign per RPC credential that is generated by application level authentication mechanism, we need to create 2 connections: first one for obtaining the credential, second one for using the credential. Is this really required?

I'm very new to gRPC so I would be missing something. I'd like to hear your comments on the mechanism, API usage, possible future change, etc.

/cc @xiang90

**Comment by iamqizhao** [comment]
With grpc.WithPerRPCCredentials, it assumes the cred has a way to generate a token for each rpc automatically via GetRequestMetadata(). If this is not the case, you can use metadata API to pass your per-rpc tokens.

**Comment by mitake** [comment]
Thanks for your reply, @iamqizhao . Do you mean gRPC provides APIs for passing per-rpc tokens to existing connections? Could you tell me the names of the APIs?

**Comment by iamqizhao** [comment]
check out the metadata API (https://github.com/grpc/grpc-go/blob/master/metadata/metadata.go).

**Comment by mitake** [comment]
Thanks for your pointer. However, the metadata API would be a thing used from server side. Is there a API that can be used from client side?

**Comment by iamqizhao** [comment]
No, metadata works for both client and server sides. Check out some end2end tests (https://github.com/grpc/grpc-go/blob/master/test/end2end_test.go#L848) as examples.

**Comment by mitake** [comment]
@iamqizhao Thanks, the e2e test file seems to be a good source of example usages. I'm closing this issue because your answers satisfied my question :)
