### ISSUE TITLE
benchmark: make it possible to configure read and write buffer sizes

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5757]
This issues addresses 2-4 from https://github.com/grpc/grpc-go/issues/5751.

Our benchmarks set [server](https://github.com/grpc/grpc-go/blob/040b795b51ea6e3f29ee273acf80505ca495f798/benchmark/benchmark.go#L201) and [client](https://github.com/grpc/grpc-go/blob/040b795b51ea6e3f29ee273acf80505ca495f798/benchmark/benchmark.go#L281) write buffer sizes to 128KB.

- [ ] Do not set the read and write buffer sizes by default. Instead let the benchmark client and server use whatever defaults grpc uses.
- [ ] Provide a command line flag to set these buffer sizes.

**Comment by atollena** [comment]
https://github.com/grpc/grpc-go/pull/5762 for the first item.

**Comment by atollena** [comment]
https://github.com/grpc/grpc-go/pull/5774 -- @easwars I think you can assign this to me, I hope to close this issue with this PR.

**Comment by atollena** [comment]
@dfawley any chance you could have a look at the linked PRs https://github.com/grpc/grpc-go/pull/5762 when you have time? It should be a quick one.

**Comment by atollena** [comment]
I think this can be closed since https://github.com/grpc/grpc-go/pull/5774 is merged.

**Comment by easwars** [comment]
Fixed via https://github.com/grpc/grpc-go/pull/5774.

**Comment by easwars** [comment]
@atollena Thank you very much for your contribution !!
