### ISSUE TITLE
transport: write buffer size should equal the size specified by the user

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5758]
This issues addresses bullet point 1 from https://github.com/grpc/grpc-go/issues/5751.

Write buffer sizes can be configured on the [client](https://pkg.go.dev/google.golang.org/grpc#WithWriteBufferSize) and the [server](https://pkg.go.dev/google.golang.org/grpc#WriteBufferSize). The docstring on these two APIs clearly states:
```
The corresponding memory allocation for this buffer will be twice the size to keep syscalls low.
```

Looking at the [implementation](https://github.com/grpc/grpc-go/blob/0d6481fb85c03d658e45bf3a2f7beb9041ec4549/internal/transport/http_util.go#L320) though, it is not obvious what benefit we get out of configuring a buffer which is twice the size.

Once we have addressed https://github.com/grpc/grpc-go/issues/5757, we can see if there is any change in benchmark results as a result of using a buffer which is the same size as configured by the user.

Another possibly important data point is that the buffer is flushed not only when we have buffered more than the user configured size, but also when the loopy writer decides that it should be flushed. It is important to understand why this is being done. See: https://github.com/grpc/grpc-go/blob/0d6481fb85c03d658e45bf3a2f7beb9041ec4549/internal/transport/controlbuf.go#L575

**Comment by atollena** [comment]
> Another possibly important data point is that the buffer is flushed not only when we have buffered more than the user configured size, but also when the loopy writer decides that it should be flushed. It is important to understand why this is being done.

This call to `Flush()` is necessary to make sure that we eventually write data on the transport when the buffer is not filled entirely. So each time there is data available and loopy runs, it gets a chance to flush the buffer.

**Comment by atollena** [comment]
I summarized the results of my benchmarks alongside a proposed change for this in https://github.com/grpc/grpc-go/pull/5807.

**Comment by atollena** [comment]
This was fixed in https://github.com/grpc/grpc-go/pull/6983.
