### ISSUE TITLE
What's the best usage of server-side keepalive  policy

### ISSUE THREAD

**Issue by kimhongji** [grpc/grpc-go#5764]
## I have a question about keepalive setting in grpc-go, exactly server-side keepalive EnforcementPolicy parameter. 
 https://github.com/grpc/grpc-go/blob/4c776ec01572d55249df309251900554b46adb41/keepalive/keepalive.go#L77-L84

#### Q1.   
Does the word **Stream** in PermitWithout**Stream** mean stream in unary or **stream** as used in grpc?

#### Q2.   
When the PermitWithoutStream value of server is false, If the client sent ping, server directly send goaway? 
-> In my experience,  server did not send goaway directly,  and after 2 pings sent goaway. (It works same when PermitWithoutStream is true or not)

#### Q3.
Where can i find that description or doc about `defaultPingTime`(2 hour) in below code.
https://github.com/grpc/grpc-go/blob/a671967dfbaab779d37fd7e597d9248f13806087/internal/transport/http2_server.go#L822-L832

So, I just want to know what is the right usage and how it works. thanks!

**Comment by easwars** [comment]
> Does the word Stream in PermitWithoutStream mean stream in unary or stream as used in grpc?

Both.

> When the PermitWithoutStream value of server is false, If the client sent ping, server directly send goaway?

The enforcement algorithm allows some leeway for client behavior. The algorithm used is described [here](https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md#server-enforcement). So, it is only when the server receives the third ping within the stipulated amount of time, does it send a GOAWAY.

> Where can i find that description or doc about defaultPingTime(2 hour) in below code.

https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md#server-enforcement


I just realized that dosctrings in the `keepalive` package could do with some improvement. Please let me know if you are interested to improve the documentation. Thanks.

**Comment by kimhongji** [comment]
@easwars thanks for your response! 
your response was so helpful for me. 
But, I have a question to understand exactly about `PermitWithoutStream`.

so, What I understanding is the `PermitWithoutStream` purpose is telling if grpc go uses tcp default timeout or uses keepalive minTime. 

is it right?

**Comment by easwars** [comment]
> so, What I understand is the PermitWithoutStream purpose is telling if grpc go uses tcp default timeout or uses keepalive minTime.

Yes, what you are saying is true on the server.

On the client, the answer is more nuanced. 
The default value for `PermitWithoutStream` is `false`, which means that if there are no outstanding RPCs on the connections, no HTTP/2 keepalive PING frames will be sent. So in this case, broken connections will only be detected when the TCP keepalive kicks in. But if the `PermitWithoutStream` is set to `true`, HTTP/2 keepalive PING frames will be sent even when there are no outstanding RPCs on the connection. This can potentially help with detecting broken connections or the server going down, faster (based on the configured values).

Also, worth remembering the following line from the proposal:
```
client authors must coordinate with service owners for whether a particular client-side
setting is acceptable. Service owners decide what they are willing to support, including
whether they are willing to receive keepalives at all.
```

Hope this helps.

**Comment by kimhongji** [comment]
thanks a lot , for kind response!

so, At last,  I want to suggest something.
how about to develop server's `PermitWithoutStream` docstrings? like below

```
// If true, server allows keepalive pings **during minTime** even when there are no active
// streams(RPCs). If false, and client sends ping when there are no active
// streams, server will send GOAWAY and close the connection.
PermitWithoutStream bool // false by default.
```

Even if it's not exactly same comment, 
I think It would be good to include something like this "when psermitWithoutStream is true, pings are affected kep.minTime"  

I wonder what you think!

ref. https://github.com/grpc/grpc-go/blob/4c776ec01572d55249df309251900554b46adb41/keepalive/keepalive.go#L77-L84

**Comment by easwars** [comment]
Feel free to open a pull request with an improvement to the docstring. We will be happy to review it. Thanks.

I'm closing this issue since we have come to an agreement here.
