### ISSUE TITLE
got error : rpc error: code = Internal desc = failed to fetch creds for cluster, while streaming

### ISSUE THREAD

**Issue by sachinkine** [grpc/grpc-go#5766]
getting this error in grafana and showing no data 
![Screenshot from 2022-11-04 12-29-24](https://user-images.githubusercontent.com/105937957/199911148-b9a6c26d-9adc-4e8c-bd38-4fb50843903c.png)

**Comment by easwars** [comment]
There is very little information in here for the gRPC team to dig deeper and help you out. Unfortunately, the gRPC team is unable to support problems of this nature on Github.  Please isolate the problem more specifically, and if you discover the problem can be attributed to gRPC, ideally demonstrated with a minimal code example, we can reopen the issue and the team will be happy to investigate further. Thanks.
