### ISSUE TITLE
ClientConn close priority problem

### ISSUE THREAD

**Issue by chenjie199234** [grpc/grpc-go#5767]
in ClientConn's Close function
1. wrapper balancer closed first，this will make wrapper balancer's watcher return
2. AddrConn closed after the wrapper balancer，all AddrConn's state update to Shutdown can't pass to the real balancer

my thoughts(maybe wrong):
1. resolver should be closed first, means we don't need new connections.
2. then close the connections we have now.
3. finally close the balancer.
![20221104-193012](https://user-images.githubusercontent.com/29348971/199963685-be9430ba-1c8c-436e-b738-f7cc87d6d368.jpeg)
![20221104-193618](https://user-images.githubusercontent.com/29348971/199963723-1bdfaf23-a7e0-4d76-b29a-383de9c1dde0.jpeg)
![20221104-193705](https://user-images.githubusercontent.com/29348971/199963743-5d7d1750-ce71-4ba7-9f8f-8fef96253231.jpeg)

**Comment by easwars** [comment]
> resolver should be closed first, means we don't need new connections.

While the resolver returns the list of addresses, it does not control when connections are established to those addresses. This is controlled by the load balancer.

> AddrConn closed after the wrapper balancer，all AddrConn's state update to Shutdown can't pass to the real balancer

This is happening when the `ClientConn` is being closed. So, it does not really matter if the load balancer sees the `SubConn` transition to `SHUTDOWN`. In fact, our documentation even says that the load balancer need to worry about closing all connections when it is being shutdown. The `ClientConn` will ensure that all connections are closed.

**Comment by easwars** [comment]
Could you describe the problem that you seeing because of this behavior?

**Comment by chenjie199234** [comment]
@easwars 
there's no problem
I just think,maybe change the close sequence will make it better.
