### ISSUE TITLE
Serving static files with gRPC server with Envoy

### ISSUE THREAD

**Issue by justinyjsong** [grpc/grpc-go#5779]
I have a gRPC server with Envoy (for grpc-JSON transcoding). 

I have been trying to implement get request that displays the html content similar to gin web framework. 

```
router := gin.Default()
router.Static("sample1/", "/css")
```

Is there any workaround with this? 

I basically want to serve all of html files from a single folder where

`localhost:8080/templates/${filename}` displays the file content of `templates/${filename}`.

I want to avoid running another `net/http` or `gin web server` with a different port and stick to using one port with gRPC server port.

**Comment by zasweq** [comment]
Taking a look at this issue, yeah grpc-gateway seems to be the best bet for you. Also, could you please describe what "gRPC server with Envoy" means? I'm having trouble piecing that architecturally in my head.

**Comment by justinyjsong** [comment]
nvm, closing this as issue resolved using hybrid solution. gRPC server with Envoy just means BE implementation is in gRPC-golang. and we have a proxy server for Envoy.
