### ISSUE TITLE
dependency on github.com/golang/protobuf should be optional

### ISSUE THREAD

**Issue by tamird** [grpc/grpc-go#578]
Many applications use https://github.com/gogo/protobuf for the extra performance and code generation options. It should be possible to avoid a dependency on golang/protobuf.

**Comment by iamqizhao** [comment]
We do need to provide a default codec using golang/protobuf for most of users who do not use custom codec and IDL. Any issue here? I do not see any circular deps issue here.

**Comment by tamird** [comment]
Yeah, there is no circular dep, but it's odd for a project to import both gogo/protobuf and golang/protobuf.

This is low priority, but deserves to be tracked.

**Comment by iamqizhao** [comment]
Personally I do not think it is an issue and there won't be any actions on this.

**Comment by dfawley** [comment]
We can't remove this dependency without breaking backward compatibility, so we have to wait until v2 (for which we have no plans at this time).
