### ISSUE TITLE
Flaky test: ServerRPCEventsLogAll

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5785]
https://github.com/grpc/grpc-go/actions/runs/3424613723/jobs/5704480203

**Comment by zasweq** [comment]
Strange.

**Comment by arvindbr8** [comment]
Doesn't flake when trying to repro in google3: http://sponge2/ee9eaea1-e6b6-4e86-8d76-4171911342b6

**Comment by easwars** [comment]
Still happens: https://github.com/grpc/grpc-go/actions/runs/4058467872/jobs/6985428070
