### ISSUE TITLE
WithUserAgent option does not override the agent as expected.

### ISSUE THREAD

**Issue by VovkoO** [grpc/grpc-go#5789]
### What version of gRPC are you using?

v1.50.1

### What version of Go are you using (`go version`)?

1.18.2

### What operating system (Linux, Windows, …) and version?

macOS

### What did you do?

I used the WithUserAgent("my-user-agent") function to override User-Agent.

### What did you expect to see?

I expected, that my User-Agent will be "my-user-agent"

### What did you see instead?

I saw, that my new User-Agent is "my-user-agent grpc-go/1.50.1" instead just "my-user-agent"

I don't understand why this line https://github.com/grpc/grpc-go/blob/master/clientconn.go#L212 will redeclare my User-Agent, its rather unobvious.

**Comment by zasweq** [comment]
This is WAI (working as intended). As per https://grpc.github.io/grpc/core/md_doc__p_r_o_t_o_c_o_l-_h_t_t_p2.html, "it is recommended that clients provide a structured user-agent string that provides a basic description of the calling library, version & platform to facilitate issue diagnosis in heterogeneous environments."

**Comment by VovkoO** [comment]
Thanks for the reply. I see that this is recommended, but it would be cool if there was a way to completely override the user-agent. Otherwise, it may interfere in some situations, for example, anti-bot systems can easily block requests for non-compliance with the desired user-agent
