### ISSUE TITLE
Server Compression Asymmetry

### ISSUE THREAD

**Issue by hshamji** [grpc/grpc-go#5792]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?
This grpc compression document describes [compression asymmetry](https://github.com/grpc/grpc/blob/master/doc/compression.md#compression-method-asymmetry-between-peers). When attempting to set `grpc-encoding` in the response metadata, I found the header not getting propagated since it is [reserved](https://github.com/grpc/grpc-go/blob/master/internal/transport/http_util.go#L94). This behavior is [confirmed here](https://github.com/grpc/grpc-go/blob/56ac86fa0f39/Documentation/compression.md#compression), excerpting:
>> Server-side, registered compressors will be used automatically to decode request messages and encode the responses. Servers currently always respond using the same compression method specified by the client.

It would be great to have functionality to vary the request vs. response compression for a server.

For more detail, I'm proxying compressed requests (without decompressing/recompressing) to backends that themselves provide asymmetric request-responses.

### Proposed Solution
Allow for manual setting of `grpc-encoding` (and possibly other) headers to allow for explicit control over request/response encoding.

**Comment by hshamji** [comment]
Would be happy to work on this if it is deemed worthwhile/appropriate. And if so, any pointers, suggestions, edge-cases would also be most welcome.

**Comment by dfawley** [comment]
#5744 may add exactly what you want here.

**Comment by hshamji** [comment]
@dfawley that's it! What timing! TY TY
