### ISSUE TITLE
Cleanup usages of resolver.Target.Authority

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5795]
`resolver.Target.Authority` is marked as deprecated, and we added `resolver.Target.URL` which is the more preferred way of getting to the details of the parsed target.

Codebase needs to be inspected for usages of `resolver.Target.Authority` and replaced with `resolver.Target.URL.Host`.

**Comment by ramil600** [comment]
I will start working, if no one took it yet

**Comment by ramil600** [comment]
I worked on cleaning up some tests: submitted PR  #5858

**Comment by ginayeh** [comment]
According to #5754, #5761 should close this issue, so marking this as closed.
