### ISSUE TITLE
Go build failed on the master branch

### ISSUE THREAD

**Issue by shafreeck** [grpc/grpc-go#581]
When I update to the latest commit , go build failed with errors 
```
# google.golang.org/grpc/transport
transport/handler_server.go:203: undefined: http2.TrailerPrefix
transport/http2_client.go:678: undefined: http2.MetaHeadersFrame
transport/http2_client.go:750: undefined: http2.MetaHeadersFrame
transport/http2_server.go:140: undefined: http2.MetaHeadersFrame
transport/http2_server.go:253: undefined: http2.MetaHeadersFrame
transport/http_util.go:279: f.fr.ReadMetaHeaders undefined (type *http2.Framer has no field or method ReadMetaHeaders)
```

BTW: Do you have any plan to release a stable version ?

**Comment by iamqizhao** [comment]
please rerun go get -u google.golang.org/grpc to get the latest updates in http2 package.

**Comment by shafreeck** [comment]
OK , It works. Thanks  !

**Comment by let4be** [comment]
same issue, `go get -u google.golang.org/grpc` doesn't help

**Comment by iamqizhao** [comment]
What go version do u use?

**Comment by let4be** [comment]
go 1.6 linux

**Comment by treeder** [comment]
Does this depend on Go 1.7 now or something? Updating doesn't help because it's still using MetaHeadersFrame: https://github.com/grpc/grpc-go/blob/35896af9ad39c1fb1b1cd925fe3621be361e3d81/transport/http2_client.go#L814

**Comment by tamird** [comment]
What's the issue with `MetaHeadersFrame`? No, grpc does not depend on 1.7.

Have you tried `go get -u google.golang.org/grpc/...`?

**Comment by treeder** [comment]
Turns out I had to update `golang.org/x/net` (I think), then it built.

**Comment by chamilad** [comment]
I came across this error on `go1.6.2 linux/amd64` on Ubuntu 16.04. Here's how I got it fixed, if someone comes across this issue after googling. 

I tried `go get -u google.golang.org/grpc`. It didn't work because `golang.org/x/net` had uncommitted changes. `git checkout -- .` inside `golang.org/x/net` and repeated `go get -u google.golang.org/grpc`. This fixed it.

**Comment by sagikazarmark** [comment]
Don't know why, but when using Glide, I had to manually update the lock file to use the latest commit. Even when I removed the lock file, it resolved the wrong commit hash. Subsequent `glide up`s work though, it does not touch the (correct) commit hash.

**Comment by ypapax** [comment]
```
cd $GOPATH/src/golang.org/x/net/http2
```
and
```
git checkout master 
```
helped me.

The head was detached there for some reason:
```
$ git status
HEAD detached at f09c466
nothing to commit, working directory clean
```

**Comment by timakin** [comment]
In my case, library cache remains on glide project directory.
So I had to clean cache with `glide cc` before I entered `glide up` .

**Comment by KeKe-Li** [comment]
[keke@localhost etcd]$ go build
# google.golang.org/grpc/transport
../google.golang.org/grpc/transport/handler_server.go:220: undefined: http2.TrailerPrefix
../google.golang.org/grpc/transport/http2_client.go:1070: undefined: http2.MetaHeadersFrame
../google.golang.org/grpc/transport/http2_client.go:1191: undefined: http2.MetaHeadersFrame
../google.golang.org/grpc/transport/http2_server.go:232: undefined: http2.MetaHeadersFrame
../google.golang.org/grpc/transport/http2_server.go:404: undefined: http2.MetaHeadersFrame
../google.golang.org/grpc/transport/http_util.go:200: undefined: http2.MetaHeadersFrame
../google.golang.org/grpc/transport/http_util.go:465: f.fr.SetReuseFrames undefined (type *http2.Framer has no field or method SetReuseFrames)
../google.golang.org/grpc/transport/http_util.go:466: f.fr.ReadMetaHeaders undefined (type *http2.Framer has no field or method ReadMetaHeaders)
../google.golang.org/grpc/transport/http_util.go:596: f.fr.ErrorDetail undefined (type *http2.Framer has no field or method ErrorDetail)

**Comment by dfawley** [comment]
@KeKe-Li did you `go get -u google.golang.org/grpc`?

If so, try to repro with a clean GOPATH.  The [build is green](https://travis-ci.org/grpc/grpc-go), so there must be something wrong with your environment.

**Comment by KeKe-Li** [comment]
okI <http://cn.bing.com/dict/search?q=I&FORM=BDVSP6&mkt=zh-cn>'m
<http://cn.bing.com/dict/search?q=%27m&FORM=BDVSP6&mkt=zh-cn> try
<http://cn.bing.com/dict/search?q=try&FORM=BDVSP6&mkt=zh-cn> again
<http://cn.bing.com/dict/search?q=again&FORM=BDVSP6&mkt=zh-cn> ,thank you !

2017-08-25 0:18 GMT+08:00 dfawley <notifications@github.com>:
