### ISSUE TITLE
How to handle stats.End event on the client side if stats.OutHeader was not even reached.

### ISSUE THREAD

**Issue by piotrkowalczuk** [grpc/grpc-go#5823]
As of today [promgrpc](https://github.com/piotrkowalczuk/promgrpc) rely on metadata available in `stats.OutHeader` to enrich metrics with `user-agent` information. On the client side it is problematic because request might end before `stats.OutHeader` fires. As a result metric that describe in-flight requests tend to go bellow zero. 

`min(sum(grpc_client_requests_in_flight{app=~"$app"}) by (instance))`:

<img width="1736" alt="image" src="https://user-images.githubusercontent.com/2438924/204620611-7a042835-c985-455e-b104-855859e461dc.png">

StatHandler implemented based on changes merged in https://github.com/grpc/grpc-go/pull/3331

```go
// HandleRPC processes the RPC stats.
func (h *ClientRequestsInFlightStatsHandler) HandleRPC(ctx context.Context, stat stats.RPCStats) {
	switch stat.(type) {
	case *stats.OutHeader:
		switch {
		case stat.IsClient():
			h.vec.WithLabelValues(h.options.handleRPCLabelFn(ctx, stat)...).Inc()
		}
	case *stats.End:
		switch {
		case stat.IsClient():
			h.vec.WithLabelValues(h.options.handleRPCLabelFn(ctx, stat)...).Dec()
		}
	}
}
```

Is it feasible to extend `stats.End` switch-case to avoid calling `Dec` if `stats.OutHeader` was never reached? Preferably in a way so that it will not break with future releases. If not, do you have suggestions, what would be the best way to adapt the `grpc` code to solve my problem?

**Comment by arvindbr8** [comment]
Hi @piotrkowalczuk 
gRPC calls TagRPC at the start of the RPC. gRPC also calls HandleRPC when the headers are sent. Now `HandleRPC` is called using the context sent by TagRPC. You can get the context info in HandleRPC using `context.Value()` and `TagRPC` sets the value using `context.withValue()` and returns the resulting context. 

Per best practice, 
+ `HandleRPC(ctx, OutHeader{})` could reach into the context and add something indicating it happened
+ `HandleRPC(ctx, End{})` could also reach into it and see it (or not) and behave accordingly. 

You could also consider looking into the [opencensus repo](https://github.com/census-instrumentation/opencensus-go/tree/v0.24.0/plugin/ocgrpc) for usage examples. 

let us know if this helps.

**Comment by piotrkowalczuk** [comment]
That's the thing. `user-agent` is not available at `TagRPC`. It is only available just before `HandleRPC.OutHeader` as implemented here https://github.com/grpc/grpc-go/pull/3331.

**Comment by arvindbr8** [comment]
Trying to understand the use case here. Why do we need `user-agent` data here? Are we trying to emit metrics per `user-agent` for inflight requests?
