### ISSUE TITLE
how to know client close channel in server side

### ISSUE THREAD

**Issue by sodaRyCN** [grpc/grpc-go#5835]
I build a gateway base on `UnknownServiceHandler` which supports grpc protocol [5388](https://github.com/grpc/grpc-go/issues/5388) . In some scenarios, I expect the gateway to actively disconnect from the server when the client close the channel from the gateway, but I haven't found a way to get the underlying connection status, because they seem to be encapsulated in the internal package.

**Comment by arvindbr8** [comment]
Hi @sodaRyCN, 

I'm trying to understand this a little better. Do you want to be able to close the connection from the gateway to the server, when the client disconnects from the gateway? Or are there additional connection status updates that needs to be sent?

**Comment by sodaRyCN** [comment]
> closing the connection from the gateway to the server when the client disconnects from the gateway 

that is currently sufficient for me.

To be clear, the scenario I have encountered is that the client and server use streams, and then the client calls clientStream.closeSend and clientConn.close in turn. The UnknowServiceHandler of the gateway can refer to the following code,
obviously, when clientStream.CloseSend is called, func UnknowServiceHandler will return, so it is impossible to know that the client will close the connection later
```
func UnknowServiceHandler(srv interface{}, grpc.ServerStream) {
        grpc.ClientStream := buildClinetStream(grpc.ServerStream)
        c2sErrChan := forwardClientToServer(grpc.ServerStream, grpc.ClientStream)
        s2cErrChan := forwardServerToClient(grpc.ClientStream, grpc.ServerStream)
        for i := 0; i < 2; i++ {
                select {
                case c2sErr := <-c2sErrChan:
                        if c2sErr == io.EOF {
                                proxyAsClientStream.CloseSend()
                        } else {
                                return c2sErr
                        }
                case s2cErr := <-s2cErrChan:
                        if s2cErr != io.EOF {
                                return s2cErr
                        }
                        return nil
                }
        }
}

func  forwardServerToClient(src grpc.ClientStream, dst grpc.ServerStream) chan error {
        ret := make(chan error, 1)
        go func() {
                f := &emptypb.Empty{}
                for {
                        if err := src.RecvMsg(f); err != nil {
                                ret <- err // this can be io.EOF which is happy case
                                break
                        }
                        if err := dst.SendMsg(f); err != nil {
                                ret <- err
                                break
                        }
                }
        }()
        return ret
}

func forwardClientToServer(src grpc.ServerStream, dst grpc.ClientStream) chan error {
        ret := make(chan error, 1)
        go func() {
                f := &emptypb.Empty{}
                for  {
                        if err := src.RecvMsg(f); err != nil {
                                ret <- err
                                break
                        }
                        if err := dst.SendMsg(f); err != nil {
                                ret <- err
                                break
                        }
                }
        }()
        return ret
}
```
Of course, if the client only calls clientConn.close instead of clientStream.closeSend in this scenario, the gateway will receive an error cotenxt canceled. It would be great if grpc.Server could consider implementing a capability like this `https://github.com/alibaba/nacos/blob/a7a5ced21af2b51d7eb1544ec78fd2c66e3be16b/core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java#L116`

**Comment by sodaRyCN** [comment]
clarified

**Comment by easwars** [comment]
The `ServerStream` passed to the `UnknownServiceHandler` contains a `Context()` method to retrieve the stream context. Please see [here](https://pkg.go.dev/google.golang.org/grpc#ServerStream). Your code on the gateway should also take into account, cancellation of this context, while determining client termination.

When the client closes its connection, the context on the `ServerStream` will be cancelled. The context will also be cancelled when the deadline associated with the RPC expires. If you also want to handle cases where the client abnormally dies, and you want to detect that case on the server, you could consider using grpc [keepalive](https://github.com/grpc/grpc-go/blob/master/examples/features/keepalive/README.md) support.

**Comment by sodaRyCN** [comment]
As mentioned above, if the client calls the ClientStream.CloseSend method first, then the Unknownhandler will complete the execution and return. At this time, even if the client calls the Client.Close method, I cannot get the ServerStream.Context.

**Comment by easwars** [comment]
My suggestion was that the context from the `grpc.ServerStream` passed to `Unknownhandler` should be passed to both your forwarding functions. And those functions should be watching the context in their `select` and should take appropriate action when they see the context being closed.

**Comment by sodaRyCN** [comment]
do u mind show me a simple example code?

**Comment by sodaRyCN** [comment]
clarified

**Comment by zasweq** [comment]
Sounds like you worked it out, let us know if you need something else.
