### ISSUE TITLE
go grpc server returns RST_STREAM with ErrCode=PROTOCOL_ERROR

### ISSUE THREAD

**Issue by VoxT** [grpc/grpc-go#5841]
### What version of gRPC are you using?
v1.51.0

### What version of Go are you using (`go version`)?
go1.18.1 linux/amd64

### What operating system (Linux, Windows, …) and version?
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### What did you do?
Android application using `grpc-java-okhttp/1.51.0` as a client to call go grpc server. From the beginning the request/response is normal, but after a while, the server returns RST_STREAM with ErrCode=PROTOCOL_ERROR for the rest of the unary request

Enable debuglog:
```
Environment="GRPC_GO_LOG_VERBOSITY_LEVEL=99"
Environment="GRPC_GO_LOG_SEVERITY_LEVEL=info"
Environment="GODEBUG=http2debug=2"
```

We have this log: 
[debug-android.log](https://github.com/grpc/grpc-go/files/10150720/debug-android.log)

Using Wireshark to capture the network, for the error one we have these frame:
[rst.txt](https://github.com/grpc/grpc-go/files/10150765/rst.txt)

### What did you expect to see?
Unary request successful

### What did you see instead?
RST_STREAM with ErrCode=PROTOCOL_ERROR

**Comment by arvindbr8** [comment]
Thanks @VoxT for filing this. Need to take a deeper look at what's going on. It seems like the stream ctx is being canceled based on the timeout set from client header value. 

Could you however help clarify one thing? The `debug-android.log` file, is that server-side or client-side logs? To me it seems like gRPC-Go logs so im assuming it could be server.

**Comment by VoxT** [comment]
TLS resolved this problem.
Certainly, the problem was the plaintext frames were dropped by some ADSL policies.
I am closing this issue now.
