### ISSUE TITLE
Does MaxCallRecvMsgSize support unlimited bytes

### ISSUE THREAD

**Issue by garima-n** [grpc/grpc-go#5842]
Does MaxCallRecvMsgSize support unlimited bytes?
In C# , -1 means unlimited bytes. How to achieve same in Go?
`"grpc.max_receive_message_length": -1 `

**Comment by arvindbr8** [comment]
Hi @garima-n,

Currently there is no way to specify support for unlimited bytes in gRPC-Go. However, there is a 2GB limit on the bytes that can be sent in a protobuf (check the reference card [here](https://developers.google.com/protocol-buffers/docs/encoding)). `MaxCallRecvMsgSize` currently is of type int and if you are running on a 64BIT machine you could potentially set it to a large enough value. 

Hope this clarifies your question. let us know :)
