### ISSUE TITLE
Configurable backoff strategies

### ISSUE THREAD

**Issue by stevvooe** [grpc/grpc-go#585]
After experimenting with connection and failure recovery, I've found the current backoff strategy slightly aggressive for certain applications. Under a total service failure with extended downtime, recovery can take several minutes waiting for backoff to retry and come back up. This is even more problematic when a running service may have several instances coming up in a random order, causing more delay under failure.

Rather than bikeshed the backoff algorithm, it seems most reasonable to provide a client option, `WithBackoff`, that would let one configure the delay time as a function of the number of retries. The options full signature would be as follows:

```go
func WithBackoff(strategy BackoffStrategy) DialOption
```

We'd also define the type `BackoffStrategy`, with the following signature:

```go
type BackoffStrategy interface {
    Backoff(retries int) time.Duration
}
```

A base implementation, exposing configuration of backoff parameters, could be as follows, cribbed from https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L414:

```go
type BackoffConfig {
    BaseDelay time.Duration
    MaxDelay time.Duration
    Factor float64
    Jitter float64
}

func (bc *BackconfConfig) Backoff(retries int) time.Duration { /*...*/ }

var DefaultBackoff = BackoffConfig{
    BaseDelay: time.Second,
    MaxDelay: 120 *time.Second,
    Factor: 1.6,
    Jitter: 0.2,
}

opt := WithBackoff(DefaultBackoff)
```

Another use case for this would be a schedule reconnect time for deterministic, planned downtime, which might look like this:

```go
type ScheduledBackoff struct {
    // after sets the time when connections should be retried.
    after time.Time
    mu sync.Mutex
}

func (sb *ScheduledBackoff) Set(after time.Time) {
    sb.mu.Lock()
    defer sb.mu.Unlock()
    sb.after = after
}

func (sb *ScheduledBackoff) Backoff(retries int) time.Duration {
    sb.mu.Lock()
    defer sb.mu.Unlock()

    wait := time.after.Sub(time.Now())
    if wait < 0 {
        return 0
    }

    return wait
}
```

In this example, we have an application defined backoff strategy that could be set elsewhere to allow reconnection after a certain time. Obviously the above isn't complete for a production implementation, but I hope you could see the utility. This could also be used to implemented circuit breakers or other strategies controlling reconnection of services.

If this sounds like a reasonable proposal, I can submit a PR with the core functionality.

**Comment by iamqizhao** [comment]
Please move this proposal to grpc/grpc repo. This needs to be consistent across languages.

**Comment by stevvooe** [comment]
@iamqizhao Would this be a proposal to change this document https://github.com/grpc/grpc/blob/e1d8d4dc1bdf54273b7ed9d4a495789430cbdf6c/doc/connection-backoff.md? What is the goal of having common backoff strategies across languages?

The current behavior is problematic, so I'd like to avoid a lengthy multi-language review. 120 seconds is just too long.

**Comment by makdharma** [comment]
Hi Stephen, Please take a look at https://github.com/grpc/grpc/issues/5377,
and associated pull request in the bug. Does this satisfy your requirements?

**Comment by stevvooe** [comment]
@makdharma Thanks for the response! That should get us off the ground. 

Although, it would be ideal to remove the lower bound on selecting the next deadline. This allows reconnection to be more evenly spread across the wait period. Other strategies might be better in certain conditions. For example, [Exponential Backoff](https://en.wikipedia.org/wiki/Exponential_backoff#Expected_backoff) has the nice property that one can set the expected wait time for reconnection based on the number of retries. In practice, it means that after fault recovery, the spread of reconnections is uniformly spread across the next retry period. The current approach tends to have clients all recover in the same jitter window, meaning at the worst case, clients that fail right before recovery have to wait the entire window before trying again.

I can submit a PR similar to the approach above but with `backoffStrategy` un-exported, if that will be accepted. It would be good to understand the intent on having all language clients implement similar strategies before submitting a proprosal in grpc/grpc.

**Comment by zellyn** [comment]
+1 although I'd pass a `func(int) time.Duration` rather than an interface.

**Comment by stevvooe** [comment]
@zellyn We could define a `BackoffFunc`, which implements `BackoffStrategy`:

```go
type BackoffFunc func(int) time.Duration
func (fn BackoffFunc) Backoff(retries int) time.Duration { return fn(retries) }
```

That would provide a shortcut for the common case and avoid having to pass method values when more structure is required.

This is probably academic until I get a response to my comment above.

**Comment by makdharma** [comment]
Hi Stephen - Would you be willing to submit a PR that just implements the
functionality in https://github.com/grpc/grpc/issues/5377 in grpc-go,
followed by a separate PR that implements a BackoffStrategy? That will
minimize the divergence as we come close to GA.

**Comment by iamqizhao** [comment]
grpc/grpc#5377 seems only target max backoff delay. If we add a dedicated API for it, it may be problematic because later ppl might want to tune other params of the backoff mechanism and then we have add additional API which is not necessary. The API to be added should be generic enough to allow tuneup of all the relevant params of the mechanism.

@stevvooe Feel free to send me the PR and in the meanwhile I will poke around other languages to see if they are willing to take the same change. Thanks.

**Comment by stevvooe** [comment]
@iamqizhao Will do. I'll probably be able to do this next week.

(Just found this message un-posted, sorry about delay).

**Comment by stevvooe** [comment]
@iamqizhao A WIP PR has been submitted as #601.

**Comment by stevvooe** [comment]
@iamqizhao Thanks for your help getting this through!
