### ISSUE TITLE
grpc dial option `keepAlive` param cause build method of Builder interface called  for client load balance policy

### ISSUE THREAD

**Issue by fengyeall111** [grpc/grpc-go#5864]
When using client load balance policy, we need achieve Reslover, Builder and Picker interface。However，grpc.dail method with   dial option `keepAlive` param  would call Build method of Builder .Why?  This method should  be called  only endpoints update???
```
	conn, err := grpc.DialContext(
		ctx,
		addr, 
		grpc.WithDefaultServiceConfig(fmt.Sprintf(`{"LoadBalancingPolicy": "%s"}`, rpc.ChatConsistentName)), 
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithBlock(),
		grpc.WithKeepaliveParams(...)
	)
```

**Comment by dfawley** [comment]
I don't fully understand your question.  Could you please explain this more?  How is keepalive related?

Also note that "LoadBalancingPolicy" in ServiceConfig is deprecated.  The preferred field is "loadBalancingConfig" as documented by [gRFC A24](https://github.com/grpc/proposal/blob/master/A24-lb-policy-config.md) and shown in some [examples](https://github.com/grpc/grpc-go/blob/master/examples/features/load_balancing/client/main.go#L77).

Also I don't usually recommend using `WithBlock`, either.  The first RPCs will wait for a connection anyway.

**Comment by fengyeall111** [comment]
> I don't fully understand your question. Could you please explain this more? How is keepalive related?
> 
> Also note that "LoadBalancingPolicy" in ServiceConfig is deprecated. The preferred field is "loadBalancingConfig" as documented by [gRFC A24](https://github.com/grpc/proposal/blob/master/A24-lb-policy-config.md) and shown in some [examples](https://github.com/grpc/grpc-go/blob/master/examples/features/load_balancing/client/main.go#L77).
> 
> Also I don't usually recommend using `WithBlock`, either. The first RPCs will wait for a connection anyway.

grpc client load balance policy  needs  achieve three interface:
```
// dnsresolver

type V2PickerBuilder interface {
    Build(info PickerBuildInfo) balancer.V2Picker
}
type V2Picker interface {
    Pick(info PickInfo) (PickResult, error)
}
```
client dial like this:
```
conn, err := grpc.DialContext(
		ctx,
		addr, 
		grpc.WithDefaultServiceConfig(fmt.Sprintf(`{"LoadBalancingPolicy": "%s"}`, "testBalance")), 
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithBlock(),
		grpc.WithKeepaliveParams(keepalive.ClientParameters{
			Time:                60 * time.Second,
			Timeout:             2 * time.Second,
			PermitWithoutStream: false, 
		}
	)
```
We find grpc conn with keepalive.ClientParameters usually calls  Build method of V2PickerBuilder. why not only  endpoints  that dnsresolver notify changed event?

**Comment by dfawley** [comment]
I don't see how keepalive is involved at all.

What version of gRPC are you using?  V2PickerBuilder only existed for a short amount of time.  It's just "PickerBuilder" now.

PickerBuilder should only be called when the resolver produces addresses.

I'm not sure I can recommend using the `balancer/base` package, either.  It's better IMO to implement the whole `balancer` API from scratch as it gives you much more control and is not significantly more work.
