### ISSUE TITLE
how compatible NewXDSResolverWithConfigForTesting

### ISSUE THREAD

**Issue by baerwang** [grpc/grpc-go#5880]
v1.48.0 version

**Comment by easwars** [comment]
Can you please describe your question in more detail? There is no way we can help you with the amount of information you have provided so far.

**Comment by baerwang** [comment]
On the pixiu repo, we added xds based on the **v.1.47** version. For various reasons, we need to upgrade the grpc version. This **v1.48** version does not have this function. How do I want to use this **NewXDSResolverWithConfigForTesting**, compatible status quo

**Comment by easwars** [comment]
We added that function back. It should be available if you upgrade to v1.49 or higher.

Also, please note that this function is intended only for testing purposes, and we might remove it at any point in the future.

**Comment by baerwang** [comment]
thx
