### ISSUE TITLE
random balancer

### ISSUE THREAD

**Issue by pirDOL** [grpc/grpc-go#5907]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?
I've a lot of clients which will connect a small number of servers to long polling some data periodically.
So it's important that each server should bear as equal connections as possible.

### Proposed Solution
In this scenario, a random balancer is an easy solution to think about.
Althrough grpc-go supports to regist customized balancer, but because random balancer is so common that I created this issue to discuss whether it's possible to add a grpc-go/balancer/random just like roundroubin etc.

p.s. I also found that pickfirst balancer is in grpc-go/pickfirst.go but not in grpc-go/balancer. I'd like to know why all balancer implentations are not in a same directory and whether it's possible to move pickfirst.go to grpc-go/balancer which makes balancers of grpc-go organized.

### Alternatives Considered
NA

### Additional Context
NA

**Comment by arvindbr8** [comment]
Hello @pirDOL 

At the moment, we do not have other asks for a random balancer at the moment. But we could definitely assist you in building your own custom implementation. If it helps, you can refer to the example [here](https://github.com/grpc/grpc-go/tree/master/examples/features/load_balancing).
