### ISSUE TITLE
Metadata validation problem

### ISSUE THREAD

**Issue by ktalg** [grpc/grpc-go#5913]
### What version of gRPC are you using?
v1.51.0
### What version of Go are you using (`go version`)?
go version go1.19.2
### What operating system (Linux, Windows, …) and version?
Linux
### What did you do?
On client side
1. setting a header which key is ""(empty string).
```go
ctx := metadata.NewOutgoingContext(context.Background(), metadata.Pairs("", "value"))
```
2. setting a invalid header using `metadata.AppendToOutgoingContext` instead of `metadata.NewOutgoingContext`
```go
ctx = metadata.AppendToOutgoingContext(ctx, "invalid/key", "bb")
```
### What did you expect to see?
1. an error should be returned
2. metadata set using either `AppendToOutgoingContext` or `NewOutgoingContext` should be verified and an error should be returned when the data is illegal
### What did you see instead?
1. validation is not working and there's a panic
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
google.golang.org/grpc/internal/metadata.Validate(0x9808a0?)
<GOPATH>/sdk/gopath/pkg/mod/google.golang.org/grpc@v1.51.0/internal/metadata/metadata.go:88 +0x22e
google.golang.org/grpc.newClientStream({0x9808a0, 0xc000114660}, 0xc6c040, 0xc00011c000, {0x8d97d1, 0x23}, {0x0, 0x0, 0x0})
<GOPATH>/sdk/gopath/pkg/mod/google.golang.org/grpc@v1.51.0/stream.go:172 +0xa5
google.golang.org/grpc.invoke({0x9808a0?, 0xc000114660?}, {0x8d97d1?, 0x18?}, {0x869220, 0xc000114690}, {0x869220, 0xc0001146c0}, 0x0?, {0x0, ...})
<GOPATH>/sdk/gopath/pkg/mod/google.golang.org/grpc@v1.51.0/call.go:66 +0x7d
google.golang.org/grpc.(*ClientConn).Invoke(0x7f7bb46b65b8?, {0x9808a0?, 0xc000114660?}, {0x8d97d1?, 0x0?}, {0x869220?, 0xc000114690?}, {0x869220?, 0xc0001146c0?}, {0x0, ...})
<GOPATH>/sdk/gopath/pkg/mod/google.golang.org/grpc@v1.51.0/call.go:37 +0x265
...

```
https://github.com/grpc/grpc-go/blob/f2fbb0e07ebf3dd46aa641ee89c9f17e8083eaf6/internal/metadata/metadata.go#L88
Here there is a lack of verification of the input parameters

2. The md validation method is bypassed when using `metadata.AppendToOutgoingContext`
```
rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR
```
and it looks like the problem is here
https://github.com/grpc/grpc-go/blob/f2fbb0e07ebf3dd46aa641ee89c9f17e8083eaf6/stream.go#L171-L175
the metadata added using append is ignored

If these issues are confirmed as bugs, I'd be happy to fix them.

**Comment by dfawley** [comment]
@ktalg - just to clarify, are you planning on working on this?

Thanks!

**Comment by ktalg** [comment]
> @ktalg - just to clarify, are you planning on working on this?
> 
> Thanks!

Absolutely. Sorry for not following up as I've been quite busy lately, but I'll get it done in the next couple of days
