### ISSUE TITLE
`rpcError` should implement `net.Error`

### ISSUE THREAD

**Issue by vieux** [grpc/grpc-go#592]
I wish [`rpcError`](https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L322) should implement [`net.Error`](https://golang.org/pkg/net/#Error) so it would be much easier to detect timeout and act accordingly.

/cc @stevvooe

**Comment by iamqizhao** [comment]
rpcError is typically the error status of a particular rpc. But net.Error usually indicates the connection level error. They are on different levels of concepts. You do need to use the error code to detect timeout of an RPC. I am thinking making transport.ConnectionError implements net.Error though.

**Comment by stevvooe** [comment]
@iamqizhao Maybe it would be good to add to this issue so that we can get back errors from rpc calls to detect timeout rather than just insta-closing the issue. With the way things are now, we cannot tell the difference between a timeout and a remote error.
