### ISSUE TITLE
Question about XDS Hashing behaviour

### ISSUE THREAD

**Issue by k-raval** [grpc/grpc-go#5933]
Hi,

I have a set of GRPC servers, lets name them S1, S2, S3. And a set of GRPC clients, lets name them C1, C2, C3. When a client sends something towards servers, we use the GRPC-XDS to do hashing on a GRPC metadata (using trafficPolicy - LoadBalancer - consistentHash of Istio destination rule). 

The metadata field on which we hash is a unique value mapping to one particular item. E.g. ItemA, ItemB and ItemC have 3 different unique values. My design is such that each item is being served by one particular server (either S1 or S2 or S3). My requirement is that when any client (whether C1 or C2 or C3) sends a message for a given item, because of hashing algo on a unique value corresponding to that item, they would end up selecting the same server. Idea is that client need not maintain the mapping of items to servers even though in the backend, we would like stickiness of item to a server as long as possible until there is change of hashing due to some event. 

e.g. ItemA being served by S1.   When C1 sends msg for itemA, it will include unique value X1 as metadata for hashing, which the hashing logic would route to S1. At the same time if C2 sends msg for itemA using the same unique value X1 as metadata for hashing then, it should also end up getting routed to S1. If S1 is no longer available, the hashing logic would start routing the itemA towards S2 or S3, one of them. That is fine. But now, all the clients independently should route the message for itemA towards the same new server. The client can also go down and come back up again and the same behaviour should continue.

I would like the opinion of the experts on whether GRPC XDS hashing support this kind of behaviour ? Do you see it deviating for any particular scenario ?

Thanks in advance.

**Comment by k-raval** [comment]
@easwars  - can you please throw some light on this..  thanks.

**Comment by easwars** [comment]
I'm not very familiar with the consistentHash rule in Istio that you are talking about. But in general, gRPC's `ring_hash` LB policy should work similar to what you have described.

This section has more details about what is supported in gRPC: https://github.com/grpc/proposal/blob/master/A42-xds-ring-hash-lb-policy.md#xds-api-fields

If you can let us know more information about how the Istio rule translates to xDS messages, we might be able to give me a better answer.

**Comment by k-raval** [comment]
Thanks for your response. 

This question is about ring hash behaviour. The Istio consistentHash policy translates to ring hash behaviour of GRPC XDS. More specifically, the question is about two different client programs running ring hash algorithm selecting the same target server based on the hashing on a given unique input value. Is there possibility that the way ring hash has organized the target server pool is different in two programs and hence for the same input, the chosen target could differ ? My requirement is that both clients always select same target server based on same input value to ring hash.

**Comment by k-raval** [comment]
Hi @easwars - updated with my answer. awaiting your comments. thanks.

**Comment by easwars** [comment]
gRPC supports two types of hashing:
- based on request headers: see `header` section [here](https://github.com/grpc/proposal/blob/master/A42-xds-ring-hash-lb-policy.md#xds-api-fields)
- consistent hashing: see `filter_state` section [here](https://github.com/grpc/proposal/blob/master/A42-xds-ring-hash-lb-policy.md#xds-api-fields)

As mentioned in the `filter_state` section in the above mentioned gRFC: all requests on a gRPC channel will hash to the same value based on the channel id (which is chosen at random). So, if you end up with two processes which each open a gRPC channel to your service, all requests made from each gRPC channel will hash to the same backend, but there is no guarantee that requests from different gRPC channels will hash to the same backend.

If you use header based hashing though, requests with same headers would hash to the same backend across gRPC channels.

This is how we build the ring in the `ring_hash` LB policy: https://github.com/grpc/grpc-go/blob/6a707eb1bb94d73e8a692961da19bb5c95b7b723/xds/internal/balancer/ringhash/ring.go#L102

And this is how we generate the hash at RPC time: https://github.com/grpc/grpc-go/blob/a7058f7b72f9c1452b6e7cf8bb9afd03997017f5/xds/internal/resolver/serviceconfig.go#L223

Hope this answers your question.
