### ISSUE TITLE
What case the second GOAWAY is sent?

### ISSUE THREAD

**Issue by hiyosi** [grpc/grpc-go#5969]
A gRPC server is configured with MaxConnectionAge=3m, MaxConnectionAgeGrace=Infinity(default).

e.g. server
```go
grpc.NewServer(
	grpc.UnaryInterceptor(unaryInterceptor),
	grpc.StreamInterceptor(streamInterceptor),
	grpc.Creds(credentials.NewTLS(tlsConfig)),
	grpc.KeepaliveParams(keepalive.ServerParameters{
		MaxConnectionAge: 3 * time.Minute,
	}),
)
```
e.g. client
```go
grpc.DialContext(ctx, address,
	grpc.WithDefaultServiceConfig(`{ "loadBalancingConfig": [ { "round_robin": {} } ] }`),
	grpc.FailOnNonTempDialError(true),
	grpc.WithBlock(),
	grpc.WithReturnConnectionError(),
	grpc.WithTransportCredentials(credentials.NewTLS(tlsConfig)),
)
```

In this case, the serevr send the first GOAWAY with LastStreamID=2147483647 every 3m ± jitter. And a client that receives the GOAWAY then reconnects.

On the server side, the server rarely send the second GOAWAY with LastStreamID=`<Real Stream ID>`, then the connection is closed.

```
2023/01/24 19:21:01 http2: Framer 0xc00037d6c0: wrote GOAWAY len=8 LastStreamID=<Real Stream ID> ErrCode=NO_ERROR Debug=""
2023/01/24 19:21:01 ERROR: [transport] transport: loopyWriter.run returning. Err: transport: Connection closing
```

On the client side, `connection reset by peer, received prior goaway: code: NO_ERROR` is occurred.

This seems like the graceful shutdown behavior.

https://www.rfc-editor.org/rfc/rfc7540#section-6.8
> A server that is attempting to gracefully shut down a
> connection SHOULD send an initial GOAWAY frame with the last stream
> identifier set to 2^31-1 and a NO_ERROR code.  This signals to the
> client that a shutdown is imminent and that initiating further
> requests is prohibited.  After allowing time for any in-flight stream
> creation (at least one round-trip time), the server can send another
> GOAWAY frame with an updated last stream identifier.  This ensures
> that a connection can be cleanly shut down without losing requests.

But in my understanding, Since MaxConnectionAgeGrace=Infinity, the second GOAWAY is effectively not sent because the server never close the connection by itself.

https://pkg.go.dev/google.golang.org/grpc/keepalive

> // MaxConnectionAgeGrace is an additive period after MaxConnectionAge after
> // which the connection will be forcibly closed.
> // MaxConnectionAgeGrace time.Duration // The current default value is infinity.

Why is the second GOAWAY sent and client get the error.

**Comment by arvindbr8** [comment]
Hi @hiyosi, 

Great job in looking at it so far. Here's what I think

> On the server side, the server rarely send the second GOAWAY with LastStreamID=<Real Stream ID>, then the connection is closed.

This might not be the case. In an ideal scenario, server sends the first GOAWAY upon expiry of the connection age, and then resets the timer to the connection age grace, and waits for it to expire before sending the second GOAWAY. 

However, when the client sees the first GOAWAY, and since there are no existing connections, it closes the connection right away(as is expected) and therefore the server never has to send the second one (although, with the grace period being set to infinity, even if the client did not close the connection, the server would not send the second GOAWAY)

One way to make sure of this is by enabling verbose logging and see if [this](https://github.com/grpc/grpc-go/blob/e2d69aa076dd070e3668784c4dc8bcf7131b3f67/internal/transport/http2_server.go#L1169) log statement appears on the server. This would only appear when the grace timeout expires. 

Does that answer your question?

**Comment by hiyosi** [comment]
@arvindbr8 
Thank you for replying.

> This might not be the case. In an ideal scenario, server sends the first GOAWAY upon expiry of the connection age, and then resets the timer to the connection age grace, and waits for it to expire before sending the second GOAWAY.

I understand. 
However,  in my case, those GOAWAY were sent almost the same time.

```
2023/01/24 19:21:01 http2: Framer 0xc00037d6c0: wrote GOAWAY len=8 LastStreamID=2147483647 ErrCode=NO_ERROR Debug=""
2023/01/24 19:21:01 http2: Framer 0xc00037d6c0: wrote GOAWAY len=8 LastStreamID=619 ErrCode=NO_ERROR Debug=""
```

> One way to make sure of [this](https://github.com/grpc/grpc-go/blob/e2d69aa076dd070e3668784c4dc8bcf7131b3f67/internal/transport/http2_server.go#L1169) is by enabling verbose logging and see if this log statement appears on the server. This would only appear when the grace timeout expires.

I could not find such logs. 
```
GRPC_GO_LOG_SEVERITY_LEVEL=info
GRPC_GO_LOG_VERBOSITY_LEVEL=2
```

**Comment by easwars** [comment]
Is it possible for you to provide us with an easy repro?

We do have a keepalive example here: https://github.com/grpc/grpc-go/blob/master/examples/features/keepalive/README.md. Can you see if you can tweak the keepalive parameters here to repro the issue you are talking about. Thanks.

**Comment by hiyosi** [comment]
@easwars  I can see the GOAWAY with follows (it may be severe timing)

server
```go
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"math/rand"
	"net"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/keepalive"

	pb "google.golang.org/grpc/examples/features/proto/echo"
)

var port = flag.Int("port", 50052, "port number")

var kasp = keepalive.ServerParameters{
	MaxConnectionAge: 30 * time.Second, // If any connection is alive for more than 30 seconds, send a GOAWAY
}

// server implements EchoServer.
type server struct {
	pb.UnimplementedEchoServer
}

var letterRunes = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")

func randomString(n int) string {
	b := make([]rune, n)
	for i := range b {
		b[i] = letterRunes[rand.Intn(len(letterRunes))]
	}
	return string(b)
}

func (s *server) UnaryEcho(ctx context.Context, req *pb.EchoRequest) (*pb.EchoResponse, error) {
	msg := req.Message + randomString(4000000)
	return &pb.EchoResponse{Message: msg}, nil
}

func main() {
	flag.Parse()
	rand.Seed(time.Now().UnixNano())

	address := fmt.Sprintf(":%v", *port)
	lis, err := net.Listen("tcp", address)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}

	s := grpc.NewServer(grpc.KeepaliveParams(kasp))
	pb.RegisterEchoServer(s, &server{})

	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
```

client
```go
package main

import (
	"context"
	"flag"
	"fmt"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	pb "google.golang.org/grpc/examples/features/proto/echo"
	"log"
	"time"
)

var addr = flag.String("addr", "localhost:50052", "the address to connect to")

func main() {
	flag.Parse()

	conn, err := grpc.Dial(*addr, grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithBlock(), grpc.WithReturnConnectionError())
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	defer conn.Close()

	for {
		c := pb.NewEchoClient(conn)

		fmt.Println("Performing unary request")
		_, err = c.UnaryEcho(context.Background(), &pb.EchoRequest{Message: "keepalive demo"})
		if err != nil {
			log.Fatalf("unexpected error from UnaryEcho: %v", err)
		}
		fmt.Println("Got RPC response")

		time.Sleep(3 * time.Second)
	}
	select {} // Block forever; run with GODEBUG=http2debug=2 to observe ping frames and GOAWAYs due to idleness.
}
```

```
2023/01/26 14:42:24 http2: Framer 0xc000226000: wrote PING flags=ACK len=8 ping="\x02\x04\x10\x10\t\x0e\a\a"
2023/01/26 14:42:27 http2: Framer 0xc000226000: read HEADERS flags=END_HEADERS stream=19 len=7
2023/01/26 14:42:27 http2: decoded hpack field header field ":method" = "POST"
2023/01/26 14:42:27 http2: decoded hpack field header field ":scheme" = "http"
2023/01/26 14:42:27 http2: decoded hpack field header field ":path" = "/grpc.examples.echo.Echo/UnaryEcho"
2023/01/26 14:42:27 http2: decoded hpack field header field ":authority" = "localhost:50052"
2023/01/26 14:42:27 http2: decoded hpack field header field "content-type" = "application/grpc"
2023/01/26 14:42:27 http2: decoded hpack field header field "user-agent" = "grpc-go/1.52.0-dev"
2023/01/26 14:42:27 http2: decoded hpack field header field "te" = "trailers"
2023/01/26 14:42:27 http2: Framer 0xc000226000: read DATA flags=END_STREAM stream=19 len=21 data="\x00\x00\x00\x00\x10\n\x0ekeepalive demo"
2023/01/26 14:42:27 http2: Framer 0xc000226000: wrote WINDOW_UPDATE len=4 (conn) incr=21
2023/01/26 14:42:27 http2: Framer 0xc000226000: wrote PING len=8 ping="\x02\x04\x10\x10\t\x0e\a\a"
2023/01/26 14:42:27 http2: Framer 0xc000226000: read PING flags=ACK len=8 ping="\x02\x04\x10\x10\t\x0e\a\a"
2023/01/26 14:42:27 http2: Framer 0xc000226000: wrote GOAWAY len=8 LastStreamID=2147483647 ErrCode=NO_ERROR Debug=""
2023/01/26 14:42:27 http2: Framer 0xc000226000: wrote PING len=8 ping="\x01\x06\x01\b\x00\x03\x03\t"
2023/01/26 14:42:27 http2: Framer 0xc000226000: read PING flags=ACK len=8 ping="\x01\x06\x01\b\x00\x03\x03\t"
2023/01/26 14:42:27 http2: Framer 0xc000226000: wrote GOAWAY len=8 LastStreamID=19 ErrCode=NO_ERROR Debug=""
2023/01/26 14:42:27 http2: Framer 0xc000226000: wrote HEADERS flags=END_HEADERS stream=19 len=2
```

**Comment by aureliar8** [comment]
Non authoritative answer here: I'm not part of the grpc maintainers.

According to this comment, the second `GOAWAY` frame is send either after a timeout of one minute or after the client answered the ping that follows the first `GOAWAY`

```go
        // For a graceful close, send out a GoAway with stream ID of MaxUInt32,
	// Follow that with a ping and wait for the ack to come back or a timer
	// to expire. During this time accept new streams since they might have
	// originated before the GoAway reaches the client.
	// After getting the ack or timer expiration send out another GoAway this
	// time with an ID of the max stream server intends to process.
```
https://github.com/grpc/grpc-go/blob/2a1e9348ff7b5d9f4b5039e84e6c9873b5b3e26e/internal/transport/http2_server.go#L1356-#L1378

**Comment by dfawley** [comment]
I think a few things are being conflated here.

The first GOAWAY and the second GOAWAY are not related to the grace period of max connection age.

When max connection age is hit, we send two GOAWAYs on the connection, following the protocol mentioned above (StreamID=MAX_INT then StreamID=MaxActiveStreamID after a ping ack or 1 minute timer).  The first GOAWAY prevents any new streams from being created by the client.  The second GOAWAY lets the client know that any streams created after that ID are not processed at all by the server, so they can be retried.  After the grace period is up, the connection is then hard closed.

If the client has no active streams, and it receives the first GOAWAY (StreamID=MAX_INT), it will just close the connection.  It will not ack the following ping, and then the server will never send a second GOAWAY.

Let me know if this doesn't answer your questions.

**Comment by hiyosi** [comment]
@dfawley Thank you for replying.

> The first GOAWAY and the second GOAWAY are not related to the grace period of max connection age.

Now I understand.

One more question.
Even though I configured the Server with `MaxConnectionAgeGrace=infinity`, 
After the second GOAWAY, `transport: Connection closing` log is appered on the Server side and `connection reset by peer, received prior goaway: code: NO_ERROR` was occurred on the Agent side is what's problems? 
It's not related gRPC?

**Comment by dfawley** [comment]
The grace period allows existing RPCs to complete.  Once all have finished, the connection is closed due to the max age elapsing.  The client will reconnect (potentially to a different backend depending on your environment and configuration), but once a GOAWAY is sent on a connection, per HTTP/2, it can't be used for new streams.  Note that the reconnect happens as soon as the first GOAWAY is received so the client can seamlessly continue sending new RPCs; this reconnecting behavior is unrelated to the second GOAWAY or the connection closing.

**Comment by hiyosi** [comment]
Thank you so mush for details.
I understand. So if a GOAWAY is received during the reception of large data, even if it is in the middle of reception, it will be reconnected immediately and may ocurre in an error.

**Comment by dfawley** [comment]
> if a GOAWAY is received during the reception of large data, even if it is in the middle of reception, it will be reconnected immediately and may occur in an error.

This is not right.  Maybe you have some other misconceptions about gRPC?  It's not a single connection -- it's a pool of connections and management/selection of them.

If you're in the middle of an RPC and a GOAWAY happens due to graceful shutdown (`server.GracefulStop`) or `MaxConnectionAge`, then the RPC will still be allowed to complete normally, unless the server either does a hard shutdown (`Server.Stop`) or `MaxConnectionAgeGrace` elapses.  There should be no errors otherwise.

The reconnection that happens is the creation of a _second_, concurrent connection in order to allow for new RPCs to start.  The first connection only goes away when the above happens or when all RPCs on it end.
