### ISSUE TITLE
WithPerRPCCredentials not working

### ISSUE THREAD

**Issue by sadlil** [grpc/grpc-go#597]
**WithPerRPCCredentials not working after commit 7459645a337d15ffdad5f1a15c9337ba68ee3193**

we are using grpc client with WithPerRPCCredential(). This was fulfilling our needs nicely. But after updating grpc-go this gets broken with the following logs.
```
2016/03/21 12:26:10 transport: http2Client.notifyError got notified that the client transport was broken read tcp 127.0.0.1:48862->127.0.0.1:50051: read: connection reset by peer.
2016/03/21 12:26:10 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2016/03/21 12:26:10 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2016/03/21 12:26:10 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2016/03/21 12:26:10 transport: http2Client.notifyError got notified that the client transport was broken read tcp 127.0.0.1:48867->127.0.0.1:50051: read: connection reset by peer.
2016/03/21 12:26:10 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2016/03/21 12:26:10 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2016/03/21 12:26:10 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2016/03/21 12:26:10 transport: http2Client.notifyError got notified that the client transport was broken EOF.
.
.
.
.
```
Removing the grpc.WithPerRPCCredential() wile dialing grpc works without any errors. But failed running with PerRPCCredential Method.

I added credentials to the helloworld example this also gets broken. [helloworld with PerRPCCredential](https://gist.github.com/sadlil/8343201f972ac9dfebeb) failed to run.

- This is the last [commit](https://github.com/grpc/grpc-go/commit/7459645a337d15ffdad5f1a15c9337ba68ee3193) where this example runs nicely with WithPerRPCCredential methods. 

- switching to this [commit](https://github.com/grpc/grpc-go/commit/b88c12e7caf74af3928de99a864aaa9916fa5aad) fails the client with the log.

```
$ go version
go version go1.5.3 linux/amd64

$ protoc --version
libprotoc 3.0.0
```

**Comment by iamqizhao** [comment]
Thanks for reporting. the fix will be out soon.

**Comment by iamqizhao** [comment]
The problem u ran into is that you used illegal header name in http/2 -- all header names in http/2 should be lower case. which is enforced by the recent change in golang http2 framer. The best fix here is probably returning a meaningful error.

**Comment by bradfitz** [comment]
@iamqizhao, shouldn't `WithPerRPCCredential` also lowercase the map keys it sends?

**Comment by sadlil** [comment]
Lowering the map key resolves the problem. The peer did not close the connection now. 
it would be better if  `WithPerRPCCredential` returns the map keys  lowercase.

**Comment by iamqizhao** [comment]
I had minor concern that this internal conversion might introduce a little confusion on the server side.  But probably it is okay to do that (at least consistent with general metadata processing)...

**Comment by sadlil** [comment]
The issue is fixed. Thnx.
