### ISSUE TITLE
Data Race on the field ''items''

### ISSUE THREAD

**Issue by yanke-xu** [grpc/grpc-go#5970]
During our research on non-blocking concurrency bugs in gRPC, we discovered a potential Data Race in the program. Specifically，there are two confilicting operations on the field "items", where

the read operation at：.../grpc/internal/wrr/random.go:90, and the write operation at：.../grpc/internal/wrr/random.go:86

I don't know whether it is accurate, so I 'm looking forward to your reply.

**Comment by dfawley** [comment]
Can you provide a reproduction sample for this?

This would only happen if the wrr state is being logged while also being changed, so wouldn't be critical for correctness.  Adding a `rw.mu.RLock(); defer rw.mu.RUnlock()` to the top of `(*randomWRR).String` would also prevent this.

**Comment by UtopiaGitHub** [comment]
您好，邮件我已收到，我会及时给您回复，祝好！

**Comment by UtopiaGitHub** [comment]
Is it possible for two statements to be executed at the same time? If so, adding a rw.mu.RLock(); defer rw.mu.RUnlock() to the top of *randomWRR).String is necessary.

**Comment by UtopiaGitHub** [comment]
Is it possible for the two statements to be executed at the same time? If so, adding a rw.mu.RLock(); defer rw.mu.RUnlock() to the top of *randomWRR).String is necessary.

**Comment by UtopiaGitHub** [comment]
Developers may not be able to guarantee exclusive access to items when the two methods are in different go routines. In order to avoid potential data race here, I use `rw.mu.RLock()`; `defer rw.mu.RUnlock()` to make sure that all usages of items is in critical section.

**Comment by UtopiaGitHub** [comment]
Is this a possible data race?

**Comment by arvindbr8** [comment]
`Add()` is always called as part of constructing the WRR object and never concurrently. Also turns out `Next()` is never called concurrently either. I started the PR (#5970) started out to avoid the race when accessing WRR.items in `String()`, but the mutex can be avoided all together for random WRR.

**Comment by yanke-xu** [comment]
您好，邮件我已收到，我会及时给您回复，祝好！
