### ISSUE TITLE
How to create multiple HTTP/2 connections to the same RPC method?

### ISSUE THREAD

**Issue by alfalfaprodigy** [grpc/grpc-go#5989]
Hi,

I have multiple instances of clients and servers.
Each client has it's own custom resolver and load balancer to balance it's own requests over all server instances.
Instance = machine.

Everything works fine until there is a high load on a client.
The machine's tcp retransmit rate increases.

TCP starts sending segments over and over again.
Instead of getting 7ms of a request time it might be 1+sec.

Usually it might be mitigated using connection pool.
But I don't understand how to create it for grpc.

Is there any examples?

Thanks.

**Comment by arvindbr8** [comment]
Hi @alfalfaprodigy,

It is possible to create multiple connections via custom LB policy. The LB policy creates connections, and this can be done multiple times per address to get multiple connections. Hope this helps answer your question.
