### ISSUE TITLE
Does The gRPC client can act as gRPC-Web client?

### ISSUE THREAD

**Issue by Shnitzelil** [grpc/grpc-go#5997]
For testing purpose I wonder if it possible to configure the client to act the same as gRPC-Web client?

**Comment by zasweq** [comment]
gRPC is very plug and play (i.e. all languages implement the same protocol, so permutations of languages are allowed and should work together seamlessly). What behaviors exactly are you trying to emulate in a gRPC-Go client from your gRPC web client?

**Comment by dfawley** [comment]
gRPC-Web uses HTTP/1.  There is no way to configure gRPC-Go to act as a gRPC-Web client, sorry!  IIUC you should be able to use a standard `http.Client` with JSON for that, though.
