### ISSUE TITLE
server/transport: send appropriate debug_data in GOAWAY frames

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5999]
According to [A9](https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md#proposal), servers should sent appropriate debug_data along with the GOAWAY frames.

- For a GOAWAY frame sent when `max_connection_idle` expired, debug_data should be set to ASCII `max_idle`. This is currently handled here: https://github.com/grpc/grpc-go/blob/6a707eb1bb94d73e8a692961da19bb5c95b7b723/internal/transport/http2_server.go#L1145.
- For a GOAWAY frame sent when `max_connection_age` expired, debug_data should be set to ASCII `max_age`. This is currently handled here: https://github.com/grpc/grpc-go/blob/6a707eb1bb94d73e8a692961da19bb5c95b7b723/internal/transport/http2_server.go#L1162

A9 does not talk about graceful stop of the server. But in this case, GOAWAY frames are sent on all open connections and we should set the debug_data to ASCII `graceful_stop` here. This is handled here: https://github.com/grpc/grpc-go/blob/6a707eb1bb94d73e8a692961da19bb5c95b7b723/server.go#L1831

In all the above three cases, we end up calling [ServerTransport.Drain](https://github.com/grpc/grpc-go/blob/6a707eb1bb94d73e8a692961da19bb5c95b7b723/internal/transport/http2_server.go#L1310). We could update this method to accept the `debug_data` to be sent out as part of the GOAWAY.

**Comment by arvindbr8** [comment]
Sure! Assigning this issue to you. We appreciate the effort. 

Please use this issue to clarify any questions you have about the approach to take. Also might be good idea to riffle through our repo's [CONTRIBUTING.md](https://github.com/grpc/grpc-go/blob/master/CONTRIBUTING.md).

**Comment by tobotg** [comment]
Thank you @arvindbr8. I will work on submitting a PR soon.

**Comment by tobotg** [comment]
Hi @arvindbr8 and @easwars 
I tried to follow the indications @easwars gave above and filed a PR a couple of days ago. I'm happy to rework it as review and feedback come.
Thanks
