### ISSUE TITLE
google.golang.org/grpc/xds has dependency on "testing"

### ISSUE THREAD

**Issue by aaronbee** [grpc/grpc-go#6015]
### What version of gRPC are you using?
v1.53.0
### What version of Go are you using (`go version`)?
v1.19.5
### What operating system (Linux, Windows, …) and version?
N/A
### What did you do?
We check for imports of unexpected dependencies for our production binaries. Upgrading to grpc v1.53.0 added an import to the standard library "testing" package.

### What did you expect to see?
Production libraries should not depend on "testing".
### What did you see instead?
This is one dependency path seen:

google.golang.org/grpc/xds/googledirectpath ->
google.golang.org/grpc/xds -> 
google.golang.org/grpc/xds/internal/balancer -> 
google.golang.org/grpc/xds/internal/balancer/cdsbalancer ->
google.golang.org/grpc/xds/internal/balancer/clusterresolver ->
google.golang.org/grpc/internal/testutils -> 
testing

"google.golang.org/grpc/xds/internal/balancer/clusterresolver" likely is not supposed to depend on "google.golang.org/grpc/internal/testutils". In This #5852 [resource_resolver_dns.go added a call to `testutils.MustParseURL`](https://github.com/grpc/grpc-go/pull/5852/files#diff-9a2e73de18e3c1cc94c9b5a44e9b0c12502ad2e07335127501e29a8b6b379301).

**Comment by dfawley** [comment]
Sounds right. Thanks for catching this!

**Comment by dfawley** [comment]
@easwars could you take a look please?

**Comment by gm42** [comment]
`google.golang.org/grpc/channelz/service` is also `importing google.golang.org/grpc/internal/testutils`, which in turn imports `testing`; I'll try to come up with a PR.

**Comment by gm42** [comment]
Opened PR #6027; if someone could fix the missing label/milestone and review it, that'd be appreciated. Thanks!
