### ISSUE TITLE
how to reduce the buffering window so that one message is sent from the client to the server

### ISSUE THREAD

**Issue by LazarenkoA** [grpc/grpc-go#6024]
Client code:
```go
// ChunkSize = 70*1024 
conn, err := grpc.Dial(target,
    grpc.WithTransportCredentials(insecure.NewCredentials()),
    grpc.WithInitialWindowSize(ChunkSize),
    grpc.WithInitialConnWindowSize(ChunkSize),
    grpc.WithReadBufferSize(ChunkSize),
    grpc.WithWriteBufferSize(ChunkSize),
)
```

Server code:
```go
s := grpc.NewServer(grpc.InitialWindowSize(ChunkSize),
    grpc.InitialConnWindowSize(ChunkSize),
    grpc.ReadBufferSize(ChunkSize),
    grpc.WriteBufferSize(ChunkSize),
)
```
But still the client sends 3 messages, provided that the server does not read them, and I need the client to block sending after each message.
Also I tried
```go
grpc.WithInitialWindowSize(0),
grpc.WithInitialConnWindowSize(0),

//...
grpc.InitialWindowSize(0),
grpc.InitialConnWindowSize(0),
```
I expected that the default buffer window of 64kb would be set, but nothing has changed. 

Is it possible to ensure that the messages leave one by one?

**Comment by easwars** [comment]
Do you happen to have an easily reproducible setup for this issue?

**Comment by LazarenkoA** [comment]
> Do you happen to have an easily reproducible setup for this issue?

made an example
[grpc_test.zip](https://github.com/grpc/grpc-go/files/10758541/grpc_test.zip)

in this example, the server reads messages with a delay of 5 seconds. When the client starts, a log shows that 4 messages are sent at the same time, after that the messages begin to go one at a time. I need those four messages also to be sent one at a time.

**Comment by zasweq** [comment]
Just a heads up, if you just don't specify Dial Option it will go to default, so no need for the explicit grpc.WithInitialXSize. If you need to block sending (and please specify blocking on what exactly? The server processing it? The message being successfully written to the wire?). https://github.com/grpc/grpc-go/blob/master/stream.go#L114 as you can see, this operation blocks until there is enough flow control to schedule the message on the transport. If you need to block on the server responding, e.g. you can have a blocking operation stream.Recv() after one stream.Send() in your for, you can wait on this until the next iteration. Also, along with specifying what event you want to block until, what advantage do you see with the client sending one message at a time in a blocking manner?

**Comment by zasweq** [comment]
Also, what does "one at a time" mean? HTTP2/frames?

**Comment by LazarenkoA** [comment]
> what advantage do you see with the client sending one message at a time in a blocking manner?

the peculiarity of my algorithm

**Comment by zasweq** [comment]
Yes. The example you attached runs blocks on stream.Send returning before printing a line. What do you mean "the peculiarity of my algorithm"? You are already blocking on something (enough flow control on the transport), so please let me know what exactly you want to block on.

**Comment by LazarenkoA** [comment]
I want the messages to go strictly one at a time, in exsemple 4 messages go first (from the client side)

**Comment by zasweq** [comment]
What do you mean "go strictly one at a time". Can you be more specific? Semantically, this can mean a lot of things. (http/2 data frames written one at a time onto wire, msg sends until recv) etc.

**Comment by LazarenkoA** [comment]
until the server receives the message `record Server.Recv()` the client did not send a new message. If we draw analogies, it now works as if we were writing to a buffered channel, and I want it to work as a non-buffered channel

**Comment by zasweq** [comment]
I don't think read/write buffers on client side can guarantee a corresponding Recv() has happened server side. This is simply gating writing to the network connection. Unless the server sends an ack, there's no way to know when the Recv() actually happens server side. The best thing here I think would be to ack the message server side and then wait client side on the ack to send message (like what I described above about blocking on a stream.Recv() client side), which guarantees a happens before relationship between Recv() happening server side and your next Send() client side.

**Comment by LazarenkoA** [comment]
but the websocket doesn't work like that, there's no buffer, or is it a feature of http 2?

**Comment by zasweq** [comment]
I don't get what you're referring to here.

**Comment by LazarenkoA** [comment]
no one answered me, this behavior is a error or not. If not an error, it is unclear what the options are responsible for
```
grpc.WithInitialWindowSize(ChunkSize),
grpc.WithInitialConnWindowSize(ChunkSize)
```

**Comment by dfawley** [comment]
If you want the client to only have 1 outstanding message at a time to the server, then the server will need to explicitly notify the client when it's ready to receive another message, at which time the client can send a second message.  The gRPC protocol doesn't have any built in feedback between clients and servers, except at a byte-buffer level (the HTTP/2 window size options you listed).  I would _not_ recommend trying to use window sizes for this purpose, as those options are intended for achieving optimal network performance without requiring large buffers in memory.
