### ISSUE TITLE
Add documentation on some anti-patterns

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#6028]
We should add clarifying documentation about certain anti-patterns which have started showing up in multiple questions from users. These are around the usage of the following APIs:
- grpc.FailOnNonTempDialError
- grpc.WithBlock
- grpc.WithReturnConnectionError

**Comment by ulascansenturk** [comment]
You can assign me :)

**Comment by easwars** [comment]
@ulascansenturk : I've assigned it to you. Please talk to us if you have any questions about this.

Basically, we want to discourage developers from using the above mentioned APIs. These APIs rely on failures at dial time. We instead want to encourage them to rely on errors from RPCs instead.

**Comment by easwars** [comment]
@dfawley : FYI

**Comment by ulascansenturk** [comment]
Could you please check it :) @easwars
