### ISSUE TITLE
Misleading documentation for status.FromError

### ISSUE THREAD

**Issue by wojciechp-remitly** [grpc/grpc-go#6032]
### What version of gRPC are you using?
`1.53.0`

### What version of Go are you using (`go version`)?
`1.19.6`

### What operating system (Linux, Windows, …) and version?
`MacOS Ventura 13.1`

### What did you do?
Using `status.FromError` function to extract `Status` from response error 

### What did you expect to see?
Status is returned with codes.OK and no message when error is nil

### What did you see instead?
nil Status and ok `bool` set to true

https://github.com/grpc/grpc-go/blob/abff344ead8f49f3a89ae8be68b1538611950ec4/status/status.go#L77-L97

Function doc states that when err is nil, Status is returned with codes.OK. Instead, (nil, true) is returned.

I would like to know which part is broken - is it function doc, or its implementation.

In my opinion, it would be better to change implementation to match doc: it would be easier to use `status.FromErro` in client code, as it could remove additional, not needed check for `ok` return variable and/or if returned Status is nil.

Once I've got confirmation, I'll be happy to create PR for that.

**Comment by dfawley** [comment]
I believe everything here is WAI.  A `nil` `*Status` has `Code() == codes.OK`.  Is this causing you some problems?

**Comment by wojciechp-remitly** [comment]
Hey @dfawley 👋 
I'm so sorry, you are right of course! I missed that Status does not expose any members, just methods 🤦 .

Again, I'm sorry for your time loss, closing this ticket.
