### ISSUE TITLE
gRPC balancer how to control which backend the Streaming method connects to

### ISSUE THREAD

**Issue by shenqidebaozi** [grpc/grpc-go#6037]
The gRPC streaming method will create a connection with the first ready instance in the balance picker, which makes it impossible to customize which instance to create a connection with. Is there any solution?

<img width="1041" alt="企业微信截图_aa437edb-ec1a-4ed3-8250-53aea148beff" src="https://user-images.githubusercontent.com/35397691/220037652-a5bd2fde-b982-4fda-ab6e-81342b3fbc00.png">

**Comment by zasweq** [comment]
This is the base picker. If you want more specific logic on how it routes across the ready SubConns, we have balancers such as round robin and pick first that customize which SubConn to use. The SubConns are determined as a result of the address list received from the resolver of your system, so you will need to map that with your desired target -> address list of SubConns you desire to use for RPCs.
