### ISSUE TITLE
Grpc client Wrap Dial function

### ISSUE THREAD

**Issue by abhi9560** [grpc/grpc-go#6039]
When i Wrap grpc.Dial function with own function it is getting error

goroutine 1 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).updateClientConnState
/root/go/src/google.golang.org/grpc/balancer_conn_wrappers.go:158
google.golang.org/grpc.(*ClientConn).updateResolverState
/root/go/src/google.golang.org/grpc/clientconn.go:678
google.golang.org/grpc.(*ccResolverWrapper).UpdateState
/root/go/src/google.golang.org/grpc/resolver_conn_wrapper.go:102
google.golang.org/grpc/internal/resolver/passthrough.(*passthroughResolver).start
/root/go/src/google.golang.org/grpc/internal/resolver/passthrough/passthrough.go:55

####my code :-
func WrapClient(target string, opts ...grpc.DialOption)(*grpc.ClientConn, error){

  	opts = append(opts, grpc.WithUnaryInterceptor(NewUnaryClientInterceptor()))
    conn, err := grpc.Dial(target,opts...)
    if err != {
    	log.Fatalf("did not connect : %v",err)
    }
    return conn,err
}

**Comment by abhi9560** [comment]
func NewUnaryClientInterceptor() grpc.UnaryClientInterceptor {
    return func(ctx context.Context, method string, req, reply interface{}, cc *grpc.ClientConn, invoker grpc.UnaryInvoker,opts ...grpc.CallOption) error {
        err:= invoker(ctx, method, req, reply, cc,opts...)
        return err
    }
}

**Comment by zasweq** [comment]
Can you provide more information here? What is the error? I see a log for a goroutine's stack trace. What is the rest of the system passed the code statement (this will help figure out what the error actually is if you provide it)?
