### ISSUE TITLE
panic prevention: check if CallOptions is nil

### ISSUE THREAD

**Issue by bo-er** [grpc/grpc-go#6045]
### What version of gRPC are you using?
The latest version
### What version of Go are you using (`go version`)?
go version go1.18.3 
### What operating system (Linux, Windows, …) and version?
darwin/amd64
### What did you do?
If possible, provide a recipe for reproducing the error.

The following code is from `grpc-go/examples/helloworld/greeter_client.go`
```
func main() {
	flag.Parse()
	// Set up a connection to the server.
	conn, err := grpc.Dial(*addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	defer conn.Close()
	c := pb.NewGreeterClient(conn)

	// Contact the server and print out its response.
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
*	r, err := c.SayHello(ctx, &pb.HelloRequest{Name: *name}, nil) // a nil is mistakenly added
	if err != nil {
		log.Fatalf("could not greet: %v", err)
	}
	log.Printf("Greeting: %s", r.GetMessage())
}
```
The line marked with a star has a `nil` tail that panics the code when using `go run ./grpc-go/examples/helloworld/greeter_client/main.go` to run the example grpc client code.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13a9510]

goroutine 1 [running]:
google.golang.org/grpc.newClientStreamWithParams({0x15372f0, 0xc0000b0960}, 0x17ecd20, 0xc00016e380, {0x1493c37, 0x1c}, {0x0, 0x0, 0x0, 0x0, ...}, ...)
        /Users/steve/Documents/GIT/grpc-go/stream.go:255 +0xf30
google.golang.org/grpc.newClientStream.func2({0x15372f0?, 0xc0000b0960?}, 0xc0000b0960?)
        /Users/steve/Documents/GIT/grpc-go/stream.go:193 +0x9f
google.golang.org/grpc.newClientStream({0x15372f0, 0xc0000b0960}, 0x17ecd20, 0xc00016e380, {0x1493c37, 0x1c}, {0xc00017e3b0, 0x1, 0x1})
        /Users/steve/Documents/GIT/grpc-go/stream.go:228 +0x4ce
google.golang.org/grpc.invoke({0x15372f0?, 0xc0000b0960?}, {0x1493c37?, 0x30?}, {0x1437100, 0xc0000b2c40}, {0x1437040, 0xc0000b2c80}, 0x0?, {0xc00017e3b0, ...})
        /Users/steve/Documents/GIT/grpc-go/call.go:74 +0x7d
google.golang.org/grpc.(*ClientConn).Invoke(0x190b5b8?, {0x15372f0?, 0xc0000b0960?}, {0x1493c37?, 0x0?}, {0x1437100?, 0xc0000b2c40?}, {0x1437040?, 0xc0000b2c80?}, {0xc00017e3b0, ...})
        /Users/steve/Documents/GIT/grpc-go/call.go:37 +0x265
google.golang.org/grpc/examples/helloworld/helloworld.(*greeterClient).SayHello(0xc000149f20, {0x15372f0, 0xc0000b0960}, 0xf?, {0xc00017e3b0, 0x1, 0x1})
        /Users/steve/Documents/GIT/grpc-go/examples/helloworld/helloworld/helloworld_grpc.pb.go:57 +0xce
main.main()
        /Users/steve/Documents/GIT/grpc-go/examples/helloworld/greeter_client/main.go:55 +0x26e
exit status 2
```

When `nil` is used as Go's variadic parameter, `[nil]` instead of `[]` is passed into the function. This is primarily due to the ease with which the function definition from "helloworld_grpc.pb.go" can be copied into the code. I copied the code but prematurely set the last parameter to nil, which should have been left empty, but I forgot this gotcha and it took me a long time to debug...

```
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}
```

### What did you expect to see?
Expect when `grpc.CallOption` is explicitly set to nil(mistakenly, of course), the program will not panic.
### What did you see instead?

The program panics.

**Comment by zasweq** [comment]
Hello, thank you for raising the bug and the subsequent PR. Whie possibly a legitimate panic, the team decided we're going to close this issue/pr. The reason is that a programmer really shouldn't call a variadic argument with a nil argument. Just remember to leave it empty :).
