### ISSUE TITLE
ServeHTTP handler never invoke HandleConn or TagConn in stats.Handler

### ISSUE THREAD

**Issue by leungster** [grpc/grpc-go#6047]
### What version of gRPC are you using?
`1.53.0`

### What version of Go are you using (`go version`)?
`go version go1.20.1 darwin/amd64`

### What operating system (Linux, Windows, …) and version?
OSX Intel

### What did you do?
I attached a [stats.Handler](https://pkg.go.dev/google.golang.org/grpc/stats#Handler) to my grpc server that is invoked with [ServeHTTP](https://pkg.go.dev/google.golang.org/grpc#Server.ServeHTTP)
The `TagRPC` and `HandleRPC` methods are invoked but the `HandleConn` and `TagConn` ones are not. 

I'm trying to count the number of active grpc connections to my server.

### What did you expect to see?
`HandleConn` and `TagConn` are invoked when gRPC connections to the server are created.

### What did you see instead?
`HandleConn` and `TagConn` are never invoked.

**Comment by zasweq** [comment]
That API surface that we define here, TagRPC and HandleRPC is unfortunately only called in our transport (http2_server). Thus, this is WAI, and if you ServeHTTP, which uses the GoLang standard library HTTP/2 Server implementation, your registered Stats Handler will not receive these calls.
