### ISSUE TITLE
Dialing a unix socket with a relative path fails

### ISSUE THREAD

**Issue by Otterverse** [grpc/grpc-go#6057]
### What version of gRPC are you using?
1.52.3 and tested against master as well

### What version of Go are you using (`go version`)?
1.19.6

### What operating system (Linux, Windows, …) and version?
Linux 6.0.10 and MacOS (Darwin Kernel Version 22.3.0)

### What did you do?
`grpc.Dial("unix://test.socket")`
or
`grpc.Dial("unix://./test.socket")`

### What did you expect to see?
No errors.

### What did you see instead?
Got errors
`failed to build resolver: invalid (non-empty) authority: test.sock`
or
`failed to build resolver: invalid (non-empty) authority: .`

### Details
The reason this became an issue is during testing on MacOS. testing.TempDir() creates relatively long paths, but the syscall for connect() itself is limited to 104 characters in length, so the long, absolute paths fail. A workaround suggested was to chdir and then use only a short, relative path. I could do that on the listening side of our code (where we directly call net.Listen()) but couldn't implement a workaround for the dialer side.

Below is a small patch that allows it to work, at least for my use case, but I'm not certain recombining fields to get the original path like this would always be safe.
```
diff --git a/internal/resolver/unix/unix.go b/internal/resolver/unix/unix.go
index 16091168..dc0bd3fd 100644
--- a/internal/resolver/unix/unix.go
+++ b/internal/resolver/unix/unix.go
@@ -20,8 +20,6 @@
 package unix
 
 import (
-       "fmt"
-
        "google.golang.org/grpc/internal/transport/networktype"
        "google.golang.org/grpc/resolver"
 )
@@ -34,16 +32,12 @@ type builder struct {
 }
 
 func (b *builder) Build(target resolver.Target, cc resolver.ClientConn, _ resolver.BuildOptions) (resolver.Resolver, error) {
-       if target.URL.Host != "" {
-               return nil, fmt.Errorf("invalid (non-empty) authority: %v", target.URL.Host)
-       }
-
        // gRPC was parsing the dial target manually before PR #4817, and we
        // switched to using url.Parse() in that PR. To avoid breaking existing
        // resolver implementations we ended up stripping the leading "/" from the
        // endpoint. This obviously does not work for the "unix" scheme. Hence we
        // end up using the parsed URL instead.
-       endpoint := target.URL.Path
+       endpoint := target.URL.Host + target.URL.Path
        if endpoint == "" {
                endpoint = target.URL.Opaque
        }
```

**Comment by zasweq** [comment]
gRPC's dial target string is speced to be scheme://authority/endpoint. Thus, when you dial with just two //, gRPC thinks that the characters after the two // are the authority.

**Comment by easwars** [comment]
@Otterverse: Please see our naming spec [here](https://github.com/grpc/grpc/blob/master/doc/naming.md), and specifically the section on the `unix` scheme.

**Comment by zasweq** [comment]
Specifically: "In the first form, the path may be relative or absolute; in the second form, the path must be absolute (i.e., there will actually be three slashes, two prior to the path and another to begin the absolute path)."

**Comment by dfawley** [comment]
More specifically, it seems you need to use `grpc.Dial("unix:test.socket")` for a relative path or `grpc.Dial("unix:/absolute/path/to/test.socket")`.
