### ISSUE TITLE
Client-side stream error with codes.Internal if returned error on server-side has a newline in it (malformed http2)

### ISSUE THREAD

**Issue by peter-edge** [grpc/grpc-go#606]
I put together https://github.com/peter-edge/grpcerr to reproduce (a lot of the code there is just boilerplate, it's from a template I use https://github.com/peter-edge/base-go).

The basic thing is that you get malformed http2 with a certain returned error, which I've never seen before. The returned error on the client side is `rpc error: code = 13 desc = "stream error: stream ID 1; PROTOCOL_ERROR"`. The error string that is returned is in https://github.com/peter-edge/grpcerr/blob/master/api_server.go. I put some more instructions in the README of the grpcerr repository.

**Comment by peter-edge** [comment]
More specifically, if you return this error from a server implementation for a unary call, then you get malformed http2:

```go
func (a *apiServer) Something(ctx context.Context, request *Request) (*Response, error) {
  return nil, errors.New(`protoc -I/tmp/protoeasy-input933135460 -I/go/src/go.pedge.io/protoeasy/vendor/go.pedge.io/pb/proto --go_out=Mgoogle/api/annotations.proto=github.com/gengo/grpc-gateway/third_party/googleapis/google/api,Mgoogle/api/http.proto=github.com/gengo/grpc-gateway/third_party/googleapis/google/api,Mgoogle/api/label.proto=go.pedge.io/pb/go/google/api,Mgoogle/api/monitored_resource.proto=go.pedge.io/pb/go/google/api,Mgoogle/datastore/v1beta3/datastore.proto=go.pedge.io/pb/go/google/datastore/v1beta3,Mgoogle/datastore/v1beta3/entity.proto=go.pedge.io/pb/go/google/datastore/v1beta3,Mgoogle/datastore/v1beta3/query.proto=go.pedge.io/pb/go/google/datastore/v1beta3,Mgoogle/devtools/cloudtrace/v1/trace.proto=go.pedge.io/pb/go/google/devtools/cloudtrace/v1,Mgoogle/example/library/v1/library.proto=go.pedge.io/pb/go/google/example/library/v1,Mgoogle/iam/v1/iam_policy.proto=go.pedge.io/pb/go/google/iam/v1,Mgoogle/iam/v1/policy.proto=go.pedge.io/pb/go/google/iam/v1,Mgoogle/logging/type/http_request.proto=go.pedge.io/pb/go/google/logging/type,Mgoogle/logging/type/log_severity.proto=go.pedge.io/pb/go/google/logging/type,Mgoogle/logging/v2/log_entry.proto=go.pedge.io/pb/go/google/logging/v2,Mgoogle/logging/v2/logging.proto=go.pedge.io/pb/go/google/logging/v2,Mgoogle/logging/v2/logging_config.proto=go.pedge.io/pb/go/google/logging/v2,Mgoogle/logging/v2/logging_metrics.proto=go.pedge.io/pb/go/google/logging/v2,Mgoogle/longrunning/operations.proto=go.pedge.io/pb/go/google/longrunning,Mgoogle/protobuf/any.proto=go.pedge.io/pb/go/google/protobuf,Mgoogle/protobuf/api.proto=go.pedge.io/pb/go/google/protobuf,Mgoogle/protobuf/descriptor.proto=github.com/golang/protobuf/protoc-gen-go/descriptor,Mgoogle/protobuf/duration.proto=go.pedge.io/pb/go/google/protobuf,Mgoogle/protobuf/empty.proto=go.pedge.io/pb/go/google/protobuf,Mgoogle/protobuf/field_mask.proto=go.pedge.io/pb/go/google/protobuf,Mgoogle/protobuf/source_context.proto=go.pedge.io/pb/go/google/protobuf,Mgoogle/protobuf/struct.proto=go.pedge.io/pb/go/google/protobuf,Mgoogle/protobuf/timestamp.proto=go.pedge.io/pb/go/google/protobuf,Mgoogle/protobuf/type.proto=go.pedge.io/pb/go/google/protobuf,Mgoogle/protobuf/wrappers.proto=go.pedge.io/pb/go/google/protobuf,Mgoogle/pubsub/v1/pubsub.proto=go.pedge.io/pb/go/google/pubsub/v1,Mgoogle/pubsub/v1beta2/pubsub.proto=go.pedge.io/pb/go/google/pubsub/v1beta2,Mgoogle/rpc/code.proto=go.pedge.io/pb/go/google/rpc,Mgoogle/rpc/error_details.proto=go.pedge.io/pb/go/google/rpc,Mgoogle/rpc/status.proto=go.pedge.io/pb/go/google/rpc,Mgoogle/type/color.proto=go.pedge.io/pb/go/google/type,Mgoogle/type/date.proto=go.pedge.io/pb/go/google/type,Mgoogle/type/dayofweek.proto=go.pedge.io/pb/go/google/type,Mgoogle/type/latlng.proto=go.pedge.io/pb/go/google/type,Mgoogle/type/money.proto=go.pedge.io/pb/go/google/type,Mgoogle/type/timeofday.proto=go.pedge.io/pb/go/google/type,Mpb/common/common.proto=go.pedge.io/pb/go/pb/common,Mpb/geo/geo.gen.proto=go.pedge.io/pb/go/pb/geo,Mpb/geo/geo.proto=go.pedge.io/pb/go/pb/geo,Mpb/money/money.gen.proto=go.pedge.io/pb/go/pb/money,Mpb/money/money.proto=go.pedge.io/pb/go/pb/money,Mpb/net/net.proto=go.pedge.io/pb/go/pb/net,Mpb/phone/phone.proto=go.pedge.io/pb/go/pb/phone,Mpb/time/time.proto=go.pedge.io/pb/go/pb/time:/tmp/protoeasy-output472003187 /tmp/protoeasy-input933135460/tmp.proto: exit status 1
tmp.proto:5:1: Expected ";".`)
}

**Comment by peter-edge** [comment]
I went through the error string and found out that if an error has a newline in it, it causes this error: https://github.com/peter-edge/grpcerr/commit/595207d8d635e2a1423ef33173a2590e6a61ffd2

So this errors:

```go
func (a *apiServer) Something(ctx context.Context, request *Request) (*Response, error) {
  return nil, errors.New("1\n2")
}
```

**Comment by peter-edge** [comment]
The error comes from https://github.com/grpc/grpc-go/blob/e5f60381dde4777aae49b7d678850c6fa25bbbc6/transport/http2_client.go#L756, I'm not a world expert on http2 (@bradfitz lol) so is there something that needs to be handled with newlines when sending from the server-side?

**Comment by iamqizhao** [comment]
duplication of #576 

Newline is an illegal char in HTTP/2 so you can PROTOCOL Error which is expected behavior. But I do think HTTP/2 framer should give more detailed info about the error instead of simply returning PROTOCOL Error.

**Comment by bradfitz** [comment]
> But I do think HTTP/2 framer should give more detailed info about the error instead of simply returning PROTOCOL Error.

It can: https://godoc.org/golang.org/x/net/http2#Framer.ErrorDetail

ErrorDetail was added to not break compatibility and change the values being returned.

**Comment by peter-edge** [comment]
I commented over on 576 FYI, def like de duping :)

**Comment by iamqizhao** [comment]
@bradfitz nice I am going to see how to instrument it into grpc. Thanks.

**Comment by iamqizhao** [comment]
@bradfitz 
Why don't we detect the illegal characters on the writing path to eliminate it in the early stage? Only enforcing the check on the reading path introduces some issue to gRPC -- e.g., if a client sends an illegal char in metadata, it is detected when the server's framer reads it then the server sends a rst_stream frame to the client. Because rst_stream only has an error code, the client loses the real root cause.

**Comment by bradfitz** [comment]
We could detect it in writing, but we could also just fix it. See #609, which isn't doing the `-bin` suffix thing yet.

**Comment by rjarmstrong** [comment]
I found I got this error if putting ':' inside `metadata.Pairs` when creating a new request context:
e.g. 

```go
metadata.NewContext(
			context.Background(),
			metadata.Pairs(
				"prefs:private_view",
                                "true",
			))
```

**Comment by menghanl** [comment]
@rjarmstrong
`:` is not allowed in metadata keys.
All allowed characters are defined in [this doc](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests). I also filed #1299 to update the doc in metadata package.
