### ISSUE TITLE
Make a new release for protoc-gen-go-grpc

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#6060]
We have had a few fixes to the plugin recently, and should push out a new release soonish.

**Comment by easwars** [comment]
@arvindbr8 : Assigning to you since you are this week's oncall. Instructions are [here](https://g3doc.corp.google.com/third_party/golang/grpc/g3doc/release.md?cl=head#releasing-protoc-gen-go-grpc).

**Comment by arvindbr8** [comment]
Released: https://github.com/grpc/grpc-go/releases/tag/cmd%2Fprotoc-gen-go-grpc%2Fv1.3.0
