### ISSUE TITLE
ringhash: improve test coverage

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#6072]
I just noticed that the amount of tests that we have for the ringhash LB policy is woefully short compared to what C-core and Java have. We should add more tests, which exercise different scenarios.

C-core tests are here: https://github.com/grpc/grpc/blob/master/test/cpp/end2end/xds/xds_ring_hash_end2end_test.cc
Java tests are here: https://github.com/grpc/grpc-java/blob/master/xds/src/test/java/io/grpc/xds/RingHashLoadBalancerTest.java

**Comment by avinilcodes** [comment]
I would like to contribute, can you assign this to me.

**Comment by dfawley** [comment]
@avinilcodes - I can gladly assign this to you, but right now it seems very ambiguous.  Do you think you'll be able to assess the tests in our repo and compare it to the tests in the other repos, or would you need us to help identify the missing things more concretely?

**Comment by shashank-priyadarshi** [comment]
Hi @dfawley , I can work on this.

**Comment by ginayeh** [comment]
@shashank-priyadarshi as @dfawley mentioned earlier, do you think you'll be able to assess the tests in our repo and compare it to the tests in other repos, or would you need us help identify the missing things more concretely?

**Comment by arvindbr8** [comment]
@shashank-priyadarshi / @avinilcodes -- friendly ping! We are almost half way through "Hacktoberfest" 😄.

**Comment by shashank-priyadarshi** [comment]
Yup, been busy with work lately, couldn't squeeze this in! Hopefull about the weekend!

**Comment by atollena** [comment]
This lines up well with some work I have in progress on improving ring hash, and such tests would actually help me, so I'm assigning to me.

**Comment by easwars** [comment]
There are more tests to be written :)

**Comment by atollena** [comment]
This work uncovered https://github.com/grpc/grpc-go/issues/7363.
