### ISSUE TITLE
RE: protoc-gen-go-grpc: allow to generate service files to dedicated dir

### ISSUE THREAD

**Issue by vtolstov** [grpc/grpc-go#6079]
Thanks for reply, @neild!

I was suggesting making the command line flag in this PR a package name string, instead of a boolean. But I just realized that it only works for one proto file (or proto files in the same package).

A `go_grpc_package` option would be nice. The downside is that the proto files need to be modified (or maybe that's an advantage as now the proto file has all the information).
I think if we move along this path, we might need both the `go_grpc_package` option for proto files, __and__ a flag similar to `M`, just like what's done in the message codegen.

_Originally posted by @menghanl in https://github.com/grpc/grpc-go/pull/5255#discussion_r842166182_
            

Does it provided suggestions may be accepted by upstream authors?

**Comment by arvindbr8** [comment]
Hi @vtolstov, Sorry I didnt understand the question correctly. Maybe let's continue the conversation in the same PR to avoid splitting context.

**Comment by dfawley** [comment]
I think it's fine to discuss here since the PR was not accepted.  However @vtolstov hasn't responded for a month or so, so I'll leave this closed for now.
