### ISSUE TITLE
Why there aran't a function that converts a `protobuff object` into a `map`?

### ISSUE THREAD

**Issue by yingshaoxo** [grpc/grpc-go#6087]
<img width="829" alt="image" src="https://user-images.githubusercontent.com/17190829/222948031-6c5efd7b-5d5f-41b3-85da-5fe65957397f.png">

<img width="691" alt="image" src="https://user-images.githubusercontent.com/17190829/222948046-f10088cc-d5aa-4451-831b-7b02e99ef6d5.png">

**Comment by easwars** [comment]
Please file an issue with the protobuf repository here: https://github.com/protocolbuffers/protobuf.
