### ISSUE TITLE
xdsclient transport logs should indicate the authority

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#6091]
In a federation enabled scenario, xdsclient transport logs for events related to sending and receiving messages would benefit from the inclusion of the authority name in them. That way, a person looking at the logs will know which requests/responses were sent/received from which management servers.

**Comment by arvindbr8** [comment]
Sure thing! Assigning this to you. Let us know if you have any questions. @my4-dev

**Comment by easwars** [comment]
> * Which authority information do you imagine to be included in the trasport logs?

With support for federation, an xDS client is able to talk to more than one management server. Each of these management servers is termed the `authority` for the resource that they return. Resource names are expected to be in the format `xdstp://<authority_name>/<resource-name>`. See [A47](https://github.com/grpc/proposal/blob/master/A47-xds-federation.md) for more details on federation support.

We have an `authority` type here which wraps all state associated with a particular management server: https://github.com/grpc/grpc-go/blob/8c70261b5c3941bab070b422fa6d630acba509c2/xds/internal/xdsclient/authority.go#L66

The `authority` type has a `Transport` which is defined here: https://github.com/grpc/grpc-go/blob/8c70261b5c3941bab070b422fa6d630acba509c2/xds/internal/xdsclient/transport/transport.go#L64

The prefix logger used by the `authority` and the `Transport` types is the same one, and is created here, when the xDS client is created:
https://github.com/grpc/grpc-go/blob/8c70261b5c3941bab070b422fa6d630acba509c2/xds/internal/xdsclient/client_new.go#L79

This results in log messages prefixed with `"[xds-client <address of the xds client object>] "`

What we want is for logs from different authorities to have the server_uri as part of the prefix. So, `authority1` will have `"[xds-client <address of the xds client object>] [server_uri_1] "`, while `authority2` will have `"[xds-client <address of the xds client object>] [server_uri2] "`.

This means that when the xDS client creates an authority, it needs to create a new prefix logger with the appropriate prefix. A new authority is created here: https://github.com/grpc/grpc-go/blob/8c70261b5c3941bab070b422fa6d630acba509c2/xds/internal/xdsclient/clientimpl_authority.go#L106 and the server_uri is available in the `config` parameter passed to this function. See: https://github.com/grpc/grpc-go/blob/8c70261b5c3941bab070b422fa6d630acba509c2/xds/internal/xdsclient/bootstrap/bootstrap.go#L129

Hope this helps. Please let us know if you have more questions before starting.

> * Do you imagine being added new log output as well as the already implemented log output within this Issue?

We don't want any new log statements added as part of this issue. All we want is the existing log statements to be outputted with the new prefix.

Try running the tests in the xdsclient package like this:
```
GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_GO_LOG_VERBOSITY_LEVEL=99  go test google.golang.org/grpc/xds/internal/xdsclient/... -v
```

And you should see logs like this:
```
    tlogger.go:116: INFO authority.go:503 [xds] [xds-client 0xc0000fe4b0] Removing last watch for type "RouteConfigResource", resource name "xdsclient-test-rds-resource"  (t=+7.831277ms)
```

What we want is for these logs to instead look like this:
```
    tlogger.go:116: INFO authority.go:503 [xds] [xds-client 0xc0000fe4b0] [<server_uri>] Removing last watch for type "RouteConfigResource", resource name "xdsclient-test-rds-resource"  (t=+7.831277ms)
```
