### ISSUE TITLE
wrr policy not work

### ISSUE THREAD

**Issue by wlbwlbwlb** [grpc/grpc-go#6100]
```
conn, e = grpc.Dial(fmt.Sprintf("%s:///%s", exampleScheme, serviceName),
		grpc.WithDefaultServiceConfig(`{"loadBalancingPolicy": "weighted_round_robin"}`), // This sets the initial balancing policy.
		grpc.WithTransportCredentials(insecure.NewCredentials()),
	)
```

Is it set correctly?

**Comment by wlbwlbwlb** [comment]
package info: google.golang.org/grpc v1.53.0

**Comment by easwars** [comment]
We don't have a fully functional weighted round robin LB policy currently. There is a proposal for the same at https://github.com/grpc/proposal/pull/343, and will be implemented soon. Thanks.
