### ISSUE TITLE
transport: protect field access with proto to avoid possible data race

### ISSUE THREAD

**Issue by UtopiaGitHub** [grpc/grpc-go#6115]
Fixed inconsistency and also potential data race in transport/transport.go:
s.ctx is read/written 4 times in transport/transport.go and transport/http2_server.go; 3 out of 4 times it is protected by t.maxStreamMu.Lock(); 1 out of 4 times it is read without a Lock, which is in func Context() on L404.
A data race may happen when Context() and other func operateHeaders() are called in parallel.

In order to avoid potential data race here, I use xxx.RLock(); defer xxx.RUnlock() to make sure that all usages of items is in critical section.

**Comment by easwars** [comment]
`A data race may happen when Context() and other func operateHeaders() are called in parallel.`

Is this your guess or do you have a test which when run with the `-race` flag reports a race?

**Comment by UtopiaGitHub** [comment]
I haven't understood the functionality of this part of the code. Is it possible for the two functions to be executed at the same time? If so, adding a xxx.RLock(); defer xxx.RUnlock() to avoid a possible data race is necessary.

**Comment by easwars** [comment]
`operateHeaders()` is where the `Stream` is created: https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_server.go#L371-L376. Therefore it can write to `s.ctx` how many ever times it wants without holding any lock. One the stream's context is set up here, it is only ever read, and therefore, methods reading the stream's context can do so without holding a lock.

The same is true on the client side as well. Hope this answers your question/concern.
