### ISSUE TITLE
Bug: When use `gzip` and call with `MaxCallRecvMsgSize(math.MaxInt64)`, will read 0 byte.

### ISSUE THREAD

**Issue by catundercar** [grpc/grpc-go#6119]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
master

### What version of Go are you using (`go version`)?
1.19.2
### What operating system (Linux, Windows, …) and version?
Linux
### What did you do?
If possible, provide a recipe for reproducing the error.
like this demo:
https://github.com/grpc/grpc-go/tree/master/examples/features/compression
I called with `grpc.MaxCallRecvMsgSize(math.MaxInt64)`
And then, I got this result:
```
UnaryEcho call returned "", <nil>
```
**The response `message` was `""`.**
### What did you expect to see?
```
UnaryEcho call returned "compress", <nil>
```

**Comment by dfawley** [comment]
> I called with `grpc.MaxCallRecvMsgSize(math.MaxInt64)`

This is definitely wrong.  The _most_ you'd ever want to do is `math.MaxInt`.  And even that is a pretty insane maximum.  The intent of this setting is to protect you from running out of memory.  No machine has 9,223,372,036,854,775,807 bytes of memory.

**Comment by catundercar** [comment]
> > I called with `grpc.MaxCallRecvMsgSize(math.MaxInt64)`
> 
> This is definitely wrong. The _most_ you'd ever want to do is `math.MaxInt`. And even that is a pretty insane maximum. The intent of this setting is to protect you from running out of memory. No machine has 9,223,372,036,854,775,807 bytes of memory.

You're right, in actual business scenarios, the received data will never reach `math.MaxInt`. But that's not the key of this issue. Perhaps I didn't describe it clearly enough. The key of this issue is that when using the `gzip` compressor and configuring `grpc.MaxCallRecvMsgSize(math.MaxInt)`, **no matter how small the actual data is, even if it's only one byte, the logic in the [`decompressor`](https://github.com/grpc/grpc-go/blob/a02aae6168aa683a1f106e285ec10eb6bc1f6ded/rpc_util.go#L781) will overflow**, causing no data to be read.

I want to emphasize a point that the original available configuration of `grpc.MaxCallRecvMsgSize(math.MaxInt)` causes the service to not return any valid messages and there is no error reported during the call, **when combined with the `gzip` compression method**. It should be a problem that needs to be fixed, rather than asking the user to modify their previously available code.

**Comment by dfawley** [comment]
As mentioned in the PR, this could be fixed by limiting the allowable values in `MaxCallRecvMsgSize` to `math.MaxInt64-1`.  The PR as submitted is incorrect, as we need to be able to read beyond the configured limit to determine whether there was an overrun.

**Comment by catundercar** [comment]
Yes, it is possible to know if the limit is exceeded without reading out all the bytes. Now it looks like there is no better way to do this than to change the `MaxCallRecvMsgSize` parameter.😥

**Comment by catundercar** [comment]
Sorry, I recently discovered that it has been reactivated. Do you have any suitable ways to fix this issue?

**Comment by purnesh42H** [comment]
@catundercar are you interested in continuing to work on this?

**Comment by catundercar** [comment]
> @catundercar are you interested in continuing to work on this?

Yep, but I have not good idea. :joy:

**Comment by infovivek2020** [comment]
@purnesh42H please assign me this issue

**Comment by infovivek2020** [comment]
@purnesh42H  while repro getting the as expected response (UnaryEcho call returned "compress", <nil>)![image](https://github.com/user-attachments/assets/c0de9f4d-1fbd-45be-82dc-92db406c7b1b)

**Comment by infovivek2020** [comment]
@purnesh42H have a look to the PR [https://github.com/infovivek2020/grpc-go/pull/2] I am able to repro in local

**Comment by infovivek2020** [comment]
@purnesh42H Please have a look to the PR [on](https://github.com/infovivek2020/grpc-go/pull/2) applied change [https://github.com/grpc/grpc-go/issues/4552](url) we do not have this issue

**Comment by purnesh42H** [comment]
@infovivek2020 please confirm if this issue is a duplicate of #4552

**Comment by infovivek2020** [comment]
This issue is duplicate one, it is resolved by PR [https://github.com/grpc/grpc-go/issues/4552](url)

**Comment by easwars** [comment]
Closing this issue as this is marked as a duplicate of https://github.com/grpc/grpc-go/issues/4552
