### ISSUE TITLE
WithBlock with xds Dial() is not working

### ISSUE THREAD

**Issue by rohsaini** [grpc/grpc-go#6124]
### What version of gRPC are you using?
v1.50.1

### What version of Go are you using (`go version`)?
1.18.1

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
Client and Server are running as separate pods on k8s cluster. Client Dials() to server with xds://.
Default behavior of Dial is non-blocking. I am trying to make it blocking using grpc.WithBlock()

If possible, provide a recipe for reproducing the error.
Sample code:
`var opts []grpc.DialOption = []grpc.DialOption{
		grpc.WithTransportCredentials(insecure.NewCredentials()),
                grpc.WithBlock(),
                grpc.FailOnNonTempDialError(true),
	}
conn, err := grpc.Dial(svcinfo, opts...)
`

### What did you expect to see?
grpc.Dial() should return with err=nil once connection is up.

### What did you see instead?
grpc.Dial() hangs forever. On checking logs, it is seen that connection is up and is in READY state.

Attaching grpc logs:
[xds_dial_block.txt](https://github.com/grpc/grpc-go/files/10989575/xds_dial_block.txt)

**Comment by easwars** [comment]
From your attached logs, I do not see your channel reaching `READY` state at all. I see the following to begin with:
```
2023/03/16 10:15:29 INFO: [core] [Channel #3] Channel created
2023/03/16 10:15:29 INFO: [core] [Channel #3] original dial target is: "xds:///prod-mobility-ns-mme1-svc-mbmdiampeer:16000"
2023/03/16 10:15:29 INFO: [core] [Channel #3] parsed dial target is: {Scheme:xds Authority: Endpoint:prod-mobility-ns-mme1-svc-mbmdiampeer:16000 URL:{Scheme:xds Opaque: User: Host: Path:/prod-mobility-ns-mme1-svc-mbmdiampeer:16000 RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}}
2023/03/16 10:15:29 INFO: [core] [Channel #3] Channel authority set to "prod-mobility-ns-mme1-svc-mbmdiampeer:16000"
```

And then `[Channel #4]` is the gRPC channel created to the xDS management server. *That* channel becomes READY and I can see a bunch of xDS resources being received. At this point, you will have to debug why your gRPC client is unable to connect to the backends specified in the received xDS resources. Unfortunately, this is not something that we can help you with, as we do not understand your deployment.

If you can get to the root of the issue and you still believe that gRPC is at fault, please feel free to open another issue with appropriate details.
