### ISSUE TITLE
Inconsistent Imports in status package

### ISSUE THREAD

**Issue by warmans** [grpc/grpc-go#6133]
### What version of gRPC are you using?

v1.53.0

### What version of Go are you using (`go version`)?

go version go1.20.2 linux/amd64

### What operating system (Linux, Windows, …) and version?

Ubuntu 18.04.6 LTS

### What did you do?

```go 
import (
	"google.golang.org/genproto/googleapis/rpc/errdetails"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

...

	details := []proto.Message{
		&errdetails.BadRequest{
			FieldViolations: []*errdetails.BadRequest_FieldViolation{
				{Field: field, Description: err.Error()},
			},
		},
		&errdetails.DebugInfo{
			Detail:       err.Error(),
		},
	}

	s, err := status.New(codes.InvalidArgument, http.StatusText(http.StatusBadRequest)).WithDetails(details...)
	if err != nil {
		return fmt.Errorf("failed to create error")
	}

...
```

### What did you expect to see?

No build error.

### What did you see instead?

```
service/grpc/errors.go:38:98: cannot use details (variable of type []protoreflect.ProtoMessage) as []protoiface.MessageV1 value in argument to status.New(codes.InvalidArgument, http.StatusText(http.StatusBadRequest)).WithDetails
```

---

I believe the problem is that `.WithDetails()` requires a `proto.Message` via `github.com/golang/protobuf/proto`, however this is deprecated so the `proto.Message`  that I'm trying to pass to the function is actually I'm using `google.golang.org/protobuf/proto` and Go doesn't allow this.

The internal `status` package should presumably be using `google.golang.org/protobuf/proto` instead.

Note:  it is possible to work around this problem by not using a slice and passing the arguments directly (because then it doesn't need to use the `proto.Message` interface at all. But this makes it hard to dynamically construct the debug data. Another workaround is just to import the old package name but my linter doesn't allow this.

**Comment by zasweq** [comment]
Unfortunately, that package uses a deprecated proto library. However, we can't break existing users of this API by changing the API type, so we have to leave it as such. If you want it to work, you will unfortunately have to use the old deprecated package :(.

**Comment by adriansmares** [comment]
You can also use [protoadapt](https://pkg.go.dev/google.golang.org/protobuf/protoadapt) starting with version `v1.30.0` of `protobuf-go`.
