### ISSUE TITLE
status.details is lost when client receives the error

### ISSUE THREAD

**Issue by wizo06** [grpc/grpc-go#6137]
### What version of gRPC are you using?
Whatever version this repository is using during the commit hash:
```
➜  grpc-go git:(master) ✗ git rev-parse HEAD
66e35339a4b76a807ab757d5897b9b8a3e554edc
```

I believe it's `v1.53.0`.

### What version of Go are you using (`go version`)?
```sh
$ go version
go version go1.18.1 linux/amd64
```

### What operating system (Linux, Windows, …) and version?
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

### What did you do?
Using the example provided in `examples/helloworld/`:

In the server, I modified the `SayHello()` method like so:
```diff
func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
	log.Printf("Received: %v", in.GetName())
+	st, _ := status.New(codes.InvalidArgument, "foobar").WithDetails(&errdetails.BadRequest_FieldViolation{
+		Field:       "bazqux",
+		Description: "field is required",
+	})
+	err := st.Err()
+	fmt.Printf("err: %v\n", err)
+	statusFromError := status.Convert(err)
+	fmt.Printf("statusFromError.Details(): %v\n", statusFromError.Details())
-	return &pb.HelloReply{Message: "Hello " + in.GetName()}, nil
+	return &pb.HelloReply{Message: "Hello " + in.GetName()}, st.Err()
}
```

In the client, I modified the `if err != nil` check like so:
```diff
	if err != nil {
+		fmt.Printf("err: %v\n", err)
+		st := status.Convert(err)
+		fmt.Printf("st.Details(): %v\n", st.Details())
		log.Fatalf("could not greet: %v", err)
	}
```

When I hit the server from the client, these are the logs that I see:

### What did you expect to see?

logs from client:
```
err: rpc error: code = InvalidArgument desc = foobar
statusFromError.Details(): [field:"bazqux" description:"field is required"]
```

### What did you see instead?

logs from server:
```
err: rpc error: code = InvalidArgument desc = foobar
statusFromError.Details(): [field:"bazqux" description:"field is required"]
```

logs from client:
```
err: rpc error: code = InvalidArgument desc = foobar
st.Details(): [proto: not found]
```

**Comment by zasweq** [comment]
Is the client side actually importing the proto representing the errors? See the example we have for this feature, we import this proto client side and this is how Details() knows the schema: https://github.com/grpc/grpc-go/blob/master/examples/features/errors/client/main.go#L29

**Comment by wizo06** [comment]
wow... so simply importing it, even if it's like this
```go
import (
	_ "google.golang.org/genproto/googleapis/rpc/errdetails"
)
```
allowed the print statement
```go
fmt.Printf("st.Details(): %v\n", st.Details())
```
in the client side to see the value inside `details`...

before import:
```
st.Details(): [proto: not found]
```
after import:
```
st.Details(): [field:"bazqux" description:"field is required"]
```

**Comment by arvindbr8** [comment]
Glad we could help you!
