### ISSUE TITLE
Create Stress test client for gRPC Go

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc-go#614]
The specification for the stress test client is at : https://github.com/grpc/grpc/blob/master/tools/run_tests/stress_test/STRESS_CLIENT_SPEC.md

FYI: The C++ stress test client is [here](https://github.com/grpc/grpc/blob/master/test/cpp/interop/stress_test.cc)

**Comment by tamird** [comment]
Why can't the c++ client be used?

**Comment by hsaliak** [comment]
@tamird we want to stress test the go client and report metrics from it.
