### ISSUE TITLE
Flaky test: Test/Span

### ISSUE THREAD

**Issue by zasweq** [grpc/grpc-go#6143]
https://github.com/grpc/grpc-go/actions/runs/4484710579/jobs/7885495142. Saw this locally as well

<img width="897" alt="Screenshot 2023-03-21 at 8 16 55 PM" src="https://user-images.githubusercontent.com/39203661/226770083-63b04945-50f1-4839-ada7-7fe88e589b05.png">

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/4558078233/jobs/8040534106?pr=6156

**Comment by arvindbr8** [comment]
https://github.com/grpc/grpc-go/actions/runs/4604540577/jobs/8135573933?pr=6035

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/4852541209/jobs/8647649957?pr=6234

**Comment by arvindbr8** [comment]
https://github.com/grpc/grpc-go/actions/runs/4872946643/jobs/8691838029?pr=6220

**Comment by dfawley** [comment]
https://github.com/grpc/grpc-go/actions/runs/4888003817/jobs/8725237470?pr=6241#step:8:329

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/4895584112/jobs/8741331999?pr=6256

**Comment by zasweq** [comment]
I'll get to this once I wrap up the custom lb stuff due. Seems to be happening quite a bit.

**Comment by zasweq** [comment]
The root cause for this test flake is that server spans have no guarantee of ordering with client spans emitted (and also not just that, but the RPC itself finishing). Fixing now.

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/actions/runs/4921153850/jobs/8790703654?pr=6224

**Comment by arvindbr8** [comment]
https://github.com/grpc/grpc-go/actions/runs/4940990791/jobs/8833539812?pr=6269
