### ISSUE TITLE
xDS: reconnect logic in xdsclient Transport

### ISSUE THREAD

**Issue by ppzqh** [grpc/grpc-go#6146]
When the stream is broken, the transport will reconnect and invoke `sendExisting`, in which the nonce map will be reset.
However, it seems that the request channel will not be cleared since the processing logic need to process requests to update the resource, nonce map. 
If an "old" ACK request is processed in `processAckRequest ` after `sendExisting`, it will set the global nonce to the nonce inside the request. Is this an expected result? 

sendExisting: https://github.com/grpc/grpc-go/blob/master/xds/internal/xdsclient/transport/transport.go#L460
processAckRequest: https://github.com/grpc/grpc-go/blob/master/xds/internal/xdsclient/transport/transport.go#L598

**Comment by zasweq** [comment]
Giving this to my teammate Easwar since he recently rewrote the xDS Client.

**Comment by easwars** [comment]
We handle this very specific case in these lines: https://github.com/grpc/grpc-go/blob/master/xds/internal/xdsclient/transport/transport.go#L584-L590

Please let me know if you still think there is an issue with the implementation. Thanks.

**Comment by ppzqh** [comment]
> We handle this very specific case in these lines: https://github.com/grpc/grpc-go/blob/master/xds/internal/xdsclient/transport/transport.go#L584-L590
> 
> Please let me know if you still think there is an issue with the implementation. Thanks.

oh I got it. Thanks for your explanation.
