### ISSUE TITLE
How to use observability 

### ISSUE THREAD

**Issue by loeffel-io** [grpc/grpc-go#6147]
I setup observability successfully but i don't know how to use the logger or tracer

This results in silence: 

```go
if err = observability.Start(ctx); err != nil {
    log.Fatalf("Unable to start gRPC observability: %s", err.Error())
}
defer observability.End()

var logger = grpclog.Component("observability")
logger.Info("youtube")
```

Would really love to get some informations about that @zasweq - ideally i would love to use the grpc middleware v2 zap logger but no glue if this is necessary or possible. 

I also use the Anthos Service Mesh - but no logs or trace labels are matching (i think, new in the anthos game)

Thank you very much 🙏

**Comment by loeffel-io** [comment]
after digging into it: i don't understand it 😄 

i setup the grpc middleware v2 zap logger like: https://github.com/uber-go/zap/issues/1095

Then i try to exclude the logging for the health server: 

```
"cloud_logging": {
   "client_rpc_events": [{
       "methods": ["grpc.health.v1.Health/*"],
       "exclude": true
   }],
   "server_rpc_events": [{
       "methods": ["grpc.health.v1.Health/*"],
       "exclude": true
   }]
}
```

but logging for the health server still appear - any info could help @zasweq 🙏

**Comment by zasweq** [comment]
Hello, again thanks for trying out observability! Observability is a GCP feature (exports data to GCP backends, needs to be run in a GCP environment for it to work correctly). See https://cloud.google.com/blog/products/networking/introducing-grpc-observability-for-microservices and https://cloud.google.com/stackdriver/docs/solutions/grpc for the public preview documentation.

**Comment by loeffel-io** [comment]
Thanks for you answer! 
I am using GCP GKE

**Comment by zasweq** [comment]
Hello, so for your logging issue, the configuration is precedence based. Thus, the first "event" (iterating from left to right) that hits is the event that determines the logic. Thus, if you had a configuration that specified something like * (log all) before your exclude and it hits that, logging lgoic would hit that event, and logs would be emitted. Another possibility is that the method name doesn't match the service/method name in your service, it doesn't hit that event, and it hits a later event configured which specifies to log. Can you please link your full config?
