### ISSUE TITLE
efficient broadcast 

### ISSUE THREAD

**Issue by xiang90** [grpc/grpc-go#618]
I have a use case to broadcast a message to large amount of client streams.

So I want to marshal the message once instead of number of clients times.
I am aware of there is sendMsg API and I can provide my own codec.

But in the sendMsg APi, it says
```
// SendMsg is called by generated code.
```

Does it mean that sendMsg should only be used by generated code? And gRPC-go might not maintain this API? Do you have any suggestion to achieve the efficient broadcast?

**Comment by iamqizhao** [comment]
I think you only need use grpc.WithCodec(...) to pass in your custom codec. Why do you want to change SendMsg. Do I miss anything?

**Comment by xiang90** [comment]
@iamqizhao I do not want to change sendMsg.

The generated Stream API is like Send(pbMessage). pbMessage is a struct type. For efficient broadcast, I want to send []byte directly. So I have to use sendMsg which accepts interface{} and my custom codec that can bypass encoding []byte by doing a type assertion.

My worry is that in the documentation it says sendMsg is used by generated code. So I wonder if I can use sendMsg directly and if gRPC go will maintain that API. If not, how shall I achieve same thing?

**Comment by iamqizhao** [comment]
I see. Yes, feel free to use that. that's the way to go. That API is pretty stable now.

**Comment by xiang90** [comment]
@iamqizhao Thank you!
