### ISSUE TITLE
Flaky test: TestFullHandshake

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#6182]
```
--- FAIL: TestFullHandshake (10.00s)
    alts_test.go:341: c.UnaryCall() failed: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "error reading server preface: EOF"
FAIL
```

https://github.com/grpc/grpc-go/actions/runs/4661138616/jobs/8250052573?pr=6181

**Comment by easwars** [comment]
This test was introduced in https://github.com/grpc/grpc-go/pull/6177.

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/4661138616/jobs/8250051999?pr=6181

**Comment by easwars** [comment]
@matthewstevenson88 : Could you please take a look as to why this test is flaky. Thanks.

**Comment by matthewstevenson88** [comment]
Sure thing, sorry about the flakiness. Let me take a look.

**Comment by easwars** [comment]
https://github.com/grpc/grpc-go/actions/runs/4670340563/jobs/8269950600?pr=6004
