### ISSUE TITLE
Got STREAM_CLOSED err code unexpectedly with the newly added handler transport 

### ISSUE THREAD

**Issue by iamqizhao** [grpc/grpc-go#619]
Saw some flakiness on Travis for TestHealthCheckOff in test/end2end_test.go for the handler transport. This test tries to access a non-registered service on the server side and expects to receive the codes.Unimplemented error. But I found when the handler server transport is used, the client may receive a RST_STREAM with STREAM_CLOSED err code, which is not expected. I saw this twice on travis yesterday but have not been able to reproduce on my desktop.

@bradfitz Can you take a look?

**Comment by bradfitz** [comment]
I haven't been able to reproduce it easily. Any tips?

**Comment by iamqizhao** [comment]
I saw it on travis when running in race mode with cpu 4. But even with that, I could not reproduce on my desktop with 1k run. In general, when is the STREAM_CLOSED err generated?

**Comment by iamqizhao** [comment]
So maybe running in race mode with multiple cores on a slow machine might help ...

**Comment by iamqizhao** [comment]
@bradfitz 

This happened again at https://travis-ci.org/grpc/grpc-go/jobs/120696193 today.

=== RUN   TestHealthCheckOff
--- FAIL: TestHealthCheckOff (0.13s)
	end2end_test.go:463: Running test in tcp-clear environment...
	end2end_test.go:463: Running test in tcp-tls environment...
	end2end_test.go:463: Running test in unix-clear environment...
	end2end_test.go:463: Running test in unix-tls environment...
	end2end_test.go:463: Running test in handler-tls environment...
	end2end_test.go:694: Health/Check(_, _) = _, rpc error: code = 13 desc = , want _, rpc error: code = 12 desc = unknown service grpc.health.v1.Health

**Comment by bradfitz** [comment]
I tried to reproduce it again yesterday but again couldn't.

I'll need to spend more time on this but I've been short on time.

Feel free to skip that test for that environment for now.

**Comment by iamqizhao** [comment]
This happened again at https://travis-ci.org/grpc/grpc-go/jobs/121308435. I am going to disable the test in the handler env. Hope you can have a fix soon.

**Comment by iamqizhao** [comment]
This happened again to a newly added test (if my memory works, I also ever ran into this when running the tests several thousand times inside google):

--- FAIL: TestStreamServerInterceptor (0.26s)
	end2end_test.go:465: Running test in tcp-clear environment...
	end2end_test.go:465: Running test in tcp-tls environment...
	end2end_test.go:465: Running test in unix-clear environment...
	end2end_test.go:465: Running test in unix-tls environment...
	end2end_test.go:465: Running test in handler-tls environment...
	end2end_test.go:1832: &{0xc82051d8c0}.StreamingInputCall(_) = _, rpc error: code = 13 desc = , want _, error code 7

https://travis-ci.org/grpc/grpc-go/jobs/129817040

I am going to disable this case also until you get time to fix it.
