### ISSUE TITLE
v1.54.0

### ISSUE THREAD

**Issue by liaokylin** [grpc/grpc-go#6205]
Please see the FAQ in our main README.md before submitting your issue.
v1.54.0 version how to suport etcd service discovery by server name

**Comment by arvindbr8** [comment]
Hi @liaokylin,

Please elaborate on your question. Seems like we are missing some context here. 

If your question is whether gRPC support etcd discovery service as a client. The answer is no. However you could try building a custom client (like the xDS client on our repo).

**Comment by arvindbr8** [comment]
It might be a good idea to check with the etcd team about this.
