### ISSUE TITLE
IncomingContext metadata seems override OutgoingContext metadata at the client

### ISSUE THREAD

**Issue by yhzs8** [grpc/grpc-go#6244]
As soon as `ctx = metadata.NewIncomingContext(ctx, md)` is invoked, it seems the `md` set here will be sent out as gRPC request HEADER instead of `ctx = metadata.NewOutgoingContext(ctx, md)` is defined later on the same `ctx`.

So seems `IncomingContext` is overriding `OutgoingContext` when sending out gRPC request at the client side?

Version: v1.54.0
Protobuf version: v1.5.3

**Comment by easwars** [comment]
> So seems IncomingContext is overriding OutgoingContext when sending out gRPC request at the client side?

That would be really bad if that happened. We don't have any reason to believe that something like that is happening though. Could you please provide us steps to reproduce this problem. Thanks.

**Comment by yhzs8** [comment]
Sorry, seems we have our own customized `UnaryClientInterceptor` which overrides OutgoingContext with IncomingContext...
