### ISSUE TITLE
Open Services for alternative Server implementations

### ISSUE THREAD

**Issue by HNoreick** [grpc/grpc-go#625]
The generated Register[SERVICENAME]Server Method should be accessible with an interface
type ServiceRegisterer Interface{
     RegisterService(sd *ServiceDesc, ss interface{})
}
Now the registerfunction is only accessible for grpc.Server and the serviceDescription is private. There is no chance for other Implementations to register.
I am not so lucky with the allinone concept of the Server and experiment with a Provider class for Services, Codecs and Compressors. If these types are accessible from a provider it is much easier to implement other servers.

**Comment by dsymonds** [comment]
I don't understand your use case. You want to write your own implementation of `*grpc.Server`? You don't have to use the RegisterFooServer function in the generated .pb.go files; that only provides a type-safe wrapper.

**Comment by HNoreick** [comment]
Thanks for that hint. I changed my workflow. If anything is in the same package, it works. But an open wrapper would be more comfortable.
No, I don't want to write my own implementation of grpc.Server, but i want access to the services from other servers. I have different use cases in mind and the services could be the one door any request has to pass. On the same maschine i would like to have a replacement for linked libraries an in web I want codecs for url encoding and jsonrpc. Even accesss to html pages could be validated with a service or rpc results could be transformed with an engine behind. That are different requirements the grpc.Server cannot deal with. The current design makes it nessesary to register any service, codec and compressor twice. I have to say that I am at a beginner state with just two weeks experience, unsure wether I have the right understanding for all concepts right now. I just can see the enormous potential in this solution.

**Comment by dsymonds** [comment]
Sorry, I still don't quite understand what you're trying to do. Are you wanting to make RPCs to another server? Or iterate over the servers that are registered on a `grpc.Server`?

Do you have a snippet of code that shows how you'd use what you originally asked for?

**Comment by HNoreick** [comment]
May be I did not find the right words for what i mean. My native language is german. 

> ..Or iterate over the servers that are registered on a grpc.Server?
Yes, I mean the services registered on a grpc.Server. I can't find a reason why the service registration is part of the server. I think registration should be an independent class accessed from the server then it would be accessible from other servers too. The current implementation forces redundant work for that. 

I separated the registration from the server with the (default-)option to register the names lowercase, so it fits better to web apis. 

I also register codecs and compressors[TODO] independent from the server.

With this separation I can build different execution shells without bindings to a specific server implementation. At the moment it is still experimental and poor documented.

What I originally asked for is unspectacular, I just register the service to a Provider instead of the grpc.Server. 

```
func NewProvider() *Provider {
	return &Provider{
		servicePool: make(map[string]*service),
		ServiceKeyConverter: strings.ToLower,
		codecPool: make(map[string]encoding.Codec),
	}
}
// The public methods
func (m *Provider) CodecByContentType( content_type string ) (encoding.Codec, error)...
func (m *Provider) DecoderByRequest( req *http.Request ) (encoding.Codec, error)...
func (m *Provider) EncoderByRequest( req *http.Request ) (encoding.Codec, error)...
func (m *Provider) Method(method_path string ) (*Method, error)..

func (m *Provider) RegisterCodecCreator(create_codec encoding.CodecCreator )..
func (m *Provider) RegisterService(sd *ServiceDesc, ss interface{})...

```

**Comment by dsymonds** [comment]
Registering a service implementation with a server is the only way that a server is going to know what RPC services to serve. And that's most of what the registration is: sticking info into a map so the server can dispatch incoming RPCs. If I understand, you're proposing pulling that map out into its own type so it can be reused. But it's trivial; other places can have their own map easily enough.

Why can't you register a service implementation with multiple servers?

**Comment by HNoreick** [comment]
> Why can't you register a service implementation with multiple servers?

Yes, I could , but i won't. The current grpc.Server leads me to reimlement the registration part and I implemented id reusable, because i think of multiple servers who can profit. I will separate the access and execution of rpcs from the server. On the web site i need the handeling of multiple codecs and internal I don't need (tcp/ip)/http at all.

**Comment by dsymonds** [comment]
Sorry, I don't think it's worth it to extract that trivial amount of code. It will only complicate the gRPC API for a niche use case that can trivially implement the same thing itself.
