### ISSUE TITLE
xds: Delete check for router filter being last in config selector

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#6259]
[gRFC A39](https://github.com/grpc/proposal/blob/master/A39-xds-http-filters.md) talks about gRPC's support for xDS HTTP filters. This gRFC was amended as part of [PR 250](https://github.com/grpc/proposal/pull/250). While we ended up implementing most of the changes mentioned in the amendment, we failed to implement the config time validation check to ensure that an LDS resource contains the `router` filter as the last filter.

HTTP filters received as part of an LDS resource are processed in this function: https://github.com/grpc/grpc-go/blob/417cf846073b216abc00f5d15c291a3eba5fd00d/xds/internal/xdsclient/xdsresource/unmarshal_lds.go#L195

While we do validate that the filter chain is not empty and that the last filter in the chain is a terminal filter, we *are not currently* validating that the last filter is in-fact the `router` filter.

The `router` filter package does provide a utility function to check if a filter is the `router` filter: https://github.com/grpc/grpc-go/blob/417cf846073b216abc00f5d15c291a3eba5fd00d/xds/internal/httpfilter/router/router.go#L42

We can use that function here to ensure that the `router` filter is present in the list *and* that it is the last filter in the list.

**Comment by easwars** [comment]
@Aditya-Sood

**Comment by Aditya-Sood** [comment]
thanks @easwars, I'll get started on this

**Comment by Aditya-Sood** [comment]
hi @easwars 
so I understand that we can additionally check for the terminal filter to also be a router filter as follows:
```
        if !ret[i].Filter.IsTerminal() {
                return nil, fmt.Errorf("http filter %q is not a terminal filter", ret[len(ret)-1].Name)
        }
+       if !router.IsRouterFilter(ret[len(ret)-1].Filter) {
+               return nil, fmt.Errorf("http filter %q is not a router filter", ret[len(ret)-1].Name)
+       }
```

however I'm still trying to figure out how to write the testcase for it

the `IsRouterFilter()` just checks whether the filter value passed can be asserted as a `router.builder` type (which in turn is an empty struct being used as a method receiver)

I found [this testcase](https://github.com/grpc/grpc-go/blob/417cf846073b216abc00f5d15c291a3eba5fd00d/xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go#L1117-L1143) corresponding to the `not a terminal filter` test, trying to understand how to modify it for 'not a router filter` test

would you happen to have any pointers for me on how to do this?

**Comment by Aditya-Sood** [comment]
Thank you, this is really helpful
One quick query - do we need to create a `terminalNonRouterHTTPFilter` as well? (To cover the test case of a terminal filter failing the `IsTerminal()` method)

**Comment by easwars** [comment]
> Thank you, this is really helpful One quick query - do we need to create a `terminalNonRouterHTTPFilter` as well? (To cover the test case of a terminal filter failing the `router.IsRouterFilter()` method)

I thought that was the only test case to add. What other cases were you planning to add?

**Comment by zasweq** [comment]
See this check: https://github.com/grpc/grpc-go/pull/4676/files#diff-9640c5b5baca36d84239eb2b3f001f169f596c89f84382eeba7abe8bbd4c5d9bR258, and unit tests here: https://github.com/grpc/grpc-go/pull/4676/files#diff-88532d359ba36ae99c09b45ae55f3788a9c528fea2472a6f1f969cbd166855f6R27

**Comment by easwars** [comment]
Currently the config selector is checking if the last filter is the router filter, which doesn't seem like the correct place to have that check. If we at all should have that check, it should be in the xds client.

**Comment by zasweq** [comment]
I don't see an issue with an explicit check for the router filter. However, if what I mentioned earlier was correct (router is only terminal filter), router filter -> terminal filter, so the check does technically encapsulate "in face the router filter" and not "any terminal filter"

**Comment by easwars** [comment]
@Aditya-Sood : Sounds good.

**Comment by Aditya-Sood** [comment]
Raised #6281 for the Router filter check

Also regarding the `errHTTPFilter`:
> errHTTPFilter - Surprisingly not used anywhere in the codebase except in the init() of unmarshal_lds_test.go - might have to create tests for it?

Shall I create test cases for this as well in a separate PR?

**Comment by Aditya-Sood** [comment]
@zasweq could you confirm if this is the cleanup you are referring to be done as part of this PR?
https://github.com/grpc/grpc-go/pull/6248#issuecomment-1568873740

**Comment by Aditya-Sood** [comment]
hi @zasweq @easwars 
I believe #6248 also fixes this issue, based on [these changes](https://github.com/grpc/grpc-go/pull/6248/files#diff-645ef5bd7a46bc17531453844144c0ce9418b3dd64d33a3f1930fbdf32a4de70L283-L287)?
forgot to mention this ticket in that PR

**Comment by zasweq** [comment]
Yeah, that is :). Closing this issue.
