### ISSUE TITLE
grpc_testing not included in v1.55.0 release

### ISSUE THREAD

**Issue by DGuhr** [grpc/grpc-go#6264]
Hey 👋 we are using a package that depends on grpc_testing - https://pkg.go.dev/google.golang.org/grpc/test/grpc_testing and after the latest dependency bump to  v1.55.0 go mod tidy breaks as the testing package is not included in the latest release. Was that on purpose? If so, what should one use instead? 

Context: https://github.com/authzed/grpcutil uses grpc_testing, we use the util in our service.

**Comment by zasweq** [comment]
Oh ok interesting. Sounds good to me. Hope it goes well :).
