### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by ggitau** [grpc/grpc-go#628]
Hi?
Is there a way to generate interfaces for the rpc method parameter types or cause getters and setters to be generated for those message types?

**Comment by iamqizhao** [comment]
I do not understand what you want to have. Can you elaborate?

**Comment by devoid** [comment]
Hi @iamqizhao, I may be able to explain the use case. I am already using the getter functions generated by `protoc-gen-go` to define interfaces that can access common data shared across multiple protobuf types:

```
message GetUserResponse{
    bool valid = 1;
    // ... etc.
}

message GetGroupResponse{
    bool valid = 1;
    // .... etc.
}
```
And then in a separate Go package:
```    
type maybeValid interface {
    GetValid() bool
}

func IsValid(response interface{}) bool {
    if t, ok := response.(maybeValid); ok {
        return t.GetValid()
    }
    return false
}

```

And now I can read multiple different protobuf messages with the same function! But I can't create ways to write into multiple different protobuf messages. Thats where having setter functions would be helpful:

```
type invalidator interface {
    SetValid(bool)
}

func Invalidate(response interface{}) {
    if t, ok := response.(invalidator); ok {
       t.SetValid(false)
    }
}
```
