### ISSUE TITLE
Interop: implement rpc-behavior server side

### ISSUE THREAD

**Issue by zasweq** [grpc/grpc-go#6288]
Right now, rpc-behavior is only supported for C++ and Java. For tests which require rpc-behavior, interop tests overwrite server side to Java (see: https://github.com/grpc/grpc/blob/master/tools/run_tests/xds_k8s_test_driver/tests/outlier_detection_test.py#L58). It would be nice to have this support in Go as well so we can test our interop Go client with a Go server.

**Comment by zasweq** [comment]
See: https://github.com/grpc/grpc/commit/be99673d069217def9036cc9ae0346da324ba373 for commit which added in C++.

**Comment by Aditya-Sood** [comment]
hi @dfawley @zasweq @sergiitk 
is the fix for this already in-progress? if not I can pick the ticket

**Comment by dfawley** [comment]
No, this issue is unowned and not in progress. I'll assign it to you, thanks!

**Comment by Aditya-Sood** [comment]
hi @zasweq and @dfawley 
based on the CPP commit shared above, I've been able to structure the helper methods [like so](https://github.com/Aditya-Sood/grpc-go/blob/867ceb73b865a71b7badb3ae784c7899d86515b5/interop/xds/server/server.go#L90-L118)

however there's a difference in the signature of the `UnaryCall()` method between the [CPP implementation](https://github.com/grpc/grpc/blob/be99673d069217def9036cc9ae0346da324ba373/test/cpp/interop/xds_interop_server.cc#L113-L125) and [ours in grpc-go](https://github.com/Aditya-Sood/grpc-go/blob/867ceb73b865a71b7badb3ae784c7899d86515b5/interop/xds/server/server.go#L85-L88) - the former returns the Status Code in addition to setting the server ID and hostname, while the latter returns an error

hence could you please explain how the three possible return values of `getStatusForRPCBehaviorMetadata()` (`nil`, `InvalidArgument` and `codes.Code(errCode)`) should affect the response of `UnaryCall()`?

**Comment by Aditya-Sood** [comment]
hi @dfawley @zasweq 
could you please clarify on the above?

**Comment by Aditya-Sood** [comment]
hi @easwars 
would you be able to help with the above query? I am currently blocked for the fix because of it 

also is there a slack channel/mailing list where I could reach out to other maintainers for queries like this?

**Comment by easwars** [comment]
> also is there a slack channel/mailing list where I could reach out to other maintainers for queries like this?

We do have a mailing list at `grpc-io@googlegroups.com`, but posting your questions/concerns here on our repo on specific issues/PRs would get you better latency :)

> however there's a difference in the signature of the UnaryCall() method between the [CPP implementation](https://github.com/grpc/grpc/blob/be99673d069217def9036cc9ae0346da324ba373/test/cpp/interop/xds_interop_server.cc#L113-L125) and [ours in grpc-go](https://github.com/Aditya-Sood/grpc-go/blob/867ceb73b865a71b7badb3ae784c7899d86515b5/interop/xds/server/server.go#L85-L88) - the former returns the Status Code in addition to setting the server ID and hostname, while the latter returns an error

This is how I see the difference in the API between C++ and Go
- In C++, the rpc method handler has the following signature:
  - accepts a context, a request message, and a response message
    - the response message is an out parameter and is to be modified by the method handler 
  - returns a grpc status
- In Go, the rpc method handler has the following signature:
  - it accepts a context and a request message
  - it returns a response message and an `error`
    - rpc handlers should generally wraps their errors using the `status` package (thereby, returning a status code and an error message)
    
 Hope this helps.

**Comment by easwars** [comment]
With respect to the changes to be made here, the `UnaryCall` rpc method handler needs to do the following:
- Look for incoming metadata in the context with a key of `rpc-behavior`. You could use this function to get to the incoming metadata given the rpc context: https://pkg.go.dev/google.golang.org/grpc@v1.57.0/metadata#FromIncomingContext
- The value of the metadata would be a slice of string
- Iterate through this slice, and for the first value that is of the form `error-code-N` where `N` is the error code
  - ensure that the returned status is of value `N` and error string "Rpc failed as per the rpc-behavior header value: error-code-N"
  
@zasweq : Could you please confirm if my reading of C++ is good or point @Aditya-Sood to some place where the expected change is documented. Thanks.

**Comment by zasweq** [comment]
I don't know what the exact specification of the behavior server side (I don't think the spec is too specific on the behaviors), but c++ has an error condition *in the case where a metadata value starts with error-code-, but N is not correctly formatted*: https://github.com/grpc/grpc/pull/32810/files#diff-03f692bf86017755496ec7bfe07c2e51bcedc947df5156738794c388c2cf0dceR99, where it returns a status.INVALID_ARGUMENT, with an error message: "Invalid format for rpc-behavior header: header-value". If none of the rpc-behavior values are set (with the prefix "error-code-"), the c++ implementation simply ignores it, and returns an OK status: https://github.com/grpc/grpc/pull/32810/files#diff-03f692bf86017755496ec7bfe07c2e51bcedc947df5156738794c388c2cf0dceR118. I don't know if this follows some sort of specific technical spec, but for the sake of interop consistency I think it would be good to keep it consistent with the c++ implementation.

**Comment by zasweq** [comment]
This follows the Java implementation too, so I guess we should keep consistent: https://github.com/grpc/grpc-java/blob/42b4c61d5e869b1534808204bc71df84720f5087/interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java#L379.

**Comment by zasweq** [comment]
Both Java and C++ are correct. I found this spec for the rpc-behavior server side: https://github.com/grpc/grpc/pull/29475/files. So what both the languages are doing is correct.

**Comment by Aditya-Sood** [comment]
thanks a lot @easwars and @zasweq, I'll resume working on this

**Comment by Aditya-Sood** [comment]
hi @easwars @zasweq
I think I have already incorporated most of the above steps in a [previous commit](https://github.com/grpc/grpc-go/commit/867ceb73b865a71b7badb3ae784c7899d86515b5)

and for my query on "how to map the `getStatusForRPCBehaviorMetadata()` return `Status` value  to an `error`", I'm now using the `status.Err()` method to represent the Status response as an error, as instructed above by @easwars  

([link to changes](https://github.com/Aditya-Sood/grpc-go/blob/6288-interop-rpc-behaviour/interop/xds/server/server.go#L85-L97)) - they run fine with the existing test cases
kindly let me know if this looks good, I'll start on the rpc-behavior test case after that

**Comment by easwars** [comment]
I don't see a pull request. Could you please send a PR for us to start reviewing. Thanks.
