### ISSUE TITLE
Know What Compression Was Used In A Stream

### ISSUE THREAD

**Issue by hshamji** [grpc/grpc-go#6289]
Hello,

I'm trying to build a grpc proxy in go, one that can proxy compressed messages without decompressing or unmarshalling them (for latency purposes).

It seems that (de)compression is deeply built into the client/server design it is hard to operate on them separately. I've been playing with [this grpc-proxy repo](https://github.com/mwitkow/grpc-proxy/blob/master/proxy/handler.go#L58), and trying to couple it with the idea of a NoOpGzipCompressor (ie. registering a NoOp compressor in the proxy layer to replace the actual "gzip", so that the decompress/compress steps are just passthroughs.

The problem is knowing whether compression was actually applied to a stream. This information appears to sit [at the transport layer](https://github.com/grpc/grpc-go/blob/master/internal/transport/transport.go#L345), and is not accessible at the ServerStream layer. I need to know this so that client part of the proxy can apply the NoOpGzipCompressor to the proxied request (ie. going to the backend) so that it can be properly decompressed there.

Is there a way to know whether (and which type of) compression was used on a stream? Or a simpler way overall to accomplish this?

Thank you,

**Comment by dfawley** [comment]
In this case, you would probably have the most success by making or using a generic HTTP/2 proxy, rather than doing it via a gRPC application.  It seems none of the gRPC libraries (incl. Java/C) have a way to determine what compression was used at the application level.  cc @ejona86 @markdroth

**Comment by hshamji** [comment]
> In this case, you would probably have the most success by making or using a generic HTTP/2 proxy, rather than doing it via a gRPC application. It seems none of the gRPC libraries (incl. Java/C) have a way to determine what compression was used at the application level. cc @ejona86 @markdroth

Thanks for your reply, @dfawley . The HTTP/2 proxy sounds like a good suggestion - I can appreciate adding something like a `GetCompressor` method here would pierce/blur levels of abstraction.
