### ISSUE TITLE
Open Telemetry Support 

### ISSUE THREAD

**Issue by joybestourous** [grpc/grpc-go#6305]
Hi folks, 
In light of the announcement of [sunsetting OpenCensus](https://opentelemetry.io/blog/2023/sunsetting-opencensus/), what are the plans to move to OpenTelemetry in grpc-go? It seems like this is being added to the [grpc core roadmap](https://github.com/grpc/grpc/issues/32508), but some sort of timeline would be incredibly helpful to us. Thanks!

**Comment by arvindbr8** [comment]
Hi, 

Thanks for your interest! OT is in our roadmap. We are hashing out the cross language design at the moment. 
Please keep a lookout for our Release Notes and/or gRPC/GCP blogs to be notified. 


thanks!
