### ISSUE TITLE
Goroutine leak in glog consider switching to klog

### ISSUE THREAD

**Issue by janisz** [grpc/grpc-go#6316]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?

1.55.0

### What version of Go are you using (`go version`)?

1.20.3

### What operating system (Linux, Windows, …) and version?
Linux 
### What did you do?
After udpating grpp from 1.54 to 1.55 leak tests started to fail due to leaking gorutine in glog.
### What did you expect to see?
No gorutines leak. 
### What did you see instead?
Leak

I think the best option will be to switch from glog to klog (it has a fix for this kind of errors)

- https://github.com/stackrox/stackrox/actions/runs/5053758960#summary-13719862453
- https://github.com/stackrox/stackrox/pull/6121
- https://github.com/kubernetes/klog/pull/293
- https://github.com/grpc/grpc-go/issues/6048

**Comment by dfawley** [comment]
Can you provide more info & a repro case for the leak you're seeing with glog?

**Comment by janisz** [comment]
It happens in tests as there is no way to stop this gorutine 
```
common/compliance: 2023/05/24 10:35:44.514084 auditlog_manager_impl.go:171: Info: Adding node `new-node` as an eligible compliance node for audit log collection
    node_inventory_handler_test.go:53: found unexpected goroutines:
        [Goroutine 22 in state select, with github.com/golang/glog.(*fileSink).flushDaemon on top of the stack:
        goroutine 22 [select]:
        github.com/golang/glog.(*fileSink).flushDaemon(0x5b0a478)
        	/go/pkg/mod/github.com/golang/glog@v1.1.0/glog_file.go:345 +0x170
        created by github.com/golang/glog.init.1
        	/go/pkg/mod/github.com/golang/glog@v1.1.0/glog_file.go:163 +0x29d

```
I've whitelisted this example so I think we can close it
