### ISSUE TITLE
Potential deadlock in server.go

### ISSUE THREAD

**Issue by hhheiaenia** [grpc/grpc-go#6322]
I notice that all the s.cv.Wait() and s.cv.Broadcast() are protected by the mutex lock s.mu in https://github.com/grpc/grpc-go/blob/master/server.go#LL1872C14-L1872C14.   
So I doubt whether this situation can cause a deadlock. 

Maybe what I said is not right, thank you for taking a look.

**Comment by dfawley** [comment]
`Wait` gives up the lock at the start.  I don't think this is a problem, thanks.
