### ISSUE TITLE
A potential data race in grpclb/grpclb_remote_balancer.go

### ISSUE THREAD

**Issue by yanke-xu** [grpc/grpc-go#6325]
I found a potential data race based on the code analysis. Specifically, there are two confilicting operations on the field "lb", where the read operation at: grpclb/grpclb_remote_balancer.go:345, and the write operation at: grpclb/grpclb_remote_balancer.go:338.   It will cause a data race when the two functions where the two operations are located are called in parallel.

**Comment by dfawley** [comment]
Please fill in similar information as requested in #6326.

**Comment by dfawley** [comment]
I don't see any issue here.  If you can be much more specific, and ideally reference master@HEAD or something more recent, then we could investigate further.
