### ISSUE TITLE
allow stream carry custom metadata after stream is built

### ISSUE THREAD

**Issue by fengyeall111** [grpc/grpc-go#6333]
### Use case(s) - what problem will this feature solve?
message level loadBalance,not only stream level loadbalance 
Now grpc stream must encode metadata in http2 header frame. For bidistream（the same as clientstream）we can not send extra metadata after the stream is built: grpc encode customdata in  http2 header frame, http2 does not allow send header frame before  send frame end flag. 
### Proposed Solution
allow stream carry custom metadata after stream is built. metadata is bind to http2 data frame, so,we can have more chance to pass metadata.
### Alternatives Considered
This would be useful for traffic management and loadbalance:unshackled from HTTP/2 header frame restrictions.
Think about this scene:
we want to send msg to some pod byBidiStream grpcCall, we just want to do loadbalance for msg，not in stream level:we must build many streams with pods in client side. This can not be spilted in service mesh.

**Comment by dfawley** [comment]
What you're asking for is a spec change of gRPC.  You can suggest such things at github.com/grpc/grpc, but I don't think we'd be able to accommodate this idea.  You're better off using a streaming RPC with a message type that allows you to add the additional information needed in each message.

**Comment by fengyeall111** [comment]
> What you're asking for is a spec change of gRPC. You can suggest such things at github.com/grpc/grpc, but I don't think we'd be able to accommodate this idea. You're better off using a streaming RPC with a message type that allows you to add the additional information needed in each message.

I would reopen this at github.com/grpc/grpc. BidiStream can do other thing, not only a single stream to endpoint for client.Every msg that a client bidiStream sends does not care about peer endpint, just care about return message in the original way if response is needed
