### ISSUE TITLE
backoff retried for gRPC client

### ISSUE THREAD

**Issue by maha-hajja** [grpc/grpc-go#6348]
I'm working on having a bi-directional stream between a gRPC server and client, and want the client to reconnect if the server went down for a while and came back up.
the client dial options are:
> 	dialOptions := []grpc.DialOption{
		grpc.WithContextDialer(d.dialer),
		grpc.WithTransportCredentials(insecure.NewCredentials()), // todo: will use mTLS with connection
		grpc.WithConnectParams(grpc.ConnectParams{Backoff: backoff.DefaultConfig}),
	}

I wanted to spawn a go routine that will monitor the connection status and use `WaitForStateChange` when the connection is down, so until the status changes back to `READY`, but the retries are not happening unless an RPC is called.
So, is the only way to trigger a retry is by calling an RPC? and if calling an RPC will trigger a retry each time, then what's the point of using the default config for `backoff.DefaultConfig` since it's not gonna retry by its own?

**Comment by dfawley** [comment]
The backoff config is used to control how quickly the client is allowed to re-attempt connections to backends that do not connect.  The defaults here are fine for most people but you can make the backoff longer to avoid overwhelming servers, etc.

I don't think you need to do anything you're talking about here, based on what I think you're saying you're trying to do.  Just start the bidi stream, and whenever it dies, create it again.  The connection to the server will be recreated on its own if you do this.
