### ISSUE TITLE
Proper way to debug outgoing metadata?

### ISSUE THREAD

**Issue by pcj** [grpc/grpc-go#6368]
With `GODEBUG=http2debug=2` outgoing / request headers are not printed but rather summarized as:

```
2023/06/12 17:08:46 http2: Framer 0x140001382a0: wrote HEADERS flags=END_HEADERS stream=1 len=925
```

By contrast, incoming / response headers are individually printed.

```
2023/06/12 17:08:46 http2: decoded hpack field header field ":status" = "200"
2023/06/12 17:08:46 http2: decoded hpack field header field "content-type" = "application/grpc"
2023/06/12 17:08:46 http2: decoded hpack field header field "grpc-accept-encoding" = "identity, deflate, gzip"
```

What's the proper way to debug?

Workaround is to patch `internal/transport/controlbuf.go`:

```go
func (l *loopyWriter) writeHeader(streamID uint32, endStream bool, hf []hpack.HeaderField, onWrite func()) error {
	if onWrite != nil {
		onWrite()
	}
	l.hBuf.Reset()

	var debugHeaders bool
	if godebug, ok := os.LookupEnv("GODEBUG"); ok && godebug == "http2debug=2" {
		debugHeaders = true
	}
	for _, f := range hf {
		if debugHeaders {
			log.Println("grpc header field:", f.Name, f.Value)
		}
		
```

related: https://github.com/golang/go/issues/46339

**Comment by easwars** [comment]
`GODEBUG=http2debug=2` is provided by the Golang http package and not by gRPC-Go. If you would like to see extended debugging information output from gRPC-Go, you could send us a PR with `Debug` logs and guarded by a high verbosity level. We would be happy to review it. Thanks.
