### ISSUE TITLE
OpenTelemetry/OpenCensus

### ISSUE THREAD

**Issue by joybestourous** [grpc/grpc-go#6375]
Hey folks,

Regarding #6305: Will we be able to rely on the [same](https://github.com/census-instrumentation/opencensus-go/blob/v0.24.0/plugin/ocgrpc/client_metrics.go#L39) [metrics](https://github.com/census-instrumentation/opencensus-go/blob/v0.24.0/plugin/ocgrpc/server_metrics.go#L42) existing in the coming OpenTelemetry instrumentation as in OpenCensus? We plan to use OpenCensus until grpc has OpenTelemetry support, and we'd like to ensure the inevitable migration to OpenTelemetry wont cause friction for customers who rely on these metrics for their dashboards. Thanks!

**Comment by zasweq** [comment]
We will continue to support the OpenCensus metrics, and try to remove ambiguities in naming for the future OpenTelemetry support. Yes, we understand this will be a friction point for our users, and we as a gRPC team have come up with a few migration strategles that we will inform our users of in the future that users can choose between.

**Comment by joybestourous** [comment]
Thanks for clarification! So to make sure I'm understanding correctly, the metric names and/or the information itself may change with OpenTelemetry support, but you folks will offer migration strategies if they do?

**Comment by zasweq** [comment]
The information from OpenCensus metrics will be kept and moved over to OpenTelemetry, and information same, but we might give more descriptive/technically specific and correct names. However, this is a whole new system that we are interfacing with, and also will require a new components within our code. Thus, for telemetry backends and monitoring systems that use exported metrics from our code, we have developed strategies for the transition between the OpenCensus system/ecosystem and OpenTelemetry.

**Comment by joybestourous** [comment]
Got it. Thanks for following up!
