### ISSUE TITLE
Queuing delay/waiting time metric for go-grpc server overload control

### ISSUE THREAD

**Issue by Jiali-Xing** [grpc/grpc-go#6376]
Description:
When running microservices under heavy load, the average or maximum queuing delay is commonly used as a signal of congestion (Dagor 2018, Breakwater 2020). I have been attempting to collect this information for overload control on a go-grpc server. Since goroutines are scheduled by Go runtimes, I have tried using the waiting time information for goroutines. However, the `/sched/latencies:seconds` metric seems to be inaccurate. I calculate the 90th percentile latency from `/runtime/metrics`, but it reports sub-millisecond latency even when the system is overloaded with latencies exceeding 100 milliseconds.

My question is:
1. Where does the delay occur in the case of an incast of unary gRPC calls from tools like `ghz` and when the server side consists of **one** instances of `GreetingServiceServer`, with no computation involved. As shown in the figure below, there's is a huge gap both horizontally (`/sched/latencies:seconds` is 0.5 second later than e2e measures) and vertically (10x smaller in the latency scale)
2. Is there a way to measure the queuing time between `when a request first came` and `when it starts running` in go-grpc servers? Does `grpc.server` provide any API for it? (I could not find any)
3. Am I missing something? Would a distributed tracing tool help with it? 

![baseline queuing-delay-10ms-no-compute](https://github.com/grpc/grpc-go/assets/53011060/8d02963b-fb06-4b40-aa50-0f405a5877a7)

Thank you. I've been trying hard to look for relevant information... Any reference would be appreciated.

**Comment by arvindbr8** [comment]
If you are trying to look for signals of congestions / load reports on the server, gRPC supports [Open Request Cost Aggregation (ORCA)](https://pkg.go.dev/google.golang.org/grpc/orca). gRPC ORCA support provides two different ways to report load data to clients from servers: out-of-band and per-RPC. Out-of-band metrics are reported regularly at some interval on a stream, while per-RPC metrics are reported along with the trailers at the end of a call. Both of these mechanisms are optional and work independently.

The full ORCA API documentation is available here: https://pkg.go.dev/google.golang.org/grpc/orca

Also please take a look at [our example](https://github.com/grpc/grpc-go/tree/master/examples/features/orca) in our repo for more help. 

Let us know if that clarifies your question.

**Comment by easwars** [comment]
> Is there a way to measure the queuing time between when a request first came and when it starts running in go-grpc servers? Does grpc.server provide any API for it? (I could not find any)

We have a stats handler API that you can enable on your server. See: https://pkg.go.dev/google.golang.org/grpc#StatsHandler. Once you register your own stats handler, you will receive events for connection start/end, RPC start/end, send/recv of headers/trailers/data etc. Maybe this is useful for you.

**Comment by Jiali-Xing** [comment]
> The full ORCA API documentation is available here: https://pkg.go.dev/google.golang.org/grpc/orca
> 
> Also please take a look at [our example](https://github.com/grpc/grpc-go/tree/master/examples/features/orca) in our repo for more help.

Thank you very much, @arvindbr8, for your references! I've taken a quick look at the [doc](https://pkg.go.dev/google.golang.org/grpc/orca), [example](https://github.com/grpc/grpc-go/tree/master/examples/features/orca), and repo. Amazing work indeed. Yet, I think the use case of ORCA is slightly different from my work. ORCA primarily focuses on reporting metrics to clients, such as for better Load Balancing.

In our case, we are specifically interested in obtaining instant signals within the server itself to detect overload quickly. For example, our overload control system needs to be aware of overload conditions even before the request RT (response time), which may involve multiple downstream components, starts to increase.

The metrics provided in ORCA are truly inspiring. I found the `queueSize` metric in the [documentation](https://github.com/grpc/proposal/blob/master/A51-custom-backend-metrics.md), and upon searching it in the [repository](https://github.com/grpc/grpc-go/search?q=queue+path%3A%2Forca%2F&type=code), it appears to be a customized metric example or placeholder.

**Comment by Jiali-Xing** [comment]
> Once you register your own stats handler, you will receive events for connection start/end, RPC start/end, send/recv of headers/trailers/data etc.

Thank you @easwars! It looks very relevant. I want to learn more about it, is there any other resources or examples talking about it? 
I found one example from [the loadtesting package I used](https://github.com/bojand/ghz/blob/fd72421f2ff2493a77dee3c17b0f9178eb52dbf9/runner/stats_handler.go#L37C14-L37C17). It was actually based on the [stats.Handler](https://pkg.go.dev/google.golang.org/grpc/stats#Handler), which I believe are the same thing as [statshandler](https://pkg.go.dev/google.golang.org/grpc/examples/features/stats_monitoring/statshandler) and [StatsHandler](https://pkg.go.dev/google.golang.org/grpc#StatsHandler). I see them used interchangeably in docs and grpc repos.

**Comment by easwars** [comment]
We do have an example here: https://github.com/grpc/grpc-go/blob/master/examples/features/stats_monitoring/README.md

And we have real implementations of the stats handler interface in our observability offering. You can see the client stats handler here: https://github.com/grpc/grpc-go/blob/11feb0a9afd844fd2ab1f18dca02ad6a344b21bf/stats/opencensus/opencensus.go#L176 and the server stats handler here: https://github.com/grpc/grpc-go/blob/11feb0a9afd844fd2ab1f18dca02ad6a344b21bf/stats/opencensus/opencensus.go#L214

Hope this helps.

**Comment by easwars** [comment]
Is there anything else pending in this issue or has your question been answered satisfactorily?

**Comment by Jiali-Xing** [comment]
Thank you for references @easwars! 
I still have a question with regard to the time scope of the `serverStatsHandler`, does it provide up-to-date telemetry of the rpc calls or does it sample once in a while, like those in the `runtime/metrics`

**Comment by Jiali-Xing** [comment]
Also, I read the README and the examples such as `(ssh *serverStatsHandler) HandleRPC` in [opencensus.go](https://github.com/grpc/grpc-go/blob/11feb0a9afd844fd2ab1f18dca02ad6a344b21bf/stats/opencensus/opencensus.go#L214), I'm not sure if I understand its potential at measuring the queuing delay of each RPC. 
From what I understand, it definitely gives the end-to-end latency with [stats.Begin and stats.End](https://github.com/grpc/grpc-go/blob/8e9c8f8e7133eb7ed64438837636dae2c5d92ce6/stats/opencensus/stats.go#L181) etc, but for the RPC waiting in one microservice, it seems not to have a method to measure/time the server-side queuing delay with StatsHandler?

**Comment by easwars** [comment]
> I still have a question with regard to the time scope of the serverStatsHandler, does it provide up-to-date telemetry of the rpc calls or does it sample once in a while, like those in the runtime/metrics

The callbacks are invoked for every RPC and for every header/trailer/payload sent or received.

**Comment by easwars** [comment]
> but for the RPC waiting in one microservice

You might want to checkout the `orca` package for sending custom metrics from the server to the client: https://pkg.go.dev/google.golang.org/grpc@v1.56.2/orca
