### ISSUE TITLE
generate MutableXX for struct filed in message

### ISSUE THREAD

**Issue by ethanvc** [grpc/grpc-go#6380]
If we have the message below:
```
message Req{
    string trace_id = 1;
    string abc = 2;
}
message Header{
    Req req = 1;
}
```
### Use case(s) - what problem will this feature solve?
for now, to set field trace_id or abc, i have to check nil for req every time. like this:
```
if xxx{
    if header.Req == nil{
        header.Req = &Req{}
    }
    header.Req.TraceId = "xxxx"
}
if xxxx{
    if header.Req == nil{
        header.Req = &Req{}
    }
    header.MutableReq().Abc = "abc"
}
```

### Proposed Solution
generate following method just like C++ generated code(https://protobuf.dev/reference/cpp/cpp-generated/):
```
func (h*Header) MutabeReq()*Req{
    if h.Req == nil{
        h.Req = &Req{}
    }
    return h.Req
}
```
Now, we can write code like this:
```
if xxx{
    header.MutableReq().TraceId = "xxxx"
}
if xxxx{
    header.MutableReq().Abc = "abc"
}
```
This will make code more readable.

**Comment by zasweq** [comment]
Hello, this repo/our team doesn't own the proto compiler :). Also, generating nil vs. a pointer to allocated heap memory seems correct behavior in the Go version. This is WAI, and there is a logical distinction between unset -> nil and set but zero value.
