### ISSUE TITLE
github.com/golang/protobuf deprecated

### ISSUE THREAD

**Issue by zlietapki** [grpc/grpc-go#6383]
### Use case(s) - what problem will this feature solve?

github.com/golang/protobuf is deprecated for 2 years  
<https://github.com/golang/protobuf/blob/master/go.mod>

### Proposed Solution

Use the "google.golang.org/protobuf" module instead.

### Additional Context

So maybe it's time to update code

**Comment by easwars** [comment]
The old protobuf repo is part of our public facing API, and we don't want to change it unless it provides tangible benefits which outweigh the cost our users have to pay when we change our API.

We have attempted moving to the new protobuf repo in the past, and it is non-trivial. If you have concrete ideas about how this could be done, please let us know. I'm closing this issue for now. Thanks.
