### ISSUE TITLE
Adding a nil check for LocalAddr() in gRPC Authz Interceptor

### ISSUE THREAD

**Issue by DawtDawt** [grpc/grpc-go#6384]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?
- Integrate gNSI interceptor with allow-all protocol policy into gRPC.
- Set up a gRPC tunnel from server to client defined in [here](https://pkg.go.dev/github.com/CustomPoint/grpc-tunnel)
- The client uses the tunnel but sets the LocalAddr() to nil [here](https://github.com/openconfig/grpctunnel/blob/6f5422b8ca70fad4504571ebc5ce98b74055abef/tunnel/conn.go#L35).
- gRPC crashes at [this line](https://github.com/grpc/grpc-go/blob/dd350d02da45d67d19705fa8e82544284801428a/internal/xds/rbac/rbac_engine.go#L228) in an attempt to invoke `String()` on a nil object.

### Proposed Solution
Add a nil check for LocalAddr() in the [rbac_engine](https://github.com/grpc/grpc-go/blob/dd350d02da45d67d19705fa8e82544284801428a/internal/xds/rbac/rbac_engine.go#L228).

### Alternatives Considered
Populate context with the LocalAddr() at the application layer.

**Comment by DawtDawt** [comment]
In addition, UnaryInterceptor and StreamIntceptor for gRPC (specifically Authz) does not require IP matching for policy authorization. gRPC requests coming through gRPC tunnel without LocalAddr() populated should be a valid use case the interceptor should accept and evaluate.

**Comment by zasweq** [comment]
Hello, thank you for raising this issue. Can you please provide some reproducible code so I can get around to figuring out the best course of action.

**Comment by zasweq** [comment]
Actually, I think this is WAI. This application was meant to be used with a net.Conn populated through gRPC's transport (if you see the comments elsewhere, you can see special header handling for the feature, which is handled in gRPC-Go's transport layer as well, i.e. https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_server.go#L432. Thus, this is meant to be used atomically in correspondence with the rest of the gRPC system, so this is WAI.
