### ISSUE TITLE
@josegonzalez

### ISSUE THREAD

**Issue by lamhieo02** [grpc/grpc-go#6389]
@josegonzalez 
I believe 
```go
// server is used to implement helloworld.GreeterServer.
type server struct{
// Embed the unimplemented server
helloworld.UnimplementedGreeterServer
}
``` 
is what you are looking for.  correct me if I am wrong @dfawley

_Originally posted by @manikanta-talanki in https://github.com/grpc/grpc-go/issues/3794#issuecomment-720599532_

**Comment by lamhieo02** [comment]
thank you bro 🥳

**Comment by zasweq** [comment]
Glad it fixed your problem :).
