### ISSUE TITLE
Revisit making resolver/balancer and other registries thread safe

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#6408]
Without a mutex to protect the map in these registries, we are seeing data races in tests where we register and unregister entries to the registry.

**Comment by zasweq** [comment]
Also, just to note, this isn't on the critical path and only called in init() and tests, so extra time to grab a mutex is not a problem here.

**Comment by easwars** [comment]
Example of a flaky test because of this issue: https://github.com/grpc/grpc-go/actions/runs/5393587878/jobs/9793539996?pr=6359

**Comment by dfawley** [comment]
I think I'd rather have a per-channel LB policy registry like we have for resolvers: https://pkg.go.dev/google.golang.org/grpc#WithResolvers

For a global registry, I think it's an error to add to it outside of init, otherwise you can have ordering bugs.  Another option to be more precise would be to set a flag when the first channel is created, and panic if an LB policy or name resolver is registered after that time.

> Also, just to note, this isn't on the critical path and only called in init() and tests, so extra time to grab a mutex is not a problem here.

It's not on the RPC path (well, not for _every_ RPC, just the initial one(s)), so isn't the end of the world to take a mutex.  But anywhere the registry is accessed must be protected by the mutex (i.e. when the name resolver produces a service config, and the LB policy needs to be looked up to parse the config).

**Comment by easwars** [comment]
> I think I'd rather have a per-channel LB policy registry like we have for resolvers: [pkg.go.dev/google.golang.org/grpc#WithResolvers](https://pkg.go.dev/google.golang.org/grpc#WithResolvers)

IIUC, this approach only works when the channel tries to look for the resolver associated with the user's dial target. https://github.com/grpc/grpc-go/blob/master/clientconn.go#L1755-L1765

It will not work for other sections of the code that try to get a resolver, like: https://github.com/grpc/grpc-go/blob/master/xds/internal/balancer/clusterresolver/resource_resolver_dns.go#L36

The same holds good for the balancer. We *could* pass the local registry to the balancer wrapper and have it use it when it switched the top-level LB policy here: https://github.com/grpc/grpc-go/blob/master/balancer_conn_wrappers.go#L173. But for the rest of the LB policy tree, we don't have that option. What this issue tries to address though is to have an override for anywhere in the code where a resolver or a balancer is looked up from the global registry.

**Comment by dfawley** [comment]
> It will not work for other sections of the code that try to get a resolver, like: master/xds/internal/balancer/clusterresolver/resource_resolver_dns.go#L36

That's a problem, then, and we should be passing the registry through the LB policy tree (e.g. via `BuildOptions`) or providing the functionality through the `ClientConn` interface (the latter is what Java does FWIW).  Dynamically modifying the global registry isn't really the ideal solution, unless the alternative just doesn't work for some reason.

**Comment by easwars** [comment]
> providing the functionality through the ClientConn interface (the latter is what Java does FWIW)

That is nice, but would require a breaking API change. Let me look into what it would take it pass it via `BuildOptions`.

**Comment by dfawley** [comment]
> That is nice, but would require a breaking API change

Not actually, though...  Users should be embedding a `ClientConn` if they are providing their own version of one.  

https://pkg.go.dev/google.golang.org/grpc/balancer#ClientConn

> This interface is to be implemented by gRPC. Users should not need a brand new implementation of this interface. For the situations like testing, the new implementation should embed this interface. This allows gRPC to add new methods to this interface.

**Comment by easwars** [comment]
Supporting a local registry for balancers is non-trivial because the config parser aka `balancer.ConfigParser` (which is invoked by gRPC when it receives service config from the name resolver, and in other places where a parent policy has to parse config sent to a child policy) does not accept a `balancer.ClientConn`. 

Also, https://github.com/grpc/grpc-go/pull/6497 seems to have resolved the race around access to the balancer registry.

So, dropping this for now until the day where we really have to support something like this.
