### ISSUE TITLE
proto: Marshal called with nil

### ISSUE THREAD

**Issue by DecodeWorms** [grpc/grpc-go#6415]
var request = &pb.VerifyEmailRequest{
         Email : "emailAddress@gmail.com"
        Password : "password"
}

email := "emailAddress@gmail.com"
pwd := "password"

//Compare the both proto values with the variables email and pwd
if request.Email == email && request.Password == pwd{
//Run these code
}

So when i executed this program , it returned an error : "Marshal called with nil"

**Comment by easwars** [comment]
I don't see how this is related to gRPC-Go. If you have a question about protocol buffers, please ask in the protocol buffers' github repository.

**Comment by DecodeWorms** [comment]
Thank you for your response
