### ISSUE TITLE
Too many logs: [orca-backend-metrics] Missing ORCA load report

### ISSUE THREAD

**Issue by YifeiZhuang** [grpc/grpc-go#6423]
The PSM test sees lots of ` [orca-backend-metrics] Missing ORCA load report` spamming the Go client log, worth fixing.

b/288852233

[client log link](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22grpc-testing%22%0Aresource.labels.container_name%3D%22psm-grpc-client%22%0Aresource.labels.namespace_name%3D%22psm-interop-client-20230626-0919-370d2%22%0Alabels.%22k8s-pod%2Fdeployment_id%22%3D%22psm-grpc-client-3vlxgsj3%22;timeRange=2023-06-26T09:24:11.981117Z%2F2023-06-26T09:31:55.425914Z?project=grpc-testing )

**Comment by dfawley** [comment]
These only are logged when setting log verbosity to 2.  Is this really a problem?  Granted, the message itself isn't very helpful, so maybe that could be improved, but I'm inclined to not work too hard to reduce log messages at log verbosity of 2.

**Comment by dfawley** [comment]
I don't actually see any way to improve this log statement..we can just delete it.  But in general, reducing log spam at verbosity 2 shouldn't be considered a priority to address, as verbosity of 2 is for debugging, not general production use.
