### ISSUE TITLE
undefined: grpc.SupportPackageIsVersion1

### ISSUE THREAD

**Issue by pawanrawal** [grpc/grpc-go#643]
go version go1.6 darwin/amd64

Trying to use grpc for adding a Service to my protocol buffer implementation. I get

`undefined: grpc.SupportPackageIsVersion1` when the `pb.go` file that is generated is compiled. I am using `proto3`

Any leads to what could be wrong here?

**Comment by hilljgo** [comment]
Any reason this was closed? I am currently running into the same issue

**Comment by dsymonds** [comment]
Your grpc/grpc-go and golang/protobuf packages need to be both in sync. Most likely one of them is out of date.

**Comment by hilljgo** [comment]
Ah yeah, that was definitely the case! Either protoc (cli tool) protoc-gen-go or my grpc plugin was out of date.
