### ISSUE TITLE
Modifying ClientConn dial-options via xDS

### ISSUE THREAD

**Issue by s-matyukevich** [grpc/grpc-go#6442]
I know that modifying ClientConn [dial-options](https://github.com/grpc/grpc-go/blob/8e9c8f8e7133eb7ed64438837636dae2c5d92ce6/dialoptions.go#L53-L82) via xDS is currently not possible because xDS at a top level is implemented as a resolver, and all interactions  with clientConn happens via sending updates to [serviceConfig](https://github.com/grpc/grpc-go/blob/8e9c8f8e7133eb7ed64438837636dae2c5d92ce6/xds/internal/resolver/xds_resolver.go#L202)

The question is whether this design principle is set in stone, or we can consider changing this in the future? It might be useful in cases where control-plane wants to control all settings on the client. We want to provide a consistent interface to our grpc users, and It feels a bit awkward to require them configuring some of the settings via our custom control-plane UI and at the same time keep configuring other setting in the code.

**Comment by arvindbr8** [comment]
Hi @s-matyukevich,

The current implementation and the design is something that is followed cross language. So this most likely not change in the future. 

> control-plane wants to control all settings on the client.
But could you elaborate a bit on this? Could you example the kind of settings and the usecase where you might want to modify it?

**Comment by s-matyukevich** [comment]
>But could you elaborate a bit on this? Could you example the kind of settings and the usecase where you might want to modify it?

Here is one example. We want service owners to fully control their clients. So the clients will just use a connection string like `xds:///<unique-service-name>` and the control plane will automatically configure the client to use the correct settings based on the parameters of the server. For example, if `serviceA` uses TLS, the connection string `xds:///serviceA` will result in a client config that has TLS enabled. In order for this to work service owners will have to tell the control plane how exactly their services are configured, which we plan to do via a custom UI. 

Now, one important property that we potentially want to control this way is [MaxMsgSize](https://github.com/grpc/grpc-go/blob/master/dialoptions.go#L191) The default value of 4MiB has led to several incidents where response message sizes suddenly start exceeding the limit (for whatever reason) and many gRPC calls start failing. We can't provide a reasonable default for this property because it obviously depend on the server. It would be nice if service owners could use the same control-plane UI to control the value of this property. This property is not the only one that is currently not configurable via xDS - I just used it as an example. 

The reason why we think that using a custom control-plane UI for service owners to configure their clients  is useful is that this potentially allows service owners to modify their services without first contacting all their clients.

**Comment by s-matyukevich** [comment]
Sounds good, thanks!
