### ISSUE TITLE
golang generator adds extra 'error' parameter not defined in proto file

### ISSUE THREAD

**Issue by psankar** [grpc/grpc-go#646]
This is a question on what is the best practice to handle errors in gRPC. To explain: I have a .proto file with a service API:

```
service Search {
 rpc Search (Params) returns (Results)
}
```

where the "Results" could be defined as either:

```
message Results {
  //int64 errorCode = 1; Should I uncomment this and the next line ??
  //string errorDescription = 2;
  repeated Result result = 3;
}
```

For the above .proto file, the generated _pb.go file will be like:
```
Search(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Results, error)
```

Now there is an 'error' parameter in the API. What is the most recommended procedure to handle our application specific errors ? Should they be part of this "error" parameter or should we add a "error" member inside the "Results" message (uncommenting the lines) and handle outside this second parameter ?

If golang generator is generating "error" as a parameter, will the other language generators generate appropriate "throws Exception" or some such for all the generated APIs ?

I sent this as a [mail](https://groups.google.com/forum/#!topic/golang-nuts/NZX1sOYosRs) to the golang nuts group, but since I did not get any official recommendation from the grpc committers, I am filing this here. Thanks.

I filed it as a bug, so that this could be mentioned in the official documentation.

**Comment by iamqizhao** [comment]
The "error" param is the recommended way to handle your application errors. The "error" in the proto is a workaround if the error is a complex object (e.g., it is a proto msg).  Another workaround is to use trailer metadata (https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md) to transmit the error.

Check the tutorial of the grpc in other lanaguages ("Tutorial section" in http://grpc.io) to see how they handle the errors.
