### ISSUE TITLE
Interop tests broken on gRPC master because of Go build failure

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-go#648]
`/go/src/golang.org/x/net/context/ctxhttp/ctxhttp.go:35: req.Cancel undefined (type *http.Request has no field or method Cancel)`

https://grpc-testing.appspot.com/job/gRPC_interop_master/4109/console

This is preventing us from merging PRs in the grpc/grpc repo, so fixing this is urgent. Please treat as P0.

**Comment by dsymonds** [comment]
It's because your test infrastructure is using Go 1.4, but grpc-go requires Go 1.5 or later.

Let me see if I can send you a quick fix.
