### ISSUE TITLE
Export ParseMethod()

### ISSUE THREAD

**Issue by ash2k** [grpc/grpc-go#6483]
### Use case(s) - what problem will this feature solve?

It's useful to be able to parse full method name into separate service and method strings. I've seen in multiple libraries that this is done not the way gRPC-Go does it. If there was an official API for it, people would use it rather than do it themselves incorrectly.

Here is OpenTelemetry instrumentation for gRPC: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/33c3a8fbb5783b8fa81a5b521da00033f696f5cb/instrumentation/google.golang.org/grpc/otelgrpc/internal/parse.go#L28-L33. It splits on the first `/` rather than the last.

### Proposed Solution

Move `grpcutil.ParseMethod()` out of `internal` somewhere where it can be used:

https://github.com/grpc/grpc-go/blob/5ce5686d5e7111d8336f4a0d8b3036c1439e82b1/internal/grpcutil/method.go#L26-L39

### Additional Context

Happy to open an MR but I'm not sure what's the best place for the function. Suggestions?

**Comment by easwars** [comment]
The [gRPC wire protocol ](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) does specify the RPC path as follows:

`Path → ":path" "/" Service-Name "/" {method name}`

and also has this extra specification around `Path`:

```
Path is case-sensitive. Some gRPC implementations may allow the Path
format shown above to be overridden, but this functionality is strongly
discouraged. gRPC does not go out of its way to break users that are
using this kind of override, but we do not actively support it, and some
functionality (e.g., service config support) will not work when the path
is not of the form shown above.
```

We have had similar requests to export the path parsing functionality in the past, and we have pushed back on it. I'm currently unable to find such issues from the archive to understand our reasoning for pushing back on this though.

This functionality is less than 10 lines of code. Would a copy-paste work for you?

**Comment by ash2k** [comment]
Well, I guess I'll just fix the otel library.
