### ISSUE TITLE
Deprecated module github.com/golang/protobuf being used

### ISSUE THREAD

**Issue by SuzukiHonoka** [grpc/grpc-go#6487]
### What version of gRPC are you using?
v1.57.0

### What version of Go are you using (`go version`)?
go version go1.20.6 windows/amd64

### What operating system (Linux, Windows, …) and version?
Windows

### What did you do?
```
"C:\Program Files\Go\bin\go.exe" mod why -m github.com/golang/protobuf #gosetup
# github.com/golang/protobuf
google.golang.org/grpc/credentials
github.com/golang/protobuf/proto
```

### What did you expect to see?
Deprecated module github.com/golang/protobuf.
Deprecation notice: Use the "google.golang.org/protobuf" module instead.
No deprecated module used

### What did you see instead?
Deprecated module used

**Comment by easwars** [comment]
This has come up before and is a non-trivial amount of work that the team does not have cycles for. See: https://github.com/grpc/grpc-go/issues/5316
