### ISSUE TITLE
Update Godoc of resolver.Target

### ISSUE THREAD

**Issue by philippgille** [grpc/grpc-go#6496]
### Use case(s) - what problem will this feature solve?

It will make the Godoc consistent with the code

### Proposed Solution

Recently some exported fields were removed from `resolver.Target` in [this PR](https://github.com/grpc/grpc-go/pull/6363/files#diff-732f365bd38694dea48332c13814847ee19a76bebc5f3d2c87733f1a4ee915ffL267-L270). The specific change I'd like to address is this one: 
![image](https://github.com/grpc/grpc-go/assets/170670/f4d7e578-8dcb-40af-92a2-32c5f986df87)
The Godoc still contains examples that make use of those fields.

I propose to change the Godoc to not reference the removed fields anymore, as well as to change the `Endpoint` one to the `URL` one.

**Comment by easwars** [comment]
Thanks for filing this issue. Would you like to send a PR for the same?

**Comment by philippgille** [comment]
> Thanks for filing this issue. Would you like to send a PR for the same?

Yes I can do that. Maybe on the weekend.

**Comment by philippgille** [comment]
PR: https://github.com/grpc/grpc-go/pull/6547
