### ISSUE TITLE
Support to initialize an any structure through jsonString

### ISSUE THREAD

**Issue by wsy6543** [grpc/grpc-go#6507]
Java can initialize an any structure through a jsonString, and golang can only initialize an any structure through a proto object
In this way, there will be a gap in the interaction between the two ends. I hope that golang also supports the initialization of an any structure through json.

java:  Any.newBuilder().setValue(ByteString.copyFrom(jsonString, StandardCharsets.UTF_8)))
go:    anypb.New(proto.Message)

**Comment by arvindbr8** [comment]
This seems to be a question for [golang](https://github.com/golang/go) than for our repo.
