### ISSUE TITLE
Correct way to perform a reconnect with gRPC client

### ISSUE THREAD

**Issue by gregorypa** [grpc/grpc-go#6508]
I have an application that successfully works with single GRPC server. We have implemented GRPC server to be running on multiple nodes for redundancy. Our client calls server every 2-3 seconds.
When we restart one of the nodes, client that was connected to that node loses connection, but regains it back almost immediate when it is up.
On the other hand if the node is down permanently, it takes between 6-15 min until client reconnects to different server.

What is the correct way to make gRPC client to reconnect in case of RPC failure?

Bellow is our current client connection implementation:

```
func dialConnection(connString string) *grpc.ClientConn {
	tlsCredentials := insecure.NewCredentials()
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*time.Duration(5))
	defer cancel()
	conn, err := grpc.DialContext(ctx, connString,
		grpc.WithTransportCredentials(tlsCredentials),
		grpc.WithBlock())
	if err != nil {
		return nil
	}
	return conn
}
```

connection string will look like "grpcserver.company.com:50051" while DNS resolver will return IPs for all servers.

**Comment by arvindbr8** [comment]
Hi, 

From the looks of it, it seems like you are using the pick-first policy for load balancing. I would turning on the logs for debugging, by running the code with the following environment variable: 

`GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info`

That way we could see what the list of addresses passed by DNS and which addresses the client tries to connect to. 

Please add the logs to this issue and we can take a look at it better.

**Comment by gregorypa** [comment]
Hi, 
Please find the requested logs.

```
2023/08/09 07:53:26 INFO: [core] [Server #1] Server created 
2023/08/09 07:53:26 INFO: [core] [Server #1 ListenSocket #2] ListenSocket created
2023/08/09 07:53:31 INFO: [core] [Channel #4] Channel created
2023/08/09 07:53:31 INFO: [core] [Channel #4] original dial target is: "controller.edgehawk.io:30051"
2023/08/09 07:53:31 INFO: [core] [Channel #4] parsed dial target is: {URL:{Scheme:controller.edgehawk.io Opaque:30051 User: Host: Path: RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}}
2023/08/09 07:53:31 INFO: [core] [Channel #4] fallback to scheme "passthrough"
2023/08/09 07:53:31 INFO: [core] [Channel #4] parsed dial target is: {URL:{Scheme:passthrough Opaque: User: Host: Path:/controller.edgehawk.io:30051 RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}}
2023/08/09 07:53:31 INFO: [core] [Channel #4] Channel authority set to "controller.edgehawk.com"
2023/08/09 07:53:31 INFO: [core] [Channel #4] Resolver state updated: {
  "Addresses": [
    {
      "Addr": "controller.edgehawk.io:30051",
      "ServerName": "",
      "Attributes": null,
      "BalancerAttributes": null,
      "Type": 0,
      "Metadata": null
    }
  ],
  "ServiceConfig": null,
  "Attributes": null
} (resolver returned new addresses)
2023/08/09 07:53:31 INFO: [core] [Channel #4] Channel switches to new LB policy "pick_first"
2023/08/09 07:53:31 INFO: [core] [Channel #4 SubChannel #5] Subchannel created
2023/08/09 07:53:31 INFO: [core] [Channel #4] Channel Connectivity change to CONNECTING
2023/08/09 07:53:31 INFO: [core] [Channel #4 SubChannel #5] Subchannel Connectivity change to CONNECTING
2023/08/09 07:53:31 INFO: [core] [Channel #4 SubChannel #5] Subchannel picks a new address "controller.edgehawk.io:30051" to connect
2023/08/09 07:53:31 INFO: [core] pickfirstBalancer: UpdateSubConnState: 0xc001b3efc0, {CONNECTING <nil>}
2023/08/09 07:53:31 INFO: [core] [Channel #4 SubChannel #5] Subchannel Connectivity change to READY
2023/08/09 07:53:31 INFO: [core] pickfirstBalancer: UpdateSubConnState: 0xc001b3efc0, {READY <nil>}
2023/08/09 07:53:31 INFO: [core] [Channel #4] Channel Connectivity change to READY
2023/08/09 07:53:32 INFO: [core] [Server #1] grpc: Server.Serve failed to create ServerTransport: connection error: desc = "ServerHandshake(\"10.19.0.56:13129\") failed: remote error: tls: internal error"


2023/08/09 07:53:50 INFO: [core] [Server #1] grpc: Server.Serve failed to create ServerTransport: connection error: desc = "ServerHandshake(\"10.19.0.56:50552\") failed: remote error: tls: internal error"
2023/08/09 07:54:57 INFO: [core] [Server #1] grpc: Server.Serve failed to create ServerTransport: connection error: desc = "ServerHandshake(\"10.19.0.56:18428\") failed: remote error: tls: internal error"
2023/08/09 07:55:08 INFO: [core] [Server #1] grpc: Server.Serve failed to create ServerTransport: connection error: desc = "ServerHandshake(\"10.19.0.56:25143\") failed: remote error: tls: internal error"


2023/08/09 07:59:26 INFO: [transport] [server-transport 0xc003cb6680] Closing: EOF
2023/08/09 07:59:26 INFO: [transport] [server-transport 0xc003cb6680] loopyWriter exiting with error: transport closed by client

2023/08/09 08:02:09 INFO: [transport] [client-transport 0xc00214d200] loopyWriter exiting with error: write tcp 172.17.0.2:44672->10.19.6.221:30051: write: connection reset by peer
2023/08/09 08:02:09 INFO: [transport] [client-transport 0xc00214d200] Closing: connection error: desc = "error reading from server: EOF"
2023/08/09 08:02:09 INFO: [core] [Channel #4 SubChannel #5] Subchannel Connectivity change to IDLE
2023/08/09 08:02:09 INFO: [core] pickfirstBalancer: UpdateSubConnState: 0xc001b3efc0, {IDLE <nil>}
2023/08/09 08:02:09 INFO: [core] [Channel #4] Channel Connectivity change to IDLE
2023/08/09 08:02:09 INFO: [core] blockingPicker: the picked transport is not ready, loop back to repick
2023/08/09 08:02:09 INFO: [core] [Channel #4 SubChannel #5] Subchannel Connectivity change to CONNECTING
2023/08/09 08:02:09 INFO: [core] [Channel #4 SubChannel #5] Subchannel picks a new address "controller.edgehawk.io:30051" to connect
2023/08/09 08:02:09 INFO: [core] pickfirstBalancer: UpdateSubConnState: 0xc001b3efc0, {CONNECTING <nil>}
2023/08/09 08:02:09 INFO: [core] [Channel #4] Channel Connectivity change to CONNECTING
2023/08/09 08:02:16 INFO: [core] [Channel #4 SubChannel #5] Subchannel Connectivity change to READY
2023/08/09 08:02:16 INFO: [core] pickfirstBalancer: UpdateSubConnState: 0xc001b3efc0, {READY <nil>}
2023/08/09 08:02:16 INFO: [core] [Channel #4] Channel Connectivity change to READY

```

**Comment by arvindbr8** [comment]
Thanks for the logs. 

Seems like the dial target is missing a schema and hence gRPC defaults to `passthrough`. 

Using the DNS name resolver would be more appropriate in your case. If you check the resolver address update logs, you can see `controller.edgehawk.io:30051` is passed as is to gRPC. Passing `dns:///controller.edgehawk.io:30051` would allow the dns resolver to get all the addresses for the dial target. 

Additionally, using a round-robin LB policy would help reducing downtime by forcing client to reconnect to a different address when the connection fails 

Let us know if that helped. 

-------

Although I'm missing some context without annotations. I have a few questions about the setup 

```
2023/08/09 07:59:26 INFO: [transport] [server-transport 0xc003cb6680] Closing: EOF

```
**Q:** Was this when the server node was killed? 


```
2023/08/09 07:59:26 INFO: [transport] [server-transport 0xc003cb6680] loopyWriter exiting with error: transport closed by client

2023/08/09 08:02:09 INFO: [transport] [client-transport 0xc00214d200] loopyWriter exiting with error: write tcp 172.17.0.2:44672->10.19.6.221:30051: write: connection reset by peer
2
```

The client detected the connection loss only in 2.5 seconds. 
**Q:** Were RPCs been sent during that time?

**Comment by evgenyreshko** [comment]
> Thanks for the logs.
> 
> Seems like the dial target is missing a schema and hence gRPC defaults to `passthrough`.
> 
> Using the DNS name resolver would be more appropriate in your case. If you check the resolver address update logs, you can see `controller.edgehawk.io:30051` is passed as is to gRPC. Passing `dns:///controller.edgehawk.io:30051` would allow the dns resolver to get all the addresses for the dial target.
> 
> Additionally, using a round-robin LB policy would help reducing downtime by forcing client to reconnect to a different address when the connection fails
> 
> Let us know if that helped.
> 
> Although I'm missing some context without annotations. I have a few questions about the setup
> 
> ```
> 2023/08/09 07:59:26 INFO: [transport] [server-transport 0xc003cb6680] Closing: EOF
> ```
> 
> **Q:** Was this when the server node was killed?
   **A:** It is HA environment in kubernetes. We're testing fail over scenario between 2 kubernetes pods.
> 
> ```
> 2023/08/09 07:59:26 INFO: [transport] [server-transport 0xc003cb6680] loopyWriter exiting with error: transport closed by client
> 
> 2023/08/09 08:02:09 INFO: [transport] [client-transport 0xc00214d200] loopyWriter exiting with error: write tcp 172.17.0.2:44672->10.19.6.221:30051: write: connection reset by peer
> 2
> ```
> 
> The client detected the connection loss only in 2.5 seconds. **Q:** Were RPCs been sent during that time?
A: yes ... rpc has been sending every 2 sec

**Comment by gregorypa** [comment]
Hello,

We have tried several tests, but without real progress.
1. we pass `dns:///` to enable DNS resolver.
2. we cannot use round_robin LB, because in our case we have many clients which connect to the server according to region and only in case of failure will connect other servers. So we need to stay with pick_first option.
3. we tried to use `WithIdleTimeout` option, but does not seems to be working. My expectation was that after timeout of consistent RPC failures, it will trigger the idle timeout and will reconnect the server.
4. we tried to use `healthCheck` feature, same here.
My suspicion is that GRPC client cannot detect connection failure, because it does not receive any replies from the server. when server dies no request gets response.

regarding your questions:
1. When connection is lost we start getting errors `rpc error: code = DeadlineExceeded desc = context deadline exceeded` for each RPC call.
2. RPCs are not sent anywhere.

This is our new implementation:

```
    dialOpts := []grpc.DialOption{
        grpc.WithTransportCredentials(tlsCredentials),
        grpc.WithBlock(),
        grpc.WithReturnConnectionError(),
    }
    if *flagLBPolicy != "" {
        backoffConfig := backoff.DefaultConfig
        backoffConfig.Multiplier = *flagBackOffMultiplier
        backoffConfig.Jitter = *flagBackOffJitter

        dialOpts = append(dialOpts,
            grpc.WithIdleTimeout(time.Duration(*flagCntrIdleTime)*time.Millisecond),
            grpc.WithConnectParams(grpc.ConnectParams{Backoff: backoffConfig}),
            grpc.WithDefaultServiceConfig(fmt.Sprintf(`{"loadBalancingPolicy":"%s",
                                                               "healthCheckConfig": {"serviceName": ""}}`,
                *flagLBPolicy)))
    }

    ctx, cancel := context.WithTimeout(context.Background(), time.Second*time.Duration(*flagCntrDialTimeout))
    defer cancel()

    conn, err := grpc.DialContext(ctx, cntrAddr, dialOpts...)

```

Can you recommend how to change the dial options in order to trigger reconnection?

Thanks

**Comment by gregorypa** [comment]
> When your server node goes down, do you see any update from the DNS resolver in your logs?

No.

> Have you tried using gRPC keepalives? These are application level HTTP/2 keepalives, and can detect unresponsive connections and close them before the TCP layer detects that the connection is dead.
> 
> The https://pkg.go.dev/google.golang.org/grpc@v1.57.0/keepalive package contains options to configure keepalive parameters, and we have a dial option and server option to configure the same on the client and the server respectively.

This seems to be the proper solution for us. we removed all the rest and leaved only keepalives. 
Our only concern is not to overload the server with unnecessary messages. Will keepalives be sent only in case there are no RPC calls?

new code:

```
	dialOpts := []grpc.DialOption{
		grpc.WithTransportCredentials(tlsCredentials),
		grpc.WithBlock(),
		grpc.WithReturnConnectionError(),
		grpc.WithKeepaliveParams(keepalive.ClientParameters{
			Time:                time.Duration(*flagKeepAliveTime) * time.Second,
			Timeout:             time.Duration(*flagKeepAliveTimeout) * time.Second,
			PermitWithoutStream: true,
		}),
	}

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*time.Duration(*flagCntrDialTimeout))
	defer cancel()

	conn, err := grpc.DialContext(ctx, cntrAddr, dialOpts...)
```

**Comment by easwars** [comment]
> Our only concern is not to overload the server with unnecessary messages. Will keepalives be sent only in case there are no RPC calls?

Keepalive time and timeout values of `1s` are super aggressive. Do you really want to detect bad connections in one second? Also, `keepalive.Timeout` should ideally be set to something greater than the expected RTT.

Also, you can setup an appropriate enforcement policy on the server side that lets you control how frequently your clients are allowed to send keepalives. See: https://pkg.go.dev/google.golang.org/grpc@v1.57.0/keepalive#EnforcementPolicy

The `keepalive.PermitWithoutStream` controls whether keepalives are sent when there are no active RPCs. The comment for the field is self-explanatory:
```
	// If true, client sends keepalive pings even with no active RPCs. If false,
	// when there are no active RPCs, Time and Timeout will be ignored and no
	// keepalive pings will be sent.
	PermitWithoutStream [bool](https://pkg.go.dev/builtin#bool) // false by default.
```

Also, you might find the following useful:
https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md
https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md

Not related to keepalives: I'm noticing the use of `grpc.WithBlock()` and `grpc.WithReturnConnectionError()` dial options. We have a document which talks about why using these are considered an anti-pattern. Hope this helps: https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md
