### ISSUE TITLE
Configure dependabot for repo

### ISSUE THREAD

**Issue by Neo2308** [grpc/grpc-go#6511]
### Use case(s) - what problem will this feature solve?
Updating go dependencies is currently a manual process

### Proposed Solution
Configure dependabot to raise the update PRs automatically.

**Comment by arvindbr8** [comment]
Hi @Neo2308

We are being open source are extra careful while updating go dependencies. Hence the manual process is to give us total control. I dont see the value in adding it to our repo; unless you have some particular scenario you think might help our OSS project.

**Comment by Neo2308** [comment]
Dependabot would only raise the PRs automatically. Merging/not merging them could still be taken up on a case by case basis. It would just make the process a bit less time consuming.

**Comment by dfawley** [comment]
We were already getting alerts from dependabot.  We were updating our dependencies manually every 6 weeks and will continue to do so, but I have clicked this button to enable dependabot to send PRs if there are vulnerabilities:

![image](https://github.com/grpc/grpc-go/assets/26072277/19845f6f-a5c6-477a-801a-4881f11048f3)
(This is the "after" picture.)

Out of curiosity, why are you concerned about this?
