### ISSUE TITLE
sending data to InterceptorHandler from ServerInterceptor

### ISSUE THREAD

**Issue by sadlil** [grpc/grpc-go#652]
I was seeing that `grpc-go` now supports server interceptor in `Unary` calls, that call solves a lots of coding to be repeated into all the handlers. But i am having an issue here to send some pre-processed data from the `UnaryServerInterceptor` to `UnaryHandler`. The handler just have only `context` and the `request` object so no way to sends data as function parameters. 

And seeing at the `info *UnaryServerInfo` that was passed to `UnaryServerInterceptor` i am seeing this

```
// Server is the service implementation the user provides. This is read-only.
Server interface{}
```
This showed the `Server` is **read-only**. Now what will be the process to send data from `ServerInterceptor` to `Handler`?

**Comment by chancez** [comment]
Why can't you use context for this?

**Comment by iamqizhao** [comment]
As @chancez pointed out, you can attach it to the context.
