### ISSUE TITLE
Question about the logic of http2Server sending FlagDataEndStream

### ISSUE THREAD

**Issue by ppzqh** [grpc/grpc-go#6540]
Hi, I notice that the `opts` is not used in http2Server.Write to set `endStream`. 
I wonder the reason of this. Seems that it won't affect the processing logic on the client side. Thanks!
source: https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_server.go#L1102

**Comment by ppzqh** [comment]
Is it because server will send `endStream = true` in trailer?

**Comment by arvindbr8** [comment]
Hi, 
You are right, endStream is set when sending trailers from the server side. 

Please see https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md
