### ISSUE TITLE
包地址错误

### ISSUE THREAD

**Issue by leonardyp** [grpc/grpc-go#655]
go get google.golang.org/grpc 地址不对啊
浏览器直接访问也访问不了

**Comment by xiang90** [comment]
Can you please use English for better communication on github?

**Comment by leonardyp** [comment]
the address google.golang.org/grpc is wrong that can not be go get
and Direct access to the browser could not access

**Comment by chai2010** [comment]
@leonardyp Please **DONOT** use `go get` in China!
Use `git clone https://github.com/grpc/grpc-go.git $GOPATH/src/google.golang.org/grpc`.
