### ISSUE TITLE
Breaking API change introduced with UnaryInterceptor

### ISSUE THREAD

**Issue by shaxbee** [grpc/grpc-go#656]
It seems that both protoc-gen-go and unit tests are broken by new change with UnaryInterceptor.
```
# google.golang.org/grpc/health/grpc_health_v1
health/grpc_health_v1/health.pb.go:150: cannot use _Health_Check_Handler (type func(interface {}, context.Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value
# google.golang.org/grpc/test/grpc_testing
test/grpc_testing/test.pb.go:712: cannot use _TestService_EmptyCall_Handler (type func(interface {}, context.Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value
test/grpc_testing/test.pb.go:716: cannot use _TestService_UnaryCall_Handler (type func(interface {}, context.Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value
FAIL	google.golang.org/grpc/test [build failed]
```

Shouldn't unary interceptor be called by server in same fashion as stream interceptor is instead of passing it on to handler and making braking interface change?

**Comment by dsymonds** [comment]
The old unary API didn't work for the interceptor design requirements so there needed to be a breaking change. You need to have grpc/grpc-go and golang/protobuf both up to date.

**Comment by shaxbee** [comment]
Still there are errors when testing grpc package due to test files not being regenerated.

**Comment by dsymonds** [comment]
Are you sure? The Travis build is showing everything building fine, and I just checked that `go build -v google.golang.org/grpc/...` works for me when everything is at HEAD.

**Comment by shaxbee** [comment]
Pulled, works at HEAD. Sorry for the ruckus.
