### ISSUE TITLE
Add a ClientConn level test for idleness race

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#6560]
See https://github.com/grpc/grpc-go/pull/6538 which was never caught by our existing tests.

One option for this test is to run cc.exitIdleMode and cc.enterIdleMode concurrently and ensure that things work as expected.

**Comment by Aditya-Sood** [comment]
hi @easwars, can I pick this up?

**Comment by dfawley** [comment]
This should wait until #6566 is merged.

**Comment by dfawley** [comment]
Let's also clean up `enterIdleMode`: `defer` the unlock and also do the channelz event synchronously instead of in the goroutine at the end.
