### ISSUE TITLE
internal/credentials/xds: add unit test for HandshakeInfo.Equal

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#6568]
We made the `Equal` method actual perform a deep equal instead of pointer equality. We should add tests for it. 
https://github.com/grpc/grpc-go/blob/master/internal/credentials/xds/handshake_info.go#L47

**Comment by Aditya-Sood** [comment]
hi @ginayeh, can I pick this up?

**Comment by dfawley** [comment]
Let us know if you still want this @Aditya-Sood  - I already assigned a few other things to you and don't want to overwhelm.

**Comment by Aditya-Sood** [comment]
hi @dfawley, yes I've responded to the action items for me on the open PRs
I will start working on 6763, can pick this up after that?

**Comment by zedGGs** [comment]
@arvindbr8 I would love to take this one,
if you think it's fine feel free to assign me

**Comment by zedGGs** [comment]
@arvindbr8 I would love to take this one,
if you think it's fine feel free to assign me

**Comment by arvindbr8** [comment]
@zedGGs -- Thanks for your interest. But it seems like we have a PR in flight. I'm more than happy to reserve this to you until we have merged that one in.

**Comment by zedGGs** [comment]
@arvindbr8 feel free to assign me on this since we finalised ongoing pr already

**Comment by janardhanvissa** [comment]
@purnesh42H Please assign me this issue.

**Comment by easwars** [comment]
Fixed by https://github.com/grpc/grpc-go/pull/7638.
