### ISSUE TITLE
For unary methods, received messages are put into buffer from the pool, but buffer is never returned back to pool.

### ISSUE THREAD

**Issue by efremovmi** [grpc/grpc-go#6578]
### What version of gRPC are you using?
1.57.0

### What version of Go are you using (`go version`)?
1.20.6

### What operating system (Linux, Windows, …) and version?
MacOS

### What did you do?
added buffer pool support and I expect that the number of allocations in the application will decrease

### What did you expect to see?
I expect to see a decrease in allocations to the query (processUnaryRPC -> recvAndDecompress -> recvMsg)

### What did you see instead?
after adding the buffer pool, the number of allocations has not changed (objects are not returned to the pool anywhere else, but they are always taken from it 616 line figure 2)

#### figure 1:
<img width="1084" alt="image" src="https://github.com/grpc/grpc-go/assets/62056392/f9a9547a-be74-45f7-8372-75e7010d0581">

#### figure 2:
![image](https://github.com/grpc/grpc-go/assets/62056392/a138c1cd-b2b6-45c1-97de-64f9425ada5e)

**Comment by easwars** [comment]
> after adding the buffer pool

How did you do that?

The buffer is retrieved from the pool [here](https://github.com/grpc/grpc-go/blob/9362f2612b6fafa34a5e7635b8635b2ec04e7005/rpc_util.go#L616C19-L616C19) and is put back to the pool [here](https://github.com/grpc/grpc-go/blob/9362f2612b6fafa34a5e7635b8635b2ec04e7005/rpc_util.go#L806).

@hueypark : Do you see any issues at all with the implementation? I remember that you wanted this functionality quite urgently. Have you been using this buffer pool with your application? How has your experience been? Thanks.

**Comment by efremovmi** [comment]
> How did you do that?

I added a SharedBufferPool to my server and set breakpoints in the Get and Put methods. When debugging, the application stopped in the Get method, but never stopped in the Put method. Then I implemented my Buffer Pool and made a structure that would satisfy SharedBufferPool and also made two breakpoints in Get and Put. The result was repeated - Put is never called.

Please try to do the same and call any unary methods. Which you can write yourself. If there are problems, I can share my repository, which you can debug.

Judging by Figure 1, I am not the only one who has faced such a problem.

**Comment by efremovmi** [comment]
@pstibrany  have you also encountered such a problem? can you describe it? thank you!

**Comment by efremovmi** [comment]
@easwars this is where the buffer pool is passed, from which the buffer is taken, and then nothing is returned back to the pool (Put).
<img width="955" alt="image" src="https://github.com/grpc/grpc-go/assets/62056392/1d84f31f-f8fc-4c39-b3c3-1aeef0f23401">

**Comment by efremovmi** [comment]
I can assume that after calling this function, you can return the buffer back to the pool
<img width="962" alt="image" src="https://github.com/grpc/grpc-go/assets/62056392/d66b57a0-e314-434b-9847-45625096c056">

**Comment by hueypark** [comment]
@easwars

> @hueypark : Do you see any issues at all with the implementation? I remember that you wanted this functionality quite urgently. Have you been using this buffer pool with your application? How has your experience been? Thanks.

I had already solved the memory problem by reducing the number of RPC calls, so I hadn't introduced a buffer pool yet.
And when I was developing this PR, I was mainly thinking about stream RPCs, so it might not work well with unary calls.

+1 for https://github.com/grpc/grpc-go/pull/5862#issuecomment-1582154054

**Comment by efremovmi** [comment]
@hueypark 
>  ...I was mainly thinking about stream RPCs, so it might not work well with unary calls.

you can add your own pool that will permanently hold memory, so it will still work well, unlike sync.Pool. The problem is that now nothing is returned back to the pool with unary calls, regardless of which pool it is: SharedBufferPool (provided by developers) or self-written

**Comment by hueypark** [comment]
@efremovmi 
> you can add your own pool that will permanently hold memory, so it will still work well, unlike sync.Pool. The problem is that now nothing is returned back to the pool with unary calls, regardless of which pool it is: SharedBufferPool (provided by developers) or self-written

I agree. Unfortunately, I won't be able to allocate time for this improvement in the immediate future.
Would you consider creating a pull request based on your current findings?

**Comment by efremovmi** [comment]
@hueypark 

> I agree. Unfortunately, I won't be able to allocate time for this improvement in the immediate future.
> Would you consider creating a pull request based on your current findings?

Yes, I will try to do it.

**Comment by efremovmi** [comment]
Added a change:
https://github.com/grpc/grpc-go/pull/6603

**Comment by ginayeh** [comment]
Seems like #6605 might be closed soon due to inactivity.  @hueypark Are you interested in taking this up since you made the initial PR if you have some bandwidth?

**Comment by hueypark** [comment]
Sure, I'll take a look and pick it up.

**Comment by vtolstov** [comment]
any news ? i want to minimise memory allocs, but i have unary and stream rpc

**Comment by dfawley** [comment]
I approved #6766; we need a second review before merging it.  Sorry for the delays.

**Comment by efremovmi** [comment]
Hi! Have you noticed any changes after merging with the main branch?

**Comment by dfawley** [comment]
@efremovmi The gRPC benchmarks (https://grafana-dot-grpc-testing.appspot.com/?orgId=1) unfortunately don't collect memory usage statistics.  Maybe another user has some data they can share?

**Comment by efremovmi** [comment]
In this case, I will try to create a load test for my pet project in my free time and come back with the results
