### ISSUE TITLE
Client errors if response has no data and connection goes through nghttpx

### ISSUE THREAD

**Issue by vlad-alexandru-ionescu** [grpc/grpc-go#658]
When using nghttpx as reverse-proxy, if the server sends no data on a streaming RPC (eg a bidi connection where server does not call `stream.Send(...)`), then the client errors out with the message `rpc error: code = 13 desc = server closed the stream without sending trailers`.
### What happens
- Server receives a bidi RPC.
- Server calls `stream.CloseSend()` without having sent anything.
- Server response contains no data frame. So the "trailers" are sent back as headers.
- nghttpx sees a headers-only response and attaches an empty data frame before sending it on to the client.
- Client receives response, interprets header frame as headers (not as "trailers"), then interprets the data frame with end stream flag as data with no trailers.
- Client freaks out.
### What should happen

Either the server should send back a data frame no matter what, followed by trailers OR the client should detect that the headers are actually trailers and allow an empty data frame with end stream flag to follow.
### Workaround (for anyone else encountering this)

Reply with an empty proto (and have your client ignore it). An empty proto's encoded size is non-zero.
### Misc

I have not tested this with other gRPC clients/servers, don't know how they behave in this situation. Also, not sure if this would happen for the reverse of this situation: client does not send any data.

See also [this issue in nghttp2 project](https://github.com/nghttp2/nghttp2/issues/588).

**Comment by iamqizhao** [comment]
I have not followed the discussion on nghttp2. But why does nghttpx attach an empty data frame when it sees a header-only response? This is the root cause it failed the grpc client.

**Comment by tatsuhiro-t** [comment]
I think this is the fault of gRPC:
See https://github.com/nghttp2/nghttp2/issues/588#issuecomment-214941473

**Comment by tatsuhiro-t** [comment]
nghttpx probably avoid empty body if it correctly utilizes END_STREAM in HEADERS.  I still think that gRPC should accept empty body, because it is allowed in HTTP/2 spec.

**Comment by hsaliak** [comment]
@MakMukhi would you be able to take a look? This should be straightforward to reproduce.

**Comment by MakMukhi** [comment]
@tatsuhiro-t  @vlad-alexandru-ionescu  Agreed that empty Data frames are allowed but here it is more than that; the proxy modifies the header frame (making End Stream = False as mentioned [here](https://github.com/nghttp2/nghttp2/issues/588)) and adds a data frame(albeit empty) when there shouldn't be any. This violates the [gRPC protocol](http://www.grpc.io/docs/guides/wire.html) that the end-points rely on.

**Comment by jaytaylor** [comment]
#### Dead Links

The wire protocol link is dead, here are archived snapshots:

http://web.archive.org/web/20170429155158/https://grpc.io/docs/guides/wire.html

http://archive.is/JAngz

and the updated version of the document:

https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md
