### ISSUE TITLE
Improve `regenerate.sh` to use the correct proto compiler version

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#6583]
Currently the regenerate script installs `protoc-gen-go` and `protoc-gen-go-grpc` in a workdir, but uses the system installed `protoc` which means that running the `regenerate.sh` script could result in all generated files being changed with a diff which would look something like:

```
@@ -20,7 +20,7 @@
 // Code generated by protoc-gen-go. DO NOT EDIT.
 // versions:
 //     protoc-gen-go v1.31.0
-//     protoc        v4.22.0
+//     protoc        v3.21.2
 // source: grpc/lb/v1/load_balancer.proto
```

**Comment by avinilcodes** [comment]
I would like to contribute, can you please assign it to me

**Comment by dfawley** [comment]
@avinilcodes - Thanks!

Note that most people on our team use both linux and macOS, so the script should be able to handle this properly on both systems, or at least fall back to the old behavior gracefully.

**Comment by Clement-Jean** [comment]
Quick question: why not using the protoc binary from the fresh pull of protobuf repository? Wouldn't that solve the problem?

We could then use Make, CMake or Bazel to generate the binary and replace all the protoc refs to the bin folder of protobuf.

**Comment by dfawley** [comment]
We don't want to always use the latest version because that would require updates to our generated code frequently.  We have a release document that includes updating other dependencies that should update this one as well.  But we'd like it to be a static version for now.

**Comment by arvindbr8** [comment]
@avinilcodes -- friendly ping

**Comment by Aditya-Sood** [comment]
hi @dfawley, can I pick this up?

**Comment by dfawley** [comment]
Similar to the other issue, @Aditya-Sood  - LMK if you still want this.

**Comment by Aditya-Sood** [comment]
thank you Doug, as suggested I will close the other issue and then pick this up
