### ISSUE TITLE
potential stream routine leak

### ISSUE THREAD

**Issue by xiang90** [grpc/grpc-go#659]
After close the underlying Conn of a stream, stream.Recv will return error as `rpc error: code = 13 desc = transport is closing`. This is expected.

However the routine created at https://github.com/grpc/grpc-go/blob/master/stream.go#L150 will still be here until the context passed into the stream creation is canceled.

This is inconvenient since now the caller of the stream needs to keep track of the status of conn or needs to understand the conn level error (transport is closing == close context). Is there a reason that gRPC does not kill the routine when there is a closing error?

/cc @heyitsanthony @tamird

**Comment by xiang90** [comment]
More context, in etcd we have one connection per client. And that client has multiple APIs. Each APIs keeps several long-live streams to the server. If one API meets a connection error, it will close the connection. Then other APIs' streams will receive error (`transport is closing`) from Recv(). If gRPC does not clean up routines, each API needs to parse if the returned error is `transport is closing` and then cancel ctx accordingly. Or APIs can just try to grab the newly created connection and restart.

**Comment by iamqizhao** [comment]
Does your version contain https://github.com/grpc/grpc-go/pull/649?

**Comment by xiang90** [comment]
@iamqizhao It does not I believe. I will bump gRPC and give it another try. Thanks!

**Comment by xiang90** [comment]
@iamqizhao It is fixed. Thanks!
