### ISSUE TITLE
`grpc.FailOnNonTempDialError` doesn't fail with wrong TLS certificate

### ISSUE THREAD

**Issue by olegbespalov** [grpc/grpc-go#6593]
### What version of gRPC are you using?

```
google.golang.org/grpc v1.55.0
```

### What version of Go are you using (`go version`)?

```
go version go1.21.0 linux/amd64
```

### What operating system (Linux, Windows, …) and version?

```
x86_64 GNU/Linux
```

### What did you do?

So we have a code dependent on the grpc library, and we were trying to establish a connection by using the:

```golang
conn, err := grpc.DialContext(ctx, addr, options...)
if err != nil {
	return nil, err
}
```

where `options` looks like:

```golang
tcred := credentials.NewTLS(tlsCfg)

options := []grpc.DialOption{
   grpc.WithBlock(),
   grpc.FailOnNonTempDialError(true),
   grpc.WithReturnConnectionError(),
   grpc.WithTransportCredentials(tcred)
}
```

Some of our tests intentionally used the wrong TLS certificate.

### What did you expect to see?

So I expected to see the error about the `bad certificate` almost immediately.

### What did you see instead?

But instead, I found that we were waiting till the context to reach the deadline, and only after that could I get the error.

I started to investigate, and it turned out that the error of a bad certificate is treated as a temporary error, which means that the transport will try to do some retries on that.

![image](https://github.com/grpc/grpc-go/assets/5425600/b06d5247-72c7-4aee-b0ae-af4530ddcfbb)

Looking into the code, I see that the place 

https://github.com/grpc/grpc-go/blob/9362f2612b6fafa34a5e7635b8635b2ec04e7005/internal/transport/http2_client.go#L1566

doesn't use the helper `isTemporary`, but instead passes the static `true` to the `connectionError`'s constructor. 

So I believe the fix is pretty straightforward like:
```diff
-return connectionErrorf(true, err, "error reading server preface: %v", err)
+return connectionErrorf(isTemporary(err), err, "error reading server preface: %v", err)
```

**Comment by olegbespalov** [comment]
If needed, I could also try to prepare a code/repo that shows the issue, or I could also try to write a test, but I am not sure about the time frame of it since I am not familiar with the grpc-go code base.

**Comment by atollena** [comment]
My guess is that this is working as intended: `DialContext` with `WithBlock` only returns an error if `context` has expired AND there is still no usable server connection established. It can't return before context has expired.

**Comment by olegbespalov** [comment]
My assumption is that it shouldn't wait for the context since we also use the `grpc.FailOnNonTempDialError(true)`.

Actually, the code is trying to check and exit earlier:
https://github.com/grpc/grpc-go/blob/aa6ce35c792863305e0f42acc27f2c7153275f89/clientconn.go#L286-L293

But the issue is that the error is wrapped so that it isn't treated as permanent (see a screenshot of my debugger from above).

For the reference, the `tls.permanentError` error implements interface properly https://cs.opensource.google/go/go/+/master:src/crypto/tls/conn.go;l=192?q=permanentError&ss=go%2Fgo

**Comment by atollena** [comment]
Ha, I didn't realize you are also using `FailOnNonTempDialError `, I'm sorry. The flag itself doesn't make much sense to me, but your point about the flag respecting the underlying error definition does (`Temporary()` never had clear semantic always and [was deprecated since](https://go-review.googlesource.com/c/go/+/340261)).

**Comment by olegbespalov** [comment]
Right, it could be a lousy naming of the issue. I'll try to adjust it.

Yeah, I see that the `net.Error`'s Temporary is deprecated, but still, I see that there are many usages of just `Temporary` interface inside the grpc-go.

Also, the suggested fix works for me. At least I've done some testing after applying it to our codebase and successfully passed the grpc-go tests.

**Comment by easwars** [comment]
With help from the community, we put together this doc about anti-patterns: https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md.

Is not using the three dial options `grpc.WithBlock()`, `grpc.FailOnNonTempDialError(true)`, and `grpc.WithReturnConnectionError()` an option for you?

And if you don't use them and instead rely on errors at RPC time, do you see the error that you expect?

**Comment by olegbespalov** [comment]
Hi, @easwars!

Thank you for getting back to me. Yes, I saw the https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md and found using these gRPC options is anti-pattern. I've started thinking about how we can re-design our API in the sense that it avoids using this anti-pattern, but unfortunately, the migration could take some time.

But I could see the case where `FailOnNonTempDialError` is still valuable, as I've described, when the user tries to connect with the wrong credentials, which is a non-temporary dial error. And for that particular one, it's good to tell the user earlier. Since it's experimental, I recognize the risks of using it, but since we already use it and are faced with something that looks incorrect and could be fixed with one line, this approach seems preferable to re-designing the API.

As I commented, I'm happy to open PR with the fix, but I need more time to get familiar with the codebase to write the proper test (right now, all tests are passing with and without the fix). But on the other side, I don't know what's your vision around the `FailOnNonTempDialError,` like maybe you're going to deprecate it soon :shrug:

**Comment by easwars** [comment]
@olegbespalov : We currently don't have any plans of marking `FailOnNonTempDialError` as deprecated.

> If needed, I could also try to prepare a code/repo that shows the issue, or I could also try to write a test

Would it be possible for you to setup a repro or a test for this issue? That would be great.

I think I buy your argument that calls to `connectionError` should use the `isTemporary()` function to determine if it is a temporary error or not. Maybe we need to audit other callsites of `connectionError` as well.

If you have a PR with test(s), feel free to send that over as well. Thanks for reporting this issue.
