### ISSUE TITLE
undefined grpc.SupportPackageIsVersion1 

### ISSUE THREAD

**Issue by tomq42** [grpc/grpc-go#663]
I'm attempting to build a grpc go client and have the above error.

I have done
go get google.golang.org/grpc
go get -a github.com/golang/protobuf/protoc-gen-go

Investigating this, it appears that the protoc plugin generates code with grpc.SupportPackageIsVersion1, but that the grpc code has grpc.SupportPackageIsVersion2.

I'm assuming I've done something wrong in the configuration or set up, but I can't see anything that would let me control this, nor do there appear to be any conditionals in the code that might generate different code for different versions. On the face of it it just looks like the two packages I have got are incompatible, which I find strange, and frustrating.

**Comment by Thomasdezeeuw** [comment]
You need to update grpc and protobuf, run `go get -u google.golang.org/grpc` and `go get -u github.com/golang/protobuf`, see https://github.com/grpc/grpc-go/issues/643.

**Comment by aaronbee** [comment]
It sounds to me that @tomq42 has an updated grpc, but an out-of-date compiled .pb.go file.

@tomq42 You should upgrade your go-protoc plugin:

`go get -u github.com/golang/protobuf/{proto,protoc-gen-go}`

And recompile your .proto files.

**Comment by iamqizhao** [comment]
As ppl already pointed out, you need to sync both grpc and protobuf to make it work. It is a nice feature we recently added to guarantee the compability of these two libraries.

**Comment by tomq42** [comment]
Hmm.
I can't reproduce this now, but I definitely did what my original description says in terms of how I got the packages, and it left with an incompatible pair. This was the first day I had tried to use go grpc, so there can't have been anything old lying around.
However since I can't reproduce, I'll leave it.

**Comment by leonid-shevtsov** [comment]
@tomq42 you might have had a vendored outdated `proto` package that was installed as some package's dependency.
