### ISSUE TITLE
Recommended way how to implement retries in a client

### ISSUE THREAD

**Issue by pavelpatrin** [grpc/grpc-go#6630]
What is the officially recommended way to implement retries? There are two options:

* Retry policy of [github.com/grpc/grpc-go](https://github.com/grpc/grpc-go/blob/master/examples/features/retry/client/main.go) project.
* Retry middleware of [github.com/grpc-ecosystem/go-grpc-middleware](https://github.com/grpc-ecosystem/go-grpc-middleware) project.

Which is recommended to use by community? Why retry middleware exists if we have built-in retry policy?

**Comment by easwars** [comment]
The retry policy support provided by gRPC is defined here: https://github.com/grpc/proposal/blob/master/A6-client-retries.md, and is configurable via service config. This is owned by the gRPC team.

The retry support in the middleware repo that you mention provides a way to do the same programmatically via interceptors. Please note that the gRPC team does not own this repo and I do not have enough knowledge about this to compare it with the option provided by gRPC.
