### ISSUE TITLE
resolver.UnregisterForTesting removed

### ISSUE THREAD

**Issue by redloaf** [grpc/grpc-go#6631]
`resolver.UnregisterForTesting` was removed in #6471. This was part of the public API and was removed with no deprecation notice. The discussion in the PR notes that it was previously used in internal Google code, but it is [used in other places](https://github.com/search?q=resolver.UnregisterForTesting+language%3AGo&type=code&l=Go).

**Comment by dfawley** [comment]
The whole package is clearly declared as experimental and is subject to change.  Let us know if you need help finding a workaround.

https://github.com/grpc/grpc-go/blob/9deee9ba5f5b654d38c737c701181dceebb57e44/resolver/resolver.go#L19-L21
