### ISSUE TITLE
Status.WithDetails uses proto.Message from deprecated protobuf library

### ISSUE THREAD

**Issue by rtjoseph11** [grpc/grpc-go#6632]
### What version of gRPC are you using?
1.58.0

### What version of Go are you using (`go version`)?
1.21

### What operating system (Linux, Windows, …) and version?
linux

### What did you do?
when calling the WithDetails function on status.Status you need to pass in a proto.Message from github.com/golang/protobuf. Go mod warns about that library:
```
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
````

### What did you expect to see?
using proto.Message from google.golang.org/protobuf

### What did you see instead?
proto.Message from github.com/golang/protobuf

**Comment by dfawley** [comment]
#5316
