### ISSUE TITLE
Unaryserverinterceptor in gRPC

### ISSUE THREAD

**Issue by salemmohammed** [grpc/grpc-go#6636]
Hello all, 

I have a client that sends many requests to a server, and I want to intercept these requests and reorder them before the handler. 
I'm trying to achieve this using a simple approach, where I use a gRPC unary server interceptor. 
In this approach, I receive each incoming request, put it into a channel(go-channel as you can see in my code below.), and then read from that channel to pass the request to the handler (ctx, req) function. 
However, I've encountered a problem where the calls are failing every time, and I'm not sure why. 

Note: If I place the lock from the beginning of the function and release it before the handler, the code works. That means only one request in the channel. 
If I placed locks before writing to the channel, then released it, and then locked again before reading and released it before handler, the code failed. I'm not sure why this approach is causing issues.

without placing the request into the Go channel, the code works fine, and no need for locks. 

var (
	Myqueue       = New()
	mymutex   	  sync.Mutex
	wg            sync.WaitGroup
	Channel1 = make(chan request,10000)
)
type request struct {
	ctx 	context.Context
	req    interface{}
	ts     interface{}
}
func Unaryserverinterceptor(ctx context.Context,req interface{},info *grpc.UnaryServerInfo,handler grpc.UnaryHandler) (interface{}, error) {

	
	mymutex.Lock()              // If i lock whole code from here and release the lock before handle, it works 
	newrequest := request{
		ctx: ctx,
		req: req,
	}
	go func() {
		fmt.Printf("newrequest.req: %v\n", newrequest.req)
		Channel1 <- newrequest
	}()
	mymutex.Unlock()

	mymutex.Lock()
	yy := <-Channel1
	req1 := yy.req
	ctx1 := yy.ctx
	fmt.Printf("req1: %v\n", req1)
	mymutex.Unlock()				

	res, err := handler(ctx1,req1)
	fmt.Printf("res: %v\n", res)
	fmt.Printf("err: %v\n", err)
	
	return res, err
}

I got an EOF error and then a dial error (dial tcp 127.0.0.1:26257: connect: connection refused). 

So, what are your suggestions to me, if possible?
Thank you all.

**Comment by easwars** [comment]
This doesn't look to be a gRPC-Go issue. Unfortunately, we don't have the time to help you with your code. If you can demonstrate clearly that there is a bug in gRPC-Go, please file an issue with the relevant details. Thanks.
