### ISSUE TITLE
Add contrib package, or add github.com/grpc/grpc-contrib-go (google.golang.org/grpc-contrib)?

### ISSUE THREAD

**Issue by peter-edge** [grpc/grpc-go#664]
Can we add one of:

1. A contrib directory, where contributors can add code in subdirs?
2. A repository github.com/grpc/grpc-contrib-go, which has a go import path of google.golang.org/grpc-contrib, with the same semantics?

The code added here would not be expected to be up to the same quality/review process as the rest of grpc-go, and would basically be merged as long as it compiles. The first option means that the code can always be tested against the latest grpc-go updates, so I would argue for that.

**Comment by iamqizhao** [comment]
It would be a separate repo instead of living in other grpc repo.

**Comment by zinuga** [comment]
Planning to add a single grpc-contrib repo across languages. have something to add?

**Comment by peter-edge** [comment]
One repo across all languages would be a different pattern right? It's going to be not as fun with go get and go build/test commands as it is right now with grpc-go.

Yes, I have a lot to add, heh.

**Comment by peter-edge** [comment]
What about splitting it as it is now, i.e. grpc-contrib/grpc-contrib-java/grpc-contrib-go?

**Comment by iamqizhao** [comment]
@zinuga I think per-language (Go, Java, C) contrib repo would be better as Peter suggested.

**Comment by iamqizhao** [comment]
https://github.com/grpc/grpc-contrib
