### ISSUE TITLE
grpc client cannot unpack headers, malformed `grpc-status` is multiple integers

### ISSUE THREAD

**Issue by mbrancato** [grpc/grpc-go#6640]
I have a client that is receiving a response from the server where the packed headers contain multiple comma separated zeros. This leads to an integer conversion failure.

I'm getting the following errors (sometimes `0,0,0` and sometimes `0,0` values):
```
rpc error: code = Internal desc = transport: malformed grpc-status: strconv.ParseInt: parsing \"0,0\": invalid syntax
rpc error: code = Internal desc = transport: malformed grpc-status: strconv.ParseInt: parsing \"0,0,0\": invalid syntax
```

Both are using `grpc-go` 1.58.1 and I'm not really sure where to begin to understand why it might have extra header data added. Not all responses are this way. I'm looking for some ideas on how to identify the cause of this.

There error happens here:
https://github.com/grpc/grpc-go/blob/94d8074c6133e17378ebea2977c436c274867dd2/internal/transport/http2_client.go#L1427-L1433

**Comment by ginayeh** [comment]
Thanks for reaching out to us.  @mbrancato Are you using a proxy or any other components in the middle?  If you have a proxy, it would be helpful to try to repro the issue you're seeing with a direct TCP connection so we have know if this is potentially related to the middleware.
