### ISSUE TITLE
Ticker leak in weighted round robin picker creation

### ISSUE THREAD

**Issue by atollena** [grpc/grpc-go#6642]
### What version of gRPC are you using?

1.57 (I believe the bug is still present on master)

### What version of Go are you using (`go version`)?

1.21.0

### What operating system (Linux, Windows, …) and version?

Linux

### What did you do?

I am using the `weighted_round_robin` balancer via service config.

I have servers set with MaxConnectionAge to 5 minutes as to force DNS re-resolultion per https://github.com/grpc/grpc-go/issues/1663#issuecomment-358048203.

### What did you expect to see?

CPU and memory usage stays constant.

### What did you see instead?

The CPU usage and memory used by the application keeps growing.

<img width="605" alt="Screenshot 2023-09-18 at 07 51 25" src="https://github.com/grpc/grpc-go/assets/1175711/ebaa72af-82a9-463e-88e9-baacc6ed364f">

**Comment by atollena** [comment]
Thanks to @HippoBaro for discovering this problem and the initial investigation.

I think the bug is just that this ticker: https://github.com/grpc/grpc-go/blob/61a1f7792387b2cce06869a49838741393b0e850/balancer/weightedroundrobin/balancer.go#L370-L379 is not properly closed. Suggested fix: https://github.com/grpc/grpc-go/pull/6643.

**Comment by easwars** [comment]
I hate the `Ticker`. This is the not the first time I'm seeing it cause a memory leak and probably wont be the last time either.

**Comment by atollena** [comment]
Yes, ideally there should be a vet rule for this.

**Comment by easwars** [comment]
Fixed by https://github.com/grpc/grpc-go/pull/6643.
