### ISSUE TITLE
Support for A44 xDS retry support

### ISSUE THREAD

**Issue by atollena** [grpc/grpc-go#6677]
### Use case(s) - what problem will this feature solve?

One of the promise of xDS is to be able to centrally control client behaviors. Retries are part of this, as outlined in the [A44-xds-retry gRFC](https://github.com/grpc/proposal/blob/master/A44-xds-retry.md). It is possible to configure retries for Go clients via service config, but not via xDS.

### Proposed Solution

Implement [A44-xds-retry gRFC](https://github.com/grpc/proposal/blob/master/A44-xds-retry.md).

### Alternatives Considered

N/A

### Additional Context

Quoting the gRFC:

> This functionality is being implemented in C-core and Java. It will be implemented in Go in the near future.

**Comment by atollena** [comment]
Opening this issue mostly to express and track interest. We do this via interceptors internally, but we can't promise centrally controlled retry behaviors for xDS as long as this isn't implemented.

**Comment by ginayeh** [comment]
Thanks for creating this.  Retry has already been implemented in grpc-go as listed in https://github.com/grpc/grpc/blob/master/doc/grpc_xds_features.md

Closing it for now and feel free to re-open if any specific use cases or details are neglected.

**Comment by atollena** [comment]
OK, thanks for the prompt answer, looks like I didn't look carefully enough.
