### ISSUE TITLE
apparent integer underflow in `transport.(*inFlow).onRead`

### ISSUE THREAD

**Issue by tamird** [grpc/grpc-go#670]
We are seeing these error messages in our logs, which very strongly suggest integer underflow:
```
I160505 13:44:12.623842 http2_server.go:317  transport: http2Server received 4294965918-bytes data exceeding the limit 1048560 bytes
I160505 13:44:12.623957 http2_server.go:317  transport: http2Server received 4294965976-bytes data exceeding the limit 1048560 bytes
```

Code in question: https://github.com/grpc/grpc-go/blob/master/transport/control.go#L194

See https://github.com/cockroachdb/cockroach/issues/6529

**Comment by iamqizhao** [comment]
Is the client the grpc-go client? Any way I can repro?

**Comment by tamird** [comment]
Yeah, the client is the grpc-go client. Honestly, I have no idea how to repro.

We could potentially discuss in the Cockroach issue.

**Comment by iamqizhao** [comment]
Are there any rpc cancellation/timeout/failure along with this symptom?

**Comment by tamird** [comment]
cc @mberhault

**Comment by mberhault** [comment]
this definitely occurs in the face of nodes being taken down, so failures or timeouts are very likely.
Unfortunately, it comes amidst a lot of traffic, so it's rather tricky to find exactly which happens. We should probably orchestrate some rpc logging, it may help diagnose this.

**Comment by bdarnell** [comment]
No timeouts show up in the logs; the only failures are "connection refused" (there's a chance that timeouts or failures are happening but not showing up in the logs). There are some cancellations in the logs but the first one doesn't show up until after we've already seen several of these errors.

**Comment by iamqizhao** [comment]
Please reopen if the issue remains.
