### ISSUE TITLE
Correct way to discover new servers

### ISSUE THREAD

**Issue by nikolaianohyn** [grpc/grpc-go#6718]
I would like to understand what's the best way for discovering new pods in kubernetes by grpc client. 
Initially I tried to use dns resolver + headless mode for kubernetes services. It works correctly when I am starting the client. But I realized that `func (d *dnsResolver) watcher()` is waiting for combination of 30s timeout + ResolveNow. Also I found out that if I set:
```
grpc.KeepaliveParams(keepalive.ServerParameters{
			MaxConnectionAge: time.Second * 30,
		}),
```
it helps me initiate ResolveNow operation on the client. But I really don't want to kill existing connections. What's the best way to initiate ResolveNow operation in my case?

**Comment by arvindbr8** [comment]
this is a known caveat when using gRPC with system like k8s. Please refer to the issue posted on grpc/grpc repo https://github.com/grpc/grpc/issues/12295. Also feel free to add your thoughts and comments on that issue. 

Closing this issue since it can be tracked in the other one.
