### ISSUE TITLE
Is there a way to know active open connections?

### ISSUE THREAD

**Issue by Kushal153** [grpc/grpc-go#6731]
Is there any way we can calculate the number of active connections

**Comment by Kushal153** [comment]
@arvindbr8 this is required at the server side, metric is required for production use

**Comment by arvindbr8** [comment]
A best option to consider would be to implement your own [statsHandler](https://pkg.go.dev/google.golang.org/grpc/examples/features/stats_monitoring/statshandler). This approach is extensible -- you consider getting other metrics to emit per RPC/connection basis.  

This [comment](https://github.com/grpc/grpc-go/issues/5823) on an old issue talks about a way of implementing something similar. 


-----

Please feel free to reopen this issue if you have other questions.
