### ISSUE TITLE
Stream Quota Leak following SettingMaxConcurrentStreams

### ISSUE THREAD

**Issue by stxmendez** [grpc/grpc-go#674]
I'm happy to submit a patch if the following explanation holds.

## Background
We’ve experienced issues where gRPC clients would seem to hang after some amount of invocations have been made against the Go Bigtable API.  The problem seems to randomly occur in about 1:3 runs.  If you add logging you can make the problem go away.

We have been able to reproduce the issue via the following horrible code [snippet](https://gist.github.com/akhenakh/adb03aa05ac1a6e85611422128d2a004) and running it with 2k-3k routines.  The code creates a WithTimeout context off of the Background context.  It then proceeds to cancel the WithTimeout context and then use it in invocations to the BT API.  As expected, the BT API calls fail due to the canceled context.  However, if you try to make one more call against BT using the parent context of the WithTimeout context the call hangs on line https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L282.

In this hang, the code is waiting for stream quota that will never become available.  The system will sit there for about 4 minutes until the client transport is torn down which causes the BT API invocation to conclude with an error.

## Debugging
As part of tracking this issue down, logging statements were added at several locations.  It was observed that adding log lines at specific points seemed to decrease or eliminate the likelihood of occurrence.  Regardless, every time the hang occurred, the goroutine invoking BT API was stuck on https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L282.

Further inspection revealed that when the test starts to run the client transport is running without any restrictions to max concurrent streams.  As the code makes more and more concurrent requests the system eventually receives a request to use http2.SettingMaxConcurrentStreams setting of 100 (https://tools.ietf.org/html/rfc7540#page-22).  This places the client code into a quota driven mode which attempts to limit the max concurrent streams in use to that new value by leveraging a channel to pass the current quota value back and forth.

When the code is running in this modality, it invokes a wait method https://github.com/grpc/grpc-go/blob/master/transport/transport.go#L499 which receives a channel (for quota among other reasons) which it monitors in a select statement.  Per the [Go Language Select Definition](https://golang.org/ref/spec#Select_statements) if multiple channels are ready, the channel is: “chosen via a uniform pseudo-random selection”.

So if you have a context that is canceled AND you have quota available, you may consume quota OR detect cancellation in a pseudo random manner.  So you could get quota via https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L282 yet fail to release it because https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L291 detects the canceled stream.  

## Possible Workarounds
Part of the problem here is that the comment on line https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L292 isn’t true since not all callers of NewStream will result in a call to CloseStream (https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L390) in all cases.

A hacky solution that avoids any refactoring is to update https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L292 to release the quota if it erroneously received any in https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L282.  This appears to address our issue, but it seems that the root is an assumption around how wait works with respect to precedence.

**Comment by iamqizhao** [comment]
Thanks for reporting. The fix will be out soon.

**Comment by stxmendez** [comment]
@iamqizhao I'd be interested in understanding what your fix will be.  If you could share your thoughts on the matter I would appreciate it.

**Comment by ianrose14** [comment]
@stxmendez Does your repro no longer fail after this merge?  I'm finding that if I use the current version of the bigtable & grpc packages, I can make your repro fail every so often (ballpark 1 out of 5 times, with para=3000).

**Comment by stxmendez** [comment]
@ianrose14 it addressed the issue that I had at the time.  We have not picked up an update in a couple of months.  I'm in the process of updating to bigtable v2 and latest grpc and can test this again.

**Comment by iamqizhao** [comment]
We are investigating this issue internally. It seems once an rpc timeout happens, the google frontend server stops working (the grpc client can still send requests to the google frontend servers but nothing is received till the rpc is timeout).

**Comment by stxmendez** [comment]
Great timing.  I was just about to respond back to @ianrose14 that I was able to reproduce the problem using the old snippet against the latest and greatest grpc and BT client v2 libs.

@iamqizhao - what is the public issue that can be used to track this problem?  Should we reopen this issue or do you have one that we can use?

**Comment by stxmendez** [comment]
@iamqizhao I was just looking at the behavior of this instance of the issue and the timeout is around 4 minutes as the last time.  I'm looking at the http2_server code and it also uses the wait function.  I wonder if under certain error conditions quota fails to be released and then we only recover via the 4 minute timer?  In any case, http2Server.Write around 575 looks curious on first blush.

**Comment by iamqizhao** [comment]
@stxmendez This should be an issue in cloud bigtable instead of grpc since as I stated, I think grpc client behaves as expected but google frontend server stops responding.

http2_server is irrelevant. The google frontend server and bigtable server are not written in grpc-go.

**Comment by dragonsinth** [comment]
When I ran the test harness myself and sent SIGQUITs while it appeared stuck, I always found a goroutine blocked here:

Every time I SIGQUIT a hung bt_fail, a goroutine is stuck here:

 ```golang.org/x/net/http2.readFrameHeader(0xc8201a20f8, 0x9, 0x9, 0x99f1e8, 0xc820156a80, 0x2000000, 0xc800000000, 0x0, 0x0)
    /Users/scottb/src/grpc-experiments/src/golang.org/x/net/http2/frame.go:237 +0xa5
```
Calling `io.ReadFull(r, buf[:frameHeaderLen])`

So it seemed to be stuck waiting on data from the server as per @iamqizhao notes.

**Comment by stxmendez** [comment]
@iamqizhao thanks for confirming that the bigtable server does not use grpc-go.  Is there a public issue that we can follow and get update on the internal investigations?

**Comment by ianrose14** [comment]
In case this info is useful, I'm finding it much easier to repro this on my local machine (a mac) rather than a GCE (linux) instance.  My local repro works at least 1/5 times locally, but often takes ~100 attempts to work on GCE.  Not sure if the difference is the OS or the latency differences, but I'd guess the latter.

**Comment by iamqizhao** [comment]
This has been fixed from both google GFE and grpc-go.
