### ISSUE TITLE
Is v1.59.0 compatible with Go 1.18 ?

### ISSUE THREAD

**Issue by fredyk** [grpc/grpc-go#6745]
### What version of gRPC are you using?

v1.59.0

### What version of Go are you using (`go version`)?

1.18

### What operating system (Linux, Windows, …) and version?

Ubuntu 22.04.3 (github actions)

### What did you do?

While running CI automated tests on westack-go, which depends on grpc-go, it reports that grpc-go 1.59.0 is not compatible with Go 1.18

### What did you expect to see?

I expected the new version to be compatible with Go 1.18

### What did you see instead?

```text
# google.golang.org/grpc
Error: /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:2082:14: undefined: atomic.Int64
note: module requires Go 1.19
```

https://github.com/fredyk/westack-go/actions/runs/6617244768/job/17973209594?pr=892#step:7:112

First time seen was in v1.58.3
https://github.com/fredyk/westack-go/actions/runs/6537636087/job/17751885150#step:7:109

**Comment by dfawley** [comment]
Per https://github.com/grpc/grpc-go#prerequisites, we only support the latest 3 releases of Go.

This even is a bit of a challenge for us, as many of our dependencies only support the latest 2 releases of Go, which means we sometimes need to pin those dependencies to an older release.  If this poses a problem (i.e. if there is a security fix in an update to a dependency that is not available with the N-2 version of Go), we may need to change our support policy to match that of our dependencies.

You can use an older version if you need support for an older version of Go, but then you won't get new features or most bug fixes.
