### ISSUE TITLE
protoc-gen-go-grpc: add tests

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#6748]
We don't currently have any tests in `protoc-gen-go-grpc`.  We should add something simple at least:

1. Create a `.proto` file with streaming / unary RPCs.
2. Generate the `.pb.go` file(s) from it and commit it/them.
3. Write a test that does (2) and diffs the results with the committed file(s).

**Comment by Aditya-Sood** [comment]
hi @dfawley, can I pick this up?

**Comment by dfawley** [comment]
@Aditya-Sood ?

**Comment by zedGGs** [comment]
@dfawley , Im looking what could be done here, but `Annotate` from `protogen` has been deprecated, do we need to take that in consideration too ?

**Comment by dfawley** [comment]
@zedGGs that seems unrelated.  At the moment there are no tests, which means any changes made here have to be tested manually.  If `Annotate` is deprecated then we should separately look into switching to whatever the alternative is, and having tests in place before making that change would help to ensure nothing is broken by the change.

**Comment by zedGGs** [comment]
@dfawley I can take this one, if thats okey for you, I will add tests for unary RPCs, and if that goes well in pull request, I can also add tests for other RPCs streaming options, 

feel free to assign me
