### ISSUE TITLE
interop: interop functions should not call context.Background() for RPCs

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#6763]
E.g. https://github.com/grpc/grpc-go/blob/70f1a4045da95b93f73b6dbdd7049f3f053c0680/interop/test_utils.go#L82-L83

This function and all others in this file should accept a context, which would allow passing RPC timeouts, metadata, etc.  `context.Background` is really only supposed to be called by `main`/`TestXyz` functions wherever possible.

**Comment by Aditya-Sood** [comment]
hi @dfawley, can I pick this up?

**Comment by dfawley** [comment]
@Aditya-Sood Yes, that would be great!  But note that we are going to be moving `stress/*` to `interop/stress/*`, so you might want to wait until that's done, first.

**Comment by Aditya-Sood** [comment]
I think that's done with the merge of #6769 now?

**Comment by arvindbr8** [comment]
@Aditya-Sood -- Yes that's right!
