### ISSUE TITLE
github.com/golang/protobuf/jsonpb is depricated

### ISSUE THREAD

**Issue by JesseLabruyere** [grpc/grpc-go#6791]
There are still some places where imports to the depricated "github.com/golang/protobuf/jsonpb" are being used.
The imports to "github.com/golang/protobuf/jsonpb" should probably be replaced with imports to "google.golang.org/protobuf/encoding/protojson". But it seems "google.golang.org/protobuf/encoding/protojson" does not contain the Marshaler and Unmarshaler structs which seems to be the only reason the old import is still in use.

The lines these imports are used:
https://github.com/grpc/grpc-go/blob/master/internal/pretty/pretty.go#L27
https://github.com/grpc/grpc-go/blob/master/xds/internal/xdsclient/bootstrap/bootstrap.go#L32

### What version of gRPC are you using?
google.golang.org/grpc v1.59.0

### What version of Go are you using (`go version`)?
go version go1.21.3 linux/amd64

### What operating system (Linux, Windows, …) and version?
Ubuntu 22.04.3 LTS

### What did you do?
import "google.golang.org/grpc"

### What did you expect to see?
No depricated indirect requires in the go.mod file.

### What did you see instead?
Deprecated module github.com/golang/protobuf.
Deprecation notice: Use the "google.golang.org/protobuf" module instead.

**Comment by dfawley** [comment]
Let's use #5316 for everything related to the v1 protobuf library.
