### ISSUE TITLE
Large concurrent streams deadlocked in writeQuota

### ISSUE THREAD

**Issue by mYmNeo** [grpc/grpc-go#6805]
### What version of gRPC are you using?
v1.58.3, but it affects all version of gRPC with `writeQuota`

### What version of Go are you using (`go version`)?
go1.21

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
If possible, provide a recipe for reproducing the error.

```
func (s) TestFlowControlWriteQuota(t *testing.T) {
	// Disable dynamic flow control.
	sc := &ServerConfig{
		InitialWindowSize:     defaultWindowSize,
		InitialConnWindowSize: defaultWindowSize,
	}
	co := ConnectOptions{
		InitialWindowSize:     defaultWindowSize,
		InitialConnWindowSize: defaultWindowSize,
	}
	server, client, cancel := setUpWithOptions(t, 0, sc, pingpong, co)
	defer cancel()
	defer server.stop()
	defer client.Close(fmt.Errorf("closed manually by test"))
	waitWhileTrue(t, func() (bool, error) {
		server.mu.Lock()
		defer server.mu.Unlock()
		if len(server.conns) == 0 {
			return true, fmt.Errorf("timed out while waiting for server transport to be created")
		}
		return false, nil
	})

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	stream, err := client.NewStream(ctx, &CallHdr{})
	if err != nil {
		t.Fatalf("Failed to create stream. Err: %v", err)
	}

	opts := &Options{}
	burstNum := 300
	msgSize := make([]int32, burstNum)
	for i := 0; i < burstNum; i++ {
		msgSize[i] = rand.Int31n(defaultWriteQuota) + defaultWriteQuota/4
	}

	errCh := make(chan error, burstNum*2)
	for _, size := range msgSize {
		go func(msgSize int32) {
			outgoingHeader := make([]byte, 5)
			outgoingHeader[0] = byte(0)
			binary.BigEndian.PutUint32(outgoingHeader[1:], uint32(msgSize))

			if err := client.Write(stream, outgoingHeader, make([]byte, msgSize), opts); err != nil {
				errCh <- fmt.Errorf("Error on client while writing message. Err: %v", err)
			}
		}(size)
	}

	go func() {
		incomingHeader := make([]byte, 5)
		for i := 0; i < burstNum; i++ {
			if _, err := stream.Read(incomingHeader); err != nil {
				errCh <- fmt.Errorf("Error on client while reading data header. Err: %v", err)
			}
			sz := binary.BigEndian.Uint32(incomingHeader[1:])
			recvMsg := make([]byte, int(sz))
			if _, err := stream.Read(recvMsg); err != nil {
				errCh <- fmt.Errorf("Error on client while reading data. Err: %v", err)
			}
		}

		client.Write(stream, nil, nil, &Options{Last: true})
		if _, err := stream.Read(incomingHeader); err != io.EOF {
			errCh <- fmt.Errorf("Client expected EOF from the server. Got: %v", err)
		}
		cancel()
	}()

	select {
	case <-errCh:
		t.Fatalf("Error while reading from stream: %v", err)
	case <-time.After(defaultTestTimeout):
		t.Fatalf("Timed out while reading from stream")
	case <-ctx.Done():
	}
}
```

### What did you expect to see?
Requests should be all finished

### What did you see instead?
Some request stuck and never got response

**Comment by arvindbr8** [comment]
@mYmNeo - Would like to know how you did you faced this issue? Did this happen in your production. If so we would like to know the more about your configuration. 
This issue seems very serious if happening. We have not seen this happening before, thats more reason why we would like to investigate this better.

**Comment by mYmNeo** [comment]
> @mYmNeo - Would like to know how you did you faced this issue? Did this happen in your production. If so we would like to know the more about your configuration. This issue seems very serious if happening. We have not seen this happening before, thats more reason why we would like to investigate this better.

1. I wrote a benchmark tool using 15k qps with 3 grpc connections, total requests are 1500k. The grpc stream server has the following configuration but I think it's not the root reason of this bug.
```
var KeepAliveServerParameters = keepalive.ServerParameters{
	MaxConnectionIdle: 10 * time.Second,
	Time:              5 * time.Second, // Ping the client if it is idle for 5 seconds to ensure the connection is still active
	Timeout:           1 * time.Second, // Wait 1 second for the ping ack before assuming the connection is dead
}

var KeepAliveServerEnforcementPolicy = keepalive.EnforcementPolicy{
	MinTime:             5 * time.Second, // If a client pings more than once every 5 seconds, terminate the connection
	PermitWithoutStream: true,            // Allow pings even when there are no active streams
}
```
Running the benchmark tool for a while, I found the client has sent 1500k request, but not receiving the same size response. 
2. No, the server is the production version, but it's not happened in real world only in the benchmark situation.
PS: the related issue are https://github.com/grpc/grpc-go/issues/5393

**Comment by arvindbr8** [comment]
Hi @mYmNeo - thanks for clarifying. Sorry I was out on vacation. 

> I wrote a benchmark tool using 15k qps with 3 grpc connections, total requests are 1500k. The grpc stream server has the following configuration but I think it's not the root reason of this bug.

Do you mind sharing the benchmarking tool with us. We would like to reproduce this on our side to get more details. Also would like to know how the benchmark test was run - the server/client setup and the environment where the benchmark was run. 

> 2. No, the server is the production version, but it's not happened in real world only in the benchmark situation.
PS: the related issue are https://github.com/grpc/grpc-go/issues/5393

The last [comment](https://github.com/grpc/grpc-go/issues/5393#issuecomment-1148851417) in the issue talks about why this most likely a usage bug than a gRPC bug. Could you take another look? 

 I would still be more inclined to believe that the deadlock is caused due to a usage bug. Or else this would really would have come up before with any of our heavy traffic gRPC-go users.

**Comment by mYmNeo** [comment]
> Hi @mYmNeo - thanks for clarifying. Sorry I was out on vacation.
> 
> > I wrote a benchmark tool using 15k qps with 3 grpc connections, total requests are 1500k. The grpc stream server has the following configuration but I think it's not the root reason of this bug.
> 
> Do you mind sharing the benchmarking tool with us. We would like to reproduce this on our side to get more details. Also would like to know how the benchmark test was run - the server/client setup and the environment where the benchmark was run.
> 
> > 2. No, the server is the production version, but it's not happened in real world only in the benchmark situation.
> >    PS: the related issue are [Large stream deadlocked in writeQuota #5393](https://github.com/grpc/grpc-go/issues/5393)
> 
> The last [comment](https://github.com/grpc/grpc-go/issues/5393#issuecomment-1148851417) in the issue talks about why this most likely a usage bug than a gRPC bug. Could you take another look?
> 
> I would still be more inclined to believe that the deadlock is caused due to a usage bug. Or else this would really would have come up before with any of our heavy traffic gRPC-go users.

Sure, the benchmark tool is a part of project(https://github.com/etcd-io/etcd), the patch is 
[0001-k8s-put.patch](https://github.com/grpc/grpc-go/files/13836978/0001-k8s-put.patch)
building command is `env CGO_ENABLED=0 go build -o benchmark tools/benchmark/main.go`
the command for tool is `benchmark k8s-put --total=200000 --clients=100 --conns=5 --watcher-total=100`

And the server project is (https://github.com/mYmNeo/kubebrain/tree/xsync)
building command is `make badger`
running server command is `kube-etcd --cluster-name=badger --data-dir=$(pwd)/data --enable-local-tso --enable-storage-metrics --history-capacity=500000 --watch-chan-capacity=500000 --logtostderr=true --leader-elect=false --compactor-num=64 --cache-enable=true --compact-duration=30s --progress-interval=2m --data-value-compress-level=0 --enable-compression=true --event-batch-size=100 --v=3`

**Comment by mYmNeo** [comment]
> Thanks for sharing that @mYmNeo.
> 
> [writeQuota](https://github.com/grpc/grpc-go/blob/master/internal/transport/flowcontrol.go#L30) is how flowcontrol works per stream. It decides whether a dataframe can be put into the underlying transports flow control. `writeQuota.get()` is only called on [transport.Write()](https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_client.go#L1033) and blocks if there is insufficient quota. Like the docstring calls out `the caller (to Write()) should proceed only if Write returns nil`. Which means there cannot be multiple calls on the same stream blocking on `writeQuota.get()`.
> 
> The setup that you have posted does not clarify gRPC's bug. A solid way to demonstrate (if it exists) would be if you could reproduce this in a gRPC client/server setup. The unit test that you've added does not replicate the actual behavior of gRPC. I'm still inclined to believe that this is not an actual bug.

That should be an actual bug. I changed the unit test to
```
	errCh := make(chan error, burstNum*2)
	for _, size := range msgSize {
		go func(mSize int32) {
			outgoingHeader := make([]byte, 5)
			outgoingHeader[0] = byte(0)
			binary.BigEndian.PutUint32(outgoingHeader[1:], uint32(mSize))

			if err := client.Write(stream, outgoingHeader, make([]byte, mSize), opts); err != nil {
				errCh <- fmt.Errorf("Error on client while writing message. Err: %v", err)
				return // return immediately
			}
		}(size)
	}

	go func() {
		defer cancel()

		incomingHeader := make([]byte, 5)
		for i := 0; i < burstNum; i++ {
			if _, err := stream.Read(incomingHeader); err != nil {
				errCh <- fmt.Errorf("Error on client while reading data header. Err: %v", err)
				break // return immediately
			}
			sz := binary.BigEndian.Uint32(incomingHeader[1:])
			recvMsg := make([]byte, int(sz))
			if _, err := stream.Read(recvMsg); err != nil {
				errCh <- fmt.Errorf("Error on client while reading data. Err: %v", err)
				break // return immediately
			}
		}

		client.Write(stream, nil, nil, &Options{Last: true})
		if _, err := stream.Read(incomingHeader); err != io.EOF {
			errCh <- fmt.Errorf("Client expected EOF from the server. Got: %v", err)
                         return // return immediately
		}
	}()
```
The `Write` function never return a error, but many goroutines block.

**Comment by arvindbr8** [comment]
> > Thanks for sharing that @mYmNeo.
> > [writeQuota](https://github.com/grpc/grpc-go/blob/master/internal/transport/flowcontrol.go?rgh-link-date=2024-01-10T04%3A30%3A13Z#L30) is how flowcontrol works per stream. It decides whether a dataframe can be put into the underlying transports flow control. `writeQuota.get()` is only called on [transport.Write()](https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_client.go?rgh-link-date=2024-01-10T04%3A30%3A13Z#L1033) and blocks if there is insufficient quota. Like the docstring calls out `the caller (to Write()) should proceed only if Write returns nil`. Which means there cannot be multiple calls on the same stream blocking on `writeQuota.get()`.
> > The setup that you have posted does not clarify gRPC's bug. A solid way to demonstrate (if it exists) would be if you could reproduce this in a gRPC client/server setup. The unit test that you've added does not replicate the actual behavior of gRPC. I'm still inclined to believe that this is not an actual bug.
> 
> I think it's an actual bug. I changed the unit test to
> 
> ```
> 	errCh := make(chan error, burstNum*2)
> 	for _, size := range msgSize {
> 		go func(mSize int32) {
> 			outgoingHeader := make([]byte, 5)
> 			outgoingHeader[0] = byte(0)
> 			binary.BigEndian.PutUint32(outgoingHeader[1:], uint32(mSize))
> 
> 			if err := client.Write(stream, outgoingHeader, make([]byte, mSize), opts); err != nil {
> 				errCh <- fmt.Errorf("Error on client while writing message. Err: %v", err)
> 				return // return immediately
> 			}
> 		}(size)
> 	}
> 
> 	go func() {
> 		defer cancel()
> 
> 		incomingHeader := make([]byte, 5)
> 		for i := 0; i < burstNum; i++ {
> 			if _, err := stream.Read(incomingHeader); err != nil {
> 				errCh <- fmt.Errorf("Error on client while reading data header. Err: %v", err)
> 				break // return immediately
> 			}
> 			sz := binary.BigEndian.Uint32(incomingHeader[1:])
> 			recvMsg := make([]byte, int(sz))
> 			if _, err := stream.Read(recvMsg); err != nil {
> 				errCh <- fmt.Errorf("Error on client while reading data. Err: %v", err)
> 				break // return immediately
> 			}
> 		}
> 
> 		client.Write(stream, nil, nil, &Options{Last: true})
> 		if _, err := stream.Read(incomingHeader); err != io.EOF {
> 			errCh <- fmt.Errorf("Client expected EOF from the server. Got: %v", err)
>                          return // return immediately
> 		}
> 	}()
> ```
> 
> The `Write` function never return a error, but many goroutines block.

That is the expected behavior. In your unit test there are multiple goroutines spun out calling Write(). However in a real scenario this cannot happen, and the caller of Write() should wait for write to return before proceeding. Which mean Write should not be called concurrently. There can only be one Write ever hanging to get stream writeQuota replenished. So there will not be a possibility of a deadlock here. 

The tests in the transport package are not setup in an end to end style. This is why we can come up with breaking test scenarios, but would never happen in real world by manner the top level gRPC code uses it.

**Comment by arvindbr8** [comment]
@nikitacrit -- We would like to know more about your setup. Providing us with something that we could run and reproduce would help us better understand the issue that you are running into. 

Also, 

> as a result I get huge amount of leaked goroutines caused by flow control quota

There are two flow control quota's in play within the transport. There is a stream level writeQuota and a quota maintain by the controlbuf. This issue talks about the former. writeQuota.get() blocks until there the quota is replenished. However, there can only be one goroutine blocking per stream. 

Could you clarify where are you seeing the leaked goroutines from? Also, are you seeing this on the server side or client side?

**Comment by arvindbr8** [comment]
The PR was closed only the ease of maintaince. Let us discuss here in the issue. Based on our decision we can always reopen the same PR.

**Comment by nikitacrit** [comment]
@arvindbr8 
Project to reproduce: https://github.com/nikitacrit/grpc-leak.
1. Run server from cmd/server
2. Run client from cmd/client
3. Just wait
4. Check pprof for server on :9000

I provide some screens and pprof sample below.
First row on screen with os stats (marked green) I see no memory issues. This is done after @mYmNeo patch. The next row (marked red) is current grpc patch. I apply patch with replace command.
`replace google.golang.org/grpc => github.com/mYmNeo/grpc-go v1.61.0-dev.0.20231207025256-b89b43a84f38`
![code](https://github.com/grpc/grpc-go/assets/74061731/1da6b430-9807-4289-92c9-d20e4f729166)
![pprof](https://github.com/grpc/grpc-go/assets/74061731/e9067a47-2119-4463-8f46-6762b8a54df1)
[profile.pb.gz](https://github.com/grpc/grpc-go/files/13892023/profile.pb.gz)

**Comment by arvindbr8** [comment]
@nikitacrit -- 

In your service handler implementation, you are calling stream.Send [concurrently](https://github.com/nikitacrit/grpc-leak/blob/main/internal/server/service.go#L22). Which is illegal. You need to wait for a Recv() before you can send again. 

See more. https://github.com/grpc/grpc-go/blob/master/stream.go#L125-L128

**Comment by dfawley** [comment]
> You need to wait for a Recv() before you can send again.

This is not quite the right way of expressing the constraint.  You can send many times between `Recv`s.  However, you must ensure that you only call `Send` _sequentially_.  Multiple concurrent calls to `Send` is illegal.

This is documented on the methods [here](https://pkg.go.dev/google.golang.org/grpc#ServerStream) and [here](https://pkg.go.dev/google.golang.org/grpc#ClientStream)
