### ISSUE TITLE
Where can I find Compatibility in terms of Client/Server with other GRPC languages

### ISSUE THREAD

**Issue by JoanFM** [grpc/grpc-go#6813]
Let's say I have a GRPC server in Golang, how can I know if I want to write a Python client, which version should I use? And viceversa?

Thanks for the help

**Comment by zasweq** [comment]
Hello, gRPC versions are all cross compatible (e.g. with respect to basic RPC functionality)! We have interop tests that run on each branch cross language. However, for specific features (e.g. something like Least Request Load Balancing client side), you can take a look at the release notes for each specific gRPC version.
