### ISSUE TITLE
How to implement LIFO style request handling in gRPC Go server?

### ISSUE THREAD

**Issue by manlinl** [grpc/grpc-go#6818]
gRPC Java allows to use a custom executor in which requests can be queued in a LIFO queue before assigned to worker thread. The major advantage of LIFO is, when server performance degrades, older requests are timeout in the queue. It is effectively a throttling/circuit breaker mechanism. However, It is not obvious how to config grpc-go to handle requests in LIFO fashion. 

Thank you!

**Comment by zasweq** [comment]
Define "requests" here. By the RPC's nature on top of HTTP/2, it receives pieces of an RPC (think a long lived stream), and header frames which create a "stream" server side (Unary and Streaming use a stream). We spawn a goroutine for every connection, and then every created stream on that connection we spawn another goroutine to process that: https://github.com/grpc/grpc-go/blob/master/server.go#L1024. This is for efficiency reasons. Thus, there is no way to process streams with an ordering guarantee, as there is no way to guarantee ordering off the wire.

**Comment by manlinl** [comment]
By "request" I mean unitary gRPC request. It is intuitive to use one goroutine per single gRPC stream. gRPC-java on the other hand, dispatches RPC handler to a thread pool. The underlying thread pool implementation can choose a custom queue to invoke handlers in LIFO order.T

hanks for the explanation.
