### ISSUE TITLE
How to enable verbose and trace logging in grpc client

### ISSUE THREAD

**Issue by sanamsarath** [grpc/grpc-go#6819]
**grpc client version**
google.golang.org/grpc v1.48.0 

**Background**
We have grpc-go client streaming data to remote server. When the third party server restarts because of issue of network dysconnectivity client is not able to re-establish the connection. From client application every time a new connection is requested different transportation level source port. The new connection always waits in "Idle" state

**What we know currently**
Captured pcap on the application and observed only DNS query but no tcp connection initiated - no syn/acks observed.

**What is needed**
How to enable grpc verbose and trace level logs?? trying to understand things under the hood

Thanks

**Comment by dfawley** [comment]
See this section of the readme to enable debug logging:

https://github.com/grpc/grpc-go#how-to-turn-on-logging

Generally speaking, if a connection is lost, the subchannel will become "IDLE", but as soon as an RPC is attempted, it will attempt to reconnect.
