### ISSUE TITLE
GRPC Call Blocked When client and the server are not on the same host

### ISSUE THREAD

**Issue by xixiwang12138** [grpc/grpc-go#6821]
When the grpc client and the server are not on the same host, the TCP connection can be established, but the request has been blocked and has not succeeded, and the request has not reached the server.

```
require (
	github.com/google/uuid v1.3.1
	google.golang.org/grpc v1.59.0
	google.golang.org/protobuf v1.31.0
)

require (
	github.com/golang/protobuf v1.5.3 // indirect
	golang.org/x/net v0.14.0 // indirect
	golang.org/x/sys v0.11.0 // indirect
	golang.org/x/text v0.12.0 // indirect
	google.golang.org/genproto/googleapis/rpc v0.0.0-20230822172742-b8732ec3820d // indirect
)
```

When on the same host, it can work normally

**Comment by pablodz** [comment]
To check if grpc is live, use reflection, you need to add few lines on server

https://github.com/grpc/grpc-go/blob/master/Documentation/server-reflection-tutorial.md#enable-server-reflection

then via grpcurl use command depending on your application

```
docker run --rm fullstorydev/grpcurl localhost:8080 list 
```

and the result will be something like this

```
~/home/service  docker run --rm fullstorydev/grpcurl localhost:50051 list                       
grpc.reflection.v1.ServerReflection
grpc.reflection.v1alpha.ServerReflection
aliveservice.AliveService # here you will see listed your functions
```
