### ISSUE TITLE
"Is there any way to make the grpc server ignore the 'grpc-timeout' header

### ISSUE THREAD

**Issue by kkHAIKE** [grpc/grpc-go#6844]
Currently, it recognizes and creates a timeout context by default, and there is no option to disable it.

**Comment by dfawley** [comment]
For future reference: no, this is not possible. The client communicates its deadline to the server, which honors it.  The client would cancel the RPC at that time, anyway, so there's no reason to ever ignore it.

**Comment by miparnisari** [comment]
@dfawley is there a way that the server can protect itself from requests that send a very high number for `Grpc-Timeout`? I mean by aborting before a given time, say 3 seconds.

**Comment by dfawley** [comment]
Servers can read the deadline with `ctx.Deadline()` (or `server.Context().Deadline()` for streaming RPC handlers).

But it's probably more typical to just do `ctx, cancel := context.WithTimeout(ctx, myDefaultTimeout /* could be longer or shorter than the context's timeout*/)` to apply the min of its default timeout or what the client specified.
