### ISSUE TITLE
HTTPS_PROXY is not working 

### ISSUE THREAD

**Issue by zhiweiyin318** [grpc/grpc-go#6846]
### What version of gRPC are you using?
v1.59.0
### What version of Go are you using (`go version`)?
go 1.20
### What operating system (Linux, Windows, …) and version?
linux
### What did you do?

I added tls for the hello world example https://github.com/grpc/grpc-go/blob/master/examples/helloworld
My codes is https://github.com/zhiweiyin318/grpctest
I have a squid proxy server enabled HTTP and HTTPS. 

I created tls files and start the server
```
./bin/server --cert="tls/server.crt" --key="tls/server.key"
```

When I set HTTP_PROXY, the client can access the server successfully. 
```
export  HTTP_PROXY=http://10.0.118.37:3128/
./bin/client --ca="tls/ca.crt" --addr="10.0.118.8:50051"
```

When I set HTTPS_PROXY, the client cannot access the server.  (have added the ca of squid to the tls/ca.crt)
```
export HTTPS_PROXY=https://10.0.118.37:3129/
./bin/client --ca="tls/ca.crt" --addr="https://10.0.118.8:50051"
2023/12/11 15:09:53 could not greet: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: reading server HTTP response: read tcp 10.0.116.95:34002->10.0.118.37:3129: read: connection reset by peer"
```
I captured the packages , the client did not setup TLS connect with the proxy server at the first, direct setup CONNECT 

<img width="1591" alt="image" src="https://github.com/grpc/grpc-go/assets/7592386/66a90a7e-ed54-4f1f-bb73-30b8c68439b8">

```
$ GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_GO_LOG_VERBOSITY_LEVEL=99 ./bin/client --ca="tls/ca.crt" --addr="https://10.0.118.8:50051"
2023/12/11 15:58:03 INFO: [core] [Channel #1] Channel created
2023/12/11 15:58:03 INFO: [core] [Channel #1] original dial target is: "https://10.0.118.8:50051"
2023/12/11 15:58:03 INFO: [core] [Channel #1] parsed dial target is: {URL:{Scheme:https Opaque: User: Host:10.0.118.8:50051 Path: RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}}
2023/12/11 15:58:03 INFO: [core] [Channel #1] fallback to scheme "passthrough"
2023/12/11 15:58:03 INFO: [core] [Channel #1] parsed dial target is: {URL:{Scheme:passthrough Opaque: User: Host: Path:/https://10.0.118.8:50051 RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}}
2023/12/11 15:58:03 INFO: [core] [Channel #1] Channel authority set to "https:%2F%2F10.0.118.8:50051"
2023/12/11 15:58:03 INFO: [core] [Channel #1] Resolver state updated: {
  "Addresses": [
    {
      "Addr": "https://10.0.118.8:50051",
      "ServerName": "",
      "Attributes": null,
      "BalancerAttributes": null,
      "Metadata": null
    }
  ],
  "Endpoints": [
    {
      "Addresses": [
        {
          "Addr": "https://10.0.118.8:50051",
          "ServerName": "",
          "Attributes": null,
          "BalancerAttributes": null,
          "Metadata": null
        }
      ],
      "Attributes": null
    }
  ],
  "ServiceConfig": null,
  "Attributes": null
} (resolver returned new addresses)
2023/12/11 15:58:03 INFO: [core] [Channel #1] Channel switches to new LB policy "pick_first"
2023/12/11 15:58:03 INFO: [core] [pick-first-lb 0xc0001c3410] Received new config {
  "shuffleAddressList": false
}, resolver state {
  "Addresses": [
    {
      "Addr": "https://10.0.118.8:50051",
      "ServerName": "",
      "Attributes": null,
      "BalancerAttributes": null,
      "Metadata": null
    }
  ],
  "Endpoints": [
    {
      "Addresses": [
        {
          "Addr": "https://10.0.118.8:50051",
          "ServerName": "",
          "Attributes": null,
          "BalancerAttributes": null,
          "Metadata": null
        }
      ],
      "Attributes": null
    }
  ],
  "ServiceConfig": null,
  "Attributes": null
}
2023/12/11 15:58:03 INFO: [core] [Channel #1 SubChannel #2] Subchannel created
2023/12/11 15:58:03 INFO: [core] [Channel #1] Channel Connectivity change to CONNECTING
2023/12/11 15:58:03 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to CONNECTING
2023/12/11 15:58:03 INFO: [core] [Channel #1 SubChannel #2] Subchannel picks a new address "https://10.0.118.8:50051" to connect
2023/12/11 15:58:03 INFO: [core] [pick-first-lb 0xc0001c3410] Received SubConn state update: 0xc0001c3560, {ConnectivityState:CONNECTING ConnectionError:<nil>}
2023/12/11 15:58:03 INFO: [core] Creating new client transport to "{Addr: \"https://10.0.118.8:50051\", ServerName: \"https:%2F%2F10.0.118.8:50051\", }": connection error: desc = "transport: Error while dialing: reading server HTTP response: read tcp 10.0.116.95:47224->10.0.118.37:3129: read: connection reset by peer"
2023/12/11 15:58:03 WARNING: [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {Addr: "https://10.0.118.8:50051", ServerName: "https:%2F%2F10.0.118.8:50051", }. Err: connection error: desc = "transport: Error while dialing: reading server HTTP response: read tcp 10.0.116.95:47224->10.0.118.37:3129: read: connection reset by peer"
2023/12/11 15:58:03 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to TRANSIENT_FAILURE, last error: connection error: desc = "transport: Error while dialing: reading server HTTP response: read tcp 10.0.116.95:47224->10.0.118.37:3129: read: connection reset by peer"
2023/12/11 15:58:03 INFO: [core] [pick-first-lb 0xc0001c3410] Received SubConn state update: 0xc0001c3560, {ConnectivityState:TRANSIENT_FAILURE ConnectionError:connection error: desc = "transport: Error while dialing: reading server HTTP response: read tcp 10.0.116.95:47224->10.0.118.37:3129: read: connection reset by peer"}
2023/12/11 15:58:03 INFO: [core] [Channel #1] Channel Connectivity change to TRANSIENT_FAILURE
2023/12/11 15:58:03 could not greet: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: reading server HTTP response: read tcp 10.0.116.95:47224->10.0.118.37:3129: read: connection reset by peer"
```

### What did you expect to see?
the client can access the server under HTTPS_PROXY env successfully.

**Comment by zhiweiyin318** [comment]
The error `Error while dialing: reading server HTTP response: read tcp 10.0.116.95:34002->10.0.118.37:3129: read: connection reset by peer` is from https://github.com/grpc/grpc-go/blob/52baf161f30fea87dd143e54dfd67d593f13bf80/internal/transport/proxy.go#L100

I guess the TLS info is not set  to the conn https://github.com/grpc/grpc-go/blob/52baf161f30fea87dd143e54dfd67d593f13bf80/internal/transport/proxy.go#L127 or the request before send  https://github.com/grpc/grpc-go/blob/52baf161f30fea87dd143e54dfd67d593f13bf80/internal/transport/proxy.go#L93

**Comment by easwars** [comment]
The grpc-go implementation simply uses the Go `http` package to get the proxy information. Specifically, it uses the `http.ProxyFromEnvironment` function to get the address of the proxy. grpc-go does not read/process the value the environment variable `HTTP_PROXY` or `HTTPS_PROXY` or `NO_PROXY. These are used by the `http` package.

The godoc for the `http` and `httpproxy` packages do call out some edge cases. See: https://pkg.go.dev/net/http#ProxyFromEnvironment and https://pkg.go.dev/golang.org/x/net/http/httpproxy#FromEnvironment. 

I would recommend ensuring that you are able to proxy http(s) traffic as per your expectation by setting these environment variables (without grpc involved), and then introduce grpc into the mix. That way, you can isolate where the problem is. Thanks.

**Comment by zedGGs** [comment]
Heey there, I wanted to mention that `BalancerAttributes` from `resolver` are deprecated, could that be potential issue, maybe no for this case, but some others ?

**Comment by dfawley** [comment]
It seems the misunderstanding is that HTTP_PROXY and HTTPS_PROXY are not the same thing as when those things point to `http://` or `https://` addresses.

HTTP_PROXY is used to proxy individual requests at the HTTP layer.

HTTPS_PROXY tunnels connections such that TLS can be negotiated between the client and server behind the proxy.

Either of those could contain an `http` or `https` address.

If we use either HTTP_PROXY or HTTPS_PROXY, gRPC will attempt to use CONNECT to tunnel the connection.  If that doesn't work (which could theoretically be the case for HTTP_PROXYs that weren't necessarily expecting that), it could cause errors.  If it does work, TLS will be negotiated directly between the client application and the server application, and the connection will be secure (or fail).

We do not support `https` addresses of proxies.  If that is essential for you, you might want to file a feature request at the cross-language repo via https://github.com/grpc/grpc/issues/new/choose.

cc @ejona86 @markdroth as FYI

**Comment by zhiweiyin318** [comment]
Hi, @dfawley I created a feature request https://github.com/grpc/grpc-go/issues/6887 And provide another simple solution for this https://github.com/grpc/grpc-go/pull/6888 (have verified using squid proxy server)
I think the other language repos could have supported this (not 100% sure). 
please comment on that issue or PR.
thanks.
