### ISSUE TITLE
Should HEADERS and DATA be sent in the same frame?

### ISSUE THREAD

**Issue by vellrya** [grpc/grpc-go#6850]
Hello.

I noticed that in some cases HEADERS and DATA are in different frames, but their size is much smaller than the maximum frame size (16kb). Can I configure something so that the HEADERS and DATA are sent in the same frame?

I would like to clarify that on multiple runs without modifying the code, the objects may or may not merge.

Variant 1:
![image_2023-12-12_03-47-58](https://github.com/grpc/grpc-go/assets/13716114/dcd706bd-e3a7-4f90-8c53-2838ecbe2595)

Variant 2:
![image_2023-12-12_03-57-06](https://github.com/grpc/grpc-go/assets/13716114/e1fd8737-9145-4d2a-aedc-197859af16bb)

> gRPC optimizes for the unary case by combining headers, data and trailer into a single HTTP/2 frame
https://grpc.io/docs/guides/metadata/#headers

gRPC: 1.59.0
go: 1.21.5

I assume it depends on the processing speed in loopyWriter run. For the experiment, I added a 10ms delay between iterations to the loop, and the three objects are now constantly merged into a single frame.

![image_2023-12-12_04-02-27](https://github.com/grpc/grpc-go/assets/13716114/85ead59c-8339-4618-95e5-7b8b2fd5bc89)

**Comment by easwars** [comment]
Could you please elaborate on what you are trying to do here?

HEADERS and DATA are separate HTTP/2 frames and therefore will be transmitted that way.

**Comment by vellrya** [comment]
Let me try to explain it with an example. This is how capture looks like from a real application using grpc implementation in Java:
![image_2023-12-15_22-49-05](https://github.com/grpc/grpc-go/assets/13716114/179565ba-35c1-4061-9dff-c33655ae56f4)
![image_2023-12-15_22-53-39](https://github.com/grpc/grpc-go/assets/13716114/1b4675f9-1e59-4dd1-8a89-e22fc1474786)

The headers and data are sent in the same frame, which is the same as this explanation:

> gRPC optimizes for the unary case by combining headers, data and trailer **into a single HTTP/2 frame**
> https://grpc.io/docs/guides/metadata/#headers

---

However, grpc-go does not satisfy this condition, different frames are used to send headers and data for the same request.
![image_2023-12-15_23-02-42](https://github.com/grpc/grpc-go/assets/13716114/fffbf8d0-ed1d-43f5-94c1-0e2da13e8b4f)
![image_2023-12-15_23-03-46](https://github.com/grpc/grpc-go/assets/13716114/3eb342ba-6e3b-4490-86f4-6e9e296f417b)

**Comment by easwars** [comment]
> gRPC optimizes for the unary case by combining headers, data and trailer into a single HTTP/2 frame
[grpc.io/docs/guides/metadata/#headers](https://grpc.io/docs/guides/metadata/#headers)

That statement in our docs seems to be false and needs to be fixed. I will follow-up and get this fixed.

Combining all these frames into a single packet at the TCP level does seem like a very micro optimization. Could you please let us know how this is affecting you or what is it that you are trying to do? Thanks.

**Comment by vellrya** [comment]
Yes, I agree with you, it is unlikely to significantly increase performance in this way. But it seems to me that this optimization is quite logical and is used in other languages)
I specified the issue type as a question, so if you think this optimisation is unnecessary, feel free to close it

**Comment by easwars** [comment]
This optimization is not a priority for the team. But if the change is simple, and if you are interested in making the change and sending a PR, we would be happy to review.

**Comment by dfawley** [comment]
We did some work a long time ago to attempt to make this happen sometimes, but we do not guarantee it.

Specifically, we do this gosched call here to allow other goroutines an opportunity to write more data to the buffer before we do the syscall to write it:

https://github.com/grpc/grpc-go/blob/c109241f34f9394e3cb070ca747d3e682462e068/internal/transport/controlbuf.go#L588
