### ISSUE TITLE
Add function to enumerate all methods

### ISSUE THREAD

**Issue by mwitkow** [grpc/grpc-go#689]
While working with Prometheus gRPC interceptors, I encountered a need to access all full service names registered with the given server. (see https://github.com/mwitkow/go-grpc-prometheus/issues/5#issuecomment-219898272) 

This would avoid some pitfalls with Prometheus data models, and make counter increments faster (as it would allow for pre-computing a lookup table).

@iamqizhao would something like this be upstream-able? :)

**Comment by brian-brazil** [comment]
In addition this would need to know about any newly registered services/methods.

**Comment by iamqizhao** [comment]
I am not strongly against this. We can probably make it happen along with the server reflection support @menghanl is working on. It may provide richer information -- e.g., beside all method names it may also provide the type info of the input&output params.

**Comment by mwitkow** [comment]
Server reflection would be awesome!

@menghanl is there any draft proposal you could share? ☺️

**Comment by menghanl** [comment]
@mwitkow here is the proto for server reflection:
https://github.com/grpc/grpc/blob/master/src/proto/grpc/reflection/v1alpha/reflection.proto

**Comment by menghanl** [comment]
@mwitkow @brian-brazil 
FYI, in #726, a new API `GetServiceInfo()` is added to `grpc.Server`, which can be used to get all registered services.
But we didn't find an appropriate way to pass the information to an interceptor. One possible workaround for you is to add an init function taking `grpc.Server` as an argument and do initialization, similar to [`reflection.Register()`](https://github.com/grpc/grpc-go/blob/master/reflection/serverreflection.go#L77).

**Comment by mwitkow** [comment]
Cool, thanks that will definitely work for us :)

**Comment by mwitkow** [comment]
@menghanl I hit a problem with `ServiceInfo`: there's no marker on it whether the given RPC is a stream or a unary one. It would be fantastic if we surfaced similar info as the `StreamServerInfo`, which is how `https://github.com/mwitkow/go-grpc-prometheus` differentiates between types.
