### ISSUE TITLE
Compatibility issues between go mod gRPC and etcd versions

### ISSUE THREAD

**Issue by ibarryyan** [grpc/grpc-go#6892]
The pb.go file I generated using protobuf displays：

```go
// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7
```

But I don't know which etcd client dependency is compatible with this higher version of gRPC dependency

**Comment by arvindbr8** [comment]
Hi @ibarryyan -- probably a question for the etcd repository?

**Comment by ibarryyan** [comment]
@arvindbr8 Thanks！
I have already resolved it，to use `go.etcd.io/etcd/etcdctl/v3`
