### ISSUE TITLE
Requesting functionality to replace error message format

### ISSUE THREAD

**Issue by saisrikark** [grpc/grpc-go#6893]
Whenever a message is returned from gRPC, it is in this format
"rpc error: code = %s desc = %s"
https://github.com/grpc/grpc-go/blame/4f03f3ff32c983f2e9b030889041ff9d5ffb6aeb/internal/status/status.go#L168

Is there a way to override this and have our own way of returning the error to the end user.
Could not find an interface for this.

Has this not been implemented because it might be difficult to get the status code on the client side?
Do let me know if I'm missing something.

**Comment by ginayeh** [comment]
I believe this is unsupported at this point.  Can you provide context about your use cases?

**Comment by saisrikark** [comment]
Thank you for responding.
When we expose a RPC using gRPC and make a request (gRPC client or HTTP doesn't matter) we see a message like 
 "rpc error: code = %s desc = %s" in case an error is returned.
 
 This format is quite grotesque to display a consumer/client.
 I would like to customize this response to suit my own preferences while maintaining client side functionality.
 i.e I should still be able to fetch the error code and other tasks on the client side.
 
 Do let me know if further clarification is required.

**Comment by dfawley** [comment]
The typical way to deal with grpc errors would be to do something like:

```go
if status, ok := status.FromError(err); ok {
	// use status.Code(), status.Message(), etc.
}
```
