### ISSUE TITLE
ALPN implementation needed in Client side

### ISSUE THREAD

**Issue by prakrit55** [grpc/grpc-go#6894]
ALPN should be configured in client side in order for a feasible connection with the server. Since according to the issue #2742, currently the server accepts using the http/2 but the implementation has to be performed in client side too with `ALPN` configured.

### Use case(s) - what problem will this feature solve?
#2742 certainly depicts the requirement

### Additional Context
This is a subpart of the issue #434.

**Comment by prakrit55** [comment]
Hey @arvindbr8, I think I got the idea wrong previously. Actually, we need to configure the client to detect the protocol in server and execute the process, and if it dosent find the protocol it should give an error.

**Comment by arvindbr8** [comment]
I need to get some context on the original issue. Let me take a look at it and get back to you

**Comment by arvindbr8** [comment]
Let's track this now in #434 and finalize what needs to be done. We can reopen if this is potentially a fix that is required.
