### ISSUE TITLE
stats: Add RemoteAddr and LocalAddr to RPCStats 

### ISSUE THREAD

**Issue by pellared** [grpc/grpc-go#6897]
### Use case(s) - what problem will this feature solve?

A `stats.Handler` implementation needs to capture the peer address in the `HandleRPC`.

The reason is that I want to add the gRPC client and server addresses as attributes to spans and metrics recorded by a stats handler.

For example imagine you would like to add the remote (peer, client) address as an additional attribute here:

https://github.com/grpc/grpc-go/blob/4f03f3ff32c983f2e9b030889041ff9d5ffb6aeb/stats/opencensus/trace.go#L81-L124

### Proposed Solution

Add `RemoteAddr` and `LocalAddr` fields to `RPCStats`.

### Alternatives Considered

None

### Additional Context

The gRPC server address attribute is recommended for all metrics by the current version of OpenTelemetry Semantic Conventions: https://opentelemetry.io/docs/specs/semconv/rpc/rpc-metrics/#attributes

Both the gRPC server and address attributes are recommended for all span by the current version of OpenTelemetry Semantic Conventions: https://opentelemetry.io/docs/specs/semconv/rpc/rpc-spans/

Here are some explorations: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4539

**Comment by zasweq** [comment]
Scaling up the RPCStats interface is not what we desire here. I think you should be able to pull out the peer with peer.FromContext, which will have the local address and remote address. Let me triage this though to see if this population of peer comes before all the stats handler callouts (I know some callouts will have it, but I don't know if all will).

**Comment by pellared** [comment]
@zasweq  Is it normal that for the gRPC Client I can only get the peer stats using `peer.FromContext(ctx);` for `case *stats.OutHeader:`? Should it not work for each `HandleRPC`? Is this behavior documented anywhere?

**Comment by zasweq** [comment]
It works in every HandleRPC call, since it is populated before.

**Comment by pellared** [comment]
> It works in every HandleRPC call, since it is populated before.

I think does not for the client's stats handler. Should I create an issue with repro steps?

**Comment by pellared** [comment]
@zasweq I created https://github.com/grpc/grpc-go/issues/6947
