### ISSUE TITLE
Make rpcError public

### ISSUE THREAD

**Issue by vikstrous** [grpc/grpc-go#692]
Since rpcError [is not public](https://github.com/grpc/grpc-go/blob/54222d50cc54928f54ebb47ad55797858e0a0268/rpc_util.go#L317), a user of your library can't inspect the type of the underlying error in order to handle it safely. The only option for handling errors right now is to do string matching, which fragile because it's likely to break with new versions. Please consider making this struct public so that users can type cast your errors and inspect the upstream error type.

**Comment by JohanSJA** [comment]
Perhaps this [function](https://godoc.org/google.golang.org/grpc#Code) can help?

**Comment by menghanl** [comment]
As @JohanSJA mentioned, grpc.Code(err) should be able to give you the error code.
I'm closing this issue now. Please reopen if it is not resolved.

**Comment by tamird** [comment]
@menghanl FYI @JohanSJA will not be able to reopen this issue.
