### ISSUE TITLE
How to get message size for RPC call

### ISSUE THREAD

**Issue by jo-me** [grpc/grpc-go#6920]
Hi,

I'm interested in tracking RPC response payload sizes to create client metrics (think payload size distribution).
Using a custom StatsHandler I can get callbacks that contain the InPayload struct which (probably) contains the size I'm interested in.

However, the StatsHandler is defined on the connection level and not on the per RPC level which means I don't know which StatsHandler callback is for which RPC call (due to concurrent requests).

What is the easiest way to get the payload size after the RPC has completed?

Thanks 

Jochen Mehlhorn <jochen.mehlhorn@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH

[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by ginayeh** [comment]
Thakns for reaching out.  The HandleRPC(context.Context, RPCStats) method on stats.Handler is called multiple times during a request-response cycle, and various event stats are passed to its RPCStats parameter (an interface). 

You can also find examples of monitoring RPC stats at https://github.com/grpc/grpc-go/tree/master/examples/features/stats_monitoring
