### ISSUE TITLE
when reference the 1.60.1 version from a go module which use bazel to build. got the erros below.

### ISSUE THREAD

**Issue by andyliuliming** [grpc/grpc-go#6929]
external/org_golang_google_grpc/internal/transport/http2_client.go:180:18: undefined: internal.NetDialerWithTCPKeepalive
external/org_golang_google_grpc/internal/transport/proxy.go:127:24: undefined: internal.NetDialerWithTCPKeepalive

**Comment by zasweq** [comment]
We do not maintain the bazel repository or the bazel rules. I think that the issue you would need to fix would be in the bazel repository.

**Comment by amit-mittal** [comment]
For anyone who runs into this issue, upgrading `gazelle` to `v0.31.1` fixed it for me.
