### ISSUE TITLE
stats.InPayload.RecvTime not accurate

### ISSUE THREAD

**Issue by blwt** [grpc/grpc-go#6932]
### What version of gRPC are you using?
v1.60.1

### What version of Go are you using (`go version`)?
go version go1.21.6 darwin/arm64

### What operating system (Linux, Windows, …) and version?
MacOS 14.2.1

### What did you do?
Creating a gRPC client with a status handler...
```go
client, err := grpc.Dial("localhost:50051", grpc.DialOption(grpc.WithStatsHandler(&myStatsHandler{})))
```
With a debugger, add a break point in ```proto.Unmarshal``` and ```stats.Handler.HandleRPC``` where ```stats.RPCStats == *stats.InPayload```.  What you should see is the break point in ```proto.Unmarshal``` happens before ```stats.Handler.HandlerRPC``` with ```stats.RPCStats == *stats.InPayload```.   As a result, ```stats.InPayload.RecvTime``` includes the timing of ```proto.Unmarshal``` which is not accurate.

This is different than `*stats.OutPayload.SentTime` which marks the sent time after `proto.Marshal`, which is more accurate.

### What did you expect to see?
Expected `*stats.InPayload.RecvTime` to record the time once the gRPC client receive the data which should be before `proto.Unmarshal`

### What did you see instead?
When gathering gRPC client status using `stats.Handler` in `google.golang.org/grpc/stats`, `*stats.InPayload.RecvTime` is not accurate enough because it also includes the time of `proto.Unmarshal`.

**Comment by zasweq** [comment]
This is WAI. A "InPayload" refers to a payload at the application layer. It even has a field called length, which is the length of the message. Thus, it cannot know how long the payload is until it unmarshals the message from the bytes off the wire. Thus, including proto unmarshaling time is the correct behavior here.
