### ISSUE TITLE
No timeout for connection backoff except RPC timeout?

### ISSUE THREAD

**Issue by frbvianna** [grpc/grpc-go#6935]
> How do we limit the connection backoff without setting a timeout for the entire RPC?

This question remains unanswered from this closed issue: https://github.com/grpc/grpc-go/issues/6812#issuecomment-1854537231

**Comment by zasweq** [comment]
The answer is within the thread. There are different knobs for connection timeout and rpc timeout.

**Comment by zasweq** [comment]
https://github.com/grpc/grpc-go/blob/master/server.go#L529 here is the connection timeout option. For RPC's, you can use the context timeout.

**Comment by zasweq** [comment]
A connection backing off is WAI and built into the gRPC protocol. See https://chromium.googlesource.com/external/github.com/grpc/grpc/+/release-0_9/doc/connection-backoff.md for more information. Thus, connections retrying is capped by the minimum connection timeout, and the time between attempts continues to increase "to avoid flooding the network or the server with requests"

**Comment by frbvianna** [comment]
> The answer is within the thread. There are different knobs for connection timeout and rpc timeout.

See my latest comment in https://github.com/grpc/grpc-go/issues/6812#issuecomment-1908008881. 
It's still not clear to me how one would achieve a **separate connection timeout than the RPC timeout**. 
I don't see how a server option helps in that, if the server is down in the first place, how is that option limiting the connection timeout?
