### ISSUE TITLE
No timeout for connection backoff except RPC timeout in client-side?

### ISSUE THREAD

**Issue by frbvianna** [grpc/grpc-go#6941]
> The answer is within the thread. There are different knobs for connection timeout and rpc timeout.

See my latest comment in https://github.com/grpc/grpc-go/issues/6812#issuecomment-1908008881. 
It's still not clear to me how one would achieve a **separate connection timeout than the RPC timeout**. 
I don't see how a server option helps in that, if the server is down in the first place, how is that option limiting the connection timeout?

_Originally posted by @frbvianna in https://github.com/grpc/grpc-go/issues/6935#issuecomment-1908016463_

**Comment by schmitcn** [comment]
Hi!
I'm having a similar issue:

I have a long-running bidi stream (so I cannot set the RPC timeout too short, otherwise I will have to keep reopening it), but when the server is inaccessible, the client "hangs" as the connection is retried until the -rather high- RPC timeout.
How does grpc-go recommend dealing with this? It seems to me to be a valid use case for gRPC to have long-running RPC streams with a high timeout but a low connection retry timeout. The server option mentioned in #6812 seems like an interesting approach, but it is not sufficient for the scenario where the server itself is inaccessible.

**Comment by zasweq** [comment]
A connection timeout is about establishing a TCP Connection. A RPC timeout is a timeout for the round trip time for an RPC on a TCP Connection. You can use WithConnectParams to change the logic of the TCP Connection backoff. The ServerOption is unrelated. For RPC timeouts, you can use the context. Like I mentioned in other issue, most users really don't need to use WithConnectParams, and should use RPC timeouts.

@schmitcn the recommended way of dealing with this is have a server send a message or headers on the stream, and the client then enforces its own timeout. There is no client side timeout provided by gRPC for stream establishment in every language.

**Comment by frbvianna** [comment]
> A connection timeout is about establishing a TCP Connection. A RPC timeout is a timeout for the round trip time for an RPC on a TCP Connection. You can use WithConnectParams to change the logic of the TCP Connection backoff. 

So how can we use the WithConnectParams to specify that the client must stop the connection backoff after e.g. 10 seconds, even if the RPC timeout is higher?

**Comment by zasweq** [comment]
See the documentation linked in the docstring of the DialOption https://github.com/grpc/grpc-go/blob/master/dialoptions.go#L253. https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md this is the outline of the algorithm which the DialOption provides knobs for. Also, an RPC happens on a connection, so it needs the connection to be established first before sending an RPC.

**Comment by schmitcn** [comment]
> A connection timeout is about establishing a TCP Connection. A RPC timeout is a timeout for the round trip time for an RPC on a TCP Connection. You can use WithConnectParams to change the logic of the TCP Connection backoff. The ServerOption is unrelated. For RPC timeouts, you can use the context. Like I mentioned in other issue, most users really don't need to use WithConnectParams, and should use RPC timeouts.
> 
> @schmitcn the recommended way of dealing with this is have a server send a message or headers on the stream, and the client then enforces its own timeout. There is no client side timeout provided by gRPC for stream establishment in every language.

Hi @zasweq,
I did not get your solution. It does not seem to resolve my issue. In case the server is inaccessible for performing a stream RPC, how can I avoid the client indefinitely retrying to establish the connection?
