### ISSUE TITLE
Wait for ready with "readiness timeout"

### ISSUE THREAD

**Issue by gnvk** [grpc/grpc-go#6948]
### Use case(s) - what problem will this feature solve?

We have a long running stream (`rpc Stream(StreamRequest) returns (stream StreamResponse) {}`). On the client side we would like to open the stream and then have it open indefinitely. If a recoverable error happens, we would like to restart it. If a non-recoverable error happens, we would like to quit. 

### Proposed Solution

It would be great if the WaitForReady flag had an optional "readiness timeout": a timeout only for having the connection ready, not for the whole RPC.

#### Timeout in the retry config
``` json
{
  "methodConfig": [{
    "name": [{"service": "..."}],
    "waitForReady": true,
    "timeout": "10s",
  }]
}
```
The timeout in the above config unfortunately stops the stream even if it's ready (and flowing).

#### Stream context timeout
``` go
ctx, cancel := context.WithTimeout(ctx, 3 * time.Second)
defer cancel()
stream, err := client.Stream(ctx, &streampb.StreamRequest{})
```
Same issue: this will cancel the stream after 3 seconds even if there were no errors at all.

#### Connection context timeout
``` go
// waitForReady is true in the retryConfig
ctx, cancel := context.WithTimeout(ctx, 3 * time.Second)
defer cancel()
conn, err := grpc.DialContext(ctx, address, grpc.WithDefaultServiceConfig(retryConfig))
```
This will never timeout if the server is not available.

#### Timeout in a different goroutine
``` go
timeout := 3 * time.Second
timer := time.NewTimer(timeout)
errCh := make(chan error)
go func() {
  stream, err := client.Stream(ctx, &streampb.StreamRequest{})
  defer timer.Stop()
  if err != nil {
    errCh <- err
    return
  }
  errCh <- readStream(ctx, stream)
}()
go func() {
  <-timer.C
  errCh <- fmt.Errorf("stream timeout after %s", timeout)
}()
return <-errCh
```
This works as expected: if we manage to connect to the stream within 3 seconds, it will stream until `ctx` is canceled. If we don't, we return an error. The problem is that the error is not very helpful ("stream timeout after 3s"). We cannot use the stream returned by `client.Stream()`, because with wait for ready it never returns.

**Comment by dfawley** [comment]
Wait-for-ready is often not a good idea, particularly with long-lived streaming RPCs (i.e. no deadline), and even more so if you need the stream to start working in a short amount of time.  Why are you using WFR?

Another option would be to stop using WFR and retry the stream a few times manually if it fails before your 3s stream establishment deadline.

**Comment by gnvk** [comment]
Retrying without WFR is exactly what we're doing now. Maybe I should've listed it as a considered alternative. But to me WFR would seem like a better approach, if its timeout worked as described in this feature request. Without it we're trying to send the RPC in a retry loop (with exponential backoff between the requests) but this doesn't really make any sense while the connection is not ready, does it?

And the 3s timeout is just an example, of course. The use case that motivated trying out the wait for ready option is that the server is simply restarted. Normally that only takes a few seconds and all its clients should reconnect as soon as possible. But on the other hand if there's a misconfiguration (e.g. the client tries to connect to a wrong address), we should see that error after a reasonable timeout, instead of waiting forever.

**Comment by dfawley** [comment]
> this doesn't really make any sense while the connection is not ready, does it?

The problem with WFR is that the name is misleading.

*ALL* RPCs wait until the channel is ready while it is connecting.  The difference with WFR is that it will survive if the channel goes into a failure mode.  This is rarely important to anyone.  Note that even if the server restarts, the client does not go into failure unless it takes too long for the restart and the reconnection attempt times out or if it gets I/O errors when reconnecting.

**Comment by dfawley** [comment]
> But on the other hand if there's a misconfiguration (e.g. the client tries to connect to a wrong address), we should see that error after a reasonable timeout, instead of waiting forever.

In this case, what are you doing in the event of a timeout?  Logging?  Changing health status?  Etc?

**Comment by gnvk** [comment]
> ALL RPCs wait until the channel is ready while it is connecting. The difference with WFR is that it will survive if the channel goes into a failure mode. This is rarely important to anyone. Note that even if the server restarts, the client does not go into failure unless it takes too long for the restart and the reconnection attempt times out or if it gets I/O errors when reconnecting.

When the server restarts, without wait for ready the client RPC returns with this error instantly:
```
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial │ds finished completely"}
tcp <ip>:9090: connect: connection refused
```

> In this case, what are you doing in the event of a timeout? Logging? Changing health status? Etc?

This depends on the particular client. Logging is always a good idea. Sending an alert, restarting the client are other options.

**Comment by gnvk** [comment]
Btw I'm playing with the service config, and the retry policy doesn't seem to work either. Given this config:
``` json
{
	"methodConfig": [{
		"name": [{"service": "%s"}],
		"retryPolicy": {
			"MaxAttempts": 30,
			"InitialBackoff": ".01s",
			"MaxBackoff": "1s",
			"BackoffMultiplier": 2,
			"RetryableStatusCodes": ["UNAVAILABLE"]
		}
	}]
}
```
the stream RPC call returns instantly with the above Unavailable error.

**Comment by dfawley** [comment]
> without wait for ready the client RPC returns with this error instantly

Hmm, yes, in that case if `Dial` fails, then channel will transition into TRANSIENT_FAILURE.

How are you restarting your servers?

Are you just doing a hard restart, or shutting them down with a `GracefulStop`, a timeout, then a hard `Stop`?

If an RPC has started on the server, then it is normally not retryable through the service config retry.

**Comment by gnvk** [comment]
> How are you restarting your servers?

In production the server is running in a Kubernetes pod and a "restart" means that the pod is restarted. But a very similar behaviour can be seen locally if you simply kill (Ctrl+C), or don't even start the server.

**Comment by dfawley** [comment]
This is not the recommended way to restart your servers (though you application needs to be resilient to server crashes, of course).  Ideally you would catch SIGINT/etc and do a `GracefulStop` + some grace period + `Stop` instead.  If you have long-running streams, you would also signal them at that time (after `GracefulStop`) to end their RPCs ASAP.

I would recommend something like this:

```go

var stream pb.FooClientStream
for {
	var err error
	if stream, err = client.Foo(ctxWithoutDeadline, req); err == nil {
		break
	}
	if clientConn.State() != connectivity.TransientFailure {
		return err
	}
	if !clientConn.WaitForStateChange(ctxWithDeadline, connectivity.TransientFailure) {
		return ctxWithDeadline.Err()
	}
}
// use stream
```

Using wait-for-ready is probably not what you want here, and with the option you're proposing, the RPC could fail in other ways besides "couldn't connect in time" (e.g. connection loss after RPC started), so you'll always need a loop around stream establishment.

**Comment by gnvk** [comment]
Thank you @dfawley 🙂  This is very close to what we're already using, with the additional `WaitForStateChange`, which I quite like 👍 

Actually, it's pretty much exactly what this proposal proposed: a `waitForReady` with the requested "readiness timeout". The (small) downside of this solution is that this code needs to be copy-pasted to wrap every single stream RPC calls (vs the single default service config).

**Comment by dfawley** [comment]
Sounds good.  I think the problem here that is preventing you from doing the simple thing is that you're getting RPC errors when your server restarts, which should be avoidable IIUC by shutting the server down gracefully.  If those errors weren't occurring, this would be simply:

```go
stream, err := client.Foo(ctxWithoutDeadline, req)
if err != nil {  // this is only ever a connection error or an internal/programmer error
	return err
}
```

With service config retries on UNAVAILABLE, I believe this should also retry in all the scenarios we're talking about.  If you aren't seeing that, then I'd be interested in a repro case if you have one.

I'm fairly sure the case I was talking about that isn't retriable isn't possible at this stage.  It would only occur after this returns, and a subsequent stream read might return a non-retriable UNAVAILABLE error.

**Comment by dfawley** [comment]
If you're logging in an interceptor, you won't see multiple calls, because interceptors are invoked per channel operation, not per attempt operation.

Also, you're not seeing 5s elapse because retries happen with a delay of `rand(0, backoff)`:

https://github.com/grpc/proposal/blob/master/A6-client-retries.md#integration-with-service-config

When I added your test to try to repro this, and logging in gRPC, I see the appropriate behavior:

https://github.com/dfawley/grpc-go/tree/testretry

```
    tlogger.go:111: ERROR stream.go:623 [core] Should retry? rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:9090: connect: connection refused"  (t=+1.785625ms)
    tlogger.go:111: ERROR stream.go:709 [core] RP=&{MaxAttempts:5 InitialBackoff:1s MaxBackoff:1s BackoffMultiplier:1 RetryableStatusCodes:map[Unavailable:true]}; fact=1, cur=1e+09  (t=+1.831392ms)
    tlogger.go:111: ERROR stream.go:716 [core] Timer with duration 181.966465ms  (t=+1.850658ms)
    tlogger.go:111: ERROR stream.go:721 [core] time to retry  (t=+183.947434ms)
    tlogger.go:111: ERROR stream.go:623 [core] Should retry? rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:9090: connect: connection refused"  (t=+184.003701ms)
    tlogger.go:111: ERROR stream.go:709 [core] RP=&{MaxAttempts:5 InitialBackoff:1s MaxBackoff:1s BackoffMultiplier:1 RetryableStatusCodes:map[Unavailable:true]}; fact=1, cur=1e+09  (t=+184.057532ms)
    tlogger.go:111: ERROR stream.go:716 [core] Timer with duration 777.045481ms  (t=+184.08327ms)
    tlogger.go:111: ERROR stream.go:721 [core] time to retry  (t=+962.094056ms)
```

(etc)

**Comment by gnvk** [comment]
@dfawley Thank you for the clarification and for your help :) 

I can live with the workaround you suggested (loop + wait for change), but in my opinion it's less convenient than what I'm suggesting in this feature request. If you disagree, feel free to close this issue.

**Comment by dfawley** [comment]
I don't think this proposal is likely to be accepted (for the reasons mentioned above), but if you do want to pursue it, it would be best to file an issue in the grpc/grpc repo, since it would need to be accepted cross-language first.  I'll close this, but feel free to reference it if you do file one.
