### ISSUE TITLE
Add new function to grpc ClientConn 

### ISSUE THREAD

**Issue by joel-rieke** [grpc/grpc-go#6967]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?
Under certain scenarios for security reasons, it would be useful to know if a connection has connected to the loopback interface (127.0.0.1).

### Proposed Solution
Add a function isLoopback() bool -- this would return true if the connection is physically connected to the loopback interface.  Don't really care about the naming of the function... as long as it provides the needed info.

### Alternatives Considered
Directly constructing my own Connecting and feeding it into grpc.  This seems unwieldy since grpc definitely has the information needed.

**Comment by ginayeh** [comment]
Can you share more context about what you try to achieve with the new function?  We might already have something to serve the purpose, so it would be helpful to know more about use cases before adding new funciton.
