### ISSUE TITLE
Reuse compression buffer

### ISSUE THREAD

**Issue by ash2k** [grpc/grpc-go#6970]
### Use case(s) - what problem will this feature solve?

gRPC's compression code allocates a `bytes.Buffer` for each sent message. This code is responsible for 25% of RAM allocations in my program.

https://github.com/grpc/grpc-go/blob/d41b01db97ca2e3627b2c9949fffe8f152a4255d/rpc_util.go#L658

<img width="813" alt="Screenshot 2024-02-08 at 11 09 27 am" src="https://github.com/grpc/grpc-go/assets/126021/9e29d656-1407-4b33-b59a-c98675400703">

### Proposed Solution

Reuse `bytes.Buffer` using a `sync.Pool`.

### Additional Context

**Comment by jzelinskie** [comment]
To the folks interested in this behavior that are open to using third-party dependencies, I suggest https://github.com/mostynb/go-grpc-compression

It's got a lot of more efficient algorithms, too.

**Comment by easwars** [comment]
We've made some recent changes to introduce a new encoding API which addresses this issue. See: https://github.com/grpc/grpc-go/pull/7356

Would appreciate your feedback on how the new changes work for you.

Also, I'm closing this, and if you still have issues, please use https://github.com/grpc/grpc-go/issues/6619 or file a new issue. Thanks.
