### ISSUE TITLE
gRPC client reports the wrong status code if server response contains an unsupported encoding

### ISSUE THREAD

**Issue by jhump** [grpc/grpc-go#6987]
According to the [gRPC docs for compression](https://github.com/grpc/grpc/blob/master/doc/compression.md), when a server sends a response using an unrecognized/unsupported encoding the client MUST report the error with an "internal" error code. (See bullet 5 in the [test cases](https://github.com/grpc/grpc/blob/master/doc/compression.md#test-cases) section of that doc.)

The reverse case (client sends a request using an encoding not supported by the server) on the other hand must use an "unimplemented" error.

In grpc-go, _both_ of the above situations result in an "unimplemented" error. Receiving messages in both the client and server runs through the `checkRecvPayload` function in [`rpc_util.go`](https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L733-L735) which always returns "unimplemented". It should instead have a condition so that it returns "internal" when called from a client.

**Comment by dfawley** [comment]
That sounds right to me.  If the client uses `UNIMPLEMENTED` in this case, it could be confused with the method not being implemented on the server.

Note that this scenario is missing from https://github.com/grpc/grpc/blob/master/doc/statuscodes.md

**Comment by Gayathri625** [comment]
I would like to pick this up
