### ISSUE TITLE
Unable to Perform Server-Side Stream Initialization Checks in gRPC Client-Side Streaming RPC to return error on stream creation

### ISSUE THREAD

**Issue by mostafafarzaneh** [grpc/grpc-go#6988]
I'm currently working on a gRPC implementation where the client is in Go, and the server is in C++. I have a client-side streaming RPC, and I want to perform some checks on the server when the client creates a new stream. Specifically, I want the server to return an error if it is busy.

However, I've observed that the server code only executes when the client starts sending requests, not during the creation of the stream itself. To overcome this, I had to send a dummy message to the server to check if it is busy or not.

Is this the expected behavior in gRPC, or am I missing something in my implementation?

**Comment by zasweq** [comment]
What does "is busy" semantically mean here? If you want to check if the server just doesn't create the stream, you can use the timeout in the context, and it will return an error. Once a stream is created, your application handler can use it to signal back to the client based off properties about the server whether it is busy or not.

**Comment by arvindbr8** [comment]
Great. Hope that solves your issue :)
