### ISSUE TITLE
Make server workers channel buffered?

### ISSUE THREAD

**Issue by YangXin-Sheep** [grpc/grpc-go#6992]
This would increase latencies, since then up to `numServerWorkers` requests can be indefinitely queued until we free up a worker.  Without buffering such a request would instead be handled by a spawned goroutine immediately.

_Originally posted by @SaveTheRbtz in https://github.com/grpc/grpc-go/pull/6004#discussion_r1162222636_

**Comment by YangXin-Sheep** [comment]
someone's benchmark shows buffered channel can speed up channel select，it means buffered channel is more effect. if requests queued means cpu overload or slow io. in cpu overload case  spawn a goroutine immediately can not effect，because requests queued just from channel queue move to golang runtime queue. in slow io case, just can improve input qps. so I think  buffered channel can improve proformance

**Comment by SaveTheRbtz** [comment]
Do you have a repro case where NumStreamWorkers with buffering on the `serverWorkerChannel` is significantly faster?

Current approach is based on the following logic: if all `NumStreamWorkers` goroutines are busy then spawning new goroutine is O(us), while buffering the request and waiting for a free goroutine is O(ms to seconds). Hence, the current approach tries to minimize tail latencies of the server.

**Comment by YangXin-Sheep** [comment]
q

**Comment by YangXin-Sheep** [comment]
> Do you have a repro case where NumStreamWorkers with buffering on the `serverWorkerChannel` is visibly faster?
> 
> Current approach is based on the following logic: if all `NumStreamWorkers` goroutines are busy then spawning new goroutine is O(us), while buffering the request and waiting for a free goroutine is O(ms to seconds). Hence, the current approach tries to minimize tail latencies of the server.


In another word，if channel buffer appear accumulate. It means goroutine will also accumulate in Processor.

**Comment by zasweq** [comment]
If you think this approach is faster, can you provide a benchmark with the difference?

**Comment by YangXin-Sheep** [comment]
> If you think this approach is faster, can you provide a benchmark with the difference?

**https://zhuanlan.zhihu.com/p/101063277** In this benchmark shows suitable buffered channel is more faster.

**Comment by SaveTheRbtz** [comment]
On the micro-benchmark side there is no doubt, based on Amdahl's law, that a buffered channel would be faster. But if this was the only concern developers care about channels would not even have a non-buffered mode.

It would be better if you showed the benefit of buffered channel using an end-to-end test with `grpc-go` with `NumStreamWorkers` set on a simple web-app using something like k6.  (ideally, using different setting for the buffer size to see the scaling properties.)

**Comment by arvindbr8** [comment]
Hi @YangXin-Sheep  -- Like @SaveTheRbtz suggested - it would be great if you could show us the benefit of buffered channel using an `gRPC-go` example since the benchmark results that you provided just shows us the benefit of buffered go channels. 

that being said, even if we decide to enable NumStreamWorkers with buffering on the serverWorkerChannel - Not sure what the right size of the buffer should be.
