### ISSUE TITLE
Question: PING frame

### ISSUE THREAD

**Issue by reatang** [grpc/grpc-go#6998]
gRPC version: 1.57.0

Dear developer
    Why is there always a PING frame after each grpc request frame?

![image](https://github.com/grpc/grpc-go/assets/8022923/eee6e55e-bb13-4c89-8e1a-8b09824494d1)

**Comment by reatang** [comment]
There is another question.  The purpose of ping is to maintain the heartbeat when the connection is idle.  But with `kpDormant` mechanism, the heartbeat will not be sent when there is no `activeStreams`.  Does it violate the original intention of the ping function?

[Related code](https://github.com/grpc/grpc-go/blob/v1.57.2/internal/transport/http2_client.go#L1703)

**Comment by reatang** [comment]
> There is another question. The purpose of ping is to maintain the heartbeat when the connection is idle. But with `kpDormant` mechanism, the heartbeat will not be sent when there is no `activeStreams`. Does it violate the original intention of the ping function?
> 
> [Related code](https://github.com/grpc/grpc-go/blob/v1.57.2/internal/transport/http2_client.go#L1703)

From my understanding, the keepalive function is mainly for stream rpc, not for unary rpc.

**Comment by arvindbr8** [comment]
> From my understanding, the keepalive function is mainly for stream rpc, not for unary rpc.

Keepalive is less likely to be triggered for unary RPCs with quick replies. Keepalive is primarily triggered when there is a long-lived RPC, which will fail if the keepalive check fails and the connection is closed.

Did you have Keepalive parameters being set to something other than default in the benchmark setup above?

**Comment by reatang** [comment]
> > From my understanding, the keepalive function is mainly for stream rpc, not for unary rpc.
> 
> Keepalive is less likely to be triggered for unary RPCs with quick replies. Keepalive is primarily triggered when there is a long-lived RPC, which will fail if the keepalive check fails and the connection is closed.
> 
> Did you have Keepalive parameters being set to something other than default in the benchmark setup above?

No, I'm using grpc's default configuration.

**Comment by arvindbr8** [comment]
Could you send up the repo and maybe the wireshark dump posted above?

**Comment by reatang** [comment]
According to my latest learning results, this Ping may be BDPPing 😆 . WINDOW_UPDATE

if server setting:
```
server := grpc.NewServer(
		grpc.InitialWindowSize(1 << 24),
		grpc.InitialConnWindowSize(1 << 24),
	)
```

and client setting:
```
	options := []grpc.DialOption{
		grpc.WithInitialConnWindowSize(1 << 24),
		grpc.WithInitialWindowSize(1 << 24),
	}
```

then there will be no more

**Comment by arvindbr8** [comment]
Glad this was resolved!
