### ISSUE TITLE
Context cancellation when request finishes

### ISSUE THREAD

**Issue by NeonWizard** [grpc/grpc-go#7016]
Are contexts cancelled automatically when a request completes? I couldn't find anything in the code that suggests it would by default, but when the timeout header is specified, a context `WithTimeout` and its associated `defer cancel()` is created, which does make the context cancel when the request finishes.

I'm trying to fire off goroutines in the request that should cancel if the client cancels the request, but should not cancel if the request completes. Is this possible?

**Comment by dfawley** [comment]
> Are contexts cancelled automatically when a request completes? 

Yes, they are:

https://github.com/grpc/grpc-go/blob/2a617ca67a6b10f38850843c22be4156c4590a3f/internal/transport/http2_server.go#L1276-L1279

> I'm trying to fire off goroutines in the request that should cancel if the client cancels the request, but should not cancel if the request completes. Is this possible?

Yes, but note that there are races possible between returning from the method handler and the client canceling the RPC.  So you can't perfectly distinguish these things in any system.

E.g.

```go
func MethodHandler(ctx context.Context, ......) {

	ctx2, cancel := context.WithCancel(context.Background())
	done := make(chan struct{})
	defer(close(done))
	go func() {
		select {
			case <-ctx.Done():
				cancel()
			case <-done:
		}
	}()
	// use ctx2
}
```

If you're very paranoid about the race between the context getting cancelled upon returning and `done` being closed before returning, then you can add a fallback check:

```go
	go func() {
		select {
			case <-ctx.Done():
				select {
					case <-done:
						// done was also closed; do nothing
					default:
						// done was not closed, so it must be client-initiated cancelation
						cancel()
				}
			case <-done:
		}
	}()
```

If you want `ctx2` to carry the same deadline, then copy it over via [Context.Deadline()](https://pkg.go.dev/context#Context).
