### ISSUE TITLE
Conn.resetTransport failed to create client transport: connection error: desc = "transport: x509: certificate signed by unknown authority" with certificate generated by Let's encrypt

### ISSUE THREAD

**Issue by jtblin** [grpc/grpc-go#702]
I must be doing something wrong as I can't get the client to connect to a server using Let's encrypt (ACME) certificates. Error:

> Conn.resetTransport failed to create client transport: connection error: desc = "transport: x509: certificate signed by unknown authority"

I know the certificate is valid, verified by running a simple Go http server:

![image](https://cloud.githubusercontent.com/assets/1388974/15626193/8bad79bc-2501-11e6-808f-60b127dc9d1f.png)

Here is part of the server code:

```
(...)
	ta := credentials.NewTLS(tlsConfig)
	listener, err := net.Listen("tcp", ":8443")
	if err != nil {
		panic("failed to listen: " + err.Error())
	}
	grpcServer := grpc.NewServer(grpc.Creds(ta))
	pb.RegisterGreeterServer(grpcServer, &server{})
	if err = grpcServer.Serve(listener); err != nil {
		panic(err)
	}
```

Here is part of the client code:

```
func main() {
	// Set up a connection to the server.
	conn, err := grpc.Dial(address, grpc.WithTransportCredentials(credentials.NewClientTLSFromCert(nil, "")))
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	defer conn.Close()
	c := pb.NewGreeterClient(conn)

	// Contact the server and print out its response.
	name := defaultName
	if len(os.Args) > 1 {
		name = os.Args[1]
	}
	r, err := c.SayHello(context.Background(), &pb.HelloRequest{Name: name})
	if err != nil {
		log.Fatalf("could not greet: %v", err)
	}
	log.Printf("Greeting: %s", r.Message)
}
```

I couldn't really find any doc showing how to setup the client properly apart from https://chromium.googlesource.com/external/github.com/grpc/grpc-go/+show/refs/heads/master/Documentation/grpc-auth-support.md

Help would be much appreciated.

**Comment by iamqizhao** [comment]
This is not an grpc issue. My speculation is that CA is not loaded properly (e.g., due to the wrong path, etc.). I am not an expert here. Please use google to find the solutions (e.g., https://github.com/docker/docker/issues/8849).

**Comment by jtblin** [comment]
Thanks @iamqizhao. The same certificate loads perfectly fine with the Go http server as per the screenshot above so it looks like the certificate is correct.

Did the example code above for the grpc client and server looked correct to you? I haven't seen real example of using TLS so I am not entirely sure I am doing the right thing.

Example code for the http side:
```
	listener, err := tls.Listen("tcp", ":8443", tlsConfig)
	if err != nil {
		panic("Listener: " + err.Error())
	}

	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) { w.Write([]byte("ok")) })

	// To enable http2, we need http.Server to have reference to tlsConfig
	// https://github.com/golang/go/issues/14374
	server := &http.Server{
		Addr:      ":8443",
		Handler:   mux,
		TLSConfig: tlsConfig,
	}
	server.Serve(listener)
```

The `tlsConfig` is initialised exactly the same for grpc, the certificate is returned using the `GetCertificate` method of `*tls.Config`.

The browser definitely can see the authority and recognize it:

![image](https://cloud.githubusercontent.com/assets/1388974/16189178/65b45e38-371c-11e6-8c9b-1431aa0714e7.png)

But in the case of grpc, the error comes from the client and says it cannot recognize it:

> transport: x509: certificate signed by unknown authority

Does that look correct? `conn, err := grpc.Dial(address, grpc.WithTransportCredentials(credentials.NewClientTLSFromCert(nil, "")))`

**Comment by jtblin** [comment]
Actually you're right, I get the same error when using the Go http client to make the request so Chrome knows the CA but not Go so it looks like the CA is not loaded properly as you said. Sorry to bother you with that.
