### ISSUE TITLE
Why does `/internal/transport/proxy.go` `doHTTPConnectHandshake` call `resp.Body.Close()`?

### ISSUE THREAD

**Issue by troymanchester** [grpc/grpc-go#7021]
I'm confused by this [line of code](https://github.com/grpc/grpc-go/blob/master/internal/transport/proxy.go#L102).

Doesn't calling `resp.Body.Close()` at the end of the function prevents proxy callers from reading the response? I believe I'm running into this trying to test something locally.

It seems much more likely that there's something misconfigured on my end vs there being a bug in this line of code thats been around for 7 years. I'd love if anybody could share some context around why that line of code is present.

**(Full Context)**
I am using grpc-go via [this telegraf code](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/gnmi/handler.go#L65). I have a proxy configured which is picked up by gprc-go via `HTTPS_PROXY` environment variable.

What I've experienced: proxy logging & tcpdump indicate that the TCP handshake with the device does occur, but telegraf fails to retrieve any data from the device. I've then forked telegraf & recompiled it - copying the grpc-go proxy.go code directly into telegraf and then removing `defer resp.Body.Close()`. When I then re-run my test, telegraf receives a steady stream of data from the device. This indicates to me that this line of code is what's causing the behavior I'm seeing.

**Comment by dfawley** [comment]
This HTTP request is the CONNECT request with the proxy that sets up the connection to be tunneled.  It's a complete request, not an open-ended thing, so closing the response body shouldn't affect the ability for the connection to tunnel data after that.  AFAIK no proxy actually sets a body in the response anyway, and we don't read it even if they do.

https://datatracker.ietf.org/doc/html/rfc2817#section-5.2

Another implementation of the a proxy CONNECT handshake that I found via google just now:

https://github.com/magisterquis/connectproxy/blob/3582e84f0c9b7b32dca59adfb152d77d9fa2f8c2/connectproxy.go#L285-L287
