### ISSUE TITLE
gRPC error ResourceExhausted should include payload size in error details

### ISSUE THREAD

**Issue by fredrb** [grpc/grpc-go#7024]
### Use case(s)

Incoming gRPC messages that exceed the `MaxCallRecvMsgSize`  will result in `.Recv()` function returning a  `ResourceExhausted` error. 

The error is written like:
```
rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (29651950 vs. 25165824)
```

The message is useful, but the important information (number `29651950`) is encoded in the string.

In order to do something useful with this number, such as incrementing a metric point or dynamically increase the threshold, I would need to extract the value from the string, which could easily break if the string format changes. 

### Proposed Solution

Add the attemped value to the error details slice. It would be ideal if could write my code as:
```go
if err != nil {
    if sErr, ok := status.FromError(err); ok && sErr.Code() == codes.ResourceExhausted{
        for _, d := range sErr.Details() {
            if exhaustedDetails, ok := d.(status.ExhaustedDetails); ok {
                // e.g. do something with exhaustedDetails numbers
                metrics.RegisterResourceExhaustedSize(exhaustedDetails.ActualMessageSize())
            }
        }
    }
}
```
This abtraction is just an example. Anyway I could get `29651950` would be useful. 

### Alternatives Considered

- Parsing the string
- Setting the threshold to a larger value and rejecting the message if it's above the virtual limit

**Comment by dfawley** [comment]
These messages are for debugging purposes.  You should not be parsing the string.  But also we will not generate error details inside of gRPC itself.  Why do you need the value programmatically?  Metrics would typically be based on the status code, and dynamically increasing the limit doesn't seem to make sense (just use a higher limit?).
