### ISSUE TITLE
mismatched MethodDesc.Handler types

### ISSUE THREAD

**Issue by weiwei04** [grpc/grpc-go#704]
When I compile my grpc code encounter a compile error

![image](https://cloud.githubusercontent.com/assets/2130651/15669049/e487dd56-2750-11e6-83d2-734f5aca13b2.png)

It seems like, the protoc compiled code are mismatched with grpc.handler type

generated code:
![image](https://cloud.githubusercontent.com/assets/2130651/15669145/5b4d1ece-2751-11e6-8a03-f8755711c859.png)

grpc.handler type
![image](https://cloud.githubusercontent.com/assets/2130651/15669162/6c5db7aa-2751-11e6-945d-b46e5d2d1638.png)

more informations...
1. I install protobuf on my mac with brew install protobuf --devel
![image](https://cloud.githubusercontent.com/assets/2130651/15668986/860af060-2750-11e6-9f6e-df3c538280ff.png)
![image](https://cloud.githubusercontent.com/assets/2130651/15668998/987931d0-2750-11e6-8093-3a22002986e6.png)
1. go get google.golang.org/grpc
   commitid 8213ee577a465c1f314d85748fb29e4eeed59baf
2. go get -a github.com/golang/protobuf/protoc-gen-go
   MD5 (protoc-gen-go) = 8fa7fc31b2257a89a25afade6534bba5
3. compile code with
   protoc -I ../protos ../protos/xxx.proto --go_out=plugins=grpc:xxx

**Comment by menghanl** [comment]
It seems your protoc-gen-go is outdated.
Can you do an update `go get -u github.com/golang/protobuf/protoc-gen-go`, and see if that works?

**Comment by weiwei04** [comment]
Thanks, It seems like an old version protoc-gen-go in another library override the new version, after update, the problem solved.
