### ISSUE TITLE
Retry and Backoff Clarification / Enabling Connection Retries

### ISSUE THREAD

**Issue by cha-king** [grpc/grpc-go#7043]
👋 Hey there! I've spent a bit too much time mulling over docs and Github issues trying to understand the retry logic provided here, so I figure I'll just ask for clarification!

To provide some context, I was initially attempting to avoid implementing my own retry logic, and was inspired by [this example](https://github.com/grpc/grpc-go/blob/master/examples/features/retry/README.md) to configure service config for retries. On doing so, I became a bit confused by the configuration. By tearing down my gRPC server and standing it back up again, I was able to see that the client connection was being re-established, but what confused me was that there was no point where the retries seemed to "give up". Given the maxAttempts value in the example, I would think that the retries would "give up" pretty quickly, but I found that it seemed to retry indefinitely. I could also confirm that the longer I waited, the longer it would take for the connection to be re-established when I started the server again, which seems to indicate the exponential backoff is coming into play.

After some digging around, I think the issue in my case was that the server config retries only seem to cater to RPC calls that are explicitly met with status codes from the server. I was very confused because the client errors I was receiving had the UNAVAILABLE status code, which I was configuring the retryPolicy for, but I imagine the policy doesn't come into play unless that code is provided via the server rather than via the client / library. Is that accurate?

I'm left a bit confused because, if the above is true, I would think that the retryPolicy I set before wasn't doing anything, but I could confirm that the library was retrying internally as opposed to returning errors, so I'm not quite sure what was changed.

I then came across the [backoff package](https://pkg.go.dev/google.golang.org/grpc/backoff) and [connection backoff protocol](https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md). Given my server was down altogether, this seemed promising and that it was more of a connection backoff that I wanted. After configuring this with ConnectParams when dialing, it didn't seem as though this was doing anything, as (while my server was down) dialing was continuing to return errors and didn't seem to be attempting to retry at all.

I should mention that, due to my server being down as I test, the error I receive is a "connection refused" error, and I recall reading somewhere that only temporary connection issues qualify for retry. Is that accurate?

So, to summarize my questions:
- If configuring retries via service config, do the RetryableStatusCodes fields need to be returned via server rather than client / library? i.e. is an UNAVAILABLE error due to "connection refused" not applicable?
- If enabling retries via service config retryPolicy, what happens to connection-style errors? It seems those changed when the retryPolicy was enabled.
- How do I opt into the connection backoff protocol? Is it enabled by default? Does enabling the service config retryPolicy enable it?
- Why does the connection backoff protocol not seem to be applying? Is it not relevant for "connection refused" errors?
- Am I chasing a dead end looking for retry logic that covers all connection-style errors? Must this be implemented manually? Is there any recommended best-practice here?

Ultimately, I'm hoping to maintain indefinite server-streams that will reconnect on the client should the server go away for any reason and continue to attempt to reconnect until the server returns.

Thanks!

**Comment by zasweq** [comment]
This is a good outline of https://grpc.io/docs/guides/retry/. As you can see in the configuration, if you want you can add UNAVAILABLE to the list of retryable status codes. Note that these retries are on *a RPC level* and errors, and not connection errors. Connection backoff is unrelated to the retry policy both conceptually and in configuration. This document: https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md shows the connection backoff algorithm. You can configure it with a Dial Option in our repository: https://github.com/grpc/grpc-go/blob/master/dialoptions.go#L253. Does this answer all your questions?

**Comment by justinfx** [comment]
I'm looking for these options as well and it seems like the option is not exported?
https://github.com/grpc/grpc-go/blob/v1.67.0-dev/dialoptions.go#L695
