### ISSUE TITLE
The API Gateway vision

### ISSUE THREAD

**Issue by lhdhtrc** [grpc/grpc-go#7070]
Scenes:
- Unified API service gateway that supports grpc requests and http requests
The functions that have been implemented so far:
- grpc proxy grpc (UnknownServiceHandler)
Current difficulties:
- The http request is forwarded or converted to the grpc service

I do not know how to solve this problem, the gateway layer is actually not concerned about the pb file, but I can not achieve http conversion grpc service, ask the community whether there is a solution, thank you!

**Comment by arvindbr8** [comment]
Unfortunately, we do not have an out of the box solution/example that might help you here. I would keep the issue open here to see if someone in the community might be able to help here.

**Comment by lhdhtrc** [comment]
@arvindbr8 thanks

**Comment by arvindbr8** [comment]
@lhdhtrc -- One second thought, this question would have a better reach if you post it to the larger community via https://grpc.io/community/#join-the-conversation. The reach for the gRPC-go issue list would be limited to the maintainers and the few people actively engaged. 

Might be worth reposting some of this content to one of the other media
