### ISSUE TITLE
Is dynamic routing currently supported in grpc-go or how can i achieve it？

### ISSUE THREAD

**Issue by EndlessSeeker** [grpc/grpc-go#7077]
I would like to ask, is the dynamic routing function for a request currently supported?
For example, I specified that the target service is a in the client dial, but I hope that during actual request, the client can dynamically call the service b, c or even specific ip:port of service a according to some rules. I hope that users of the framework will be unaware of this logic.
How can I implement the above function? At present, I think it may be possible to achieve it by customizing a Resolver. Is this feasible? Or is there a more recommended way?

**Comment by arvindbr8** [comment]
The best way to go about this would be to use xDS and a management server that has the configuration as per the "rules". You could also achieve this using a Custom Resolver - but it would be static and a client upgrade would be in order to change the routing logic. Using a xDS management server gives you the dynamic Out of Band routing you might be looking for. 

See: https://github.com/grpc/grpc-go/tree/master/examples/features/xds

**Comment by EndlessSeeker** [comment]
Thanks for your suggestion! 
Follow your suggestions, I deployed a grpc server and istio in k8s, and a grpc client will access the grpc server in my mac. However, I found that the client seemed to have an exception in parsing lds (guessed from the printed log). 
The grpc-go version is 1.62.x, and the istio version is 1.20.3. I would like to ask if we have any restrictions on the istio version?

`
[Transport.sendAggregatedDiscoveryServiceRequest] req: resource_names:"114.55.2.69:80"  type_url:"type.googleapis.com/envoy.config.listener.v3.Listener"  response_nonce:"058bfd7a-75eb-4968-88e8-9e09ef131a97"  error_detail:{code:3  message:"error parsing \"ListenerResource\" response: resource \"10.0.245.146_443\": network filters {[name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"} name:\"envoy.filters.network.tcp_proxy\"  typed_config:{type_url:\"type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy\"  value:\"\\n3outbound|443||istiod.istio-system.svc.cluster.local\\x123outbound|443||istiod.istio-system.svc.cluster.local\"}]} has unsupported network filter \"type.googleapis.com/stats.PluginConfig\" in filter {name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"}};\nresource \"192.168.41.1_10250\": network filters {[name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"} name:\"envoy.filters.network.tcp_proxy\"  typed_config:{type_url:\"type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy\"  value:\"\\n5outbound|10250||kubelet.kube-system.svc.cluster.local\\x125outbound|10250||kubelet.kube-system.svc.cluster.local\"}]} has unsupported network filter \"type.googleapis.com/stats.PluginConfig\" in filter {name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"}};\nresource \"10.0.220.75_8848\": unsupported field 'listener_filters' contains 2 entries;\nresource \"virtualOutbound\": unsupported field 'use_original_dst' is present and set to true;\nresource \"10.0.112.177_15021\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.0.10_53\": network filters {[name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"} name:\"envoy.filters.network.tcp_proxy\"  typed_config:{type_url:\"type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy\"  value:\"\\n3outbound|53||kube-dns.kube-system.svc.cluster.local\\x123outbound|53||kube-dns.kube-system.svc.cluster.local\"}]} has unsupported network filter \"type.googleapis.com/stats.PluginConfig\" in filter {name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"}};\nresource \"0.0.0.0_15010\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.211.31_80\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.245.146_15012\": network filters {[name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"} name:\"envoy.filters.network.tcp_proxy\"  typed_config:{type_url:\"type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy\"  value:\"\\n5outbound|15012||istiod.istio-system.svc.cluster.local\\x125outbound|15012||istiod.istio-system.svc.cluster.local\"}]} has unsupported network filter \"type.googleapis.com/stats.PluginConfig\" in filter {name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"}};\nresource \"0.0.0.0_15014\": unsupported field 'listener_filters' contains 2 entries;\nresource \"virtualInbound\": unsupported field 'listener_filters' contains 3 entries;\nresource \"10.0.194.156_20003\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.112.177_443\": network filters {[name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"} name:\"envoy.filters.network.tcp_proxy\"  typed_config:{type_url:\"type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy\"  value:\"\\nAoutbound|443||istio-ingressgateway.istio-system.svc.cluster.local\\x12Aoutbound|443||istio-ingressgateway.istio-system.svc.cluster.local\"}]} has unsupported network filter \"type.googleapis.com/stats.PluginConfig\" in filter {name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"}};\nresource \"10.0.208.25_20001\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.1.252_80\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.159.201_80\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.0.10_9153\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.239.31_20002\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.172.54_3306\": network filters {[name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"} name:\"envoy.filters.network.tcp_proxy\"  typed_config:{type_url:\"type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy\"  value:\"\\n4outbound|3306||demo-mysql.mse-demo.svc.cluster.local\\x124outbound|3306||demo-mysql.mse-demo.svc.cluster.local\"}]} has unsupported network filter \"type.googleapis.com/stats.PluginConfig\" in filter {name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"}};\nresource \"0.0.0.0_80\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.0.1_443\": network filters {[name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"} name:\"envoy.filters.network.tcp_proxy\"  typed_config:{type_url:\"type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy\"  value:\"\\n2outbound|443||kubernetes.default.svc.cluster.local\\x122outbound|443||kubernetes.default.svc.cluster.local\"}]} has unsupported network filter \"type.googleapis.com/stats.PluginConfig\" in filter {name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"}};\nresource \"10.0.130.20_443\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.220.75_9848\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.145.146_80\": unsupported field 'listener_filters' contains 2 entries"}[clientStream.SendMsg] msg: resource_names:"114.55.2.69:80"  type_url:"type.googleapis.com/envoy.config.listener.v3.Listener"  response_nonce:"058bfd7a-75eb-4968-88e8-9e09ef131a97"  error_detail:{code:3  message:"error parsing \"ListenerResource\" response: resource \"10.0.245.146_443\": network filters {[name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"} name:\"envoy.filters.network.tcp_proxy\"  typed_config:{type_url:\"type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy\"  value:\"\\n3outbound|443||istiod.istio-system.svc.cluster.local\\x123outbound|443||istiod.istio-system.svc.cluster.local\"}]} has unsupported network filter \"type.googleapis.com/stats.PluginConfig\" in filter {name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"}};\nresource \"192.168.41.1_10250\": network filters {[name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"} name:\"envoy.filters.network.tcp_proxy\"  typed_config:{type_url:\"type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy\"  value:\"\\n5outbound|10250||kubelet.kube-system.svc.cluster.local\\x125outbound|10250||kubelet.kube-system.svc.cluster.local\"}]} has unsupported network filter \"type.googleapis.com/stats.PluginConfig\" in filter {name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"}};\nresource \"10.0.220.75_8848\": unsupported field 'listener_filters' contains 2 entries;\nresource \"virtualOutbound\": unsupported field 'use_original_dst' is present and set to true;\nresource \"10.0.112.177_15021\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.0.10_53\": network filters {[name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"} name:\"envoy.filters.network.tcp_proxy\"  typed_config:{type_url:\"type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy\"  value:\"\\n3outbound|53||kube-dns.kube-system.svc.cluster.local\\x123outbound|53||kube-dns.kube-system.svc.cluster.local\"}]} has unsupported network filter \"type.googleapis.com/stats.PluginConfig\" in filter {name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"}};\nresource \"0.0.0.0_15010\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.211.31_80\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.245.146_15012\": network filters {[name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"} name:\"envoy.filters.network.tcp_proxy\"  typed_config:{type_url:\"type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy\"  value:\"\\n5outbound|15012||istiod.istio-system.svc.cluster.local\\x125outbound|15012||istiod.istio-system.svc.cluster.local\"}]} has unsupported network filter \"type.googleapis.com/stats.PluginConfig\" in filter {name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"}};\nresource \"0.0.0.0_15014\": unsupported field 'listener_filters' contains 2 entries;\nresource \"virtualInbound\": unsupported field 'listener_filters' contains 3 entries;\nresource \"10.0.194.156_20003\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.112.177_443\": network filters {[name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"} name:\"envoy.filters.network.tcp_proxy\"  typed_config:{type_url:\"type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy\"  value:\"\\nAoutbound|443||istio-ingressgateway.istio-system.svc.cluster.local\\x12Aoutbound|443||istio-ingressgateway.istio-system.svc.cluster.local\"}]} has unsupported network filter \"type.googleapis.com/stats.PluginConfig\" in filter {name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"}};\nresource \"10.0.208.25_20001\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.1.252_80\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.159.201_80\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.0.10_9153\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.239.31_20002\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.172.54_3306\": network filters {[name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"} name:\"envoy.filters.network.tcp_proxy\"  typed_config:{type_url:\"type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy\"  value:\"\\n4outbound|3306||demo-mysql.mse-demo.svc.cluster.local\\x124outbound|3306||demo-mysql.mse-demo.svc.cluster.local\"}]} has unsupported network filter \"type.googleapis.com/stats.PluginConfig\" in filter {name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"}};\nresource \"0.0.0.0_80\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.0.1_443\": network filters {[name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"} name:\"envoy.filters.network.tcp_proxy\"  typed_config:{type_url:\"type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy\"  value:\"\\n2outbound|443||kubernetes.default.svc.cluster.local\\x122outbound|443||kubernetes.default.svc.cluster.local\"}]} has unsupported network filter \"type.googleapis.com/stats.PluginConfig\" in filter {name:\"istio.stats\"  typed_config:{type_url:\"type.googleapis.com/stats.PluginConfig\"}};\nresource \"10.0.130.20_443\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.220.75_9848\": unsupported field 'listener_filters' contains 2 entries;\nresource \"10.0.145.146_80\": unsupported field 'listener_filters' contains 2 entries"}
`

**Comment by EndlessSeeker** [comment]
I found that this code caused that the lds data returned by istio can not be parsed. May I ask why it is designed like this? Is it necessary to optimize here, because it is normal for lds to carry listener filter info now?
path: xds/internal/xdsclient/xdsresource/unmarshal_lds.go::processServerSideListener
`
func processServerSideListener(lis *v3listenerpb.Listener) (*ListenerUpdate, error) {
	**if n := len(lis.ListenerFilters); n != 0 {
		return nil, fmt.Errorf("unsupported field 'listener_filters' contains %d entries", n)
	}**
        ……
`

**Comment by EndlessSeeker** [comment]
I tried many ways, even modified the code, but still couldn't get through the xds client. Regarding the sample given, is there a bootstrap.json file that can be used for my reference?

**Comment by arvindbr8** [comment]
@EndlessSeeker - 

From the logs, the code path that was likely invoked if you are using a xDS enabled gRPC server. And based on your initial question I dont think this is what you need. You would need the client to be using xDS. 

Also regarding [this](https://github.com/grpc/grpc-go/issues/7077#issuecomment-2041940624), that particular scenario is called out in in gRFC A36 - xDS for servers, and talks about NACKing when listener filters are present. See: https://github.com/grpc/proposal/blob/ea5552587c5b93e978c4bcb695e2210ff97ccbf8/A36-xds-for-servers.md?plain=1#L160

**Comment by EndlessSeeker** [comment]
yes, i need use xDS in client scenarios. Maybe I'm using it incorrectly, but I didn't find the correct way to use it...It would be nice if the xds example has the instruction about bootstrap file. I guess my bootstrap is not written correctly.
