### ISSUE TITLE
Confusing for NewClient in 1.63

### ISSUE THREAD

**Issue by SamYuan1990** [grpc/grpc-go#7093]
Please see the FAQ in our main README.md before submitting your issue.

NewClient 

https://github.com/grpc/grpc-go/blob/c31cec33dd5d1b524a010acbef9d6932dfc791dc/clientconn.go#L124

but

https://github.com/grpc/grpc-go/blob/c31cec33dd5d1b524a010acbef9d6932dfc791dc/dialoptions.go#L392

```
// WithTimeout returns a DialOption that configures a timeout for dialing a
// ClientConn initially. This is valid if and only if WithBlock() is present.
//
// Deprecated: use DialContext instead of Dial and context.WithTimeout
// instead.  Will be supported throughout 1.x.
```

hence, which means in 1.63 we Deprecated timeout support?

as I found this issue by lint https://github.com/Hyperledger-TWGC/tape/pull/384 

if I change to the NewClient following unit test case https://github.com/grpc/grpc-go/blob/c31cec33dd5d1b524a010acbef9d6932dfc791dc/clientconn_test.go#L390 I will use another Deprecated function as WithTimeout?

Any suggestion?

**Comment by SamYuan1990** [comment]
Further more, https://github.com/grpc/grpc-go/blob/c31cec33dd5d1b524a010acbef9d6932dfc791dc/clientconn.go#L126-L290

as NewClient is going to replace DialContext,
the DialContext invokes Newclient and handle timeout out of NewClient... but from the code comments, it seems NewClient should handle timeout. But in fact it just handle `idleTimeout`?

**Comment by dfawley** [comment]
Setting a timeout when creating a client is an anti-pattern, and is not possible in any other gRPC implementations.

See https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md#dialing-in-grpc for more info.

> from the code comments, it seems NewClient should handle timeout

From which comments specifically?  I'd like to cleanup the documentation as much as possible, so please let me know any places where you think it could be improved.

**Comment by SamYuan1990** [comment]
> Setting a timeout when creating a client is an anti-pattern, and is not possible in any other gRPC implementations.
> 
> See https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md#dialing-in-grpc for more info.
> 
> > from the code comments, it seems NewClient should handle timeout
> 
> From which comments specifically? I'd like to cleanup the documentation as much as possible, so please let me know any places where you think it could be improved.

@dfawley , I suppose you are not get my point. I am not query on anti-pattern, or say if we apply the lint checking to current code. I am not sure if anti-pattern still works as for example WithTimeout is marked as Deprecated and the impl https://github.com/grpc/grpc-go/blob/master/clientconn.go#L244-L262 for timeout feature seems not anti-pattern ?

here are my steps, please go through them:
1. the lint reports https://github.com/grpc/grpc-go/blob/master/clientconn.go#L200C4-L200C14 as Deprecated hence I go to NewClient https://github.com/grpc/grpc-go/blob/master/clientconn.go#L126 as here.
2. at the NewClient, where https://github.com/grpc/grpc-go/blob/master/clientconn.go#L124-L125 seems I can use `WithTimeout`
3. but ... https://github.com/grpc/grpc-go/blob/c31cec33dd5d1b524a010acbef9d6932dfc791dc/dialoptions.go#L390 WithTimeout is another Deprecated code

so...
if I follow the NewClient hint, I will use WithTimeout as a Deprecated function then the lint fails again.
or
back to the 1st as following here https://github.com/grpc/grpc-go/blob/master/clientconn.go#L215 try to just use NewClient instead of DialContext which I found the timeout handle at https://github.com/grpc/grpc-go/blob/master/clientconn.go#L244-L262 which means the NewClient does not equals with DialContext and I can't replace it.
As the NewClient at https://github.com/grpc/grpc-go/blob/master/clientconn.go#L194 seems just handle cc.dopts.idleTimeout but not cc.dopts.Timeout, does it supports timeout ? if yes, why https://github.com/grpc/grpc-go/blob/master/clientconn.go#L244-L262 impls timeout by itself?

step further to learn from test case, https://github.com/grpc/grpc-go/blob/master/clientconn_test.go#L390 as https://github.com/grpc/grpc-go/blob/master/clientconn_test.go#L392 the WithTimeout is marked with Deprecated, the lint will fail, which not helpful.

**Comment by dfawley** [comment]
> at the NewClient, where [master/clientconn.go#L124-L125](https://github.com/grpc/grpc-go/blob/master/clientconn.go?rgh-link-date=2024-04-04T15%3A48%3A39Z#L124-L125) seems I can use `WithTimeout`

I'm not sure why you think it says you _can_ use `WithTimeout`.  It explicitly says the opposite exactly where you quoted it:

> The DialOptions returned by WithBlock, **WithTimeout**, and WithReturnConnectionError are **ignored by this function**.

Feel free to make your linter ignore these deprecated functions.  We will not be removing them.

But your best bet is to read and follow https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md#dialing-in-grpc and stop using both `Dial` and `WithTimeout`.  It will give you more consistent behavior with other languages and ensure you have proper error handling around where RPCs are occurring.

If you have specific parts of the documentation that you can point to that need to be updated, I'd appreciate it.  We can cover that in #7068.
