### ISSUE TITLE
Deprecate WithBlock and WithReturnConnectionError

### ISSUE THREAD

**Issue by pellared** [grpc/grpc-go#7095]
### Use case(s) - what problem will this feature solve?

https://github.com/grpc/grpc-go/pull/7029 has deprecated `Dial` and `DialContext`. 
`NewClient` ignores `WithBlock`, `WithTimeout`, `WithReturnConnectionError`.

`grpc.WithTimeout` is already deprecated.

`WithBlock` and `WithReturnConnectionError` have a GoDoc comment which discourages its usage.

### Proposed Solution

Deprecate `WithBlock` and `WithReturnConnectionError` so to better notify that these options should not be used and additionally that they are ignored by `NewClient`.

Deprecation is more visible in https://pkg.go.dev/google.golang.org/grpc and more usable for static analysis tools such as `golangci-lint`.

**Comment by dfawley** [comment]
Thank you for creating this issue.  I had not realized these functions were not already tagged as "deprecated" properly.  Let's do that.

**Comment by pellared** [comment]
@dfawley I think that `FailOnNonTempDialError` can also be deprecated. Can you please double-check that?

**Comment by dfawley** [comment]
> @dfawley I think that FailOnNonTempDialError can also be deprecated. Can you please double-check that?

Yes, that sounds right to me, thanks!
