### ISSUE TITLE
gRPC casing looks really ugly [Serious]

### ISSUE THREAD

**Issue by gilperopiola** [grpc/grpc-go#7100]
I know it's a trivial thing, but it just really bugs me when writing the words gRPC and HTTP many times on a project.

Imagine if it was hTTP and not HTTP. It would be madness.

GRPC maybe? 🦔

**Comment by dfawley** [comment]
You are free to write it however you wish.  However, this is the official name of the project, and we don't have the power to change that in this repo, sorry.

**Comment by ejona86** [comment]
FWIW, if you used "GRPC" or "grpc" you [wouldn't](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) [be](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md) [alone](https://github.com/grpc/grpc/blob/master/examples/python/xds/client.py#L14). Even [the old logo used GRPC](https://developers.googleblog.com/2015/10/grpc-releases-beta-opening-door-for-use.html), yet we still wrote gRPC in the text. In code there's plenty of GRPC or grpc for various constants and strings. It's not a big deal.

But GrPc would be madness!
