### ISSUE TITLE
In picker logic(picker_wrapper.go), clearly understand the real reason for failures after a context.Error(timeout)

### ISSUE THREAD

**Issue by holdno** [grpc/grpc-go#7135]
https://github.com/grpc/grpc-go/blob/a2f8e612d700df49e6b88ec47cbcf8bbd6076149/picker_wrapper.go#L153  

Should we consider setting the error content for lastPickErr so that clients can clearly understand the real reason for failures after a timeout? This might improve troubleshooting and user experience.

``` go
if err == balancer.ErrNoSubConnAvailable {
    lastPickErr = err
    continue
}
```

**Comment by aranjans** [comment]
Hi @holdno, can you please share your findings on running your code?
