### ISSUE TITLE
rpc error: code = Internal desc = header key "myheader" contains value with non-printable ASCII characters

### ISSUE THREAD

**Issue by ErshovYS** [grpc/grpc-go#7136]
### What version of gRPC are you using?
gRPC version v1.63.2

### What version of Go are you using (`go version`)?
Go version 1.22.0

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
When I send in metadata cyrillic value (not key), I have error from the title
For example:
`ctx = metadata.AppendToOutgoingContext(ctx, "myheader", "ЖОПА")`

### What did you expect to see?
I expect to see new header in my grpc request

### What did you see instead?
I see error
`rpc error: code = Internal desc = header key "myheader" contains value with non-printable ASCII characters`

**Comment by aranjans** [comment]
@ErshovYS Thanks for writing in. gRPC protocol has restrictions on allowable characters in headers(as per grpc spec [here](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)). The value "ЖОПА" contains Cyrillic characters that fall outside the printable ASCII range. One way could be to encode such values and send that as part of metadata from client side but make sure to handle it on server side as well, or use a -bin header.
