### ISSUE TITLE
TransportAuthenticator.Dial is ignored, net.Dial("tcp", addr) is always called

### ISSUE THREAD

**Issue by tv42** [grpc/grpc-go#72]
https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L106-L119

**Comment by tv42** [comment]
Sorry, I submitted the form too early. Still diagnosing, this might be user error. Will report back soon.

**Comment by iamqizhao** [comment]
No, it is called in https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L113 when some TransportAuthenticator is set in authOpts.

**Comment by iamqizhao** [comment]
Close now. Please reopen if you still think there is a problem here. Thanks.

**Comment by tv42** [comment]
Okay here's the better diagnosis: the client lib assumes addresses always have a port. It calls net.SplitHostPort and fails unless the address was host:port style. There's several calls, removing the error path from this makes the greeter example work over unix domain sockets, with a custom Dial:
https://github.com/grpc/grpc-go/blob/master/call.go#L118

**Comment by tv42** [comment]
Oh, and I can't re-open this issue.

**Comment by iamqizhao** [comment]
On Thu, Feb 26, 2015 at 2:22 PM, Tv <notifications@github.com> wrote:

> Okay here's the better diagnosis: the client lib assumes addresses always
> have a port. It calls net.SplitHostPort and fails unless the address was
>
Right now the client lib does not assume addresses always have a port. It
REQUIRES!

> host:port style. There's several calls, removing the error path from this
> makes the greeter example work over unix domain sockets, with a custom Dial:
> https://github.com/grpc/grpc-go/blob/master/call.go#L118
>
Unix domain socket is not supported now. And I plan to add it in the next a
couple of weeks.

**Comment by iamqizhao** [comment]
make #73 to track UDS separately.
