### ISSUE TITLE
cds: update picker synchronously upon receipt of configuration update

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#7211]
https://github.com/grpc/grpc-go/issues/5469 recommends an audit of existing LB policies to ensure that they update their pickers synchronously upon receipt of a configuration update.

`cds_experimental` does not update its picker synchronously.

- Configuration updates are handled here: https://github.com/grpc/grpc-go/blob/b4f7947184ed45e72283a37aeaf214e38c35bc63/xds/internal/balancer/cdsbalancer/cdsbalancer.go#L281
- In the above function, the LB policy
  - initially checks for some error conditions
  - returns early if the cluster name in the configuration has not changed (the cluster name is the only field in its configuration currently)
  - if the cluster name has changed
    - schedules a serializer callback in a blocking fashion to create a new watcher for the cluster name: https://github.com/grpc/grpc-go/blob/b4f7947184ed45e72283a37aeaf214e38c35bc63/xds/internal/balancer/cdsbalancer/cdsbalancer.go#L313
      - if the new cluster turns out to be an aggregate cluster, more watches will be registered
- Anyways, at the end of the `UpdateClientConnState` , it does not return a picker inline
  - It does not even push the child policy configuration inline, because that has to wait for the cluster graph to be resolved completely

This needs fixing in at least a few places, and we need answers for these:
- Should the cds LB policy return a picker at build time? It currently does not.
- Should the cds LB policy return an erroring picker when cluster graph resolution is incomplete? It currently does not.

**Comment by aranjans** [comment]
@arjan-bal yes, this is completed and can be closed.
