### ISSUE TITLE
<invalid gRPC request method "PRI">, when happend grpc and http use sample port

### ISSUE THREAD

**Issue by PaiHL** [grpc/grpc-go#7254]
### What version of gRPC are you using?

grpc v1.64.0 

### What version of Go are you using (`go version`)?

go version go1.20.14 windows/amd64

### What operating system (Linux, Windows, …) and version?

Windows 11

### What did you do?

server code
```go
func (s *Server) Serve() {
	pb.RegisterCloudPluginServer(s.server, s.srv)
	server := &http.Server{
		Addr: fmt.Sprintf("%s:%d", host, setting.Port),
		Handler: http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
			if requestIsGrpc(request) {
				s.server.ServeHTTP(writer, request)
			} else {
				s.mux.ServeHTTP(writer, request)
			}
			return
		}),
	}
	if err := server.ListenAndServe(); err != nil {
		panic(err)
	}
	if err := s.server.Serve(lis); err != nil {
		logger.Panicf("failed to serve: %v", err)
		panic(err)
	}
}

func requestIsGrpc(request *http.Request) bool {
	if request.ProtoMajor != 2 {
		return false
	}
	if len(request.Header) == 0 || strings.Contains(request.Header.Get("Content-Type"), "application/grpc") {
		return true
	}
	return false
}
```

use postman send grpc request

### What did you expect to see?

Process grpc requests as normal as you would with grpcServer.Serve

### What did you see instead?

One was returned while processing the request  <invalid gRPC request method "PRI">

Locate this row ~/go/pkg/mod/google.golang.org/grpc@v1.64.0/server.go:1074

**Comment by PaiGack** [comment]
这里可以使用 x/net 中的 h2c 替代
