### ISSUE TITLE
When the client receives the "too many pings" error log, how to get the server's target or remoteIP information?

### ISSUE THREAD

**Issue by win5do** [grpc/grpc-go#7265]
`google.golang.org/grpc v1.59.0`

```log
2024/05/22 21:03:45 ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".
```

Is it possible to add this information to the log?
Or provide some user-injectable hook API to trace conn close.

I need to find the corresponding server and then adjust the keepalive configuration.

**Comment by purnesh42H** [comment]
@win5do I am looking into it and will update you with more information

**Comment by purnesh42H** [comment]
@win5do We are working getting an official fix merged and released which aims to get the logging better with remote addr for the whole of the transport package. Meanwhile you can make a local change to unblock yourself. Feel free to use/refer to my fork #7285 where the fix has been made.

**Comment by purnesh42H** [comment]
I am marking this issue closed for now as

**Comment by win5do** [comment]
@purnesh42H   The PR was closed and no other PR solved this issue. Should we reopen this issue?

**Comment by purnesh42H** [comment]
@win5do there is a bigger fix in progress to improve transport logs which will cover this. @arvindbr8 fyi
