### ISSUE TITLE
GitHub Action: branch protection checks are skipped, and also not blocking merges

### ISSUE THREAD

**Issue by arvindbr8** [grpc/grpc-go#7287]
This issue to investigate why the 1.22, 386 Tests have been skipped in the recent runs 
- https://github.com/grpc/grpc-go/actions/runs/9295249502
- https://github.com/grpc/grpc-go/actions/runs/9291288759

[This](https://github.com/grpc/grpc-go/actions/runs/9295249502/job/25581866622) run is the first time (that I saw) where there was an log message. Maybe from the other runs we just need to dip deeper to find the logs for the run. I suspect this is a timeout issue. 

I am considering to bump up the timeout specified here: https://github.com/grpc/grpc-go/blob/master/.github/workflows/testing.yml#L38

**Comment by arvindbr8** [comment]
Seeing this in for checks now: [Testing / tests (tests, 1.21) (pull_request) Skipped](https://github.com/grpc/grpc-go/actions/runs/9297417578/job/25587538385?pr=7262)

GitHub is weeeirrrrd 👎 

Modifying the title to talk more about GitHub actions being skipped, and when skipped not blocking merge.

**Comment by arvindbr8** [comment]
Additional findings by @dfawley :
-  https://github.com/actions/setup-go/issues/427#issuecomment-1946115668
-  https://github.com/orgs/community/discussions/126539
 ---- 
Seems like runs have been okay since yday? https://github.com/grpc/grpc-go/issues/7287

**Comment by dfawley** [comment]
This issue seems resolved but it might be nice to follow-up on the [above comment](https://github.com/actions/setup-go/issues/427#issuecomment-1946115668) to remove the spammy warning and maybe(?) improve performance.
