### ISSUE TITLE
HTTP2 Server fails on WindowUpdateFrame in place of SettingsFrame

### ISSUE THREAD

**Issue by sarietta** [grpc/grpc-go#729]
Relevant line: https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L235

I'm not an HTTP2 expert, but we have noticed non-go clients (e.g. `nodejs`, `c++`) tend to avoid sending a `SettingsFrame` every time. I believe that this is due to the following check in the grpc client portion of the C library: https://github.com/grpc/grpc/blob/7bfa751404a0f9b1581df96b714df227aa48fcf4/src/core/ext/transport/chttp2/transport/writing.c#L63

In our local copy we are treating the lack of a `SettingsFrame` as simply not an error and continue to the process the frames, with no obvious issues.

I would be happy to submit a PR with our fix to this issue, but wanted to ensure that we are interpreting the HTTP2 spec correctly and that removing the condition that there is always a `SettingsFrame` doesn't cause any unforeseen issues.

**Comment by iamqizhao** [comment]
quoted from http2 spec:

"The server connection preface consists of a potentially empty SETTINGS frame (Section 6.5) that 
**MUST** be the first frame the server sends in the HTTP/2 connection."

**Comment by sarietta** [comment]
Fair enough. This must be an issue with the C library in that case, because our client repeatedly fails to issue gRPCs to a `go` server with the error:

```
transport: http2Server.HandleStreams saw invalid preface type *http2.WindowUpdateFrame from client
```

Is it possible that an empty `SettingsFrame` is causing the issue? 

I will also make an issue on the C library for grpc to see what that side of equation has to say about it.

**Comment by iamqizhao** [comment]
I wanted to quote the following instead :)

"The client connection preface starts with a sequence of 24 octets, which in hex notation is:

0x505249202a20485454502f322e300d0a0d0a534d0d0a0d0a
That is, the connection preface starts with the string PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n). This sequence **MUST** be followed by a SETTINGS frame (Section 6.5), which MAY be empty. "

**Comment by iamqizhao** [comment]
According to the error you saw, it seems the client sends WindowUpdateFrame before the Preface. My speculation is that they still send Preface every time but due to some race, the preface may arrive after WindowUpdateFrame.

**Comment by adityadani** [comment]
Hello,

I am also seeing the same error. I am trying to run the helloworld example where the server is running in go and client is in cpp. I am pretty new to grpc and protobufs. 

Is this a version mismatch between go and cpp grpc/protobuf? Or is there a workaround for this issue?

**Comment by promiseofcake** [comment]
Seeing issues with this from requests coming from PHP clients as well on `0.15.0`. @sarietta, what grpc version/hash were your non-go clients pinned to at the time?

**Comment by phbcanada** [comment]
We are running into this problem with clients using 0.14.0. Does this still occur with the 1.0.0 release?

**Comment by hsaliak** [comment]
@sarietta are you still seeing this issue?
