### ISSUE TITLE
Upgrade to using math/rand/v2 to get perf enhancements 

### ISSUE THREAD

**Issue by arvindbr8** [grpc/grpc-go#7293]
Follow up from: https://github.com/grpc/grpc-go/pull/7283#issuecomment-2142662503

Go1.22 introduced a new rand package with a lot of improvements. See: [go.dev/blog/randv2](https://go.dev/blog/randv2). 

We would love to update our usages of math/rand once gRPC-go requires Go 1.22 or later.

**Comment by silaselisha** [comment]
@arvindbr8 I would like to be assigned this task.

**Comment by purnesh42H** [comment]
@silaselisha assigned it to you

**Comment by easwars** [comment]
This is blocked until we bump the minimum Go version supported to `1.22` in our go.mod.

**Comment by marcoferrer** [comment]
Is switching to randv2 still blocked?

**Comment by easwars** [comment]
I see that we bumped up our minimum supported Go version to `1.22.7` in https://github.com/grpc/grpc-go/pull/7624. So, this should be unblocked.

@marcoferrer : Would you be interested in making this change? We'll be happy to review. Thanks.

**Comment by marcoferrer** [comment]
@easwars Sounds good. PR opened.
