### ISSUE TITLE
Experimental API related to metadata

### ISSUE THREAD

**Issue by KarthikReddyPuli** [grpc/grpc-go#7298]
I would like to fetch metadata in a more efficient manner and I found an API that is experimental but the PR was ~2 years ago. Can I consider this safe to use now ? Is there any plan on removing the experimental tag on this API and make it permanent ?

PR for reference: https://github.com/grpc/grpc-go/pull/5596

**Comment by arjan-bal** [comment]
Hi @KarthikReddyPuli, we would like to get feedback before stabilising an experimental API. This helps avoid the risk of needing breaking changes after stabilisation. If users are happy with an experimental API and request it's stabilisation, we will stabilise it.

You can use the [ViewFromIncomingContext](https://github.com/grpc/grpc-go/blob/6d236200ea68ea644d78a164c4ad9952a765aed3/metadata/metadata.go#L228-L254) function and share feedback, if any. The gRPC project still reserves the right to make breaking changes to it, however we don't have any changes planned currently, and don't foresee any in the near future

**Comment by KarthikReddyPuli** [comment]
Hi @arjan-bal, thanks for the reply. We have started using this API and we have found considerable improvements in our profiler. I request to stabilise this API in any of the upcoming releases

**Comment by arjan-bal** [comment]
Good to know that the API works well.

Assigning to @dfawley to comment on stabilisation of the API.

**Comment by dfawley** [comment]
I don't have any objections.

**Comment by KarthikReddyPuli** [comment]
@arjan-bal I have raised a PR to stabilise this API, can you please help in review/merging it ?
https://github.com/grpc/grpc-go/pull/7368
