### ISSUE TITLE
Support Unix domain socket

### ISSUE THREAD

**Issue by iamqizhao** [grpc/grpc-go#73]

**Comment by tv42** [comment]
All I have to do to make it work is put a dummy ":kludge" suffix on the address, and strip it out in my TransportAuthenticator.Dial. But that really shouldn't be necessary ;)

**Comment by iamqizhao** [comment]
This is not sufficient because it does not work in the case when there is no TransportAuthenticator (i.e., plain TCP). Plus, how does the client lib differentiate a malformed host:port address (e.g. a user passed an IP addr and forgot setting the port) and real unix socket domain name if we allow users pass an arbitrary string. My idea is to make things explicit. For example, if users want to use UDS, they need to specify the protocol explicitly when creating the transport. This approach is also scaling when we want to support more transport protocols.

**Comment by tv42** [comment]
Oh, absolutely. I am abusing the TransportAuthenticator point to hook up a custom dialer; proper custom dialer support would definitely be better.

Oh and just to be clear, just passing "network, addr string" to net.Dial would cover the unix domain socket part, but still leave out all the things that are truly custom transports, e.g. reliable stream transports over UDP.

**Comment by iamqizhao** [comment]
Agree, those kind of transports (e.g., QUIC, RDMA, etc.) need the native support from the underlying library (e.g., Go net package).

**Comment by iamqizhao** [comment]
closed via #169
