### ISSUE TITLE
Authorize single rpc via transport layer

### ISSUE THREAD

**Issue by R-omk** [grpc/grpc-go#731]
How I can authorize a procedure call without Per RPC Credentials?
May I authorize only first call in connection with token (oauth), but next calls in the same connection without the token?

The token may be too large relative to the size of the transmitted data structures, this creates additional overhead over the payload.

**Comment by iamqizhao** [comment]
I think you can implement your custom grpc.PerRPCCredentials which attaches the token to the first call and empty token to the others.

**Comment by R-omk** [comment]
But how to identify during request  that is the same connection?

**Comment by iamqizhao** [comment]
note that grpc.PerRPCCredentials is installed via a DialOption, which means it is per-connection thing and all the invocations of GetRequestMetadata are on the same connection.

**Comment by R-omk** [comment]
But PerRPCCredentials set up http2 header on each request in the same tls connection,  or it is not?

**Comment by iamqizhao** [comment]
Let's first clarify some terms to make our communication better.
i) an RPC may have 1 request and 1 response (unary) or N requests and M responses (streaming);
ii) Per your question, you want oauth token attached on the first RPC on the connection and no token on the following RPCs on the connection? Correct?

**Comment by R-omk** [comment]
Yes, it's correct, I am interested in unary type.
How to distinguish one from the other connection on the server side based on the context in a method or in a grpc.UnaryServerInterceptor

**Comment by R-omk** [comment]
And another question, does client identification with private key?
And how to identify a client that connects to grpcServer with own exclusive private key?

**Comment by R-omk** [comment]
The short answer to my question
```
p: = peer.FromContext(ctx)
//  if p.AuthInfo.AuthType()== "tls"
tls, _ := p.AuthInfo.(credentials.TLSInfo)
uniqConnectionId := tls.State.TLSUnique  // byte array
```
