### ISSUE TITLE
Strongly-type request inside a Stream Server Interceptor

### ISSUE THREAD

**Issue by Galaf** [grpc/grpc-go#7325]
Hello!

I'd like to strongly-type a request coming via a Stream Server interceptor in order to read its fields but I'm not sure how I could convert a `proto.Message` to do so.

I'm looking at doing something that would look like so:

```go
func (w *wrappedStream) RecvMsg(m any) error {
    err := w.ServerStream.RecvMsg(m)
    // inlining to make it easy to understand
    p, ok := m.(userv1.GetUserRequest)
    // err check...

    // I can use the fields from `GetUserRequest` as I see fit.

    return err
}
```

Essentially, I'm trying to do something very similar to `proto.Unmarshal` but I don't think I can get the underlying bytes of the request without reimplementing what `RecvMsg` does and injecting my own functions into it.

Could you tell me what would be the best solution for my use-case, please?

Thank you for your time!

**Comment by purnesh42H** [comment]
@Galaf from the code snippet you provided, the interceptor doesn't look correct. Could you try following the example here https://github.com/grpc/grpc-go/blob/master/examples/features/metadata_interceptor/server/main.go#L98
