### ISSUE TITLE
protoc gen adds comment, does not follow godoc.

### ISSUE THREAD

**Issue by titpetric** [grpc/grpc-go#7350]
For the service interface a comment is added to the generated interface, as seen on https://github.com/grpc/grpc-go/issues/3794

```
// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
```

This appended comment violates godoc as it does not end with punctuation (dot).

Expected:

```
// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility.
```

Is there a way we can:

- turn off this comment (flags?),
- modify this comment on our own (flags?),
- just get the dot added in a future release?

Thank you for understanding :D

**Comment by purnesh42H** [comment]
@titpetric we can fix this by adding punctuation in protoc generation here https://github.com/grpc/grpc-go/blob/master/cmd/protoc-gen-go-grpc/grpc.go#L267 and then regenerate all pb.go files. Do you want to give a try for fix?

**Comment by purnesh42H** [comment]
@titpetric just checking in if you will doing a fix PR for this

**Comment by titpetric** [comment]
@infovivek beat me to it :) 🫡✅

**Comment by arjan-bal** [comment]
Assigning to @purnesh42H since @infovivek2020 isn't showing up as an option to set as the assignee.

**Comment by infovivek2020** [comment]
@purnesh42H I have raised PR https://github.com/grpc/grpc-go/pull/7392 the please review
