### ISSUE TITLE
Setting HTTPS proxy without setting HTTPS_PROXY env variable

### ISSUE THREAD

**Issue by jskiba** [grpc/grpc-go#7358]
https://github.com/grpc/grpc-go/blob/master/Documentation/proxy.md#custom-proxy - this page seems to be out of date since `WithDialer` option is deprecated. Is there any other alternative to this?

**Comment by purnesh42H** [comment]
@jskiba I will take a look and get back to you

**Comment by purnesh42H** [comment]
@jskiba `WithDialer` is deprecated. You can use [WithContextDialer](https://pkg.go.dev/google.golang.org/grpc#WithContextDialer) instead
