### ISSUE TITLE
Allow client-side access to `grpc-status` and `grpc-message`

### ISSUE THREAD

**Issue by koiuo** [grpc/grpc-go#7399]
### Use case(s) - what problem will this feature solve?

In issue #5485, I described a scenario where applications use their own message definitions for the `grpc-status-details-bin` header.

#6662 by @dfawley addresses that by adding the decoded `grpc-status-details-bin` value to the `mdata` map.

https://github.com/grpc/grpc-go/blob/5e0fa765ba0c9c9b6c703dfa56705c3acfa056c3/internal/transport/http2_client.go#L1493-L1504 

If the `grpc-status-details-bin` can not be deserialized by the runtime into the default `Status` message, the runtime returns an error with code `INTERNAL` and human-readable message containing original values for `grpc-status` and `grpc-message` trailers. This allows client to inspect the original value for `grpc-status-details-bin` and modify the response as needed.

This approach works well if all status information is stored in the `grpc-status-details-bin` (i.e. if it contains both the status code and the message).

However, in our company we use `grpc-status-details-bin` as additional optional information:  `grpc-status-details-bin` enhances the status, but does not substitute `grpc-message` and `grpc-status`. With the current grpc-go we have to resort to parsing out original `grpc-status` and `grpc-message` values out from the human-readable message, which is very inconvenient and error-prone.

### Proposed Solution

Expose decoded `grpc-message` and `grpc-status` values to clients, by adding them to the `mdata` map.

**Comment by dfawley** [comment]
> If the grpc-status-details-bin can not be deserialized by the runtime into the default Status message, the runtime returns an error with code INTERNAL and human-readable message containing original values for grpc-status and grpc-message trailers. 

If you are seeing this behavior, then it is a bug.

From #6662, the intended behavior is:

> * If there is 1 value and it deserializes into a google.rpc.Status, ensure the code field matches the grpc-status header's code. If it does not match, convert the code to codes.Internal
> * Otherwise, the status returned to the application will use the grpc-status and grpc-message values only.

Please let me know if that's what you're seeing.

**Comment by koiuo** [comment]
@dfawley 
It's the end of the day, and I apologize if I'm still misreading something after multiple re-reads, but

This

> If there is 1 value and it deserializes into a google.rpc.Status, ensure the code field matches the grpc-status header's code. If it does not match, convert the code to codes.Internal

matches the behavior I'm describing

> If the grpc-status-details-bin can not be deserialized by the runtime into the default Status message, the runtime returns an error with code INTERNAL and human-readable message

To make it more specific, our servers use `grpc-status-details-bin` for passing
```
message Details {
    oneof kind {
        ApplicationError application_error = 1; // further details do not matter
        ValidationError validation_error = 2;
    }
}
```

So whatever server returns, can't be deserialized into `google.rpc.Status`, and thus the behavior is exactly as you intended; my gRPC interceptor sees 
```
spb.Status {
  Code: Code.Internal
  Message: "grpc-status-details-bin mismatch: grpc-status=\"InvalidArgument\", grpc-message=\"<original message>\", grpc-status-details-bin=\"<original details>\","
  Details: []*anypb.Any{} // empty
}
```

In a case like this I want to parse the original `grpc-status-details-bin`, which is possible, thanks to the original trailer value being exposed.

However, `grpc-status` and `grpc-message` are only available through `Status.Message`. And reliably parsing it out is more hassle than it should be.

I hope the example makes it clear.

____

I lack the whole perspective, but I've been wondering, why changing the code to `Internal` at all? Why don't just silently ignore `grpc-status-details-bin` if it can be deserialized?

FWIW, this is the change we've made on our side to accommodate our use case fully
https://github.com/wix-incubator/grpc-go/commit/245e5ce646371da278f1bca3278d9771f963b1af

This code does not override `grpc-status` and `grpc-message`. We expect our message in the `gprc-status-details-bin`, so on the application level we intercept the call and enrich the status object with the missing details if the trailer is present.

I understand the downside of such an approach is an implicit behavior.
On the other hand, for the client to interpret error details returned by the server, it must possess some prior knowledge about the schema. Either the client has prior knowledge and is prepared to handle `grpc-status-details-bin` on their side, or they don't, but then they likely do not care anyway.

**Comment by dfawley** [comment]
> I lack the whole perspective, but I've been wondering, why changing the code to Internal at all? Why don't just silently ignore grpc-status-details-bin if it can't be deserialized?

If the statuses don't match between the two sources, it's a potential security issue, so we convert to INTERNAL.  gRPC-Java will throw an exception if it encounters this scenario when retrieving the `google.rpc.Status` message.

> Why don't just silently ignore grpc-status-details-bin if it can't be deserialized?

We do ignore it if it can't be deserialized.  We only convert to internal if both sources are valid and disagree.

We highly recommend using _only_ `google.rpc.Status` in your `grpc-status-details-bin` headers if you are using protobuf for your messages already, in accordance with https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#appendix-a---grpc-for-protobuf, which says:

> * **Status-Details** → {_google.rpc.Status proto message_}

gRPC-Go makes this very easy to do by using the `status.WithDetails` API.  I know gRPC-Java also has a very friendly API for this.  gRPC-C++ requires some extra manual steps and doesn't do any validation IIRC, but it's also possible.

**Comment by koiuo** [comment]
@dfawley, thank you for the explanation.

From the document you linked:

> Status-Details is allowed only if Status is not OK. If it is set, it contains additional information about the RPC error. If it contains a status code field, it MUST NOT contradict the Status header. The consumer MUST verify this requirement.

In our case, The Status-Details header does NOT *contradict* the Status header. Our status details info does not contain any code at all, which, I suspect, may be interpreted by the current implementation as code 0. And I believe, at that point there may be an inconsistency between Go and Java runtimes.

I intend to research how our status details proto messages is handled by Go and Java runtimes and if indeed there are differences in behavior, me or my colleagues will report here.

**Comment by dfawley** [comment]
> Our status details info does not contain any code at all, which, I suspect, may be interpreted by the current implementation as code 0. 

Yes, the default code is 0 which is OK.  So you aren't setting it, but it is contradictory to leave it unset.

> And I believe, at that point there may be an inconsistency between Go and Java runtimes.
> I intend to research how our status details proto messages is handled by Go and Java runtimes and if indeed there are differences in behavior, me or my colleagues will report here.

cc @ejona86 as FYI.

Please let us know if you see any deviations from the spec from either behavior.  Note that this feature was implemented a long time ago without following the kind of process we follow now for new features, and it was implemented 3 different ways in the 3 different major languages.  We've done the best we can to make them support similar use cases without breaking backward compatibility, but it's impossible to completely unify them.  The best we can promise is that all 3 should adhere to the spec (which is not very specific, unfortunately).
