### ISSUE TITLE
Default fallback scheme changed from `passthrough` to `dns`

### ISSUE THREAD

**Issue by Malhavok** [grpc/grpc-go#7407]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
1.63.2

### What version of Go are you using (`go version`)?
1.21

### What operating system (Linux, Windows, …) and version?
macOS 14.5

### What did you do?
I'm using opentelemetry otlp collector, in version 0.98.0 (1.62.1 of the gRPC library I believe) the gRPC default scheme was `passthrough`, but in 0.99.0 (1.63.2 gRPC) it changed to `dns`.

### What did you expect to see?
[core] [Channel #1]original dial target is: "<redacted, address without a scheme>"   {"grpc_log": true}
[core] [Channel #1]parsed dial target is: resolver.Target{URL:url.URL{Scheme:"<redacted>", Opaque:"<redacted>", User:(*url.Userinfo)(nil), Host:"", Path:"", RawPath:"", OmitHost:false, ForceQuery:false, RawQuery:"", Fragment:"", RawFragment:""}}       {"grpc_log": true}
[core] [Channel #1]fallback to scheme "passthrough"     {"grpc_log": true}
<a bit later>
[core] [Channel #1 SubChannel #2]Subchannel picks a new address "<redacted, matching the original dial target>" to connect    {"grpc_log": true}

### What did you see instead?
[core] [Channel #1]original dial target is: "<redacted, address without a scheme>"   {"grpc_log": true}
[core] [Channel #1]parsed dial target is: resolver.Target{URL:url.URL{Scheme:"<redacted>", Opaque:"<redacted>", User:(*url.Userinfo)(nil), Host:"", Path:"", RawPath:"", OmitHost:false, ForceQuery:false, RawQuery:"", Fragment:"", RawFragment:""}}       {"grpc_log": true}
[core] [Channel #1]fallback to scheme "dns"     {"grpc_log": true}
<a bit later>
[core] [Channel #1 SubChannel #2]Subchannel picks a new address "<redacted, IP instead of an address>" to connect {"grpc_log": true}

The only change I've noticed that could be it was in here:
https://github.com/grpc/grpc-go/commit/7c377708dc070bc6f4dfeedfb3c3f38c3410912b#diff-b3ac34dd7da6ea95744549a03abfa3b6806cb81499f7f70b7b5e957b829f473fR647
Default scheme was changed to a literal "dns" while it should probably be taken from here:
https://github.com/grpc/grpc-go/blob/master/resolver/resolver.go#L40

I might be missing something tho. As a workaround I'm currently setting the default scheme before starting any connections.

**Comment by aranjans** [comment]
@Malhavok Thanks for writing in. There was a recent change in NewClient api post 1.63 version of gRPC release, where NewClient uses dns as default scheme, but on the other hand Dial uses passthrough by default. Do you mind checking if you're using Dial or NewClient to create the client?

**Comment by Malhavok** [comment]
@aranjans Thank you for your response. I've checked the diffs between version 0.98.0 and 0.99.0 of the open telemetry-collector, and that's exactly what happens:

```
-	return grpc.DialContext(ctx, gcs.sanitizedEndpoint(), opts...)
+	return grpc.NewClient(gcs.sanitizedEndpoint(), opts...)
```

Thank you again!
