### ISSUE TITLE
transition from TRANSIENT_FAILURE to IDLE

### ISSUE THREAD

**Issue by rittneje** [grpc/grpc-go#7435]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?

n/a

### What version of Go are you using (`go version`)?

n/a

### What operating system (Linux, Windows, …) and version?

n/a

### What did you do?

Read the code.

### What did you expect to see?

I expect it to abide by the spec at https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md. That currently states that transitioning from TRANSIENT_FAILURE to IDLE is invalid.

### What did you see instead?

This library can transition from TRANSIENT_FAILURE to IDLE.

https://github.com/grpc/grpc-go/blob/0231b0d9429d46c8c5e534450f7dd97a4c53812f/clientconn.go#L1269-L1293

Personally, I think what this library is doing is reasonable, so the resolution of this bug might just be to fix the table.

**Comment by easwars** [comment]
The spec that you linked to talks about channel connectivity state, while the code that you linked to transitions the connectivity state of a subchannel.

While a channel is a virtual connection from the grpc client to the grpc service that it is talking to, and encapsulates a wide array of functionality like name resolution, load balancing etc, a subchannel represents an actual connection to a real backend server. A channel might have multiple subchannels within it, and it is the responsibility of the LB policy to aggregate the connectivity state of these subchannels into a single channel level connectivity state and set it on the channel.

The gRPC client API allows applications to watch the overall connectivity state of the channel. It *does not* allow applications to watch the connectivity state of subchannels.

Thanks for writing to us, and hope this helps.
