### ISSUE TITLE
How can I configure a usable gRPC-Go Retry Policy?

### ISSUE THREAD

**Issue by C4a15Wh** [grpc/grpc-go#7446]
version info:  
```
Golang: 1.20.11
gRPC-Go: v1.65.0
```

I'm using grpc-go in my project as NVIDIA Triton Inference Server client. Recently I discovered that the retry policy I configured may not take affect. When grpc server fails and return INTERNAL error code, grpc-go seems didn't take retry attempts, instead of simply return the errors.

NVIDIA Triton Inference Server protobuf code can be found at: https://github.com/triton-inference-server/common/tree/main/protobuf

My service config is as follow:
```
// just want to make sure if go-grpc will take retry attempts
var serviceConfig = `{
"loadBalancingPolicy": "round_robin",
"methodConfig": [{
	"name": [{"service": "inference.GRPCInferenceServiceClient"}],
	"waitForReady": true,
	"retryPolicy": {
		"MaxAttempts": 100,
		"MaxBackoff": "60s",
		"InitialBackoff": "0.3s",
		"BackoffMultiplier": 1.2,
		"RetryableStatusCodes": [ "UNAVAILABLE", "DEADLINE_EXCEEDED", "INTERNAL" ]
	}
}]}`
```

The expected performance is when I called `ModelInfer` (a method of inference.GRPCInferenceServiceClient, grpc_service.proto) and an INTERNAL error occurs inside grpc server, at this time, client retry until the request successfully returned.

In additional, I configured some environment variables for grpc-go:  
```
GRPC_GO_RETRY=on
GRPC_GO_LOG_VERBOSITY_LEVEL=99
GRPC_GO_LOG_SEVERITY_LEVEL=info
```
when I enable grpc-go logger, I didn't findout any WARNING or INFO log about retry attempts or retry policies...

I just want to make clear what's happened inside grpc-go client? If any configuration is wrong, pls figure out it, thx.

**Comment by purnesh42H** [comment]
@C4a15Wh could you also add the status code returned and error returned from the service?

**Comment by C4a15Wh** [comment]
Sure, the error code is INTERNAL, the detailed error is as follow:  
![image](https://github.com/user-attachments/assets/a063fa84-ef89-43d1-80f5-3e023c28f474)

**Comment by easwars** [comment]
The screenshot is not very readable/usable. Text output would help.

**Comment by easwars** [comment]
Also, `GRPC_GO_RETRY` doesn't seem to be an env var that is supported in grpc-go.

**Comment by dfawley** [comment]
> Also, GRPC_GO_RETRY doesn't seem to be an env var that is supported in grpc-go.

This was added when the feature was still experimental, but removed awhile ago.  If any of our documentation still refers to it, please let us know so we can remove it.

**Comment by C4a15Wh** [comment]
> The screenshot is not very readable/usable. Text output would help.

text output:  
```
rpc error: code = Internal desc = in ensemble 'det_pipeline', Failed to process the request(s) for model instance 'det_preprocess_0_1', message: RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

At:
  /stariver/model_repository/det/det_preprocess/1/model.py(33): _forward_cv2
  /stariver/model_repository/det/det_preprocess/1/model.py(42): forward
  /stariver/model_repository/det/det_preprocess/1/model.py(62): <lambda>
  /stariver/miniconda/envs/pt/lib/python3.10/site-packages/torch/nn/modules/module.py(1541): _call_impl
  /stariver/miniconda/envs/pt/lib/python3.10/site-packages/torch/nn/modules/module.py(1532): _wrapped_call_impl
  /opt/tritonserver/backends/pytorch/model.py(285): execute
```

**Comment by C4a15Wh** [comment]
> > Also, GRPC_GO_RETRY doesn't seem to be an env var that is supported in grpc-go.
> 
> This was added when the feature was still experimental, but removed awhile ago. If any of our documentation still refers to it, please let us know so we can remove it.

I got know this variable from a legacy personal blogs, seems GO_GRPC_RETRY is deprecated? I will no longer use it.

**Comment by dfawley** [comment]
We will need full client logs to help debug retry issues.  https://github.com/grpc/grpc-go#how-to-turn-on-logging
