### ISSUE TITLE
failed to install protoc-gen-go-grpc@v1.5.0

### ISSUE THREAD

**Issue by ukai** [grpc/grpc-go#7448]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of Go are you using (`go version`)?

```
go version go1.22.5 linux/amd64
```

### What operating system (Linux, Windows, …) and version?

linux

### What did you do?
If possible, provide a recipe for reproducing the error.

```
$ go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.0
```

### What did you expect to see?

successfully installs protoc-gen-go-grpc

### What did you see instead?

```
go: downloading google.golang.org/grpc v1.5.0
go: downloading google.golang.org/grpc/cmd/protoc-gen-go-grpc v1.5.0
go: google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.0 (in google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.0):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.

```

**Comment by yurifedoseev** [comment]
+1,
I've rolled back to v1.4.0 (was `latest` before)

**Comment by ukai** [comment]
https://github.com/grpc/grpc-go/commit/9671c4a8c503ba2c9137f64aa3500e4ceca36f80

**Comment by artemis-my** [comment]
same here

**Comment by haruyama480** [comment]
reproduced on mac and linux.

This degradation fails all `go install` of `v1.5.0` and `latest`.

**Comment by ray5273** [comment]
Same here.

**Comment by hmtj99** [comment]
Facing same issue

**Comment by DriverX** [comment]
same

**Comment by hmtj99** [comment]
Reverting to v1.4.0 (instead of @latest) for now solves the issue

**Comment by narik41** [comment]
same issue with @latest

**Comment by github-charles-fraisse** [comment]
Same here with @latest, enforcing v1.4.0 to fix it

**Comment by saharatTiew** [comment]
Same here on wsl ubuntu

**Comment by ishustava** [comment]
It looks like the `grpc` module was only pulled in for testing. Do we really need it in this module or can we maybe avoid pulling in this dependency? This broke a lot of people who are trying to `go install` the latest module so if we can avoid this dependency, that would be great.

**Comment by dfawley** [comment]
Sorry for the breakage.  Pushed release 1.5.1 without the replace directive.

https://github.com/grpc/grpc-go/releases/tag/cmd%2Fprotoc-gen-go-grpc%2Fv1.5.1
