### ISSUE TITLE
design tradeoffs about not including ctx in method argument for generated stream handler

### ISSUE THREAD

**Issue by DMwangnima** [grpc/grpc-go#7455]
- related issue
https://github.com/grpc/grpc-go/issues/173

Hi all, I noticed that for grpc-go, instead of adding a ctx in method argument, it adds a ```Context()``` method to the Stream interface that is exposed to the user. But for unary method, it still includes ctx.
```
type RouteGuideServer interface {
        GetFeature(context.Context, *Point) (*Feature, error)
	ListFeatures(*Rectangle, grpc.ServerStreamingServer[Feature]) error
	RecordRoute(grpc.ClientStreamingServer[Point, RouteSummary]) error
	RouteChat(grpc.BidiStreamingServer[RouteNote, RouteNote]) error
}
```
Can you guys explain the reasoning behind this design? 
I think introducing a ctx in the method parameters like the unary method would make the interface more uniform and intuitive to use.

**Comment by dfawley** [comment]
> Can you guys explain the reasoning behind this design?

Maybe it wasn't the best design, but we can't change it now.

**Comment by DMwangnima** [comment]
@dfawley 
Thx for your reply! 
Actually I didn't mean to change it, but rather to ask about the reasons for such a design and the trade-offs. I'm sure there were similar questions when designing this interface, rather than making a decision in a snap of the head.

**Comment by dfawley** [comment]
It's hard to say.  I wasn't here then, but I think at the time, the team was very small and under pressure to deliver a large product in a small amount of time, so it's quite likely many decisions were made with our API that were not very deeply considered before they were done.  There are certainly many things that I would change if we ever did a gRPC-Go v2, but we most likely never will.
