### ISSUE TITLE
Reduce default max message size to 4 MiB

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-go#746]
This is the Go equivalent of grpc/grpc-java#1676. It is assumed there is a channel option that can increase the max message size for users that need it. If that's not the case, then it is fine to punt this post-GA for Go.

If this turns out not to be a one-line change with limited impact, then we should punt post-GA. It would be best before GA though.

**Comment by iamqizhao** [comment]
closed by #780

**Comment by ejona86** [comment]
Is this actually fixed? #780 looks server-side only. This issue was not specific to server.
