### ISSUE TITLE
Examples using the `experimental` stats package

### ISSUE THREAD

**Issue by davinci26** [grpc/grpc-go#7492]
Hey folks,

I am looking into the metrics registered in https://github.com/grpc/grpc-go/blob/0b33bfe7863c548658efdb4eac6e742ef2c8f3de/balancer/weightedroundrobin/balancer.go#L4 and they seem quite useful but I have hard time figuring out how I can use the `experimental` stats/metrics package to extract them. 

Do you have any examples/pointers?

**Comment by purnesh42H** [comment]
Are you looking for this https://github.com/grpc/grpc-go/blob/master/examples/features/stats_monitoring/README.md ?

**Comment by davinci26** [comment]
@purnesh42H hmmm I have to look into this a bit more, I dont think this example is the best one because it is not immediately obvious how you can retrieve the values here https://github.com/grpc/grpc-go/blob/b45fc413ca1ffd56cb2c7fe51220d0ed9167243b/balancer/weightedroundrobin/balancer.go#L51-L58 for example

**Comment by purnesh42H** [comment]
@davinci26 did you try enabling the metrics from opentelemetry API https://github.com/grpc/grpc-go/blob/master/examples/features/opentelemetry/README.md ?

they are are probably be already being exported through opentelemetry

**Comment by davinci26** [comment]
Our infra doesnt really support `opentelemetry` so I was looking into how I can export this metrics into a format that is `prometheus` native. So I ended up seeing how `otel` is implemented and then create a `prom` integration based on that.
 
Basically you need to implement an `estats.MetricsRecorder` and then: register it as a `MetricsRecorder`
