### ISSUE TITLE
undefined: grpc.SupportPackageIsVersion2

### ISSUE THREAD

**Issue by perrohunter** [grpc/grpc-go#750]
For some reason the latest protoc-gen is not generting the stubg with SupportPackageIsVersion3 which is the latest indicated in https://github.com/grpc/grpc-go/blob/master/rpc_util.go

I removed my protoc and grpc libraries from my GOPATH and re-downloaded via go get, regenerated the stubs and the value is still the old one, perhaps the grpc plugin for protoc is not up to date?

Manually changing this value to SupportPackageIsVersion3 in the generated stub seems to solve the issue

**Comment by zellyn** [comment]
You need to re-get the latest Go protobuf generator. `protoc` itself changes rarely: `go get -u github.com/golang/protobuf/{proto,protoc-gen-go}`
