### ISSUE TITLE
grpc usage on unix sockets: strange grpc registry behaviour

### ISSUE THREAD

**Issue by sbodese** [grpc/grpc-go#7516]
Hi everyone

i run into a strange problem on a go lang grpc usage with unix sockets:

1. a separate grpc server process with a registered service api is running on a unix socket, all fine
2. a separate service process with a grpc client, can call this grpc server successfully, all fine 
3. if i restart this service process, this client call again gives me "rpc error: code = Unimplemented desc = unknown service"
4. if i restart the grpc server now, the already restarted service can call this grpc server successfully 

This seems for me as a grpc registry issue or misuse.

Have anyone a idea or suggestion pls?

Thanks

Greetings Steffen

**Comment by aranjans** [comment]
Thanks @sbodese for raising the question. We are looking into this and will get back on this soon!

**Comment by sbodese** [comment]
Hi @aranjans 
problem is solved. It was caused by a wrong socket file usage: two different grpc server uses the same socketfile.

Regards Steffen
