### ISSUE TITLE
Question about option experimental.WithRecvBufferPool

### ISSUE THREAD

**Issue by wauxhall** [grpc/grpc-go#7517]
The comment says:
// Note: The shared buffer pool feature will not be active if any of the
// following options are used: WithStatsHandler, EnableTracing, or binary
// logging. In such cases, the shared buffer pool will be ignored.

So I'd like to know if there are any workarounds to use shared buffer with WithStatsHandler option? Or this is impossible at the moment? Perf tests show we really need this, but stats are also needed)))

I also can't find the code where options compatibility check is performed, I mean where is the code that checks if WithRecvBufferPool and WithStatsHandler are not used together.

Thanks!

**Comment by purnesh42H** [comment]
@wauxhall there have been similar asks in the past https://github.com/grpc/grpc-go/issues/6660. Current state of API doesn't allow reuse of buffer with Stats handler. Some discussion https://github.com/grpc/grpc-go/pull/5862/files#r1171991389.

We're doing new memory sharing entirely, and this option will mostly be going away https://github.com/grpc/grpc-go/pull/7356

**Comment by wauxhall** [comment]
Thanks a lot for your answer!
