### ISSUE TITLE
Valid allow-all Authz Policy return permission denied

### ISSUE THREAD

**Issue by alshabib** [grpc/grpc-go#7526]
### What version of gRPC are you using?

latest

### What version of Go are you using (`go version`)?

1.23

### What operating system (Linux, Windows, …) and version?

Linux

### What did you do?

Passed a valid authz policy that allows all rpcs. See unit test [here](https://github.com/alshabib/grpc-go/blob/failing-test/authz/grpc_authz_end2end_test.go#L83)

The principal is set `*` which is valid but this results in no policy being matched and therefore a permission denied is returned.

### What did you expect to see?

Permitted RPC

### What did you see instead?

Permission denied

**Comment by arjan-bal** [comment]
I ran a debugger along with the test and found that the policy match fails because the test is not using TLS, and this check returns early: https://github.com/grpc/grpc-go/blob/6a5a283b699dd16c8caa240d209d7302988ff753/internal/xds/rbac/matchers.go#L403-L407

**Comment by alshabib** [comment]
Thanks for your reply - I updated the test but it fails. 

Please have a look at [this test](https://github.com/alshabib/grpc-go/blob/failing-test/authz/grpc_authz_end2end_test.go#L391).

**Comment by arjan-bal** [comment]
The wildcard "*" gets converted to the regex `.+`, i.e. any non-empty substring:https://github.com/grpc/grpc-go/blob/1e2bb717e0d00d3191f2b90c0c458cf62bb2e5a5/authz/rbac_translator.go#L115-L119

So to allow "any" identity, we need to add two patterns, similar to the existing unit test:
```
"principals": [
	"*",
        ""
]
```

FYI @gtcooke94, please correct me if I'm wrong.

**Comment by alshabib** [comment]
According to the [gNSI.Authz spec](https://github.com/openconfig/gnsi/tree/main/authz), a presence match is only "*" which will match when the value is not empty. Requiring a "" diverges from the spec.

**Comment by arjan-bal** [comment]
Since this is TLS (not MTLS), there is no client certificate and I suspect there client has no client principal. This line is getting executed which uses empty string ("") as the principal: https://github.com/grpc/grpc-go/blob/ee5cbce343d2fa75705696cf38919849a891cf48/internal/xds/rbac/matchers.go#L412-L417

I tried your the authz config in the MTLS test case and it passes without the need for the empty string pattern.
https://github.com/grpc/grpc-go/blob/ee5cbce343d2fa75705696cf38919849a891cf48/authz/grpc_authz_end2end_test.go#L419

**Comment by gtcooke94** [comment]
Here's the proposal for grpc's authorization library, linking the specific line that says "*" will match when not empty" - https://github.com/grpc/proposal/blob/9a2c5794ed90f6625812146cc3d3e647d43e6641/A43-grpc-authorization-api.md?plain=1#L75

It looks like that same presence match definition is in the `gNSI.Authz` spec you linked.

**Comment by gtcooke94** [comment]
And the other relevant section of gRFC - https://github.com/grpc/proposal/blob/9a2c5794ed90f6625812146cc3d3e647d43e6641/A41-xds-rbac.md?plain=1#L175-L189

**Comment by alshabib** [comment]
Hmm that's a good point - I will try the same test in mTLS and see if this behaviour still exists. Thanks.

**Comment by alshabib** [comment]
Ah it does pass when the client principal is set. Apologies, I will close this. Thank you for looking into this.
