### ISSUE TITLE
bug: `FATAL: [core] grpc: Server.RegisterService found duplicate service registration for "grpc.health.v1.Health"`

### ISSUE THREAD

**Issue by afifurrohman-id** [grpc/grpc-go#7527]
### What version of gRPC are you using?
1.65.0
### What version of Go are you using (`go version`)?
go version go1.23.0 linux/amd64

### What operating system (Linux, Windows, …) and version?
Linux 🐶 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 GNU/Linux

### What did you do?
- `svc.proto`
```proto
syntax = "proto3";

package example;

import "google/protobuf/empty.proto";

option go_package = "example.com/health/main";


service Foo {
  rpc Ping(google.protobuf.Empty) returns (google.protobuf.Empty);
}

service Bar {
  rpc Ping(google.protobuf.Empty) returns (google.protobuf.Empty);
}
```

- `main.go`
```go
package main

import (
        "google.golang.org/grpc"
        "google.golang.org/grpc/health/grpc_health_v1"
)

type Svc1 struct {
        UnimplementedFooServer
        grpc_health_v1.UnimplementedHealthServer
}

type Svc2 struct {
        UnimplementedBarServer
        grpc_health_v1.UnimplementedHealthServer
}

func main() {
        s := grpc.NewServer()

        svc1 := new(Svc1)
        svc2 := new(Svc2)

        RegisterFooServer(s,svc1)
        RegisterBarServer(s, svc2)

        grpc_health_v1.RegisterHealthServer(s, svc1)
        grpc_health_v1.RegisterHealthServer(s, svc2)

}
```

- Gen
```sh
protoc --go_out=. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --go-grpc_out=. svc.proto
```

### What did you expect to see?
It should work, each service have own health check and serve as single server

### What did you see instead?
`FATAL: [core] grpc: Server.RegisterService found duplicate service registration for "grpc.health.v1.Health`

**Comment by andisulistyonugroho** [comment]
Hi, why dont just?
```go
        grpc_health_v1.RegisterFooServer(s,svc1)
        grpc_health_v1.RegisterBarServer(s, svc2)
```
perhaps you can share your generated _grpc.pb.go?

Not sure if this is related to your issue, but
the same error also happened to us when trying to use two controllers for one proto & reregistering both controllers to the same service, the solution is reuse the same "server" for both controllers & register only one controller.


foo.controller.go
```go

type FooServer struct {
    UnimplementedFooServer
}

func FooService() *FooServer {
	return &FooServer{}
}

func (srv FooServer) GetFooList() {
...
}
```

bar.controller.go
```go
func (srv FooServer) GetBarList() {
...
}

```

main.go
```go
s := grpc.NewServer()

RegisterFooServer(s, controllers.FooService())
```

**Comment by afifurrohman-id** [comment]
> Hi, why dont just?
> 
> ```go
>         grpc_health_v1.RegisterFooServer(s, svc1)
>         grpc_health_v1.RegisterBarServer(s, svc2)
> ```
> 

Wdm ? it doesn't have those method, that is third party.

> perhaps you can share your generated _grpc.pb.go?

If you follow the reproduceable steps it should give same generated output.

**Comment by purnesh42H** [comment]
The error you're encountering is due to trying to register the `grpc_health_v1.HealthServer` service twice, once for Svc1 and once for Svc2. In gRPC, each service name must be unique, and the grpc_health_v1.HealthServer service is already registered when you attempt to register it again, which results in a duplicate service registration error.

If both Svc1 and Svc2 should report their health using the same health service, you only need to register the `grpc_health_v1.HealthServer` once. You can use a single health server to manage the health status of both services.

Please refer to example https://github.com/grpc/grpc-go/tree/ee5cbce343d2fa75705696cf38919849a891cf48/examples/features/health for correctly setting up health server
