### ISSUE TITLE
Reasoning about retry throttling parameters

### ISSUE THREAD

**Issue by roanta** [grpc/grpc-go#7539]
Hi!

I would like to reason about [retry throttling](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#throttling-retry-attempts-and-hedged-rpcs) in terms of an upper bound for traffic amplification, relative to the steady state of my service. It looks like `token_count` is [equivalent](https://github.com/grpc/grpc-go/blob/master/clientconn.go#L1620) to `successRate` * `tokenRatio`, which is close to what I need. However, I don't know how to reasonably set `maxTokens`, which is also used to derive the threshold. Part of the problem is that `maxTokens` is a defined in absolute terms, rather then relative. 

- Am I missing an obvious way to set `maxTokens`?
- Is it possible to "bend" this implementation to conform to the semantics I'm describing?

I'm new to gRPC, so please let me know if there are additional docs or resources I've missed which make this clearer.

Thanks in advance!

**Comment by purnesh42H** [comment]
@roanta right now maxTokens is absolute number. However, the token computation is based on the number of successful and failed RPCs, as per https://github.com/grpc/proposal/blob/master/A6-client-retries.md#throttling-retry-attempts-and-hedged-rpcs

I don't think we have any useful guidance to offer here. I think you'll just need to experiment with it a bit and see what works for your service
