### ISSUE TITLE
How to stop client from connecting to tcp socket

### ISSUE THREAD

**Issue by barthr** [grpc/grpc-go#754]
I have this use case where I need to connect to the right server which will handle the messages.
I'm just redialing another tcp address with the grpc.Dial function. But this blocks because it keeps reconnecting the client to the old address

example:

`	if err := requestClient.DialServer(remoteAddr, grpc.WithInsecure()); err != nil {
		log.Printf("DialServer failed because: %v", err)
	}`

Here I dial the Server(with grpc.Dial) but when I Dial again in another part of my code, the program just blocks on the connecting with the old socket (which is not available anymore) (ClientConn.Close() is not working aswell)

**Comment by puellanivis** [comment]
I'm highly confused about the code you present.

`lleuad grpc-go$ grep -r DialServer .`
`Error Code 1 returned`

Are you wrapping around something in the library? Because if you are, we can't really help you out without knowing what the DialServer method is doing…

**Comment by barthr** [comment]
My excuse, 

this is the function I was referring to:

`func (this *GrpcClient) DialServer(targetUrl string, options grpc.DialOption) error {
	var err error

	this.Connection, err = grpc.Dial(targetUrl, options)

	if err != nil {
		return err
	}

	return nil
}
`

The problem is that when the socket which get's dialed is not available the program just blocks, but instead I want to send the messages to another server. I was looking into load balancing on the client side but I'm not entirely sure how to implement it

**Comment by iamqizhao** [comment]
It is still unclear to me how you run into the problem. grpc.Dial does not block unless you specify grpc.WithBlock DialOption.

Can you show me how you dial two addresses in this code?

**Comment by barthr** [comment]
It is not truly blocking, it just keeps reconnecting to the socket and my program doesn't allow any other connection than

```Go
func readMessageQueue(listener client.QueueListener, brokerClient interface{}) {
	msgs := listener.ListenForMessages()
	brokerMsg := reflect.ValueOf(brokerClient).Interface().(brokercontracts.BrokerUrlContractClient)

	for msg := range msgs {
		if err := requestClient.DialServer(knownServers[1], grpc.WithInsecure()); err != nil {
			log.Printf("DialServer failed because: %v", err)
		}

		if len(msg.Body) == 0 {
			continue
		}

		log.Printf("Received message: %s\n", msg.Body)

		messageToBeSend := &brokercontracts.UrlRequest{
			Url: string(msg.Body),
		}
        message:
		r, err := brokerMsg.CrawlWebsiteRequest(context.Background(), messageToBeSend)

		if err != nil {
			log.Printf("Could not send message: %v", err)
			log.Println("Starting server discovery.....")
			serverDiscovery()
                        goto message
		}
		// When there is a message from the RabbitMQ queue
		log.Println("Message send to Remote")

		log.Println(r.Content)

	}
}

func serverDiscovery() {
	for _, endpoint := range knownServers {
		err := requestClient.DialServer(endpoint, grpc.WithInsecure())
		if err == nil {
			return
		}
	}
}



````

**Comment by menghanl** [comment]
If I understand correctly, there are multiple servers, and the client is trying to send message to them. This send should succeed if one of the servers is working.

If you want to manage the connections on your own, one way is to create a list of connections, and then create a new gRPC client for each of this connections. Changing the underlying connection for a gRPC client is not supported.
```go
func (this *YourClient) DialServer(targetUrls []string, options grpc.DialOption) error {
  var err error
  for i, addr := range targetUrls {
    this.Connections[i], err = grpc.Dial(targetUrl, options)
    if err ... // check error
    this.Clients[i] = yourpb.NewYourServiceClient(this.Connections[i])
  }
}
```

Another way to do this is to create your own [name resolver](https://github.com/grpc/grpc-go/blob/master/naming/naming.go#L61).

**Comment by barthr** [comment]
That seems logical but by using this the underlying connection will keep trying to connect to All the sockets, and produce error messages

**Comment by barthr** [comment]
That seems logical but by using this the underlying connection will keep trying to connect to All the sockets, and produce error messages

**Comment by barthr** [comment]
I solved it with using context.WithTimeout, the generated function from grpc was blocking because the rpc was not avalaible
