### ISSUE TITLE
Add cancel cause when client sends RST_STREAM frame

### ISSUE THREAD

**Issue by dastrobu** [grpc/grpc-go#7541]
### Use case(s) - what problem will this feature solve?

When a client resets a connection, the http2_server cancels the current context to interrupt all "server internal processing". Relevant code is [`t.closeStream(s, false, 0, false)`](https://github.com/grpc/grpc-go/blob/6a5a283b699dd16c8caa240d209d7302988ff753/internal/transport/http2_server.go#L832) and [`s.cancel()`](https://github.com/grpc/grpc-go/blob/6a5a283b699dd16c8caa240d209d7302988ff753/internal/transport/http2_server.go#L1315). 

When there is a big context stack within the server's logic, it can be quite hard to find out why the context was canceled. 
Was it due to some internal error? Timeout? Or is it due to a client sending the RST frame? 

A real-world problem analysis is described in https://github.com/grafana/tempo/issues/3957. 

### Proposed Solution

I am proposing to replace [`context.CancelFunc`](https://github.com/grpc/grpc-go/blob/6a5a283b699dd16c8caa240d209d7302988ff753/internal/transport/transport.go#L246C2-L246C33) with `context.CancelCauseFunc` and adjust all context cancellations to  report the cause. 

For the example described above, it could be something like this

```go
func (t *http2Server) handleRSTStream(f *http2.RSTStreamFrame) {
	// If the stream is not deleted from the transport's active streams map, then do a regular close stream.
	if s, ok := t.getStream(f); ok {
		t.closeStream(s, false, 0, false, errors.New("RST_STREAM frame received"))
		return
	}

// ... 

func (t *http2Server) closeStream(s *Stream, rst bool, rstCode http2.ErrCode, eosReceived bool, cause error) {
	// In case stream sending and receiving are invoked in separate
	// goroutines (e.g., bi-directional streaming), cancel needs to be
	// called to interrupt the potential blocking on other goroutines.
	s.cancel(cause)
```

### Alternatives Considered

`nil`

### Additional Context

When a pattern is established to communicate the cause of context cancellation, there are a few other cases, in addition to the one described above, where it could be useful:

1. **Client closes connection**:
   When the client closes a connection before the server can process all requests (asynchronously), the server's context gets canceled. It is up to the server implementor to decide how to handle that case. Should it rollback a transaction? Continue execution until done? To achieve that, the connection closed (by client) should be set as the cancel cause in [http2_server.go#L1272](https://github.com/dastrobu/grpc-go/blob/cancel-cause/internal/transport/http2_server.go#L1272).

2. **Client sets timeout via the `grpc-timeout` header**:
   When the client sets a timeout, the server should be able to distinguish between a gRPC timeout and other timeouts set elsewhere. To achieve that, `context.WithTimeout(ctx, timeout)` should be replaced by something like `context.WithTimeoutCause(ctx, timeout, GrpcTimeoutErr)` in [context.go#L29](https://github.com/dastrobu/grpc-go/blob/cancel-cause/internal/transport/context.go#L29).

3. **Other situations**:
   Even for situations that should rarely happen, like `Received a HEADERS frame with :method %q which should be POST` in [http2_server.go#L564](https://github.com/dastrobu/grpc-go/blob/cancel-cause/internal/transport/http2_server.go#L564), it could be beneficial to communicate a cause.

In essence, each case that leads to a `s.cancel()` call informs the calling client about the reason (e.g., via an HTTP status) but does not inform the server's goroutines working on the stream about the reason. In the long run, the goroutines should get as much information as possible about the actions the calling client took (e.g., closing the connection, setting a timeout, sending an RST frame) to react accordingly or if gRPC canceled the context (e.g., receiving bad headers).

The purpose is to allow the server's goroutines to implement logic to react to the client's actions appropriately and, as an additional benefit, make debugging easier, and allow the implementation of metrics and alerting which can distinguish a badly configured server (timeouts, etc.) from a badly configured client (closing connections, etc.).

**Comment by arjan-bal** [comment]
Hi @dastrobu, thanks for submitting this proposal. It seems useful to me, I'm discussing this with other maintainers to see if we want to add this.

**Comment by arjan-bal** [comment]
@dastrobu are you trying to propagate the reason for context cancellation to service method handlers? If yes, can you describe some use cases in which the handlers would react differently to different `causes`?

If the `cause` is not intended for method handlers, can you explain how it will be used?

**Comment by dastrobu** [comment]
@arjan-bal sure, let me try to detail the described use case a bit.

The Grafana Tempo distribute exposes a gRPC API to consume data.  
In the handler, the context is propagated and some goroutines do some data processing in parallel.  
When one of the goroutines fails (for whatever reason), it cancels the context, which in turn cancels all other goroutines.

In the handler, the error is reported so that operations teams can react to it.  
However, the error message is just saying "context canceled". So what happened?

1. The client sent a RST frame. So the server is behaving correctly. The client may have canceled intentionally or the client is somehow misbehaving.
2. The server had an internal error and canceled the context. The ops team needs to investigate and fix it.

The proposal would make it transparent if the context cancellation was due to a client or a server error.

To illustrate, I tried to sketch a simplified version of the code:
```go
func handle(ctx context.Context, d []string) {
	err := processData(ctx, d)
	if err != nil {
		fmt.Printf("Error processing data: %v\n", err) // Error processing data: context cancelled
	}
}

func processData(ctx context.Context, d []string) error {
	ctx, cancel := context.WithCancelCause(ctx)
	defer cancel(nil)

	doneChan := make(chan struct{}, 1)
	errChan := make(chan error, 1)

	var wg sync.WaitGroup
	wg.Add(len(d))
	for _, di := range d {
		go func() {
			defer wg.Done()
			err := doStuff(ctx, di)
			if err != nil {
				cancel(err) // interrupt other goroutines
				errChan <- err
				return
			}
		}()
	}

	go func() {
		wg.Wait()
		doneChan <- struct{}{}
	}()

	select {
	case err := <-errChan:
		return err
	case <-doneChan:
		return nil
	case <-ctx.Done():
		return context.Cause(ctx)
	}
}
```

In the real-world situation described in https://github.com/grafana/tempo/issues/3957, it took us several weeks to find out that context cancellation was actually caused by a misconfigured client.  
We did not find the reason until patching the Go SDK to log stack traces of context cancellation.  
I would like to avoid this hassle for my team and others in the future, and I think implementing this small feature could contribute a lot.

**Comment by dastrobu** [comment]
@purnesh42H, thanks for your question.

The primary use case I was creating this issue for is the client-side request cancellation described in https://github.com/grpc/grpc-go/issues/7541#issuecomment-2306980949. 

There are certainly more scenarios, where causes would come in handy. Consider, for example, timeout handling. 
The Go server may cancel with `context deadline exceeded` when a timeout is set: https://github.com/grpc/grpc-go/blob/6a5a283b699dd16c8caa240d209d7302988ff753/internal/transport/http2_server.go#L531)

Considering the case where there are more timeouts down the context stack, it would also be very helpful to see the cause of the timeout. So changing to 

```go
	if timeoutSet {
		s.ctx, s.cancel = context.WithTimeoutCause(ctx, timeout, grpcTimeoutErr)
```
could make this more transparent.

I would not consider myself a gRPC expert, but I'd say status codes will primarily communicate errors to the calling client, while context cancellation (with causes) communicates to the upstream handler.

I see that introducing causes to all context cancellations might be a larger change. But you might consider introducing it step-by-step, as it is not a breaking change.

Application code checking just for `ctx.Err()` won't be affected by the added cause. However, application code will introduce checking for `context.Cause(ctx)` over time anyway (in my opinion). Note that `context.Cause(ctx)` falls back to `ctx.Err()` if no cause was provided. 

Over time, one could introduce the cancellation cause to many places like, for example:

```go
	if t.state != reachable {
		t.mu.Unlock()
		s.cancel(stateUnreachableErr) // ⬅ cause 
		return nil
	}
	if uint32(len(t.activeStreams)) >= t.maxStreams {
		t.mu.Unlock()
		t.controlBuf.put(&cleanupStream{
			streamID: streamID,
			rst:      true,
			rstCode:  http2.ErrCodeRefusedStream,
			onWrite:  func() {},
		})
		s.cancel(tooManyStreamsErr) // ⬅ cause 
		return nil
	}
```

@purnesh42H, I'd be interested if you see any downside to adding the cause (apart from the actual implementation work)?

**Comment by purnesh42H** [comment]
@dastrobu i agree to the use case for providing cause of context cancelation but all the use cases you are describing are applicable to application logic. As far as grpc server library is concerned, the cause for timeout is either client canceled the context or context deadline exceeded which is inferred from the error code and can always be logged by the application handler itself if they need to log more information about the timeout etc.

We still don't see much use in changing the grpc server library to add cause for context cancelation. I agree that application handler can utilize the cause cancelation to propagate more information applicable to their use case.

**Comment by dastrobu** [comment]
@purnesh42H I am not sure I can follow your suggestion to detect request cancellation from a handler that offloads work to another goroutine.

> which is inferred from the error code and can always be logged by the application handler itself if they need to log more information about the timeout etc.

Taking your example code from https://github.com/grpc/grpc-go/tree/master/examples/features/cancellation and modifying it a bit may illustrate the problem:

```go
func workOnMessage(ctx context.Context, msg string) {
	i := 0
	for {
		if err := ctx.Err(); err != nil {
			fmt.Printf("context cancelled for message worker %q: %v\n", msg, err)
			return
		}
		fmt.Printf("working on message: %q %d\n", msg, i)
		i += 1
	}
}

func (s *server) BidirectionalStreamingEcho(stream pb.Echo_BidirectionalStreamingEchoServer) error {
	ctx := stream.Context()
	for {
		if err := ctx.Err(); err != nil {
			fmt.Printf("context closed: %v\n", err)
			return nil
		}
		recv, err := stream.Recv()
		if err != nil {
			fmt.Printf("server: error receiving from stream: %v\n", err)
			if err == io.EOF {
				return nil
			}
			return err
		}
		msg := recv.Message
		go workOnMessage(ctx, msg)
		stream.Send(&pb.EchoResponse{Message: msg})
	}
}
```

Note that the `err` in `fmt.Printf("server: error receiving from stream: %v\n", err)` will just report: `server: error receiving from stream: rpc error: code = Canceled desc = context canceled`, so I am not sure how the handler would tell that the client canceled via an RST.

Next, you mentioned that a context gets canceled only in the case of the RST frame (and the context deadline). First, that is very implicit to always assume that any context cancellation is caused by an RST. Second, I do see a few other calls of https://github.com/grpc/grpc-go/blob/6f50403edb0c2db1bb557168cf4e6f87ea2efdb5/internal/transport/http2_server.go#L1324

For example [here](https://github.com/grpc/grpc-go/blob/6f50403edb0c2db1bb557168cf4e6f87ea2efdb5/internal/transport/http2_server.go#L799) and [there](https://github.com/grpc/grpc-go/blob/6f50403edb0c2db1bb557168cf4e6f87ea2efdb5/internal/transport/http2_server.go#L804).

Note that `rstCode http2.ErrCode` from `closeStream(...)` would be valuable information to pass to the context cancellation cause. Please also note that `s.cancel()` is called before updating the stream state.

From my perspective, I still don't see a good way for error handling in asynchronous scenarios such as outlined above.  
I'd be happy to contribute an example along the outlined scenario for asynchronous message processing with proper error handling under your guidance, if I am missing something here.

I'd also still be interested in your opinion on my previous question:

> @purnesh42H, I'd be interested if you see any downside to adding the cause (apart from the actual implementation work)?

**Comment by purnesh42H** [comment]
@dastrobu let me know if i understand your ask correctly. You want to distinguishing client-initiated RST_STREAM from other cancellation causes? `context.Canceled` doesn't tell you why the context was canceled, making it difficult to differentiate between:

1) Client intentionally closing the connection (e.g., normal shutdown, user action).
2) Client sending a RST_STREAM due to an error on their end.
3) Server-side timeout or any internal error leading to stream termination.

Let me know if i missed anything.

Meanwhile, would it be possible for you to send a draft PR of what/how much you will change in grpc library to achieve 1)? We can bring the proposal to other maintainers if the change is contained, additive and clean

**Comment by dastrobu** [comment]
@purnesh42H Great summary, that's exactly what I had in mind. I can work on drafting a PR in about three weeks, as I likely won't have time before then. Thanks for the productive discussion up to this point!

**Comment by dastrobu** [comment]
I've put together a quick draft to help move the discussion forward. The tests and details still need further refinement, but this should give a good illustration of the idea I had in mind.

**Comment by purnesh42H** [comment]
Thanks @dastrobu i will take a look.

**Comment by dfawley** [comment]
> Client closes connection:

Why is the application responding to a cancellation by the client differently from connection loss?  Can you give reasonable examples of why it would want to do anything differently for these two cases?

> Client sets timeout via the grpc-timeout header:
> When the client sets a timeout, the server should be able to distinguish between a gRPC timeout and other timeouts set elsewhere.

What else is setting the timeout?  There is nothing between gRPC and the application that would alter it.  And how would a server handler realistically behave differently in the two cases?

> Other situations:
> Even for situations that should rarely happen, like Received a HEADERS frame with :method %q which should be POST in [http2_server.go#L564](https://github.com/dastrobu/grpc-go/blob/cancel-cause/internal/transport/http2_server.go?rgh-link-date=2024-08-20T13%3A40%3A32Z#L564), it could be beneficial to communicate a cause.

This example causes the RPC to short-circuit the application on the server side entirely.  So there is no context to cancel yet based on client incoming headers problems.

I don't see any value in annotating the context with an extra cause, considering there are very very few causes, and the response to them is not expected to change.  If this is purely for monitoring and alerting, then we may have other, better options we can discuss.  I don't think the server application is expected to behave differently in any of these cases, and doing so may be an anti-pattern.

**Comment by dastrobu** [comment]
> Why is the application responding to a cancellation by the client differently from connection loss? Can you give reasonable examples of why it would want to do anything differently for these two cases?

It seems the discussion is about handling these two situations differently from other causes of cancellation. I feel that the discussion might not be progressing, as the original real-world example referenced in [#7541](https://github.com/grpc/grpc-go/issues/7541#issue-2475685787) might be too complex for a simple illustration, while the simplified example might be too basic to convey the real-world issues our team faces.

In real scenarios, more packages are involved beyond gRPC and simple client code. These packages create additional contexts with deadlines and cancellations in the context stack. Since gRPC is at the root of the context, distinguishing cases becomes challenging. This is why I proposed a simple extension to gRPC, which I believe is a non-breaking and not very invasive solution.

> What else is setting the timeout? There is nothing between gRPC and the application that would alter it. And how would a server handler realistically behave differently in the two cases?

As previously mentioned, there can be various other libraries in between. Ideally, every library would adopt the cancel cause pattern, allowing the most flexible reaction to context cancellations.

> I don't see any value in annotating the context with an extra cause, considering there are very very few causes, and the response to them is not expected to change. If this is purely for monitoring and alerting, then we may have other, better options we can discuss. I don't think the server application is expected to behave differently in any of these cases, and doing so may be an anti-pattern.

Even setting a single cause for all gRPC-induced context cancellations could be beneficial, but it seems I might not have articulated the problem clearly, or the gRPC team may have a different perspective, which is perfectly acceptable. 

> If this is purely for monitoring and alerting, then we may have other, better options we can discuss. 

I would be interested in learning about these "better options." Could you provide any references?

**Comment by purnesh42H** [comment]
> Since gRPC is at the root of the context, distinguishing cases becomes challenging.
@dastrobu is your requirement only for alerting and monitoring? or you expect server to do something different than what it is doing now?

**Comment by dfawley** [comment]
Note that connection loss can already be detected using the stats handler's HandleConn getting a ConnEnd message, so it's possible that surfacing these connection termination events on your dashboards might be all you needed to see that there were connectivity problems occurring at the same time as seeing the cancellation events.

> I feel that the discussion might not be progressing, as the original real-world example referenced in https://github.com/grpc/grpc-go/issues/7541#issue-2475685787 might be too complex for a simple illustration, while the simplified example might be too basic to convey the real-world issues our team faces.

I am pretty sure I followed the example, but I'm still not really understanding what you would do differently that would have made the problem better.  Whether the client cancels the RPC or the connection is lost, the server should just stop handling the RPC, and you can either expect the client stopped caring or there was a connectivity issue, neither of which is the responsibility of the server's owner to resolve.

The Java analog here would be the stream tracer:

https://grpc.github.io/grpc-java/javadoc/io/grpc/StreamTracer.html#streamClosed%28io.grpc.Status%29

I don't think there's much to distinguish that we aren't already distinguishing.  Just connection loss vs. cancellation, which currently both show up as the context being cancelled.  If there are compelling use cases, I'm OK with adding a cancel cause that carries a `status.Status` error.  Connection loss would be code `UNAVAILABLE` and RST_STREAM-based cancellation can be `CANCELLED` and timeout would be `DEADLINE_EXCEEDED`.  There can be a string with more details as appropriate.

**Alternatively**, our per-RPC stats handler interface already has an `End` event with an error field:

https://pkg.go.dev/google.golang.org/grpc/stats#End

I'm not sure how or if we're setting this on the server-side.  If we aren't setting it at all, we could start setting it in the same way as described above.  That should provide sufficient metrics for monitoring/alerting purposes.  If the results must be tied to the RPC more directly, then the cancel cause approach is probably OK to use as well, but I'm still not sure I understand exactly how you plan on using it.

**Comment by dastrobu** [comment]
It looks like the stats handler is providing some of the required information. Specifically, the `toRPCErr` function seems to offer the error API I was essentially suggesting, and it resembles your suggestion:

> Connection loss would be code UNAVAILABLE and RST_STREAM-based cancellation can be CANCELLED, and timeout would be DEADLINE_EXCEEDED.

I have to say that I am missing the connection between [`handleRSTStream`](https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_server.go#L828) and [`Canceled`](https://github.com/grpc/grpc-go/blob/master/codes/codes.go#L45). According to the documentation of `Canceled`:

> Canceled indicates the operation was canceled (typically by the caller).

The question arises about what other cases there are, apart from that "typical" scenario. In any case, the connection to the RST frame is very subtle.

The stats handler has the drawback that it reports `stats.End` after the context has been canceled. Reacting to context cancellation is challenging to implement, as the stats are not available when the context is canceled. There might be ways to extract the information from the stats handler, though.

> I'm not sure how or if we're setting this on the server side. If we aren't setting it at all, we could start setting it in the same way as described above.

The stats handler is just reacting to the canceled context and converting it by passing it to the `toRPCErr` function. So there is no additional information in the `stats.End` error, apart from the fact that one receives an additional stat for the connection closed case (`stats.ConnEnd`), plus it is not reacting to child contexts that get canceled for other reasons.

Unfortunately, the error from `stats.End` cannot be properly matched with `errors.Is(s.Error, status.Error)`, as [`status.Error`](https://github.com/grpc/grpc-go/blob/4bb0170ac65f2726d593eb7364a807b171fa1d63/internal/status/status.go#L207) does not implement the error protocol: "Type does not implement error as the Error method has a pointer receiver" (only the type `*status.Error` does). Furthermore, I am not sure this is the intended way to match the error, as `status.Error` is located in the `internal` folder.

An improvement would be to make `toRPCErr` return a `StatusError` type that can be properly matched with `errors.Is`. Then one could determine the status [`Code`](https://github.com/grpc/grpc-go/blob/070d9c793af46df05f24b4de548509627606f5b7/codes/codes.go#L35) from `stats.End`.

Still, one would only get the `Canceled` gRPC code, which indicates the call is "typically" canceled by the caller.

From a user's perspective, handling cancel causes would be a lot simpler from my point of view.  
To follow your suggestion, setting the cancel cause to a `status.Error` carrying a [`Code`][Code] would be a good idea if we could make that type an API type (not an internal type) that implements the Error interface such that it can be matched with `errors.Is` to retrieve the [`Code`][Code] in the end.

Thanks for pointing me to the stats handler; this is already providing some good insights. I do still see some room for improvement to make the error cases (especially those caused by client behavior) more transparent and easier to handle.

[Code]: https://github.com/grpc/grpc-go/blob/070d9c793af46df05f24b4de548509627606f5b7/codes/codes.go#L35

**Comment by dfawley** [comment]
> The question arises about what other cases there are, apart from that "typical" scenario. In any case, the connection to the RST frame is very subtle.

The way RPCs are canceled in gRPC leverages RST_STREAM directly.  So when the client wants to cancel an RPC, it cancels its context, the gRPC client library sees this and sends a RST_STREAM frame, which the server sees and then cancels the server handler's context.  The user typically shouldn't have to even know about any of these details.

> I am not sure this is the intended way to match the error, as status.Error is located in the internal folder.

`Status` is defined in internal to allow some internal code to access it in a way that we don't want users to (e.g. because it provides mutable data that we want to have direct access to for optimizations, but that we don't want anyone to mutate).  But `Status` is a public API: https://pkg.go.dev/google.golang.org/grpc/status#pkg-types

> Still, one would only get the Canceled gRPC code, which indicates the call is "typically" canceled by the caller.

Typically because a proxy could send a RST_STREAM instead, but the gRPC library can't distinguish these two situations since they are the same on the wire.

> to retrieve the Code in the end.

[`status.Code`](https://pkg.go.dev/google.golang.org/grpc/status#Code) (or `FromError`) should be used for this purpose.

I am also still wondering about your actual use cases here:

> I'm still not really understanding what you would do differently that would have made the problem better

**Comment by dastrobu** [comment]
> The way RPCs are canceled in gRPC leverages RST_STREAM directly. So when the client wants to cancel an RPC, it cancels its context, the gRPC client library sees this and sends a RST_STREAM frame, which the server sees and then cancels the server handler's context. The user typically shouldn't have to even know about any of these details.

This seems to come from the assumption that the client is also implemented in Go. However, from my point of view, the client may be implemented in any language. In our scenario, most clients are implemented in Java, which does not have the Go concept of contexts. I'd expect the server is reporting errors in a way that is not making any assumptions about the implementation of the client.  

> [status.Code](https://pkg.go.dev/google.golang.org/grpc/status#Code) (or FromError) should be used for this purpose.

I guess `FromError` was the bit I was missing, as `stats.End` contains an instance of the internal [`Status`](https://github.com/grpc/grpc-go/blob/4bb0170ac65f2726d593eb7364a807b171fa1d63/internal/status/status.go#L43).  

See the following code path:  

 * https://github.com/grpc/grpc-go/blob/0d0e5308485f563e58bc559dd07a5bb652b544b2/server.go#L1595
 * https://github.com/grpc/grpc-go/blob/3e925040f34cde54321fb02d8e6ef88d154da6d3/status/status.go#L59
 * https://github.com/grpc/grpc-go/blob/4bb0170ac65f2726d593eb7364a807b171fa1d63/internal/status/status.go#L125  

However, converting with `FromError` does work as you suggested. Maybe extending the `stats_monitoring` example would benefit from showing that conversation.  

> Typically because a proxy could send a RST_STREAM instead, but the gRPC library can't distinguish these two situations since they are the same on the wire.

Agree.  

> I'm still not really understanding what you would do differently that would have made the problem better

I am also still not quite getting what information I am missing to provide. It is basically identifying clients that "misbehave." I.e., sending an RST frame too early but not closing the connection, or closing the connection too early.  

Most of that seems to be doable with a proper stats handler and matching errors in `stats.End` with `FromError` as you suggested. The only remaining challenge will be correlating these errors with the closed contexts in other goroutines. But I guess this may be doable somehow.  

Thank you for the suggestions on the stats handler part. I personally think that the library would be probably simpler to use with cancel causes, as this is a Go built-in concept. I don't quite get the hesitation of adopting that concept in the library, but that is ok.

**Comment by dfawley** [comment]
> This seems to come from the assumption that the client is also implemented in Go.

That paragraph was written with a Go client in mind, but the concept is the same in all languages -- the only difference is they just don't have a Go context on their side.  That's equivalent to how a server written in Java communicates errors by throwing exceptions, but in a Go client those errors will appear as `status`-package `error`s instead.  And vice-versa: the Java client will get an exception caused by Go returning an `error`.

> I am also still not quite getting what information I am missing to provide. It is basically identifying clients that "misbehave." I.e., sending an RST frame too early but not closing the connection, or closing the connection too early.

"Identifying clients that 'misbehave'" is "what you want".  I'm trying to determine "why you want to do that".  Once you've identified these clients, what will you do with that information?  If a stats handler for monitoring will meet your needs, then we can focus on that -- whether it already has what you need or how it can be extended to add it.  If you have a use case that requires the server handler itself to behave differently, then it does seem like the cancel cause would be the only viable way to communicate that.

But at the end of the day, as a service owner, it doesn't seem like there is really anything you can do, regardless of whether it was connection loss or client-side cancellation that caused an RPC to terminate early.  If that assumption is true, then adding a feature that lets you distinguish between these two things that you can't do anything about anyway seems to have relatively little value.

> However, converting with `FromError` does work as you suggested. Maybe extending the `stats_monitoring` example would benefit from showing that conversation.  

I'd be OK with this, but only if it doesn't add too much complexity into the existing example.  Otherwise we could create a new example to highlight this.
