### ISSUE TITLE
How to give grpc connection Creating a Listener

### ISSUE THREAD

**Issue by xiatianqiuyu** [grpc/grpc-go#7563]
How to give grpc connection creating a Listener

**Comment by aranjans** [comment]
@xiatianqiuyu you mean how to create a gRPC listener in Go and set up a connection? If so, you can take a look at [this](https://github.com/grpc/grpc-go/blob/cfd14baa8264cbeebf6308a7b68333c8c2fc6e86/examples/features/reflection/server/main.go#L75) example where it does the same.
