### ISSUE TITLE
Backport #7571 to 1.66 once merged

### ISSUE THREAD

**Issue by arvindbr8** [grpc/grpc-go#7572]
PR #7571 resolves a bug that was introduced in version 1.66. We need to apply this patch and release a new version to fix the issue. This issue is used to track the progress of patching and releasing the fix.

**Comment by coxley** [comment]
@arvindbr8: Any idea when we can get this patched in? :)

**Comment by arjan-bal** [comment]
Closed via https://github.com/grpc/grpc-go/pull/7616
The fix is part of version 1.66.2.
