### ISSUE TITLE
Why is Metadata still being used instead of Attributes in clientconn.go?

### ISSUE THREAD

**Issue by marsevilspirit** [grpc/grpc-go#7585]
### Description

While reading the `grpc-go` source code, I noticed that the `Metadata` field in `clientconn.go` has been marked as deprecated with a recommendation to use `Attributes` instead. However, in the current implementation, particularly at line 923, `Metadata` is still being used for comparison.

```go
/home/mars/git_clone/grpc-go/clientconn.go|923 col 3-13 note| a.Metadata is deprecated: use Attributes instead.
/home/mars/git_clone/grpc-go/clientconn.go|923 col 17-27 note| b.Metadata is deprecated: use Attributes instead.
/home/mars/git_clone/grpc-go/clientconn.go|1312 col 6-27 note| ac.scopts.CredsBundle is deprecated: Use the Attributes field in resolver.Address to pass arbitrary data to the credential handshaker.
/home/mars/git_clone/grpc-go/clientconn.go|1313 col 24-45 note| ac.scopts.CredsBundle is deprecated: Use the Attributes field in resolver.Address to pass arbitrary data to the credential handshaker.


func equalAddressIgnoringBalAttributes(a, b *resolver.Address) bool {
	return a.Addr == b.Addr && a.ServerName == b.ServerName &&
		a.Attributes.Equal(b.Attributes) &&
		a.Metadata == b.Metadata
}
```

### Questions

- Since `Metadata` is marked as deprecated, are there plans to replace it with `Attributes` in future versions?
- Is there a specific reason for retaining `Metadata` in the code, such as backward compatibility or specific use cases?

### Additional Information

- **gRPC-Go version**: v1.66.0
- **Go version**: go1.23.0 linux/amd64
- **Operating System**: arch linux 1.10.7-arch1-1
- **Editor**: neovim

Thank you for your help and for the great work on this project! I’m looking forward to understanding the reasoning behind this decision.

**Comment by marsevilspirit** [comment]
Can Attributes fully replace Metadata? If so, can the Metadata field be removed from the Address struct?

**Comment by purnesh42H** [comment]
We have a pending item to remove `resolver.address.metadata` as part of https://github.com/grpc/grpc-go/issues/6472. @marsevilspirit fyi
