### ISSUE TITLE
Allow generated handlers to check the correct errors are returned at compile time

### ISSUE THREAD

**Issue by markusthoemmes** [grpc/grpc-go#7596]
### Use case(s) - what problem will this feature solve?

Currently, it's enforced by convention that a gRPC handler returns an error generated by `status.Error`. The docs state

> gRPC service handlers should return an error created by this package

This is all good, but it makes it unnecessarily hard for the implementation to be correct. It's quite easy to accidentally return just `err` and have absolute no guarantees that the underlying type is indeed a `*status.Status`. This becomes increasingly difficult to check as the code base grows.

### Proposed Solution

An option to generate a server interface that expects `*status.Status` instead of `error` as its return type.

### Alternatives Considered

Instead of changing the generation of grpc-go (optionally), we can of course generate another interface + the translation layer (which is trivial) outside of grpc-go. That should be relatively straightforward but also potentially unnecessary if others agree.

Another way I thought about this is to attach a top-level error handler that transforms errors from the application into the appropriate grpc errors. That should be possible theoretically, but its hard to remain correct as well as the top-level often lacks useful context of the error and it's impossible to guarantee completeness of the handler.

**Comment by arjan-bal** [comment]
The Go Language encourages not using concrete error types as return values in exported functions, [see FAQ](https://go.dev/doc/faq#nil_error):
> It’s a good idea for functions that return errors always to use the error type in their signature (as we did above) rather than a concrete type such as *MyError, to help guarantee the error is created correctly. As an example, [os.Open](https://go.dev/pkg/os/#Open) returns an error even though, if not nil, it’s always of concrete type [*os.PathError](https://go.dev/pkg/os/#PathError).

So, returning a `*status.Code` would not be idiomatic in Go. We also don't want to support an option that makes declaring service handlers different depending on how the option is set.  Such an option would cause fragmentation in the ecosystem and maintaining it wouldn't be worth it.
