### ISSUE TITLE
Can make default/initial Window Size configurable ?

### ISSUE THREAD

**Issue by thundercw** [grpc/grpc-go#760]
We use etcd-raft to build a distributed logging system, the remote node due to network delays are always behind other nodes. In order to catch up, the logs will be batched before sending. This will lead to a large data packet (about 1M) and send speed is very slowly;
I have tried to increase defaultWindowSize to 2M, it is significantly faster;

**Comment by iamqizhao** [comment]
Yes, we will expose the hooks to configure that but we have not setup an ETA for that now. Will ping this back once we sort out the plan.

**Comment by runeaune** [comment]
This is biting me too; and I'm seeing 20-30x higher throughput when increasing `defaultWindowSize`. Could this be put in `ConnectOptions`? It seems that mismatch between client and server has the potential to cause breakage, do you have any ideas how to avoid that other than making sure they have it set to the same?

**Comment by xiang90** [comment]
@runeaune 

What does your workload look like? A lot of small payload? Or very large payload?

**Comment by runeaune** [comment]
Mostly large workloads (can be several MB in each RPC). The benefit of increased window increases with the size of the workload. And obviously with increasing latency.

**Comment by hsaliak** [comment]
#1210  should solve this. We also have #1073 in flight which should help with large messages throughput.  
/cc @MakMukhi @apolcyn 
Can you try the API introduced in #1210 and let us know if it helps? 
If the issue still exists, it would be super useful for us to get pointers to benchmarks that can help us identify the problem.

**Comment by runeaune** [comment]
Some cursory testing on the current `master` version seems to indicate that the problem has been solved, even without setting a larger initial window size (my tests can't detect a difference). Could it be that there was an issue with the automatic adjustment of the window in the older version (the setting has `initial` in its name for a reason I presume)?

That said, my test isn't directed specifically at GRPC, it just happens to send large payloads over high-latency links.

**Comment by dfawley** [comment]
> Could it be that there was an issue with the automatic adjustment of the window in the older version
> (the setting has initial in its name for a reason I presume)?

Without #1073 (now #1248), there is no automatic window size adjustment in grpc-go.  The "initial" name was chosen in anticipation of this new feature.  So you will probably want to either use that feature or wait for #1248 to land soon.

Window sizes are now configurable with #1210, so I think we can close this and continue any other network performance discussions in other issues.

**Comment by hsaliak** [comment]
@dfawley that works for me, closing this issue.
