### ISSUE TITLE
Where are the v1.66.1 release notes?

### ISSUE THREAD

**Issue by rootulp** [grpc/grpc-go#7608]
## Context

I'm trying to review this PR: https://github.com/celestiaorg/celestia-app/pull/3852

## Problem

I don't know what is new in v1.66.1 because I can't find release notes for it. The last release I can see is https://github.com/grpc/grpc-go/releases/tag/v1.66.0

The diff seems insignificant to me: https://github.com/grpc/grpc-go/compare/v1.66.0...v1.66.1 so maybe it was intentional to not create an official release for it? 

## Proposal

1. Create a release for v1.66.1 with release notes

**Comment by purnesh42H** [comment]
yeah 1.66.1 is a patch release we are planning. It hasn't been published yet. I have deleted the tag for now. Will re-publish once everything is ready.

**Comment by purnesh42H** [comment]
1.66.2 is published https://github.com/grpc/grpc-go/releases/tag/v1.66.2 and we don't retraction since it is just the exact same as v1.66.0 except for the user agent string
