### ISSUE TITLE
Receiving INTERNAL (13) error with no description on RPC Call.

### ISSUE THREAD

**Issue by AmandaCameron** [grpc/grpc-go#761]
I'm not sure what's causing this, however near as I can tell the RPC is  never happening on the server's end, and on the client's end I'm getting back `rpc error: code = 13 desc =`. The server also isn't setup to actually return this error code from my code.

I'm not sure what could be causing this, and the fact there's no error description attached is leaving me confused.

**Comment by ejona86** [comment]
The library should guarantee that it doesn't generate empty messages (empty messages from the server are "okay"). I did a quick look and found multiple places where it appeared empty descriptions were used.

**Comment by AmandaCameron** [comment]
While looking around the grpc-go code that raises codes.Internal, I noticed that one of them was a RST packet, which can be sent during the header parsing stage on the server. It appears that my metadata containing an empty string as one of the matadata values is causing issues with the grpc server, causing it to send a RST which is causing the empty codes.Internal error.

**Comment by iamqizhao** [comment]
@AmandaCameron Yes, exactly. We can probably add something like "server reset the rpc" into the error description.

**Comment by AmandaCameron** [comment]
I'd say ideally I should be getting an error somewhere other than the RPC call itself when I'm trying to add an invalid header to the call, but I'm not sure where that should be or go.
