### ISSUE TITLE
google.golang.org/grpc v1.66.1 is missing a retraction

### ISSUE THREAD

**Issue by mx-psi** [grpc/grpc-go#7618]
The v1.66.1 tag is available on the [pkg.go.dev docs domain](https://pkg.go.dev/google.golang.org/grpc@v1.66.1) and the official Go proxy (download [here](https://proxy.golang.org/google.golang.org/grpc/@v/v1.66.1.zip), sumdb entry [here](https://sum.golang.org/lookup/google.golang.org/grpc@v1.66.1)), but it looks like the tag has been removed from this repository.

This breaks build for anyone that is not using the official Go proxy and is building a module that has v1.66.1 on their dependency tree, it breaks automatic dependency tools like Dependabot and it breaks even people pinning commits if their pseudoversion has v1.66.1 as the base version. **Would it be possible for this tag to be re-added to the repository to avoid this breakage?** Thanks!

Similar issues on other projects for context:
- ionos-cloud/sdk-go/issues/27
- DataDog/agent-payload/issues/218
- go-chi/chi/issues/713
- openshift/api/issues/1661
- redis/go-redis/issues/3057

As mentioned on this comment https://github.com/grpc/grpc-go/issues/7608#issuecomment-2340624446 the correct approach is to `retract` the version but keep the tag available.

**Comment by dfawley** [comment]
Sorry for the trouble.  I have re-added the tag for 1.66.1.  There is nothing in this release, but v1.66.2 should be released later today with some bug fixes.

**Comment by mx-psi** [comment]
Thank you! :pray: Would be great if `v1.66.2` [retracts](https://go.dev/ref/mod#go-mod-file-retract) `v1.66.1` as well :)

**Comment by dfawley** [comment]
@mx-psi - I don't believe it's important to do a retraction here, since the v1.66.1 version is "fine" -- it reflects the proper version number in the user agent string, and it contains no regressions or unintended code.  It is just the exact same as v1.66.0 except for the user agent string.

**Comment by mx-psi** [comment]
Thanks for clarifying :+1: that makes sense, I agree it can be kept as is then :)
