### ISSUE TITLE
please update  golang/protobuf 's ProtoPackageIsVersion to 3!

### ISSUE THREAD

**Issue by sunwangme** [grpc/grpc-go#763]
rt.

**Comment by menghanl** [comment]
Can you elaborate on what you mean here?
`ProtoPackageIsVersion` is generated by `golang/protobuf`, and should not be modified manually.
As far as I know, they didn't bump this version recently. Did I miss something?

**Comment by puellanivis** [comment]
https://github.com/golang/protobuf/blob/master/proto/lib.go#L892

Current ProtoPackageIsVersionN is 2.

ProtoPackageIsVersion3 does not exist.

As such, there is no reason to up any of the “ProtoPackageIsVersion*” anywhere in grpc to three.

**Comment by onlyjob** [comment]
IMHO it should wait till _protobuf_ v3 is released: https://github.com/google/protobuf/releases

**Comment by sunwangme** [comment]
the latest code，ProtoPackageIsVersion3 in    https://github.com/grpc/grpc-go/blob/master/    rpc_util.go，but ProtoPackageIsVersion2 in protobuf-codegen。

fail to compile grpc-go。

**Comment by iamqizhao** [comment]
They are two different things -- one is to track the version of the generated code of grpc; the other is for protobuf itself.

**Comment by menghanl** [comment]
@onlyjob `ProtoPackageIsVersion` is golang proto lib version, not the proto compiler version.

@sunwangme I believe the version you saw in `rpc_util.go` is `SupportPackageIsVersion3` for gRPC generated code, not `ProtoPackageIsVersion3`. 
If the code doesn't compile, please do an update and recompile your proto.
`go get -u github.com/golang/protobuf/{proto,protoc-gen-go}`

**Comment by puellanivis** [comment]
Indeed, as I understand the use case, grpc will reference ProtoPackageIsVersion3 when there is a breaking-change between the protoc generation and grpc. As such, this will ensure that grpc will not compile correctly with an outdated {proto,protoc-gen-go}

It's ALMOST basically like a shared token to ensure that a change that must be done synchronously between {grpc-go,proto,protoc-gen-go} MUST happen synchronously… after all, otherwise the code would refuse to compile.

So if someone runs a go get -u grpc-go, but also need a {proto,protoc-gen-go} the code won't silently continue to compile.

**Comment by sunwangme** [comment]
still fail to compile, i update grpc-go proto protoc-gen-go to lastest!

https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go:65
const generatedCodeVersion = 2

https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go:1181
		g.P("const _ = ", g.Pkg["proto"], ".ProtoPackageIsVersion", generatedCodeVersion, " // please upgrade the proto package")

**Comment by menghanl** [comment]
Did you recompile your proto files after update?
Can you post the error message you got?

**Comment by zellyn** [comment]
It's a little confusing, because that comment is trying to give you a hint, if you end up looking there because of breakage, that you need to upgrade the _other_thing - `github.com/golang/protobuf/proto`, not the file that the comment is actually in.
