### ISSUE TITLE
More resolvers to support third-party registry

### ISSUE THREAD

**Issue by EndlessSeeker** [grpc/grpc-go#7649]
In microservices scenario, in addition to directly accessing services through domain names or k8s svc, they are usually called base on the third-party registration center.
In grpc-go, the appropriate way is to implement a self-defined resolver, the resovler monitor the node updates in the registration center and update the connections.
However, there seems to be no official implementation currently provided. Developers can only develop independently. Can we provide a official plugin library, and the library includes some extension implementations such as resolvers supporting third-party registry? In this way, it improves the convenience for developers to use like me

**Comment by easwars** [comment]
gRPC supports a way to implement custom resolvers. The API is defined in this file here: https://github.com/grpc/grpc-go/blob/ac41314504cbacaf5e7de2c6c205a393fdac7a00/resolver/resolver.go#L314

The team does not have the time or expertise to implement an official resolver for the use-case that you are asking. But if you want to implement it, please send us a detailed proposal. We can have a discussion and then move towards an implementation.
