### ISSUE TITLE
Allow per service codecs

### ISSUE THREAD

**Issue by bsideup** [grpc/grpc-go#7659]
### Use case(s) - what problem will this feature solve?

https://github.com/grpc/grpc/issues/36765
https://github.com/grpc/grpc/issues/36766

And concretely:
https://github.com/grpc/grpc/issues/14101#issuecomment-2366814417

### Proposed Solution

Add an optional `Codec` field to `ServiceDesc`, similar to how it is done in grpc-java. _Maybe_ also allow overriding it per `MethodDesc`/`StreamDesc`.

### Alternatives Considered

sub-type but it is not implemented anywhere but in Go

### Additional Context

https://github.com/bsideup/grpc-bidi/tree/main/go (allows calling services on the client via a reverse tunnel) is optimized to use the raw bytes from the wire, but, to provide the codec, the user **must** register it and **must** set the sub-type, meaning that currently it will only work with gRPC clients that are sub-type aware (Only Go, to the best of my knowledge).

Note that grpc-java's server does not have this problem because it requires the codecs to be specified by method:
https://github.com/bsideup/grpc-bidi/blob/7f4900bd97642f9d6c2e6bc71819b0140a448119/java/src/main/java/io/grpc/bidi/ClientChannelService.java#L29

**Comment by purnesh42H** [comment]
Thanks @bsideup for the proposal. We will discuss with other maintainers and get back.

**Comment by purnesh42H** [comment]
@bsideup could you take a look at [ForceServerCodec](https://github.com/grpc/grpc-go/blob/ca4865d6dd6f3d8b77f1943ccfd6c9e78223912d/server.go#L344). 

This function is provided for advanced users; prefer to register codecs using encoding.RegisterCodec. The server will automatically use registered codecs based on the incoming requests' headers. See also https://github.com/grpc/grpc-go/blob/master/Documentation/encoding.md#using-a-codec.

do you actually need different codecs per-service, but not per-server?

**Comment by bsideup** [comment]
Hi @purnesh42H,

I know the function but doesn't it force the codec for every server handler? While the problem at hand is being able to force the codec for one particular one.

`encoding.RegisterCodec` requires the client to provide the subtype (as per the issue) which is not supported widely and did not seem to make it to the spec.

**Comment by purnesh42H** [comment]
Yes, [ForceServerCodec](https://github.com/grpc/grpc-go/blob/ca4865d6dd6f3d8b77f1943ccfd6c9e78223912d/server.go#L344) applies to the entire server and wouldn't allow you to specify different codecs for different services. Could you share some more details about why you need to use different codecs for different services? This will help us understand if this is something that might be useful for the wider gRPC community.

Regarding the issue(s) of sub-type, it's important to have a consistent approach across all gRPC implementations, and we want to ensure any changes we make in Go align with the broader direction of gRPC.
