### ISSUE TITLE
Performance issue with recent changes

### ISSUE THREAD

**Issue by gyuho** [grpc/grpc-go#771]
First reported at https://github.com/coreos/etcd/issues/6010.

Recently we changed our grpc-go dependency here https://github.com/coreos/etcd/pull/5948. And exact commit (changes in grpc) is https://github.com/coreos/etcd/pull/5948/commits/d9a8a326dfe4691cf90d2c4d2674e3602de812d8. Read query performance dropped from 95K to 48K (almost 2 times slower). Performance numbers are:

<br>

https://github.com/coreos/etcd/commit/07ed4da2ffe871444c83be63e508d2adf4c87175

```
$ benchmark --endpoints=${IP_1},${IP_2},${IP_3} --conns=100 --clients=1000 range aaaaaaaa --consistency=s --total=100000
bench with serializable range
 100000 / 100000 Boooooooooooooooooooooooooooooooooooooooooooooooo! 100.00%1s

Summary:
  Total:    1.0602 secs.
  Slowest:  0.0742 secs.
  Fastest:  0.0003 secs.
  Average:  0.0069 secs.
  Stddev:   0.0061 secs.
  Requests/sec: 94323.9382

Response time histogram:
  0.000 [1] |
  0.008 [65910] |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.015 [26302] |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.022 [5257]  |∎∎∎
  0.030 [1173]  |
  0.037 [983]   |
  0.045 [220]   |
  0.052 [59]    |
  0.059 [80]    |
  0.067 [12]    |
  0.074 [3] |

Latency distribution:
  10% in 0.0015 secs.
  25% in 0.0028 secs.
  50% in 0.0052 secs.
  75% in 0.0094 secs.
  90% in 0.0137 secs.
  95% in 0.0177 secs.
  99% in 0.0340 secs.
```

<br>

https://github.com/coreos/etcd/commit/d9a8a326dfe4691cf90d2c4d2674e3602de812d8

```
$ benchmark --endpoints=${IP_1},${IP_2},${IP_3} --conns=100 --clients=1000 range aaaaaaaa --consistency=s --total=100000
bench with serializable range
 100000 / 100000 Boooooooooooooooooooooooooooooooooooooooooooooooo! 100.00%2s

Summary:
  Total:    2.0064 secs.
  Slowest:  0.2937 secs.
  Fastest:  0.0003 secs.
  Average:  0.0196 secs.
  Stddev:   0.0248 secs.
  Requests/sec: 49841.3578

Response time histogram:
  0.000 [1] |
  0.030 [78888] |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.059 [13889] |∎∎∎∎∎∎∎
  0.088 [5035]  |∎∎
  0.118 [1551]  |
  0.147 [448]   |
  0.176 [126]   |
  0.206 [40]    |
  0.235 [16]    |
  0.264 [4] |
  0.294 [2] |

Latency distribution:
  10% in 0.0004 secs.
  25% in 0.0005 secs.
  50% in 0.0174 secs.
  75% in 0.0267 secs.
  90% in 0.0507 secs.
  95% in 0.0687 secs.
  99% in 0.1079 secs.
```

You can see the commit that introduced new grpc dependency has slower performance.

Could anybody take a look?

Please let me know if you need more information.

/cc @xiang90 @heyitsanthony

**Comment by xiang90** [comment]
@iamqizhao This is a pretty significant performance regression for us. It would be great if you can take a look. Also do we have any documentation around running grpc benchmark tool?

**Comment by iamqizhao** [comment]
I do not see anything on our performance dashboard (https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5760820306771968). Do you have any etcd side changes along with this?

**Comment by iamqizhao** [comment]
That benchmark we use is at https://github.com/grpc/grpc-go/tree/master/benchmark/worker. menghanl@, can you provide the instruction to run them locally?

**Comment by gyuho** [comment]
https://github.com/coreos/etcd/commit/07ed4da2ffe871444c83be63e508d2adf4c87175 with 95K is the direct parent commit of https://github.com/coreos/etcd/commit/d9a8a326dfe4691cf90d2c4d2674e3602de812d8 with 48K. So I think etcd doesn't have any other change.

**Comment by iamqizhao** [comment]
Do you use custom name resolver or load balancer?

**Comment by iamqizhao** [comment]
The only thing suspicious to me is the change of the round-robin load balancer -- to make it fit for fail-fast we added a bit memory alloc and copy. I do not expect it introduce any visible performance impact though (as shown in our perf dashboard). It might be possible your benchmark scenario runs into some cases to enlarge the impact of theses mem alloc and copy significantly. Let me see if I can improve the impl of round-robin balancer.

**Comment by xiang90** [comment]
@iamqizhao We will do more investigation tomorrow. We will let you know the result. Probably you can hold off the optimization for now.

**Comment by iamqizhao** [comment]
sounds good. Thank you.

**Comment by gyuho** [comment]
@menghanl Is there any instruction to run grpc benchmark? By the way, we are developing in Google Cloud Platform as well.

Thanks.

**Comment by gyuho** [comment]
Ok, will try that. Thanks!

**Comment by menghanl** [comment]
@gyuho I just ran the local benchmark and the benchmark as in [dashboard](https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5760820306771968), and didn't see any performance regression. Please keep us posted if you find anything suspicious.

**Comment by menghanl** [comment]
If you want to run benchmark using `benchmark/worker`, please try the following steps:
```
mkdir test
cd test
git clone https://github.com/grpc/grpc-go
git clone https://github.com/grpc/grpc
cd grpc
git submodule update --init
make grpc_cpp_plugin
tools/run_tests/run_performance_tests.py -l go
```

The `grpc-go` in dir `test/grpc-go` will be used to run the benchmark, not the one in your `$GOPATH`. So changes should be made to `test/grpc-go` if you want to run benchmark on different versions of grpc-go.

**Comment by menghanl** [comment]
@gyuho Any update on this issue?

**Comment by xiang90** [comment]
@menghanl We found it is probably a compiler related issue. We are not sure how this change (changing error from struct to pointer) triggered it. Probably we should report to go upstream.

**Comment by iamqizhao** [comment]
We probably should. We also found some performance regression from 1.6 to 1.7 in some internal benchmarks.

**Comment by xiang90** [comment]
@iamqizhao Yes. The regression was from 1.6.3,, 1.7. The performance dropped 50% or so for no reason other than updating Go. We changed some code around the rpc path (like reverting the error pointer change or adding some random printf in the unreachable code path). And magically, we got the performance back... So we do not really understand why. We have not dig into the root cause.
