### ISSUE TITLE
Proposal: Allow Clients to Receive GOAWAY Notifications via CallOption

### ISSUE THREAD

**Issue by ktalg** [grpc/grpc-go#7750]
### Use case(s) - what problem will this feature solve?

In scenarios involving long-lasting bidirectional streaming, the server's current graceful shutdown implementation waits indefinitely. Although a GOAWAY message is sent to the client, this message is not directly available at the application layer. This limitation forces server-side developers to implement additional mechanisms for notifying the client about server shutdown, leading to complexity and lack of elegance.

For instance, current approaches may involve:
1. Returning before the `GracefulStop`, which forfeits "gracefulness."
2. Modifying the protocol to include a specific "shutdown notice" before `GracefulStop`, which adds unnecessary complexity.

### Proposed Solution

I am preparing to submit a PR that adds a `CallOption` parameter allowing clients to receive GOAWAY notifications through a channel. This feature could use the existing GOAWAY message, and the client, upon starting a new stream, would be able to receive these notifications easily.

### Additional Context

Here is an example usage of the proposed solution:
```go
ctx, cancel := context.WithCancel(context.Background())
ConnClosingChan := make(chan struct{})
stream, err := client.Invoke(ctx, grpc.ConnClosing(ConnClosingChan)) // <- capture GOAWAY event notificationt
if err != nil {
    log.Fatalf("Failed to invoke stream: %v", err)
}

go func() {
    <-ConnClosingChan
    log.Println("Connection closing")
    // Do some cleanup work before ending the stream...
    cancel()
}()
// Use stream...

```

**Comment by aranjans** [comment]
@ktalg Introducing a CallOption for GOAWAY notifications would simplify client-side handling of server shutdowns, especially in long-lived streaming connections, asynchronous mechanism to react to server-initiated connection closures. This reduces the need for complex manual workarounds, improving resource management and also client responsiveness. But there is a problem there in case user is having proxy layer which has further bunch of backend server. In such scenario, passing a notification channel won't work and that is why we hadn't implemented it so far.
