### ISSUE TITLE
In picker logic(picker_wrapper.go), add possibility of wrapping returned error

### ISSUE THREAD

**Issue by nezhibitskiy** [grpc/grpc-go#7770]
Hi!

In picker wrapper logic in case, when no one subconnection is unavailable, wrapper waits, until channel changes state.
https://github.com/grpc/grpc-go/blob/4bb0170ac65f2726d593eb7364a807b171fa1d63/picker_wrapper.go#L158

I have my own wrapping of picker, which adds additional logic of choosing subchannel, based on request context (different versions of one application). I'd like to wrap returned error ErrNoSubConnAvailable with additional information (used version of appilcation). But strong equality of errors in picker wrapper makes it impossible. Is it possible to change this error check to smth like this:
```go
if errors.Is(err, balancer.ErrNoSubConnAvailable) {
    continue
}
```

**Comment by aranjans** [comment]
@nezhibitskiy Could you answer the below questions:

- How are you determining the "application version" from the request context? Is it a custom header?
- What is the purpose of including the application version in the error?
- Can you elaborate on your custom picker wrapper logic and how it uses the application version?
- Can you provide a concrete example of a scenario where wrapping the error with the application version is essential?

**Comment by aranjans** [comment]
@nezhibitskiy How are you determining the version of the backend in the LB policy?

**Comment by nezhibitskiy** [comment]
@aranjans resolver pass information to balancer and picker via attributes field in `resolver.State` struct

**Comment by aranjans** [comment]
@nezhibitskiy Use case of having hidden information of a service to be added in grpc library error message is not recommended. Here, no sub-conn means no address available for a particular service, and that is all what lb policy needs to know.

**Comment by nezhibitskiy** [comment]
@aranjans definitely, if error is only used in lb policy mechanisms and not returned to userspace. But this error returns when gRPC call is occurred. And now this strong equality between errors is limiting usage of gRPC mechanisms. Especially if you take into account the ideology of error handling in Go, which recommends using `errors.Is` in comparing errors. Of course, it's up to you to decide, which way is best in this case, but it's seems, that userspace errors should be able to deliver more information, than only lb policy requires.

**Comment by purnesh42H** [comment]
@nezhibitskiy have you written your own custom load balancer? Why did you have to write your own pick wrapper? could you share the code for that? Thanks
