### ISSUE TITLE
Deprecate `stats` package trace methods

### ISSUE THREAD

**Issue by purnesh42H** [grpc/grpc-go#7836]
Due to https://opentelemetry.io/blog/2023/sunsetting-opencensus, we need to migrate the gRPC instrumentation to OpenTelemetry while still supporting OpenCensus until everyone migrates to OpenTelemetry which has the identical trace context format but is injected/extracted directly to/from metadata.

Considering that `grpc-trace-bin` is not a reserved header, both OpenCensus and OpenTelemetry can be allowed to directly set/get traces to/from metadata and we can mark the trace methods of `stats` package deprecated and recommend to use the metadata directly. While marking it deprecated, we can modify them to use the metadata directly for consistency.

Open Questions
- Should we remove all usages of trace methods of `stats` packages? or keep using them internally for now in opencensus and tests
- What about tags methods? Should they be deprecated as well as `grpc-tags-bin`

**Comment by purnesh42H** [comment]
@dfawley

**Comment by dfawley** [comment]
> Should we remove all usages of trace methods of stats packages? or keep using them internally for now in opencensus and tests

Yes, we should stop calling it entirely.

> What about tags methods? Should they be deprecated as well as grpc-tags-bin

Yes, that too.
