### ISSUE TITLE
EOF not probably handled in http2_server

### ISSUE THREAD

**Issue by cube2222** [grpc/grpc-go#786]
Go version: 1.7rc2-3

The server ends up writing:
```
transport: http2Server.HandleStreams failed to read frame: EOF
```
after each processed request. Even though everything is working correctly.
The cause is here:
https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L241
https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L256

How it is being done in the standard lib:
https://github.com/golang/net/blob/6a513affb38dc9788b449d59ffed099b8de18fa0/http2/server.go#L1023

Reproduction:
https://github.com/cube2222/grpcRepro

**Comment by dpiddy** [comment]
Fixed by https://github.com/grpc/grpc-go/pull/787
