### ISSUE TITLE
Please regularly tag new releases

### ISSUE THREAD

**Issue by lucab** [grpc/grpc-go#788]
It looks like several bugfixes have piled up since 1.0.0. As an example, etcd vendored dependency has been updated to include https://github.com/grpc/grpc-go/pull/756. This now induces other projects to update as well, otherwise common consumers will break similarly to kubernetes in https://github.com/kubernetes/kubernetes/pull/29399#issuecomment-234648879.

Could you please regularly tag new releases, at least for those important bugfixes? That would make the whole process of synch-ing grpc-go dependency across projects much more smooth.

**Comment by iamqizhao** [comment]
Yes, we will do. Sorry about that. We made a mistake at that time and cannot roll it back.

**Comment by gdm85** [comment]
Dup of #562.
