### ISSUE TITLE
goroutine deadlock.

### ISSUE THREAD

**Issue by zhiyunliu** [grpc/grpc-go#7880]
Today I encountered a strange issue where my gRPC call resulted in a goroutine deadlock. However, this is not a common problem. The specific stack trace is as follows. My gRPC version is v1.60.1 and my Go version is v1.21.12.

![image](https://github.com/user-attachments/assets/0cd55c8b-b3e9-49f2-aa6b-e0e926d60c78)

**Comment by aranjans** [comment]
Thanks @zhiyunliu for reporting this. We are looking into this and will update soon!

**Comment by zhiyunliu** [comment]
I have traced the blocking goroutine to the following location. Please confirm if it is this location.
---------
1 @ 0x44726e 0x41252d 0x412132 0x1018e4f 0x1018af3 0xfc77ea 0xfc76c7 0x47a8e1
#	0x1018e4e	google.golang.org/grpc.(*ClientConn).enterIdleMode+0xee			/root/go/pkg/mod/google.golang.org/grpc@v1.60.1/clientconn.go:376
#	0x1018af2	google.golang.org/grpc.(*idler).EnterIdleMode+0x12			/root/go/pkg/mod/google.golang.org/grpc@v1.60.1/clientconn.go:310
#	0xfc77e9	google.golang.org/grpc/internal/idle.(*Manager).tryEnterIdleMode+0xc9	/root/go/pkg/mod/google.golang.org/grpc@v1.60.1/internal/idle/idle.go:180
#	0xfc76c6	google.golang.org/grpc/internal/idle.(*Manager).handleIdleTimeout+0xc6	/root/go/pkg/mod/google.golang.org/grpc@v1.60.1/internal/idle/idle.go:130

**Comment by zhiyunliu** [comment]
This is my full stack information.
[fullstack.txt](https://github.com/user-attachments/files/17956110/fullstack.txt)

**Comment by arjan-bal** [comment]
I suspect the lock is held by this goroutine
```
1 @ 0x44726e 0x41252d 0x412132 0x1018e4f 0x1018af3 0xfc77ea 0xfc76c7 0x47a8e1
#	0x1018e4e	google.golang.org/grpc.(*ClientConn).enterIdleMode+0xee			/root/go/pkg/mod/google.golang.org/grpc@v1.60.1/clientconn.go:376
#	0x1018af2	google.golang.org/grpc.(*idler).EnterIdleMode+0x12			/root/go/pkg/mod/google.golang.org/grpc@v1.60.1/clientconn.go:310
#	0xfc77e9	google.golang.org/grpc/internal/idle.(*Manager).tryEnterIdleMode+0xc9	/root/go/pkg/mod/google.golang.org/grpc@v1.60.1/internal/idle/idle.go:180
#	0xfc76c6	google.golang.org/grpc/internal/idle.(*Manager).handleIdleTimeout+0xc6	/root/go/pkg/mod/google.golang.org/grpc@v1.60.1/internal/idle/idle.go:130
```
The lock is acquired in this code: https://github.com/grpc/grpc-go/blob/49ecf7a5a1b4d837cfcc09531dc16bde399599e3/internal/idle/idle.go#L148-L162

The goroutine is stuck at this line after acquiring the lock: https://github.com/grpc/grpc-go/blob/49ecf7a5a1b4d837cfcc09531dc16bde399599e3/clientconn.go#L376

This is the goroutine waiting on the resolver to be closed:
```
1 @ 0x44726e 0x4587b8 0x45878f 0x4767c5 0x497548 0xfc2279 0x102484a 0xfc5df8 0x47a8e1
#	0x4767c4	sync.runtime_Semacquire+0x24								/usr/local/go121/src/runtime/sema.go:62
#	0x497547	sync.(*WaitGroup).Wait+0x47								/usr/local/go121/src/sync/waitgroup.go:116
#	0xfc2278	github.com/zhiyunliu/glue/contrib/xrpc/grpc/balancer.(*registrarResolver).Close+0x18	/root/go/pkg/mod/github.com/zhiyunliu/glue@v0.5.23/contrib/xrpc/grpc/balancer/resolver.go:33
#	0x1024849	google.golang.org/grpc.(*ccResolverWrapper).close.func1+0x29				/root/go/pkg/mod/google.golang.org/grpc@v1.60.1/resolver_wrapper.go:108
#	0xfc5df7	google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run+0x177		/root/go/pkg/mod/google.golang.org/grpc@v1.60.1/internal/grpcsync/callback_serializer.go:82
```

This is the line that is waiting on a `WaitGroup`: 
```
#	0xfc2278	github.com/zhiyunliu/glue/contrib/xrpc/grpc/balancer.(*registrarResolver).Close+0x18	/root/go/pkg/mod/github.com/zhiyunliu/glue@v0.5.23/contrib/xrpc/grpc/balancer/resolver.go:33
```
This seems like a custom resolver, so I'm not digging deeper into this code. @zhiyunliu is looks like gRPC is waiting for the `registrarResolver` to close which is causing the deadlock that you're seeing.

**Comment by zhiyunliu** [comment]
Yes, in my custom registrarResolver, the Close method uses a WaitGroup to wait for my resolver to exit. Therefore, I want to understand under which scenarios the Resolver would trigger a close.

**Comment by arjan-bal** [comment]
There are two conditions when the resolver is closed:
1. The channel, known as `ClientConn` is closed, or
2. The `ClientConn enters` `Idle` state. This is controlled by the Load Balancing Policy. For example, the default LB policy `pick-first` puts the ClientConn in `Idle` when the active transport to the backend fails.

**Comment by zhiyunliu** [comment]
OK, then I understand the specific issue. My Resolver did not handle the situation when ClientConn enters the Idle state. Thank you very much!

**Comment by arjan-bal** [comment]
Happy to help!
