### ISSUE TITLE
http2Client.notifyError every 4 minutes when using gcd

### ISSUE THREAD

**Issue by nvartolomei** [grpc/grpc-go#798]
Can someone take a look at the following issue? https://github.com/GoogleCloudPlatform/gcloud-golang/issues/293

Thanks.

**Comment by iamqizhao** [comment]
I think it is because GFE closes the connection every 4 minute. On grpc-go side, we do need to improve logging and reduce logging spamming.

**Comment by iamqizhao** [comment]
dup of #120. closed.
