### ISSUE TITLE
Multiple encoding support

### ISSUE THREAD

**Issue by mwitkow** [grpc/grpc-go#803]
It seems that the [gRPC wire protocol description](http://www.grpc.io/docs/guides/wire.html#requests)  provides a way of specifying what `Content-Type` is used (e.g. `application/grpc+proto`, `application/grpc+json`). It would be great if `CustomCodec` option on the server tool multiple codecs and the choice of which one is used was made by parsing the part after `+`.

**Comment by mwitkow** [comment]
Would happily provide a patch, but want to make sure this was acceptable :)

**Comment by iamqizhao** [comment]
It sounds good but my concern is that this adds some overhead to every single rpc and slow them down.

**Comment by mwitkow** [comment]
What if it was opt in? I.e. by default we use the single `Codec()` if exactly `application/grpc` was used (without the `+` part).

By default all implementations already do a check on the [`validContentType`](https://github.com/grpc/grpc-go/blob/0e0265f78b7758cad2fcd2731bb1e08fd5fc7a90/transport/http_util.go#L148). 
Extending that code point to add an optional substring past `+` (if it existed) shouldn't be a performance problem for typical case. Then you just take the extra content type and put it in `Stream` and do a `if != ""` check before doing any codec lookups.

The performance impact would be totally opt-in :)

**Comment by mwitkow** [comment]
I can hack something together over the weekend. Are there any pointers as to how to run the benchmarks? :)

**Comment by menghanl** [comment]
We have local benchmarks in `benchmark/benchmark_test.go`. Run them by `go test -bench=.`

More benchmarks can be run using `benchmark/worker`, please refer to the comments here for how to run them: https://github.com/grpc/grpc-go/issues/771#issuecomment-234400243

**Comment by nizsheanez** [comment]
Hello. Do you have any update on it? Can we help?

**Comment by mwitkow** [comment]
Got a half-broken branch somewhere. However, it's problably worhtwhile syncing with the efforts in:
https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md

@wenbozhu thoughts?

**Comment by wenbozhu** [comment]
@mwitkow  Not quite, grpc-web addresses the wire encoding of grpc frames, not the encoding of the payload of grpc frames.

**Comment by mwitkow** [comment]
Indeed, but the spec allows you to specify an Accept header that specifies
encoding (json or PB). I assume the underlying grpc library would need to
chose the respective marshaller before putting it down to the framing
layer.

**Comment by peter-edge** [comment]
I'd like to put something together for this if there is still interest. We're running into wanting this in https://github.com/yarpc/yarpc-go/issues/911 where an exposed transport (such as grpc) needs to handle multiple inbound encodings, and our choices are to do grpc at a lower level (not use large portions of grpc-go) or to get this added. We want to add as few custom headers as possible for our usage of grpc.

**Comment by hsaliak** [comment]
If there is still interest, this might be a good item to write [a short proposal for](https://github.com/grpc/proposal) and discuss with the community.

**Comment by peter-edge** [comment]
I've put together a PR for this, we're discussing it there as of now, this seems like a grpc-go specific issue - grpc as a protocol supports multiple encodings, we just should implement it I think.

**Comment by hsaliak** [comment]
@peter-edge sounds good, took a look at #1203, as it looks like we are converging on a solution, lets just stay the course and close this issue out.
