### ISSUE TITLE
Classic appengine server support

### ISSUE THREAD

**Issue by nodirt** [grpc/grpc-go#805]
Filing this bug to track classic appengine server support in grpc go.

Related issue: #216

**Comment by mwitkow** [comment]
@nodirt does classic AppEngine do HTTP2 now? :)

**Comment by nodirt** [comment]
@mwitkow not at this time

**Comment by atishpatel** [comment]
Does this imply it's possible to do grpc with golang with an App Engine Flexible env? If so, does anyone have a link to a project with grpc and App Engine Flexible?

**Comment by atishpatel** [comment]
For anyone looking for a workaround to do grpc on appengine until app engine adds http2: https://github.com/salrashid123/gcegrpc

**Comment by tjerkw** [comment]
A function that basically maps an http1 Request to an http2 Request and an http1 ResponseWriter to an http2 ResponseWriter would solve it for me.

    func ServeHTTP(w ResponseWriter, r *Request) {
        grpcServer.serveHttp(toHttp2ResponseWrite(w), toHttp2Request(r));
    }


Note: I don"t need streaming support. I just want to have faster development by using the grpc IDLS.

**Comment by hsaliak** [comment]
Providing this support depends on the App Engine project and there has been discussions with that team in that regard. 

I am not sure what the gRPC project can do here short of making changes to work around the limitations of the app engine sandbox, which is beyond the scope of the core project.
