### ISSUE TITLE
`FailFast(false)` does not honor context cancellation during transport failures

### ISSUE THREAD

**Issue by tamird** [grpc/grpc-go#815]
In other words if the transport is down during a `FailFast(false)` RPC, the RPC will block indefinitely. See https://github.com/cockroachdb/cockroach/commit/a79b1b9406e83e7a1293cffff24c9918b46084fc.

**Comment by menghanl** [comment]
context cancellation should have been handled here. Maybe we missed some corner case.
Do you have a reproduction for this?

**Comment by tamird** [comment]
Closing in favour of #826 which includes a repro case.
