### ISSUE TITLE
# github.com/test/vendor/google.golang.org/grpc/transport transport/http2_client.go:91: undefined: credentials.PerRPCCredentials

### ISSUE THREAD

**Issue by shangsony** [grpc/grpc-go#838]
# github.com/test/vendor/google.golang.org/grpc/transport

transport/http2_client.go:91: undefined: credentials.PerRPCCredentials

**Comment by shangsony** [comment]
this is build error

**Comment by shangsony** [comment]
in vendor dir build

**Comment by therealplato** [comment]
i ran into this because I updated only the grpc package and not the children packages. try `govendor fetch google.golang.org/grpc/...`

**Comment by shangsony** [comment]
google.golang.org Can not visit in China @therealplato

**Comment by menghanl** [comment]
Not sure what the problem is. If you put the source cloned from github to directory `google.golang.org`, probably some directory is configured my mistake.
Try to reinstall everything from google.golang.org using VPN, and see if that works...

**Comment by iamqizhao** [comment]
google.golang.org is not accessible from China. Please refer to https://github.com/grpc/grpc-go/issues/350 for a workaround using git clone.
