### ISSUE TITLE
What is encoding of string?

### ISSUE THREAD

**Issue by mattn** [grpc/grpc-go#84]
https://github.com/mattn/grpc-example

When passing utf-8 strings as protobuf's string, It can't be decoded as utf-8

![](http://go-gyazo.appspot.com/336e06561d0bba55.png)

Is this problem of grpc-go? or grpc?

**Comment by iamqizhao** [comment]
If you change 

fmt.Println(person)

to

fmt.Println(person.Name)

it works fine. This means fmt.Println does not work well with proto message. gRPC is just fine. I am going to to talk to goprotobuf team to get help.

**Comment by dsymonds** [comment]
Are you sure that's not your terminal setup, @mattn? The protobuf package treats strings as opaque byte sequences. I don't think this has anything to do with fmt.Println or proto messages.

**Comment by iamqizhao** [comment]
Hi David,

Simply on my desktop, I got

person := &pb.Person{
Name: "ほげ",
Age:  int32(1),
}
fmt.Println(person)

output:
name:"\343\201\273\343\201\222" age:1

fmt.Println(person.Name)

output:
ほげ

**Comment by dsymonds** [comment]
`fmt.Println(person)` is rendering the protobuf message in the standardised text format, which specifies using octal escapes for non-ASCII (see https://github.com/golang/protobuf/blob/master/proto/text.go#L476). This is working as intended.

**Comment by mattn** [comment]
http://play.golang.org/p/ENZjynLjV_

Ah, right. protobuf's textWriter seems to avoid to print non-ASCII as @dsymonds says. Should be used `unicode.IsPrint` instead?

**Comment by dsymonds** [comment]
The protobuf package matches the equivalent C++ code already.

**Comment by mattn** [comment]
fair enoguh.
