### ISSUE TITLE
How to detect `grpc.Dial()` connection failure?

### ISSUE THREAD

**Issue by therealplato** [grpc/grpc-go#849]
Hi, I'm upgrading my vendored grpc package from version 2 to version 3. My test started failing:

```
opts := grpc.WithInsecure()
clientConn, err := grpc.Dial("", opts)
assert.Equal(t, errors.New("grpc: target is unspecified"), err)
```

This test used to pass because I'd get an error when dialing an empty string. With current `google.golang.org/grpc` master branch, `err` is nil. I have looked at the grpc.io docs and the godoc.org docs but I can't find any instructions. What is the new method to determine if the connection succeeded?

**Comment by menghanl** [comment]
Can you try dial with block
```go
clientConn, err := grpc.Dial("", grpc.WithInsecure(), grpc.WithBlock())
```

**Comment by therealplato** [comment]
@menghanl This blocked permanently (or at least, much longer than I was comfortable with in a test suite.) I've still got some test failures but they look unrelated to this issue. I ended up with:

```
       clientConn, err := grpc.Dial(
               "",
               grpc.WithInsecure(),
               grpc.WithBlock(),
               grpc.WithTimeout(30*time.Second),
       )
```

**Comment by iamqizhao** [comment]
You seemed work on a very old version of grpc-go. We removed this error when adding Balancer since the Balancer can be used to get addresses even when the target is an empty string. menghanl@ will add some check back to the case (balancer is nil and target is empty string) to fix this.

**Comment by cored** [comment]
@iamqizhao how does the balancer figure out an address with a blank target?

**Comment by iamqizhao** [comment]
In the current code, if balancer is specified, all the name resolution work is taken over by the balancer. For example, we can make a custom balancer which always returns 127.0.0.1 to the grpc internals regardless what the target is for testing purpose. And yes, we can also add the non-empty constraint to Balancer but we do not now.

**Comment by cored** [comment]
@iamqizhao so nothing happens with an empty target because since there's a custom balancer it's defaulting to localhost ?
