### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by rubenv** [grpc/grpc-go#85]
How does grpc handle concurrency? Can I use a client from different threads in parallel?

**Comment by iamqizhao** [comment]
On Fri, Feb 27, 2015 at 9:40 AM, Ruben Vermeersch <notifications@github.com>
wrote:

> How does grpc handle concurrency? Can I use a client from different
> threads in parallel?
>
On client, if you want to perform multiple rpc in parallel, you should
spawn multiple goroutines to do that since the rpc is synchronous/blocking.

**Comment by jpfuentes2** [comment]
> since the rpc is synchronous/blocking

That's what I got from looking at the `route_guide` example: the server's end points access a slice without locks. Is this considered quasi similar to an actor model? Is there documentation about this fact (I might have missed it)?

**Comment by iamqizhao** [comment]
On Fri, Feb 27, 2015 at 11:27 AM, Jacques Fuentes <notifications@github.com>
wrote:

> since the rpc is synchronous/blocking
>
> That's what I got from looking at the route_guide example: the server's
> end points access a slice without locks. Is this considered quasi similar
> to an actor model? Is there documentation about this fact (I might have
> missed it)?
>
To be clear, I was talking about client side. On the server side, each rpc
still has its own goroutine but the concurrency is model is different --
the goroutine is spawned by grpc internals instead of applications.

Were you talking about "savedFeatures" slice? There is no lock for that
because it is read-only once it is initialized (in grpc.NewServer).

**Comment by jpfuentes2** [comment]
> There is no lock for that because it is read-only once it is initialized

Got it, thanks.

**Comment by trevorgray** [comment]
I also wasn't able to find this documented anywhere but this issue. Would you be able to add this to the godoc documentation to make it more clear that it's safe to call a client from multiple go routines concurrently?

**Comment by timbunce** [comment]
Trying to summarize for myself... 

@rubenv asks:
> Can I use a client from different threads in parallel?

@iamqizhao replies:
> On client, if you want to perform multiple rpc in parallel, you should spawn multiple goroutines to do that since the rpc is synchronous/blocking

That's helpful, thanks, but doesn't quite clarify if a _single client object_ can be used by all those "multiple goroutines". It sounds like the answer is yes. This [example](https://talks.golang.org/2015/gotham-grpc.slide#21) suggests the same. Is that right?

However, [a _stream_ can't be shared](https://groups.google.com/forum/#!topic/grpc-io/aI6L6M4fzQ0).

@trevorgray, these kinds of concurrency topics are apparently still not documented, per #682.

**Comment by dfawley** [comment]
> That's helpful, thanks, but doesn't quite clarify if a single client object can be used by all those "multiple goroutines". It sounds like the answer is yes. This example suggests the same. Is that right?
>
> However, a stream can't be shared.

That all sounds right to me.

> @trevorgray, these kinds of concurrency topics are apparently still not documented, per #682.

Documentation is a well-known deficiency that I hope to address sometime this quarter.
