### ISSUE TITLE
SetTrailer should be callable multiple times

### ISSUE THREAD

**Issue by zellyn** [grpc/grpc-go#854]
Making [`SetTrailer`](https://github.com/grpc/grpc-go/blob/0032a855/server.go#L883) callable only once from a unary RPC handler limits the utility of server-side interceptors. Specifically, we would like to be able to add a trailer to return server health on every RPC call, so that the health status can be updated in clients. If we do that now, we have to disallow all other use of trailers by unary RPC handlers.

cc @maniksurtani @jhump @lukaszx0

**Comment by iamqizhao** [comment]
Yes, it appeared before interceptor and has not evolved yet.
