### ISSUE TITLE
Issues with grpc.DialContext

### ISSUE THREAD

**Issue by iamqizhao** [grpc/grpc-go#856]
The comments of net.DialContext emphasizes that

> Once successfully connected, any expiration of the context will not affect the connection.

Currently this is not the case for grpc.DialContext because ClientConn and the underlying addrConn and ClientTransport will keep listening on ctx.Done and the expiration of the context will impact all the following connected connections. 

The context passed in grpc.DialContext should be only applied to the initial connection. After that, the expiration and cancellation on that context should be no-op for grpc internals.

/cc @tamird

**Comment by tamird** [comment]
As I mention on the referenced PR, `grpc.DialContext` is not `net.DialContext`. The proximate reason for adding `grpc.DialContext` was to be able to control the complete shutdown of the `grpc.ClientConn` via context cancellation. In particular, it is important that cancelling the context passed to `grpc.DialContext` terminates the goroutine which attempts to reconnect the `grpc.ClientConn` to its target. Note that `net.DialContext` does not spawn such a goroutine, and thus the semantics can be different.
