### ISSUE TITLE
go get & go run errors

### ISSUE THREAD

**Issue by Helen-Xie** [grpc/grpc-go#865]
When I go get grpc, return this error message: 
````
lin@XYL:~$ go get google.golang.org/grpc
google.golang.org/grpc/transport
go/src/google.golang.org/grpc/transport/handler_server.go:209: undefined: http2.TrailerPrefix
go/src/google.golang.org/grpc/transport/http2_client.go:821: undefined: http2.MetaHeadersFrame
go/src/google.golang.org/grpc/transport/http2_client.go:918: undefined: http2.MetaHeadersFrame
go/src/google.golang.org/grpc/transport/http2_server.go:145: undefined: http2.MetaHeadersFrame
go/src/google.golang.org/grpc/transport/http2_server.go:281: undefined: http2.MetaHeadersFrame
go/src/google.golang.org/grpc/transport/http_util.go:379: f.fr.ReadMetaHeaders undefined (type *http2.Framer has no field or method ReadMetaHeaders)
go/src/google.golang.org/grpc/transport/http_util.go:509: f.fr.ErrorDetail undefined (type *http2.Framer has no field or method ErrorDetail)
```
`

Then I go get -u:
````
go get -u google.golang.org/grpc
#cd /home/lin/go/src/golang.org/x/net; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
    git pull <remote> <branch>
package golang.org/x/net/context: exit status 1
````

````
go get -u golang.org/x/net/http2
#cd /home/lin/go/src/golang.org/x/net; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
    git pull <remote> <branch>
package golang.org/x/net/http2: exit status 1
```
`

My go version:
````
go version
go version go1.6.3 linux/amd64
```
`

**Comment by Helen-Xie** [comment]
When I go run exanple, also the same error:
```
lin@XYL:~/go/src/google.golang.org/grpc/examples/helloworld$ go run greeter_server/main.go 
# google.golang.org/grpc/transport
../../transport/handler_server.go:209: undefined: http2.TrailerPrefix
../../transport/http2_client.go:821: undefined: http2.MetaHeadersFrame
../../transport/http2_client.go:918: undefined: http2.MetaHeadersFrame
../../transport/http2_server.go:145: undefined: http2.MetaHeadersFrame
../../transport/http2_server.go:281: undefined: http2.MetaHeadersFrame
../../transport/http_util.go:379: f.fr.ReadMetaHeaders undefined (type *http2.Framer has no field or method ReadMetaHeaders)
../../transport/http_util.go:509: f.fr.ErrorDetail undefined (type *http2.Framer has no field or method ErrorDetail)

```

**Comment by menghanl** [comment]
Seems something is wrong with your `golang.org/x/net`.
Try to delete the source from your `$GOPATH` and run go get again.
You can first try to only delete source for `golang.org/x/net`. If this doesn't work, try to delete all source and start again.

**Comment by Helen-Xie** [comment]
@menghanl So, I shoud delete all the `golang.org/x` source ? 
 I delete the `golang.org/x/net` source, then run go get again 
```
go get -u golang.org/x/net
package golang.org/x/net: no buildable Go source files in /home/lin/go/src/golang.org/x/net
```

**Comment by menghanl** [comment]
Not `go get -u golang.org/x/net`, run `go get -u google.golang.org/grpc`.
If this doesn't work, delete all source, and run `go get -u google.golang.org/grpc`.

**Comment by Helen-Xie** [comment]
Thanks，the problem has been solved.
