### ISSUE TITLE
Create an end to end example demonstrating server reflection

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc-go#866]
We need to add an example to the readme for server reflection which covers the following:
- Set up a simple server with reflection enabled. 
- Uses the cli tool to query that service and obtain information on rpc/message types
- Aids in creation of generated code from that which can access the server.

/cc @y-zeng

**Comment by mwitkow** [comment]
I was thinking about developing something like [polyglot](https://github.com/grpc-ecosystem/polyglot) in Golang, but unfortunately it seems that there are no dynamic protobuf serialization libraries in Golang (Java/C++ Dynamic Message equivalents).

@hsaliak Is that something that is planned? :)

**Comment by hsaliak** [comment]
@mwitkow Server reflection https://github.com/grpc/grpc-go/tree/master/reflection 
allows you to query for a list of services and obtain the FileDescriptorProto ( a .proto file represented as a protocol buffer) for a given service.

I do not know if a dynamic protobuf serialization library is planned for in golang though.

**Comment by menghanl** [comment]
Closing this issue.
We have a [reflection tutorial](https://github.com/grpc/grpc-go/blob/master/Documentation/server-reflection-tutorial.md) and an example for this in the helloworld example.
