### ISSUE TITLE
Connection reset by peer when server is restarted

### ISSUE THREAD

**Issue by neilgarb** [grpc/grpc-go#870]
I'm running a gRPC server in one docker container and a client in another docker container.  The client connects to the server using TLS on the docker host's IP.  I'm also using a round-robin balancer, although in this case I'm only supplying one endpoint.

```
func (cl client) connect(address string) {
    ta := tls.Config{...}
    rr := grpc.RoundRobin(...)
    opts := []grpc.DialOption{
       grpc.WithTransportCredentials(ta),
       grpc.WithBalancer(rr),
    }
    conn, err := grpc.Dial(address, opts...)
    ...
    cl.conn = conn
}
```

I've found that if I restart the server container, any requests the client makes error with:

```
Aug 30 09:51:12 staging docker/fe/2bd8f113086b: 2016/08/30 07:51:12 Internal Server Error for POST ..., err=rpc error: code = 13 desc = connection error: desc = "transport: read tcp 172.17.0.4:33851->172.17.0.1:50053: read: connection reset by peer"
```

This persists until I restart the client, then the connection is reestablished and everything works.

I don't have this problem in production, where the balancer is provided multiple endpoints.

Is it bad practice to use a single *grpc.ClientConn? Should I reconnect for each request?

Environment:
go version go1.6.2 darwin/amd64
docker version 1.11.1, linux/amd64

**Comment by tamird** [comment]
This was recently separately observed in https://github.com/cockroachdb/cockroach/issues/8939. @neilgarb which version of grpc are you on? Does it include https://github.com/grpc/grpc-go/pull/864?

**Comment by neilgarb** [comment]
Thanks for your response. I pulled yesterday, so I'm running 79b7c349179cdd6efd8bac4a1ce7f01b98c16e9b on both client and server.  Still seeing this behaviour.

More info: In production (which is using an older version of grpc) I have a balancer with two endpoints.  There I also get `connection reset by peer` when I restart a server, but the client seems to sort itself out after a short while.

More more info: I'm going to run a test with multiple connections per endpoint (something like https://github.com/google/google-api-go-client/blob/master/internal/pool.go#L38), so even if one endpoint is provided the client establishes multiple connections.  Will provide feedback once I'm one.

**Comment by tamird** [comment]
What you're describing is definitely a bug. The current error handling is
still too heavy handed in its treatment of errors as permanent. @bdarnell
writes in
https://github.com/cockroachdb/cockroach/issues/8939#issuecomment-243393233:

The error handling in GRPC needs to be reworked: instead of treating errors
from ClientHandshake as permanent by default with a whitelist of transient
errors (currently io.EOF and context.DeadlineExceeded), it should assume
that all errors are retryable (as it does for every operation except
ClientHandshake) and use a blacklist of certificate-related errors to treat
as permanent failures (or maybe even those should be transient - a
misconfigured server could transiently reject valid certificates and it
shouldn't take a restart of all clients to recover from that).

**Comment by bdarnell** [comment]
`ECONNRESET` counts as `Temporary()` (`syscall/syscall_unix.go`), so #864 should've fixed this, unless there's a different location where errors need to be checked (or if there's something that is throwing away the true type of the error).

And my question in #846 still stands: As long as GRPC distinguishes between transient and temporary failures, client applications will need to be able to tell the difference too. What is the recommended way to do this?

**Comment by neilgarb** [comment]
Creating a pool of connections in the resolver seems to have fixed the symptoms:

```
	for _, a := range addresses { // there's only one in this instance
		for i := 0; i < poolSize; i++ {
			upd = append(upd, &naming.Update{
				Op:       naming.Add,
				Addr:     a,
				Metadata: i,
			})
		}
	}
```

**Comment by tamird** [comment]
@neilgarb be sure to log with both `%T` and `%+v` so you can see the error's type.

**Comment by iamqizhao** [comment]
@tamird we also discussed the blacklist approach about a week ago but have not come up with a decent solution because it requires the credential impl to do the proper pre-processing for error, which could be tricky. We keep thinking ...

**Comment by neilgarb** [comment]
Frustratingly, I can no longer reproduce the problem.  Here are the errors that are logged:

```
// http2_client.go#165: log.Printf("issue-870: %T %+v", err, err)
2016/09/01 09:40:41 issue-870: *net.OpError read tcp 172.17.0.4:36216->172.17.0.1:50053: read: connection reset by peer
2016/09/01 09:40:42 issue-870: <nil> <nil> 
```

Perhaps I wasn't actually running https://github.com/grpc/grpc-go/pull/864. I'll try a server restart again in a few minutes just to confirm, and then close this issue.

**Comment by neilgarb** [comment]
Seems resolved - I must just have muddled up my deployment.

Thanks for all the help/info.

**Comment by tamird** [comment]
Hurray paranoid preemptive fixes!
