### ISSUE TITLE
Support Google Flatbuffers.

### ISSUE THREAD

**Issue by pcariel** [grpc/grpc-go#880]
Hi, friend's. grpc-go Support Flatbuffers?

**Comment by therc** [comment]
cc @rw @gwvo

**Comment by gwvo** [comment]
Not at the moment. @royalharsh has been working on porting the GRPC-FlatBuffers integration to other languages, but I am not sure if he has any plans for go yet.

**Comment by royalharsh** [comment]
Currently, I am working on porting the GRPC-FlatBuffers integration to python. Most probably java and Go are next.

**Comment by ekarlso** [comment]
@royalharsh any news on this ?

**Comment by royalharsh** [comment]
Haven't started working on this yet.

**Comment by gwvo** [comment]
If anyone with Go experience wants to step in and help, that be very much appreciated.

**Comment by JRonak** [comment]
I have been working on it, have been reading the source code for a while after speaking with Wouter.
How do we handle Codec support for flatbuffers?, as of now ProtoCodec is default. 
ref:https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L54

**Comment by gwvo** [comment]
Well, that will have to be refactored to be serialization system agnostic. For example `UnMarshall` would be a no-op in FlatBuffers since it works directly from serialized data. See the C++ code for some inspiration on how to structure this.

**Comment by JRonak** [comment]
Flatbuffers now supports grpc go now!
google/flatbuffers#4082 got merged

**Comment by hsaliak** [comment]
Closing this. We are not officially planning to support flatbuffers as an IDL at the moment. There is some support upstream as per google/flatbuffers#4082 and it works as a message interchange format with grpc already. 

If we do need to support flatbuffers in grpc-go natively, it should be proposed as a [gRFC](https://github.com/grpc/proposal)
