### ISSUE TITLE
Request logs?

### ISSUE THREAD

**Issue by tejasmanohar** [grpc/grpc-go#884]
Is there a good practice for logging request/response/errors in a GRPC go server? I haven't found any concept of middleware yet that I can drop some logs into and have been writing a lot of code like

```
log.Error(msg)
return nil, errors.New(msg) (or grpc.Errorf(<code>, msg)
```

whereas i'd rather just return errors and have something else log them

**Comment by menghanl** [comment]
Is server side interceptor (https://github.com/grpc/grpc-go/blob/master/clientconn.go#L221) what you are looking for?

**Comment by tejasmanohar** [comment]
I think this makes sense. Thanks!

**Comment by fatih** [comment]
For anyone who finds this via Google, here is a simple snippet that shows how the log the **return** error:

```
errHandler := func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
	resp, err := handler(ctx, req)
	if err != nil {
		log.Printf("method %q failed: %s", info.FullMethod, err)
	}
	return resp, err
}

srv = grpc.NewServer(grpc.UnaryInterceptor(errHandler))
```
