### ISSUE TITLE
Server-side client disconnection notification

### ISSUE THREAD

**Issue by aarondl** [grpc/grpc-go#889]
Because gRPC is http2, my understanding is the client dials once and re-uses the connection for all it's rpc calls. In which case it seems possible that the server may be able to create some resources on the server side for that connection to persist across each rpc call.

However, there seems to be no way to determine when a disconnection occurs (outside of maybe streaming). In my code I'd like to set TCP KeepAlive and then when the connection dies, clean up those resources.

Any thoughts on this?

**Comment by vimalk78** [comment]
i am also looking for the same.

i posted in the grpc-go mailing list

https://groups.google.com/forum/#!topic/grpc-io/EIcQlLqlNQg

**Comment by juanpmarin-infocorp** [comment]
Any update about this ?

**Comment by dfawley** [comment]
As of now, the only way to do something like this would be to use a [stats handler](https://godoc.org/google.golang.org/grpc#StatsHandler) (unintuitively), which can tag a connection's context.  This context is propagated to all incoming calls, and data could be shared this way.

This is not a unique request, but we generally recommend against keeping state on the server at a connection-level.  The same client could connect to multiple servers or the same server multiple times, which could lead to races or data loss if you aren't careful.

Feel free to follow-up here if you have further questions.
