### ISSUE TITLE
server closed the stream without sending trailers when use nginx1.11.3 as proxy server

### ISSUE THREAD

**Issue by wangming1993** [grpc/grpc-go#892]
Hi,

Recently I learn grpc-go, as we know, it can be a server or client. But I have a demand that use php as server language when use grpc. Unfortunately, there is no supports now, so I tried to use nginx 1.11.3 as proxy serve to parse http2 protocol, then rediect all request to php.

From the response, I got such message: **`server closed the stream without sending trailers`**,   I got some search that nginx has no supports to trailers, is it right? 

Here is the code I wrote with php:

```
header("content-type: application/grpc");
header("status: 200");
header("grpc-timeout: 003S");
echo $reply;
//header("trailer: 4")
header("grpc-status: 0");
```

And I can get response body, but occurs errror with ` unexpected EOF`, because of **no sending trailers.**

Needs some help from grpc-go group.

Thanks

**Comment by menghanl** [comment]
We are not sure what the real problem is.
A better place to ask gRPC php questions is repo https://github.com/grpc/grpc, so you can get answers from gRPC php maintainers and other gRPC php users.

**Comment by iamqizhao** [comment]
The current grpc protocol requires a trailer to indicate the completion of an rpc. There are some discussions regarding this in progress but currently it is required.

**Comment by wangming1993** [comment]
Thanks, and I know it required a trailer for ending stream. What I really confused is **how to send a trailer with nginx1.11.3**.  *Is it supported by nginx ?*  My case is:  use nginx1.11.3 as server proxy to pasre http2 protocol,  then gprc-go as client, client dial 443 port then all request redirect index.php, then nginx send a response to rpc client.  
@iamqizhao

**Comment by wangming1993** [comment]
Thanks, and I know it required a trailer for ending stream. What I really confused is **how to send a trailer with nginx1.11.3**.  *Is it supported by nginx ?*  My case is:  use nginx1.11.3 as server proxy to pasre http2 protocol,  then gprc-go as client, client dial 443 port then all request redirect index.php, then nginx send a response to rpc client.  
@iamqizhao

**Comment by iamqizhao** [comment]
Currently it is not supported and according to the info I got back in May they did not have plan to support it yet.
