### ISSUE TITLE
balancer.Up is called after balancer.Close is called

### ISSUE THREAD

**Issue by xiang90** [grpc/grpc-go#893]
We found gRPC might call balancer.Up even if balancer.Close is called.

I am not super familiar with gRPC internal. But it seems that after we call clientConn.Close, gRPC might still call into clientConn.resetAddrConn and then call Balancer.Up.

Is it the users' responsibility to ensure balancer should work well even if Up is called after Close (which the default balancer does)? Or should we fix gRPC to ensure it wont call balancer.Up after balancer is closed? Or there is a misuse of gRPC in our application?

**Comment by iamqizhao** [comment]
I think this is a race the balancer has to deal with because these operations (i.e., ClientConn.Close, lbWatcher founds a new address to connect) are racy. I think your balancer can simply do no-op in this case if balancer.Close() has been called.

**Comment by xiang90** [comment]
OK. Will fix at the application side.
