### ISSUE TITLE
Implement HTTP→gRPC status code mapping

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-go#896]
As defined in grpc/grpc#4955. Please wait until PR is in before merging the code changes, although the PR has received general agreement ("but it's not official until it's official").

This is important to return useful gRPC status codes when proxies generate errors.

**Comment by shuoli84** [comment]
The upstream issue is merged. So this one is unblocked? I guess?

**Comment by mwitkow** [comment]
@yugui you may be interested in this as the maintainer of grpc-gateway.

**Comment by yugui** [comment]
Yes. Thank you for letting me know, @mwitkow
