### ISSUE TITLE
Can grpc-go supports intercept all request?

### ISSUE THREAD

**Issue by wangming1993** [grpc/grpc-go#901]
Hi, 

I have such requirement: **limit each rpc request times**. And I know grpc-go has  `UnaryServerInterceptor` and `StreamServerInterceptor`, I can do that with XXXServerInterceptor.
But I found it's too later because it takes effect after calling server method that client wants.

For example:
Client want call `sayHello`, The server process is:

```
1. get server transport and transport stream
2. processXXXRPC
3. parse request body and check payload
4. handle XXXServerInterceptor if registered
5. server call `sayHello`
6. response
```

But what I want just like this:

```
1. get server transport and transport stream
2. do intercept, if ok, continue
3. processXXXRPC
4. parse request body and check payload
5. handle XXXServerInterceptor if registered
6. server call `sayHello`
7. response
```

Maybe I can add a interceptor for server:

``` go
type Interceptor func(t transport.ServerTransport, stream *transport.Stream) error

type Server struct {
    ...
    interceptor Interceptor
}

func (s *Server) RegisterInterceptor(interceptor Interceptor) {
    s.interceptor = interceptor
}

func (s *Server) handleStream(t transport.ServerTransport, stream *transport.Stream, trInfo *traceInfo) {
    if s.interceptor != nil {
        err := s.interceptor(t, stream)
        if err != nil {
            if trInfo != nil {
                trInfo.tr.LazyLog(&fmtStringer{"%v", []interface{}{err}}, true)
                trInfo.tr.SetError()
            }
            if err = t.WriteStatus(stream, codes.FailedPrecondition, err.Error()); err != nil {
                if trInfo != nil {
                    trInfo.tr.LazyLog(&fmtStringer{"%v", []interface{}{err}}, true)
                    trInfo.tr.SetError()
                }
                grpclog.Printf("grpc: Server.handleStream failed to write status: %v", err)
            }
            if trInfo != nil {
                trInfo.tr.Finish()
            }
            return
        }

    }
...
}

```

Is this solution acceptable? Or there has other ideal can resolve such case? 

Thanks,

**Comment by wangming1993** [comment]
@iamqizhao please give some suggestion if I want such feature,  thanks!!

**Comment by iamqizhao** [comment]
I think you need a transport layer interceptor. Your proposal does not work either because it is still too late (per-stream goroutine has been spawned). The good news is that we will add this feature (probably call it "transport filter" or something) for sure because we have the similar requirement internally. But there is high chance we won't have time to make it happen this quarter. The ETA would be Q1 2017.
