### ISSUE TITLE
metadata.NewContext should not trample old metadata

### ISSUE THREAD

**Issue by pongad** [grpc/grpc-go#902]
Motivating issue: https://github.com/googleapis/toolkit/issues/474

We have a use case for merging multiple MDs together. While we can individually implement this, I think this is general enough to deserve a place in the metadata library.

I wrote up a possible design/implementation [here](https://play.golang.org/p/kkL5QTe2tn). I think it gels decently well with the rest of the library so far. Please let me know what you think, I'll gladly make a PR for it.

**Comment by menghanl** [comment]
We have a plan to change the behavior of `metadata.NewContext()` to do a merge before creating a new context.
Does this work for your issue?

**Comment by pongad** [comment]
Sounds good to me. I'll work around the issue in the meantime. I cannot seem to find a tracking issue for it. Do you have the link handy?

**Comment by menghanl** [comment]
We don't have an issue for that now.
We can edit the title of this issue and use this one to track, if you don't mind.

**Comment by pongad** [comment]
That sounds good to me. Not sure if you've already have an implementation running, but since I already put something together, I'll open a PR for it.
