### ISSUE TITLE
handle client disconnect

### ISSUE THREAD

**Issue by mephux** [grpc/grpc-go#904]
I have a few streams that need to be cleaned up and restarted when the client disconnects and then successfully reconnects.

Is there a workaround for something like this right now?

**Comment by iamqizhao** [comment]
Having native support of streaming rpc retrying is challenging. You need to do it in your code now. We are designing the retry policy and corresponding mechanism now. But the ETA would probably be Q1 next year.

**Comment by mephux** [comment]
@iamqizhao that's fair - what could I use on the client side to detect this? I see logs sent to stderr on connection loss and during back off but how can I hook into that.

Maybe I am missing something in the docs for that or do I have to just create the connection logic myself?

**Comment by dfawley** [comment]
Sorry for the long delay here.  The stream's `Send` and `Recv` methods should return an error when there is a connection problem.  At that point you should be able to do your cleanup/reconnect.  If you still have any questions/comments about this, please let me know and I'll try to answer them.  Thanks!
