### ISSUE TITLE
Chinese ErrDesc error

### ISSUE THREAD

**Issue by wencan** [grpc/grpc-go#909]
return:
 rpc error: code = 10 desc = 系统发生异常

received: 
rpc error: code = 10 desc = %E7%B3%BB%E7%BB%9F%E5%8F%91%E7%94%9F%E5%BC%82%E5%B8%B8

**Comment by puellanivis** [comment]
This article seems relevant: http://www.joelonsoftware.com/articles/Unicode.html

Not that I'm a pillar of never-making-a-mistake…
