### ISSUE TITLE
Read gRPC server response header and trailers in client interceptor

### ISSUE THREAD

**Issue by NeoCN** [grpc/grpc-go#915]
Is there any way to read gRPC server response header and trailers in client interceptor？
The current client api design makes the header and trailers inaccessible in the client interceptor.
The CallOption interface has two internal method, we can not make a custom CallOption to  read headers and trailers.

**Comment by menghanl** [comment]
For Unary RPCs, you can append your own CallOption `grpc.Header()` or `grpc.Trailer()` to `opts`.
For Streaming RPCs, header and trailer can be read from the `ClientStream`.

**Comment by NeoCN** [comment]
@menghanl Thanks, I figured out the way as you mentioned! close this issue now.
