### ISSUE TITLE
Release a new version of gRPC with the new balancer API

### ISSUE THREAD

**Issue by xiang90** [grpc/grpc-go#917]
The new balancer breaks the API. Libraries that depend on that API break when linking against the head version of gRPC. This can be easily avoided if users vendor the current version of gRPC. However, this is not what go get does. We have seen people complain they cannot compile etcd client due to this change.

So is it possible to do a quick release that has the new API? So we can update etcd/client to track the new released version of gRPC? Thanks!

**Comment by iamqizhao** [comment]
Sorry about the inconvenience. It will be released shortly.

**Comment by menghanl** [comment]
Created a tag v1.0.2.
