### ISSUE TITLE
Messages with repeated oneof serialize nil values

### ISSUE THREAD

**Issue by buckhx** [grpc/grpc-go#926]
What version of Go are you using (go version)? 1.7
What operating system and processor architecture are you using? darwin/amd64
What did you do? I have a service definition whose output message contains a repeated oneof and consumers of the service would receive nils in place of the actual values.

Due to https://github.com/golang/protobuf/issues/237 using a repeated oneof field will result in nil messages.

Switching rpc_util to use gogoproto here is a hotfix I'm using, but obviosuly not desirable https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L46

**Comment by hsaliak** [comment]
@buckhx this seems to not be a gRPC issue but a protobuf issue, as filed in  golang/protobuf#237  so I am closing this. I'll follow up on the protobuf issue on that bug.
