### ISSUE TITLE
Unregister Service (feature request)

### ISSUE THREAD

**Issue by panamafrancis** [grpc/grpc-go#928]
I'm unsure if this feature request should be made to the GRPC working group instead, but i want to know what the implications would be if it was possible to not only register a service but also unregister it.

For example:

``` go
 server = grpc.NewServer()
myService = NewMyService()
pb.RegisterMyServer(server, myService)

// ...

pb.UnregisterMyServer(server, myService)
```

It would require changes to the grpc.Server and also the protobuffer compiler to generate the unregister methods.

I would find it very useful for composing services dynamically, are there any strong arguments against implementing this?

Thx!

**Comment by panamafrancis** [comment]
Ping... Any comment here?

**Comment by hsaliak** [comment]
@panamafrancis we do not have any plans to implement this at the moment.  Strong arguments against doing something like this would be how this would work in an actual scenario where clients are connected to a service. As far as the client is concerned, the service availability is impacted, the same as a restart.
