### ISSUE TITLE
Cannot run route_guide example

### ISSUE THREAD

**Issue by ccressent** [grpc/grpc-go#933]
I am unable to successfully run the `route_guide` example on the latest master (b057848 at the time of this writing).

**What version of Go are you using (go version)?**
```
$ go version
go version go1.7 darwin/amd64
```

**What operating system and processor architecture are you using?**
```
$ uname -a
Darwin MacBook-Pro 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
```
**What did you do?**
```
$ go get google.golang.org/grpc
$ cd $GOPATH/src/google.golang.org/grpc/examples/route_guide
$ go run server/server.go &
$ go run client/client.go
```
and
```
$ go run server/server.go -tls &
$ go run client/client.go -tls
```

**What did you expect to see?**
I expected to have the `route_guide` example running without errors.

**What did you see instead?**
```
2016/10/14 16:56:12 Getting feature for point (409146138, -746188906)
2016/10/14 16:56:12 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/10/14 16:56:12 &{0xc420146900}.GetFeatures(_) = _, rpc error: code = 13 desc = transport is closing:
exit status 1
```
and with the -tls flag:
```
2016/10/14 16:57:15 Getting feature for point (409146138, -746188906)
2016/10/14 16:57:15 Failed to dial 127.0.0.1:10000: connection error: desc = "transport: tls: oversized record received with length 20527"; please retry.
2016/10/14 16:57:15 &{0xc42018aa20}.GetFeatures(_) = _, rpc error: code = 13 desc = connection error: desc = "transport: tls: oversizedrecord received with length 20527":
exit status 1
```

**Comment by iamqizhao** [comment]
It runs fine on my desktop. Did you run it with docker? If yes, I think there were some issues on the docker config. You can probably test with some simple non-grpc programs (e.g., simply use net.Conn or tls.Conn) to check.

**Comment by ccressent** [comment]
It turns out an unsuspected docker container was exposing its port 10000 on the host machine's port 10000... which is the default port for this example. The example server would still run fine, but the client would try to talk to the docker container, generating the errors because that container doesn't "speak" gRPC.

This is somewhat related to #120.

Closing for now.
