### ISSUE TITLE
TLSInfo not available from ClientHandshake

### ISSUE THREAD

**Issue by donovanhide** [grpc/grpc-go#934]
https://github.com/grpc/grpc-go/blob/master/credentials/credentials.go#L168-L170

It is useful to receive access to the ConnectionState of a TLS connection when both server and client want to prove their identity in a peer to peer scenario at the application level. For example both peers might want to sign the TLSUnique bytes with their private key. This omission prevents that from happening.

**Comment by yacovm** [comment]
I agree, this is useful to defend against attacks such as described in:
https://mitls.org/pages/attacks/3SHAKE

**Comment by menghanl** [comment]
@MakMukhi is working on this. Will have a PR shotly.

**Comment by donovanhide** [comment]
Cool, thanks!
