### ISSUE TITLE
Interceptors aren't (easily) composable

### ISSUE THREAD

**Issue by atombender** [grpc/grpc-go#935]
You can't add more than one interceptor, which makes it harder to structure code around a server. For example, if you want logging and request tracing, you'll want to split this up this up in two separate interceptors can that can be tested independently.

However, I don't think there's any technical reason why the current interceptor interface cannot support this. As far as I can see, you can chain interceptors like this:

```go
func composeUnaryServerInterceptors(interceptor, next grpc.UnaryServerInterceptor) grpc.UnaryServerInterceptor {
	return func(
		ctx context.Context,
		req interface{},
		info *grpc.UnaryServerInfo,
		handler grpc.UnaryHandler) (interface{}, error) {
		return interceptor(ctx, req, info,
			func(nextCtx context.Context, nextReq interface{}) (interface{}, error) {
				return next(nextCtx, nextReq, info, handler)
			})
	}
}
```

And from this we can build one that takes a whole bunch:

```go
func ComposeUnaryServerInterceptors(interceptors ...grpc.UnaryServerInterceptor) grpc.UnaryServerInterceptor {
	for {
		switch len(interceptors) {
		case 0:
			panic("Interceptor list cannot be empty")
		case 1:
			return interceptors[0]
		case 2:
			return composeUnaryServerInterceptors(interceptors[0], interceptors[1])
		default:
			interceptors[1] = composeUnaryServerInterceptors(interceptors[0], interceptors[1])
			interceptors = interceptors[1:]
		}
	}
}
```

However, I think it would be better to build it into the server constructor, and simply allow more than one interceptor to be passed in.

**Comment by iamqizhao** [comment]
This is intentional. We only provide a hook so that various complex interceptor patterns (e.g., chaining, nested, stack, concurrent, etc.) can be built on top of it without running into the argument of the execution ordering of the multiple interceptors while keeping grpc itself simple.

**Comment by atombender** [comment]
This is useful functionality. Why not provide it in a utils subpackage?

**Comment by iamqizhao** [comment]
We are not going to put it as part of grpc-go. If you want to contribute, you can make one at https://github.com/grpc-ecosystem.
