### ISSUE TITLE
Side-effect loggers

### ISSUE THREAD

**Issue by ahmetb** [grpc/grpc-go#943]
My service has structured logging. However when I call `grpc.Dial` on a service that is not reachable, in my process logs, I see lines such as:

```
2016/10/24 21:39:31 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:8080: getsockopt: connection refused"; Reconnecting to {localhost:8080 <nil>}
```

It appears like `grpc.Dial()` function has a side-effect which is logging stuff even though it is not configued to do so.

It still returns error (such as `rpc error: code = 14 desc = grpc: the connection is unavailable`) from `grpc.Dial()` but there is also a log line. How can I turn the logging from grpc package off?

**Comment by menghanl** [comment]
> even though it is not configued to do so.

What do you mean here? What's the config you changed?

**Comment by ahmetalpbalkan** [comment]
@menghanl I didn't configure anything (such as any loggers). I'm just following the tutorials.

It's odd that some go package is printing to stderr/stdout without my consent. Ideally this wouldn't happen.

**Comment by menghanl** [comment]
Currently the default gRPC logger logs everything to stderr.
If you don't want this behavior, please set a different logger with [SetLogger](https://github.com/grpc/grpc-go/blob/master/grpclog/logger.go#L61).

We are working on improving the logging system, stay tuned.

**Comment by hsaliak** [comment]
@menghanl can you reference related pull requests that might help here?
Will #922 address this?

**Comment by menghanl** [comment]
The new [`grpclog`](https://godoc.org/google.golang.org/grpc/grpclog) only logs Errors by default. 
And it's behavior can be controlled by environment variables. Closing this now.
