### ISSUE TITLE
Hangs when there is contention over stream

### ISSUE THREAD

**Issue by thesandlord** [grpc/grpc-go#948]
I am benchmarking gRPC functionality. I have a server that takes in a object and base64 encodes it. The client generates X requests with a for loop and sends these requests on the **same** bidi stream.

The server code is pretty simple:

```go
func (s *grpcServer) AsyncPerson(stream pb.PingPong_AsyncPersonServer) error {
	for {
		in, err := stream.Recv()
		if err == io.EOF {
			return nil
		} else if err != nil {
			return err
		}
		go func() {
			str := customEncode(in)
			if err := stream.Send(&pb.Base64{Message: str}); err != nil {
				log.Printf("Can't send, %v", err)
			}
		}()
	}
}
```

At a certain point (around 10,000 simultaneous requests) this seems to fall over.

Two possible solutions:

1) Use a mutex or remove the goroutine

```go
func (s *grpcServer) AsyncPerson(stream pb.PingPong_AsyncPersonServer) error {
	for {
		in, err := stream.Recv()
		if err == io.EOF {
			return nil
		} else if err != nil {
			return err
		}
		str := customEncode(in)
		if err := stream.Send(&pb.Base64{Message: str}); err != nil {
			log.Printf("Can't send, %v", err)
		}
	}
}
```

This fixes the problem but hurts performance.

2) Make the client use a separate stream per request.

The docs did not state that using multiple goroutines over a single stream is not "safe" to do. I would have expected this to be called out. There are many examples I can think of where someone would be sending data from multiple goroutines over a single stream and expecting messages back asynchronously (for example an IoT hub that is aggregating data from multiple devices). If the recommended solution is to open a stream per goroutine and not to share a single stream, this should be documented clearly.

**Comment by iamqizhao** [comment]
we do not support concurrent writers for a single stream for now.

**Comment by broady** [comment]
@iamqizhao is that planned for the future? If not, it would be good to see documentation to that effect.

**Comment by campoy** [comment]
+1 this should be documented clearly on the docs and probably on the comments of the Send method too
