### ISSUE TITLE
expose read-only connection information in interceptors

### ISSUE THREAD

**Issue by clutchski** [grpc/grpc-go#951]
As far as i can tell, none of the structs available to client interceptors expose the address of the server you'll ping. Is it possible to expose this in a read-only manner for telemetry, logging, etc?

**Comment by iamqizhao** [comment]
https://github.com/grpc/grpc-go/blob/master/peer/peer.go#L62 gives the peer address.

**Comment by gbbr** [comment]
This doesn't work. There is nothing found using `peer.FromContext` in a unary client interceptor. I wonder if I'm doing something wrong.

**Comment by gbbr** [comment]
If anyone ever finds this issue, the solution is to use the [`grpc.Peer`](https://godoc.org/google.golang.org/grpc#Peer) option inside the UnaryClientInterceptor and to pass it to the `invoker` function. Afterwards, peer information will be obtainable.

**Comment by dfawley** [comment]
@gbbr, that sounds right to me.  To hopefully explain this further: we don't know which server will be attempted *before* `invoker` is called -- the interceptor is almost the first thing we do after the user's code.  And note that with retry, you may end up hitting multiple different servers in the same call, so the `Peer` is only valid after the RPC has completed (or has been [_committed_](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#when-retries-are-valid)).

Thanks for clarifying the solution here.
