### ISSUE TITLE
Panic when grpc encode the data in sendResponse function.

### ISSUE THREAD

**Issue by Fall12** [grpc/grpc-go#959]
Hi, the process has been running for five months well, but last night a panic occurred when grpc encode the data in sendResponse function. the grpc code is update at October 14,2016.every help is much appreciated, thanks!

	panic: reflect: call of reflect.Value.Set on zero Value
	
	goroutine 65372089 [running]:
	panic(0xc30b60, 0xc426fc3980)
	        /usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
	reflect.flag.mustBeExported(0x0)
	        /usr/local/Cellar/go/1.7/libexec/src/reflect/value.go:209 +0x14e
	reflect.Value.Set(0xc8b6e0, 0xc420290970, 0x196, 0x0, 0x0, 0x0)
	        /usr/local/Cellar/go/1.7/libexec/src/reflect/value.go:1328 +0x40
	golang/protobuf/proto.(*Buffer).enc_new_map(0xc4253cf930, 0xc4221ba640, 0xc420f28cb8, 0xc6b120, 0x118abc0)
	        /Users/go/src/golang/protobuf/proto/encode.go:1163 +0x37b
	golang/protobuf/proto.(*Buffer).enc_struct(0xc4253cf930, 0xc4221bca00, 0xc420f28cb8, 0xc8b320, 0xc420f28cb8)
	        /Users/go/src/golang/protobuf/proto/encode.go:1236 +0x41c
	golang/protobuf/proto.(*Buffer).Marshal(0xc4253cf930, 0x11816a0, 0xc420f28cb8, 0xc42047f930, 0x700)
	        /Users/go/src/golang/protobuf/proto/encode.go:281 +0x2eb
	golang/protobuf/proto.Marshal(0x11816a0, 0xc420f28cb8, 0xc420f28cb8, 0xc42047f988, 0xc440000000, 0x0, 0x1ac0390)
	        /Users/go/src/golang/protobuf/proto/encode.go:236 +0x175
	google.golang.org/grpc.protoCodec.Marshal(0xc8b320, 0xc420f28cb8, 0x5d60df, 0xc423559714, 0xecfa55b2f, 0x22b8752f, 0x11ad3e0)
	        /Users/go/src/google.golang.org/grpc/rpc_util.go:68 +0x79
	google.golang.org/grpc.(*protoCodec).Marshal(0x11cd358, 0xc8b320, 0xc420f28cb8, 0xc422d57ba0, 0xc41fd76d2c, 0xc42047fab8, 0x41139e, 0xc425125a60)
	        <autogenerated>:34 +0x60
	google.golang.org/grpc.encode(0x1183360, 0x11cd358, 0xc8b320, 0xc420f28cb8, 0x0, 0x0, 0x0, 0x0, 0x10, 0x10, ...)
	        /Users/go/src/google.golang.org/grpc/rpc_util.go:264 +0x2eb
	google.golang.org/grpc.(*Server).sendResponse(0xc420522140, 0x1186b40, 0xc4217bc3f0, 0xc426deeb40, 0xc8b320, 0xc420f28cb8, 0x0, 0x0, 0xc425125a70, 0x0, ...)
	        /Users/go/src/google.golang.org/grpc/server.go:512 +0x91
	google.golang.org/grpc.(*Server).processUnaryRPC(0xc420522140, 0x1186b40, 0xc4217bc3f0, 0xc426deeb40, 0xc420588210, 0x11a4d88, 0xc424ad2570, 0x0, 0x0)
	        /Users/go/src/google.golang.org/grpc/server.go:637 +0x1050
	google.golang.org/grpc.(*Server).handleStream(0xc420522140, 0x1186b40, 0xc4217bc3f0, 0xc426deeb40, 0xc424ad2570)
	        /Users/go/src/google.golang.org/grpc/server.go:769 +0x6b0
	google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc422106010, 0xc420522140, 0x1186b40, 0xc4217bc3f0, 0xc426deeb40)
	        /Users/go/src/google.golang.org/grpc/server.go:422 +0xab
	created by google.golang.org/grpc.(*Server).serveStreams.func1
	        /Users/go/src/google.golang.org/grpc/server.go:423 +0xa3

**Comment by menghanl** [comment]
The panic was in `proto.Marshal`, please file an issue at https://github.com/golang/protobuf.

And a test to reproduce would be very helpful.
