### ISSUE TITLE
Custom transport.ConnectionError values cannot be created.

### ISSUE THREAD

**Issue by havoc-io** [grpc/grpc-go#971]
The GA release of gRPC exported the `transport.ConnectionErrorf` function, which was useful when using a custom dialer to indicate a non-transient connection failure. For some reason this function (along with `transport.StreamErrorf`) was unexported in commit 086edd7d.

Unfortunately there is no longer a way for dialers to indicate non-transient failures to `resetTransport`, since the single exported `transport.ConnectionError` constant (`ErrConnClosing`) is defined to be transient. It's also a bit unfortunate because it breaks the API after the GA release by removing functions that were not tagged as experimental.

Is it possible to have these functions returned, or to have a `transport.ConnectionError` constant defined that is marked as non-transient, so that the `resetTransport` function wouldn't try to reconnect indefinitely?  This would help facilitate working around #668.

**Comment by menghanl** [comment]
`transport.ConnectionError` was designed as a gRPC internal only error, which we didn't expect users to create. We removed `transport.ConnectionErrorf` on purpose to stop users from creating `ConnectionError` outside of gRPC.

For your issue, we think the correct solution should be that, the dialer returns an error with `Temporary()` method. Just created #974 to resolve this. Please take a look.

**Comment by havoc-io** [comment]
That sounds like a fine solution.  The change at line 153 of `http2_client.go` seems a bit fragile to me though given that the error propagates up through `NewClientTransport`, `resetTransport`, and `resetAddrConn`.  It seems like the behavior could very easily be broken by some future change at a higher level (especially given the degree of refactoring that's been done in `resetTransport` over the last year).  Would it be possible to document (perhaps as part of the documentation for `WithDialer`) that this `interface{ Temporary() bool }` check occurs and has the behavior of aborting re-dial attempts?

**Comment by menghanl** [comment]
Added comments to `WithDialer`.

**Comment by havoc-io** [comment]
Thanks a lot for the quick response and elegant solution!  I'll watch for your PR to be merged.
