### ISSUE TITLE
significant time of unary qps test in `runtime.newobject` and `reflect.New` 

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc-go#977]
after changes in https://github.com/grpc/grpc-go/pull/973 and https://github.com/grpc/grpc-go/pull/940 tried together profiling the server under unary QPS test shows a lot of cpu-clock events in `runtime.newobject`, with the main producer being `reflect.unsage_New` from protobuf. 
Not sure at the moment what can be done about this.

snippet of a profile shown here
```
-   31.41%     0.51%  worker  worker             [.] runtime.newobject
   - runtime.newobject
      + 44.86% google.golang.org/grpc.(*Server).processUnaryRPC
      - 40.22% reflect.unsafe_New
           reflect.New
           github.com/golang/protobuf/proto.(*Buffer).dec_struct_message
           github.com/golang/protobuf/proto.(*Buffer).unmarshalType
           github.com/golang/protobuf/proto.(*Buffer).Unmarshal
         - google.golang.org/grpc.protoCodec.Unmarshal 
```

**Comment by dfawley** [comment]
We've done some pretty significant refactoring and performance tuning in the past couple months, so I'm going to close this now.
