### ISSUE TITLE
Too many arguments in call to transport.NewServerTransport error on go build

### ISSUE THREAD

**Issue by EwanValentine** [grpc/grpc-go#978]
# Go version 
1.7.1

# OS
Official Golang:1.7.1 docker image.

# What did I do?
I attempted to compile my Go API using a docker image, grpc-go lib present in `vendor` folder, using `$ govendor add github.com/grpc/grpc-go` and `$ govendor add github.com/grpc/grpc-go/internal`. 

I'm then using the following code to create a gRPC server... 

```go
type server struct{}

func (s *server) ValidateToken(ctx context.Context, in *pb.ValidateTokenRequest) (*pb.ValidateTokenResponse, error) {
	isValid, err := services.ValidateToken(in.Token)

	if err != nil {
		return &pb.ValidateTokenResponse{Validated: isValid}, err
	}

	return &pb.ValidateTokenResponse{Validated: isValid}, nil
}

func main() {
        listen, err := net.Listen("tcp", port)

	if err != nil {
		log.Fatalf("Error connecting: %v", err)
	}

	s := grpc.NewServer()

	pb.RegisterAuthServer(s, &server{})

	go s.Serve(listen)

        // Omitted. 
}
``` 

# What did I expect? 
I expected gRPC to be running on port 50051, and my API to compile without errors. 

# What did I see instead? 
The following error... 

```
bitbucket.org/bandzest/bandzest-service-auth/api/vendor/google.golang.org/grpc
vendor/google.golang.org/grpc/server.go:425: too many arguments in call to transport.NewServerTransport
``` 

Thanks in advance!

**Comment by menghanl** [comment]
I noticed that you are using vendor, my guess is that something is not updated in your vendored gRPC.
Please do an update and try again.

**Comment by EwanValentine** [comment]
@menghanl I deleted the vendor folder and re-added them, still the same error

**Comment by menghanl** [comment]
I think the gRPC code is not up to date. I'm not sure how you did the update, but you can check you local code to see if it's updated.

In the error message you provided, error happens at line 425.
But in latest code, `transport.NewServerTransport` is called at line 443:
https://github.com/grpc/grpc-go/blob/master/server.go#L443

`transport.NewServerTransport` is defined at:
https://github.com/grpc/grpc-go/blob/master/transport/transport.go#L368

**Comment by EwanValentine** [comment]
My bad, I'm new to govendor, and I didn't realise 'add' was just adding my
local version. I tried again and it worked, ish. I got a different error,
but I think that's something unrelated. Thanks for pointing me in the right
direction, were spot on!
