### ISSUE TITLE
RPC connection error : rpc error: code = 14 desc = grpc: the connection is unavailable

### ISSUE THREAD

**Issue by Ch3ck** [grpc/grpc-go#979]
I think it's somehow related to [this](https://github.com/grpc/grpc-go/issues/498)

But I"m trying to run a basic [microservice ](https://github.com/Ch3ck/go-serve)and when I try this : `curl "http://localhost:9000?lat=4.1482&long=2453" -H "Authorization: Bearer VALID_TOKEN"`
 I get `rpc error: code = 14 desc = grpc: the connection is unavailable`. 

I've looked at this code for hours, I can't seem to figure out the issue here.

Thanks,
Nyah

**Comment by menghanl** [comment]
Can you elaborate? Where did you get the error?
Can you give more details on what you did?
A small test to reproduce would also be helpful.

**Comment by Ch3ck** [comment]
@menghanl I misconfigured my docker-compose yml file which caused the issue. I erroneously thought it was coming from the grpc package. Thanks

**Comment by EwanValentine** [comment]
@Ch3ck What did you misconfigure? I'm having a similar issue in Kubernetes, but not locally :/

**Comment by marcosArruda** [comment]
@Ch3ck same problem here. What did you misconfigured??

**Comment by nizsheanez** [comment]
@Ch3ck, please, come back and say what was wrong :-)

**Comment by Ch3ck** [comment]
Hi @EwanValentine @marcosArruda @nizsheanez I did not properly configure one of the services in the Docker compose file. I missed adding one of the services to the docker compose file. So when I started `docker-compose` there was the rpc error which meant one of the connections was not available which actually referred to the missing service. I think I fixed that in this commit: https://github.com/Ch3ck/go-serve/commit/ca9c7b2c16560f91a4c67276628c757fb7e2a47d

**Comment by nizsheanez** [comment]
I also did miss-configuration in docker compose - used wrong hostname of target service. 
Thanks. 
Anyway, `connection is unavailable` is not friendly error - in tons of microservices world need to know "which host/port is unavailable?". 
And it's even more important with Go - where we don't have stack traces. 

Anyway, thanks, everybody.

**Comment by Ch3ck** [comment]
You could check out `delve` tool, It's the best `golang` debugger I've used so far. They provide stacktraces, although not very good.

**Comment by FX-HAO** [comment]
Same problem, but my service works well for a few days, and then got `rpc error: code = Unavailable desc = grpc: the connection is unavailable`, if i restart the container, it works again, but for a few days, repeatedly.

**Comment by FX-HAO** [comment]
I got it, the problem is that i created a new connection for every RPC and don't close it, so the number of file descriptors increases infinitely, finally, it reach the limit of open files. It seems i need a connection pool to reuse the connections.

**Comment by dfawley** [comment]
@FX-HAO,

> It seems i need a connection pool to reuse the connections.

You only need to create a single client, and you can use that one simultaneously for all of your RPCs.  You should not need to maintain a pool.

**Comment by Astone-Chou** [comment]
@dfawley Can u give me some suggestion or some doc about, In stream model, one grpc.ClientConn for all user or multi-grp.ClientConn for all user. Thanks very much !
