### ISSUE TITLE
Concurrent access to metadata.MD

### ISSUE THREAD

**Issue by kokaz** [grpc/grpc-go#983]
Hi!

Here is an issue we came across using gRPC with the gRPC OpenTracing project.

1. What version of Go are you using (go version)?

Go 1.7

2. What operating system and processor architecture are you using?

Linux amd64/Darwin amd64

3. What did you do?

A gRPC method calling 2 other gRPC calls (from 2 different services)  in their own goroutine using the same `context.Context` in order to pass metadata from OpenTracing to the subsequent calls.

4. What did you expect to see?

Not a panic.

5. What did you see instead?

A panic on concurrent read/write on a map (i.e. the `metadata.MD` struct).
The issue happens when one goroutine try to read metadata.MD from the context and the other one is writting to it. We used `md.Copy()` but still not concurrently safe.

Here is some background info: https://github.com/grpc-ecosystem/grpc-opentracing/issues/7

**Comment by iamqizhao** [comment]
Is it possible to have a mutex to guard your MD accesses? grpc MD is not concurrency-safe.

**Comment by bensigelman** [comment]
(Cross-posting from that PR)

@iamqizhao

> I do not read into your code. Is it possible to have a mutex to guard your MD accesses? grpc MD is not concurrency-safe.

Since the GRPC MD is shared across all users of the GRPC connection, adding locking in this code (or any other) is not sufficient to make it concurrency-safe. We would need all readers and writers to share concurrency primitives. This is why I would argue that the MD struct should be made thread-safe intrinsically... otherwise how can one confidently write code that either reads or writes from that structure?

**Comment by kokaz** [comment]
@bensigelman The _issue_ is that `MD` is not a struct but a `map` so anyone using `MD` can end up using it non thread-safely and so we can't really make `MD` intrinsically thread safe except for the method it has (i.e. `Copy`, `Join`).

**Comment by bensigelman** [comment]
@kokaz one *could* make `MD` an interface and document that it is concurrency-safe. I recognize that this would be a backwards-incompatible change for some callers, but it's not like the documentation change in #986 is the only (or even the best or certainly the most robust) way to address the problem.
