### ISSUE TITLE
error with vendor/

### ISSUE THREAD

**Issue by hsulei** [grpc/grpc-go#987]
i have  a  problem ,i don't know what  create it 。the error message is 
`cannot use p.Conn (type *"xxx/vendor/google.golang.org/grpc".ClientConn) as type *"google.golang.org/grpc".ClientConn in argument to cabrand.NewCABranderClient`  ,two grpc package has same version `0d9891286aca15aeb2b0a73be9f5946c3cfefa85`。

**Comment by iamqizhao** [comment]
I think it is because of some misuse of vendor tool so that the importing path is not set correctly. You can send the mail to grpc.io email group for help with more detail. Close it here since this is not a grpc issue.

**Comment by hsulei** [comment]
thanks
