### ISSUE TITLE
server side only latencies - baseline idea

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc-go#988]
For an idea of some baseline latency times on the grpc-go server, roughly measured the time taken between reading a new data frame and writing the corresponding one back, on the current master.

The "write time" was recorded right before the flush, just before https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L691, and the "read time" was recorded right after getting the stream ID, just before https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L377.

For the unary ping pong test, with a median latency of 327 us, I found a median latency between these two points to be about 56 us.

For the streaming ping pong test, with a median latency of 327 us, I found a median latency to between these two points to be about 22 us.

**Comment by dfawley** [comment]
@apolcyn, do you remember why you filed this bug?  Is this a request to add a benchmark?  Or metrics gathering? Or something else?  Thanks!

**Comment by apolcyn** [comment]
This was just metrics gathering. I was just trying to get a ballpark idea of where time was getting spent. This is just more data for the record, so closing it.
