### ISSUE TITLE
Stream receiver cancelation

### ISSUE THREAD

**Issue by olix0r** [grpc/grpc-go#990]
As far as I can tell, there is no mechanism for a stream receiver to cancel a stream.  Only the sender may terminate a stream.

Consider a situation when a [web service has a gRPC client that reads a stream](https://github.com/BuoyantIO/linkerd-examples/blob/4256b569648894b3a2b533fe8934610d6c05ed1a/gob/web/main.go#L117).  When a client to the web server disconnects, the application should close the receiving stream without tearing down the entire client connection.  Ideally, I think this would work by sending a `RST_STREAM` frame with the `CANCEL` code.

`stream.CloseSend()` is not sufficient for this, since it attempts to send a `DATA` frame (even when the local http2 stream is half closed).

Am I correct that this functionality is missing? Should there be a `stream.CloseRecv()` method as well?

**Comment by iamqizhao** [comment]
To terminate a stream, you can cancel the context on the client side and return from the service handler on the server side.

To be clear, CloseSend does not terminate a stream -- it just claims it won't send any data to the peer.

**Comment by olix0r** [comment]
Thanks for the prompt response, @iamqizhao. Are there any examples you can point me at?

**Comment by menghanl** [comment]
Create a new context from the old context with `WithCancel`, and then you can call `cancel()` to cancel it.
```go
ctx, cancel := context.WithCancel(ctx)
stream, err := client.StreamingRPC(ctx)
// do something on stream
cancel()
```
