### ISSUE TITLE
Version4 compile-time assertion completely replaced Version3 compile-time assertion

### ISSUE THREAD

**Issue by troylelandshields** [grpc/grpc-go#991]
When generating code from proto files using protoc, the `proto.ProtoPackageIsVersion3` flag was completely replaced with `proto.ProtoPackageIsVersion4` flag. 

This has the effect that you cannot run code that imports a client generated with version 3 and a client generated with version 4.

Is this the desired behavior? The only reason I suspect it might not be is that the flags for version1 and version2 still exist in `lib.go`.

```
// ProtoPackageIsVersion2 is referenced from generated protocol buffer files
// to assert that that code is compatible with this version of the proto package.
const ProtoPackageIsVersion2 = true

// ProtoPackageIsVersion1 is referenced from generated protocol buffer files
// to assert that that code is compatible with this version of the proto package.
const ProtoPackageIsVersion1 = true
```

There was an issue that sort of address this (https://github.com/grpc/grpc-go/issues/969), but it doesn't seem to address the fact that backwards compatibility was maintained for versions 1 and 2, but not for version 3.

**Comment by troylelandshields** [comment]
Sorry, I misread the source. The missing flag is `SupportPackageIsVersion3`, not `ProtoPackageIsVersion3`. So I guess my whole argument is just wrong. My question still stands though, is there a solution for compiling code that imports clients from older versions?

Seems like there isn't and if that's the case feel free to close this. Any insight you can give is appreciated though. Thanks.

**Comment by iamqizhao** [comment]
I would suggest sync-ing up to the latest code in this situation.
