### ISSUE TITLE
Upgraded to latest version and no longer able to make connections

### ISSUE THREAD

**Issue by jdoliner** [grpc/grpc-go#996]
We recently tried upgrading our vendored code to the latest version of grpc-go and have thus far been unable to get it to work for us. The commit we're on is b13ef794997191ec801db90a42c50034df91850a. The first thing we noticed was that several of our connections would error with "the connection is unavailable" I figured out that we could get around that by adding `WithBlock` to the calls to `Dial` in our code so that they wouldn't return until the connection was ready. That worked but now we're having a different problem which is that when we try to use the connection it returns "transport is closing."

Have you guys seen anything like this before and do you have any ideas for things to try to get the latest version working for us?

**Comment by iamqizhao** [comment]
I speculate your previous version was very old (seems it was before the roll-out of fail-fast feature). Can you try to set your rpcs to non-failfast (via grpc.FailFast(false) call option)?

**Comment by jdoliner** [comment]
Hmm, that didn't seem to fix the problem. It just took the requests from failing to blocking indefinitely. Anything else we could try?

**Comment by iamqizhao** [comment]
It is not clear to me how you got the "the connection is unavailable" error. Can you send me some code snippets or tests which can reproduce your observation?

**Comment by hsaliak** [comment]
@jdoliner are you still seeing this issue?

**Comment by jdoliner** [comment]
@hsaliak I'm not, we were using some third party libraries and once we got rid of those things seemed to work. Closing.
